### ISSUE TITLE
table features - potential enhancements

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#1]
Table/list potential features:
CORE 
Prio 1
- [ ] craft a stable API
- [ ] support images in addition to text/links
- [ ] sorting/filtering functionality
- [ ] pagination (expose items per page field)
- [ ] selection modes (no selection, single row selection, multiple rows selection)
- [ ] show/hide columns
- [ ] table toolbar buttons
- [ ] one-click actions (including more menu)
- [ ] load on scroll end
- [ ] responsiveness

Prio 2
- [ ] grouping rows
- [ ] drag and drop
- [ ] adjustable column width
- [ ] infinite scrolling
- [ ] export

Prio 3
- [ ] edit mode
- [ ] fix columns(left/right); fix rows(bottom/top); sticky headers
- [ ] options for resizing table height
- [ ] header columns options (wrapping description)

Platform:
- [ ] personalization
- [ ] meta-data driven columns (CRUD)

**Comment by sbgreene1307** [comment]
It would be nice if the table supported a popover rowData element to be used as a contextual menu. To further that, it'd be nice if we could put in any fundamental-ngx class. i.e. a button. Currently, we have a delete button as one of our rowData elements, so we can't use the fundamental-ngx table implementation. If it were a contextual menu like in the fundamental css [docs](https://sap.github.io/fundamental/components/table.html), then I could probably push that pattern to my superior.

**Comment by droshev** [comment]
https://github.com/SAP/fundamental-ngx/wiki/Platform:-Datatable-Technical-Design

**Comment by mikerodonnell89** [comment]
closing this as table requirements have changed
