### ISSUE TITLE
[Sourcing][Accessibility][High][Jul] On checking table header checkbox table scrolls down

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10009]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On checking header checkbox using enter key , the table scrolls down.
However, table should not scroll until user shifts or traverse through rows

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15
core / platform: 0.42.0-rc.13

#### If this is a bug, please provide steps for reproducing it.
1) move the focus to header checkbox 
2)hit enter or space to check the checkbox
3) notice that the page scrolls along with table rows

#### Is there anything else we should know?
[Task_46797_NGXIssue.mov.zip](https://github.com/SAP/fundamental-ngx/files/11705434/Task_46797_NGXIssue.mov.zip)

**Comment by fkolar** [comment]
@I543348 

I am not able to replicate exactly what you are showing in the video. Let's separate what is the docs issue or feature or table. But I have created this demo, when when Check All is selected using SPACEBAR, it does scroll to some random position within the table. 

So not sure what exactly is your issue?

**Comment by I543348** [comment]
Hi @fkolar , Please check the recording , the checkbox in the header column should stay in the view after checking/unchecking.
This was reported by ATL testing

Expectation: the target checkbox should stay in the view port 

https://github.com/SAP/fundamental-ngx/assets/88182358/d3bfbc72-07e7-49e4-9352-fb9f9e9b66b2
