### ISSUE TITLE
[Sourcing][Accessibility][High][Jul] Single selection row table issue

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10000]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
ATL testing issue on single selection row table

#### If this is a bug, please provide steps for reproducing it.
**Issue 4:** 
On accessing the selected row and non-selected row, both are read in the same manner and the information “Selected” is not read for the selected row and this will create confusion among screen reader users.
**Note**: This issue persists in multiple row selection table also
<img width="452" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/8b5be444-f70d-4b3e-8bf7-c0dec34e5494">
<img width="451" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/30ff999c-629d-4e52-bdfd-36f702cf2629">

#### Please provide relevant source code if applicable.
All these were tested as on 31st May 2023 on https://sap.github.io/fundamental-ngx/#/platform/table/ platform table component samples

**Comment by fkolar** [comment]
@I543348 

It seems to be fine for multi section. I also compared this with https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable
 - N rows selected changes based on the selection

Can you confirm? 

For he single selection it just says what row and column you are on. Not if its selected or now.  - this is valid

**Comment by I543348** [comment]
> @I543348
> 
> It seems to be fine for multi section. I also compared this with https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable
> 
> * N rows selected changes based on the selection
> 
> Can you confirm?
> 
> For he single selection it just says what row and column you are on. Not if its selected or now. - this is valid

Hi @mikerodonnell89 , it will be an issue for disabled users who wont be able to understand whether row is selected or not.
Hence this issue.

**Comment by sagar7259** [comment]
The selected row is being read as "To deselect a rew press spacebar" and this is clear to the users that this is select. Hence this can be closed.

Regards,
Sagar(ATL team)
