### ISSUE TITLE
Will be sap.m.PlanningCalendar migrated to fundamental-ngx?

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#10008]
Hello, fundamental-ngx team,

I have a question, will be [sap.m.PlanningCalendar](https://sapui5.hana.ondemand.com/#/entity/sap.m.PlanningCalendar/sample/sap.m.sample.PlanningCalendar) control implemented in the fundamental-ngx library?

Best Regards

**Comment by droshev** [comment]
@egorwow70 what is your use-case and in which applications do you need that component?

**Comment by egorwow70** [comment]
> @egorwow70 what is your use-case and in which applications do you need that component?

Hello. We are using that in the Flexconnect application to show you when and where your colleagues are working, I hope you can access the link - https://sapit-realestate-prod-gerbil-flex-connect-flexconnect-router.cfapps.eu10-004.hana.ondemand.com/index.html#/office?shortCode=WDF&name=Walldorf

**Comment by egorwow70** [comment]
@droshev 
Hello, do you have news regarding the issue?

**Comment by droshev** [comment]
@egorwow70 can you contact me in teams?

**Comment by egorwow70** [comment]
@droshev 

Hello, sorry for the late response, we had a UI/UX review of the application, that we are developing, and our design team changed the plans and probably won't use the planning calendar in the future,

So, it is up to you whether to close the ticket or keep it if you have any plans on your side to implement that,

And big thanks for the time, that you spent on the ticket.
