### ISSUE TITLE
Changing focus using the TAB key skips through inputs on a <fd-table>

### ISSUE THREAD

**Issue by netux** [SAP/fundamental-ngx#10010]
#### Is this a bug, enhancement, or feature request?

Bug report.

#### Briefly describe your proposal.

Pressing TAB to focus on an input should not skip inputs inside of `<fd-table>`s.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.8
Fundamental NGX (core, platform, cdk, i18n): 0.41.0

#### If this is a bug, please provide steps for reproducing it.

Based on the StackBlitz page below:

**Case of trying to focus from outside the table:**
1. Focus on the input labeled "Focusable input before table"
2. Press the TAB key on your keyboard

Expected: Focus should now go to the input labeled "Row 1; Col 1"
Result: Focus goes to input labeled "Focusable input after table"

**Case of trying to focus to the next input in the table:**
1. Focus on the first input in the table, labeled "Row 1; Col 1"
2. Press the TAB key on your keyboard

Expected: Focus should now go to the input labeled "Row 1; Col 2"
Result: Focus goes to input labeled "Focusable input after table"

#### Please provide relevant source code if applicable.

On StackBlitz:
- [with Fundamental NGX 0.41.0 (broken)](https://stackblitz.com/edit/angular-nb5e4k-2enr1x?file=src%2Fapp%2Ftable-example.component.html)
- [with Fundamental NGX 0.36.4 (working)](https://stackblitz.com/edit/angular-nb5e4k-nubsax?file=src%2Fapp%2Ftable-example.component.html)

#### Is there anything else we should know?

This was working fine as far back as Fundamental NGX v0.36.4. I have not checked with versions in between.

I tried adding the `focusable` directive to the table rows and columns, which seems to add some navigation capabilities. But pressing TAB specifically does not work.
I also tried using <input>s with the `fd-form-control` directive, which didn't work either.

I thought this might be related to #9791, but that ticket talks about navigation between cells, not inputs inside of cells.

**Comment by mikerodonnell89** [comment]
Hi @netux, are you able to update to the current rc version ([0.42.0-rc.22](https://www.npmjs.com/package/@fundamental-ngx/core/v/0.42.0-rc.22))? We have made some improvements and `[focusable]="true"` is working fine there for this issue: https://stackblitz.com/edit/angular-nb5e4k-ocjkxh?file=package.json

**Comment by netux** [comment]
Hello @mikerodonnell89. Thanks for the update.

Would it be possible to support this without the `[focusable]` directive on the cell? My goal was to only select the input within the cell, as it is the only content on the cell. Maybe by adding `[focusable]` to the input somehow?
I would expect to be able to move focus between inputs without having to focus on the containing cell first.

I also noticed for the second case of "focusing on the next input inside the table", once you are focused on the input in cell 1,1, you have to press Escape to bring focus on the cell containing the input, then Right Arrow to focus on the next cell, then Tab again to focus on the input inside the cell. I think this is _fine_ but not the best when you want to quickly fill out the table.

Thanks for the swift action, and looking forward to further improvements.
