### ISSUE TITLE
When will release the new version to support Angular 16.0.5?

### ISSUE THREAD

**Issue by sssunsha** [SAP/fundamental-ngx#10023]
Because of some CSP security issues(Angular uses inline styles to insert the styles associated with a component. This violates the strict styles which doesn't allow inline styles by default. This has been solved in v16 of Angular. https://github.com/angular/angular/pull/49444), my angular project need to be upgrade to V16, however, now for fd-ngx, the latest version is still pointed to V15. I want to know the plan ofthe new version for angular 16. Thanks a lot

**Comment by sssunsha** [comment]
@droshev thanks for your information.

**Comment by droshev** [comment]
It has been done already
