### ISSUE TITLE
Complete rxjs Subject when closing modal

### ISSUE THREAD

**Issue by hisabimbola** [SAP/fundamental-ngx#1002]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
On the modalRef method, there is an observable `afterClosed`. However, when it's converted to a promise, the promise never resolves.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Fundamental NGX: 0.6.0
#### Please provide relevant source code if applicable.
```
    close(result?: any): void {
        this._afterClosed.next(result);
        this._afterClosed.complete();
    }
```
#### Is there anything else we should know?
To fix this we have to call `afterClosed.complete()` so that the observable is completed

**Comment by MattL75** [comment]
Yeah this is a good issue. It works completely fine without a complete if you're using rxjs, but with promises it won't work.

**Comment by mpienkowski** [comment]
@MattL75 It is also a problem when using rxjs, for example with ngrx effects. With current approach you can't use finalize() operator to handle both dismissal and close of a modal. I've prepared a PR that fixes it
