### ISSUE TITLE
The style of Wizard Component is not removed when Wizard Component destroyed

### ISSUE THREAD

**Issue by Sherry-Lee** [SAP/fundamental-ngx#10027]
#### Briefly describe your proposal.
The style of Wizard Component should be erased while Wizard Component destroyed

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15.2.7
Fundamental-ngx/core: 0.40.0

#### If this is a bug, please provide steps for reproducing it.
1.  Search the Wizard component at the https://sap.github.io/fundamental-ngx/#/core/
2. Open any example Wizard that displayed in the right example demo
3. Search the Dialog component at the https://sap.github.io/fundamental-ngx/#/core/
4. Open any Dialog component demo based on the illustrated page.

Then the non-full-screen dialog will be shown full-screen, and the root cause is that the fd-scrollbar rule width: 100% and height: 100% comes from the Wizard component, but when switching the Dialog component, this style should be removed but it’s not.

**Comment by droshev** [comment]
@IB002 Can you check this issues, summarize the findings, and eventually come up with a fix, if it is a bug?

**Comment by droshev** [comment]
@Sherry-Lee Can you check whether the issue is addressed on the latest version if it is not, can you report a new ticket.
