### ISSUE TITLE
Search placeholder and tooltips localization support

### ISSUE THREAD

**Issue by sreekanthkarini** [SAP/fundamental-ngx#10026]
#### Is this a bug, enhancement, or feature request?
Bug.

#### Briefly describe your proposal.
Search placeholder and all the tooltips are not supporting localization

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

#### If this is a bug, please provide steps for reproducing it.
- On accessing search input box search placeholder is not supporting localization for 'fdp-search-field'

![image](https://github.com/SAP/fundamental-ngx/assets/136553940/c18bf499-5f40-4888-850c-5543f9bb262c)

- On accessing tooltips and hover over the icons behind to view the tooltips are not supporting localization for 'fdp-button'

![image](https://github.com/SAP/fundamental-ngx/assets/136553940/55dddcdf-1a88-4807-8e05-7556a28bb7b9)

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/search-field
https://sap.github.io/fundamental-ngx/#/platform/button

**Comment by mikerodonnell89** [comment]
The search button and all buttons on the fdp-search-field component are in fact localized. Some translations may be missing in certain languages

https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/src/lib/search-field/search-field.component.html#L99
