### ISSUE TITLE
[Sourcing][Perf] MultiComboboxComponent hangs the page when has 10K dropdown values.

### ISSUE THREAD

**Issue by vidworks** [SAP/fundamental-ngx#10022]
#### Is this a bug, enhancement, or feature request?
Not sure if bug or enhancement, as the `MultiComboboxComponent` limitations is not defined.

#### Briefly describe your proposal.
The `MultiComboboxComponent` performs poorly when provided with 10K values to it. There are instances when customer has more than 10K dropdown values to be populated to the component and the pages basically hangs for sometime resulting in bad user experience.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`angular` version is `15.2.0`
`"@fundamental-ngx/core": "0.41.1-rc.7"`
`"@fundamental-ngx/platform": "0.41.1-rc.7"`

#### If this is a bug, please provide steps for reproducing it.
Populate `MultiComboboxComponent` with 10K random strings. I used object to store `displayKey` and `secondaryKey`.

#### Is there anything else we should know?
Profiler screenshot
<img width="1171" alt="Screenshot 2023-06-12 at 2 19 34 PM" src="https://github.com/SAP/fundamental-ngx/assets/136386704/ad842281-6a10-4fa1-bbe6-05f2807e4a4f">

**Comment by droshev** [comment]
@vidworks According to the [guidelines](https://experience.sap.com/fiori-design-web/multi-combobox/#use-the-multicombo-box-if) the combobox should be used if you have up to 200 items. In your case the recommendation is to use Value-Help Dialog
