### ISSUE TITLE
[Sourcing] Tree table: Ability to restore to last table state when user navigates back and forth between pages using Angular router

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#10024]
Is this a bug, enhancement, or feature request?
--
Feature request

Briefly describe your proposal.
--
Whenever user performs any type of editing to the row data on a new page (navigated via Angular router), the table view should retain its last viewed page when user navigates back from that editing page view. 

However, as of now, even with the fixes done in #9907, the `<fdp-table>` component instance gets destroyed when we navigated away and then came back. Due to this, we are unable to use those newly added functionalities to restore to previous table state.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
--
Current release.

**Comment by fkolar** [comment]
I think we can't just stat implementing but we need to define what needs to be persistent and how. Currently you can persist:

- sortBy (list of field names and their directions)
- filterBy (list of field names and their directions)
- groupBy  (list of field names and their directions)
- Current Page and its size  (also used for scrolling)
- SearchInput (text and its category)
- Columns and their keys
- FreezeTo Column  / End info information


@yixuan-liu, is there any thing else ? I think these information should be sufficient to restore original state, if the scrolling part. The only thing that Table cannot persist and it should be application responsibility is the Expanded/Collapsed State of the nodes. 

- Application stores TableState (here we use Table Service and its tableState$ if needed)
- Application needs to keep track of what node is expanded and collapsed - here we can use already implemented feature. (App will use TabelRow interface)
