### ISSUE TITLE
[DateTime Picker] Popup width and height calculation goes crazy

### ISSUE THREAD

**Issue by emadaldin-baybars** [SAP/fundamental-ngx#10030]
#### Is this a bug, enhancement, or feature request?
it's a bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`@angular/core: ^15.2.6`,
`@fundamental-ngx/core: ~0.40.0`

#### If this is a bug, please provide steps for reproducing it.
- try to add a fundamental DateTime picker in a page with a lot of content
- click on the DateTime input to open the picker popup
- scroll up or down till the popup got hidden and return back to it 
**Expected** to be correctly resized and scroll bars work 
**Reality** the popup dimensions calculated wrongly and sometime the scroll bars do not work fine

[Untitled_ Jun 14 2023 4_52 PM.webm](https://github.com/SAP/fundamental-ngx/assets/10583606/86f22626-9919-4a9e-b95a-dc287a21e98d)

#### Is there anything else we should know?
No style added from my side at all

**Comment by droshev** [comment]
It is not reproducible in the latest; it is reproducible on 0.40.0. The screen size should be small enough to hide only the footer from the date time picker, but not more than that. Also, the datetime picker should be shown below the field. (The issue: the date time picker is not scrollable at all)

**Comment by droshev** [comment]
a fix was provided with version `0.40.4`
