### ISSUE TITLE
The popup width is not correct by the calculating

### ISSUE THREAD

**Issue by Sherry-Lee** [SAP/fundamental-ngx#10037]
#### Is this a bug, enhancement, or feature request?
it's a bug.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@angular/core: 15.2.7,
@fundamental-ngx/core: 0.42.0-rc.22

#### If this is a bug, please provide steps for reproducing it.
When the more button(...) position is left, once clicking the more button, the popup will be shown but with incorrect width. However, the width of the content is larger than the calculated value. The 0.40.4 version of @fundamental-ngx/core is tried as well refer to the issue https://github.com/SAP/fundamental-ngx/issues/10030, but it is still not working.

#### Please provide relevant source code if applicable.

<img width="1401" alt="Screenshot 2023-06-15 at 14 35 30" src="https://github.com/SAP/fundamental-ngx/assets/24450770/54556263-c5ef-4196-a199-e5034952bf14">

**Comment by N1XUS** [comment]
@Sherry-Lee Could you please create Stackblitz example?
