### ISSUE TITLE
How we know it is up or down when InfiniteScrollDirective emits scroll event?

### ISSUE THREAD

**Issue by MingZhang-PS** [SAP/fundamental-ngx#1003]
From the source code, https://github.com/SAP/fundamental-ngx/blob/4143f4f3bf796a27fa7697488ba08ce335edca6d/library/src/lib/infinite-scroll/infinite-scroll.directive.ts#L32
It seems there is no way to do it. 
So as consumer, how can we know it is up or down?

**Comment by mikerodonnell89** [comment]
What is the use case here?  The directive is intended for lazy loading items in lists, tables etc. as the user scrolls down

**Comment by MingZhang-PS** [comment]
Hi @mikerodonnell89 
I am using the lazy loading functionality, which means once the scroll action emits, I will try to fetch another page of data from server and **append** the response to the buffered data collection.
However, I found when user scroll up, the scroll action is also get emitted, which makes my "fetch" operation be triggered unnecessarily. It is not what I want, since the data has already been cached on client side..

**Comment by MattL75** [comment]
Hi @MingZhang-PS! I am not sure how you implemented it, but if you look at our [example](https://sap.github.io/fundamental-ngx/infiniteScroll) you can see that data is only added when the user scrolls down. 

If you intend to use this as a **virtual scroll** which is when you remove the items from the DOM when they are not visible, I would recommend to instead use the Angular CDK as we do not currently support that.
