### ISSUE TITLE
AOT broken when importing component modules individually

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#1004]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

AOT compilation breaks when importing the components' modules individually.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 8.0.3 (this might be the root cause)
Fundamental-ngx 0.6.0 (also checked with 0.7.0-rc.8)

#### If this is a bug, please provide steps for reproducing it.

```import { NgModule } from '@angular/core';
import { ButtonModule, FileInputModule, InputGroupModule, MenuModule, PopoverModule, ToggleModule } from 'fundamental-ngx';

const modules = [
  ToggleModule,
  ButtonModule,
  FileInputModule,
  InputGroupModule,
  MenuModule,
  PopoverModule
];

@NgModule({
  imports: modules,
  exports: modules
})
export class MyFundamentalModule {
}
```

Compiler output:
```ERROR in : Unexpected value 'ToggleModule in (...)/node_modules/fundamental-ngx/fundamental-ngx.d.ts' imported by the module 'MyFundamentalModule in (...)/src/app/my-fundamental-module.ts'. Please add a @NgModule annotation.```

It works if I don't use AOT or if I import the whole lib like this:
```import { FundamentalNgxModule } from 'fundamental-ngx';```

#### Is there anything else we should know?

I didn't check it with Angular 7 and I've seen that Angular 8 is not officially supported yet.

**Comment by hisabimbola** [comment]
I got this also, thought something was wrong with my app 🤦‍♂ 😄

**Comment by MattL75** [comment]
Seems like this is related to an Angular + ngpackagr bug. Basically barrel-imports don't play well with libraries. I'll put up a PR in a second.
