### ISSUE TITLE
[Sourcing][Responsiveness] Item inside fdp-menu are shown as button in fdp-table's toolbar

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#10057]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.

-- In 200% browser zoom, the action buttons are moved inside the fdp-menu in the fdp-table's toolbar. 
But the items inside the fdp-menu looks like buttons rather than menu-items as shown in the below screenshot.
<img width="554" alt="Screenshot 2023-06-21 at 11 24 44 AM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/10a9a38d-0a30-482f-85e7-14315d795856">

It should be displayed like menu-items inside the fdp-menu similar to the one shown in below screenshot.
<img width="1055" alt="Screenshot 2023-06-21 at 11 57 57 AM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/bc0e4a70-e9e1-4560-a660-cd5fadb9d6bd">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "15.2.0"
"@fundamental-ngx/core": "0.42.0-rc.14",
"@fundamental-ngx/platform": "0.42.0-rc.14",

#### Please provide relevant source code if applicable.
Editor URL - https://stackblitz.com/edit/angular-knha3l?file=src%2Fapp%2Fplatform-table-default-example.component.html

**Comment by droshev** [comment]
works as espected

**Comment by I543348** [comment]
@Sayandeep-123  pls evaluate and confirm
