### ISSUE TITLE
[Sourcing][High][Aug] Slowness  on fd-multi-input modal

### ISSUE THREAD

**Issue by KaptaanBarbosa** [SAP/fundamental-ngx#10052]
#### Is this a bug, enhancement, or feature request?
 BUG
#### Briefly describe your proposal.
After implementing keyword search(Rest api call )  via fd-multi-input (searchTermChange) dropdown list doesnt come up first time until we explicitly go on in put box and write/delete one character

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular15

#### If this is a bug, please provide steps for reproducing it.
After implementing keyword search(Rest api call )  via fd-multi-input (searchTermChange) dropdown list doesnt come up first time until we explicitly go on in put box and write/delete one character

**Comment by fkolar** [comment]
@KaptaanBarbosa , Please provide more information. Reproducible example is needed. It is impossible to help unless we see how you implemented it.

**Comment by KaptaanBarbosa** [comment]
https://stackblitz.com/edit/angular-anqr4o?file=src%2Fapp%2Fmulti-input-example.component.ts,src%2Fapp%2Fmulti-input-example.component.html. adding a reference here

**Comment by fkolar** [comment]
This should not be an issue anymore. as we explain this on the call plus add this example into my repo https://github.com/fkolar/table-destroy
