### ISSUE TITLE
Tabs: fd-tab-nav and fd-tab-list api difference

### ISSUE THREAD

**Issue by lx-kiryldryha** [SAP/fundamental-ngx#10059]
#### Is this a bug, enhancement, or feature request?
Enhancement
 
#### Briefly describe your proposal.
Tabs: https://fundamental-ngx.netlify.app/#/core/tabs.

Official documentation offers to use fd-tab-nav and fd-tab-item directives to implement tabs with router links.
 
**Example from documentation:** https://fundamental-ngx.netlify.app/#/core/tabs#simple
 
 `< nav fd-tab-nav> <div fd-tab-item> <a fd-tab-link [active]="rla1.isActive" [routerLink]="'tab1'" routerLinkActive #rla1="routerLinkActive"> <span fd-tab-tag>Link 1</span> </a> </div> <div fd-tab-item> <a fd-tab-link [active]="rla2.isActive" [routerLink]="'tab2'" routerLinkActive #rla2="routerLinkActive"> <span fd-tab-tag>Link 2</span> </a> </div> <div fd-tab-item> <a fd-tab-link [active]="rla3.isActive" [routerLink]="'tab3'" routerLinkActive #rla3="routerLinkActive"> <span fd-tab-tag>Link 3</span> </a> </div> </ nav>`
 
 **The problem:** I want to use collapseOverflow property (https://fundamental-ngx.netlify.app/#/core/tabs#collapsible) for my tabs that are build on fd-tab-nav and fd-tab-item directives, but this property is available only for tab-list component

 I haven't found workaround or examples how add links to component.
 
 **Proposed solution** API difference should be eliminated
 
 #### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest

**Comment by droshev** [comment]
@lx-kiryldryha the tabs component has been deprecated and the Icon Tab Bar is its successor. Can you use it instead?
