### ISSUE TITLE
Placeholder in a Select component

### ISSUE THREAD

**Issue by DominikaZamojska** [SAP/fundamental-ngx#10088]
#### Is this a bug, enhancement, or feature request?
Bug (usability, not according to Visual Core)

#### Briefly describe your proposal.
The placeholder in a select forms should be italic - the same as we have in other form controls, here the spec from Visual Core:
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915140
Now placeholder - it visually looks like selected item which brings confusion
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### Is there anything else we should know?
![Screenshot 2023-06-26 at 21 45 38](https://github.com/SAP/fundamental-ngx/assets/137824445/a72d918f-dc2e-464c-bd52-5b1d0f7ec7c3)

**Comment by Astrid-k** [comment]
Hi, this is still not correct for the Angular library: https://sap.github.io/fundamental-ngx/#/core/select @InnaAtanasova

**Comment by InnaAtanasova** [comment]
> Hi, this is still not correct for the Angular library: https://sap.github.io/fundamental-ngx/#/core/select @InnaAtanasova

hi @Astrid-k thanks for noticing it. I fixed it again https://github.com/SAP/fundamental-ngx/pull/12358
