### ISSUE TITLE
The fd-icon cannot be displayed

### ISSUE THREAD

**Issue by blueskymyw** [SAP/fundamental-ngx#10083]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The fd-icon cannot be displayed.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 15.2.8
fundamental 0.40.3

#### If this is a bug, please provide steps for reproducing it.
 The web page cannot display the icon.

#### Please provide relevant source code if applicable.
<img width="602" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/117795601/90be69cb-ab27-4dce-a286-436e02fbd456">

**Comment by droshev** [comment]
@blueskymyw can you provide more information?
