### ISSUE TITLE
[Sourcing][Regression] Expand All does not expand all children

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10095]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In platform tree table, when we try to expandAll children, the children are not displayed even though the expand icon shows the row is expanded:

https://github.com/SAP/fundamental-ngx/assets/22842279/4a4c3576-896f-4b68-976e-d1350ff14d61

Noticed that it only shows children which also contains other children rows but for row containing children without other nested children, it will not be displayed

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.42.1-rc.4

#### If this is a bug, please provide steps for reproducing it.

Create a tree platform table with expandAll and collapseAll buttons.

#### Please provide relevant source code if applicable.

fundamental playground in Basic Examples with Tree Table and Expand/Collapse All buttons.

**Comment by fkolar** [comment]
Is this is a regression? When I check the docs example it works fine: https://sap.github.io/fundamental-ngx/#/platform/table/basic#tree

@CSENoni

**Comment by CSENoni** [comment]
> Is this is a regression? When I checked the docs example it works fine: https://sap.github.io/fundamental-ngx/#/platform/table/basic#tree
> 
> @CSENoni

I use this one: https://fundamental-ngx.netlify.app/#/platform/table/basic#tree since it contains the latest release.

**Comment by fkolar** [comment]
> > Is this is a regression? When I checked the docs example it works fine: https://sap.github.io/fundamental-ngx/#/platform/table/basic#tree
> > @CSENoni
> 
> I use this one: https://fundamental-ngx.netlify.app/#/platform/table/basic#tree since it contains the latest release.

Thank you, it is a regression. Try to also include a link when you have it..

**Comment by CSENoni** [comment]
It is working fine now. Thanks!
