### ISSUE TITLE
Value Help Dialog: No Pagination shown

### ISSUE THREAD

**Issue by MaxGillmann** [SAP/fundamental-ngx#10090]
#### Is this a bug, enhancement, or feature request?
Bug because code suggests feature which is not available)

#### Briefly describe your proposal.
I would expect a pagination to show below the table as described in the documentation for the **searchTablePageSize** Parameter. It reads: Items per page for pagination below search table

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
- Implementing the **platform/value-help-dialog** as described in the documentation. 
- Add a data source with 100 Entries. 
- Set searchTablePageSize to 20

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-clxjin-x3cd3d?file=src%2Fapp%2Fplatform-vhd-basic-example.component.html

#### Is there anything else we should know?
As far as I can tell there is simply the pagination component missing in the Table footer: https://github.com/SAP/fundamental-ngx/blob/fa6d6c4aa52566bc41febdf233d515c60576d601/libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html#L136C1-L137C1
Thanks for your help :)

**Comment by droshev** [comment]
@mikerodonnell89 Can you check this one?

**Comment by mikerodonnell89** [comment]
The VHD table uses infinite scrolling, which doesn't show a pagination widget, I think we can close this. @MaxGillmann please open another issue if you need to expand on this
