### ISSUE TITLE
[Sourcing][Low]Hardcoding in Watched projects "1 more"

### ISSUE THREAD

**Issue by I589341** [SAP/fundamental-ngx#10106]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Currently, the "1 more" text is hard coded or from the ngx library and is appearing translated. We should expect to see these strings externalized for translation and not appear in English for other languages.

![image](https://github.com/SAP/fundamental-ngx/assets/138152904/1ec1656e-53ce-4025-bcad-e7afae6e6306)
![image](https://github.com/SAP/fundamental-ngx/assets/138152904/917e1c80-955b-4f26-98a5-917605befaea)
![image](https://github.com/SAP/fundamental-ngx/assets/138152904/9e0751a0-39bd-4797-a971-d250d935505a)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest or previous

#### If this is a bug, please provide steps for reproducing it.
1. Log in & click on "For You" Tab
2. Click "View all" under 'Watched Projects' card.
3. Select & Add one project to the Watched Projects list.
4. Observe issue in the "Languages" input box.

**Comment by N1XUS** [comment]
Hello @I589341. This string supports translation. [Here's more information](https://sap.github.io/fundamental-ngx/#/core/i18n#language-customization) on how to provide own translated strings. The key of this string is `coreTokenizer.moreLabel`
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/618cee5e-312c-41c7-b722-d2bd9352398a)

**Comment by droshev** [comment]
We need to downport this to `ng15`

**Comment by droshev** [comment]
fixed with `0.43.6`
