### ISSUE TITLE
Card size in Resizable card layout

### ISSUE THREAD

**Issue by DominikaZamojska** [SAP/fundamental-ngx#10104]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

https://fundamental-ngx.netlify.app/#/core/resizable-card-layout 
Resizable card layout has got too big cards inside - the visible focus is not fully visible for the user and because of it it is hard to noticed. Accessibility Standard - https://wiki.one.int.sap/wiki/display/Acc/ACC-271+Details  as well as we should cover the
the minimum size of the card here is too big it should be 304 px instead of 319 px to have visible focus and hover state visible.
(320 px is required thanks for this Standard https://wiki.one.int.sap/wiki/display/Acc/ACC-282+Details )

![Screenshot 2023-06-29 at 14 19 15](https://github.com/SAP/fundamental-ngx/assets/137824445/4d2e2fdb-8733-4e92-a5de-7c00bf61214f)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.

 Go to Resizable card layout in Fundamentals library https://fundamental-ngx.netlify.app/#/core/resizable-card-layout , set the viewport to 320 px and try to tab as you reach the card. The Focus is cut from both side.

**Comment by khotcholava** [comment]
Please check the latest version since I cant reproduce it.  @DominikaZamojska 

![Image](https://github.com/user-attachments/assets/91e342f8-5fe2-44d2-b091-baad78790711)
