### ISSUE TITLE
[Sourcing] Emitter for expandAll is not working

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10101]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

The event emitter for both expandAll and collapseAll are introduced in this https://github.com/SAP/fundamental-ngx/pull/10097. However, only emitter for collapseAll is working. 

https://github.com/SAP/fundamental-ngx/assets/22842279/ae61b08f-5228-4f84-af4a-bfce197d1695

I think it is only working if we define childDataSource?

```
    expandAll(): void {
        const expandableRows = this._tableRows.filter((row) => row.type === TableRowType.TREE);
        if (!this._dataSourceDirective.childDataSource) {
            this._markAsExpanded(expandableRows);
            return;
        }

        this._tableRowService.loadChildRows(expandableRows);
        this._markAsExpanded(expandableRows);
        this.allRowsExpanded.emit();
    }
```

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.42.1-rc.6

#### If this is a bug, please provide steps for reproducing it.

- In platform table tree table, enable expand/collpaseAll
- Add allRowsExpanded and use console log to observe the behavior.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-mm8ah9?file=src%2Fapp%2Fplatform-table-tree-example.component.html,src%2Fapp%2Fplatform-table-tree-example.component.ts,package.json

#### Is there anything else we should know?

This is not urgent since we have a workaround for this.

**Comment by fkolar** [comment]
I just noticed this that we have this `childDataSource`, which should not be there. The whole point of having 

_UI Component_ -> **DataSourcing** -> _DataProvider,_ is DataSource is always UIComponent specific and should cover most of the component interactions. **DataSource**, should not be a DataType specific - we should not mix this. 

**DataProvider** is meant to be generic across all the UIComponents, as this is Type specific, it knows e.g.:  how to fetch, save the data.

This was the original idea behind this pattern. When we say DS is UIComponent specific, it should cover all needed interaction. 

So you can have a DS: MyTreeTableBasedDS, that could have a methods that are called when `expandAll()`, `expand()` and it could lazily load data. But we should not introduce additional DataSources just based on data. 

Later on we are going to implement Detail Rows. are we going to have DetailRowDataSource? No, we have TableDS, TreeDS, ComboboxDS, <UIComponent that deals with large DataSet>DS.

**Comment by CSENoni** [comment]
It is working fine now, for both expandAll and collapseAll. Thanks!
