### ISSUE TITLE
Modals confirmed with <ENTER> key

### ISSUE THREAD

**Issue by kwiatekus** [SAP/fundamental-ngx#1012]
#### Is this a bug, enhancement, or feature request?

Feature request.

#### Briefly describe your proposal.

Usually, when a modal is displayed, the user, after reading the content, or filling up the data,  needs to confirm/apply changes by pressing some kind of confirmation button (`OK`, `Apply`, `Save`, `Done`, etc...).

It would be great to have a configuration option for modals that would allow triggering the "confirm" action (button) by pressing <enter> key. 

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

v0.7.0

**Comment by MattL75** [comment]
Most uses of the modal I've seen have a form on the inside which handles the enter key submit functionality. I recommend you go that route as well, unless there's something specific blocking you from doing so.

Including this in the modal would require extra logic which would depend on the content within the modal. I want to avoid this and instead (generally) have the responsibility of the content be on the developer.

**Comment by MattL75** [comment]
Closed for housekeeping. Please re-open the issue if there are further questions.
