### ISSUE TITLE
`fd-popover` will not close the popover body after focusout

### ISSUE THREAD

**Issue by MIAeh** [SAP/fundamental-ngx#10123]
#### Is this a bug, enhancement, or feature request?
- Bug

#### Briefly describe your proposal.
When focusing out from the popover control using keyboard, like `Tab`, it will not automatically close the dropdown popover body.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`0.36.3-rc.4`

#### If this is a bug, please provide steps for reproducing it.
Using 2 popover control in a row and try to use `Tab` key to navigate.

**Comment by droshev** [comment]
@MIAeh the popover is not opinionated generic component and you can achieve whatever you need using the [API](https://fundamental-ngx.netlify.app/#/core/popover/api). Feel free to open an issue if the API is not flexible enough
