### ISSUE TITLE
Accessibility issue for fdp-link

### ISSUE THREAD

**Issue by MIAeh** [SAP/fundamental-ngx#10124]
#### Is this a bug, enhancement, or feature request?
- Bug

#### Briefly describe your proposal.
`fdp-link` render the `link` twice in screen reader.
![Screenshot 2023-07-05 at 11 36 35](https://github.com/SAP/fundamental-ngx/assets/26197222/b15fa02b-f9bf-416d-a197-c083a4053baf)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`0.36.3-rc.4`

**Comment by droshev** [comment]
@MIAeh It seems to be fixed already:
![Screenshot 2024-03-02 at 08 15 37](https://github.com/SAP/fundamental-ngx/assets/4380815/999c545a-00a8-4bbf-b2cb-a17629068fe6)
