### ISSUE TITLE
[Sourcing][Regression] fdp platform table rowNavigate event not working

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#10127]
#### Is this a bug, enhancement, or feature request?
Bug. This was previously working but doesn't work anymore

#### Briefly describe your proposal.
For navigatable or activable rows in fdp platform table, the rowNavigatable or rowActivate event isn't being emitted.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.42.1-rc.7
This used to work in 0.42.0.xx versions

#### If this is a bug, please provide steps for reproducing it.
This is a bug.
For fdp-table with rowNavigatable true, on click of row the rowNavigate event is not being emitted.

#### Please provide relevant source code if applicable.
<img width="437" alt="Screenshot 2023-07-05 at 5 04 39 PM" src="https://github.com/SAP/fundamental-ngx/assets/12679774/cb567109-2845-46fb-b1cf-4515c9c1ee72">

#### Is there anything else we should know?
This is very critical for our release (Public Sector Guided Sourcing) for this SP and existing use cases are impacted because of this. Request you to please look into this issue urgently since this is a regression scenario.

**Comment by N1XUS** [comment]
Hello @snigdhaman. Thank you for your ticket. From what I see, described functionality works as expected: https://stackblitz.com/edit/angular-w9meff?file=src%2Fapp%2Fplatform-table-default-example.component.html,src%2Fapp%2Fplatform-table-default-example.component.ts,src%2Fapp%2Fapp.module.ts

If you still have issues with this functionality, could you please provide a stackblitz example where it doesn't work?

**Comment by CSENoni** [comment]
Hi @N1XUS, it can be replicable with `0.43.0` if NGX package is imported in child module. We just found out that it causes regression to our [Sourcing] application:

https://stackblitz.com/edit/angular-sufq3o-2ux57a?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fchild.module.ts,src%2Fapp%2Fapp.component.ts,src%2Findex.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,package.json

**Comment by snigdhaman** [comment]
Added regression tag as per above comment.

**Comment by I543348** [comment]
This is also reported as Guided sourcing application regression, Team - please help and check.
Thanks.

**Comment by N1XUS** [comment]
Hello @CSENoni. Sorry for a delayed answer. I've found the issue. It appears that your application's root module should import `ClickedBehaviorModule.forRoot()` in order for table row navigation to work. Here's an updates Stackblitz example: https://stackblitz.com/edit/angular-sufq3o-9njz7n?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fchild.module.ts,src%2Fapp%2Fapp.component.ts,src%2Findex.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fapp.component.html

**Comment by i563785** [comment]
Hi @N1XUS, ClickedBehaviorModule.forRoot() fix worked for us. Thanks a lot.
