### ISSUE TITLE
[P1][Sourcing][translation] `f-ngx/i18n` missing some lang locales

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#10137]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
`F-NGX/i18n` is missing some locales that Guided Sourcing currently supports. We will need complete i18n locale support from `F-NGX/i18n` to cover all of our supported languages/locales. 

Our complete locale list:
Languages supported by Guided Sourcing

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/I036737/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/I036737/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Lang   (SS) | Lang   (SS) | Lang   Description(SS) | F-NGx   supported
-- | -- | -- | --
bg | bg_BG | Bulgarian |  v1 |
cs | cs_CZ | Czech |  v1 |
da | da_DK | Danish |  |
de | de_DE | German | ✅ | 
el | el_GR | Greek |  |
en | en_US | English | ✅ |  
es | es_ES | Spanish |  |
fi | fi_FI | Finnish |  |
fr | fr_FR | French |  v1 |
hu | hu_HU | Hungarian |  |
hr | hr_HR | Croatian |  |
it | it_IT | Italian |  v1 |
ja | ja_JP | Japanese | |  
ko | ko_KR | Korean |  |
nl | nl_NL | Dutch |  |
no | no_NO | Norwegian | | 
pl | pl_PL | Polish |  v1 |
pt | pt_BR | Brazilian Portuguese | ✅ |
ro | ro_RO | Romanian |  |
ru | ru_RU | Russian |  v1 |
sv | sv_SE | Swedish |  |
tr | tr_TR | Turkish |  v1 |
zh_CN | zh_CN | Simplified Chinese |  tbd |
zh_TW | zh_TW | Traditional Chinese |  tbd |
th | th_TH | Thai |  |

</body>

</html>

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest version with Angular 15.

#### Is there anything else we should know?

Note that the `eu` code in our locale list stands for pseudo locale only.

**Comment by fkolar** [comment]
This is to discuss wtih F-NGX about the process. Currently it is based on contribution mode, whoever wants to translate they can:
 - In such case we use google translate 
 - hard to validate if its correct translation
 - How we can plug them into existing SAP Localisation team process ?

**Comment by yixuan-liu** [comment]
> This is to discuss wtih F-NGX about the process. Currently it is based on contribution mode, whoever wants to translate they can:
> 
> * In such case we use google translate
> * hard to validate if its correct translation
> * How we can plug them into existing SAP Localisation team process ?

Thanks Frank! I remember F-NGX used to output all i18n strings using `@angular/localize`, and our translation team was able to pick those up in their pipeline. Any reason why they moved away from that approach?

**Comment by yixuan-liu** [comment]
Hi Frank, just wanted to check in and see if we have any updates on this issue? Thanks!

**Comment by I543348** [comment]
adding @fkolar  for further clarification
cc: @yixuan-liu

**Comment by droshev** [comment]
there is an investigation needed how to proceed; see the translation format files and how convert that.
setup the repo for the translation system

**Comment by droshev** [comment]
We discussed the issues where the translation of diff. languages would require multiple translations. As the translation team doesn't support that Sourcing team agrees to move with 1:1 translation, which could lead to not correct translations for all strings.

**Comment by rvamudha** [comment]
Languages supported by Guided Sourcing

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/I036737/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/I036737/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Lang   (SS) | Lang   (SS) | Lang   Description(SS) | F-NGx   supported
-- | -- | -- | --
bg | bg_BG | Bulgarian |  
cs | cs_CZ | Czech |  
da | da_DK | Danish |  
de | de_DE | German |  
el | el_GR | Greek |  
en | en_US | English |  
es | es_ES | Spanish |  
fi | fi_FI | Finnish |  
fr | fr_FR | French |  
hu | hu_HU | Hungarian |  
hr | hr_HR | Croatian |  
it | it_IT | Italian |  
ja | ja_JP | Japanese |  
ko | ko_KR | Korean |  
nl | nl_NL | Dutch |  
no | no_NO | Norwegian |  
pl | pl_PL | Polish |  
pt | pt_BR | Brazilian Portuguese |  
ro | ro_RO | Romanian |  
ru | ru_RU | Russian |  
sv | sv_SE | Swedish |  
tr | tr_TR | Turkish |  
zh_CN | zh_CN | Simplified Chinese |  
zh_TW | zh_TW | Traditional Chinese |  
th | th_TH | Thai |  



</body>

</html>

**Comment by rvamudha** [comment]
Sourcing side JIRA tracking - https://product-jira.ariba.com/browse/SS-49291

**Comment by droshev** [comment]
German and Brazilian Portuguese are already included

**Comment by droshev** [comment]
The translation team requested all text items to have comments and prefixes:
the prefix guidelines are https://help.sap.com/saphelp_ewm92/helpdata/en/83/1039835e7c4da3a8a0b49567573afe/frameset.htm

**Comment by g-cheishvili** [comment]
This is already in the ngx both main and ng15
