### ISSUE TITLE
[P2][Sourcing][Responsiveness][Sep18] breadcrumb : caret and 3 dots are overlapped in 200% responsiveness

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10135]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
the caret and 3 dots should not overlap with each other in 200% responsiveness resulting in 1280 x 1024 pixels
This is reported by ATL testing 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core / platform: 0.42.1-rc.9

#### If this is a bug, please provide steps for reproducing it.
<img width="452" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/b4c0ead2-8082-4716-8e18-e28ccc30d507">

**Comment by mikerodonnell89** [comment]
Happening only with the Quartz themes, @droshev what's the plan here?

**Comment by droshev** [comment]
the issue has been fixed with the latest design. as far as I understood from Mike that it is only reproducible only in Quartz. So it should not be a blocker

**Comment by g-cheishvili** [comment]
This issue is not reproducible on v0.43.7 but it is on main. This is a styles issue which will be fixed by the https://github.com/SAP/fundamental-styles/pull/4800

**Comment by droshev** [comment]
fixed with `0.43.9`

**Comment by sagar7259** [comment]
Hello,

As the ATL validation in NGX breadcrumb component the '...' link is now adapting correctly to the 200% resize without any overlapping. Hence closing this ticket can be closed as its fixed.

Regards,
Sagar
