### ISSUE TITLE
[Sourcing][Regression] Platform Table Search display wrong content

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10149]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

This issue happens when we use `expandedStateKey` when some or more rows are expanded and  we have customized component(s) in table cell. 

https://github.com/SAP/fundamental-ngx/assets/22842279/b9b2e7f4-eda1-4d68-824f-49d74ade3d3a

In the example, we have customized component to simply display description. Notice the children of laptops 3 have different description before and after search. When we collapse laptops 3, the description is changed but still not correct. We could recover it when we try collapseAll and then expandAll.

Just double check with 0.42.0-rc.14 version. It is working in this version with `expandedStateKey`, so I will mark it as Regression.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest or since after 0.42.0-rc.14.

#### If this is a bug, please provide steps for reproducing it.

Create a customized component (any) to display value.
Use that component in any column of platform table.
Use expandedStateKey and set all rows are expanded.
Search value having one or more children (make sure rows are kept expanded after search)

#### Please provide relevant source code if applicable.

Current version (not working):
https://stackblitz.com/edit/angular-uqspms-tm7kav?file=package.json,src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html,src%2Fapp%2Fplatform-table-virtual-scroll-example.component.ts

0.42.0-rc.14:
https://stackblitz.com/edit/angular-uqspms-odvj45?file=package.json,src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html,src%2Fapp%2Fplatform-table-virtual-scroll-example.component.ts,src%2Fapp%2Fdisplay-text.component.ts

#### Is there anything else we should know?

I think it may not work with row having no children if it also use customized component. Please also invest this case and also make sure deep level of nested children also working.

**Comment by CSENoni** [comment]
I think this issue can be reproduced without `expandedStateKey` as long as it has customized components. We can reproduce it in our application without using that property.

**Comment by CSENoni** [comment]
https://github.com/SAP/fundamental-ngx/assets/22842279/7f7b89b5-c11a-4b37-a9da-aa635ea754be

https://stackblitz.com/edit/angular-ttxut2?file=src%2Fapp%2Fdisplay-text.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fdisplay-text-label.component.html

**Comment by fkolar** [comment]
@CSENoni , I think this is similar to #10152, I would not use this `**Key` to control the state.

**Comment by CSENoni** [comment]
@fkolar for this issue, please ignore `expandedStateKey` here because this can be reproduced without it. 

> Here is a simple flat table:
> 
>  Screen.Recording.2023-07-11.at.8.51.38.PM.mov 
> https://stackblitz.com/edit/angular-ttxut2?file=src%2Fapp%2Fdisplay-text.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fdisplay-text-label.component.html

**Comment by fkolar** [comment]
Checking ..

**Comment by fkolar** [comment]
Not a error: 

**What is happening is:**
- You start to type **name 3** and it correctly retrieve all rows that has **name 3** 
- Since Table tries to reuse existing rows and it uses row with current index 0 `(Product name 0)`, the rows with Product Name 3 is destroyed.
   - The reason is, the default **trackBy** function table uses internally is based on the index



**Solution** :
1. Implement `ngOnChanges(changes: SimpleChanges): void` to set correct label  - yes it is called correctly 
2. Implement custom truckBy if you want to reuse rows based on the content and not based on the index
`   customTruckBy: TrackByFunction<ExampleItem> = (index: number, item: ExampleItem ) => item.name;`

**Comment by CSENoni** [comment]
@fkolar The `customTrackBy` solves the issue. Thanks! But has been any change that cause this issue in current version? Because if I downgrade the package to `0.42.0-rc.14`, it is working without the need to add that `customTrackBy`. A few of our tables have been affected this.

**Comment by fkolar** [comment]
> @fkolar The `customTrackBy` solves the issue. Thanks! But has been any change that cause this issue in current version? Because if I downgrade the package to `0.42.0-rc.14`, it is working without the need to add that `customTrackBy`. A few of our tables have been affected this.

I need to check...
