### ISSUE TITLE
WIP: [Sourcing] `<fdp-table>` supports sort/filter by row selection state

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#10148]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
Could `<fdp-table>` supports sort/filter by row selection state?

Current, event with `<fdp-table-view-settings-filter>` we still couldn't sort/filter by the selection state of the row

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
    "@fundamental-ngx/core": "0.42.1-rc.9",
    "@fundamental-ngx/platform": "0.42.1-rc.9",
```

#### If this is a bug, please provide steps for reproducing it.
this a feature request

#### Please provide relevant source code if applicable.
N/A

#### Is there anything else we should know?
N/A

**Comment by fkolar** [comment]
@oscargong , Do you think you can provide more details ? How do you think it should work?

**Comment by mikerodonnell89** [comment]
@fkolar makes sense to me, pretty sure @oscargong means adding a boolean filter option to this dialog 
<img width="644" alt="Screenshot 2023-07-14 at 9 10 59 AM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/edf12355-a32b-4920-b8e0-8eae19cc23e0">

**Comment by I543348** [comment]
@oscargong  to validate and clarify further.

**Comment by oscargong** [comment]
Hi Frank,

Currently, the titlebar check box is assigned for select al l/ de-select all action. 

Perhaps we could add selection state as additional sorting/filtering criteria  if `fdp-table-p13-dialog` is attached.

**Comment by fkolar** [comment]
> 
> Hi Frank,
> 
> Currently, the titlebar check box is assigned for select al l/ de-select all action.
> 
> Perhaps we could add selection state as additional sorting/filtering criteria if `fdp-table-p13-dialog` is attached.

Since we want to keep things consistent, I would not go ahead on this at least with some minimal visual/specs. Still I can explain this requirements by many different ways. 

What is in this context row state? Expanded/Collapsed, Selected/notSelected and instead of sorting by value you want to sort it by all that are collapsed or selected? If yes, how this would work with the tree?

**Comment by oscargong** [comment]
I agree with Frank's input. We could close this issue for now.
