### ISSUE TITLE
fdp-action-bar with h2 title violate the assessibility check. 

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#10156]
#### Is this a bug, enhancement, or feature request?
Accessibility 
#### Briefly describe your proposal.
```html
<div title="Product Details" class="fd-action-bar__title" data-tag="actionbar__title" aria-level="2" fd-action-bar-title=""><h2 class="fd-title fd-title--h3">Product Details</h2></div>
```
![image](https://github.com/SAP/fundamental-ngx/assets/10548281/4420b99a-6b42-4544-bdf9-2612124a5988)

The h2 element should always to under the h1 element.  h1 element under document, which could make clear structure level. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 14.2.5
fundamental: 0.36.3-rc.4

Please help check.

**Comment by droshev** [comment]
What exactly is the issue? You need to have somewhere `H1` once for the page.

**Comment by droshev** [comment]
@truezn The platform action bar has been deprecated and its successor is https://fundamental-ngx.netlify.app/#/core/action-bar where the developer has the freedom to set any `H` element.
