### ISSUE TITLE
[Sourcing][Regression] Row is collapsed but children is still displayed

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10152]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In tree platform table with row having children with deeper nested children and all are expanded initially and using `isExpandedStateKey`, and we try to collapse top most row and search. Notice that even we set it collapsed initially, some children is still displayed after search.

https://github.com/SAP/fundamental-ngx/assets/22842279/283472bf-e4e7-43ce-bc5d-c6aa2cb87eec

Even some children are still displayed, it does not display correctly.

Another scenario which I think having the same root cause is in preserved table, when we try recover the state after it disappear:

https://github.com/SAP/fundamental-ngx/assets/22842279/03126fb5-3ab2-4bfa-b64d-cf4e3183a488

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest or previous (maybe a regression since platform table optimization release)

#### If this is a bug, please provide steps for reproducing it.

Please refer link below. Try to have all children expanded initially, collapse a row with many layers of children -> search

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-t6pj6l?file=src%2Fapp%2Fplatform-table-tree-example.component.ts,src%2Fapp%2Fplatform-table-tree-example.component.html,node_modules%2F%40fundamental-ngx%2Fplatform%2Ftable-helpers%2Fmodels%2Ftable-row-toggle-open-state-event.model.d.ts

https://fundamental-ngx.netlify.app/#/platform/table/preserved-state

**Comment by mikerodonnell89** [comment]
With the state preservation updates, you need to maintain the expanded state for the children on the application side, something like this:

```
    checkChildren(arr: any[], expanded: boolean) {
        arr.forEach(child => {
            child.isExpanded = expanded;
            if (child.children) {
                this.checkChildren(child.children, expanded);
            }
        });
    }

    onRowToggleOpenState(event: TableRowToggleOpenStateEvent<ExampleItem>): void {
        event.row.isExpanded = event.expanded;
        if (event.row.children) {
            this.checkChildren(event.row.children, event.expanded);
        }
    }
```

**Comment by CSENoni** [comment]
It looks like that if we collapse the parent, all the rows in parent should be collapsed also? would prefer to have some rows kept expanded even when we collapse the parent. And after we expand parent again, we still see these rows are expanded. But UI5 also behave like that so it should be ok. Thanks!

**Comment by CSENoni** [comment]
```
checkChildren(arr: any[], expanded: boolean) {
    arr.forEach(child => {
        child.isExpanded = expanded;
        if (child.children) {
            this.checkChildren(child.children, expanded);
        }
    });
  }

onRowToggleOpenState(event: TableRowToggleOpenStateEvent<ExampleItem>): void {
    event.row.isExpanded = event.expanded;
    if (event.row.children && !event.expanded) {
        console.log('expand all children inside');
        this.checkChildren(event.row.children, true);
    }
}
```

For example, in this case, I set the parent row is collapsed but all children are still expanded instead. When I hit search, it still behave incorrectly:


https://github.com/SAP/fundamental-ngx/assets/22842279/02935013-0c67-4fa6-990f-c86c416a1b6a

**Comment by fkolar** [comment]
@CSENoni , to preserve all this correctly can you use `TableRow` as your main dataSource type, where you should be able to set this state?  such as https://github.com/fkolar/table-destroy/blob/main/src/app/items-page/items-page.component.ts


**Setting it like this I am not sure what happens with table updates:**
 - We emit an event `onRowToggleOpenState`, we change the internal state of the the row instance and but we dont tell table to refresh (update viewpoint and recalc virtual rows)
 - Another problem I see, when you set this new state on the row and in meanwhile new fetch is called, it will create new instances and all this is lost

This is why we should use `TableRow` for these use-cases, where you can control all those on the application level.

**Comment by fkolar** [comment]
@CSENoni , I can confirm that on collapse; it always marks all the children as collapsed too. I could not find any difference what was before and after. But if you have a link where it worked I can look at this. 

<img width="1577" alt="Screenshot 2023-07-14 at 13 39 27" src="https://github.com/SAP/fundamental-ngx/assets/17149942/0779eecc-1515-4656-8b18-0369282f0b75">


Even this is by design this is not correct. Who decides when I close root node that all the children are collapsed as well?  This would be more like a enhancement and plus send one request to UX to evaluate this what is right.

**Comment by CSENoni** [comment]
@fkolar We can close. Thanks for the code source. We could chat offline regarding to this one if needed since it is not urgent now.
