### ISSUE TITLE
[Sourcing] Filter/Sort indicator disappeared from table header

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#10154]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Not sure if they was removed intentionally. Before there was an indicator on the column header if any sorting/filtering applied to that column. Now, indicator disappeared.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
    "@fundamental-ngx/core": "0.42.1-rc.9",
    "@fundamental-ngx/platform": "0.42.1-rc.9",
```

#### If this is a bug, please provide steps for reproducing it.

https://github.com/SAP/fundamental-ngx/assets/7035787/5e9da4d8-bc44-4771-8865-1e43f8e68a7d

https://sap.github.io/fundamental-ngx/#/platform/table/basic#custom-columns

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table/basic#custom-columns

**Comment by I543348** [comment]
This is a regression

**Comment by fkolar** [comment]
Yes, The code is to show fd-icon with, but:
 - its **ngIf**ed hidden 
 - Also when initially shown it does not update based on the ASC/Desc

**Comment by droshev** [comment]
@I543348 the links that @oscargong quoted are not from `0.42.1-rc.X`, they are from `0.42.0`. Can you test with the lates rc?

**Comment by oscargong** [comment]
> @I543348 the links that @oscargong quoted are not from `0.42.1-rc.X`, they are from `0.42.0`. Can you test with the lates rc?

Hi Deno, this is still reproducible on 0.43.0-rc4:
https://deploy-preview-10162--fundamental-ngx.netlify.app/#/platform/table/basic#basic-add-rows


https://github.com/SAP/fundamental-ngx/assets/7035787/502f4190-77a2-4991-a7b4-ce7f6c16696e

**Comment by fkolar** [comment]
@droshev, I can confirm even on the latest 0.43*. 

The` table-header-cell-content.component.html` does not have the hasSorting set, this is why you dont see icon not even the `fd-table__inner` class on the main div. 


```
<div class="fd-table__text--no-wrap" [class.fd-table__inner]="hasSorting || hasFilter">
    <ng-container *ngTemplateOutlet="tableHeaderCellContentTemplate; context: { column: column }"></ng-container>

    <div class="fd-table__column-header-icons" *ngIf="hasSorting || hasFilter">
        <fd-icon *ngIf="hasFilter" fd-table-icon glyph="filter"></fd-icon>

        <fd-icon
            *ngIf="hasSorting"
            fd-table-icon
            [glyph]="sorting?.direction === SORT_DIRECTION.ASC ? 'sort-ascending' : 'sort-descending'"
        ></fd-icon>
    </div>
</div>
```

I think there is something with updating sortingRules when you click sort popover

```
 <fdp-table-header-cell-content
            [id]="rowId"
            [column]="column"
            [hasFilter]="(_fdpTableService.filterRules$ | async)?.has(column.key) === true"
            [hasSorting]="(_fdpTableService.sortRules$ | async)?.has(column.key) === true"
            [sorting]="(_fdpTableService.sortRules$ | async)?.get(column.key)"
            [attr.title]="column?.headerOverflows ? column.label : null"
```

**Comment by g-cheishvili** [comment]
I investigated the issue too, looks like `sortRules$` is not being updated when needed. In general, I do not see value in manual update of the sortRules, I think those should be calculated automatically from the state always
