### ISSUE TITLE
platform table column header filter popover issue

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#10165]
If you open the popover from the column header, you can then focus the filter input and type in it with no issues. However if you select the sort descending option first, when you then attempt to focus the filter input and type something, focus moves back to the sort option in the popover and you're unable to type in the filter input.

Found in 0.43.0-rc.4 but appears to have been around before

https://github.com/SAP/fundamental-ngx/assets/2471874/b8078c3f-b2b7-4ac8-8298-71bd492c01d3

**Comment by khotcholava** [comment]
Not reproducible in the latest version.

https://github.com/user-attachments/assets/a941befa-b49f-412d-adfe-e6a6905879b5
