### ISSUE TITLE
Platform Combobox - MatchingStrategy.STARTS_WITH_PER_TERM 

### ISSUE THREAD

**Issue by aaasarthak** [SAP/fundamental-ngx#10166]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
With Platform combobox's `MatchingStrategy.STARTS_WITH_PER_TERM`, it should first filter the 'starts_with' and then the 'starts with per term'

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version - 15.2.2
fundamental version - 0.42.0

#### If this is a bug, please provide steps for reproducing it.
- Use the platform's combobox with any type of data source.
- Make sure the data source has more than 20-30 values for a search string with different combinations(some values start with that search string, and some values have the search string in the middle), etc. And also keep the values that start with the search string at the bottom of the data source list.
- As the popover shows max 12 values at a time, type the search string, and observe that the values which start with the search parameter don't show up in the popover list whereas the values which have the search string somewhere in the middle show up.
- Ideally the search criteria for `MatchingStrategy.STARTS_WITH_PER_TERM` that first it should show the values starting with the search parameter and then it should show the values containing the search parameter somewhere else.

#### Is there anything else we should know?
For now, I had to change the MatchingStrategy to STARTS_WITH so that it fixes this issue.

**Comment by N1XUS** [comment]
Hello @aaasarthak. Thank you for your ticket.
Unfortunately, multi-combobox component does not support sorting out-of-the box. On the other hand, this component supports passing custom dataSource class which can implement sorting based on your needs. Here's a simple stackblitz example with kinda similar functionality you looking for: https://stackblitz.com/edit/angular-f75iui?file=src%2Fapp%2Fdata-source.ts,src%2Fapp%2Fdata-provider.ts,src%2Fapp%2Fmulti-combobox-forms-example.component.ts,src%2Fapp%2Fmulti-combobox-forms-example.component.html

If this suffice, I'll close the ticket. Thanks
