### ISSUE TITLE
Unexpected value 'undefined' exported by the module 'FundamentalNgxModule 

### ISSUE THREAD

**Issue by hamiarcher** [SAP/fundamental-ngx#1016]
#### Briefly describe your proposal.
Including latest build **0.8.0-rc.3** in project and doing "ng build --prod" producing following issue. if revert back to **"0.7.0"** build thing work fine.
**_ERROR in : Unexpected value 'undefined' exported by the module 'FundamentalNgxModule in /workspace/sap/git/config-mgr/icm/icm-ui/node_modules/fundamental-ngx/fundamental-ngx.d.ts'_**

#### If this is a bug, please provide steps for reproducing it.
_1. Create new project
2. include Fundamental NGX 
3. Do npm install
4. do ng build --prod_

**Comment by MattL75** [comment]
Looks like the break happened with 0.8.0-rc.1 which is the addition of the split button. Thanks for the report @hamiarcher not sure how this wasn't picked up by the CI as it does build our library fully.

**Comment by MattL75** [comment]
Found the problem. Split-button was merged without adhering to the new public_api methodology that had been added a couple hours prior to the merge. For some reason Travis didn't pick up on the error though so we'll need to follow up on that.
