### ISSUE TITLE
[Sourcing] `fd-switch` keeps toggling every scroll in `virtualScroll`

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10171]
#### Is this a bug, enhancement, or feature request?

bug (and questions)

#### Briefly describe your proposal.

Please help us with this issue when `fd-switch` is jumping every scroll. For this case, it should be replicable at the page after `renderAhead` (100 in my link) and `[(checked)]` is set. When only on-way binding `[checked]` is set, the toggle is not updated when we scroll down or up. This can be replicable with `virtualScroll`.

https://github.com/SAP/fundamental-ngx/assets/22842279/7f2e2206-7af0-4ef9-8737-8ebed1160108

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

current or version after `0.42.0-rc.14`

#### If this is a bug, please provide steps for reproducing it.

Please refer to link:

#### Please provide relevant source code if applicable.

`fd-switch` (case 2)
https://stackblitz.com/edit/angular-ttxut2-cklqbt?file=src%2Fapp%2Fdisplay-text.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

#### Is there anything else we should know?
`fdp-switch` may also be affected so please take a look at it also.

**Comment by CSENoni** [comment]
This issue has been modified to focus on one issue. Please refer to https://github.com/SAP/fundamental-ngx/issues/10183 for _case 3_.

**Comment by fkolar** [comment]
I can confirm if you (on provided stackblitz example) e.g. on the row 43 switch those toggles ON, and you start scrolling up and down, you can see the flickering and those switches refreshes. 
On does not happen with line 30 for example

**Comment by fkolar** [comment]
@CSENoni , Do you think  you can quickly check this agian. Today I was not able to reproduce it.

**Comment by CSENoni** [comment]
> @CSENoni , Do you think you can quickly check this agian. Today I was not able to reproduce it.

Hi Fran, you can use this link as baseline: https://stackblitz.com/edit/angular-ttxut2-ujafdu?file=src%2Fapp%2Fdisplay-text.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,package.json 

You can see the issue starting from 'Product name 45' or row 45. I think the link I had in description having `renderAhead` set to be 100 so that can be only reproducible start somewhere from row > 100.

**Comment by fkolar** [comment]
**Update**:

- Issue is related only to Virtual Scroll

**Comment by mikerodonnell89** [comment]
@fkolar because fd-switch is not a native html element, it does not have a `[value]` property, so, because it's implementing ControlValueAccessor, we should use ngModel. You'll find if you use `[arbitraryProperty]="node.verified"` you will see the same results as using `[value]`

I believe the flicker effect is being caused by the row being redrawn and the css animation of the switch turning active

**Comment by CSENoni** [comment]
It works but I hope this is served as a temp fix only since this may also apply on other components that we haven't found out yet. Also during the test, I found another issue that `fd-switch` label, when using `virtualScroll`, does not update until we scroll ([LINK](https://stackblitz.com/edit/angular-ttxut2-iyymbf?file=src%2Fapp%2Fdisplay-text.component.ts,package.json,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,src%2Fapp%2Fdisplay-text-label.component.html)): 

https://github.com/SAP/fundamental-ngx/assets/22842279/4416323d-a67a-4a1c-b859-2f773796f468

Unless I do something wrong, I will file another separate issue later. Thanks for the fix though.
