### ISSUE TITLE
<fdp-value-help-dialog> Localization issues

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#10184]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.

Tooltip text: **search, synchronise, clear selected items**, for (icon of the button on the right of the input field) is not localized

Place holder: **GO** not localized.
Button : **Ok Cancel** not localized.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0
If this is a bug, please provide steps for reproducing it.

<img width="1321" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/fbd21a8d-124d-4f05-bf9d-5cb1fd27bf12">

<img width="1314" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/c1cb7a4c-da28-43a4-b236-d86f43aed6cf">

<img width="1321" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/fc73dc5d-cbdd-4e44-b579-bac12174eccb">

<img width="1719" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/58f3f2f6-d779-4f91-a74a-b72367095b71">

**Comment by fkolar** [comment]
Closing as there is already  #10137 generic topic
