### ISSUE TITLE
<fd button> : Localization issues

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#10187]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.

Tooltip text: Move to Bottom,Add filter,Remove,colum,filter,sort for (icon of the button on the right of the input field) is not localized

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0
If this is a bug, please provide steps for reproducing it.

<img width="1317" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/e950d5cf-a733-45ee-ada8-5ac8d481cae6">

<img width="1300" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/8e9df3de-d636-461c-9309-ffcb9412e75c">

<img width="1319" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/50658661-a6df-49c8-98f4-bf80108d70a5">

**Comment by fkolar** [comment]
Closing and linking to #10137
