### ISSUE TITLE
<fd-select> : Localization issues

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#10189]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.

drop dow: **ascending ,descending, equal to  etc** is not localized

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0
If this is a bug, please provide steps for reproducing it.

<img width="1304" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/860fd73c-a7bc-4c62-a215-6653230f4834">

<img width="1309" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/28dc473d-ffbc-4fac-83ce-0e32d50778b1">

**Comment by fkolar** [comment]
Closing and linking to main one: #10137
