### ISSUE TITLE
Keyboard support needed in table headers in case of sorting

### ISSUE THREAD

**Issue by DominikaZamojska** [SAP/fundamental-ngx#10194]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Keyboard support needed in case of Sorting column in the table headers
Here: https://fundamental-ngx.netlify.app/#/core/table in a sorting table there is no keyboard support in case you open the popover…the focus not moved in to the popover and this is not usable from keyboard users. I tested it with Voice Over as well
![Screenshot 2023-07-19 at 11 11 22](https://github.com/SAP/fundamental-ngx/assets/137824445/49feebe0-46f3-47ff-871c-116fc9ab4433)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Lates

#### If this is a bug, please provide steps for reproducing it.
Go to the sorting table focus on the header element and click enter/space on keyboard to open the popover - there is no possibility to move with a keyboard into the popover to choose an option

**Comment by mikerodonnell89** [comment]
Any time you need to allow the contents of a popover to be focused, you'll need to use the `[focusAutoCapture]` input, seen here: https://fundamental-ngx.netlify.app/#/core/popover#simple

You will likely also want to use `[focusTrapped]` but not necessarily always. We should have had this in the table docs, I'll open a PR updating them now
