### ISSUE TITLE
overflowing text in fd-card

### ISSUE THREAD

**Issue by I539321** [SAP/fundamental-ngx#10190]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

The text overflows outside of the container.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
I guess it happens on version 0.42.0 of the Fundamental library, and Angular 15.

#### If this is a bug, please provide steps for reproducing it.

Write very long text in it.

#### Is there anything else we should know?

I'm attaching a screenshot of this.
<img width="448" alt="Screenshot 2023-07-18 at 14 48 10" src="https://github.com/SAP/fundamental-ngx/assets/101869667/80a73571-60b4-4afd-b807-7e5e1bc1fd5d">

**Comment by droshev** [comment]
it looks like not reproducible with the latest https://fundamental-ngx.netlify.app/#/core/card
