### ISSUE TITLE
[Sourcing][Accessibility]Platform table row number not read for few cases

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10196]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
For multi select table : The row number is read by the screenreader only when focus is on the "checkbox - first column" always.
However , the column number is read when user changes the column focus - which is good and expected.
Expectation: row number should be announced whenever user moves between the rows using keyboard. too just like column.

For no selection tables / basic table : No row number is read by screenreader on changing row focus

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
replicable on https://sap.github.io/fundamental-ngx/#/platform/table/basic and https://sap.github.io/fundamental-ngx/#/platform/table/row-selection

#### If this is a bug, please provide steps for reproducing it.

[Recordings.zip](https://github.com/SAP/fundamental-ngx/files/12103349/Recordings.zip)

#### Please provide relevant source code if applicable.
replicable on https://sap.github.io/fundamental-ngx/#/platform/table/basic and https://sap.github.io/fundamental-ngx/#/platform/table/row-selection

#### Is there anything else we should know?
Inconsistency in column and row reading for disabled users impacts Guided sourcing users.

**Comment by mikerodonnell89** [comment]
published a hotfix to 0.43.3

**Comment by I543348** [comment]
To be evaluated and confirmed

**Comment by I543348** [comment]
This works fine tested on deploy preview URL

**Comment by sagar7259** [comment]
Hello,

Now the row count and column counts are being read correctly on changing the row or column, hence this needs ticket can be closed.

Regards,
ATL Team
