### ISSUE TITLE
[Sourcing] fdp-input-group enhancement on mousewheel scroll

### ISSUE THREAD

**Issue by bharathSivaSAP** [SAP/fundamental-ngx#10192]
Is this a bug, enhancement, or feature request?
Enhancement

Briefly describe your proposal.
We need a property to control the mousewheel scroll on the input field to be disabled or enabled
This is a clone of the issue https://github.com/SAP/fundamental-ngx/issues/9925
Initially this got closed thinking there is a workaround which was to remove SAP UI5 script from index.html.
Looks like the SAP UI5 script cannot be removed since CatMan Cards will not work without it.
So, we want a property to control mousewheel event.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
15

If this is a bug, please provide steps for reproducing it.
Enhancement.

Please provide relevant source code if applicable.
Is there anything else we should know?

**Comment by mikerodonnell89** [comment]
You can catch the `wheel` event in your html like so:
`<fdp-input-group (wheel)="mousewheelEvent($event)">`

And handle it in your component code however you like
```
mousewheelEvent(event: WheelEvent): void {
    console.log(event);
    event.preventDefault(); // or whatever you want to do
}
```

Please let me know with more specifics if there is something I'm not understanding from the original issue
