### ISSUE TITLE
Internalisation code example isn't seen

### ISSUE THREAD

**Issue by jyoti1507** [SAP/fundamental-ngx#10199]
#### Is this a bug, enhancement, or feature request?
Internalisation code example isn't seen in https://sap.github.io/fundamental-ngx/#/core/home
#### Briefly describe your proposal. 
attaching screenshot
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
all version having same [issue]([url](url))

**Comment by jyoti1507** [comment]
<img width="1363" alt="Screenshot 2023-07-21 at 10 27 18 AM" src="https://github.com/SAP/fundamental-ngx/assets/38528135/c9650a85-da8a-4d88-a229-30f1a26dec5e">

**Comment by fkolar** [comment]
@jyoti1507 , Unable to reproduce, can you check again on latest version?

**Comment by jyoti1507** [comment]
> @jyoti1507 , Unable to reproduce, can you check again on latest version?

I'm still facing sae issue in latest version

**Comment by fkolar** [comment]
You can directly access: https://github.com/SAP/fundamental-ngx/tree/main/libs/docs/i18n/examples, while this is fixed.
