### ISSUE TITLE
[P2][Sourcing] Header checkbox can still be selectable if NGX package imported in child module

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10201]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

Following the fix from https://github.com/SAP/fundamental-ngx/issues/10134, if we have NGX package imported in child module, when table is empty or has no visible columns, the header checkbox is still selectable.

![Screenshot 2023-07-21 at 12 35 55 PM](https://github.com/SAP/fundamental-ngx/assets/22842279/e69ec390-29d1-4c35-8181-52585200cc78)

Expectation: it should work even the NGX packages are imported in child module.

Baseline: https://fundamental-ngx.netlify.app/#/platform/table/scrolling when we search to return empty data.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

- Have NGX core/platform packages imported in child module.
- Create platform table in multi selectionMode
- Search or set columns so that no data is displayed.
- Try to se/delect header checkbox

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-sufq3o-jvuhry?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

**Comment by CSENoni** [comment]
I think it maybe somewhat similar issue to this https://github.com/SAP/fundamental-ngx/issues/10127, may need to import some module in root?

**Comment by fkolar** [comment]
The stackblitz does not work - missing some import..

**Comment by CSENoni** [comment]
Link is changed: https://stackblitz.com/edit/angular-sufq3o-jvuhry?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

**Comment by fkolar** [comment]
Just a note, please dont use 

  ```
 FundamentalNgxCoreModule,
    FundamentalNgxPlatformModule,
```

this is not the best we can do, try to import individual modules, but of course it does not solve the problem but just to remember.

**Comment by droshev** [comment]
if there is a fix => downport to `ng15`

**Comment by CSENoni** [comment]
Selection is hidden when no data is displayed in table. It works for both search/filter and all hidden columns in child module. Thanks!
