### ISSUE TITLE
Popover with mobile config can't be closed

### ISSUE THREAD

**Issue by nikola-miletic** [SAP/fundamental-ngx#10216]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

Popover in mobile view should be closable

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx: 0.42.0 and angular: 15.2.8

#### If this is a bug, please provide steps for reproducing it.
Go to official documentation: https://sap.github.io/fundamental-ngx/#/core/popover
Search for: _Responsive Popover in mobile mode_
Click on: _Open Mobile Popover_
Click on "X" in top of right corner
Notice that nothing happen

#### Please provide relevant source code if applicable.
<img width="1679" alt="Screenshot 2023-07-24 at 14 59 38" src="https://github.com/SAP/fundamental-ngx/assets/43137517/b09ca371-3daf-42bd-9eb2-0048be8012db">

**Comment by nikola-miletic** [comment]
Hi @N1XUS, looks like this is fixed via https://github.com/SAP/fundamental-ngx/pull/10063/files

I have tested this on version 0.43.0-rc.4 which is also available here: https://fundamental-ngx.netlify.app/#/core/popover
and it is working fine.

**Comment by N1XUS** [comment]
@nikola-miletic thank you for your comment. I've also tested this behaviour with the latest RC branch and can confirm that the issue was fixed before. Closing this ticket.
