### ISSUE TITLE
[P3][Sourcing]Table column title not available until column resized

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10212]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Platform table column title property is not available until user shrinks the column.
This is impacting the column which has lengthy text by default (without shrink or expand). However , ellipsis is available for the text but there is not tooltip using "title" attribute.
Please help for this use case.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core / platform: 0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
Bind a lengthy text such that an ellipsis is displayed in the column header label by default.
Hover on it , and see there is no tooltip displayed.

#### Is there anything else we should know?
"fd-table__cell--truncate-txt" class is applied but there is no "title" attribute for displaying full name of the column

**Comment by fkolar** [comment]
Stackblitz or something similar is needed. here.

**Comment by I543348** [comment]
Hi @fkolar  , please find the stackblitz link for this use case: https://stackblitz.com/edit/angular-vs32is?file=src%2Fapp%2Fplatform-table-wrap-example.component.html
Please notice the "Description" column for which i have increased the length of the text

**Comment by fkolar** [comment]
@I543348 , Do you mean title property (binding) or label? Do the issue is, until you start shrinking the column the tooltip is not shown. and in this case it should trigger immediately for the description..

**Comment by I543348** [comment]
the issue is for html property "title" (tooltip).
The issue happens when the column name is by default lengthy and table loads without title attribute

**Comment by fkolar** [comment]
Not, its ok. The title is only added after we resize the column and we just need to run the logic during initialize.

**Comment by droshev** [comment]
if there is a fix => downport to `ng15`

**Comment by g-cheishvili** [comment]
@fkolar , I was thinking, why not add `attr.title` always, regardless of whether it overflows or not?

**Comment by droshev** [comment]
fixed with `0.43.8`
