### ISSUE TITLE
[Sourcing][Accessibility] Multi input button is read as toggle button for value-help dialog

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10214]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

Multi input Button label is read as toggle button and no description is provided here which can say what this button does ( there should custom variable  where we can pass text like 'press enter to open modal')

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15
core /platform: 0.43.0-rc.16
#### If this is a bug, please provide steps for reproducing it.
1) Focus on multi-input button
2) Notice that the role is read as toggle button even though its not and there is no option to tell user how to open dialog

<img width="538" alt="Screenshot 2023-07-24 at 12 14 19 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/527aa6c3-fdc1-478d-b72f-3cdb24d6ea20">

**Comment by fkolar** [comment]
Not a bug, MultiInput has binding called title that you should use.

**Comment by I543348** [comment]
Title is just for tooltip , however that is not read by screenreader , hence reported this https://github.com/SAP/fundamental-ngx/issues/10393
