### ISSUE TITLE
[P1][Sourcing] [Accessibility][Chooser][a11y help]Multi-input with value help dialog redundant text is read on dialog open

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10213]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Extra information apart from label on dialog and dialog role is been read like 1 more item and 1 more item...

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core / platform: 0.43.0-rc.16
#### If this is a bug, please provide steps for reproducing it.
1) Focus on multi-input button 
2) Dialog is opened and focus goes to Search box with below screenreader text "3 more items and 1 more item and 1 more item" is redundant here.
Please help here.

<img width="748" alt="Screenshot 2023-07-25 at 2 47 47 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/cc511710-65fe-4ab9-bd3c-e9e8e645497f">

**Comment by fkolar** [comment]
Instead of passing screenshot from internal application this is something that you should be able to reproduce on the regular table if there is a problem.

**Comment by I543348** [comment]
I am currently working and will try to provide a stackblitz link soon.

**Comment by droshev** [comment]
We need to downport to `ng15`

**Comment by sagar7259** [comment]
Hello,

As per the retest activity, the issue with additional information read is no more reproducible. But upon opening the value help, the respective dialog title 'Single select value help dialog' is not being read to the users and only the information of the focused 'Search' input fields is read . and this needs to be fixed.

Regards,
Sagar

**Comment by droshev** [comment]
The reported request has been done. This is a separate topic, which we would need to discuss and analyze with the accessibility expert first. Please, report a new issue.
