### ISSUE TITLE
Popover  disableScrollbar= true will trigger click event on fd-list-item when use keyboard navigate through popover/fd-list

### ISSUE THREAD

**Issue by itsnode** [SAP/fundamental-ngx#10221]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Setting  Popover  disableScrollbar= true will trigger click event on fd-list-item when navigate with Tab key and space/enter to open the second popover.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15.2.8 and Ngx 0.40
#### If this is a bug, please provide steps for reproducing it.
1) Using Enter key to open the user menu and Tab key navigate to the **Settings**, then Enter/Space key  the second level popover will open, and you will see onClick event triggered automatically which should not. Set disableScroobar to false will fix the problem.

#### Please provide relevant source code if applicable.
See https://stackblitz.com/edit/angular-usdxnt?file=src%2Fapp%2Flist-example.component.ts,src%2Fapp%2Flist-example.component.html

**Comment by N1XUS** [comment]
Hello @itsnode. Thank you for your ticket.
I've updated the stackblitz example with the correct usage of popover inside list item. https://stackblitz.com/edit/angular-usdxnt-bfxmne?file=src%2Fapp%2Flist-example.component.ts,src%2Fapp%2Flist-example.component.html

By the way, have you considered using [Menu Component](https://sap.github.io/fundamental-ngx/#/platform/menu) for this scenario?

**Comment by itsnode** [comment]
@N1XUS thanks for helping on this. Will check your solution to see how we can adopt it.
As for converting to using Menu, we tried, it seems menu/submenu does not support template-outlet. See example under 
https://stackblitz.com/edit/angular-uimumh?file=src%2Fapp%2Fmenu-example.component.html

**Comment by itsnode** [comment]
@N1XUS Tried based on your solution. Found couple issues.

- Tab key not able to navigate to the settings button. Need add tabindex="0" to allow tab into. Why this "Settings" requires adding Tabindex. Should not that be default?
- Once tab to the Settings and click "SPACE", if the page has scrollbar, it will trigger scrolling. How to not trigger home page scrolling if press "SPACE"
- Once the second popover opened up, click ESC key will return back to the first popover, stay focus on the "Setting" which is correct. But to reopen the second popover, you need click "SPACE" or "Enter" twice.

Can you help take another look?
