### ISSUE TITLE
Defect Hunting Sprint 118

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#10237]

**Comment by N1XUS** [comment]
- [ ] Core mobile calendar: unnecessary scrollbar: 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/7646cb12-8800-4276-b19c-9e3a53d1c32f)
- [ ] Carousel: strange outline design for button focus: 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/81c42d00-bc3e-4858-b9f4-7b325c7b2521)
- [ ] Carousel: keyboard navigation works only once. After slide being changed, user needs to click on the image again in order for the navigation to work again
- [ ] Carousel loading example: Busy indicator a bit off
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/c1936e2d-e591-4336-8413-7430cfdfdd60)

- [ ] Core combobox: Mobile mode, after closing the dialog, combobox receives doubled outline 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/d8a827f2-1f75-4e6c-a0d6-29340bc6b1ca)

- [ ] More as an improvement: Core combobox accepts TemplateRef input property for the item renderer. It's better to use structural directive here with support of typed arguments
- [ ] Complex dialog example: cursor has `grab` type even if hovered over list item
- [ ] Link: when focused, icon color is still blue: 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/4e3b8342-b2c3-40c4-ba67-003ff494da03)

- [ ] Pagination: when page loading is in progress, I think we should disable pagination buttons in order not to mess up the data.
- [ ] Docs sidebar has standard scrollbar. Should be fundamentals one: 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/614baade-f714-4e75-a709-cb1dbb75c6d7)

- [ ] Rating indicator docs uses native controls (inputs, selects). Should be replaced with fundamentals alternative
- [ ] Core select: Icon in placeholder is skewed: 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/f59584a2-fb1c-489d-9bc3-2090d47997f3)

- [ ] Time: using mousewheel is not smooth (not feeling natural). I'm assuming it does not count delta property of mousewheel efect and just moves the value up/down based on the direction of the scroll. I would suggest applying similar logic as we have with dragging - we scroll the numbers according to the deltaX of the mousewheel event;

**Comment by droshev** [comment]
moved the issues which are not fixed in #10649
