### ISSUE TITLE
search field rtl issue 

### ISSUE THREAD

**Issue by IB002** [SAP/fundamental-ngx#10234]
#### Is this a bug, enhancement, or feature request?

It is a Bug. 
RTL does not properly show Search field suggestions when used.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.42.0-rc.31

#### If this is a bug, please provide steps for reproducing it.

Select simulate RTL in the ngx Search field example. Then type any letter that has suggestions. Example "L".
### Screenshot:

<img width="2335" alt="Screenshot 2023-07-27 at 10 32 28 AM" src="https://github.com/SAP/fundamental-ngx/assets/132930816/b59313f3-b2c5-4bac-8f56-6735c2efea5e">

**Comment by droshev** [comment]
@N1XUS There is a weird issue here, can you check it out?
