### ISSUE TITLE
fundamental ngx components are not loading inside bootstrap modal

### ISSUE THREAD

**Issue by vivekgupta1008** [SAP/fundamental-ngx#10239]
#### Is this a bug, enhancement, or feature request? 
**Bug**

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
**Angular 13**
"@fundamental-ngx/core": "0.33.7",
"@fundamental-ngx/platform": "0.33.7",
"@ng-bootstrap/ng-bootstrap": "9.1.2",

#### If this is a bug, please provide steps for reproducing it.
-Open a modal using from @ng-bootstrap/ng-bootstrap
-If the opened modal is using any fundamental ngx components, it is not loading/showing up.

#### Is there anything else we should know?
Opening a modal using bootstrap library:
<img width="708" alt="Screenshot 2023-07-28 at 20 08 36" src="https://github.com/SAP/fundamental-ngx/assets/43698920/4b22598f-10b4-4fc4-a697-18aa4317e6c0">

The modal component that uses fundamental ngx component
<img width="566" alt="Screenshot 2023-07-28 at 20 10 01" src="https://github.com/SAP/fundamental-ngx/assets/43698920/cd9eb74f-08e0-495a-9e02-0c08f80879b8">

**Comment by droshev** [comment]
@vivekgupta1008 Can you try the same scenario with a newer version?
