### ISSUE TITLE
[Sourcing][Aug21] `datepicker` popover is not closed in `virtualScroll` after value is selected

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10243]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

We have a platform table with `virtualScroll` enabled. After we try to scroll pass the default `renderAhead` and open `datepicker` popover to select a value, the popover is not closed till we select different value. However, previous selected value will be added instead.

https://github.com/SAP/fundamental-ngx/assets/22842279/2ef9ea93-8b5f-4d36-be3a-5b5363ec9042

It is only replicable with `virtualScroll` on.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.43.0

#### If this is a bug, please provide steps for reproducing it.

- Create a platform table with `virtualScroll` enabled.
- Scroll pass a default `renderAhead`.
- Open any `datepicker`.
- Try to select a value.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-9jp2kz-fe9jqa?file=package.json,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

**Comment by CSENoni** [comment]
Source code link is updated. Not sure why it was removed.

**Comment by droshev** [comment]
@N1XUS we would need to downport this to `ng15`. We can discuss internally how to tackle this.

**Comment by CSENoni** [comment]
It is working now with `0.43.5`. Thanks!
