### ISSUE TITLE
[P3.2][Sourcing][Accessibility]Row border color is not correct in `fdp-table` single row selection

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10244]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

The focus color when we select a row in single selection mode is different:

![Screenshot 2023-06-20 at 9 23 07 AM](https://github.com/SAP/fundamental-ngx/assets/22842279/6bb9afab-83d0-4b14-aea0-561e6e5b6280)
<img width="365" alt="Screenshot 2023-06-20 at 9 23 25 AM" src="https://github.com/SAP/fundamental-ngx/assets/22842279/b3de373b-3a5f-4861-bee4-ff85381ee07b">

#### If this is a bug, please provide steps for reproducing it.

Please refer to the link below:

#### Please provide relevant source code if applicable.

https://ui5.sap.com//#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Selection
https://fundamental-ngx.netlify.app/#/platform/table/row-selection

**Comment by CSENoni** [comment]
From @fkolar 

> I can replicate now with the row-selection example. The white border is not definitely not correct.

**Comment by droshev** [comment]
We need to create a fix for `ng15` locally, instead of coming from styles.

**Comment by mikerodonnell89** [comment]
This was fixed with https://github.com/SAP/fundamental-ngx/pull/10754
