### ISSUE TITLE
[Sourcing][Multi-input][Chooser][Accessibility] Tokens selected are read as "not selected" which is wrong

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10259]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1) Reach a selected token in multi-input using left or right arrow keys
2) Screen reader is reading as token name , deletable , not selected

Here "not selected" is not true as they are all tokens which are selected from list

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
1) Reach a selected token in multi-input using left or right arrow keys
2) Screen reader is reading as token name , deletable , not selected

#### Please provide relevant source code if applicable.
Replicable on https://sap.github.io/fundamental-ngx/#/core/multi-input

<img width="1792" alt="issue_2_NGX" src="https://github.com/SAP/fundamental-ngx/assets/88182358/dedd9a20-7529-419b-8b6e-07eb8f631c4b">

**Comment by mikerodonnell89** [comment]
This is working the same as UI5. They are reading as selected when they're clicked or otherwise marked for deletion. I guess we need a way to differentiate between selected as in marked for deletion, and selected as in a selected option. We'll likely need input from the accessibility teams on this

**Comment by droshev** [comment]
The only operation that you can perform to that item is to delete. Furthermore, we will stay aligned with ui5.

**Comment by I543348** [comment]
ATL Re-verification needed

**Comment by sagar7259** [comment]
Hello,

Now the additional information "Not selected" is no more being read on accessing the tokens. Hence this ticket can be closed.

Regards,
Sagar
