### ISSUE TITLE
[Datepicker] manual date entering is challenging #2

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#1027]
#### Is this a bug, enhancement, or feature request?

bug / bad ux

#### Briefly describe your proposal.

It requires extra effort to input dates manually to datepicker

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

After https://github.com/SAP/fundamental-ngx/issues/967 fix - Its still extremally hard to input date via keyboard comparing to other datepickers in the market. Could you play around and have a look? Example below:

![datepicker-autocomplete](https://user-images.githubusercontent.com/12159534/60447351-8f17c980-9c23-11e9-8ddc-257780c2b116.gif)

**Comment by JKMarkowski** [comment]
Hi @konradkukier2, problems with date picker/datetime picker will be solved, after pushing https://github.com/SAP/fundamental-ngx/issues/983 .
