### ISSUE TITLE
[P2][Sourcing][Accessibility][Table]The search field is marked with aria-haspopup, although no pop-up can be opened (see screenshot).

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10285]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The search field is marked with aria-haspopup, although no pop-up can be opened (see screenshot).

#### If this is a bug, please provide steps for reproducing it.
Tested on NGX website table example https://sap.github.io/fundamental-ngx/#/platform/table/basic#default

<img width="1462" alt="Screenshot 2023-08-03 at 9 41 33 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/f18b73cf-97eb-4bf1-bb29-c12c3342bac5">

#### Is there anything else we should know?
Reported by customer

**Comment by nikolay-kolarov** [comment]
Hi,

The search field needs aria-haspopup only then it will open a popup.
E.g.: https://ui5.sap.com/#/entity/sap.m.SearchField/sample/sap.m.sample.SearchFieldSuggestions
If this is not the case in the scenario here, the aria-haspopup needs to be removed.

Best Regards,
Nikolay

**Comment by droshev** [comment]
We need to downport to `ng15`

**Comment by I543348** [comment]
ATL Re-verification needed

**Comment by droshev** [comment]
fixed with `0.43.7`

**Comment by sagar7259** [comment]
Hello,

Aria-has popup is still true for the search input field and this needs to be fixed.

@rvamudha please reopen this ticket.

Regards,
Sagar

**Comment by droshev** [comment]
@sagar7259 which version did you test that on?

**Comment by sagar7259** [comment]
Hi @droshev ,

The issue is not been verified in 0.43 and found that the issue is fixed. Now the aria has popup is set to false, hence this ticket can be closed.

Regards,
Sagar
