### ISSUE TITLE
[P2][Sourcing][Accessibility][Multi-input list]The selection list allows multiple selection, but was not marked with aria-multiselectable.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10288]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The selection list allows multiple selection, but was not marked with aria-multiselectable.

#### If this is a bug, please provide steps for reproducing it.
tested on multi input mobile mode example
The selection list allows multiple selection, but was not marked with aria-multiselectable.

#### Is there anything else we should know?
reported by customer

**Comment by I543348** [comment]
ATL comment:
The multi value input (type=text) element does not have a mechanism that allows an accessible name value to be calculated.

**Comment by nikolay-kolarov** [comment]
Hi,

Yes, aria-multiselectable="true" can be added to the ul element. Also it currently has a role list and contains options, which is not allowed. List shall contain listitems.
In UI5 the role is listbox: https://ui5.sap.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox

Best Regards,
Nikolay

**Comment by droshev** [comment]
We need to downport this to `ng15`

**Comment by droshev** [comment]
fixed with `0.43.7`
