### ISSUE TITLE
[P2][Sourcing][Accessibility][Table]The buttons at the search field do not have a label, but only a description via title attribute (see screenshot).

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10286]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The buttons at the search field do not have a label, but only a description via title attribute (see screenshot).

#### If this is a bug, please provide steps for reproducing it.

<img width="1335" alt="Screenshot 2023-08-03 at 9 43 25 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/2749e22d-c954-4e28-9d29-ab05cfe215af">

#### Is there anything else we should know?
Reported by customer

**Comment by I543348** [comment]
Comments from ATL team:
On accessing the ‘Clear’ and ‘Synchronize’ buttons on ‘Search’ input field in forms mode, the labels are being read correctly but the same labels are not being associated with linear reading mode.

**Comment by nikolay-kolarov** [comment]
Hi,

Historically there was a lengthy discussion with the acc experts and UX, and finally an agreement that on desktop the buttons in input fields need to be hidden from screen reader (aria-hidden=true). Also no tooltip shall be provided.
On mobile, you can leave the role button and put the purpose of the button in aria-label.

With regards to the labelling of the search field, you can add an aria-label.
Please check the implementation in UI5 DatePicker as a reference: https://ui5.sap.com/#/entity/sap.m.DatePicker/sample/sap.m.sample.DatePicker

Best Regards,
Nikolay

**Comment by sagar7259** [comment]
Hello,

The issue is now fixed.

Thanks,
Sagar
