### ISSUE TITLE
[P3.2][Sourcing][Accessibility][Multi input tokens][doc]No indication for keyboard users how to reach and delete them.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10291]
#### Is this a bug, enhancement, or feature request?

Bug 
#### Briefly describe your proposal.
No indication for keyboard users how to reach and delete them.
We mostly need a proper documentation if user can reach them using some keys.

#### If this is a bug, please provide steps for reproducing it.
No indication for keyboard users how to reach and delete them.
Multi input mobile mode selected tokens

#### Is there anything else we should know?
reported by customer

**Comment by droshev** [comment]
@I543348 Can you provide more input, context and screenshot?
In mobile I see the X button and when i click the item gets removed.

**Comment by I543348** [comment]
Hi @droshev ,This is a customer testing issue.
We had discussed this and triaged the issue along with ATL.
Could you please connect with them for more details?

Thanks.

**Comment by droshev** [comment]
@I543348 The agreement is that you provide us with all the input so we can work on the issue.

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

I think they simply need a documentation on how to use and test the control with keyboard.
E.g. when the focus is on the input, you can press the arrow-left key to go in the tokens, etc.
I gave some links as inspiration in #10280.

Best Regards,
Nikolay

**Comment by sagar7259** [comment]
Hello,

I agree with Nikolay's comment here. The documentation of the key combinations to reach and delete the tokens is more than enough.

Regards,
Sagar(ATL team)

**Comment by droshev** [comment]
so there is no need to downport anything, but just link to sap keyboard documentation. I doubt this is a blocker

**Comment by droshev** [comment]
moving to [P3] as agreed  and as it is just doc update

**Comment by droshev** [comment]
agreed to be closed as it will be handled by sourcing team
