### ISSUE TITLE
[P2][Sourcing][Accessibility][Multi input tokens]The horizontal alignment of the list is not perceptible with the screen reader. Selection lists are usually vertically oriented and are operated with the up and down arrow keys. Here, however, only right and left arrow keys work, which is not perceptible with JAWS

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10295]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The horizontal alignment of the list is not perceptible with the screen reader. Selection lists are usually vertically oriented and are operated with the up and down arrow keys. Here, however, only right and left arrow keys work, which is not perceptible with JAWS

#### If this is a bug, please provide steps for reproducing it.
The horizontal alignment of the list is not perceptible with the screen reader. Selection lists are usually vertically oriented and are operated with the up and down arrow keys. Here, however, only right and left arrow keys work, which is not perceptible with JAWS
tested on multi input mobile mode after selecting few tokens

#### Is there anything else we should know?
reported by customers

**Comment by droshev** [comment]
@I543348 Can you provide more context and screenshots

**Comment by droshev** [comment]
@I543348 The agreement is that you provide us with all the input so we can work on the issue.

**Comment by nikolay-kolarov** [comment]
Hi,

I found a gap in the implementation which I think is the issue for with the customer complains.
When you navigate in the tokenizer in the multiinput, you should be able to use [arrow left] and [arrow up] to go to the previous token on the left. But in the MultiInput implementation only [arrow left] works and [arrow up] goes in the list, which is wrong.
You can have a look at the UI5 implementation as a reference: https://ui5.sap.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInput

Best Regards,
Nikolay

**Comment by fkolar** [comment]
@I543348, I will keep the WIP, until we are 100% sure and until we update this with some screenshot or some more details. Unless you can say, that you agree @nikolay-kolarov and you guys are talking about the same problem. In this case please remove WIP

**Comment by sagar7259** [comment]
Hello,

On accessing the tokens of the multi value input, the reading is made has
"list with 7 items
Blueberry Deletable token
7 of 7
To move to an item press the Arrow keys."

Here to move to an next token, tutor message is read as to use the arrow keys, but its failed to conveyed which arrow keys to be used, weather is a up/down arrow key or right/left arrow key.

When this issue is compared with UI5 component, here in UI5 demo kit the same tokens can be accessed using any arrow keys.

Conclusion: either the NGX multi value tokens should be accessed using both up/down and right/left arrow keys or the information to use left/right arrow keys to be conveyed to the users.

UI5 component: https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputMaxTokens
NGX component: https://sap.github.io/fundamental-ngx/#/core/multi-input#mobile

Regards,
Sagar

**Comment by droshev** [comment]
@sagar7259 the mobile example is not supposed to be tested on desktop. Please, ignore that example. How about the desktop examples?

**Comment by rvamudha** [comment]
ATL re-verification required

**Comment by sagar7259** [comment]
Hello,

My Previous comment holds true for the desktop example also. This can be verified here in all the other desktop examples.

https://sap.github.io/fundamental-ngx/#/core/multi-input

Regards,
Sagar

**Comment by g-cheishvili** [comment]
> Hello,
> 
> My Previous comment holds true for the desktop example also. This can be verified here in all the other desktop examples.
> 
> https://sap.github.io/fundamental-ngx/#/core/multi-input
> 
> Regards, Sagar

You are looking at the stable release. [Checkout RC version.](https://fundamental-ngx.netlify.app/#/core/multi-input)

**Comment by g-cheishvili** [comment]
> > Hello,
> > My Previous comment holds true for the desktop example also. This can be verified here in all the other desktop examples.
> > https://sap.github.io/fundamental-ngx/#/core/multi-input
> > Regards, Sagar
> 
> You are looking at the stable release. [Checkout RC version.](https://fundamental-ngx.netlify.app/#/core/multi-input) And since this is already downported, you can check also [the downport deployment](https://ng-15-downport--fundamental-ngx.netlify.app/#/core/multi-input) which is for version v0.43.9

Tip: you can install from npm latest Angular compatible version using the tag `ng15` on [npm](https://www.npmjs.com/package/@fundamental-ngx/core?activeTab=versions)
