### ISSUE TITLE
[P3][Sourcing][Accessibility][Multi input tokens]After deleting a list entry and refocusing the list, JAWS outputs the old number of list entries rather than the current number.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10297]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
 After deleting a list entry and refocusing the list, JAWS outputs the old number of list entries rather than the current number.

#### If this is a bug, please provide steps for reproducing it.
 After deleting a list entry and refocusing the list, JAWS outputs the old number of list entries rather than the current number.
tested on multi input mobile mode

#### Is there anything else we should know?
reported by customer

**Comment by nikolay-kolarov** [comment]
Hi @I543348 ,

I tried to reproduce on this page (with Jaws on windows): https://sap.github.io/fundamental-ngx/#/platform/multi-input and I was not able to reproduce what you have experienced.

Could you please provide a link where you tested this (or try it directly on the test page here https://sap.github.io/fundamental-ngx/#/platform/multi-input) and give us detailed steps what you do with the keyboard?

Thanks,
Nikolay

**Comment by I543348** [comment]
hi @nikolay-kolarov , I have asked ATL team to help here, as it was also reported by ATL team.
Thanks.

**Comment by sagar7259** [comment]
Hello Nikolay,

You can find the issue from this link https://github.wdf.sap.corp/pages/Ariba-Sourcing/ngxwrapper/ch

Its a custom control and this is where the issue still exist.

Regards,
ATL team

**Comment by nikolay-kolarov** [comment]
Hi,

Thanks! In this example it is reproducible. When a token is deleted aria-setsize on the other tokens is not updated.

Best Regards,
Nikolay

**Comment by nikolay-kolarov** [comment]
I managed to reproduce it in the MultiInput as well: https://sap.github.io/fundamental-ngx/#/platform/multi-input
Add three tokens, and then go and delete the middle one.
