### ISSUE TITLE
[P2][Sourcing][Accessibility][Button]Buttons have the unnecessary addition "Emphasized " in the label

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10292]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Buttons have the unnecessary addition "Emphasized " in the label

#### If this is a bug, please provide steps for reproducing it.
Buttons have the unnecessary addition "Emphasized " in the label
tested in multi input mobile mode "Approve" button

#### Is there anything else we should know?
reported by customer

**Comment by droshev** [comment]
`<button aria-description= "emphasized" aria-label="approve">`

test in Voice Over

**Comment by droshev** [comment]
fixed with `0.43.6`

**Comment by I543348** [comment]
ATL Re-verification needed

**Comment by sagar7259** [comment]
Hi Team,

The information "Emphasized" is read only for the emphasized buttons and not for normal buttons, which is reading correctly has expected. Emphasized buttons should be conveyed to the users has its emphasized.
Hence this is not an issue from ATL side and can be closed.

Regards,
Sagar
