### ISSUE TITLE
[WIP][Sourcing][Accessibility][Multi input selection list]A list entry can be selected with SPACE key and ENTER key. The purpose of the selection is not apparent

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10300]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
A list entry can be selected with SPACE key and ENTER key. The purpose of the selection is not apparent.
#### If this is a bug, please provide steps for reproducing it.
A list entry can be selected with SPACE key and ENTER key. The purpose of the selection is not apparent.
tested on multi input mobile mode selection list inside dialog

some feedback we got from customers - 
 The items can be selected and the selection state is also output by the screen reader as well as visually displayed (blue color). But nothing can be done with the selected items, so the selection option is meaningless. In addition, the keyboard operation of the selection is unusual, because in selection lists the selection is usually made automatically with arrow key navigation and not with SPACE or ENTER
 
#### Is there anything else we should know?
reported by customer

**Comment by I543348** [comment]
Hi @nikolay-kolarov , This was reported by ATL , I will ask them to confirm the same.

**Comment by sagar7259** [comment]
Hello,
When this is compared with the UI5 lists, the list items can be selected using both spacebar as well as enter key. This is done in order to give the possibility to a keyboard user to have multi selection and deletion of tokens. Hence this is not an issue.

Regards,
Sagar (ATL team)

**Comment by nikolay-kolarov** [comment]
Hi,

Here Space and Enter also work as expected. So I am closing the issue.
Please reopen if I miss something.

Best Regards,
Nikolay
