### ISSUE TITLE
Modify Dropdown width not possible

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#1030]
#### Is this a bug, enhancement, or feature request?
**Enhancement**

&nbsp;
#### Briefly describe your proposal.

I'm using the dropdown element and I try to expand the width to 100%, but I'm not able to do it.

Here is what I have now:
![Screenshot 2019-07-16 at 14 23 20](https://user-images.githubusercontent.com/26272656/61294443-19d8f680-a7d6-11e9-85f4-101d8851b502.png)

This is what I want (The arrow should be on the right side):
![Screenshot 2019-07-16 at 14 24 08](https://user-images.githubusercontent.com/26272656/61294444-19d8f680-a7d6-11e9-84f7-680a3e892bd1.png)

The Dropdown element has currently no API documentation: https://sap.github.io/fundamental-ngx/dropdown.
Therefore, I checked the component code, but I didn't found any attribute that can be used for this requirement: https://github.com/SAP/fundamental-ngx/blob/master/library/src/lib/popover/popover-dropdown/popover-dropdown.component.ts

I tried also to modify the CSS manually, but the tag that need to be modified is in a child-tag of the dropdown-component where I don't have access to.

&nbsp;
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
* **Angular version "^7.1.3"**
* **Fundamental NGX version "0.7.0"**

&nbsp;
#### Please provide relevant source code if applicable.
```html
<fd-popover [isDropdown]="true" [fillControl]="true">
    <fd-dropdown-control [toolbar]="true"  style="width: 100% !important">
        <span style="width: 100% !important">{{companySelected}}</span>
    </fd-dropdown-control>
    <fd-popover-body *ngIf="companyOptions && companyOptions.length">
        <fd-menu>
            <ul fd-menu-list>
                <li fd-menu-item *ngFor="let option of companyOptions"
                    (click)="updateCompany(option)">
                    {{option}}
                </li>
            </ul>
        </fd-menu>
    </fd-popover-body>
</fd-popover>
```

**Comment by MattL75** [comment]
Hey @zaheral! We're currently in the process of adding a much more robust select component, which should be a better fit for your usecase.  

Meanwhile, you can take a look at the styled native select element here https://sap.github.io/fundamental-ngx/form. It is worth noting that the native select is harder to style, but does offer better accessibility features than any other custom select.

**Comment by MattL75** [comment]
Closing for housekeeping. Select component will be out soon.
