### ISSUE TITLE
[Sourcing][Accessibility][Sep4] Focus does not shift to the other dates in the date-picker inside fd-dialog.

### ISSUE THREAD

**Issue by kit-ngx23** [SAP/fundamental-ngx#10323]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

When the fdp-date-picker component is placed within the fd-dialog component, the focus does not get shifted within the calendar. Due to this, clicking the tab key or arrow keys does not move the focus to the other dates in the date-picker. 

Expectation:
On clicking the arrow keys, the focus should move accordingly to the other dates in the date-picker.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15.2.0
Fundamental ngx 0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.

1. Add fdp-date-picker inside fd-dialog.
2. Open the date-picker and use arrow keys or tab key.
3. The focus does not shift to the subsequent dates inside the date picker.

URLs:
Editor URL- https://stackblitz.com/edit/angular-g8uaq1?file=src%2Fapp%2Fdialog-backdrop-container-example.component.ts
Application URL - https://angular-g8uaq1.stackblitz.io

Screenshot:
![image](https://github.com/SAP/fundamental-ngx/assets/141992844/7ed4781c-1394-4384-9545-1e5245aa27e5)

**Comment by I543348** [comment]
This is raised by customer (cust1)

**Comment by sagar7259** [comment]
Hi Team,

This was verified with https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/datetime-picker and still the issue is reproducible.

@rvamudha please reopen this ticket.

Regards,
Sagar
