### ISSUE TITLE
Additional tab stop with reading

### ISSUE THREAD

**Issue by Nitin-789** [SAP/fundamental-ngx#10326]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
While navigating a form having wizard component there is an additional tab stop in between which is not focused on the page also voice over reads the entire page when reached on that element having tabindex as 0.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
Have a for with wizard component and try navigating via tab key press, after the navigation passes through the wizard and enter the form an additional tab stop is encountered which is not visible in the screen.

#### Please provide relevant source code if applicable.

<img width="695" alt="Screenshot 2023-08-12 at 11 19 28 PM" src="https://github.com/SAP/fundamental-ngx/assets/37510228/32837a63-a303-4d04-8e1e-d0cda0da0899">

#### Is there anything else we should know?
No

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

I was not able to reproduce this and saw that the scrollbar do not have tabindex.
I tried https://fundamental-ngx.netlify.app/#/platform/wizard-generator and here https://fundamental-ngx.netlify.app/#/core/wizard.

Best Regards,
Nikolay
