### ISSUE TITLE
[P2][Sourcing]fdp-table search input field has aria-expanded attribute

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#10346]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
aria-expanded is not a valid attribute for input field. The search input field for fdp-table has aria-expanded attribute

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
Inspect the fdp-table search input through browser & check that aria-expanded attribute is added for this input

#### Please provide relevant source code if applicable.
<fdp-table #table 
        [dataSource]="source"
        [selectionMode]="selectionMode"
        [selectedKey]="'selected'"
        emptyTableMessage="No data found"
        [virtualScroll]="true"
        [expandOnInit]="true"
        bodyHeight="61vh"
        [noVerticalBorders]="true"
        [noOuterBorders]="true"
        [highlightNavigatedRow]="true"
        (rowSelectionChange)="onRowSelectionChange($event)">

#### Is there anything else we should know?
This is an accessibility issue which is affecting Guided Sourcing Application
<img width="938" alt="Screenshot 2023-08-15 at 8 53 50 AM" src="https://github.com/SAP/fundamental-ngx/assets/12679774/b96d12e5-8323-450c-91a5-0a30e3084f49">
![Picture1-3](https://github.com/SAP/fundamental-ngx/assets/12679774/6f6c2aab-12fc-475a-abdb-ad65b1ba0268)

**Comment by I543348** [comment]
ATL comment:
The aria-expanded attribute is not allowed on the input ‘Search’.

**Comment by nikolay-kolarov** [comment]
Hi,

Yes, the aria-expanded is not allowed on an element with role input and not needed in this case.
It will be needed, if this field is more like a combobox and opens up a popup with items, which is not the case. 
So it can be removed in combination with aria-haspopup, as noted in #10285.
You can use the Ui5 SearchField implementaiton as a reference: https://ui5.sap.com/#/entity/sap.m.SearchField/sample/sap.m.sample.SearchField

Best Regards,
Nikolay

**Comment by droshev** [comment]
fixed with `0.43.7`

**Comment by sagar7259** [comment]
Hi Team,

This issue is no more reproducible using AMP tool, hence this can be closed as now its fixed.

Regards,
Sagar
