### ISSUE TITLE
TabIndex is reset to -1 for fdp column and fdp table cell

### ISSUE THREAD

**Issue by ravesingh1983** [SAP/fundamental-ngx#10340]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

While navigating from one column header to another column header and from one table cell to another table cell we are seeing that  the current focussed UI element is making tabIndex to be set to -1 for other UI elements. Due to this the navigation to UI element where tabIndex is set to -1 is blocked

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.

Steps to reproduce:

1) Create a fdp-table add a static column

2) Add  dynamic columns

3) Try to navigate to table header using the tab option. We will see that we are not able to navigate to 2nd Column. 

#### Please provide relevant source code if applicable.

<img width="908" alt="Screenshot 2023-08-14 at 3 12 38 PM" src="https://github.com/SAP/fundamental-ngx/assets/32221444/7b4301c9-4061-4989-bcfb-b02c25ef4c76">

#### Is there anything else we should know?

No

**Comment by N1XUS** [comment]
Hello @ravesingh1983. Keyboard navigation in platform table is following W3C and SAP recommendation for grid keyboard navigation. To actually navigate inside the table, use arrow keys.
