### ISSUE TITLE
[P2][Sourcing]fdp-table Column resizing information is not read

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#10345]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On resizing the columns of a fdp-table using Ctrl+Shift+arrow keys, the same is not conveyed to the screen reader user

#### If this is a bug, please provide steps for reproducing it.
Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16

#### Please provide relevant source code if applicable.
    <fdp-table #table 
            [dataSource]="source"
            [selectionMode]="selectionMode"
            [selectedKey]="'selected'"
            emptyTableMessage="No data found"
            [virtualScroll]="true"
            [expandOnInit]="true"
            bodyHeight="61vh"
            [noVerticalBorders]="true"
            [noOuterBorders]="true"
            [highlightNavigatedRow]="true"
            (rowSelectionChange)="onRowSelectionChange($event)">

#### Is there anything else we should know?
This is an accessibility issue which is affecting Guided Sourcing Application

![Picture1-2](https://github.com/SAP/fundamental-ngx/assets/12679774/d8a0cbb3-7f70-4ae5-ace4-78779cdfa3b8)

**Comment by snigdhaman** [comment]
Hi @nikolay-kolarov 

Please find the comments from ATL team below:
On resizing the columns using Ctrl+Shift+arrow keys, the same is not conveyed to the screen reader user. Here just “Selected” is being read which is not meaningful.

Expected Behavior:   
Information & properties of all UI elements should be conveyed correctly to the screen reader users when accessed.

**Comment by nikolay-kolarov** [comment]
UI5 example: https://ui5.sap.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Resizing/code

**Comment by droshev** [comment]
the standard component in ui5 doesn't provide information either. If this is needed then the application can implement it.
Aligned with sapui5
