### ISSUE TITLE
Dynamic modal body height

### ISSUE THREAD

**Issue by parostatkiem** [SAP/fundamental-ngx#1035]
#### Is this a bug, enhancement, or feature request?
Feature request and also a bug.
#### Briefly describe your proposal.
A modal body component should expand (of course keeping on mind modal's maximum height) if its content expands. For now, you can set the modal height to a fixed value or not set it to let the modal adopt to its content. It works fine until the content changes - the modal size is unchanged. This is problematic when any dropdown or other expandable element is used as a modal content. A vertical scroll of modal's body appears while the modal itself **could** be expanded vertically instead.

![image](https://user-images.githubusercontent.com/22825433/61370298-6255ea00-a892-11e9-8c76-72f4a5140eba.png)

![image](https://user-images.githubusercontent.com/22825433/61370317-6aae2500-a892-11e9-8eb2-ae5f9fa928fd.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current

**Comment by InnaAtanasova** [comment]
@jeannewalters what would be the best solution in terms of user experience?
- Option 1: 
![Screen Shot 2019-07-24 at 2 32 23 PM](https://user-images.githubusercontent.com/39598672/61818946-fb9b7800-ae1f-11e9-808c-4214dcc92499.png)

- Option 2:
![Screen Shot 2019-07-24 at 2 32 13 PM](https://user-images.githubusercontent.com/39598672/61818966-05bd7680-ae20-11e9-9e52-27f8d47a5730.png)

- Option 3: Expanding the modal body to fit the dropdown list

**Comment by parostatkiem** [comment]
Although the question is not addressed to me, I'd choose the option `3` as the best one. `2` would take the second place. Of course it's my personal opinion 😃

**Comment by MattL75** [comment]
Our official solution, and the one we agreed upon previously with the other libraries, is option 3.

**Comment by stefanoScalzo** [comment]
@parostatkiem  Can you please give examples of existing scenarios

**Comment by parostatkiem** [comment]
@stefanoScalzo What you mean by _existing scenarios_? There's a screenshot above that  shows the problem. I can't show it to you live in my app because it's secured. 
I'm not sure if the problem exists anymore... There was a refactor that put popovers in Portals in React version of the lib.

btw. Your example seems to work well 👍 However, I noticed the arrow in the drop**down** points down but the popover opens upwards.
