### ISSUE TITLE
[P3][Sourcing]Reset button is not enabled if boolean equal to `No` in p13 filter

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10353]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

After filter from p13 is used, `Reset` button is enabled so that we could revert back to original list. However, if column is boolean type, and we set it equal to `No`, the filter works but `Reset` button is not enabled. For example, we have `verified` is boolean type here, set it equal to `No` will disable reset button.

https://github.com/SAP/fundamental-ngx/assets/22842279/4e7b8c9f-b092-49a2-a95d-54d4858bb741

Not a blocker since we could use another method to revert back to original list.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.43.0

#### If this is a bug, please provide steps for reproducing it.

- Create a platform table with p13 filter
- Have one column with dataType = boolean.
- Go to p13 filter dialog -> choose that boolean column -> set to equal to "No"

#### Please provide relevant source code if applicable.

https://fundamental-ngx.netlify.app/#/platform/table/p13-dialog-table#p13-table-filter

**Comment by I543348** [comment]
@CSENoni , pls connect with @fkolar  as the issue is in WIP state.
Thanks

**Comment by fkolar** [comment]
There is a definitely problem with UX, but internally it works correctly. When you select a `verified`, the default value is false, so when you select No (false) - nothing really changes. Maybe it should default the dropdown to the value NO which is already set there.

**Comment by droshev** [comment]
downport to `ng15`

**Comment by CSENoni** [comment]
Reset button is enabled now with boolean type is set to "No" in filter in `0.43.8`. Filter functionality is still working fine. Thanks!
