### ISSUE TITLE
Dynamic Page Header Issues

### ISSUE THREAD

**Issue by DominikaZamojska** [SAP/fundamental-ngx#10351]
#### Is this a bug, enhancement, or feature request?
Bugs in component

#### Briefly describe your proposal.

1. Component needs to be verify from accessibility perspective. I found some issues:
Title/Header name should be provided as a level 2 heading (H2) like we have in UI5 Library example:
![Screenshot 2023-08-17 at 10 18 57](https://github.com/SAP/fundamental-ngx/assets/137824445/a96a1b25-90be-42fa-9758-1be1990acbaf)
now in example with facets there is simple text.

2. Other thing which I found is that Heading from the facets are indicated as H1 level which shouldn’t be there - and it is reserved for whole Page Title. If we want them they should be below the H2 as a H3 level.
![Screenshot 2023-08-17 at 10 21 51](https://github.com/SAP/fundamental-ngx/assets/137824445/bb05180d-84b1-472f-a2ab-a3f49b88180e)

3. Chevron  in header pointed always the same direction in your library  but in fact it should changes depends it is collapsing or expanding should show the possible action that user can trigger - same like in the spec
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2039387288 
![Screenshot 2023-08-17 at 10 32 57](https://github.com/SAP/fundamental-ngx/assets/137824445/14eff4a3-c253-40dc-866f-68850888330c)
check the UI5 implementation:
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.f.DynamicPage/sample/sap.f.sample.DynamicPageFreeStyle 
Tooltips are good.

4. In UI5 library we see the Focus on a whole group the same with hover state, after clicking it we can collapse or expand as well the section below:
Check here: https://sapui5.hana.ondemand.com/sdk/#/entity/sap.f.DynamicPage/sample/sap.f.sample.DynamicPageFreeStyle 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Newest 
https://fundamental-ngx.netlify.app/#/core/dynamic-page 

#### Is there anything else we should know?

This whole component needs to be reviewed by the A11y experts

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

Yes, for 1 you need to use either a heading htmlo element or role heading with aria-level. 
For 2 you need to take the heading level hierarchy and nesting into account. If you do not know which heading level is expected according to a floorplan and the usage/nesting of the control is not clear then you need to expose an API, so that the app devs can adjust this accordingly.
3 and 4, as Dominika suggested, you can use UI5 as a reference.

Best Regards,
Nikolay

**Comment by mikerodonnell89** [comment]
@DominikaZamojska could you expand on your fourth point? Maybe provide some A/B screenshots/videos? I don't understand what is being asked here

**Comment by DominikaZamojska** [comment]
Hi @mikerodonnell89 I checked this once again in a version v 0.48.0-rc.45 and it seems to be not an issue anymore. Hover and focus on the header of the page behave and look the same in Fundamental like in SAP UI5. 

So this is not an issue anymore.
