### ISSUE TITLE
[2][Sourcing][Sept18]Scrolling on the table with Virtual Scroll enabled, header goes missing after scroll in Safari and Firefox

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#10367]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In Safari and Firefox -
I am trying to use a virtual scroll for the table and when start scrolling, observed couple of issues
1. Table Header goes missing
2. Row rendering goes for a toss

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
ng 15

#### If this is a bug, please provide steps for reproducing it.
Please open the virtual scroll example in Safari or Firefox browser
[Virtual Scroll example](https://sap.github.io/fundamental-ngx/#/platform/table/scrolling)
<img width="1703" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/107252602/506417a4-7afb-4ad7-92ff-a56156cc247f">

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table/scrolling

#### Is there anything else we should know?
If I drag the scrollbar to the middle, the header gets disappeared.
**My view:** Some additional scroll bar is getting introduced and the header is going up where we are getting the feel that the header is getting disappeared.

**Comment by prasad-userdev** [comment]
<img width="1232" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/107252602/ab8b780d-8107-4bc1-b24f-81dacffb541c">

**Comment by prasad-userdev** [comment]
For point 2, When I drag the scrollbar up and down multiple times and then move to other tab and comeback, the below issue is observed. In some cases It is reproducible when I drag the scrollbar multiple times.

https://github.com/SAP/fundamental-ngx/assets/107252602/41b4ccf5-8e08-44e8-8c32-deee89d45063

<img width="130" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/107252602/3daacc42-bfdd-4037-b955-5a06bb4736f2">

**Comment by droshev** [comment]
we need to downport this to `ng15`

**Comment by droshev** [comment]
fixed with `0.43.6`
