### ISSUE TITLE
Width of the datepicker not getting adjusted to the width of input field

### ISSUE THREAD

**Issue by vsomsekhar** [SAP/fundamental-ngx#10366]
#### Is this a bug, enhancement, or feature request?
Enhancement 

#### Briefly describe your proposal.
Width of the datepicker not getting adjusted to the width of input field

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular - 15
fundamental ngx - 0.43.3

#### If this is a bug, please provide steps for reproducing it.
Go to :- https://deployv2-dev.dev-eu10.build.cloud.sap/lobby
1. Click on the settings tab
2. Click on Governance dropdown
3. Click on Environments
4. Click on Date Picker
<img width="574" alt="Screenshot 2023-08-21 at 9 29 58 AM" src="https://github.com/SAP/fundamental-ngx/assets/142768234/92b58b28-8666-44fe-8dd8-21759c2146fa">

**Comment by droshev** [comment]
@vsomsekhar what is your expectation? the datepicker popover has a fixed width(`20rem`) and there is no a chance that the field itself to have exactly the same width
