### ISSUE TITLE
Accessibility defect | On escape keypress focus from the dropdown is not returned back to the same element.

### ISSUE THREAD

**Issue by Nitin-789** [SAP/fundamental-ngx#10369]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On click of escape button the focus should retain on the same element instead of focus moving to the page.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
1. Navigate the page via keyboard and reach to the fdp-combobox component(dropdown) 
2. Click space bar to open the list of options in the drop down
3. Click down arrow key to enter the option list but don't select any options
4. Click escape and observe that the focus is not retained on the same element

#### Please provide relevant source code if applicable.
https://github.com/SAP/fundamental-ngx/blob/baae10763d57d9cf48fbf4cce170f5762fcda116/libs/platform/src/lib/form/combobox/combobox/combobox.component.ts

#### Is there anything else we should know?
No

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

I was able to reproduce this in the samples of the combobox. Yes, after escape in the picker of the combobox the focus need to stay into the combobox.

Best Regards,
Nikolay
