### ISSUE TITLE
[P2][Sourcing]Need control to enable/disable "snap on scroll" feature in dynamic page

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#10375]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

In our application, there is no "**_snap on scroll_**" feature. So, while adopting the **_dynamic page_**, "snap on scroll" feature is not required to be enabled. So, control is needed to enable/disable it.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

"@fundamental-ngx/core": "0.43.0"
"@angular/cli": "15.2.0"

**Comment by Sayandeep-123** [comment]
Linking the previous ticket raised regarding this - https://github.com/SAP/fundamental-ngx/issues/9908
cc- @fkolar

**Comment by fkolar** [comment]
What you want is a new binding:

```html
 [disableSnapOnScroll] = "true"
```

- **Disable** because by default its always ON

and the component will not receive any scroll event and it will not hide the header part?

**Comment by Sayandeep-123** [comment]
Yes @fkolar. Thanks.

**Comment by I543348** [comment]
This is related Responsiveness issue

**Comment by droshev** [comment]
fixed with `0.43.9`
