### ISSUE TITLE
Text getting cut in certain screen resolutions while using fdCompact in Multi Input

### ISSUE THREAD

**Issue by vsomsekhar** [SAP/fundamental-ngx#10371]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Text getting cut from bottom in certain screen resolutions while using fdCompact in Multi Input ( alphabets like g, y, etc )

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular - 15
fundamental ngx - 0.43.3

#### If this is a bug, please provide steps for reproducing it.
Go to :- https://deployv2-dev.dev-eu10.build.cloud.sap/lobby
1. Click on the settings tab
2. Click on Governance dropdown
3. Click on Environments
4. Open any environment for environments table
5. Click on share button
6. Click on Authorisation multi input
<img width="370" alt="Screenshot 2023-08-22 at 9 00 29 AM" src="https://github.com/SAP/fundamental-ngx/assets/142768234/ee0c8024-d025-44d4-bd06-addcde4aa16b">

**Comment by droshev** [comment]
this is native and controlled and rendered by the browser
