### ISSUE TITLE
[P1][Sourcing]MultiComboBox Component not getting tokenized for selected data.

### ISSUE THREAD

**Issue by vidworks** [SAP/fundamental-ngx#10377]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
We've have certain use case where we provide the values for MultiComboBox from backend as the user types into the search input.

To achieve this, we wrote a custom class that inherits the `BaseDataProvider` and overrides the `fetch` function. So when the user types in the input field, this function is invoked to get the data from server thru API if the data was not found in the values passed during the MultiComboBoxDataSource initialization in constructor.

_**The issue is that when the user selects the value passed from `fetch` function, the selection is not getting tokenized and the value is not getting emitted in the `selectionChange` Emitter**_

https://github.com/SAP/fundamental-ngx/assets/136386704/3c537d05-3b96-461c-aa82-fcbf12243fa9

As in the above recording, values like "Apple", "Pineapple" were passed in the initial list to the MultiComboBox whereas the values like "Turkey", "Tesla" were passed as the user types in the search from `fetch` function which are not getting tokenized.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest

#### If this is a bug, please provide steps for reproducing it.

1. Create a component to use MultiComboBox and have dataset of 10 values of type Object.
2. Have a custom class that inherits the BaseDataProvider and pass only first 5 values in the constructor.
3. Override the `fetch` function, that will return the remaining values as the use types in search. This is to mimic server call.
4. Search for the value from the remaining dataset and select the value. You'll see it will not get tokenized as shown in the above recording.   

You can also just clone the following repo which has the above setup.
https://github.com/vidworks/table-destroy

#### Please provide relevant source code if applicable.
https://github.com/vidworks/table-destroy/tree/main/src/app/multi-combo-example

http://localhost:4200/multi-combo

#### Is there anything else we should know?
This is an issue for both Core and Platform MultiComboBox. In fact Platform is more stable than Core.

**Comment by vidworks** [comment]
Adding @fkolar for visibility.

**Comment by Aryan9592** [comment]
You are providing links from your forked repository, Are you sure of this? If yes then try keeping it updated with the original one!!

**Comment by fkolar** [comment]
Yes, we discussed this there is even github sample

**Comment by droshev** [comment]
We created a stackblitz https://stackblitz.com/edit/angular-wxdnls?file=src%2Fapp%2Fmulti-combobox-datasource-example.component.html,src%2Fapp%2Fmulti-combobox-datasource-example.component.ts

It is not the standard one

**Comment by droshev** [comment]
fixed with `0.43.6`
