### ISSUE TITLE
[P2][Sourcing][Accessibility][ATL Testing] [Multi-input token]The aria-readonly attribute is not allowed on this SPAN

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10382]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The aria-readonly attribute is not allowed on this SPAN
Note: This issue is common for all the selected list items
<img width="451" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/abeab3fe-15b0-440b-9529-d11344c39336">

![image](https://github.com/SAP/fundamental-ngx/assets/88182358/dfab9d05-8e1d-42f0-bbd2-49b5a028f30b)

#### If this is a bug, please provide steps for reproducing it.
Tested on https://sap.github.io/fundamental-ngx/#/core/multi-input#simple token span

#### Please provide relevant source code if applicable.
Code Snippet:
<span aria-setsize="1" aria-readonly="false" aria-selected="false" class="fd-token" tabindex="-1" role="option"><span class="fd-token__text no-text-select"><span>Astro Laptop 1516</span></span><span aria-label="Deletable" class="fd-token__close" role="button"></span></span>

#### Is there anything else we should know?
Reported by ATL testing

**Comment by droshev** [comment]
@I543348 We would need more information and steps how to reach to the issue

**Comment by droshev** [comment]
@I543348 The agreement is that you provide us with all the input so we can work on the issue.

**Comment by fkolar** [comment]
Adding WIP, @I543348, can you provide more relevant information that are linked to F-NGX components? Are you trying to say that for the CHIPS (token) we use to present selection in the multiinput should not have area-readonly and this should be removed ? 

Just to confirm this is related to multiinput not multiinput combobox right ? 

![Image](https://github.com/SAP/fundamental-ngx/assets/17149942/85d1c8a9-ca16-4b05-9af8-b24e7b03726e)

**Comment by I543348** [comment]
Hi @fkolar , This was reported by ATL , i have asked them to answer the query here.
Thanks.

**Comment by nikolay-kolarov** [comment]
Hi,

The role option does not allow/support aria-readonly according to ARIA standard: https://www.w3.org/TR/wai-aria-1.2/#option
So if it is rendered for MultiInput and MultiComboBox it needs to be removed from both.

Best Regards,
Nikolay

**Comment by sagar7259** [comment]
Hello,

This issue was reported by using our automation tool. The issue generally talks about the attribute 'aria-readonly'. As this is the interactive element the attribute 'aria-readonly' should not be used even its been set to false. Hence the tool is detecting this issue as the attribute 'aria-readonly' is used irrespective to its state.

Regards,
Sagar

**Comment by sagar7259** [comment]
Hi Team,

The issue is no more reproducible, using AMP tool, hence closing the ticket has its fixed.

Regards,
Sagar
