### ISSUE TITLE
[P3.1][Sourcing][Accessibility][ATL Testing][Table][a11y help]On searching any characters with ‘Search’ input field, instead of conveying the total number of search results, whole data within all table cells are being read in one go which is not meaningful.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10381]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On searching any characters with ‘Search’ input field, instead of conveying the total number of search results, whole data within all table cells are being read in one go which is not meaningful.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
tested on https://sap.github.io/fundamental-ngx/#/platform/table/basic#default

#### If this is a bug, please provide steps for reproducing it.
1) Turn on JAWS
2) try to search something using keyboard
3) notice the screenreader 
<img width="442" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/f1e3323a-429e-4337-a37a-c808afe37322">

**Comment by droshev** [comment]
<span style="... to be hiddensomehow" aria-live="polite" >{$number-received-from-the-data-source-filter}</span>

**Comment by I543348** [comment]
Hi @mikerodonnell89 , @droshev , 
Even if we handle this on app side and make the screenreader read the total number of rows on searching , the NGX table will still read all the table content at once , so is there anything that can make it not read everything at once?
I am checking this with UI architects in our team as well.
We shall get back soon.

cc: @sagar7259, @nikolay-kolarov

**Comment by nikolay-kolarov** [comment]
Hi Colleagues,

The table is wrapped with an element with aria-live polite. Not sure why it is there, but it forces the announcement of the whole table when the table is changed. In my opinion it has to be removed. If there is a reasoning to have it there, please provide more info, so that we can discuss it.

![image](https://github.com/SAP/fundamental-ngx/assets/17043004/b3468ef4-4481-416b-9647-6e3bc080133c)

Best Regards,
Nikolay

**Comment by sagar7259** [comment]
Hi Team,

The issue now fixed. Now on searching any characters, JAWS wont read the whole table data at all which is correct as expected.
Hence this can be closed.

Regards,
Sagar
