### ISSUE TITLE
[Sourcing][ATL Testing][Multi-input mobile] The previously selected list items cannot be deselected, instead they are being selected twice which is incorrect causing duplicity.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10385]
#### Is this a bug, enhancement, or feature request?
Bug- functional

#### Briefly describe your proposal.

The previously selected list items cannot be deselected, instead they are being selected twice which is incorrect causing duplicity.
<img width="451" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/f92a3747-4881-4f62-93e0-0e1748c0f218">

#### If this is a bug, please provide steps for reproducing it.
tested on https://sap.github.io/fundamental-ngx/#/platform/multi-input

**Comment by droshev** [comment]
I cannot reproduce the issue


![Image](https://github.com/SAP/fundamental-ngx/assets/4380815/81d50467-feca-401e-8e83-b8af7c57f88d)

**Comment by I543348** [comment]
Hi team,
This is reported by ATL testing.
Could you please check with ATL team?
Thanks.

**Comment by I543348** [comment]
ATL Re-verification needed
