### ISSUE TITLE
[P2][Sourcing][Sep18] `fd-popover` loads content from body even when it is closed

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10392]
#### Is this a bug, enhancement, or feature request?

enhancement

#### Briefly describe your proposal.

It can be reproduced with one or more `fd-popover`. In initial load, even when it is closed, the content in `fd-popover-body` is still loaded. To reproduce this issue, I have multiple `fd-popover` and one customized component with two lifecycle hooks to showcase the issue:

https://github.com/SAP/fundamental-ngx/assets/22842279/049a4ef8-6221-47f7-bae9-86d40326c3dd

As observed here from log, all the customized components are initialized for initial load. Not sure if this is expected behavior, but from what I think, the content should be loaded only when we open the popover. It can be further observed with the following fix on the `datepicker` issue in https://github.com/SAP/fundamental-ngx/issues/10242 since `datepicker` is also using `fd-popover`.

This will cause major perf issue in place we have many usage of popover, especially affecting `fdp-combobox`, `fdp-select`, or `fdp-multi-combobox`...

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

- Create a fd-popover with two-way bindings [(isOpen)]
- Set isOpen initially closed.
- Create a customized component having `ngOnInit` to show log.
- Add multiple `fd-popover`
- Loading browser and observe the logs

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-39lqgd?file=src%2Fapp%2Fpopover-programmatic-open-example.component.html

**Comment by droshev** [comment]
We need to downport to `ng15`

**Comment by g-cheishvili** [comment]
This would be a breaking change for some, because someone might depend on that behavior, for example fetching the data from the server using the current state and not reacting on anything. @droshev should I downport breaking change?

**Comment by g-cheishvili** [comment]
I can create an input on popover-body, call it `reinitContentOnOpen`, and make it default `true`, to match the current behavior. Would that be acceptable? @CSENoni

**Comment by CSENoni** [comment]
@g-cheishvili Sure, that works. Thanks!

**Comment by CSENoni** [comment]
@g-cheishvili Given that if we set it false, `fd-popover` will not load content till we open the popover if that is your intention.

**Comment by fkolar** [comment]
**Expected behavior**:

- The body content should not load ahead of time, even before clicking on the icon/button to show the popover.
- It should load lazily, as the user might not even click on it at all, so preloading the content is unnecessary.

When I consider this, there could be a situation where inside the popover could be a table for example, and you do want to preload it, so we should make it optional. For the majority of the cases, it is not required to load the content ahead of time.

**Comment by g-cheishvili** [comment]
I already addee that feature, struggling with the destruction. Will create PR today or latest monday 🫡

**Comment by CSENoni** [comment]
@g-cheishvili Thanks for the fix. It works fine if we use `fd-popover` component directly. However, I don't think we have a way to add this directive correctly to, for example, `fdp-combobox` or `fdp-multi-combobox`.... Maybe I did something wrong here, I am using ang 16 since downport version has not been released:

![Screenshot 2023-09-05 at 2 24 35 PM](https://github.com/SAP/fundamental-ngx/assets/22842279/bfc1e7aa-30e0-439c-955a-671abbb447e0)

Looking at the `fdp-combobox`, I think it is because it is already using `fd-popover-body` component there, is there anyway to override this?

**Comment by droshev** [comment]
fixed with `0.43.7`

**Comment by CSENoni** [comment]
It is working fine for this component. I create another ticket: https://github.com/SAP/fundamental-ngx/issues/10509 to keep track of related issues. Thanks!
