### ISSUE TITLE
Wizard focus and scrolling issues

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#10391]
When navigating to the next step, the first focusable item in the new step should be focused. Also there seems to be an issue with scrolling with the stacking wizards. When navigating to a new step, the wizard no longer automatically scrolls to the step. And if the user has scrolled down, the wizard will scroll itself to the top

**Comment by MichaelBaySAP** [comment]
When running this Stackblitz from the Wizard Generator Examples, it is not focussing the Input on top for me https://stackblitz.com/edit/angular-j5pk2z?file=src%2Fmain.ts
