### ISSUE TITLE
[Sourcing][a11y help]fdp-table-row adds aria-colindex to TH tags

### ISSUE THREAD

**Issue by sameerchandekar** [SAP/fundamental-ngx#10394]
#### Is this a bug, enhancement, or feature request?
bug 

#### Briefly describe your proposal.
aria-colindex is not a valid attribute for TH tag. fd-table-row adds aria-colindex to th tags

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
Inspect the TH tag for table having fd-table-row on TR tag through browser

#### Please provide relevant source code if applicable.
 ```
 <table  aria-labelledby="some-label">
      <thead fd-table-header >
          <tr fd-table-row >
              <th fd-table-cell >col 1</th>
              <th fd-table-cell >col2</th>
          </tr>
      </thead>
      <tbody></tbody>
</table>
```
#### Is there anything else we should know?
![Picture1](https://github.com/SAP/fundamental-ngx/assets/8946016/14ec7b2b-412a-4118-9001-161952a48318)

**Comment by nikolay-kolarov** [comment]
Hi @sameerchandekar,

This is not correct, aria-colindex is allowed on th/columnheder: https://www.w3.org/TR/wai-aria-1.2/#columnheader
Also when I have run the access assistant on the table sample page I do not get the issue: https://sap.github.io/fundamental-ngx/#/platform/table/basic.
When I test in NU validator and AXE with this snippet I do not get an error:
<table>
     <thead>
         <tr>
             <th  aria-colindex="1" >col 1</th>
             <th  aria-colindex="2" >col2</th>
         </tr>
     </thead>
     <tbody></tbody>
</table>

So I think we can close this as a false positive, unless there is user impact based on this?

Thanks,
Nikolay
