### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by waboqin** [SAP/fundamental-ngx#1041]
#### Briefly describe your proposal.
Uncaught TypeError: Cannot read property 'nativeElement' of undefined
vendor.js:107691 Uncaught TypeError: Cannot read property 'nativeElement' of undefined
    at LabelDirective.push../node_modules/fundamental-ngx/fesm5/fundamental-ngx.js.AbstractFdNgxClass._addClassToElement (vendor.js:107691)
    at LabelDirective.push../node_modules/fundamental-ngx/fesm5/fundamental-ngx.js.LabelDirective._setProperties (vendor.js:108972)
    at LabelDirective.AbstractFdNgxClass (vendor.js:107676)
    at new LabelDirective (vendor.js:108954)
    at _createClass (vendor.js:35854)
    at _createProviderInstance (vendor.js:35828)
    at initNgModule (vendor.js:35761)
    at new NgModuleRef_ (vendor.js:36488)
    at createNgModuleRef (vendor.js:36477)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (vendor.js:38308)
push../node_modules/fundamental-ngx/fesm5/fundamental-ngx.js.AbstractFdNgxClass._addClassToElement @ vendor.js:107691
push../node_modules/fundamental-ngx/fesm5/fundamental-ngx.js.LabelDirective._setProperties @ vendor.js:108972
AbstractFdNgxClass @ vendor.js:107676
LabelDirective @ vendor.js:108954
_createClass @ vendor.js:35854
_createProviderInstance @ vendor.js:35828
initNgModule @ vendor.js:35761
NgModuleRef_ @ vendor.js:36488
createNgModuleRef @ vendor.js:36477
debugCreateNgModuleRef @ vendor.js:38308
push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create @ vendor.js:39012
(anonymous) @ vendor.js:32358
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:399
onInvoke @ vendor.js:31892
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:398
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:158
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ vendor.js:31806
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory @ vendor.js:32356
./src/main.ts @ main.js:10725
__webpack_require__ @ runtime.js:79
0 @ main.js:10739
__webpack_require__ @ runtime.js:79
checkDeferredModules @ runtime.js:46
webpackJsonpCallback @ runtime.js:33
(anonymous) @ main.js:1

it happens when className is 'fd-label'
![image](https://user-images.githubusercontent.com/33823788/61601105-8fc1df80-ac66-11e9-8482-61200521345a.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
   "fundamental-ngx": "^0.7.0",
    "fundamental-styles": "^0.1.0",
#### If this is a bug, please provide steps for reproducing it.
I just update fundamental-ngx from 0.4.5 to 0.7.0
once the syntax has been changed , run npm start, it occurs errors, it seems like relative to fundamental

**Comment by JKMarkowski** [comment]
Hi @waboqin  Would you mind providing template, where this issue occurs ?

**Comment by waboqin** [comment]
Hi @JKMarkowski ,
 I already fix it with the help of my colleges. 
Thanks
