### ISSUE TITLE
[Sourcing][Accessibility][Busy indicator] [P3]The label's color contrast doesnt meet standard ratio

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10412]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The label of busy indicator should be visible properly to the user , just like indicator.
But the color of label is too light and unnoticeable, looks like disabled state
Expectation : the label should be near to the busy indicator animation with a little darker color , at the center of the the content

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-5l37ya?file=src%2Fapp%2Fbusy-indicator-wrapper-example.component.html

<img width="557" alt="Screenshot 2023-08-29 at 11 39 09 AM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/bbc9f964-b7d3-41cb-b0f6-c7ea8922a6c9">

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-5l37ya?file=src%2Fapp%2Fbusy-indicator-wrapper-example.component.html

**Comment by sagar7259** [comment]
@I543348 will be checking this
