### ISSUE TITLE
[P3.2][Sourcing][a11y help][ariaLabel] is not getting recognised for fdp components

### ISSUE THREAD

**Issue by Vijaya-Bharathi-Reddy** [SAP/fundamental-ngx#10413]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When [ariaLabel] is added to the fdp components, it is not getting applied to textarea component.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
1. Go to any fdp component, example textarea
2. Go the html file of it and try passing the [ariaLabel] to the fdp component and check if it is getting added to the actual component or not.

#### Please provide relevant source code if applicable.
![image](https://github.com/SAP/fundamental-ngx/assets/143493234/be9398ac-d2de-4a07-a6f8-740707fc9819)
![image](https://github.com/SAP/fundamental-ngx/assets/143493234/56e999c9-1176-423c-9f55-1a74059f6927)

Please find below the stackblitz source code link for platform-textarea-basic-example.component.html, where the ariaLabel is being added but not recognised by the textarea component.

https://stackblitz.com/edit/angular-1e5g5i?file=src%2Fapp%2Fplatform-textarea-basic-example.component.html

#### Is there anything else we should know?
This bug is causing an issue in accessibility testing.

**Comment by droshev** [comment]
@Vijaya-Bharathi-Reddy you would need to pass `aria-labelledBy` and it will solve your request. `aria-LabelledBy` expects an id to another element containing the label you want the screen reader to read.

stackblitz - https://stackblitz.com/edit/angular-1e5g5i-tqxfgo?file=src%2Fapp%2Fplatform-textarea-basic-example.component.html



![Image](https://github.com/SAP/fundamental-ngx/assets/4380815/f306e1d1-04dd-4a7b-a540-d431267a59ce)
