### ISSUE TITLE
Switch component does not match Visual Core

### ISSUE THREAD

**Issue by TheGui-1** [SAP/fundamental-ngx#10411]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Switch component from [Fundamental Styles](https://sap.github.io/fundamental-styles/?path=/docs/sap-fiori-components-switch--docs#default) & [NGX](https://fundamental-ngx.netlify.app/#/core/switch) does not match current [Visual Core](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915420)

Visual Core:
<img width="899" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/143414885/16a20585-5374-4171-97ff-4b3a29eb4787">

Fundamental Styles:
<img width="1009" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/143414885/acbf8394-3e3e-4d87-8e61-0b6a7b65907f">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Current version

**Comment by droshev** [comment]
https://fundamental-ngx.netlify.app/#/core/switch - there are semantic examples

**Comment by TheGui-1** [comment]
@droshev , the default state should have icons as well, not only the semantic values
