### ISSUE TITLE
Platform thumbnail focus issues

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#10422]
Not sure why this is happening, but when clicking an image in the thumbnail component, seeing this strange focus outline. Happening since at least 0.45.1 if not earlier

<img width="1407" alt="Screenshot 2023-08-29 at 1 51 50 PM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/c0d7925c-521a-4445-86e8-705c66292217">

**Comment by droshev** [comment]
It is a deprecated component - we will drop it soon
