### ISSUE TITLE
[P1][Sourcing][fdp-table][Dev Blocker]: Freeze/unfreeze table columns doest not take effect even with property`[freezable]=true`

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#10424]
#### Is this a bug, enhancement, or feature request?
A bug

#### Briefly describe your proposal.
We'd like to let user dynamically freeze/unfreeze certain table columns depending on their needs

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Current version

#### If this is a bug, please provide steps for reproducing it.
- Create a table
- Define some width value for all table columns
- Set the `freezeColumnsTo=` property to some column name. Here we're setting the freeze boundary up to `Price` column

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-qkfyaa?file=src%2Fapp%2Fplatform-table-freezable-example.component.html,src%2Fapp%2Fplatform-table-freezable-example.component.ts

#### Is there anything else we should know?
In the above StackBlitz example, notice that when we click on the `Price` column which is set to be frozen, the `Unfreeze` menu option is shown, but when we click on it the column is still being frozen.  

Also, in the example, when we click on the `Unfreeze` menu option, the `(columnFreeze)` event emitter does not emit. 

For other table columns passing that `freezeColumnsTo=` boundary, user cannot dynamically toggle freeze/unfreeze table columns even though we have set their property `[freezable]=true`

![Screenshot 2023-08-29 at 4 44 58 PM](https://github.com/SAP/fundamental-ngx/assets/22454655/55878258-5685-4e85-9d9d-25f633798d58)

**Comment by I543348** [comment]
This is dev blocker

**Comment by droshev** [comment]
fixed with `0.43.9`
