### ISSUE TITLE
Radio Button Options numbering read out is not correct

### ISSUE THREAD

**Issue by ravesingh1983** [SAP/fundamental-ngx#10425]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

When we use fd-radio-button component and then tab to go to the options available, the options are always read as 1 of 1 irrespective of which number of option is seclected by the screen reader. It should actually read 1 of 2 for first radio button and 2 of 2 for second radio button

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.43.0-rc.16

#### Please provide relevant source code if applicable.

<img width="908" alt="Screenshot 2023-08-30 at 1 26 11 PM" src="https://github.com/SAP/fundamental-ngx/assets/32221444/6332f50d-312d-48c2-acf9-683e8991867b">

#### Is there anything else we should know?

No

**Comment by nikolay-kolarov** [comment]
Hi @ravesingh1983 ,

Could you please provide a link where you have tested this?
When I test here it is not reproducible:
https://ng-15-downport--fundamental-ngx.netlify.app/#/core/radio

Thanks,
Nikolay

**Comment by droshev** [comment]
not reproducible
