### ISSUE TITLE
[P1][Sourcing][Regression][Date time picker] Only first time the date time picker popover opens with mouse and keyboard , second time it just starts blinking

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10436]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
This is a issue found while evaluating the fix for https://github.com/SAP/fundamental-ngx/issues/10323
The datetime picker popover opens only the first time on page load with both mouse and keyboard.
However , second time onwards, it just starts blinking and forcefully the focus is moving to the input field of date time picker.
User is unable to select the date or time starting second time usage.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15.
core / platform: 0.46.0-rc.7
Able to replicate on : https://deploy-preview-10396--fundamental-ngx.netlify.app/#/core/datetime-picker

#### If this is a bug, please provide steps for reproducing it.
https://deploy-preview-10396--fundamental-ngx.netlify.app/#/core/datetime-picker
[Screen Recording 2023-08-31 at 11.28.10 AM.mov.zip](https://github.com/SAP/fundamental-ngx/files/12482755/Screen.Recording.2023-08-31.at.11.28.10.AM.mov.zip)

#### Is there anything else we should know?
This is a regression as it was working fine before.

**Comment by droshev** [comment]
@I543348 This issue is reported against version core / platform: 0.46.0-rc.7 (which is with Angular 16, not Angular 15). so there is no need to downport it
