### ISSUE TITLE
[P2][Sourcing][Accessibility][Date time picker] [ATL Testing] When navigating through the time picker (hour, minute, second) with the arrow keys, the focused list entry is always output twice by screen reader JAWS

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10437]
#### Is this a bug, enhancement, or feature request?
Bug - Low priority

#### Briefly describe your proposal.
When navigating through the time picker (hour, minute, second) with the arrow keys, the focused list entry is always output twice by screen reader JAWS in both linear reading mode and forms mode

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Tested on https://deploy-preview-10396--fundamental-ngx.netlify.app/#/core/datetime-picker#simple

#### If this is a bug, please provide steps for reproducing it.
Turn on JAWS and Navigate through dates and times using keyboard
![MicrosoftTeams-image (5)](https://github.com/SAP/fundamental-ngx/assets/88182358/2c4a67fd-d358-478e-a052-66e6435b02ab)

#### Is there anything else we should know?
This is reported by ATL testing

**Comment by nikolay-kolarov** [comment]
Hello,

I compared the implementation with UI5 and I do not see major changes (but there it is announced once). In UI5 there is also an element with a live region updated when the hour/minutes are changed, which is styled differently.
Can be seen here: https://ui5.sap.com/1.84.37/#/entity/sap.m.TimePicker/sample/sap.m.sample.TimePicker

One difference is the way how the element is hidden from the screen reader.
As a potential solution, can you try to apply the styles from sapUiInvisibleText css class in UI5 and see if this solves the issue on your side? I tried it with an isolated HTML sample and it worked. But when I did it on the fly in the browser in the sample it did not worked. Still I think the screen reader is doing some initial detection of the live regions when the page is loaded and maybe that is why my later change did not worked. So it needs to be tested in the dev environment.

Best Regards,
Nikolay

**Comment by droshev** [comment]
<img width="600" alt="Screenshot 2023-09-28 at 11 08 20 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/8f6c3210-a5ee-4ebf-ac25-b6797459d994">
<img width="637" alt="Screenshot 2023-09-28 at 11 06 01 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/6a043e5e-6a7e-45fb-a46d-15aeae72061b">

**Comment by mikerodonnell89** [comment]
To elaborate, it is read twice when the user uses the up/down arrow keys to change the set time. Only hearing it once when using the left/right arrow keys to move from hours/mins/sec/period
