### ISSUE TITLE
[P3.1][Sourcing][Accessibility][ATL Testing][Date time picker][a11y help]Screenreader should read the "Hrs" and "Min" in fullform rather than short form 

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10438]
#### Is this a bug, enhancement, or feature request?
Bug- low priority

#### Briefly describe your proposal.
When navigating screenreader should read the "Hrs" and "Min" in full form as "Hours" and "Minutes" respectively as different locale users , and also not clearly understandable by some users
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Tested on https://deploy-preview-10396--fundamental-ngx.netlify.app/#/core/datetime-picker#simple
#### If this is a bug, please provide steps for reproducing it.
Navigate to hours and minutes using JAWS

#### Please provide relevant source code if applicable.

![MicrosoftTeams-image (5)](https://github.com/SAP/fundamental-ngx/assets/88182358/31e30cc3-ed9d-4a42-be66-a5ffaa883e71)

**Comment by droshev** [comment]
@mikerodonnell89 this issue can be combined with #10437
