### ISSUE TITLE
table responsive

### ISSUE THREAD

**Issue by andresfelipe66** [SAP/fundamental-ngx#1044]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.

I ilke to implement web site with first mobile principle but the fd-table component is not working now.. ¿how is the plan with the responsive?

**Comment by JKMarkowski** [comment]
Hi @andresfelipe66 take a look at the last example of table usage. There is presented the way, how to use tables with responsive layouts. [Documentation](https://sap.github.io/fundamental-ngx/table)

**Comment by andresfelipe66** [comment]
Hi @JKMarkowski ... SAP Fiori manage differents kinds of presentation based in the device. For example with SAPUi5 the tables in size L are converted in Lists in size S. Is is planning the same behavior for this Framework?  

Thank you

**Comment by JKMarkowski** [comment]
Hi @andresfelipe66 as far as I know, there are no plans for that.

**Comment by droshev** [comment]
WE will use this issue as a wrapper to our MVP responsive table. It includes:

- [Fiori 3 table - add toolbar](#2435)
- [Fiori 3 table - search](#2436)
- [Fiori 3 table - toolbar CRUD operations](#2437)
- [Fiori 3 table - sorting/filtering via column header](#2438)
- [Fiori 3 table - show/hide columns](#2439)
- [Fiori 3 table - column drag and drop](#2440)
- [Fiori 3 table - pagination](#2441)

**Comment by droshev** [comment]
We have the table responsice
