### ISSUE TITLE
[P3.1][Sourcing] `fdp-multi-combobox` fires multiple times after value is selected

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10457]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

After value is selected/deselected in `fdp-multi-combobox`, `selectionChange` emits multiple times:

https://github.com/SAP/fundamental-ngx/assets/22842279/63b95f53-d899-4142-873c-e14fa0458433

As observed from the log:

- After value is selected, it emits 4 times.
- After value is deselected, it emits 2 times.

Expectation is that it should emits only one time.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15
0.43.8

#### If this is a bug, please provide steps for reproducing it.

- Have `fdp-multi-combobox` with selectionChange.
- Select a value and observe the log.
- Deselect a value and observe the log.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-9jp2kz-7cgxzk?file=src%2Fapp%2Fmulti-combobox-loading-example.component.ts

#### Is there anything else we should know?
It can be low/medium priority since it is not a blocker but on our application side we have to handle it carefully especially with api call.

**Comment by CSENoni** [comment]
@droshev @fkolar I think this is no longer WIP since pr is created for this issue.

**Comment by fkolar** [comment]
> @droshev @fkolar I think this is no longer WIP since pr is created for this issue.

yes, you are right
