### ISSUE TITLE
[P4][Sourcing] fdp table does not emit any event after filter is applied through p13n dialog

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#10453]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
fdp table component should emit an event after filter is applied to the table rows through p13n dialog component. This will give app developers a suitable hook to apply additional logic after filter application.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.46.0-rc.11

**Comment by skaquib123** [comment]
@snigdhaman Can you please provide an example explaining in detail what exactly the issue is? It will help me understand how you are using the component and what is the issue.

**Comment by mikerodonnell89** [comment]
The table does emit a change event when a filter is applied, whether from the basic table or the personalization dialog: https://github.com/SAP/fundamental-ngx/blob/ng-15-downport/libs/platform/src/lib/table/table.component.ts#L1620

`<fdp-table #table [dataSource]="source" (filterChange)="filterChange($event)">...</fdp-table>`


```
    filterChange(event: any): void {
        console.log('filterChange event fired!');
        console.log(event);
    }
```
