### ISSUE TITLE
WIP: [Sourcing] [P2] Approval flow component does not show watchers but only show approvers.

### ISSUE THREAD

**Issue by nehabeke** [SAP/fundamental-ngx#10485]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
When I create a workflow for a task with a node with a watcher team assigned, we can only see approvers not watchers, could you please also show watchers in the this control?

There is inability to add watchers in the guided sourcing but we can add watchers in the legacy app for which I have provided a screenshot. Please help us having watchers same as of legacy app in guided sourcing also while creating a workflow.

<img width="567" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/14968987/48118281-c189-4472-9541-132683bd8b0d">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current version
@fundamental-ngx/core - "version": "0.43.0"
@fundamental-ngx/platform - "version": "0.43.0",

**Comment by fkolar** [comment]
Please try to provide some sample. you can use existing [one from demo](https://sap.github.io/fundamental-ngx/#/platform/approval-flow) and start from there.

**Comment by nehabeke** [comment]
Hi, I have to discuss regarding this with our PM. Once I get any updates from him, I will give you more details.

**Comment by nehabeke** [comment]
Please hold on till I discuss with our PM.
