### ISSUE TITLE
[Sourcing] In MultiCombobox Component, "more" feature doesn't work for dynamically added values

### ISSUE THREAD

**Issue by vidworks** [SAP/fundamental-ngx#10495]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In MultiCombobox Component, `more` feature doesn't work for dynamically added values. When the user selects enough dynamically added values to make `more` button appear and clicks on it, the dropdown doesn't display the selected values. But it works for selected values that are part of component initialization. 

As seen in the video below, the first few selected values were added dynamically and when clicked on `more`, the dropdown doesn't appear. Whereas when the value `apple` is selected, the dropdown appears when clicked on `more`. Thats because `apple` was added as part of component initialization.

https://github.com/SAP/fundamental-ngx/assets/136386704/9a0007f6-c52e-4ca5-8657-b766879f6a55

 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-wxdnls-grfzxd?file=src%2Fapp%2Fmulti-combobox-datasource-example.component.ts

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-wxdnls-grfzxd?file=src%2Fapp%2Fmulti-combobox-datasource-example.component.ts

#### Is there anything else we should know?
Looks like the code is comparing selected values with values that were passed during component initialization.
https://github.com/SAP/fundamental-ngx/blob/017c6b4dcc23b1adb440f27cd35cb86a1a832511/libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts#L265

This might the fix for this issue, not sure.
<img width="1743" alt="Screenshot 2023-09-06 at 7 30 14 PM" src="https://github.com/SAP/fundamental-ngx/assets/136386704/f2860a7b-f75e-4cbd-89e2-fc7ae46c7e2b">

**Comment by droshev** [comment]
@vidworks in your case with 30,000 items the design guidelines recommend using value help dialog
