### ISSUE TITLE
<fd-datetime-picker>: Localization Issue

### ISSUE THREAD

**Issue by c5360788** [SAP/fundamental-ngx#10500]
![hardcoding_forwardAuction_zh_CN_2](https://github.com/SAP/fundamental-ngx/assets/144129077/ceabf455-ff6e-42c9-bb86-589808b3c79d)
![hardcoding_time_eu](https://github.com/SAP/fundamental-ngx/assets/144129077/44bf9437-051e-40d2-94a0-4cbc34af1511)
![hardcoding_time_zh_CN_rfp](https://github.com/SAP/fundamental-ngx/assets/144129077/f8d7950c-0537-4090-92bb-7db17e861891)
![hardcoding_time_zh_CN](https://github.com/SAP/fundamental-ngx/assets/144129077/80aef406-ad68-4bab-8e31-09f8b2e9bc55)
![open picker_ru](https://github.com/SAP/fundamental-ngx/assets/144129077/65646b8d-784d-4d5f-89b5-0b35de0b535f)
Is this a bug, enhancement, or feature request?
Bug
Briefly describe your proposal.
Hardcoded text (Hrs, Min, Open picker ) & buttons (OK, Cancel) in date and time picker are not localized.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

**Comment by droshev** [comment]
the issue has been addressed
