### ISSUE TITLE
[WIP][P2][Sourcing] Combobox preloads item list 

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10509]
#### Is this a bug, enhancement, or feature request?

enhancement

#### Briefly describe your proposal.

Following https://github.com/SAP/fundamental-ngx/issues/10392, we cannot lazy-load item list from `fdp-combobox` and `fdp-multi-combobox`. The directive `fdPopoverBody` does not work for those components when I try to customize the template. I notice that these components are already using `fd-popover-body` components:

```
<div class="fdp-multi-combobox">
    <ng-container [ngTemplateOutlet]="controlTemplate" *ngIf="mobile"></ng-container>

    <fd-popover
        *ngIf="!mobile"
        additionalBodyClass="fd-popover-custom-list fdp-multi-combobox__list-container"
        (isOpenChange)="popoverOpenChangeHandle($event)"
        [isOpen]="isOpen"
        [triggers]="[]"
        [disabled]="disabled"
        [fillControlMode]="fillControlMode"
    >
        <fd-popover-control>
            <ng-container>
                <ng-container *ngTemplateOutlet="controlTemplate"></ng-container>
            </ng-container>
        </fd-popover-control>
        <fd-popover-body [style.width.%]="!autoResize && 100">
            <ng-container *ngTemplateOutlet="listTemplate"></ng-container>
            <ng-content></ng-content>
        </fd-popover-body>
    </fd-popover>
</div>
```

Can you also provide us a way to lazy-load list from `fdp-combobox` and `fdp-multi-combobox`?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15
0.43.7

#### If this is a bug, please provide steps for reproducing it.

Not a bug.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-9jp2kz-ufwzjp?file=src%2Fapp%2Fcombobox-templates-example.component.html

**Comment by fkolar** [comment]
**Expected behavior**

These components that are meant to deal with large datasets (combo, multicombo, ..), they need to load data lazily by default and I would not even have any other option for these components as it does not make much sense.

**Comment by rvamudha** [comment]
Some tables and many pages in GS are using this component and the current behavior will cause some perf issue

**Comment by droshev** [comment]
> **Expected behavior**
> 
> These components that are meant to deal with large datasets (combo, multicombo, ..), they need to load data lazily by default and I would not even have any other option for these components as it does not make much sense.

Actually they are not meant to load big set of data https://experience.sap.com/fiori-design-web/v1-110/multi-combobox/

**Comment by CSENoni** [comment]
We can have multiple of these components in a page (ofc with limit). We don't want the page to preload n*200 items, for example. Expectation is that it should only load the list when user open the dropdown and only from the combobox they interact with.

**Comment by droshev** [comment]
Wasn't this solve with the latest discussions with @fkolar ?

**Comment by CSENoni** [comment]
@droshev with my latest discussion with @fkolar (few weeks ago), we still see this as an issue. After that, I am not aware of how he think of this issue lately if there was current discussion on this. I agree that a combobox per design will contain max 200 items, but we can have multiple combobox in a page and some pages of our GS currently has it. So worst case scenarios, we still preload more than 200 items.
In addition, we already have this https://github.com/SAP/fundamental-ngx/issues/10392 implemented. It would be helpful if we can have a binding to lazy load combobox. Thanks!

**Comment by droshev** [comment]
@CSENoni in #10392 it is a feature for a generic popover, which is not an opinionated component. Having lazy loading for combobox will make the logic very complicated. Maybe a solution for could be https://fundamental-ngx.netlify.app/#/core/combobox#custom-item - where you will have the freedom to do anything you want

**Comment by CSENoni** [comment]
Core is also using the `fd-popover-body` as a container of the list that including itemTemplate:

```
<ng-template #desktopTemplate>
    <fd-popover
        additionalBodyClass="fd-popover-custom-list"
        [class.fd-combobox-full-width]="isSearch"
        [isOpen]="open && displayedValues && displayedValues.length > 0"
        (isOpenChange)="isOpenChangeHandle($event)"
        [fillControlMode]="fillControlMode"
        [scrollStrategy]="_repositionScrollStrategy"
        [focusTrapped]="true"
        [triggers]="triggers"
        [disabled]="disabled || readOnly"
        [maxWidth]="640"
        [closeOnOutsideClick]="closeOnOutsideClick"
    >
        <fd-popover-control>
            <ng-container *ngTemplateOutlet="controlTemplate"></ng-container>
        </fd-popover-control>
        <fd-popover-body [hidden]="!displayedValues.length">
            <ng-container *ngTemplateOutlet="listTemplate"></ng-container>
            <ng-content></ng-content>
        </fd-popover-body>
    </fd-popover>
</ng-template>
```

What can be tried is to load/destroy the template at parent level. If it is too complex to implement, I will close now since we really have not faced any issue using this component in GS.
