### ISSUE TITLE
Form Generator: Do not show redundant default placeholder values

### ISSUE THREAD

**Issue by colinjoy** [SAP/fundamental-ngx#10510]
#### Is this a bug, enhancement, or feature request?

UX Enhancement

#### Briefly describe your proposal.

For the form generator, when no explicit value is provided for the `placeholder` property, the label is re-used automatically and shown as placeholder. This is an anti-pattern as it add visual noise without adding any information. It would be better to not output a redundant placeholder when no explicit value is set.

**Comment by N1XUS** [comment]
Hello @colinjoy. Thank you for your ticket. We have option called `useMessageAsPlaceholder` that should do exactly as you describe. For more convenience, developers can pass this option to `PlatformFormGeneratorModule.withConfig()` module when imported to application
