### ISSUE TITLE
fdp-select component does not show default value on load

### ISSUE THREAD

**Issue by vikalpgautam** [SAP/fundamental-ngx#10536]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When we are loading UI with an fdp-select component, the component does not display initial/default value. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
15.2.0

#### If this is a bug, please provide steps for reproducing it.
Created an HTML page with fdp-select component. Assign a list of values for the dropdown and then assign an initial/default value to this component. Load the page in browser. The component does not display the initial value. Only when one value is selected, its that value displayed.

**Comment by g-cheishvili** [comment]
https://stackblitz.com/edit/angular-5uxlxs?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fplatform-select-semantic-state-example.component.ts,src%2Fapp%2Fplatform-select-semantic-state-example.component.html

I could not reproduce what you're saying both on ng16 and ng15 branches
