### ISSUE TITLE
[Sourcing]<fdp-column>: the sort option strings are not localized.

### ISSUE THREAD

**Issue by C5341784** [SAP/fundamental-ngx#10537]
#### Is this a bug, enhancement, or feature request?
bug
 
#### Briefly describe your proposal.
1.   In fdp-table, when the column is sortable. The Sort option strings are not localized.
![sort_ascending_hardcoding](https://github.com/SAP/fundamental-ngx/assets/144683607/bc034a6b-fd54-4747-9d19-4e25f9b2b66f)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental-NGX (core, platform, cdk, i18n): 0.43.7

#### If this is a bug, please provide steps for reproducing it.
1. Create a fdp-table.
2. add fdp-column with sortable property as true
3. observes sort option on clicking the column header.

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table/api

#### Is there anything else we should know?
Attached screenshot above.

**Comment by droshev** [comment]
to be covered with https://github.com/SAP/fundamental-ngx/issues/10137
