### ISSUE TITLE
Focus on the Busy Indicator inside the fd-dialog-body component

### ISSUE THREAD

**Issue by shawchandankumar** [SAP/fundamental-ngx#10547]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Inside the fd-dialog-body component, the initial focus is put on the busy indicator.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version - 15.2.4
fundamental-ngx version - 0.43.3

#### If this is a bug, please provide steps for reproducing it.

`https://spa-registry-dev-consumer-eu-applicationdevelopment-dev.cfapps.sap.hana.ondemand.com/lobby`

Go to the above link
Under the All Projects section there are 6 columns.
Under the versions columns, if any projects have an entry then click on the drop down button and click on the more option which is on the right side (3 dots). It has 2 options `promote` and `delete`. Clicking  on the `promote` option will open an dialog body which will show a busy indicator for some seconds and it is focused. The focused part is the part which is unwanted.

#### Please provide relevant source code if applicable.
N/A

#### Is there anything else we should know?
When we put any textarea or an input inside the fd-dialog-body component then that input or textarea is also focused, that means any first focusable element is getting focused initially which should not happen.

<img width="960" alt="Screenshot 2023-09-14 134349" src="https://github.com/SAP/fundamental-ngx/assets/74846322/e3d39bb3-e22a-4c3e-99f9-9c017d74049e">

![Screenshot (6)](https://github.com/SAP/fundamental-ngx/assets/74846322/2178a3b7-0611-4d8d-a16d-ac83c78719e6)

**Comment by droshev** [comment]
@kalo2711  Can you check whether you can reproduce it with https://ng-15-downport--fundamental-ngx.netlify.app/ and write steps how to do so? thanks

**Comment by droshev** [comment]
@nikolay-kolarov Do you think what the reporter says is correct? If you have active input why should we prevent the focus going there?
