### ISSUE TITLE
[P1][Sourcing] [fdp-table][design needed]: After rearranging column order using p13n dialog, Expand arrow stays inside first column of the table

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#10545]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The `>` arrow is should not still be inside the original column.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Observed with NG15 for `0.43.9`

#### If this is a bug, please provide steps for reproducing it.
- Create a tree table
- Enabled the `p13n` dialog
- Open the `p13n` dialog by clicking on the Settings button on table toolbar, and move the first column down the row
- Observed that the `>` indicating tree structure still remains at the first table column

https://github.com/SAP/fundamental-ngx/assets/22454655/40edc731-2189-4354-b579-b024f7c0256b

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-fqpyom?file=src%2Fapp%2Fplatform-table-tree-example.component.html

#### Is there anything else we should know?

Not sure if this is as per Fiori UX design, but does not look pleasing to end-users.

**Comment by droshev** [comment]
@yixuan-liu there is not a bug. You have offered a personalization dialog where the user can rearrange the columns. Whether the data makes sense is another story, but this is controlled by the application.
According to the design all the columns should be available in the dialog.
If you want to hide that, I think Frank offered you a solution for that.

**Comment by yixuan-liu** [comment]
Thanks @droshev. But I noticed that in UI5 example here the very first column containing the hierarchical structure is hidden inside the `p13n` dialog. Is there way we can customize this `p13n` dialog to hide that very first column?

https://sapui5.hana.ondemand.com/sdk/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable.smarttreetable

![Screenshot 2023-09-25 at 10 28 25 AM](https://github.com/SAP/fundamental-ngx/assets/22454655/139cecb5-d133-454e-b9b2-1d678cbe3188)
