### ISSUE TITLE
Platform package deprecation components/API

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#10557]
#### Is this a bug, enhancement, or feature request?
List all components/features/API in Platform that need to be deprecated

**Comment by g-cheishvili** [comment]
My opinion:
Everything except Table, VHD, Variant management, entire layouts section, utilities section, smart filter bar, settings generator, and upload collection(even though it's deprecated).
What I'm saying is that the distinct features should be kept and anything that is already in the core should go. If the amount of features that are added with the platform counterpart is very small, we should provide the same feature set with the core and get rid of the platform one.

**Comment by g-cheishvili** [comment]
Icon tab bar should definitely be moved into the Core
The list needs reassessment and maybe unification.
