### ISSUE TITLE
[P2][Sourcing] [fdp-table]: Cannot increase column header width after setting `[freezable]=true` on that column

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#10552]
#### Is this a bug, enhancement, or feature request?
A bug

#### Briefly describe your proposal.
We'd like to let user still adjust the table column width freely even after freezing that column

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Observed with current NG16 release and NG15's version `0.43.9`

#### If this is a bug, please provide steps for reproducing it.
- Set the `width` property for all table columns `<fdp-column>`
- Set `[freezable]=true` and `[noWrap]=true` for any table column
- Before unfreezing that column, user can expand or shrink the width of that column with no restriction
- Now click on that column header, and click the `Freeze` menu option
- Shrink that column to a much smaller width, and then try to expand that to the original width at before freezing the column
- Notice that the width cannot be expanded back. It get stuck at a certain point.

Recording:

https://github.com/SAP/fundamental-ngx/assets/22454655/f35779fe-2cc1-483d-aad0-cab109961198

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-9xw7hs-rx7p13?file=src%2Fapp%2Fplatform-table-freezable-example.component.html

**Comment by mikerodonnell89** [comment]
This is intentional - it is done to ensure that, when a table contains frozen columns, the user cannot resize columns such that other columns will be permanently hidden and inaccessible via scroll due to the large frozen column.

https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts#L318

**Comment by mikerodonnell89** [comment]
It looks like UI5 behaves in the case I described above, where the width of the frozen columns is greater than the width of the whole table, the columns do not freeze at all. So I think we should go for that, and I'll reach out to UX and confirm if this is the desired functionality
