### ISSUE TITLE
Component Bug: Dynamic Page Sub-Header Style

### ISSUE THREAD

**Issue by rebecagm** [SAP/fundamental-ngx#10550]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The fd-dynamic-page-subheader style **should not** present the **shadow** when (1) there is the fd-tab-list below, and (2):
            [collapsible]="false"
            [pinnable]="false"
            [collapsed]="false"

![sub-header-false](https://github.com/SAP/fundamental-ngx/assets/144914282/30ebf37a-9996-4802-baef-b88d5fa04333)

That is how it should look, but **without the custom css**:

![custom-sub-header](https://github.com/SAP/fundamental-ngx/assets/144914282/7e1a8994-cb57-4f92-ad40-ccae936b84a9)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Current

#### If this is a bug, please provide steps for reproducing it.
See screenshots above

**Comment by InnaAtanasova** [comment]
hi @rebecagm and @pawelkarwat , I added a fix for this issue in https://github.com/SAP/fundamental-ngx/pull/12443
It will be soon available in the latest rc version. Let me know if I missed something. Thank you!
