### ISSUE TITLE
ScrollBar issue in Horizon themes for scroll Spy

### ISSUE THREAD

**Issue by Soumadeep1993** [SAP/fundamental-ngx#10579]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
The scrollbar of scroll spy in horizon themes are not compliant.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.43.3

#### If this is a bug, please provide steps for reproducing it.
The scrollbar in scroll spy can be seen in fundamental ngx documentation page.

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/core/scroll-spy

**Comment by droshev** [comment]
this is just a plain html example. There is a separate component for that https://sap.github.io/fundamental-ngx/#/core/scrollbar
