### ISSUE TITLE
Platform Table: fixed Header scrolls away in Mozilla Firefox

### ISSUE THREAD

**Issue by muellerDana** [SAP/fundamental-ngx#10577]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In Mozilla Firefox wenn you open a lots of items in the [Advanced Tabel](https://sap.github.io/fundamental-ngx/#/platform/table/advanced) and scroll through the table, the header gets scrolled away, even if the settings fixed is true.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Noticed it in Angular 16.2.4 and Fundamentals 0.45.1, was also reproducible in the  Example which uses Angular 16.1. and Fundamentals 0.43

#### If this is a bug, please provide steps for reproducing it.

Open some of the elements in the table, so that lots of elements are included inside the table.
If you scroll down, there is a point where the header gets scrolled out of the view.

#### Please provide relevant source code if applicable.

Reproduced it in the [stack blitz example](https://stackblitz.com/edit/angular-r59qtj?file=package.json).

#### Is there anything else we should know?

We only noticed the problem in Mozialla Firefox, in Google Chrome there it works fine.

**Comment by JoramM** [comment]
I have the same issue and I was also able to reproduce it with the Stackblitz example from above.

![image](https://github.com/SAP/fundamental-ngx/assets/6030513/dd3def4e-2181-4fb0-b6d9-8916ec9f2bc1)

**Comment by N1XUS** [comment]
Not reproducible with latest version of Firefox and fundamental-ngx: https://stackblitz.com/edit/wj4pkw?file=src%2Fmain.ts,src%2Fapp%2Fadvanced-scrolling-example.component.ts
