### ISSUE TITLE
Enhancement to combobox control: onblur and data property

### ISSUE THREAD

**Issue by carlostekken** [SAP/fundamental-ngx#1057]
enhancement

expose onblur event and property to specify showing property from data object

0.8.0

We want to implement the feature ourselves. onblur is require to trigger other control actions when the user selects the element in the list. currently the only way to specify the display property is through dataFn in typescript. it would be more flexible if a property is exposed for this. For example we want to map the display property in the control template since this can change dinamically

**Comment by MattL75** [comment]
Not sure what it is you're trying to accomplish. Could you clarify please? Maybe with a code example of what you envision this change would be?

**Comment by carlostekken** [comment]
I am closing this issue since we are implementing this using angular reactive forms.
