### ISSUE TITLE
[P1][Sourcing] [multi-input]: Selected items are not checked in the popever when using objects

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#10572]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

Since application can pass an **any** object as a `valueFn`, it creates a problem both on the usage side as well as multi-input itself.

this part 
`displayedOptions.forEach((c) => (c.isSelected = selected.findIndex((d) => d?.value === c.value) > -1));`

fails to evaluate the **.isSelected**, when working with Rest API, the `selected` is one instance and `dropdownValues` item that is just selected can be difference instance from what is fetched from API - the same object different instances. 

Since application provides list of objects in the `dropdownValues` and gets back only strings, there needs to be additional logic and crossref calls to lookup correct objects, which might impact performance.

**Comment by droshev** [comment]
should be addressed with #10341

**Comment by I543348** [comment]
Hi @droshev , @g-cheishvili  could you pls confirm the release version for this issue.?
I tried finding it in releases with 10572 but no luck.
Pls help here.

Thanks much.

**Comment by g-cheishvili** [comment]
> Hi @droshev , @g-cheishvili  could you pls confirm the release version for this issue.?
> I tried finding it in releases with 10572 but no luck.
> Pls help here.
> 
> Thanks much.

It should be in 0.43.11 and in last 10-15 RC versions at least

**Comment by I543348** [comment]
Hi @g-cheishvili , we are still able to replicate this issue in 0.43.11 version 
pls check and follow below steps:
1) open the list , select "Mike" , "Frank"
2) now close the list
3) search for "Mi" you get to see "Mike" without checkbox selection  - this is an issue originally reported
4) Coz of point 3 , user is also able to again select the already checked token "Mike" - now user sees duplicate tokens with same name.

Both points 3 and 4 are original issues,
pls check in stackblitz - https://stackblitz.com/edit/angular-f4elgf-qaext9?file=package.json,src%2Fapp%2Fmulti-input-displaywith-example.component.ts,src%2Fapp%2Fmulti-input-displaywith-example.component.html

**Comment by g-cheishvili** [comment]
@I543348 What you're missing in your example is `optionItemIdentifier="label"`, we've discussed this with @fkolar, when you have a object, which does change it's reference through the lifecycle of the component, it needs some primitive identifier, to properly distinguish between items. If you add the `optionItemIdentifier` input, then you fix it

**Comment by I543348** [comment]
Thanks @g-cheishvili , I modified my example and it works fine now.
