### ISSUE TITLE
If 'tr' is an Angular component and it has the 'fdkRepeat' input, then verify that it is a part of an @NgModule where this component is declared

### ISSUE THREAD

**Issue by jyoti1507** [SAP/fundamental-ngx#10591]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
https://sap.github.io/fundamental-ngx/#/core/table
Skeleton loading section throwing error
table-skeleton.component.html:11 NG0303: Can't bind to 'fdkRepeat' since it isn't a known property of 'tr' (used in the 'TableSkeletonComponent' component template).
1. If 'tr' is an Angular component and it has the 'fdkRepeat' input, then verify that it is a part of an @NgModule where this component is declared.
2. To allow any property add 'NO_ERRORS_SCH
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.45.1
#### If this is a bug, please provide steps for reproducing it.
bug from NGX component

**Comment by droshev** [comment]
@jyoti1507 We are not able to reproduce it.
