### ISSUE TITLE
Height of the popover is not according to the content.

### ISSUE THREAD

**Issue by shawchandankumar** [SAP/fundamental-ngx#10602]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
When we open the popover at different positions the height should be according to the content. But currently the height of the popover is not dependant on the content. It gets altered according to the placement of the popover

Below are the screenshots.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version - 15.2.4
fundamental-ngx version - 0.43.3

#### If this is a bug, please provide steps for reproducing it.
`https://spa-registry-dev-consumer-eu-applicationdevelopment-dev.cfapps.sap.hana.ondemand.com/lobby`
Open the URL and in any project click on the members section of the Members column on different scrolls, where the no of members is more than 2.

#### Is there anything else we should know?

<img width="451" alt="Screenshot 2023-09-27 151513" src="https://github.com/SAP/fundamental-ngx/assets/74846322/7b15783b-2c19-4c3b-8711-ab0a5b17bd61">
<img width="374" alt="Screenshot 2023-09-27 151615" src="https://github.com/SAP/fundamental-ngx/assets/74846322/cd7b0f0b-3da7-4c04-af4d-9f7cb5cf5d84">
<img width="365" alt="Screenshot 2023-09-27 151659" src="https://github.com/SAP/fundamental-ngx/assets/74846322/c0e449b5-727e-4b4d-9555-3cd0ae538950">
<img width="384" alt="Screenshot 2023-09-27 151749" src="https://github.com/SAP/fundamental-ngx/assets/74846322/a0819281-7ff0-40f1-aa95-b59ff0e1d016">
<img width="353" alt="Screenshot 2023-09-27 151834" src="https://github.com/SAP/fundamental-ngx/assets/74846322/b3358fc0-902a-45c5-83e4-4fb147dc8a14">

**Comment by droshev** [comment]
@shawchandankumar Can you create a small stackblitz with this issue?

**Comment by droshev** [comment]
@shawchandankumar can you update the ticket?

**Comment by droshev** [comment]
closing it as there no update from the author
