### ISSUE TITLE
Icons not rendering properly in horizon theme

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#10603]
#### Briefly describe your proposal.
When we load the theme in horizon, the icons which we use as a glyph gets switched back to icons in quartz theme. This issue is observed in latest version of fundamental NGX and Theming Service as well. We are also using Theming Service as provided by fundamental ngx to change themes. I have also added screenshots which describes this issue.

When we load the application in horizon theme, these is how the icons load :-

![image](https://github.com/SAP/fundamental-ngx/assets/102856000/61d4df08-92b6-4c1b-b1c8-4025372a1756)

After few seconds, the icons gets switched back to normal icon in quartz light theme :-

<img width="156" alt="Screenshot 2023-09-28 at 12 31 35 AM" src="https://github.com/SAP/fundamental-ngx/assets/102856000/de7c852d-b3b6-4a54-81ec-eedf678ccf53">

#### Which versions of Angular and Fundamental Library for Angular are affected? 

NGX Version -> **0.43.10**
Theming-service -> **11.6.8**

#### If this is a bug, please provide steps for reproducing it.

Use any icons like inbox, refresh, download from the list if icons provided in fundamental ngx. Load the application in horizon theme. Initially these icons in correct way how its supposed to come for horizon theme. But after a while, these icons gets switched back to icons in quartz light theme. 

#### Is there anything else we should know?

Issue observed in latest version of fundamental-ngx and theming-service.

**Comment by N1XUS** [comment]
Hello @sameesheikh25. Could you please provide an example code of how you initialize theming for your app? Do you use `.withConfig()` method for `ThemingModule` or `provideTheming()` function in your app?

**Comment by N1XUS** [comment]
Closing since the issue relates directly on how theme is being set in https://github.com/SAP/fundamental-ngx/issues/10700
