### ISSUE TITLE
Dialog is not closed on esc key

### ISSUE THREAD

**Issue by nikola-miletic** [SAP/fundamental-ngx#10604]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Dialog should be closeable when  `escKeyCloseable` is set to `true`

#### If this is a bug, please provide steps for reproducing it.
1. Set `escKeyCloseable` to `true` 
2. Open dialog
3. Click on esc key
4. Nothing happen

https://github.com/SAP/fundamental-ngx/assets/43137517/658ee570-d445-47b4-92e1-ea86654380ef

**Comment by droshev** [comment]
I wasn't able to reproduce it

**Comment by nikola-miletic** [comment]
Hi @droshev ,

I have made example on stackblitz, you can take a look:
https://stackblitz.com/edit/angular-kcxkgq?file=src%2Fapp%2Ftemplate-based-dialog-example.component.ts

when the flag `escKeyCloseable: true`, I expect to be able to close the dialog on esc key.

What I have noticed is that when the flag `focusTrapped: false` this is not working, but when the flag `focusTrapped: true` it will works because the focus in already on the dialog.

I should be able to close dialog no matter on focus.

**Comment by N1XUS** [comment]
@droshev I would argue that this is a bug: We have cases when user can open stacked dialogs, and if we would listen on esc key for the entire document, pressing esc would automatically try to close all dialogs.

**Comment by droshev** [comment]
it works as Denis explained. no issue here.
