### ISSUE TITLE
[P3.1][Sourcing][Accessibility][ATL testing][Table]: Sort popover in table has wrong key usage for focus

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10615]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
As soon as user opens sort column popover for a column , automatically the first menu of the popover "Sort Ascending" has to be focussed. But currently focus is not trapped inside and user has to press extra tab key to move the focus explicitly to this popover and then use up or down arrow keys to move between the menu items which is wrong.
Expectation: User opens the sort popover and automatically the first menu item has to receive the focus and user can then only use up / down arrow keys to operate

<img width="1522" alt="Screenshot 2023-09-29 at 11 17 41 AM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/51eecb50-e7f8-44c1-906c-262b4f0ec07c">

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
replicable on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic

**Comment by nikolay-kolarov** [comment]
Hi Colleagues,

The issue is valid. Please have a look at this as a reference: https://ui5.sap.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Sorting

Best Regards,
Nikolay

**Comment by mikerodonnell89** [comment]
Further context - this is an issue with initial focus in popovers in general
