### ISSUE TITLE
[P3.1][Sourcing][Accessibility][ATL Testing][Table]: search icon or synchronize icon buttons dont have tooltips

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10612]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
hover on search icon or synchronize icon and see there are no tooltips

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
core / platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
hover on search icon or synchronize icon and see there are no tooltips

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic replicable here

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes , this is reported by Accessibility test lab team

**Comment by nikolay-kolarov** [comment]
Hello,

There is a conscious UX decision not to have tooltips on the icons inside the input fields.
Can be seen in UI5 as well:
https://ui5.sap.com/#/entity/sap.m.SearchField/sample/sap.m.sample.SearchField

So with this I think we can close this issue?

Thanks,
Nikolay

**Comment by I543348** [comment]
With the explanation given by @nikolay-kolarov . i think we are good here.
@sagar7259  pls check and confirm if you have any other inputs.

**Comment by sagar7259** [comment]
@nikolay-kolarov  thanks for your clarification, this ticket can be closed has we have an explanation here.
