### ISSUE TITLE
[P3.2][Sourcing][Accessibility][ATL Testing][Table]: Irrelevant information read on checking / unchecking checkbox in table as "Click to select"

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10616]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When focus is on multi-selectable rows table , the screenreader is reading "Click to Select" and also "press enter or space" to select or deselect which is irelevant, here "click to select" doesnt make sense for a disabled user.
pls keep anyone description

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
replicable on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#multiple-row-selection

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Reported by ATL team

**Comment by nikolay-kolarov** [comment]
Hi Colleagues,

This is the same as in UI5. There is an explicit announcement that for selection the Spacebar needs to be pressed.
And also the tooltip contains the info "Click to (de)select".
So it needs to be further aligned with UX. @droshev  - Could you please move this further to UX for discussion?

Nevertheless, I am not sure if this deserve to be treated as an issue, as it is rather a tooltip that can be optimized.

Best Regards,
Nikolay

**Comment by I543348** [comment]
@sagar7259 pls help and confirm if this can be closed

**Comment by sagar7259** [comment]
@droshev please have a look into the below screenshot
![image](https://github.com/SAP/fundamental-ngx/assets/143692208/97dda771-9fc7-461c-80a6-5d47d7c60c93)

Here I have highlighted 2 check boxes one with tooltip 'Select all' and the other with tooltip 'Click to select'
But the speech read for both the elements are different

Speech for 'Select all' check box:
"Check box not checked select all
To check press space bar"

Speech for 'Click to select' check box:
"Click to select
row 2 of 124 to select row press spacebar
Click to select"

Here the expectation is that it should read the UI type "Check box" for all the rows and the information "Click to select" is a tooltip which is already reading and its correct.

Regards,
Sagar

**Comment by I543348** [comment]
As we discsused with UX and accessbility experts. 
Pls help reopen the issue accordingly.
below is the summary for this issue

>>> … "press enter or space to select or deselect"”
 
If this comes from the screen reader based on the control role (tutor text how to use control) then nothing to comply or to do.
 
If this comes from the UI5 then please remove.

the tooltip should be removed from the Fundamental-NGX table for this is also the plan on the UI5 tables.

cc: @droshev , @sagar7259

**Comment by I543348** [comment]
The tooltip text "Click to select or deselect" is still not removed , pls help to get this reopened. after the validation we had raiseda similar issue https://github.com/SAP/fundamental-ngx/issues/10817 may be one of them can be reopened.
cc: @mikerodonnell89
