### ISSUE TITLE
[P2][Sourcing][Accessibility][ATL testing][Multi-input]: Show All link is listed as list item and wrong UI type read

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10625]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Show All link is listed as list item and wrong UI type read, rather it should be a link.
This apeears when we search for a text in multi-input and there are lot of matching records, among that the last record is the "Show All"list item.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Multi-input search and dropdown list

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
reported by ATL team

**Comment by droshev** [comment]
The topic is in discussion for some time and there isn't solution yet.
The solution: make `Show All` features optional.

**Comment by mikerodonnell89** [comment]
> The topic is in discussion for some time and there isn't solution yet. The current solution: make `Show All` feature optional.

There is the `showAll` input making this optional. But I think it would be helpful to add `role="button"` to the show all link to make the purpose more clear to users (and I think of this functionality as more of a button than a link)

**Comment by sagar7259** [comment]
Hi Team,

The issue is now fixed. The 'Show all' button is no more listed with the list items and as clarified by @mikerodonnell89 this is a button and not a link, hence the same is being read.
Therefore this ticket can be closed.

Regards,
Sagar
