### ISSUE TITLE
[P3.2][Sourcing][Accessibility][ATL testing][Multi-input]: Value help button label or description has two sentences read

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10627]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
If developers are sending "title" attibute to multi-input then we dont really need other sentence in the screenreader context.
Pls keep this sentence only if title is null or blank or not being sent by developers or consumers. This is causing too much information to users issue which is not needed.
<img width="408" alt="Screenshot 2023-09-27 at 3 13 24 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/33c27261-ffe3-45eb-b6f3-d21ccd9aeaa8">

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
NG: 15
platform: 0.43.x

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
reported by ATL

**Comment by droshev** [comment]
The button in the multi-input
<img width="1172" alt="Screenshot 2023-10-02 at 9 47 08 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/dc30902e-1281-4f67-a9ae-fbbd2ce6712f">

`aria-hidden="true"`
`tabindex=-1`
, remove the tooltip
Similar to #10613
