### ISSUE TITLE
[P2][Sourcing][Accessibility][ATL testing][Multi-input] : flat list is open for first time- no screenreader announcement is made

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10622]
#### Describe your proposal.
When user starts typing in multi-input , a dropdown or list opens , the disabled user is not aware that such a list is open at the bottom of the control where user can traverse and select between matching list items.
This is huge gap in usage of the control.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Multi-input 

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
reported by ATL

**Comment by droshev** [comment]
Live region needs to be added and include that missing information

**Comment by nikolay-kolarov** [comment]
Hi,

You can use this sample as a reference: https://ui5.sap.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInput
If you focus the field, you will not receive info for navigation.
If you type "No", and there are suggestions available, you will receive info how to navigate in them with the arrow keys. Also if a tokenizer is available, you will get the announcement - to press left to go to the tokenizer.
If you continue typing further this is not announced (to not bother the user with duplicated announcements).
Also an additional announcement is made about the found results, which is useful for the users.

Best Regards,
Nikolay

**Comment by sagar7259** [comment]
Hi Team,

The example and explination provided by @nikolay-kolarov is totally correct and its what expected. But here in NGX component of 'Multi input' this is not the case.
When the user enter random text for example: "Ar", there will be 2 search results available and the first item is automatically selected.
But the screen reader just reads the selected list item and nothing more. 
Here no information about search results is read.
No total count of search results is read.
All these needs to be fixed.

https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/multi-input

@rvamudha please reopen this ticket.

Regards,
Sagar

**Comment by droshev** [comment]
@mikerodonnell89 Can you check what @sagar7259 wrote?
