### ISSUE TITLE
[P2][Sourcing][Accessibility][ATL testing][Multi-input]: "X more" button has no context in multi-input , appears as link but read as button

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10620]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
In multi input control, after selecting more number of tokens we get "X more" blue color link , JAWS doesnt announce what is this "X more" without being informing the user that its a part of control Multi-input.
Also, it looks like a link but screenreader reads as button , which i wrong UI type

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
replicable on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/multi-input#simple

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
reported by ATL

**Comment by droshev** [comment]
the `x more` should not be focusable

**Comment by sagar7259** [comment]
Hi Team,

As not the focus is removed from 'X more' button, this ticket can be closed has this ticket is no more valid.

Regards,
Sagar
