### ISSUE TITLE
Theme not working properly

### ISSUE THREAD

**Issue by jyoti1507** [SAP/fundamental-ngx#10628]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
Theme not working properly from last 5 days there are some issue in theme. With latest compilation we are getting
  --sapField_Background: #fff; 
before it was   --sapField_Background: #eff1f2;
This is example of sap horizion them. Same issue with other theme. This is causing accessibility issue as after this before and after hover background color is samme
#### Can you handle that on the application side
no
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
    "@fundamental-ngx/core": "^0.45.1",
    "@fundamental-ngx/i18n": "0.45.1",
    "@fundamental-ngx/platform": "^0.45.1",
    "@sap-theming/theming-base-content": "^11.4.0",

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
create a angular project using theme

**Comment by droshev** [comment]
@jyoti1507 the values for the variables are coming from theming-base-content, like the one you mentioned https://github.com/SAP/theming-base-content/blob/4c41296da62474895e5ab91ddc29accc20b0e776/content/Base/baseLib/sap_horizon/css_variables.css#L465

What exactly is the contrast issues? in which components?
