### ISSUE TITLE
[P3.2][Sourcing][Accessibility][ATL testing][List with group header]: Header is included in total list items count

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10664]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
The platform list with group header is having some problem when screenreader is reading the total count , the header is also counted as list item.
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/list#group-header

Expectation: screenreader should not include the header of the list as list item or option.
Few hints: "li" has been added with role=option under "fdp-list-group-header"
I believe this might done to make header also traverse using up / down arrow keys for reachability, but this might be a root cause for screenreader reading it wrongly

<img width="1759" alt="Screenshot 2023-10-05 at 4 20 49 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/8d334b0a-3268-4b43-ad44-9c209b97b44f">

#### Can you handle that on the application side
Not really, as fdp-list and its structure depends on F-NGX library we cannot access child elements

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

angular 15
core / platform: 0.43.9
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/list#group-header

#### Please provide relevant source code (if applicable).
```
<fdp-list [role]="'listbox'" id="recentsearchid">
 <fdp-list-group-header   class="recentSearches_color" [groupHeaderTitle]="recentSearchLbl"></fdp-list-group-header> 
  
  <fdp-standard-list-item 
      *ngFor="let item of items"
      [role]="'option'"
      [title]="item.title || item.name"
      class="recentSearches_color_value"
      (click)="actionedRow($event,item)"
      (keydown.enter)="actionedRow($event,item)">
  </fdp-standard-list-item >
</fdp-list>
```
#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
This issue has been reported by ATL testing for sourcing.

**Comment by I543348** [comment]
@sagar7329 pls provide your inputs.

**Comment by sagar7259** [comment]
Within a list the group header should not be included when the count is read and this separation should also be conveyed to the users as there is a group header present within a list. 

For example if there are 2 different groups within the list and each group has 3 items. Now the count for first group should be read as "1 of 3", 2" of 3" and 3 of 3" and again the next group count should start from 1.

Regards,
Sagar

**Comment by nikolay-kolarov** [comment]
Hello @sagar7259,

There are two statements in your last comment:
- That the group headers should not be added as part of the total count. I agree to this and there was recently a change in UI5 in this direction.
- That in each group the total count needs to be only the count of all items within the group. For me this is wrong and it is not implemented like this in UI5. Could you please give more info where have you seen this and why you think it is required to be this way?

As a reference, here is the list grouping implementation in UI5: https://ui5.sap.com/#/entity/sap.m.List/sample/sap.m.sample.ListGrouping

Keep in mind that with ARIA 1.2 the usage of group in list was removed, so there might be further changes in the structure.

Thanks,
Nikolay

**Comment by sagar7259** [comment]
Hi @nikolay-kolarov,

The second point of your comment is just a recommendation or a suggestion from my side, because the list can also be implemented in 2 ways,

1)  It can be a simple list with Grouping & Context Menu where all the lists are considered as a whole with respect to count excluding the group headers.
https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListGrouping

2)  It can also be implemented as a navigation list where the group headers can be expanded/collapsed to access their respective list items, here the count will be separate for each and every group.
https://sapui5.hana.ondemand.com/#/entity/sap.tnt.NavigationList/sample/sap.tnt.sample.NavigationList

Either way the group headers should be excluded with respect to list count.

Regards,
Sagar

**Comment by nikolay-kolarov** [comment]
Hi @sagar7259 ,

Thanks for the details. Case 2 that you pointed out is implemented as a "tree" and respectively gives other announcements and semantic. So let`s focus on the "list" implementation.

@droshev , @InnaAtanasova  and team: You can have a look at https://ui5.sap.com/#/entity/sap.m.List/sample/sap.m.sample.ListGrouping to see how at the moment the groups are excluded from the count. There is a future change coming with regards to the grouping and ARIA 1.2, but there is still not clarity how this will affect the structure, so for now I suggest to make it in the same way as UI5 and we can change it in future once we have more clarity.

Best Regards,
Nikolay
