### ISSUE TITLE
Implement BTP Horizontal Navigation component

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#10670]
- [x] Update fd-styles to the latest design (e.g. two-click area) - https://github.com/SAP/fundamental-styles/pull/4997
- [ ] Bring the Horizontal Navigation to the library under BTP package

**Comment by droshev** [comment]
waiting for the design accessibility spec to be signed off

**Comment by droshev** [comment]
closed as it is deprecated. Once a new final spec is available and the component will be used we can implement it
