### ISSUE TITLE
datepicker focus trap issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1068]
1. open https://deploy-preview-1048--fundamental-ngx.netlify.com
2. go to datepicker
3. click on the first datepicker to open
4. tab twice so the focus ends up on the month
5. press `space` to open the month menu
6. tab 3 times so the focus goes on the current month down
7. use the arrows to focus on another month
8. press `space` then the focus is out of the datepicker

Simiar issue:
open the datepicker by clicking on the calendar icon
- if you keep tabbing then the focus trap stays in the calendar
- if you press `shift` + `tab` then the focus goes out

**Comment by MattL75** [comment]
A lot of stuff in this issue is expected behaviour 😅
