### ISSUE TITLE
[WizardGenerator]: items hidden by when lose choices, value & default after being shown

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#10695]
Bug: The following [Stackblitz ](https://stackblitz.com/edit/angular-thk1pk-piljsk?file=src%2Fapp%2Fwizard-generator-condition-example.component.ts)shows how the choices & a value is dynamically loaded into a select control initially hidden by when. After the control gets shown, the choices and the value is lost. This only happens for controls hidden by when, in the moment that they are "unhidden", i.e. shown. 

The resolution to this bug should be to maintain any data in the formItem that has previously been assigned and not lose it after showing it with when. 

1. Open the  [Stackblitz ](https://stackblitz.com/edit/angular-thk1pk-piljsk?file=src%2Fapp%2Fwizard-generator-condition-example.component.ts)
2. Click on Show Payment Method
3. Navigate to the Payment step
4. Observe that the select shows no data, despite data was loaded in code line 69

**Comment by MichaelBaySAP** [comment]
The bug only occurs for some controls. Sometimes the value in an input is not removed when it is shown(unhidden), sometimes it is.

**Comment by MichaelBaySAP** [comment]
It also occurs when default on the formItem is modified at runtime.

**Comment by droshev** [comment]
closing it as it won't be needed anymore
