### ISSUE TITLE
[Sourcing] fdp-table toolbar has additional space between separator during toolbar overflow scenario

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#10707]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
The spacing between toolbar options should be symmetrical on both sides between the starting and end separator icon
![Screenshot 2023-10-12 at 12 04 52 PM](https://github.com/SAP/fundamental-ngx/assets/12679774/ec15e764-4b8e-440f-8f0d-e13513f962c0)

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - 15.2.0
F-NGX - 0.43.9

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Use fdp-table component with fdp-table-toolbar (shouldOverflow should be true) and fdp-table-p13-dialog component (with fdp-table-p13n-filter support). Decrease the table width to trigger overflow scenario and observe the spacing between the filter and settings buttons

#### Please provide relevant source code (if applicable).
![Screenshot 2023-10-12 at 12 25 39 PM](https://github.com/SAP/fundamental-ngx/assets/12679774/90bd9f43-3b6c-4bca-969e-de1747a1a465)
![Screenshot 2023-10-12 at 12 25 45 PM](https://github.com/SAP/fundamental-ngx/assets/12679774/2857c2ff-7c89-4838-a078-03471149444a)

**Comment by droshev** [comment]
@kalo2711 Can you try to reproduce the scenario?

**Comment by droshev** [comment]
That is expected behaviour as the overflow menu goes in the opposite side
