### ISSUE TITLE
[Sourcing][a11y help] using fd-icon component tooltip text is being read 3 times with JAWS tool

### ISSUE THREAD

**Issue by Vijaya-Bharathi-Reddy** [SAP/fundamental-ngx#10708]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
Using fd-icon component for adding a tooltip, the tooltip text is being read 3 times when testing it with JAWS tool.
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
In the Windows OS, install JAWS version 2023 and check the fd-icon component with glyph="question-mark" and role="tooltip"
#### Please provide relevant source code (if applicable).
<img width="380" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/143493234/d60218f7-0ede-421a-b760-054ec904a5e6">

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-qdorsn?file=src%2Fapp%2Finline-help-styled-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes
#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes
#### Is there anything else we should know?
No

**Comment by droshev** [comment]
@Vijaya-Bharathi-Reddy Can you re-test with the latest version?

**Comment by droshev** [comment]
@Vijaya-Bharathi-Reddy any update?
