### ISSUE TITLE
[Sourcing][Accessibility][P.2] fd-list stopped reading out position after upgrade from Ngx 0.36.3 to the latest 

### ISSUE THREAD

**Issue by itsnode** [SAP/fundamental-ngx#10715]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15.2.1 and Ngx 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Tested the fd-list read out using screen reader Jaws 2023, for Angular 14 and Ngx 0.36, the fd-list is reading out the position correctly. See screenshot.
<img width="1791" alt="Screenshot 2023-10-13 at 10 08 26 AM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/3d68e315-4773-4e18-8675-747af65f4bf3">

Code test under:
https://stackblitz.com/edit/angular-zh1zus-mqg6ki?file=src%2Fapp%2Fshellbar-basic-example.component.html

After upgrade to Ngx 0.43 with Angular 15, the position is not reading out any longer.
Also the Group header is not reading out.
<img width="256" alt="Screenshot 2023-10-13 at 9 28 11 AM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/538e84b6-afe8-47d4-bad6-a005164cc3dd">

<img width="256" alt="Screenshot 2023-10-13 at 9 26 05 AM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/fba0fd02-ef0c-4423-a32a-a38109941780">

Code to test:
https://stackblitz.com/edit/angular-usdxnt-3xuto3?file=src%2Fapp%2Flist-example.component.ts,src%2Fapp%2Flist-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes, talked with SAP accessibility team, this is a bug.
#### Is there anything else we should know?
We see after Ngx upgrade to 0.43 and Angular upgrade to 15, the fd-list-item  role changed from "listitem" to link for <a> element. This causing screen reader stopped reading out the position.

**Comment by skaquib123** [comment]
Hello @itsnode I can't open the stackblitz link and i tried the same on fundamental library website got this result
<img width="1072" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/110972289/970a466a-f41d-4f98-b907-a15543d2204d">

**Comment by itsnode** [comment]
> Hello @itsnode I can't open the stackblitz link you provided and I tried the same on fundamental library website got this result <img alt="image" width="1072" src="https://user-images.githubusercontent.com/110972289/280967628-970a466a-f41d-4f98-b907-a15543d2204d.png">

@skaquib123, thanks for help look into the issue. Please test the JAWS screen reader on windows, not Voice Over on Mac. Tsting over Fundamental library website is fine, but I tried stackblitz links, both are still working.

**Comment by itsnode** [comment]
@droshev Please help downport to Ngx 0.43.11 for minor version upgrade. thanks.
