### ISSUE TITLE
[Combobox] Traditional Chinese Characters are causing issues in input field of combobox

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#10710]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
The input field is not working well in Combobox when Chinese characters (Pinyen - Traditional) are entered. 

Open this stackblitz link to find information on how to reproduce the issue on an example with a combobox field: https://stackblitz.com/edit/fundamental-issue-10710?file=src%2Fapp%2Fcombobox-example.component.html

Here is also a recording that shows the issue: 
[Fundamental-NGX Example - StackBlitz.webm](https://github.com/SAP/fundamental-ngx/assets/26272656/1ad74050-275c-4522-9cd1-6964fdfa0e21)

#### Can you handle that on the application side
The issue is reproducible on the application side. It is also a customer-facing issue.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

    "@angular/core": "16.1.0",
    "@fundamental-ngx/cdk": "0.43.0-rc.4",
    "@fundamental-ngx/platform": "0.43.0-rc.4",
    "@fundamental-ngx/core": "0.43.0-rc.4",

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Yes, see the above description.

#### Please provide relevant source code (if applicable).
See the above description.

#### Please provide stackblitz example(s).
See the above description.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Not relevant

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
It is a customer-facing issue.

**Comment by droshev** [comment]
We fix it in the latest (and to 0.43.x if @zaheral says so)

**Comment by zaheral** [comment]
0.43.x and the latest Fundamentals version would be great 
CC: @droshev
