### ISSUE TITLE
Fundamental Platform Table: can't hide border for platform table 

### ISSUE THREAD

**Issue by snowqu** [SAP/fundamental-ngx#10729]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
should have option to hide all the borders.

#### Can you handle that on the application side
No.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15.2.9
Fundamental: 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
It's a bug

1.https://sap.github.io/fundamental-ngx/#/platform/table/basic
2.try playground example
3.enable noHorizontalBorders, noVerticalBorders, noBorders, noOuterBorders, noBodyBorders
4.There is still a vertical border before the last column, and there is a horizontal border under header. 
It shouldn't display any border now. 

<img width="2529" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/6847549/b74e05e1-5e4f-4bfb-831f-33af9a57ea39">

#### Please provide relevant source code (if applicable).
it could reproduce from official playground example. 

#### Please provide stackblitz example(s).
it could reproduce from official playground example. 

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
No

**Comment by droshev** [comment]
@kalo2711 Can you try to reproduce the issue?

**Comment by kalo2711** [comment]
The issue is still there, the last vertical and first horizontal borders still appear in this configuration.
