### ISSUE TITLE
[P3.1][Sourcing][Accessibility][Table][ATL testing]: Expand all / collapse all buttons are read as toggle but its state not conveyed

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10737]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Expand all / collapse all buttons i the table are read as toggle button, however when one is pressed ,  its state not conveyed by JAWS.
This is reported by ATL testing team

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
core/ platform: 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) Open JAWS
2) Move the focus to expand all button
3) press enter and all the tree table nodes will. be expanded
4) Note that the next time expand all button gets the focus, notice that whether its pressed or released is not read since its read as toggle button
Expectation: Either make it read as simple button and not toggle button then we are good.Coz we have 2 buttons for expand collapse each

**Comment by nikolay-kolarov** [comment]
Hi @I543348,
Hi @droshev,

Where can I test/reproduce this? Could you please give a link and point me to the concrete table example?

Thanks,
Nikolay

**Comment by I543348** [comment]
Hi @nikolay-kolarov , you can use this example https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree for testing
