### ISSUE TITLE
[P1][Sourcing][Responsiveness] Multiple tabs are shown selected in tab-list

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#10741]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
On rendering the fd-tab asynchronously, multiple fd-tabs are shown selected (blue underline) as shown in the below screenshot.
<img width="400" alt="Screenshot 2023-10-17 at 4 27 52 PM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/214bfcf0-2b8e-4c1c-8731-b429357de707">
 
But only the first tab should be selected (by default) and others should not be selected.

#### Can you handle that on the application side
No, it cannot be handled from application end. Tried multiple things.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: "15.2.0"
Fundamental Library: "0.43.11"

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. fd-tab-list is being used
2. Render fd-tabs asynchronously( using setTimeout, api calls etc.) inside fd-tab-list

#### Please provide stackblitz example(s).
Editor Link : https://stackblitz.com/edit/angular-ugca8x?file=src%2Fapp%2Fdynamic-page-tabs-example.component.ts
Application Link: https://angular-ugca8x.stackblitz.io

#### Did you check the documentation and the API?
Yes

**Comment by I543348** [comment]
This is a release blocker.

**Comment by Sayandeep-123** [comment]
The fix provided is not working as expected. The proper tab is not getting selected on addition of tabs asynchronously.

In the screenshot, we can see that the tab content and tab selected is not matching.

<img width="558" alt="Screenshot 2023-10-19 at 9 23 15 AM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/a5c7a469-47c5-4a15-96f8-d1e733f97281">

**Comment by I543348** [comment]
To be reopened based on above comments

**Comment by Sayandeep-123** [comment]
editor URL - https://stackblitz.com/edit/angular-ugca8x?file=src%2Fapp%2Fdynamic-page-tabs-example.component.html
application URL - https://angular-ugca8x.stackblitz.io
