### ISSUE TITLE
Stop Popover auto placement

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#1074]
#### Is this a bug, enhancement, or feature request?
Between Bug and Enhancement

#### Briefly describe your proposal.
We are using the Shellbar with custom popovers. Our issue is that the placement of the popover is changing when there is not enough place.
Here is a screenshot of our popover:
![image](https://user-images.githubusercontent.com/26272656/62196180-d5c12680-b37d-11e9-850c-1302b0925e82.png)

We defined it with the placement "bottom-end". But when the hight of the screen gets lower then it will be changed to "top-end" (see below screenshot). Therefore, the popover goes out the screen. We want to stop this behaviour.
BTW. it just happens if the screen hight is too low. If the screen width is too low then the placement will not be changed.

![image](https://user-images.githubusercontent.com/26272656/62196168-cd68eb80-b37d-11e9-8c18-fa0785676cdb.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
"@angular/core": "^7.1.3"
"fundamental-ngx": "^0.7.0"

#### Please provide relevant source code if applicable.
```
<fd-popover placement="bottom-end" noArrow="false">
    <fd-popover-control>
         ........
    </fd-popover-control>
    <fd-popover-body>
         ........
    </fd-popover-body>
</fd-popover>
```

**Comment by MattL75** [comment]
See the [Popper.js](https://popper.js.org/popper-documentation.html). Options can be passed to the `options` input of the popover component. I believe what you're looking for is the (flip)[https://popper.js.org/popper-documentation.html#modifiers..flip] property.

**Comment by zaheral** [comment]
Yes man, it worked for me like that:
![image](https://user-images.githubusercontent.com/26272656/62296784-1d27df80-b470-11e9-9845-07bb3e30b67b.png)

Thank you

**Comment by MattL75** [comment]
No problem! Glad to help out
