### ISSUE TITLE
BTP Components refactoring

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#10750]
Vertical Nav

- [x] investigate whether we can apply structural directives; 
- [x] Update fd-styles to the latest design (e.g. two-click area)
- [ ] add an example with a `spacer`
- [ ] move CSS to fd styles
- [x] refactor it to data driven
- [ ] communicate with the lobby and maybe support them with the transition
- [x] write unit tests
- [x] improvement for snapped vertical nav (with the mouse): click on nav item and move away the mouse from it. The expected behaviour is that the title disappear: 
<img width="72" alt="Screenshot 2023-10-23 at 2 48 40 PM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/55aeb5fd-d96a-43ec-a80c-48672aed3e19">(Disclaimer) if the user is using the keyboard then the focused item keeps the title too 
<img width="147" alt="Screenshot 2023-10-23 at 2 49 48 PM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/d0127f8e-d6dd-462f-84b5-0f5e8b24017f">

 Tool Header

- [x] refactor action buttons
- [x] space between the buttons (in styles it is fine) 
<img width="365" alt="Screenshot 2023-10-23 at 8 49 22 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/3af01815-b6e2-4c29-95ee-cd3e26f09a4f">
<img width="287" alt="Screenshot 2023-10-23 at 8 49 16 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/ddc2b0c9-d3d3-4dce-abb9-9fb596c4317a">

- [ ] #11016
- [ ] review with Paige

**Comment by N1XUS** [comment]
Closing this issue since all nav-related tasks are completed. Tool header has it's own dedicated task
