### ISSUE TITLE
ComboBox component should return object for formControl value.

### ISSUE THREAD

**Issue by carlostekken** [SAP/fundamental-ngx#1075]
#### Currently ComboBoxComponent with dropdownValues is synchronizing the selected text value to the formControl. For example if I have the following structure assigned to the comboBox:

  dropdownValues:  = [
       {
      id: 111,
      description: 'XXX'
    },
   {
      id: 222,
      description: 'YYY'
    }
  ];

When the value is selected the formControl is assigned with the description (assuming displayFn returns description)

this make sense to reflect the value selected in the input text However it does not make sense for the formControl value since there we need to have the whole object in order to get the "id" attribute.

I am aware you are returning the whole object in the "selected" property however this will not work with a reactive approach since selected attribute is not bonded with any formControl.

Find the example for the enhancement described here:

https://stackblitz.com/edit/angular-xmns77

#### 0.8.0

https://stackblitz.com/edit/angular-xmns77

Reactive Forms implementation value subscription requires the whole object no the the display value.

**Comment by MattL75** [comment]
That's a good point. I'm not really a fan of complicating the component's usage within reactive forms, but there's really no other way to solve this issue that I can see.
