### ISSUE TITLE
<fdp-column> : Localization issues 

### ISSUE THREAD

**Issue by wangwanlin** [SAP/fundamental-ngx#10786]
#### Is this a bug, enhancement, or feature request?
bug
#### Describe your proposal.
Freeze is not localized 
<fdp-column name="more"
                key="item"
                align="center"
                label="Actions"
                i18n-label="Actions @@arcRfxPricingItems_ActionsColumnLabel"
                [width]="'80px'"
                [noWrap]="true"
                [sortable]="false"
                **[freezable]="true"**
<img width="1122" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/13607996/17eaac18-88c3-48b2-95cc-22ddf172f8a3">

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
NGX: 0.43.9

**Comment by N1XUS** [comment]
Hello @wangwanlin.
Freeze/Unfreeze is translatable with these i18n keys:
`platformTable.headerMenuFreeze`, `platformTable.headerMenuEndFreeze` and `platformTable.headerMenuUnfreeze`.
More info on how you can change the translations available here: https://fundamental-ngx.netlify.app/#/i18n/changing-translations
