### ISSUE TITLE
Drop down is still open after one item is selected

### ISSUE THREAD

**Issue by yingzhou03** [SAP/fundamental-ngx#1078]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
0.8.0-rc.22

#### If this is a bug, please provide steps for reproducing it.
You can use this example code that was copied from https://sap.github.io/fundamental-ngx/dropdown to reproduce the defect:

`<fd-popover>
    <fd-dropdown-control [compact]="true">Compact Dropdown</fd-dropdown-control>
    <fd-popover-body *ngIf="menu1 && menu1.length">
        <fd-menu>
            <ul fd-menu-list>
                <li fd-menu-item *ngFor="let option of menu1">
                    {{option.text}}
                </li>
            </ul>
        </fd-menu>
    </fd-popover-body>
</fd-popover>`

**Comment by MattL75** [comment]
The dropdown pattern is completely un-opinionated and handles very little on the functionality side. Implementation here is left to the user. 

If you are looking for something simple to use but less flexible, you can wait until 0.9.0 is released and make use of the incoming `Select` component.

If you want to proceed with the popover/dropdown pattern, you can listen for a selected item and when one is fired you can switch the `isOpen` input of the popover component to `false`.
