### ISSUE TITLE
The aria-colindex attribute is not allowed on this TH and TD

### ISSUE THREAD

**Issue by dhivya910** [SAP/fundamental-ngx#10794]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
This is regarding one of the accessibility bug. The aria-colindex attribute is not allowed on this TH and TD. This is something framework is adding by its own.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
angular - 15.2.4
fundamental ngx - 0.38.2

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
<img width="952" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/67852219/143a7af1-e969-4de1-9e28-e42adf4e22f1">

![image](https://github.com/SAP/fundamental-ngx/assets/67852219/6ad15adb-fc8e-4aac-8a90-5a6c62dffeae)

#### Please provide stackblitz example(s).
<img width="690" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/67852219/ee37ea38-47e5-4884-b8eb-7c8b9e90f50a">

#### Did you check the documentation and the API?
Yes

**Comment by droshev** [comment]
duplicated with [this](https://github.com/SAP/fundamental-ngx/issues/10394) and it is coming from the tool
