### ISSUE TITLE
[Accessibility] fd-list the list items does not support arrow key navigation if the item is referenced in template

### ISSUE THREAD

**Issue by itsnode** [SAP/fundamental-ngx#10793]
#### Is this a bug, enhancement, or feature request?
bug
#### Can you handle that on the application side
no
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
latest version
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
see example code under
https://stackblitz.com/edit/angular-zh1zus-zt1rth?file=src%2Fapp%2Fshellbar-basic-example.component.html,src%2Fapp%2Fshellbar-basic-example.component.scss

#### Please provide relevant source code (if applicable).
I see under ListComponent, the _focusItems is query under ContentChildren directive. This will not work for any list item referenced under template.  Maybe should use viewChildren instead.

Based on
<img width="705" alt="Screenshot 2023-10-24 at 2 10 11 PM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/a3493801-7f21-4db3-91c3-dc8a85e6981c">

export class ListComponent implements ListComponentInterface, ListUnreadIndicator, OnInit, AfterContentInit, OnDestroy, ```
AfterViewInit {
    /** @hidden */
    @ContentChildren(ListFocusItem)
    private _focusItems: QueryList<ListFocusItem>;
```

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-zh1zus-zt1rth?file=src%2Fapp%2Fshellbar-basic-example.component.html,src%2Fapp%2Fshellbar-basic-example.component.scss

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 

#### Did you check the documentation and the API?

#### Did you search for similar issues?

#### Is there anything else we should know?

**Comment by N1XUS** [comment]
@itsnode Hello. `ViewChildren` will not work since this decorator is used to query items that are inside the  component`template` rather than projected content. Another thing is that why do you actually need to use ng-template with the list? From your example it's ok if you just place list item inside ng-container, and it will work as it should

**Comment by itsnode** [comment]
> @itsnode Hello. `ViewChildren` will not work since this decorator is used to query items that are inside the component`template` rather than projected content. Another thing is that why do you actually need to use ng-template with the list? From your example it's ok if you just place list item inside ng-container, and it will work as it should

@N1XUS thanks for quick response. The example code is just for reproducing the issue. We have a User account menu features(see screenshot). The multi-level menus are dynamically generated based on API data. It was implemented using nested ng-template with ngTemplateOutlet/ngTemplateOutletContext(see snippet just for one section). There are many business logics around it, very hard to refactor.

Since ViewChildren will not work, would it possible to refresh _focusItems with displayed list items under AfterViewInit() ?
Any suggestion for a quick fix or any workaround(maybe from application level) since we need meet Accessibility certification deadline this year.

<img width="1790" alt="Screenshot 2023-10-25 at 8 58 49 AM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/a4969229-5267-4d09-9a9e-a6eb939d6881">
<img width="1276" alt="Screenshot 2023-10-25 at 9 09 15 AM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/ab3b56af-f629-4fc8-b31c-95447650f7c8">

**Comment by N1XUS** [comment]
Hello @itsnode. Thank you for your response. Now the issue is more clear to us. I think for your case it's more preferable to use [Menu Component](https://fundamental-ngx.netlify.app/#/core/menu) rather than List. Here's an example of the dynamic menu items that are stored in ng-template https://stackblitz.com/edit/8prqtg?file=src%2Fapp%2Fmenu-with-submenu-example.component.ts,src%2Fapp%2Fmenu-with-submenu-example.component.html

**Comment by itsnode** [comment]
> Hello @itsnode. Thank you for your response. Now the issue is more clear to us. I think for your case it's more preferable to use [Menu Component](https://fundamental-ngx.netlify.app/#/core/menu) rather than List. Here's an example of the dynamic menu items that are stored in ng-template https://stackblitz.com/edit/8prqtg?file=src%2Fapp%2Fmenu-with-submenu-example.component.ts,src%2Fapp%2Fmenu-with-submenu-example.component.html

@N1XUS Thanks for your suggestion. We have requirements of having separator for sections and also section headers(which seems supported). Does menu support placement to the left side(see our screenshot, we have a long menu, requires to be placed on left site and centered in height) ? Also can submenu being triggered only by keyboard/or mouse click only? Currently hover over will immediately trigger submenu which is a changing behavior to user. 

https://stackblitz.com/edit/8prqtg-s1uxe2?file=src%2Fapp%2Fmenu-with-submenu-example.component.ts,src%2Fapp%2Fmenu-with-submenu-example.component.html
<img width="558" alt="Screenshot 2023-10-26 at 8 34 51 AM" src="https://github.com/SAP/fundamental-ngx/assets/48496287/9a31d267-c841-4daf-8f10-20c05e1f2ede">

http://10.76.116.116:31060/ for a quick demo if you have access to SAP internal network.

**Comment by droshev** [comment]
@alexhristov14 can you check whether this is still valid?
