### ISSUE TITLE
One day shift in database on formatted dates

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#1080]
#### Is this a bug, enhancement, or feature request?
Bug ?
#### Briefly describe your proposal.
My formatted dates (dd/mm/yyyyy) are correctly displayed in the date-picker but are displayed with one day less in the database (TimeZone ?)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 7
Fundamental NGX 0.5.6

#### If this is a bug, please provide steps for reproducing it.

Set up a date-picker in dd-mm-yyyy format

#### Please provide relevant source code if applicable.

I used the DateFormatDashes class from the date-picker documentation

#### Is there anything else we should know?
Tested in combination with an internationalized date-picker

**Comment by JKMarkowski** [comment]
It's for sure about  timezone. We abandoned usage of JS Date object in new date-picker, which is in 0.9 version.

**Comment by JohnHavok** [comment]
Thank you @JKMarkowski  for the quick answer. I'll wait patiently for the 0.9.0
