### ISSUE TITLE
[P2][Sourcing][Accessibility][Pretest] [FDP-Select] Incorrect role "listbox" with the misleading additional information "collapsed" and "has popup"

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10806]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Incorrect role "listbox" with the misleading additional information "reduced" and "has popup"https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/
This is not as per w3 standards.

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15
core/ platform: 0.43.14
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
When focus is on select box, correct role of the component is not announced and only listbox is getting announced

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/select#mode

**Comment by droshev** [comment]
@I543348 what is the role you expect and what do you mean with this `reduced`? In sapui5 the announcement is very similar ([link](https://ui5.sap.com/#/entity/sap.m.Select/sample/sap.m.sample.Select))

**Comment by sagar7259** [comment]
Hello @droshev ,

Please find the attached screen shots of reading for both sapui5 and fundamental NGX components for the comparision where this additional reading "Collapsed" and "Has popup" is only read for NGX component and not for ui5.

NGX Select:
![image](https://github.com/SAP/fundamental-ngx/assets/143692208/64bc7b3b-bc5d-45cd-a5c3-d30575cf216b)

UI5 Select:
![image](https://github.com/SAP/fundamental-ngx/assets/143692208/442a44b4-9b77-4c38-9ce7-d8bc48388719)

Regards,
Sagar

**Comment by droshev** [comment]
@nikolay-kolarov Can you advise us here? thank you
