### ISSUE TITLE
[P3.2][Sourcing][Accessibility][Pretest][FDP-Select]When reading with the virtual cursor and in the element overview (INS+F5), the value is not perceptible with the screen reader. 

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10807]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When reading with the JAWS virtual cursor and in the element overview (INS+F5), the value is not perceptible with the screen reader. 
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular : 15
core/platform: 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) Open an fdp-select box
2) turn on JAWS VPC mode on / linear reading mode
3) go over values and notice that value is not getting announced.

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/select

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

Yes, you can add the value in a similar way as done in UI5 https://ui5.sap.com/#/entity/sap.m.Select/sample/sap.m.sample.Select
or in the ARIA APG sample https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/.

Best Regards,
Nikolay

**Comment by I543348** [comment]
Hi Team,
As @mikerodonnell89 suggested me to check this issue today.
The issue is no more replicable and can be closed, I also cross verified with ATL team.
Pls find the screenshot of the readings.

<img width="1393" alt="Screenshot 2024-01-10 at 10 42 18 AM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/e73d58a2-5e15-43ac-81c5-c6f6e66f4f41">
