### ISSUE TITLE
[P3.2][Sourcing][Accessibility][Pretest][Multi input automcomplete] [multi combobox] If an inline autocomplete entry is displayed, the rest of the word is highlighted and output by the screen reader which is difficult to understand.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10812]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Issue happens both with multi input autocomplete list and multi comboobox
If an inline autocomplete entry is displayed, the rest of the word is highlighted and output by the screen reader which is difficult to understand.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular: 15
core/platform: 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Type some random starting word like for eg : To, only "mato" is highlighted and read by screenreader. 
https://ng-15-downport--fundamental-ngx.netlify.app/#/core/multi-input#includes
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/multi-combobox#data-source

**Comment by nikolay-kolarov** [comment]
Hi @I543348,
Hi @droshev,

This is according to the UX design for highliting. While there is a highlighted text the screen reader reads the info that this is a selection and the user knows what was entered so far. It is the same as well in UI5.

So I think we can close this one.

Best Regards,
Nikolay

**Comment by I543348** [comment]
This is even same in w3 standards , and we are good here. can be conveyed same to customer 
ref: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/
