### ISSUE TITLE
[P3.2][Sourcing][Accessibility][Pretest][Fdp-select]When navigating through open list, the focused list item will not automatically become the selected value but must be activated with SPACE or ENTER.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10810]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When navigating through open list, the focused list item will not automatically become the selected value but must be activated with SPACE or ENTER.

Expectation: if user is navigating through list and presses tab and moves to next control , then the last focussed item should ideally become selected value in fdp-select
w3: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular: 15
core/platform: 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
[Screen Recording 2023-10-26 at 3.39.36 PM.mov.zip](https://github.com/SAP/fundamental-ngx/files/13175975/Screen.Recording.2023-10-26.at.3.39.36.PM.mov.zip)

1) Reach fdp-select using keyboard
2) Open the dropdown list using enter
3) now traverse through some option 
4) try to press tab key now
5) observe that the option that was in step 3 is not selected in dropdown after moving out of dropdown
This is not as per w3 standards https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

works fine in UI5 Select : https://sapui5.hana.ondemand.com/#/entity/sap.m.Select/sample/sap.m.sample.Select

**Comment by nikolay-kolarov** [comment]
Hi,

Yes, I also think it makes sense to make it consistent as in UI5, except there is no specific reason/requirements why this is done like this.

Best Regards,
Nikolay
