### ISSUE TITLE
[P2][Sourcing][Accessibility][Pretest][Multi input complete] When leaving the field with an invalid entry, the value is deleted without an error message, which is problematic especially for screen reader users

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10813]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When leaving the field with an invalid entry via keyboard , the value is deleted without an error message, which is problematic especially for screen reader users

 Expectations: Please remove inline autocomplete or give the user the hint that he has to select valid values or show an error message when leaving the field if no valid value was entered

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/platform: 0.43.14

**Comment by droshev** [comment]
@I543348 What is your scenario on in your application and can you share your code? The multi input offers different options and they can be configured and handled by the application depending on the use case. We may help you to pass the right input and achieve the expected result

**Comment by I543348** [comment]
> @I543348 What is your scenario on in your application and can you share your code? The multi input offers different options and they can be configured and handled by the application depending on the use case. We may help you to pass the right input and achieve the expected result

Hi @droshev , the example and configuration in application is similar to example https://ng-15-downport--fundamental-ngx.netlify.app/#/core/multi-input#includes.
Here , what end user will enter is not under application's control or developer's control, hence whatever invalid text the user enters , we need to either show and make screenreader read some error message or hints which would tell disabled users , that the text they are entering is actually invalid.

**Comment by droshev** [comment]
@I543348 Can you create a stackblitz example?

**Comment by I543348** [comment]
Yes @droshev , I will be attaching a stackblitz if possible or a proper recording.

**Comment by droshev** [comment]
@I543348 we need a stackblitz with your specific example.

**Comment by I543348** [comment]
pls find the stackbliz link , here when i typed "Sourcing" ,customer suggested we can either provide a screenreader hint (aria-description) as invalid text or we show a visible error beneath the control that typed text is invalid.
[stackblitz](https://stackblitz.com/edit/angular-ss96jz-ptqfjh?file=src%2Fapp%2Fplatform-table-custom-width-example.component.html,src%2Fapp%2Fplatform-table-custom-width-example.component.ts,src%2Fapp%2Fapp.module.ts)

**Comment by N1XUS** [comment]
@I543348 multi input component provides ability to define a callback function on every user input: `(searchTermChange)`. So technically, you can add a custom callback with some live announcer to read that the entered text is invalid.
Closing the issue for now, if you have additional questions, please re-open the ticket.

**Comment by sagar7259** [comment]
Hello Colleagues,

The autocompleted is removed and on searching any invalid text or the text which is not in the list, the token is not at all accepted.
Also the screen reader is reading has "No results" when there are zero search results and "x results available" if we have any search results. 
Hence this ticket can be closed has its fixed.

Regards,
Sagar
