### ISSUE TITLE
[P2][Sourcing][Accessibility][Pretest][Multi combobox] If a valid value is entered from the list, it is automatically deleted without an error message when the field is exited.

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10822]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
If a valid value is entered from the list, it is automatically deleted without an error message when the field is exited.

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core platform:0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
[Screen Recording 2023-10-26 at 5.09.50 PM.mov.zip](https://github.com/SAP/fundamental-ngx/files/13176841/Screen.Recording.2023-10-26.at.5.09.50.PM.mov.zip)
ble).

**Comment by droshev** [comment]
The expected behaviour: if the user types exact match completely then the value gets tokenized
