### ISSUE TITLE
[P2][Sourcing][Accessibility][Pretest][Multi input] Role is input field: with the screen reader it is not noticeable that no values can be entered freely and that multiple entries are possible. 

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10826]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Role is an input field: with the screen reader it is not noticeable that no values can be entered freely and that multiple entries are possible. 

expectation: 
Please use description (title, aria-describedby, aria-description) or aria-roledescription="Multi Value Input".

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core platform 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Platform Multi input component

**Comment by nikolay-kolarov** [comment]
Hello @I543348,

I tested this and it is already available: https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/multi-input
Could you please retest?

@droshev , @InnaAtanasova - FYI

Thanks,
Nikolay
