### ISSUE TITLE
[P3.2][Sourcing][Accessibility][Pretest][Multi combobox]The tokens are in an unlabelled selection list. 

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10827]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
The tokens are in an unlabelled selection list. 
Please label the listbox, e.g. aria-label="Values for [label of the input field]".
#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core platform: 0.43.14

**Comment by nikolay-kolarov** [comment]
Hi,

Yes, the listbox needs to have aria-label="Tokenizer" or aria-labelledby pointing to a span containing the text Tokenizer.
Please check this implementation as a reference: https://ui5.sap.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox

Best Regards,
Nikolay
