### ISSUE TITLE
@fundamental-ngx/core/combobox can groupFn field be a null?

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#10829]
Hello, Fundamental-ngx Team. I have a question regarding combobox component and its groupFn property.

I am implementing generic combobox component, that can be based on different entities, f.e. buildings or floors etc., so that to keep the same interaction with any combobox in the application. So the trouble comes, **_when I need to pass groupFn as null or undefined_**, because f.e. I want to keep building combobox grouped, but floor don't want. And as I can see from the docs the type of this field is strictly GroupFunction:
https://github.com/SAP/fundamental-ngx/blob/03e181bbc9328d95e197a6a08e5262fa8d5d93fd/libs/core/src/lib/combobox/combobox.component.ts#L230
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/c5079c15-3990-484e-8abf-e435289aac0c)

**_But it seems in the template, that groupFn can be treated as null or undefined_**, so if I use null assertion operator, it is working (but it is not safe, because on your side smth can be changed)!
**_So is it possible to make a correction in the type of the field? Make it groupFn: GroupFunction | null?_**

Best Regards,

**Comment by N1XUS** [comment]
Hello @egorwow70. groupFn can be null or undefined (which one you prefer). but Angular Language Service may complain that the value is not a function. As a temporary fix you can wrap groupFn value with `$any()` function.
