### ISSUE TITLE
Add clear button and search button both in fd-input-group

### ISSUE THREAD

**Issue by KakaWangSAP** [SAP/fundamental-ngx#1083]
#### Briefly describe your proposal.
![image](https://user-images.githubusercontent.com/51769984/62509375-837c7b80-b83d-11e9-8c74-e05e8d60efd4.png)
The basic requirement is that an input search box like above pic, then input some something in it, the clear button shows up.  Now with below code I can only have the input box and search button. seams I can not have this clear button in this version.
![image](https://user-images.githubusercontent.com/51769984/62509550-36e57000-b83e-11e9-8669-411973d2fa42.png)

**Comment by JKMarkowski** [comment]
I guess there would be needed some changes on ngx library, but so far it's blocked by your issue https://github.com/SAP/fundamental/issues/1518
