### ISSUE TITLE
Current date is also marked in the date picker even after date range is selected

### ISSUE THREAD

**Issue by SandhyaJuvvala** [SAP/fundamental-ngx#10842]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
Current date is also marked in the date picker even after date range is selected
![image](https://github.com/SAP/fundamental-ngx/assets/148187258/4eab166e-d131-46c8-bf23-f4616f7c86a0)

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx : 0.46.1

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. In range date picker,  select a date range 
2. Date picker will be closed
3. Reopen date picker, current date is also marked in the date picker 
![image](https://github.com/SAP/fundamental-ngx/assets/148187258/f77a7362-247a-49fa-b6c1-23511ae73a54)

#### Did you check the documentation and the API?
Yes https://sap.github.io/fundamental-ngx/#/core/date-picker

#### Is there anything else we should know?
Is it possible to not show current date once the date range is selected

**Comment by droshev** [comment]
@SandhyaJuvvala this is the new design
