### ISSUE TITLE
Double square seen for focus in Date Picker

### ISSUE THREAD

**Issue by SandhyaJuvvala** [SAP/fundamental-ngx#10843]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
Double square seen for focus in Date Picker

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx : 0.46.1

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
In range date picker, dates are double focused, double square seen for focus
![image](https://github.com/SAP/fundamental-ngx/assets/148187258/302def27-d190-4b59-972b-8d4d4c00b7c0)
![image](https://github.com/SAP/fundamental-ngx/assets/148187258/8a8e064b-10b3-46c1-b35a-a367df1a162e)

#### Did you check the documentation and the API?
Yes https://sap.github.io/fundamental-ngx/#/core/date-picker

**Comment by droshev** [comment]
@SandhyaJuvvala that is the new design
