### ISSUE TITLE
The examples in "stackblitz" don't work.

### ISSUE THREAD

**Issue by ehmh2009** [SAP/fundamental-ngx#10844]
Not possible to use sample applications in StackBlitz. e.g. for Timeline component.
![image](https://github.com/SAP/fundamental-ngx/assets/9335235/67f489e0-a4fe-49c1-b3d7-7ea6645c79ec)

**Comment by droshev** [comment]
@kalo2711 Can you check which stackblitz examples aren't working properly

**Comment by kalo2711** [comment]
Action bar with back button: ❌ The back button doesn't appear.

**Comment by droshev** [comment]
@kalo2711  Can you try to finish the testing this week? Can you update the progress?

**Comment by InnaAtanasova** [comment]
Pagination

❌ Example 1
✅ Example 2
🟡  Example 3

**Comment by InnaAtanasova** [comment]
Pagination

- [ ] Example 1
- [ ] Example 2
- [ ] Example 3

**Comment by kalo2711** [comment]
Facets
-[] Group

**Comment by droshev** [comment]
@kalo2711 Once you restart testing, can you remove the blocked label?

**Comment by kalo2711** [comment]
{Platform Docs}

**Comment by kalo2711** [comment]
_- Action Bar_

**Comment by kalo2711** [comment]
No Compile Issues, but dropdown menu is not opening fully on almost all components that contain it: 
Action Sheet
- Default (Small Menu Scroll)
- Compact Mode (Small Menu Scroll) 
Carousel
- Carousel with no page indicator (Image in bad format)
- Carousel with looped navigation (Image in bad format)
Menu
- Simple (small Menu Scroll)
- With icons (small Menu Scroll)
- With separator (small Menu Scroll)
- With Scrollbar (small Menu Scroll)

**Comment by kalo2711** [comment]
Problem Components from "Micro Process Flow" to "Tabs"

Object Number
Basic Object Number (Lack of Spacing)
Large Object Number (Lack of Spacing)
Bold Object number (Lack of Spacing)
Object Number Decimal (Lack of Spacing)
Popover
Lazy initialization of popover body (Menu dropdown minimized)
Handling dynamic control offset (Menu dropdown minimized)
Dropdown Popover (Menu dropdown minimized)
Dynamic Body Height (Menu dropdown minimized)
Product Switch
Basic Product Switch inside Shellbar (Menu dropdown minimized)
Shellbar
Responsive Shellbar (Compile)
Shellbar with growing groups (Compile)
Shellbar with custom user menu (Compile)
Split Button
Buttons with icons (Menu dropdown minimized)
Custom template for action button (Menu dropdown minimized)
Status Indicator
Status Indicator Clickable (Compile)
Table
Customizable Columns (Compile)
Column Sorting and Filtering (Compile)
Tabs
Process Table (Compile)

**Comment by kalo2711** [comment]
Text -> Wizard

All Components are working perfectly! :)

**Comment by kalo2711** [comment]
Core until -> Truncate is all good! ;)

**Comment by kalo2711** [comment]
**Platform**
Date Picker
• Date picker that updates its value on blur (Calendar is displayed too small)

**Comment by droshev** [comment]
All known failing stackblitz examples have been fixed
