### ISSUE TITLE
fd-input-group-search clear button not show up

### ISSUE THREAD

**Issue by KakaWangSAP** [SAP/fundamental-ngx#1085]
#### 
In https://sap.github.io/fundamental-ngx/inputGroup,  fd-input-group-search example, when enter some value in search input, the clear button is not show up, even we can find it in the DOM.
![image](https://user-images.githubusercontent.com/51769984/62515999-75872480-b856-11e9-9262-3a1b1cef1ba3.png)
One more thing, can we put the search icon in the end of the input box and make it clickable?
For example:
![image](https://user-images.githubusercontent.com/51769984/62516811-9ea8b480-b858-11e9-9731-57e670a6fecd.png)

**Comment by JKMarkowski** [comment]
I guess there would be needed some changes on ngx library, but so far it's blocked by your issue https://github.com/SAP/fundamental/issues/1518
