### ISSUE TITLE
[P2][Sourcing]On clicking on 1 more in multicombo box, the items are getting duplicated

### ISSUE THREAD

**Issue by Pallavi-I585022** [SAP/fundamental-ngx#10854]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
On clicking "N more" label of fdp-multicombo-box, we see the selected items getting duplicated.On clicking "N more" label be it 1 more, 2 more, so on in the fdp-multicombo-box, only selected items must be displayed and must not be duplicated.

<img width="953" alt="Screenshot 2023-10-31 121027" src="https://github.com/SAP/fundamental-ngx/assets/149486454/0bdc74de-60c9-4a7a-ba6b-ddb17c2a64f0">

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Steps to Reproduce
Go to https://sap.github.io/fundamental-ngx/#/platform/multi-combobox
Go to Examples -> under Datasource -> Example with "N more label" -> click on 1 more.
We see that items are duplicated
https://sap-my.sharepoint.com/:v:/p/pallavi_p/EUkgMN9cVV1PiQAFIlvh4YUBgqS7uC69FRn8X5_1kQiL8g?e=WLW2d6

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/7aeapv-5tgkma?file=src%2Fapp%2Fmulti-combobox-datasource-example.component.html

**Comment by droshev** [comment]
Even though the ticket targets `0.46.x`, the fix should be also downported to `0.43.x`

**Comment by Pallavi-I585022** [comment]
Can you please confirm if this fix works for fundamental-ngx  0.43.0 and above?

**Comment by Pallavi-I585022** [comment]
Hello @droshev ,
I request you to fix this issue for version 0.43.x  The fix is still not visible even for version 0.46.x. Please verify this.
https://sap-my.sharepoint.com/:v:/p/pallavi_p/Ec0NVLAxMNtFiSO3xyZnfv0BQfwVLEZc20NPyzYdVsiK7A?e=j35glV

**Comment by Pallavi-I585022** [comment]
Hello @droshev,
I wanted to test if this issue is resolved for 0.43.x version. But it is not mentioned in the changelog in which version this issue is resolved. I had added a comment to the issue but there was no response. Can you please help me with this?
