### ISSUE TITLE
[P3.1][Sourcing][Accessibility][fdp-table] Associated Table Column header not being read for empty table cell values

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#10869]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When using reader to access empty table cell, its associated table column header name should be announced.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
- Angular 15
- F-NGX Platform: 0.43.14

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using a simple basic table example https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table, set some of the cell values to empty, and then use the screen reader to navigate to that particular table cell.

![Screenshot 2023-11-01 at 5 08 00 PM](https://github.com/SAP/fundamental-ngx/assets/22454655/13b22c30-a049-4b6a-8ea3-7e43b0978ddf)

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Empty cells and cells with data are not associated with their respective column headers. Here only position of the cell is being read.

**Comment by nikolay-kolarov** [comment]
Hello @yixuan-liu,

I tested this and I am not able to reproduce? Could you please retest and if still reproducible provide more info about browser, Jaws version,etc and the exact steps to reproduce.


https://github.com/SAP/fundamental-ngx/assets/17043004/bdacec96-4fac-4fc4-bcd0-c8f5c5f3499d


Thanks,
Nikolay

**Comment by I543348** [comment]
> Hello @yixuan-liu,
> 
> I tested this and I am not able to reproduce? Could you please retest and if still reproducible provide more info about browser, Jaws version,etc and the exact steps to reproduce.
> 
>  screen.reccording.2023-11-07_11-10-25.mp4 
> Thanks, Nikolay

Yes @nikolay-kolarov this is still replicable and stackblitz link is attached in new issue #11167 , It was not replicable for you as teh website uses very old version of 0.43.x-rc-4 in which it may work.
