### ISSUE TITLE
The tiles (fd-tile component) are not accessible using the keyboard. 

### ISSUE THREAD

**Issue by dhivya910** [SAP/fundamental-ngx#10873]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
The tiles (fd-title component) is not accessible by keyboard

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
angular - 15.2.4
fundamental ngx - 0.38.2

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
<img width="959" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/67852219/49c8cf4e-1ad4-490c-9952-98e71c7da6a3">

#### Please provide relevant source code (if applicable).
reference- https://sap.github.io/fundamental-ngx/#/core/tile

#### Please provide stackblitz example(s).
<img width="909" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/67852219/a3a47a90-eda6-434e-bfd8-a7a6e7dd5751">

#### Did you check the documentation and the API?
yes

**Comment by N1XUS** [comment]
@dhivya910 you can use `clickable` input property of `fd-tile` to make inner content tabbable (focusable).

**Comment by dhivya910** [comment]
Thank you, now the tile is accessible by tab

**Comment by dhivya910** [comment]
Thank you, now the tile is accessible by tab
