### ISSUE TITLE
Search field issues

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#10885]
<img width="924" alt="Screenshot 2023-11-03 at 2 09 32 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/e1bbd046-3699-4127-9ace-901d3b675810">

In Horizon design there's no Synchronize button. Should we keep it?

**Comment by g-cheishvili** [comment]
In distinct search field page I could not find both categories and the sync button as well, only place where I could find the sync button was in fiori 3 search fields. But in fiori 3 search field page I could not see categories selector, only when in shellbar.
