### ISSUE TITLE
Dropdown features implementation

### ISSUE THREAD

**Issue by djagielo** [SAP/fundamental-ngx#109]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal
Proposed features:
- preserve selected value - model binding
- enable binding to reactive forms (control value accessor)
- expose input for selectable (available) items of label-value pairs (like SelecItem in PrimeNG)
- expose output of 'item selected'/change event

#### What versions of Angular and Fundamental NGX? (If this is a feature request, use current version)
Angular 6, Fundamental NGX - current version

**Comment by droshev** [comment]
@saadmhybris do we have implemented fundamental-ui component for that request?

**Comment by saadmhybris** [comment]
@droshev is this what you are referring to? https://github.com/SAP/fundamental/issues/349

if yes, then it's part of the 1.2 milestone.

**Comment by droshev** [comment]
blocked by https://github.com/SAP/fundamental/issues/349

**Comment by mikerodonnell89** [comment]
@djagielo are you requesting these features for the existing [Dropdown component](https://sap.github.io/fundamental-ngx/docs/dropdown) or for the combobox coming in 1.2?

**Comment by mikerodonnell89** [comment]
I spoke with @djagielo and he is talking about the dropdown.  Unblocking

**Comment by droshev** [comment]
@mikerodonnell89 what do we do here?

**Comment by droshev** [comment]
I those requests will be handled by the `combobox` component
