### ISSUE TITLE
No possibility of having responsive paddings in TabListComponent

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#10901]
#### Is this a bug, enhancement, or feature request?

It is an enchantment.

#### Describe your proposal.

**`DynamicPageComponent`** has two properties:
`size` -  that sets size which in turn adds corresponding padding for the size type,
and `autoResponsive` - that allows DynamicPage to have responsive side spacing changing with Page window width.

There is also a `size` property in **`TabListComponent`** (which is commonly used in DynamicPage even in Fundamental NGX documentation), but it doesn't have such `autoResponsive` property, so its paddings conflict with DynamicPage paddings.

In order to have the same padding both in DynamicPage and its tabs on different screen sizes, can you add `autoResponsive` property to **`TabListComponent`**?

<img width="218" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/86781159/3362aee6-4508-4cb7-bac8-8134bbac19a5">
<img width="215" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/86781159/fece9464-f54b-4e15-871a-ec6b9fef5a3b">
<img width="215" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/86781159/12c9ef40-bfca-47d3-afe6-237e1c3226f7">

#### Can you handle that on the application side

No.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

0.44.0

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

No

**Comment by droshev** [comment]
@programister42 Can you try using the iconTabBar Component as it is tab container successor. Please, report a new ticket if  the issue is still present in the icon tab bar
