### ISSUE TITLE
Angular 17 migration

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#10910]
Since Angular 17 release introduces major changes, we need to appropriately adopt them:

- [x] ESBuild/Vite builder;
- [x] Migrate New Control Flow Syntax
- [ ] Add `@defer` blocks for component examples;

**Comment by droshev** [comment]
let's just focus on the bare minimum first. the rest can be planned later on.

**Comment by DominikPieper** [comment]
While with Angular 17 the old control flows still work a first v17 compatible release would be great and adapt the new features after that 😁

**Comment by g-cheishvili** [comment]
https://github.com/SAP/fundamental-ngx/issues/10004
This is a very important thing as well, since ng17 by default comes with standalone setup

**Comment by N1XUS** [comment]
Closing this task since migration is complete. Usage of the `@defer` block may not have anticipated results in terms of e2e rewrite complexity.
