### ISSUE TITLE
bundle size increases heavily with v0.46

### ISSUE THREAD

**Issue by nbblum** [SAP/fundamental-ngx#10935]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Describe your proposal.
When updating @fundamental-ngx/core in our application from v0.45.1 to v.0.46.1 we've seen that our bundle size increased more than expected. When comparing the two bundles I noticed that the fundamental-ngx-i18n module growed from 25 kb to 600 kb which is really a huge block in the v0.46 version. 

![image](https://github.com/SAP/fundamental-ngx/assets/85098790/905f3f69-62f5-438a-bca4-bb8bd8ea87d8)

When comparing the releases I've seen that you switched from a language definition in .ts files to a definition in .json files. But the translations seems to be more or less the same. 

Is this really expected and wished or did I oversee something

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

v0.45.1 to v.0.46.1

https://github.com/SAP/fundamental-ngx/compare/v0.45.1...v0.46.1

**Comment by droshev** [comment]
@nbblum thank you for reporting the issue.
