### ISSUE TITLE
Multi Input With Value help dialog box with complex Objects : Empty Thumbnail div element

### ISSUE THREAD

**Issue by nagacharangt** [SAP/fundamental-ngx#10959]
#### Describe your proposal.

Extra empty spacing for dropdown list with byline/description: Thumbnail is not present but still occupies "empty space". 
 it doesn't match with the  [UI5](https://wiki.one.int.sap/wiki/display/visualcore/List+%28Horizon%29+-+Standard+List+with+Byline) standards

#### Can you handle that on the application side
NO

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
v0.47.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Visit https://sap.github.io/fundamental-ngx/#/platform/multi-input#complex for Multi Input With Value help dialog box with complex Objects object.
2.  Use the same fundamental example with one more property **selectionMode="multi"**

![image](https://github.com/SAP/fundamental-ngx/assets/15129807/c54a1acb-b1a5-4f5b-909b-f4a5d733d33c)

**Comment by droshev** [comment]
@nagacharangt I think in fundamental example the images of the thumbnails are missing

**Comment by droshev** [comment]
@N1XUS Can you check what's wrong with the examples?
