### ISSUE TITLE
[Issue] Programmatically open tabs that hidden in more button

### ISSUE THREAD

**Issue by TatsianaShynkevich** [SAP/fundamental-ngx#10969]
Hello!

We faced an issue while using tabs for our application. Tabs are stacked to the more button and we need to open it programmatically using this feature: https://sap.github.io/fundamental-ngx/#/core/tabs#programmatic-selection.
So when we try to open programmatically tab that hidden in 'more' button header do not refresh and show the last tab that was selected manually.

Could you please review it on your side?

Our version:
"@angular/core": "15.2.1",
"@fundamental-ngx/core": "0.41.0",

Steps to reproduce:
Create so many tabs that it will be stacked to more button
Try to open programmatically tab that hide in more button using this feature: https://sap.github.io/fundamental-ngx/#/core/tabs#programmatic-selection
Header will not refresh and show tabs that was last clicked manually

Stackblitz example: https://stackblitz.com/edit/3iwgz8?file=src%2Fapp%2Ftab-selection-example.component.html

Thanks a lot!

**Comment by droshev** [comment]
@N1XUS is this doable for Icon Tab Bar? If so, can you close the issue?
