### ISSUE TITLE
[Accessibility] List with Byline - Screen reader doesn't identify unread list item

### ISSUE THREAD

**Issue by harshitha-s-kanchan** [SAP/fundamental-ngx#10967]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Screen reader should identify the unread list items when unread blue dot is visible for the list item
<img width="1160" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/149040487/139bb60b-4397-45bd-b80f-5759efbf8bdd">

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
Ngx - 0.43.11
Screen reader - JAWS

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
The issue can be reproduced by reading out List with Byline component using JAWS screen reader. 
https://sap.github.io/fundamental-ngx/#/core/list-byline#list-byline-unread

<img width="1709" alt="Screenshot 2023-11-15 at 2 04 52 PM" src="https://github.com/SAP/fundamental-ngx/assets/149040487/89787b42-1e45-4163-acdf-0dbbf0b7da65">

#### Please provide relevant source code (if applicable).
https://github.com/SAP/fundamental-ngx/blob/3672ff066b2d4bf1d4dbeeb90b8fec26710c154c/libs/core/src/lib/list/list-item/list-item.component.html#L8

#### Please provide stackblitz example(s).
N/A

**Comment by droshev** [comment]
@nikolay-kolarov Can you advise us with that request? Thanks
