### ISSUE TITLE
[feature] form-generator: image on radio-button 

### ISSUE THREAD

**Issue by MichaelSp** [SAP/fundamental-ngx#10971]
#### Is this a bug, enhancement, or feature request?

Feature

#### Describe your proposal.

I would like to provide an image on the radio buttons

#### crappy 💩 mockup of your idea

![image](https://github.com/SAP/fundamental-ngx/assets/448282/9301730f-f915-4a75-be79-2fade9723bc9)

#### 🤔 how to use it

```ts
questions: DynamicFormItem<{}, HeaderDynamicFormControl>[] = [ {
      type: 'radio',
      name: 'buildTool',
      message: '',
      guiOptions: {
        inline: true,
        icon: 'some/icon.svg',
      },
}]
```

#### Can you handle that on the application side

yes, I could create a [custom form control](https://sap.github.io/fundamental-ngx/#/platform/form-generator#custom)

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

`v0.47.2`

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 

🤨

#### Is there anything else we should know?

you are awesome 😻

**Comment by droshev** [comment]
I think this is not relevant anymore

**Comment by MichaelSp** [comment]
We are still waiting for this feature. For us at least it is still relevant.

**Comment by MichaelSp** [comment]
@droshev this is still relevant for us. Any chance to get this re-opened?

**Comment by droshev** [comment]
@MichaelSp This request has a very niche usage, we offer a way to create a custom component and add it in the wizard
