### ISSUE TITLE
Multi-input height is changing based on theme

### ISSUE THREAD

**Issue by vsomsekhar** [SAP/fundamental-ngx#10977]
#### Is this a bug, enhancement, or feature request?
bug

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

"@fundamental-ngx/core": "0.46.1"
 "@angular/core": "^16.2.8"

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

SAP Horizon High Contrast Black
<img width="891" alt="Screenshot 2023-11-17 at 9 32 34 AM" src="https://github.com/SAP/fundamental-ngx/assets/142768234/2f48d8ce-1f94-4308-825d-f26e64148a17">

SAP Evening Horizon
<img width="902" alt="Screenshot 2023-11-17 at 9 33 04 AM" src="https://github.com/SAP/fundamental-ngx/assets/142768234/56229fa9-bef5-4e78-a012-8f24c185ea7e">

Height of multi-input(Select Authorizations) is varying w.r.t theme

#### Please provide relevant source code (if applicable).
https://github.tools.sap/AP-AC-Products-Services/Lobby/blob/master/deployment-container-header/src/app/sharing-dialog/sharing-dialog.component.html

**Comment by droshev** [comment]
actually the issue is in all themes

**Comment by SomVelisetty** [comment]
Is there any timeline when this will be solved?
