### ISSUE TITLE
[P3.1][Sourcing] Dynamic page component need translation support for 'Expand/Collapse Header' tooltips

### ISSUE THREAD

**Issue by sreekanthkarini** [SAP/fundamental-ngx#10992]
#### Is this a bug, enhancement, or feature request?
feature

#### Describe your proposal.
Need translation support to 'Expand/Collapse Header' tooltips for Dynamic page component 
<img width="1728" alt="Collapse Header" src="https://github.com/SAP/fundamental-ngx/assets/136553940/d0bf692e-1285-4004-8f33-353d33dca204">
<img width="1728" alt="Expand Header" src="https://github.com/SAP/fundamental-ngx/assets/136553940/92c36728-3139-4ee6-8b36-72a564a38057">

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.43.9

#### Please provide relevant source code (if applicable).
https://sap.github.io/fundamental-ngx/#/platform/dynamic-page

**Comment by rvamudha** [comment]
@sreekanthkarini  - can you please add the tag [P3.1] in the title of the message for tracking purpose
@droshev  - looks like this translation is missing checked for Portuguese and Deutsch languages 

Checked here ](https://fundamental-ngx.netlify.app/#/platform/upload-collection) by changing the language to Portuguese
