### ISSUE TITLE
multi input/combobox: Remove the placeholder once at least one item is selected

### ISSUE THREAD

**Issue by AmosZhang-cn** [SAP/fundamental-ngx#10998]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
In the multi-input component, the placeholder is truncated after selecting some options and needs to be fixed.
Expected Results: Show full text when hovering over truncated text

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
- Angular 15
- F-NGX ngx core 
- Version: 0.43.17

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
multi-input componen
Please see the screenshot. There is a language input box on the page. Select the language. The placeholder is truncated and cannot be displayed in full.

<img width="685" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/29881909/04ce7608-82fd-46d4-b0c0-26df39e5ca20">

bug
<img width="855" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/29881909/9deb8587-10b4-4405-83d2-0800e839ee5e">

**Comment by droshev** [comment]
@AmosZhang-cn What do you expect in this situation? In your scenario you don't have the space for it

**Comment by AmosZhang-cn** [comment]
hello @droshev 
I want the characters to be fully visible when the mouse is over the placeholder, even if the placeholder is truncated or otherwise obscured.
This is very important for users. Even if the prompt information is blocked, the prompt information can be seen by hovering the mouse.

**Comment by droshev** [comment]
@N1XUS Can you check this one? thanks
