### ISSUE TITLE
Closing fd-product menu in shellbar after entry selection not possible

### ISSUE THREAD

**Issue by D043319** [SAP/fundamental-ngx#1099]
#### Is this a bug, enhancement, or feature request?
probably a bug

#### Briefly describe your proposal.
When you use the fd-product-menu in the shellbar, the "popup" does not automatically close after you have selected an entry from the fd-product menu. You need to close it manually.
 
In the event handler of the selected item you don't have access to the popup object, so you can't force closing the fd-menu via program code in the event handler.

So it looks like the proposed solution for the issue #1078 does not work for the fd-product-menu embedded in the shellbar.
"Drop down is still open after one item is selected"
https://github.com/SAP/fundamental-ngx/issues/1078

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
V. 0.7.0

#### If this is a bug, please provide steps for reproducing it.
Can be reproduced in the shellbar demo.
https://sap.github.io/fundamental-ngx/shellbar
Open fd-product-menu, select an entry, event handler get's called. No way to close the menu.

**Comment by JKMarkowski** [comment]
Hi @D043319 You will be able to achieve it, by adding `[closePopoverOnSelect]="true"` option to `fd-shellbar-actions` component. It will come up with patch 0.9.0

**Comment by D043319** [comment]
Hello @JKMarkowski,
thank you for your fast reaction and sorry for the delay in my answer, I was not online for the last 10 days.

I guess your fix works only for the "menues" on the right side of the shell bar which are controlled via the "shell-bar-actions".
I was talking about the "fd-product-menu" which is located at the left side of the shellbar.
In the shell bar example implementation this is filed with , "Application A, Application B ... Application D".

https://sap.github.io/fundamental-ngx/shellbar

    <fd-product-menu [control]="productMenuControl"
                     [items]="productMenuItems">
    </fd-product-menu>

Here you can't add the new option [closePopoverOnSelect]="true" to close the product menu after one of the entries was selected.

Can you pls. check if the provided fix can be also applied for the fd-product-menu?
Thank you for your support.
