### ISSUE TITLE
[P1][Sourcing] Boolean value is not available in value help dialog component

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#10997]
#### Describe your proposal. In Value help dialog component we do not have boolean value filter 
<img width="725" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/110370099/8afde070-7db1-4a52-93f9-efc940aae534">

**Comment by rvamudha** [comment]
s this a bug, enhancement, or feature request? enhancement

Describe your proposal. 

In Value help dialog component, we do not have Boolean value filter. 

<img width="954" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/143414187/56377805-867c-493b-82d3-b4e35f6d5b7d">
https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog

We have below filter options can not have pre-defined list which can be used in the filter 
contains = 'contains'
equalTo = 'equal to'
between = 'between'
startsWith = 'starts with'
endsWith = 'ends with'
lessThan = 'less than'
lessThanEqual = 'less than or equal to'
greaterThan = 'greater than'
greaterThanEqual = 'greater than or equal to'
empty = 'empty'


Can you handle that on the application side? 
 No we cannot
Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15

If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog 

Please provide relevant source code (if applicable).
Please provide stackblitz example(s).
In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Did you check the documentation and the API?
Did you search for similar issues?
Is there anything else we should know?

**Comment by droshev** [comment]
The requirement: offer comobobox as a input type in the filters. Another one is the data for the filters can come either from the table fields and/or from others.

**Comment by rvamudha** [comment]
@droshev  - as conveyed over our MS teams chat, implementing the workaround / customer solution from Sourcing side is difficult. We will wait for standard solution from F-NGx

**Comment by N1XUS** [comment]
Agreed solution: add ability to define custom control per each filter type.

**Comment by oscargong** [comment]
Hi @N1XUS,
I see your PR https://github.com/SAP/fundamental-ngx/pull/11080 for 0.48. Is it possible to include this feature for Fundamental 0.43 (for Angular 15)?

**Comment by N1XUS** [comment]
> Hi @N1XUS, I see your PR #11080 for 0.48. Is it possible to include this feature for Fundamental 0.43 (for Angular 15)?

Hey @oscargong. I will create a PR for ng15 once I get an approval for main

**Comment by sahanaN123** [comment]
Hi @N1XUS @droshev ,

   We tried to implement the dropdown in advanced filters. But we are just getting label and no combo box is displayed. Even we tried using the exact code from the website and still its the same.
https://stackblitz.com/edit/angular-ugca8x-tigsbs?file=src%2Fapp%2Fapp.module.ts
  But we observed that on the website we see combo box present again with same code which we used in stackblitz.
<img width="1076" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/110370099/644ad0c5-93ac-4d80-bc73-bd1db558fc31">

Thanks,
Sahana.

**Comment by N1XUS** [comment]
@sahanaN123 https://stackblitz.com/edit/angular-ugca8x-uhmsjb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdynamic-page-tabs-example.component.html

it turns out in docs I've applied fd-form-control component to fd-combobox, which is a no-no. I've updated an example in stackblitz and moved fd-form-control outside fd-combobox.
