### ISSUE TITLE
[P2][Sourcing][Regression][Platform Table]: After scrolling and applying filter , the rows rendered are not correct

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11002]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When table with pageScrolling is enabled with pageSize say 20 or 30.
On scrolling to 2nd page , the data loads with next set of rows.
Now at this state, filtered rows are not getting displayed in the table

Observation: datasource model is getting updated correctly with filtered rows, but the view is not updated.
Expectation: The table has to render correct rows based on filter no matter on which page we are.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
Core /platform: 0.43.17

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) Use the [stackblitz](https://stackblitz.com/edit/angular-9qxxca-fwha6v?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) 
2) The table example has 60 rows with pageSize= 30, now scroll to get 2nd page data (next 30 records)
3) Now click on button "Filter Results"
4) Observe that rows are not filtered based on data source

Pls note this issue works fine in 0.41.1-rc.7 but not working in 0.43.17 , hence regression
[Screen Recording 2023-11-24 at 3.39.42 PM.mov.zip](https://github.com/SAP/fundamental-ngx/files/13458164/Screen.Recording.2023-11-24.at.3.39.42.PM.mov.zip)

#### Please provide stackblitz example(s).
[stackblitz](https://stackblitz.com/edit/angular-9qxxca-fwha6v?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) 

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
NA

#### Is there anything else we should know?

Pls note this issue works fine in 0.41.1-rc.7 but not working in 0.43.17 , hence regression
I think view is not getting updated based on dataSource of the table in this case.
The filtered results works fine when user is not moving to other pages other than 1st page,

**Comment by g-cheishvili** [comment]
The datasource swapping should not cause this issue, but it causes, I agree. But also, this is not how rows should be filtered. You should set filters on provider and that's how it should update the items which are rendered, not entirely swapping out the full data source

**Comment by I543348** [comment]
Verified on NGX stackblitz using 0.43.18 and the issue seems to be fixed.
Thanks.
https://stackblitz.com/edit/angular-9qxxca-fwha6v?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json

**Comment by I543348** [comment]
Hi @N1XUS , This issue is working fine however the issue https://github.com/SAP/fundamental-ngx/issues/11002 is again replicable , pls find the stackblitz [link](https://stackblitz.com/edit/angular-9qxxca-nwzrms?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json)

Here pls follow below steps to reproduce the issue

Use above stackbliz
Click on filter results button
notice table has only one record
Now click on undo filter table button where we are again binding all 60 rows in table
Notice that only 2nd page records starting from 30 to 59 are getting binded in the table.
The table is not showing first page records at all.
Please help as this was a customer issue which was fixed.
Thanks.

cc: @Sayandeep-123 , @droshev
