### ISSUE TITLE
[P2][Sourcing][fd-popover] there is no focus on popover after popover opened

### ISSUE THREAD

**Issue by nancy07-f** [SAP/fundamental-ngx#11001]
#### Is this a bug, enhancement, or feature request?
bug
#### Describe your proposal.
When open popover, should focus on popover box.
#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
ngx core platform: 0.43.17
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Click on the link, show popover, but there's no focus on the popover after popover opened. [focusTrapped]="true" and [focusAutoCapture]="true" both have been added. used fd-popover component.
#### Please provide relevant source code (if applicable).
    <fdp-link *ngIf="linkName" tabindex="0"
              ada-focus ada-setattribute attrSelector="a" attr="data-high-contrast=true"
              (click)="onEditStart($event, itemPopoverDialog, popoverEditType, node, column, currentTerm, terms)"
              [title]="linkName"
              [attr.awname]="linkName">
        {{linkName}}
    </fdp-link>
    <fd-popover #itemPopoverDialog
                [focusTrapped]="true"
                [focusAutoCapture]="true"
                [noArrow]="false"
                [maxWidth]="600"
                [closeOnOutsideClick]="false"
                [closeOnEscapeKey]="false"
                [fixedPosition]="true"
                [placement]="placement ? placement : 'top-start'"> ....</fd-popover>
#### Is there anything else we should know?
 it works on 0.43.14.

**Comment by droshev** [comment]
@nancy07-f Is there a way to provide an example of code?

**Comment by nancy07-f** [comment]
@droshev I put some relevant source code on here.

**Comment by droshev** [comment]
@nancy07-f this seems a regression one

**Comment by mikerodonnell89** [comment]
@nancy07-f I think we need to see what that `onEditStart` function is doing. Or, try adding `[fdPopoverTrigger]="itemPopoverDialog"`. This is working fine on 0.43.20 with the following source:

```
<button fd-button [fdPopoverTrigger]="popover">Popover Trigger</button>

<fd-popover [focusTrapped]="true" [focusAutoCapture]="true" #popover>
    <fd-popover-control>
        <button fd-button label="Sample"></button>
    </fd-popover-control>
    <fd-popover-body>
        <div fd-popover-body-header id="popover-bar-simple-header-2">
            <div fd-bar barDesign="header-with-subheader" [cozy]="true">
                <div fd-bar-left>
                    <fd-bar-element>Cozy Header</fd-bar-element>
                </div>
            </div>
            <div fd-bar barDesign="subheader" [cozy]="true" id="popover-bar-simple-header-3">
                <div fd-bar-middle>
                    <fd-bar-element [fullWidth]="true"
                    >SubHeader Middle section with Full Width Element
                    </fd-bar-element>
                </div>
            </div>
        </div>
        <fd-avatar [circle]="true" style="margin: 1rem" size="xl" glyph="group"></fd-avatar>
        <div fd-popover-body-footer>
            <div fd-bar barDesign="footer" [cozy]="true">
                <div fd-bar-right>
                    <fd-button-bar label="Save" fdType="emphasized"></fd-button-bar>
                    <fd-button-bar label="Cancel"></fd-button-bar>
                </div>
            </div>
        </div>
    </fd-popover-body>
</fd-popover>
```

https://github.com/SAP/fundamental-ngx/assets/2471874/5c6e102f-14ca-4383-a88d-8303714283a9

**Comment by nancy07-f** [comment]
@mikerodonnell89 can you provide me with the ui link? I want to test on my side. thanks.

**Comment by nancy07-f** [comment]
this one can be resolved on my side, so will close it. thanks @droshev @mikerodonnell89 .
