### ISSUE TITLE
When will the search input control be discarded

### ISSUE THREAD

**Issue by Elly-chen** [SAP/fundamental-ngx#1102]
#### Is this a bug, enhancement, or feature request?

probably a feature request.

#### Briefly describe your proposal.

I noticed that in version 0.8.0 it was mentioned that search input would be discarded. I wondered when it would be discarded.And the version 0.8.0 prompted me to replace the search input with combobox, but it did not satisfy the search input function. Will search input function be added to combobox in future versions?

At present, I have a requirement to add icon in dropvalues of search input. And I want to add a clear button to the search input to clear the previous input. Will this function be satisfied in subsequent versions?

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

V 0.8.0

**Comment by JKMarkowski** [comment]
Hi @Elly-chen the search function is presented in combobox, see:
https://sap.github.io/fundamental-ngx/combobox/api
If you want to add icons to dropvalues, please use `[itemTemplate]`. Check the last example (Custom Item Template) of combobox here: https://sap.github.io/fundamental-ngx/combobox

**Comment by Elly-chen** [comment]
Hi,@JKMarkowski think you for your reply,and I also want to add a clear button to clear the previous input.Can combobox do this?

**Comment by JKMarkowski** [comment]
Unfortunately, so far It's not possible.

**Comment by Elly-chen** [comment]
Well, thank you.

**Comment by Elly-chen** [comment]
Hi,@JKMarkowski  I did not find an API to set the trigger button event
Can't this control set the event triggered when clicking the button?

**Comment by droshev** [comment]
@Elly-chen What i understand in this issue that you want to know whether ( and if yes then when) `combobox` will offer clear button. Is that right?

**Comment by droshev** [comment]
@Elly-chen any updates from your side?

**Comment by Elly-chen** [comment]
oh yes,now we've solved this problem with custom development.@droshev
