### ISSUE TITLE
[P1][Regression] Datetime picker doesn't work when trying to open it after first time

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#11023]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
The date-time picker (fd-datetime-picker) doesn't open after opening and closing it for the first time.
And on clicking again, it gets open and close simultaneously. Please refer the attached recording.

https://github.com/SAP/fundamental-ngx/assets/71999626/292dbfdb-ec29-4fde-a0e1-4e262e9e5c20

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular version - 15.x
Fundamental library version - v0.43.17

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Use the above mentioned angular version and fundamental library version and use simple "fd-datetime-picker".

#### Please provide stackblitz example(s).
Editor URL - https://stackblitz.com/edit/gz5v9e?file=package.json

#### Is there anything else we should know?
In older fundamental library version, it used to work.

**Comment by droshev** [comment]
fixed with `0.43.18`

**Comment by mikerodonnell89** [comment]
https://github.com/SAP/fundamental-ngx/pull/11020

**Comment by Sayandeep-123** [comment]
Verfied in stackblitz, it's working fine.
Thanks.
