### ISSUE TITLE
Segmented Button - emphasize state for active button 

### ISSUE THREAD

**Issue by Happyjump** [SAP/fundamental-ngx#11049]
#### Describe your proposal.
Currently it's difficult to identify which button part of a segmented button is active. 
The request is to enable also the emphazised state for the active button part
![image](https://github.com/SAP/fundamental-ngx/assets/31856793/6a9192e7-7512-4737-ae60-90857c723e5a)
![image](https://github.com/SAP/fundamental-ngx/assets/31856793/7f475093-1de9-494d-83f6-1c5906b1fc0a)

#### Can you handle that on the application side
Only with custom CSS

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest Version

**Comment by droshev** [comment]
that needs to be done on design level first

**Comment by droshev** [comment]
@Happyjump any update here

**Comment by droshev** [comment]
no activities => closing the issue
