### ISSUE TITLE
[WIP][P2][Sourcing] Control to enable/disable select-all in VHD

### ISSUE THREAD

**Issue by vidworks** [SAP/fundamental-ngx#11050]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Describe your proposal.
Add new input parameter for value-help-dialogue component to enable or disable the select-all checkbox.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
NA

#### Please provide relevant source code (if applicable).
NA

#### Please provide stackblitz example(s).
NA

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
NA

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
NA

#### Is there anything else we should know?
NA

**Comment by droshev** [comment]
@vidworks Can you elaborate more?

**Comment by vidworks** [comment]
Hi @droshev , when value-help-dialogue box is provided with more than 200 values for ex: 10000. and when the user clicks on select-all checkbox, clicks okay. The fd-multi-input component used to display the selected values/tokens slows down the page.

In example code here https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog#multi-input. Give an input of 10000 values and select all, you'll see it reproducible.

As a work around we want to disable select-all button/checkbox.

<img width="1028" alt="Screenshot 2023-12-06 at 8 44 19 AM" src="https://github.com/SAP/fundamental-ngx/assets/136386704/7aa043b8-a4b4-47ed-924f-3b1a213afa5a">

**Comment by vidworks** [comment]
@droshev Please let me know if more information is required.

**Comment by droshev** [comment]
@vidworks yes, can you create stackblitz example?

**Comment by vidworks** [comment]
@droshev we just want an input parameter to disable the `select all` check box because Sourcing doesn't support adding all the items to the selection.

**Comment by vidworks** [comment]
Thank you @droshev for helping with ticket. Will there be a new patch for version `0.43.*` ?
