### ISSUE TITLE
[P2][Sourcing][fdp-combobox]: Combobox not showing correct selected value when lookupKey is unique and label is same

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11067]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
There are 2 issues with respect to fdp-combobox
**Issue 1:** 
 When using custom dataSource that is passed to combobox with group=true which has name , type and id, then the selection value is not shown properly even though  lookupKey="id" is being passed and getting console error.

Expectation: among groups with same label but with different lookupKey - the selected value has to show that matches lookupKey unique one selected.

Getting below console error

<img width="1343" alt="Screenshot 2023-12-09 at 1 44 02 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/38bf04f1-8abe-49e2-97fd-9463341648fd">

**Issue 2:** 
When using fdp-combobox without group=true, with just lookupKey and displayName then the records having same label but different lookupKey , both are shown as selected 
Expectation: Both records should not be shown as selected but only the one based on lookupKey needs to be shown as selected 

<img width="1338" alt="Screenshot 2023-12-09 at 1 44 37 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/2daa5752-33d8-4362-ac3b-669a0e558cb0">

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
Core / platform: 0.43.20
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
For issue 1:
1) Use stackblitz [link](https://stackblitz.com/edit/angular-9qxxca-qhylee?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json)
2) Notice that from ts file the default selected item is given as datasource[0] but it doesnt show it as selected.
3) Open combobox select first record "Apple"
4) Check the console error.

https://github.com/SAP/fundamental-ngx/assets/88182358/4de90bda-8fb1-4cec-8e76-faf503516e67

For issue 2:
1) remove properties   [group]="true"and groupKey="type" from html file
2) Open combobox
3) Observe that both the Apple having different lookupKey are shown as selected.

https://github.com/SAP/fundamental-ngx/assets/88182358/c28f291e-c321-45a8-8d75-2ac4c161a98d

#### Please provide stackblitz example(s).
Pls use [link](https://stackblitz.com/edit/angular-9qxxca-qhylee?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) 

#### Is there anything else we should know?
This is a customer issue for us , and we need this fix to further address the customer issue.

**Comment by I543348** [comment]
Hi Team , pls let me know in case of any queries so that we can start with the issue fix and remove "WIP"
Thanks much

**Comment by mikerodonnell89** [comment]
@I543348 you can remove the WIP status, on first glance I think this may be a problem with fundamental-ngx

**Comment by I543348** [comment]
Hi @mikerodonnell89 , 
could you pls confirm if its available for Angular 15 as well ?
coz i can only see the fix in [v0.48.0-rc.17](https://github.com/SAP/fundamental-ngx/releases/tag/v0.48.0-rc.17)
