### ISSUE TITLE
[Reopened][P2][Sourcing][Regression][Platform Table]: After scrolling and applying filter , the rows rendered are not correct

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11066]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
This issue has been reopened after fix for https://github.com/SAP/fundamental-ngx/issues/11057
This is  same as issue https://github.com/SAP/fundamental-ngx/issues/11002
Pls refer to comments https://github.com/SAP/fundamental-ngx/issues/11002#issuecomment-1846549440

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
core/ platform: 0.43.20

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
pls refer stackblitz link and steps in comment https://github.com/SAP/fundamental-ngx/issues/11002#issuecomment-1846549440

#### Is there anything else we should know?
This was working fine before issue fix for #11057 and after upgrading to 0.43.20. its broken again and replicable now

**Comment by N1XUS** [comment]
Hello @I543348
We have released version 0.43.21 with the fix for this behaviour. Please check that version.

**Comment by I543348** [comment]
This is working fine now.
Thanks
