### ISSUE TITLE
[WIP][P3.2][Sourcing]NGX Platform Table with more columns and virtual scroll - Scroll bar issue

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#11062]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Platform table with virtual scroll and more columns having a scrollbar issue. Ideally the scroll bar should stop but the flickering happens

#### Can you handle that on the application side
NO

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - v15.2.10
NGX- 0.43.20

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Add more columns more than 10+ which It should have both vertical and horizontal scroll

#### Please provide relevant source code (if applicable).
NA

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/xpgqsj-xmfydi?file=src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
NA

**Comment by droshev** [comment]
@prasad-userdev Can you answer to all the questions? Also the stackblitz is on the latest NGX. Is this intentional? if not can you update it?

**Comment by droshev** [comment]
here is an [example](https://stackblitz.com/edit/xpgqsj-lzcxs2?file=src%2Fapp%2Fplatform-table-virtual-scroll-example.component.ts) where the table has horizontal and vertical scrolling and no issue with scrolling. 
![table3](https://github.com/SAP/fundamental-ngx/assets/4380815/e64041b3-c861-4a9c-aa28-1c6ff37e7445)

**Comment by prasad-userdev** [comment]
Please check this
https://stackblitz.com/edit/xpgqsj-bbjgxb?file=src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html

**Comment by prasad-userdev** [comment]
I think the issue is with cell height. If we have more data in the cell or column width is less then the current issue appears but If the column width is more then the scroll works fine. Please refer the screen recording below. thanks!
https://github.com/SAP/fundamental-ngx/assets/107252602/16651d79-3b38-412e-a5bc-9024bfbda2fc

**Comment by droshev** [comment]
If you have this scenario where your table looks like that then you can consider the [responsive table](https://fundamental-ngx.netlify.app/#/platform/table/basic#responsive-columns)(the popin)

**Comment by prasad-userdev** [comment]
https://stackblitz.com/edit/angular-9qxxca-cqakkc?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html

**Comment by mikerodonnell89** [comment]
It does look like angular CDK virtual scrolling has an experimental feature `autoscroll` that supports virtual scroll with dynamic height rows. Something we should look in to and possibly replicate here

**Comment by mikerodonnell89** [comment]
After discussing with the team and investigating how some other libraries handle this, we believe the platform table's virtual scrolling should remain restrictive to functioning solely with rows of equal height. Because the table data cell (and therefore the height) can change at any time, and because we want to be able to allow for preserved state including scroll position, these advanced scrolling techniques can't work with rows of variable height. So, when dealing with data like this, we have to recommend using `[pageScrolling]` rather than `[virtualScroll]`

**Comment by droshev** [comment]
Reducing the prio to [P2] as the team is exploring other solutions.

**Comment by droshev** [comment]
@prasad-userdev any update? or maybe we close the issue?

**Comment by droshev** [comment]
We will close it, if a new issue appears we can discuss it in a new ticket
