### ISSUE TITLE
fd-datepicker does not align properly when used with fd-form-set

### ISSUE THREAD

**Issue by carlostekken** [SAP/fundamental-ngx#1107]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

fd-datepicker does not align properly when used with fd-form-set

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

angular: 7.2
fundamentals 0.8.0

#### If this is a bug, please provide steps for reproducing it.

Create a project using fd-panels and grid containers.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-b1guhy

#### Is there anything else we should know?

**Comment by JKMarkowski** [comment]
There are a lot of new versions of NGX. This issue is not reproducible anymore
