### ISSUE TITLE
[P3.2][Sourcing] Platform tree table: Parent cell text alignment issue

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#11089]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Tree structure with Parent cell where we have arrow and text, the text need to be properly aligned.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
NGX - 0.43.21
Angular - 15.2.10

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
<img width="691" alt="Screenshot 2023-12-14 at 10 36 14 AM" src="https://github.com/SAP/fundamental-ngx/assets/107252602/cb087083-1fc9-4089-88c0-5c4a087ca5b2">

#### Please provide relevant source code (if applicable).
NA

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-9qxxca-cqakkc?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.ts

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
NA

**Comment by droshev** [comment]
The ellipsis needs to be applied and cut the text

**Comment by prasad-userdev** [comment]
If you observe other cells, It is aligned properly. When other cells are aligned properly, I think It is not recommended to cut the text and add ellipsis

**Comment by droshev** [comment]
@N1XUS Can you check why we are not applying ellipsis to the table tree ? It breaks the tree.
