### ISSUE TITLE
[P3.1][Sourcing] PopOver alignment Issue - Popover for fdp-link alignment issue 

### ISSUE THREAD

**Issue by spprasad137** [SAP/fundamental-ngx#11090]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
Popover should work properly for fdp-link when link is opened at the corners of browser.
#### Can you handle that on the application side
No
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Create Event Page - Add one more items in Items table
then try to open popover by clicking Set Initial value or Add Term link when link text is at the end or half visible

Components used is <fd-popover> and <fdp-link>

<img width="922" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/153801405/2e486bed-9541-444e-84ce-8672339d75d3">

**Comment by droshev** [comment]
@spprasad137 Can you create a small stackbliz example?

**Comment by spprasad137** [comment]
Hi @droshev 

Please find the below stackblitz sample and also Issue reproducable screenshot.

<img width="960" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/153801405/b460be1b-1576-4936-bbc7-fe3e8e065ea0">

https://stackblitz.com/edit/ng4yxr?file=src%2Fapp%2Fplatform-table-virtual-scroll-example.component.ts,src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html

Steps to Reproduce : 
- In table, Link setInitial Value should be right end corner as shown in screenshot then try to open or click - popover not visible completely.

Same way in application popover not visible completely for text link as shown in below screenshot().
<img width="947" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/153801405/0098b4d7-7461-4101-8460-880493ee4907">

**Comment by droshev** [comment]
I don't see any issue. I used your stackblitz and set different options and all they were rendered properly:
<img width="1509" alt="Screenshot 2024-01-04 at 14 39 38" src="https://github.com/SAP/fundamental-ngx/assets/4380815/767397f5-cbb9-4d15-a48d-a29c867770e4">
<img width="1475" alt="Screenshot 2024-01-04 at 14 39 26" src="https://github.com/SAP/fundamental-ngx/assets/4380815/02b42e8a-cdb4-4083-8c55-ab03198da3db">
<img width="1415" alt="Screenshot 2024-01-04 at 14 39 13" src="https://github.com/SAP/fundamental-ngx/assets/4380815/a521df78-af3e-4e53-a36c-4d5c1d9d8f4a">
<img width="1456" alt="Screenshot 2024-01-04 at 14 38 53" src="https://github.com/SAP/fundamental-ngx/assets/4380815/e5144cfc-c013-4aa7-b8a1-37151a487181">
<img width="1464" alt="Screenshot 2024-01-04 at 14 38 34" src="https://github.com/SAP/fundamental-ngx/assets/4380815/edfbdf63-dfeb-4b33-8171-8381fbf62a23">


Btw, from accessibility point you should avoid using links for this scenario [`One of the most serious barriers is to create links that go nowhere. Developers sometimes use JavaScript to create dynamic menus that drop down when the user hovers over certain links with the mouse. `](https://webaim.org/techniques/hypertext/)

**Comment by spprasad137** [comment]
Hi @droshev,

Issue is still not resolved. Please follow the below steps to reproduce. 

**Steps to Reproduce :** 
           -     In table, Text "setInitialValue" link should be right end corner as shown in screenshot then try to open or click - popover not visible completely.

@droshev  @mikerodonnell89  Shall we connect over call to discuss on the same?

**Comment by spprasad137** [comment]
Hi @droshev/ @mikerodonnell89 ,

Issue is still not resolved, I have given the steps to reproduce. Could you please reopen the Ticket or schedule a call, will connect and discuss.

Steps to Reproduce :
- In table, Text "setInitialValue" link should be right end corner as shown in screenshot then try to open or click - popover not visible completely.
