### ISSUE TITLE
review Tabs usages in ngx lib

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#11091]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Describe your proposal.
Tabs Component has been deprecated, but it is used in other components(e.g. core and platform Dynamic Page) => it requires some refactoring. 
- [ ] find other usages if there are and think about how to tackle
- [ ] abstract the usage of IconTabBar (similar to fdp search field in shellbar)
- [ ] update the examples
- [ ] fix IconTabBarstackblitz examples

**Comment by N1XUS** [comment]
Additional functionality required:

- [ ] Tabs projection. Currently Icon Tab Bar is manually controlled by the application developer.
- [ ] Add `stacked` option
- [ ] Add `collapsible` option
