### ISSUE TITLE
Platform Table: programmitally added columns don't appear in the right order

### ISSUE THREAD

**Issue by muellerDana** [SAP/fundamental-ngx#11117]
Is this a bug, enhancement, or feature request?
bug

Briefly describe your proposal.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
I noticed it in Angular 17.0.7 and Fundamentals 0.46.1.

If this is a bug, please provide steps for reproducing it.
We add dynamic columns to the table. However, these are not entered at the position added in the columns array but are added at the end of the existing columns. So we can't set an order for the columns.

Please provide relevant source code if applicable.
I have reproduced it in the [stack blitz example](https://stackblitz.com/edit/2fwcob?file=src%2Fapp%2Fplatform-table-default-example.component.ts).

**Comment by N1XUS** [comment]
Hello @muellerDana. I recommend using `setColumns` method of the `TableComponent`. This way you can ensure the correct order of the columns. https://stackblitz.com/edit/2fwcob-jeoy8a?file=src%2Fapp%2Fplatform-table-default-example.component.ts,src%2Fapp%2Fplatform-table-default-example.component.html
