### ISSUE TITLE
<fd-combobox> Localization issues

### ISSUE THREAD

**Issue by C5370748** [SAP/fundamental-ngx#11120]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Tooltip text navigation-down-arrow for (icon of the button on the right of the input field) is not localized.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
![navigation-down-arrow](https://github.com/SAP/fundamental-ngx/assets/154427205/f16ab952-6758-44a6-958f-3b89aa8fa762)

**Comment by droshev** [comment]
has been fixed, it should be in the latest 0.42.x
