### ISSUE TITLE
Multiselect (multiple checkbox) Value Help Dialog to be integrated to input field and not as a separate button 

### ISSUE THREAD

**Issue by I553351** [SAP/fundamental-ngx#11125]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Describe your proposal.

Currently multi select (multiple checkbox enabled) value help dialog is implementable only with a separate clickable button ("Open Value Help Dialog").

Referance : https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog#multi-input

![Screenshot 2023-12-20 at 18 54 23](https://github.com/SAP/fundamental-ngx/assets/154462301/ff4bee88-777e-42e7-a3ef-ea9a6def2d82)

Proposal is : the multiselect value help dialog should be integrated with the input field itself without a separate button to open the dialog. i.e, clicking the input field icon button should open up the value help dialog instead of opening the multiinput dialog. The multiinput dilaog and the separate button "open value hlep dialog" are no more needed in that case.

![Screenshot 2023-12-20 at 18 50 00](https://github.com/SAP/fundamental-ngx/assets/154462301/735cf3b6-2327-44df-b2b7-cad975262d4c)
![Screenshot 2023-12-20 at 18 47 38](https://github.com/SAP/fundamental-ngx/assets/154462301/19047bab-5e7c-4f32-b773-871d9544409b)

And the selected options should be displayed in the input field as before.

![Screenshot 2023-12-20 at 18 47 05](https://github.com/SAP/fundamental-ngx/assets/154462301/57bb980e-c3cf-474d-969c-e2d1dbca806a)

The single select vhd works this way -With an input field and upon clicking the input icon it opens up the vhd. The proposal for multi select is to behave in a similar way .

![Screenshot 2023-12-20 at 19 09 35](https://github.com/SAP/fundamental-ngx/assets/154462301/16eb0346-baae-4b29-b575-f5318995d7a1)

#### Can you handle that on the application side

No

#### Did you check the documentation and the API?

Yes
#### Did you search for similar issues?

Could not find.

**Comment by N1XUS** [comment]
https://stackblitz.com/edit/xuaexk?file=src%2Fapp%2Fplatform-vhd-multi-input-example.component.html%3AL9

**Comment by julia-siegl** [comment]
Hi @N1XUS thank you for providing the example!

I found however some issues when multiple times updating the search from the input bar and the vhd. Then the changes in the input bar are not properly reflect in the vhd:

https://github.com/SAP/fundamental-ngx/assets/143191726/c013b146-8abf-4037-b5fe-d28001d7cff0

Could you please have a look at this as well? Thank you in advance.
