### ISSUE TITLE
[P2][Sourcing][Accessibility] Search in filters not working by pressing Enter in Value Help Dialogue

### ISSUE THREAD

**Issue by vidworks** [SAP/fundamental-ngx#11123]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Pressing enter when searching thru filters should show the results

#### Can you handle that on the application side
No.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.43.21

#### If this is a bug, please provide steps for reproducing it; the exact components you are using; { PlatformValueHelpDialogModule  from '@fundamental-ngx/platform/value-help-dialog';

https://github.com/SAP/fundamental-ngx/assets/136386704/376d2f54-0ba6-45f2-9786-209ea4661e27

**Comment by droshev** [comment]
It filter out when you press `Go` - same does ui5
