### ISSUE TITLE
[issue][core][Object Status] click over object status make it white, looks like it disappear 

### ISSUE THREAD

**Issue by lpgarzonr** [SAP/fundamental-ngx#11146]
When the user click on the Object Status Icon/Text Only, the [Object Status](https://fundamental-ngx.netlify.app/#/core/object-status) `color` change to white due to the focus styles giving the appearance that  it disappear, is should stay within the same color. 

#### Which versions of Angular and Fundamental Library for Angular are affected?
Fundamentals 0.48.0-rc.21
Angular "17.0.4
Component https://fundamental-ngx.netlify.app/#/core/object-status

#### Please provide stackblitz example(s).
![image](https://github.com/SAP/fundamental-ngx/assets/6719251/54dd64e7-7f14-48a8-93b3-cc3b1eaa5fe8)
https://stackblitz.com/edit/ewb8kw?file=src%2Fapp%2Fobject-status-default-example.component.html

**Comment by N1XUS** [comment]
Fixed with https://github.com/SAP/fundamental-ngx/commit/3eacc6d2960a5bbc0ab5f75f4074c54fb7ddfe27
In case you still want for Object Status to be clickable, please refer to `[clickable]` input property of the Object Status component.
