### ISSUE TITLE
fd-switch not working as expected

### ISSUE THREAD

**Issue by aaasarthak** [SAP/fundamental-ngx#11147]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When checked property is false, it is showing as - 
![image](https://github.com/SAP/fundamental-ngx/assets/45348322/ae46ab36-fc80-43c0-b87a-8d6f3ac4cafe)

When checked property is true, it is showing as  - 
![image](https://github.com/SAP/fundamental-ngx/assets/45348322/67f0f4c3-6721-4325-ad6b-fe33fc6d7cfb)

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 16
Fundamental version - 0.47.4
fundamental styles - 0.32.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
The switch is not working as expected

#### Please provide relevant source code (if applicable).
<fd-switch [(ngModel)]="checked"></fd-switch>

#### Did you check the documentation and the API?
Yes, it looks fine there. And used in the same way.

**Comment by N1XUS** [comment]
@aaasarthak Could you check if your app uses rtl direction? Such appearance happens in rtl mode only

**Comment by aaasarthak** [comment]
> @aaasarthak Could you check if your app uses rtl direction? Such appearance happens in rtl mode only

We are not using RTL direction, as other components are working fine as expected in LTR direction. Only The switch component started behaving as RTL after the upgrade from version 0.45.1 to 0.47.4. With the old version, this switch was working perfectly fine.
