### ISSUE TITLE
[P3.2][Sourcing] <fd-multi-input> is missing the attribute "iconTitle" to update the button tooltip to a meaningful string

### ISSUE THREAD

**Issue by nwu-eden** [SAP/fundamental-ngx#11164]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Describe your proposal.
when we use the <fd-multi-input>, we can't update the button tooltip to a meaningful string..
we want to add the attribute "iconTitle" so that we can update the button tooltip.
<img width="262" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/90431788/8bad73d0-5d97-4de5-9d4a-39ff40ed2e2b">

#### Can you handle that on the application side
no, we can't

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Have checked all versions, all are affected.
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
just use <fd-multi-input>
#### Please provide relevant source code (if applicable).
None
#### Please provide stackblitz example(s).
None
#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
None
#### Is there anything else we should know?
None

**Comment by mikerodonnell89** [comment]
The fd-multi-input has the `title` input:
![Screenshot 2024-01-04 at 3 06 08 PM](https://github.com/SAP/fundamental-ngx/assets/2471874/6f9ebbef-10f0-4834-8aed-103d951e5440)

```
<fd-multi-input
    inputId="multiInput"
    [dropdownValues]="['Apple', 'Banana', 'Pineapple', 'Tomato', 'Kiwi', 'Strawberry', 'Blueberry', 'Orange']"
    placeholder="Search here..."
    (searchTermChange)="searchTermChange($event)"
    [(ngModel)]="selected"
    title="Multi input title"
></fd-multi-input>
```

**Comment by nwu-eden** [comment]
Hi @mikerodonnell89 , the attribute "title" is only for the input box tooltip, not for the icon,,, we want to update the tooltip of the icon on the right side, not on the input box on the left side..
