### ISSUE TITLE
create @fundamental-ngx/schematics library

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-ngx#11165]
We have a lot of the schematics and their helpers essentially doing the same thing. We need to take them into single library and call that library's schematics from other libs. e.g from core, platform and etc.

The similar pattern is used in Angular and Material packages. This greatly reduces duplications and parallel implementations. Also that package will be the home for the ng-update skelleton schematics. I mean that we need to have generic schematics for things like "renamed ClassName" or "renamed selector". This kinds of schematics will result in far easier update cycles for the end users and the architecture will ease our development of such migrations

estimated work 4d

**Comment by droshev** [comment]
we can consider that in the future, closing it for now
