### ISSUE TITLE
ngx-file-uploader reuploading file does not work.

### ISSUE THREAD

**Issue by gsaukov** [SAP/fundamental-ngx#11168]
Hi team, where i can report a bug regarding [ngx-file-uploader](https://fundamental-ngx.netlify.app/#/core/file-uploader)? It stops adding file after file was added and then removed.
Use simple file upload:
1. Select and add file,
2. Remove added file,
3. Try again select and add file
4. It is impossible, selected file is not added.

**Comment by droshev** [comment]
@gsaukov how do you remove the added file?

**Comment by gsaukov** [comment]
Hi @droshev,
I use buttons, Clear() and  ngModel.
However it only reproduces when you reupload same file multiple times.

I use MacOS 14.2.1 (23C71) and Chrome 120.0.6099.129 (Official Build) (arm64) it is also reproducible with Safari Version 17.2.1 (19617.1.17.11.12)

![image](https://github.com/SAP/fundamental-ngx/assets/48772739/6aa93aa8-09b9-4287-af7a-aa172d158ca0)
