### ISSUE TITLE
Enhancement: Value help dialog with platform table

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#11163]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Describe your proposal.
Currently, Value Help Dialog uses core table inside, which is a base for platform table.
Core table does not support such rich features that Platform Table supports: lazy loading, virtual scroll, tree, etc.
Proposal is to migrate Value Help Dialog component from using Core table to Platform table and extend API to support more rich features from Platform Table.

**Comment by droshev** [comment]
maybe downport to ng15?

**Comment by droshev** [comment]
closing and will wait if users request that
