### ISSUE TITLE
Reopened issue 10869: [P3.1][Sourcing][Accessibility][fdp-table] Associated Table Column header not being read for empty table cell values

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11167]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When using reader to access empty table cell, its associated table column header name should be announced.
This is happening when both table cell has some text or when its empty cell
Since #10869 is closed , reopening as a new issue

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/ platform: 0.43.24

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
pls use [link](https://stackblitz.com/edit/angular-9qxxca-7pyeha?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) 

#### Please provide relevant source code (if applicable).
pls refer above link

#### Please provide stackblitz example(s).
pls refer above link

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes this has been reported by ATL team

**Comment by nikolay-kolarov** [comment]
Hello @I543348,

I tried the [link](https://stackblitz.com/edit/angular-9qxxca-7pyeha?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) on Windows in Edge with Jaws 2023 and the screen reader reads normally the column headers. 
Could you please provide more info on what you use as software, OS, browser? Also the exact steps or video recording showcasing the issue?

Thanks,
Nikolay

**Comment by I543348** [comment]
> Hello @I543348,
> 
> I tried the [link](https://stackblitz.com/edit/angular-9qxxca-7pyeha?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) on Windows in Edge and Chrome with Jaws 2023 and the screen reader reads normally the column headers. Could you please provide more info on what you use as software, OS, browser? Also the exact steps or video recording showcasing the issue?
> 
> Thanks, Nikolay

Sure @nikolay-kolarov 
steps
1) reach table using keyboard
2) traverse through data cells 
3) observe that only cell values are being read however, column headers are not getting associated
For eg: It has to read 5 "Price" when focus is on 5 cell under Price column
[Screen Recording 2024-01-03 at 7.56.06 PM.mov.zip](https://github.com/SAP/fundamental-ngx/files/13820098/Screen.Recording.2024-01-03.at.7.56.06.PM.mov.zip)

**Comment by sagar7259** [comment]
Hello Nikolay,

We are using the latest version of chrome (Version 120.0.6099.130 (Official Build) (64-bit))
Also, the JAWS version is JAWS 2023.2307.37 ILM 64bit for Windows.
This issue is also reproducible using voiceover in MAC

The steps are in previous comment.

**Comment by nikolay-kolarov** [comment]
Hi @sagar7259,

Do you use [this link](https://stackblitz.com/edit/angular-9qxxca-7pyeha?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) for reproduction?
If yes, will it be possible to record me a short video?

I use the latest chrome (I updated it today to Version 120.0.6099.200, but with the previous version it was also ok) and the same Jaws version as you. So I assume we are doing/testing something differently.

Here is a video of my test: https://github.com/SAP/fundamental-ngx/assets/17043004/a9bec7c8-72fa-43cb-bdec-6242a69901f4

PS: There is one known issue in chrome with tables (https://bugs.chromium.org/p/chromium/issues/detail?id=1499595), but it is related with aria-labelldby and here we do not have this in this concrete sample.

Thanks,
Nikolay

**Comment by sagar7259** [comment]
Hello Nikolay,

The issue is no more reproducible in the latest version and also in the application as well. Hence this can be closed.
Thanks for your comments.

Regards,
Sagar
