### ISSUE TITLE
DynamicPageHeaderComponent styles differ across operating systems

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#11171]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
The font width of the title in the DynamicPageHeaderComponent in the Chrome browser is different on different operating systems (even in the documentation examples). On MacOS, the font width is thicker than on Windows. Is this behavior intentional or a bug?

1. on Windows 
![DynamicPageHeaderComponent on Windows](https://github.com/SAP/fundamental-ngx/assets/86781159/578908cf-d189-471d-9f8f-a78a40e1c818)
2. on macOS 
![DynamicPageHeaderComponent on macOS ](https://github.com/SAP/fundamental-ngx/assets/86781159/79982d62-e72b-4068-a8ba-688c95e0951e)

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.44.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Set `title` input on DynamicPageHeaderComponent and open on the different operating systems in the Chrome browser.

#### Please provide stackblitz example(s).
https://sap.github.io/fundamental-ngx/#/core/dynamic-page

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

**Comment by droshev** [comment]
@programister42 that is usually due to not loading all the font files. @N1XUS did a solution for our schematics. if you didn't use them you can check out what he did and do the same thing in your application
