### ISSUE TITLE
[P2][Sourcing] fdp-table `enableRowHeaderRole` @input is missing in  both 0.43.24 and 0.48.0

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#11177]
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
We have a new `@Input enableRowHeaderRole` for Platform Table since v0.42.0-rc.3 (PR https://github.com/SAP/fundamental-ngx/pull/9956)

But such input property is missing in latest ng-15 downport 0.43.24. it is missing in 0.48.0-rc.29 too.

This property got removed in this PR: https://github.com/SAP/fundamental-ngx/pull/9991

![Oscar ScreenCapture 2024-01-04 at 17 44](https://github.com/SAP/fundamental-ngx/assets/7035787/0552b095-c714-42ed-b524-a75392dcc64a)

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

```
    "@angular/core": "15.2.10",
    "@fundamental-ngx/core": "0.43.24",
    "@fundamental-ngx/platform": "0.43.24",
```

**Comment by mikerodonnell89** [comment]
@oscargong this can now be handled with the `role` input on the `fdp-column-header` component ([api link](https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/api)):
![Screenshot 2024-01-08 at 4 37 33 PM](https://github.com/SAP/fundamental-ngx/assets/2471874/c484a7ce-2b41-4786-bb06-caeab1da4c0d)
