### ISSUE TITLE
[Sourcing] [P1] filter on value help dialog component

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11178]
#### Is this a bug, enhancement, or feature request?
BUG

#### Describe your proposal.
1. In value-help-dialog component, filter search is a free text search. For eg: filter dropdown values are invited, not invited and if we try to search entries with invited value, then even not invited entries get filtered.
2. How could we hide the columns in value-help-dialog.

#### Can you handle that on the application side
NO

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
angular- 15.2
NGX - 0.43.24

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Step to reproduce search issue here [click here](https://stackblitz.com/edit/angular-ugca8x-tigsbs?file=src%2Fapp%2Fdynamic-page-tabs-example.component.ts)
2. [Not able to view table in 200% zoom]
<img width="1723" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/110370099/42010b9b-18a3-4644-be4f-750cad1254e5">
3. Replicate the freeze, unfreeze issue here https://stackblitz.com/edit/angular-ugca8x-isacnh?file=src%2Fapp%2Fdynamic-page-tabs-example.component.html

**Comment by droshev** [comment]
1. the user has options to include filters next to the search

**Comment by N1XUS** [comment]
For the first item: https://stackblitz.com/edit/angular-ugca8x-sefsk5?file=src%2Fapp%2Fdynamic-page-tabs-example.component.ts

**Comment by droshev** [comment]
closing the ticket as Denis offered solutions how to achieve the request
