### ISSUE TITLE
Combobox Issue when used in Reactive Form

### ISSUE THREAD

**Issue by pranay-gupta-01** [SAP/fundamental-ngx#11183]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.

1. When using [communicateByObject]="true" with custom objects for dropdownValues, clicking on a dropdown item is not updating the form's value. 
2. Once a particular value is selected from dropdownValues, the other options using the dropdown arrow disappear and the only way to make a selection again is to erase the currently selected value using the cursor. 

The above is not observed with the same implementation when using the fd-select. 

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 16.2.12
NGX: 0.46.1
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
These are observed when using fd-combobox with reactive form. 
Specifically, when [communicateByObject]="true" is used with custom objects for dropdownValues, the form value is not updated on the first try, but this goes away on subsequent tries. 
Please refer to the recordings for more info. 

#### Please provide relevant source code (if applicable).

https://github.com/SAP/fundamental-ngx/assets/155584127/8d73ccf1-f5c1-4e44-acd6-085de5ee70f4

https://github.com/SAP/fundamental-ngx/assets/155584127/ee07c195-a50e-423f-94c0-1f6e324a90ed

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
NA
#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes

**Comment by N1XUS** [comment]
Hello @pranay-gupta-01.
Could you please provide a stackblitz example so we could analyze source code of this recordings? It will definitely help us to speed things up a lot.

**Comment by droshev** [comment]
@pranay-gupta-01 Can you follow up with @N1XUS request?

**Comment by pranay-gupta-01** [comment]
Hello @N1XUS,
I've been trying to use the stackblitz [examples](https://stackblitz.com/run?file=package.json) linked in the fundamental library [page](https://fundamental-ngx.netlify.app/#/core/combobox), but they don't seem to be compiling. Do you have a working stackblitz with the fundamental library dependencies I can use to illustrate the bug?
Thank you.

**Comment by dreamweiver** [comment]
@pranay-gupta-01  @droshev , looks like this issue is similiar to the one which was fixed sometime back,  https://github.com/SAP/fundamental-ngx/pull/12207

@pranay-gupta-01 , can you confirm this on latest version of the library and close the bug?
https://sap.github.io/fundamental-ngx/#/core/combobox#reactive-form
