### ISSUE TITLE
[P2][Sourcing] `visible` input for `fdp-column` is not working when not using `ngFor`

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#11201]
#### Is this a bug, enhancement, or feature request?
bug, also can be a feature request

#### Describe your proposal.
The `visible` input for `fdp-column` is not working when not using `ngFor`

#### Can you handle that on the application side
We could use `[initialVisibleColumns]` input as a workaround. But when the columns are generated dynamically, this can be expensive, sometimes, impossible.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
```
        "@fundamental-ngx/cdk": "0.47.4-rc.10",
        "@fundamental-ngx/platform": "0.47.4-rc.10",
        "@fundamental-ngx/core": "0.47.4-rc.10",
        "@fundamental-ngx/i18n": "0.47.4-rc.10",
```

#### Please provide relevant source code (if applicable).
libs/platform/src/lib/table/components/table-column/table-column.component.ts
```typescript
    /** Initial visibility state of the column. Default `true`. */
    @Input()
    visible = true;
```
#### Please provide stackblitz example(s).
https://stackblitz.com/edit/honfwe?file=src%2Fapp%2Fplatform-table-custom-width-example.component.html

description is set to false, but still visible on the initial rendering.

```html

  <fdp-column
    [visible]="false"
    name="description"
    key="description"
    label="Description"
    width="30rem"
  >
  </fdp-column>
```

**Comment by droshev** [comment]
@oscargong Are you looking a change only for version `0.47`?

**Comment by oscargong** [comment]
> @oscargong Are you looking a change only for version `0.47`?

Hi Deno, no, we need this for 0.43 ng-15 now. But we will upgrade our application's Angular, we will need this for 0.48 as well.
