### ISSUE TITLE
Dropdown when changing resolution upper line of button disappear 

### ISSUE THREAD

**Issue by neihynocnir** [SAP/fundamental-ngx#1121]
#### Is this a bug, enhancement, or feature request?
it's a bug

#### Briefly describe your proposal.
When using the Dropdown component and opening  with Firefox and changing the resolution the upper line of the button is disappearing,  

#### Which versions of Angular and Fundamental NGX are affected?
Version 0.6.0

#### If this is a bug, please provide steps for reproducing it.
When using the Dropdown component and opening  with Firefox or even changing the resolution in Chrome the upper line of the button disappear.  

Screenshots:
![Screen Shot 2019-08-13 at 11 45 47 AM](https://user-images.githubusercontent.com/39598672/62966258-a88c6380-bdd4-11e9-9190-4332265a3fd5.png)
![Screen Shot 2019-08-13 at 11 46 27 AM](https://user-images.githubusercontent.com/39598672/62966259-a88c6380-bdd4-11e9-8416-7e5c28fb4af8.png)

**Comment by JKMarkowski** [comment]
Hi @neihynocnir, thanks for noticing this issue. Would you mind creating this ticket on [fundamental-styles](https://github.com/SAP/fundamental/issues) library? This is mostly css bug and ngx library is not responsible for styling.
