### ISSUE TITLE
[Sourcing][P3.2] Screen Reader not reading Column visibility dialogue items in list properly. 

### ISSUE THREAD

**Issue by tariq123a4** [SAP/fundamental-ngx#11226]
#### Is this a bug, enhancement, or feature request?

Bug

#### Describe your proposal.

Screen reader is not reading whether the list item is selected or not and also is not reading the item number of the item in the list.  Please refer to the screenshot below. 

<img width="1698" alt="Screenshot 2024-01-16 at 12 05 46 PM" src="https://github.com/SAP/fundamental-ngx/assets/156745815/6ee7110a-91c1-4f68-bb60-7afaad714ffa">

It should read the item number and whether it is selected or not. For example : "Item 1 of 5, Selected, Name, Clickable' 

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

angular- 15.2
NGX - 0.43.24

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Please use this link : [Click Here](https://stackblitz.com/edit/zcsxrs?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html) 

Open the column visibility dialog and notice the issue using a screen reader. 

#### Please provide stackblitz example(s).

[Click Here](https://stackblitz.com/edit/zcsxrs?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html) 

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 

It should read the item number and whether it is selected or not. For example : "Item 1 of 5, Selected, Name, Clickable' 

#### Did you check the documentation and the API?

Yes

**Comment by mikerodonnell89** [comment]
@tariq123a4 I'm unable to load the stackblitz, are you still seeing this issue? Perhaps try another version? Not seeing it myself:
![Screenshot 2024-01-30 at 3 59 21 PM](https://github.com/SAP/fundamental-ngx/assets/2471874/494136f4-48da-4fbd-936a-f9ecc4583183)

**Comment by tariq123a4** [comment]
Hi @mikerodonnell89 , looks like the issue has been fixed in the newer versions. Thanks.
