### ISSUE TITLE
Observable Async - Multi Input field value is not displayed properly

### ISSUE THREAD

**Issue by shajihamza1988** [SAP/fundamental-ngx#11227]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Describe your proposal.

In Observable Async - Multi Input field(https://fundamental-ngx.netlify.app/#/core/multi-input#observable-async), when I use a search API to get the dropdown list based on the searched keyword from backend, at first the preselected checkbox is shown properly but when the updated data is received from backend, the preselected checkbox is cleared off. I noticed the observable async work fine with limited static json API, but if the API take a bit more time, the multi input field fails to show the preselected options.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.48.0-rc.36

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://fundamental-ngx.netlify.app/#/core/multi-input#observable-async

#### Please provide relevant source code (if applicable).
https://fundamental-ngx.netlify.app/#/core/multi-input#observable-async

**Comment by N1XUS** [comment]
Hello @shajihamza1988. I've tried increasing delay for the example you've provided by 10 seconds, and couldn't achieve the result you describing. Could you compose a stackblitz example where the issue is reproducible?

**Comment by droshev** [comment]
@shajihamza1988 Can you follow up with what @N1XUS asked?

**Comment by droshev** [comment]
@shajihamza1988 if you are able to create a stackblitz with the issue, feel free to report a new ticket
