### ISSUE TITLE
[Sourcing][P1] How do we limit the selection of rows in value-help-dialog component

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11225]
#### Is this a bug, enhancement, or feature request?
 Bug

#### Describe your proposal.
How do we limit the selection of rows in value-help-dialog component. Lets say user has 100 rows in value help dialog component with multiple choice enabled. but they choose to restrict the user to select only 20 maximum rows. For this to achieve we do not have any implementation from NGX component.

#### Can you handle that on the application side
We can show error only after they confirm the selection and not during check box selection.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
angular- 15.2
NGX - 0.43.24

**Comment by rvamudha** [comment]
Hi @droshev  ,
We are trying to handle the list selection validation on click of 'OK' as workaround, we can able to throw error message but the value help dialog got closed 
we need 
> On click of 'OK' button within Value help dialog, validation of selection and throw error based on the validation  - this is possible now but value help dialog got closed
> Keep the dialog open, so the end user can correct / limit the number of selection - This is not possible now
![image](https://github.com/SAP/fundamental-ngx/assets/143414187/a3e590b3-f142-4d07-97ea-745bd80caca9)

Please let us know if you need more details. 
Regards,
Amudha R V

**Comment by rvamudha** [comment]
Hi @droshev  ,
We could able to throw validation error but it closes the Dialog, we this to be open so that end user can correct their selection.
Best Regards,
Amudha R V
