### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-264.1][WIP] Within settings dialog ‘User account’  and 'Appearance' tabs are read out as ‘Link’.

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11248]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
https://sap.github.io/fundamental-ngx/#/platform/settings-generator. Within NGX platform settings dialog ‘User account’  and 'Appearance' tabs are read out as ‘Link’. Visual appearance of ‘User account’  and 'Appearance' UI is as ‘tab’, hence reading as link is confusing the user.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader easily can check NGX platform settings dialog ‘User account’  and 'Appearance' tabs are read out as ‘Link’.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

Please check the tab bar spec, as according to it those needs to be tabs.
You can also have a look at the icon tab bar in UI5: https://ui5.sap.com/#/entity/sap.m.IconTabBar/sample/sap.m.sample.IconTabBar

Best Regards,
Nikolay

**Comment by droshev** [comment]
the component being used is https://fundamental-ngx.netlify.app/#/core/list#navigation It needs further discussion.

**Comment by mikerodonnell89** [comment]
The list with navigation items is no longer using link roles, closing this issue
