### ISSUE TITLE
[fd-dialog] When using DialogRef.afterClosed - Escape, Backdrop, Navigation Change causes Observable errors

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#11240]
Hello, fundamental-ngx Team.

Our team is currently developing the angular application with **"@fundamental-ngx/core": "0.44.0" and "@angular/core": "^16.2.0".**

We received a requirement to display a confirmation dialog with two buttons - "Confirm" and "Close". We found out, that there is an **afterClosed observable**, that we can use to manage the logic, that should be handled after a user do any action inside the dialog:

```typescript
@Component({
	selector: 'generic-confirmation-dialog',
	templateUrl: './generic-confirmation-dialog.component.html',
	styleUrls: ['./generic-confirmation-dialog.component.scss'],
	standalone: true,
	imports: [DialogModule, TitleModule, BarModule],
})
export class GenericConfirmationDialogComponent {
	public readonly dialogRef = inject(DialogRef);

	public onConfirm(): void {
		this.dialogRef.close('confirmed');
	}

	public onClose(): void {
		this.dialogRef.close('closed');
	}
}
```

Also we have a service to open that dialog with a such method:
```typescript
        public openGenericConfirmationDialog$({
		title,
		text,
	}: {
		title: string;
		text: string;
	}): Observable<unknown> {
		const dialogRef = this._dialogService.open(GenericConfirmationDialogComponent, {
			data: {
				title,
				text,
			},
		});
		return dialogRef.afterClosed.pipe(
			filter((val) => val === 'confirmed'),
			catchError(e => {
				console.log(e)
				// e = undefined  - navigation change?
				// e = escape
				// e = backdrop

				// I disabled errors with `return of()`
				// So that they do not pop up in the app error interceptor
				// but because of that the real errors are skipped now
				return of();
			})
		);
	}
```

And we are questioning why does the error appear, if a user press escape button or click backdrop or change the navigation the error appears, which is popping app in the **global angular error interceptor**, that is used in our application.
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/fd8d577b-1807-4f2e-965b-bf5df8e9dc9d)
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/da9df9b8-6bf2-4512-9da7-2f030b3aee0f)
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/40647086-3842-4b22-8217-17d2bdaef89d)

I checked the library code and it seems like [DialogRef.dismiss](https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dialog/base/dialog-ref-base.class.ts#L38-L40) throws an error.

### 2. If a user press esc, click backdrop, change navigation, is it logically an error?

I also looked into the [dialog class](https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dialog/base/dialog-base.class.ts)

And, yeah, it seems like those events, that I described, call .dismiss() under the hood

- [Escape press - .dismiss('escape')](https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dialog/base/dialog-base.class.ts#L78-L84)
- [Backdrop click -  .dismiss('backdrop')](https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dialog/base/dialog-base.class.ts#L86-L92)
- [Navigation change - .dismiss()](https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dialog/base/dialog-base.class.ts#L130-L139)

**Comment by N1XUS** [comment]
Hello @egorwow70. I've created a PR for enum values of the dismiss reason. As to the usage of the `error` method. I would say it is done by a historical reasons long time ago, and since lots of components are currently relying on that functionality, refactoring it would seem like not a best idea. I would suggest you adding an exception list to your `app-error-handler.service.ts`.
