### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-255.1] There is no text alternative provided to ‘Back' Icon button within 'Filter By' dialog.

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11242]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
NGX Platform Table, We have filter option in tool bar on click of Filter icon we get Filter dialog prompt. If we select any field in from filter by option then we get option of Filter by: field. Along with that we can see back arrow button also. There is no text alternative provided to this ‘Back' Icon button within 'Filter By' dialog.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
NGX Platform Table toolbar menu filter option
NGX Platform Table, We have filter option in tool bar on click of Filter icon we get Filter dialog prompt. If we select any field in from filter by option then we get option of Filter by: field. Along with that we can see back arrow button also. There is no text alternative provided to this ‘Back' Icon button within 'Filter By' dialog.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes
#### Is there anything else we should know?
Attaching screenshot for references
![Uploading Screenshot 2024-01-21 at 12.19.35 PM.png…]()

**Comment by mikerodonnell89** [comment]
Fixed by https://github.com/SAP/fundamental-ngx/pull/11658 and https://github.com/SAP/fundamental-ngx/pull/12197
