### ISSUE TITLE
[Accessibility: ACC-264.1] Tab strips: Incorrect tutor message 

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11258]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/core/tabs
Whenever we access tabs then  ‘To switch pages, press control+ Page down’  is read out 
Only relevant message about the UI must be announced for the UI.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader can check by implementing similar case. Just use multiple tab and and click these tab. Screen reader read  ‘To switch pages, press control+ Page down’  along with tab name.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

**Comment by droshev** [comment]
@JyotiKumari1507 Tabs has been deprecated. can you test and validate the IconTabBar?
