### ISSUE TITLE
popover - not listening to menu clicks and get detached from its control

### ISSUE THREAD

**Issue by kandarp-sap** [SAP/fundamental-ngx#1125]
#### Is this a bug, enhancement, or feature request?
This is a bug I guess. I am using the latest version
Currently, I have implemented multilevel side-nav-menu in popover-body.
However when I open / close submenu, popover-body get detached from its controller.

Following is the code of the component's template. 

```
    <fd-popover [(isOpen)]="isOpen" [closeOnOutsideClick]="true" [focusTrapped]="true" placement="top"
        [noArrow]="false" title="top">
        <fd-popover-control>
            <button fd-button [glyph]="'add'" class="fd-image--circle"></button>
        </fd-popover-control>
        <fd-popover-body>
            <fd-side-nav *ngFor="let component of componentWithTasks">
                <fd-side-nav-item>
                    <a fd-side-nav-link [hasSublist]="true">{{component.name}}</a>
                    <div fd-side-nav-sublist>
                        <span *ngFor="let task of component.tasks">
                            <div fd-side-nav-subitem>
                                <a fd-side-nav-sublink (click)="addStep(task)">{{task.name}}</a>
                            </div>
                        </span>
                    </div>
                </fd-side-nav-item>
            </fd-side-nav>
        </fd-popover-body>
    </fd-popover>
```
Following is the screenshot that shows an issue. Where opend popover get detached when I tried to open submenu.

![Screenshot 2019-08-15 at 16 23 22](https://user-images.githubusercontent.com/51914152/63101324-1d989e00-bf79-11e9-8594-c008a18ea0f8.png)

What are the possible workarounds for that?

**Comment by MattL75** [comment]
There is a method `updatePopover()` in the component API which refreshes the positioning. You could try calling that when something is opened/closed.

**Comment by JKMarkowski** [comment]
Hi @kandarp-sap, we can't consider it as a bug. There was need to use `updatePopover()` method, as Matt mentioned. This method's example will be soon in popover site.
