### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-264.1][WIP]Table: Region Information and tabular list container not mentioned.

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11263]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/platform/table/basic
When the first interactive element under the tabular section receives focus, tabular list container must be mentioned along Region/Heading information. But its not happening

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader can check by implementing similar case. Just use table with search or few button in toolbar and try to access first button/search as it is the first element under the tabular section , the user must be informed by screen reader about the existence table by mentioning as ‘Tabular list container’ and also region/heading information.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

**Comment by nikolay-kolarov** [comment]
Hi @JyotiKumari1507,

Could you please provide info where exactly you expect such a tabular list announcement and why? Maybe you can add a screenshot?
The table here has a grid role and is not a list.

Thanks,
Nikolay

**Comment by JyotiKumari1507** [comment]
@nikolay-kolarov @droshev  Please refer screenshot of screen reader provide. As per accessibility team, When the user access the ‘Rotate’ button within the tabular section ‘Key Encryption Keys’, as it is the first element under the tabular section , the user must be informed about the existence table by mentioning as ‘Tabular list container’ and also region/heading information.
<img width="269" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/157268666/329f9427-7907-44fa-ad6b-61e447001553">

**Comment by nikolay-kolarov** [comment]
Hi @JyotiKumari1507,
HI @droshev,

On the provided link (https://sap.github.io/fundamental-ngx/#/platform/table/basic) what you have is a grid and it will be announced when you focus the first cell in it:

![image](https://github.com/SAP/fundamental-ngx/assets/17043004/3a668100-9e02-4046-99e6-e803ad4afe28)

It is the same as in UI5: https://ui5.sap.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Selection

What you focus on top is a toolbar and you get the announcement that you are in a toolbar.
So from my point of view, the implementation is ok.

Best Regards,
Nikolay

**Comment by MeghanaVernekar** [comment]
Hello Colleague's,
Retested the issue with the new URL provided: https://qa.cobalt.ariba.com/emc/. and the issue is partially fixed. observed that 
1. for **'Key Encryption Keys (37)'** the tabular header is not conveyed.
2. Toolbar is conveyed for both the tables.

Attached Evidence for reference.
![image](https://github.com/SAP/fundamental-ngx/assets/172006721/43cdc861-0797-48c0-a701-0163a88df1f3)

Regards,
Meghana.

**Comment by droshev** [comment]
Can you open a new ticket and creating a stackblitz with the issue?

**Comment by divyamalhotra488** [comment]
Created new defect: https://github.com/SAP/fundamental-ngx/issues/12045
