### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-264.1][WIP] Edit field: place holder value not read.

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11277]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/core/textarea
The place holder value for the textarea field is not conveyed. The label and the place holder value must be conveyed for all edit fields.
#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader can check by implementing similar case. Just use textarea with place holder. Placeholder won't be read by screen reader

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

#### Is there anything else we should know?

**Comment by droshev** [comment]
@JyotiKumari1507 Can you provide more specific input? It is not very clear what the issue is

**Comment by JyotiKumari1507** [comment]
@droshev In Text area we provide place holder. But during testing by Accessibility team , screen reader isn't able to read these placeholder. We can discuss about these more in next call

**Comment by droshev** [comment]
@JyotiKumari1507 we need the input written so it will be easier to process

**Comment by droshev** [comment]
Most of the fields are not filled.

**Comment by JyotiKumari1507** [comment]
@droshev please let us know what fields are pending to fill from our side

**Comment by droshev** [comment]
@JyotiKumari1507 you are free to set any aria attributes

**Comment by JyotiKumari1507** [comment]
@droshev we have already a attribute placeholder which hold default value for text area and its not able to recognize by screen reader tool . can you pls suggest
