### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-264.1][WIP] Radio Button: Label and group label not read.

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11281]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Component having issue:https://sap.github.io/fundamental-ngx/#/core/radio
radio button:
The radio buttons should always be associated to its individual and group label.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader can check by implementing similar case. Just use any Radio Button. Radio buttons will not be associated to its label both label  and also its group label header by screen reader
#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

#### Is there anything else we should know?

**Comment by droshev** [comment]
@JyotiKumari1507 Can you provide more specific input here, what scenario are you trying to achieve and what can't you set via HTML and API?

**Comment by JyotiKumari1507** [comment]
@droshev The radio buttons should always be associated to its individual and group label. Screen reader isn't able to read out  radio button with its both value and its label. We can have more discussion on this in next call

**Comment by droshev** [comment]
@JyotiKumari1507 we need the input written so it will be easier to process

**Comment by JyotiKumari1507** [comment]
@droshev  attaching screenshot for more details where Screen reader isn't able to read out radio button with its both value and its label.:
<img width="903" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/157268666/c2684730-ce3c-416f-beb3-37bc6f160cc7">
<img width="568" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/157268666/71ea35f3-e801-40fb-87a4-c705162bf78d">

**Comment by droshev** [comment]
Most of the fields are not filled.

**Comment by JyotiKumari1507** [comment]
@droshev please let us know what fields are pending to fill from our side

**Comment by droshev** [comment]
@nikolay-kolarov @InnaAtanasova do we have to set something, or the application dev can set it?

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

In UI5 it is a task for the application to relate the two elements:
If a label is used, it can be done via the labelFor API of the Label which adds aria-labelledby on the radiogroup element: https://ui5.sap.com/#/entity/sap.m.RadioButtonGroup/sample/sap.m.sample.RadioButtonGroup/code
If another element is used the RadioButtonGroup has ariaLabelledBy API which can be used.

Best Regards,
Nikolay

**Comment by droshev** [comment]
we need to add 2 attributes on the group level: `role` and `aria-labelledby`. The latter points to a label

![Image](https://github.com/SAP/fundamental-ngx/assets/4380815/96c98a6c-1bb1-4adc-a124-bf2bf3ca423c)
