### ISSUE TITLE
Combobox - provide an option for the user to pass a custom template for the trigger element 

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1129]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
[Select](https://sap.github.io/fundamental-ngx/select) component has an option to pass a custom template for the trigger element. A similar option should be available for the [Combobox](https://sap.github.io/fundamental-ngx/combobox).

**Comment by MattL75** [comment]
This is more complicated in combobox than first appears FYI. It won't be possible to make it as simple as select unless we rewrite a significant portion of the template.

**Comment by sKudum** [comment]
Assigning to Loki and closing #1131

**Comment by Lokanathan-k** [comment]
code change done and pull request approved
https://github.com/SAP/fundamental-ngx/pull/1195
