### ISSUE TITLE
[Accessibility: ACC-270.5] Theme Tab: Focus does not follow the command 

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11291]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/platform/settings-generator
The tab "Appearance" is the selected tab, but when the user is navigating with tab key instead of the selected tab receiving focus always, the tab 'User account' receives focus first.
When there UI elements in group, always the selected UI element within the group should receive tab focus first.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
The tab "Appearance" is the selected tab, but when the user is navigating with tab key instead of the selected tab receiving focus always, the tab 'User account' receives focus first.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

**Comment by droshev** [comment]
this has been already fixed
