### ISSUE TITLE
Title provided in tabs component is being displayed everywhere when hovering over it.

### ISSUE THREAD

**Issue by i563785** [SAP/fundamental-ngx#11301]
#### 
          Go to tabs component under core components on ngx playground
          hover anywhere under a tab
          observe that title of tab is being displayed everywhere upon hovering.
<img width="1026" alt="Screenshot 2024-01-23 at 12 27 56 PM" src="https://github.com/SAP/fundamental-ngx/assets/113977593/37b81fe9-59a4-47ac-971a-7953a9c49d96">
<img width="1002" alt="Screenshot 2024-01-23 at 12 28 29 PM" src="https://github.com/SAP/fundamental-ngx/assets/113977593/654ee564-78e5-4910-b5e1-ed0230f07669">

**Comment by N1XUS** [comment]
You can use `[title]` syntax: https://stackblitz.com/edit/u8g3hi?file=src%2Fapp%2Ftabs-example.component.html,src%2Fapp%2Ftabs-example.component.ts,package.json

**Comment by i563785** [comment]
Thanks @N1XUS , the solution provided is working.
