### ISSUE TITLE
DH 129

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#11307]
- [x] Action sheet: Navigation is happening with TAB key, where with other lists we use arrow keys;
- [x] Checkbox with Display-only mode: clicking on the label will toggle the checkbox even though it should be readonly;
- [x] Dialog Full screen toggler: Template example does not change expand/collapse button icon when expanded;
- [x] Feed input: deprecated API used for dicebar
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/b7c19ec5-738c-46e8-8d4c-4d2ce106b91a)

- [x] Simple File Upload: select file, then click on " Reset File Selection via clear() function", then select the same file again. Input text will not be changed;
- [x] Core standard list: shellbar example for some reason
- [x] Message strip is not self-closed when navigated to another page;
- [x] Shellbar: when hovering over search field, border is misalligned: 
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/9b756e5a-45bf-4b6c-a907-8faadcd5e5bb)

- [x] Tokenizer: majority of our form single-line controls (e.g. input, combobox) are having 36px height. but Tokenizer has 44;
- [ ] Platform panel: shouldn't we deprecate it in favor of core's?

**Comment by droshev** [comment]
@N1XUS regarding platform panel: if it is the same with core in terms of features and API: yes
