### ISSUE TITLE
Combobox - custom sorting function

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1130]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Combobox component has a custom filter function. There should be a similar functionality allowing the user to pass a custom sorting input function.

**Comment by MattL75** [comment]
What is the use of this? They can sort it themselves when they pass the elements to the `dropdownValues` input. Adding a sorting function doesn't make sense.

**Comment by Lokanathan-k** [comment]
sorting function is not available

**Comment by MattL75** [comment]
See my comment above - you don't need a sorting function.

**Comment by manjunathanagaraj** [comment]
Agree, sorting is nor required. This can be closed.
