### ISSUE TITLE
Menu items should have an optional add-on container

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1132]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Menu items should be able to have an optional add-on container

![Screen Shot 2019-08-15 at 4 09 22 PM](https://user-images.githubusercontent.com/39598672/63123484-14a6cd00-bf77-11e9-9922-93e18258d4d9.png)

**Comment by MattL75** [comment]
Menu content is provided by the user already. What is the proposed feature here??

**Comment by kavya-b** [comment]
Hi Inna/Matt,
Menu with optional add-on container is different from menu with optional icons.
The **add-on container** looks like this:
<img width="124" alt="image" src="https://user-images.githubusercontent.com/53509521/63313407-ec75f000-c321-11e9-9878-749bc7f58dfe.png">
and behaves much like a menubar on Word( View->see the options with check mark beside it) retaining the selected option the next time menu is opened:
<img width="351" alt="Screenshot 2019-08-20 at 11 11 50 AM" src="https://user-images.githubusercontent.com/53509521/63334199-8193db80-c358-11e9-986b-b2de7bcda92a.png">

whereas the **optional icons** look like this:
<img width="138" alt="image" src="https://user-images.githubusercontent.com/53509521/63313433-0b748200-c322-11e9-86b2-f4fca7fff49e.png">
and Matt's comment on user-provided content might apply here. However, we do need to provide documentation with an example on how to use menu with optional icons.

**Comment by MattL75** [comment]
Okay sure. We can provide some documentation on how to accomplish this. However, on the library I'm not convinced that it's feasible to implement as a feature. It's likely best to leave it up to the user but to showcase it in the docs.

**Comment by kavya-b** [comment]
Hi Matt,
> However, on the library I'm not convinced that it's feasible to implement as a feature. It's likely best to leave it up to the user but to showcase it in the docs.

Are you talking about the add-on container here?

**Comment by JKMarkowski** [comment]
Hi @kavya-b and @InnaAtanasova ,
I also don't think that any change on library should be applied. User can put whatever he wants inside `fd-menu-item`. I think that it's pretty simple to understand usage of menu directives, which are responsible mostly for putting classes to elements. We can provide some example of using more complex templates inside menu in the future.

**Comment by sKudum** [comment]
Assigning it to Kavya, as she is not able to assign it to herself.
