### ISSUE TITLE
Menu items should have optional separator lines between them

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1133]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Currently the [Menu](https://sap.github.io/fundamental-ngx/menu) component has no separator lines between the menu items. There should be an option to have items with separators.

![Screen Shot 2019-08-15 at 4 11 28 PM](https://user-images.githubusercontent.com/39598672/63123658-7f580880-bf77-11e9-9b83-08e66763a21d.png)

**Comment by kavya-b** [comment]
I am working on this issue at present, but unable to assign it myself due to some access issues.

**Comment by sKudum** [comment]
Reassigning it to Kavya, As she is working on it and same has informed to JKMarkowski as well.

**Comment by kavya-b** [comment]
Fixed in PR https://github.com/SAP/fundamental-ngx/pull/1180
