### ISSUE TITLE
Menu - submenu option

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1134]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
There should be an option to have menu items with submenus

![Screen Shot 2019-08-15 at 4 14 18 PM](https://user-images.githubusercontent.com/39598672/63123992-48362700-bf78-11e9-9428-6562fa59aae6.png)

**Comment by JKMarkowski** [comment]
It actually will be new component named mega menu.

**Comment by kavya-b** [comment]
During our gap analysis, we had identified some things that a sub-menu should follow. It is captured in our FRD [here](https://wiki-ariba.sjc.sap.corp/display/UED/FRD%3A+Menu). 
The specific points from that article for sub-menu(Mega menu) are:
1. The sub-menu shall, compulsorily have atleast one menu item or option.
2. There shall be clear visual cue (eg, a filled triangle pointing horizonally, or a bordered ‘>’ symbol) on the right side of the menu item to indicate the presence of sub-menu. When this visual cue is in focus, the sub menu shall expand to the right side of the the visual cue to display the sub-menu items.
![image](https://user-images.githubusercontent.com/53509521/63512402-63b5aa80-c501-11e9-93ec-f8b072d484bd.png)
3. All the visual properties of the menu and menu items shall be applicable to sub-menu items as well.
4. While there shall be no limit on number of menu items to have sub-menu, it shall be host application’s prerogative to limit the menu items having sub-menus.

Can the above points be considered valid?

**Comment by manjunathanagaraj** [comment]
Please can I know the ETA for this component?
