### ISSUE TITLE
Multiple Icons listed with fd-menu-addon

### ISSUE THREAD

**Issue by AnkitSomani22** [SAP/fundamental-ngx#11348]
#### Is this a bug, enhancement, or feature request? : 
Bug

#### Describe your proposal. :  
Multiple Icons are getting listed in fd-menu-addon after upgrade of fundamental ngx to 0.46.1 from 0.45.1 though there is no source code changed.
It is found that sporadically multiple icons are listed in a menu item where one icon would be the icon which glyph is passed and other icons would be wither the same glyph or repeated from other menu-item in same menu.
This issue is also there in fundamental ngx library version 0.47.1 as well.

<img width="152" alt="Screenshot 2024-02-02 at 1 51 31 PM" src="https://github.com/SAP/fundamental-ngx/assets/50194839/8c89ba52-43f7-4ea2-8174-c3b427df93a5">

#### Can you handle that on the application side : 
No

#### Which versions of Angular and Fundamental Library for Angular are affected? 
Please, specify the exact version. (If this is a feature request, use current version.) : 0.46.1

#### If this is a bug, please provide steps for reproducing it; the exact components you are using; :  
It is sporadic issue where sometime we are seeing multiple icons in fd-menu-addon. 

#### Please provide relevant source code (if applicable).

```
<fd-menu>
    <li *ngFor="let item of items; trackBy: trackBy" fd-menu-item>
      <a fd-menu-interactive>
        <fd-menu-addon [position]="'before'" [glyph]="item.glyph"></fd-menu-addon>
        <span fd-menu-title>{{ item.title }}</span>
      </a>
    </li>
</fd-menu>
```

#### Is there anything else we should know? 
After refresh of UI this issue is not replicable.
I think here is`fd-icon` is not getting destroyed in `fd-menu-addon`.

**Comment by InnaAtanasova** [comment]
Hi @AnkitSomani22 , thank you for opening the issue!
I have tried to recreate this issue but I couldn't. You mention in the issue that you were able to reproduce it in our documentation. Which component was that. Here are some screenshots of Stackblitz with Action Bar component using version `0.47.4`. 
<img width="1793" alt="Screenshot 2024-02-05 at 1 30 59 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/f83b72f1-54c8-4ca1-bb1c-9999cb7af659">
<img width="1807" alt="Screenshot 2024-02-05 at 1 31 12 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/b5eb30e0-2d95-4a60-80f2-9da4241ccec4">

**Comment by InnaAtanasova** [comment]
Here's the same example with version `0.46.1`: 
<img width="1472" alt="Screenshot 2024-02-05 at 1 36 22 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/92a43fd0-9c7c-455d-b73d-9a92a3f0eb6e">
<img width="1465" alt="Screenshot 2024-02-05 at 1 36 11 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/be17d016-5ae7-4d7b-8c04-50572ec91102">

**Comment by droshev** [comment]
@AnkitSomani22 We didn't get any further update. Can you create a stackblitz with the issue and report a new issue?
