### ISSUE TITLE
[P1][Sourcing][Regression] Flickering components in platform table

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#11343]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

Currently, we see this happens in table using `virtualScroll` when we scroll pass 30-40 rows. When we are scrolling the table, `fdp-switch`, some NGX components, and some of our custom components are dancing. This did not happen before in `0.43.14`.

Version `0.43.14`:

https://github.com/SAP/fundamental-ngx/assets/22842279/e5aa3f55-b1bb-4f83-8e22-e84dac024ef4

Our current version `0.43.26`:

https://github.com/SAP/fundamental-ngx/assets/22842279/65c26fa8-e04b-4d01-92b4-974ae6e443b2

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

`0.43.26`, start broken from `0.43.25`

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

- Import platform, core NGX packages in child module.
- Create a platform table with `virtualScroll` on with more than 400 rows.
- Have any inline component like `fdp-combobox`, `fdp-date-picker`, or `fdp-switch`.... Make sure each row has different values to clearly see the issues.
- Scroll pass 40 rows.

#### Please provide relevant source code (if applicable).

in stackblitz

#### Please provide stackblitz example(s).

`0.43.26`: https://stackblitz.com/edit/angular-sufq3o-jcwn1i?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

**Comment by droshev** [comment]
@mikerodonnell89 Can you analyze the issue and check whether this is something the application needs to change?

**Comment by CSENoni** [comment]
FYI, the issue can be reproducible starting from `0.43.25`. It was still fine with `0.43.24`. The issue can also be seen when package is imported at app module for some components so I think it is not just about the import issue.
