### ISSUE TITLE
Not Loclize Search bar placeholder< fdp-search-field>

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#11345]
Is this a bug, enhancement, or feature request?
bug

Briefly describe your proposal.
In a table RFX  pricing-items search bar placeholder  is not translated component <fdp-search-field>

![image](https://github.com/SAP/fundamental-ngx/assets/136554008/1883f015-b12c-4862-8522-dd60a2e458c1)

![image](https://github.com/SAP/fundamental-ngx/assets/136554008/863f2f88-3717-4cf2-8a83-2226545709b4)

![image](https://github.com/SAP/fundamental-ngx/assets/136554008/e917f800-4f3c-4cfd-a39f-e213f62b1d20)

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0
If this is a bug, please provide steps for reproducing it.

**Comment by droshev** [comment]
@akilhaidar123 Can you check with version [v0.43.26](https://github.com/SAP/fundamental-ngx/releases/tag/v0.43.26)?

**Comment by droshev** [comment]
I checked and the translation is there
![Screenshot 2024-03-03 at 07 53 17](https://github.com/SAP/fundamental-ngx/assets/4380815/90ac0e13-7347-4138-97a5-059ae751a81d)
