### ISSUE TITLE
Table Growing behavior with Button

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#11369]
#### Is this a bug, enhancement, or feature request?
Feature request to growing behavior of Table component

#### Describe your proposal.
Currently, Table has Scroll growing behavior: more rows are loaded when the user scrolls to the bottom of the table.
The UX guidelines offer 2 types of growing behavior: scroll and button. We are missing the button one, where the table shows a More button at the bottom. Pressing the button loads more items.

More information: 
https://experience.sap.com/internal/fiori-design-web/table-web-component/#growing-behavior

**Comment by dominik-oelfin** [comment]
Hi! Having a look at the the current fix, I have two questions:

1) From the UX guidelines, I was expecting the More button to appear as the last row of currently displayed items of the table. OpenUI5 example of the same behavior can be found here: https://sdk.openui5.org/entity/sap.m.Table/sample/sap.m.sample.TableScrollToIndex. To click the button the user should scroll to the end of the currently displayed amount of items. The button should not be shown separated and fixed at the bottom of the container as it is now.
Can this be enabled as an option or changed?

2) Will this only be available for the platform table or also for the core table?

Thanks!
