### ISSUE TITLE
[WIP][P3.2][Sourcing] For Flat list fdp tables, row re-ordering or Drag and Drop feature is not available

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#11364]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Describe your proposal.
Would like to have a drag and drop of rows/ re-ordering of rows and preserving the state

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
v15.x

#### Is there anything else we should know?
Please address this at the earliest

**Comment by droshev** [comment]
@prasad-userdev did you consider using https://ng-15-downport--fundamental-ngx.netlify.app/#/cdk/drag-n-drop? We provide all the tools doing drag and drop

**Comment by prasad-userdev** [comment]
Thanks @droshev for the response. We tried using this CDK. But we have following challenges
1. cdk module is currently not part of the application. It will be challenging for us to include this.
2. tried- List with checkbox, It was bit buggy. not working as expected.

Also had discussed with Mike before raising this feature request. Thanks!

**Comment by droshev** [comment]
@prasad-userdev what are the challenges including the CDK? That is the main purpose to use for any drag and drop you need.

**Comment by prasad-userdev** [comment]
@droshev - Currently, just for this use case It will be challenging for us to include CDK as we have already written many custom directives. This might create duplication with the existing ones.

**Comment by droshev** [comment]
Our library offers all the tools and feature to achieve your requirements.
