### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-271.2]List Item: focused element is not  in the visible area

### ISSUE THREAD

**Issue by JyotiKumari1507** [SAP/fundamental-ngx#11371]
Is this a bug, enhancement, or feature request?
Bug

Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/core/select
Focused UI elements should always be in visible area.

Whenever the user uses a keyboard (s)he needs to be in control of where the input happens and affects consequences. Therefore, the focus must always be in visible area and easy to find.

Can you handle that on the application side
No

Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

If this is a bug, please provide steps for reproducing it; the exact components you are using;
Use select component. Use Keyboard to scroll down. As we move down focus will be lost from screen

Please provide relevant source code (if applicable).
Please provide stackblitz example(s).
In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes we have got this bug from Accessibility expert only.

Did you check the documentation and the API?
Yes

Did you search for similar issues?
Is there anything else we should know?

Check the attachement
![MicrosoftTeams-image (2)](https://github.com/SAP/fundamental-ngx/assets/157268666/7eba72e8-8489-4715-bc3d-082d225cbc21)
<img width="347" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/157268666/bebb857b-f681-46d6-8831-47630f73de83">

**Comment by droshev** [comment]
@mikerodonnell89 what happened to that issue?
