### ISSUE TITLE
[P1][Accessibility][Sourcing][Single select table]: User is able to select all rows using ENTER / SPACE key for single select table

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11373]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
User is able to select all rows using ENTER / SPACE key on header column in single row selection table
This is a big issue for accessibility and functionality point of view.
I am able to replicate it in even on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#single-row-selection in 0.43.rc-4

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
core / platform: 0.43.26

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) bring the focus on first header column where we have blank cell
2) hit enter or space key
3) notice that all rows are getting highlighted in blue color as selected

https://github.com/SAP/fundamental-ngx/assets/88182358/05a15de3-80f3-42ea-b017-f3149e21f6e0

#### Please provide relevant source code (if applicable).
Able to replicate on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#single-row-selection

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#single-row-selection
#### Is there anything else we should know?
This is reported by ATL team

**Comment by droshev** [comment]
@N1XUS can you check that issue? It is reproducible in main too/
