### ISSUE TITLE
Combobox - Emit event when button icon is clicked

### ISSUE THREAD

**Issue by KevinOkamoto-SAP** [SAP/fundamental-ngx#1139]
#### Is this a bug, enhancement, or feature request?
Feature request.

#### Briefly describe your proposal.
When using combobox as a search input field, the user needs to be able to execute a "free-text" search where the search text may or may not be one of the items in the `dropdownValues`.

While the developer can currently capture a "free-text" search event by using the attribute `searchFunction` and binding their custom search function. The `searchFunction` only is invoked on keyboard 'enter'. This function also needs to be invoked when the "icon" button is clicked.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
Fundamental 0.9.0

#### If this is a bug, please provide steps for reproducing it.
Steps:
- Enter text in input field, e.g. "Ap"
- Click "icon button"

Result:
No event is emitted, nor is the `searchFunction` executed.

Expected Result:
Event should be emitted or `searchFunction` gets executed

**Comment by JKMarkowski** [comment]
Thanks for reporting this issue, that's a good point.
