### ISSUE TITLE
[Sourcing][P2][Accessibility] Value Help Dialog Fiori Compliant and Enhancements

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#11399]
#### Is this a bug, enhancement, or feature request?
But/Enhancement

####  1st issue
The "Go" is not meaningful here:
![Oscar ScreenCapture 2024-02-13 at 14 34](https://github.com/SAP/fundamental-ngx/assets/7035787/ec9bb71f-37ed-472c-a274-153d7ecbde7f)

It should be "Search":
https://experience.sap.com/fiori-design-web/value-help-dialog/
<img width="1128" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/7035787/62069f2d-9599-4c93-98d8-8eb5da8c4e3f">

#### 2nd issue:
There is no way to reset `fd-combobox` inside the `fdp-value-help-dialog-filter`

https://github.com/SAP/fundamental-ngx/assets/7035787/4c457464-602e-4dc6-965d-d76bee84f1bc

#### 3rd issue:
The "Go" label read by the screen reader  ("description") is meaningless
<img width="1188" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/7035787/50bfa415-ab47-4816-9d6a-f2f1a506d429">

#### Can you handle that on the application side
No

**Comment by oscargong** [comment]
> @oscargong Regarding the second issue the button is refresh, not reset. Regarding the label Go - we need to check more thoroughly and if you are right we will update it.

Hi Deno,

Could we introduce a button to reset everything? Although I haven't seen such a spec in the Fiori for Web Design Guidelines or in the UI5 demo.

Also, only search placeholder "Go" we need to change. For Go button, we need to change the text read by the screenreader.

Thanks,
Oscar(I572124)

**Comment by nikolay-kolarov** [comment]
Hi,

With regards to 3, I think this is screen reader specific and it announces that this emphasised text is part of the description for the control. So we cannot do something on our side to control this. In Jaws it is currently not announced like this, but there for example when you have a placeholder in an input a new text "placeholder" is announced before the placeholder value with Jaws 2024.

Best Regards,
Nikolay

**Comment by droshev** [comment]
@oscargong I have fixed point 1; point 3 was commented by @nikolay-kolarov and there isn't more we can do.
point 2 is a new custom requirement request. It is not convincing to link search field with other components from the page. It is not aligned with UI5 so we won't do it. The user can clear the other fields by themselves.

**Comment by oscargong** [comment]
thanks Deno
