### ISSUE TITLE
[P2][Sourcing][Tree table multi select]: Table count for rows is wrong after expand All or collapse All

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11406]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When the parent nodes are just 5 then the table title displays Items(5) as title for the table when rows are all collapsed.
When all rows are expanded then since child nodes get rendered. the count in the title is not updated based on total rows after Expand All.

Expectation: when user clicks on "Expand all" the count of table rows in Title has to get updated based on all child nodes rendered.
When user clicks on "Collapse all" then again the count of table rows has to match as that of total number of outer parent nodes.,

This is replicable on 0.43.0-rc-4  https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree
#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
core platform : 0.43.26

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree

**Comment by droshev** [comment]
@I543348 This is part of the application and it can be done in `TableDataProvider.fetch` update `totalItems`

**Comment by I543348** [comment]
Thanks @droshev , we have temporarily made false for count of item
