### ISSUE TITLE
calendar first day of the week by default is not compliant with ISO 8601

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1141]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
It seems the calendar's default first day of the week is Sunday. This is fine if the developer pass the localized strings for the weekdays starting with Sunday.
It doesn't behave correct if we set different day as starting day(e.g. Monday) and  pass localized strings for the weekdays starting with Monday.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
`fundamental-ngx` version `0.9.0`

#### If this is a bug, please provide steps for reproducing it.
1. go to https://stackblitz.com/edit/angular-pajrvk-bqtile
2. open the calendar and see the current date is not rendered under the right day of the week

**Comment by JKMarkowski** [comment]
In my opinion It's better to force users to put day names, with sunday at first position. 
Otherwise even on simple `startingWeekDay` change user would be forced to provide whole service with everything
