### ISSUE TITLE
Click of checkbox works on label/text

### ISSUE THREAD

**Issue by pavandk** [SAP/fundamental-ngx#11427]
#### Is this a bug, enhancement, or feature request?

Bug:

Checkbox should be selected/unselected only if we click on checkbox. But I see I am able to do select/unselect even if I click on label/text.

https://github.com/SAP/fundamental-ngx/assets/1974613/15d6d4eb-44f7-43ff-94a4-d2242cb7a4e1

**Comment by N1XUS** [comment]
According to accessibility rules, clicking on the checkbox label should also trigger checkbox state modification, so it's an expected behavior
