### ISSUE TITLE
Request for new component - Identifier bar

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#1143]
#### Is this a bug, enhancement, or feature request?
Feature

#### Briefly describe your proposal.
Few SAP Ariba apps support a user acting on behalf of someone else to carry out a business process. 
For example, in Guided Buying, a user can buy items on behalf of another user; or on Ariba Network, a customer can allow customer support to access their site as an administrator for troubleshooting purposes. 
The identifier bar displays this information and enables the user to easily switch between users.
The identifier bar is at the top of the page, below the shellbar. 

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
Fundamental 0.9.0

**Comment by sKudum** [comment]
link for reference-
https://wiki-ariba.sjc.sap.corp/display/UED/Identifier+bar
It has the design and FRD details of the component.

**Comment by LeoT7508** [comment]
@droshev 

Is this something we need to add to our library? This looks like something very specific the Ariba team would create and maintain for their products. I don't think we should add this to the base set of components for the library.
