### ISSUE TITLE
Select Form Message

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#11430]
#### Is this a bug, enhancement, or feature request?
enhancement/feature request

#### Describe your proposal:

The message displayed in the dropdown list of the Select component is being truncated when it exceeds a certain length. This truncation poses usability issues, especially when users need to view longer messages or options.

#### Proposed Solution:
Introduce an input property that allows the user to display the message on multiple lines within the dropdown list of the Select component. This enhancement would improve the user experience by ensuring that longer messages are fully visible and comprehensible.

**Comment by khotcholava** [comment]
No longer reproducible. @InnaAtanasova 

### Current Version.

![Image](https://github.com/user-attachments/assets/49886278-4f0b-4943-8488-8cad01bccf83)

**Comment by khotcholava** [comment]
@do-oel Please provide a StackBlitz example to make debugging easier and clearly demonstrate the issue.

**Comment by droshev** [comment]
@khotcholava did you have troubles reproducing the reported issue?
