### ISSUE TITLE
[FEATURE REQUEST] Pick multiple days in DatePicker and Calendar controls

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#11446]
Hello, fundamental-ngx team,

We are developing an angular application with the use of fundamental-ngx library.

The main purpose of the application is booking and we have a requirement, that a user should have the possibility to pick random booking dates in the DatePicker.

I have a question, is there any chance to add this functionality to the DatePicker and Calendar controls - [MultipleDaySelection](https://sapui5.hana.ondemand.com/#/entity/sap.ui.unified.Calendar/sample/sap.ui.unified.sample.CalendarMultipleDaySelection)?

A user can pick dates randomly
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/d1397526-0a2f-4c96-b26c-0e5c02044437)

A user can select all week days in one click (in the row) by clicking on the week number on the left side
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/9846d2d6-7cbc-4a87-a2cb-ec8e2eb6a2cc)

A user can select all current month days in one click (in the column) by clicking on the weekday name at the top
note: there is no such functionality in the sapui5 yet, but will be great to have it in the fundamental-ngx
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/0fe05fa1-c04c-4a55-8d30-5196309ef480)

Is it possible to extend the current fundamental-ngx controls with such requirements?

Best Regards.

**Comment by droshev** [comment]
@egorwow70 I requested some design support as a first step.

**Comment by egorwow70** [comment]
@droshev Hello, any news regarding this ticket?

**Comment by droshev** [comment]
@egorwow70 let me discuss with the team and see how we can move forward with it.

**Comment by dpavlenishvili** [comment]
[egorwow70](https://github.com/egorwow70)
it's not possible to implement multi selection for DatePicker, because it's input with calendar and it's not possible to set multiple irregular numbers as input value.

**Comment by droshev** [comment]
> @egorwow70 it's not possible to implement multi selection for DatePicker, because it's input with calendar and it's not possible to set multiple irregular numbers as input value.

@dpavlenishvili actually the question is: how @egorwow70 wants to display the multiple days in the field? is it like multi input?
