### ISSUE TITLE
[BUG] IllustratedMessage renders SVG with a different form

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#11447]
Hello, fundamental-ngx team,

We are developing an angular application with the use of fundamental-ngx library:
**"@angular/common": "^16.2.0"**
**"@fundamental-ngx/core": "^0.47.0",**

We found a bug connected to the [IllustratedMessage component](https://sap.github.io/fundamental-ngx/#/core/illustrated-message). When we use a custom SVG, its form is different (**svg hands are out of circle**) from the real one. I am not an svg expert and cannot find the reason of the bug, is it possible to fix? Although using the same svg with an image tag looks fine. So it seems like there is a trouble with a control..?

![image](https://github.com/SAP/fundamental-ngx/assets/41961241/58ea935f-093e-4060-acce-4447b7b7d9b0)

**SVG has been taken from sap design library** - https://www.figma.com/file/4ypTByPFaQ2koG3wna03XF/S%2F4HANA-Web-UI-Kit---Compact-(Non-touch-Devices)?type=design&node-id=36415-216394&mode=design&t=j9MpOFNeT3vO7YJe-4

**Issue on Stackblitz** - https://stackblitz.com/edit/ed53zg-hpt82n?file=src%2Fapp%2Fillustration.component.html

Best Regards.

**Comment by egorwow70** [comment]
I added one more example in the stackblitz sample, seems like same issue
![image](https://github.com/SAP/fundamental-ngx/assets/41961241/f0a21cfa-8266-4128-b967-fff9df8ad6bc)

**Comment by droshev** [comment]
@egorwow70 I don't think the problem is in the library. If you render SVG element like this:

```
  <svg class="fd-illustrated-message__illustration">
    <use
      href="assets/images/sapIllus-Dialog-EmptyList.svg#sapIllus-Dialog-EmptyList"
    ></use>
  </svg>
```

it renders like the component. [here](https://stackblitz.com/edit/ed53zg-fqz57u?file=package.json) is a modified stackblitz

the difference in rendering between the two methods may be due to the way SVGs are handled in HTML.
