### ISSUE TITLE
Request for Side Navigation enhancement

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1144]
#### Is this a bug, enhancement, or feature request?

feature request

#### Briefly describe your proposal.

- Side Navigation has a footer area (A)
- If a button is added to the footer area it doesn't need the complete space. Instead, it can be small and right- or left-aligned. (A)
- If the Side Navigation is expanded, the Side Navigation is scrollable in case there is not enough space to display all items
- If the Side Navigation is collapsed and there is not enough space to display all items, further items can be accessed through an overflow icon (B)

![side_navigation](https://user-images.githubusercontent.com/51904901/63324886-4cbc6000-c329-11e9-8d66-cb758abbb22a.jpg)

Can you please give feedback how long it would take to implement such features?

**Comment by MattL75** [comment]
This is already being worked on. Any ETA @InnaAtanasova ?

**Comment by kistll** [comment]
@droshev @InnaAtanasova : I saw there is pull request which adds a header and a footer section to the side navigation: https://github.com/SAP/fundamental-styles/pull/255 Will this also support right-aligned buttons?

**Comment by droshev** [comment]
@kistll We updated the side nav! Thanks for the patience :)
Here are my comments:
- we have a utility section(bottom one)
- the collapse/expand button will come from the hamburger menu
- we are addressing this - @JKMarkowski in a small PR
- the overflow icon was not as part of the spec we got.

**Comment by droshev** [comment]
@kistll regarding the overflow menu(3 dots) - this is not part of the current design. We have raised the topic to the owners of the spec. They will review it again. If they decide to introduce it we will implement it.
I will close the issue as the other points have been addressed. Feel free to reopen it or report a new one if you see other issues.
