### ISSUE TITLE
[Sourcing] ACC-264.1(Level A) Fdp-table filter dialog button labels are incorrectly conveyed

### ISSUE THREAD

**Issue by devika-devanand** [SAP/fundamental-ngx#11462]
#### Is this a bug, enhancement, or feature request?
Accessibility bug

#### Describe your proposal.
On accessing the ‘Expand/collapse’ button of ‘Include’ and ‘Exclude’ of the fdp-table filter dialog box, their respective labels are wrongly conveyed has “Undefined”.
However the labels, state, properties of all the UI elements should be conveyed correctly only once to the users when accessed.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx version : 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
-Open the filter dialog box from the fdp-table 
-Collapse the Include and Exclude sections
-Activate the voice reader and navigate through the dialog box buttons

<img width="930" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/2a483b4c-12e1-4863-84a0-4be604748013">

#### Please provide relevant source code (if applicable).
The filter dialog box appears with the following piece of code

<img width="401" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/80ad05a1-2e31-4c93-8a4b-db0572087edf">

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Labels, state, properties of all the UI elements should be conveyed correctly only once to the users when accessed.

**Comment by droshev** [comment]
@devika-devanand Can you provide a stackblitz or steps and example where we can analyze the issue?

**Comment by droshev** [comment]
@devika-devanand any update?

**Comment by droshev** [comment]
@devika-devanand the ticket will be closed if there is no further updates

**Comment by droshev** [comment]
no activities => closing the issue
