### ISSUE TITLE
Closing fd-product menu in shellbar after entry selection not possible (re-open)

### ISSUE THREAD

**Issue by D043319** [SAP/fundamental-ngx#1146]
Hello,
this issue is related to the already closed issue #1099 which did not fix the problem in total.
https://github.com/SAP/fundamental-ngx/issues/1099

I guess your fix works only for the "menues" on the right side of the shell bar which are controlled via the "shell-bar-actions".
I was talking about the "fd-product-menu" which is located at the left side of the shellbar.
In the shell bar example implementation this is filed with , "Application A, Application B ... Application D".

https://sap.github.io/fundamental-ngx/shellbar

<fd-product-menu [control]="productMenuControl"
                 [items]="productMenuItems">
</fd-product-menu>
Here you can't add the new option [closePopoverOnSelect]="true" to close the product menu after one of the entries was selected.

@JKMarkowski,
Can you pls. check if the provided fix can be also applied for the fd-product-menu?
Thank you for your support.

**Comment by JKMarkowski** [comment]
Hi @D043319, this flag will be applied to `fd-product-menu`. Thanks for noticing it.
