### ISSUE TITLE
[Sourcing]ACC-253.4(Level A) fdp-table filter dialog box input field, explicit label is not provided and UI is not marked as required

### ISSUE THREAD

**Issue by devika-devanand** [SAP/fundamental-ngx#11461]
#### Is this a bug, enhancement, or feature request?
Accessibility bug

#### Describe your proposal.
The input field within ‘Include’ and ‘Exclude’ sections are only visible when focused. Here they are not provided with explicit visible label.
These input fields are read has “required” fields, but not visually marked as mandatory fields.

The input fields should be provided with explicit visible label which describes the purpose of the UI and all required fields should be marked has mandatory which can be recognized by all users.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx version : 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
-Open the filter dialog box from the fdp-table 
-Check the focus for the input boxes for the Include and Exclude sections
-Activate the voice reader and navigate through the Include and Exclude sections
<img width="718" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/3819666e-c13a-453f-a78b-afc4380966da">

#### Please provide relevant source code (if applicable).
The filter dialog box appears with the following piece of code

<img width="401" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/80ad05a1-2e31-4c93-8a4b-db0572087edf">

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
The input fields should be provided with explicit visible label which describes the purpose of the UI and all required fields should be marked has mandatory which can be recognized by all users.

**Comment by droshev** [comment]
@devika-devanand I tested the filtering in fdp-table doc [here](https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic) and the inputs seems to be ok.
Do you think you can create a stackblitz?
![Uploading Screenshot 2024-03-03 at 09.07.21.png…]()

**Comment by droshev** [comment]
@devika-devanand any update?

**Comment by droshev** [comment]
@devika-devanand We will close the issue if it doesn't get any updates.

**Comment by droshev** [comment]
no activities => closing the issue
