### ISSUE TITLE
[Sourcing]ACC-271.1(Level A) Fdp-table sort dialog box element focus issue

### ISSUE THREAD

**Issue by devika-devanand** [SAP/fundamental-ngx#11468]
#### Is this a bug, enhancement, or feature request?
Accessibility bug

#### Describe your proposal.
On changing the value of the column drop down in the sort dialog box using arrow keys, focus is lost and goes to the ‘Reset’ button.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx version : 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using
-Create an fdp-table with the sort functionality added for a few columns.
-Open the Sort dialog box and try navigating using the keyboard - check the same after changing the column dropdown value.
<img width="428" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/3943b267-6a59-44e8-8b13-4d37e49cc87f">

#### Please provide relevant source code (if applicable).
Create an fdp-table with the sort functionality. 
<img width="401" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/80ad05a1-2e31-4c93-8a4b-db0572087edf">

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Focus should not change to a different element on changing the values of the list and it should retain on the same UI.

**Comment by droshev** [comment]
@devika-devanand I tried to reproduce the issue, but I wasn't able to reproduce it.
![sort-table](https://github.com/SAP/fundamental-ngx/assets/4380815/6ff31ba4-cc15-445d-ac83-0781d2db0b88)


Do you think you can provide the steps and which example did you use?

**Comment by droshev** [comment]
@devika-devanand we didn't get any reply => closing the ticket. If you are able to reproduce, please, provide us with stackblitz, detailed steps and what the expectation is.
