### ISSUE TITLE
[Sourcing]ACC-264.1, ACC-270.1(Level A) Fdp-table sort list UI is not reachable using keyboard and incorrect UI type and no count is read

### ISSUE THREAD

**Issue by devika-devanand** [SAP/fundamental-ngx#11470]
#### Is this a bug, enhancement, or feature request?
Accesibility bug

#### Describe your proposal.
The list box is not reachable using keyboard when accessed without any screen reader.
And when screen reader is used, we have 4 different tab stops where their UI type is conveyed has link and not has “list items”. Here the count information “x of x” is also not conveyed.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx version : 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
-Create an fdp-table with the sort functionality added to few of the columns.
-Access the Sort dropdown for selecting the ascending or descending order using the keyboard and voice reader.
<img width="1135" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/475b25bb-5f74-4200-bc75-406dfe2d59fb">

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Labels, state, properties of all the UI elements should be conveyed correctly only once to the users when accessed.
And all UI elements should be accessed and used from all input devices such as keyboard, mouse or touch.

**Comment by droshev** [comment]
@nikolay-kolarov Can you advise us here?
