### ISSUE TITLE
When using Message Strip Alerts, they sometimes appear in the wrong place

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#11474]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
When using Message Strip Alerts, they sometimes appear in the wrong place (at the bottom of the page).
![IMG_20240227_124718_423-01](https://github.com/SAP/fundamental-ngx/assets/86781159/ec698f48-4287-484c-9e30-fe7280f5a237)
Apparently the styles for `.cdk-overlay-*` are not always present. I saw on your stackblitz examples in the documentation that you use `@import '@angular/cdk/overlay-prebuilt';` in `styles.scss`. This fixes my problem, but there is nothing in the documentation that says to add this import.
#### Can you handle that on the application side
Yes
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 16.1.0
Fundamental Library: 0.44.0
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
For example if I just interact with the buttons on the page, the message strip alert appears under the page, but if I interact with the buttons in a dialog, it shows up normally
#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes
#### Is there anything else we should know?
No

**Comment by droshev** [comment]
We need to document that explicitly. (TBD where)
