### ISSUE TITLE
shellbar item should not be triggered by "enter" key down, but "Enter" key up

### ISSUE THREAD

**Issue by wei368** [SAP/fundamental-ngx#11480]
#### Is this a bug, enhancement, or feature request?

Bug

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

0.43.21

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

1. go to https://sap.github.io/fundamental-ngx/#/core/shellbar
2.  tab to Bell icon
3. press "Enter" key down, (do not release) 
4. you will see the popup is trigger

The correct behavior is that showing the popup when the "Enter" key is released. (ie key up)
It should work the same as "Space" bar key. ie space bar key works correctly right now

![Screenshot 2024-02-27 at 3 04 22 PM](https://github.com/SAP/fundamental-ngx/assets/5350405/f739b221-b6e6-4e33-bd28-5d7e152ce436)

**Comment by mikerodonnell89** [comment]
The default behavior for a vanilla HTML button is space bar keyup, but enter works with a keydown: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_button_test

UI5 is the same: https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button
