### ISSUE TITLE
[Accessibility] Pagination - Input field label and screen reader issue

### ISSUE THREAD

**Issue by harshitha-s-kanchan** [SAP/fundamental-ngx#11481]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.

1. Input field to enter page number does not have a label on initialization / on load.
2. Input field has required attribute, which is causing screen reader to read out as 'edit spin box **required**'. Additional text 'required' should not be read out.
3. On editing the pagination input filed with different value, in linear reading mode the value is announced twice by the screen reader which can use confusion to the user.
4. Not able to change the input field page value using left and right arrow keys in linear reading mode.

#### Can you handle that on the application side
As we do not have access to this input field, its not possible to handle in application end.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - 15
NGX - 0.43.21
Component - `<fd-pagination>`
Screen reader - JAWS 2023

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
For issue 1 :

<img width="1705" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/149040487/cd236350-3050-4dea-a1fd-ebdfe16cd112">

For Issue 2 and 3 :
Required text is being read out on accessing text field
On updating the value as 4 in the input field, 4 is being read out twice.

https://github.com/SAP/fundamental-ngx/assets/149040487/f3b69830-8602-4657-802f-57f1949460e8

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes this issue is raised by Central Accessibility team in our application

**Comment by droshev** [comment]
@nikolay-kolarov Can you advise us here?

**Comment by nikolay-kolarov** [comment]
Hi @droshev,

I have not seen such a pattern so far in Fiori, so maybe you can double check this with UX for proper acc spec.

Here is my opinion with regards to the problems described above:
1 - Input field to enter page number does not have a label on initialization / on load -> An invisible label can be added and referenced via aria-labelledby.
2 - Input field has required attribute, which is causing screen reader to read out as 'edit spin box required'. Additional text 'required' should not be read out. -> The required announcement comes from the required attribute. The field somehow acts as such, as when you delete the value it is restored. So I am not sure if it makes sense to remove it.
3 - On editing the pagination input filed with different value, in linear reading mode the value is announced twice by the screen reader which can use confusion to the user. -> This seems to be the same with https://ui5.sap.com/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInput, so I assume it is screen reader specific. I tested with NVDA and there it is not announced twice.
4 - Not able to change the input field page value using left and right arrow keys in linear reading mode. -> I am not sure what exactly is meant here. @harshitha-s-kanchan  - Could you please provide more info? Here is a sample of number input type in UI5 https://ui5.sap.com/#/entity/sap.m.Input/sample/sap.m.sample.InputTypes and there left and right also do not change the value.

Something on top - The arrow up and down keys do not work to change the value and this is important for number input: https://ui5.sap.com/#/entity/sap.m.Input/sample/sap.m.sample.InputTypes

Best Regards,
Nikolay

**Comment by droshev** [comment]
@harshitha-s-kanchan can you answer what @nikolay-kolarov asked?

**Comment by harshitha-s-kanchan** [comment]
Hi @droshev @nikolay-kolarov ,
The input field in pagination is being read in JAWS as '`edit spinbox required {inputValue}. To set the value use the arrow key or type the value.`' but the arrow key support is not provided to set the value. (Screen reader read out can be seen in the recording attached)
The screen reader read out is similar to https://ui5.sap.com/#/entity/sap.m.StepInput/sample/sap.m.sample.StepInput where up / down arrow keys can be used to set the value along with typing the value.
Also, the central accessibility team is using JAWS screen reader for testing applications.
