### ISSUE TITLE
[Sourcing] fdp-approval-flow component Input text is getting cleared in search bar while typing and going to next screen

### ISSUE THREAD

**Issue by sreekanthkarini** [SAP/fundamental-ngx#11497]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
In **fdp-approval-flow** component when we type in search input, text is getting cleared and it is going to next screen when it is used in pop up

https://github.com/SAP/fundamental-ngx/assets/136553940/d5335ca3-fab9-4d5f-827e-4b040b88f9f5

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.43.28

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Open **fdp-approval-flow** component (when it is used in pop up)
Type some random text in input search bar
Text is getting cleared
Screen is going to next screen

#### Did you check the documentation and the API?
yes

**Comment by droshev** [comment]
@sreekanthkarini @I543348 any update?

**Comment by droshev** [comment]
closing the ticket as there is no update provided
