### ISSUE TITLE
Defect hunting

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#11494]
- [x] [EDIT: this is not an issue, it's like this per specs and in UI5] https://fundamental-ngx.netlify.app/#/platform/menu -> Top and bottom items border is not aligned with other dropdown item tyles 
Menu:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/ac6e17a2-f08d-4913-9b6f-ed1d8b828723)
Combobox:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/fd25aa11-cb34-41e1-85d5-dd253c90e778)
Select:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/6b2178d4-b5d6-46cc-9612-f3a9f799c9bb)

- [x] https://fundamental-ngx.netlify.app/#/core/multi-input -> Warnings in console
- [x] https://fundamental-ngx.netlify.app/#/core/popover -> change `http://picsum.photos/id/1018/400` to `https://picsum.photos/id/1018/400`
- [x] [fix](https://github.com/SAP/fundamental-styles/pull/5246) [EDIT: this is a styling issue due to the border appearing only when the item has state] https://fundamental-ngx.netlify.app/#/core/product-switch -> Selecting item in the popover results in item jumps by couple pixels

- [x] https://fundamental-ngx.netlify.app/#/core/shellbar -> Error in console

- [x] https://fundamental-ngx.netlify.app/#/platform/checkbox#with-form -> Should clicking on the checkbox label toggle it's state? [fix](https://github.com/SAP/fundamental-ngx/pull/11591)

- [x] https://fundamental-ngx.netlify.app/#/platform/message-popover -> Heading should be above description.

![image](https://github.com/SAP/fundamental-ngx/assets/6586561/54d96b35-4820-4bdc-9c99-166ccb25b536)

- [x] https://fundamental-ngx.netlify.app/#/platform/panel -> Example code states that `aria-pressed` should be `true` only if the panel is epanded, yet, if panel is not expanded the button is still highlighted
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/70f15c90-c187-47cd-9ba9-0cdaf0a55427)

- [x] https://fundamental-ngx.netlify.app/#/platform/table/settings-dialog-table -> 
ncorrect border:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/b57610da-4073-43de-a254-5daa5c5e2322)
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/0e7a9abd-c596-475f-927c-67ec2d52fcaf)

`Filter By` group header looks incorrect:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/a4a171be-d566-4fe6-939b-73d4e8ded60d)
By pressing `Escape` button we see error in the console. This is due to the reason of how we handle dialog cancel action

- [x] https://fundamental-ngx.netlify.app/#/platform/value-help-dialog -> [fix](https://github.com/SAP/fundamental-ngx/pull/11610)
`Include` / `Exclude` looks like option item rather than group item:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/319007cf-788e-450c-8f75-d6678a71a23b)

**Comment by droshev** [comment]
- [ ] Multi Input/Combo token focus is cut. The focus on the token alone is fine:
![Screenshot 2024-03-02 at 08 02 26](https://github.com/SAP/fundamental-ngx/assets/4380815/1085bbe0-cc6e-4a4c-86c1-2fea13871c4d)
![Screenshot 2024-03-02 at 08 02 36](https://github.com/SAP/fundamental-ngx/assets/4380815/a3f31ad1-0cf7-4947-a265-825bc2a091e2)
