### ISSUE TITLE
Add possibility to hide icon in  Form Message and in Generic Tag

### ISSUE THREAD

**Issue by Tomashow** [SAP/fundamental-ngx#11495]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Describe your proposal.
Add possibility to hide icon in  Form Message (https://sap.github.io/fundamental-ngx/#/core/form-message) and in Generic Tag (https://sap.github.io/fundamental-ngx/#/core/generic-tag) as it was implemented for Message Strip (https://sap.github.io/fundamental-ngx/#/core/message-strip)

#### Did you check the documentation and the API?
Yes

**Comment by droshev** [comment]
@Tomashow the request needs to be validated with the designers whether it breaking any accessibility or other requirements.

**Comment by Tomashow** [comment]
@droshev 
Main use-cases for Form Message is using it with error in different input validation, and removing of icon help better use space inside of it for long validation messages example below.
For generic Tag the same reason using space inside as affective as possible for different types of generic Tag
![image](https://github.com/SAP/fundamental-ngx/assets/72388089/7e3be6a1-dece-401a-ad6b-1b1dbe4f888d)

**Comment by droshev** [comment]
@Tomashow in case of error validation then you would need to show the icon in parallel to the color as it will break the accessibility requirement.

**Comment by Tomashow** [comment]
By our design we using variant without icon, but if we will hide it from our side(with css) does it break accessibility?
Also I have different sources of information regarding the way how to show this validation error:
Here https://experience.sap.com/fiori-design-web/form-field-validation/ for form validation used form message without icon,
but here https://sapui5.hana.ondemand.com/#/entity/sap.m.Input/sample/sap.m.sample.InputValueState icon used will colour.

**Comment by droshev** [comment]
@Tomashow the visual design is on a different place. https://experience.sap.com/fiori-design-web/form-field-validation/ is more for interaction spec.

**Comment by droshev** [comment]
@Tomashow any update?
