### ISSUE TITLE
I18n console endless warnings [Enhancement/bug]

### ISSUE THREAD

**Issue by ogobelbel** [SAP/fundamental-ngx#11508]
#### Enhancement

During development in our app we got tons of warnings like this, which is decreasing a page load speed, because in some cases we're getting more than thousand warnings. So as enhancement I want to suggest a way to disable console warnings by a flag or disable it completely, because it doesn't have much meaning and will basically slow down the application and clutter up the console.

<img width="443" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/74075526/bffa719f-b8ea-4452-8b27-70d405a441cb">

#### Yes, I've checked the API refs.

Screen record for example: 

https://github.com/SAP/fundamental-ngx/assets/74075526/75932403-294f-4774-a94f-22511cfd2be2

**Comment by g-cheishvili** [comment]
I am more interested in why do you have such keys at all, those are not our keys. are you trying to use our pipes with your translations?

**Comment by ogobelbel** [comment]
> I am more interested in why do you have such keys at all, those are not our keys. are you trying to use our pipes with your translations?

yes. We're using our own translations with help of TranslationResolver.resolve. We're injecting custom translations from json file

**Comment by g-cheishvili** [comment]
I need stackblitz example or gh thing to know how to help. I would not like to remove the warnings

**Comment by ogobelbel** [comment]
I cannot provide stackblitz, but only parts of code for example:
we have copied the entire english translation file from https://github.com/SAP/fundamental-ngx/blob/v0.48.4-rc.1/libs/i18n/src/lib/translations/translations.ts

Then we have an object, which is importing our translations from json inside copied object.

So as a result something like this: 

`import * as EN from '@translations/en.json';`

`export const FD_LANGUAGE_ENGLISH: FdLanguage & typeof EN = { `<br>`
    ...EN,`<br>`
    coreCalendar: {`<br>`
        yearSelectionLabel: 'Select year',`<br>`
        yearsRangeSelectionLabel: 'Select years range',`<br>`
        monthSelectionLabel: 'Select month',`<br>`
        dateSelectionLabel: 'Select date'`<br>`
...`<br>``

Then using it in our pipe with TranslationResolver: 
`... `<br>`
this.translationResolver.resolve(FD_LANGUAGE_ENGLISH, key, args) `<br>`
... `<br>`
`
       

> I need stackblitz example to know how to help. I would not like to remove the warnings

**Comment by g-cheishvili** [comment]
I can not say that I am on the side of using our i18n as a full blown i18n library like transloco or something, but I can definitely say that it is more than capable of satisfying those needs. [here is the example of what you are doing](https://stackblitz.com/edit/stackblitz-starters-4ynugt?file=src%2Fmain.ts) and it works with the latest RC version.

**Comment by g-cheishvili** [comment]
I just do not know what is happening in your pipe, so something might be off in there and because of that, it might not work. So using our pipe, all works fine. If you want to, you can use it like I showed

**Comment by ogobelbel** [comment]
> I can not say that I am on the side of using our i18n as a full blown i18n library like transloco or something, but I can definitely say that it is more than capable of satisfying those needs. [here is the example of what you are doing](https://stackblitz.com/edit/stackblitz-starters-4ynugt?file=src%2Fmain.ts) and it works with the latest RC version.

it works, I do not argue. The only think is that when I have undefined keys, console warnings are showing and I could not control it. https://stackblitz.com/edit/stackblitz-starters-k8d5ru?file=src%2Fmain.ts
<img width="458" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/74075526/04765879-a290-4ec4-9a3e-1a831abf7016">

So if at least it's possible to handle it somehow it would be really nice :) Thank you

**Comment by g-cheishvili** [comment]
> > I can not say that I am on the side of using our i18n as a full blown i18n library like transloco or something, but I can definitely say that it is more than capable of satisfying those needs. [here is the example of what you are doing](https://stackblitz.com/edit/stackblitz-starters-4ynugt?file=src%2Fmain.ts) and it works with the latest RC version.
> 
> it works, I do not argue. The only think is that when I have undefined keys, console warnings are showing and I could not control it. https://stackblitz.com/edit/stackblitz-starters-k8d5ru?file=src%2Fmain.ts <img alt="image" width="458" src="https://private-user-images.githubusercontent.com/74075526/311044879-04765879-a290-4ec4-9a3e-1a831abf7016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDgxMTMsIm5iZiI6MTcwOTg0NzgxMywicGF0aCI6Ii83NDA3NTUyNi8zMTEwNDQ4NzktMDQ3NjU4NzktYTI5MC00ZWM0LTlhM2UtMWE4MzFhYmY3MDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIxNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYzI0ZjdiNmE0MjMwZWViMDZjNDJmNDYyMTE4M2FlM2U1NWI2NTZhMWMyOTc4NjYyZTVkMzNhNjg0ZjRjYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SYABIBpVErRKt40nDiufMaVUfqSegi-VQ0VCxdduL-w">
> 
> So if at least it's possible to handle it somehow it would be really nice :) Thank you

[In production builds, you will not have the warning](https://github.com/SAP/fundamental-ngx/blob/5fa5e37746429f926a38a9f36fb277bd55618ccc/libs/i18n/src/lib/utils/translation-resolver.ts#L30), in development it is needed to know that you have missing keys, `isDevMode` does what you've described.

By the way, why don't you use something else for your application translations? Angular's native translations, or transloco for example. Technically ours can work with anything you throw at it, but even the typings indicate that it's not really intended for such use 😄

**Comment by droshev** [comment]
@ogobelbel Did what @g-cheishvili write helped you?

**Comment by droshev** [comment]
@ogobelbel I will close the ticket, feel free to report a new one if you are facing other issues
