### ISSUE TITLE
[WIP][Sourcing][P2][Accessibility] Value Help Dialog: Various elements are not correctly read by screen reader

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#11512]
#### Is this a bug, enhancement, or feature request?
bug / enhancement

####  Various elements are not correctly read by screen reader

Here, the "level" is redundant
Also, on accessing the table, its respective label “Suppliers” and UI type “Table” and total row/column count is not read to the users.
<img  alt="image" src="https://github.com/SAP/fundamental-ngx/assets/7035787/b5375b9e-d359-4ecb-a3bb-dbac8d66bcf7">

**Comment by droshev** [comment]
@oscargong Can you provide more details and a stackblitz example if it is not reproducible in our doc example?

**Comment by oscargong** [comment]
Close ,as this seems expected.

![Oscar ScreenCapture 2024-03-12 at 02 54](https://github.com/SAP/fundamental-ngx/assets/7035787/3206b97f-317d-4b1f-accb-bed9ef7bc9ae)
