### ISSUE TITLE
[P3][Sourcing] Gap between approval flow

### ISSUE THREAD

**Issue by CSEHoangV** [SAP/fundamental-ngx#11511]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

In some flows of approval flow, especially if we have one to many or many to one flow, there will be some gap between approval nodes:

https://github.com/SAP/fundamental-ngx/assets/162270184/9e357b00-6d22-4165-af48-48f7ee85d17a

I notice that depending on how many parallel nodes we have to the most right, the gap from left will gradually be increased.

#### Can you handle that on the application side

No. I have tried to "override" the style. I notice that among those gap there are some nodes having class name "space" so trying to  hide it but it looks like it will break other things including functionality.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Current

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Create approval flow with many to one relationaship.
Add parallel nodes to the to most right.

#### Please provide relevant source code (if applicable).

NGX playground

#### Please provide stackblitz example(s).

https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/approval-flow

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 

N/A

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

Our customer said these gaps are causing confusion to them.

**Comment by droshev** [comment]
@CSEHoangV you would need to contact the guides sourcing team for approval flow support

**Comment by CSEHoangV** [comment]
Hi @droshev, as you suggested, we will create a pr to address the issue if needed. Thanks!

**Comment by CSEHoangV** [comment]
Close since it will be handled by GS team.
