### ISSUE TITLE
<app-notification-dialog>  Localization issues

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#11521]
s this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.

Tooltip text: Close, synchronise, clear selected items, for (icon of the Cross button on the right top ) is not localized
Button : Lock not localized while enable toggle parameter **minerva-monitor-question-fundamental**

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.43.28
If this is a bug, please provide steps for reproducing it.

![image](https://github.com/SAP/fundamental-ngx/assets/136554008/6d33d864-354b-4867-94f8-5a32f7ffa84e)

**Comment by droshev** [comment]
@akilhaidar123 This seems to be application specific string so you would need to contact the application development team about that.

**Comment by akilhaidar123** [comment]
> @akilhaidar123 This seems to be application specific string so you would need to contact the application development team about that.

Tooltip Close coming From NGx.

**Comment by droshev** [comment]
@akilhaidar123 check the configuration you are passing to the dialog.
