### ISSUE TITLE
notification component is always reads out the whole description along with page title for the first notification item

### ISSUE THREAD

**Issue by wei368** [SAP/fundamental-ngx#11537]
The default behaviour of fundamental-ngx notification component is always reads out the whole description along with page title for the first notification item. 

#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.

It would be better to read out the page title and action button only. Not include whole description

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

0.43.21

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

1. open notification component from ngx sample component. 
https://sap.github.io/fundamental-ngx/#/core/notification
![_thumb_1757351](https://github.com/SAP/fundamental-ngx/assets/5350405/f678a4a5-2185-418d-91c7-54245a9c36dd)

2. tab to the component indicated in the attachment. Use JAWS to read out the notification component one item by one item

3. You will hear notification component always reads out the whole description along with page title for the first notification item. 

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 

Yes, they recommend read out title and action button only 

#### Did you check the documentation and the API?

Yes

**Comment by droshev** [comment]
@nikolay-kolarov we would need you guidance again here. thanks

**Comment by nikolay-kolarov** [comment]
Hello @droshev,

The complaint here is that when the notifications are opened in a Popover they are announced in additioon. By principle when you open a dialog, you will hear the label of the dialog, the role dialog and info for the current focus element. Then on further navigation the user can explore the dialog. In some cases where the dialog contains short/important message then it can be included in the announcement (e.g this is done in the MessageBox in UI5).

For some reason the notifications have a role of alertdialog on their own and the structure becomes you open a dialog that contains alertdialogs in it, which is strange and I assume creates this announcement for which the tester complains.
![image](https://github.com/SAP/fundamental-ngx/assets/17043004/20183082-e172-45d1-906f-a3d0fd06d547)

Please revise the implementation. You can check the implementaion in UI5 as a reference for the used roles there: https://ui5.sap.com/#/entity/sap.m.NotificationListItem/sample/sap.m.sample.NotificationListItem

Best Regards,
Nikolay
