### ISSUE TITLE
Dropdown Dynamically Resizes Based on Selected Value

### ISSUE THREAD

**Issue by sbgreene1307** [SAP/fundamental-ngx#1154]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

The dropdown component will dynamically change size when the fd-dropdown__control button text is longer or shorter. The options in our dropdown vary greatly in length. We can fix the width of the dropdown using custom css, however any time a user adds a new value that is even longer, the text will run over the ::after pseudo element. 

If you try to use 
```
.fixed-width-dropdown {
  width: 180px !important;
  overflow: hidden !important;
  text-overflow: ellipsis !important;
  min-width: 100% !important;
}
```
The ::after element will be inside the fixed-width. The text will only have an ellipsis once the text meets the end of the 180px width.

If instead the ::after element were a separate element then our fixed width would cause the text to overflow properly. 

Of course we can write an angular pipe that truncates the text to a specific length, but the css solution would be the preferred method.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it.
Change the text of the dropdown to see it grow/shrink in size. 

Fix the width with: 
```
.fixed-width-dropdown {
  width: 180px !important;
  overflow: hidden !important;
  text-overflow: ellipsis !important;
  min-width: 100% !important;
}
```
Add long text to fill up the width.

**Comment by JKMarkowski** [comment]
Hi @sbgreene1307, Generally issues like that should be reported on [fundamental styles](https://github.com/SAP/fundamental-styles). We encountered similars problems having this pseudo elements ::after before.

**Comment by droshev** [comment]
the dropdown has been deprecated and removed and its successor is select/combobox
