### ISSUE TITLE
Paste does not display the popover in fd-combobox in windows

### ISSUE THREAD

**Issue by ambikesh-SAP** [SAP/fundamental-ngx#11543]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
We are using the fundamental core element fd-combobx. Whenever we try pasting something in search field for fd-combox the popover with result is not displayed in windows, it works correctly in MAC.

Can someone please look into this and advise whether it's by design?

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.31.x & latest

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. copy a text and try pasting it in search of fd-combox (in windows);
2. search results is not displayed in popover;
3. if you press enter/ delete a text and the the popover comes;

#### Please provide stackblitz example(s).
Can be replicated in https://sap.github.io/fundamental-ngx/#/core/combobox:~:text=Combobox%20as-,Search,-Field;
<img width="678" alt="Screenshot 2024-03-13 at 11 13 30 AM" src="https://github.com/SAP/fundamental-ngx/assets/162120960/9a23b216-2725-4121-bfe6-fd0a6a299643">

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

**Comment by droshev** [comment]
@ambikesh-SAP I am not able to reproduce the issue under windows
![Uploading win-combo.gif…]()

**Comment by mikerodonnell89** [comment]
@droshev I am able to replicate this issue on windows via keyboard shortcuts. @ambikesh-SAP can you verify that the fix deployed at https://deploy-preview-11565--fundamental-ngx.netlify.app/#/core/combobox and we'll merge the PR? Thank you
