### ISSUE TITLE
[Accessibility] [fd-select] wrong aria atrributes

### ISSUE THREAD

**Issue by Renkoru** [SAP/fundamental-ngx#11547]
#### Is this a bug, enhancement, or feature request?
accessibility issues

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular version: 17
Fundamental library: 0.48.4

#### Please provide relevant source code (if applicable).
![image (19)](https://github.com/SAP/fundamental-ngx/assets/3147119/1d0a49af-5635-4be5-b034-ab677b094a3a)
![image (18)](https://github.com/SAP/fundamental-ngx/assets/3147119/93c12bbb-9d63-4ea6-a14e-fe6d2668e535)
![image (17)](https://github.com/SAP/fundamental-ngx/assets/3147119/6c296d70-e8b5-4a00-96aa-d9819c66f6b2)

#### Did you search for similar issues?
yes

#### Is there anything else we should know?
We have analyzed fd-select with AMP tool (https://sap.levelaccess.net/)
Also google chrome lighthouse accessibility tool shows similar results

**Comment by InnaAtanasova** [comment]
Hi @Renkoru ,
Thank you for opening this issue. We need some help understanding the problem.
![Screenshot 2024-03-14 at 2 52 54 PM](https://github.com/SAP/fundamental-ngx/assets/39598672/d5f3fea0-efc2-45f1-80b8-be900f93ca71)

Which aria attributes are not valid in this case?

**Comment by InnaAtanasova** [comment]
![Screenshot 2024-03-14 at 2 54 22 PM](https://github.com/SAP/fundamental-ngx/assets/39598672/cd3c4bde-85b8-421b-9617-73544ccca564)

Regarding this issue, we couldn't find a duplicate or invalid ids. The ids are generated automatically by the library on component instantiation. Could you help us with more information here?
<img width="1445" alt="Screenshot 2024-03-14 at 2 47 25 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/32742451-a3d9-4c9d-9a16-154ec27a79a9">
<img width="1447" alt="Screenshot 2024-03-14 at 2 47 17 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/4d1b66aa-edeb-415a-aad0-9a247fb98f8e">
<img width="1437" alt="Screenshot 2024-03-14 at 2 47 06 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/0a76fb21-be6b-4bb5-8100-8f00394580a3">
<img width="1421" alt="Screenshot 2024-03-14 at 2 46 48 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/a8dc360e-a180-42a8-a562-39deffecdc75">

**Comment by droshev** [comment]
@Renkoru closing as we didn't get any update. Feel free to report a new ticket is you are able to reproduce the issue and provide us with stackblitz and the expectation
