### ISSUE TITLE
[Accessibility] [fd-card] role=region issue

### ISSUE THREAD

**Issue by Renkoru** [SAP/fundamental-ngx#11548]
#### Is this a bug, enhancement, or feature request?
accessibility issues

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular version: 17
Fundamental library: 0.48.4

#### Please provide relevant source code (if applicable).
![image (21)](https://github.com/SAP/fundamental-ngx/assets/3147119/427d9bc5-b552-4a9d-ba3b-a7178be44dbb)

#### Is there anything else we should know?
We have analyzed fd-select with AMP tool (https://sap.levelaccess.net/)

**Comment by InnaAtanasova** [comment]
Hi @Renkoru could you please provide more information regarding the problem? What is the expected role and why does role region present a problem? I checked with UI5 implementation and there the Card component also has role region. Thank you!
