### ISSUE TITLE
[Sourcing][P3]Value Help Dialog: Previous filter applied is persisted after closing/opening component

### ISSUE THREAD

**Issue by hbrnguyen** [SAP/fundamental-ngx#11542]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Previous filter applied is persisted after closing/opening component. In video, 'Name 137' is searched successfully, then filter is closed. Filter is reopened and field 'Product verified: Yes' is applied. We see that there are products that match this field, but none show up. This is because the filter 'Name 137' hasn't been cleared from the first search, so it is looking for a product with 'Name 137' and 'Product Verified: Yes'.

https://github.com/SAP/fundamental-ngx/assets/45953395/cf78bfc2-4e46-4142-9273-5ce88fccc15c

Reproduction Site (Basic Value Help Dialog): https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Current version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
See proposal and reproduce steps in first code example
https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

**Comment by droshev** [comment]
@hbrnguyen you need to press the button so the filter gets applied

**Comment by hbrnguyen** [comment]
Hi @droshev, the filter application works fine. The problem is when applying a filter and closing/reopening the popup to apply a different filter, the previous filter is still persisting. Can we please reopen this issue? Thanks!

**Comment by droshev** [comment]
@hbrnguyen that is expected behaviour, the user can change the filtering
