### ISSUE TITLE
Combobox control: The borders where is the arrow disappear on hover.

### ISSUE THREAD

**Issue by REIP** [SAP/fundamental-ngx#1155]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
The style of fd-button--light:hover should have the next to keep the border.
     border: 1px;
     border-radius: 2px !important;
and the border for the control does not already disappear.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
current version, 0.9.x

#### Please provide relevant source code if applicable.
It is related to the fd-button--light:hover

**Comment by droshev** [comment]
fixed
