### ISSUE TITLE
[P2][Sourcing][Accessibility] Not able to reach freeze/unfreeze buttons. On clicking freezable columns using keyboard, it is automatically freezing/unfreezing.

### ISSUE THREAD

**Issue by Pallavi-P-I585022** [SAP/fundamental-ngx#11578]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
On clicking the freezable column in fdp-table, it will automatically freeze/unfreeze. We cannot select the freeze/ unfreeze column buttons

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core / platform: 0.43.29

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Open the fdp table having freezable column with property [freezable] set to true
2. Using tab key reach the column header.
3. select the column header using enter key in keyboard
4. It will automatically freeze or unfreeze the column. We should be able to navigate to the buttons. But this is not possible.

#### Please provide relevant source code (if applicable).
https://stackblitz.com/edit/angular-9qxxca-ac9we5?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,src%2Fapp%2Fapp.module.ts

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-9qxxca-ac9we5?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,src%2Fapp%2Fapp.module.ts

https://github.com/SAP/fundamental-ngx/assets/163818610/624d9b08-8c4f-4c45-ab80-cd23edd6f22e

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
On clicking freezable column, we must move to freeze/unfreeze column button. Freeze/unfreeze column should be done only on again clicking these buttons.

**Comment by droshev** [comment]
If you press Enter with the menu `Freeze Column` then the column will freeze. If the column is frozen then you will see `Unfreeze Column` and by pressing Enter it will unfreeze the column

**Comment by I543348** [comment]
Hi @droshev ,
The issue is different than what you have added comment.
**Here when user is pressing ENTER on column header - at that point of time its getting Frozen without even moving to menu option.**

Could you pls reopen the issue and help?
Thanks much.

**Comment by sagar7259** [comment]
Hello,

the column headers should be activated by both spacebar and enter key to get the menu item 'Freeze/unfreeze column. 
There are two different behaviours here
1)  When enter key is used for this a menu will popup which has an item 'Freeze column', then user can select this to freeze a column.
2)  But for the same when spacebar is used, the column is getting frozen directly without showing any popup menu here.

The expected behaviour is that both enter and spacebar key should behave in the same manner.

Can you confirm the behaviour which is right..?

Regards,
Sagar

Regards,
Sagar

**Comment by I543348** [comment]
Reported a new issue https://github.com/SAP/fundamental-ngx/issues/11612 as this is not addressed
