### ISSUE TITLE
[Combobox] Arrow icon disappears when clicking on input field

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#11585]
The Combobox has an arrow icon on the input field that disappears when you click on the input field. This bug only visible in the theme "Quartz Light", which currently our default theme.
Here is a recording that shows the issue:

[scrnli_19_03_2024_16-53-35.webm](https://github.com/SAP/fundamental-ngx/assets/26272656/d8724e8c-56cb-46bb-8702-c3b0ca8649b9)

#### Is this a bug, enhancement, or feature request?
bug

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 17.x
Fundamental-NGX Core 0.48.4

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
See above recording

**Comment by InnaAtanasova** [comment]
Hi @zaheral thanks for reporting the issue. The PR for fixing it is in review and should be available soon. Thanks
