### ISSUE TITLE
Module not found Can't resolve 'fundamental-ngx/lib/tile/tile-grid/tile-grid.directive'

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#1158]
#### Is this a bug, enhancement, or feature request?

Bug (or misuse on my part) ?

#### Briefly describe your proposal.
Module not found: Can't resolve 'fundamental-ngx/lib/tile/tile-grid/tile-grid.directive' in ''
(however my IDE finds it without problem when I click in the import)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
Fundamental NGX: 0.7.0

#### If this is a bug, please provide steps for reproducing it.

Import TileGridDirective for change col and change col

#### Please provide relevant source code if applicable.

something like this

`
import {TileGridDirective} from 'fundamental-ngx/lib/tile/tile-grid/tile-grid.directive';
...

constructor( private tileGrid: TileGridDirective) {this.method()}
method(){...; this.tileGrid.col = 3;}
`

**Comment by harikusumba** [comment]
Have seen similar error with PaginationComponent too.
`
Module not found: Error: Can't resolve 'fundamental-ngx/lib/pagination/pagination.component' in ..
`
