### ISSUE TITLE
[P1][Sourcing][Accessibility]Table: The empty cell information is not conveyed through screenreader

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11596]
#### Is this a bug, enhancement, or feature request?
Bug,
Since the issue #10320 is no addressed.
Reopening as new issue.
the word"empty" is not being conveyed when user is on blank or empty cell without any value.
This is happening both in JAWS 2023 and JAWS 2024

#### Describe your proposal.
When user is using screenreader either jaws 2023 or 2024 version and traversing through empty cells, then the screenreader is not conveying empty cell information.
This should work both in VPC mode on and off of jaws.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
Core/ Platform: 0.43.29

#### Please provide relevant source code (if applicable).
can be replicable on NGX website : https://sap.github.io/fundamental-ngx/#/platform/table/basic
#### Please provide stackblitz example(s).
can be replicable on NGX website : https://sap.github.io/fundamental-ngx/#/platform/table/basic

**Comment by droshev** [comment]
@mikerodonnell89 you had fixed the original, can you check whether there is something wrong on our side?
