### ISSUE TITLE
Message Popover Form container example 

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#11602]
https://fundamental-ngx.netlify.app/#/platform/message-popover#form-container -> This example does not automatically recalculates the amount of errors, while form generator does

**Comment by droshev** [comment]
@InnaAtanasova we would need more context

**Comment by InnaAtanasova** [comment]
> @InnaAtanasova we would need more context

that's all I can provide. Denis logged it during the defect hunting
