### ISSUE TITLE
[P2][Sourcing][Accessibility][Dynamic page with table]: The table title is being read twice when its inside dynamic page content

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11614]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Press tab and reach the content of the dynamic page , and notice that the title of the table is being read twice.
Once as region and other time as group.
It should read only once.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core / platform: 0.43.29

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) Press tab and reach dynamic page content and notice the screenreader reading for title

#### Please provide relevant source code (if applicable).
https://stackblitz.com/edit/angular-knha3l-wpgdcf?file=package.json,src%2Fapp%2Fplatform-table-default-example.component.html,src%2Fapp%2Fplatform-table-default-example.component.ts

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-knha3l-wpgdcf?file=package.json,src%2Fapp%2Fplatform-table-default-example.component.html,src%2Fapp%2Fplatform-table-default-example.component.ts

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Reported by ATL

**Comment by mikerodonnell89** [comment]
closing as this has been fixed
