### ISSUE TITLE
[P2][Sourcing][Accessibility][Dynamic page]: Unnecessary breadcrumb word is being read even though there are no breadcrumbs

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11613]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Issue 1:
bring the focus on dynamic page header element 'fd-dynamic-page-header' and observe that the screenreader is reading "Breadcrumbs" word , and we dont have any breadcrumb yet in header element container.

Issue 2:
When we focus on first button of dynamic page header container, the screenreader is reading breadcrumb word again.
Where in we dont have breadcrumb at all.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular : 15
core / platform: 0.43.29

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Issue 1:
1) bring the focus on dynamic page header element 'fd-dynamic-page-header' and observe that the screenreader is reading "Breadcrumbs" word , and we dont have any breadcrumb yet in header element container.

Issue 2:
When we focus on first button of dynamic page header container, the screenreader is reading breadcrumb word again.
Where in we dont have breadcrumb at all.

<img width="1728" alt="Screenshot 2024-03-21 at 4 36 12 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/98ce858f-f110-4373-a0be-64051f82e6c7">
<img width="1728" alt="Screenshot 2024-03-21 at 4 36 29 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/4d3c21ba-357f-4c24-8856-2364bcb186d3">

#### Please provide relevant source code (if applicable).
Replicable on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/dynamic-page

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/dynamic-page

https://stackblitz.com/edit/angular-knha3l-wpgdcf?file=package.json,src%2Fapp%2Fplatform-table-default-example.component.html,src%2Fapp%2Fplatform-table-default-example.component.ts

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
This is reported by ATL

**Comment by InnaAtanasova** [comment]
> fix(core, platform): add fix for breadcrumb template not being rendered in Dynamic Page component #11676

hi @I543348 here's the PR for v15 https://github.com/SAP/fundamental-ngx/pull/11677
It's been merged

**Comment by I543348** [comment]
Thank you
