### ISSUE TITLE
Combo box does not clear invalid values

### ISSUE THREAD

**Issue by pavandk** [SAP/fundamental-ngx#11618]
#### Is this a bug, enhancement, or feature request?

Bug:
When we click on combobox and enter text/value which is not part of the dropdown value then it should be cleared when we move out of combobox.

https://github.com/SAP/fundamental-ngx/assets/1974613/be61e76d-37a1-4eba-ab95-9119c477160e

**Comment by droshev** [comment]
@pavandk according to https://experience.sap.com/fiori-design-web/combo-box/ it should allow custom value too
