### ISSUE TITLE
<fd-overflow-layout > Localization issues

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#11630]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.

More Icon is not localized issue in fd-overflow-layout

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.43.0
If this is a bug, please provide steps for reproducing it.
<img width="1181" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/136554008/dd90c1dd-c911-47fc-a54f-b84a531d323b">

**Comment by droshev** [comment]
This has been done - check `0.43.31`
