### ISSUE TITLE
[Sourcing][P1] Expand all in infinite scrolling on fundamental table is expanding only one level at a time.

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11638]
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15 
NGX 0.43.29

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
component is fdp-table and below are the steps to replicate

1. Create table with tree structure and table having infinite scrolling.
2. Now click on expand all with the data currently being loaded in the table. You observe that only one level being expanded.
3. If you click on expand all again, then next level gets expanded.

But this is not the expected behaviour with expand all. Also what do we see is that with virtual scroll this is been handled rightly. So we would ask you to have consistency with both the approach of scrolling in fdp table.

#### Is there anything else we should know?

***IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone.***

**Comment by sahanaN123** [comment]
https://github.com/SAP/fundamental-ngx/issues/11428 this is the ticket we had earlier and closed as not a bug. Our concern is that we are actually able to expand the data that we get after API call. But the concern now we have is with the data that is already been sent to NGX.
for eg: Consider the table with five levels of data and number of items in the table are 1000. The page size of the table is 50.
Now we load the table freshly and we click on expand all. what we observe is that one level from the loaded 50 items will be expanded, leaving other 4 levels collapsed. On application side, what we are doing is that the data we get after API call which is on demand as its an infinite scrolling. we are reading allRowsExpanded and setting next of data in expanded state. But the control to set first 50 items completely to expanded is not with application and something need to addressed by NGX.

**Comment by droshev** [comment]
@sahanaN123 We have a custom [example](https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic#tree) on our doc site where the expand all (again implemented on the application side) works. Can you create a similar stackblitz example where your expand all doesn't work properly?

**Comment by mikerodonnell89** [comment]
@sahanaN123 It would be helpful for this case to be isolated to a stackblitz so we can have a better idea of your situation - I'm confused about how the data is "already sent to ngx" but not rendered in the table. But I have some ideas on solutions for you. One option would be to utilize the `expandAll()` function on the table component programmatically whenever you need.  Check out this stackblitz, see what I'm doing with the `(allRowsExpanded)` event in the HTML and the `dataFinalized` event in the typescript: https://stackblitz.com/edit/usdyvu?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html

Also worth experimenting with the `expandedStateKey` you can see in action here: https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/preserved-state

Let me know if you have further questions

**Comment by sahanaN123** [comment]
@mikerodonnell89 , please find the stackblitz replicating the issue. Also, sharing the recording which shows, on click of expand all, only first level is expanded in table when infinite scrolling is implemented. 

https://github.com/SAP/fundamental-ngx/assets/110370099/60951729-0c64-45e4-b370-8224033b0345

[expand all issue](https://stackblitz.com/edit/angular-ugca8x-vfbz2u?file=src%2Fapp%2Fdynamic-page-tabs-example.component.ts,src%2Fapp%2Fdynamic-page-tabs-example.component.html)

**Comment by mikerodonnell89** [comment]
Thanks for the stackblitz and video, I was confused about what you were describing because this problem you're demonstrating isn't actually related to any scrolling feature. My suggestions earlier pertain to handling the expansion of newly loaded items after a page scroll - those may still be helpful if you are indeed concerned with that issue. 

The issue you are describing is actually because you are using the `childDataSource` feature, which is intended to be used when you wish to load child data in a separate load from the main parent. If you have all of your data loaded into a single datasource, and click the expand all button, all nodes with child nodes will be expanded. I've modified your stackblitz to use just one datasource here: https://stackblitz.com/edit/angular-ugca8x-oxhssk?file=src%2Fapp%2Fdynamic-page-tabs-example.component.ts

https://github.com/SAP/fundamental-ngx/assets/2471874/8a600f6d-8e27-4126-a667-0c2b4309b6e7

Hope that helps!

**Comment by sahanaN123** [comment]
Hello @Mike,
   its required for us to have child datasource. But what i did try was expandAll() on the table component. This worked and was able to expand all the levels. But i observed is, when i have 2000 entries in the table and did infinite scroll till i get all the entries in the table i.e; loading all 2000 line items and clicked expand all. The table got frozen for few moment. Is there something that NGX can help us here??
Thanks,
Sahana.

**Comment by mikerodonnell89** [comment]
> Hello @mike, its required for us to have child datasource. But what i did try was expandAll() on the table component. This worked and was able to expand all the levels. But i observed is, when i have 2000 entries in the table and did infinite scroll till i get all the entries in the table i.e; loading all 2000 line items and clicked expand all. The table got frozen for few moment. Is there something that NGX can help us here?? Thanks, Sahana.

If you are using a child data source it will call the loadChildRows function many times, and I'm not sure there's any workaround for that, data will be loaded even if it is not yet rendered to an element. Maybe you want to use the `[expandOnInit]` input?

**Comment by sahanaN123** [comment]
Sure @mikerodonnell89 , we will try to minimise the calls for child data source if possible.
