### ISSUE TITLE
[Sourcing][P1] Can we have cells clickable in fdp-table

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11639]
#### Describe your proposal. 

Currently in fdp-table we have row clickable. But our business use case we need each cell in the row to be clickable.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
NGX 0.43.29

#### Is there anything else we should know?

***IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone.***

**Comment by droshev** [comment]
@sahanaN123 There is nothing written in the ticket. Can you try to answer the questions and give us more context?

**Comment by sahanaN123** [comment]
@droshev : Currently in fdp-table we have entire to be row clickable. But for our business use case we need each cell in the row to be clickable. Attaching the recording from our existing UX . So we are expecting the same with NGX platform table as well.

https://github.com/SAP/fundamental-ngx/assets/110370099/5f7de094-110a-4072-8983-7d9431e9380f

**Comment by droshev** [comment]
@sahanaN123 you need to remove the internal solutions from external tickets.

**Comment by droshev** [comment]
@mikerodonnell89  @sahanaN123 - from the recording that i saw i think platform table doesn't look the best component for this feature. Maybe @sahanaN123 can go with a custom component?

**Comment by mikerodonnell89** [comment]
@sahanaN123 the recording you shared with me was relating to your other issue, #11638

**Comment by droshev** [comment]
@sahanaN123 Can you create a stackblitz example with your usecase and explain why you need to use the platform table

**Comment by sahanaN123** [comment]
@droshev : We are using fdp-table along with advance techniques to render complex tree table. So this component is the best option to render our data.

@mikerodonnell89 : We need an event to be triggered when user click on cell. So that we perform further actions at our end. Also the focus should be moved to that cell. Please consider that we have internally adding a input field for user to enter a value. So when they click on input field, that should not be consider as the cell click.

**Comment by sahanaN123** [comment]
> @sahanaN123 the recording you shared with me was relating to your other issue, #11638. For this issue we need more details about what needs to be passed with this event you'd like to have

I have shared the recording with you on teams. Please do check.

**Comment by mikerodonnell89** [comment]
> > @sahanaN123 the recording you shared with me was relating to your other issue, #11638. For this issue we need more details about what needs to be passed with this event you'd like to have
> 
> I have shared the recording with you on teams. Please do check.

I just checked and the video you sent me is about the tree table row expansion issue you filed.

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89 : We need an event to be triggered when user click on cell. So that we perform further actions at our end.

The table fires an event `cellFocused` you may find useful

![Screenshot 2024-04-03 at 10 05 19 AM](https://github.com/SAP/fundamental-ngx/assets/2471874/7238f3b7-2c8a-4a7f-a03c-f173ce6d22a0)

You have explained that you'd like an event for a cell being clicked (and this should meet that criteria, but additionally this event is also fired when the user navigates to a cell using the keyboard). However you haven't explained what (if any) parameters you'd like to see passed through the event

cellFocused event looks like this in practice:

`<fdp-table (cellFocused)="handleCellFocused($event)">`

```
    handleCellFocused(event: any): void {
        console.log(event);
    }
```

**Comment by sahanaN123** [comment]
Sure @mikerodonnell89 . Let me try this and get back to you. Thanks

**Comment by droshev** [comment]
@sahanaN123 I think there isn't any issue to be solved here so i will close the issue. You can explore our [documentation](https://ng-15-downport--fundamental-ngx.netlify.app/#/core/home) and you don't have to stop here. You can even check out the typescript source in the repository

**Comment by sahanaN123** [comment]
@mikerodonnell89 / @droshev : We tested the suggested solution. but its meeting our expectation where in each cells are not clickable which deviates from our current UX. So we would ask to re-open the issue and provide us the solution where each cell be clickable and emit the event with cell details in the emitted event. I hope the concern is understood.

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89 / @droshev : We tested the suggested solution. but its meeting our expectation where in each cells are not clickable which deviates from our current UX. So we would ask to re-open the issue and provide us the solution where each cell be clickable and emit the event with cell details in the emitted event. I hope the concern is understood.

Cells are "clickable" - as made evident in some videos above. As for the event, what do you mean regarding "cell details"? The element itself? Some object representing the data within a cell? Are you able to utilize the cellFocused event to get the cell you're looking for? You could also add event listeners to the cells after they're rendered: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by sahanaN123** [comment]
Are you saying that now cells are clickable in fdp-table?? Also yes, we would expect the object representing the cell data.
