### ISSUE TITLE
Floating Footer in Flexible Column Layout

### ISSUE THREAD

**Issue by julia-siegl** [SAP/fundamental-ngx#11640]
#### Is this a bug, enhancement, or feature request?
Enhancement/ Bug

#### Describe your proposal.
When using the floating footer bar design in a dynamic page inside column layout, it would be great if each column gets is own footer toolbar instead of a overall footer toolbar spanning several columns to be in alignment with guidelines. Currently the code, e.g. used   in example https://sap.github.io/fundamental-ngx/#/core/dynamic-page#layout:
```
<fd-dynamic-page-footer>
    <!-- page footer content goes here -->
        <div fd-bar barDesign="floating-footer">
            ....
       </div>
</fd-dynamic-page-footer>
```

leads to an footer that is spanned over multiple columns:
![image](https://github.com/SAP/fundamental-ngx/assets/143191726/55396ec0-be44-4e4d-a275-f9f232b3c6bd)
([source](https://sap.github.io/fundamental-ngx/#/core/dynamic-page#layout) is library example)

Guideline:

<img width="539" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/143191726/968b43bc-52f3-4f88-8db3-e6bc54a4c6d4">

([source](https://experience.sap.com/internal/fiori-design-web/flexible-column-layout/#footer-toolbar))

#### Can you handle that on the application side
Implementing dynamic resizing/positioning on application side seems like a workaround.
Can use the 'normal' footer ([here](https://sap.github.io/fundamental-ngx/#/core/bar#footer)), which is placed as expected, but not ideal.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

"@angular/core": "^17.1.1",
"@fundamental-ngx/core": "^0.49.0-rc.24",

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
- Check out library example:
https://sap.github.io/fundamental-ngx/#/core/dynamic-page#layout

#### Did you check the documentation and the API?
yes, issue also in the documentation, API in bar did not change floating footer ( e.g. tried _inPage_, _inHomePage_, _size_)...

#### Did you search for similar issues?
yes, nothing found

**Comment by droshev** [comment]
example https://stackblitz.com/edit/1hqnwx

**Comment by InnaAtanasova** [comment]
Hi @julia-siegl you can add a very quick fix to your project by adding position relative to the dynamic page. 
If you add 
```
<ng-template #startColumn>
    <fd-dynamic-page [autoResponsive]="true" ariaLabel="Example Dynamic Page" style="position: relative;">
       ...
    </fd-dynamic-page>
</ng-template>
```

it will result to this:
<img width="2556" alt="Screenshot 2024-04-01 at 2 35 23 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/125152d7-aa4f-4c18-99d9-c17b7586fe11">

**Comment by julia-siegl** [comment]
Hi @InnaAtanasova, thank you for providing this solution. 
One remark, wouldn't it make sense to set the default positionRelative to true rather then false [here](https://github.com/SAP/fundamental-ngx/pull/11678/files#diff-6505ba7effbc7d770e3e1c1eb9cd480cde4d566090888ff42ee88eccbe1b91c5R109) to a) be in alignment to guideline and b) since other bar / footer bar types (e.g. 'normal' footer [here](https://sap.github.io/fundamental-ngx/#/core/bar#footer)), are by default relative?

**Comment by InnaAtanasova** [comment]
> here

Hi Julia, it makes sense what you wrote but since this is an existing component already used in many applications we don't want to break something on user's side. Our practice is to always keep the default behaviour as it was and add new functionality with props so the changes on applications side are minimal or none.
