### ISSUE TITLE
fd-toolbar buttons are cropped in fd-dynamic-page-layout-actions

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#11654]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
![image](https://github.com/SAP/fundamental-ngx/assets/86781159/accb76c0-8f3b-485f-961b-1c4e4946d95f)

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 17.3.1
FundamentalNGX 0.49.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
`fd-dynamic-page > fd-dynamic-page-header > fd-dynamic-page-global-actions > fd-toolbar > button[fd-toolbar-item fd-button]`

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/yee48a?file=src%2Fapp%2Fdynamic-page-routing-example.component.html

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
No

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by programister42** [comment]
> @programister42 Which buttons are cropped?

![image](https://github.com/SAP/fundamental-ngx/assets/86781159/87c797cd-2705-4a4f-a627-9f88c0d2efb5)
In this example, the "Accept" and "Reject" buttons are cropped.

These buttons are inside the `fd-toolbar` in the `fd-dynamic-page-global-actions` component.

**Comment by dpavlenishvili** [comment]
> > [@programister42](https://github.com/programister42) Which buttons are cropped?
> 
> ![image](https://private-user-images.githubusercontent.com/86781159/318422351-87c797cd-2705-4a4f-a627-9f88c0d2efb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTY5NDEsIm5iZiI6MTcyMTk5NjY0MSwicGF0aCI6Ii84Njc4MTE1OS8zMTg0MjIzNTEtODdjNzk3Y2QtMjcwNS00YTRmLWE2MjctOWY4OGMwZDJlZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEyMjQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMWQzZTNiMTBjNTdjMWVkMzhmMWE0OTBjNmI3Njc2YWZlZTBjYmYxYjU0ZWM1OGM5YjRhMDllMzc2ZjczNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKcv9_9WYrN3oy14ucmqc_E0uTE4wvCjKxwQt93XNiY) In this example, the "Accept" and "Reject" buttons are cropped.
> 
> These buttons are inside the `fd-toolbar` in the `fd-dynamic-page-global-actions` component.

Is this problem still valid? i am checking 0.49.0 version and this bug is not appearing.


![Image](https://github.com/user-attachments/assets/19aceb92-b562-4f51-9533-018382f31eb4)

**Comment by InnaAtanasova** [comment]
<img width="1712" alt="Screenshot 2024-07-26 at 10 24 01 AM" src="https://github.com/user-attachments/assets/46d4dd22-cabb-4268-82e7-8a6b8c6178d7">

Hi @programister42 , the problem comes from the different content densities of the elements. The toolbar is in a compact mode while the buttons are in cozy mode. While it's possible to use elements with different density modes, it's not recommended and can cause issues like this. Your buttons should be in compact mode OR set the mode of Toolbar to cozy. Let us know if you have more questions.
