### ISSUE TITLE
Add the ability to use Routing in Platform Dynamic Page

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#11655]
#### Is this a bug, enhancement, or feature request?
feature request

#### Describe your proposal.
I am asking if you could add the ability and documentation on how to use routing on the Platform Dynamic Page, just like you did for the Core Dynamic Page
https://sap.github.io/fundamental-ngx/#/core/dynamic-page#routing

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 17.3.1
FundamentalNGX 0.49.0

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
No

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@programister42 any update?

**Comment by programister42** [comment]
@droshev Sorry for not answering! We thought there was some style difference between core and platform dynamic page. Now we are using core dynamic page with routing and it seems to meet our requirements
