### ISSUE TITLE
[P4][Sourcing][Accessibility]Add Content From Sourcing Library-tooltip is not showing the exact text

### ISSUE THREAD

**Issue by Sunilkumarbssap** [SAP/fundamental-ngx#11675]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
After selecting value from multi input, tooltip is not showing the exact text for the selected values.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core / platform: 0.43.29

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Select values from multi input.
2. Mouse over on the selected value.
3. Tooltip should show for the selected value.

#### Please provide relevant source code (if applicable).
https://github.com/SAP/fundamental-ngx/blob/main/libs/core/multi-input/multi-input.component.html

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/6jb1hz?file=src%2Fapp%2Fmulti-input-example.component.ts,src%2Fapp%2Fmulti-input-example.component.html

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**
<img width="1726" alt="MC" src="https://github.com/SAP/fundamental-ngx/assets/165650658/1e8d8069-478d-4f1d-bafb-b1f1f2eef11e">

<img width="1726" alt="Screenshot 2024-06-14 at 12 53 15 PM" src="https://github.com/SAP/fundamental-ngx/assets/165650658/184a15e3-a1ec-4382-944c-6736c8dfa10c">

**Comment by droshev** [comment]
For me the tooltip is not cut from the stackblitz you have provided
![Screenshot 2024-05-23 at 14 44 29](https://github.com/SAP/fundamental-ngx/assets/4380815/a0cfaf66-25ca-4dec-82ed-e658407d6872)

@Sunilkumarbssap Can you provide more descriptive steps and what's wrong what the expectation is?

**Comment by Sunilkumarbssap** [comment]
@droshev Thanks for the response. Sorry for the delay and i didn't receive any response notification. 
Tooltip is not working in the  below motioned details 
Angular: 15
core / platform: 0.43.29
PLease find the link and attachment.
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/multi-input
<img width="1726" alt="Screenshot 2024-06-14 at 12 53 15 PM" src="https://github.com/SAP/fundamental-ngx/assets/165650658/d370be41-ee93-4499-806b-13ab6ad29db0">

**Comment by mikerodonnell89** [comment]
Looks like this is something we have on main that wasn't downported to the ng15 branch. From https://github.com/SAP/fundamental-ngx/pull/11121

But, also looks like ui5 doesn't do this:
https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInput
https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox

Nor ui5 webcomponents (select the last option):
https://sap.github.io/ui5-webcomponents/components/MultiComboBox/

So if anything, I think we need to remove this from main
