### ISSUE TITLE
[P2][Sourcing] Breadcrumb does not pass click when collapse in the menu

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#11685]
#### Is this a bug, enhancement, or feature request?
enhancement or feature request

#### Describe your proposal.
In `breadcrumb-item.component.ts` :

```typescript
get _needsClickProxy(): boolean {
        return  !!this.breadcrumbLink?.elementRef.nativeElement.getAttribute('href') || !!this.breadcrumbLink.routerLink;
    }
```

But we cannot use simply use <code>href</code> attribute or <code>routerLink</code> directive. We are handling click event manually in the `fd-breadcrumb-item`

However, If breadcrumb is in a menu, `(click)` event won't be trigger

#### Can you handle that on the application side
No workaround from my application

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
V0.49.3

#### Please provide relevant source code (if applicable).
```html
<fd-breadcrumb class="breadcrumb-style" *ngIf="containsCurrentInBreadcrumbs() ? breadcrumbs.length > 1 :  breadcrumbs.length >0">
    <ng-container *ngFor="let bc of breadcrumbs">
        <fd-breadcrumb-item>
            <a *ngIf="bc.routerLink" fd-breadcrumb-link (click)="breadscrumbClick(bc)">{{bc.name}}</a>
        </fd-breadcrumb-item>
    </ng-container>
</fd-breadcrumb>
```

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Not an ADA issue

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@oscargong We couldn't not understand the problem and the use case. Do you think you can elaborate more?

**Comment by oscargong** [comment]
Hi @droshev 

I made a stackblitz example:

https://stackblitz.com/edit/e2njgi?file=src%2Fapp%2Fbreadcrumb-routerLink-example.component.html

Also a screen recording:

https://github.com/SAP/fundamental-ngx/assets/7035787/72474bab-9cc1-4b7f-a0ae-10a1148a2379

I have a `(click)` event bind to the  `<a>` inside the `fd-breadcrumb-item`

**Comment by droshev** [comment]
> Breadcrumb is used to indicate the table tree node hierarchy, not route.

@oscargong are you using the breadcrumb to manipulate the tree? It doesn't seem correct usage of it.

**Comment by oscargong** [comment]
> > Breadcrumb is used to indicate the table tree node hierarchy, not route.
> 
> @oscargong are you using the breadcrumb to manipulate the tree? It doesn't seem correct usage of it.

Not directly. We are using the breadcrumb to show the hierarchy of the table. 

I think this is fine use case as guideline mentioned:

![Oscar ScreenCapture 2024-04-06 at 12 15](https://github.com/SAP/fundamental-ngx/assets/7035787/34c53702-eb6f-452b-baf0-a23b4abd5bc6)

https://wiki.one.int.sap/wiki/display/SFSFSPM/Breadcrumb

**Comment by oscargong** [comment]
Could we have an EventEmitter similar to the `item-click` event in UI5-WebComponent?

https://sap.github.io/ui5-webcomponents/components/BreadcrumbsItem/

<img width="866" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/7035787/5e7fbc18-a021-4808-91f9-bbb633a06689">
