### ISSUE TITLE
fdp-table header empty with i18n package

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#11682]
#### Is this a bug, enhancement, or feature request?
bug ?

#### Describe your proposal.
_I've been using fundamental since version ~0.8.  
I have a well-known library that handles i18n: ngx-translate in association and have never had any problems since._  
  
Since the switch to angular 17 (with the versions requested by fundamental). 
**The header of my fdp-table is empty**. 
At first, I thought it was a ngx-translate problem. 
I then tested with transloco, another i18n library, and the same problem was observed: my fdp-table headers are empty. No text is displayed.
All other text is well displayed and translated in any other fundamental component.
I don't know if it's due to the initialization of the fdp-table component that's causing this problem. Or something else.
(In the stackblitz, used as an example, all headers are translated (but not displayed) and so is the "Order Line Items" (no problem for it)).

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

* Angular version: 17.3.0
* Fundamental version: 0.49.2

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Any project with angular 17, fundamental and either the i18n transloco or ngx-translate package

#### Please provide stackblitz example(s).  
* [Stackblitz example](https://stackblitz.com/edit/jusbrs?file=src%2Fapp%2Ftable-custom-pagination-example.component.html)

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

**Comment by MehdiNabiClapLabs** [comment]
Hi Guys, any news on this ? We have multiple apps in production awaiting this to be fixed to be updated.

**Comment by khotcholava** [comment]
Hello @MehdiNabiClapLabs. You can use this approach until the actual fix is implemented, if you are blocked. 


```html
fdp-table
  [dataSource]="source"
  selectionMode="multiple"
  relationKey="children"
  emptyTableMessage="No data found"
  bodyHeight="300px"
  [pageSize]="pageSize"
  (pageChange)="pageChanged($event.current.currentPage)"
  [state]="state"
  [showGrowingButton]="true"
  [showItemsCount]="true"
  #table
>
  <fdp-table-toolbar
    [title]="'toolbar.title.orderLineItems' | transloco"
    [hideItemCount]="false"
    [hideSearchInput]="true"
  />

  <fdp-column name="name" key="name" align="start">
    <ng-container *fdpHeaderCellDef="let column">
      {{ 'table.header.name' | transloco }}
    </ng-container>
  </fdp-column>

  <fdp-column name="description" key="description">
    <ng-container *fdpHeaderCellDef="let column">
      {{ 'table.header.description' | transloco }}
    </ng-container>
  </fdp-column>

  <fdp-column name="price" key="price.value" align="end">
    <ng-container *fdpHeaderCellDef="let column">
      {{ 'table.header.price' | transloco }}
    </ng-container>
  </fdp-column>

  <fdp-column name="status" key="status" align="center">
    <ng-container *fdpHeaderCellDef="let column">
      {{ 'table.header.value' | transloco }}
    </ng-container>
  </fdp-column>
</fdp-table>
```

**Comment by JohnHavok** [comment]
Thanks for the workaround and the fix
