### ISSUE TITLE
Disabling of tabs in "fdp-icon-tab-bar" component

### ISSUE THREAD

**Issue by dreamweiver** [SAP/fundamental-ngx#11739]
#### Is this a bug, enhancement, or feature request?
**Feature Request**

#### Describe your proposal.:

I am using fdp tab component in my application and recently we for a requirement for the customer to implement a certain feature in the app like disabling certain tabs to indicate they are not accessible at the moment but available in the app.

when i checked NGX fundamental api's, i couldn't find any info about dynamically enabling or disabling of tabs and when i further investigated, i found this old issue [(bug-2651)](https://github.com/SAP/fundamental-ngx/issues/2651) that was created for same reason but closed due to insufficient business requirement. 

#### Can you handle that on the application side ? 
**NO**

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.) ?

**Angular** : 17.2.0
**ngx fundamental** : 0.48.4

#### If this is a bug, please provide steps for reproducing it; the exact components you are using:
**there are no steps to reproduce, it's a feature request.**

#### Please provide relevant source code (if applicable): 
**NA**

#### Please provide stackblitz example(s): 
**NA**

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. : 
**NA**

#### Did you check the documentation and the API?
**YES, i did check the documentation and this feature was never supported.**

#### Did you search for similar issues?
**YES, there was a similar issue and it was closed due to insufficient data, https://github.com/SAP/fundamental-ngx/issues/2651**

#### Is there anything else we should know?
**NA**

**Comment by droshev** [comment]
@dreamweiver I discussed this request with the designers. They would need a detailed requirement related to that so we can consider adding what you asked in the design specs. Do you think you can contact me through Teams for the next steps?

**Comment by dev-kalleno** [comment]
Why we need to provide more details on that feature? Disabling a tab is a bare minimum feature, should be not that difficult to add. 

We even cant bind a class to the element to add that basic feature via css. 

Please consider that feature request

**Comment by droshev** [comment]
@dev-kalleno That is why the designers need some use cases. Do you think you can contact me in teams and share your use-case(s)?
