### ISSUE TITLE
Icons in RTL mode

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#1174]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Icons in the menu items should flip horizontally when in RTL mode. This can be made optional(for eg, if icon is a checkmark, it doesn't make sense to flip it in RTL).
LTR: 
<img width="210" alt="Screenshot 2019-08-26 at 10 50 20 AM" src="https://user-images.githubusercontent.com/53509521/63666948-9e645f00-c7ef-11e9-8208-604ac9d036f7.png">
RTL:
<img width="214" alt="Screenshot 2019-08-26 at 10 50 33 AM" src="https://user-images.githubusercontent.com/53509521/63666954-a3c1a980-c7ef-11e9-8505-b0a5fb188954.png">
Checkmark in RTL should not flip:
<img width="210" alt="Screenshot 2019-08-26 at 10 53 57 AM" src="https://user-images.githubusercontent.com/53509521/63667005-dd92b000-c7ef-11e9-8054-b8cd28b28220.png">

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
Fundamental NGX 0.9.0

#### Is there anything else we should know?

**Comment by JKMarkowski** [comment]
Hi @kavya-b you should for sure put it to [fundamental-styles](https://github.com/SAP/fundamental-styles) library. It should be introduced with whole menu addOn feature.

**Comment by kavya-b** [comment]
Hi @JKMarkowski, so is fundamental-styles library currently open for making changes? If not, then this issue will remain open for a while. As per our last call, my understanding was that any changes to fundamental-styles is parked for now.

**Comment by kavya-b** [comment]
Hi @droshev, any update on if this will be taken up?

**Comment by droshev** [comment]
@kavya-b looks like not all the icons needs to be flipped(https://material.io/design/usability/bidirectionality.html#mirroring-layout). Only icons that show directions(e.g. back button) need to be flipped. @kavya-b in your example the icons in the menu do not need to be flipped.
