### ISSUE TITLE
[Sourcing][P2][Accessibility][Table Search]: Row 1 and Row2 are being read on accessing table search which is not meaningful

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11753]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
On accessing search input box, some extra words like "Row1 , Row2" are being read as if focus is inside table.
This will create confusion for disabled users.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/ platform: 0.43.32

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) move the focus on search box using JAWS
2) notice the reading 
<img width="338" alt="Screenshot 2024-04-15 at 5 29 59 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/d899fe9e-6ef2-460b-97b6-4e7206e565fd">
as attached below

#### Please provide relevant source code (if applicable).
Replicable on https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic with 0.43.32

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
This is reported by Accessibility test lab team

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
<img width="1145" alt="Screenshot 2024-04-24 at 12 40 16 PM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/7f1d0f5d-891e-4576-a28f-45efa01f7b9c">

Unable to recreate this on our docs site - can you isolate the issue to a stackblitz?

**Comment by sagar7259** [comment]
Hello,

This issue is no more reproducible now as per the verification in

https://stackblitz.com/edit/angular-9qxxca-hgtuob?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json

This ticket can be closed.

Regards,
Sagar

**Comment by I543348** [comment]
> <img alt="Screenshot 2024-04-24 at 12 40 16 PM" width="1145" src="https://private-user-images.githubusercontent.com/2471874/325343606-7f1d0f5d-891e-4576-a28f-45efa01f7b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDA1NjAsIm5iZiI6MTcxNTE0MDI2MCwicGF0aCI6Ii8yNDcxODc0LzMyNTM0MzYwNi03ZjFkMGY1ZC04OTFlLTQ1NzYtYTI4Zi00NWVmYTAxZjdiOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDM1MTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE0MzEwNDUxNjM0YWQxNDdjYWY4OGI4ZGRmYzlmYWUwNTY5MGMzMmI5Y2U1ODg1M2FlMDFiZTVjMWNmMGYwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bdscSIqEKXyXBInVwoVK9_FJtV_cG1tpNwHo91_Jw5A">
> Unable to recreate this on our docs site - can you isolate the issue to a stackblitz?

Hi @mikerodonnell89 , hope you checked on ng15 site and not on latest angular site?

**Comment by I543348** [comment]
Hi @mikerodonnell89 , @droshev ,
Confirmed from ATL team that the issue is no more replicable on 0.43.33
