### ISSUE TITLE
Placeholder is not displayed when the combobox is disabled

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#11757]
#### Is this a bug, enhancement, or feature request?

Bug, I suppose

#### Describe your proposal.

Placeholders are not displayed if the combobox is disabled. Is this an intentional behavior or a bug? We would like to be able to display placeholders in disabled comboboxes

![image](https://github.com/SAP/fundamental-ngx/assets/86781159/3307a64b-0c8d-4469-8f71-03ee256196fc)

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 17.3.1
FundamentalNGX 0.49.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Combobox with reactive form control

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/cif8ev?file=src%2Fapp%2Fcombobox-forms-example.component.html,src%2Fapp%2Fcombobox-forms-example.component.ts

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by InnaAtanasova** [comment]
Hi @programister42 , the visual specs state that "there is no placeholder variant for disabled inputs, the placeholder text is only available for editable states."

**Comment by programister42** [comment]
> Hi @programister42 , the visual specs state that "there is no placeholder variant for disabled inputs, the placeholder text is only available for editable states."

Okay, I get it. But is it possible to make the styles of disabled combobox more obvious, for example make the background gray as it is implemented in sapui5 component: ![image](https://github.com/SAP/fundamental-ngx/assets/86781159/ef4f710c-1abd-41bd-867e-c71ec5e3d7b0), because it is not very obvious to our users that this field is disabled.

**Comment by droshev** [comment]
@programister42 we all are supposed to follow one design:
<img width="361" alt="Screenshot 2024-04-19 at 11 37 45" src="https://github.com/SAP/fundamental-ngx/assets/4380815/e01276a6-5b00-4b6d-b4fc-1ec0cefa23f2">

our case
<img width="731" alt="Screenshot 2024-04-19 at 11 38 25" src="https://github.com/SAP/fundamental-ngx/assets/4380815/06dca54a-641d-4746-9435-4e190027e118">
