### ISSUE TITLE
Add possibility make generic tag unclickable  

### ISSUE THREAD

**Issue by Tomashow** [SAP/fundamental-ngx#11770]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Describe your proposal.

Make possibility make generic take unclickable (change cursor to default) ,as it can be used in situations when it should be unclickable (in cards, headers) and be only for informative goal.

#### Can you handle that on the application side

Yes

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 17.3.1
FundamentalNGX 0.49.0

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@Tomashow if you want to use something with informative objective then you can use [Object Status](https://fundamental-ngx.netlify.app/#/core/object-status) - you can read more [here](https://experience.sap.com/fiori-design-web/object-display-elements/#object-status) too

**Comment by Tomashow** [comment]
Thanks for answer, works for us!
