### ISSUE TITLE
Input in edit mode change padding in another inputs on the page in global compact mode

### ISSUE THREAD

**Issue by Tomashow** [SAP/fundamental-ngx#11782]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
After using ContentDensityModule and switching application form cozy to compact mode during the editing input it remove padding form  class fd-input-group .fd-input-group__input:first-child  and it jumping 

example on combobox components (the same with date picker)
![image](https://github.com/SAP/fundamental-ngx/assets/72388089/bebbf8e6-51ec-47cb-84ff-6efdd966e170)

 

#### Can you handle that on the application side

Yes

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 17.3.1
FundamentalNGX 0.49.0

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@Tomashow is the issue that when you toggle the compact/cozy the spacing is changing?

**Comment by droshev** [comment]
no activities => closing the issue
