### ISSUE TITLE
[BUG] The skeleton view in the table does not work with responsive features

### ISSUE THREAD

**Issue by pawelkarwat** [SAP/fundamental-ngx#11799]
Skeleton loading does not work properly alongside page responsiveness features in the Table fundamental-ngx/platform component. If we use [fdpTableCellResponsive] and hide columns or utilize popping columns, skeleton loading does not appear as expected.

Steps to reproduce:
1. Utilize the Table component in the platform.
2. Implement hiding columns or popping columns using [fdpTableCellResponsive].
3. Adjust the screen width to hide a column.
4. Refresh the page to initiate data loading and observe the skeleton loading behavior.

Expected behavior:
During both loading and display states, the skeleton loading should display the same number of columns in the table as after loading the data.

**Comment by droshev** [comment]
@pawelkarwat 
```
During both loading and display states, the skeleton loading should display the same number of columns in the table as after loading the data.
```
according by who?

**Comment by pawelkarwat** [comment]
![2024-04-19_15-18-13](https://github.com/SAP/fundamental-ngx/assets/43954783/c7c02109-c7d3-4e19-803f-a138831771e0)
Displaying it this way doesn't look very good, so I suggest sticking to the same number of columns in the skeleton.

**Comment by droshev** [comment]
@pawelkarwat then this is up to the application to implement it in their fashion.
