### ISSUE TITLE
[BUG]  implementing custom platform table loading  logic

### ISSUE THREAD

**Issue by esporysz** [SAP/fundamental-ngx#11800]
In documentation https://fundamental-ngx.netlify.app/#/platform/table/basic#loading we can read:

_By default, Table tracks these loading events and apply loading state internally. However, you can modify this logic by using **onDataRequested** and **onDataReceived** methods and **loading** input on the component_

Currently it is not possible to use loading Input because this is private field     [private loading: boolean | undefined;](https://github.com/SAP/fundamental-ngx/blob/92d29641465f47392e34dfb8613ec66624bc0d11/libs/platform/table/table.component.ts#L747).

Needed input to implement custom loading logic.

**Comment by mikerodonnell89** [comment]
Can you instead use the public `loadingState`? https://github.com/SAP/fundamental-ngx/blob/92d29641465f47392e34dfb8613ec66624bc0d11/libs/platform/table/table.component.ts#L626

**Comment by esporysz** [comment]
Thank you for your answer,
loadingState is a getter. I need sth to set loading value and delay loading indicator visibility. Is is currently possible?

**Comment by mikerodonnell89** [comment]
@dmitry-stepanenko Do you recall why you made this input private? From this PR: https://github.com/SAP/fundamental-ngx/pull/7671

The documentation has me inclined to think we want to keep it public, allowing the application developer to handle loading state manually, if they desire

**Comment by dmitry-stepanenko** [comment]
Hey @mikerodonnell89, most likely it was set as private to prevent its usage from the template in favour of `loadingState`. 

Probably it should be fine to make it public again or to create a public method to do that, which will still prevent the usage of `loading` variable in the template
