### ISSUE TITLE
[P3.2][Reopen] [Sourcing][Accessibility][Fd-dialog]: Fixed for vhd but not for Fd-dialog Reopen of 11377, 10698

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11819]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
the issue #11377 is only fixed for value help dialog, upon evaluating the issue still exists for fd-dialog component.
Pls check and help.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/ platform: 0.43.33

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Fd-dialog

1. open [link](https://stackblitz.com/edit/angular-9qxxca-ghhuyw?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json) 
2. click on button "Open Dialog"
3. turn on JAWS
6. notice the jaws speech history reading "Fundamental Library for Angular -Google chrome dialog"
![325191662-68c7acaf-6118-49cd-8413-8c6609099feb](https://github.com/SAP/fundamental-ngx/assets/88182358/4cadef52-c903-4c32-80f8-f75d16155c8b)
https://ng-15-downport--fundamental-ngx.netlify.app/#/core/dialog

#### Please provide relevant source code (if applicable).
pls refer [stackblitz](https://stackblitz.com/edit/angular-9qxxca-ghhuyw?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json)

#### Please provide stackblitz example(s).
[stacblitz](https://stackblitz.com/edit/angular-9qxxca-ghhuyw?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json)

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
This is reported and reopened in comment by Accessibility test lab team under https://github.com/SAP/fundamental-ngx/issues/11377#issuecomment-2074671377
#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@I543348 Can you create a stackblitz example for that so we can test an isolated scenario and not our documentation page?

**Comment by I543348** [comment]
Updated steps and link of stackblitz in issue description
cc: @droshev

**Comment by droshev** [comment]
@I543348 Can you test this [example](https://stackblitz.com/edit/angular-9qxxca-892qxv?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,src%2Fmain.ts)? what is read here?

**Comment by I543348** [comment]
Sure @droshev , I will ask ATL team and get back

**Comment by sagar7259** [comment]
Hello,

the issue is still reproducible in the above stackblitz example please find the screenshot below,

![image](https://github.com/SAP/fundamental-ngx/assets/143692208/fb2bcf4e-59fc-4b96-9b63-5390b2a7bdb1)

Regards,
Sagar

**Comment by droshev** [comment]
@I543348 @sagar-mahanthappa As you can see this is not coming from Fundamental Library. I set that title(Ariba Example) in your stackblitz. This is controlled by the application, and please don't create another ticket for the same thing.
