### ISSUE TITLE
feat: add link before header title

### ISSUE THREAD

**Issue by JYSW380** [SAP/fundamental-ngx#1182]
#### Is this a bug, enhancement, or feature request?
feature
#### Briefly describe your proposal.
add link before header title for easy navigate.
see below screenshot for an example:
![Screen Shot 2019-08-27 at 9 21 59 AM](https://user-images.githubusercontent.com/41170611/63774883-332c9280-c8ac-11e9-9dbc-89cf2d04f587.png)

**Comment by droshev** [comment]
We will merge the example with `input` and implement to for the whole documentation library later on
