### ISSUE TITLE
[Bug] Info Label:  Accent Border Colors for Info Labels 9 and 10 are reversed

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#11847]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Info labels 9 and 10 show wrong border colors. Label no. 9 with a light purple background should have accent color 09 as a border, while label no. 10 should have accent color 10 as border color. Currently both info label colors are reversed.

#### Can you handle that on the application side
Probably, but this should be corrected in the standard component

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
49.2

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://sap.github.io/fundamental-ngx/#/core/info-label --> change to Quartz Light theme

#### Please provide example(s).
![image](https://github.com/SAP/fundamental-ngx/assets/52921101/0bd0f020-a982-4de9-82aa-e50e18e92a14)

**Comment by droshev** [comment]
@D034394 This is from the spec(for Quartz):
<img width="326" alt="Screenshot 2024-05-03 at 14 45 32" src="https://github.com/SAP/fundamental-ngx/assets/4380815/79dd5766-5345-4a9f-ab3a-f9b81b7bcfca">

and [this](https://github.com/SAP/fundamental-styles/blob/7d1c67c812e9d2526ad38f9b78395e16cec912df/packages/styles/src/theming/common/info-label/_sap_fiori.scss#L13) is our mapping

**Comment by D034394** [comment]
Hi Deno, I understand what you are trying to say. But there is obviously somewhere a mismatch of parameters and color codes. You should see if you review the info labels in fundamentals for Quartz Light. Please see also the picture below. I will reopen the ticket. Please investigate!
![image](https://github.com/SAP/fundamental-ngx/assets/52921101/1a360ea5-1582-49f1-889f-fe5221649c1b)
