### ISSUE TITLE
Busy State for the components

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#1184]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
When implementing the combobox as a search input field, there are times where the search results may take some time to resolve. As such, it would be nice to put the combobox/search input component into a "loading" state, so that the user is clued that a search is in process.

<img width="216" alt="Screen Shot 2019-08-27 at 6 41 17 AM" src="https://user-images.githubusercontent.com/48103491/63776207-c0b0b800-c895-11e9-90f0-5a2ae138c65d.png">

Additionally, it would be nice to have a feature where the user can "stop" the search during the "loading" state.

<img width="243" alt="Screen Shot 2019-08-27 at 6 41 27 AM" src="https://user-images.githubusercontent.com/48103491/63776229-cc03e380-c895-11e9-8489-d895811052de.png">

In the above proposed design, when the component is in a "loading" state, hovering over the "loading" icon will change the icon to a "cancel/stop" icon. Clicking on the "cancel/stop" icon will cause the component to emit a "cancel search" event, and the component will toggle off the "loading" state.

### Let's list the potential components/layouts/forms where this can be applied and then discuss the implementation options.

**Comment by droshev** [comment]
will be tackled with #1873
