### ISSUE TITLE
[P2][Sourcing][Accessibility][Table with Multiselect checkbox]: When focus is on header checkbox , the screenreader reads whole table content at once which is irrelevant

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11843]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When focus is on header checkbox , the screenreader reads whole table content at once which is irrelevant to the disabled users.
On forward navigation,  the visible focus will be covering whole table, but the information read is

“Table

Column 1 row 2

Tree grid to select row press spacebar

Check box not checked

Column 1 row 2”

Here in the reading, the whole information is very confusing where even though the whole table is getting focused the information “Column 1 row 2” is not meaningful and also the information “To select row press spacebar checkbox not checked” is relevant to only one cell and not the whole table.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular : 15
Core / platform: 0.43.33

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Reach header checkbox (first column) by pressing tab from search box , and observe the screenreader reading.
<img width="419" alt="Screenshot 2024-04-29 at 3 02 30 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/f524e5ee-d893-4308-9ce3-2eeb859f0d0e">

#### Please provide relevant source code (if applicable).
https://stackblitz.com/edit/angular-9qxxca-hgtuob?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-9qxxca-hgtuob?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
This is reported by Accessibility test lab team

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by I543348** [comment]
@mikerodonnell89 can you pls share an ETA for this ?

**Comment by droshev** [comment]
@I543348 this will be estimated once the table focus issues (#11443) is implemented. S

**Comment by mikerodonnell89** [comment]
Can't recreate on mac screenreader, possibly unique to jaws

**Comment by droshev** [comment]
> Can't recreate on mac screenreader, possibly unique to jaws

@mikerodonnell89 we need to address it for JAWS if it is happening

**Comment by mikerodonnell89** [comment]
Definitely some things to improve here, but this issue no longer seems to be happening

![Screenshot 2024-07-24 at 2 51 16 PM](https://github.com/user-attachments/assets/247af09b-a695-4519-9799-738d4e17517d)
