### ISSUE TITLE
Throw error for invalid values in combobox

### ISSUE THREAD

**Issue by pavandk** [SAP/fundamental-ngx#11848]
Enhancement:

This is created on follow up of [ticket](https://github.com/SAP/fundamental-ngx/issues/11618)
We understand combo box should allow invalid values as well. But we have scenario where we need to show error if user enters values other than dropdown values. We are unable to do because in case of invalid values the control still holds previous selected dropdown value. Can you please enhance control to handle such scenarios?

**Comment by ZsDeak-SAP** [comment]
@pavandk for the invalid values and state you should use the `state` input. there was indeed an issue with the selection after the input has been modified.
@droshev i fixed the issue, see the PR please 😸

**Comment by mikerodonnell89** [comment]
fixed with https://github.com/SAP/fundamental-ngx/pull/12062
