### ISSUE TITLE
[Accessibility] Screen Reader Reads Star (*) When Focusing on Required Input/Select Fields

### ISSUE THREAD

**Issue by sunilb1295** [SAP/fundamental-ngx#11859]
#### Is this a bug, enhancement, or feature request?
Bug in version 0.43.11

#### Describe your proposal.
While navigating to/focusing on the Input fields which are required, the Screen Reader(JAWS) reads **star** for (*).
It should ideally read only `Required`

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15
Ngx 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

When focusing on the required field it reads as below
Issue is seen in - v0.43.11  - https://stackblitz.com/edit/angular-6akhtd?file=src%2Fmain.ts

When focusing on required input it reads as **Required Input colon star**
Issue is seen in latest version document as well : https://sap.github.io/fundamental-ngx/#/core/input

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/angular-6akhtd?file=src%2Fmain.ts

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.

Yes. below comments as reported by expert:
`**Retest has been taken and star is still announced**`

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@sunilb1295 Can you try the same scenario but with version [0.43.34](https://www.npmjs.com/package/@fundamental-ngx/core/v/0.43.34) instead?

**Comment by droshev** [comment]
@sunilb1295 If you are able to reproduce the issue in the latest version, please, open a new ticket
