### ISSUE TITLE
ngx modules names do not have fd namespace

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental-ngx#1185]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Fundamental-Ngx modules do not have an `Fd` namespace. For example, the modal module is called `ModalModule` and the button module is called `ButtonModule` which can be confused with application native modules. 

The suggestion is to prepend all modules with `Fd` so they read `FdModalModule` and `FdModalModule`

Material and other libraries have namespace on their modules: 
`MatButtonModule`
`OwlDateTimeModule`
 
#### Which versions of Angular and Fundamental NGX are affected? 
0.9.0

**Comment by droshev** [comment]
We will try to address it at some point of time

**Comment by droshev** [comment]
TypeScript allows importing as aliases ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)). This approach can be used in case there are duplicated names
