### ISSUE TITLE
Bug: Additional padding below dynamic page header

### ISSUE THREAD

**Issue by do-oel** [SAP/fundamental-ngx#11862]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
When using the dynamic page, an empty container appears below the page header although the subheader is set to [collapsible]="false". 

![image](https://github.com/SAP/fundamental-ngx/assets/143730992/afa91d4f-bcbf-4377-9293-2ac67a2fae6c)
#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Current and below.
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component: fd-dynamic-page

**Comment by InnaAtanasova** [comment]
Hi Dominik, I am not able to reproduce this. Can you check in the Stackblitz example: https://stackblitz.com/run?file=src%2Fapp%2Fplatform-dynamic-page-example.component.html

**Comment by pawelkarwat** [comment]
Hi Inna,

Unfortunately, I can't access StackBlitz. I will try to describe our implementation. During the implementation, we used the fd-message-subheader, to which we add the fd-message-strip component if there is an error. When the fd-message-subheader is empty, it adds additional padding that is not expected. Would it be possible for Fundamental to set the padding to 0 when we insert an empty fd-message-subheader component? I'm not sure if this is reported correctly as a bug.

**Comment by InnaAtanasova** [comment]
Hi @pawelkarwat would this solve the problem: https://github.com/SAP/fundamental-ngx/pull/11961? Thanks
