### ISSUE TITLE
Text getting populated in empty rows in tree table

### ISSUE THREAD

**Issue by lakshaysap** [SAP/fundamental-ngx#11872]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
if I try to use fdp-table-cell in fdp column  in fundamental platform ngx tree table the rows are which are empty are also getting populated with text when i click collapse button
#### Can you handle that on the application side
NO
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular version 17.2.1 and Fundamental Library 0.48.4
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
COMPONENT USED- Fundamentalngx/platfrom -  Table. 
1. In tree table code just place fdp-table-cell inside fdp-column

#### Please provide relevant source code (if applicable).
<fdp-table
  [dataSource]="source"
  [isTreeTable]="true"
  selectionMode="multiple"
  [enableTristateMode]="true"
  relationKey="children"
  selectedKey="selected"
  emptyTableMessage="No data found"
  [dropPredicate]="dropPredicate"
  (rowSelectionChange)="onRowSelectionChange($event)"
  (rowToggleOpenState)="onRowToggleOpenState($event)"
  (rowsRearrange)="onRowsRearrange($event)"
>
  <fdp-column name="name" key="name" label="Name" align="start">
    <fdp-table-cell *fdpCellDef="let data">
      {{ data.name }}
    </fdp-table-cell>
  </fdp-column>

  <fdp-column name="description" key="description" label="Description">
    <fdp-table-cell *fdpCellDef="let data">
      {{ data.name }}
    </fdp-table-cell>
  </fdp-column>
</fdp-table>

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/szf3ep?file=src%2Fapp%2Fplatform-table-tree-example.component.html
https://szf3ep-2ags--4200--0314a412.local-credentialless.webcontainer.io/
#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Not applicable 
#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes
#### Is there anything else we should know?
NO
**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by lakshaysap** [comment]
There are 2 scenarios that are happening. 

1) The first Code below is the one which was already written by my team you can see the video for better understanding.
https://github.com/SAP/fundamental-ngx/assets/142865933/797fa36f-f1b6-4919-a5e3-0af194996894

<div class="actions-body">
	<h3>{{ 'PACKAGE.actions.TEXT' | translate }} ({{ totalActions }})</h3>
	<fd-card card-type="table">
		<fd-card-content>
			<fdp-table
				[dataSource]="source"
				[isTreeTable]="true"
				relationKey="children"
				emptyTableMessage="No data found"
				[enableRowReordering]="false"
				expandedStateKey="name"
				[noBorderY]="true"
				[noOuterBorders]="true"
			>
				<fdp-column name="name" key="name" label="Name" width="40%">
					<fdp-table-cell *fdpCellDef="let data">
						{{ data.name }}
					</fdp-table-cell>
				</fdp-column>
				<fdp-column name="description" key="description" label="Description">
					<fdp-table-cell *fdpCellDef="let data">
						<fd-text
							class="fdp-table-description"
							text="{{ data.description }}"
							[maxLines]="1"
							[expandable]="true"
							[fdPatchLanguage]="{ coreText: { moreLabel: 'show more', lessLabel: 'show less' } }"
						>
						</fd-text>
					</fdp-table-cell>
				</fdp-column>
			</fdp-table>
		</fd-card-content>
	</fd-card>
</div>


2) I tried to fix this issue by removing the fdp table cell. But you can see the video it affects the responsiveness. 
https://github.com/SAP/fundamental-ngx/assets/142865933/75722fe8-9a2a-44d6-b634-854a61414e27

<div class="actions-body">
	<h3>{{ 'PACKAGE.actions.TEXT' | translate }} ({{ totalActions }})</h3>
	<fd-card card-type="table">
		<fd-card-content>
			<fdp-table
				[dataSource]="source"
				[isTreeTable]="true"
				relationKey="children"
				emptyTableMessage="No data found"
				[enableRowReordering]="false"
				expandedStateKey="name"
				[noBorderY]="true"
				[noOuterBorders]="true"
			>
				<fdp-column name="name" key="name" label="Name" width="40%"> </fdp-column>

				<fdp-column name="description" key="description" label="Description"> </fdp-column>
			</fdp-table>
		</fd-card-content>
	</fd-card>
</div>


AFTER TRYING THESE APPROACHES I THINK THERE IS SOME ISSUE WITH FDP-TABLE-CELL. Please look into it.

**Comment by mikerodonnell89** [comment]
I think I see the problem you're describing in your first video (the text "Use this endpoint to delete a customer's..." being populated in the "Description" column of the "Action" row), and I am concerned with how that is happening but I don't see how the stackblitz you've provided is relevant. With this code:

```
  <fdp-column name="description" key="description" label="Description">
    <fdp-table-cell *fdpCellDef="let data">
      {{ data.name }}
    </fdp-table-cell>
  </fdp-column>
```

You are taking every row in the description column and deliberately placing `data.name` inside of every cell. So I don't think the stackblitz is pertinent to the problem in the video. If I adjust your stackblitz to have the contents of the description cell be `data.description` which I think is what you want, I'm not able to recreate the problem from your video. See below:

https://github.com/SAP/fundamental-ngx/assets/2471874/4e64b0d7-7213-4afe-a833-58dc42a8896f

I would like to get to the bottom of this, so if you could update your stackblitz to more accurately demonstrate the problem you're seeing in your application, that would be great

**Comment by Raksha001** [comment]
Currently, the cell content displays correctly when I use:
```
<fdp-table-cell *fdpCellDef="let data">
      {{ data.description }}
</fdp-table-cell>
```
However, if the text inside the cell is too long, it takes up excessive width, requiring horizontal scrolling.

Also I want to use Fundamental NGX TextComponent for handling whitespaces, setting max lines, and making the text expandable. While this works on initial load, the text gets populated into different cells randomly upon collapsing and expanding, which is shown in the attached reference video.

https://github.com/user-attachments/assets/43666a86-367b-446c-bd42-dcd9184a2665

https://stackblitz.com/edit/szf3ep-39aaxh?file=src%2Fapp%2Fplatform-table-tree-example.component.html

Any insights or solutions to ensure proper text alignment and formatting within the cells would be greatly appreciated.

**Comment by mikerodonnell89** [comment]
Ok I understand the issue you're having now. This does appear to only happen when using the `fd-text` component inside the cell. For example, placing an `fdp-button` in the cell like so does not have the same problem:

```
        <fdp-table-cell *fdpCellDef="let data">
            <fdp-button [label]="data.description"></fdp-button>
        </fdp-table-cell>
```

While I investigate the true cause and solution for this, you can use this working below utilizing `*ngIf`

```
        <fdp-table-cell *fdpCellDef="let data">
            <fd-text
                *ngIf="data.description"
                [text]="data.description"
                [whitespaces]="true"
                [maxLines]="1"
                [expandable]="true"
            >
            </fd-text>
        </fdp-table-cell>
```
