### ISSUE TITLE
Platform Multi Combobox - Console error on opening and closing the popover

### ISSUE THREAD

**Issue by sarthak505** [SAP/fundamental-ngx#11892]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Console errors are coming on opening and closing the platform multi input's popover

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - 17.0.0
Fundamental - 0.49.2

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Simply open and close the options of the platform's multi combobox and observe the error.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

https://github.com/SAP/fundamental-ngx/assets/70737015/93393f50-d5ad-4f0f-8b35-b73b841ca580

**Comment by droshev** [comment]
@sarthak505 it looks like the video has a glitch. do you think you can create a stackblitz example, document the steps how to see the error? thanks
