### ISSUE TITLE
Filter field not working properly in platform table

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#11894]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
For the component, Filter input field for the columns is working only single time. It doesn't allow editing the field later.
It should allow filtering any number of times.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Create a table using platform-table that has filter option for the columns.
2. Try filtering by clicking on any column header and typing in the text in the filter field. It only allow entering filter value one time.

#### Please provide relevant source code (if applicable).
Provided component reference

#### Please provide stackblitz example(s).
The example provided in ngx docs is valid for this bug.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
NA

#### Did you check the documentation and the API?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 Can you create a stackbliltz example with the issue? this can speed up the things. thanks

**Comment by divyamalhotra488** [comment]
Hi @droshev, please find the stackblitz example here: https://stackblitz.com/edit/prywkj?file=src%2Fapp%2Fplatform-table-initial-state-example.component.html
Also, looks like the issue happens for a field which is filterable and sortable/groupable.

**Comment by g-cheishvili** [comment]
@droshev the filter input keydown has a prevent default or something. When you type, the focus moves up to the list item, tried to "cut" the text after writing the first time and filter works.

**Comment by khotcholava** [comment]
@divyamalhotra488 Hello,
Please update Fundamental-ngx to the latest version to fix the issue. You can see the example with the latest version here: https://stackblitz.com/edit/prywkj-x8xy3n?file=src%2Fapp%2Fplatform-table-initial-state-example.component.ts
