### ISSUE TITLE
[BUG] IconTabBarTab params aren't async

### ISSUE THREAD

**Issue by KamilaZaeva** [SAP/fundamental-ngx#11902]
We're trying to re-write old Tab Component with Icon Tab Bar in our project ([SAP Minutes](https://minutes.tools.sap/#/)).
And use [fdp-icon-tab-bar-tab](https://sap.github.io/fundamental-ngx/#/platform/icon-tab-bar#tabs-content) for tab content.
We need to show count of elements for each tab and this count is dynamic. 
But unfortunately, both label and counter params looks not async. 

[Stackblitz example here](https://stackblitz.com/edit/76p6mz?file=src%2Fapp%2Fexample%2Ficon-tab-bar-tabs-content-example.component.html)
I change the name and counter by click - and we can see updated value in the tab content below, but both params in tab hasn't been changed:
![image](https://github.com/SAP/fundamental-ngx/assets/143951907/5ff753b1-549a-41ad-ae14-9a85bf327c56)

I couldn't find any such examples in your documentation or similar open issues in Github. 
Feel free contact with me directly via [sap account](kamila.zaeva@sap.com) if you need any additional information.

**Comment by droshev** [comment]
@dpavlenishvili can you check this issue? thanks
