### ISSUE TITLE
[Sourcing][P2]Screen is blank when page is scrolled backwards in fdp-table

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11915]
#### Is this a bug, enhancement, or feature request?
BUG

#### Describe your proposal.

Consider a tree table with atleast 500 rows and 20 columns and data being rendered using infinite scrolling technique. This should also include setting renderAhead value to 50 which helps in sliding through rowIndex. So when user scrolls through the page, API calls are made to get items. After loading few items lets say 200 items, user scrolls backward and rowIndex gets changed according to visible row. But this is something happening slow and table is getting blank for few seconds.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
v0.43.34
Angular 15

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Consider a tree table with atleast 500 rows and 20 columns and data being rendered using infinite scrolling technique. This should also include setting renderAhead value to 50 which helps in sliding through rowIndex. So when user scrolls through the page, API calls are made to get items. After loading few items lets say 200 items, user scrolls backward and rowIndex gets changed according to visible row. But this is something happening slow and table is getting blank for few seconds.

#### Please provide stackblitz example(s).

I tried replicating the issue here [Issue link](https://stackblitz.com/edit/angular-mexm86-rujude?file=src%2Fapp%2Fadvanced-scrolling-example.component.html). But seems to be not replicating on stackblitz always.

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@sahanaN123 let's wait for https://github.com/SAP/fundamental-ngx/issues/11443 as it is connected.

**Comment by mikerodonnell89** [comment]
There's no silver bullet for this issue. When using virtual scroll, you can set the `[renderAhead]` input to a higher number, which would draw more elements to the DOM, at the cost of performance. `[scrollWholeRows]` helps too but you may still see some lag when scrolling too much too fast. You could avoid virtual scrolling altogether, but again, performance issues. This is an inherent problem with rendering thousands of elements to the DOM, we try to address it with virtual scrolling but that introduces its own limitations. I'm going to close this issue and I suggest opening a new, more detailed issue if there are specific things in mind for performance enhancements
