### ISSUE TITLE
Broken form-message in Date Time Picker in Reactive Form

### ISSUE THREAD

**Issue by markywilson** [SAP/fundamental-ngx#11916]
#### Is this a bug, enhancement, or feature request?
Bug

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Happening since version 0.45
https://docs-0-45--fundamental-ngx.netlify.app/#/core/datetime-picker

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
form message is shown correctly by default
![image](https://github.com/SAP/fundamental-ngx/assets/7045276/2940c410-ff54-4877-9a30-0ce2dc437103)
if the `message` attribute is updated, it's broken
![image](https://github.com/SAP/fundamental-ngx/assets/7045276/22e122b3-b66e-40f3-981a-129c48f0a9ec)
It stays broken
![image](https://github.com/SAP/fundamental-ngx/assets/7045276/34d8aa63-c480-4072-a2cc-4a3456a033a2)

#### Please provide stackblitz example(s).
https://sap.github.io/fundamental-ngx/#/core/datetime-picker#reactive-form

#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes
#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@dpavlenishvili do you think you can look this ticket?
