### ISSUE TITLE
Ability to disable the hover effect in the column header

### ISSUE THREAD

**Issue by pawelkarwat** [SAP/fundamental-ngx#11919]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Describe your proposal.

The improvement proposal concerns the TableComponent in the Fundamental Platform. From a UX point of view, if column headers are not interactive in any way, their background should not change when hovering. I propose adding the option to disable this behaviour on the table.

**Comment by InnaAtanasova** [comment]
This feature would first require CSS changes before it's implemented in ngx

**Comment by karolgromacki** [comment]
Hi @droshev @InnaAtanasova, is it possible to move property from fdp-table element to fdp-column? Because for now, it removes hover effect from all headers and we want to have a hovering effect only on particular headers.

**Comment by droshev** [comment]
@karolgromacki I will let @InnaAtanasova answer here.

**Comment by karolgromacki** [comment]
Hi @InnaAtanasova, I see that the issue is closed on Jun 12 is there any other ticket for moving the property or is it already fixed?

**Comment by InnaAtanasova** [comment]
We currently only provide an option to make all header cells non-interactive. We have to add an enhancement to the `fdp-column` to make individual cells non-interactive. I will see what I can do.

**Comment by InnaAtanasova** [comment]
@pawelkarwat please check what I added as a solution and let me know if this would work in your case or if you need something additional (the first example): https://deploy-preview-12552--fundamental-ngx.netlify.app/#/platform/table/basic

The PR: https://github.com/SAP/fundamental-ngx/pull/12552
