### ISSUE TITLE
[P2][Sourcing][Accessibility][Table platform sort menu] : Sort Menu item count is not read when focused

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#11922]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Continuation of https://github.com/SAP/fundamental-ngx/issues/11470
The menu item count is not being read
Expectation is when focus is on menu buttons for eg : Sort ascending then the screenreader has to read 1 of 2 , 2 of 2 and so on.
Currently this is not happening.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/ platform: 0.43.34

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) Open menu from column using keyboard enter key
2) menu opens and focus is moved to first menu button from the menu
3) Now observe that screenreader is not reading 1 of 2 or 2 of 2 

![image (1)](https://github.com/SAP/fundamental-ngx/assets/88182358/014164b5-f8ce-429e-b22b-511c8e85cc53)

#### Please provide relevant source code (if applicable).
https://stackblitz.com/edit/angular-9qxxca-amqznc?file=package.json,src%2Fapp%2Fplatform-table-preserved-state-example.component.html

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-9qxxca-amqznc?file=package.json,src%2Fapp%2Fplatform-table-preserved-state-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
This is reported by Accessibility test lab team from SAP

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@nikolay-kolarov Do you think you can help us here?

**Comment by I543348** [comment]
> ng-15

Hi @droshev , i see from the screenshot that you have tested on core table.
However. , the reported issue if for Platform table, Could you pls help and reopen accordingly?
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/p13-dialog-table

Thanks.
