### ISSUE TITLE
[Sourcing] [P3] Incorrect info returned by <fdp-table> component method `getRowsInViewport()` and property `_tableRowsVisible`

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#11946]
#### Is this a bug, enhancement, or feature request?
A bug (more like a feature enhancement)

#### Describe your proposal.
We'd like the the `getRowsInViewport()` method and the `_tableRowsVisible` table property only returns us the table rows that are currently visible only in table viewport (current scrollable container).

This is affecting our app side logic of getting the real visible table rows to frontend user, as we need to send the IDs of those visible table rows to feed into our backend API to return us their associated column values rendered in table cells.

#### Can you handle that on the application side
Difficult as we need to avoid DOM manipulation and access.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
- Angular 15
- F-NGX Platform v0.43.34

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
- Initialize a tree table
- Subscribe to table `onAllRowsExpanded(evt)` event and invoke the `getRowsInViewport()` method and log the `_tableRowsVisible` property
- Observed that each returns us the total number of table rows within current table `page`, but not the actual ones within current table viewport

#### Please provide relevant source code (if applicable).
![Screenshot 2024-05-23 at 3 15 13 PM](https://github.com/SAP/fundamental-ngx/assets/22454655/94b312cc-5e4f-4178-a3fe-413d65541ca7)

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/usdyvu-prcyah?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

#### Did you check the documentation and the API?
Looks like the property and the method both are fetching the total number of rows within the current table page, instead of from the real visible table viewport.

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
This function will be reworked with the refactor from #11491 and should give you the results you'd expect. But I also think it would be nice to add a function similar to `expandAll()` but that only attempts to expand visible rows

**Comment by mikerodonnell89** [comment]
`getRowsInViewport()` is a bit of a misnomer, so I'll need to update the function names. Along with `setRowsInViewport()`. This will be a breaking change as the public API is changing. `_tableRowsVisible` is not a part of the public API

Regarding your comment here:

> Difficult as we need to avoid DOM manipulation and access.

There is no way for the library to give you the currently visible rows without accessing the DOM, so any performance issues you may be concerned about will be present, whether the solution is coming from the library or the client.
