### ISSUE TITLE
Allow Content Projection in Dynamic Page Title

### ISSUE THREAD

**Issue by SomeKay** [SAP/fundamental-ngx#11948]
#### Is this a bug, enhancement, or feature request?

Enhancement (maybe even Feature Request)

#### Describe your proposal.

We're using `ng-content` in Dynamic Page content and subheader/header (depending on Core/Platform) to great success. We would also love to use it in the title which doesn't seem to work. Ideally, it would be supported in both, Core and Platform, but even one would be great.

It could very well be that I am doing something wrong and would love to know how to do it correctly.

#### Can you handle that on the application side

I am not sure, but if you have an idea, I would love to hear it.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

49

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/dchhvm

This is the most minimalistic example I could produce.

Using `ng-content` in either `fdp-dynamic-page-header` or `fdp-dynamic-page-content` works, as expected.

Putting `<span *fdpDynamicPageHeaderTitle>FOO</span>` directly into `fdp-dynamic-page-title` inside `page.component.html` also works, of course.

#### Did you check the documentation and the API?

Yes, and I couldn't find anything.

#### Did you search for similar issues?

There was an issue with modularity of the Dynamic Page several years ago (https://github.com/SAP/fundamental-ngx/issues/5172), but I don't think that it's quite the same.

**Comment by InnaAtanasova** [comment]
hi @SomeKay have you tried with these 2 directives: 
https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dynamic-page/directives/dynamic-page-header-title.directive.ts

https://github.com/SAP/fundamental-ngx/blob/main/libs/core/dynamic-page/directives/dynamic-page-header-subtitle.directive.ts

<img width="1002" alt="Screenshot 2024-05-27 at 10 00 51 AM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/05a2b56b-f24b-4fb8-af0e-66458fe08475">

**Comment by SomeKay** [comment]
Hey @InnaAtanasova, yes, the stackblitz is using those exact directives (though for the Platform version of Dynamic Page, but both versions, Core and Platform, exhibit the same behavior).

**Comment by InnaAtanasova** [comment]
hi @SomeKay could you please provide a code snippet of the expected markup? What markup would work best in your case? Thank you!

**Comment by SomeKay** [comment]
Hey @InnaAtanasova, as is in the stackblitz would already be enough.

I've tested it also with using a standard Web Component `slot` element, but also with just a regular Angular Component and none of these work either even though it would be good if they were supported, too.

**Comment by g-cheishvili** [comment]
@SomeKay Hey Kristian, I checked your stackblitz. The problem is that in order for the queries to work, you need to write them inside the dynamic page component directly. What you have now is a projected one and projected one shares DI with the place from which it was created, not with the target component you try to pluck in. Hope I explained well 😆 

So what you need to do is to have a code like this

```html
<fdp-dynamic-page-title>
                <span *fdpDynamicPageHeaderTitle>
                     <ng-content select="page-title" />
                </span>
</fdp-dynamic-page-title>
```

and it should work like a charm
