### ISSUE TITLE
[P1][Sourcing] Not able to load complete data for a parent when some children of parent are expanded

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11959]
#### Is this a bug, enhancement, or feature request?
BUG

#### Describe your proposal.
1. set data in table with multiple levels
2. expand level 0 to get level 1 children
3. expand few level 1 children and scroll down to load all of its children
4. now scroll even more to bottom to load remaining children of level 0 parent.

Issue is that we are able to return data Map rightly from fetch method. But the data is not being rendered on to the table.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
NGX - 0.43.34

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

https://github.com/SAP/fundamental-ngx/assets/110370099/7adb5a87-76fd-40e9-97a8-b3e30694f9b3

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/advanced

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@sahanaN123 can you provide a bit more details?

**Comment by sahanaN123** [comment]
Issue is no more replicable. Thanks

**Comment by sahanaN123** [comment]
https://github.com/user-attachments/assets/2bf686bf-5ea7-4c9d-83c9-5e77c2299b11

Issue is no more replicable
