### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-264.1][WIP] Edit field: Label not read.

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#11965]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/core/textarea
When the textarea, only the placeholder value is mentioned and not its label by screen reader.
The corresponding label should be read out, when each & every UI is accessed.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest versions

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader can check by implementing similar case. Just use textarea and few other input with place holder and label. Label won't be read by screen reader

#### Please provide relevant source code (if applicable).
Provided stackblitz example.

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/npoyvc?file=src%2Fapp%2Ftextarea-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes we have got this bug from Accessibility expert only.

#### Did you check the documentation and the API?
Yes

#### Is there anything else we should know?
Reopened https://github.com/SAP/fundamental-ngx/issues/11283 as it was closed without fix.

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by InnaAtanasova** [comment]
hi @divyamalhotra488 , can you provide the screen reader report? 
I tested with macos voiceover and nvda and the label is read, no matter if there's a placeholder text or not. Please see the attached screenshot from nvda testing:
<img width="1352" alt="Screenshot 2024-06-19 at 3 13 54 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/56c9243a-3954-49ee-9fc7-9dcaa2164f83">

Fundamental-ngx label and textarea use the browser native tags `label` and `textarea`. To connect these 2 the textarea should have an id and the label should have a `for` attribute with the same id. The text example should have these. 
Please provide the code for the example your a11y expert tested. Thanks

**Comment by MeghanaVernekar** [comment]
Hello Colleagues,

Retested the issue using NVDA and issue still exists. The label 'Commnet' is not read on accessing the edit field.
![image](https://github.com/user-attachments/assets/46390c5b-abda-4d4a-9d36-62e6882d3dcd)

Regards,
Meghana.

**Comment by droshev** [comment]
@MeghanaVernekar based on the screenshot it looks like you are testing an application. If you believe this is fundamental-ngx issue, then you would need to create a stackblitz example where we can see the issue.

**Comment by divyamalhotra** [comment]
Hi @droshev, stackblitz example is already attached in description. Again adding here: https://stackblitz.com/edit/npoyvc?file=src%2Fapp%2Ftextarea-example.component.html

**Comment by droshev** [comment]
@divyamalhotra thank you for providing the stackblitz example. I tested with JAWS and it is fine there: 
<img width="560" alt="Screenshot 2024-09-30 at 16 16 20" src="https://github.com/user-attachments/assets/a712c863-a39f-4f1f-8dd7-a0e6253b8938">

**Comment by MeghanaVernekar** [comment]
Hello @droshev ,
Tested the stackblitz added: https://stackblitz.com/edit/npoyvc?file=src%2Fapp%2Ftextarea-example.component.html

and label 'Required Textarea' is not read when tested with JAWS, Attached speech history below:
![image](https://github.com/user-attachments/assets/6a5ec546-865c-406d-b0e1-0a586bde242b)
