### ISSUE TITLE
dialogService hasOpenDialogs not working with multiple Directories in a Project

### ISSUE THREAD

**Issue by Ashah2013** [SAP/fundamental-ngx#11983]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
with multiple directories and error handling in respective service files, dialogService hasOpenDialogs does not detect the error dialog already opened by the other directory and open multiple overlapping error dialogs

#### Can you handle that on the application side
Yes, but would require 3rd party Library

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.48.4

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Create two directories with separate service and error handling files.
2. Both should should trigger API that throws error
3. In error handling of each directory use following to restrict from opening multiple error dialogs
`if (!this._dialogService.hasOpenDialogs()) {
	this.openErrorDialog(data);
}`
4. Call both the created directories from main

#### Did you check the documentation and the API?
yes

#### Did you search for similar issues?
yes, but could not find anything related

#### Is there anything else we should know?
No

**Comment by Ashah2013** [comment]
How can we solve this issue? Is there a workaround?

**Comment by droshev** [comment]
@dpavlenishvili can you help @Ashah2013 how to solve their problem?

**Comment by droshev** [comment]
@Ashah2013 Can you explain how you got that issue so @dpavlenishvili can support you?

**Comment by Ashah2013** [comment]
Issue has been fixed now. Thanks for the concern.
