### ISSUE TITLE
Bug: Multi-Combobox selectedItems can't be updated after the first rendering

### ISSUE THREAD

**Issue by KamilaZaeva-sap** [SAP/fundamental-ngx#11981]
Use case: we use combobox list for filtering data. And User should have two options: 1) click by element from combobox list (it works perfect) or click by label in another component and receive the same behaviour (this element is added to selectedItems of combobox).
But unfortunately, I noticed that selectedItems work just the first rendering, although it's an input parameter of angular component. 

I prepared an example, where I update selectedItems by click on button. And nothing changes in combobox element.
[Stackblitz example](https://stackblitz.com/edit/6xgylt?file=src%2Fapp%2Fmulti-combobox-datasource-example.component.ts)

Feel free to contact with me directly if you need more information (kamila.zaeva@sap.com)

**Comment by droshev** [comment]
@KamilaZaeva-sap Can you open a new issue providing more details to the bug you have reported.
