### ISSUE TITLE
[Sourcing-2] multi-combobox limitless is not working

### ISSUE THREAD

**Issue by PAVANC56** [SAP/fundamental-ngx#11999]
Is this a bug, enhancement, or feature request?
bug

Describe your proposal.

Component having issue: https://sap.github.io/fundamental-ngx/#/core/multi-combobox
Even after setting [limitless] to true, default limit is still showing only 100 for core-multicombobox component
When set limitless to true Multi-combobox should show all records in dropdown list.
Can you handle that on the application side
No

Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions

If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Pass object list as datasource to multicombobox(Make sure that the list contains more than 150 items).
2. Set limitless to true.
3. All items should be shown in dropdown of multicombobox.
4. In the attached image you can see if the record count is more than 100 those records can only be accessed by search and are not available in dropdown.

Please provide relevant source code (if applicable).
Components specified in description.

Please provide stackblitz example(s).
https://stackblitz.com/run?file=src%2Fapp%2Fmulti-combobox-datasource-example.component.ts

In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
No

Did you check the documentation and the API?
Yes
Did you search for similar issues?
NA
Is there anything else we should know?
NA
**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**
<img width="1840" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/19906597/94c877f4-2397-48a9-bc55-966ddbc77b00">

**Comment by JyotiKumari1507** [comment]
@droshev  can you pls have look on this? We are block

**Comment by droshev** [comment]
@JyotiKumari1507 Can you create a stackblitz example with the issue? Thanks
