### ISSUE TITLE
String in multi-combobox need to be localized

### ISSUE THREAD

**Issue by akilhaidar123** [SAP/fundamental-ngx#12002]
is this a bug, enhancement, or feature request?
bug

Briefly describe your proposal.
how can we handle the string # more to different locales?
![image](https://github.com/SAP/fundamental-ngx/assets/136554008/61bf3a20-2fef-4c79-b14f-b607dc5f21b0)

![image](https://github.com/SAP/fundamental-ngx/assets/136554008/7aff09ac-a6e7-40b9-8ce1-9c9a8bcc1fac)

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
If this is a bug, please provide steps for reproducing it.
Please provide relevant source code if applicable.
Is there anything else we should know?

**Comment by droshev** [comment]
@akilhaidar123 it has been localized
<img width="730" alt="Screenshot 2024-06-16 at 19 13 43" src="https://github.com/SAP/fundamental-ngx/assets/4380815/c8cf8393-ca46-4c86-b6e1-0392bd455e1a">
