### ISSUE TITLE
Time control accepts non-numeric characters in Safari and Firefox

### ISSUE THREAD

**Issue by matt-williams8** [SAP/fundamental-ngx#1202]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Replicate behaviour in Chrome where only numeric characters can be entered into time controls

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Latest, this can be seen in the example controls at https://sap.github.io/fundamental-ngx/time, https://sap.github.io/fundamental-ngx/timePicker and https://sap.github.io/fundamental-ngx/datetime-picker

#### If this is a bug, please provide steps for reproducing it.

Go to any of the example components listed above in Safari or Firefox and when editing a time control type in non-numeric characters. Whilst typing the time segment (hours, minutes or seconds) you are editing displays as `null` in the input field and when the popover is closed it reverts back to 0  

#### Is there anything else we should know?

In Chrome non-numeric characters are totally blocked and cannot be entered

**Comment by droshev** [comment]
@matt-williams8 I couldn't reproduce that the non-numeric characters are accepted. It is true that you can type letters, but once you move to the next field or move the focus to other field then the input gets reset.

**Comment by matt-williams8** [comment]
@droshev perhaps accept was the wrong choice of words, allows to be typed may have been a better choice. 

The input does reset, but that does not seem like the desired behaviour. For example if you have the hours set to 14 and the type some letters the input resets to 0, not 14. As mentioned in the original description, letters cannot even be typed in Chrome so ideally this behaviour would be replicated across all browsers

**Comment by JKMarkowski** [comment]
Hi @matt-williams8, I will add some pipe which allows only numbers. It will work on every browser.
