### ISSUE TITLE
Issue when a dialog is open after trigger a select.

### ISSUE THREAD

**Issue by joseserrano15** [SAP/fundamental-ngx#12039]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When I trigger a fd-select to choose an option or a fd-date-picker, and immediately after opening a dialog, which contains an fd-select, the fd-select does not show the options. It is as if they are displayed below the dialog.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 17.2.0
Fundamental: 0.49.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
fd-select
fd-date-picker
fd-dialog

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

![image](https://github.com/SAP/fundamental-ngx/assets/68348356/a28f5a87-800e-431d-b24d-bb89a3ccd4e1)

**Comment by ZsDeak-SAP** [comment]
if there's a click outside of the select or calendar it'll automatically close, there's no Input overriding it, so clicking anywhere to open a dialog, or in your dialog must close the calendar. if it does not, that means somehow you are forcing it to keep open. regardless, please provide a code example as I could not reproduce the issue. \
note that for this GIF to happen i needed to programatically open the calendar on the same click event that also opens the dialog, so normally it's not even a scenario that should happen.
![popover over popover](https://github.com/SAP/fundamental-ngx/assets/115458873/0800c231-8cdf-4f7d-bfc7-bf43d911445c)
