### ISSUE TITLE
[P3][Sourcing][Performance] Issue when we mousemove on platform table

### ISSUE THREAD

**Issue by CSEHoangV** [SAP/fundamental-ngx#12037]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

This can be easier to be observed when we have many columns and large amount of items since this determine at table cell level. When we mousemove, the `_getResizer` gets called at [table-cell-resizable](https://github.com/SAP/fundamental-ngx/blob/ng-15-downport/libs/platform/src/lib/table-helpers/directives/table-cell-resizable.directive.ts#L80) and the function `_getResizer` [getResizer](https://github.com/SAP/fundamental-ngx/blob/ng-15-downport/libs/platform/src/lib/table-helpers/directives/table-cell-resizable.directive.ts#L111) is executed with DOM manipulation. Those will run frequently and potentially cause force reflow or high CPU usage especially with table having many items and columns.

![Screenshot 2024-06-25 at 10 49 36 AM](https://github.com/SAP/fundamental-ngx/assets/162270184/0a966e19-1da1-4015-ac73-a4061ea7ccc7)

Can we optimize this function? (like reduce how many times it triggers...)

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15
0.43.35

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Create a platform table (with large dimensions (row and columns))
Turn on performance profile 
Record and mousemove on table
Check recalculation style and see what function/file cause issue
We can also check CPU usage 

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@CSEHoangV Can you create a stackblitz example so faster processing?

**Comment by CSEHoangV** [comment]
You can reproduce it on any platform table from fundamental playground. Here is stackbitz:
https://stackblitz.com/edit/angular-rvez99-mm1c2t?file=src%2Fapp%2Fadvanced-scrolling-example.component.ts,src%2Findex.html

https://github.com/user-attachments/assets/c7658da9-a031-40da-adf9-47856482e046
