### ISSUE TITLE
Combobox with asyc dataSource leads to: Cannot read properties of undefined (reading 'length') 

### ISSUE THREAD

**Issue by irsapirsap** [SAP/fundamental-ngx#12036]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Stackblitz:
https://stackblitz.com/edit/vutgl2-n2yi5x?file=src%2Fapp%2Fcombobox-loading-example.component.ts,src%2Fapp%2Fcombobox-loading-example.component.html

fails with (open developer tools to see the console):
vendor.js:57447 ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at ComboboxComponent_ng_template_1_Template (vendor.js:155437:92)
    at executeTemplate (vendor.js:58830:7)
    at refreshView (vendor.js:60254:7)
    at detectChangesInView (vendor.js:60416:5)
    at detectChangesInEmbeddedViews (vendor.js:60363:7)
    at refreshView (vendor.js:60277:5)
    at detectChangesInView (vendor.js:60416:5)
    at detectChangesInComponent (vendor.js:60394:3)
    at detectChangesInChildComponents (vendor.js:60428:5)
    at refreshView (vendor.js:60304:7)

#### Can you handle that on the application side
no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
See the stackbliz example

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
See the stackbliz example

#### Please provide relevant source code (if applicable).
https://stackblitz.com/edit/vutgl2-n2yi5x?file=src%2Fapp%2Fcombobox-loading-example.component.ts,src%2Fapp%2Fcombobox-loading-example.component.html

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/vutgl2-n2yi5x?file=src%2Fapp%2Fcombobox-loading-example.component.ts,src%2Fapp%2Fcombobox-loading-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
not accessibility related

#### Did you check the documentation and the API?
yes

#### Did you search for similar issues?
yes

#### Is there anything else we should know?
Yes, the probem appears because you declare the `dataSource` as opitional
https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/form/combobox/commons/base-combobox.ts#L167
but then out of this optional `@Input` you initialize the `_suggestions` variable. Which means when the value is null (and it is null when using `| async`) the code does not enter here: https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/form/combobox/commons/base-combobox.ts#L169 and as a result the processing of your template here: https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/form/combobox/combobox/combobox.component.html#L4 is broken.

**Comment by khotcholava** [comment]
@irsapirsap Hello!

The issue in your Stackblitz is that you're providing an Observable to the dataSource input, which expects an array. Since null is not an array, it cannot be accepted.

As shown in the `FdpComboBoxDataSource` type definition:

TypeScript
`export type FdpComboBoxDataSource<T> = ComboBoxDataSource<T> | Observable<T[]> | T[];`

To resolve this, you'll need to handle the null case on your end.

```
<fdp-form-group [noLabelLayout]="false" columnLayout="XL2-L2-M1-S1">
    <fdp-form-field id="loading" label="Loading" [column]="1">
        <fd-busy-indicator
            [loading]="loading"
            ariaLabel="loading"
            title="Please Wait"
        >
            <fdp-combobox
                name="Loading example"
                placeholder="Type some text..."
                (onDataRequested)="onDataRequested()"
                (onDataReceived)="onDataReceived()"
                [dataSource]="(dataSource | async) || []" <=== Please add || [] check on our end
            ></fdp-combobox>
        </fd-busy-indicator>
    </fdp-form-field>
</fdp-form-group>
```
Please let me know if you have any issue.

**Comment by irsapirsap** [comment]
> The issue in your Stackblitz is that you're providing an Observable to the dataSource input, which expects an array. Since null is not an array, it cannot be accepted.

that is false, The code creates a dataSource input which is observable that emits arrays. The arrays are emitted 4 seconds later. There is no null sent anywhere. This issue is in fundamentals as I have analyzed at the end in great detail.

Can you call me make a quick debug together?
