### ISSUE TITLE
Inline Help Component

### ISSUE THREAD

**Issue by Sherry-Lee** [SAP/fundamental-ngx#12047]
#### Is this a bug, enhancement, or feature request?
It's a bug.

#### Describe your proposal.
If the text is too long in the inline help component, the text is cut although the scroll bar is here, but the scrollbar is not working once the mouseleave the content of the popover will be disappear.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
v50.0.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Inline Help Component

#### Please provide relevant source code (if applicable).
fd-inline-help="Inline Help Tooltip Inline Help TooltipInline Help TooltipInline Help TooltipInline Help TooltipInline Help TooltipInline Help Tooltip TooltipInline Help TooltipInline Help TooltipInline"
#### Please provide stackblitz example(s).
https://stackblitz.com/edit/6jg8xg?file=src%2Fapp%2Finline-help-example.component.html,src%2Fapp%2Finline-help-example.component.ts

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
It's not an accessibility related topic.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by ZsDeak-SAP** [comment]
you can customize the CSS of the inline-help via `additionalBodyClass`, see the [docs](https://sap.github.io/fundamental-ngx/#/core/inline-help#styled)
you can also customize when the inline-help closes and when it opens. try for example 
```
    [triggers]="[{ trigger: 'mouseleave', openAction: false, closeAction: false }, { trigger: 'mouseenter', openAction: true, closeAction: false }]"
    [closeOnOutsideClick]='true'
```
this is not a bug
