### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-264.1][WIP]Table: Region Information and tabular list container not mentioned. 

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12045]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Component having issue: https://sap.github.io/fundamental-ngx/#/platform/table/basic
When the first interactive element under the tabular section receives focus, tabular list container must be mentioned along Region/Heading information. But its not happening

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Screen reader can check by implementing similar case. Just use table with search or few button in toolbar and try to access first button/search as it is the first element under the tabular section , the user must be informed by screen reader about the existence table by mentioning as ‘Tabular list container’ and also region/heading information.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes we have got this bug from Accessibility expert only.
As per them, the issue is partially fixed. Observed that
1. for 'Key Encryption Keys (37)' the tabular header is not conveyed.
2. Toolbar is conveyed for both the tables.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Reopened from https://github.com/SAP/fundamental-ngx/issues/11263

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@nikolay-kolarov Can you check that issue and advise us whether there is something we can do more? thank you!

**Comment by nikolay-kolarov** [comment]
Hello @droshev,

@divyamalhotra488 - the table starts after the toolbar.

The announcement is the same as in the grid table in UI5:
https://ui5.sap.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.ui.table.sample.Filtering&sap-ui-xx-sample-lib=sap.ui.table&sap-ui-xx-sample-origin=.

This is the announcement from the table in fundamentals:
![image](https://github.com/user-attachments/assets/5bcfc291-8f38-4327-b18d-0334565f8191)

And this is the one in UI5:
![image](https://github.com/user-attachments/assets/dbe7a518-6070-4adf-8b13-01c2ceaa74f0)

So in my opinion the current announcement is ok and this issue can be closed.

Best Regards,
Nikolay
