### ISSUE TITLE
[Sourcing-2][Accessibility: ACC-270.16][WIP] Logo: UI is triggered by the down-event.

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12044]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
On accessing the image link, the UI gets activated without releasing the enter key.
every UI element should be activated only when the key is released. If the key is on hold, the UI should not be activated.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All latest version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Use any image, UI will gets activated without releasing the enter key

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes we have got this bug from Accessibility expert only.
There is an accessibility requirement (270.16) that No UI should get triggered with only down event and should not be activated until the user releases the key. For more info about the requirement attached the link below: https://wiki.one.int.sap/wiki/display/Acc/ACC-270+Details#ACC270Details-acc27016.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Reopened defect from https://github.com/SAP/fundamental-ngx/issues/11294

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 Can you create a sample with that?

**Comment by droshev** [comment]
@divyamalhotra488 Can you help me understand where in your stackblitz example you have the issue?

**Comment by divyamalhotra488** [comment]
Hi @droshev, Try clicking on the button link, it will be clicked by keydown, which should not happen till we release click.
I have earlier given a video recording for the issue: [here](https://sap-my.sharepoint.com/:v:/p/divya01/EUO5QtUTWK1BkenTub82MwMBnlN6B67b1GuWcVCHj0usog?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=7EsDhY)

**Comment by droshev** [comment]
@divyamalhotra488 the stackblitz is using vanila links. I don't see where Fundamental NGX is involved.

**Comment by MeghanaVernekar** [comment]
Hello Colleagues,

Retested the issue and issue still exists.  The ‘SAP' logo button, gets activated without releasing the enter key.
Regards,
Meghana

**Comment by droshev** [comment]
@MeghanaVernekar Can you see my previous comment?

**Comment by MeghanaVernekar** [comment]
Hello Colleagues,
This issue where the SAP logo button gets triggered even before the user releases the enter key is also observed in SAP Ui5 technology and we have already created an issue there and the Ui5 team is already working on this and as this application is from different technology we have created a ticket for this project too.

Please let me know if you need any more details for this.

Regards,
Meghana.

**Comment by droshev** [comment]
I don't see where Fundamental NGX is involved.
