### ISSUE TITLE
Searching in MultiCombobox yields prefix-matches only

### ISSUE THREAD

**Issue by hyperlinqq** [SAP/fundamental-ngx#12040]
Entering a search term in the MultiCombobox yields only results that start with the search term. To me this is unexpected behavior for a dropdown menu.

Steps to reproduce
- Place the cursor in the MultiCombobox with label `Array of Strings` on page https://sap.github.io/fundamental-ngx/#/core/multi-combobox

- Type `apple`: I would expect two results, i.e. `Apple` and `Pineapple` but there is only one (`Apple`). When I type `Pine` then the result `Pineapple` is given

#### Is this a bug, enhancement, or feature request?
Bug - the behavior is unexpected for a dropdown menu.

#### Describe your proposal.
The root cause seems to be the preselected MatchingStrategy in the DataSource base class: https://github.com/SAP/fundamental-ngx/blob/7418a7c27de3daaf9222c16c296ff6ae11e13611/libs/platform/shared/domain/data-source.ts#L120

One option to handle this could be to set the default to the `CONTAINS` strategy either in the base class or in the derived MultiCombobox-related classes.

Another option could be to expose the MultiComboboxConfig to the user so the MatchingStrategy could be passed via the template, e.g. such as for the MobileConfig.

#### Can you handle that on the application side
Yes but it involves extending one of this libraries base classes.

### Additional note
When I transitioned our MultiCombobox to the `CONTAINS` matching strategy I noticed that the highlighting of search terms in the dropdown is off, e.g. when I type `pple` then this infix is not highlighted in the matching result `Pineapple`.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
[v0.50.1-rc.3](https://github.com/SAP/fundamental-ngx/releases/tag/v0.50.1-rc.3) (current version)

**Comment by InnaAtanasova** [comment]
hi @dpavlenishvili , can you take a look at this when you finish with the ng18?
