### ISSUE TITLE
Dynamic page tabs resize issue

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#12069]
This appears to be unique to the core dynamic page with tabs, and is working fine for the base tab component itself.

If you navigate to the https://fundamental-ngx.netlify.app/#/core/dynamic-page#tabbed example and open the non-stacked example, and shrink the window such that only a few tabs are showing and select, for example, "Tab 3", then re-expand the window, you'll notice that "Tab 3" is the first tab on the left, when you'd expect it to be the third. Video below:

https://github.com/SAP/fundamental-ngx/assets/2471874/8502d592-8793-4107-8f84-f225b1996324

**Comment by InnaAtanasova** [comment]
Hi @mikerodonnell89 I am closing this as it's already reported in this issue https://github.com/SAP/fundamental-ngx/issues/12043 and Davit is working on it.
