### ISSUE TITLE
Include ObjectAttributeComponent in FundamentalNgxCoreModule

### ISSUE THREAD

**Issue by moxaj** [SAP/fundamental-ngx#12060]
#### Is this a bug, enhancement, or feature request?

enhancement

#### Describe your proposal.

`ObjectAttributeComponent` should be exported as part of `FundamentalNgxCoreModule` (https://github.com/SAP/fundamental-ngx/blob/main/libs/core/fundamental-ngx.module.ts#L141-L144).

#### Can you handle that on the application side

I can, but it's an extra import.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

angular: 17.3.11
fundamental: latest

#### Did you check the documentation and the API?

I did.

#### Did you search for similar issues?

Yes.

**Comment by InnaAtanasova** [comment]
hi @moxaj , thanks for opening the issue. Would this PR fix the problem: https://github.com/SAP/fundamental-ngx/pull/12066/files?

**Comment by moxaj** [comment]
@InnaAtanasova hi, I think it would!
