### ISSUE TITLE
Reset filter doesn't reset the number beside Include/Exclude [UI issue]

### ISSUE THREAD

**Issue by saikrishna143** [SAP/fundamental-ngx#12061]
Is this a bug, enhancement, or feature request?

Bug.

Briefly describe your proposal.

Reset filter doesn't reset the number beside Include/Exclude

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

If this is a bug, please provide steps for reproducing it.

**Steps To Reproduce:**
Create a quick RFP, have some suppliers and questions.
Click on the filter icon in the question table. Apply some condition. View the table. The filter is applied. Now click again on the filter icon and click on reset button. You can see the input from the text box is cleared but the number beside the Include/Exclude is present.
The same can be seen for supplier table filter. 

Before we click on reset button 
<img width="1689" alt="Screenshot 2024-07-02 at 11 31 12 AM" src="https://github.com/SAP/fundamental-ngx/assets/174311678/6fd76a3b-e77b-485f-9b5c-64709626ce73">

After reset till the count is showing 
<img width="1669" alt="Screenshot 2024-07-02 at 11 43 04 AM" src="https://github.com/SAP/fundamental-ngx/assets/174311678/89d6f1b7-02b7-4669-affd-a474760f7483">

Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table/advanced

**Comment by ZsDeak-SAP** [comment]
this reproduction is not applicable as we don't have access to the application you're developing, neither should we debug problems in it. please provide a Fundamental code example or steps involving the use of Fundamental.

**Comment by saikrishna143** [comment]
**Steps to reproduce** 

open  this link https://sap.github.io/fundamental-ngx/#/platform/table/advanced

 will be navigated to below  page 

<img width="1727" alt="Screenshot 2024-07-02 at 5 59 48 PM" src="https://github.com/SAP/fundamental-ngx/assets/174311678/87aec888-3e8f-4249-87b8-a3c7ce9b5fd0">

click on filter icon
![image](https://github.com/SAP/fundamental-ngx/assets/174311678/a28e1d02-b967-4b1c-b81e-9804ea64d99d)

Now, Apply some condition. View the table. 

<img width="1461" alt="Screenshot 2024-07-02 at 6 39 51 PM" src="https://github.com/SAP/fundamental-ngx/assets/174311678/917694b1-dc20-462d-8acf-87042ae66227">


 click on reset button. You can see the input from the text box is cleared but the number beside the Include/Exclude is present.

<img width="1348" alt="Screenshot 2024-07-02 at 6 41 20 PM" src="https://github.com/SAP/fundamental-ngx/assets/174311678/b8e19815-b89c-4854-a0e1-09a4d8f43a55">
