### ISSUE TITLE
Icons which have the same size should have the same resolution

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1207]
#### Is this a bug, enhancement, or feature request?

I am not sure if this is bug or a feature request.

#### Briefly describe your proposal.

I have added icons in the side navigation and all icons are of size 'm'. Unfortunately, the icons and the texts are not aligned. The reason for this is that the resolution of those icons differs. Icons have either 16x16, 14x16 or 12.03x16 resolution. Is it possible that all icons have the same resolution?

![image](https://user-images.githubusercontent.com/51904901/64095442-133f1800-cd5f-11e9-8f1d-b3926048df51.png)

**Comment by droshev** [comment]
@kistll Thanks for the feedback. We would need to investigate further. The icons that are coming are SAP Icon library.

**Comment by kistll** [comment]
@droshev: Thx for your fast reply.

**Comment by JKMarkowski** [comment]
It will be solved, on this [ticket](https://github.com/SAP/fundamental-ngx/issues/1512).
