### ISSUE TITLE
BUG: breakpoints in fd-shellbar component

### ISSUE THREAD

**Issue by KamilaZaeva-sap** [SAP/fundamental-ngx#12085]
When attempting to use breakpoints for the `fd-shellbar` component (like `<fd-shellbar [sideNav]="true" [breakpoints]="breakpoints">`), an error appears in the browser console. 
It is assumed that the problem arises from the use of `this._shellbar.nativeElement` (in `@Input()`) before the component is initialized.

![image](https://github.com/SAP/fundamental-ngx/assets/170612124/fadc2027-c3fa-4027-9a9a-7c567f36576c)
![image](https://github.com/SAP/fundamental-ngx/assets/170612124/2ca632f9-b219-443c-a601-8e0f0dc2d93e)

If you have any questions regarding this issue, feel free to contact with Siarhei Punko (C5379244)

**Comment by InnaAtanasova** [comment]
hi @KamilaZaeva-sap could you check with the latest RC version if everything now is working well on your side. Thank you!
