### ISSUE TITLE
"Send" button is truncated for some locales in conversation messages

### ISSUE THREAD

**Issue by C5358948** [SAP/fundamental-ngx#12098]
Is this a bug, enhancement, or feature request?

Bug.

Briefly describe your proposal.

"Send" button is truncated for some locales in conversation messages

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

If this is a bug, please provide steps for reproducing it.

Steps To Reproduce:
Log in as language user eu_FR210309b, fr210309b, etc.
Create a guided sourcing project > RFP
Add items, suppliers > Publish
Click the small conversation icon to send a message 
Select a user
View send button
Observe the issue

<img width="1316" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/174795756/d74b2df7-03e1-4fc5-a06f-c882d6d236d9">

**Comment by InnaAtanasova** [comment]
hi @C5358948, thank you for creating the issue. Unfortunately, I don't have access to the application you provided a screenshot from.
The Button component will grow to fit the content inside (text) and will not truncate unless it has a max-width, set by the consuming application.
Here's the default behaviour of the Button component (grows to fit the text):
<img width="1237" alt="Screenshot 2024-07-11 at 12 11 08 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/8eec9514-b51b-461c-aca3-e0a84b498587">

Here's when the button has a max-width apply to it (truncates):
<img width="1416" alt="Screenshot 2024-07-11 at 12 17 00 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/4f433a8c-3acf-4cb6-adc8-7ab47013d74e">

If this is not helpful, please create a Stackblitz example that illustrates the problem. Thank you

**Comment by droshev** [comment]
@C5358948 Can you create a stackblitz isolating the issue?
