### ISSUE TITLE
[BUG] Sorting and filtering dialogs for Table fundamental-ngx/platform component can be opened multiple times one on top of the other

### ISSUE THREAD

**Issue by karolgromacki** [SAP/fundamental-ngx#12095]
Sorting and filtering dialogs can be opened multiple times one on top of the other when many data are loaded simultaneously in the Table fundamental-ngx/platform component. This causes overlapping of dialogs and backdrops.

Steps to reproduce:
1. Utilize the Table component with over 400 elements, growing button, sort and filter settings in the platform.
2. Set the pageSize to 200.
3. Click the growing button to load data.
4. Immediately scroll to the top of the table.
5. Click the sorting or filtering icon repeatedly.

Expected behavior: There should be only one instance of dialog for sorting and filtering table data visible at a time.

**Comment by droshev** [comment]
@karolgromacki Do you think you can create a stackblitz example in case it is not reproducible on our documentation?

**Comment by karolgromacki** [comment]
https://stackblitz.com/edit/6vfrhd-4ghmut

Steps to reproduce:
1. Launch the project.
2. Quickly click 5 times on the load more button.
3. Immediately click the Sort button on the table toolbar 5 times.
4. Wait for the data to load.
5. Observe the problem with overlapping dialogs.

Expected behavior: 
There should be only one instance of dialog for sorting and filtering table data visible at a time.
