### ISSUE TITLE
Incorrect Javascript icon in SAP-icons-TNT

### ISSUE THREAD

**Issue by BL19** [SAP/fundamental-ngx#12090]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
The icon labeled as "javascript" in the TNT Icons set is incorrect. It currently displays the logo for Java instead of the correct logo for JavaScript. This should be corrected to accurately represent JavaScript while the current icon could be renamed to Java.

#### Can you handle that on the application side
No, this needs to be corrected in the TNT Icons set provided by fundamental-ngx.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
This issue affects version 0.50.0 present in the documentation and in a local environment on version 0.50.0.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Import and use the "javascript" icon from the TNT Icons set.
2. Observe that the icon displayed is the logo for Java, not JavaScript.

#### Please provide relevant source code (if applicable).
```typescript
import { IconModule } from 'fundamental-ngx';

<fd-icon glyph="javascript" font="SAP-icons-TNT"></fd-icon>
```

#### Please provide stackblitz example(s).
A stackblitz example is not necessary as the issue can be observed directly from the [icon set in the documentation](https://sap.github.io/fundamental-ngx/#/core/icon:~:text=o%2Ddata-,javascript,-value%2Dmapping)

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
This is not an accessibility-related issue.

#### Did you check the documentation and the API?
Yes, the documentation and API confirm the incorrect icon.

#### Did you search for similar issues?
Yes, no similar issues were found.

#### Is there anything else we should know?
No, that covers the issue.

**Comment by InnaAtanasova** [comment]
Hi @BL19 thank you for reporting the issue. Fundamental-ngx is a consumer of SAP Theming Base Content that provides the SAP fonts and icons. We are just providing an API for using them in Angular projects without all the settings and imports. I will report this problem to the SAP Theming Base Content.
