### ISSUE TITLE
[Feature Request] Property for saving scroll position when using GrowingButton that works with outerScroll

### ISSUE THREAD

**Issue by karolgromacki** [SAP/fundamental-ngx#12096]
Is this a bug, enhancement, or feature request?
Feature Request

We use in our table component outerScroll and growingButton pagination. After deleting item from the table we want to scroll to previous position. We found that pageScrolling provide tableScrolled property that emit value and change scrollTopPosition state. We are looking for same solution to our growingButton and outerScroll case.

Can you handle that on the application side
No

Which versions of Angular and Fundamental Library for Angular are affected? 
v0.50.1

If this is a bug, please provide steps for reproducing it; the exact components you are using;
N/A

Please provide relevant source code (if applicable).
N/A

Please provide stackblitz example(s).
N/A

In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
N/A

Did you check the documentation and the API?
Yes

Did you search for similar issues?
Yes

Is there anything else we should know?
N/A

**Comment by droshev** [comment]
that is already supported. here is an [example](https://stackblitz.com/edit/sjxljz?file=src%2Fapp%2Ftable-custom-pagination-example.component.ts,src%2Fapp%2Ftable-custom-pagination-example.component.html,src%2Findex.html)
You need to add an event listened for `tableScrolled ` and pass the value when needed using `setScrollTop `
