### ISSUE TITLE
Dynamic page is scrollable when in a smaller container

### ISSUE THREAD

**Issue by BL19** [SAP/fundamental-ngx#12099]
#### Is this a bug, enhancement, or feature request?
Feature Request

#### Describe your proposal.
I need some way to disable the [_setDynamicPageHeight()](https://github.com/SAP/fundamental-ngx/blob/2ed634648676de03bf4e7db0f29000d7ad6c87eb/libs/core/dynamic-page/dynamic-page.component.ts#L323) method in the dynamic page. If I could set a custom css height too that would be great. A null value could be used for no height attribute, "auto" for the current behavior and a css value of choice otherwise (like `calc(65vw - 150px)`).

So for the current behavior:
```html
<fd-dynamic-page
  size="small"
  ariaLabel="Example Dynamic Page"
  [autoResponsive]="false"
  height="auto"
>
...
</fd-dynamic-page>
```

And to not set the height on the component the following could be used
```html
<fd-dynamic-page
  size="small"
  ariaLabel="Example Dynamic Page"
  [autoResponsive]="false"
  [height]="null"
>
...
</fd-dynamic-page>
```

#### Can you handle that on the application side
No I don't think so.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.50.0

#### Please provide relevant source code (if applicable).
The method [_getCalculatedFullHeight()](https://github.com/SAP/fundamental-ngx/blob/2ed634648676de03bf4e7db0f29000d7ad6c87eb/libs/core/dynamic-page/dynamic-page.component.ts#L257) in the dynamic-page component.

#### Please provide stackblitz example(s).
I have an example here of what my UI looks like: https://stackblitz.com/edit/stackblitz-starters-4tphfh?file=src%2Fmain.ts

#### Did you check the documentation and the API?
Yes, all the examples in the documentation are fullscreen and the API does not expose any way to alter the height.

#### Did you search for similar issues?
Yes, I could not find any.

**Comment by droshev** [comment]
Thanks for reporting the issue, @BL19. To better assist you, please describe the problem in more detail and what is your target scenario. thanks

**Comment by BL19** [comment]
It seems like I had missed the [expandContent](https://sap.github.io/fundamental-ngx/#/core/dynamic-page/api:~:text=component.ts%3A63-,expandContent,-expandContent%3A) property of the dynamic-page, that setting does what I requested above by disabling the [_setDynamicPageHeight()](https://github.com/SAP/fundamental-ngx/blob/2ed634648676de03bf4e7db0f29000d7ad6c87eb/libs/core/dynamic-page/dynamic-page.component.ts#L323) method.
