### ISSUE TITLE
Combobox - Reactive form not working properly with [communicateObject]

### ISSUE THREAD

**Issue by saurabhagarwal7755** [SAP/fundamental-ngx#12097]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
For COMBOBOX
We are using fd-combobox with [communicateByObject] as we are using custom objects from the dropdownValues (trigger new div when the value changes) and the combobox is "Required" field for us.
In fundamentals version 0.43, upon removal of the data from combobox it was clearing the data like this: https://docs-0-43--fundamental-ngx.netlify.app/#/core/combobox
Please check the image below:
![Screenshot 2024-07-11 at 12 27 08 PM](https://github.com/SAP/fundamental-ngx/assets/52731148/282e1a52-8f8b-4990-b8cc-ab169c680453)
In fundamentals version 0.47 to 0.50 it got updated and now upon clearing the field in combobox, its taking the previously selected value, due to which we are not able to do invalid check and it is allowing to save the information even if the data is empty, as it is taking the last selected value and saving it: https://docs-0-47--fundamental-ngx.netlify.app/#/core/combobox
Please check the image below:
![image](https://github.com/SAP/fundamental-ngx/assets/52731148/bc164cd9-ed58-4597-a46b-533e0d7fd74f)

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Go to version 0.47 of fundamentals.
2. Navigate to combobox, in which  [communicateByObject]="true" is used.
3. Select an option and then clear the value. 
4. Upon clearing it should clear the Json Value also, but here it is having the value selected in step 3
5. In version 0.43, this behaviour is working as expected.

**Comment by InnaAtanasova** [comment]
Hi @saurabhagarwal7755 thanks for opening the issue. Could you please verify if this solution is what you expect as behaviour. Thanks

**Comment by saurabhagarwal7755** [comment]
Hello @InnaAtanasova ,
Checked the preview in provided link. This solution would work for me, thank you for the fix.
Thanks
