### ISSUE TITLE
[P2][Sourcing] Unable to select multiple users if using search in approval flow

### ISSUE THREAD

**Issue by CSEHoangV** [SAP/fundamental-ngx#12093]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

- When we try to add multiple users in approval flow and if we use search and select another user, the previous selected users will be clear:

https://github.com/SAP/fundamental-ngx/assets/162270184/cfca8254-e4c8-439c-9fc3-bff497803f7b

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15 (I think even in main branch)
0.43.35

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

bug

#### Please provide relevant source code (if applicable).

https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/approval-flow

#### Please provide stackblitz example(s).

https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/approval-flow

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

We have multiple reports from customers about this issue. This is not good for them especially when they have a lot of approvers so they need to use search to select user.

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
Fix has been merged for ng15 but we'll need this on the main branch as well

**Comment by droshev** [comment]
closing it as we don't have spec
