### ISSUE TITLE
Hardcoded tooltip "navigation-down-arrow"

### ISSUE THREAD

**Issue by C5382598** [SAP/fundamental-ngx#12101]
Is this a bug, enhancement, or feature request?

Bug.

Briefly describe your proposal.

Hardcoded tooltip "navigation-down-arrow"

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.0

Fundamental NGX (core, platform, cdk, i18n): 0.42.0

If this is a bug, please provide steps for reproducing it.

Steps To Reproduce:

Log in as Pseudo Tagged locale user eu_FR210309b
Create a guided souring project > full project
Create a new phase
Hover over the Alert dropdown to bring up the tooltip
Observe the issue
<img width="1699" alt="image" src="https://github.com/user-attachments/assets/3623ccb0-b610-4e56-9203-663ece4e6f04">

**Comment by InnaAtanasova** [comment]
hi @C5382598 , thanks for opening the issue. You described steps to reproduce the problem, but unfortunately we don't have access to this project. The best way to describe a problem with a component from our library is to point to an example in the documentation or create a Stackblitz example that is similar to your case and can show us the problem. Here's an example of how to describe a problem in your app:
https://github.com/SAP/fundamental-ngx/issues/12099

The user mentioned the component they used, provided a code snippet and also an example of their UI. In most cases just an example is enough for us to understand the use case and the problem. 
Please let me know if you need more information or have any questions. Thanks

**Comment by sreekanthkarini** [comment]
There was a same f-ngx issue logged back to 2023 - https://github.com/SAP/fundamental-ngx/issues/11120, and it was mentioned in the f-ngx comment that it should be in the latest 0.42.x. but it was not implemented correctly.

Looks like the fix by F-NGX was not applied correctly onto the `<fdp-combobox>` component. Instead, it went to `<fd-combobox>`
Please check the diff here:
Source code HTML for `<fd-combobox>`
https://github.com/SAP/fundamental-ngx/blob/ng-15-downport/libs/core/src/lib/combobox/combobox.component.html#L55
 
Source code HTML for `<fdp-combobox>`
https://github.com/SAP/fundamental-ngx/blob/ng-15-downport/libs/platform/src/lib/form/combobox/combobox/combobox.component.html#L43 (You can see that it is missing the fdTranslate directive compared to one above)

**Please implement the fix correctly for `<fdp-combobox>` component this time as part of this F-NGX issue.**

**Comment by droshev** [comment]
@C5382598 Version `0.42` is not supported as it is quite old. If you are able to reproduce the issue with newer version, please, create a new ticket.
