### ISSUE TITLE
In button group by default selected button is not getting unselected

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#1211]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
By default when we have a button selected on the group, on select of another button, class is not getting reset to default/disabled from selected.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
fundamental-ngx 0.9.0
#### If this is a bug, please provide steps for reproducing it.
-> On page load have button selected by default.
--> now select on another button.
-->previous button still remains selected.

**Comment by sKudum** [comment]
<img width="189" alt="Screen Shot 2019-09-02 at 5 16 35 PM" src="https://user-images.githubusercontent.com/53487468/64112774-00036b00-cda6-11e9-8f54-d960263a3d3c.png">

**Comment by JKMarkowski** [comment]
It's not really bug, we didn't provide functionality to have only 1 selected button. Generally it's more visual component, user can control/change states of each button without any restrictions.

**Comment by sKudum** [comment]
Hi Mark, 
 Shall I change the label then? and can I provide the functionality to have only 1 selected button to fundamental-ngx?

**Comment by JKMarkowski** [comment]
@sKudum it's fine with label, I brief you what is the decision tomorrow.

**Comment by JKMarkowski** [comment]
@sKudum Sorry for not briefing yo beforeu, we will include this functionality in next sprint.

**Comment by sKudum** [comment]
> @sKudum Sorry for not briefing yo beforeu, we will include this functionality in next sprint.

Thank You Mark, Let me know when I can work on it then.

**Comment by JKMarkowski** [comment]
Actually maybe it will be better for you to wait, we are currently doing very big refactor, related to latest `fundamental-styles` library changes.

**Comment by droshev** [comment]
Let's improve the examples by adding:
- button group where 1 button can be toggled at a time
- button group where each of the button can be toggled independently from the others
We want to support all the scenarios so the applications can decide which way to use it

**Comment by sKudum** [comment]
> Let's improve the examples by adding:
> 
> * button group where 1 button can be toggled at a time
> * button group where each of the button can be toggled independently from the others
>   We want to support all the scenarios so the applications can decide which way to use it

Hi Deno, we are implementing this feature in the platform with [multiselect], I will provide the same in core as well. 
Draft design for the approach in the platform (it is still under discussion)
https://github.com/SAP/fundamental-ngx/wiki/Platform:-Grouped-Button-Component-V1.0-Technical-Design
