### ISSUE TITLE
[Icons] Downport AI-related icons to 0.43.x

### ISSUE THREAD

**Issue by MiaXu-SAP** [SAP/fundamental-ngx#12128]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Describe your proposal.
We'd like the **AI-related icons (da, da-2, ai)** to be downported to version 0.43.x as we're using A15 and our app will require the icons.
- Latest version: https://sap.github.io/fundamental-ngx/#/core/home
- 0.43.x: https://docs-0-43--fundamental-ngx.netlify.app/
![Screenshot 2024-07-17 at 10 50 01](https://github.com/user-attachments/assets/aa6b9ad1-2876-41f3-89c8-2d42881854e5)

#### Can you handle that on the application side
No.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
Fundamental: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
N.A.

#### Please provide relevant source code (if applicable).
N.A.

#### Please provide stackblitz example(s).
N.A.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
N.A.

#### Did you check the documentation and the API?
Yes. The icons are only available in version >= 0.46.x

#### Did you search for similar issues?
Yes.

#### Is there anything else we should know?
No.

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by MiaXu-SAP** [comment]
Hi @droshev , kindly check in as I saw this issue is tagged with Spring 136 release. Does it mean our proposal will be accepted and the icons will be available in 0.43.x? 
:) Thanks

**Comment by droshev** [comment]
@MiaXu-SAP the change is coming from the package theming-base-content. What you need to do is:
- update to the version of that package(which has the font-files)
- include this css selectors in your application:
`
.sap-icon--ai:before {
   content: "\e2a5";
} 

.sap-icon--da:before {
    content: "\e2a3";
} 
[ngicon.zip](https://github.com/user-attachments/files/16317270/ngicon.zip)


.sap-icon--da-2:before {
    content: "\e2a4";
} 
`

you can see a sample angular application
