### ISSUE TITLE
button gets unselected when we click on the page any ware

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#1212]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Button gets unselected when even user clicks on the page.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
fundamental-ngx 0.9.0

#### If this is a bug, please provide steps for reproducing it.
-->select a button.

<img width="233" alt="Screen Shot 2019-09-02 at 5 23 27 PM" src="https://user-images.githubusercontent.com/53487468/64112930-73a57800-cda6-11e9-8ea1-9e4b27ed3aeb.png">

--> click some ware of the page. the button won't remain selected.
<img width="208" alt="Screen Shot 2019-09-02 at 5 23 47 PM" src="https://user-images.githubusercontent.com/53487468/64112950-83bd5780-cda6-11e9-870e-8fc5c77bb943.png">

**Comment by droshev** [comment]
@sKudum is this platform related issue?

**Comment by sKudum** [comment]
> @sKudum is this platform related issue?

Hi Deno, This issue we observed while using **button group** from core.

**Comment by JKMarkowski** [comment]
@sKudum this behaviour can be implemented in application level.
