### ISSUE TITLE
Virtual scroll whole rows [attr.title] performance issue

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#12137]
When using `scrollWholeRows`, and thus forcing line wraps in table cells, long text is truncated and the complete text is applied to the cell's title attribute, using the following code:

```
                [attr.title]="
                    tableTextContainer.offsetWidth < tableTextContainer.scrollWidth
                        ? tableTextContainer.textContent
                        : null
                "
```

The `offsetWidth < scrollWidth` comparator can cause performance issues. Need to refactor how this is handled. Also need to add a conditional that this is only when using `scrollWholeRows`

**Comment by CSEHoangV** [comment]
Can you help prioritizing this either with solution or removal? This does not only affect `scrollWholeRows`.

**Comment by droshev** [comment]
@mikerodonnell89 What version are we talking about?

**Comment by mikerodonnell89** [comment]
> Can you help prioritizing this either with solution or removal? This does not only affect `scrollWholeRows`.



> @mikerodonnell89 What version are we talking about?

for ng-15, 0.43.37. And whatever fix we have for ng15 we'll need for the main branch as well
