### ISSUE TITLE
Message Strip Alerts aren't showing.

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#12139]
#### Is this a bug, enhancement, or feature request?
bug?

#### Describe your proposal.

https://fundamental-ngx.netlify.app/#/core/message-strip -> Message Strip Alerts aren't showing

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
latest

**Comment by khotcholava** [comment]
We need to update the documentation example. This is not a bug; it works correctly on the [StackBlitz example](https://stackblitz.com/run?file=package.json).
