### ISSUE TITLE
Bug when accepting autosuggestions for combobox

### ISSUE THREAD

**Issue by programister42** [SAP/fundamental-ngx#12142]
#### Is this a bug, enhancement, or feature request?

Bug

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

angular 17.3.1
fundamental-ngx 0.49.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Component: combobox from core lib

Steps to reproduce:

- open stackblitz example
- open browser console (to watch `isBusy$` value changes)
- type `Toma` into the combobox
- press the right arrow key to expand the word to `Tomato`
- press enter

Expected result: skeleton hides after one second delay, combobox is ready to use
Actual result: skeleton is still displayed after one second, even if the `isBusy$` value in the console is already `false`

#### Please provide relevant source code (if applicable).

https://stackblitz.com/edit/3wucuz?file=src%2Fapp%2Fcombobox-forms-example.component.ts

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/3wucuz?file=src%2Fapp%2Fcombobox-forms-example.component.ts

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by alexhristov14** [comment]
@programister42 Issue is fixed in latest versions of fundamental-ngx and angular.
