### ISSUE TITLE
[P2][Sourcing] `scrollWholeRows`: parent scrollbar gets affected when table scrollbar hits bottom

### ISSUE THREAD

**Issue by CSEHoangV** [SAP/fundamental-ngx#12159]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

When we scroll and table scrollbar hits bottom in `scrollWholeRows`, it propagates to outer scroll and also makes it scroll which does not happen when we disable `scrollWholeRows`.

https://github.com/user-attachments/assets/dac19cb3-c27c-4bcb-b885-0b020047666b

#### Can you handle that on the application side

no

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

angular 15
0.43.38

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

- Create platform table with `scrollWholeRows` and `pageScrolling`.
- Make sure document body or parent is scrollable.
- Scroll till scrollbar hits table bottom.

Result: parent body also scroll.
Expected: it should not affect parent body.

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/angular-rvez99-yk8hzz?file=src%2Fapp%2Fadvanced-scrolling-example.component.html

#### Did you check the documentation and the API?

yes

#### Did you search for similar issues?

yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
After speaking with the designers, they said, in the event of scrolling via mouse/touch gestures, we should be fetching enough data ahead of time that it is loaded (i.e. more rows and at a higher px threshold) before the user gets to the point where they'll need to see a busy indicator. Of course this is best case scenario, and there are times when an API call takes longer than expected. Or, for keyboard users, they may press the "End" key and skip straight to the bottom. In this case we should display a busy indicator, not over the entire table but at the bottom of the table over one blank row. And I think (I am guessing) when we are displaying this one loading row, we can apply `overscroll-behavior-y: contain` to the table. But i think it should go back to `auto` when the loading is done.
