### ISSUE TITLE
combobox should support states

### ISSUE THREAD

**Issue by GauSim** [SAP/fundamental-ngx#1216]
#### Is this a bug, enhancement, or feature request?

enhancement  / consistency bug? :) 

#### Briefly describe your proposal.

`fd-combobox` should support states like input to give user indication of input errors or warnings in the form. Red & Orange highlighting

```html
<fd-combobox formControlName="some" [state]="'invalid'">
</fd-combobox>
```

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

0.9.3

#### If this is a bug, please provide steps for reproducing it.
![Screenshot 2019-09-03 at 16 45 34](https://user-images.githubusercontent.com/5481197/64183526-4e7a3d80-ce6a-11e9-94a6-9f7377eb2062.png)

**Comment by droshev** [comment]
Example of existing state can be found in `input` - https://sap.github.io/fundamental-ngx/input Section `https://sap.github.io/fundamental-ngx/input`
