### ISSUE TITLE
[P3][Sourcing][Accessibility][Value help dialog table]: UI role table /grid is not conveyed

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#12165]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
When accessing table inside value help dialog , the role of the table saying grid / table is not conveyed in screenreader

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng:15
core/platform: 0.43.36

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1) traverse to table inside value help dialog inside 
2) notice screenreader 
3) nothing is read stating entering table or grid

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/value-help-dialog

#### Please provide stackblitz example(s).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/value-help-dialog

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Reported by ATL team

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
Table has role="grid". Need to check this on jaws

![Screenshot 2024-07-23 at 4 46 14 PM](https://github.com/user-attachments/assets/612d2772-c2c5-44dc-947b-1b414ccdf913)

**Comment by mikerodonnell89** [comment]
![Screenshot 2024-07-24 at 4 48 53 PM](https://github.com/user-attachments/assets/1c8fb700-9dc7-43fd-9e63-3f84a7973550)
