### ISSUE TITLE
date picker should support state

### ISSUE THREAD

**Issue by GauSim** [SAP/fundamental-ngx#1217]
#### Is this a bug, enhancement, or feature request?

enhancement / consistency bug? :)

#### Briefly describe your proposal.
`fd-date-picker` should support states like input to give user indication of input errors or warnings in the form. Red & Orange highlighting

```html

<fd-date-picker [type]="'single'" formControlName="some" [state]="'invalid'">
</fd-date-picker>

```

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

0.9.3

#### If this is a bug, please provide steps for reproducing it.

![Screenshot 2019-09-03 at 16 50 15](https://user-images.githubusercontent.com/5481197/64183935-f5f77000-ce6a-11e9-8508-2361579bef5c.png)

**Comment by droshev** [comment]
Let's try to target 2 things:
- [ ] identify all the components that need to be extended with state
- [ ] identify the design changes for each component

**Comment by JKMarkowski** [comment]
Hi @droshev 
I think every component that uses input group should be extended with state
- Combobox
- Datepicker
- DateTimePicker
- InputGroup
- TimePicker
- Localization Editor (maybe)
- MultiInput

About the messages, I would rather follow our actual form-message like that.
![image](https://user-images.githubusercontent.com/26483208/66659113-1fae6e80-ec43-11e9-9070-37ad95aaff6d.png)

**Comment by droshev** [comment]
Let's plan the work in styles and then for ngx(sprint 23)
