### ISSUE TITLE
Platform table personalization dialog column ordering updates

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#12175]
The table column ordering p13 dialog needs to match the new design that we seen in ui5 etc, where the buttons to reorder a column are on the list item representing the column itself, rather than how we have it now, in the dialog toolbar.

Current: 
![Screenshot 2024-07-24 at 12 08 24 PM](https://github.com/user-attachments/assets/386f4f29-5097-42eb-a11d-c879508dc412)

Desired:
![image](https://github.com/user-attachments/assets/98af9742-10f0-4d5b-b4c9-ad753752fd96)

**Comment by shawchandankumar** [comment]
@mikerodonnell89 Only the reordering buttons needs to be shifted in the column right? other UI should remain same
As I see in the desired image there is sort, group and filter also in the same dialog
