### ISSUE TITLE
Table Dialog Improvements

### ISSUE THREAD

**Issue by GoodDesignWorks** [SAP/fundamental-ngx#12181]
#### Is this a bug, enhancement, or feature request?
Visual bugs

#### Describe your proposal.
The Table dialogs improvements 

1. Filtering Dialog now:
<img width="538" alt="Screenshot 2024-08-02 at 16 52 26" src="https://github.com/user-attachments/assets/24b499c5-1faf-4d41-aa99-24a8910abccb">

- **height**: The dialog has a lot of unused white space. Especially above and below the list component. Footer and header must be aligned with the component without spacing. Each List Item should have 44px height.
- **width**: The dialog has also a lot of unused width. The specified options do not require the entire width. 320px width would be enough.
- 

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
open it on a test page

**Comment by dreamweiver** [comment]
@GoodDesignWorks , Its difficult to understand what you are expecting here,  would it be possible for you to add a visual snapshot or create a live example on stackblitz ?

**Comment by droshev** [comment]
The issue makes sense, we just need to sit and document all the points against the design.

**Comment by droshev** [comment]
we have another ticket to track the changes
