### ISSUE TITLE
[FEATURE REQUEST] Add modal property to Popover control

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#12210]
#### Is this a bug, enhancement, or feature request?

It is a feature request.

#### Describe your proposal.

Is it possible to add a "modal" property to the Popover control like it is working in sapui5? https://sapui5.hana.ondemand.com/#/api/sap.m.Popover%23constructor

![image](https://github.com/user-attachments/assets/d0afd4a8-a2fb-4a99-a7be-2de8eeb30c7f)

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

- Angular 17.3.1
- FundamentalNGX 0.51.1 (current available version)

#### Did you check the documentation and the API?

Yes, I didn't find it here - https://sap.github.io/fundamental-ngx/#/core/popover/api

**Comment by droshev** [comment]
@egorwow70 we have an input for that `closeOnOutsideClick`

**Comment by alexhristov14** [comment]
@egorwow70 In the api tab, if you select the `PopoverComponent` file, you will find the `closeOnOutsideClick` input which is essentially the same as the modal property as commented above.

**Comment by egorwow70** [comment]
@alexhristov14 

Hello, sorry for the late response, I think they are different, because closeOnOutsideClick controls whether the control can be closed by outside click. But modal property in sapui5 makes the outside background black and you cannot close it by clicking outside anymore.

![image](https://github.com/user-attachments/assets/dd4138a7-758f-453b-801f-b54fb04c0f34)
