### ISSUE TITLE
Grid list item with multi selection and navigation - can't select item via mouse click

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#12218]
When trying to select a grid list item that has navigation in multiselect mode with a mouse click, only the navigation event is fired, and the select does not go through.  See vid

https://github.com/user-attachments/assets/aeb3559b-2c21-4dd2-8885-563a6646a539

**Comment by droshev** [comment]
@khotcholava Can you check this one after you fix the grid list keyboard? thanks
