### ISSUE TITLE
[FEATURE REQUEST] Add the ability to hide the refresh button in the search input of the platform table.

### ISSUE THREAD

**Issue by pawelkarwat** [SAP/fundamental-ngx#12236]
#### Is this a bug, enhancement, or feature request?

feature request

#### Describe your proposal.

In the platform table's search input, we need to add the ability to hide the refresh button. This button is not needed in our implementation, and we would like to have the option to hide it, similar to how it is possible to add [disableRefresh]="true" when using the SearchFieldComponent directly.

#### Can you handle that on the application side

No

**Comment by InnaAtanasova** [comment]
Hi @pawelkarwat thank you for creating the issue. I opened a PR with the feature. Please check if there's something more needed. Thank you!
