### ISSUE TITLE
"Invalid Date" is hardcoded in Date Range date picker

### ISSUE THREAD

**Issue by C5358948** [SAP/fundamental-ngx#12237]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.

"Invalid Date" is hardcoded in Date Range date picker

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Steps To Reproduce:
Log in as language user such as eu_FR210309b, zh_CN210309b, etc. 
Create a guided souring project > RFP
Click event action > View event audit log
In date range date picker > Select a future date as the start, and select a past date as the end date to trigger Invalid date error
Observe the issue

![image](https://github.com/user-attachments/assets/7e8876b3-dffa-4840-9127-baeaae9516a9)

**Comment by droshev** [comment]
@C5358948 Can you create a stabkblitz isolating the scenario? We cannot access your application.

**Comment by droshev** [comment]
no activities => closing the issue
