### ISSUE TITLE
Bug: Overflow of fdp table toolbar leads to changing spacing when resizing the viewport

### ISSUE THREAD

**Issue by do-oel** [SAP/fundamental-ngx#12239]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal

- When using the fdp-table with a table toolbar and adding additional buttons to the toolbar actions, resizing the browser window leads to a growing and shrinking spacing between the sort button and the overflow button (see stackblitz example and video below). This is not intended.
- **Expected behavior: all actions should always be aligned to the right with fixed spacing in between**
- Additionally the automatically appearing separators (grey lines) in between the search bar, filter button, the additional actions and the overflow button are not needed and can be removed

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
see description above
#### Please provide stackblitz example(s).
https://stackblitz.com/edit/775juw?file=src%2Fapp%2Fplatform-table-sortable-example.component.html
#### Screen Recording
https://github.com/user-attachments/assets/3a95d7ae-3085-4fd1-9d5b-f0c0465b5c9a

**Comment by droshev** [comment]
@do-oel the link to the [stackbliz](https://stackblitz.com/edit/775juw?file=src%2Fapp%2Fplatform-table-sortable-example.component.html) example doesn't have that problem. Can you update it?

**Comment by do-oel** [comment]
@droshev Just checking in - any updates here? I updated the stackblitz example a while ago and it should illustrate the issue. Let me know if you need any additional information
