### ISSUE TITLE
search field UI inconsistency. 

### ISSUE THREAD

**Issue by ShirSAP** [SAP/fundamental-ngx#12260]
#### Is there anything else we should know? On NGX there is an extra padding between the close and magnifying glass
on the Wiki it states there should be none.

NGX:
<img width="102" alt="image" src="https://github.com/user-attachments/assets/6f574d1c-505d-4566-a7b9-e47c30b678a1">

Wiki:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/a4921e1b-d69e-4d1c-9a4a-596f4ba65351">

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by InnaAtanasova** [comment]
Hi @ShirSAP 
which version is this? I just tested our documentation with the latest version and there's no space between the buttons:
https://fundamental-ngx.netlify.app/#/platform/search-field

<img width="1345" alt="Screenshot 2024-08-19 at 9 28 23 AM" src="https://github.com/user-attachments/assets/c5ec4f56-6a4b-40ba-9ac6-7e4b98d2352e">

**Comment by droshev** [comment]
It was implemented in styles; brought in ngx
