### ISSUE TITLE
Platform table grouping not spanning entire row

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12261]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
For the platform table component, grouping should span entire row with navigation and semantic highlighting.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Use [platform table](https://sap.github.io/fundamental-ngx/#/platform/table/basic) with grouping, navigation and semantic highlighting.
2. Try grouping on some field. The group headers does not span entire row which gives bad user experience. Please refer below screenshot:
<img width="849" alt="Screenshot 2024-08-14 at 3 56 49 PM" src="https://github.com/user-attachments/assets/07b23003-0940-45e8-9919-9fec12216306">

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/prywkj-gdtmcd?file=src%2Findex.html

#### Did you check the documentation and the API?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by rebecagm** [comment]
I'm also experiencing the same issue. @InnaAtanasova

**Comment by droshev** [comment]
Update: the issue is **only** reproducible if the table is set to `[rowNavigatable]="true"` and has grouping enabled.

**Comment by divyamalhotra488** [comment]
Hi @droshev, as I have already mentioned in the description the issue happens with grouping when either navigation is enabled or when semantic highlighting is enabled or both.
