### ISSUE TITLE
[Feature Request] Property for tracking scroll position when using table component with outerScroll

### ISSUE THREAD

**Issue by karolgromacki** [SAP/fundamental-ngx#12264]
Is this a bug, enhancement, or feature request?
Feature Request

Request for a table component property to track scroll position when using outerScroll.
There is a tableScrolled property to track the scroll position, but it does not work with the outerScroll property.
Reading the scroll position only works with this particular property configuration:
 (tableScrolled)="setTableOffset($event)" [pageScrolling]="true" bodyHeight="550px"

For [my table](https://stackblitz.com/edit/sjxljz-ru4fzc), I use the growing button with outerScroll, and the table does not have a fixed bodyHeight. I also don't want to use the pageScrolled function. I just need to track the scroll position.

Can you handle that on the application side
No

Which versions of Angular and Fundamental Library for Angular are affected?
Fundamental: v0.51
Angular: 18.0.3

If this is a bug, please provide steps for reproducing it; the exact components you are using;
N/A

Please provide relevant source code (if applicable).
N/A

Please provide stackblitz example(s).
https://stackblitz.com/edit/sjxljz-ru4fzc

In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
N/A

Did you check the documentation and the API?
Yes

Did you search for similar issues?
Yes

Is there anything else we should know?
N/A

**Comment by mikerodonnell89** [comment]
I can remove the requirement that `pageScrolling` must be true in order for the table to emit the `tableScrolled` event, but if the table itself isn't scrollable (which, when using outerScroll without a bodyHeight, it is not), I'm don't think emitting the event from the table component makes sense. Would it then be better instead to add a scroll listener on the wrapping container?

**Comment by mikerodonnell89** [comment]
@karolgromacki I recommend what I mentioned above. If you take a look at my [fork of your stackblitz](https://stackblitz.com/edit/sjxljz-q18yxc?file=src%2Fapp%2Ftable-custom-pagination-example.component.ts) you'll see the "scroll the table" button working fine. You could also add a scroll listener to the `this.pageContent.nativeElement.parentNode` element to store the scroll position. Hope this helps. Please let me know if this isn't sufficient and we'll reopen the issue
