### ISSUE TITLE
[Sourcing][Accessibility] Focus and visibility of the cell is not working properly in fdp-table

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#12284]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.

**Case 1:**

**Steps with proposal:**
1. In `fdp-table with scrolling`, make the first row partially visible.
2. Use tab to reach the first column header of the table
3. Use arrow down key, to focus the first cell .
4. The first cell (which is in the focus) should be completely visible.

**Case 2:**

**Steps with proposal:**

1. Selected any cell in the `fdp-table`
2. Selected something ouside of the cell and use tab to reach the table
3. The focus should go to the table directly, without any additional tab stop.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular - 15
F-NGX - 0.43.41

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

**Steps for Case 1:** 

1. Use `fdp-table` with scrolling and table toolbar available
2. Make the first row partially visible
3. Use tab to reach the first column header of the table
4. Use arrow down key, to focus the first cell .
5. Observe that the first cell (which is in the focus) isn't completely visible.

<img width="1700" alt="Screenshot 2024-08-19 at 12 50 24 PM" src="https://github.com/user-attachments/assets/0b335528-9adf-44a3-b059-2c204f816e44">

**Steps for Case 2:**

1. Use `fdp-table` with scrolling and table toolbar available
2. Selected any cell in the table
3. Selected something outside of the cell and use tab to reach the table
4. Observe that the focus isn't going directly to the cell.

<img width="1705" alt="Screenshot 2024-08-19 at 12 51 28 PM" src="https://github.com/user-attachments/assets/90515922-64e6-40de-9ac8-b21692c33050">

#### Please provide stackblitz example(s).

Stackblitz Link - [click here](https://stackblitz.com/edit/angular-4umppk?file=src%2Fapp%2Fadvanced-scrolling-example.component.ts)

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, the focused cell should be completely visible.

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@mikerodonnell89 I thought this was addressed with the new virtual scrolling implementation, no?

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89 I thought this was addressed with the new virtual scrolling implementation, no?

Yes, @Sayandeep-123 you should utilize the new `[scrollWholeRows]` input if this is a concern
