### ISSUE TITLE
Input placeholder text missing left margin

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#12296]
Appears to be fine in fundamental-styles latest documentation, so I think this is probably coming from ngx

<img width="207" alt="Screenshot 2024-08-22 at 3 10 14 PM" src="https://github.com/user-attachments/assets/cbfa0b10-40e8-460d-a889-e0376e2ee639">

**Comment by shawchandankumar** [comment]
I could not reproduce the issue. Looks working in my local setup.

**Comment by alexhristov14** [comment]
It seems to be working fine right now in the official docs
