### ISSUE TITLE
i18n support for the time period text of the Time Picker control

### ISSUE THREAD

**Issue by ronsantiago** [SAP/fundamental-ngx#1229]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Have the ability to translate the time period (am / pm) to other languages (e.g Chinese)

![image](https://user-images.githubusercontent.com/29599364/64443457-e90f9200-d09f-11e9-9e75-4875f5376c06.png)

**Comment by JKMarkowski** [comment]
Hello @ronsantiago, please check https://sap.github.io/fundamental-ngx/time on `Internationalization` section, there is example of changing the placeholders/time period, by providing service. It will work also on datetime picker or time picker.

**Comment by ronsantiago** [comment]
Great! I was not aware that it was already implemented. Thanks!
