### ISSUE TITLE
All the documentation dissapeared

### ISSUE THREAD

**Issue by aksh3ll** [SAP/fundamental-ngx#1230]
#### Is this a bug, enhancement, or feature request?
A BUG

#### Briefly describe your proposal.
A documentation online accessible.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
The released version.

#### If this is a bug, please provide steps for reproducing it.
Open https://sap.github.io/fundamental-ngx/ then 404

#### Please provide relevant source code if applicable.
https://github.com/SAP/fundamental-ngx/blob/master/package.json#L10
Did you miss a step when published last release?

#### Is there anything else we should know?
It's pretty nice, but i'm impatient to see a tree component.

**Comment by droshev** [comment]
@aksh3ll The issue has been resolved.
