### ISSUE TITLE
Use select API for Form generator type select

### ISSUE THREAD

**Issue by ghost** [SAP/fundamental-ngx#12302]
Hi, we are trying to use the [select](https://sap.github.io/fundamental-ngx/#/platform/select) api in the [Form generator type select](https://sap.github.io/fundamental-ngx/#/platform/form-generator). Here we have seen an example of the type `switch`. It seems that it uses the same API as this [switch](https://sap.github.io/fundamental-ngx/#/platform/switch). Like the following.
```
 {
        type: ‘switch’,
        name: ‘enable_feature’,
        message: ‘Enable Some Analytics’,
        default: false,
        guiOptions: {
            additionalData: {
                semantic: true
            }
        }
    }
```
Our goal is to set the width of `select` to the same width as `input` width with `guiOptions`, as the following code example and the attached screenshot show.

```
 {
        type: ‘select’,
        name: ‘big select,
        message: ‘make it big´,

        guiOptions: {
            additionalData: {
                   minWidth: 999999,
            }
        }
    }
```
<img width="841" alt="Screenshot 2024-08-23 at 15 56 41" src="https://github.com/user-attachments/assets/e3ccbf00-a66a-46fa-82f3-926e44e5d9ab">

We would appreciate any advice and support.
Regards
Thaer

**Comment by khotcholava** [comment]
@Tai000000 Please attach a StackBlitz example to the issue for better clarity and reproduction.
