### ISSUE TITLE
[P2][Sourcing][Localisation][PLATFORM Multi-Combobox] : Invalid entry - error message in english not translated to Hungarian language

### ISSUE THREAD

**Issue by 184801** [SAP/fundamental-ngx#12336]
#### Is this a bug, enhancement, or feature request?
BUG

#### Describe your proposal.
**Invalid entry - error message EN**
Expectation :  Invalid Entry" error message is  not translated into the Hungarian  language.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/ platform: 0.43.40

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
*"Invalid Entry" error translation in fdp-multi-combobox*
Open the fdp-multi-combobox Component
Enter Text Not Present in the List
Observe the "Invalid Entry" Error
Translate the "Invalid Entry" Error Message
"Invalid Entry" error message is  not translated into the Hungarian language.

https://github.com/user-attachments/assets/1a41fe97-43fe-499b-b2f6-13982595e7f9

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/angular-6mvwz6?file=src%2Fapp%2Fmulti-combobox-columns-example.component.ts

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
fixed and will be published in 0.43.44
