### ISSUE TITLE
adopt self-contained styles from fundamental-styles version 0.2

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1234]
User Story for adopting self-contained styles from `fundamental-styles` (version 0.2)

## Branch Strategy
To be discussed. There are few options:
- each component update is done in a separate branch that goes to `master`. In that case each PR should not introduce regression to the other components. This way we should be able to release at any time
- we create a dedicated feature branch where we bring all the component refactoring. Once the whole library is ready we merge the special feature branch into `master`

## List of components/directives
- [x] action-bar
- [x] alert
- [x] badge-label
- [x] breadcrumb
- [x] button 
- [x] button-group 
- [x] calendar
- [x] combobox
- [x] date-picker
- [x] datetime-picker
- [x] file-input - Doesn't need change
- [x] form
- [x] icon
- [x] identifier
- [x] image
- [x] infinite-scroll - Doesn't need change
- [x] inline-help
- [x] input-group - **Refactored**
- [x] layout-grid **NEW ONE** - **In review with panel/table** - Jedrzej
- [x] list
- [x] loading-spinner
- [x] localization-editor - **Refactored**
- [ ] mega-menu - CSS in Review - **Inna**
- [x] menu
- [x] modal
- [x] multi-input -  **Refactored**
- [x] pagination
- [x] panel - **in review** - Jedrzej
- [x] popover
- [x] scroll-spy - IT doesn't need styles
- [x] search-input - **to be removed/or delegate to combobox**
- [x] select
- [x] shellbar 
- [x] side-navigation
- [x] split-button
- [x] table - **In review** - Jedrzej
- [x] tabs
- [x] tile
- [x] time
- [x] time-picker - **In Review** - Jedrzej
- [x] toggle
- [x] token
- [x] tree - **In review - little code refactor - add section** - Jedrzej
- [ ] doc site review/improvement

## Additional Remarks:
- `fundamental-styles` breaking changes in version `0.2` [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes).
- Angular doesn't support importing stylesheet in `directive`. In order to import stylesheet we need change our implementation. One approach is as to have a directive but wrap in TypeScripted as a component so I can import the stylesheet

**Comment by droshev** [comment]
Issues to be addressed:
- [ ] modal custom backdrop class is not assigned
- [ ] popover examples styling is off

**Comment by JKMarkowski** [comment]
All types of form elements: input, select, textarea right now needs to have class (fd-input, fd-textarea etc.).

**Comment by JKMarkowski** [comment]
For Addons / Input Groups `.fd-input-group>*` is usually overwritten by `.fd-input`, or `.fd-button` classes which cause weird alignment.

**Comment by JKMarkowski** [comment]
Class's hierarchy is set by order of imports instead of basic order.

**Comment by JKMarkowski** [comment]
`Mega Menu` component is missing from styles.
