### ISSUE TITLE
Manual Enter Date and Time Format not picked in Event Bidding Start Date Using DayJs

### ISSUE THREAD

**Issue by venkataramanagorela** [SAP/fundamental-ngx#12352]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.

Date Conversion Format is different in datetime picker and manual entry. While entering datetime picker, it takes the correct time, like 02/09/2024 11:02 AM, and entering same date time manual entry, it takes 02/09/2024 18:30 PM GMT (+05:30) format. I debugged the application, it is not showing the conversion format of local date to GMT conversion while entering manual. Please suggest how DayJs converts manual entry datetime to a specific format, like GMT, and why manual entry does not take user-entered time, like 02/09/2024 11:02 AM, it takes 02/09/2024 18:30:00 PM.
where this time format gets converted to 18:30:00 PM
<fd-datetime-picker>
                        </fd-datetime-picker>

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15
core/ platform: 0.43.40
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Using Date Range component
and trying to implement https://sap.github.io/fundamental-ngx/#/core/dayjs-datetime-adapter
#### Please provide relevant source code (if applicable).
<fd-datetime-picker #eventStartDateFieldEdit id="arcrfxeventtimingrules_eventStart"
                                            [attr.awname]="'arcRfxEventTimingRules_eventStart'"
                                            [name]="'eventStartDateChooser'"
                                            inputId="arcrfxeventtimingrules_eventStart"
                                            [(ngModel)]="eventStartDateDayJs"
                                            [disabled]="event.plannedBeginDateType === PlanedDateType_ReadOnly"
                                            placeholder="Select a date"
                                            i18n-placeholder = "Select a date | Select a date place holder@@arcrfxeventtimingrules_shortDateEventStarts"
                                            [attr.ariaLabel]="startDateChooserAriaLabel"
                                            (ngModelChange)="updateEventStartDate()"
                                            [disableFunction]="disablePastDates"
                                            [allowNull]="false"
                                            [required]="true">
                        </fd-datetime-picker>

providers: [
        {
            provide: LOCALE_ID,
            useFactory: getDayJSLocaleId,
            deps: [EventDataService]
        },
        {
            provide: CalendarI18nLabels,
            useClass: CalendarI18nLabels
        },
        {
            provide: DatetimeAdapter,
            useClass: DayjsDatetimeAdapter,
        },
        /* DAYJS_DATETIME_FORMATS is just a constant
           we could make custom format https://day.js.org/docs/en/parse/string-format#list-of-all-available-parsing-tokens */
        {
          provide: DATE_TIME_FORMATS,
          useValue: DAYJS_DATETIME_FORMATS,
        }
      ]

#### Did you check the documentation and the API?
Yes
#### Did you search for similar issues?
Yes, but could not find any similar issue for date Range .
#### Is there anything else we should know?
Please note that issue is not for single date picker
Date Conversion Format is different in datetime picker and manual entry. While entering datetime picker, it takes the correct time, like 02/09/2024 11:02 AM, and entering same date time manual entry, it takes 02/09/2024 18:30 PM GMT (+05:30) format. I debugged the application, it is not showing the conversion format of local date to GMT conversion while entering manual. Please suggest how DayJs converts manual entry datetime to a specific format, like GMT, and why manual entry does not take user-entered time, like 02/09/2024 11:02 AM, it takes 02/09/2024 18:30:00 PM.
where this time format gets converted to 18:30:00 PM

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
@venkataramanagorela I'm a bit confused by your issue description, but we did just fix a bug relating to parsing the datetime input, I believe this may address your issue: https://github.com/SAP/fundamental-ngx/pull/12416, can you check the deploy preview here? https://deploy-preview-12416--fundamental-ngx.netlify.app/#/platform/datetime-picker

**Comment by mikerodonnell89** [comment]
fixed with #12416
