### ISSUE TITLE
The Roles are hardcoded in Inviter project team pop up window

### ISSUE THREAD

**Issue by C5358948** [SAP/fundamental-ngx#12355]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.

The Roles are hardcoded in Inviter project team pop up window

Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular: 15.2.0
Fundamental NGX (core, platform, cdk, i18n): 0.42.0

If this is a bug, please provide steps for reproducing it; the exact components you are using;

Steps To Reproduce:
Log in as Pseudo Tagged locale user eu_FR210309b
Create a guided sourcing project > RFP > Template: Lang_Minerva_RFP
Add an item, supplier
Click Project Owner under Inviter project team and view the pop up window
Observe the issue

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/39736c76-165c-4e43-b6b2-b5be7d84c413">

**Comment by droshev** [comment]
@C5358948 this is not the place to open tickets specific to that application. If you think the issue is from frundamental-ngx, please, create a stackblitz example isolating the issue.
