### ISSUE TITLE
Missing overflow functionality in FilterBar 

### ISSUE THREAD

**Issue by NTSAP** [SAP/fundamental-ngx#12368]
#### Describe your proposal.
Filter Bar overflow actions / buttons behaviour/ responsiveness for smaller screens is missing in Filter Bar & Variant Management

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@khotcholava Can you check that request? Let me know if you have questions. thanks
