### ISSUE TITLE
Console Errors when using IconTabBarComponent from Platform on smaller screens.

### ISSUE THREAD

**Issue by amritanshvns** [SAP/fundamental-ngx#12364]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
Console Errors when using IconTabBarComponent from Platform on smaller screens.
#### Can you handle that on the application side
Nope.
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
I can see this in 49.2 as well as 52.1 [here](https://sap.github.io/fundamental-ngx/#/platform/icon-tab-bar)
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

1. Open the example [here](https://sap.github.io/fundamental-ngx/#/platform/icon-tab-bar)
2. Reduce the width by opening the dev console. Refer the screenshot below.
![image](https://github.com/user-attachments/assets/da4fa2d6-444c-48c5-90d2-182ffc12be87)

#### Did you search for similar issues?
Yes, not reported.

#### Is there anything else we should know?
My use case is to have a dynamic page with tab to be shown in the Second column of the Flexible Column Page View

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@dpavlenishvili Can you check this issue? thanks
