### ISSUE TITLE
Bug: Input field gains hover and focus while cursor hovers / clicks label

### ISSUE THREAD

**Issue by do-oel** [SAP/fundamental-ngx#12373]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
**Current Incorrect Behavior:**
1. When the user hovers over the label of an input field, the input field changes to the hover styling although the cursor is not hovering over the field itself.
2. When the user clicks the label of an input field, the input field becomes focused / active although the cursor didn't click on the field itself.

https://github.com/user-attachments/assets/5e1eebc9-f459-45bf-b068-c57cb2e91091

**Expected Behavior (screen recording from UI5 Webcomponents):**
1. When the user hovers over the label of an input field, the input field doesn't change to the hover visualization.
2. When the user clicks the label of an input field the input field doesn't become focused / active

https://github.com/user-attachments/assets/f1cdd8a5-89b3-4b1e-b2de-810f7bb0df06

#### Can you handle that on the application side
No
#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest and potentially all previous versions

**Comment by droshev** [comment]
@do-oel I don't find any issue here.
