### ISSUE TITLE
"Search" is displaying in English for languages on Select items and lots pop up window

### ISSUE THREAD

**Issue by C5382598** [SAP/fundamental-ngx#12389]
Is this a bug, enhancement, or feature request?

Bug.

Briefly describe your proposal.

"Search" is displaying in English for languages on Select items and lots pop up window

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 15.2.0

Fundamental NGX (core, platform, cdk, i18n): 0.42.0

If this is a bug, please provide steps for reproducing it.

Steps To Reproduce:

Log in as Pseudo Tagged locale user eu_FR210309b or any language users such as de210309b, zh_CN210309b, etc.

Create a guided sourcing project > RFP

Add an item, suppliers

Click 1 item under invited to bid on in Supplier table

Observe the issue
![image](https://github.com/user-attachments/assets/4910993c-9660-401e-a8e2-41b8ad3ae90e)

**Here, is the stackbitz url found in the fundamental NGX Document.**
      https://stackblitz.com/run?file=src%2Findex.html

**Comment by droshev** [comment]
That is up to the application to pass the placeholder. It is part of the api
