### ISSUE TITLE
Core Calendar/DatePicker specialDaysRules not set

### ISSUE THREAD

**Issue by dpavlenishvili** [SAP/fundamental-ngx#12393]
Currently, in the DatePickerComponent, the specialDaysRules input does not apply correctly when used in combination with ngModel or formControl. This issue causes the calendar to not display special days when dates are updated through reactive forms or two-way binding.

**Comment by egorwow70** [comment]
@dpavlenishvili @droshev 

Hello, guys. It seems the issue is still reproduced, please check this stackblitz example - https://stackblitz.com/edit/ed53zg-tddqv9?file=src%2Fapp%2Fdate-picker-issue.component.html

**Comment by egorwow70** [comment]
@droshev 

Hello, deno. I see that the fix was made. Do you know the version of the library and the date when it will arrive?

**Comment by droshev** [comment]
@egorwow70 it should be with `0.53.1`. We are planning to release it next week.

**Comment by egorwow70** [comment]
@droshev 
Hello, thanks a lot for the info

**Comment by egorwow70** [comment]
@droshev 

Hello, sorry to disturb you again, any news about the release?

![image](https://github.com/user-attachments/assets/b60bf49e-fb59-4227-b946-c191f1c690df)

**Comment by droshev** [comment]
It is out now
