### ISSUE TITLE
[Sourcing] The search is not happening properly in Value-help dialog and tool tip is not showing for search icon

### ISSUE THREAD

**Issue by sreecharansai05** [SAP/fundamental-ngx#12395]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal
The search result is being there when we close and open the value-help dialog and when we don't give any keyword and click on search the result is coming which we have searched last Time.

issue -2: The tooltip is not showing for the search and synchronise button in value-help dialog component

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular: 15.2.10
core/platform: 0.43.40

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

https://github.com/user-attachments/assets/6512f19a-67c5-4db3-a4fd-84f5545a21ec

<img width="942" alt="image" src="https://github.com/user-attachments/assets/fdd7f9dc-93d1-4d8f-92be-ac23519dec45">

#### Please provide relevant source code (if applicable).
https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/value-help-dialog
#### Please provide stackblitz example(s).
https://stackblitz.com/run?file=src%2Fapp%2Fplatform-vhd-input-example.component.ts
#### Did you check the documentation and the API?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@sreecharansai05 I used ng-15 and I am not able to reproduce it.
![vhd](https://github.com/user-attachments/assets/685714f1-425e-49f7-b895-93946a96a1cf)

**Comment by sreecharansai05** [comment]
@droshev I could still all to reproduce this issue . When we search anything and close the value-help dialog and open the value-help dialog without refreshing the page and click on search icon the previous search result is showing up.

https://github.com/user-attachments/assets/10b6ca06-96ea-44cd-9b0e-90f3d7f65e85

**Comment by mikerodonnell89** [comment]
@sreecharansai05 We've been advised against using tooltips as they are not touchscreen friendly. The sync button does have an associated aria-label so works with the screenreader
