### ISSUE TITLE
[BUG] Empty space when message-strip is dismissed in dynamic-page-subheader

### ISSUE THREAD

**Issue by karolgromacki** [SAP/fundamental-ngx#12411]
Is this a bug, enhancement, or feature request?
Bug

Describe your proposal.
In the [attached example](https://stackblitz.com/edit/temt94-sd6ata) when message-strip placed in dynamic-page-subheader is dismissed, the empty container remains, leaving space between the dynamic-page-header and the content below. 

**I also added toggle button to show expected behaviour.**

Can you handle that on the application side
No

Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Fundamental: v0.51
Angular: 18.0.3

If this is a bug, please provide steps for reproducing it; the exact components you are using;

components:
MessageStripComponent, DynamicPageModule

Steps to reproduce:

1. Open attached example of table.
2. Dismiss message strip disappear or wait 7 seconds until it's autoDismissed.
3. Observe that space reserved for message strip remained.

Expected behavior: 
After message strip is dismissed the message strip container should be removed from DOM if there are no elements in it.
Click on toggle button from provided example to see expected behaviour.

Please provide stackblitz example(s).
https://stackblitz.com/edit/temt94-sd6ata

Did you check the documentation and the API?
Yes

Did you search for similar issues?
Yes

**Comment by droshev** [comment]
@InnaAtanasova Can you investigate this issue?

**Comment by InnaAtanasova** [comment]
hi @karolgromacki , thanks for opening the issue. I provided a fix in this PR: https://github.com/SAP/fundamental-ngx/pull/12443
