### ISSUE TITLE
ComboboxModule not found

### ISSUE THREAD

**Issue by camilo2312** [SAP/fundamental-ngx#1243]
I am trying to implement this control (Combobx), but the module is not found

![Screenshot_2](https://user-images.githubusercontent.com/42982644/64563349-c0dc9900-d314-11e9-819a-7fa29b34d12c.png)

And not only that, but I also implement the combobox-input and it doesn't load the information

![image](https://user-images.githubusercontent.com/42982644/64563484-24ff5d00-d315-11e9-9d10-2dd36df1bab8.png)

![image](https://user-images.githubusercontent.com/42982644/64563519-39dbf080-d315-11e9-8379-b336c7c6a86c.png)

**Comment by droshev** [comment]
@camilo2312 Can you help us understand more your scenario?
I created a simple example here: https://stackblitz.com/edit/angular-jszvip
what i different in your case?

**Comment by camilo2312** [comment]
It is exactly the example you need, but how can I install this dependency?, To be able to import the Combobx module

**Comment by droshev** [comment]
@camilo2312 what are you missing?

**Comment by JKMarkowski** [comment]
Hi @camilo2312 , could you write what is your NGX version?

**Comment by droshev** [comment]
@camilo2312 It has been a while since the issue was opened. Feel free to re-open it if you still facing the same issue by providing more details.
