### ISSUE TITLE
Bug: fdp table Filter Dialog - List items don't change cursor to pointer on hover

### ISSUE THREAD

**Issue by do-oel** [SAP/fundamental-ngx#12447]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
In the filter dialog I am selecting the column to be filtered. When I hover over the list items, the list items change to their hover state. **The cursor should change to the pointer variant. Currently (only on the first level of the filter dialog), the cursor doesn't change to the pointer.**

https://github.com/user-attachments/assets/744a091a-97dc-455f-acd2-c0230276a319

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Latest
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://sap.github.io/fundamental-ngx/#/platform/table/basic#filterable

**Comment by droshev** [comment]
will be done as part of https://github.com/SAP/fundamental-ngx/issues/12441
