### ISSUE TITLE
[P2][Sourcing] Platform table switch focus with custom indicator

### ISSUE THREAD

**Issue by CSEHoangV** [SAP/fundamental-ngx#12450]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

When we use custom busy indicator through `[loading]="!!(loading | async)"` and we want to fetch the table, the content switch focus to different position (or table is scrolled). If we remove this, there is no issue.

https://github.com/user-attachments/assets/61b13582-a285-4c6f-b47d-3d78cbeafeb0

Expectation: when using [loading] and table is fetched, position should stay in place.

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15
0.43.43

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

- Create platform table using custom loading indicator input.
- Create a button to use fetch functionality from table and input `[loading]`.
- Scroll the table to certain position.
- Click to focus on certain cell.
- Trigger table fetch.

#### Please provide relevant source code (if applicable).

https://stackblitz.com/edit/angular-l9ndgq?file=src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/angular-l9ndgq?file=src%2Fapp%2Fplatform-table-virtual-scroll-example.component.html

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

#### Is there anything else we should know?

This is important for us to use custom indicator to control when to show indicator especially which we involve API call.

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
This doesn't have anything to do with the custom busy indicator (in the video below I've removed `[loading]="!!(loading | async)"` and you see the same behavior, it's not happening in your video after removing that line because your fetch does not shift the scroll position of the table). I've gone through some old messages with the UX and accessibility designers around the time we were working on #11491 and it is intentional to keep focus at the previously focused row/column index as the user scrolls the table or the table data changes via fetch, search, filter etc. This is done because it is important to keep focus on a cell within the visible pane of the table. However, on our implementation, it looks like this doesn't work in all cases, including: 
- when scrolling quickly with the scrollbar (rather than mousewheel or trackpad)
- within the first few rows of the table

I think it is a happy accident for us, that it is working as the designers intended in some cases - likely just a side effect of our virtual scrolling implementation

**Comment by CSEHoangV** [comment]
I found another workaround:
Instead of `[loading]="!!(loading | async)"`, I set `[loading]="((loading | async) === true) ? true : undefined"` and it seems working. The reason for the scroll is from:

<img width="2420" alt="Screenshot 2024-09-27 at 10 19 32 AM" src="https://github.com/user-attachments/assets/3038180f-4cbe-47d7-a1d9-92ca93c0884a">

When it gets the top from busy indicator rather than the table to do the scroll. It is not supposed to go there since there is a check in the table to do the focus only when `loadingState` is false, so the root cause comes the nullish check (??) from loading state:

```
get loadingState(): boolean {
        return (
            this.loading ??
            (this._dataSourceDirective._internalLoadingState ||
                this._dataSourceDirective._internalChildrenLoadingState ||
                this._dndLoadingState)
        );
    }
```

The ?? only checks null/undefined so if it has value (even false), it will not consider the second statement and return false. This check considers internal loading state but with `[loading]` it will change this.loading value from table `ngOnChanges` so it becomes problematic. Since the workaround works, I will close this. But if you have time please refine this logic.

**Comment by CSEHoangV** [comment]
The workaround is only reduce the timing this issue occurring but it is still triggered depending on when we start triggering busy indicator through the listener to execute refocus:

```
private _listenToLoadingAndRefocusCell(): void {
        this._subscriptions.add(
            this._tableService.tableLoading$.pipe(filter((loadingState) => !loadingState)).subscribe(() => {
                setTimeout(() => {
                    if (this._tableHeaderResizer.focusedCellPosition && this._focusableGrid) {
                        this._focusableGrid.focusCell(this._tableHeaderResizer.focusedCellPosition);
                    }
                });
            })
        );
    }
```
` this._focusableGrid.focusCell(this._tableHeaderResizer.focusedCellPosition);` should be run only when `loadingState` is false. However, since it is asynchronously run in `setTimeout`, there is a chance that `loadingState` is set to true (for example, from `[loading]` in this case while this got triggered by dataSource through fetch) and `scrollInToView` will get `top` from busy indicator and gave wrong position.
I think this should be addressed from library instead of workaround given random async run in this case and it is tedious for application to apply workaround and be mindful when to trigger `[loading]` or modify data source to prevent this issue.

I will provide a fix on this.
