### ISSUE TITLE
Add Translation Support for the "More" Button in Tabs

### ISSUE THREAD

**Issue by sunilb1295** [SAP/fundamental-ngx#12466]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Add Translation Support for the "More" Button in Tabs

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
**Angular 15**
**Ngx 0.43.21**

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
When the number of tabs increases / the screen size is changed / any `maxVisibleTabs` property is set in Tabs, the More Button is showed but its not translated poperly.
https://sap.github.io/fundamental-ngx/#/core/tabs#collapsible.

#### Please provide stackblitz example(s).
Images:
![image](https://github.com/user-attachments/assets/4373ecbc-7a8f-487e-9111-1c3a4629f9c4)

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
I checked in the version 0.43.45 the string has been translated. You can test it here https://ng-15-downport--fundamental-ngx.netlify.app/#/core/tabs#collapsible
