### ISSUE TITLE
Search Input Component in platform

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#1246]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Create an opinionated component for "Search Input" for the "platform" library.

The code should leverage the "ComboBoxComponent" from the "core" library, as it has 90% of the functionality needed.

Additional features which should be addressed in this component:
* Add "loading" state to inform user that a search initiated by component is in process
* Add "cancel" button in "loading" state, to allow user to trigger an event to interrupt search process
* Add "category" dropdown

**Loading State**
<img width="216" alt="Screen Shot 2019-08-27 at 6 41 17 AM" src="https://user-images.githubusercontent.com/48103491/64635966-8f67da00-d3b5-11e9-9e1c-72ee32896bd6.png">

**Cancel Button**
<img width="243" alt="Screen Shot 2019-08-27 at 6 41 27 AM" src="https://user-images.githubusercontent.com/48103491/64635989-9c84c900-d3b5-11e9-91a7-390c4fdd4283.png">
NOTE: The cancel button appears when the "loading state" spinner icon is hovered over.

**Category Dropdown**
<img width="214" alt="Screen Shot 2019-09-10 at 10 29 32 AM" src="https://user-images.githubusercontent.com/48103491/64636133-f08fad80-d3b5-11e9-8d11-14c0588c7793.png">

**Comment by KevinOkamoto** [comment]
The current `ComboboxComponent` handles user input via `[(ngModel)]` binding for input values, and via binding of a user function to the `searchFunction` attribute.

I would prefer if this newer `SearchInputComponent` would handle these interactions using emitted events. So the interface would look like:

```
<fd-search-input
    [placeholder]="'Search...'"
    [dropdownValues]="dropdownValues"
    (inputChange)="onInputChange($event)"
    (searchSubmit)="onSearchSubmit($event)">
</fd-search-input>
```
where `inputChange` would be emitted whenever there was an input text change, and `searchSubmit` would be emitted whenever the user selected an option from the dropdown list or hit the "enter" key.

**Comment by KevinOkamoto** [comment]
A fully-loaded `SearchInputComponent` will look like this:

```html
<fd-search-input
    [placeholder]="'Search...'"
    [dropdownValues]="dropdownValues"
    [categoryValues]="categoryValues"
    (inputChange)="onInputChange($event)"
    (searchSubmit)="onSearchSubmit($event)">
</fd-search-input>
```
where
* `placeholder` accepts a string
* `dropdownValues` accepts an array of strings
* `categoryValues` accepts an array of key/value string pairs
* `inputChange` emits an object whenever the input text changes or the category selection changes
* `searchSubmit` emits an object whenever a dropdown menu item is selected or the user hits the "enter" key

**Comment by KevinOkamoto** [comment]
The dropdown list is suppose to be a basic type-ahead suggestion feature. The current design docs from Fiori do not require any icons in the dropdown list. Right now I feel we should do the simplest design possible, as adding complexity will increase development time and the amount of testing we need to do.

The current `ComboboxComponent` in core has the `dropdownValues` (or `list`) as an array of strings. The easiest thing to do is to keep this signature. However perhaps we can change the `dropdownValues` or `list` to a more complex data type like:

```ts
export interface DropdownItem {
    value: string;
}

@Input() list: DropdownItem[];
```
so that in the future we can add additional data like `icon` if we need it.

**Comment by fkolar** [comment]
**1.** :  I hope we are still in the context of SearchInput the Dropwown they call select
**2**: Let's keep the same naming like this then, the same applies for events as well 
**3**: I just check and they already have basic support to work wiht more complex objects. 
      * DisplayFn
      * searchFn - just one they cann fn and another one they call Function but this is minor we will use FN. 


So then it could look like besides supporting all the featues from existing `core inputsearch` we will support more complex object as:

```html
<fdp-search-input
    [placeholder]="'Search...'"
    [dropdownValues]="dropdownValues"
    [displayFn]="labelFn"
    [searchFn]="lookupFn"
>
</fdp-search-input>
```

If we want to customize actual item template, we will use `<ng-template #item>`

**Comment by KevinOkamoto** [comment]
I disagree with having a `searchFn` passed into the component. I'd rather emit an event and have the application developer handle invocation of the search logic. To me it's better separation of concerns. 

```
<fdp-search-input
    [placeholder]="'Search...'"
    [dropdownValues]="dropdownValues"
    [displayFn]="labelFn"
    (searchSubmit)="lookupFn($event)"
>
</fdp-search-input>
```
As for the `displayFn`, I wasn't sure what the purpose of the function is here. Perhaps you can provide an example?

**Comment by fkolar** [comment]
We need to support at minimum the same set of features what `core` has, and enhance it. We shoudl start from there!

They are different approaches to the same problem: 

using `searchFn` that fundamentals is to trigger search function in autocomplete. For this there is no doubt. Emitting event or some `DataSource pattern` is better alternative

-> On enterprise level it might not be even enough emittign event we will have to use DataSources and emitting event will be as **secondary thing.**  But we will get there!

`using displayFn` -> is there to format / display complext object. 
 - > For this we can introduce custom stucture that application need to implement,  - programatic approach
  - The same should be achivable with custom template that woudl format the same. 

```html
<my-search [displayFN]="formatMyLabel" list=list>
```

```ts
ngInit()
   list.push(new Invoice('INV1', 'Suppler1', 'price',..))

formatMyLabel(item: invoice)
     return `${item.id} (${item.supplier}) `
```
Also I think is nessesary to support different formating option both for selected item and the one listed. 

How are we thinking in terms of Single Select / Multiselect ?

**Comment by KevinOkamoto** [comment]
For search input there is no "multiselect". The user just selects one type-ahead suggestion, which then invokes a search on the selected suggestion.
