### ISSUE TITLE
Button as Standalone component (instantiable)

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#1248]
#### Briefly describe your proposal.

In order to be able to effectively work with with the component and have the ability to instantiate them on the fly angular offers no other way than using components. With this in mind buttons need to be enhanced in such way that most of the things will be hidden for developer. 

The basic usage of this component with minimal setup need to represent the best practice to defined Fiori 3 design. 

To clarify this further, and to achieve the best DX (developer experience) we will start from the end, meaning we will try to craft here different signature of the component how it will be used and viewed by the end application developer, Later on, we will execute actual implementation.  

 - Use existing `@fundamental-ngx/core` button directive structure in order to create an instantiable component. 

**Signature Wikki:**
https://github.com/SAP/fundamental-ngx/wiki/Platform:-Button-Component-V1.0-Technical-Design

**Comment by fkolar** [comment]
What if we start with somethign like this:
> still working on proper prefixng so we dont colide with exisitng components under core

```html
<fd-button   [name]="'button'"  (action)="onClicked($event)" 
    [style]="'warning'" > ClickMe </aw-button>
```
Where both type and style needs to be typed. we could have different varion of this

```html
<fd-button   [name]="'button'"  (action)="onClicked($event)" 
   [size]="'small'"    [style]="'warning'" >ClickMe</aw-button>
```

Passing button label as content feels more natural, but can can also use binding


```html
<fd-button   [name]="'button'"  (action)="onClicked($event)"  label="Click me"
   [size]="'small'"    [style]="'warning'" ></aw-button>
```

**Comment by droshev** [comment]
@fkolar @sKudum We are changing the `button` from a `directive` to `component` - look at here https://github.com/SAP/fundamental-ngx/blob/42e9970357d81188e92228f2e59764dbbd2d25e2/libs/core/src/lib/button/button.component.ts#L11

**Comment by droshev** [comment]
`fdp-button` has been introduced
