### ISSUE TITLE
Colon attribute in Core Input Label produces whitespace before the colon

### ISSUE THREAD

**Issue by SomeKay** [SAP/fundamental-ngx#12490]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Describe your proposal.

Using the `colon` attribute in an Input Label, produces a colon which has a whitespace before and after and it should only have whitespace after the colon.

#### Can you handle that on the application side

No.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

All of them.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Use a label like this: `<label fd-form-label colon="true">My label</label>`

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/wfcaop?file=src%2Fapp%2Finput-example.component.html

#### Did you check the documentation and the API?

Yes.

#### Did you search for similar issues?

Yes (https://github.com/SAP/fundamental-ngx/issues?q=is%3Aissue+colon).

**Comment by littleamigo** [comment]
@droshev @SomeKay Can you re-open this issue because the fix is not really successful as the rendering looks quite broken since we use @fundamental-ngx v0.50.5:

**Comment by droshev** [comment]
@littleamigo @SomeKay can you check with one of the following versions: `0.50.6`, `0.51.6`, or `0.52.4`?

**Comment by littleamigo** [comment]
@droshev it is fixed with `0.50.7`
