### ISSUE TITLE
fd-token control with 'more' text translation not work

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#12529]
#### Is this a bug, enhancement, or feature request?
This is a bug

#### Describe your proposal.

fd-token control, its 'more' text is not translated in difference language. 

![image](https://github.com/user-attachments/assets/922b40bb-a822-43fc-b9e4-05bcecc593ee)

#### Can you handle that on the application side
We have not handle it in our application 

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.43.33

**Comment by droshev** [comment]
@truezn version `0.43.x` has been updated and in the latest `0.43.46` that is translated
