### ISSUE TITLE
date picker/calendar issue in months selected state

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#12522]
bug

there is a minor miss-alignment in the calendar in the month selector as reported [here](https://github.com/SAP/fundamental-ngx/pull/12341#pullrequestreview-2313161043)

Comment from Inna: The problem is caused by adding `fd-calendar__item--selected` class to `fd-calendar__my-item`, which is wrong. This changes the element height on selected state (the jumping), and also adds an additional outline. In selected mode the button should be in toggled state, not add an additional class. 
The specs:

<img width="819" alt="Screenshot 2024-10-07 at 11 59 49 AM" src="https://github.com/user-attachments/assets/55d22b0c-df06-40fd-9b61-cc367754d126">

Fund-styles (Months example): https://fundamental-styles.netlify.app/?path=/docs/sap-fiori-components-calendar--docs

**Comment by shawchandankumar** [comment]
@InnaAtanasova With `fd-button--toggled` class there is no border in the button

**Comment by InnaAtanasova** [comment]
> @InnaAtanasova With `fd-button--toggled` class there is no border in the button
> 
> <img alt="image" width="221" src="https://private-user-images.githubusercontent.com/74846322/374327278-07f265d0-1738-451c-86fa-ba265eefa8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTY3MDAsIm5iZiI6MTcyODM5NjQwMCwicGF0aCI6Ii83NDg0NjMyMi8zNzQzMjcyNzgtMDdmMjY1ZDAtMTczOC00NTFjLTg2ZmEtYmEyNjVlZWZhOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0MDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMTRhYzRiZDZlNmI2NWNhMDM0OTFjYTc5NGMxNGJiODk4MTUxNTE0OWI0ZDZmOGQzMzI3MzgwNjMyZjY4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jva2GfjZbElwwFWyX-xkKTrAFnYJFArYS2AZpjqQSB8">

hi @shawchandankumar , I see in the PR you created everything looks ok. Could you provide more info?
<img width="314" alt="Screenshot 2024-10-08 at 10 09 04 AM" src="https://github.com/user-attachments/assets/127e5129-f7fb-4f77-99cd-bedf7850ad57">
