### ISSUE TITLE
[Bug, Translation] fd-token control with 'more' text translation not work

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#12533]
#### Is this a bug, enhancement, or feature request?
This is a bug

#### Describe your proposal.
Hi 
I have updated the version to be 0.43.46. Which another closed issue https://github.com/SAP/fundamental-ngx/issues/12529, 

But I still got the same issue that, the "more" text is not translated as follow. 
<img width="1635" alt="image" src="https://github.com/user-attachments/assets/9443880f-e241-4b4c-883f-4c8fe78ae807">
Could you please help check again. 

#### Can you handle that on the application side
We have not handle it in our application 

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.43.46

**Comment by droshev** [comment]
@truezn this is a public repo and you should not upload internal screenshots or video. I have tested on 0.43.46 ([link](https://ng-15-downport--fundamental-ngx.netlify.app/#/core/multi-combobox)) and `more` is translated. I guess you are missing something in the application
![more-translation](https://github.com/user-attachments/assets/9bb1c088-e511-4b2f-af01-ba35017d15d0)


In case you have doubt you can create a stackblitz example to prove something is missing
