### ISSUE TITLE
[BUG] Theme is only partially applied

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#12534]
#### Is this a bug, enhancement, or feature request?

Probably a bug.

#### Describe your proposal.

In our app, we have two different themes Morning Horizon (Light) and Quartz Light. Sometimes it can happen that a theme is not fully applied. Unfortunately, I did not find a way to reproduce it in a certain way.

Screenshot I shows only the partially applied Morning Horizon (Light) theme. The color is not correct. The color of the Shellbar should be white and the icons inside the Shellbar should be black (see Screenshot II). Colorwise, it looks like Screenshot I has Quartz Light active but it is not if you compare it carefully with Screenshot III. The height of the Shellbar is different and also the icons inside the Shellbar are different. 

Screenshot I (Morning Horizon (Light) is only partially applied):

![Theming Bug III](https://github.com/user-attachments/assets/371e3683-65d6-4d88-95c5-5c92c0010749)

Screenshot II (Morning Horizon (Light) is fully applied):

![Morning Horizon (Light)](https://github.com/user-attachments/assets/be82a5b9-5e2f-44af-8c95-643af235e607)

Screenshot III (Quartz Light is fully applied):

![Quartz Light](https://github.com/user-attachments/assets/c09d0283-02d0-4dd7-a5ef-c9ca9a477031)

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 18 (18.2.3) and Fundamental Library 0.53.0

#### Is there anything else we should know?

When I was debugging, I figure out that the correct theme id was provided to the Fundamental Theming Service and also in the network tab I saw that the correct theme was loaded. There might be something wrong with the Fundamental Theming Service.

**Comment by droshev** [comment]
closing as there is no update. Feel free to open a new one with more details
