### ISSUE TITLE
[Translation] Invalid Date text in date picker is hard coded

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#12532]
#### Is this a bug, enhancement, or feature request?

In date pick, the showen text "Invalid Date" is not translated 
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/c24ca6b2-04cc-41c9-a3b4-cc3f6c6affd3">

Version: 0.43.46

**Comment by droshev** [comment]
@truezn you need to use the semantic messages(Reactive Form validation) and translate them with the proper message.
