### ISSUE TITLE
ID attributes from Settings Generator items not rendered, affecting e2e testability

### ISSUE THREAD

**Issue by CaiCharles01** [SAP/fundamental-ngx#12546]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
In the Settings Generator, you can specify an `id` in the configured `items`, for example, `id: 'userAccount'`. However, in the rendered webpage, it is not possible to find the specified `id` from `items` in either the `id` or `class` attribute of each `li` under `fdp-settings-generator__sidebar`. This makes it difficult to uniquely locate each setting in e2e tests. 
In a single language environment, elements can be located using the `title` attribute. However, in a multilingual environment, once switched from English to another language, the original locators become invalid.

Settings Generator documentation: [https://sap.github.io/fundamental-ngx/#/platform/settings-generator](https://sap.github.io/fundamental-ngx/#/platform/settings-generator)

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Current Version

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1. Configure `items` in Settings Generator with an `id`, e.g., `id: 'userAccount'`.
2. Render the Settings Generator in the application.
3. Inspect the `li` elements under `fdp-settings-generator__sidebar`.
4. Observe that the `id` from `items` is not found in the `id` or `class` attributes of the `li` elements.

#### Please provide relevant source code (if applicable).
N/A

#### Please provide stackblitz example(s).
N/A

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
N/A

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
N/A

**Comment by InnaAtanasova** [comment]
Hi @CaiCharles01 , I would need more information regarding this issue. 
List items, by default, generate default ids if an id is not provided. So each list item inside the Settings Generator has a unique id. Isn't this enough for testing purposes? 
![Screenshot 2024-10-16 at 2 16 33 PM](https://github.com/user-attachments/assets/d427f335-4722-41e5-99a7-cd2920a49ade)

**Comment by CaiCharles01** [comment]
When testing list elements, if using auto-generated IDs to locate elements, the corresponding IDs will also change when the order of elements changes. Custom IDs are more semantic, making it possible to directly identify which list item it is from the ID. In the Settings Generator, you provide the option to configure IDs, but it does not reflect in the rendered list element IDs, which is confusing.
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/68332773-1925-4ed4-83f8-f5ccd238787e">

**Comment by InnaAtanasova** [comment]
@CaiCharles01 , please let me know if this would work for you: https://github.com/SAP/fundamental-ngx/pull/12593

**Comment by CaiCharles01** [comment]
Hi @InnaAtanasova, that's what I expect, thanks for your help!
By the way, which type of fixes will be backported to previous version, like fundamental-ngx@0.50.3 which is compatible with angular@17?
