### ISSUE TITLE
[Translation] Invalid Date text in date picker is hard coded 

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#12549]
#### Is this a bug, enhancement, or feature request?
The original issue is https://github.com/SAP/fundamental-ngx/issues/12532 , due to it is closed, i have created new one. 
As the above issue mentioned, we should use the semantic messages(Reactive Form validation). 

But we just use fdp-date-picker, and its validation is controlled by control itself, we could not handle the logic of control itself. 
![图片](https://github.com/user-attachments/assets/6731ec6d-b97e-45b3-95de-2d4a58905a56)

Please help  recheck.

**Comment by droshev** [comment]
@truezn [here](https://fundamental-ngx.netlify.app/#/platform/message-popover#form-generator) is an example how you can control invalid message on fdp-datepicker
<img width="244" alt="Screenshot 2024-10-16 at 14 59 39" src="https://github.com/user-attachments/assets/53e6d0d9-a5c3-4e9d-a1d2-39a8ea8ab72b">
 (Message Popover with Form Generator component)
