### ISSUE TITLE
[Bug, Translation] fd-token control with 'more' text translation not work when change browser display language

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#12547]
#### Is this a bug, enhancement, or feature request?
fd-token control with 'more' text translation not work when switch the browser display language
Due to i could not reopen the below language, i have to create new one, the following is original one. 
https://github.com/SAP/fundamental-ngx/issues/12533

#### Describe your proposal.

In https://ng-15-downport--fundamental-ngx.netlify.app/#/core/multi-combobox, when you switch the different language in up right, it works. But for our end users, they mainly switch the browser display language, this is our use case. Our app use this control, and when switch different language, the fd-token 'more' text is still in English. 
Does your multiple languages have consider the browser language switch. Please help check.

**Comment by droshev** [comment]
@truezn if you want to link it with the browser then you would need to handle this on the application side.
