### ISSUE TITLE
[BUG] More button can't work as expected in fdp-icon-tab-bar

### ISSUE THREAD

**Issue by Mino-Chen-Sap** [SAP/fundamental-ngx#12554]
Angular version: 17.3.12
**Fundamental version: 0.50.3 & 0.49.2**

After More button is clicked, some items are not in the list, and sometimes, even the popover is not visible.
Please see the screenshot below, there are 10 items in all, but only 2 items display in the list. 
<img width="499" alt="image" src="https://github.com/user-attachments/assets/309b989e-5309-45d7-aee8-6bff04026bdf">

And I found that because other items are hidden. Why are they hidden?
<img width="504" alt="image" src="https://github.com/user-attachments/assets/5645cfdc-257e-490c-a663-95248d0dda6f">

Please fix from your side. And all the versions should be covered.

Note: It's an urgent bug from customer. Please take high priority to this issue.

You can easily reproduce it in stackblitz which is mentioned in the doc: https://docs-0-50--fundamental-ngx.netlify.app/#/platform/icon-tab-bar

**Comment by droshev** [comment]
@dpavlenishvili Can you check this issue and analyze the root cause?

**Comment by Mino-Chen-Sap** [comment]
@dpavlenishvili Hello, please also fix it on 0.50.3 and including versions after 0.50.3

**Comment by droshev** [comment]
the fix has been downported to [`0.50.4`](https://github.com/SAP/fundamental-ngx/releases/tag/v0.50.4), [`0.51.4`](https://github.com/SAP/fundamental-ngx/releases/tag/v0.51.4), [`0.52.2`](https://github.com/SAP/fundamental-ngx/releases/tag/v0.52.2)
