### ISSUE TITLE
[Accessibility: ACC-271.1] Date Picker: Focus overlapping the UI 

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12569]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
There should be strong and clear visible focus provided for all the UI elements without overlapping the focused element.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Date Picker](https://sap.github.io/fundamental-ngx/#/core/date-picker)
**Issue: **  Selected and focused indications on selected year within the date picker are overlapping each other.
<img width="506" alt="Screenshot 2024-10-17 at 2 57 28 PM" src="https://github.com/user-attachments/assets/d19cdd78-bf3b-4015-b5df-a2868ac7e324">

#### Please provide stackblitz example(s).
You can try ngx example, it is reproducible.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
already fixed - https://fundamental-ngx.netlify.app/#/core/date-picker
