### ISSUE TITLE
[BUG] Link in checkbox lable is not clickable

### ISSUE THREAD

**Issue by akatyabg** [SAP/fundamental-ngx#12577]
The links in a checkbox component cannot be opened (is not clickable).
The issue can be seen also in the documentation: https://sap.github.io/fundamental-ngx/#/core/checkbox#custom-label

To Reproduce

Go to [checkbox with custom label example](https://sap.github.io/fundamental-ngx/#/core/checkbox#custom-label)
Click on the link
The link doesn't open

**Comment by droshev** [comment]
@khotcholava Can you check this issue as it is important for one team? thanks
