### ISSUE TITLE
[Accessibility: ACC-255.1] Button: No text alternatives provided

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12573]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
For all non-text UI elements provided text alternatives should be meaningful and fulfil the purpose of the UI.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [VHD](https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog)
There is no text alternative provided for ‘Search Magnifier’ and ‘Synchronize’ buttons in search field and ‘Remove/Delete’ buttons in ‘Tokens’ within VHD.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/8c948ec1-d9ad-4253-a775-d3da334672d9">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
The deleting of the tokens through the keyboard is handled by deleting it with Delete on focus of the whole token instead.
