### ISSUE TITLE
[Accessibility: ACC-264.1] Button: Additional information read

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12574]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Additional information should be avoided.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [VHD](https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog)
To reproduce: Use VHD component and access through screen reader.
1. Additional information ‘ContentInfo Region’ is read on accessing ‘Clear/Remove’ button associated to ‘Selected Items and Conditions’ tokenizer text box
<img width="452" alt="image" src="https://github.com/user-attachments/assets/561d13f8-b8ea-4259-a599-5afe7591da77">

2. On accessing ‘Synchronize’ button and ‘Clear Conditions’ buttons within the same dialog, additional information ‘Create Report – Google Chrome dialog’ is read
<img width="452" alt="image" src="https://github.com/user-attachments/assets/dd471d57-03b0-4c16-8236-de2fdb82ff42">
<img width="452" alt="image" src="https://github.com/user-attachments/assets/c6b90ad4-ac21-4646-8e5b-c3cb655e4d54">
<img width="452" alt="image" src="https://github.com/user-attachments/assets/d91463da-ce98-4f1e-b700-63dc4c51ce84">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 you need to address those issues to the application owner, not to the library.
