### ISSUE TITLE
[Accessibility: ACC-255.1] Button: Incorrect text alternative provided

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12572]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
For all non-text UI elements provided text alternatives should be meaningful and fulfil the purpose of the UI.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All versions.

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Date Picker](https://sap.github.io/fundamental-ngx/#/core/date-picker)
‘Open Picker’ is incorrect text alternative provided for ‘Open Date Picker’ button.
<img width="1062" alt="Screenshot 2024-10-17 at 3 34 50 PM" src="https://github.com/user-attachments/assets/c0274b3b-381c-4dbe-adc1-cd88e4602e74">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
same as ui5 
<img width="2476" alt="Screenshot 2024-10-18 at 15 01 34" src="https://github.com/user-attachments/assets/8cf7d7ce-a9fa-4c93-8d8a-830296be3006">
