### ISSUE TITLE
[Accessibility: ACC-270.2] Button: Dynamically available UI elements are not placed appropriately

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12580]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
In VHD, Search button should be placed in such a way that user should not have to navigate backwards to submit the filter selection.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [VHD](https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog)
Users have to navigate backward once after entering the filter values to activate ‘Search’ button in VHD.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/c87c4288-1cb5-460d-bb9c-429441a29919">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 If you disagree with the design, then you should address this to the design department
