### ISSUE TITLE
[Accessibility: ACC-264.1] List Box: Expanded state information not read correctly.

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12585]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Expanded state should be read.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Components used:
1. [Multi Combobox](https://sap.github.io/fundamental-ngx/#/core/multi-combobox)
2. [Combobox](https://sap.github.io/fundamental-ngx/#/core/combobox)
On expanding all lists throughout the application, ‘ExtendedSelect List box’ is read instead of ‘List Expanded’.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/15cc36fb-0059-4a02-a657-5fca1c1d648e">
<img width="452" alt="image" src="https://github.com/user-attachments/assets/ffc50d9b-efad-462b-b354-1b52f2101f8e">
<img width="452" alt="image" src="https://github.com/user-attachments/assets/12843f25-d317-490a-823e-632c31bccbfe">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 the screenshot is from an application and i assume this is a result of the application usage of multi combobox as I am not able to reproduce it.
<img width="1262" alt="Screenshot 2024-10-18 at 16 20 22" src="https://github.com/user-attachments/assets/e3f2d018-e52d-4ac4-9708-e7edc1bf4eae">

If you can create an isolated stackblitz with the issue we can try to support you
