### ISSUE TITLE
File Uploader event emitters issue

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#12592]
#### Is this a bug, enhancement, or feature request?
Bug
#### Describe your proposal.
`selectedFilesChanged` and `selectedInvalidFiles` methods are being called continuously, which causes applications to freeze. 
Version "0.45.1" is the last one where the issue is not present.

**Comment by mikerodonnell89** [comment]
To give some further details, this happens when you have two file uploader components on the same page, and their `[(ngModel)]` refers to the same variable on the component
