### ISSUE TITLE
[Accessibility: ACC-271.2] Table: Focused UI element not in visible area at 200% zoom

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12590]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Focused UI elements should always be in visible area.
Whenever the user uses a keyboard (s)he needs to be in control of where the input happens and affects consequences. Therefore, the focus must always be in visible area and easy to find.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [VHD](https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog)
On navigating table columns using arrow keys focus is not in visible area in VHD on resizing the application to 200% zoom.
<img width="1065" alt="Screenshot 2024-10-17 at 6 52 34 PM" src="https://github.com/user-attachments/assets/48e80b6d-4432-43c7-95f1-b779c197e4d8">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
I was not able to reproduce it:
<img width="2905" alt="Screenshot 2024-10-18 at 12 02 37" src="https://github.com/user-attachments/assets/72cb8809-881a-43a0-9b83-519ce8856cab">
