### ISSUE TITLE
[Accessibility: ACC-264.1] Wizard: Info coneveyed twice

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12602]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
All the information must be conveyed only once to the user additional reading must be avoided.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Wizard Dialog](https://sap.github.io/fundamental-ngx/#/core/wizard)
The dialog header ‘Add applications and the step no ‘3’ is conveyed twice to the user in wizard.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/c775aa4b-4215-450e-9759-fe7be0f19683">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 the screenshot is from an application and this issue should be reported to them. I tested on our wizard and there is no repetition. 
<img width="1415" alt="Screenshot 2024-10-18 at 15 25 43" src="https://github.com/user-attachments/assets/dea10dd1-fcc7-449d-8f3b-58e159563693">
