### ISSUE TITLE
[Accessibility: ACC-264.1] List item: Filter conveyed twice

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12608]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Any information must be communicated only once to the user. Additional reading should be avoided.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Platform Table](https://sap.github.io/fundamental-ngx/#/platform/table/basic)
The list item ‘Filter’ available on activation of any columns header of a table the label is coneveyed twice.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/468ab269-4bc3-4945-bc3d-631811af7d76">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 I am not able to reproduce it
<img width="1208" alt="Screenshot 2024-10-18 at 16 17 41" src="https://github.com/user-attachments/assets/1c93f2ba-3740-41f4-8275-e5888f89a006">
