### ISSUE TITLE
[Accessibility: ACC-264.1] Message Box: Error message conveyed twice

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12601]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
All the information must be conveyed only once to the user and additional reading must be avoided.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Message Box](https://sap.github.io/fundamental-ngx/#/core/message-box)
When the error message dialog is displayed, this information is conveyed twice to the user.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/d653bdeb-a56c-4f62-b126-beeb05aeb7b3">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 i tried moving the focus on our datepicker and it doesn't stop to 2 elements.
![datepicker](https://github.com/user-attachments/assets/654340c7-386a-49b0-adf4-44438f211735)
Can you provide a stackblitz with the problem if you can reproduce it?

**Comment by droshev** [comment]
@divyamalhotra488 the screenshot is from an application. This should be addressed to the application. I tested on our side and everything seems ok:
<img width="894" alt="Screenshot 2024-10-18 at 14 46 43" src="https://github.com/user-attachments/assets/83441d2b-dc02-4564-bc3e-a23d327cb719">
