### ISSUE TITLE
[Accessibility: ACC-264.1] List box: List items mentioned thrice

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12610]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
All the information must be conveyed only once to the user and repeated reading must be avoided.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Select](https://sap.github.io/fundamental-ngx/#/core/select)
Within the select when user changes the list items with arrow keys the options are coneveyed thrice to the user.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/c116bfe0-e525-4a60-a213-729cfde7f2a7">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 I have tested our select with JAWS and I was not able to reproduce it:
<img width="603" alt="Screenshot 2024-10-18 at 16 31 07" src="https://github.com/user-attachments/assets/24bc0721-3835-48f4-94b2-a6e4d382cfb6">
