### ISSUE TITLE
[Accessibility: ACC-264.1] List item: SC silent when received focus

### ISSUE THREAD

**Issue by divyamalhotra488** [SAP/fundamental-ngx#12619]
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
All the relevant information about the UI should be communicated to the user when the UI receives focus.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
All

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used: [Platform Table Filter](https://sap.github.io/fundamental-ngx/#/platform/table/preserved-state)
When the list items within the ‘Filter’ dialog receives focus, screen reader is silent, and no information is coneveyed.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/22a9b344-925f-4ec6-86d9-49a229e5a216">

#### Please provide stackblitz example(s).
You can try ngx examples, issue is reproducible there.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
Yes, issue is raised by an accessibility expert.

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@divyamalhotra488 the screenshot is from an application and it should be addressed to them. On our filter dialog the focus is visible on the OK button
<img width="2436" alt="Screenshot 2024-10-18 at 15 30 17" src="https://github.com/user-attachments/assets/7f219238-d0f8-4fb7-a90d-f0edd06e7c07">
