### ISSUE TITLE
action bar as standalone instantiable component

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1262]
#### Briefly describe your proposal.

To improve developer expirience as well as to be able to instantiate action bar programatically, we need to wrap existing functionality with, styles, templates and make it standalong component. 

Some ideas:

It should represent the best practice usage of Fiori3 with the most basic component signature

```html
<afd-action-bar title="User profile details"
                showBackAction="true"
                description="This is some description" (onBack)="onBack($event)">
</afd-action-bar>
```

You should be able to provide a template for several areas custom header:
If we want to let user to have a freeddom if to use H1, H2,.., the best option is probably template

```html
<afd-action-bar title="User profile details" subTitle="Hello Welcome to Jungle"
                showBackAction="true"
                description="This is some description" (onBack)="onBack($event)">
    <ng-template #header>
           <h5>My Title           </h5>
    </ng-template>
</afd-action-bar>
```
But with this maybe we are forcing user to much to understand whta is inside and asking him to work directly with H tags. What if we let him pick from the predefined constants?

And its up to how its implemented inside. 
```html
<afd-action-bar title="User profile details"
                [titleSize]="'Large'"
                showBackAction="true"
                description="This is some description" (onBack)="onBack($event)">
</afd-action-bar>
```

I think the defaula behavior should have those 2 actions cancel/ Submit and user should be able to pass also label for them. As well as maybe introduce another binding to say if we are editing or not, so we can automatically show only one button or none. as we dont have to submit or save

We shoudl also introduce somethign like actionMode or ActionType :

```html
<afd-action-bar title="User profile details"   [titleSize]="'Large'"  [actionMode]="button|menu">
             
</afd-action-bar>
```

so we can turn button to menu items. Also have on top level ` output events`

```html
<afd-action-bar title="User profile details"   (onCancel)="action($event)"   (onSubmit)="action($event)" (onBack)="action($event)">
             
</afd-action-bar>
```

When working with action and since we need to be able to turn them automatically to menu, we should wrap them into component so its easier to work with them.

Then for custom set of actions we could do somethign like:
```html
<afd-action-bar title="User profile details"  [actionMode]="actionMode">
            <ng-template #actions>
                      <afd-page-action id="profile" label="Profile" (click)="$event" > </afd-page-action>
                      <afd-page-action id="profile" label="Profile" (click)="$event" > </afd-page-action>
                      <afd-page-action id="profile" label="Profile" (click)="$event" > </afd-page-action>
                      <afd-page-action id="profile" label="Profile" (click)="$event" > </afd-page-action>
            </ng-template>
</afd-action-bar>
```
Or in this case we dont need to worry about each individual click but the parent component, could automatically introspect all the events and intercept them and broadcast them for each used actions. 

```html
<afd-action-bar title="User profile details"  [actionMode]="actionMode" (onAction)="clicked($event)">
            <ng-template #actions>

```

Let's play with signature to get the feel if it make sense.

**Comment by JKMarkowski** [comment]
Hello @manu-kr, it will be included with self contained styles adoption.

**Comment by fkolar** [comment]
Sorry we should clarify better. We should not create just place holders ;-) Let me rewrite it a bit.

**Comment by droshev** [comment]
`fdp-action-bar` has been created
