### ISSUE TITLE
Custom color support for Fundamental components

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#12620]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Describe your proposal.
We are using some Fundamental components that are supporting color changes. The problem is that they are only supporting a set of colors. It is not possible to pass custom colors (hash color codes).

Use Case: the customers are able to define their own custom colors, which should be used by these components.

These are the components, where we need the custom color support:

1. https://sap.github.io/fundamental-ngx/#/core/facets
2. https://sap.github.io/fundamental-ngx/#/core/avatar#accent-colors
3. https://sap.github.io/fundamental-ngx/#/core/object-status

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Fundamental-NGX 0.53.x

**Comment by droshev** [comment]
@zaheral How would that work for different themes(especially when it comes to accessibility and contrast)?

**Comment by zaheral** [comment]
Hi @droshev, 
the idea is to have support for standard colors that support theming and accessibility like it is done today, but in addition having the possibility to pass custom colors that doesn't have support for theming and accessibility. 
When the user is choosing a custom color instead from the standard color palette, then he is getting a warning message that this color is not following the SAP Product Standards.
Today we have already the feature to let the customer choose a custom color. What we want now is to make use of the Fundamental components. But we can only do that when they deliver the custom color support.

**Comment by droshev** [comment]
@zaheral In that case maybe you can offer a custom theme instead. This way you know those colors will be applied only with this specific theme.
The problem with your request is that the same passed color value will be hardcoded for each other standard theme and this will most probably lead to accessibility issue. Let's take an example with the critical color. The value in all the themes are different:
- [Horizon Morning](https://github.com/SAP/theming-base-content/blob/92783723e3fe4c13d55924db62c9422e97fde545/content/Base/baseLib/sap_horizon/css_variables.css#L30) `#e76500`
- [Horizon Evening](https://github.com/SAP/theming-base-content/blob/92783723e3fe4c13d55924db62c9422e97fde545/content/Base/baseLib/sap_horizon_dark/css_variables.css#L30) `#ffdf72`
- [High Contrast](https://github.com/SAP/theming-base-content/blob/92783723e3fe4c13d55924db62c9422e97fde545/content/Base/baseLib/sap_horizon_hcb/css_variables.css#L30) `#ffab1d`
This make the contrast better for each theme.

**Comment by zaheral** [comment]
Hi droshev, thanks for the feedback. I was communication with my colleagues and we are going in a different direction now.
