### ISSUE TITLE
[UX QUESTION] search with spaces around doesn't work in fd-multi-input component

### ISSUE THREAD

**Issue by egorwow70** [SAP/fundamental-ngx#12635]
#### Is this a bug, enhancement, or feature request?

Hello, guys.

I have a UX question. Does a search with spaces around work in fd-multi-input component?

Because in Observable async example - https://sap.github.io/fundamental-ngx/#/core/multi-input#observable-async
I see that you used .trim() before sending request
![image](https://github.com/user-attachments/assets/f9e11db7-bb2d-401c-b088-2343f053a68b)

But it seems the control itself won't return a suggestion with spaces around

So "Apple" works

![image](https://github.com/user-attachments/assets/5bc0090a-32a7-4546-9cb8-d9260c80be09)

But " Apple" doesn't
![image](https://github.com/user-attachments/assets/5637586b-f1c8-4abb-b7ed-8d409c3ebeaf)

#### Describe your proposal.

I am not a UX expert, but does it make sense to even return suggestions if a search value is with spaces around (because a user by mistake can add them, but idk)

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

- "@angular/core": "18.0.3",
- "fundamental-styles": "0.38.0",
- "@sap-theming/theming-base-content": "11.18.0",
- "@fundamental-ngx/cdk": "0.53.0",
- "@fundamental-ngx/platform": "0.53.0",
- "@fundamental-ngx/core": "0.53.0",

**Comment by droshev** [comment]
@khotcholava Can you check and add support for text with empty characters matching?

**Comment by egorwow70** [comment]
@droshev  @khotcholava 

Also question guys, if we display objects in fd-multi-input component, is it possible to search by different fields?
Because now it seems we can search only by the value, that is displayed for each object entity.

But in our app we implemented a user search with fd-multi-input and we had a request to search by fullname, id, email. I didn't find the way to search by multiple fields, but I used a temporal hack - I display fullname and id together - `${fullname} (${id})`, but in this case we cannot add email to the string, because it becomes too huge

**Comment by droshev** [comment]
> uest to search by fullname, id, email. I didn't find the way to search by multiple fields, but I used a temporal hack - I display fullname and id together - valu

did you check the current API ?

**Comment by egorwow70** [comment]
> > uest to search by fullname, id, email. I didn't find the way to search by multiple fields, but I used a temporal hack - I display fullname and id together - valu
> 
> did you check the current API ?

Sorry, deno, my bad, I found it
![image](https://github.com/user-attachments/assets/bde20ff6-d6c3-4f0f-849a-8b0b3b6fb26f)

Also there is a documentation - https://sap.github.io/fundamental-ngx/#/core/multi-input#custom-filter
