### ISSUE TITLE
[P2][Sourcing][fd-combobox]The user cannot immediately delete the corresponding character in the input box

### ISSUE THREAD

**Issue by nancy07-f** [SAP/fundamental-ngx#12638]
#### Is this a bug, enhancement, or feature request?
a bug

#### Describe your proposal.
When there is too much data in the drop-down box, the corresponding characters in the input box cannot be deleted immediately by using the backspace button. 
for example:  we tries to delete the word 'each' in input box, but can only delete the 'ch', the rest of the word 'ea' takes a while to be erased.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
core/platform: 0.43.47

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
component: fd-combobox
 steps for reproducing:

https://github.com/user-attachments/assets/b9ee949d-aa0b-4349-9026-3e9c159c8a7d

#### Please provide relevant source code (if applicable).
Refer to stackblitz example

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/uktomz?file=src%2Fapp%2Fcombobox-includes-example.component.ts,src%2Fapp%2Fcombobox-includes-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.
N/A
#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
This is a performance issue. If you are anticipating having that many potential options in the combobox, you'll want to use an observable to load items, see this example here: https://fundamental-ngx.netlify.app/#/core/combobox#observable-async

**Comment by nancy07-f** [comment]
Hi @mikerodonnell89, I tried the method before, it doesn't work. please refer to the recording:

https://github.com/user-attachments/assets/c078f3a5-7de2-45cf-988e-5c6ea5deebda

**Comment by nancy07-f** [comment]
stackblitz example : https://stackblitz.com/edit/q7pfm6?file=src%2Fapp%2Fcombobox-async-example.component.ts,src%2Fapp%2Fcombobox-async-example.component.html

**Comment by mikerodonnell89** [comment]
> stackblitz example : https://stackblitz.com/edit/q7pfm6?file=src%2Fapp%2Fcombobox-async-example.component.ts,src%2Fapp%2Fcombobox-async-example.component.html

You are still loading all 1500 items in the combobox at once, which is causing this performance issue. Any change of the combobox input will run a comparison for every item loaded into the combobox. You need to implement some logic to avoid loading all items from your collection into the combobox at once, and one way we recommend dealing with this is by using observables to handle fetching the data based on the input

**Comment by droshev** [comment]
@nancy07-f check the [guidelines](https://experience.sap.com/internal/fiori-design-web/combo-box-web-component/#when-to-use). If you have more than 200 items you should consider using either select or value-help dialog.

**Comment by nancy07-f** [comment]
> Hi @mikerodonnell89, I tried the method before, it doesn't work. please refer to the recording:
> 
>  Screen.Recording.2024-10-24.at.22.13.05.mov

@mikerodonnell89 previous recording is wrong, so I updated it. FYI

**Comment by nancy07-f** [comment]
> > stackblitz example : https://stackblitz.com/edit/q7pfm6?file=src%2Fapp%2Fcombobox-async-example.component.ts,src%2Fapp%2Fcombobox-async-example.component.html
> 
> You are still loading all 1500 items in the combobox at once, which is causing this performance issue. Any change of the combobox input will run a comparison for every item loaded into the combobox. You need to implement some logic to avoid loading all items from your collection into the combobox at once, and one way we recommend dealing with this is by using observables to handle fetching the data based on the input

thanks Mike, we need to display all list of item when user clicking on arrow button, and for any change of the combobox input, I think this behavior should be related to the filtering method in fd-combobox.

**Comment by droshev** [comment]
> > @nancy07-f check the [guidelines](https://experience.sap.com/internal/fiori-design-web/combo-box-web-component/#when-to-use). If you have more than 200 items you should consider using either select or value-help dialog.
> 
> thanks @droshev, but select not support text input, right?

?

**Comment by nancy07-f** [comment]
> > > @nancy07-f check the [guidelines](https://experience.sap.com/internal/fiori-design-web/combo-box-web-component/#when-to-use). If you have more than 200 items you should consider using either select or value-help dialog.
> > 
> > 
> > thanks @droshev, but select not support text input, right?
> 
> ?

I mean, you suggest we can use select or value-help dialog, but for select, we cannot enter text to filter from the list. we will 
allow user to enter value, so maybe for 'select', we can't use it. and for value-help dialog, can you provide the related link? thanks.

**Comment by droshev** [comment]
https://fundamental-ngx.netlify.app/#/platform/value-help-dialog
