### ISSUE TITLE
Platform-Table grouping spanning  by using  semanticHighlighting property and group property at the same time.

### ISSUE THREAD

**Issue by Meggie886** [SAP/fundamental-ngx#12677]
#### Is this a bug, enhancement, or feature request?
Yes 

#### Describe your proposal.
Fix the bug

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
all the versions
#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1.  Use fdp-table
2.  Use semanticHighlighting property and group property at the same time.
3. Use rowNavigatable property and group propert

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
![image](https://github.com/user-attachments/assets/381fc0cd-f529-4c43-a442-8c246f1dc7c1)
![image](https://github.com/user-attachments/assets/a4ebe51b-69c4-453a-ad16-5a23de58380f)

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by khotcholava** [comment]
@Meggie886 Can you please provide stackblitz example? I cant open the screenshots and cant see the code.

**Comment by khotcholava** [comment]
@Meggie886 

I can't reproduce that issue on my end. Could you provide a StackBlitz example where the issue occurs?
![Image](https://github.com/user-attachments/assets/31321b78-7ccb-492d-b957-73ab12d50dc7)

![Image](https://github.com/user-attachments/assets/aec5194b-0de1-4779-adfe-d59ed5f744ab)
