### ISSUE TITLE
Creating new diff types of DropDown Button types

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#1268]
#### Is this a bug, enhancement, or feature request?
enhancement 

**Briefly describe your proposal.**

in order to implement the different types of button types need make code change in such a way that it should be a minimal code change and need to allow the user to create a DropDown button in a configurable manner which allows the user to work effectively and easy development of the application

**Comment by fkolar** [comment]
What is diff types ?

**Comment by Lokanathan-k** [comment]
[cid:image001.png@01D56C7E.2F0ABE50]


With Regards,
Lokanathan K
