### ISSUE TITLE
Dropdown: Maximum width and truncation

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#1269]
Is this a bug, enhancement, or feature request?
Enhancement

 **Briefly describe your proposal.**
If no fixed width is set, the width of the button is set automatically, depending on the text and the container. The maximum width of the dropdown button is 12 rem (192 px).

If the label exceeds the maximum width or the set fixed width, use an ellipsis to indicate that there's overflow text.

Since there is no text box area to display the selected text value need to introduce the text value in the DropDown component

**Comment by fkolar** [comment]
Let's finish this one..
