### ISSUE TITLE
[P2][Sourcing] Confusing UI on p13 dialog when reordering columns

### ISSUE THREAD

**Issue by CSEHoangV** [SAP/fundamental-ngx#12737]
#### Is this a bug, enhancement, or feature request?

bug

#### Describe your proposal.

Our user reports that bulk column reorder is not working because they think it is supported based on current design. When they select multiple rows, reordering only moves one row:

https://github.com/user-attachments/assets/a4b0f3bd-bdf1-440a-b629-534dba897e16

However, based on both f-ngx and UI5 samples, this bulk reorder functionality is not supported. From UI5, it is more intuitive when these reorder buttons are displayed on each row instead of the header.

https://github.com/user-attachments/assets/a51fdf6e-19b0-45a2-b258-91e8525bc8e1

I saw we already had the fix on the main branch: https://github.com/SAP/fundamental-ngx/pull/12300. Can we have a ng15 downport for this?

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular 15
0.43.47

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Open p13 dialog from ng15 playground
Check multiple rows
Move row up/down.

#### Please provide stackblitz example(s).

https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/p13-dialog-table

#### Did you search for similar issues?

https://github.com/SAP/fundamental-ngx/issues/12175

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment]
Given the user is able to reorder the columns on ng15 and this is more of a visual change, I'm sorry to say that we won't be downporting this to ng15
