### ISSUE TITLE
Using Datetime Picker with only keyboard does not work properly

### ISSUE THREAD

**Issue by esporysz** [SAP/fundamental-ngx#12769]
#### Is this a bug, enhancement, or feature request?

bug

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

angular: 18.2.4
fundamental: 0.53.1-rc.23

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Try to pick date and time using only keyboard. Currently it is not possible. It can be experienced also on  [documentation page](https://sap.github.io/fundamental-ngx/#/core/datetime-picker). 

It should be possible to pick date and time using only keyboard.

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations.

Accessibility expert confirms it should be possible to pick date and time using only keyboard.

**Comment by droshev** [comment]
@esporysz F4 opens the datepicker and then with the focus, arrows, and space you should be able to change date/time
