### ISSUE TITLE
IllustrationMessage not working inside fdp-table-no-data-wrapper

### ISSUE THREAD

**Issue by pawelkarwat** [SAP/fundamental-ngx#12764]
#### Is this a bug, enhancement, or feature request?
This is a bug

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

0.53.1

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

1. Create the platform table.
2. Add the fd-illustrated-message to the fdp-table-no-data-wrapper component.
3. Try to search for an item that does not exist.

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/q5nhyp-eupezt?file=src%2Fapp%2Fplatform-table-tree-example.component.html,src%2Fapp%2Fplatform-table-tree-example.component.ts,package.json,src%2Fapp%2FillustratedMessage%2Fillustrated-message-example.component.html,src%2Fassets%2Fimages%2FsapIllus-Dialog-NoMail.svg,src%2Fassets%2Fimages%2FsapIllus-Scene-NoMail.svg,src%2Fapp%2FillustratedMessage%2Fillustrated-message-example.component.ts

#### Did you check the documentation and the API?

Yes

#### Did you search for similar issues?

Yes

**Comment by droshev** [comment]
@pawelkarwat you can follow the duplicate [issue](https://github.com/SAP/fundamental-ngx/issues/12678)
