### ISSUE TITLE
ModalRef NullInjectorError

### ISSUE THREAD

**Issue by camilo2312** [SAP/fundamental-ngx#1278]
Hello everyone

I am trying to make a modal in modal, but when I try to import the "ModalRef" and then inject it into the component, I receive this error

![image](https://user-images.githubusercontent.com/42982644/65169628-8bb70180-da0c-11e9-8234-deab082d2995.png)

Could you help me I can't find a solution

**Comment by fkolar** [comment]
It is missing a servive, you are asking for a service but the service is not probably injected for current context.

**Comment by camilo2312** [comment]
What service do I need?

**Comment by fkolar** [comment]
Anyway Can you put in here more context, e.g. how your component secondmodal looks like? Are you injecting some service into it ?

**Comment by camilo2312** [comment]
This is how my component looks

![image](https://user-images.githubusercontent.com/42982644/65170705-d33e8d00-da0e-11e9-9eac-c0b4000166fa.png)

**Comment by camilo2312** [comment]
And this is my HTML

![image](https://user-images.githubusercontent.com/42982644/65170868-329c9d00-da0f-11e9-80e1-83805ac2bf67.png)

**Comment by fkolar** [comment]
In angular, when you try to Inject any service and you do inject `ModalRef`here  it try to lookup available provider that is injected for current root of components and thsi error just means that nobody provides Modalref as provider either on the module level or component level.

For more please see: https://angular.io/guide/dependency-injection

So question we need to ask: 
Is `Modalref`really a service if so when where we inject a provider for it ? If not you should not be using this in the constructor

**Comment by fkolar** [comment]
If you try to follow this example https://sap.github.io/fundamental-ngx/modal
Where you have actual contructor with this ModalRef, then Definitelly somebody like this service needs to provide this reference. and bind it to the component it it creates a instance. 

So you will not be able to use this component on its own and when you let angular to instantiate this then you get this error, If you use this component as `custom template ` to the ModalService it should work.

**Comment by camilo2312** [comment]
This Modal service is referred as a provider in my App.module.ts and I get the following error

![image](https://user-images.githubusercontent.com/42982644/65251631-43a3e780-dabd-11e9-9cc8-3f5e68af62c0.png)

**Comment by camilo2312** [comment]
This Modal service is referred as a provider in my App.module.ts and I get the following error

![image](https://user-images.githubusercontent.com/42982644/65251706-6c2be180-dabd-11e9-94c2-3f99117d2cac.png)

then i add the DynamicComponentService  but i get the following error:

![image](https://user-images.githubusercontent.com/42982644/65251813-97aecc00-dabd-11e9-8638-21bfd072c3e8.png)

![image](https://user-images.githubusercontent.com/42982644/65251864-aac19c00-dabd-11e9-8ac0-26ffb86ee7fc.png)

**Comment by droshev** [comment]
@camilo2312 is this https://stackblitz.com/edit/angular-tacyfa what you are trying to create?

**Comment by camilo2312** [comment]
What module should install here?

FundamentalNgxCoreModule o FundamentalNgxModule

**Comment by Ynhockey** [comment]
Having the same issue. I tried following this example as closely as possible for my (different) use case: https://stackblitz.com/edit/angular-tacyfa

However, it also complains about no provider for DynamicComponentService, and when it's injected, says that the module cannot be found (exactly like in the above post: https://github.com/SAP/fundamental-ngx/issues/1278#issuecomment-533149767).

It could be a case of not installing Fundamental NGX correctly, but I followed the instructions given here: https://sap.github.io/fundamental-ngx/#/core/home

Angular version: 8.2.7
