### ISSUE TITLE
Combobox performance issue: slow response with large sets of grouped data

### ISSUE THREAD

**Issue by Tomashow** [SAP/fundamental-ngx#12781]
#### Is this a bug, enhancement, or feature request?
BUG

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
''@angular/core": "18.0.3"
"fundamental-styles": "0.38.0",
"@sap-theming/theming-base-content": "^11.18.1",
"@fundamental-ngx/cdk": "0.53.1",
"@fundamental-ngx/core": "0.53.1",
"@fundamental-ngx/platform": "0.53.1",

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
1)Open the StackBlitz example: https://stackblitz.com/edit/nytpv8-vxhadw
2)Select any value from the ComboBox.
3)Delete some letters from the ComboBox.
4)The ComboBox freezes for 1-2 seconds.

#### Please provide stackblitz example(s).
Stackblitz - https://stackblitz.com/edit/nytpv8-vxhadw

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
Maybe can brconnecteed with this issue - https://github.com/SAP/fundamental-ngx/issues/12518

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment]
@Tomashow the combobox is not meant to be used for examples with large data ([link](https://experience.sap.com/internal/fiori-design-web/combo-box/)) if you have such examples then the guidelines recommends to use Select or Value Help Dialog
