### ISSUE TITLE
ComboBox - Able to type arbitrary text into field which does not clear 

### ISSUE THREAD

**Issue by damien-murphy** [SAP/fundamental-ngx#1279]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
ComboBox can be used as a text box. Anything can be typed into it and it gets marked as valid. 

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
0.9.3

#### If this is a bug, please provide steps for reproducing it.

![image](https://user-images.githubusercontent.com/12972366/65183953-5fee4880-da19-11e9-8eaa-723a840c39ec.png)

#### Is there anything else we should know?

Ideally when focus is lost the contents of the field would be removed

Alternatively the component state would not display the typed text in the backing model and only selected items would show in the components state

**Comment by JKMarkowski** [comment]
Hello @damien-murphy, On 0.12.0 Version we introduced some options to combobox. You can check the example of controlling the open state in combobox [here](https://sap.github.io/fundamental-ngx/#/core/combobox).  Is it what you wanted to achieve ?

**Comment by damien-murphy** [comment]
@JKMarkowski  In the docs it is missing the combobox

![image](https://user-images.githubusercontent.com/12972366/67600359-dc65fc80-f726-11e9-9c1e-6cc87bf31612.png)

**Comment by JKMarkowski** [comment]
Hi @damien-murphy, sorry for issues. Please go [here](https://deploy-preview-1493--fundamental-ngx.netlify.com/#/core/combobox#open-control) To see working example.
