### ISSUE TITLE
[Bug] Side Navigation: Long side nav item text looks out of alignment

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1280]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In case the side nav item text is long, the text might not be aligned: 

Doesn't look fine:

![image](https://user-images.githubusercontent.com/51904901/65242552-96de6000-dae6-11e9-98be-dac1651bf5b8.png)

Looks fine:

![image](https://user-images.githubusercontent.com/51904901/65242583-ad84b700-dae6-11e9-9dac-712113869c22.png)

In both cases it is the same entry but the language is different. I assume that in the second screen there is more space between the text and the symbol (which hides/shows the second level nav items) because the word 'Wissendatenbank' is longer and therefore the line break is earlier. My expectation would be that there is always a minimum space between the text and the symbol.

**Comment by droshev** [comment]
@kistll We are waiting for the the latest design of the side navigation in order to implement it. It should happen any time soon

**Comment by droshev** [comment]
@zaheral @kistll check the latest version here https://fundamental-ngx.netlify.com/#/core/sideNavigation
