### ISSUE TITLE
Migrating to Angular 8

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#1281]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
We need to migrate `fundamental-ngx` library to angular 8.2.x. There will be listed some issues, caused during this migration.

**Comment by fkolar** [comment]
It will be mostly smooth. There might a few issues running command ng update that will try to force to version 9, but if you specify purelly version 8 we shoudl be ok.

**Comment by fkolar** [comment]
in case u wil run into the same issue, then it just run this specific command;

`ng update @angular/cli@8 @angular/core@8` instead of the generic one:
`ng update @angular/cli @angular/core` 

I will try to update to version 9 as I would like to test this with Ivy

**Comment by JKMarkowski** [comment]
I just noticed that, some of libraries are no longer supported and won't be working with IVY. So I need to replace them in scope of this issue.

**Comment by fkolar** [comment]
What libraries, what features are you refering to? There is breaking change as they now need to provide additional a flag for each View query, to tell if this needs to executed in ngInit or ngAfter... 

but the rest shoudl be ok.

**Comment by JKMarkowski** [comment]
The libraries that are used on docs page.

**Comment by fkolar** [comment]
If you find some issues, then please let me I know we will log issue on angular and I send message directly to Angular Team, as they are asking me to test migration to 9.

**Comment by JKMarkowski** [comment]
`ngx-highlight.js` package had to be removed.
