### ISSUE TITLE
Token closes when clicking outside label

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#1300]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 8, Fundamental 0.10.2

#### If this is a bug, please provide steps for reproducing it.

- go to docs for token: https://sap.github.io/fundamental-ngx/token
- click on the Closeable token, a bit left from its label
- it will close

It should not close unless you click directly on the X button 

![fundamental-token](https://user-images.githubusercontent.com/5263214/65510936-4f851480-ded6-11e9-8280-e4845a888931.gif)

**Comment by JKMarkowski** [comment]
Hi @mpienkowski I took a look on, it's strongly related to the fact, that `x` icon is in `pseudo element`. We check if the click was inside `<span>` element.
There is related issue:
https://github.com/SAP/fundamental-styles/issues/143

**Comment by JKMarkowski** [comment]
I will add some temporary solution.
