### ISSUE TITLE
Docs: New structure for documentaion

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#1302]
#### Is this a bug, enhancement, or feature request?

# enhancement

#### Briefly describe your proposal.

Since we have two different libraries `core` and `platform` we need to also update our existing `docs-app` to be aligned with this addition. 

New `docs-app`  should have main landing page discussing project itsef and some intro to fundamentals family and then main side bar navigatoin should capture new structure:

- Introduction
- Getting Started
- Modules (libraries) 
   - here you can jump to specific landing page of the library
- Receipts
   - how tos
- FAQs
...

It should have more generics topics e.g.:: 

<img width="1214" alt="Screen Shot 2019-09-24 at 7 10 02 PM" src="https://user-images.githubusercontent.com/17149942/65534582-119ce600-df00-11e9-9675-2840d3ab2469.png">

Plus the top left branding should capture where we are (core/platform)..
Also main `README.md` file should be updated with new section that talks about some high level information

**Comment by fkolar** [comment]
Adding more folks for ideas: @droshev, @KevinOkamoto, @JKMarkowski, @InnaAtanasova

**Comment by JKMarkowski** [comment]
I think we should change `Modules` to `Libraries`. Anyway, maybe on landing page we should have 2 big screens 50/50 split with some graphic. Each of parts will shortly describe the platform/core and after redirection it should be site dedicated only for core/platform. It can be switcher somewhere on the header with `Visit Platform/Core Site` link.

**Comment by fkolar** [comment]
Cool. yeah I mean Libraries too, as I was copying in the html inspector and changing things I left this one. 

But the landing page shoudl be more usable like other have, with some FAQ, fundamentals,  How receipts , etc..

**Comment by droshev** [comment]
implemented
