### ISSUE TITLE
Fix: Reuse fdp-button component inside fdp-action-bar

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1308]
#### Is this a bug, enhancement, or feature request?
 Enhancement

#### Briefly describe your proposal.
Once the button componet development is completed , We have to reuse the button componet inside action bar. Currently action bar  action button implemented using the button directives from the fundamental-ngx/core library.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 7

**Comment by droshev** [comment]
done
