### ISSUE TITLE
header links on the docs aren't working

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1310]
#### Is this a bug, enhancement, or feature request?
bug

go to any component documentation page and click on any header
![broken-link](https://user-images.githubusercontent.com/4380815/65618315-17400d80-df8c-11e9-85c3-7398f99dc96f.gif)

**Comment by JKMarkowski** [comment]
Let's have a talk about it on today's grooming. We got to think about it and prepare urls for platform library

**Comment by fkolar** [comment]
What is the issue? The routing stopped working?

**Comment by stefanoScalzo** [comment]
@fkolar The links applied with github have an extra part added to the url being /fundamental-ngx/ whereas the local host didn't!
@JKMarkowski sure!

**Comment by fkolar** [comment]
Is this related to` <base href="/"` ?

**Comment by stefanoScalzo** [comment]
> Isnt this related to` <base href="/"` ?

Yes and no because that's not the actual base since github is prefixing it with fundamental-ngx/

**Comment by fkolar** [comment]
Exactly when github is prefixing all we usually set base href to to root which in this case `fundamental-ngx`

**Comment by stefanoScalzo** [comment]
> Isnt this related to` <base href="/"` ?

There were different ways to do it, but yes that is the most simplest
