### ISSUE TITLE
Fix: Reuse fdp-menu component inside fdp-action-bar

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1318]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.
Once the menu componet development is completed , We have to reuse the menu componet inside action bar. Currently action bar action menu implemented using the fd-menu directives from the fundamental-ngx/core library.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 7

**Comment by droshev** [comment]
fixed
