### ISSUE TITLE
 Multi Input has no complete border when hovering the pointer over the button

### ISSUE THREAD

**Issue by yingzhou03** [SAP/fundamental-ngx#1319]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
`Multi Input` has no complete border when hovering the pointer over the button
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
The current version
#### If this is a bug, please provide steps for reproducing it.
This bug can be reproduced in https://sap.github.io/fundamental-ngx/multi-input. Please refer to the following screenshot for the detail.
![Screen Shot 2019-09-27 at 11 38 57 AM](https://user-images.githubusercontent.com/53583995/65793763-73856780-e11b-11e9-84c3-3a1f7b88e22c.png)

#### Is there anything else we should know?
Firefox and Chrome have this issue. Safari doesn't have.

**Comment by harikusumba** [comment]
Ying, try adding color for `border-top` and `border-bottom`

**Comment by droshev** [comment]
fixed
