### ISSUE TITLE
Review main README.md files

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1320]
We decided to create 2 packages in the repository `fundamental-ngx` so we would need to split and re-organize our `README.md` files.
The proposal:
- [ ] `README.md`
keeps the content related to both libraries; general information about the repository and contribution and adds links to the other 2 files
- [ ] `/libs/core/README.md`
contains information related to the package `@fundamental-ngx/core` - how to consume and how to contribute. This one gets published for npm package `@fundamental-ngx/core`
- [ ] `/libs/platform/README.md`
contains information related to the package `@fundamental-ngx/platform` - how to consume and how to contribute. This one gets published for npm package `@fundamental-ngx/platform`

**Comment by JKMarkowski** [comment]
I added and copy pasted some information into Core lib README.md and changed a little infor on main README.md. It would be great if everyone can take a look on it
