### ISSUE TITLE
"/node_modules/@fundamental-ngx/core/fundamental-ngx-core"' has no exported member 'FundamentalNgxModule'

### ISSUE THREAD

**Issue by GarrusNapp** [SAP/fundamental-ngx#1324]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 7.3.9
@fundamental-ngx/core@0.12.0-rc.0

#### If this is a bug, please provide steps for reproducing it.

 `@fundamental-ngx/core/fundamental-ngx-core"' has no exported member 'FundamentalNgxModule'`

Hello, I have a problem installing fundamental-ngx, I'm new to Angular so maybe I'm doing something wrong.

At first I tried `ng add fundamental-ngx` which worked, but I had Angular 8, and fundamental-ngx required peer Angular 7, so I've uninstalled CLI and installed older one (7.3.9).

Now `ng add fundamental-ngx` works but displays `The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.` 

I've also used [Full Installation Guide](https://github.com/SAP/fundamental-ngx/wiki/Full-Installation-Guide) but to no avail:

This is my `app.module.ts`
```import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { FundamentalNgxModule } from "@fundamental-ngx/core";
import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, AppRoutingModule, FundamentalNgxModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by JKMarkowski** [comment]
Hi @GarrusNapp, there is big difference between `fundamental-ngx` and `@fundamental-ngx/core`. We are about to push angular 8 migration. Let's try to go to angular 8 and add our lib by `ng add @fundamental-ngx/core`

**Comment by GarrusNapp** [comment]
@JKMarkowski Hello, I've double checked and `ng add @fundamental-ngx/core` while using angular 8 cli does not work - the error in my IDE while importing module into `app.module.ts` is the same:

```Module '"../../../../../../Users/user/Desktop/ng-fiori/node_modules/@fundamental-ngx/core/fundamental-ngx-core"' has no exported member 'FundamentalNgxModule'.ts(2305)```

Following warns are displayed when adding, which led me to believe that I should degrade angular to v. 7, but that doesn't work as well:
```npm WARN @fundamental-ngx/core@0.12.0-rc.0 requires a peer of @angular/common@^7.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN @fundamental-ngx/core@0.12.0-rc.0 requires a peer of @angular/core@^7.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN @fundamental-ngx/core@0.12.0-rc.0 requires a peer of @angular/forms@^7.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN @fundamental-ngx/core@0.12.0-rc.0 requires a peer of @angular/animations@^7.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN @fundamental-ngx/core@0.12.0-rc.0 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.``

**Comment by fkolar** [comment]
do we have already published NG 8 version ? 
Right now it works againts what is on master which example this version. So there is a pear dependency that specify examples these versins of angular. This is correct behaivor. I think the module is called `FundamentalNgxCoreModule `

**Comment by GarrusNapp** [comment]
Hello @fkolar, Thank you -  `FundamentalNgxCoreModule` appears to be correct module name - the error disappeared. 
Please note that README.md states other name: 

```import { FundamentalNgxModule } from '@fundamental-ngx/core';

@NgModule({
    ...
    imports: [FundamentalNgxModule],
})
export class DemoModule { }```

**Comment by fkolar** [comment]
I know. There is already issue created for this #1320 , #1321 , #1322
