### ISSUE TITLE
Review self-contained adoption for issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1326]
1. *Combobox* - I am able to open/close the menu by clicking outside of the element.       **FIXED**
2. *Identifier* - the accent colors are missing       **FIXED**
![Screen Shot 2019-09-30 at 3 45 48 PM](https://user-images.githubusercontent.com/39598672/65910832-77262200-e399-11e9-9a3a-1bb31c5bbb7a.png)

3. *Localization editor* is broken (**the break is coming from Fundamental-styles**)
<img width="516" alt="Screen Shot 2019-09-30 at 3 32 43 PM" src="https://user-images.githubusercontent.com/39598672/65910865-8c9b4c00-e399-11e9-9c89-20bb61b080d2.png">

4. *Menu with Addon* - when you hover over the element, the test area gets hover background but not the addon (the icon) (**the break is coming from Fundamental-styles**)
![Screen Shot 2019-09-30 at 3 33 21 PM](https://user-images.githubusercontent.com/39598672/65910945-be141780-e399-11e9-8da8-b68f4c4f5daa.png)

5. *Multi Input* - the control element is not taking 100% width. The cursor changes to pointer when you are close to the control element.       **FIXED**

6. *Multi Input* - the `disabled` state is broken. I can still click on the button (the button is active and if you inspect the DOM it triggers an action) - (**the break is coming from Fundamental-styles**)

![Screen Shot 2019-09-30 at 3 34 33 PM](https://user-images.githubusercontent.com/39598672/65911387-8eb1da80-e39a-11e9-918d-286e105d11a7.png)

7.  *Multi Input* Custom Filter - we need to get rid of the empty menu list OR display a custom msg to the user that no results are found
![Screen Shot 2019-09-30 at 3 34 55 PM](https://user-images.githubusercontent.com/39598672/65911610-df293800-e39a-11e9-8394-c7435e48e6a5.png)

8. *Popover Placement* documentation is broken      **FIXED**
![Screen Shot 2019-09-30 at 3 35 16 PM](https://user-images.githubusercontent.com/39598672/65911658-f10adb00-e39a-11e9-9ab9-a5a112c7441e.png)

9. Search Input should be removed from the Side navigation in the Documentation      **FIXED**
![Screen Shot 2019-09-30 at 3 35 56 PM](https://user-images.githubusercontent.com/39598672/65911714-041dab00-e39b-11e9-99c1-daecfe3bd9c4.png)

10. Documentation for *Status Indicators*       **FIXED**
![Screen Shot 2019-09-30 at 3 37 13 PM](https://user-images.githubusercontent.com/39598672/65911766-18fa3e80-e39b-11e9-9a4f-27e4ef45e21e.png)

11. *Alert* - The close button in Fund-ngx seems 1px bigger that the container of the alert
In NGX: (**the break is coming from Fundamental-styles**)
![Screen Shot 2019-09-30 at 3 39 58 PM](https://user-images.githubusercontent.com/39598672/65911855-43e49280-e39b-11e9-98dc-46863c93460f.png)

In Styles:
<img width="391" alt="Screen Shot 2019-09-30 at 3 39 48 PM" src="https://user-images.githubusercontent.com/39598672/65911871-49da7380-e39b-11e9-8ef5-3e816644e0c0.png">

12 Combobox - Input should be 100% width      **FIXED**

**Comment by JKMarkowski** [comment]
The alert bug is also on fundamental-styles. I will add `min-height: 40px;` there
![image](https://user-images.githubusercontent.com/26483208/65964298-eadd3300-e45c-11e9-9cc8-934989d0410d.png)

**Comment by JKMarkowski** [comment]
**#3 and #10** done on https://github.com/SAP/fundamental-styles/pull/359
