### ISSUE TITLE
CSS styles not loading

### ISSUE THREAD

**Issue by GarrusNapp** [SAP/fundamental-ngx#1329]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8
fundamental-ngx/core 0.12.0-rc.0

Hello, I've successfully installed fundamental-ngx through `ng add`, but not all CSS styles are applied to components, for example responsive table is only styled partially. 
I've checked that in `angular.json` only fonts and and icon stylesheets are imported. 

Full installation guide does state that `"node_modules/fundamental-styles/dist/fundamental-styles.min.css"` should be imported as well, but if I add it manually, it doesn't work as `fundamental-styles` package doesn't include such file. 

I've setup project to use SCSS, but it doesn't seem as if that's the problem.

**Comment by JKMarkowski** [comment]
Hi @GarrusNapp, our documentation is being updated,  right now the only things you need to put in your styles array in `angular.json` are: 
- "node_modules/fundamental-styles/dist/fonts.css" 
- "node_modules/fundamental-styles/dist/icon.css"

**Comment by GarrusNapp** [comment]
Hey @JKMarkowski , thank you for answering, I'll try to downgrade package version and see if it works. However I'm not sure if version 0.12.0-rc.0 should be marked as latest on npm and installed as default with `ng add` , please check if this is correct behaviour.
