### ISSUE TITLE
Inconsistent use of angle bracket template binding syntax in docs

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#133]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal
In our documentation, sometimes we use angle brackets on a component's properties when we shouldn't, and vice versa.  The angle brackets should be used when a property value needs (or could benefit from) data binding.  For example, a "hidden" property should be in brackets when a component's visibility may change while the user is on a page.  However, something like a component's ID that does not need data binding and will not change should not be in brackets.  I'll comb through the docs for each component and clean this up

#### What versions of Angular and Fundamental NGX? (If this is a feature request, use current version)
Angular 6.0.0, fundamental-ngx 0.0.8-beta

#### Is there anything else we should know?
https://angular.io/guide/template-syntax

**Comment by InnaAtanasova** [comment]
Inconsistency in the Modal, Panel, and Form documentation
