### ISSUE TITLE
fd-pagination boundary links request

### ISSUE THREAD

**Issue by jedrzejiwanicki** [SAP/fundamental-ngx#1342]
#### Is this a bug, enhancement, or feature request?

Feature request

#### Briefly describe your proposal.

1. Pagination component is currently  showing only navigation buttons allowing to increment/decrement current page. It would be useful to provide boundary link functionality which would navigate to first or last item.

2. Pagination has ellipsis by default, a feature allowing disabling ellipsis would be appreciated

3. Not sure if a bug, but rotation does not work properly e.g `1,2,3...5`. Clicking 3 will not rotate the buttons to display 4. However clicking 5 will rotate to 4. Further investigation of this issue would be appreciated.

#### Please provide relevant source code if applicable.

Example

1. Boundary links

```html
  <fd-pagination [boundaryLinks]="true" [firstLabel]="'First'" [lastLabel]="'Last'"></fd-pagination>
```
2. Optional ellipsis

```html
  <fd-pagination [ellipsis]="false"></fd-pagination>
```

**Comment by droshev** [comment]
@jedrzejiwanicki would you mind giving us some examples (for point 1 and 2)?

**Comment by jedrzejiwanicki** [comment]
@droshev Thanks for the anwser. 

The easiest way to understand what I want to achieve is by looking at example at [Angular Bootstrap Pagination](https://ng-bootstrap.github.io/#/components/pagination/api).

 It accepts `ellipsis` input which is a boolean enabling/disabling the `...` break between pagination buttons. `boundaryLinks` flag enables the appearance of `Last` button and `First` button

**Comment by droshev** [comment]
@jedrzejiwanicki do you think you can create a PR?
