### ISSUE TITLE
Calendar components performance issue.

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#1355]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
The calendar, datepicker, datetime picker components are very slow and it takes a lot of time to redirect to docs pages with them.

Also, when using IVY with datepicker on `[type]="'range'"` there is error:
![image](https://user-images.githubusercontent.com/26483208/66135606-8061f980-e5fa-11e9-89e5-1cdb9d012440.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
0.12.rc-9+ versions
Merging https://github.com/SAP/fundamental-ngx/pull/1353 could have a impact on it.

#### If this is a bug, please provide steps for reproducing it.
Go to calendar, datepicker, datetimepicker examples on docs.

#### Is there anything else we should know?
Generally disabling IVY fixes the performance issue.

**Comment by fkolar** [comment]
Usually the error like this was caused by not importing the `FormsModule`

**Comment by fkolar** [comment]
I check the code and we are importing it in teh shared so this shoudl nto be the case

**Comment by fkolar** [comment]
It just checked locally and its really IVY problem as it works without IVY, do we work already under stackblitz? If yes we are able to replace this sample using this component on stackblitz. I cna send it directly to angular team.

**Comment by JKMarkowski** [comment]
I can't put IVY options into stackblitz. Error can be caused by performance issues.

**Comment by JKMarkowski** [comment]
I got it.
  `<fd-date-picker [type]="'range'" [(ngModel)]="selectedRange" style="width: 300px"></fd-date-picker>`
Makes error, but
  `<fd-date-picker [type]="'range'" [(ngModel)]="selectedRange"></fd-date-picker>`
Does not. This pack of attributes provide the error.
