### ISSUE TITLE
Input focusable components hides border

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#1373]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.
When input fields are selected (namely those that has popover), the border turns 2px and darker. It creates a gap between design file and NGX implementation in terms of styles (please see pics).
 
FUI Design file: 2px border inside
FUI NGX: 2px border outsize

We should move on 2px border inside, because border outside looks like bug and error.

<img width="737" alt="Screen Shot 2019-10-08 at 4 33 54 PM" src="https://user-images.githubusercontent.com/17149942/66405098-e7602380-e9e9-11e9-9120-d2e8c77806f2.png">
<img width="164" alt="Screen Shot 2019-10-08 at 4 34 09 PM" src="https://user-images.githubusercontent.com/17149942/66405109-eaf3aa80-e9e9-11e9-8058-89ac326bd64c.png">

Also besides having border outside the overlay also hides the bottom (top) border. 

<img width="591" alt="Unknown" src="https://user-images.githubusercontent.com/17149942/66405152-f8a93000-e9e9-11e9-890a-2ac3870b152c.png">

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Current docs sites

**Comment by bcullman** [comment]
might be an issue for https://github.com/SAP/fundamental-styles.

**Comment by fkolar** [comment]
good point closing, thanks
