### ISSUE TITLE
Docs: fundamental-ngx/core/home pages are not responding properly

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#1389]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
http://localhost:4200/fundamental-ngx#/core/home should respond to user actions.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 8.
#### If this is a bug, please provide steps for reproducing it.

Git clone fundamental-ngx in local.
npm install
ng build core
ng build platform
ng build docs
ng serve

try to access the docs in local
http://localhost:4200/fundamental-ngx#/core/home

1).Side menu is not closing on select of component.
2).console is displaying a error
<img width="1680" alt="Screen Shot 2019-10-11 at 3 25 43 PM" src="https://user-images.githubusercontent.com/53487468/66643010-83349e00-ec3b-11e9-84c1-970fed1f6c6d.png">

**Comment by fkolar** [comment]
Are you sure you built this corectly?

**Comment by sKudum** [comment]
> Are you sure you built this corectly?
> 
> It works for latest master.
> 
> <img alt="Screen Shot 2019-10-11 at 12 10 27 PM" width="1634" src="https://user-images.githubusercontent.com/17149942/66643967-24adf680-ec20-11e9-8c35-dd14ec6d87c9.png">
> 
> Try to also checkout package.json and some documentation, the steps you described this is not how we build this.
> 
> ```
>  npm run build-all
>  npm run build-docs
> ng serve docs
> ```
> 
> I just updated my existing project with reseting to head -> hard, git pull on master, rm node_modules and npm install and then I run above commands,

- Yes Frank, I followed the steps mentioned by you, I redid again all now. I can still see the errors in console ng.probe
and I am trying to access using link:http://localhost:4200/fundamental-ngx#/core/button

**Comment by fkolar** [comment]
let;s have somebody with windows machine to validate this on windows..

**Comment by JKMarkowski** [comment]
You don't need to use  `npm run build-all npm run build-docs`. Now, after some changes, you need only to put `ng serve`

**Comment by sKudum** [comment]
> You don't need to use `npm run build-all npm run build-docs`. Now, after some changes, you need only to put `ng serve`
Tried the same, I can see the issue still persists. 
I am trying to access
http://localhost:4200/fundamental-ngx#/core/button.
I hope this is correct URL.

for core it will :
http://localhost:4200/fundamental-ngx#/core/button

So for platform we will be creating 
http://localhost:4200/fundamental-ngx#/platform/button

**Comment by JKMarkowski** [comment]
Hi @sKudum, if you are still having any issues with it, ping me on slack.

**Comment by JKMarkowski** [comment]
@sKudum `ng.probe` error can be caused by `augury` extension, when using `isOnDevMode` method.
