### ISSUE TITLE
How to override the padding of the shellbar?

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1397]
#### Is this a bug, enhancement, or feature request?

Question

#### Briefly describe your proposal.

I would like to override the padding of the shellbar. When I inspected the html code, the code was looking like this: 

```
<top-bar _ngcontent-xat-c0 _nghost-xat-c1>
  <fd-shellbar _ngcontent-xat-c1>
    <div class="fd-shellbar">...</div>
  </fd-shellbar>
</top-bar>
```

The div seems to generated and contains all the shellbar content. The css class fd-shellbar is coming from luigi.css and contains all the css including the padding of the shellbar. In luigi.css the padding for the shellbar is defined like this:

```
@media (min-width:320px) {
  .fd-shellbar {
    padding: 4px 8px
  }
}

@media (min-width:600px) {
  .fd-shellbar {
    padding: 4px 16px
  }
}

@media (min-width:1024px) {
  .fd-shellbar {
    padding: 4px 32px
  }
}

@media (min-width:1440px) {
   .fd-shellbar {
    padding: 4px 32px
}

@media (min-width:1920px) {
  .fd-shellbar {
    padding: 4px 32px
  }
}
```

Because of that I've defined my own @media entries in my scss file like...

```
@media (min-width:320px) {
  .fd-shellbar {
    padding: 4px
  }
}

@media (min-width:600px) {
  .fd-shellbar {
    padding-left: 6px;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-right: 8px
  }
}

...

```

...but they have been ignored. Is there anyway how I can override those entries? In general, I can change the predefined css from luigi.css.  I've added the following entry...

```
.fd-shellbar__logo {
  display: inline-block;
}
```

...to my scss file and it was recognized and display was switched from 'flex' to 'inline-block'. I can also add successfully @media entries to elements which does not have any @media yet. E. g. ...

```
@media (min-width:1000px) {
  fd-shellbar-logo {
    margin-right: 100px;
  }
}
```
is also recognized and works. Did I something wrong in regard to the padding of the shellbar or is it not allowed/possible to change it?

BR
Lukas

**Comment by JKMarkowski** [comment]
Hi @kistll, please tell me which version do you use. Also try to add 
`encapsulation: ViewEncapsulation.None`
To your *.ts file which imports the *.scss file with .shellbar classes.

**Comment by kistll** [comment]
Hi @JKMarkowski, thx for your reply. Currently we use "@fundamental-ngx/core": "^0.11.0". I'm not quite sure where to put encapsulation: ViewEncapsulation.None. I've added to the component which defines our shellbar but it didn't help.

**Comment by JKMarkowski** [comment]
Hello @kistll , It's weird, I check it on `0.11.0` version and it works, when I add `ViewEncapsulation.None`. This is code example:
```
@Component({
    selector: 'fd-shellbar-basic-example',
    templateUrl: './shellbar-basic-example.component.html',
    styleUrls: ['./shellbar-basic-example.component.scss'],
    encapsulation: ViewEncapsulation.None
})
export class ShellbarBasicExampleComponent {
```

**Comment by kistll** [comment]
Hi @JKMarkowski,
Can you please verify it with version 0.12.0?

I tried the following:

top-bar.component.html

```
<fd-shellbar>
  <fd-shellbar-logo>
    <a href="#" class="fd-shellbar__logo fd-shellbar__logo--image-replaced" aria-label="SAP"></a>
  </fd-shellbar-logo>

  <fd-product-menu [(isOpen)]="isOpen" *ngIf="showAppChooser$ | async" [closePopoverOnSelect]="true" [control]="'SHELL_NAVIGATION_SWITCH_APPLICATION_L' | translate"
    [items]="appItems$ | async">
  </fd-product-menu>

  <fd-shellbar-subtitle>
    <span>{{(currentRootNavigationItem$ | async)?.label | translate}}</span>
    <experimental-button *ngIf="(currentRootNavigationItem$ | async)?.experimental === true"></experimental-button>
  </fd-shellbar-subtitle>

  <fd-shellbar-actions [closePopoverOnSelect]="true">
    <preview-button></preview-button>
    <more-button></more-button>
    <profile-popover></profile-popover>
  </fd-shellbar-actions>

</fd-shellbar>

```
top-bar.component.scss

```
@media (min-width:1440px) {
  .fd-shell-bar {
    padding-left: 100px;
  }
}
```
top-bar.component.ts

```
import { Component, OnInit, OnDestroy, ViewEncapsulation } from '@angular/core';

...

@Component({
  selector: 'top-bar',
  templateUrl: './top-bar.component.html',
  styleUrls: [
    './top-bar.component.scss'
  ],
  encapsulation: ViewEncapsulation.None
})
export class TopBarComponent implements OnInit, OnDestroy {

...
```

Have I done something wrong?

BR Lukas

**Comment by JKMarkowski** [comment]
Hello, yes, you should change class name `.fd-shell-bar` to `.fd-shellbar` :) Hope it will help.

**Comment by kistll** [comment]
Hi @JKMarkowski,
Switching the class name from `.fd-shell-bar` to `.fd-shellbar` helped. Now, I am capable of overwriting media entries. Thx a lot for your help.
BR Lukas
