### ISSUE TITLE
performance issues in Fundamental NGX in angular 8/9

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1399]
We are experiencing some performance issues when we switched to IVY from Angular 8/9.
This is a central issue tracking all the issues related to IVY and Angular 9

**Comment by fkolar** [comment]
We are not running IVy with ng8. Are you talking about some other branch running on ng9?

**Comment by JKMarkowski** [comment]
Hi @fkolar  We run IVY on our docs page, also we allow to run our library with IVY.

**Comment by JKMarkowski** [comment]
Generally we had issues with `ngAfterViewChecked` / `ngAfterContentChecked`, that's why I pushed this PR https://github.com/SAP/fundamental-ngx/pull/1369 . Also I made some research and the fact it that we have some performance issues on more complex component's sites (calendar and pickers).
We should work on https://github.com/SAP/fundamental-ngx/issues/1371. Maybe the fact that we have 1 shared module and 1 very huge module is the case.

**Comment by droshev** [comment]
We need to understand why with IVY the performance is that much slower.

**Comment by JKMarkowski** [comment]
There are [performance tests](https://docs.google.com/document/d/1r7UaXEeOmvfVsmb6yL_hLXTCl6V-XEkVC458ESrdrW0/edit?usp=sharing)

**Comment by JKMarkowski** [comment]
The size of bundles with IVY is ~15% lower, but generally the time it takes to render application is quite longer. For calendar component it takes a lot of time. Even with ng9.
[ng9 without IVY Preview](https://github.com/SAP/fundamental-ngx/pull/1380)
[ng9 with IVY Preview](https://github.com/SAP/fundamental-ngx/pull/1385)

**Comment by fkolar** [comment]
@JKMarkowski this is strange it looks like ng-packagr issue. I see button is exported, can quickly test this to explicitelly export it? 

export ButtonComponent from ..... directly in the top index file - just to make sure this one works?

**Comment by fkolar** [comment]
Should we use IVY for the library? and only for the actual application?

**Comment by JKMarkowski** [comment]
@fkolar  This is actually the ng-packagr issue with IVY. I'm not sure, if we should use IVY for library. In Ng9 the IVY will be used by default, so I wanted ot make it work with it.

**Comment by fkolar** [comment]
i have asked . i am not sure either

**Comment by fkolar** [comment]
Based on angular recomendation:


"Currently libs shall not use ivy. The consuming app can decide whether it compiles everything with ivy or not. This is the current recommendation for ng9. It will change in future when almost `everyone` uses ivy.

**Comment by droshev** [comment]
@fkolar thanks for the update. Not i think we can limit the performance issue to popover and using https://github.com/FezVrasta/popper.js in angular 8 or 9. @JKMarkowski can you confirm?

**Comment by JKMarkowski** [comment]
@droshev Yes, I can completely confirm it. Also we should boost our library, by changing `changeDetectionStrategy` to `onPush`.

**Comment by JKMarkowski** [comment]
I tested our lib usage with some components with `changeDetectionStrategy` and the results were very promising. I followed `@angular/material`, because that library uses `onPush` on every single component.
