### ISSUE TITLE
remove fundamental-ui css overwrites from docs/styles.scss

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#141]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal
We have overwritten some core fundamental-ui styles in docs/styles.scss in order to make the components more presentable in the documentation.  However by doing this, we run the risk of introducing inconsistent/unexpected behavior throughout the documentation app.  For example if we overwrite styles on fd-button in order to make the button documentation look better, other pages that use the button will not have anticipated this change.  We should create new style classes for these adjustments rather than overwriting existing fundamental-ui styles

#### What versions of Angular and Fundamental NGX? (If this is a feature request, use current version)
Angular 6.0.0, fundamental-ngx 0.0.8-beta

**Comment by droshev** [comment]
@mikerodonnell89 could you list the components with that? this way we can plan improvements

**Comment by MattL75** [comment]
Mostly done. The issue is not closed because there's still SIDENAV overrides left. However, these are necessary because the styles we get from Fundamentals are not sufficient to create a proper sidenav.

**Comment by droshev** [comment]
@droshev to refer the issue from `fundamental-styles' regarding `SideNav` refactoring

**Comment by droshev** [comment]
Let's audit the current state

**Comment by droshev** [comment]
after adopting self-contained feature from `fundamental-styles`
