### ISSUE TITLE
Tabs component enhancements (overflow menu and stacking option)

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1410]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
1. For more than a specific number of tabs (for example - 5) we can move the additional tabs to an overflow menu. The number should be configurable and specified by the user.
<img width="1082" alt="Screen Shot 2019-10-15 at 11 12 12 AM" src="https://user-images.githubusercontent.com/39598672/66844684-b8433800-ef3c-11e9-88c8-41a3ca476692.png">

This behaviour can also be applied to mobile view (smallest screens) where we show only the first tab and an additional tab with the overflow icon that triggers an overflow menu with the remaining tabs. 

<img width="442" alt="Screen Shot 2019-10-15 at 11 12 30 AM" src="https://user-images.githubusercontent.com/39598672/66844803-ed4f8a80-ef3c-11e9-8be5-79b2c492dc71.png">

2. Introduce an option where the tabs' content gets stacked on top of each other.

5d

To Do - check the design for the overflow menu

**Comment by tjbutz** [comment]
Hi,

Next to a specific number of tabs to show (point 1), please also consider the option to show as much tabs as possible which fit into the tab strip (based on the screen size), before hiding them in the menu.

Best regards
Tino
