### ISSUE TITLE
Positioning of Modal component is off  in IE11

### ISSUE THREAD

**Issue by harikusumba** [SAP/fundamental-ngx#1411]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
NGX: Latest
Angular: any
Browser: IE11
#### If this is a bug, please provide steps for reproducing it.
Modal component does not work in IE11. Use IE11 Go to the ngx components page and click on Modal component. 
#### Is there anything else we should know?
Browser version : IE11

**Comment by harikusumba** [comment]
<img width="557" alt="Screen Shot 2019-10-19 at 12 35 49 AM" src="https://user-images.githubusercontent.com/9489102/67139806-f83e3f80-f208-11e9-8e4c-5e0e8b8d5f7f.png">
![Uploading Screen Shot 2019-10-19 at 12.38.50 AM.png…]()

**Comment by droshev** [comment]
@harikusumba were you able to test in Edge?

**Comment by harikusumba** [comment]
@droshev we ended up adding IE specific css properties to fix it i our app.

```@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  ::ng-deep .fd-overlay--modal {
    left: 0 !important;
  }

  ::ng-deep .fd-modal-custom {
    position: relative !important;
  }
}```
