### ISSUE TITLE
BadgeComponent.status has not type

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#1436]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Provide type for possible `BadgeComponent.status` values

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
0.10.0

#### If this is a bug, please provide steps for reproducing it.
Currently `BadgeComponent.status` has no type. In the comment above it there's a list of valid values. I suggest to create add a TS type with possible values.

#### Please provide relevant source code if applicable.

https://github.com/SAP/fundamental-ngx/blob/master/libs/core/src/lib/badge-label/badge-label/badge.component.ts#L17

**Comment by droshev** [comment]
@mpienkowski we would nee to migrate the badges to support all the accent colors(1-10) from the theming parameters - https://github.com/SAP/theming-base-content/blob/1bcf23f0e592b71e26372f33af6c45c77cef063b/content/Base/baseLib/sap_fiori_3/css_variables.css#L275
I am not sure whether exposing types now would be helpful as we may need to remove them
