### ISSUE TITLE
Platform: Change loading icon on SearchInputComponent

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#1442]
#### Is this a bug, enhancement, or feature request?
Feature.

#### Briefly describe your proposal.

The current loading icon for the SearchInputComponent does not use the standard loading spinner for fundamental-styles.

***CURRENT:***
<img width="263" alt="Screen Shot 2019-10-21 at 12 18 00 PM" src="https://user-images.githubusercontent.com/48103491/67235898-e6bd8900-f3fc-11e9-8eeb-5830bc64261d.png">

***PROPOSED:***
<img width="234" alt="Screen Shot 2019-10-21 at 12 17 35 PM" src="https://user-images.githubusercontent.com/48103491/67235913-f1781e00-f3fc-11e9-8baa-16ac09c10aa9.png">

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8
Fundamental-NGX v0.12.0

**Comment by harikusumba** [comment]
@KevinOkamoto FYI, We made a similar customization for the the multi-input component but are using the refresh icon - double arrow with states, blue: drop-down arrow, blue: processing with the spinner, red - error spinner. I would like to know if you also intend to add the error state.

**Comment by KevinOkamoto** [comment]
This issue is obsolete as SearchInput has been replaced by SearchField. Also the Fiori 3 requirements do not feature a loading spinner.
