### ISSUE TITLE
Add pixel offset value for scrollSpy activation 

### ISSUE THREAD

**Issue by GarrusNapp** [SAP/fundamental-ngx#1446]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

It'd be nice if we could pass value in pixels to add/substract from event activation threshold.
I have a case where one of element becomes sticky on the top of the list and can't simply add its height to threshold.
[Similar case](https://sapui5.hana.ondemand.com/test-resources/sap/ui/demoapps/demokit/rta/freestyle/test/flpSandbox.html#masterDetail-display&/product/HT-1000)

**Comment by JKMarkowski** [comment]
Hello @GarrusNapp, this feature will be included in 0.12.0.
