### ISSUE TITLE
No matching version found for fundamental-ngx@0.11.0

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#1456]
#### Briefly describe your proposal.
Unable to update ngx to version 0.11.0.
![image](https://user-images.githubusercontent.com/34537974/67378392-768f3e80-f587-11e9-8772-d27c52b9b9a5.png)  
And if i write  
`"fundamental-ngx": "0.11.0",` then use `npm i`:  
![image](https://user-images.githubusercontent.com/34537974/67378842-2bc1f680-f588-11e9-9707-937d5b3ac3b7.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7  
Fundamental ngx 0.10.0

**Comment by JKMarkowski** [comment]
Hello @JohnHavok, we changed name of our library, cause of monorepo with other library. Now it's named `@fundamental-ngx/core`. Check the [instalation guide](https://github.com/SAP/fundamental-ngx/wiki/Full-Installation-Guide)

**Comment by droshev** [comment]
@JohnHavok As @JKMarkowski wrote the package name has changed to `@fundamental-ngx/core` as we did split the repo to 2 packages:
- `@fundamental-ngx/core` 
- `@fundamental-ngx/platform`
Also you may want to see the Angular support [here](https://github.com/SAP/fundamental-ngx/wiki#angular-version-support)

**Comment by JohnHavok** [comment]
Sorry for this issue.. And thank you for your explanation.
