### ISSUE TITLE
Request for attributes enhancements for elements within UI

### ISSUE THREAD

**Issue by itz4aparna** [SAP/fundamental-ngx#1463]
#### Is this a bug, enhancement, or feature request?
Feature Request

#### Briefly describe your proposal.

1. Drop down values do not have specific attributes when using options
2. This falls as a requirement as we also implement E2E tests using selenium web driver and the driver is unable to recognize the required elements within drop down values

Can you kindly give feedback/ suggestion if there is a better way to implement the below code in order to have attributes visible for Selenium web driver as well?

#### Please provide relevant source code if applicable.
 
          <div class="profile-popover-item-container"
              *ngIf="languageOptions && languageOptions.length && (selectedLanguageCode$ | async)">
            <div fd-form-item>
              <label fd-form-label for="profile-popover-language-dropdown">
                {{ 'Language' | translate }}
              </label>

              <select fd-form-control 
                id="selectedLanguageCode"
                [ngModel]="selectedLanguageCode$ | async"
                (ngModelChange)="updateLanguage($event)">

                <option
                  id="lang-option-{{option.code}}"
                  *ngFor="let option of languageOptions" 
                  [ngValue]="option.code">
                  <div>{{ option.name | translate }}</div>
                </option>

              </select>
            </div>
          </div>

**Comment by JKMarkowski** [comment]
Hello @itz4aparna, could you provide version of NGX are you using and whole template code? It seems like you are using the `fd-form-control`, which adds classes only. It has no impact on any functionality of element. You can put some `id` to elements here to recognize, by this `id`.

**Comment by zaheral** [comment]
Hi @JKMarkowski 
we are using following versions:
        "fundamental-ngx": "^0.10.0",
        "fundamental-styles": "^0.1.0",

Unfortunately, we cannot give you the whole code, because it is an internal project. But we will send you via mail the link to the code, which you will have access to.

Best Regards,
Zaher

**Comment by itz4aparna** [comment]
Hi @JKMarkowski ,
were you able to look at the code?
Let us know if any further details required.

Thanks & Regards,
Aparna Srinivasan

**Comment by itz4aparna** [comment]
The issue is set to closed as we have implemented "directly initializing the selenium webdriver" for drop down values
