### ISSUE TITLE
Docs: broken hash links

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#1477]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Hello again friends! I don't really have time to work on this, but I'm using fd-ngx in a personal project and noticed some weird stuff in the new docs. I'll post individual issues though.

So the header links are broken, and also using an href and not the router for some reason? Not too sure, I haven't looked much into it :woman_shrugging: 

Also I'm not sure if this is already implemented (didn't check) or a planned feature, but it would be nice if the hash link was copied to the clipboard using the CopyService when you click on it.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Latest

#### If this is a bug, please provide steps for reproducing it.
Click on a link in a section header

**Comment by JKMarkowski** [comment]
Hi @MattL75, good to see you in our github again :D, I will take a look on these things. We should for sure use `[routerLink]` instead of basic `href`. I will also add some icon for copying the link near the section-title.

**Comment by MattL75** [comment]
Hi @JKMarkowski :D

Actually having looked at angular.io maybe it's not necessary to copy, but instead just have the link in the address bar for people to copy. Whatever is better UX I guess :man_shrugging:

**Comment by JKMarkowski** [comment]
Ok, probably we'll add the copy button later. For now I will push the fixes :)
