### ISSUE TITLE
Docs: Stackblitz button ux problems

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#1478]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The stackblitz button in the fd-ngx docs has the same icon as the copy button. To be conform to fd-vue, the button should have the play icon. It could be another icon though.

Also, the title (hover text) of the button is the same as the copy button. Hover over the stackblitz button to see.

**Comment by stefanoScalzo** [comment]
Will change the button icon and styling immediately

**Comment by droshev** [comment]
@MattL75 thanks for pointing out :) We are happy you show interest.
Feel free to open even PRs

**Comment by MattL75** [comment]
Of course, this lib is still very close to my heart :sweat_smile: 

Pretty busy with work atm, but if I have time I'll be looking into doing PRs
