### ISSUE TITLE
docs: (platform) README.md needs update

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1489]
Hello,

I think [platform README.md](https://github.com/SAP/fundamental-ngx/blob/master/libs/platform/README.md) needs improvements:
- we need to emphasize more what `platform` is about
- update the example section

**Comment by sKudum** [comment]
Hi Deno,

. I added more descriptions about platform. Let me know if you feel still anything is missing in it.

. In example section, I have updated with all button component details and options provided. 
If you can elaborate more then it will help to proceed further.

**Comment by fkolar** [comment]
@sKudum Maybe should link a pR to this.

**Comment by sKudum** [comment]
> @sKudum Maybe should link a pR to this.

https://github.com/SAP/fundamental-ngx/pull/1488

**Comment by droshev** [comment]
@sKudum do you think you can give some examples what platform is providing and in which use-cases it should be used?
Can you put yourself in the shoes of a developer who is browsing the documentation for the first time?

**Comment by sKudum** [comment]
> @sKudum do you think you can give some examples what platform is providing and in which use-cases it should be used?
> Can you put yourself in the shoes of a developer who is browsing the documentation for the first time?

https://github.com/SAP/fundamental-ngx/pull/1494 =>Will this do?

**Comment by droshev** [comment]
done
