### ISSUE TITLE
Cannot compile UI with fundamental-ngx version 0.12.0

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1503]
#### Is this a bug, enhancement, or feature request?

Probably a bug

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Version 0.12.0 (the problem persists also in the latest prerelease version which is currently 0.12.1-rc.9)

#### If this is a bug, please provide steps for reproducing it.

The compiling of the UI fails with the following error message:

```
...

ERROR in node_modules\@fundamental-ngx\core\fundamental-ngx-core.d.ts.ɵbm.html(2,25): : Cannot invoke an object which is possibly 'undefined'.

i ｢wdm｣: Failed to compile.
```

**Comment by JKMarkowski** [comment]
Hello @kistll, could you provide your Angular version ?

**Comment by kistll** [comment]
Hello @JKMarkowski,

Currently, we have the following angular dependencies:

```
"@angular/animations": "^7.1.3",
"@angular/cdk": "^7.1.1",
"@angular/common": "^7.1.3",
"@angular/compiler": "^7.1.3",
"@angular/core": "^7.1.3",
"@angular/forms": "^7.1.3",
"@angular/http": "^7.1.3",
"@angular/platform-browser": "^7.1.3",
"@angular/platform-browser-dynamic": "^7.1.3",
"@angular/platform-server": "^7.1.3",
"@angular/router": "^7.1.3",
"@angular-devkit/build-angular": "^0.11.3",
"@angular/cli": "^7.1.3",
"@angular/compiler-cli": "^7.1.3",
"@angular/language-service": "^7.1.3",
```

**Comment by JKMarkowski** [comment]
I'm afraid, you need to switch to angular 8, or use 0.11.1 version instead of 0.12.0

**Comment by JKMarkowski** [comment]
Could you switch to `"@fundamental-ngx/core": "^0.12.0"` ?

**Comment by kistll** [comment]
I face the same issue with "@fundamental-ngx/core": "0.12.0".

**Comment by kistll** [comment]
Issue could be solved by removing 'strictNullChecks: true' from tsconfig.app.json.

**Comment by rossgardt** [comment]
I am facing the same issue. How can this be avoided without changing how we compile the application?

**Comment by zaheral** [comment]
Hi @JKMarkowski , I also face this issue. Will it be fixed on the next version.
I'm using the current version 0.12.0

**Comment by JKMarkowski** [comment]
Hello @zaheral and @rossgardt It will be fixed on 0.13.0.

**Comment by rossgardt** [comment]
Thanks for the update @JKMarkowski 🙏

**Comment by zbug** [comment]
Could you please publish 0.12.0 and 0.13.0 on npm? I am unable to consume them

Regards
