### ISSUE TITLE
Platform: Search Input autosuggestion dropdown not working in Edge and IE browsers

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#1510]
#### Is this a bug, enhancement, or feature request?
Bug.

#### Briefly describe your proposal.

The autocomplete feature of the search input component is not working in IE 11 or Edge.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8
Fundamental NGX 0.12.0

#### If this is a bug, please provide steps for reproducing it.

* Open page with search input component in IE 11 (or Edge) browser
* Type in input field
* A dropdown with suggestions does not appear

***Expected:***
The suggestion dropdown should appear on keyboard input in text field.

**Comment by fkolar** [comment]
Kevin what component are you refering to? Combobox ?

**Comment by KevinOkamoto** [comment]
Search Input

**Comment by KevinOkamoto** [comment]
This issue is obsolete, as the SearchInput has been replaced by SearchField component.
