### ISSUE TITLE
Unable to import LayoutGridModule

### ISSUE THREAD

**Issue by hisabimbola** [SAP/fundamental-ngx#1521]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
I can't install LayoutGridModule
#### Please provide relevant source code if applicable.
import { LayoutGridModule } from '@fundamental-ngx/core';
"@fundamental-ngx/core": "0.12.0",

**Comment by JKMarkowski** [comment]
No @hisabimbola, I see, there is missing export of layout-grid in index.ts. To work around it, You can import whole FundamentalNgxCoreModule. We will provide fixes soon.

**Comment by ivijan** [comment]
hello, I experienced the same issue, in what version will fix be released?

**Comment by JKMarkowski** [comment]
Hello @ivijan,

it will be fixed in 0.13.0 version.
