### ISSUE TITLE
Doc: Outdated import example

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#1534]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.

In the docs on component level we still show the old example how to import module

https://sap.github.io/fundamental-ngx/#/core/layoutGrid

`import { LayoutGridModule } from 'fundamental-ngx';`

**Comment by droshev** [comment]
@fkolar this was fixed with https://github.com/SAP/fundamental-ngx/pull/1528
