### ISSUE TITLE
Component 'Status Indicator Label with semantic colors' has inconsistent color

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#1554]
This is a UX bug. Please refer to the NGX page for the component Status Indicators:
https://sap.github.io/fundamental-ngx/#/core/badgeLabel

The text on top of that page says that "Black is used to indicate default or inactive status." In fact all the following status indicator examples show the Fiori blue color for 'Draft' ... which is correct from my perspective. The only exception is the last example on that page at the very bottom, 'Status Indicator Label with semantic colors'. Here the draft status is implemented black/grey. This should be changed to blue as in the previous implementation examples to ensure consistency.

![image](https://user-images.githubusercontent.com/52921101/68368861-33150280-0139-11ea-9b22-433192631edf.png)

**Comment by droshev** [comment]
@D034394 would you mind opening this issue in fundamental-styles? We haven't migrated the colors of status indicator yet.

**Comment by D034394** [comment]
Done. Thank you.
https://github.com/SAP/fundamental-styles/issues/418
