### ISSUE TITLE
LocalizationEditor: form submitted at the click of the button

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#1585]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Clicking the localization-editor button of the localization-editor component submits the form
![image](https://user-images.githubusercontent.com/34537974/68781570-47c13100-0638-11ea-9349-dd957c3ff4bc.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7
NGX 0.11.0 

#### If this is a bug, please provide steps for reproducing it.
Insert a localization editor in a reactive form

#### Is there anything else we should know? Type per default
It seems to me that the default type of a button when it is not indicated is 'submit'.  
Maybe just add type="button" for the button line 6 in localization-editor-main.component.html fix this?

**Comment by JKMarkowski** [comment]
Hello @JohnHavok, this fix is currently on 0.11.2, so let's switch version. There is no any breaking change in 0.11.0 -> 0.11.2.
