### ISSUE TITLE
Select component is overriding defaultValue

### ISSUE THREAD

**Issue by richard-velito** [SAP/fundamental-ngx#1597]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When the options of the component  are loaded async way, SelectComponent is setting to  `undefined`  the value of the control, despite the default value is going to match with the options once loaded.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
fundamental-ngx/core : 0.12.0
angular/core: 8.0.0

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-g3ceru

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-g3ceru

`
 private unselectOptions(): void {
        setTimeout(() => {
            if (this.selected) {
                this.selected.setSelected(false, false);
            }
            this.selected = undefined;
            this.value = undefined;
            this.valueChange.emit(undefined);
            this.onChange(undefined);
        });
    }
`

#### Is there anything else we should know?
take a look on unselectOptions method on 

https://github.com/SAP/fundamental-ngx/blob/master/libs/core/src/lib/select/select.component.ts

**Comment by JKMarkowski** [comment]
Hi @richard-velito,
It is gonna be fixed, by adding `autoUnselect` input option. So user will be able to choose if he wants to unselect automatically missing option.

**Comment by droshev** [comment]
@richard-velito thanks for your feedback! :)
