### ISSUE TITLE
DatePicker control does not support null or empty values and the Control and Form are invalid.

### ISSUE THREAD

**Issue by REIP** [SAP/fundamental-ngx#1598]
#### Is this a bug, enhancement, or feature request?
This is a bug

#### Briefly describe your proposal.

I have tested the datePicker control and I have found a bit problem using this one.
I have a case which I have to support null or empty values on the control for dates by default.
When the  datePicker control is loaded as empty, it returns a Valid:false and as consequence 
the Form that contains this control is valid:false too, and it is not ok.

So, currently this control does not support to enter an empty or null value by default, I have reviewed the properties of the control and there is a property called "allowNull" but this one is not used on the logic for the control in order to allow null values.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7/ Angular 8
Fundamental Ngx 0.9.3
Fundamental-Ngx/Core : 0.12.0

#### If this is a bug, please provide steps for reproducing it
I am enclosing the stackblitz's url  where you can check my case that I have explained before.
https://stackblitz.com/edit/angular-gkbnxd

#### Please provide relevant source code if applicable. 
I have fixed this issue so as to support null values if the allowNull property is on true.
It is necessary to add the next code on dateStringUpdate method

//when is single mode
if (!date && this.allowNull) {
                    this.isInvalidDateInput = false;
                    this.selectedDate = FdDate.getToday();
                    this.refreshCurrentlyDisplayedCalendarDate(this.selectedDate);
                    this.onChange(null);
                }
//when is range mode
if (!date && this.allowNull) {
                    this.isInvalidDateInput = false;
                    this.selectedRangeDate = { start: FdDate.getToday(), end: FdDate.getToday().nextDay() };
                    this.refreshCurrentlyDisplayedCalendarDate(this.selectedRangeDate.start);
                    this.onChange(null);
                }

#### Is there anything else we should know?
The DateTimePicker works fine, this one allows null or empty values by default even the control and form are valid

**Comment by JKMarkowski** [comment]
Hi @REIP thanks for reporting the issue.
Fix will be merged to master soon. It will be in 0.13.0-rc.* version, or after deploy on 0.13.0.
