### ISSUE TITLE
Bug(core): Action Bar Tab order is not working properly in Fire fox browser.

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1615]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.
 Tab order should work in proper order for action bar component. But in mozila fire fox browser, for action bar component tab order is not working

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
 Angular 8
#### If this is a bug, please provide steps for reproducing it.

open url https://sap.github.io/fundamental-ngx/#/core/action-bar in fire fox browser and select back button and press tab key.

**Comment by JKMarkowski** [comment]
Hi @manu-kr, I tested it in firefox v70 and it worked well. 
![actionbar](https://user-images.githubusercontent.com/26483208/69135186-fe019c00-0ab8-11ea-9491-0cfce22d8c50.gif)
Could you provide your version of firefox?

**Comment by manu-kr** [comment]
> Hi @manu-kr, I tested it in firefox v70 and it worked well.
> ![actionbar](https://user-images.githubusercontent.com/26483208/69135186-fe019c00-0ab8-11ea-9491-0cfce22d8c50.gif)
> Could you provide your version of firefox?

70.0.1 (64-bit)

**Comment by droshev** [comment]
should be fine now
