### ISSUE TITLE
Bug(core): RTL is not working properly in safari browser

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1620]
#### Briefly describe your proposal.
RTL is not working for all the platform components (action bar, button, menu, search and dropdown) in Safari browser.
 

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8.

#### If this is a bug, please provide steps for reproducing it.
open safari browser

open below url.

https://devfarm.aws.ariba.com/appframework-master/component-examples/action-bar

**Comment by droshev** [comment]
fixed
