### ISSUE TITLE
Bug(core/platform):Keyboard access will not work in workflow for IE, Edge and Safari browsers

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1621]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.
Unable to access the elements like menu by using keys like(Up and Down Arrow ) in specific browser like IE ,Edge, and Safari.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8
#### If this is a bug, please provide steps for reproducing it.
https://sap.github.io/fundamental-ngx/#/core/menu .

Scroll down to Keyboard Support example.

- Click on Focus First Element button.

First menu item should get highlight.

**Comment by JKMarkowski** [comment]
Hello @manu-kr , the fact that first item is not highlighted is fixed [here](https://github.com/SAP/fundamental-ngx/pull/1583), [preview](https://deploy-preview-1583--fundamental-ngx.netlify.com/#/core/menu).

The bigger problem in my opinion is the fact, that keyboard events are not recognized by IE and Edge. For safari I'm not able to test it so far

**Comment by KevinOkamoto** [comment]
@JKMarkowski and @manu-kr I've done a little investigation into this issue and found a problem in the following code:

https://github.com/SAP/fundamental-ngx/blob/8cb805c7d90203a21041b8f857ca977be1b40430/libs/core/src/lib/combobox/combobox.component.ts#L223-L244

`KeyboardEvent.code` is not supported by IE and Edge, as reported here:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#Browser_compatibility

However, I think`KeyboardEvent.key` might be able to be used as an alternative, and it is supported by IE and Edge:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#Browser_compatibility

There is also an example using `KeyboardEvent.key` on the same page:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#Example
