### ISSUE TITLE
Bug: Localization is not implemented

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#1622]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.
Components should support the localization.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8
#### If this is a bug, please provide steps for reproducing it.

Open browser 

https://devfarm.aws.ariba.com/appframework-master/component-examples/action-bar

Check for different language.

**Comment by droshev** [comment]
we will be deprecating action bar soon
