### ISSUE TITLE
Different behaviour for combobox

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#1623]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
The current combobox has following behaviour:
a. click on the input-field -> list of options will be shown
b. include a search-term -> list of matched options will be shown
c. click on input-field, when search-term is already there ->  list of matched options will be shown

The behaviour of point a. & b. is ok, but we have an issue with point c., because when the use clicks again on the combobox, then he wants to see the other options, too. Currently, this is just possible if the search-term will be removed.

Here is a UI5 demo, which has the behaviour that we are looking for: http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox

We tried to use the "filterFn" API, to show all options, but this works unfortunately also for point b., which means, when I include/modify a search-term, then all options will still be shown.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
    "@angular/core": "~8.1.3",
    "@angular/forms": "~8.1.3",
    "@fundamental-ngx/core": "^0.12.0",
    "fundamental-styles": "^0.1.0",

**Comment by JKMarkowski** [comment]
Hi @zaheral, can you provide some details ?

**Comment by zaheral** [comment]
Hi @JKMarkowski , I clicked too fast on the create button ^^
Meanwhile, I updated the information (see first Quote)

**Comment by JKMarkowski** [comment]
@zaheral  I had a look on it, I think it can be solved by some workaround, I will prepare some stackblitz example tomorrow.

**Comment by JKMarkowski** [comment]
Hi @zaheral unfortunately there is no way to handle it by workaround, without touching core. I will create some PR with exposed method `resetDisplayedValues()`, which can be called whether the `open` state changes in combobox

**Comment by zaheral** [comment]
Hi @JKMarkowski ,
is there a follow-up ticket that we can check, so we can continue with our ticket when it is ready.
Best Regards,
Zaher
