### ISSUE TITLE
How to hide button / add-ons from input group.

### ISSUE THREAD

**Issue by kandarp-sap** [SAP/fundamental-ngx#1628]
#### Is this a bug, enhancement, or feature request?

Hello, 
Currently, we are using input group control along with fd-popover. 
Following is the example code which opens the popover on click of the button exists in the input group. 

```
<fd-popover [(isOpen)]="isValueHelpOpen[i]" [focusTrapped]="true" [closeOnOutsideClick]="true" [noArrow]="false"
    placement="bottom">
    <fd-popover-control>
        <fd-input-group [button]="true" [placement]="'after'" [compact]='true' [glyph]="'value-help'"
            (addOnButtonClicked)="openValueHelp()">
        </fd-input-group>
    </fd-popover-control>
    <fd-popover-body>
        <fd-menu  *ngFor="let item of selectionValues">
            <fd-menu-group>
                <h1>{{item}}</h1>
            </fd-menu-group>
        </fd-menu>
    </fd-popover-body>
</fd-popover>
```

We have an array `selectionValues` which displayed on button click. 
Now there is a case when this array is empty and I don't want to show button in input group at all. 

How to achieve that?

Thanks
Kandarp

**Comment by JKMarkowski** [comment]
Hello @kandarp-sap, 
take a look on [example](https://stackblitz.com/edit/angular-bi5eyi?file=src/app/input-group-number-example.component.html), there is `complex` InputGroup example, whch allows to put your own template of addons or input.

**Comment by kandarp-sap** [comment]
Hello @JKMarkowski ,

Thanks for the quick response. However, my requirement is I want to remove/hide that add on from the input group dynamically. 

Like in you example, 

Suppose I remove following lines 
![Screenshot 2019-11-20 at 10 49 02](https://user-images.githubusercontent.com/51914152/69229145-2bb41700-0b85-11ea-8842-ff93c6377be8.png)

I removed add on text, but not add on completely. that confuse the user. I want to make it invisible when there is not add on required. 

![Screenshot 2019-11-20 at 10 49 17](https://user-images.githubusercontent.com/51914152/69229262-69b13b00-0b85-11ea-8a5e-361e5573c3a3.png)

**Comment by JKMarkowski** [comment]
I see your point, can't you add some class by `[ngClass]` to the element, which will have `display: none`? Take a look [here](https://stackblitz.com/edit/angular-bi5eyi-wp7yhq?file=src/app/input-group-number-example.component.html).

**Comment by kandarp-sap** [comment]
Yup, that's a cool workaround. However, I was thinking to listed here so this feature can be added as a new property.

Thanks for this. solution. Maybe you can close this issue.
