### ISSUE TITLE
In case side navigation is collapsed, icon and symbol, which indicates a sublist, are overlapping.

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1629]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In case side navigation is collapsed, icon and symbol, which indicates a sublist, are overlapping:

![image](https://user-images.githubusercontent.com/51904901/69231107-cb26d900-0b88-11ea-944a-6a9123d1a00b.png)

Will this be fixed with Fundamental-ngx version 0.13.0 ?

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Fundamental-ngx version 0.12.0

**Comment by JKMarkowski** [comment]
Hi @kistll, what's your fundamental-styles version ?

**Comment by JKMarkowski** [comment]
Side Navigation will be completely changed in 0.13.0, take a look [here](https://fundamental-ngx.netlify.com/#/core/sideNavigation) how it will look like.

**Comment by kistll** [comment]
We use fundamental-styles@0.3.0. fundamental-styles is not specified in the package.json. It is just installed as a peer dependency for @fundamental-ngx/core. The entry in  the package-lock.json looks as follows: 

"@fundamental-ngx/core": {
      "version": "0.12.0",
      ....
      "requires": {
        "focus-trap": "^5.0.2",
        "fundamental-styles": "~0.3.0",
        "popper.js": "^1.15.0",
        "tslib": "^1.9.0"
      }

As the design is completely changed with fundamental-ngx version 0.13.0, the issue is obsolete. How long will it roughly take until fundamental-ngx version 0.13.0 is released?

**Comment by JKMarkowski** [comment]
Hi @kistll, I'm not sure, it should be released till end of next week.

**Comment by droshev** [comment]
fixed
