### ISSUE TITLE
Side nav with icons error

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#1635]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
The side nav gives errors for the item glyphs and read only propertys.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
prerelease
#### If this is a bug, please provide steps for reproducing it.
Open stackblitz with https://fundamental-ngx.netlify.com/#/core/sideNavigation#withIcons 
![Screen Shot 2019-11-20 at 2 18 35 PM](https://user-images.githubusercontent.com/50607147/69270413-e1409380-0ba0-11ea-8860-b8ece941115d.png)

**Comment by JKMarkowski** [comment]
Hi @stefanoScalzo, it's about using `@fundamental-ngx/core: 0.12.0` instead of `prerelease`. In 0.12.0 there wasn't this directive, which provides inputs like that.
