### ISSUE TITLE
Expose `buttonFocusable` in combobox component

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#1639]
#### Is this a bug, enhancement, or feature request?
Feature request.

#### Briefly describe your proposal.
Currently there is no option to enable the combobox button to be focusable. In the combobox template `buttonFocusable` is set to `false`:

https://github.com/SAP/fundamental-ngx/blob/8cb805c7d90203a21041b8f857ca977be1b40430/libs/core/src/lib/combobox/combobox.component.html#L11-L12

I propose exposing `buttonFocusable` as an input property of Combobox, so that the developer can enable if needed.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 8
Fundamental NGX 0.13.0

**Comment by JKMarkowski** [comment]
I think it should be added in all of `input-group` related components.
