### ISSUE TITLE
fd-list-checkbox checkbox right margin not reasonable when label text is empty

### ISSUE THREAD

**Issue by cstechfoodie** [SAP/fundamental-ngx#1660]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
When a checkout box is used without any label. The checkbox element still has a right margin. However, the event handler is placed on the checkbox, that means, for example, when I click the margin area, it still triggers the eventHandler, but not toggle the checkbox. 

Solution 1: reduce the margin-right of label to 0. Area for eventhandler should not expand the visualizable area of checkbox

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current
#### If this is a bug, please provide steps for reproducing it.
![Screen Shot 2019-11-22 at 1 54 10 PM](https://user-images.githubusercontent.com/30379428/69453083-27c4f800-0d31-11ea-86e3-b4e7075202ad.png)
![Screen Shot 2019-11-22 at 1 54 59 PM](https://user-images.githubusercontent.com/30379428/69453092-2c89ac00-0d31-11ea-916d-2b9fe7f7cf43.png)
Consider what if the users click the blue area out of the checkbox

![Screen Shot 2019-11-22 at 2 25 39 PM](https://user-images.githubusercontent.com/30379428/69454344-01548c00-0d34-11ea-9f55-4de857384a6e.png)

Should be something like this which is more reasonable in this case.
#### Please provide relevant source code if applicable.
See above

**Comment by JKMarkowski** [comment]
Hello @cstechfoodie, could you provide your NGX version? The latest 0.12.0 has removed `fd-list-checkbox`. [Here](https://github.com/SAP/fundamental-ngx/wiki/0.12.0-Breaking-changes#list-component) is example how you can replace it.
