### ISSUE TITLE
Publish fundamental ngx 0.11.0 - 0.13.0 to npm

### ISSUE THREAD

**Issue by zbug** [SAP/fundamental-ngx#1672]
#### Briefly describe your proposal.
Please publish fundamental ngx 0.11.0 - 0.13.0 to npm or leave some instructions how to properly include fundamental ngx into any package.json

#### Which versions of Angular and Fundamental NGX are affected? 
Angular 8, using [latest published fundamental ngx](https://www.npmjs.com/package/fundamental-ngx) 0.10.0, see 

#### Details
I found your [breaking changes documentation](https://github.com/SAP/fundamental-ngx/wiki/0.12.0-Breaking-changes), that full ng 8 support would require Fundamental Ngx 0.12.0 at least. However, this is not yet published. 

Using Fundamentals ngx with Angular 8 is causing the following npm warnings: 
```
npm WARN fundamental-ngx@0.10.0 requires a peer of @angular/common@^7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN fundamental-ngx@0.10.0 requires a peer of @angular/core@^7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN fundamental-ngx@0.10.0 requires a peer of @angular/forms@^7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN fundamental-ngx@0.10.0 requires a peer of @angular/animations@^7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN fundamental-ngx@0.10.0 requires a peer of rxjs@^6.5.2 but none is installed. You must install peer dependencies yourself.
```

I found other issues in this project, where people seemed to already consume 0.12.0 or 0.13.0. I assume this was individually compiled. We would like to establish a CI pipeline with hopefully not too many customisation. 

Thanks!

**Comment by JKMarkowski** [comment]
Hello @zbug, thanks for reporting the issue. Please take a look at [versioning](https://github.com/SAP/fundamental-ngx/tree/master/libs/core#3-versioning). We changed name of lib to `@fundamental-ngx/core` - [npm](npmjs.com/package/@fundamental-ngx/core).
0.12.0 version came with a lot of new [changes](https://github.com/SAP/fundamental-ngx/wiki/0.12.0-Breaking-changes). So it's better to get familliar before migrating project to upper version.
0.13.0 unfortunately hasn't been released yet.

**Comment by zbug** [comment]
Thanks a lot for clarification
