### ISSUE TITLE
Loading Spinner component not disappearing

### ISSUE THREAD

**Issue by rossgardt** [SAP/fundamental-ngx#1678]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Loading Spinner is not working

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
@fundmanetal-ngx/core 0.12

#### If this is a bug, please provide steps for reproducing it.
1. open the demo page for the component: https://sap.github.io/fundamental-ngx/#/core/loadingSpinner
2. In the second example, click on the "click to toggle loading" button

**Expected:**
Spinner disappears

**Actual:**
Spinner is still there

#### Please provide relevant source code if applicable.
n/a

#### Is there anything else we should know?
n/a

**Comment by droshev** [comment]
@rossgardt thank you for raising the issue. Btw all the loading spinners have been deprecated from Fiori 3. We are in process of bringing https://fundamental-styles.netlify.com/components/busy-indicator.html

**Comment by salarenko** [comment]
Cannot be reproduced
