### ISSUE TITLE
Closing fd-popover causes ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1683]
#### Is this a bug, enhancement, or feature request?

Maybe a bug or something wrong in our setup

#### Briefly describe your proposal.

In our project we make use of fd-popover to create a popover. This popover contains a select which allows to switch to a different language. When a new language has been picked the popover should close automatically. Unfortunately, closing the popover automatically after chosen a new language results in the following error message:

![image](https://user-images.githubusercontent.com/51904901/69869501-4e44df00-12ad-11ea-9412-44b572fe8747.png)

The error only occurs the first time when a language is switched. The next time a language is switched the error does not occur anymore.

The code of the popover component looks like this (I removed all code parts which have nothing to do with switching the language):

```
@Component({
  selector: 'profile-popover',
  templateUrl: './profile-popover.component.html',
  styleUrls: ['./profile-popover.component.scss']
})
export class ProfilePopoverComponent {
  public selectedLanguageCode$: Observable<string | null>;
  private subscriptions: Subscription[];

  public isOpen: boolean;

  constructor(
    private translateProviderService: TranslateProviderService,
    private popoverService: PopoverService
  ) {
    this.subscriptions = [];
  }

  public onOpenChange(isOpen: boolean) {
    if (isOpen) {
      this.initialize();
    } else {
      this.destroy();
    }
  }

  public initialize() {

    this.subscriptions.push(this.popoverService.getCloseEmitter().subscribe(() => {
      this.isOpen = false;
      this.onOpenChange(false);
    }));
	
    this.selectedLanguageCode$ = this.translateProviderService.getSelectedlocale();
  }
  
  public updateLanguage(_languageCode: string) {
    this.subscriptions.push(
      this.translateProviderService.setSelectedLocale(_languageCode).subscribe()
    );

    this.popoverService.getCloseEmitter().emit();
  }

  public destroy() {
    for (const subscription of this.subscriptions) {
      if (!!subscription) {
        subscription.unsubscribe();
      }
    }
  }

}
```

The code of the select in the popover looks like this:

![image](https://user-images.githubusercontent.com/51904901/69870125-353d2d80-12af-11ea-936e-36bdb5a6853e.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

0.12.0

**Comment by JKMarkowski** [comment]
Hello @kistll, could you check how dies it work with latest RC version? It could get fixed along with introducing `onPush` strategy

**Comment by kistll** [comment]
@JKMarkowski  Thx for your help. 

Error could be solved by refactoring code and using 

```
public ngAfterViewInit() {
    this.changeDetectorRef.detectChanges();
}
```

See https://stackoverflow.com/questions/34364880/expression-has-changed-after-it-was-checked for more details.
