### ISSUE TITLE
 Complex i18n. Datepicker & DatetimePicker not working in stackblitz

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#1691]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
 Complex i18n. Datepicker & DatetimePickernot working in stackblitz
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
current

**Comment by droshev** [comment]
@stefanoScalzo what is the status of this issue?
