### ISSUE TITLE
[FEATURE REQUEST] Combobox input field has a closing cross to clear Combobox input field

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1709]
#### Is this a bug, enhancement, or feature request?

feature request

#### Briefly describe your proposal.

It would be nice to have a closing cross or the like in the Combobox input field to clear the input field of a combo box. It could look similar to the following screenshot:

![image](https://user-images.githubusercontent.com/51904901/70223350-e1699300-174b-11ea-8265-37870f727074.png)

**Comment by droshev** [comment]
you can use the search field for that purpose https://fundamental-ngx.netlify.app/#/platform/search-field
