### ISSUE TITLE
Menu items are not correctly aligned

### ISSUE THREAD

**Issue by d067006** [SAP/fundamental-ngx#1713]
This is a BUG

I would like to see the items of  "**Menu with Addon**" aligned

Angular version: **8.1.0**
NGX: **0.12.0**
Fundementals: **0.3.0**

**Steps to reproduce:**
Simply copy paste " Menu with Addon" example from [ngx page](https://sap.github.io/fundamental-ngx/#/core/menu) .. items and their icon are not aligned. ( even in the example itself).

#### Please provide relevant source code if applicable:
           <fd-menu fd-menu-addon>
                        <ul fd-menu-list>
                            <li>
                                <div fd-menu-item-addon>
                                    <fd-icon [glyph]="'edit'"></fd-icon>
                                </div>
                                <a fd-menu-item (click)="editHeader()">{{ 'FLD_FlowHeader_EditHeader_A' | translate }}
                                </a>
                            </li>
                            <li>
                                <div fd-menu-item-addon>
                                    <fd-icon [glyph]="'copy'"></fd-icon>
                                </div>
                                <a fd-menu-item (click)="copyFlow()">{{ 'FLD_FlowHeader_CopyFlow_A' | translate }}</a>
                                <div id="item-delete-flow"  *ngIf="!flowState.flowChanged ? true : false">
                                    <div fd-menu-item-addon >
                                        <fd-icon [glyph]="'delete'"></fd-icon>
                                    </div>
                                    <a fd-menu-item (click)="deleteFlow()">{{ 'FLD_FlowHeader_DeleteFlow_A' | translate }}</a>
                                </div>
                            </li>
                            
                            <li>
                                <div *ngIf="showDownloadButton" fd-menu-item-addon>
                                    <fd-icon [glyph]="'download'"></fd-icon>
                                </div>
                                <a *ngIf="showDownloadButton" [href]="flow_href" fd-menu-item [href]="flow_href"
                                    download="{{flowState.flow.name}}.json">Download
                                    Flow</a>
                            </li>
                        </ul>
                    </fd-menu>

![image](https://user-images.githubusercontent.com/52275838/70312042-1bea3300-1813-11ea-8fdb-acb91e2d476a.png)

#### Is there anything else we should know?
 The bug can be also seen here https://sap.github.io/fundamental-ngx/#/core/menu

**Comment by salarenko** [comment]
Should be fixed with: https://github.com/SAP/fundamental-styles/issues/466

**Comment by JKMarkowski** [comment]
It's fixed on `fundamental-styles` 0.4.0
