### ISSUE TITLE
Missing dependency lib @angular/cdk

### ISSUE THREAD

**Issue by ivijan** [SAP/fundamental-ngx#1720]
#### Error during compilation:

`
10% building 3/3 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.06 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 122 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.11 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2019-12-09T09:40:09.466Z - Hash: 1cde30e072b1a43b76ce - Time: 5084ms

ERROR in node_modules/@fundamental-ngx/core/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.d.ts:2:38 - error TS2307: Cannot find module '@angular/cdk/drag-drop'.

2 import { CdkDrag, CdkDragMove } from '@angular/cdk/drag-drop';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/core/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.d.ts:2:29 - error TS2307: Cannot find module '@angular/cdk/drag-drop'.

2 import { CdkDragMove } from '@angular/cdk/drag-drop';
                              ~~~~~~~~~~~~~~~~~~~~~~~~

Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.

`

**Comment by JKMarkowski** [comment]
Hello @ivijan, On version 0.12.1 we added `@angular/cdk` to schematics, so after writing `ng add @fundamental-ngx`, you will have `@angular/cdk` installed. 
In general we keep it in `peerDependency`, so it's not installed automatically for version conflicts reason. 
In this case I tried to follow other angular libraries such as `@angular/material`
