### ISSUE TITLE
core: Date picker is  messed up

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#1721]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

I just check latest ngx core ^0.13.0-rc.80 and when I tested DatePicker this is what I get:

<img width="746" alt="Screen Shot 2019-12-09 at 7 28 48 PM" src="https://user-images.githubusercontent.com/17149942/70462247-ce8fef00-1aba-11ea-99fc-4721c30247ca.png">

Usage is simple:
```html
<fd-date-picker #elementRef
                [(ngModel)]="fdDate"
                [disabled]="disabled"
                [compact]="compact"
                [type]="type">

</fd-date-picker>
```

**Comment by Aqebutto** [comment]
Same issue. Works in Chrome. But safari and iE breaks the calender.
