### ISSUE TITLE
popover text wrap not working

### ISSUE THREAD

**Issue by kandarp-sap** [SAP/fundamental-ngx#1728]
I am using fd-popover to display text which is ellipsis on screen. However, popover not display whole text inside the box. The text went out of the box. I have used property of ` word-wrap: break-word`
but still not working. 

Full code as follows

```
            <p class="ext-description-overflow" #flowDescription placement="bottom"
                [triggers]="['mouseenter', 'mouseleave']" 
                [noArrow]="false" 
                [fdPopover]="hoverTemplate">
                {{flowState.flow.description}}
            </p>
            <ng-template #hoverTemplate>
                <div class="fd-has-padding-small ext-description-tooltip">
                    {{flowState.flow.description}}
                </div>
            </ng-template>
```
Css class to wrap text,

```
.ext-description-tooltip {
    width: 150px; 
    border: 1px solid #000000;
    overflow-wrap: break-word;
    word-wrap: break-word;
    display: block;
    
    -ms-word-break: break-all;
    /* This is the dangerous one in WebKit, as it breaks things wherever */
    word-break: break-all;
    /* Instead use this non-standard one: */
    word-break: break-word;
    
    /* Adds a hyphen where the word breaks, if supported (No Blink) */
    -ms-hyphens: auto;
    -moz-hyphens: auto;
    -webkit-hyphens: auto;
    hyphens: auto;
}
```

However  it is not working,
<img width="640" alt="Screenshot 2019-12-11 at 18 36 42" src="https://user-images.githubusercontent.com/51914152/70623997-48ec7a80-1c45-11ea-82a1-914f436493f6.png">

Moreover, as you can see this control is popover and I used it for tooltip. Do NGX fundamentals provide any specific control to display tooltip ??

**Comment by loeper** [comment]
Hi colleagues, are there any updates regarding this ticket? Or do you have any suggestion how to implement a very long tooltip?
Thanks and regards, Stefanie

**Comment by loeper** [comment]
Hi colleagues, i solved the issue for me by using css style
white-space: normal;
Seems that white-space is set with nowrap by default.
Regards, Steffi
