### ISSUE TITLE
FdDate: nextDay in January does always increase also the year

### ISSUE THREAD

**Issue by agugger** [SAP/fundamental-ngx#1740]
#### Is this a bug, enhancement, or feature request?
It's a Bug.

#### Briefly describe your proposal.
run `nextDay()` function on a FdDate object in January in future years always increases the year too. 

This happens only for dates in January. Doesn't matter if 2020 or 2021.
For the 31. December 2019 it works correct -> 1. January 2020
For the 31. January 2020 it works also correct -> 1. February 2020

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
@fundamental-ngx/core: 0.13.0-rc.88

#### If this is a bug, please provide steps for reproducing it.
1. Select a date in January with the DatePicker (ex. 3/1/2020)
2. Log this selected FdDate -> It shows the correct date. (day: 3, month: 1, year: 2020)
3. Add a day with the `nextDay()` function
4. Log this next date -> It shows the day after the selected, but in the next year (day: 4, month: 1, year: 2021)

#### Is there anything else we should know?
Maybe because I try it now in December for future years.

**Comment by JKMarkowski** [comment]
PR is merged (newest RC version).
