### ISSUE TITLE
Input group styles need update after fundamental-styles upgrade

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#1741]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Any component which uses the fundamental-styles `input-group` CSS styles needs to be revisited, after the upgrade to fundamental styles 0.4.x. There was a refactor of the input group styles in fundamental-styles, which is affecting the display of the current fundamental-ngx components.

https://github.com/SAP/fundamental-styles/blob/master/CHANGELOG.md#features-2

**Screenshot:**
![Screen Shot 2019-12-17 at 7 44 52 AM](https://user-images.githubusercontent.com/48103491/71010777-28874a80-20a1-11ea-9b20-0080900605e2.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 8
Fundamental NGX 0.13.0

#### If this is a bug, please provide steps for reproducing it.
1. Pull latest version of fundamental-ngx
2. Build and start docs applications `npm start`
3. Open browser and goto http://localhost:4200/fundamental-ngx#/core/inputGroup
4. Additionally goto http://localhost:4200/fundamental-ngx#/core/combobox

**Result:** The display of the input group has double borders and wrong sized buttons.

**Comment by droshev** [comment]
@KevinOkamoto this is a plan activity, but if you want to do it then you can use the ticket to do the migration

**Comment by droshev** [comment]
we have already addressed it
