### ISSUE TITLE
Weird class hierarchy behaviour, when AbstractFdNgxClass is used

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#1759]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
We should fix or get rid of `AbstractFdNgxClass`. It provides a unexpected changes on class hierarchy.
So having example of most used `fd-button` component. Sometimes we want to add different classes manually, by passing `class=""`. Classes added by `class=""` are shadowed, by classes from `AbstractFdNgxClass` method. We should keep the hierarchy of classes, because otherwise we will need to add some styles manually.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Newest

**Comment by rengare** [comment]
working on it

**Comment by droshev** [comment]
@JKMarkowski could you document more information regarding the issue?

**Comment by JKMarkowski** [comment]
@droshev Sure, It's on my way.
