### ISSUE TITLE
NotificationModule 

### ISSUE THREAD

**Issue by urielrodriguezusma** [SAP/fundamental-ngx#1764]
Hello.

I try to use the NotificationModule module but I can't find it in the path contained in the documentation. Is it possible that this path has changed?

Thanks for your help.

![Notification](https://user-images.githubusercontent.com/36137028/71480892-8fa3ae00-27c9-11ea-9f20-f957920321e9.png)

**Comment by JKMarkowski** [comment]
Hi @urielrodriguezusma, what is your NGX version?

**Comment by urielrodriguezusma** [comment]
> Hi @urielrodriguezusma, what is your NGX version, because Notification Module has been added on version `0.12.0`.

Hi JKMarkowski in my project the current version is 0.3.3 
Thanks for the info.
