### ISSUE TITLE
Bug - Date time-picker

### ISSUE THREAD

**Issue by Jagoooo** [SAP/fundamental-ngx#1796]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
https://sap.github.io/fundamental-ngx/#/core/datetime-picker

We need an Angular & React version

Can it also be updated in 'Fundamental Styles'?

It should have locale support for the dates

It should be range compatible. Meaning it greys out date previously selected. eg so you cannot 
click and end date before a start date (I believe it used to support this)

It needs zeros to be added. See image below

![Unknown](https://user-images.githubusercontent.com/38916020/72082482-1f804680-32f8-11ea-95bd-87480890880a.jpeg)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

All versions.

#### Is there anything else we should know?
 We need urgently as may of our applications in Context-driven services are now broken. They are currently being used by customers.

**Comment by mikerodonnell89** [comment]
@JKMarkowski i see this was merged on jan 13 but still appears to be an issue in the latest release

**Comment by JKMarkowski** [comment]
It's working fine, we can close this issue
