### ISSUE TITLE
Test the latest changes before 0.13.0 release

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1811]
We need to smoke test the latest changes we added to the library before we release 0.13.0

- bugs
- a11y
- different browsers

# Checkbox (Michal)
 * tristate - IE11

# Combobox (Jedrzej) - on PR / Partially Done
* missing icons on the input, Open State Control, rounded corners for the button (all browsers), Input groups border radius issue

# DatePicker - IE11 - Done
<img width="320" alt="Screen Shot 2020-01-15 at 9 36 26 AM" src="https://user-images.githubusercontent.com/39598672/72442773-22a58780-377b-11ea-8836-ed4a46723adc.png">

# Safari - DateTimePicker - Done
<img width="199" alt="Screen Shot 2020-01-15 at 9 44 04 AM" src="https://user-images.githubusercontent.com/39598672/72443046-a790a100-377b-11ea-9ff1-4d80dc23a79f.png">

<img width="700" alt="Screen Shot 2020-01-15 at 9 44 04 AM" src="https://user-images.githubusercontent.com/39598672/72443698-b2980100-377c-11ea-8b10-f79ceeb08449.png">

# Input (All Browsers): (Stefano)
<img width="951" alt="Screen Shot 2020-01-15 at 9 51 26 AM" src="https://user-images.githubusercontent.com/39598672/72443676-ab70f300-377c-11ea-8b9e-dcb6643cdad0.png">
<img width="978" alt="Screen Shot 2020-01-15 at 9 51 04 AM" src="https://user-images.githubusercontent.com/39598672/72443686-add34d00-377c-11ea-9466-3980638685b0.png">

# Input Edge and IE11 - Couldn't reproduce anymore / button truncate fixed on styles:
<img width="984" alt="Screen Shot 2020-01-15 at 9 53 38 AM" src="https://user-images.githubusercontent.com/39598672/72443887-086ca900-377d-11ea-8608-fda3e89cd3d0.png">

<img width="1460" alt="Screen Shot 2020-01-15 at 9 57 52 AM" src="https://user-images.githubusercontent.com/39598672/72444175-8e88ef80-377d-11ea-90b7-d727821d5d6a.png">

# MultiInput: (Mike) - done
* remove the empty popover body:
<img width="1083" alt="Screen Shot 2020-01-15 at 10 07 09 AM" src="https://user-images.githubusercontent.com/39598672/72444955-eecc6100-377e-11ea-8ae8-485976054392.png">

* Open/close behavior for the MultiInput

* Safari: disabled input still has click events - on PR
<img width="1041" alt="Screen Shot 2020-01-15 at 10 10 19 AM" src="https://user-images.githubusercontent.com/39598672/72445212-5da9ba00-377f-11ea-8d3b-96c157dee5ce.png">

# Radio Buttons - IE11 (Gracjan) - Done
<img width="1477" alt="Screen Shot 2020-01-15 at 10 13 32 AM" src="https://user-images.githubusercontent.com/39598672/72445671-140d9f00-3780-11ea-974d-10fc424476ef.png">

# Textarea - all browsers (Stefano)
* States should be in popover
<img width="922" alt="Screen Shot 2020-01-15 at 10 19 31 AM" src="https://user-images.githubusercontent.com/39598672/72446131-f5f46e80-3780-11ea-9341-0fc7327ec2bf.png">

<img width="879" alt="Screen Shot 2020-01-15 at 10 19 39 AM" src="https://user-images.githubusercontent.com/39598672/72446138-f8ef5f00-3780-11ea-9b32-20fc25764e77.png">

# Time  (Jedrzej) - Done
<img width="492" alt="Screen Shot 2020-01-15 at 10 24 37 AM" src="https://user-images.githubusercontent.com/39598672/72446292-49ff5300-3781-11ea-8de7-9e0d538b12a2.png">

* All browsers - padding issue - Done
* Edge and IE11 - up and down arrows in the input

# TimePicker (Jedrzej) - Done
<img width="459" alt="Screen Shot 2020-01-15 at 10 27 36 AM" src="https://user-images.githubusercontent.com/39598672/72446568-cf830300-3781-11ea-801d-622114e3b7b1.png">

<img width="474" alt="Screen Shot 2020-01-15 at 10 32 26 AM" src="https://user-images.githubusercontent.com/39598672/72446890-5e901b00-3782-11ea-8931-690be345ef62.png">
<img width="511" alt="Screen Shot 2020-01-15 at 10 32 16 AM" src="https://user-images.githubusercontent.com/39598672/72446891-5e901b00-3782-11ea-88b2-1e46a4d736cb.png">
<img width="402" alt="Screen Shot 2020-01-15 at 10 33 18 AM" src="https://user-images.githubusercontent.com/39598672/72446944-78316280-3782-11ea-8d25-cef76f9c538d.png">

**Comment by JKMarkowski** [comment]
`Combobox` - wrong value on `openChange`  event

**Comment by mikerodonnell89** [comment]
Re: multi-input "Disabled input still has click events", the disabled input still throws a click event on Chrome, it just looks to me like browsers color the disabled + focused elements differently
