### ISSUE TITLE
Fiori Component Requiest - Dynamic Side Content

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental-ngx#1812]
The Commerce Domain Services are requesting the dynamic side content component. 

Here is the wire:

![image](https://user-images.githubusercontent.com/24274321/72375376-58e2f880-36e2-11ea-8fa9-95d3447229ba.png)

Please contact Jeanne Walters for any further information.

**Comment by droshev** [comment]
@InnaAtanasova do you think we can sync up with the designers regarding the latest spec?

**Comment by droshev** [comment]
i guess this is not valid anymore
