### ISSUE TITLE
Input Group icon broken in IE

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-ngx#1813]
The icons in Input Group is broken.

<img width="635" alt="Annotation 2020-01-14 155852" src="https://user-images.githubusercontent.com/54589269/72382240-d90b5d00-36e6-11ea-9d74-2d199a76999f.png">
<img width="635" alt="Annotation 2020-01-14 155924" src="https://user-images.githubusercontent.com/54589269/72382242-d9a3f380-36e6-11ea-87d7-8a15ca578af7.png">

**Comment by InnaAtanasova** [comment]
I will close this issue. it's documented in  [1811](https://github.com/SAP/fundamental-ngx/issues/1811)
