### ISSUE TITLE
Cannot compile side navigation from fundamental-ngx v0.13.0

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1849]
#### Is this a bug, enhancement, or feature request?

Maybe a bug but probably something missing

#### Briefly describe your proposal.

When I try to compile the side navigation icon example from https://sap.github.io/fundamental-ngx/#/core/sideNavigation#withIcons I'll receive the following error messages:

```
ERROR in Can't bind to 'glyph' since it isn't a known property of 'span'. ("sted-list-item>
              <a fd-nested-list-link>
                  <span fd-nested-list-icon [ERROR ->][glyph]="'menu'"></span>
                  <span fd-nested-list-title>Link 1</span>
              <")

...

Can't bind to 'textOnly' since it isn't a known property of 'ul'. ("     <span fd-nested-list-title>Link 3</span>
              </a>
              <ul fd-nested-list [ERROR ->][textOnly]="true">
                  <li fd-nested-list-item>
                      <a fd-nested-li")

```

Did I miss something? SideNavigationModule is imported in the app.module.ts.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

v0.13.0

**Comment by JKMarkowski** [comment]
Hello @kistll make sure you imported `NestedListModule` to module.

**Comment by kistll** [comment]
Hello @JKMarkowski,
Thx for your quick help, now it works.
