### ISSUE TITLE
Condensed side navigation does not look like expected (version 0.13.0)

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#1850]
#### Briefly describe your proposal.

In case condensed equals false, the side navigation looks like this, which matches the expectations: 

![image](https://user-images.githubusercontent.com/51904901/72817960-f4d4ad00-3c6a-11ea-9f0b-7aa6a1525346.png)

In case condensed equals true, the side navigation looks like this, which does not match the expectations: 

![image](https://user-images.githubusercontent.com/51904901/72817786-ac1cf400-3c6a-11ea-8e3a-60ae73556586.png)

The width has not been changed and is as big as condensed would equals false. Expectation would be to have a reduced width of the side navigation which has only space to show the icons.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

version 0.13.0

**Comment by JKMarkowski** [comment]
Caused by other library's css.

**Comment by droshev** [comment]
@JKMarkowski  can you write more info so we can use this issue in the future?
