### ISSUE TITLE
Datepicker is missing some padding from fd-styles

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#1859]
#### Is this a bug, enhancement, or feature request?
visual bug

#### Briefly describe your proposal.
Especially on the sides, the date picker is missing some padding. Makes the component look pretty weird. Considering the date picker is one of the more important components for the library's reputation, it should look good.

**Comment by salarenko** [comment]
Should be addressed to https://github.com/SAP/fundamental-styles.
Is going to be changed with https://github.com/SAP/fundamental-styles/pull/506.
