### ISSUE TITLE
Checkbox visual state different than control state

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#1887]
This is a bug in `CheckboxComponent`

#### If this is a bug, please provide steps for reproducing it.

- Go to: [Multi input example](https://sap.github.io/fundamental-ngx/#/core/multi-input#simpleMultiInput)

- Click on the edge of element list inside popover

- **Checkbox visual state has been updated, but checkbox control state stays the same**

#### Is there anything else we should know?

Checkbox control updates its state on checkbox label click. In this case HTML binds additional label wrapping component with checkbox input and updates input state not triggering checkbox control state update.

**Comment by JKMarkowski** [comment]
Fixed
