### ISSUE TITLE
document how to generate release notes manually

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1905]
#### Briefly describe your proposal.
Create a wiki listing the steps how to generate a release notes manually in case the release script fails

**Comment by JKMarkowski** [comment]
I created some wiki page with this case: 
https://github.com/SAP/fundamental-styles/wiki/Manually-Generate-Release-Notes

**Comment by Vanessa-Cusmich** [comment]
I made some changes to the documentation. Please review to make sure that the content is accurate before closing the issue.

**Comment by droshev** [comment]
🚢 LGTM
