### ISSUE TITLE
update documentation: how to use fundamental-ngx under IE11

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1907]
#### Is this a bug, enhancement, or feature request?
documentation
#### Briefly describe your proposal.

- document in how to use ngx application locally (disabling IVY as it doesn't work under IE11)
- create a separate tsconfig file for netlify

**Comment by rengare** [comment]
Wiki page how to run project locally in IE11 https://github.com/SAP/fundamental-ngx/wiki/Run-project-locally-in-IE11
