### ISSUE TITLE
When typing 2 spaces consecutively in the Input field,  a "." is showing up

### ISSUE THREAD

**Issue by yingzhou03** [SAP/fundamental-ngx#1914]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
When typing 2 spaces consecutively in the Input field,  a "." is showing up.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current version

#### If this is a bug, please provide steps for reproducing it.
This bug can be reproduced in https://sap.github.io/fundamental-ngx/#/core/input. Please refer to the following screenshots for the detail.
1) Chrome:
![Screen Shot 2020-02-04 at 3 21 54 PM](https://user-images.githubusercontent.com/53583995/73798779-c7a6f500-4768-11ea-93d7-ae54f92383a3.png)

2) Firefox
![Screen Shot 2020-02-04 at 3 20 34 PM](https://user-images.githubusercontent.com/53583995/73798793-d1c8f380-4768-11ea-9eef-049c41d56c10.png)

We can also find the behavior on Chrome is slightly different from that on Firefox, when we type two consecutive spaces.
1) on Chrome, the first space is kept, and the second space is replaced by ".";
2) on Firefox, the first space is replaced by "." after typing two consecutive spaces;

**Comment by JKMarkowski** [comment]
Hello @yingzhou03 I can't reproduce it. Make sure you don't use any external software that provides such a thing.

**Comment by yingzhou03** [comment]
@JKMarkowski could you please type this string: "aaa aaa aaa  ", and you will see the last one space will be changed to one dot, thanks

**Comment by JKMarkowski** [comment]
@yingzhou03 We don't provide anything related to such a issue. As I remember some browsers/operation systems transform 2 spaces to dot. Could you provide some info about your operation system?

**Comment by rengare** [comment]
@yingzhou03 can you test this in browser's private mode without extension? We cant reproduce the issue

**Comment by yingzhou03** [comment]
@JKMarkowski, your guess is right. I found that MacOs has a default option in Keyboard: Add period with double-space. 
This is not a bug, and thank you guys for the help!
