### ISSUE TITLE
Not able to get combobox search-term that is not matching to the given options

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#1928]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.

Hi Fundamental Team,

we have an issue with the combobox "fd-combobox", because it gives us just the valid values back. In our case, we are using the combobox for searching & selecting items. There could be thousands of items, therefore we are just loading the top 20 items and give them to the combobox. In case that the user is entering some characters, then we would use these characters to request the top 20 items that are matching with these characters. This is not working now, because the combobox is just giving a value (to the change listener) that matches to the initial top 20 items.

```xml
<fd-combobox [communicateByObject]="true" formControlName="items.control.name" [dropdownValues]="(dropdownItems$ | async)" [placeholder]="" [filterFn]="dropdownFilterFn"></fd-combobox>
```
In the above html you can see that we are binding the element with the *formControlName*. We are also using the *filterFn*, because the items are objects and no string values.

```javascript
formGroup.controls['items.control.name'].valueChanges.pipe(
     map((inputValue) => {
          // If inputValue don't match with an item, then we do a request of the top 20 items that contains the characters on the inputValue.
     })
).subscribe()
```
In the code you can see how we listen to the changes. We are using the *valueChanges* observer of the form-control. This will be triggered in case if the user is entering some character or if the user is selecting an item. In the first case, the *inputValue* will be undefined, even if there are characters in the combobox-field. This is our problem here. We also checked the control object inside the map(...), but nothing helpful there. The combobox is just giving a non-undefined *inputValue* if it is matching to the dropdown options.

What we also tried was the **[(ngModel)]** to bind the InputValue as described in the [combobox doc](https://sap.github.io/fundamental-ngx/#/core/combobox/api), but unfortunately, Angular is not letting you using *formControlName* and *ngModel* in the same time if you have Angular 7+. You will get log-message with the description in the console.

There is also the *searchFunction* API from the combobox, but it will just be triggered if the user presses the Enter key. Additionally, it doesn't include the searchTerm as parameter.

It would be at best for us, if we can handle the value in the *valueChanges* API where we also handle the rest of the businessLogic. Here we just need to get access to the inputValue, which is not matching to the dropdown options.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
"@angular/core": "^8.2.7",
"@fundamental-ngx/core": "^0.13.1",
"fundamental-styles": "^0.4.1",

**Comment by droshev** [comment]
@JKMarkowski @rengare can you take a look?

**Comment by JKMarkowski** [comment]
Hello @zaheral 
If I understood correctly, it can be [solution](https://stackblitz.com/edit/angular-usqnbc?file=src/app/combobox-forms-example.component.ts). I used `inputText` from combobox reference.
Let me know if that's exactly what you needed.

**Comment by zaheral** [comment]
Hi @JKMarkowski 
the static combobox is a great way to get the dirty value. But in my case, it is seven comboboxes instead one. Therefore, it doesn't work for me. When I try to get the dirty value (`this.combobox.inputText`) in the formControl of a combobox, then I get the inputText value of a different combobox. Is there a way how to create several static comboboxes and reference them to an exactly field?

**Comment by JKMarkowski** [comment]
Hello @zaheral, you can do it in several ways
1. This [example](https://stackblitz.com/edit/angular-usqnbc-8fp4le?embed=1&file=src/app/combobox-forms-example.component.ts) shows usage of `(ngModelChange)`, which can also be used with `formControl`
2. You can create more `ViewChild('comboboxFirst) ViewChild('comboboxSecond)` and then use `<fd-combobox #comboboxFirst>` and `<fd-combobox #comboboxSecond>`
3.  Add additional properties with `prototype` to `FormControlName` [example](https://stackblitz.com/edit/angular-usqnbc-exyc1n?file=src/app/combobox-forms-example.component.ts)
4. If it's not needed yo ucan also set `[communicateByObject]="false"`, to always have value of string input as form Value

**Comment by zaheral** [comment]
Hi @JKMarkowski ,
thank you very much for these options. The second option worked for me.
Best Regards, Zaher
