### ISSUE TITLE
Giving a range to fd-input-group-number

### ISSUE THREAD

**Issue by TangMichael** [SAP/fundamental-ngx#1929]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Give the option to give the input a range of accepted number such as no negative number. Something like this: https://www.w3schools.com/tags/att_input_min.asp

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
0.13.1

**Comment by droshev** [comment]
@salarenko can you consider this issue in #2386
