### ISSUE TITLE
fundamental style classes are unavailable in version 0.13.0 fundamental-ngx/core

### ISSUE THREAD

**Issue by rakshetha-jn** [SAP/fundamental-ngx#1936]
#### Is this a bug, enhancement, or feature request?
Bug , color classes and other classes from fundamental-styles.css are unavailable 
ex: --fd-color-neutral-3, fd-has-type-1, .fd-has-padding-tiny

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
migrated from fundamental 0.10 to fundamentals 0.13 

#### If this is a bug, please provide steps for reproducing it.
Followed the steps described in the full installation guide

#### Please provide relevant source code if applicable.

this is the entries in my package.json
   "@fundamental-ngx/core": "^0.13.1",
    "chart.js": "^2.9.3",
    "fundamental-ngx": "^0.10.0",
    "fundamental-styles": "^0.3.0",
    "lodash": "^4.17.15",

angular.json 
![image](https://user-images.githubusercontent.com/60785445/74138985-dcfda280-4bf2-11ea-9766-2acb632ddb87.png)

#### Is there anything else we should know?

Is this a breaking change as well ? will there be a different concept for styles / colors in 0.13 ?

**Comment by droshev** [comment]
@rakshetha-jn all the `--fd-color` are not Fiori 3 and are being phased out.
What we started adopting is https://github.com/SAP/theming-base-content and the css variables as those colors are themable.

**Comment by rakshetha-jn** [comment]
thanks for the support,  appreciate the help.
