### ISSUE TITLE
Stackblitz doesn't work

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#1939]
#### Is this a bug, enhancement, or feature request?
fix
#### Briefly describe your proposal.
Stackblitz is taking `latest` versions of `@angular` and related npm packages. We should have same versions, as on docs page.

**Comment by yor101** [comment]
If you mean the "Getting started with Angular" course, yes it is not working. I was trying the course saterday and it wasn't working then either
