### ISSUE TITLE
Product switch styles not looking proper with shellbar

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#1953]
**Describe the bug**
Product switch grid and background colors not being displayed due to rendering of the component places fd-product-switch__control under fd-button
- [ ] color for shellbar
- [ ] dots outside of styles
> Is this issue related to a specific component?
product-switch
> What version of the Fundamental Styles are you using?
0.3
> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**Screenshots**

![Screen Shot 2019-10-30 at 9 38 01 AM](https://user-images.githubusercontent.com/50607147/67862821-37b63700-faf9-11e9-9038-28bb27b22be7.png)
![Screen Shot 2019-10-30 at 9 37 54 AM](https://user-images.githubusercontent.com/50607147/67862823-37b63700-faf9-11e9-89d3-63d947550196.png)

**Comment by droshev** [comment]
This will be done once the shellbar is being released in styles and adopted in ngx https://github.com/SAP/fundamental-ngx/issues/1852
