### ISSUE TITLE
storybook tests for Fiori 3 components

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#1954]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.

create storybooks for the following components
- [x] breadcrumb
- [x] input
- [x] inline help
- [x] input group
- [x] input states
- [x] textarea
- [ ] form select
- [x] link
- [x] notifications
- [x] product switch
- [x] side navigation

**Comment by stefanoScalzo** [comment]
@droshev form select as in select component or checkbox/radio ?
