### ISSUE TITLE
fix(platform): Extends docs example for Select

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#1963]
#### Is this a bug, enhancement, or feature request?
More like a enhacements but ...

#### Briefly describe your proposal.

Select also supports custom templating where developer is able to customize also the individual items. Please extends a example to showcase this.. 

```html
<fdp-select ...>
  <ng-template #item let-item>
       // my custom item with icon
   <ng-template>
</fdp-select >

```

**Comment by droshev** [comment]
@manjunathanagaraj is this still valid?

**Comment by droshev** [comment]
@manjunathanagaraj ?

**Comment by droshev** [comment]
closing it since @manjunathanagaraj didn't respond
