### ISSUE TITLE
Fundamentals Ngx to Fundamentals Ngx Core

### ISSUE THREAD

**Issue by camilo2312** [SAP/fundamental-ngx#1966]
Hi everyone

I try to update my Fundamentals Ngx to Fundamentals Bgx Core, but when I try to do so I get the following error

![image](https://user-images.githubusercontent.com/42982644/74536276-c4003480-4f05-11ea-998a-d19aaf4be9d1.png)

I also want to know if there is any guide or procedure that allows me to update my library

Thank you

**Comment by JKMarkowski** [comment]
Hello @camilo2312 
Take a look at [breaking changes](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes) on out wiki page. Every breaking change is described there, also please take a look at examples on [docs page](https://sap.github.io/fundamental-ngx/docs/home). It's currently `0.13.1`, but soon it we will release `0.14.0`
