### ISSUE TITLE
Defect hunting Feb14

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#1967]
- [x] Keyboard service used in tabs is not really supported in RTL mode. The ArrowKeys should also behave inversely. - JEDRZEJ

- [x] All browsers: Table needs new checkbox - STEFANO 
![Screen Shot 2020-02-14 at 10 02 53 AM](https://user-images.githubusercontent.com/50607147/74542375-75f12e00-4f11-11ea-904b-79a231f29880.png)

- [x] All browsers: Fix typo should say without seconds - TYPO - INNA
![Screen Shot 2020-02-14 at 10 10 07 AM](https://user-images.githubusercontent.com/50607147/74542821-50b0ef80-4f12-11ea-988e-060a403aaeb9.png)

- [x] Pagination on RTL - Mike
<img width="253" alt="Screen Shot 2020-02-14 at 10 20 55 AM" src="https://user-images.githubusercontent.com/4380815/74543662-c7022180-4f13-11ea-9ddb-e0e1860f0a75.png">

- [x] Scroll Spy arrow direction for RTL - Jedrzej
![Screen Shot 2020-02-14 at 10 21 28 AM](https://user-images.githubusercontent.com/50607147/74543700-d6816a80-4f13-11ea-90b5-fdecd70c2bc5.png)

- [x] All browsers: Add rtf for collapsed side nav - GRACJAN
![Screen Shot 2020-02-14 at 10 16 04 AM](https://user-images.githubusercontent.com/50607147/74543310-29a6ed80-4f13-11ea-9a7f-d3e614efcc8c.png)

**Comment by salarenko** [comment]
- [ ] Checkbox label prevents links inside custom label from receiving events (IE11)
![image](https://user-images.githubusercontent.com/17496353/74543994-a99a7b00-4f46-11ea-9b08-25aab3751094.png)

- [ ] Checkbox example doesn't works properly on. Should be `acceptAll: null` (IE11)
![image](https://user-images.githubusercontent.com/17496353/74544295-304f5800-4f47-11ea-800b-d42df66c7b49.png)

- [ ] Input addons have problems with rendering inside Input Group (IE11)
![image](https://user-images.githubusercontent.com/17496353/74544218-10b82f80-4f47-11ea-9981-63e3795fefa9.png)

![image](https://user-images.githubusercontent.com/17496353/74544260-2299d280-4f47-11ea-9bfb-6848cf2c7a5e.png)

- [ ] Blue font color on list elements (IE11) [link](http://localhost:4200/fundamental-ngx#/core/list#list-simple)
![image](https://user-images.githubusercontent.com/17496353/74544536-93d98580-4f47-11ea-8f87-86b19908f0ab.png)

- [ ] Button is not centered [link](http://localhost:4200/fundamental-ngx#/core/list#actionList)
![image](https://user-images.githubusercontent.com/17496353/74544660-cbe0c880-4f47-11ea-930d-6edcd1cfcaf6.png)

- [ ] Broken input layout in localization (IE11) [link](http://localhost:4200/fundamental-ngx#/core/localizationEditor#forms)
![image](https://user-images.githubusercontent.com/17496353/74544837-16624500-4f48-11ea-8c18-465ab01e02b5.png)

- [ ] Missing icons inside mega menu tabs (IE11) [link](http://localhost:4200/fundamental-ngx#/core/mega-menu#def)
![image](https://user-images.githubusercontent.com/17496353/74544955-51fd0f00-4f48-11ea-9c08-ea202e31005c.png)

- [ ] Modal has no background overlay and it is not centered (IE11) [link](http://localhost:4200/fundamental-ngx#/core/modal)
![image](https://user-images.githubusercontent.com/17496353/74545277-e1a2bd80-4f48-11ea-9359-20a47d5d3f2e.png)

- [ ] Missing border on Multi Input (IE11) [link](http://localhost:4200/fundamental-ngx#/core/multi-input)
![image](https://user-images.githubusercontent.com/17496353/74545368-0eef6b80-4f49-11ea-94c5-430dfb73e8af.png)

- [ ] Notification examples are not working (IE11, Chrome) [link](http://localhost:4200/fundamental-ngx#/core/notification)
![image](https://user-images.githubusercontent.com/17496353/74545622-76a5b680-4f49-11ea-9fa8-6b24c496c8e4.png)

**Comment by salarenko** [comment]
- [ ] Misaligned check icon (IE11) [link](http://localhost:4200/fundamental-ngx#/core/radio)
![image](https://user-images.githubusercontent.com/17496353/74545964-16634480-4f4a-11ea-94c5-2fdb2beafa30.png)

- [ ] Broken loading select example (IE11) [link](http://localhost:4200/fundamental-ngx#/core/select)
![image](https://user-images.githubusercontent.com/17496353/74546062-427ec580-4f4a-11ea-929c-121f620ed516.png)

- [ ] Broken styles for search in shellbar (IE11)
![image](https://user-images.githubusercontent.com/17496353/74546244-94bfe680-4f4a-11ea-86ba-905471bd2208.png)

**Comment by stefanoScalzo** [comment]
How are the notifications not working?

**Comment by stefanoScalzo** [comment]
@salarenko list is actually just a href. I think it's done intentionally? @InnaAtanasova

**Comment by salarenko** [comment]
> @salarenko How are the notifications not working?

Sorry, my bad. I've removed that one from the list.

**Comment by JKMarkowski** [comment]
> Checkbox label prevents links inside custom label from receiving events (IE11)
It's also on opera/chrome

**Comment by JKMarkowski** [comment]
> Modal has no background overlay and it is not centered (IE11)

No background is on styles. Centered is fixed.
