### ISSUE TITLE
Strange behavior with Notification examples

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#1972]
Clicking "Approve" makes the notification larger rather than dismissing it.  Should rewrite the examples so they behave more like you'd expect a notification to behave
![Screen Shot 2020-02-14 at 8 08 34 AM](https://user-images.githubusercontent.com/2471874/74542711-53571900-4f01-11ea-9659-f1875a3bb6e4.png)

**Comment by JKMarkowski** [comment]
There is no way to reproduce it, can you check it again ?
![notification](https://user-images.githubusercontent.com/26483208/74738470-431fa080-5257-11ea-94db-492c623d75b1.gif)
