### ISSUE TITLE
Combobox component migration

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2007]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
migrate `combobox` component reflecting fundamental-styles version `0.8.0` (including the mobile)

**Comment by mikerodonnell89** [comment]
Waiting for #2080 to get merged - changes to the menu keyboard service are needed for this story as well

**Comment by InnaAtanasova** [comment]
Hey @mikerodonnell89 could you also take a look at this issue during the migration?
[#2105](https://github.com/SAP/fundamental-ngx/issues/2105)
