### ISSUE TITLE
Bug: Stackblitz Null Injector for Platform Documentation

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#2020]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Stackblitz is not a provider in PlatformDocumentationModule.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 8

#### If this is a bug, please provide steps for reproducing it.
In latest release version,  go to platform/home and then select any component eg. Action bar/Link.
go to console, here you can find Null Injector Error for stackblitz.

**Comment by rengare** [comment]
duplicated #2009
