### ISSUE TITLE
Test the Documentation Site and Components on iPad

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2043]
The goals of this issue it to test Fundamental NGX on iPad and validate:
- [ ] test the Fundamental NGX is rendered properly and is accessible
- [ ] the component are rendered and behave as expected

**Comment by droshev** [comment]
@estelaxu3 what is the status of this issue?

**Comment by estelaxu3** [comment]
The documentation can be find at https://github.com/SAP/fundamental-ngx/issues/2064
I think the rest has been addressed by @JKMarkowski
