### ISSUE TITLE
Select: Standard Select drop down button

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-ngx#2053]
#### Bug
In standard select loading mode, the drop down button is not deactivated. 
https://sap.github.io/fundamental-ngx/#/core/select#standard
<img width="964" alt="Screen Shot 2020-02-21 at 1 55 09 PM" src="https://user-images.githubusercontent.com/54589269/75063103-2cc15100-54b2-11ea-9d0c-869f6b6d66d4.png">

**Comment by JKMarkowski** [comment]
I belive, it's gonna be fixed in https://github.com/SAP/fundamental-ngx/issues/2006
