### ISSUE TITLE
iPad visual testing: Button group RTL control issue

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-ngx#2062]
In button group when I use Simulate RTL for example Default Size with Toggle, it controls another example Default Size with Selected. 
https://sap.github.io/fundamental-ngx/#/core/buttonGroup#Button-l

![IMG_0019](https://user-images.githubusercontent.com/54589269/75178072-5f16bc80-5705-11ea-9882-2d7ba331d0f8.PNG)

**Comment by JKMarkowski** [comment]
It's not only iPad, it's general issue with repeating ids/names on rtl/background component
