### ISSUE TITLE
iPad visual testing: Menu icon not aligned 

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-ngx#2064]
The square in option 4 is not aligned with rest of the icons.
https://sap.github.io/fundamental-ngx/#/core/menu#addon

![IMG_0020](https://user-images.githubusercontent.com/54589269/75178498-33e09d00-5706-11ea-87a7-aced9f0b6d72.PNG)

**Comment by JKMarkowski** [comment]
It's again not only iPad issue. The element used in example is native `checkbox input`, which means that it's not styled by us, but by default styling of browser/device. We should change this example on docs.

**Comment by JKMarkowski** [comment]
It's gonna be fixed with new menu's PR

**Comment by salarenko** [comment]
Closed with #2524
