### ISSUE TITLE
fd-form-input-message-group doesn't render fd-form message properly

### ISSUE THREAD

**Issue by cstechfoodie** [SAP/fundamental-ngx#2070]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 8.2.14
Fundamental-ngx 0.13.1

#### If this is a bug, please provide steps for reproducing it.
1. create a single reactive form
using the component in this way 
```
                  <div fd-form-item>
                      <label
                        fd-form-label
                        [required]="true"
                        for="scc-location-name"
                        >Name</label
                      >
                      <fd-form-input-message-group>
                        <input
                          fd-form-control
                          [type]="'text'"
                          formControlName="name"
                          pattern="^[a-zA-Z0-9]+[a-zA-Z0-9\s]*$"
                          [state]="formControlValidate('name')" //return "valid" or "invalid" or ""
                        />

                        <fd-form-message
                          *ngIf="formControlValidate('name') === 'invalid'"
                          [type]="'error'"
                        >
                          No special characters allowed
                        </fd-form-message>
                      </fd-form-input-message-group>
                    </div>
```

2. load this project in browser. click the input. you will see a small dot on the left bottom left conner because of the container for the popover.
![Screen Shot 2020-02-25 at 2 35 32 PM](https://user-images.githubusercontent.com/30379428/75281663-a8d2d600-57dd-11ea-9d7b-4ac141beb2f6.png)

3. when you have an invalid input. The popover is not vertically aligned.
![Screen Shot 2020-02-25 at 2 35 43 PM](https://user-images.githubusercontent.com/30379428/75281737-c7d16800-57dd-11ea-8413-7b4c5c652d4d.png)

4. Click outside of the input and then re-highlight the input again. This popover looks good.
![Screen Shot 2020-02-25 at 2 35 10 PM](https://user-images.githubusercontent.com/30379428/75281864-06ffb900-57de-11ea-91ec-f1fd1d3e87e1.png)

#### Please provide relevant source code if applicable.
See above
#### Is there anything else we should know?
Contact Shunyu Wang in SAP EC if you need more info

**Comment by salarenko** [comment]
Popover displays its body event when there is no message to show.

**Comment by JKMarkowski** [comment]
Let's use 
```      <div fd-form-item>
                      <label
                        fd-form-label
                        [required]="true"
                        for="scc-location-name"
                        >Name</label
                      >
                      <fd-form-input-message-group [triggers]="[]" [isOpen]="formControlValidate('name') === 'invalid'">
                        <input
                          fd-form-control
                          [type]="'text'"
                          formControlName="name"
                          pattern="^[a-zA-Z0-9]+[a-zA-Z0-9\s]*$"
                          [state]="formControlValidate('name')" //return "valid" or "invalid" or ""
                        />

                        <fd-form-message
                          [type]="'error'"
                        >
                          No special characters allowed
                        </fd-form-message>
                      </fd-form-input-message-group>
                    </div>
