### ISSUE TITLE
Switch is loosing focus when being clicked

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2076]
#### Is this a bug, enhancement, or feature request?
This is a bug

#### Briefly describe your proposal.
Bug can be reproduced in documentation page: https://fundamental-ngx.netlify.com/#/core/switch
![focus-switch](https://user-images.githubusercontent.com/17496353/75366219-aeecb380-58be-11ea-9bd0-a3aadc717ce5.gif)

Switch component is loosing focus when clicked multiple times.

#### Which versions of Angular and Fundamental Library for Angular are affected?
v0.14.1-rc.14

**Comment by JKMarkowski** [comment]
@salarenko this is valid behaviour, it's same for styles's checkbox or switch component. If you click on component very fast, the focus is lost.

**Comment by salarenko** [comment]
@JKMarkowski How is this valid behavior? For me it means that other components are broken as well.

**Comment by droshev** [comment]
I agree with @salarenko - we need to investigate this more
