### ISSUE TITLE
Add rowSpan input to fd-panel

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#208]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

Panels support row and column span, currently the panels are only accepting column span and the user must manually set the row span class on the component.  Row span should be an input (rowSpan) and column span input should be renamed to colSpan

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 6.0.0, fundamental-ngx 0.0.16-beta

**Comment by mikerodonnell89** [comment]
https://github.com/SAP/fundamental/issues/630

**Comment by droshev** [comment]
@mikerodonnell89 is this still valid?
