### ISSUE TITLE
Is a expected behavior that <fd-tab> hasn't [disable] property when version upgrade from 0.13.1 to 0.14.0?

### ISSUE THREAD

**Issue by cocotao** [SAP/fundamental-ngx#2082]
#### Is this a bug, enhancement, or feature request?
Yes, it is a bug.

#### Briefly describe your proposal.
When I upgrade version from 0.13.1 to 0.14.0, I found there are some incompatible changes. I want to know whether they are the expected behavior. 
1. <fd-tab> hasn't [disable] property in 0.14.0.
2. <fd-toggle> and ToggleModule deprecated? Seems I need to use <fd-switch> now?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version: angular 8
Fundamental Library: 0.13.1 -> 0.14.0

#### If this is a bug, please provide steps for reproducing it.
1. Upgrade Fundamental Library from 0.13.1 to 0.14.0.
2. Angular project compile failed, there is no [disable] property in <fd-tab>, ToggleModule is not exported. 

#### Please provide relevant source code if applicable.
`<fd-tab [title]="'MDT_DETAIL_TAB_CALENDAR' | translate" [disabled]="editMode">`

#### Is there anything else we should know?
No more info.

**Comment by JKMarkowski** [comment]
Hello @cocotao, sorry for late answer, but due to fiori3 specifications `[disable]` mode has been removed. Every disabled tabs should be hidden.
