### ISSUE TITLE
shellbar buttons styling issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2098]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
go to the shellbar example https://fundamental-ngx.netlify.com/#/core/shellbar#linksCollapseProductSwitcher where the shellbar looks ok. Open the stackblitz link and see that the shellbar buttons are off
<img width="772" alt="Screen Shot 2020-03-01 at 6 12 28 PM" src="https://user-images.githubusercontent.com/4380815/75635948-6566d600-5be8-11ea-8ede-43ebf5d9310b.png">
<img width="1054" alt="Screen Shot 2020-03-01 at 6 10 54 PM" src="https://user-images.githubusercontent.com/4380815/75635949-6566d600-5be8-11ea-8700-4a237d457621.png">

I guess the issue is a result of different order of the styles coming in
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/platform": "0.15.0-rc.16",

**Comment by mikerodonnell89** [comment]
This can be resolved by re-ordering the styles imports in the stackblitz example, so it's an issue with the specificity of the fd-shellbar styles in fundamental-styles

**Comment by mikerodonnell89** [comment]
Could be fixed by https://github.com/SAP/fundamental-styles/pull/744 but I believe we will have to wait for a new fundamental-styles version to be sure

**Comment by droshev** [comment]
Once you merge the styles issue, you can validate it in stackblitz by using the rc version

**Comment by JKMarkowski** [comment]
![image](https://user-images.githubusercontent.com/26483208/78777029-23744100-7999-11ea-8b4a-f560224ba69c.png)
It's still there, after releasing styles@0.8.0
