### ISSUE TITLE
fd-overlay class is not applied to modal

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#2101]
**Describe the bug**
The .fd-overlay--modal class is not applied to fd-modal-overlay 

**Is this issue related to a specific component?**  
Modal

**What version of the Fundamental Styles are you using?**  
0.2.0

**What front-end framework are you implementing in, e.g., Angular, React, etc.?**
Angular with Ngx-fundamental

**To Reproduce**
1. Create a modal **with ngx-fundamental**
2. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/34537974/64944685-31cd0500-d86f-11e9-8bdf-9bc025ef26b4.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser Chrome

**Comment by salarenko** [comment]
Bug has been fixed in next ngx and styles versions.
https://fundamental-ngx.netlify.com/#/core/modal#templateAsContent
