### ISSUE TITLE
Combobox with selected input only shows selected option on click

### ISSUE THREAD

**Issue by migg24** [SAP/fundamental-ngx#2105]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Feedback from users is they do not understand that you need to remove the text in the input field for the other options to reappear because the currently selected input is treated as the current "search" string when you just click on the field. You will only see one option or a few that match the currently selected option and users think this is everything they can choose. 
We would need a configurable option to change this behaviour on click on the already selected option to show everything and only start filtering again when the user changes the input text. This is not easily achievable with `filterFn` because we cannot access the private original filterFn and displayFn (technically possible but prone to break with updates) and implementing around that would be hacky.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### Is there anything else we should know?
Maybe this problem can also be fixed or made better by giving the user a visible clear button like mentioned in #1709.

**Comment by droshev** [comment]
will be covered with https://github.com/SAP/fundamental-ngx/issues/2285

**Comment by droshev** [comment]
@migg24 Thanks for the feedback. A fix has been released.
