### ISSUE TITLE
fix(platform): Button has to be updated with fundamental-styles 0.7.0 changes

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#2111]
Is this a bug, enhancement, or feature request?
Enhancement

Briefly describe your proposal.
fundamental -styles -0.7.0 has below-mentioned changes, the same has to reflect in platform as well.

1).New button types added: fd-button--attention and fd-button--ghost
2).fd-button--light renamed to fd-button--transparent
3).fd-button--standard has been removed and replaced by the default (fd-button)

**Comment by droshev** [comment]
@sKudum is this still valid? If not, can we close it?

**Comment by sKudum** [comment]
Closing it, as it is already addressed  and merged in PR #2365
