### ISSUE TITLE
Form Input with required flag does not work well with fd-inline-help 

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#2116]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.

When Required flag is used with `fd-inline-help`  combination asterisk appears after inline help. 

<img width="1306" alt="Screen Shot 2020-03-04 at 9 07 25 PM" src="https://user-images.githubusercontent.com/17149942/75918666-715ace00-5e5c-11ea-971f-ec1ae2af619a.png">

It shoudl be still sticked with label text no?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

```
Angular CLI: 8.3.18
Node: 10.9.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.803.22
@angular-devkit/build-ng-packagr   0.803.22
@angular-devkit/build-optimizer    0.803.22
@angular-devkit/build-webpack      0.803.22
@angular-devkit/core               8.3.22
@angular-devkit/schematics         8.3.22
@angular/cdk                       8.2.3
@angular/cli                       8.3.18
@angular/material                  8.2.3
@ngtools/webpack                   8.3.22
@schematics/angular                8.3.22
@schematics/update                 0.803.18
@fundamental-ngx/core": "0.15.0-rc.17
@fundamental-ngx/platform": "0.15.0-rc.17
ng-packagr                         5.7.1
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2

```

#### If this is a bug, please provide steps for reproducing it.
Please see screenshot

#### Is there anything else we should know?

Looks wierd when required flag is after the hint icon.

**Comment by droshev** [comment]
@JKMarkowski can you check this issue when you are working on https://github.com/SAP/fundamental-ngx/pull/4061 ?

**Comment by JKMarkowski** [comment]
@droshev this will be fixed on https://github.com/SAP/fundamental-ngx/pull/4061
