### ISSUE TITLE
Using of inline block for popoveer

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#2119]
**Describe the bug**
Inline block is causing the form control to be shrunk.
Issue is related to form control component

> What version of the Fundamental Library Styles are you using?
newest

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
angular

**To Reproduce**
open stackblitz and you will see it is shrunk

**Expected behavior**
Full width such as on the home page for ngx
**Screenshots**
![Screen Shot 2020-03-04 at 5 24 15 PM](https://user-images.githubusercontent.com/50607147/75928830-3b5a2180-5e3d-11ea-97a3-be28eac4987b.png)

**Comment by TheGreatMarkus** [comment]
Yeah unfortunately still getting this issue even in the latest release. However, just something interesting I noticed is that the issue doesn't seem to until the page is reloaded.

Here is the styling on first load: 
![image](https://user-images.githubusercontent.com/23544999/78375110-50d87d80-759a-11ea-92bc-db9fa9b63199.png)
Notice that `display: inline-block` from `.fs-popover-custom` is overriden by the `display: flex` from `.fd-form-input-message-group`.

On reload, the inverse happens, and the style breaks: 
![image](https://user-images.githubusercontent.com/23544999/78375228-81b8b280-759a-11ea-90ab-5f56b0f3c5e0.png)

I hope this helps in some way.
