### ISSUE TITLE
migrate to Angular 9

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2125]
#### Is this a bug, enhancement, or feature request?
enhancement

Migrate Fundamental NGX to Angular 9:
- [ ] Core Library
- [ ] Core Documentation
- [ ] Platform Library
- [ ] Platform Documentation

**Comment by droshev** [comment]
@fkolar who from your group can help migrating the platform to angular 9?

**Comment by fkolar** [comment]
i I think the whole repo shoud be done by one person, otherwise it will be hard to manage. But the names you have there are fine. either Me or Kevin.

**Comment by fkolar** [comment]
As part of this what we should is to enforce stricker policy for LINT, to keep things more aligned. When I was restructuring git repo and I had to remove many policies to make it pass.

**Comment by fkolar** [comment]
@droshev How do you want to do this? 

here are link to follow:

https://update.angular.io/#8.2:9.0l3
https://angular.io/guide/ivy-compatibility
https://angular.io/guide/updating-to-version-9#removals

**Comment by JKMarkowski** [comment]
Hello @fkolar there is prepared working PR with ng9 https://github.com/SAP/fundamental-ngx/pull/2023
