### ISSUE TITLE
Introduce FormGroup Layout to simplify form assembly

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#2131]
#### Is this a bug, enhancement, or feature request?
Feature

#### Briefly describe your proposal.
Implement (migrate) Application level component based on [following spec](https://github.com/SAP/fundamental-ngx/wiki/Platform:-FormGroup-Layout-Technical-Design) and introduce formal structure how form inputs control will be treated. 

Need to use directly Fundamental Styles as new updated form structure will not allow us to extend to higher component.

**Comment by droshev** [comment]
@manjunathanagaraj @fkolar any plans bringing this? if not, would you close the issue?

**Comment by droshev** [comment]
done with this https://github.com/SAP/fundamental-ngx/pull/5622
