### ISSUE TITLE
Combobox with enterprise functionality (platform)

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#2157]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.

Based on the ComboBox [specs](https://github.com/SAP/fundamental-ngx/wiki/Platform-Library-Home) we are bringing Combobox under the platform with enterprise grade functionality. 

We need to support DataAdapter pattern and some other features to scale better when working with large data sets https://github.com/SAP/fundamental-ngx/wiki/Data-Components-Standard-for-Enterprise-scale

**Comment by droshev** [comment]
@Lokanathan-k what do we do with this issue?

**Comment by Lokanathan-k** [comment]
this has been addressed as part of PR https://github.com/SAP/fundamental-ngx/pull/3048
