### ISSUE TITLE
[Shelbar] Circle with initials is not displaying properly

### ISSUE THREAD

**Issue by KamilZemczak** [SAP/fundamental-ngx#2161]
#### Is this a bug, enhancement, or feature request
Bug.
#### Briefly describe your proposal.
Its seems that shelbar using styles from fd-button if fd-button is appearing in page.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`"@fundamental-ngx/core": "^0.15.1",`
#### If this is a bug, please provide steps for reproducing it.
Please open your documentation: https://sap.github.io/fundamental-ngx/#/core/shellbar
Then, open first example with stackblitz and add simple button below shelbar, like in screenshot:

![image](https://user-images.githubusercontent.com/23119029/76501567-c68d7580-6442-11ea-8227-270250116fd2.png)

#### Please provide relevant source code if applicable.

```
<fd-shellbar>
    <fd-shellbar-logo>
        <a href="#" class="fd-shellbar__logo fd-shellbar__logo--image-replaced" aria-label="SAP"></a>
    </fd-shellbar-logo>
    <fd-shellbar-title>
        Corporate Portal
    </fd-shellbar-title>
    <fd-shellbar-actions [user]="user" [userMenu]="userMenu" [closePopoverOnSelect]="true"></fd-shellbar-actions>
</fd-shellbar>

  <button fd-button>Test</button>
```

#### Is there anything else we should know?

In 14.0.0 version of library everything works fine.

**Comment by JKMarkowski** [comment]
@mikerodonnell89 Is it done on styles? I belive it's because we relied on order of classes in `0.6.0` styles version.

**Comment by droshev** [comment]
@KamilZemczak We are aware of this issue. It is address in https://github.com/SAP/fundamental-styles/pull/744

**Comment by droshev** [comment]
The issue has been downported to version 0.15.2
