### ISSUE TITLE
notification buttons not placed properly

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#2168]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
The notification component's buttons are stuck together and even go outside of the container
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Newest
#### If this is a bug, please provide steps for reproducing it.
open notifications in stackblitz
![Screen Shot 2020-03-13 at 12 10 43 PM](https://user-images.githubusercontent.com/50607147/76639120-f82a3d80-6523-11ea-96d5-3b244efdf4a6.png)

**Comment by mikerodonnell89** [comment]
This issue comes from styles and could possibly be fixed as a part of https://github.com/SAP/fundamental-styles/issues/581
