### ISSUE TITLE
Issues found during the Defect Hunting - 18.03 

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2192]
Please report issues in one comment per reporting person.

**Comment by mikerodonnell89** [comment]
"Select a FIle" button should have arrow icon
![Screen Shot 2020-03-18 at 7 58 29 AM](https://user-images.githubusercontent.com/2471874/76968362-66894a00-68ee-11ea-8601-b4d811b5dd01.png)

**Comment by salarenko** [comment]
- Action Bar popover cannot be opened - IE11
![image](https://user-images.githubusercontent.com/17496353/76968383-1aa7c680-6929-11ea-84fe-1e18fb6d6185.png)

- Cannot be opened - IE11
![image](https://user-images.githubusercontent.com/17496353/76968636-8c801000-6929-11ea-9ef8-0099a6ba88fe.png)

- Wider spacing for RTL mode
![image](https://user-images.githubusercontent.com/17496353/76968885-eaacf300-6929-11ea-9eaf-21571e7ca6e4.png)
![image](https://user-images.githubusercontent.com/17496353/76968925-fc8e9600-6929-11ea-968b-0fc81513d404.png)

-

**Comment by JKMarkowski** [comment]
Doubled headers:
File Input:
![image](https://user-images.githubusercontent.com/26483208/76970563-5db76900-692c-11ea-9ce4-5d5530630475.png)

Image Component:
![image](https://user-images.githubusercontent.com/26483208/76970613-6f007580-692c-11ea-9371-ff6eeba95da6.png)

**Comment by JKMarkowski** [comment]
Safari/Firefox - Tabs are not selected (Examples/API) - Mike / Inna

**Comment by rengare** [comment]
Popover works for IE 11 both locally and on netlify master's branch
![image](https://user-images.githubusercontent.com/10849982/76974483-8f7efe80-6931-11ea-80e3-e075b7ce588a.png)

![image](https://user-images.githubusercontent.com/10849982/76974505-9574df80-6931-11ea-98dd-54b16e433f05.png)
