### ISSUE TITLE
[DatePicker] The enhancement of right border of Date Picker Calendar

### ISSUE THREAD

**Issue by Cyw1994** [SAP/fundamental-ngx#2241]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Browser: Chrome
Action: Scaling the display size of window to 75%
Result: The right border of calendar is overflowed.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: v8.x
Fundamental: v0.14.0

#### If this is a bug, please provide steps for reproducing it.
Open the chrome and your ngx page, then scaling the size of window from browser settings, when the display size is between 75% to 90%, the calendar right border will be overflowed.

#### Please provide relevant source code if applicable.
No special using case, just simply use the component of DatePicker.

#### Is there anything else we should know?
I find that the overflowed lines is just the border of the date number button, so it maybe result from the scaling of date button.

**Comment by JKMarkowski** [comment]
Hello @Cyw1994 We implemented new calendar, that follows fiori3 specs. It's also in date and datetime picker. It's on v0.16.0. 
I can't reproduce this issue on such a version.
