### ISSUE TITLE
Scrollable Table Body

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#2247]
#### Is this a bug, enhancement, or feature request?

feature request

#### Briefly describe your proposal.

What do we want? Table component's body to be scrollable.

In some cases we have to render more rows that can fit in the browser's viewport. This we would like to support by making the table component's body scrollable.

The requested feature is nicely shown in the SAP UI5 table:
https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@angular/core: 8.2.7
@fundamental-ngx/core: 0.15.1

**Comment by droshev** [comment]
This should be part of #2248
