### ISSUE TITLE
Sticky Column Headers 

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#2248]
#### Is this a bug, enhancement, or feature request?

feature request

#### Briefly describe your proposal.

What do we want? _Sticky column headers_.

In some cases we have to render more rows that can fit in the browser's viewport. When the users scrolls down, he shall still be able to see the column names.

The requested feature is nicely shown in the SAP UI5 table:
https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@angular/core: 8.2.7
@fundamental-ngx/core: 0.15.1

#### Is there anything else we should know?

Related to #2247

**Comment by droshev** [comment]
It is already in development
