### ISSUE TITLE
How to change the TextArea hight?

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2250]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
We need an opportunity to define the hight of the textarea, based on how much lines a user can write, before a scroll bar appears. Here are the guidelines from fiori that describes it in more details:  https://experience.sap.com/fiori-design-web/text-area/#properties (second point)

Currently, a user can include in the [fundamental textarea](https://sap.github.io/fundamental-ngx/#/core/textarea) two lines and then the scroll bar appears with the third line. We have cases where we need a textarea with 6 lines hight, before the scroll bar appears. See following screenshot:
<img width="521" alt="Screen Shot 2020-04-01 at 14 13 00" src="https://user-images.githubusercontent.com/26272656/78135879-e7822e80-7422-11ea-8677-973f60910e48.png">

Here are also some nice examples from the sapui5 textarea: https://sapui5.hana.ondemand.com/#/entity/sap.m.TextArea

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

    "@angular/core": "^8.2.12"
    "@fundamental-ngx/core": "^0.15.1"

**Comment by zaheral** [comment]
Hi have an another point to this issue. There is also the opportunity to let the textarea grow until a defined limit of hight. Here are some examples: https://sapui5.hana.ondemand.com/#/entity/sap.m.TextArea/sample/sap.m.sample.TextAreaGrowing
The first point is more critical for us

**Comment by JKMarkowski** [comment]
Hello @zaheral Thanks for pointing it out, we will try to provide built-in auto resize on textarea component.

**Comment by droshev** [comment]
@zaheral you can use the native properties of `textarea` directly

**Comment by zaheral** [comment]
Hi @droshev 

thanks for this info. Unfortunately it is not possible with the textarea native attributes like "row" to have an growing behaviour like described in the Fiori Design Guidelines here: https://experience.sap.com/fiori-design-web/text-area/#growing-behavior
The growing behaviour is required from our side to fulfil the example shown in the above screenshot.

You can also check in this SAPUI5 example (the first one), how the textarea is growing dynamically up-to a configured maximum line: https://sapui5.hana.ondemand.com/#/entity/sap.m.TextArea/sample/sap.m.sample.TextAreaGrowing

**Comment by droshev** [comment]
@zaheral How about using the platform textarea https://fundamental-ngx.netlify.app/#/platform/textarea

**Comment by zaheral** [comment]
Really cool. That includes the growing behavior
