### ISSUE TITLE
Error "ExpressionChangedAfterItHasBeenCheckedError..." when creating items dynamically in Side Navigation

### ISSUE THREAD

**Issue by armandorod2000** [SAP/fundamental-ngx#2253]
#### Is this a bug, enhancement, or feature request?
It seems to be a bug

#### Briefly describe your proposal.
When building a side navigation and trying to create some list items dynamically, I get the following error:

> ERROR
> Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'is-selected: undefined'. Current value: 'is-selected: false'.

My understanding is that the attribute "selected" is optional. How do I get around this?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular ===> 8.2.13 or 8.3.17
Fundamental library ===> 0.15.1 or 0.15.2

#### If this is a bug, please provide steps for reproducing it.
I'm writing a very simple example here https://stackblitz.com/edit/angular-mjunz7

#### Please provide relevant source code if applicable.
In the stackblitz project

#### Is there anything else we should know?
nop

**Comment by JKMarkowski** [comment]
Hello @armandorod2000, Please consider migrating your project to `fundamental-ngx/core@0.16.0`, which is also compatible with angular9.
There you can test it in angular 9 and ngx@0.16.0 (stackblitz)[https://stackblitz.com/edit/angular-y1pzlx]
