### ISSUE TITLE
checkbox label cannot be marked as required

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2255]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
In the fundamental-ngx, we are missing the asterix option for the checkbox label that marks a checkbox as required:
![image (2)](https://user-images.githubusercontent.com/26272656/78271727-cbf35280-750c-11ea-9d98-1795ec1d053c.png)

I tried it in the same way like in the input label with <.... required="true">, but it seems currently not to be supported. In the API docs I also didn't found something: https://sap.github.io/fundamental-ngx/#/core/checkbox/api

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

    "@angular/core": "^8.2.12"
    "@fundamental-ngx/core": "^0.15.1"

**Comment by zaheral** [comment]
I found an additional point to this issue:
The fundamental checkbox supports the "Reactive Forms by binding". I used it in this way and created a formControl with a validator:
```javascript
this.formBuilder.group({
      'checkbox.field': [undefined, Validators.required]
});
```
In this way I can mark it as required, but then the checkbox is shown with a red border:
![Screen Shot 2020-04-03 at 11 14 17](https://user-images.githubusercontent.com/26272656/78344164-45865180-759c-11ea-8a0f-2dbbde4968cf.png)

Usually, a red border means that there is an error. It makes sense, because the only validation to a checkbox is the "required validation". But here I'm also not really sure what the fiori guidelines are, because there are no information about the required state: https://experience.sap.com/fiori-design-web/checkbox/
If this is the way how it should be marked as required, then it works for the reactive form.

**Comment by salarenko** [comment]
@zaheral I'm sorry but currently there is no supported way to add required asterisk to checkbox label.

You can do quite ugly workaround by specifying custom label content and using `fd-form-label` to create required asterisk. Remember not to wrap whole label content into `fd-form-label`, because this might lead to unexpected behavior.
```
        <fd-checkbox [(ngModel)]="checkboxValue">
            Custom label<label fd-form-label [required]="true">:</label>
        </fd-checkbox>
```

Sorry for inconvenience, we will try to fix this as soon as possible.

**Comment by zaheral** [comment]
@salarenko no problem, the workaround works wonderful. Thank you for your support.
