### ISSUE TITLE
StacksBlitz not working.

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental-ngx#2276]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
StackBlitz is broken and shows the following error 
<img width="332" alt="Screen Shot 2020-04-06 at 11 32 04 AM" src="https://user-images.githubusercontent.com/15215400/78582090-62b85b80-77fa-11ea-86a3-25c2e62eef4a.png">

Downgrading `core-js` to 2.6.9 (as suggested in forums) results in the following error 
<img width="492" alt="Screen Shot 2020-04-06 at 11 34 22 AM" src="https://user-images.githubusercontent.com/15215400/78582289-ab701480-77fa-11ea-82e9-d67d906ff8e7.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`v0.15.1`

#### If this is a bug, please provide steps for reproducing it.
1. open any component documentation page
2. expand code view and click on `StackBlitz` button
3. StackBlitz spins and failed

**Comment by JKMarkowski** [comment]
Hello @saad-mo, please take a look at one of out [wiki](https://github.com/SAP/fundamental-ngx/wiki/Known-Contribution-Issues) page with known contribution issues, there is guide how to put quick fixup to stackbltiz project. It will be fixed on `0.16.0` release.
