### ISSUE TITLE
Combobox open/close behavior improvements

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#2285]
The open/close behavior on our combobox differs between our implementation and ui5's.  Ours should match theirs.  Here is an explanation of the differences, thanks to @salarenko for compiling this list

https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox

**NGX Core Combobox vs SAPUI5 Combobox behaviour:**

| Action | NGX Core  | SAPUI5 |
| ------------- | ------------- | ------------- |
| Focus input with `Tab` and start typing | No action | Displays list of elements matching provided input. |
| Click on Combobox `input` | Displays list of all options | No action |
| Click on Combobox `input` and start typing | Filters elements lists, makrs list element only when its 1:1 with typed in query, element cannot be selected without manual `Arrow Down` navigation and `Enter` selection. | Filters elements lists, marks most accurate result on the list which can be selected by pressing `Enter` key. |
| Select an element from the list and click on `Input expand button` | Shows results filtered by selected element. | Show all possible options with currently selected element focused. |
| Click on Combobox `input` and start typing | No element has visible focus. | Input is focused. |
| Expand options list | No visuals for Combobox input group changed | Expand button marked as active |

**Comment by mikerodonnell89** [comment]
Combobox needs focus styles in styles lib

**Comment by droshev** [comment]
Make sure to check https://github.com/SAP/fundamental-ngx/issues/2105
