### ISSUE TITLE
Multi Input - Responsive behavior not according to Fiori guidelines

### ISSUE THREAD

**Issue by RubenSalzegber** [SAP/fundamental-ngx#2291]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The Multi Input field is showing an unexpected behavior in case the tokens do not fit the width of the field. Contrary to the Fiori guidelines – which are requiring a "n more" indicator – the token in the current implementation are hidden and cannot be viewed anymore.

https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2059233657
https://ux.wdf.sap.corp/fiori-design-web/multiinput/#reviewing-tokens

#### If this is a bug, please provide steps for reproducing it.
![Screenshot 2020-04-08 at 14 42 32](https://user-images.githubusercontent.com/50944236/78786685-7950e500-79a9-11ea-9611-cbca079f6c29.png)

**Comment by mikerodonnell89** [comment]
This will be fixed when https://github.com/SAP/fundamental-ngx/pull/2086 is deployed

**Comment by JKMarkowski** [comment]
Hi @RubenSalzegber We jsut released `ngx@0.16.0`, this issue should be fixed. You can test it [there](https://fundamental-ngx.netlify.app/#/core/multi-input)

**Comment by droshev** [comment]
@RubenSalzegber let us know if there are some issues.
