### ISSUE TITLE
Dialog is missing ARIA attributes 

### ISSUE THREAD

**Issue by trilodge** [SAP/fundamental-ngx#2299]
BUG

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current version

#### If this is a bug, please provide steps for reproducing it.
The markup of the dialog component is missing some crucial aria attributes regarding accessibility. 

It would be better if the dialog follows the w3c wai aria recommendation like given here: 
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

This issue will also be mirrored to fundamental styles: https://sap.github.io/fundamental-styles/components/dialog.html because none of the essential attributes is stated there. 

#### Please provide relevant source code if applicable.
Attributes needed: 

role="dialog" 
aria-labeledby="xxxxxx" -> linked to the headline of the dialog

**Comment by salarenko** [comment]
Dialog supports proposed features. Use `DialogConfig.ariaDescribedBy`
