### ISSUE TITLE
Refactor Menu Component to be consistent with the latest version of Fundamental-UI

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#230]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
The latest version of Fundamental-UI has Menu with Separator and Menu with addon before
#### Please provide relevant source code if applicable.
Fundamental-UI [Menu](https://sap.github.io/fundamental/components/menu.html)

**Comment by mikerodonnell89** [comment]
duplicate https://github.com/SAP/fundamental-ngx/issues/292
