### ISSUE TITLE
RtlService should not be a required provider

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#2301]
In v 0.16 rc's, if an app is importing the whole FundamentalNgxModule, it is required to add RtlService to the app module's provider list, whether or not the app is using the RtlService.  This should not be necessary

**Comment by JKMarkowski** [comment]
@mikerodonnell89 It has been addressed in some PRs. Rtl Service is not required to be provided anymore. Everywhere it's used with `@Optional` decorator
