### ISSUE TITLE
Implement Multi Input Component

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#231]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Multi Input is a new component coming with Fundamental-UI version 1.2.1
#### Please provide relevant source code if applicable.
Fundamental-UI [Multi Input](https://sap.github.io/fundamental/components/multi-input.html)

**Comment by droshev** [comment]
<img width="350" alt="screen shot 2019-02-15 at 10 11 34 am" src="https://user-images.githubusercontent.com/4380815/52867874-ece1c400-310f-11e9-9d12-5a588a659c37.png">

**Comment by droshev** [comment]
![screen shot 2019-02-15 at 10 53 23 am](https://user-images.githubusercontent.com/4380815/52867883-f539ff00-310f-11e9-81b5-427e611880e2.png)

**Comment by droshev** [comment]
![screen shot 2019-02-15 at 10 54 38 am](https://user-images.githubusercontent.com/4380815/52867962-21558000-3110-11e9-8d33-2d287018353e.png)
![screen shot 2019-02-15 at 10 54 42 am](https://user-images.githubusercontent.com/4380815/52867963-21558000-3110-11e9-9ecf-ceb07c44f290.png)
![screen shot 2019-02-15 at 10 54 47 am](https://user-images.githubusercontent.com/4380815/52867964-21ee1680-3110-11e9-8d42-1973394aa65c.png)
