### ISSUE TITLE
bug - first and last menu items have an extra bit of space

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2313]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
First and last menu items have an extra bit of space before the top or bottom of the popover - to be address with the new menu styling - version 0.17.0
![image](https://user-images.githubusercontent.com/4380815/79059516-fbab0480-7c48-11ea-877c-667d46eb6a52.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest

**Comment by rengare** [comment]
Closed by #2547
