### ISSUE TITLE
Refactor Table to be consistent with the latest version of Fundamental-UI

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#233]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
The latest version of Fundamental-UI has [Table with Sortable Column Headers](https://sap.github.io/fundamental/components/table.html#table-with-sortable-column-headers), [Table with Sortable Column Headers - Ascending](https://sap.github.io/fundamental/components/table.html#table-with-sortable-column-headers---ascending), [Table with Sortable Column Headers - Descinding](https://sap.github.io/fundamental/components/table.html#table-with-sortable-column-headers---descinding), [Table with Column Headers with context menu](https://sap.github.io/fundamental/components/table.html#table-with-column-headers-with-context-menu), and [Table with Fix Column Header and context menu](https://sap.github.io/fundamental/components/table.html#table-with-fix-column-header-and-context-menu)
#### Please provide relevant source code if applicable.
 Fundamental-UI [Table](https://sap.github.io/fundamental/components/table.html)

**Comment by mikerodonnell89** [comment]
Can we discuss https://github.com/SAP/fundamental-ngx/pull/244 before starting this one?

**Comment by droshev** [comment]
@mikerodonnell89 I merged #244 already

**Comment by mikerodonnell89** [comment]
duplicate https://github.com/SAP/fundamental-ngx/issues/294
