### ISSUE TITLE
Multiple fdtype support for button is missing

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental-ngx#2352]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The buttons lack support (or it is not documented) on how to render a button with a combination of types. e.g. a `negative` `transparent` button. 

One of the use cases for this is in a wizard where you can cancel out of a step-by-step process and need to indicate to the user that this button will cancel out of the process. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 9 and fundamental-ngx `0.16.0-rc.107` 

#### If this is a bug, please provide steps for reproducing it.
Try rendering a button with a `negative` `transparent` type. 

#### Please provide relevant source code if applicable.
Tried the following combination, but does not yield a desired result 
`<button fd-button [fdType]="'transparent negative'">Transparent Button</button>`
`<button fd-button [fdType]="'transparent', 'negative'">Transparent Button</button>`
`<button fd-button [fdType]="['transparent', 'negative']">Transparent Button</button>`

**Comment by droshev** [comment]
This is against Fiori Design guidelines:
https://experience.sap.com/fiori-design-web/button/
It is either transparent or semantic
