### ISSUE TITLE
(Platform) Menu behavior bugs

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2371]
#### Is this a bug, enhancement, or feature request?
This is a bug.

#### Briefly describe your proposal.
Menu component suffer for multiple behavior bugs and accessibility features.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.16.0-rc.64

#### If this is a bug, please provide steps for reproducing it.
- Need two clicks to open another menu.
![platform-menu-1](https://user-images.githubusercontent.com/17496353/79556581-940a1480-80a1-11ea-87b1-e9e4ab289cac.gif)

-  Breaking sub-lists
![image](https://user-images.githubusercontent.com/17496353/79555933-a6378300-80a0-11ea-872c-258247e97c7a.png)

- Focus not following hover behavior
![image](https://user-images.githubusercontent.com/17496353/79555969-b2234500-80a0-11ea-8c61-3a904f970a71.png)

- Misplaced popover for RTL example
![image](https://user-images.githubusercontent.com/17496353/79556218-0fb79180-80a1-11ea-93b8-bbfd959bef7c.png)

- No focus trap

**Comment by droshev** [comment]
@manjunathanagaraj some of the issues are still reproducible

**Comment by droshev** [comment]
@manjunathanagaraj

**Comment by manjunathanagaraj** [comment]
These are fixed.
