### ISSUE TITLE
Compact Multi Input displays incorrect number of selected tokens

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#2390]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
show correct number of selected tokens

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
![compact_bug](https://user-images.githubusercontent.com/12159534/79866652-6690d400-83dd-11ea-900d-c7943c8c2c6b.gif)

**Comment by stefanoScalzo** [comment]
issue has been fixed
