### ISSUE TITLE
Can't resolve modules

### ISSUE THREAD

**Issue by camilo2312** [SAP/fundamental-ngx#2409]
Hi everyone

Previously I had fundamentals-ngx, update to @ fundamental-ngx / core and when I compile my application the following appears

![image](https://user-images.githubusercontent.com/42982644/80253319-a73b5800-863e-11ea-8861-bb8d2d72b9c9.png)

Need to install something?

Thanks for the help

**Comment by JKMarkowski** [comment]
Hello @camilo2312 could You provide your module, where you import `ngx/core` modules and Your version of `ngx/core`?

**Comment by camilo2312** [comment]
Of course

![image](https://user-images.githubusercontent.com/42982644/80373274-6f106100-885a-11ea-9185-c8a7ee7c362a.png)

My version of fundamental-ngx/core

![image](https://user-images.githubusercontent.com/42982644/80373356-949d6a80-885a-11ea-9932-3312a09851de.png)

**Comment by camilo2312** [comment]
Any solution?

**Comment by mikerodonnell89** [comment]
@camilo2312 Not sure why that would be `export` and not `import`... can you provide the contents of the entire file?

**Comment by droshev** [comment]
@camilo2312 I will close the issue. If you still have issues, you either create a new one or open this one.
