### ISSUE TITLE
There is a lag, slow down in click events on the page with multiple fd-popovers present

### ISSUE THREAD

**Issue by rakshetha-jn** [SAP/fundamental-ngx#2442]
#### I have a table where all the table cells on hover (mouseEnter,mouseLeave) shows a fd- popover , since the table has over 100 rows and 7 columns  there are several fd-popovers .
I removed the popover from 4 columns and the lag reduced to 2 seconds and the lag /slow down disappears when fd-popover is not used.

#### 

![image](https://user-images.githubusercontent.com/60785445/80571219-82f3c880-89fc-11ea-8abf-245dbcbad5e5.png)

**Comment by fkolar** [comment]
@droshev  Guys this is a perfect usecase the for the angular debugger tools we discussed yesterday

1. enable DebugTools 

```
platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .then(moduleRef => {
    const applicationRef = moduleRef.injector.get(ApplicationRef);
    const componentRef = applicationRef.components[0];
    // allows to run `ng.profiler.timeChangeDetection();`
    enableDebugTools(componentRef);
  })
  .catch(err => console.error(err));
```

2. rebuild app and serve it
3. go to chrome console and run `ng.profiler.timeChangeDetection()`
  - this should be under 3ms per D. cycle
4. Run `ng.profiler.timeChangeDetection({record:true})` to record data for your JS profiler
5. Open JS profiler tab inside your chrome (it might be hidden, so you need to make it visible from the option popover)
6. Switch to Bottom UP view (it should be default view) and check which call is the slowest 
7. analyze , fix

**Comment by JKMarkowski** [comment]
@rakshetha-jn Try to check `0.13.2` Version. There are included performance improvements

**Comment by rakshetha-jn** [comment]
> @rakshetha-jn Try to check `0.13.2` Version. There are included performance improvements

thanks @JKMarkowski for the fix.It works and i don't see the lag anymore.
So i tired the following 
Version 0.13.2 = Works great no lag 
Version 0.14.1 = Works great no lag
Version 0.15.3 = Lag/slow down is back 
Didn't check 0.16.0 as we are still on angular 8.

Currently we are sticking to 0.13.2 but are planning to migrate to 0.15.x in the near future as we don't want to be left behind from the new features.

**Comment by JKMarkowski** [comment]
@rakshetha-jn Check `0.15.4` version. There are improvements included.
