### ISSUE TITLE
fd-dialog dark theme

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2462]
**Versions:**
@fundamental-ngx/core": 0.17.1 (@latest)
@fundamental-ngx/platform: 0.17.1 (@latest)
fundamental-styles: 0.7.0

**Bug:**
fd-dialog's border is part white part black. 
![image](https://user-images.githubusercontent.com/49150290/80911746-02f19980-8d41-11ea-8cbb-ca521b02e38d.png)

**Comment by droshev** [comment]
this was fixed already
