### ISSUE TITLE
fd-panel dark theme support

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2463]
**Versions:**
@fundamental-ngx/core": 0.17.1 (@latest)
@fundamental-ngx/platform: 0.17.1 (@latest)
fundamental-styles: 0.7.0

**Bug:**
fd-panel doesn't support dark theme
![image](https://user-images.githubusercontent.com/49150290/80911791-4815cb80-8d41-11ea-99c5-4ff2ae500d4a.png)

**Comment by droshev** [comment]
The panel is not yet migrated. We are in progress of migrating the styling part https://github.com/SAP/fundamental-styles/pull/1024
Once we release it in styles then we will migrate the NGX part

**Comment by droshev** [comment]
should be good now
