### ISSUE TITLE
fd-multi-input multiple problems

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2465]
**Versions:**
@fundamental-ngx/core": 0.17.1 (@latest)
@fundamental-ngx/platform: 0.17.1 (@latest)
fundamental-styles: 0.7.0

**Bug:**
1.	Dark theme is not being properly applied to this component.
2.	Background color can’t be changed.

![image](https://user-images.githubusercontent.com/49150290/80912066-fe2de500-8d42-11ea-880a-959141ce0dfe.png)

**Comment by droshev** [comment]
The white background will be fixed once we merge PR #2514 https://deploy-preview-2514--fundamental-ngx.netlify.app/#/core/multi-input
