### ISSUE TITLE
fd-multi-input feature request

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2466]
**Versions:**
@fundamental-ngx/core": 0.17.1 (@latest)
@fundamental-ngx/platform: 0.17.1 (@latest)
fundamental-styles: 0.7.0

**Bug:**
The component is missing key features such as:
1.	Wrap tokens instead of hiding the content or stretching the container.
2.	Option to hide the “Show All” button.
3.	Hide list item check boxes or resize them or manipulate them in any way.

**Comment by droshev** [comment]
@shaysap regarding the 1st point - you can scroll left/right to see the full content

**Comment by droshev** [comment]
@shaysap 
Regarding the point 2: you can use the input 'showAllButton' to hide it.
Regarding the point 3: if you hide the checkboxes then how would you select/unselect the items?
