### ISSUE TITLE
fd-tab-list

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2467]
**Versions:**
@fundamental-ngx/core": 0.17.1 (@latest)
@fundamental-ngx/platform: 0.17.1 (@latest)
fundamental-styles: 0.7.0

**Bugs:**
1.	CSS rules can’t be applied to the header (the tabs cotainer).
2.	Process mode icons can’t be changed.
3.	Circle and underline colors can’t be changed.
![image](https://user-images.githubusercontent.com/49150290/80911969-7c3dbc00-8d42-11ea-8f54-2a75d8b8503c.png)

**Comment by droshev** [comment]
@shaysap Thank you for opening this issue. here is one example where i changed few of CSS colors/background and replaced the icons
![Screen Shot 2020-05-14 at 10 11 47 PM](https://user-images.githubusercontent.com/4380815/82004030-ebaf8780-962f-11ea-8031-bdd246bc54df.png)
: [link](https://stackblitz.com/edit/angular-xoi4dd?file=src/index.html).

**Comment by shaysap** [comment]
Thank you for your response.
I know I can modify everything from the global CSS file (like you did in the example) but I don't think this is the right way to go. Creating global CSS rules to override your component's styles will most probably create a huge mess across the project.
Working your way also requires the users to run the component, manually find the relevant classes in the DOM at run time and then create rules to override them.
This approach is risky as it can lead to many breaking changes you will not be aware of.
The component should support basic changes like color/icon changes.

**Comment by droshev** [comment]
@shaysap how about this approach: [here](https://stackblitz.com/edit/angular-xoi4dd)
