### ISSUE TITLE
fd-table dark theme support

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2469]
**Versions:**
@fundamental-ngx/core": 0.17.1 (@latest)
@fundamental-ngx/platform: 0.17.1 (@latest)
fundamental-styles: 0.7.0

**Bug:**
fd-table doesn't support dark theme

**Comment by droshev** [comment]
The issue will be tackled as part of https://github.com/SAP/fundamental-ngx/issues/1044
