### ISSUE TITLE
Enabled Switch Plays Enabling Animation on Refresh

### ISSUE THREAD

**Issue by MichaelLambertz** [SAP/fundamental-ngx#2502]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

The status of an enabled `fd-switch` element plays the enabling animation (jumping from disabled to enabled) when the `[checked]` reference is updated, depending on how the element is set up - please see below.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Fundamental 0.17.1
Angular 9.1.1

#### If this is a bug, please provide steps for reproducing it.

Use the code below and click:
- The second switch any number of times: on each click, the first switch will jump to disabled and back to enabled in an instant.
- The button below the switches any number of times: the first switch will never play an animation (expected behaviour).

#### Please provide relevant source code if applicable.

TS:
```
import { Component, OnInit } from '@angular/core';

interface Item { checked: boolean; }
@Component({
    selector: 'app-fd-switch-jumping',
    templateUrl: './fd-switch-jumping.component.html'
})
export class FdSwitchJumpingComponent implements OnInit {
    public items: Item[] = null;

    public ngOnInit(): void {
        this.items = [{checked: true}, {checked: true}];
    }

    public changeItems(): void {
        this.items = [{checked: true}, {checked: false}];
    }
}
```
HTML:
```
<div *ngFor="let item of items">
    <fd-switch [checked]="item.checked" (checkedChange)="changeItems()"></fd-switch>
</div>
<button (click)="changeItems()">Init</button>
```

**Comment by mikerodonnell89** [comment]
This is actually a chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=332189

See possible workarounds here: https://stackoverflow.com/questions/14389566/stop-css-transition-from-firing-on-page-load

You also may be able to work around this in your component by avoiding re-initializing the object that isn't being changed.

**Comment by MichaelLambertz** [comment]
Thanks @mikerodonnell89! This bug does indeed not occur on Firefox.
I'm closing this since it's not related to Fundamental.
