### ISSUE TITLE
Feature Request: Input Assistance for Intelligent Systems

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#2504]
Feature request

Dear colleagues, we would like to use the input assistance line for input fields (https://experience.sap.com/fiori-design-web/input-field/#input-assistance). This feature is recommended for designing intelligent systems (https://experience.sap.com/fiori-design-web/recommendations/#input-assistance1). Ideally, additional text below the input field is also available in read/display mode of the input field to provide required information.
Please provide as soon as possible.
Many thanks and regards,
Kai

**Comment by droshev** [comment]
This can be done on application level
