### ISSUE TITLE
replace popper.js with Angular CDK overlay

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2527]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
- Evaluate the pros/cons of replacing popper.js with [Angular CDK overlay](https://material.angular.io/cdk/overlay/overview)
  - performance
  - bundle size

- estimate the migration

We decided to migrate to Angular CDK overlay and we will do it iteratively.
Starting with popover component:
- [x] review the popover component markup and API and write a technical spec - [specs](https://app.gitbook.com/@fundamental-ngx/s/docs/work-in-progress/popper.js-to-cdk-overlay-migration)
- [x] create/update an util object/component/directive that can be reused for other components in CORE and PLATFORM
- [x] popover implementation
- [x] review the styling and identify gaps(best case bring them in fundamental-styles)
- [x] testing all components using popover

consider #2883

**Comment by FezVrasta** [comment]
Also consider to upgrade to Popper 2, its size is way smaller and fixes most of the known bugs
