### ISSUE TITLE
Platform update button to match the core button API

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2538]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
The current platform button doesn't match the latest updates of the button from core platform.
The extensibility part is outdated: https://sap.github.io/fundamental-ngx/#/platform/button#Button-extensibility

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

`@fundamental-ngx/platform` version `0.18.0`

**Comment by sKudum** [comment]
Hi @Deno,

**Comment by sKudum** [comment]
Hi @droshev ,
 As mentioned in [#2365 ](https://github.com/SAP/fundamental-ngx/pull/2365). 
![Uploading Screen Shot 2020-05-18 at 10.17.37 AM.png…]()
and it is dependent on issue:[2481](https://github.com/SAP/fundamental-ngx/issues/2481)

**Comment by droshev** [comment]
The fdp button should support this:
```
If you'd like to add multiple options, you could use [options]="['emphasized', 'option1', 'option2']".
This would result in 3 classes being added to the button: fd-button--emphasized, fd-button--option1, and fd-button--option2.
```
it is against Fiori 3

**Comment by sKudum** [comment]
> The fdp button should support this:
> 
> ```
> If you'd like to add multiple options, you could use [options]="['emphasized', 'option1', 'option2']".
> This would result in 3 classes being added to the button: fd-button--emphasized, fd-button--option1, and fd-button--option2.
> ```
> 
> it is against Fiori 3
> The issue is just targeting the button component and not the other button variations


Hi @Deno, 

Fiori3 has types and platform has  [type]="['emphasized', 'option1', 'option2']". it won't be having options going further in core as well.

This is considered by following the

1). fiori3 guideline.( these does not mention about options, it just list down the types.)

<img width="885" alt="Screen Shot 2020-05-18 at 4 42 29 PM" src="https://user-images.githubusercontent.com/53487468/82206917-adafad80-9926-11ea-83b5-59b7b52ce738.png">

2).Below PR changes done in Core. Which mentions fdOption will be deprecated.

<img width="826" alt="Screen Shot 2020-05-18 at 4 48 51 PM" src="https://user-images.githubusercontent.com/53487468/82207529-97562180-9927-11ea-8479-721eeb349bd4.png">

**Comment by droshev** [comment]
More button issues:
<img width="229" alt="Screen Shot 2020-06-17 at 11 02 00 PM" src="https://user-images.githubusercontent.com/4380815/84973348-dd510180-b0ee-11ea-9592-93a8eeb3ee65.png">

**Comment by sKudum** [comment]
Changes are merged as part of 2720 PR.
