### ISSUE TITLE
Platform Menu issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2539]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

- styling looks broken

![Screen Shot 2020-05-17 at 8 56 36 PM](https://user-images.githubusercontent.com/4380815/82164893-eac16480-9880-11ea-807e-2b9b2f754bd8.png)
- the menu doesn't get open if another menu is open. Steps to reproduce:
  - open one menu -> it will open it
  - click on another menu -> the second menu doesn't get open but it will close the first one only

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`@fundamental-ngx/platform` version `0.18.0`

**Comment by KevinOkamoto** [comment]
Styling has been fixed by PR #2294

**Comment by KevinOkamoto** [comment]
> Styling has been fixed by PR #2294

Looks like this is not fixed in the latest master. I'll need to take a look at it again.
