### ISSUE TITLE
Platform Action Bar issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2540]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- the context menu's styling looks broken
![Screen Shot 2020-05-17 at 9 00 19 PM](https://user-images.githubusercontent.com/4380815/82165036-881c9880-9881-11ea-9857-c88445389c8c.png)

- on mobile the context menu should open in full screen

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`@fundamental-ngx/platform` version `0.18.0`

**Comment by KevinOkamoto** [comment]
Styling has been fixed by #2294
