### ISSUE TITLE
Platform Link component issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2542]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
The current [platform link](https://sap.github.io/fundamental-ngx/#/platform/link) doesn't have enough information why developers should use the platform link instead of the core one. It would be great if the documentation is more verbose what the differences are and what is this component providing.

Another missing part is exposing all anchor native attributes as the application developer doesn't have a way to set them in the platform component

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`@fundamental-ngx/platform` version `0.18.1`

**Comment by DeepakSap14** [comment]
PR #2751 address documentation and examples for link.
It has been approved and merged. so closing this issue.
