### ISSUE TITLE
Platform Split Button issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2544]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
The current Platform Split Button component documentation page lacks information why the component should be used.
There are few styling issues (the icon button is too wide, the menu looks broken)
Core Package:
![Screen Shot 2020-05-17 at 9 16 24 PM](https://user-images.githubusercontent.com/4380815/82165674-fe21ff00-9883-11ea-9a4b-6b55019aa35b.png)

Platform Package:
![Screen Shot 2020-05-17 at 9 16 32 PM](https://user-images.githubusercontent.com/4380815/82165678-011cef80-9884-11ea-885d-8a7691d12053.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`@fundamental-ngx/platform` version `0.18.1`

**Comment by DeepakSap14** [comment]
PR #2603 merged with fix. closing the issue.
