### ISSUE TITLE
Platform: Introducing new Object Marker Component Creation.

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#2601]
#### Is this a bug, enhancement, or feature request?

Feature

#### Briefly describe your proposal.

*  This indicates the technical status of an object.
  It is enabled for the dynamic page layout, snapping header, object page header, upload collection, and object list item.
  The technical status can be represented as and icon, with an icon and text, or as text only, depending on the screen size. 
Currently, the following technical statuses can be visualized by the object marker:

    Flag
    Favorite
    Editing Status (Draft, Locked, Unsaved Changes)
    The editing status is part of the draft handling concept.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

NA

#### If this is a bug, please provide steps for reproducing it.

NA

#### Please provide relevant source code if applicable.

NA

**Comment by droshev** [comment]
@Lokanathan-k is this still valid?

**Comment by Lokanathan-k** [comment]
addressed with the PR https://github.com/SAP/fundamental-ngx/pull/3525
