### ISSUE TITLE
fd-product-menu is out of viewport

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#2608]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
fd-product-menu is only half visible. Placement property is not taken into account

<img width="695" alt="Screenshot 2020-06-03 at 14 40 58" src="https://user-images.githubusercontent.com/5263214/83637917-a0422680-a5a8-11ea-9f08-440b9aa7cb16.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.18 (it shows fully in 0.17, but placement input property is also not taken into account)

#### If this is a bug, please provide steps for reproducing it.
1) Open https://sap.github.io/fundamental-ngx/#/core/shellbar#linksCollapseProductSwitcher
2) Click open on stacblitz
3) Click menu button

**Comment by JKMarkowski** [comment]
Hello @mpienkowski,

**Comment by JKMarkowski** [comment]
Hello @mpienkowski I introduced some PR fixing this issue, it will be available after 0.19.0 merge, ping me if it's necessary to include it into previous versions.

**Comment by mpienkowski** [comment]
@JKMarkowski Thank you! it'd be great to have it in 0.18

**Comment by JKMarkowski** [comment]
I will let you know when it's introduced as fixup in 0.18.1

**Comment by JKMarkowski** [comment]
Hi @mpienkowski There is fixup on 0.18.1, it's also on our current master.

**Comment by zaheral** [comment]
Hi @JKMarkowski, the fix on 0.18.1 works wonderful. But the issue appears in version 0.19.2 again.

**Comment by JKMarkowski** [comment]
Hello @zaheral, try to use `[placement]` property, like in this example
```
<fd-product-menu [placement]="'bottom'"></fd-product-menu>
```
