### ISSUE TITLE
time/timepicker should accept block/disable functions as an input, like calendar

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#261]
Time and TimePicker components should accept block and/or disable functions as an input, like calendar, to prevent users from setting certain times.  For example, a dev may want to restrict a time picker's selectable times to workday hours or something similar

**Comment by droshev** [comment]
@mikerodonnell89 didn't we provide this already?

**Comment by MattL75** [comment]
@droshev ^ Not related to datepicker

**Comment by SaiShan** [comment]
Waiting for final design and UX.

**Comment by droshev** [comment]
Let's bring this back for design discussion

**Comment by stefanoScalzo** [comment]
blocked
[blocked by](https://github.com/SAP/fundamental-styles/issues/280)

**Comment by mikerodonnell89** [comment]
@droshev is this something we still want?

**Comment by droshev** [comment]
let's provide this once someone requests it
