### ISSUE TITLE
"hello world" app

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental-ngx#2616]
I am looking for a simple fundamental-ngx app, with couple of form input fields.

Any example I could start from?

Thanks in advance.

**Comment by JKMarkowski** [comment]
Hello @bsrdjan 
You can take a look at our [master - preview(0.19.0-rc.*)](https://fundamental-ngx.netlify.app).
Also to see latest(0.18..0) version let's visit [this site](https://sap.github.io/fundamental-ngx/#/core/home)
There are examples of component usages, with stackblitz support to make some experiments with the code.

**Comment by bsrdjan** [comment]
Thanks @JKMarkowski . The "Getting Started" example given in https://fundamental-ngx.netlify.app/#/core/home, is about existing Angular CLI application and I don't have one.

I am looking for one running fundamental /angular or react app, like this one for example, ideally with couple of form inputs: https://blogs.sap.com/2019/12/09/create-your-first-fundamental-library-application/ ? Is that app perhaps available? I could not find the repository.

**Comment by droshev** [comment]
@bsrdjan We don't have one right now. Feel free to create one and we will be happy to accept it back

**Comment by bsrdjan** [comment]
Was just thinking, the end-to-end app can be the 2nd step.

As a 1st step, I would adapt the `backend` script, to generate flat HTML lists of fundamental-ngx elements, annotated with ABAP metadata:

- [Checkbox](https://fundamental-ngx.netlify.app/#/core/checkbox)
- [ComboBox](https://fundamental-ngx.netlify.app/#/core/combobox)
- [DatePicker](https://fundamental-ngx.netlify.app/#/core/datePicker)
- [TimePicker](https://fundamental-ngx.netlify.app/#/core/timePicker)
- [Textarea](https://fundamental-ngx.netlify.app/#/core/textarea)
- [Input](https://fundamental-ngx.netlify.app/#/core/input)

Let us have a look into that first and if looks good, add layouts and views and complete the end-to-end app. Would that make sense?

**Comment by droshev** [comment]
https://github.com/SAP-samples/fundamental-ngx-sample-apps
