### ISSUE TITLE
Product Switch in collapsed Shellbar displays always above shellbar 

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2635]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Product Switch menu should display below shellbar if the shellbar is placed at the top of the screen

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v 0.18.0

#### If this is a bug, please provide steps for reproducing it.
https://sap.github.io/fundamental-ngx/#/core/shellbar#linksCollapseProductSwitcher

![image](https://user-images.githubusercontent.com/17496353/84010525-1235b980-a975-11ea-9bca-a98dcf2dfbf6.png)

**Comment by olshansky** [comment]
Looks fixed in v 0.24.2
![product-switch_position](https://user-images.githubusercontent.com/14160094/100741046-4947cd80-33e2-11eb-96d3-bc2e19dc6603.gif)
