### ISSUE TITLE
DateTimePicker events are not working

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2645]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In the DateTimePicker API docs you can find some APIs under Outputs for the DateTimePicker Component. They are used for listening if the date/time is changed. I tried the following APIs and they are not working:
* dateChange
* calendarChange
* timeChange

I have build this stackblitz project for which shows DatePicker and DateTimePicker: https://stackblitz.com/edit/angular-5yowaz
The Output API of DatePicker is working, but not the DateTimePicker.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

* On my local machine I'm using for my project: "@fundamental-ngx/core": "^0.17.0",
* On stackblitz it is: "@fundamental-ngx/core": "0.18.0",

#### If this is a bug, please provide steps for reproducing it.
Check out the above stackblitz line and open the console when you change the date/time

**Comment by JKMarkowski** [comment]
Hello @zaheral I don't why we kept those events in our library, you should take a look how the `[(ngModel)]` and `(ngModelchange)` works there, it throws an event everytime you change something in the component.

**Comment by zaheral** [comment]
Hi @JKMarkowski 
thanks for this tipp. I tried it out on the above stackblitz example and it works with ngModelchange.
