### ISSUE TITLE
<fd-tab> click event bug

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2648]
<fd-tab> element is not firing a click event when clicked.

example: 
```
<fd-tab [tabState]="'neutral'" (click)="myFunction()">
      <ng-template fd-tab-title-template>
        <span fd-tab-icon [icon]="''">1</span>
        <div fd-tab-process>
          <span>Settings</span>
        </div>
      </ng-template>
      <div class="tab-body-container">
      </div>
    </fd-tab>
```

myFunction will never be called.

**Comment by JKMarkowski** [comment]
Hi @shaysap,

I prepared some ways to handle click events on tab headers, It's currently on PR. I will let you know when it's merged.

**Comment by shaysap** [comment]
What if I want to perform operations before the tab changes? What if I don't want the tab to change if those operations failed?

**Comment by shaysap** [comment]
Please take a look at my previous comment, I still need a solution for this problem
