### ISSUE TITLE
<fd-tab> can't be disabled

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2651]
<fd-tab> can't be disabled. This functionality is very basic and required for many use cases.

**Comment by shaysap** [comment]
Hey, I've upgraded to version 0.19.0 but still can't disable the tabs. Is there any way this can be done?

**Comment by droshev** [comment]
@shaysap could you provide us with a business use case so we can follow up with the designers.
You can contact me directly in slack

**Comment by droshev** [comment]
@shaysap feel free to reopen or create a new issue once you bring your business case
