### ISSUE TITLE
highlight.js v.10 doesn't support IE11

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2671]
At the moment we cannot migrate to version 10 of highlight.js as they dropped support for IE11.
https://github.com/highlightjs/highlight.js/issues/2501

**Comment by yyyc514** [comment]
You certainly could if you wanted to do client-side browser sniffing and just load v9 or v10 depending on whether IE11 was detected or not... best of both worlds.

**Comment by droshev** [comment]
We need to address this as it brings also a security issue

**Comment by joshgoebel** [comment]
Out of curiosity, how was this resolved?
