### ISSUE TITLE
User Menu image

### ISSUE THREAD

**Issue by JensSteckhan** [SAP/fundamental-ngx#2679]
#### Is this a bug, enhancement, or feature request?
It's partly a bug, partly a feature request 😃

#### Briefly describe your proposal.
Currenty, you can assign a user to a shellbar like this:
<fd-shellbar-actions [user]="fooUser">  (html)

fooUser.initials = 'xy'  (ts)
fooUser.image = '/api/userPic'

The image property overrides the initials.
That's all very well, but we have the following problem: our api/userPic connects to a service which doesn't have pictures for all of our users, but only for some.
If it has a picture, everything is working fine.
If there is no picture, the user menu only displays a circle filled with a color, no initials.
It would be great if the initials would be displayed when the image url does not provide an image
It would be even better if the userMenu could show some sort of default avatar like this:
![avatar](https://user-images.githubusercontent.com/9308805/84688407-9670d980-af3f-11ea-9b67-603573a333e7.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.18.0, Angular 9.1.7

#### If this is a bug, please provide steps for reproducing it.
Create a shellbar with a user menu. Set the initials to xy and the image to an invalid url.
You will see a coloured circle with no initials.

#### Is there anything else we should know?
I simply want to thank you for providing Fundamental-ngx and for your responsiveness to bug reports and feature requests!

**Comment by droshev** [comment]
@JensSteckhan - Can't you set initials as well?

**Comment by JensSteckhan** [comment]
@droshev That's just the point. If I set the initials as well, they are not displayed.

**Comment by JensSteckhan** [comment]
@droshev Any updates? There is no way to tell whether or users have maintained their image, so those who haven't end up with a coloured circle as avatar with no initials.

**Comment by salarenko** [comment]
@JensSteckhan in our opinion current behavior is correct and the responsibility for validation of image URLs should be on users side. You can do it on your side in multiple ways, like:
- downloading the image and passing it as base64 to our component
- using some third party library offering this functionality (like https://www.npmjs.com/package/is-image-url)

However I'm going to bring this during todays meeting.

**Comment by JensSteckhan** [comment]
@salarenko Thank you for the update and the useful links.
The reason why I think it would be nice if your component would do this is that a double download attempt could be thus avoided.

Anyway, for the time being, I will do the extra check on the client then.

Could it be that is-image-url is only meant to run under node and not on the client?
It requires is-image which in turn requires 'path' (which in turn requires server libs)?
Not sure, this could be my mistake ;-)

**Comment by JensSteckhan** [comment]
For the time being, I have implemented a workaround with double-loading as suggested:
I create an Image with the avatar url. In the onload function (= there is a valid avatar) I assign a user object with the image's url. In the onerror function (=no valid avatar) I assign no url but the initials.
Not perfect because of the double loading, but a lot better than a coloured circle.
Thank you for your help!
