### ISSUE TITLE
Button's arrow is not centered

### ISSUE THREAD

**Issue by Mino-Chen-Sap** [SAP/fundamental-ngx#2682]
Button's arrow is not located in the centre of the button.

The code is:
`   <button fd-button [fdMenu]="true" [fdType]="'transparent'"></button>`

![image](https://user-images.githubusercontent.com/51769949/84745408-17cf7700-afe7-11ea-9764-0855f9779347.png)

**Comment by salarenko** [comment]
Hey @Mino-Chen-Sap, Menu Button is not designed to be used as a button with icon only. If you want to use a button with only an icon check https://sap.github.io/fundamental-ngx/#/core/button#Button-icons.
