### ISSUE TITLE
The self- adjusting of calendar control doesn't work very well.

### ISSUE THREAD

**Issue by Mino-Chen-Sap** [SAP/fundamental-ngx#2683]
When the input box of calendar control is put on the right side.
Then click it, the popover of the calendar can't display fully.

fundamental version is 0.18.0

The example code is [here](https://stackblitz.com/run?file=src%2Fapp%2Fbutton-types-example.component.html)

![image](https://user-images.githubusercontent.com/51769949/84747044-5c5c1200-afe9-11ea-8372-b702dd1f6ed8.png)

**Comment by salarenko** [comment]
Thanks for reporting an issue. Right now we do not support dynamic popover placement, however you can control it manually using `[position]` option.

**Comment by salarenko** [comment]
This topic will be continued in #2684
