### ISSUE TITLE
Could change the left and right for button

### ISSUE THREAD

**Issue by Mino-Chen-Sap** [SAP/fundamental-ngx#2686]
Could I exchange the left icon and right text via some parameter?
Make it like the second screenshot.

![image](https://user-images.githubusercontent.com/51769949/84756095-f1b0d380-aff4-11ea-887c-ad09a4319e38.png)

![image](https://user-images.githubusercontent.com/51769949/84756295-2fadf780-aff5-11ea-984c-4e7e77fb2757.png)

**Comment by salarenko** [comment]
@Mino-Chen-Sap Could you explain what is the Issue? If you are asking about changing menu icon button, it is possible only with overriding icon with styles, there is no common API to change it. I recommend getting familiar with Button Component and its API.
