### ISSUE TITLE
Loading-spinner always display even though [loading]="false"

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#2692]
#### Is this a bug, enhancement, or feature request?
Bug?

#### Briefly describe your proposal.
The loading spinner rotates continuously and are always display even though `<fd-loading-spinner [loading]="false"></fd-loading-spinner>`

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 8 and fundamental-ngx 0.12.0

#### If this is a bug, please provide steps for reproducing it.
Add a loading-spinner in the above mentioned versions

#### Is there anything else we should know?
(I hope I didn't miss any information that could have helped me solve this problem...)

**Comment by mikerodonnell89** [comment]
@JohnHavok this has been fixed in version 13 with this pr https://github.com/SAP/fundamental-ngx/pull/1537

Any chance you could update?

**Comment by JohnHavok** [comment]
> @JohnHavok this has been fixed in version 13 with this pr #1537
> 
> Any chance you could update?

Um, I've seen that PR ..
It was my plan B to upgrade to version 0.13, so perfect. 
Thank you for your response
