### ISSUE TITLE
Split button menu in platform is broken

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2704]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
The [split menu button](https://fundamental-ngx.netlify.app/#/platform/split-menu-button) in platform looks broken

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx platform 0.19.0 rc. 50
<img width="250" alt="Screen Shot 2020-06-17 at 11 15 12 PM" src="https://user-images.githubusercontent.com/4380815/84974113-995efc00-b0f0-11ea-9e26-5ba1e15b9b80.png">

**Comment by DeepakSap14** [comment]
https://github.com/SAP/fundamental-ngx/pull/2722 provides fix for this issue. hence closing it.
