### ISSUE TITLE
Cannot access 'SubmenuComponent' before initialization

### ISSUE THREAD

**Issue by ehmh2009** [SAP/fundamental-ngx#2721]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "^0.19.0"

#### If this is a bug, please provide steps for reproducing it.
Cannot easily provide steps for reproducing the problem, because problem occurred when upgraded from 0.18.0 to 0.19.0 (fine for 0.18.0).
(screenshot presenting error message in attachment)

![submenucomponent_bug_1906](https://user-images.githubusercontent.com/9335235/85135113-dbe21f00-b23d-11ea-8d98-93c62e3e3b7a.png)

**Comment by salarenko** [comment]
@ehmh2009 Could you share your code that's throwing this error?

**Comment by ehmh2009** [comment]
Unfortunately not, I will try to reproduce issue in separate project, then I can share the code.

**Comment by ehmh2009** [comment]
I attach sample project.
To reproduce:
1) unzip
2) npm install
3) ng serve
4) open in web browser and to go to console to find error message
[reproduce.zip](https://github.com/SAP/fundamental-ngx/files/4812412/reproduce.zip)

**Comment by salarenko** [comment]
Ok, I can see the issue. Today we will release path with the fix for v.19

**Comment by salarenko** [comment]
Hey @ehmh2009, `v0.19.1` is out
