### ISSUE TITLE
Template based Dialog dependencies

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2729]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Currently our template based Dialog requires the user to pass `DialogRef` and `DialogConfig` dependencies from context variables to the component:
```
<ng-template let-dialog let-dialogConfig="dialogConfig">
    <fd-dialog [dialogConfig]="dialogConfig" [dialogRef]="dialog">
    </fd-dialog>
<ng-template>
```
This the reason for this solution was a problem with dynamic configuration of `Injector` for component embedded inside `ng-template`, because of Angular configuring `Injector` based on where the template __has been declared__.

Current approach costs us:
- additional markup on user side (passing context variables)
- shifted header/body/footer initialization phase (dependencies are passed on `ngContentInit` phase)

Actions for this ticket:
- analyzing current solution in search of improvements, to get rid of context variable passing, or shifted initialization phase
- analyzing how other libraries handle this problem

**Comment by droshev** [comment]
@salarenko still valid?

**Comment by salarenko** [comment]
@droshev yup, still valid and it looks like finally the day has come and with Angular v.14 there is a way to configure injector for `ng-template` 🎉 
[more here](https://netbasal.com/new-in-angular-13-pass-an-injector-to-embedded-views-cb71155025b4)

**Comment by droshev** [comment]
@salarenko you are still keeping an eye! that is great!
