### ISSUE TITLE
Combobox readonly mode

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2733]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Combobox in readonly mode can be interacted with, using `ArrowUp`/`ArrowDown` and `Space`.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.19.0

#### If this is a bug, please provide steps for reproducing it.
Navigate to readonly Combobox with Tab and play with arrow keys

![combobox-read-only](https://user-images.githubusercontent.com/17496353/85295929-ed773100-b4a0-11ea-91e1-0ce03c2dbdce.gif)

**Comment by JKMarkowski** [comment]
Fixed
