### ISSUE TITLE
Combobox opening list on enter

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2734]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When trying to open `Combobox` options list with `Enter` popover opens and the automatically closes.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.19.0

#### If this is a bug, please provide steps for reproducing it.
Click on expand arrow in `Combobox` control and then press `Enter`

![combobox-expand](https://user-images.githubusercontent.com/17496353/85296266-6aa2a600-b4a1-11ea-8e19-521b71ac12b3.gif)

**Comment by fkolar** [comment]
It looks like whole keyboard navigation is not working.

**Comment by salarenko** [comment]
@fkolar Combobox has some keyboard-interaction related issues, but it works fine for basic simple cases. However we need to revisit this component.

**Comment by Smiranin** [comment]
Can't reproduce this issue, I think it isn't actual.
