### ISSUE TITLE
Cant Use Notifications Component: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by jaca0900** [SAP/fundamental-ngx#2755]
#### Is this a bug, enhancement, or feature request?
BUG
#### Briefly describe your proposal.
When trying to use notifications feature I've encountered this issue:
<img width="482" alt="consoleSuperError" src="https://user-images.githubusercontent.com/6820093/85840489-d4ba9400-b79c-11ea-83c2-7d060a52e13e.PNG">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version 9
Fundamental 0.19.1

#### If this is a bug, please provide steps for reproducing it.
Below is a sample project:
unzip
npm install
npm start
go to **localhost:4200** and click **open from component** button

#### Please provide relevant source code if applicable.
[norificationReproduce.zip](https://github.com/SAP/fundamental-ngx/files/4836333/norificationReproduce.zip)
unzip
npm install
npm start

#### Is there anything else we should know?

**Comment by droshev** [comment]
@jaca0900 Thank you for the contribution. We triggered a release: `0.19.2` which includes your fix. We will bring it to `0.18.2`
