### ISSUE TITLE
Date-Picker makes no changes after patching null/undefined as value

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2757]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
I'm using a observer to offer the value to the date-picker like following
```
<fd-date-picker
   [ngModel]="(dateValue$ | async)"
   ...
>
</fd-date-picker>
```
If the observer gets an FdDate as value, then the changes will taken from the date-picker. But in case of null or undefined, nothing happens. The input field of the date-picker is not changing.
I created a stackblitz example here: https://stackblitz.com/edit/angular-rlacup-p2hzgp?embed=1&file=src/app/date-picker-complex-i18n-example.component.html

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "rxjs": "^6.5.4",
    "@angular/core": "^9.1.7",
    "@fundamental-ngx/core": "^0.17.0",
Can also check the stackblitz example

#### If this is a bug, please provide steps for reproducing it.
Steps are described in the stackblitz example

**Comment by JKMarkowski** [comment]
Hello @zaheral, I just discovered, that we have some issues with change detection. The PR has been created. Let me know, if you need some fix workaround.

**Comment by zaheral** [comment]
Hi @JKMarkowski , thanks for the fix. Looking forward for it
