### ISSUE TITLE
DatePicker: How to parse a date string and ngModelChange event

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2769]
#### Is this a bug, enhancement, or feature request?
Enhancement/Bug

#### Briefly describe your proposal.
I have an issue the event-handler if I'm using an custom DateFormatParser.
The event-handler function will be triggered after the user is changing the date. In this case, I'm just focusing on manual change and not changes through the calendar. Before this happens, the parse function will be triggered at first and the result of the parse will go to the event-handler function.

There are several use cases, where we need to make differentiate when the user is entering the date:
<ol>
  <li>Empty input field (user removed the date)</li>
  <li>Uncomplete date like 02/02/201 (user is currenlty changing the year)</li>
  <li>Invalid date like 02/02/cyx (user entered something wrong)</li>
  <li>Invalid date like 30/02/2020 (day doesn't exist)</li>
</ol>

I need to make different between the first point and the other points. Empty field, means I can make a update on the data, because user wants to clear the date (which can be optional). Invalid date, means either the user is currently editing the date or he maked some mistake. In this case, I would ignore the data and just change the state of the date-picker to error.

In the end I need to make different return values from the parse function, the the event-handler knows what to do. I tried with null/undefined/empty-string (with help of any) and also with FdDate(NaN, NaN, NaN). But if the parse function has this kind of result, then it will be retriggered again, but with the param 'InVaLiDDaTe'. Then I don't know how to make a difference! The result of the second trigger goes to the event-handler.

I have created an example to work on it: https://stackblitz.com/edit/angular-rlacup-jzqg11?embed=1&file=src/app/date-picker-complex-i18n-example.component.html

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "rxjs": "^6.5.4",
    "@angular/core": "^9.1.7",
    "@fundamental-ngx/core": "^0.17.0",

#### If this is a bug, please provide steps for reproducing it.
This is not directly an bug, but it is a workaround, because a bug.
The bug is that on different locales than en-US the event-handler is working different. This is because of the default parse-function. Therefore, it is required to create an custom parse-function.

#### Please provide relevant source code if applicable.
Check example

**Comment by zaheral** [comment]
Hi colleagues,
just want to check if there are some news on this one.

CC: @JKMarkowski

**Comment by JKMarkowski** [comment]
@zaheral 
I think this situation occurs, becuase we force invalid date, even when it's empty by having those statements:
Single:
![image](https://user-images.githubusercontent.com/26483208/87773990-3a41f380-c824-11ea-9424-3e9e2afe9665.png)

Ranged:
![image](https://user-images.githubusercontent.com/26483208/87773964-2dbd9b00-c824-11ea-850a-ff1dec9764eb.png)

Removing them will cause that behaviour. So the object has differences between null and invalid
![datepickernewapproach](https://user-images.githubusercontent.com/26483208/87774586-02877b80-c825-11ea-92d5-1afd7ea1608a.gif)

**Comment by zaheral** [comment]
Hi @JKMarkowski 

I found the mentioned code: https://github.com/SAP/fundamental-ngx/blob/0b864f8e0c7d5e7e5a7610e1f0d79821bfbbe6d6/libs/core/src/lib/date-picker/date-picker.component.ts#L436

But is there a way how to get this workaround solution working? With this issue, we have a business logic gap and we could not make use of this solution.
