### ISSUE TITLE
Components having menu (ex: popover, menu button) do not work under shadow dom.

### ISSUE THREAD

**Issue by rajeev-learner** [SAP/fundamental-ngx#2772]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
There is an Angular application which has a Home component, in which shadow dom is enabled. Now, when I try to use popover component inside the Home component, the popup menu does not open up upon mouse click. It starts working as expected as soon as I turn off ViewEncapsulation.ShadowDom on Home component.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "^0.17.1",
"@angular/core": "~9.1.3",

#### If this is a bug, please provide steps for reproducing it.
1. enable encapsulation: ViewEncapsulation.ShadowDom for a component.
2. use <fd-combobox> in component's template
3. load the ui and observe the combo control.
Issue: popup menu does not open upon mouse click.

**Comment by droshev** [comment]
we can reproduce it [here](https://stackblitz.com/edit/angular-zxxnky?file=src/app/popover-example.component.ts)

**Comment by JKMarkowski** [comment]
Adding `[closeOnOutsideClick]="false"` to popover is workaround there. [this](https://github.com/SAP/fundamental-ngx/blob/master/libs/core/src/lib/popover/popover-directive/popover.directive.ts#L393) method doesn't work properly with shadow dom.
