### ISSUE TITLE
Use cdk auto resize options for platform textarea growing

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#2775]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Related to #2691 , use cdk resize options and add enhancements to achieve auto growing by rows and height.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Ang 9

**Comment by droshev** [comment]
re-evaluate and fix if needed-otherwise we should close it

**Comment by manjunathanagaraj** [comment]
This is more a technical 'nice to have'. Closing it now. Can always reopen if at all need arises.
