### ISSUE TITLE
Defect Hunting - June 30, 2020

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2777]
List all the issues here:
Stefano takes Safari
Mike takes Chrome
Inna takes FF
Jedrzej takes IE11
Michal takes Edge

- [x] stackblitz for action bar - https://sap.github.io/fundamental-ngx/#/core/action-bar#actionbar-standard not working #2784
- [x] dialog with popover overflow issue - the popover doesn't go beyond the borders of the dialog even if it is bigger
![Screen Shot 2020-06-30 at 10 28 32 AM](https://user-images.githubusercontent.com/4380815/86138464-82d77e00-babc-11ea-916b-5949280a93bd.png)

Inna: Ii tested the current master and it looks like it's already fixed. Here's a screenshot with a similar example:
<img width="1454" alt="Screen Shot 2020-06-30 at 4 16 15 PM" src="https://user-images.githubusercontent.com/39598672/86173116-7a4b6b80-baed-11ea-8e25-27f3c609d6a1.png">

- [x] select has white corners - Inna - https://github.com/SAP/fundamental-ngx/pull/2779
![Screen Shot 2020-06-30 at 10 53 34 AM](https://user-images.githubusercontent.com/50607147/86141660-502f8480-bac0-11ea-8091-ff97b3dad570.png)

- [x] select has a double focus - fixed in #2796 
![Screen Shot 2020-06-30 at 10 53 45 AM](https://user-images.githubusercontent.com/50607147/86141647-4b6ad080-bac0-11ea-8b7e-bdf62fdf8c32.png)

**Comment by JKMarkowski** [comment]
Checkbox - when user clicks fast on tristate enabled
![image](https://user-images.githubusercontent.com/26483208/86137140-38bac080-baed-11ea-9619-a9c85ec853c9.png)

Docs page logo is centered
![image](https://user-images.githubusercontent.com/26483208/86137170-407a6500-baed-11ea-9590-16f573a8bddf.png)

**Comment by mikerodonnell89** [comment]
When cozy tokenizer receives focus, outline is cut off on right side
![Screen Shot 2020-06-30 at 8 14 52 AM](https://user-images.githubusercontent.com/2471874/86138234-739c0480-baab-11ea-8ca2-ec6658c49d45.png)

Need to remove status indicator

Split button needs top/bottom margin on examples

Buttons for example code copy and stackblitz need margin

Docs resize issue where at 992 pixels the content gets darkened but the side nav is normal

**Comment by salarenko** [comment]
- Multi input/Tokenizer filtering causes performance input which might lead to browser crash. Go to Multi Input, open mobile mode and start typing in text input.
![multi-2](https://user-images.githubusercontent.com/17496353/86141267-242cf700-baf2-11ea-868f-278b339e798a.gif)

- Navigating through Multi Input list element and selecting them with `Space` is selecting list items but does not update checkbox state.
![multi-1](https://user-images.githubusercontent.com/17496353/86141291-2b540500-baf2-11ea-91df-71408b79d27f.gif)

**Comment by InnaAtanasova** [comment]
- [ ] Breadcrumb has an `/` after the last element 
<img width="566" alt="Screen Shot 2020-06-30 at 10 08 08 AM" src="https://user-images.githubusercontent.com/39598672/86143423-676f7180-bac2-11ea-92b5-208f403a213e.png">

- [ ] Combobox highlighting issue
Select Apple and open the dropdown menu. The `apple` part of Pineapple is highlighted
<img width="1113" alt="Screen Shot 2020-06-30 at 10 19 55 AM" src="https://user-images.githubusercontent.com/39598672/86143546-8e2da800-bac2-11ea-8302-c995d34502cc.png">

- [ ] Tokenizer has performance issues
Go to Tokenizer example and start adding new tokens. It takes time to add the new token and at some point the browser stops working

- [ ] Mega Menu component should be deprecated

- [ ] Select component should be deprecated

- [ ] Pagination - should not display `...` in the case where we have < 1 2 3 4 5 >

- [ ] Inverted link issues - different from styles and should be used in dark mode

- [ ] RTL issue with icon and notifications in Shellbar
<img width="94" alt="Screen Shot 2020-06-30 at 10 59 35 AM" src="https://user-images.githubusercontent.com/39598672/86144130-478c7d80-bac3-11ea-9107-1569d780ddfd.png">
<img width="89" alt="Screen Shot 2020-06-30 at 10 59 28 AM" src="https://user-images.githubusercontent.com/39598672/86144132-48251400-bac3-11ea-97dc-3a3404d9acee.png">
