### ISSUE TITLE
Select in dialog is not behaving properly

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2780]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
add a select in a dialog is not behaving properly
https://stackblitz.com/edit/angular-pvek7l?file=src/app/dialog-example.component.ts

Can we introduce a doc example where we have select in dialog?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

`@fundamental-ngx/core` version `0.20.0-rc.13`

#### If this is a bug, please provide steps for reproducing it.

https://stackblitz.com/edit/angular-pvek7l?file=src/app/dialog-example.component.ts
#### Is there anything else we should know?
<img width="598" alt="Screen Shot 2020-06-30 at 6 08 13 PM" src="https://user-images.githubusercontent.com/4380815/86181796-b20ddf80-bafc-11ea-92fa-c005b838e4ec.png">

**Comment by fkolar** [comment]
I did quick test to test several scenarios:

- Test material select in material dialog

![Screen Shot 2020-07-01 at 8 35 42 AM](https://user-images.githubusercontent.com/17149942/86213303-c80db580-bb79-11ea-81e8-8c0ff687a483.png)

-  Test Our select in material dialog
![Screen Shot 2020-07-01 at 8 41 15 AM](https://user-images.githubusercontent.com/17149942/86213347-d6f46800-bb79-11ea-9143-bfbac149597f.png)

-  Test Our select in our dialog with ng-template

![Screen Shot 2020-07-01 at 8 41 15 AM](https://user-images.githubusercontent.com/17149942/86213380-e8d60b00-bb79-11ea-84b8-e9c05351cf12.png)

-  Test Our select in our dialog dialog as component

![Screen Shot 2020-07-01 at 8 56 06 AM](https://user-images.githubusercontent.com/17149942/86213400-f25f7300-bb79-11ea-9967-8599c36e4c93.png)

What I noticed that cdk overlay has z-index 1000, just like our dialog, so I suggest here to do 999. 

please check out my branch where you can better troubleshoot the problem: 
https://github.com/SAP/fundamental-ngx/tree/SelectFix


@droshev , @JKMarkowski , @salarenko

**Comment by salarenko** [comment]
Irrelevant with current code-base. Might be brought back if #2813 reopens.
