### ISSUE TITLE
Unable to clear fd-form-control state

### ISSUE THREAD

**Issue by shaysap** [SAP/fundamental-ngx#2809]
Bug:
It is not possible to clear fd-form-control state after setting it.

The only way to get rid of an error state (for example) is by setting another state. The default (original) state can't be returned to.
Setting the state to anything other then 'success' | 'error' | 'warning' | 'information' results in a compilation error.

Please provide the option to clear the fd-form-control state.

Example:
`        <input fd-form-control
               formControlName="eventName"
               [state]="settingsForm.controls['eventName'].errors? 'error' : 'success'">`

I'm not interested in setting the input state to "success" if the form control is valid. I want it to return to it's original state.

**Comment by salarenko** [comment]
I'm not sure what is the problem here.  I don't know if you are aware of it, but code sample you posted is invalid. Maby thats what causes the error?
Here is an easy example how to change form control states:
https://stackblitz.com/edit/angular-ivy-mtwgdf

**Comment by shaysap** [comment]
Thanks for the example, It would have been great if you showed this example in your documentation.
We are not supposed to guess that 'null' resets the state

**Comment by salarenko** [comment]
Sorry, we thought this is quite clear, but perhaps you are right and we should be more precise in this case.
![image](https://user-images.githubusercontent.com/17496353/86578948-ed852f80-bf7c-11ea-9393-4ef3e7a7ef24.png)
