### ISSUE TITLE
Enhancement Request: Time Zone Field Required in DateTime Picker

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#2816]
#### Is this a bug, enhancement, or feature request?
_Enhancement_

#### Briefly describe your proposal.
_For certain objects/business documents (e.g. a service order or activity) we need to select date and time related to a specific time zone. Ideally, we can select the time zone already in the picker and not in an additional field only._

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
_All_

#### If this is a bug, please provide steps for reproducing it.
_n/a_

#### Please provide relevant source code if applicable.
_n/a_

#### Is there anything else we should know?
_n/a_

**Comment by droshev** [comment]
@estelaxu3 @jessmetivier let's follow up on that with the other designers
