### ISSUE TITLE
Time-Picker makes no changes after patching null/undefined as value

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2824]
#### Is this a bug, enhancement, or feature request?
Bug
Very similar to this one: https://github.com/SAP/fundamental-ngx/issues/2757

#### Briefly describe your proposal.
I'm using an observer to offer the value to the time-picker like following
```
<fd-time-picker
   [ngModel]="(value$ | async)"
   ...
>
</fd-time-picker>
```
If the observer gets a TimeObject as value, then the changes will be taken from the time-picker. But in case of null or undefined, nothing happens. The input field of the time-picker is not changing.
I created a stackblitz example here: https://stackblitz.com/edit/angular-rlacup-v8vc4w?embed=1&file=src/app/fd-time-picker-example.component.ts

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
"rxjs": "^6.5.4",
"@angular/core": "^9.1.7",
"@fundamental-ngx/core": "^0.17.0",
```
Can also check the stackblitz example

#### If this is a bug, please provide steps for reproducing it.
Steps are described in the stackblitz example

**Comment by hoya1101** [comment]
Hi, do we have this fix patched in fundamental-core version 0.20.0 at least?
