### ISSUE TITLE
Locale support for TimePicker

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2825]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
The [fd-time-picker](https://sap.github.io/fundamental-ngx/#/core/timePicker) component has the opportunity to switch between a am/pm format and a 24 hours format. But the format is not changing based on the locale. Instead, you need to specify manually if you want ap/pm format or 24 hours with a flag (*[meridian]="true"*). If you change the locale value for fd-time-picker than nothing happens.

The problem here is that as a developer we don't know which locale which format should use. It would be great if the format is changing based on the locale like shown here in [momentJS](https://momentjs.com/) (see at Multiple Locale Support).

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use the current version.)
"@angular/core": "^9.1.7",
"@fundamental-ngx/core": "^0.19.2",

**Comment by stefanoScalzo** [comment]
Parse the locale to overwrite the meridian as some locales/languages do not support meridian, etc

**Comment by zaheral** [comment]
Hi @stefanoScalzo 
the idea is that with help of the locale, the fundamental component "time-picker" can check if it is in 24-hour format or 12-hour format. E.g.:
locale === "en-US" -> 12-hour format
locale === "de" -> 24-hour format

To avoid that every fundamental consumer is developing the logic to get this information (which language which format) again and again. It would be nice if it is developed once in fundamental

**Comment by zaheral** [comment]
Tested on the latest RC version "0.20.1-rc.50" with the workaround solution by creating a custom format-parser (TimeFormatParser) like described for the date-picker ticket: https://github.com/SAP/fundamental-ngx/issues/2769
Following results are coming:
* Parser-function is not triggered after changing the data in the input field. Instead the format-function is always triggered.
* Format function is triggered every time when input will be clicked.

**Comment by zaheral** [comment]
Hi All,

I'm trying a workaround by using a custom TimeFormatParser. With the date picker it worked, but with the time-picker, there are some issues. I have created an stackblitz example with more description about the issue: https://stackblitz.com/edit/fundamental-ngx-issue-2825?embed=1&file=src/app/example.component.html

@stefanoScalzo This issue is actually not solved. Can we please open it again.

CC: @droshev & @JKMarkowski

**Comment by zaheral** [comment]
@stefanoScalzo This issue is actually not solved. Can we please open it again.

**Comment by zaheral** [comment]
This issue is actually not solved. Can we please open it again.
CC: @JKMarkowski

**Comment by zaheral** [comment]
Hi @JKMarkowski  do we have some news on this one?

**Comment by zaheral** [comment]
Hi @JKMarkowski & @droshev 
do we have here some updates?

**Comment by zaheral** [comment]
It seems that with the newest version locale support is there. I close this ticket
