### ISSUE TITLE
Popup error message is hiding time-picker buttons

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2826]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Popup error message is hiding the time-picker buttons:
![Screen Shot 2020-07-08 at 15 34 53](https://user-images.githubusercontent.com/26272656/86925057-9e7ffb80-c130-11ea-951e-522568ac3bb1.png)

Is there a way how to make the error message popup going on the other side?
E.g. if time-picker popup is down then error-message-popup und on the top and vice-versa

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

    "@angular/core": "^9.1.9",
    "@fundamental-ngx/core": "^0.18.1",

#### Please provide relevant source code if applicable.
```
      <fd-popover>
        <fd-popover-control>
          <fd-time-picker
            [ngModel]="(value$ | async)"
            [state]="'error'"
          ></fd-time-picker>
        </fd-popover-control>

        <fd-popover-body>
          <fd-form-message type="error">
            translated(this is a custom error message)
          </fd-form-message>
        </fd-popover-body>
      </fd-popover>
```

**Comment by droshev** [comment]
@zaheral this should be tackled with #2802 
@JKMarkowski can you confirm this?

**Comment by JKMarkowski** [comment]
Hello @zaheral there is way to change position of popover, which has message inside body.

**Comment by zaheral** [comment]
Hi @JKMarkowski ,
thanks for this workaround. Unfortunately, I don't know this way ^^
Is it possible to get a stackblitz example?

**Comment by JKMarkowski** [comment]
Hello @zaheral, [there](https://stackblitz.com/edit/angular-ngencx?file=src/app/popover-example.component.html) is example of position usage :)

**Comment by JKMarkowski** [comment]
Hello @zaheral does the example solve issue for you?

**Comment by zaheral** [comment]
Hi @JKMarkowski 
thanks for the solution. But the field could be also at the bottom. THen the time picker popup goes also above the field like the message popup. I tried this with the provided solution by making the screen smaller and the result looks like this:
![Screen Shot 2020-07-20 at 09 18 30](https://user-images.githubusercontent.com/26272656/87910341-28519200-ca6a-11ea-8fcc-24c776df2fa0.png)

**Comment by JKMarkowski** [comment]
Hi @zaheral The only way to fix it is to have some dedicated form messages for every picker (time/date/datetime). Unfortunately there are no designs for that.

**Comment by zaheral** [comment]
Do you mean like this: 
![Screen Shot 2020-07-20 at 17 26 34](https://user-images.githubusercontent.com/26272656/87955624-4a6d0380-caae-11ea-873c-e267378d00e3.png)

How can this be done? I have no control over the date/time/datetime picker popups. In the select component it is done by passing the message in the select component:
```
<fd-select placeholder="Select value"
           stateMessage="Error message"
           [(value)]="selectedValue3"
           [state]="'error'">
    <fd-option *ngFor="let option of options" [value]="option">{{option}}</fd-option>
</fd-select>
```
Is there a similar way to do it for date/time/datetime?

**Comment by JKMarkowski** [comment]
@zaheral For now I will add this message behaviour. you can test it [here](https://deploy-preview-2802--fundamental-ngx.netlify.app/#/core/time#inForm)

**Comment by droshev** [comment]
@zaheral we don't have a design spec for those use-cases. Could you share when you plan to use a message with an open time picker?

**Comment by zaheral** [comment]
Hi @droshev & @JKMarkowski 

@droshev 
we are using it for the error messages. We have configurable field wrappers around the time/date/datetime picker. The customer can include configuration-rules to tell when this field is invalid (e.g. invalid if after 6 pm, invalid if it is a Sunday, ....). In such cases, the error message must come out, so the user can see why the selected time/date is invalid.

@JKMarkowski 
The above link referencing the time-component. I think you meant this link: https://deploy-preview-2802--fundamental-ngx.netlify.app/#/core/timePicker#inForm.
Unfortunately, the problem is now the other way around. The Message popover is nearly hidden now: 
![Screen Shot 2020-07-22 at 14 25 47](https://user-images.githubusercontent.com/26272656/88176315-5cbe7d00-cc27-11ea-8508-605011f13f72.png)

**Comment by rengare** [comment]
nothing to be done here

**Comment by zaheral** [comment]
@rengare This issue is actually not solved. Check the last comment from me. Can we please open it again.

**Comment by zaheral** [comment]
Thanks @JKMarkowski for the solution with the embedded message: https://stackblitz.com/edit/angular-issue-2984-fix
