### ISSUE TITLE
adopt latest tile component styles(excluding line and slide tiles)

### ISSUE THREAD

**Issue by vrathodsap** [SAP/fundamental-ngx#2827]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.

fd-tile is broken with latest version 0.19.2. I checked inside the fd-tile code of library and it has still 0.9.0 fundamental-style code. fd-tile component should adapt 0.10.0 version code.
![image](https://user-images.githubusercontent.com/68018509/86932578-d8093480-c139-11ea-82f1-7f25b5c5fe04.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
    "@angular/core": "~10.0.1",
    "@fundamental-ngx/core": "^0.19.2",
    "fundamental-styles": "^0.10.0",
```
#### Please provide relevant source code if applicable.
``` 
            <fd-tile>
              <div fd-tile-media>
                <span fd-identifier [size]="'m'" [glyph]="'home'" [colorAccent]="3"></span>
              </div>
              <div fd-tile-content>
                <h2 fd-tile-title>
                  Tile Title
                </h2>
                <p fd-tile-text>Tile Description</p>
              </div>
            </fd-tile>
```

**Comment by mikerodonnell89** [comment]
Hi @vrathodsap, we have just today released the new version of fundamental-ngx which utilizes the new tile: https://www.npmjs.com/package/@fundamental-ngx/core

**Comment by vrathodsap** [comment]
It is not fixed yet and still has 0.9.0 css inside fd-tile component

**Comment by droshev** [comment]
@vrathodsap It is true. The latest markup of tile from fundamental-styles (version 0.10.0) is not yet implemented in fundamental-ngx. We will bring it very soon

**Comment by mikerodonnell89** [comment]
@vrathodsap apologies, was confused with another component when I first made that comment
