### ISSUE TITLE
Combobox raises exception when used with *ngIf inside of reactive form

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#2831]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

I believe a bug in Angular (https://github.com/angular/angular/issues/20007) is causing an exception in combobox component.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 9, Fundamental-ngx 0.18.1, 0.19

#### If this is a bug, please provide steps for reproducing it.

The bug is a bit ephemeral, isn't reproducible every time, so I won't provide source code, but it can be boiled down to:
1) have combobox in a reactive form
2) hide combobox with an `*ngIf="show", show === false`
3) show combobox with `show === true`

You get an exception raised from this line https://github.com/SAP/fundamental-ngx/blob/release/0.18.1/libs/core/src/lib/combobox/combobox.component.html#L41

as `listMessages` is undefined. I believe it has to do with the mentioned Angular bug. When you show the combobox again (point 3) the formGroup references old ComboboxComponent object which has been detached from DOM (hence undefined in listMessages instead of an empty QueryList) 

#### Please provide relevant source code if applicable.

Until the bug is properly fixed in Angular, the problem can be silenced by adding a check if listMessages isn't undefined, like this: ```[hasMessage]="listMessages && listMessages.length > 0"```

**Comment by mikerodonnell89** [comment]
Hi @mpienkowski thank you for pointing this out.  I've opened a [pull request](https://github.com/SAP/fundamental-ngx/pull/2875) for this, but for future reference, we welcome contributions from developers outside the team so feel free to open a PR yourself!
