### ISSUE TITLE
Adding @Input and @Output to fd-checkbox

### ISSUE THREAD

**Issue by kalikalyandash** [SAP/fundamental-ngx#2834]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
for `fd-checkbox` it would be great if we can have an eventemitter and input data binding parameter. Currently two way binding is the only way to manipulate the state.
We want to run some actions along with changing the state of the checkbox.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
We are using 
angular: 8.2
```
"@fundamental-ngx/core": "0.13.2"
"@angular/core": "8.2.14"
```

#### If this is a bug, please provide steps for reproducing it.
N/A
#### Please provide relevant source code if applicable.
N/A
#### Is there anything else we should know?
N/A

**Comment by salarenko** [comment]
Hey @kalikalyandash. As for every form control Angular you can use `(ngModelChanges)` for template driven forms and `valueChanges()` for reactive forms. Adding some more emitters is an option and we will consider it in the future.
