### ISSUE TITLE
Datetime-Picker makes no changes after patching null/undefined as value 

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2849]
#### Is this a bug, enhancement, or feature request?
Bug
Very similar to this one: https://github.com/SAP/fundamental-ngx/issues/2757

#### Briefly describe your proposal.
I'm using an observer to offer the value to the datetime-picker like following
```
<fd-datetime-picker
   [ngModel]="(value$ | async)"
   ...
>
</fd-datetime-picker>
```
If the observer gets a FdDatetime as value, then the changes will taken from the datetime-picker. But in case of null or undefined, nothing happens. The input field of the datetime-picker is not changing.
I created a stackblitz example here: https://stackblitz.com/edit/fundamental-ngx-issue-2849?embed=1&file=src/app/example.component.ts

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "rxjs": "^6.5.4",
    "@angular/core": "^9.1.7",
    "@fundamental-ngx/core": "^0.20.0",
Can also check the stackblitz example

#### If this is a bug, please provide steps for reproducing it.
Steps are described in the stackblitz example

**Comment by zaheral** [comment]
Hi @JKMarkowski 
sorry for the dumb question, but in the linked PR I cannot see in which version the fix will be delivered.

**Comment by droshev** [comment]
in the latest
