### ISSUE TITLE
DateTime-Picker: Locale support is not working well with the event-handler

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2850]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.
This issue has to do with the locale and the even-handler. If the user is currently on entering the date, then the event-handler will get after the changes a wrong value (not invalid value!). As a Developer, I need to find out if the entered data is invalid. This scenario happens, when the user is not finished entering the data.
Here is a stackblitz example with more details regarding this behavior: https://stackblitz.com/edit/fundamental-ngx-issue-2850?embed=1&file=package.json

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "@angular/core": "^9.1.7",
    "@fundamental-ngx/core": "^0.20.0",
> See also at the  stackblitz example

#### If this is a bug, please provide steps for reproducing it.
See at the  stackblitz example

**Comment by JKMarkowski** [comment]
This behaviour requires implementation of custom parser, same as on DatePicker.

**Comment by zaheral** [comment]
Hi @JKMarkowski 
the workaround with the custom parser has, unfortunately, some issues as discussed in this issue item: https://github.com/SAP/fundamental-ngx/issues/2769

**Comment by rengare** [comment]
2

**Comment by zaheral** [comment]
Tested on the latest RC version "0.20.1-rc.50" with the workaround solution by creating a custom format-parser like described for the date-picker ticket: https://github.com/SAP/fundamental-ngx/issues/2769
Following results are coming:
* If the parse-function returns (new FdDatetime(new FdDate(NaN, NaN, NaN), { hour: 0, minute: 0, second: 0 })), then the last valid value will be patched to the event-handler (ngModelChange). This kind of return value is used, to tell the event-handler that the value is invalid. It would be even better to send somehow an invalid value back.
* If the parse-function returns (null), then the event-handler (ngModelChange) will be patched two times. One time with the last valid value and second with null. This kind of return value is used, to tell the event-handler that the user deleted the date from the input field. Currently, the Typescript definition of the parse-function does don't allow it, but it is required to tell the event-handler to clear the data. Therefore, we need to work with `return null as any`.

**Comment by zaheral** [comment]
Hi all,

I'm trying an workaround by using an custom DateTimeFormatParser. With the date picker it worked, but with the datetime-picker, there are some issues. I have created an stackblitz example with more description about the issue: https://stackblitz.com/edit/fundamental-ngx-issue-2850-2?embed=1&file=src/app/example.component.html

CC: @JKMarkowski

**Comment by JKMarkowski** [comment]
Hello @zaheral how does it work for you with this [workaround](https://stackblitz.com/edit/fundamental-ngx-issue-2850-2-6lmw39?file=src%2Fapp%2Fexample.component.html)?

**Comment by zaheral** [comment]
Hi @JKMarkowski 
yes it worked great. Thanks for this solution 👍
