### ISSUE TITLE
npm package size looks incorrect

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2854]
At the moment the size of the package in [npm](https://www.npmjs.com/package/@fundamental-ngx/core) looks too big - +20MB with over 3k files.
<img width="393" alt="Screen Shot 2020-07-13 at 6 43 55 PM" src="https://user-images.githubusercontent.com/4380815/87360891-05d6ea80-c539-11ea-9c01-0df9c83d9fda.png">

We need to investigate
- check the icon.css and all fundamental-styles import
- unnecessary imports
- do we include by mistake platform files
- etc.
time box: 1d?

**Comment by mikerodonnell89** [comment]
Do we need to distribute every bundle the build creates? We can get away with only publishing the minified UMD bundle.  And I do not see why we need to bundle the tgz as well.

**Comment by mikerodonnell89** [comment]
A lot of the size of our npm package comes from the 5 different bundles being built (UMD, es5, esm2015, fes5, fesm2015), which is standard procedure when building any Angular library.  Each bundle serves a purpose and the user will pull the bundle that they need to work with their browser.  Yes, every time a developer runs npm install on our library, they'll be pulling down 20+mb worth of stuff, but that doesn't affect the end user so I'd consider it a non-issue.  Take a look at Material or PrimeNG, same deal there (though they are using a different directory structure)

**Comment by droshev** [comment]
Maybe we can validate this with our demo app?

**Comment by salarenko** [comment]
Bundle size for sample app importing `FundamentalNgxCoreModule` module.
![image](https://user-images.githubusercontent.com/17496353/87554183-1b245400-c6b4-11ea-8057-2dab2f5824f7.png)

Complete stats: 
[stats-es2015.zip](https://github.com/SAP/fundamental-ngx/files/4925737/stats-es2015.zip)

**Comment by droshev** [comment]
Can we run the same tool on our doc site?

**Comment by salarenko** [comment]
Our docs app doesn't look well. We are fetching over 9MB at first load (probably documentation Core chunk requires dependency check). Core components stand for about 4MB of documentation bundle size.

Complete stats:
[stats.zip](https://github.com/SAP/fundamental-ngx/files/5001204/stats.zip)
