### ISSUE TITLE
Time-Picker not usable for duration use cases

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2856]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
The Time-Picker is wonderful for use cases to define a time point. The same component could be used for use cases for defining a duration (E.g. how long takes a job to be solved). The issue is that the time-picker has a limit of 24 hours. It would be nice if we have a flag to get the time-picker without this limitation because we have use cases where we need more than 24 hours and the time-picker looks wonderful to define a duration.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

"@angular/core": "^9.1.7",
"@fundamental-ngx/core": "^0.20.0",

**Comment by salarenko** [comment]
This is a potential enhancement that needs to be confronted with Fiori3 sepcification

**Comment by stefanoScalzo** [comment]
> This is a potential enhancement that needs to be confronted with Fiori3 specification

Technically wouldn't this be the date picker? Over 24 hours is considered a day

**Comment by JKMarkowski** [comment]
@zaheral  You should use other components for this case. For example dropdown, select or even step input

**Comment by zaheral** [comment]
Hi @JKMarkowski 
you are right. I could use input components as a base, but I need to develop the logic around it to make it suitable for duration use cases (E.g. time format validation, popup for selecting duration, ....). Dropdown and Select are not really suitable, because I don't know the time in front and these components are just offering to pick from a list of options.

I think that time-picker is a really great component of such use cases. If we could have a flag to avoid the limitation of 24-hours, then it would be perfect :)

**Comment by droshev** [comment]
@zaheral you are right. 
We can think about enhancing this component in the future.

Or you can help us by opening a PR and help us.
