### ISSUE TITLE
Problem encoding some icons

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#2865]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Some icons are not displayed because of content added in its CSS class.
Pagination: 
![image](https://user-images.githubusercontent.com/34537974/87662395-70b73a00-c762-11ea-8a0e-a8aede2a4096.png)
Alert: 
![image](https://user-images.githubusercontent.com/34537974/87668198-01464800-c76c-11ea-88ca-274a088ab100.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Fundamental 0.13.0 et fundamental-style 0.4.0
(test too in 0.14.0 and 0.5.0)

#### Is there anything else we should know?
I don't get this bug when the app is local but only when it's deployed (Tomcat server)

**Comment by JohnHavok** [comment]
(Maybe it's more of a ticket to fundamental-style in retrospect.)

**Comment by droshev** [comment]
@JohnHavok Could you open a new issue if you still face this issue?
