### ISSUE TITLE
Menu doesn't allow non-interactive items

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#2888]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.19.x, 0.20.0
#### If this is a bug, please provide steps for reproducing it.

Have a non-interactive item in the menu, you'll get an error message:

```
preview-25341a6da1ca77425572b.js:1 ERROR TypeError: Cannot read property 'setSubmenu' of undefined
    at MenuItemComponent._initialiseItemState (menu-item.component.ts:186)
    at MenuItemComponent.ngAfterContentInit (menu-item.component.ts:98) (...)
```

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-egq15h

#### Is there anything else we should know?

Non-interactive menu items were allowed in 0.18.x

It'd be great to have it fixed in 0.20.x

**Comment by salarenko** [comment]
Hey @mpienkowski, it is not possible by design. Menu is an interactive element which should have interactive or disabled items.
Could you give an example when do you need a non-interactive item inside the Menu?

**Comment by mpienkowski** [comment]
@salarenko The idea is to have something like headers in select field extended options example https://sap.github.io/fundamental-ngx/#/core/select#nested-options

**Comment by salarenko** [comment]
As previously mentioned this is not a part of Fiori3 design, but we will address the question and hopefully cover that feature.
