### ISSUE TITLE
Panel button styles are wrong when used in isolation

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#2904]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
If I use the panel in isolation, the button looks like this:
![image](https://user-images.githubusercontent.com/7091280/88387135-25300c00-cdb2-11ea-8adb-c296d64c794c.png)

If I also use a fd-button, it looks like this:
![image](https://user-images.githubusercontent.com/7091280/88387162-36791880-cdb2-11ea-8d9b-369af350bf13.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
https://github.com/JenniferStamm/fundamental-ngx-panel/blob/master/package.json

#### If this is a bug, please provide steps for reproducing it.
You can observe it using
https://stackblitz.com/github/JenniferStamm/fundamental-ngx-panel

The button is commented at the beginning of app.component.html. Including it changes the styles of the panel button as seen in the images above.

#### Please provide relevant source code if applicable.
https://github.com/JenniferStamm/fundamental-ngx-panel

**Comment by droshev** [comment]
@JenniferStamm thank you for reporting this issue. @salarenko let's downport the fix.
