### ISSUE TITLE
product switch: selected element(highlighted)

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2916]
![image](https://user-images.githubusercontent.com/4380815/88605825-10b97100-d049-11ea-9a0e-36a7d96f1821.png)
![image](https://user-images.githubusercontent.com/4380815/88605833-157e2500-d049-11ea-87ab-637bd2850e58.png)

**Comment by mikerodonnell89** [comment]
@droshev This problem actually originates in styles

**Comment by mikerodonnell89** [comment]
Should be fixed automatically with https://github.com/SAP/fundamental-styles/pull/1337
