### ISSUE TITLE
fix: (platform) create name property for fdp-form-field

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#2920]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
name should be applied on form field level. currently name property is not required by fdp-form-field. need to include this.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10

#### If this is a bug, please provide steps for reproducing it.
No

**Comment by droshev** [comment]
@manjunathanagaraj

**Comment by DeepakSap14** [comment]
This requirement seems not to be valid anymore.
In platform we have BaseComponent class, which has "name" property. Every component in platform is extending this class.
Even this property is available in Form components as well through extending BaseInput.

If we include name property in "fdp-form-field" then form components will have duplicate "name" field available. which does not look good.

@fkolar, is my point valid? or should we include "name" property in fdp-form-field.
