### ISSUE TITLE
Core: Toolbar Enhancements

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#2921]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
We should adopt/accept @fundamental-ngx/core implementation of Toolbar. There is no advantage of platform building its own component. However the following features could be added to the core Toolbar:
- Core implementation does not have priority feature.
- Core implementation does not have grouping of child elements.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
n/a
#### If this is a bug, please provide steps for reproducing it.
n/a
#### Please provide relevant source code if applicable.
n/a
#### Is there anything else we should know?
Requirements Checklist
- [ ] Should be able to add Button, Menu Button, Segmented Button, Select, Toggle Button, Checkbox Button, Input, Search Field, Combobox, Date Time, Label, Link, and Toolbar Separator.
- [ ] Should always place a child element designated fdpOverflowPriority="always" in the overflow menu.
- [ ] Should never place a child element designated fdpOverflowPriority="never" in the overflow menu.
- [ ] Should place a child element designated as fdpOverflowPriority="low" in the overflow menu before a child element designated as fdpOverflowPriority="high" as the toolbar width is reduced.
- [ ] Should remove child element designated as fdpOverflowPriority="disappear" from toolbar and not place it in the overflow menu, as the toolbar width is reduced.
- [ ] Should place child elements with the same fdpOverflowGroup value in the overflow menu together.

**Comment by fkolar** [comment]
@droshev what do you think in such enhacement in core ?

**Comment by fkolar** [comment]
@Betrozov I think your little requirements list directives with fdp prefix in has fd

**Comment by Betrozov** [comment]
Closed because already created here https://github.com/SAP/fundamental-ngx/issues/2890
