### ISSUE TITLE
Saucelab Integration to karma testing on different devices and browsers.

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#2930]
#### Is this a bug, enhancement, or feature request?
feature

#### Briefly describe your proposal.
Integrate Saucelab with fundamental-ngx to run the unit test on different devices and browsers in local and on PR push.

**Comment by manjunathanagaraj** [comment]
Basic Integration is done. For IE, there seems to be an issue as the test case executing seems to get stuck. Investigation in progress. Moving to sprint 48.

**Comment by manjunathanagaraj** [comment]
Integration is working. Test cases are failing on IE, Firefox and Edge browsers. This will be investigated as a separate task.
