### ISSUE TITLE
0.21.0 Defect Hunting - 30.07.2020

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#2939]
- [x] Checkbox on IE11 - Difference between fast/slow clicking - https://github.com/SAP/fundamental-ngx/pull/2949
![checkboxx](https://user-images.githubusercontent.com/26483208/88909370-4cc42000-d25b-11ea-93a6-63bbe26fbbc4.gif)

- [x] Combobox crashes on IE11 - 1) try to pick something from first combobox, 2) Open this combobox, 3) click on other combobox - try to blur - https://github.com/SAP/fundamental-ngx/pull/2966
![comboboxie11](https://user-images.githubusercontent.com/26483208/88909931-03c09b80-d25c-11ea-8d87-cc5c801308ed.gif)

- [x] Example of warning input - https://fundamental-ngx.netlify.app/#/core/input#input-states is not triggered - all browsers - https://github.com/SAP/fundamental-ngx/pull/2943
![image](https://user-images.githubusercontent.com/26483208/88923448-0af2a400-d272-11ea-9a83-67c5d52c4a1e.png)

 - [x] Multi input - all browsers - https://github.com/SAP/fundamental-ngx/pull/2942
![image](https://user-images.githubusercontent.com/26483208/88925784-4e9add00-d275-11ea-9c7a-1e0117d779f2.png)

- [x] Multi input keyboard support on IE11 - https://github.com/SAP/fundamental-ngx/pull/2942
![multiinput](https://user-images.githubusercontent.com/26483208/88927054-27dda600-d277-11ea-8106-20a5d48e87d4.gif)

- [x] Combobox limited width for container
![image](https://user-images.githubusercontent.com/26483208/89169158-274a5580-d57e-11ea-91f9-da9a108251f3.png)

**Comment by salarenko** [comment]
- [ ] Combobox - Chrome
![image](https://user-images.githubusercontent.com/17496353/89163392-ce76bf00-d575-11ea-9a30-1c18758db0d2.png)

- [ ] Combobox does not update its view value when used with Reactive Forms - Chrome
![combobox-reactive-forms](https://user-images.githubusercontent.com/17496353/89165391-c79d7b80-d578-11ea-85a0-bc7eca2027cc.gif)

- [ ] Datepicker/Datetimepicker/Timepicker opening on input click - Chrome
![datepicker-opening](https://user-images.githubusercontent.com/17496353/89165402-ca986c00-d578-11ea-8fea-1d59a804ae5b.gif)

- [ ] Datepicker in disabled state is interactive - Chrome
![datepicker-disabled](https://user-images.githubusercontent.com/17496353/89165598-121ef800-d579-11ea-8b59-d43130c41f01.gif)

- [ ] Multi Input in disabled mode is interactive - Chrome
![multi-input-disabled](https://user-images.githubusercontent.com/17496353/89166794-dbe27800-d57a-11ea-8a01-1b1e2c9c5574.gif)

- [ ] Multi Input in compact mode has space on the right of the toggle button - Chrome
![image](https://user-images.githubusercontent.com/17496353/89166861-f1f03880-d57a-11ea-9c47-5a3378449045.png)

- [ ] Multi Input in mobile has misaligned list items - Chrome
![image](https://user-images.githubusercontent.com/17496353/89167905-52cc4080-d57c-11ea-9a9e-2d910b4756f5.png)

- [ ] Panel wrong button state when initially expanded - Chrome #2937
![image](https://user-images.githubusercontent.com/17496353/89169168-2a454600-d57e-11ea-8001-c66439110aa3.png)
