### ISSUE TITLE
Table - implement table with sortable col headers, context menu and fix col header

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#294]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
- Add table with sortable column headers
- Add table with column headers with context menu
- Add table with fix column header and context menu

**Comment by thomasgauvin** [comment]
@mikerodonnell89 
Can we discuss the table component?

**Comment by droshev** [comment]
@mikerodonnell89 what is the status of this issue?
