### ISSUE TITLE
fix: (core) configure angular.json for linting

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#2940]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
At the moment Tslint works only for docs.
Need to configure `angular.json` lint to work with `core` and `platform`
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10
#### If this is a bug, please provide steps for reproducing it.
NA
#### Please provide relevant source code if applicable.
NA
#### Is there anything else we should know?
NA

**Comment by salarenko** [comment]
Closed by #2941
