### ISSUE TITLE
fix: (core) Add title to core Panel toggle button

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#2944]
#### Is this a bug, enhancement, or feature request?

enhancement

#### Briefly describe your proposal.

Taking into account that panel toggle button doesn't have text inside it (only icons) it would be nice to have `title` on this toggle button with the same value as `expandAriaLabel`.
In this case when the button is hovered it will show a title pointing an user what click action will lead to.

**Comment by stefanoScalzo** [comment]
This would be implemented by the user as the panel toggle button is just an fd-button
In order to achieve this I would use text-interpolation on the button with a ViewChild to detect when the button is being hovered on
