### ISSUE TITLE
Unify the behavior of MultiInput in compact and cozy mode

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2948]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
MultiInput component behaves differently based on compact/cozy mode. Behavior should be unified and do not change based on display mode.

**Comment by mikerodonnell89** [comment]
@salarenko this is directly from the interaction specification, I've had a few conversations about it with the designers and this is what they want

**Comment by salarenko** [comment]
I don't think designers understand that most of desktop applications are using Cosy versions of our components. If we want to create mobile-specific behavior for our component it should be based on `[mobile]` flag.

**Comment by droshev** [comment]
@salarenko could you follow up with the designers?

**Comment by InnaAtanasova** [comment]
@droshev we have this behaviour but it's not documented as it's against the Fiori 3 specs. Should we document it or keep it hidden?

**Comment by droshev** [comment]
Let's keep it as it for now
