### ISSUE TITLE
Tree component implementation

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2959]
Implement Tree Component
- [x] write gitbook specification
- [x] review gitbook spec
- [ ] implement the component

**Comment by g-cheishvili** [comment]
I think we should split implementation into two components.
One would be core component, which would be responsible for Tree-like structure rendering and orchestration for states. Without any kind of visualisation by itself. It would manage tree state. Something like this, but better:
https://github.com/g-cheishvili/ngx-tree/tree/master/projects/ngx-tree/src/lib/modules/core/components/tree-core
This component can be opened up for developers to use, for implementing any tree-like structure, it even can satisfy needs for creating tree-tables

Second component would be component, complying with Fiori and Horizon specs. It would be just skeleton of it.

Benefit would be additional flexibility for users. They would be able to, if wanted, create their own tree based components, without worrying about the iterations, searches through it, render as they wish and open up as they wish.

If we create second component the way that we start using developments from FN, even selection, focus, disable and all sorts of other things can be utilized here and implementation would be very fast and easy
