### ISSUE TITLE
Combobox with displayFn  does not pre populate value

### ISSUE THREAD

**Issue by vinitkumar33** [SAP/fundamental-ngx#2968]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Can not pre populate value of combo box when its values are model with multiple attribute and has a displayFn.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Fundamental-ngx 0.18.0

#### When a combo-box is used with display function where the dropdownValues is an object with multiple attribute. When we try to pre populate the combobox with default value, it doesnt work. It works perfectly fine for combobox without displayFn.

In the below example, I have tried to achieve populating combobox value on click of a button. I have two combo-box  - One (disabledComboControl) properly populates values but the other one doesnt (disabledComboControl1). I have tried populating the value in multiple ways.. 
//this.customForm.controls.disabledComboControl1.patchValue('Newval'); or
//this.customForm.controls.disabledComboControl1.patchValue({name1: 'AppleNew'}); Or
//this.customForm.setValue({disabledComboControl: '1', disabledComboControl1: '2', 
         disabledComboControl2: '3'});

None of the above works

**HTML**
```
<form [formGroup]="customForm">
    <fieldset fd-fieldset class="flex-form">
        <div fd-form-item>
          <label fd-form-label for="form-combo-2">Select Fruit11:</label>
            <input type='text' formControlName="disabledComboControl2"/>
            <label fd-form-label for="form-combo-2">Select Fruit:</label>
            <fd-combobox formControlName="disabledComboControl" fd-form-control id="form-combo-2"></fd-combobox>
            <fd-combobox [id]="ey"
                         formControlName="disabledComboControl1"
                         [dropdownValues]="dropdownValues"
                         [displayFn]="displayFnt">
            </fd-combobox>
        </div>
         <button fd-button
                        class="searchPageButton text-color" (click)="btnClicked()"
                        i18n="Clear|Clear@@SEARCH_VIEW_COMPONENT.Clear">click</button>
    </fieldset>
</form>


#### 
**Ts file**
import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
    selector: 'fd-combobox-disabled-example',
    styleUrls: ['combobox-disabled-example.component.scss'],
    templateUrl: './combobox-disabled-example.component.html'
})
export class ComboboxDisabledExampleComponent {
    dropdownValues = ['Apple', 'Pineapple', 'Banana', 'Kiwi', 'Strawberry'];
    dropdownValues1 = [{name1: 'Apple1'}, {name1: 'Pineapple1'}, {name1: 'Banana'}, {name1: 'Kiwi'}, {name1:'Strawberry'}];
searchTerm: string;
    customForm = new FormGroup({
        disabledComboControl: new FormControl({ value: 'Kiwi12', disabled: true }, Validators.required),
        disabledComboControl1: new FormControl({value: null, disabled: false }, Validators.required),
        disabledComboControl2: new FormControl({ value: 'Ki21', disabled: false }, Validators.required)

    });

    btnClicked() {
         this.customForm.setValue({disabledComboControl: '1', disabledComboControl1: '2', 
         disabledComboControl2: '3'});

      //this.customForm.controls.disabledComboControl.patchValue('AppleNew');
      //this.customForm.controls.disabledComboControl1.patchValue();
      //this.customForm.controls.disabledComboControl2.patchValue('new1');

    }

    displayFnt(value) {
      return value.name1;
    }
}

#### Please provide relevant source code if applicable.
Provided above

#### Is there anything else we should know?

**Comment by mikerodonnell89** [comment]
@vinitkumar33 So, a few problems with the source you've provided:

- you cannot use fd-form-control as a directive on fd-combobox.  fd-form-control is a component
- fd-combobox with [id]="ey" - not sure what this is supposed to be but it will throw an error
- I am confused as to why the combobox in the example is using `dropdownValues` instead of `dropdownValues1`, when dropdownValues1 is the array with objects containing multiple properties
- Assuming you meant to use `dropdownValues1`, you should be building new FormControls like so: `new FormControl({name1: 'Mango', disabled: false }, Validators.required)` emphasis on using `name1` instead of `value`
- Similarly when using `patchValue` you cannot simply pass a string, you must pass an object like so `.patchValue({name1: 'Orange'})` and you should see the desired effect
