### ISSUE TITLE
Core maintenance

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2976]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Core library needs to update its status on its deprecated elements:

- [x] Remove Dropdown
- [x] Remove Identifier
- [ ] Remove checkbox crash notice for v0.22.0
- [ ] Remove radio button crash notice for v0.22.0
- [x] Remove Input Group Number PR #2993
- [x] Remove Loading Spinner PR #2988
- [x] Remove Select Native
- [ ] Remove usages of `fd-segmented-button` directive and the directive itself
- [ ] Get rid of Shellbar related classes from InputGroup

**Comment by katekozlowska** [comment]
work will be continued under https://github.com/SAP/fundamental-ngx/issues/3079
