### ISSUE TITLE
chore: cross team code style enforce

### ISSUE THREAD

**Issue by valorkin** [SAP/fundamental-ngx#2980]
#### Is this a bug, enhancement, or feature request?
**enhancement**
#### Briefly describe your proposal.
https://palantir.github.io/tslint/rules/typedef/

"parameter" checks type specifier of function parameters for non-arrow functions.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
**master**

**Comment by droshev** [comment]
@valorkin shall we push this forward. If yes, what would be your estimate?

**Comment by g-cheishvili** [comment]
Closing this as we do not use TSLint and if described functionality is still needed, we should create new issue
