### ISSUE TITLE
Popup error message overlying calendar of date-/datetime-picker

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#2984]
#### Is this a bug, enhancement, or feature request?
Bug/Enhancement

#### Briefly describe your proposal.

The error message is over the calendar popup:
![translated(udfMeta group1_field13)](https://user-images.githubusercontent.com/26272656/89303829-fd239100-d66c-11ea-8ac0-9830d9110b52.png)

A similar issue was solved in the time-picker: https://github.com/SAP/fundamental-ngx/issues/2826
The same solution for date-/datetime-picker would be perfect.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "0.20.1",

**Comment by mikerodonnell89** [comment]
@zaheral how was the issue "solved" in the time-picker example?  Looks like that issue was closed as a won't-fix

**Comment by zaheral** [comment]
Hi @mikerodonnell89 , the issue is still open. The expected solution will be that the error message will be shown as part of the calendar-pop. That means, you have just one popup and therefore, no overlaps.

**Comment by zaheral** [comment]
Thanks @JKMarkowski for the solution with the embedded message: https://stackblitz.com/edit/angular-issue-2984-fix
