### ISSUE TITLE
Adding the events for the Input under platform component 

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#2994]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

Adding events like Keyup, Keydown and few more events. These missing event will be added as part of enhancement and addressed in the different PR

**Comment by droshev** [comment]
@manjunathanagaraj

**Comment by Lokanathan-k** [comment]
since the input uses form based approach these additional validation functionality are not required to be duplicated.
