### ISSUE TITLE
Multi select menu goes below the modal footer

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#3000]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
The multi select menu goes below the modal footer (or header).
![image](https://user-images.githubusercontent.com/34537974/89536771-aa76e000-d7f8-11ea-8eba-e876e20a6544.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Fundamental-ngx: 0.14.0
Fundamental-style: 0.5.2

#### Please provide relevant source code if applicable.
```html
[..]
<fd-modal-body>
  <div fd-form-item>
    <label class="fd-has-display-block">...</label>
    <select fd-form-control [compareWith]="compare" [(ngModel)]="selectedCurrency">...</select>
  </div>
  <div fd-form-item>
    <label class="fd-has-display-block">...</label>
    <fd-multi-input [dropdownValues]="statuses" [(ngModel)]="selected" [displayFn]="displayNameFn"></fd-multi-input>
  </div>
</fd-modal-body>
[...]
```

#### Is there anything else we should know?
Also the checkbox label is offset upwards and aligns perfectly when the checkbox is clicked.
You can see a margin on the left side of the checkbox (I think I saw a merge request on that).
Edit: The scroll, once in the middle, goes up by itself, impossible to go down.

**Comment by droshev** [comment]
@JohnHavok is there any chance you want to upgrade to a bit newer version?

**Comment by JohnHavok** [comment]
@droshev Which version solves the problem? because I tested in 0.15.0 and 0.6.0, I still had the problem

**Comment by mikerodonnell89** [comment]
This is still a problem with current version of ngx (using the dialog)
