### ISSUE TITLE
Merge Material Select Implementation

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3014]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.

There is PR https://github.com/SAP/fundamental-ngx/pull/2619 that enhances  / replaces current select implementation. It needs to be merged to main breanch with following updates:
- Sync up with the latest master
-  Add MIT licence at the top of the select-commons.ts file 

Here is the licence:

```
/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
```

**Comment by InnaAtanasova** [comment]
It's merged.

**Comment by InnaAtanasova** [comment]
@droshev we need to discuss it

**Comment by droshev** [comment]
i think this is done already
