### ISSUE TITLE
Sync UP Select implementation with latest Styles

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3015]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
There is a new functionality in the fundamental styles for Select which adds Max Option Panel Width suport as well as optionItem Wrapping and truncation. 

<img width="610" alt="Screen Shot 2020-08-11 at 1 13 35 PM" src="https://user-images.githubusercontent.com/17149942/89891077-bd145f00-dbd4-11ea-8a87-213ec976fa1c.png">
<img width="678" alt="Screen Shot 2020-08-11 at 1 13 31 PM" src="https://user-images.githubusercontent.com/17149942/89891082-bdacf580-dbd4-11ea-9841-3a516bc0cbaf.png">

**Comment by InnaAtanasova** [comment]
Will be done after introducing the CDK.
1 day

**Comment by droshev** [comment]
I think this was done?
