### ISSUE TITLE
Message toast not available

### ISSUE THREAD

**Issue by Architgoel4** [SAP/fundamental-ngx#3020]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
UI5 message toast sample
https://sapui5.netweaver.ondemand.com/#/entity/sap.m.MessageToast/sample/sap.m.sample.MessageToast

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
 "@fundamental-ngx/core": "^0.21.0-rc.7",
  "@fundamental-ngx/platform": "^0.20.0-rc.0",

**Comment by droshev** [comment]
duplicated - follow https://github.com/SAP/fundamental-ngx/issues/3002
