### ISSUE TITLE
DateTime-Picker: Event-handler is giving wrong date in locale which is not "en-US"

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#3021]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In different locale than "en-US", the event-handler is giving the wrong date information after the calendar will be invisible. In the case of "en-GB" and "de", you the day and month will be switched.
Here is a stackblitz example with more details regarding this behavior: https://stackblitz.com/edit/fundamental-ngx-issue-3021?embed=1&file=src/app/example.component.html

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "^9.1.7",
"@fundamental-ngx/core": "^0.20.0",
> See at the stackblitz example

#### If this is a bug, please provide steps for reproducing it.
See at the stackblitz example

**Comment by zaheral** [comment]
Any news on this issue?
Tried it also with the new version 0.21.0, but the issue is the same.

CC: @droshev

**Comment by zaheral** [comment]
Any news on this issue?

CC: @droshev

**Comment by InnaAtanasova** [comment]
@zaheral we plan on working on the issues related to DateTime-Picker next sprint. We will include this one, too.

**Comment by zaheral** [comment]
Hi @InnaAtanasova 
do we have some news here?

**Comment by zaheral** [comment]
Checked this on the new Fundamental version 0.31.0 and it is solved
