### ISSUE TITLE
fix: (platform) Introduce Platform Input Group

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3023]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Introduce `input-group` component in the `platform` which allows you to add additional icons and/or buttons to an input field to provide context for the user.

![image](https://user-images.githubusercontent.com/3263744/90113485-1954bb80-dd5a-11ea-966e-bbd06aaa4ba7.png)
![image](https://user-images.githubusercontent.com/3263744/90114439-62593f80-dd5b-11ea-93a1-a2ffcd32d74f.png)

**Comment by manjunathanagaraj** [comment]
https://github.com/SAP/fundamental-ngx/pull/3165  -  PR is merged. Therefore closing it.
