### ISSUE TITLE
Checkbox field can not be clicked by webdriver 

### ISSUE THREAD

**Issue by baflQA** [SAP/fundamental-ngx#3024]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
I'm trying to automate our implementation of Fundamental NGX. I'm using Selenium with ChromeDriver to driver my tests. I want to click the checkbox field, as a user would do. 
I'm not able to click this field, because it can't even be located - the checkbox is styled as a CCS pseudo-class element. 
<img width="991" alt="Screen Shot 2020-08-13 at 12 31 24" src="https://user-images.githubusercontent.com/27357499/90124591-eb26aa00-dd60-11ea-80cf-fc244fcad4c6.png">

The only feasible workaround is to perform a JavaScript click - it's an ugly workaround which doesn't mimic a user's action so that we can not be safe that the checkbox is really clickable.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use the current version.)
0.20.0
#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/core/checkbox

**Comment by InnaAtanasova** [comment]
@baflQA could you try clicking on the checkbox label and see if it works? Let us know if the issue is still there.

**Comment by baflQA** [comment]
Hey @InnaAtanasova  - this might be another workaround, but it doesn't solve an issue. 
E.g. element located by "#background-ex4 > fd-checkbox-custom-label-example > fd-checkbox > label" contains an URL in the label. According to W3C specification, webdriver clicks in the middle of the element. In this case, it's the URL. So instead of changing the state of the checkbox, You are being redirected to the T&C page. 
I guess there might be more issues with clicking the label. And still - I don't expect that's what a user would do in most of the cases. I think that people are used to clicking checkboxes, not the labels.

**Comment by JKMarkowski** [comment]
Hi @baflQA, could you force webdriver to click only on left side of label?

**Comment by baflQA** [comment]
Hi, yes, I can calculate the size of the element's rectangle with some simple algebra and then move some number of pixels in any direction from the centre of this element. As I mentioned in the description I can use JavaScript to perform the click too. 
I don't mind if You leave it as it is, I just wanted to point out a poor "testability" of this element :)
