### ISSUE TITLE
Platform Input issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3029]
#### Is this a bug, enhancement, or feature request?
bugs

#### Briefly describe your proposal
1. go to  https://sap.github.io/fundamental-ngx/#/platform/input
2. open any stackblitz examples - none of the examples works

Another visual issue:
![Screen Shot 2020-08-14 at 6 39 24 PM](https://user-images.githubusercontent.com/4380815/90297808-c106e200-de5d-11ea-82dc-b52a4bf826f0.png)

the messages is off

expected
![Screen Shot 2020-08-14 at 6 42 29 PM](https://user-images.githubusercontent.com/4380815/90297852-f27fad80-de5d-11ea-9cd5-32397ee9a5ca.png)

**Comment by valorkin** [comment]
Could be related to https://github.com/angular/angular/issues/38453

**Comment by Lokanathan-k** [comment]
closed with PR: https://github.com/SAP/fundamental-ngx/pull/3064
