### ISSUE TITLE
remove File Input component from Ngx core, As we introduced new File Uploader component.

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#3042]
#### Is this a bug, enhancement, or feature request?
feature request
#### Briefly describe your proposal.
Remove File Input component from Ngx core, As we introduced new File Uploader component.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 10

**Comment by droshev** [comment]
done
