### ISSUE TITLE
Overview Page floor plan - define technical specs for ngx-core

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3046]

**Comment by DeepakSap14** [comment]
@manjunathanagaraj , i think this is not valid.
I will be working on Card group now, as assignment has been changed.

**Comment by manjunathanagaraj** [comment]
Yes, Deepak. I have now assigned this to Sushma.

**Comment by manjunathanagaraj** [comment]
to manage this in a separate epic meant for tech specs, a new issue is created. Therefore deleting this issue.
