### ISSUE TITLE
fix: (core) fix classes binding for input-group

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#3049]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
need to fix classes binding

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
NA
#### If this is a bug, please provide steps for reproducing it.
1. Go to the [combobox](https://sap.github.io/fundamental-ngx/#/core/combobox), [multi-input](https://sap.github.io/fundamental-ngx/#/core/multi-input) or something that use core `input-group` component
2. Click on any field to open suggestions list
3. Suggestions  list will be opened
3. Near with input located button that is active and has a blue background
4. Close suggestions list 
5. Button still active and has a blue background

#### Please provide relevant source code if applicable.
NA

**Comment by salarenko** [comment]
Fixed with #3050
