### ISSUE TITLE
Datetime-Picker Calendar causing problems when it disappears

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#3065]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The fields are triggering "ngModelChange" events, even when no changes are occurring. This happens when the calendar disappears. Additionally, the calendar is showing the current date in the calendar, in case if the current value of datetime-picker is null. There are more details of these problems in the stackblitz example: https://stackblitz.com/edit/fundamental-ngx-issue-3065?embed=1&file=src/app/example.component.ts

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
"rxjs": "^6.5.4",
"@angular/core": "^9.1.7",
"@fundamental-ngx/core": "^0.20.0",
```

#### If this is a bug, please provide steps for reproducing it.
Steps are described in the stackblitz example

**Comment by JKMarkowski** [comment]
Hello @zaheral Our DateTime picker will behave different. Check this [issue](https://github.com/SAP/fundamental-ngx/issues/2950) with prepared  [PR](https://github.com/SAP/fundamental-ngx/pull/3136)

**Comment by zaheral** [comment]
We adapted the new version with the Buttons in the Calendar, which fixed the issue.
Thanks @JKMarkowski
