### ISSUE TITLE
fd-select within fd-form-input-message-group: border / shadow missing

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#3072]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
When using `<fd-select` with  `<fd-form-input-message-group` the select-component's drop down menu doesn't have a border / shadow.

<img width="457" alt="Screenshot 2020-08-24 at 09 58 01" src="https://user-images.githubusercontent.com/1498400/91019100-c51ac880-e5f0-11ea-8b55-7fc02895d104.png">

When using `<fd-select` alone, then the following border / shadow appears:
<img width="480" alt="Screenshot 2020-08-24 at 09 59 00" src="https://user-images.githubusercontent.com/1498400/91019162-d9f75c00-e5f0-11ea-9d11-a128800eac08.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@angular/core: 10.0.5
@fundamental-ngx/core: 0.21.0

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-ovk7py

#### Please provide relevant source code if applicable.
The highlighted rule `box-shadow: none` seems to be the culprit. When this rule is disabled, then select's border is shown as expected.
<img width="790" alt="Screenshot 2020-08-24 at 09 54 41" src="https://user-images.githubusercontent.com/1498400/91019386-30fd3100-e5f1-11ea-89e8-7ac68810810d.png">

**Comment by JKMarkowski** [comment]
Hello @desaroxx Take a look at select specified messages there: [example](https://fundamental-ngx.netlify.app/#/core/select#semantic).It shouldn't be used with `fd-form-input-message-group`

**Comment by desaroxx** [comment]
We only want to show the error message within `fd-form-message`:
- error does exist
- AND user in inside 

This is what I currently have:
```html
<fd-form-input-message-group [triggers]="['mouseenter', 'mouseleave']">
  <fd-select>
    ...
  </fd-select>
  <fd-form-message *ngIf="control?.errors" [type]="control?.errors ? 'error' : null">
    <custom-error-message [errors]="control?.errors"></custom-error-message>
  </fd-form-message>
</fd-form-input-message-group>
```

With the proposal in the example you provided how can I "show message only when mouseover"?
```html
<fd-select>
  ...
</fd-select>
<fd-form-message *ngIf="control?.errors" [type]="control?.errors ? 'error' : null">
  <custom-error-message [errors]="control?.errors"></custom-error-message>
</fd-form-message>
```

**Comment by droshev** [comment]
I think the issue is more visible in this [example](https://stackblitz.com/edit/angular-ovk7py-pfyb7y?file=src%2Fapp%2Fform-message-example.component.html)
