### ISSUE TITLE
No initials are displayed in user image if a (non-working) image URL is also set

### ISSUE THREAD

**Issue by JensSteckhan** [SAP/fundamental-ngx#3074]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
I have an image service, that provides avatars only for those users who have uploaded pics of themselves.
So this image service may or may not provide an image for a user.
If there is an image, it should be displayed. 
Otherwise the initials should be displayed.

However, if I set both the image and initials for users where no image is available, nothing is displayed.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
The newest

#### If this is a bug, please provide steps for reproducing it.
Create a shellbar with user:
<fd-shellbar-actions [user]="fooUser"> (html)

Set boty the initials and an invalid url for the avatar
fooUser.initials = 'xy' (ts)
fooUser.image = '/api/userPic'

Expected behaviour: since no valide picture is given, the initials xy are displayed
Observed behaviour: only a coloured circle is displayed

#### Is there anything else we should know?
Thisi is a duplicate of #2679, but there was no feedback for more than two months. So I am opening this ticket

**Comment by salarenko** [comment]
@JensSteckhan lets get back to the conversation in #2679.
