### ISSUE TITLE
Installation Guide incorrect  information

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3078]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.
Just tried to follow installation guide for latest version and it says that I should copy some parts referering to fonts into my styles file. Those paths are wrong

```
@font-face {
 font-family: '72';
 src: url('node_modules/@sap-theming/theming-base-content/content/Base/baseLib/sap_base_fiori/fonts/72-Regular-full.woff') format('woff');
 font-weight: normal;
 font-style: normal;
}

...
```

It should use instead:

```
@font-face {
  font-family: "72";
  src: url("~@sap-theming/theming-base-content/content/Base/baseLib/sap_base_fiori/fonts/72-Regular-full.woff")
  format("woff");
  font-weight: normal;
  font-style: normal;
}
...
```

**Comment by droshev** [comment]
@fkolar thanks for the finding. I updated the wiki. Feel free in the future to update it too :)
