### ISSUE TITLE
fd-form-control does not include required styles

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3084]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

For now `fundamental-ngx/core` `form-control` does not include required input styles.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
core 0.22.0-rc.6

#### If this is a bug, please provide steps for reproducing it.
Example with `fdp-input` https://stackblitz.com/edit/angular-mc4cbf-bowtkg 
#### Please provide relevant source code if applicable.
`FormControlDirective` is implemented as directive and does not have additional styles
https://github.com/SAP/fundamental-ngx/blob/5d5da9aa3f59144f8b8510a7d692f2e67f876a62/libs/core/src/lib/form/form-control/form-control.directive.ts#L12-L17

**Comment by droshev** [comment]
We agreed to convert `form-control` to component and include the styling for the `input`
