### ISSUE TITLE
Use Angular Material Keycodes with KeyUtil

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#3105]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
`KeyUtil` has been extended with new method accepting Angular Material Keycodes. Changes were brought with this PR #3048.

`KeyUtil.isKey` logic should be replaced with `KeyUtil.isKeyCode` and all usages based on previous `KeyUtil.isKey` and new `KeyUtil.isKeyCode` should be unified.

**Comment by InnaAtanasova** [comment]
Estimation: 1 day
