### ISSUE TITLE
Dialog config properties are mandatory

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#3106]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
After https://github.com/SAP/fundamental-ngx/pull/2941, The dialog config properties are now mandatory and throwing compilation errors. We need to change it into an interface
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest
![Screen Shot 2020-08-27 at 9 48 02 AM](https://user-images.githubusercontent.com/50607147/91450535-6781b880-e84a-11ea-802f-f7762a1e1d4a.png)

**Comment by droshev** [comment]
@stefanoScalzo can you update the ticket after you discuss with the team?
