### ISSUE TITLE
Accessibility Bug: There is no keyboard support for the breadcrumbs highlighted in ‘Responsive Breadcrumbs’ section.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3114]
Fundamental Core component: "Breadcrumb"
Description: There is no keyboard support for the breadcrumbs highlighted in ‘Responsive Breadcrumbs’ section.

Expected: All the UI elements should be able to reach via keyboard.

Attached screenshot. 
![image](https://user-images.githubusercontent.com/32538291/91552617-b8c4a180-e949-11ea-81e0-bc9474524330.png)

**Comment by droshev** [comment]
@puru-hk there is no bug in this component. In the example the links are missing reference and that's why the focus is not stopping.
We can definitely enrich the example. Feel free to open a PR
