### ISSUE TITLE
Accessibility Bug: The ‘Open Dialog closable only with footer button’ is truncated when the screen is reduced to 320 CSS pixels.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3115]
Fundamental Core component: "Dailog"
Description: The ‘Open Dialog closable only with footer button’ is truncated when the screen is reduced to 320 CSS pixels.

Expected: The content be presented at a width equivalent to 320 CSS pixels without loss of information or functionality, and without requiring two-dimensional scrolling.

Attached screenshot. 
![image](https://user-images.githubusercontent.com/32538291/91553006-54561200-e94a-11ea-8b16-7d3991429a6c.png)

**Comment by droshev** [comment]
@puru-hk this is just an example how to open and close dialog programatically.
