### ISSUE TITLE
Accessibility Bug: When the application is reduced to 320 pixels, the messages trips highlighted are truncated.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3122]
Fundamental core component: "Message Strip"

Description: When the application is reduced to 320 pixels, the messages trips highlighted are truncated.

Expected: The content be presented at a width equivalent to 320 CSS pixels without loss of information or functionality, and without requiring two-dimensional scrolling.

Attached Screenshot:
![image](https://user-images.githubusercontent.com/32538291/91556473-66d34a00-e950-11ea-8500-d18e62d5075c.png)

**Comment by olshansky** [comment]
Looks like it fixed:
![image](https://user-images.githubusercontent.com/14160094/100608874-c5c0aa80-3315-11eb-897e-83f649525113.png)
