### ISSUE TITLE
Accessibility Bug: When the message strips are accessed in the virtual pc mode, the reading order is not followed the proper order in the application

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3124]
Fundamental core component: "Message Strip"

Description: When the message strips are accessed in the virtual pc mode, the reading order is not followed the proper order in the application
i.e. Dismiss button -> Message strip information

Expected: When using the keyboard, correct reading order should be preserved.

i.e. Message strip information -> Dismiss button

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91557040-5cfe1680-e951-11ea-96f6-ecd539ff4f85.png)

**Comment by droshev** [comment]
something is wrong with your test. The message strip text should not get any focus

**Comment by puru-hk** [comment]
This issue regarding the screen reader. Message strip is accessing via "Jaws" for screen reading testing. I can be focus using this software, issue is reader order is not followed.
