### ISSUE TITLE
Accessibility Bug: On accessing the message strip there is an extra tab stop with speech ‘blank’ is made after tabbing out from ‘Dismiss’ button and no where focus is visible.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3125]
Fundamental core component: "Message Strip"

Description: On accessing the message strip there is an extra tab stop with speech ‘blank’ is made after tabbing out from ‘Dismiss’ button and no where focus is visible.

Expected: An extra tab stop with speech ‘Blank’ should be removed when tabbing out from ‘Dismiss’ button.

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91557197-acdcdd80-e951-11ea-88be-30530b01110a.png)

**Comment by droshev** [comment]
i tried on IE11 and not able to reproduce it

**Comment by puru-hk** [comment]
Again this issue with the screen reader. May be if you could install Jaws in windows machine it can be reproduce.
