### ISSUE TITLE
Accessibility Bug: When the screen is reduced to 320 CSS pixels, the highlighted pop overs are truncated and overlapped with each other.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3137]
Fundamental core component: "Popover"

Description: When the screen is reduced to 320 CSS pixels, the highlighted pop overs are truncated and overlapped with each other.

Expected: The content be presented at a width equivalent to 320 CSS pixels without loss of information or functionality, and without requiring two-dimensional scrolling.

![image](https://user-images.githubusercontent.com/32538291/91651277-83829580-eaa8-11ea-87db-52b36cb4b6cb.png)

**Comment by olshansky** [comment]
Looks like it fixed:
![image](https://user-images.githubusercontent.com/14160094/100608874-c5c0aa80-3315-11eb-897e-83f649525113.png)

**Comment by puru-hk** [comment]
Tested it is working fine.
