### ISSUE TITLE
update README.md in terms of dependencies and other issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#314]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
- update README.md in terms of dependencies since we don't need ng-bootstrap anymore and fundamental-ui was renamed
- the path for importing a separate component is outdated
- once we add for example `import { AlertModule } from 'fundamental-ngx/lib/alert/alert.module';`
 we get this error:
`ERROR in : Unexpected value 'AlertModule in /Users/i820906/develop/test/p2/fd-ngx-helloworld/node_modules/fundamental-ngx/lib/alert/alert.module.d.ts' imported by the module 'AppModule in /Users/i820906/develop/test/p2/fd-ngx-helloworld/src/app/app.module.ts'. Please add a @NgModule annotation.`

**Comment by mikerodonnell89** [comment]
- The readme regarding removal of ng-bootstrap is updated in the pull request containing the cdk refactor, and it's updated on develop regarding the change to fiori fundamentals 
- I can import individual modules and use individual components - i think you may be forgetting to add the module to the "Imports" array
