### ISSUE TITLE
Accessibility Bug: There is no visible label provided for the ‘input field’ inside the Popover Example.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3142]
Fundamental core component: "Popover"

Description: There is no visible label provided for the ‘input field’ inside the Popover Example.

Expected: Input field should have placeholder text. 

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651431-2ee01a00-eaaa-11ea-8ed4-bd70bd844608.png)

**Comment by manjunathanagaraj** [comment]
Content on the pop over is upto the application developer. This is not a bug. Therefore closing it.
