### ISSUE TITLE
Accessibility Bug: There is no visible focus provided for the highlighted button in the shell bar

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3147]
Fundamental core component: "Product Switch"

Description: There is no visible focus provided for the highlighted button in the shell bar

Expected: All the UI elements should have a clear and visible focus.

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651580-25f04800-eaac-11ea-83d5-1ce1c710d2c1.png)

**Comment by droshev** [comment]
There is focus 
![Uploading Screen Shot 2020-09-28 at 8.57.43 PM.png…]()
