### ISSUE TITLE
Accessibility Bug: When the screen is reduced to 320 CSS pixels, the labels of the icons are overlapped with each other.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3152]
Fundamental core component: "Icon Tab"

Description: When the screen is reduced to 320 CSS pixels, the labels of the icons are overlapped with each other.
 
Expected:  The content be presented at a width equivalent to 320 CSS pixels without loss of information or functionality, and without requiring two-dimensional scrolling.

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651714-acf1f000-eaad-11ea-9f42-be2677e980d2.png)

**Comment by droshev** [comment]
this is a documentation issue - definitely something to improve

**Comment by puru-hk** [comment]
@Sanjay-1312 Tested this issue in this url https://deploy-preview-5462--fundamental-ngx.netlify.app/#/core/icon. It is working as expected attached the screen shot. Please verify from your side and close it. 

<img width="838" alt="Screenshot 2021-05-27 at 11 41 30" src="https://user-images.githubusercontent.com/32538291/119775111-ca3ed800-bee0-11eb-909b-8bebc9561a64.png">

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

The actual issue is fixed.
The horizontal scroll bars are available when it resized to 320 pixels.
So please fix the issue.
URL:https://deploy-preview-5462--fundamental-ngx.netlify.app/#/core/icon
JAWS 2021

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/119934264-2407d680-bfa3-11eb-939f-f52abf7fe333.png)

**Comment by manjunathanagaraj** [comment]
Labels of the icons are now not getting overlapped. Tooltip, alt text, etc as well is provided and working for each icon. So, a11y needs are met.
This page is basically icon component documentation for available set of SAP Icons. In a typical business scenario, a suitable single icon will be used by the application developer. So, this can be closed.
@Sanjay-1312 , hope this helps.

**Comment by puru-hk** [comment]
@Sanjay-1312 Also i have tested in the real device (Samsung Galaxy S5) I have not seen the horizontal scroll bar. Hence you can close this issue.

**Comment by kavya-b** [comment]
Hi @Sanjay-1312 the horizontal scroll bars appear in every other documentation page when screen is resized to smaller resolutions, and is not related to icon component
