### ISSUE TITLE
(platform) Menu component items not in the right place.

### ISSUE THREAD

**Issue by slithzerikai** [SAP/fundamental-ngx#3186]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

The menu component (https://sap.github.io/fundamental-ngx/#/platform/menu) seems to open in the wrong place.

#### If this is a bug, please provide steps for reproducing it.

https://stackblitz.com/edit/angular-feccn1-rdtezq

**Comment by KevinOkamoto** [comment]
@slithzerikai The stackblitz link resulted in a 404 not found page. Can you provide a screenshot of the defect you're seeing and also state which browser(s) you're seeing this defect?

**Comment by slithzerikai** [comment]
Darn, I had left a trailing ] after the URL, updated the description but I'll add a screenshot.

This happens at least in Chrome and Edge. I don't believe the menu is meant to show where it does.

![image](https://user-images.githubusercontent.com/10758623/92146877-456fd380-ee12-11ea-9e78-ec59d4fb4ddf.png)
![image](https://user-images.githubusercontent.com/10758623/92146885-47399700-ee12-11ea-918f-943d48db82f9.png)

**Comment by droshev** [comment]
@slithzerikai I was able to see the issue on your stackblitz but it was fine on the link https://sap.github.io/fundamental-ngx/#/platform/menu
could you check one more time?

**Comment by slithzerikai** [comment]
@droshev The issue is also visible in stackblitz directly from the link:

![image](https://user-images.githubusercontent.com/10758623/93345609-ee62f900-f82a-11ea-9f57-232412999b1c.png)

Where the drop-down shows under the 'Item Selected:' text and not under the button as it does on the documentation link:

![image](https://user-images.githubusercontent.com/10758623/93346359-cd4ed800-f82b-11ea-8b25-46b5da090534.png)

**Comment by kavya-b** [comment]
@slithzerikai could you verify if this still exists? We can't reproduce this in the recent versions.

cc: @manjunathanagaraj

**Comment by slithzerikai** [comment]
> @slithzerikai could you verify if this still exists? We can't reproduce this in the recent versions.
> 
> cc: @manjunathanagaraj

Hard to tell, stackblitz for the documentation of this isn't even working:

Error: inject() must be called from an injection context

So I cannot recreate currently.

**Comment by kavya-b** [comment]
@slithzerikai there is some issue with stackblitz in the latest version, but you can check it on this netlify's stackblitz examples: https://602a61e08b3cf200074fa0b5--fundamental-ngx.netlify.app/#/platform/menu which runs v0.27.0 
![image](https://user-images.githubusercontent.com/53509521/117429983-3a42e980-af45-11eb-9150-c8d8d9d55f2b.png)

**Comment by slithzerikai** [comment]
Thanks for that. As I can see, the issue seems to be fixed.
