### ISSUE TITLE
(platform) Button component does not respect "type" option

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3205]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Button component ignores `type="submit"` option.
#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-6mjpaa?file=src/app/platform-button-truncate-example.component.html
#### Please provide relevant source code if applicable.
@fundamental-ngx/platform0.22.0-rc.28

**Comment by manjunathanagaraj** [comment]
@dimamarksman , i think button has all the types Fiori3 recommends. Fiori3 doesnt recommend'submit' type. I think this can be closed. Please can you check once again?

**Comment by dimamarksman** [comment]
it works now, thanks
