### ISSUE TITLE
Extend coding style guide to allow public members to start from underscore

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3211]
#### Is this a bug, enhancement, or feature request?
Enhancement

- [ ] Core
- [ ] Platform

#### Briefly describe your proposal.
It is needed to update the current coding style guide regarding the private/non-private properties.
We need to allow `_xxxx` also for public members which are part of template, but belongs to private API.

**Comment by fkolar** [comment]
This is common development thing. Having private API properties as public variables creates problem. If I am accessing component and its properties and there are not marked with `_` it means its allowed, but these properties are actually private API. 

@valorkin

**Comment by droshev** [comment]
@dimamarksman I guess this is still valid. Do you think we should bring it on the table again?

**Comment by dimamarksman** [comment]
@droshev yes
I think we need to update this guide https://github.com/SAP/fundamental-ngx/wiki/Code-Contribution-Guideline
