### ISSUE TITLE
(platform) Step Input manual entry doesn't seem to work

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3225]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Step Input manual entry doesn't seem to work
![image](https://user-images.githubusercontent.com/4380815/92053467-b0120800-ed5b-11ea-90fe-c3dad4020763.gif)

Step Input validation appears on every other change
![image](https://user-images.githubusercontent.com/4380815/92054740-24e54200-ed5c-11ea-84d6-4af9e3b2ca09.gif)

**Comment by kavya-b** [comment]
first issue is fixed in #3234. As mentioned in that PR, the second issue is not related to step-input and more with the form message validation triggers.

cc: @manjunathanagaraj

**Comment by manjunathanagaraj** [comment]
@kavya-b , as discussed, close this issue and create a new one to address the validation logic in Forms.
