### ISSUE TITLE
Platform Textarea form message styles have issues

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3229]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
https://github.com/SAP/fundamental-ngx/pull/3221#pullrequestreview-484522019 
- The overlay is not properly attached to the textarea in 'without Platform Forms' example
<img width="1313" alt="Screen Shot 2020-09-08 at 5 57 32 PM" src="https://user-images.githubusercontent.com/4380815/92531697-d3760080-f1fc-11ea-9a8a-8a017dbf4b91.png">

- first click on a textarea with message shows the message shifted:
![textarea](https://user-images.githubusercontent.com/4380815/92532025-6878f980-f1fd-11ea-8ba1-d6b2bb00a342.gif)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Ang10, 
ngx v 0.22.0-rc.31

#### If this is a bug, please provide steps for reproducing it.
1. Go to Platform->Textarea
2. Enter some characters above maxlength in 'without Platform Forms' example
3. Notice the form message
4. Go to Template-driven form example and do steps 2 and 3 again. 

#### Is there anything else we should know?
Issue could be with the way form message is being used in Platform Forms. Other components might also face similar issues.

**Comment by olshansky** [comment]
Looks like it fixed and could be closed

**Comment by puru-hk** [comment]
Tested it is working fine.
