### ISSUE TITLE
Core: Switch style is not proper for toggle button in IE browser

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#3242]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.

Style is not proper for switch toggle button in IE browser
![image](https://user-images.githubusercontent.com/32538291/92234289-5f232080-eecf-11ea-926e-b93fd426af80.png)

**Comment by salarenko** [comment]
Cannot reproduce in v.0.25.0
