### ISSUE TITLE
side navigation cuts of long content

### ISSUE THREAD

**Issue by tm4g1x** [SAP/fundamental-ngx#3243]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.
If a navigation item in the side navigation has too long content the text is cut off and the user has no option to read the full content https://stackblitz.com/edit/fundamental-ngx-side-navigation-cuts-off-long-content. 

![image](https://user-images.githubusercontent.com/24810353/92728523-1fe24d00-f371-11ea-83b2-74a1bdef89c0.png)

This can easily occure, if a text-content is longer in a translated language. I'd expect that the text is being truncated, if it is too long to be displayed in the available space, but you can hover it to read the full text.

*Optional*
An optional feature could be to make the sidebare adapt automatically in width based on the content (may a max width could still be stated til that the automatic width adoption is allowed to spread).

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10.0.5 and older
Fundamental ngx 0.21.0 and older

I'd need a fix for fundamental ngx 0.18.0.

#### If this is a bug, please provide steps for reproducing it.
See stackblitz example
https://stackblitz.com/edit/fundamental-ngx-side-navigation-cuts-off-long-content

#### Please provide relevant source code if applicable.
See stackblitz example
https://stackblitz.com/edit/fundamental-ngx-side-navigation-cuts-off-long-content

**Comment by droshev** [comment]
@tm4g1x thank you for raising the issue and I understand the inconvenience when you have long item names. We can definitely try to fix this issue some time in the future, but I cannot tell you when. The general recommendation from the designers is to keep the text as short as possible.
Also we would love to get PRs

**Comment by droshev** [comment]
we migrated to vertical navigation. hopefully the problem is not there anymore
