### ISSUE TITLE
test case failures when moving from modal to Dialog Service - No provider for InjectionToken DialogRef!

### ISSUE THREAD

**Issue by rakshetha** [SAP/fundamental-ngx#3251]
#### In our project we replaced the Modal Service with the Dialog Service. The new component works fine.
But our test cases are failing because we don't use the injection token DIALOG_REF correctly.
I was hoping the team here could help us/guide us...

We are using [Component Based Dialog](https://github.wdf.sap.corp/CentralEngineering/IEInsights/tree/angualar-update/angular/src/app/shared/components/info-dialog).
We have a [test case](https://github.wdf.sap.corp/CentralEngineering/IEInsights/blob/angualar-update/angular/src/app/shared/components/info-dialog/info-dialog.component.spec.ts) for the component creation.

#### 
![image](https://user-images.githubusercontent.com/6457825/92893029-99ce1100-f419-11ea-94bd-4962e462ca32.png)

**Comment by salarenko** [comment]
Hey @rakshetha, as you probably noticed to properly create the Dialog, you need to provide `DialogRef` and `DialogConfig` dependencies. When using the dialog in your application, `DialogService` takes care of everything, but when you are testing single dialog instance, created with template/component driven approach, you need to take care of providing missing dependencies yourself.

To do this, configure your testing module with proper providers:
```
    const dialogRef = new DialogRef();
    const dialogConfig = new DialogConfig();

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [TestModule],
            providers: [
                { provide: DIALOG_REF, useValue: dialogRef },
                { provide: DIALOG_CONFIG, useValue: dialogConfig }
            ]
        });
    }));
```

**Comment by rakshetha** [comment]
@salarenko This works ! thanks a lot for the quick fix, i had spent some time trying to mock the injection dependency but was not successful. Have a great day !
