### ISSUE TITLE
Platform: Table - Phase 1

### ISSUE THREAD

**Issue by olshansky** [SAP/fundamental-ngx#3252]
#### Is this a bug, enhancement, or feature request?
feature

#### Briefly describe your proposal.
The Grid Table is a table component for displaying large data sets. 

- Basic table toolbar
- Basic column definitions
- Custom column definitions
- Single item/row selection
- Multiple item/row selection

Requirements Checklist
- [x] Should be able to display data from a data source using `basic` column definitions.
- [x] Should be able to set column alignment using `basic` column property align.
- [x] Should be able to display data from a data source with customized column headers and column cells.
- [x] Should be able to display table title in toolbar.
- [x] Should be able to display table item count in toolbar.
- [x] Should be able to display table in `single` selection mode.
- [x] Should be able to display table in `multiple` selection mode.
- [x] Should be able to get selected item from `selectionChange` event when item is selected in `single` selection mode.
- [x] Should be able to get selected items from `selectionChange` event when items are selected in `multiple` selection mode.

**Comment by manjunathanagaraj** [comment]
Phase1 table implementation is done, released in 0.23.
