### ISSUE TITLE
Core: Panel action buttons

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#3253]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Toolbar component is missing a convenient way of adding action buttons to the toolbar.
There is no proper documentation on how to create panel with actions.

Currently to create a toolbar with action buttons user needs to create a toolbar by himself:
```
<fd-panel [compact]="true" [expandAriaLabel]="'Panel Expand'">
    <h5 fd-panel-title>Header</h5>
    <div fd-panel-content>Content</div>

    <fd-toolbar fdType="transparent" [clearBorder]="true">
        <button>Action 1</button>
        <button>Action 2</button>
        <button>Action 3</button>
    </fd-toolbar>
</fd-panel>
```

We could create a simple component to make the action items creation process more clear and easy for the users:

```
<fd-panel [compact]="true" [expandAriaLabel]="'Panel Expand'">
    <h5 fd-panel-title>Header</h5>
    <div fd-panel-content>Content</div>

    <fd-panel-actions>
        <button>Action 1</button>
        <button>Action 2</button>
        <button>Action 3</button>
    </fd-panel-actions>
</fd-panel>
```

**Comment by mikerodonnell89** [comment]
We'll move forward with adding fd-toolbar in panel example to docs and possibly implement fd-panel-actions component in the future

**Comment by droshev** [comment]
we can come to this if other teams need it
