### ISSUE TITLE
Warning on Application using ngx library

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3263]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

Warning on Application using ngx library
 ![image](https://user-images.githubusercontent.com/26483208/92388627-e7940200-f117-11ea-8fe0-e2d47771a967.png)

Performance issues on calendar - follow up locally
![calendarperformance](https://user-images.githubusercontent.com/26483208/92362670-9d4b5a80-f0f0-11ea-9e44-35fdeafb6618.gif)

1day

**Comment by mikerodonnell89** [comment]
Can no longer recreate either issue here on Mac, tested chrome, safari and firefox
