### ISSUE TITLE
console error while using fix for shadow dom popover bug

### ISSUE THREAD

**Issue by Architgoel4** [SAP/fundamental-ngx#3272]
#### Is this a bug, enhancement, or feature request?
bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "^0.22.0-rc.62",
    "@fundamental-ngx/platform": "^0.21.2",
console-> 
ERROR TypeError: (intermediate value).withWrap(...).withHomeAndEnd is not a function
    at KeyboardSupportService.setKeyboardService (fundamental-ngx-core.js:4729)
    at ListComponent.ngAfterContentInit (fundamental-ngx-core.js:10906)
    at callHook (core.js:4770)
    at callHooks (core.js:4734)
    at executeInitAndCheckHooks (core.js:4674)
    at refreshView (core.js:12026)
    at refreshDynamicEmbeddedViews (core.js:13372)
    at refreshView (core.js:12007)
    at refreshDynamicEmbeddedViews (core.js:13372)
    at refreshView (core.js:12007)

Also, "@fundamental-ngx/platform": "^0.22.0-rc.62", doesn't get built only it throws the below error in our application: 

Compiling @fundamental-ngx/platform : es2015 as esm2015
ERROR: Failed to find exported name of node (class HighlightPipe {
    constructor(comboboxConfig) {
        this.comboboxConfig = comboboxConfig;
    }
    transform(value, searchText, matchingStrategy = this.comboboxConfig.matchingStrategy) {
        if (!(value && searchText)) {
            return value;
        }
        if (matchingStrategy === MatchingStrategy.STARTS_WITH) {
            return this._searchByStrategyStartsWith(value, searchText);
        }
        if (matchingStrategy === MatchingStrategy.CONTAINS) {
            return this._searchByStrategyContains(value, searchText);
        }
        return value;
    }
    _searchByStrategyStartsWith(value, searchText) {
        const valueLowerCase = value.toLowerCase();
        const searchTextLowerCase = searchText.toLowerCase();
        if (!valueLowerCase.startsWith(searchTextLowerCase)) {
            return value;
        }
        const startIndex = valueLowerCase.indexOf(searchTextLowerCase);
        if (startIndex !== -1) {
            const matchingString = value.substr(startIndex, searchText.length);
            return value.replace(matchingString, '<strong>' + matchingString + '</strong>');
        }
    }
    _searchByStrategyContains(value, searchText) {
        return value.replace(new RegExp(`(${searchText})`, 'gi'), '<strong>$1</strong>');
    }
}) in '/Users/i311672/Documents/dwc/central-connection-ui/node_modules/@fundamental-ngx/platform/fesm2015/fundamental-ngx-platform.js'.
An unhandled exception occurred: Failed to find exported name of node (class HighlightPipe {
    constructor(comboboxConfig) {
        this.comboboxConfig = comboboxConfig;
    }
    transform(value, searchText, matchingStrategy = this.comboboxConfig.matchingStrategy) {
        if (!(value && searchText)) {
            return value;
        }
        if (matchingStrategy === MatchingStrategy.STARTS_WITH) {
            return this._searchByStrategyStartsWith(value, searchText);
        }
        if (matchingStrategy === MatchingStrategy.CONTAINS) {
            return this._searchByStrategyContains(value, searchText);
        }
        return value;
    }
    _searchByStrategyStartsWith(value, searchText) {
        const valueLowerCase = value.toLowerCase();
        const searchTextLowerCase = searchText.toLowerCase();
        if (!valueLowerCase.startsWith(searchTextLowerCase)) {
            return value;
        }
        const startIndex = valueLowerCase.indexOf(searchTextLowerCase);
        if (startIndex !== -1) {
            const matchingString = value.substr(startIndex, searchText.length);
            return value.replace(matchingString, '<strong>' + matchingString + '</strong>');
        }
    }
    _searchByStrategyContains(value, searchText) {
        return value.replace(new RegExp(`(${searchText})`, 'gi'), '<strong>$1</strong>');
    }
}) in '/Users/i311672/Documents/dwc/central-connection-ui/node_modules/@fundamental-ngx/platform/fesm2015/fundamental-ngx-platform.js'.
See "/private/var/folders/0y/zc7t44tx54z6l3v30sjl61g00000gn/T/ng-dBVbNh/angular-errors.log" for further details.

#### Is there anything else we should know?
links to https://github.com/SAP/fundamental-ngx/pull/3196

**Comment by salarenko** [comment]
Hey @Architgoel4, I see you are using release-candidate versions of both `core` and `platform` libraries, which are not official builds. Thanks for reporting the errors, but we do not recommend using `rc` versions in your application.
There might occur some incompatibility errors and other unexpected behaviors.

**Comment by Architgoel4** [comment]
@salarenko sure we'll change that. But, we needed the shadow dom fix and I couldn't find a patch for that fix. Is any release planned with that fix?

**Comment by reinholdk** [comment]
@salarenko `FocusKeyManager.withHomeAndEnd` does not exist in Angula 9 (@angular/cdk@9.2.4) are you planning to drop Angular 9 support with fundamental-ngx 0.22.0?
