### ISSUE TITLE
Bug: Combobox In RTL mode list is not aligned properly 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3275]
Description: Combobox In the RTL mode combobox list is not aligned properly. 

Expected: RTL mode list should be aligned. 

Attached the screenshot
![image](https://user-images.githubusercontent.com/32538291/93053577-a35bb100-f685-11ea-9add-ba934adfc031.png)

**Comment by maxym-valor** [comment]
Fixed!
