### ISSUE TITLE
Bug: Combobox Style issue 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3276]
Description: On selecting the option from the combobox list style is not as per the fiori3. 

Expected: Style should be as per the Fiori3 

Attached screenshot 

Issue: 
![image](https://user-images.githubusercontent.com/32538291/93054187-9db29b00-f686-11ea-9ea3-cf6567a7b245.png)

Fiori3 screenshot:

![image](https://user-images.githubusercontent.com/32538291/93054231-a73c0300-f686-11ea-8ce2-9fa4db33ba44.png)

**Comment by Seamoo13** [comment]
not reproduced
