### ISSUE TITLE
Bug: Combobox - Entered the invalid letter in the input field. There is no error message

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3277]
Description: Combobox - Entered the invalid letter in the input field. There is no error message

Expected: Error message should display if user entered the invalid.

Attached screenshot. 

![image](https://user-images.githubusercontent.com/32538291/93054616-3b0dcf00-f687-11ea-9166-e7de0b202f9f.png)

As per the Fiori3 if user entered the invalid below screenshot should display. 

![image](https://user-images.githubusercontent.com/32538291/93054745-73ada880-f687-11ea-85cc-da1d1c815f7e.png)

**Comment by olshansky** [comment]
Assigned to Oleksiy Drozdov
