### ISSUE TITLE
Carousel component implementation in ngx-core

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3279]

**Comment by manjunathanagaraj** [comment]
Awaiting tech spec presentation from fundamental team.

**Comment by manjunathanagaraj** [comment]
Tech spec presented, approval pending. Work in progress. Moving to sprint 47.

**Comment by DeepakSap14** [comment]
PR #3551 is merged. This can be closed.

**Comment by manjunathanagaraj** [comment]
PR 3551 review in progress. Will be moved to sprint 48 to take it to closure.
