### ISSUE TITLE
Bug: Combobox- Clearing the letter from the input field is not working properly in firefox browser. 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3281]
Description: Clearing the letter from the input field is not working properly in firefox browser. 
Steps to reproduce:
- In Mac machine 
- Open the firefox browser 
- Enter the URL (https://fundamental-ngx.netlify.app/#/platform/combobox)
- In any combobox input field 
- Entered some letters
- Try the delete from the keyboard it is not working properly. 

Firefox version - 80.0.1 (64-bit)

Expected: Enter the delete key from the keyboard it should clear the letter in input field.

[Screen Recording 2020-09-14 at 2.06.32 PM.zip](https://github.com/SAP/fundamental-ngx/files/5217372/Screen.Recording.2020-09-14.at.2.06.32.PM.zip)

**Comment by puru-hk** [comment]
Current fundamental ngx version it is working fine. Hence closing this defect.

**Comment by manu-kr** [comment]
@puru-hk Not able to reproduce this with new version.
