### ISSUE TITLE
Bug: Combobox- RTL mode list option is not showing proper in firefox browser. 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3282]
Description: RTL mode list option is showing wrong side in firefox browser.  
Expected: List option should display as per the RTL 

Firefox version - 80.0.1 (64-bit)

Attached the video. 
[Screen Recording 2020-09-14 at 2.46.59 PM.zip](https://github.com/SAP/fundamental-ngx/files/5217425/Screen.Recording.2020-09-14.at.2.46.59.PM.zip)

**Comment by Betrozov** [comment]
can not reproducible

**Comment by nikvalor** [comment]
Fixed
