### ISSUE TITLE
Bug: Combobox- Focus is highlighting in green in firefox browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3283]
Description: Focus is highlighting in green in firefox browser.

Expected: It should be as per the fiori 3. 

Attached the screenshot. 

![image](https://user-images.githubusercontent.com/32538291/93069228-0f94df80-f69b-11ea-929b-ab1393565836.png)

As per the Fiori3 
![image](https://user-images.githubusercontent.com/32538291/93069379-36531600-f69b-11ea-9c44-c58e2b2c185f.png)

**Comment by kavya-b** [comment]
@puru-hk @Seamoo13 doesn't seem to be reproducible with latest major version and netlify urls either. Please check.

**Comment by Seamoo13** [comment]
verified, not reproduced.
