### ISSUE TITLE
QA - Pre-release testing of the components in netlify landscape

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3294]
1. Styles: Rating Indicator, Dynamic page layout,object list item.
2. Core: Card,Formatted rext, Object Number,Object Marker,Carousel
3. Platform: Input group, Combo box, Fixed card layout,Table-phase1,Thumbnail image, Object Marker, Multi Input.

While updating, please indicate the test landscape, number of defects/issues raised and the issue numbers.

**Comment by puru-hk** [comment]
Combobox Testing is done raised these issues in github: #3275, #3276, #3277, #3280, #3281, #3282, #3283, #3298, #3300, #3301
Input group Testing in done raised these issues in github: #3315, #3316, #3317, #3318, #3319, #3320, #3321, #3322, #3323, #3324, #3345. 
Rating indicator testing is done raised issue in github: #3335
Object Marker: Testing is done raised issue in github: https://github.com/SAP/fundamental-styles/issues/1692
Fixed card layout : raised issues in PR3341
