### ISSUE TITLE
QA- Accessibility testing

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3295]
Co-ordinate with a11y team, share the component details to be tested.
Analyse the a11y test report, raise the defects.

**Comment by puru-hk** [comment]
Below components are sent to the accessibility team for testing. 

Textarea
Panel
Switch
File uploader
Object Status
Step Input
Combobox
Input group
List
Standard List Item

**Comment by manjunathanagaraj** [comment]
Done. Raised issues. Issues to be analysed in coming sprints.
