### ISSUE TITLE
Core carousel directive creates Hammer instance using invalid options

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3296]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
It was noticed that carousel directive creates Hammer instance using invalid second parameter `options`.
https://github.com/SAP/fundamental-ngx/blob/2c8312ba35c4c1a89064ac5ee297bd6e86618dcb/libs/core/src/lib/utils/directives/carousel/carousel.directive.ts#L224
[`HammerConfig`](https://github.com/SAP/fundamental-ngx/blob/master/libs/core/src/lib/utils/directives/carousel/hammer.config.ts) does not create Hammer options instance, it's angular config that is used in `HammerGesturesPlugin`.
By the way to enable Hammer events in angular scope we must import [`HammerModule`](https://angular.io/api/platform-browser/HammerModule) as well.

In the current implementation I don't see the need to have [`HammerConfig`](https://github.com/SAP/fundamental-ngx/blob/master/libs/core/src/lib/utils/directives/carousel/hammer.config.ts) cause we don't use `HammerModule`.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
10

**Comment by JKMarkowski** [comment]
@dimamarksman That's true, this file and its usages can be removed without any impact
