### ISSUE TITLE
Accessibility Issue: Combobox- Tab order is not working in IE browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3299]
Description: when user enter the tab key from the keyboard "Tab order" is not working in IE browser

Expected: Tab order should work

**Comment by olshansky** [comment]
Right now all work in the same way in Chrome and IE (v 0.25.0-rc.13).

@puru-hk could you re-test it? And if your issue still reproducible, could you provide more details and maybe a video?

**Comment by Seamoo13** [comment]
checked tab for combobox inputs and dropdown items, works.
