### ISSUE TITLE
Bug: Input Group: Style issue 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3315]
Description: Submit button border is not as per the fiori3 

Expected: Submit button should be as per the fiori3

attached the screenshot

![image](https://user-images.githubusercontent.com/32538291/93423848-810ba280-f8d4-11ea-8994-5ca70200c074.png)

**Comment by puru-hk** [comment]
There is no example how expected should be.

**Comment by dimamarksman** [comment]
Fixed in scope of https://github.com/SAP/fundamental-ngx/pull/3328
Please check it one more time

**Comment by puru-hk** [comment]
Tested this issue it is working as expected. 

![Uploading image.png…]()
