### ISSUE TITLE
Bug: Input Group: On click on the submit button nothing is happen 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3317]
Description: On click on the submit button nothing is happen 

What is purpose of submit button?

Expected: Some action should be triggered.

**Comment by dimamarksman** [comment]
Handling button's click is not part of input-group functionality.
App developer is responsible to add any handler to a button.

**Comment by puru-hk** [comment]
As per the above comments submit button is not part of input group functionality and App developer is responsible to add any handler to a button.Hence I'm closing this bug
