### ISSUE TITLE
Bug : Input group: No validation for email field.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3318]
Description: No validation for email field.

Expected: Validation should be in place for email field. 

Attached screenshot.

![image](https://user-images.githubusercontent.com/32538291/93424685-22dfbf00-f8d6-11ea-9279-39e0780fb7aa.png)

**Comment by dimamarksman** [comment]
@puru-hk Why are you expecting validation in this example?

This examples just shows that we can use `icon` as an addon and `type` option for the input, app devloper has to be responsible for adding input validation in case if t's required.

**Comment by dimamarksman** [comment]
The last example shows usage with form validation

**Comment by puru-hk** [comment]
This is app developer responsibility for adding the input validation. This is not an issue.
