### ISSUE TITLE
Bug: Input group: In Edge browser input group field displaying small.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3320]
Description: In Edge browser input group field displaying small.
Mac machine edge browser
Version 86.0.608.0
Expected: It should displayed as other browser. 

Attached the screenshot: 
Issue: 

![image](https://user-images.githubusercontent.com/32538291/93426692-29703580-f8da-11ea-9905-5fb6fc6afde5.png)

Other browser in chrome: 

![image](https://user-images.githubusercontent.com/32538291/93426765-40168c80-f8da-11ea-949a-60b92aef037a.png)

**Comment by skocharian** [comment]
@puru-hk The latest official Edge for MacOS is Version 85.0.564.60, please see how input group renders there:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/10288615/93749182-28087b00-fc02-11ea-95a2-34d6e215b044.png">
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/10288615/93749331-6b62e980-fc02-11ea-85d3-239fc5c1da8e.png">

**Comment by puru-hk** [comment]
Tested in Edge Version 87.0.644. it is working fine. 

![image](https://user-images.githubusercontent.com/32538291/93751979-9ad22000-fc1b-11ea-88ae-7b5dd32bef42.png)
