### ISSUE TITLE
Bug: Input Group: Able to enter the value in Input group disable field.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3324]
Description: Able to enter the value in Input group disable 

Expected: In Disabled field user should not allowed to enter the values

Attached video:

[Able to enter the values in disabled field.zip](https://github.com/SAP/fundamental-ngx/files/5236967/Able.to.enter.the.values.in.disabled.field.zip)

**Comment by dimamarksman** [comment]
Fixed on scope of https://github.com/SAP/fundamental-ngx/pull/3333

**Comment by puru-hk** [comment]
Tested it is working as expected. Hence it is closed.
