### ISSUE TITLE
platform input with ngModel and disabled state

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3334]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Using `base.input` based component (e.g. fdp-input) with `ngModel` and disabled state does not go to enabled state back.

Playground 
https://stackblitz.com/edit/angular-njvtab?file=src%2Fapp%2Fplatform-input-example.component.html

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
10.05
#### If this is a bug, please provide steps for reproducing it.
Open https://stackblitz.com/edit/angular-njvtab?file=src%2Fapp%2Fplatform-input-example.component.html
click button to disable fdp-input
click button to enable it
See result, `fdp-input` remains disabled

**Comment by OleksiyDrozdov** [comment]
Defect is not reproducible. Please see link below https://stackblitz.com/edit/angular-xxaend?file=src%2Fmain.ts
Also, I was trying to reproduce in fund-ngx and it is not possible to reproduce as well, please see screenshot below
![image.png](https://images.zenhubusercontent.com/60492e1f104385ee3fc0608a/c22e983f-49f4-406e-aa6f-a110960f1d67)
![image.png](https://images.zenhubusercontent.com/60492e1f104385ee3fc0608a/b9072691-11e3-44b3-b5db-37532777a85d)

**Comment by maxym-valor** [comment]
not reproducible
