### ISSUE TITLE
Bug: Rating Indicator: In safari browser customs icon section when mouse hover it behaving differently

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3335]
Description: In safari browser customs icon section when mouse hover it behaving differently

Expected: It should behave differently

Attached video. 

[Screen Recording 2020-09-18 at 1.53.44 PM.zip](https://github.com/SAP/fundamental-ngx/files/5251014/Screen.Recording.2020-09-18.at.1.53.44.PM.zip)

**Comment by kavya-b** [comment]
The video attached is of Fundamental Styles, not ngx. The issue is not reproducible in either Styles or Ngx anymore. Please verify @puru-hk @Seamoo13

**Comment by maxym-valor** [comment]
Still reproducible!
[Запись экрана 2021-06-02 в 10.45.26.zip](https://github.com/SAP/fundamental-ngx/files/6582919/2021-06-02.10.45.26.zip)

**Comment by puru-hk** [comment]
@maxym-valor I have tried in safari Version 14.1.1 (16611.2.7.1.4). Not able to reproduce it is working fine. Please update your safari browser and verify once.

**Comment by kavya-b** [comment]
@maxym-valor wow this is strange, could you specify your safari version? 
this is what I see: 
![2021-06-02_13-35-45 (1)](https://user-images.githubusercontent.com/53509521/120447095-db3b8d80-c3a7-11eb-9044-70d0b46f74c1.gif)

**Comment by maxym-valor** [comment]
@kavya-b yeah, I safari version is 13.1.3 (15609.4.1)

**Comment by puru-hk** [comment]
It's not bug. Hence closing this issue.
