### ISSUE TITLE
sprint 47-goals

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3342]
Sprint47(available 93+10pds, allocated 95pds)-ends on Oct9 - 
Valor(29):
Artur - Platform Table Implementation – Table Phase2: 10pds [#3258](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3258) 
Dmitriy Tkachenko - Styles Implementation for Dynamic Side Content - 5dps - [#1503](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-styles/1503)
Dmitriy Tkachenko - Platform implementation for Dynamic Side Content - 5pds - [#3393](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3393)
Yury - Platform Upload Collection – tech spec and implementation – 10pds  - [#3171](https://github.com/SAP/fundamental-ngx/issues/3171)
Evgeny Beregovoy - Feed List Item styles implementation – 5pd - [#857](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-styles/857)
Evgeny Beregovoy – Feed input core implementation – [5pd-#3394](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3394)
Oleksii Aleksandrov  - Styles Implementation for Icon – 5pd - [#1710](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-styles/1710)
Oleksii Aleksandrov - Platform implementation for Approval Flow-Phase1 – 10pd (1st sprint) - [#3403](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3403)
Nikolay Vorobyev - Formatted text - core tech spec and implementation 
 Core implementation for Rating Indicator – 5pd - [#3037](https://app.zenhub.com/workspace/o/sap/fundamental-ngx/issues/3037)
Nikolay Vorobyev - Feed list item core tech spec - 2pd - [#3288](https://app.zenhub.com/workspace/o/sap/fundamental-ngx/issues/3037)

Ilya Surmay - Styles implementation Slider – [5pds-#1709](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-styles/1709)
Ilya Surmay - Object Number 

Ariba(45+10):
31 pds capacity to be planned

//Manu - Feed list item platform tech spec - 2pd - assigned to Nikolay
//Manu - Platform Implementation of File Uploader: 5pds - plan this in later sprint
//Manu – Styles tech spec for Label – 1pd - not needed
//Manu -  Core tech spec for Label – 1pd - plan this in later sprint

//Lok – Object Identifier core implementation – 5pds
Lok - Implementation of Platform Multi input - 5pds [#3274](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3274)
Lok - Styles implementation for multi combobox - 5pds - [#1469](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-styles/1469)
//Lok – Core tech spec and implementation for icon – 5pds

Sushma:
Sushma - object attribute is dependent component, will be developed in platform - 5pds
Sushma - Implementation - platform - Object List Item – 10pds [#3290](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3290). Potentially it could spill over to sprint 48 by 5 pds.

//Deepak - Feed list item core implementation - 5pd 
Deepak - Carousel core implementation - 5pds(continuation from sprint 46) [#3279](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3279)
Deepak - Platform - Input List Item – tech spec – 3pds

Kavya:
Core tech spec for range slider – 1pd
Datetime picker platform tech spec and implementation – 5+1 pds - [#3398](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/3398)

Kevin:
Approval Flow - platform tech spec - phase1 
Table phase 3 - tech spec –5pds
Thumbnail platform implementation - 3pds(takeover from Manu) - [#1487](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-styles/1487)
Platform tech spec for slider – 1pd
Tree List – tech spec for styles – 3pds - no need
Tree List – Tech spec for core – 2pds - to be planned in the sprint where tree list styles implementation is scheduled.

QA Activities:
Puru - Co-ordinating with SAP Accessibility team for accessibility testing and analysing report, raising bugs 
Puru - To give heads up on next set of components(sprint 47 components) to SAP Accessibility team
Puru - Help Valor QA folks in ramp up 
Puru - Track on saucelab integration with CI/CD
Puru - Prepare automation plan (unit testing, browser testing - functional testing, accessibility, i18n, RTL)
Puru - Pre-release testing / accessibility testing for sprint 47 components.
Puru - Test cases for sprint 47 components

**Comment by manjunathanagaraj** [comment]
As per our revised approach, Tree List tech spec for core to be planned after a PR for its Styles is raised.

**Comment by manjunathanagaraj** [comment]
### Spillovers from 46:

1.  **Tech Spec:** Feed List item - core and platform
2. **Implementation:** a) Dynamic Page Layout platform  - 3pds b) Carousel - core


**Continuation:**
Saucelab integration with CI/CD - presentation on automation plan by Oct 7th.
Upload Collection  - Platform

**Moved from 46:**
Dynamic Side Content - styles implementation - 5dps




Formatted text - core implementation
Object Number - core impelementation - PR closure

**Comment by manjunathanagaraj** [comment]
have feed list item core tech spec instead of platform tech spec

**Comment by puru-hk** [comment]
Testing task for Valor and Puru

![image.png](https://images.zenhubusercontent.com/5f4c9866d9d21de4c96444ff/6ffea759-f825-4be9-b689-e7133d227369)

**Comment by manjunathanagaraj** [comment]
Completion of sprint 46 backlogs:
Dmitriy Tkachenko - Card 
Nikolay - formatted text
Ilya - Core Implementation of Object Number
Evgeny - Platform tech specs - Feed input
Kavya - Platform implementation for Dynamic Page layout
Kavya - Styles-Dynamic Page Layout 
Deepak - Completion of Fixed Card Layout
Sushma - Implementation of Tech spec for styles for object list item
Loki - Implementation. - core - Object Marker
Loki - Implementation - platform - multi input
Kevin - Thumbnail completion (styles+platform)
Kevin - Tech spec for approval flow phase1

**Comment by manjunathanagaraj** [comment]
Sprint 47 has 9 working days.

**Comment by manjunathanagaraj** [comment]
Sushma - object attribute is dependent component, will be developed in platform  - on track
Deepak - Carousel core implementation - 5pds(continuation from sprint 46)  - PR to be raised - on track

**Comment by manavs** [comment]
OPS Review Meeting Notes:- Oct 7th 2020

Artur - Phase 1 to finished this sprint.
Dmitriy - Styles raised (https://github.com/SAP/fundamental-styles/pull/1749)and Platform PR will be raised. 
Yury - Platform Upload Collection - PR done by Sprint 48 - week 1
Evgeny - PR raised for styles ,  Feed Input Core - PR will be raised
Oleksii - PR will raised for ICON , 
Nikolay - Formatted Text (https://github.com/SAP/fundamental-ngx/pull/3568)PR raised , Working on Feed List Item - tech spec for ngx-core
Ilya Surmay - Object number — https://github.com/SAP/fundamental-ngx/pull/3567. Working on Slider styles - PR will be raised and merged. 
------
App Shell 
Dima Sheksohvtsov — Working on MF, planned Sprint 2, working on architecture with Frank, Bundling and Plugin configuration
Danil Zhmyrov — MF, working on iFrame support

------ 

Sushma - Object Attribute PR raised (https://github.com/SAP/fundamental-ngx/pull/3531) - Object List Item - PR will raised by mid next week Sprint 48 

Deepak - PR raised (https://github.com/SAP/fundamental-ngx/pull/3551) - will be addressed Sprint 47. Input List Item - Monday Oct 12th

Kavya - Dynamic Page Layout Styles (https://github.com/SAP/fundamental-styles/pull/3598) - pending approval from Dino
           - Dynamic Page Layout platform (https://github.com/SAP/fundamental-ngx/pull/3515) - internal review in progress. 
           - Core - range slider is dependent core slider(yury is doing core slider and range slider), dependent on styles for slider.
           - Datetime picker platform tech spec - To be presented Oct 8th 

Kevin - Approval Flow - Design still pending

**Comment by manjunathanagaraj** [comment]
Sushma - Object Attribute PRs raised (https://github.com/SAP/fundamental-styles/pull/1765 and https://github.com/SAP/fundamental-ngx/pull/3531) 
Sushma - Object List Item - PR will raised by mid next week Sprint 48.

Deepak - PR raised (https://github.com/SAP/fundamental-ngx/pull/3551). 
Input List Item -to be presented on Monday Oct 12th

**Comment by manjunathanagaraj** [comment]
Formatted Text - https://github.com/SAP/fundamental-ngx/pull/3574  - PR merged on Friday.
