### ISSUE TITLE
Enhancement for Dialog Title to support icon and also styling for header

### ISSUE THREAD

**Issue by Architgoel4** [SAP/fundamental-ngx#3343]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
We would like to have the option to have a icon besides the title for a Dialog. For example: <warning-icon> Warning in the title along with border-bottom as fiori-warning. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "@fundamental-ngx/core": "^0.22.0-rc.66",

**Comment by salarenko** [comment]
Hey @Architgoel4,
currently you can build your dialog header in any way you want to. For more information visit [Dialog documentation](https://sap.github.io/fundamental-ngx/#/core/dialog#complexDialog).
However there is a component we are going to introduce soon, which will out of the box provide the functionality you are looking for. This component is [Message Box](https://experience.sap.com/fiori-design-web/message-box/). You can follow the progress with [this ticket](https://github.com/SAP/fundamental-ngx/issues/2430).
