### ISSUE TITLE
Bug: Input Group: In IE browser submit button is not highlighted when the tab order from the keyboard.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3345]
Description:  In IE browser submit button is not highlighted when the tab order from the keyboard.
IE browser version 11.1016
Window machine 

Expected: It should focus on submit when the tab order 

Attached the video. 
[IE browser submit button is not highlighted.zip](https://github.com/SAP/fundamental-ngx/files/5254643/IE.browser.submit.button.is.not.highlighted.zip)

**Comment by dimamarksman** [comment]
I suppose this issue comes from fundamental styles, if so we need to address this issue to fundamental-styles repo.

**Comment by dimamarksman** [comment]
@puru-hk could you please check it in the [fundamental-styles](https://fundamental-styles.netlify.app/iframe.html?id=components-forms-input-group--input-with-actions&viewMode=story) to see if the previous statement is valid.

**Comment by droshev** [comment]
Angular 12 had deprecated IE11 and in Angular 13 will drop the support so we will close the issue
https://github.com/SAP/fundamental-ngx/wiki/Browser-Support
