### ISSUE TITLE
I can't create libraries with Fundamentals Ngx Core

### ISSUE THREAD

**Issue by camilo2312** [SAP/fundamental-ngx#3351]
Hello everyone 
Create a project type library in angular. In my module enter the ButtonModule

![image](https://user-images.githubusercontent.com/42982644/93812157-d61e2000-fc16-11ea-87cc-dc33ef1ffce0.png)

![image](https://user-images.githubusercontent.com/42982644/93812205-e59d6900-fc16-11ea-8393-b81c03ed91e6.png)

And when trying to execute "ng build" I get the following error

![image](https://user-images.githubusercontent.com/42982644/93812292-fe0d8380-fc16-11ea-9c4f-8fb6748a83cc.png)

Somebody could help me

Thank you very much to all

**Comment by droshev** [comment]
it's been a while since the issue has been open. Can you reopen it if the issue persists
