### ISSUE TITLE
platform combobox issues

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3358]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
filtering issue

1. go to https://fundamental-ngx.netlify.app/#/platform/combobox
2. click on the first combobox field and type `a`
![platform-combo-issue](https://user-images.githubusercontent.com/4380815/93828057-9700c680-fc38-11ea-8342-e49246382e57.gif)
it only keeps `Apple`, but instead it should keep all items that contain `a`
![core-combo](https://user-images.githubusercontent.com/4380815/93828111-af70e100-fc38-11ea-817f-8d1bef0e65ef.gif)

![Screen Shot 2020-09-21 at 6 29 36 PM](https://user-images.githubusercontent.com/4380815/93828120-b4ce2b80-fc38-11ea-908b-c85b960631f1.png)

Can you add examples which take 100% of the width, as the current examples seems to have hardcoded width?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by skocharian** [comment]
@droshev In regards to filtering issue — Platform combobox spec mentions that startsWith should be used by default — described here https://app.gitbook.com/@fundamental-ngx/s/docs/wip-combobox#configurable-properties
