### ISSUE TITLE
Bug: SplitMenubutton: Split menu button, the menu aligns with the left line of the icon area

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3367]
Description: Split menu button, the menu aligns with the left line of the icon area, Currently it is right aligned. 

Expected: The menu should be left aligned 

Attached the screenshot:

![image](https://user-images.githubusercontent.com/32538291/93997232-cb978e00-fdb0-11ea-80bb-0bd5d3b070b1.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/93997255-d2260580-fdb0-11ea-9a4e-b4121a629c0c.png)

**Comment by DeepakSap14** [comment]
This has been fixed in latest master release.

**Comment by DeepakSap14** [comment]
<img width="566" alt="Screenshot 2020-10-21 at 12 04 37 PM" src="https://user-images.githubusercontent.com/57661487/96681922-a4bf7e00-1395-11eb-8d0e-360512ed1317.png">

This has been fixed in latest master release. so closing this issue.
