### ISSUE TITLE
Bug: Menu: Example is missing for Icon+Label+Icon (arrow), Combination

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3368]
Description: Need to add these combination for examples  in ariba these combination is required Icon+Label+Icon (arrow), 
Currently Label only is there in menu
Expected:  in ariba these combination is required Icon+Label+Icon (arrow)

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/93998109-bff89700-fdb1-11ea-865d-9d72b6c32f48.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/93998196-d9014800-fdb1-11ea-87cc-00a7716eb314.png)

**Comment by DeepakSap14** [comment]
core menu example is created but platform menu has bug, because of which example is not getting created correctly. have to correct platform menu implementation.

**Comment by puru-hk** [comment]
Examples is added for the above. Hence this issue is closed.
