### ISSUE TITLE
View shrinks after opening a modal.

### ISSUE THREAD

**Issue by christinaLinderer** [SAP/fundamental-ngx#340]
Is this a bug, enhancement, or feature request?
bug

Briefly describe your proposal.
View shrinks after opening a modal.

If this is a bug, please provide steps for reproducing it.
1. Go to https://sap.github.io/fundamental-ngx/docs/modal
2. Click on "Launch Demo" button
3. Page in the background shrinks + the scrollbar

**Comment by mikerodonnell89** [comment]
Hi Christina, would you mind taking some screenshots?  What browser are you using?  I'm unable to recreate this bug in chrome, firefox or safari, even after changing the window size.

**Comment by christinaLinderer** [comment]
Sure, here you go
![screen shot 2018-11-30 at 08 51 49](https://user-images.githubusercontent.com/8125207/49275955-40336700-f47d-11e8-86b0-e11e2e21b1f1.png)
