### ISSUE TITLE
Approval Flow (Process Flow) - phase2 - Platform Implementation

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3404]
Develop Approval Flow for edit mode scenarios.
Tech spec to be presented and approval to be recieved before starting the development

**Comment by manjunathanagaraj** [comment]
To be assigned to Oleksii Aleksandrov

**Comment by manjunathanagaraj** [comment]
PR merge target - sprint55

**Comment by IlyaSurmay** [comment]
**status update:**

the main part of phase 2 functionality is implemented (edit watchers, add/edit/remove approvers, drag&drop support)

**what's left:**
- RTL /  i18n support for new parts
- handle edge cases with parallel approvers and drag&drop
- fix minor UI issues and UX glitches

Expect to raise a PR by the end of next week (5th Feb)
