### ISSUE TITLE
Bug: Platform Combobox - Button icons styles are broken

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3412]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Button icons are breaking in combobox. Related to Button component. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/platform/combobox
2. Observe the buttons
![image](https://user-images.githubusercontent.com/53509521/94397388-57c6fe00-0181-11eb-9f18-eb1846ad71eb.png)

**Comment by manjunathanagaraj** [comment]
Could be due to breaking changes from Button component.

**Comment by EvilAlexei** [comment]
@manjunathanagaraj This issue is not actual, I checked icons on [platform](https://fundamental-ngx.netlify.app/#/platform/combobox) and [core](https://fundamental-ngx.netlify.app/#/core/combobox), icons are ok.

https://prnt.sc/uqhkly
