### ISSUE TITLE
Bug: Platform Combobox - RTL for custom template not handled

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3413]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
RTL for custom template looks off with the icon sticking to the text.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/platform/combobox#templates
2. Focus on the first combobox.
3. Select a value.
4. RTL the example.
5. Observe

![image](https://user-images.githubusercontent.com/53509521/94401429-39183580-0188-11eb-9b34-8339a0eaad9e.png)

**Comment by manjunathanagaraj** [comment]
Could be due to breaking changes on buttons component. Need to be analysed and fixed.
