### ISSUE TITLE
Bug: Platform Object Status - focus and tabbing issue for clickable object status

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3414]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
For linked object status, focus should happen after clicking. Also, clickable objects should be tabbable. Fundamental Styles supports tabbing https://fundamental-styles.netlify.app/?path=/docs/components-object-status--primary#clickable-object-status 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/platform/object-status
2. Go to Clickable Object Status example.
3. Try to tab through the clickable object statuses. None of them are tabbable.
Also, UI5 example shows focus for clickable object status, but it is not present here. Generally, if something is a link, one would expect focus and tabbing for it.

UI5: 
![image](https://user-images.githubusercontent.com/53509521/94402097-3407b600-0189-11eb-803c-be2b945a6de7.png)

**Comment by Betrozov** [comment]
Fix for focus here https://github.com/SAP/fundamental-styles/issues/2009

**Comment by kavya-b** [comment]
This is now fixed with the Styles PR 2009 merging. Verified on ngx: 
![image](https://user-images.githubusercontent.com/53509521/120265858-75bfa200-c2be-11eb-882f-0c5f5538d92a.png)
@puru-hk please verify

**Comment by puru-hk** [comment]
Tested it is working as expected.
