### ISSUE TITLE
Bug: Platform List - Keyboard accessibility issue

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#3415]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Keyboard accessibility of arrow-key up/down not working correctly.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10

#### If this is a bug, please provide steps for reproducing it.
1. click on third item of the list.
2. press arrow-key down
3. focus should go on to forth item.
4. but focus goes to first item.

**Comment by manjunathanagaraj** [comment]
Not critical for 0.22, but to be fixed in sprint47
