### ISSUE TITLE
 Horizontal scroll in table

### ISSUE THREAD

**Issue by daiyidong** [SAP/fundamental-ngx#3417]
#### Is this a bug, enhancement, or feature request?
Feature request
#### Briefly describe your proposal.
In FSM, we have a case customer have more than20+ columns in one table, it will not display completely or perfectly in small screen, customer expect the table content could be scroll horizontally.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v 0.21.0

**Comment by droshev** [comment]
@daiyidong how about [this](https://fundamental-ngx.netlify.app/#/platform/table#freezable-table)

**Comment by platon-rov** [comment]
Currently, that's the case if all the table columns not fit then the table gets a horizontal scrollbar, even without using `freezableColumnsTo` feature.

**Comment by puru-hk** [comment]
@daisy-yovcheva verified the recent ngx version rc 53 https://fundamental-ngx.netlify.app/#/platform/table. Horizontal scrollbar is appears in the small screen all the column is visible. Could you please verify from your side and close.
