### ISSUE TITLE
Bug: core card - fd-card-counter RTL not aligned

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#3418]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

For Counter the variables in counter is displayed in a wrong manner "of 15 3" instead it has to displayed in 3 of 15  https://fundamental-ngx.netlify.app/#/core/card

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest

#### If this is a bug, please provide steps for reproducing it.

Goto: https://fundamental-ngx.netlify.app/#/core/card
Goto: Analytical section 
click on  the RTL mode and check the counter string 

Expected has to "3 of 15" but we see "of 15 3" and negative number is displayed in wrong manner 14.52

same thing has been reflected in all the card layout types. please check 

Screen shot:
![image](https://user-images.githubusercontent.com/53534379/94410078-91edcb00-0194-11eb-926d-87e4c593f320.png)

**Comment by manjunathanagaraj** [comment]
@dimamarksman ,please fix this.

**Comment by dimamarksman** [comment]
This probably should be fixed in fundamental-styles, it reproduces there as well

**Comment by dimamarksman** [comment]
Btw the counter behaves intentionally, not an issue at all

![image](https://user-images.githubusercontent.com/3263744/94536761-71cd1300-024b-11eb-8794-88ec8d032921.png)

Dev is responsible to put appropriate string to the `counter`.
So if it should be in RTL then appropriate string should be there.
In our case if translate `3 of 15` in arabic it will be `3 من 15`. If you past this translates string in the counter in RTL mode it will render the next:

![image](https://user-images.githubusercontent.com/3263744/94538464-bb6a2d80-024c-11eb-907a-537daeeaa33a.png)
