### ISSUE TITLE
Context menu in table

### ISSUE THREAD

**Issue by daiyidong** [SAP/fundamental-ngx#3419]
#### Is this a bug, enhancement, or feature request?
Feature request
#### Briefly describe your proposal.
The context menu gives users an alternative way to modify the focused elements by giving them access to context-specific functions. the Fiori Guideline : https://ux.wdf.sap.corp/fiori-design-web/grid-table/#context-menu

**Comment by JKMarkowski** [comment]
This will be checked once we merge https://github.com/SAP/fundamental-ngx/pull/3582

**Comment by droshev** [comment]
will be part of #7118
