### ISSUE TITLE
Defect Hunting Fundamental NGX 0.22 [2]

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#3420]
Defect Hunting before v0.22.0 release.

**Comment by JKMarkowski** [comment]
- [ ] Notifications - Need to bring old styling

- [ ] Header Github icon not centered
![image](https://user-images.githubusercontent.com/26483208/94420607-ade97080-0184-11eb-838b-b358d654f4f6.png)

- [ ] Action Bar - Need to bring changes from [this pr](https://github.com/SAP/fundamental-styles/pull/1338/files)
![image](https://user-images.githubusercontent.com/26483208/94420684-c8bbe500-0184-11eb-9297-caa0a33bab04.png)

- [ ] Overflow breadcrump - Color + cursor is not pointer
![image](https://user-images.githubusercontent.com/26483208/94420830-00c32800-0185-11eb-838b-42c769777ecf.png)

**Comment by katekozlowska** [comment]
## CHROME 


 - [ ] Tokens are not centered
![deploy-preview-3400--fundamental-ngx netlify app_](https://user-images.githubusercontent.com/7014311/94432441-117c9980-0197-11eb-9115-0c8a9fff9f7d.png)

**Comment by salarenko** [comment]
- [ ] Floating Bar Footer example is broken - IE11
![image](https://user-images.githubusercontent.com/17496353/94422919-19810d00-0188-11eb-9448-5bbb10067504.png)

- [ ] Combobox Custom Item Template should be updated to use list item markup to provide proper styling.

- [ ] `composedPath` is not supported in IE11 (Popover)

- [ ] `attachShadow` is not supported in IE11, breaking whole documentation page (Popover)

- [ ] File Uploader placeholder is cleared out when file input is focused - IE11
![file-uploader](https://user-images.githubusercontent.com/17496353/94429734-12abc780-0193-11eb-91c4-c47b08074b50.gif)

- [ ] Notification has not been migrated to Fundamental Styles v0.12.0
![image](https://user-images.githubusercontent.com/17496353/94430727-aaf67c00-0194-11eb-83b8-c1e8e4cbb38f.png)

- [ ] Basic Shellbar button - IE11
![image](https://user-images.githubusercontent.com/17496353/94431822-19880980-0196-11eb-871a-d0ae94af892a.png)

- [ ] Shellbar Menu button icon - IE11
![image](https://user-images.githubusercontent.com/17496353/94431983-5bb14b00-0196-11eb-857a-2de2cdfdff54.png)

- [ ] Side Navigation examples missing expand icon? - IE11
![image](https://user-images.githubusercontent.com/17496353/94432125-94e9bb00-0196-11eb-91aa-5e97e457b8b9.png)

- [ ] Empty column in table example - Cross browser
![image](https://user-images.githubusercontent.com/17496353/94433697-0165b980-0199-11eb-934d-ebe18c7b8a82.png)

- [ ] Layout Grid is missing styles - Cross browser
![image](https://user-images.githubusercontent.com/17496353/94434943-cbc1d000-019a-11eb-8cd0-fa4d8fdb3111.png)

**Comment by katekozlowska** [comment]
Several issues reported under **FIrefox** are also applicable to **Chrome**, please check fixes under both browsers.

**Comment by stefanoScalzo** [comment]
![Screen Shot 2020-09-28 at 10 24 48 AM](https://user-images.githubusercontent.com/50607147/94444961-e6814e00-0174-11eb-88ab-161b74d3d30e.png)
Table toolbar issues

**Comment by InnaAtanasova** [comment]
> ![Screen Shot 2020-09-28 at 10 24 48 AM](https://user-images.githubusercontent.com/50607147/94444961-e6814e00-0174-11eb-88ab-161b74d3d30e.png)
> Table toolbar issues

@stefanoScalzo 
If you meant buttons issues in the table, they've been fixed with the Buttons PR. Here's how it's in master now:
<img width="1944" alt="Screen Shot 2020-09-29 at 4 24 24 PM" src="https://user-images.githubusercontent.com/39598672/94611890-5b857e00-0270-11eb-9095-771f71790c21.png">

If you meant other issues, please specify

**Comment by InnaAtanasova** [comment]
All issues have been addressed and the PRs have been merged. Awesome job everyone!
