### ISSUE TITLE
Bug: Platform Standard List Item - label text issue

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3423]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

When switching between LTR and RTL the 'items selected' label text becomes incorrect. The parenthesis become backwards. i.e. instead of "(1) items selected" it shows ")1( items selected".

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 10

#### If this is a bug, please provide steps for reproducing it.

1. Select an item
2. Click to enable RTL
3. Click to disable RTL
4. Look at '() items selected' label
**Actual results:** label shows as ")1( items selected" - parenthesis are backwards
**Expected results:** label will show as "(1) items selected" - parenthesis will be correct

![2020-09-28_2](https://user-images.githubusercontent.com/47522152/94434434-738ecc00-01a2-11eb-9ed2-60c94748a2ef.png)
![Peek 2020-09-28 15-44](https://user-images.githubusercontent.com/47522152/94434441-75f12600-01a2-11eb-92ff-31cb13645c6f.gif)

#### Is there anything else we should know?

Reproduced for list - multi selection
Chrome v.85

**Comment by sKudum** [comment]
```
<fd-toolbar fdType="info" active="true">
    <label fd-toolbar-label>({{_selectedItems.length}}) Items selected</label>
</fd-toolbar
```

fd-toolbar-label [dir=rtl] styles needs to be update to support it.
