### ISSUE TITLE
Bug: Platform Combobox - IE11 - Dropdown positioning

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3428]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Dropdown is positioned incorrectly in IE11 (the issue happens for bottom positioning only)

![image](https://user-images.githubusercontent.com/3263744/94438256-8b1c8380-01a7-11eb-951e-f1e5550010b2.png)

#### Is there anything else we should know?
OS Windows 10

**Comment by puru-hk** [comment]
Tested in fundamental ngx version 30.1. it is working as expected.
