### ISSUE TITLE
Bug: Platform Combobox - IE11 - Input shows "X" clear sign

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3429]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In IE11 when some text is entered and input field is in focus the "X" sign is shown in the text field (aka clear button)

#### If this is a bug, please provide steps for reproducing it.
1. Open in IE11 https://fundamental-ngx.netlify.app/#/platform/combobox
2. Select any item from dropdown.
3. Put focus to the field.
4. See result
![image](https://user-images.githubusercontent.com/3263744/94440809-b81e6580-01aa-11eb-9c54-969293821e99.png)

#### Is there anything else we should know?
OS: Windows 10

**Comment by dmitry-stepanenko** [comment]
cannot reproduce
