### ISSUE TITLE
Improve Travis and Netlify build time

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3433]
At the moment our average build time:
- in netlify is 7m 26s
<img width="895" alt="Screen Shot 2020-09-28 at 4 48 46 PM" src="https://user-images.githubusercontent.com/4380815/94484613-b48ade80-01aa-11eb-8d4f-390b3747effd.png">
- in Travis each of the tasks take between 8-12 minutes.

![Screen Shot 2020-09-28 at 4 51 20 PM](https://user-images.githubusercontent.com/4380815/94484831-09c6f000-01ab-11eb-980a-882c7ea70b60.png)

#### Briefly describe your proposal.
Investigate and see whether we can improve those times

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by InnaAtanasova** [comment]
Possible issues:
- tests
- lint running on Travis
- having the 2 projects together
- different builds (distinguish if the PR is in core or platform and run the checks/builds only for this project)

Consult with the Valor team if they have some solutions in mind.
Time box: 2 days max

**Comment by JKMarkowski** [comment]
Every push to our repo triggers CI - Check this build for [example](https://travis-ci.org/github/SAP/fundamental-ngx/builds/733591080) It's worth to investiate how we can disable it

**Comment by droshev** [comment]
getting slower
<img width="927" alt="Screen Shot 2020-10-07 at 7 49 20 AM" src="https://user-images.githubusercontent.com/4380815/95327169-a22b3780-0871-11eb-8cf7-e5f96ac0206c.png">
