### ISSUE TITLE
Style issue: TriState Checkbox selected blue indicator misplaced

### ISSUE THREAD

**Issue by yukioht** [SAP/fundamental-ngx#3435]
#### Is this a bug, enhancement, or feature request?
Bug. Only found in NGX and not Fundamental Styles as this style seems to be not yet created.

#### Briefly describe your proposal.
The placement of TriState state blue indicator is off-center. It should be center-aligned.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v 0.21.0

#### If this is a bug, please provide steps for reproducing it.
See some of the blue indicator element on the Tristate Checkbox are misplaced (off-center).
https://sap.github.io/fundamental-ngx/#/platform/checkbox

#### Is there anything else we should know?
Please see the screenshots. 
The misplaced blue indicator is most noticeable in Chrome.

<img width="1149" alt="Chrome" src="https://user-images.githubusercontent.com/71727800/94511131-51f70a00-01cd-11eb-8edd-f45d03d16f30.png">
<img width="1093" alt="Safari" src="https://user-images.githubusercontent.com/71727800/94511137-56232780-01cd-11eb-86fb-3acfc9087a52.png">
<img width="1251" alt="FF" src="https://user-images.githubusercontent.com/71727800/94511143-59b6ae80-01cd-11eb-8f11-b8a9a7587569.png">

**Comment by DeepakSap14** [comment]
@puru-hk  This is styles issue.

**Comment by puru-hk** [comment]
@yukioht could you please raise this issue in fundamental styles.

**Comment by yukioht** [comment]
Done. https://github.com/SAP/fundamental-styles/issues/1876
