### ISSUE TITLE
Style issue: Checkbox (Compact) dimension, color and padding

### ISSUE THREAD

**Issue by yukioht** [SAP/fundamental-ngx#3436]
#### Is this a bug, enhancement, or feature request?
Bug (Styling related) found in NGX only as this style is not found in the Fundamental Styles examples.

#### Briefly describe your proposal.
Compact Checkbox dimension, icon size, padding need to be corrected to the latest spec listed below.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v 0.21.0

#### If this is a bug, please provide steps for reproducing it.
Compact Checkbox dimension, icon size, padding in the existing NGX component library to below spec.
https://sap.github.io/fundamental-ngx/#/platform/checkbox

Spec: 
Checkbox size: 14px or 0.875 rem (currently 15.989px)
Icon (arrow) color: #0A6ED1 
Icon padding 1px

Please refer to:
<img width="393" alt="Screen Shot 2020-09-28 at 9 04 59 PM" src="https://user-images.githubusercontent.com/71727800/94511478-4f48e480-01ce-11eb-80ad-534373ddd617.png">

#### Please provide relevant source code if applicable.
Please see attached screenshot.
<img width="1037" alt="Screen Shot 2020-09-28 at 9 12 41 PM" src="https://user-images.githubusercontent.com/71727800/94511860-61775280-01cf-11eb-9086-e722b7690af7.png">

#### Is there anything else we should know?
Here's a mock-up created by the screenshots of the currently implemented checkbox and the proposed design.
<img width="862" alt="Screen Shot 2020-09-28 at 9 17 48 PM" src="https://user-images.githubusercontent.com/71727800/94512103-1873ce00-01d0-11eb-8c07-d6cb9aeb8292.png">

**Comment by puru-hk** [comment]
@yukioht could you please this issue in fundamental styles.

**Comment by yukioht** [comment]
Hi @puru-hk 
This is an NGX specific issue and different from the checkbox implementation in Fundamental Styles.
Please see attached screenshot. 

<img width="1294" alt="Screen Shot 2020-11-10 at 10 17 12 AM" src="https://user-images.githubusercontent.com/71727800/98714701-160fa280-233e-11eb-9468-ddc3f34ac44a.png">
<img width="1294" alt="Screen Shot 2020-11-10 at 10 16 56 AM" src="https://user-images.githubusercontent.com/71727800/98714712-190a9300-233e-11eb-847c-42c46fd8c993.png">

@KevinOkamoto,
Should I still report this issue in Fundamental Styles?

**Comment by DeepakSap14** [comment]
verified but could not find the issue. 
checkbox in fundamental-ngx has same dimensions as specified in fiori checkbox page.
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2060052861
Moreover fundamental-ngx is having same styles as fundamental-ngx checkbox.
Fundamental-ngx is not applying/modifying any styles.

Icon has some issue related to font-size because SAP-icons does not work same way in every browser.
If this is the issue then it can be handled with a separate issue. (here only resolution will be to not using sap-icons.)
