### ISSUE TITLE
Fixed card layout dimension does not change on card hide

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#3437]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.

lets assume component is in following state:

`[ card ] [ card ] [ card ] [ card ]`
And then number of cards changes to 1:

`[ card ] [  ] [  ] [  ]`
Leaving with empty containers for columns.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10

**Comment by droshev** [comment]
We need to revisit the Card Layouts in general
