### ISSUE TITLE
Accessibility: Textarea: There is no keyboard support provided for Help icon highlighted in red. 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3441]
Description: There is no keyboard support provided for Help icon highlighted in red. That is, the ‘Help’ icons are not reachable via keyboard. 

Expected: Ideally, each & every UI should be reachable via keyboard

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/94518455-92936980-0247-11eb-9657-a9e5717954d8.png)
![image](https://user-images.githubusercontent.com/32538291/94518464-97581d80-0247-11eb-9a6c-aaffc044ce9a.png)

**Comment by kavya-b** [comment]
This has to be handled at the Platform Forms level, and is not related to Textarea.
