### ISSUE TITLE
Bug:  Toolbar - label with special characters display issue

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#3455]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

When switching between LTR and RTL the label text with special characters becomes incorrect. The parenthesis becomes backward. i.e. instead of "( ) " it shows ")( ".

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 10

#### If this is a bug, please provide steps for reproducing it.

1. Select an item
2. Click to enable RTL
3. Click to disable RTL
4. Look at '()' label
**Actual results:** label shows as ")( " - parenthesis are backward
**Expected results:** label will show as "() " - parenthesis will be correct
![2020-09-29_12-15-01 (1)](https://user-images.githubusercontent.com/53487468/94522978-223c1680-024e-11eb-977b-1f27518abb96.gif)

**Comment by olshansky** [comment]
I believe it's not really a toolbar issue, but maybe a general `rtl` issue. I've tried the same with `tab` and got similar behavior:
![rtl-issue](https://user-images.githubusercontent.com/14160094/94687812-6eae5180-0335-11eb-9012-81abfa719f1c.gif)

**Comment by dimamarksman** [comment]
Yeah, that's a chrome issue. In other browsers it works fine.
There is a similiar [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1034338&q=LTR%20RTL%20mode&can=1) reported in the chromium issue tracker regarding it.

**Comment by skocharian** [comment]
I can confirm this is working properly with Firefox and Safari
