### ISSUE TITLE
Collapsing sidenav

### ISSUE THREAD

**Issue by schaefermichael** [SAP/fundamental-ngx#347]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
It would be great if the sidenav would implement a collapse mechanism. Currently, the sidenav collapse attribute only removes some spacing but does not actually hide the navigation labels. Also, it does not offer a fully collapsed state which would be helpful for mobile screens.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
fundamentals-ngx 0.0.22-beta, Angular 7

**Comment by mikerodonnell89** [comment]
@saadmhybris @xak thoughts on this?

**Comment by xak** [comment]
I'm not clear what this is about. Collapsing the list groups, the full nav?

There is a new side navigation spec that is currently under review that will address a variety of collapse states with mobile considered.

**Comment by schaefermichael** [comment]
It's about collapsing the whole nav to either the collapsed state (with only the icons visible) or even disappear fully (probably needed on mobile).
Great to hear that a spec will be coming

**Comment by droshev** [comment]
Hello, We have all of the features which will be released as `0.13`.
We need to add examples on our documentation site:
- add hamburger button on the shell bar - toggles between the state with labels(and icons) to just icons(called condensed) and on mobile it toggles between no side nav and side nav with icons and text

**Comment by stefanoScalzo** [comment]
Hide 3rd level
https://deploy-preview-1604--fundamental-ngx.netlify.com/#/core/sideNavigation#buildByObject
