### ISSUE TITLE
Design: Handling responsiveness for Dynamic Page layout in platform

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3473]
#### Is this a bug, enhancement, or feature request?
design

#### Briefly describe your proposal.
Currently, there is no standard single way of handling responsiveness in the ngx library. For eg; Bar chooses to ask user to input the s, m,l,xl sizes to set the padding for the bar accordingly; whereas Dialog listens for windowResize event and handles these sizes within the library itself. For the first phase, we are going with the Bar approach of asking user’s input for the size that should be applied, and revisit this when we have a better idea of how to handle responsiveness for Dynamic Page Layout.
The effect of not handling this for now will be that the following requirements from Fiori design spec will not be handled now:
1. less than 1299px, the global layout actions must move one row above
2. summary line should be visible for mobile

**Comment by droshev** [comment]
I hope this issue has been tackled. closing it and reopen and plan properly if more things are needed
