### ISSUE TITLE
Implement Dynamic Page Layout in ngx/platform

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3474]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
Implement the Dynamic Page Layout in the platform library. 
Over core, it will have the added feature of automatically creating tab navigation, if at least one of the Dynamic Page Content components have a `tabLabel` defined.

Not supported for Phase 1: 
1. Handling responsiveness- as of now there is no standard single way of handling responsiveness in the ngx library. For eg; Bar chooses to ask user to input the s, m,l,xl sizes to set the padding for the bar accordingly; whereas Dialog listens for windowResize event and handles these sizes within the library itself. For the first phase, we are going with the Bar approach of asking user’s input for the size that should be applied, and move this to backlog since we should ideally have a common way of doing responsiveness. An issue for tracking any update on this is created- https://github.com/SAP/fundamental-ngx/issues/3473 .
2. Summary Line - this feature is only available for mobile, and not a priority for 1P either so this can be moved to backlog as well.

The effect of not handling this for now will be that the following requirements from Fiori design spec will not be handled now:
1. less than 1299px, the global layout actions must move one row above
2. summary line should be visible for mobile

**Comment by manjunathanagaraj** [comment]
PR still in progress. Therefore moving to sprint48
