### ISSUE TITLE
Accessibility:Switch: Switch buttons are read(by screen reader) as checkbox.  

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3495]
Description: Switch buttons are read(by screen reader) as checkbox. 

Expected: each & every UI should be correctly read out based upon its type when accessed. 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/94651150-9ee5f800-0315-11eb-9fc2-a1e9ee5f8e17.png)

**Comment by puru-hk** [comment]
@Sanjay-1312 Please test this issues

**Comment by Sanjay-1312** [comment]
Description: Switch buttons are read(by screen reader) as checkbox.

Expected: each & every UI should be correctly read out based upon its type when accessed.

Comment: Issue is still  reproducible, can you please fix it

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/108034660-d8689700-705b-11eb-8386-8016b011aea7.png)

**Comment by puru-hk** [comment]
@Betrozov This issues tested by accessibility team. Still it is not fixed. Could you please look into this issue.
