### ISSUE TITLE
Accessibility:Step Input: The aria-expanded attribute is not allowed on this DIV

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3499]
Description: The aria-expanded attribute is not allowed on this DIV
Code snippet:
<div aria-disabled="false" aria-expanded="false" ng-reflect-append-to="[object HTMLDivElement]" ng-reflect-close-on-escape-key="true" ng-reflect-close-on-outside-click="true" ng-reflect-options="[object Object]" ng-reflect-focus-trapped="false" ng-reflect-placement="right" ng-reflect-triggers="mouseenter,mouseleave" ng-reflect-disabled="false" ng-reflect-no-arrow="false" ng-reflect-is-open="false" ng-reflect-additional-classes="" ng-reflect-content="[object Object]" class="fd-popover__control" aria-haspopup="true"><div><span class="fd-inline-help" role="alert"></span></div></div>

Expected: When ARIA attributes (state, roles, and properties) are not used correctly assistive technology may not correctly function as expected. Valid markup should always be used.
Developers must use valid markup and follow the rules of the ARIA specification.

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/94652075-1a947480-0317-11eb-95cf-da0c6b9f6832.png)

**Comment by Betrozov** [comment]
Hi @puru-hk 
This issue is outdated.
The Popover component was reworked to use `@angular/cdk/overlay`.
Could you please retest it?

**Comment by puru-hk** [comment]
@Sanjay-1312  Could you please retest this issue and let us know if you are able to reproduce.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Couldn't able to reproduce the issue.
Hence Closing the ticket.

Thanks and Regards
Sanjay
