### ISSUE TITLE
Accessibility: This input (type=radio) should not have an aria-checked attribute, as it has a native semantic checked state.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3504]
Description: This input (type=radio) should not have an aria-checked attribute, as it has a native semantic checked state.

Code snippet:
<input aria-checked="false" aria-disabled="false" ng-reflect-value="1" ng-reflect-name="radio1" id="radio-id-0" ng-reflect-is-disabled="false" class="fd-radio fd-radio ng-untouched ng-pristine ng-valid" type="radio">

Expected: When ARIA attributes (state, roles, and properties) are not used correctly assistive technology may not correctly function as expected. Valid markup should always be used.
Developers must use valid markup and follow the rules of the ARIA specification.

screenshot

![image](https://user-images.githubusercontent.com/32538291/94654027-1ae23f00-031a-11eb-8c3d-defac6a6a5a9.png)

**Comment by sKudum** [comment]
fd-radio-button is used in list, so assigning it to @DeepakSap14 for further investigation.

<img width="1535" alt="2020-12-16_12-37-30" src="https://user-images.githubusercontent.com/53487468/102316269-a3788f00-3f9b-11eb-8dc7-399adaca386b.png">

Hi @DeepakSap14 , Could you please have a look at checkbox and radio button for aria-checked and update accordingly.

**Comment by DeepakSap14** [comment]
after debugging found that this fix is needed in list component. This is fixed in PR #4160
