### ISSUE TITLE
Unify all 'cozy' / 'cosy' appearances.

### ISSUE THREAD

**Issue by katekozlowska** [SAP/fundamental-ngx#3518]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

Change all 'cosy' appearances to 'cozy'.

![image (1)](https://user-images.githubusercontent.com/7014311/94781284-e4fc9380-03c9-11eb-8254-780174fef6a5.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.22.0

**Comment by InnaAtanasova** [comment]
We need to use 'cozy'.
1 hour
