### ISSUE TITLE
Adapt Fiori v0.12.0 Layout Grid

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#3520]
#### Is this a bug, enhancement, or feature request?
This is enhancement

#### Briefly describe your proposal.
Fundamental NGX needs to adapt new version of Layout Grid component available in Fundamental Styles v0.12.0.

#### Is there anything else we should know?
There is already existing implementation on this branch: [3420-layout-panel](https://github.com/SAP/fundamental-ngx/tree/fix/3420-layout-panel)

The PR contains:
- Implementation of Fundanemtal Styles v0.12.0 Layout Grid and its features

The work to be done there is:
- Writing tests for the component
- Finishing the documentation
- Writing down the breaking changes

**Comment by droshev** [comment]
@mikerodonnell89 any update here?
