### ISSUE TITLE
Style issue: Button icon font not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3524]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
- Please double check Compact and Cozy Buttons: **Visual core has icon font at 1rem (16px) vs Inspect mode on NGX is at .875rem (14px)**
#### Please provide relevant source code if applicable.
<img width="532" alt="Screen Shot 2020-10-01 at 4 12 06 PM" src="https://user-images.githubusercontent.com/71797052/94872969-ded6d900-0402-11eb-845b-6a402be0a3a8.png">

**Comment by sKudum** [comment]
It can't be fixed in ngx, It is a styles issue, please log it in fundamental-styles.
