### ISSUE TITLE
Platform - Textarea component has wrong position of the * in required field

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3528]
#### Is this a bug, enhancement, or feature request?
<img width="1072" alt="Screen Shot 2020-10-02 at 8 57 21 AM" src="https://user-images.githubusercontent.com/39598672/94925938-01fa9a80-048e-11eb-8895-f1bb2247c567.png">

The * in a required field is shown after the help icon. Should be after the text.

Exprected behaviour:
<img width="891" alt="Screen Shot 2020-10-02 at 9 04 02 AM" src="https://user-images.githubusercontent.com/39598672/94926100-3ec69180-048e-11eb-8f4c-f13180d89397.png">

**Comment by kavya-b** [comment]
fixed with #3680
