### ISSUE TITLE
Update doc examples for Object Status icons 

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-ngx#3533]
Object status icon, we still use the old version. 
- Fiori 3 suggests the new version: https://ux.wdf.sap.corp/fiori-design-web/object-display-elements/#object-status.
- Visual core also suggests the new version: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2057761379

Old version:
<img width="1016" alt="Screen Shot 2020-10-06 at 10 14 55 PM" src="https://user-images.githubusercontent.com/72157987/95290320-d119bd00-0821-11eb-9141-8f2bf099ff84.png">

New version:
<img width="539" alt="Screen Shot 2020-10-06 at 10 15 10 PM" src="https://user-images.githubusercontent.com/72157987/95290340-de36ac00-0821-11eb-9e81-c462d018152a.png">

**Comment by droshev** [comment]
@wenyang33 thank you for your ticket. There is no issue with Object Status. It allows you to specify any icon you want to use by setting it with `glyph`
