### ISSUE TITLE
Split menu button

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-ngx#3535]
#### Split menu button, the menu aligns with the left line of the icon area
- In Fiori, the menu aligns with the very left line of the whole component: https://ux.wdf.sap.corp/fiori-design-web/button/#menu-button
- In UI5, the same with Fiori 3: http://veui5infra.dhcp.wdf.sap.corp:8080/sapui5-sdk-dist/#/entity/sap.m.MenuButton/sample/sap.m.sample.MenuButton

Our version:
<img width="349" alt="Screen Shot 2020-10-06 at 10 19 29 PM" src="https://user-images.githubusercontent.com/72157987/95290449-205fed80-0822-11eb-925f-3959e63a266f.png">

Fiori 3:
<img width="187" alt="Screen Shot 2020-10-06 at 10 19 10 PM" src="https://user-images.githubusercontent.com/72157987/95290455-23f37480-0822-11eb-8b41-3727f05be226.png">

**Comment by droshev** [comment]
@wenyang33 thank you for opening the issue! would you mind not setting the release number as a label?

**Comment by droshev** [comment]
@manjunathanagaraj would you include this bug to be addressed?
