### ISSUE TITLE
Fixed card Layout: RTL mode count is showing wrong (3 of 10)

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3541]
Description: RTL mode count is showing wrong (of 10 3)

Expected: Count should be displayed properly 

screenshot:

![image](https://user-images.githubusercontent.com/32538291/95042180-b8f94f00-06f6-11eb-91f9-49d42dcced0e.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/95042294-02e23500-06f7-11eb-8b70-07f6f925c9d6.png)

**Comment by DeepakSap14** [comment]
Seems to be card component issue. @puru-hk  please assign relevant person.

**Comment by dimamarksman** [comment]
Please take a look https://github.com/SAP/fundamental-ngx/issues/3418#issuecomment-700573734

**Comment by Seamoo13** [comment]
according to the comment mentioned above and the discussions on the old tickets for the same issue, not a bug.
