### ISSUE TITLE
Fixed card Layout: Styles are not proper in both portrait and landscape mode in Mobile device 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3542]
Description: Styles are not proper in both portrait and landscape mode in Mobile device

Expected: Styles should be as per the Fiori3 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/95044580-6a9b7e80-06fd-11eb-8836-e52daafe7250.png)

![image](https://user-images.githubusercontent.com/32538291/95044587-6cfdd880-06fd-11eb-9e91-6e60cfc569f6.png)

![image](https://user-images.githubusercontent.com/32538291/95044596-6ff8c900-06fd-11eb-8e5f-570e38102098.png)

**Comment by puru-hk** [comment]
In the portrait mode not able to scroll down to view card.

**Comment by DeepakSap14** [comment]
Addressed in https://github.com/SAP/fundamental-ngx/pull/3651.

**Comment by DeepakSap14** [comment]
PR is merged with fix. Issue can be closed

**Comment by puru-hk** [comment]
Still this is issue is not fixed.

**Comment by puru-hk** [comment]
Verified in fundamental ngx i'm able to reproduce this issue. Before closing the issue please recheck once and then closed.

**Comment by puru-hk** [comment]
this issue is fixed in netlify master.
