### ISSUE TITLE
Fixed Card Layout: Changing from portrait to landscape mode card position is changing 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3543]
Description: Changing from portrait to landscape mode card position is changing 

Expected: Card position should not change when user change from portrait to landscape mode

attached the video. 

[Screen Recording 2020-10-05 at 12.09.29 PM.zip](https://github.com/SAP/fundamental-ngx/files/5325714/Screen.Recording.2020-10-05.at.12.09.29.PM.zip)

**Comment by DeepakSap14** [comment]
This will be handled in application side. Application developer will use cookies for saving these positions.

**Comment by puru-hk** [comment]
Assign back to deepak.

**Comment by puru-hk** [comment]
Tested it is working as expected
