### ISSUE TITLE
bug: core card: UI elements cut off and not shown

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3550]
![analyticalcard_cutoff_windows_ie11](https://user-images.githubusercontent.com/47522152/95056750-d5e55080-06fd-11eb-8f01-cdebb4ad6e00.jpg)
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

When using internet explorer:
1. numeric elements are cut off 
2. status icon is not shown (arrow up/down)
3. numeric scale not shown (i.e. %,K)
setup: Windows PC, **Internet Explorer**, env: https://fundamental-ngx.netlify.app/#/core/card 

#### If this is a bug, please provide steps for reproducing it.

1. navigate to the analytical card using internet explorer browser
2. look at header content

![analyticalcard_missingicon_windows_ie11](https://user-images.githubusercontent.com/47522152/95056735-d1209c80-06fd-11eb-87fe-7e8f5f4c4cc7.jpg)

**Comment by DeepakSap14** [comment]
It is not reproducible, tested in IE 11 browser under windows machine.

**Comment by Seamoo13** [comment]
not reproduced.
