### ISSUE TITLE
Fixed card Layout: In IE browser Focus is not as per the fiori3 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3552]
Description: In IE browser Focus is not as per the fiori3 

Expected: Focus should be as per the fiori3 spec.

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/95093613-97c04f00-0746-11eb-909c-e3dc8d7b37f9.png)

Expected:
![image](https://user-images.githubusercontent.com/32538291/95093700-ae66a600-0746-11eb-8945-0812465a95e0.png)

**Comment by DeepakSap14** [comment]
@puru-hk , fiori does not mention about focus on entire card.
focus will be based on card component.
This was extra focus that was coming. It has bee fixed. please verify in below PR.
https://github.com/SAP/fundamental-ngx/pull/3651
