### ISSUE TITLE
Remove insensitive terms from repo: migrate from "master" to "main"

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3554]
**Description**
`master` -> `main` per new SAP open source guidelines. Deadline 12/31.

- update CI, scripts and repo
- master must not be present in the source code at all - don't just rename the branch
- audit for other insensitive terms (I did a brief look and I think master is our only one we need to change)

For more info, see email sent 10/5 from Open Source Program Office

**Comment by JKMarkowski** [comment]
What should be done:
- merge https://github.com/SAP/fundamental-ngx/pull/4100
- change production branch master -> main in [netlify settings](https://app.netlify.com/sites/fundamental-ngx/settings/deploys#deploy-contexts)
- change default branch in [github settings](https://github.com/SAP/fundamental-ngx/settings/branches)
- travis CI has been changed in `travis.yml` file in PR
