### ISSUE TITLE
bug: core: object marker: spelling mistake in aria-label text

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3558]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

for the object marker  with text section and icon with text section, the aria labels say "maker" instead of "marker". Subsequently the screen reader technology reads "maker" to the user instead of "marker"
env: https://fundamental-ngx.netlify.app/#/core/object-marker

#### If this is a bug, please provide steps for reproducing it.

![2020-10-06](https://user-images.githubusercontent.com/47522152/95179752-be739980-07c9-11eb-8c54-fbf5543219b7.png)
![Screenshot_3](https://user-images.githubusercontent.com/47522152/95179767-c0d5f380-07c9-11eb-9c26-3a35d3daf123.jpg)
![2020-10-06_1](https://user-images.githubusercontent.com/47522152/95180520-c41daf00-07ca-11eb-8425-9c612c40af4a.png)

**Comment by Lokanathan-k** [comment]
closed as part of this PR https://github.com/SAP/fundamental-ngx/pull/4081
