### ISSUE TITLE
bug: core card: for safari, tab navigation misses buttons, content sections, footers

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3560]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

The 'tab' navigation skips over the RTL selector, switch background selector, card footer, buttons.. 
Tab should navigate through all points

MacOs Catolina
Safari 13
env: https://fundamental-ngx.netlify.app/#/core/card

#### If this is a bug, please provide steps for reproducing it.

use 'tab' navigation through card components
![Peek 2020-10-06 13-36](https://user-images.githubusercontent.com/47522152/95192804-65146600-07db-11eb-84d9-6dfccd37c661.gif)

**Comment by DeepakSap14** [comment]
https://user-images.githubusercontent.com/57661487/104410707-e9227a80-558e-11eb-8eca-bf0bf0a1fcb3.mov

Not reproducible on MacOs safari/chrome/firefox.
