### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3564]
In Ariba System we have 3 types: Label only, Icon+Label+Icon (arrow), and Combination.
You only show interactions with labels. The other two types are missing.

Ariba system: https://wiki.ariba.com/pages/viewpage.action?pageId=97363748

**Comment by manjunathanagaraj** [comment]
@daisy-yovcheva , is this applicable for core or platform menu component?

**Comment by daisy-yovcheva** [comment]
Hi @manjunathanagaraj, I bet I was looking at the Platform because I can see now all the types in Core.  Please feel free to close the ticket. Thank you!
