### ISSUE TITLE
Switch: It's missing a variant with on/off label

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3565]
It’s missing switch example with label on/off inside:
Visual core: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2033867295

**Comment by manjunathanagaraj** [comment]
This is not a bug. Please refer [Fiori3 guidelines](https://ux.wdf.sap.corp/fiori-design-web/switch/). Text within the switch is obsolete.

**Comment by puru-hk** [comment]
@daisy-yovcheva Can you please add the label as Core/Platform

**Comment by Lokanathan-k** [comment]
Primary analysis done, on analysing found that this need code change in style and in the core.

**Comment by Lokanathan-k** [comment]
hi Team on analysis found that the switch with label inside is obsolete as per the fiori 3 guidelines, Please find the attached screenshot. Assigning back to the design team.

![image](https://user-images.githubusercontent.com/53534379/119480768-9e501500-bd6f-11eb-8e51-dbcd2da5084e.png)

**Comment by puru-hk** [comment]
This issue is a duplicate of #3366. Hence closing this issue

**Comment by puru-hk** [comment]
@daisy-yovcheva Please close this issue
