### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3566]
·         You only show “Manual Search”. 
·         “Live search” interactions are missing -> Giving suggestions on typing…
·         Cozy and Compact Search by category are wrong. 

Link: https://wiki.ariba.com/display/UED/Search

**Comment by puru-hk** [comment]
@daisy-yovcheva  could please upload the screen to better understand.

**Comment by olshansky** [comment]
- “Live search” (Giving suggestions on typing) – presented in [Search Field with Categories](https://fundamental-ngx.netlify.app/#/platform/search-field#search-field-categories) and [Search Field with Data Source](https://fundamental-ngx.netlify.app/#/platform/search-field#search-field-data-source) examples
- Cozy and Compact Search height equal to 36px and 26px respectively (as described in  https://wiki.ariba.com/display/UED/Search)
