### ISSUE TITLE
fundamental-ngx/core module is added twice in the final JS file

### ISSUE THREAD

**Issue by jeyaganeshan-s** [SAP/fundamental-ngx#3571]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
we have our dependency graph like below
 
fundamental-ngx/core
fundamental-ngx/platform
fundamental-ngx/core
 
core module is added twice here.

Because of this the final js file generated has duplicate contents for 'core module components'.
Angular dependency injection is not able to pick right components for injection.
 For the 'fdp-search-field' component is it not able to find RtlService. 
I could see in the final js file, RtlService is defined twice

Path1: "./node_modules/@fundamental-ngx/core/__ivy_ngcc__/fesm2015/fundamental-ngx-core.js"
Path2: "./node_modules/@fundamental-ngx/platform/node_modules/@fundamental-ngx/core/__ivy_ngcc__/fesm2015/fundamental-ngx-core.js":

Error Message:
ERROR NullInjectorError: R3InjectorError(AppModule)[RtlService -> RtlService -> RtlService]:
  NullInjectorError: No provider for RtlService!

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
 "@fundamental-ngx/core": "^0.21.4",
   "@fundamental-ngx/platform": "^0.21.2",

#### If this is a bug, please provide steps for reproducing it.
1. Add '@fundamental-ngx/core": "^0.21.4' and '@fundamental-ngx/platform": "^0.21.2' to package.json
2. Import FundamentalNgxPlatformModule in the AppModule
3. Use fdp-search-field in the component template.

**Comment by JKMarkowski** [comment]
Hello @jeyaganeshan-s, to avoid `NullInjectorError: No provider for RtlService!` you can prodive RtlService in you `app.module`. This shouldn't be mandatory and we will investigate this issue, same as 2 same modules added.

**Comment by InnaAtanasova** [comment]
Can't be reproduced. Please reach us again if the issue is still there.
