### ISSUE TITLE
Dialog default Config option to show/hide/disable approve button

### ISSUE THREAD

**Issue by Architgoel4** [SAP/fundamental-ngx#3581]
#### Is this a bug, enhancement, or feature request?
Request/ enhancement

#### Briefly describe your proposal.

Expose the buttons to handle visibility based on conditions, when using the default config. 
I know with a templateRef we can control this behavior, but when using defaultconfig option there is no option for this.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.22.0

**Comment by JKMarkowski** [comment]
Hi @Architgoel4 To hide approve/cancel buttons, you can just not pass `approveButton` or `cancelButton` variable into `DefaultDialogObject`.

**Comment by Architgoel4** [comment]
Hi @JKMarkowski, I would need to dynamically show/hide the approve btn. Once the dialog is created, is there a way to, later on, change this in the dialogRef returned?

**Comment by JKMarkowski** [comment]
@Architgoel4 unfortnuately this is not supported by dialog component. the thing you can do is 
1. Locate dialog by id (id can be added in config)
2. Add some class that apply `display: none` to `fd-button--emphasized` class (for approve)

Or You can use component/template based dialog

**Comment by Architgoel4** [comment]
@JKMarkowski I understand, I was trying to avoid using this only. Do you think, you would be able to provide a handler for the approve button? Maybe, as a defaultDialogConfig handler or in the dialogRef, or a bindable property for the same?

**Comment by JKMarkowski** [comment]
@Architgoel4 It won't be possible to provide handler for object based dialog. The problem is the object is passed to dialog only once, when it's opened, so there is no way to control it, until it's opened again. It is meant to be used only for most basic scenarios, otherwise you should use component/template based dialog.
