### ISSUE TITLE
Bug: Core Fixed Card Layout - focus border style on card is incorrect

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3594]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
There is a blue focus border on tabbing through the cards. UI5 does not focus on the entire card at all, and visual spec doesn't specify having a focus on entire card either. Even if it is present, it should follow Fiori's focus specifications and not the browser focus style.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/fixed-card-layout
2. tab through the examples on any card
3. when focus reaches a card, observe the blue border focus.
![image](https://user-images.githubusercontent.com/53509521/95712263-1e62b800-0c82-11eb-99bf-a8b00a5bb07d.png)

**Comment by DeepakSap14** [comment]
PR is merged with fix. Issue can be closed
