### ISSUE TITLE
Bug: Core Fixed Card Layout - horizontal spacing between cards is not as per spec

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3595]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
The horizontal spacing between cards is not as per spec. It should be 1rem, but is actually more than that.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/fixed-card-layout 
2. Collapse the page sidebar.
3. Observe spacing between cards.
![image](https://user-images.githubusercontent.com/53509521/95714515-f6755380-0c85-11eb-8a3b-a5ef2b4e089a.png)

#### Is there anything else we should know?
This happens because of using the flex-layout, which occupies only as much space as is needed. The specs are being followed but due to flex usage, this issue can happen.

**Comment by DeepakSap14** [comment]
PR is merged with fix. Issue can be closed
