### ISSUE TITLE
Schema enhancements

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/fundamental-ngx#36]
While we move to angular 6 (#12) we updated typescript along the way. This gives a lot of the following errors, since the Schema is not used correctly. 
```
Types of property 'properties' are incompatible.
```

We haven't fixed this with the upgrade since, that needs to be done in this ticket. Instead we removed the Schema model and used `any` type.

**Comment by droshev** [comment]
We will remove the schemas
