### ISSUE TITLE
Bug: Core Fixed Card Layout - Unable to scroll the page within fixed cards on mobile

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#3600]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Unable to scroll the page using fixed cards area on mobile device with a touch screen (it starts dragging imidiatly without any chance for page scrolling)
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
1. open https://fundamental-ngx.netlify.app/#/core/fixed-card-layout on mobile device with a touch screen.
2. Start scrolling to page bottom.
3. When the fixed card area is reached the page scrolling becames not doable.
#### Please provide relevant source code if applicable.
The [Screenrecorder-2020-10-12-14-19-53-38.mp4.zip](https://github.com/SAP/fundamental-ngx/files/5364865/Screenrecorder-2020-10-12-14-19-53-38.mp4.zip)

**Comment by DeepakSap14** [comment]
PR is merged with fix. Issue can be closed
