### ISSUE TITLE
Bug: Core Fixed Card Layout - unnecessary header space if card has no subtitle

### ISSUE THREAD

**Issue by IlyaSurmay** [SAP/fundamental-ngx#3602]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

card's subtitle container is rendered even if there's no subtitle which leads to empty block with 4px vertical margin and this makes card title not vertically centered

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

1. Go to https://fundamental-ngx.netlify.app/#/core/fixed-card-layout
2. Look at the card that has no subtitle in header and pay attention to empty spaces above and below the title - the space below is bigger

![image](https://user-images.githubusercontent.com/18414330/95742996-a902e180-0c99-11eb-9633-42146ee49bbf.png)
<img width="429" alt="Снимок экрана 2020-10-12 в 14 46 35" src="https://user-images.githubusercontent.com/18414330/95743048-c2a42900-0c99-11eb-9d76-8ae788e93a4c.png">

#### Is there anything else we should know?

probably the solution for this issue would be not rendering this div with subtitle  (`*ngIf`)  if subtitle isn't provided

**Comment by dimamarksman** [comment]
this issue is related to core card component itself.
