### ISSUE TITLE
Bug. Core unit tests are failing in the Safari 13.1 (DatetimePickerComponent)

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#3614]
#### Is this a bug, enhancement, or feature request?
Bug.
#### Briefly describe your proposal.
Core. 1 unit test is failing in the Safari 13.1
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular CLI: 10.0.5
Fundamental Library: 0.23.0-rc.7
#### If this is a bug, please provide steps for reproducing it.
To reproduce run core unit tests in the Safari browser on you local OR
To reproduce using sauce labs: checkout https://github.com/AntonOlkhovskyi/fundamental-ngx/tree/feature/setup-saucelabs-integration
In the package.json update test:core:saucelabs with
SAUCE_USERNAME='YOU_SAUCE_USERNAME' SAUCE_ACCESS_KEY='YOUR_SAUCE_ACCESS_KEY'
Make sure it is bind to the EU Central 1 data center.
In karma.conf-ci.js comment all but sl_safari_macOS browsers in the customLaunchers obj.
run test:core:saucelabs npm script
#### Please provide relevant source code if applicable.
TOTAL: 1 FAILED, 966 SUCCESS

1) should not update input with invalid date
     DatetimePickerComponent
     Expected false to equal true.

**Comment by droshev** [comment]
@AntonOlkhovskyi is it possible to bring this in the main repo?

**Comment by Seamoo13** [comment]
not running unit tests on safari anymore
