### ISSUE TITLE
Bug. Platform unit tests are failing in the FireFox 81, on Mac 10.15 (InputGroup component, ObjectStatusComponent, ButtonComponent, Advanced Textarea, InfoLabelComponent)

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#3617]
#### Is this a bug, enhancement, or feature request?
Bug.
#### Briefly describe your proposal.
Platform. 7 unit tests are failing in the FireFox 81 on Mac 10.15
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular CLI: 10.0.5
Fundamental Library: 0.23.0-rc.7

#### If this is a bug, please provide steps for reproducing it.
To reproduce using sauce labs: checkout https://github.com/AntonOlkhovskyi/fundamental-ngx/tree/feature/setup-saucelabs-integration
In the package.json update test:platform:saucelabs with
SAUCE_USERNAME='YOU_SAUCE_USERNAME' SAUCE_ACCESS_KEY='YOUR_SAUCE_ACCESS_KEY'
Make sure it is bind to the EU Central 1 data center.
In karma.conf-ci.js comment all but sl_firefox_macOS browsers in the customLaunchers obj.

#### Please provide relevant source code if applicable.
TOTAL: 7 FAILED, 270 SUCCESS

1) Should render children in the order that they are placed
     InputGroup component
     Expected false to be truthy.

2) Should Validate diffrent object states and icon
     ObjectStatusComponent
     Expected false to be true.

3) should not select a button
     ButtonComponent
     Expected undefined to be 'false'.

4) should have aria disabled
     ButtonComponent
     Expected undefined to be truthy.

5) should handle grow indefinitely if max height is not specified
     Advanced Textarea
     Expected 153 to be 149.

6) should handle call autogrow for any other keypress
     Advanced Textarea
     Expected '57px' to be '60px'.

7) Should Add label with color
     InfoLabelComponent
     Expected false to be true.

#### Is there anything else we should know?

**Comment by Seamoo13** [comment]
not running unit tests on FF anymore
