### ISSUE TITLE
Bug: Dialog resize doesn't work when dialog in shadow root container 

### ISSUE THREAD

**Issue by Architgoel4** [SAP/fundamental-ngx#3618]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
core: 0.22.0

#### If this is a bug, please provide steps for reproducing it.
Fails to find .fd-dialog class for resize.

**Comment by JKMarkowski** [comment]
Hi @Architgoel4, could you reproduce this issue on stackblitz, everything seems to be working fine in [this example](https://stackblitz.com/edit/angular-6nruhk-1qqujp?file=src/app/dialog-configuration-example.component.ts)

**Comment by Architgoel4** [comment]
Hi @JKMarkowski please check this:  [stackblitz](https://angular-6nruhk-js1479.stackblitz.io)
https://stackblitz.com/edit/angular-6nruhk-js1479?file=src/app/RootShadow.component.ts

The resize icon still shows up, but open the console and try to resize the dialog manually.

**Comment by InnaAtanasova** [comment]
1 day
