### ISSUE TITLE
Bug. Core unit tests are failing in the FireFox 81, on Win 10 (DatetimePickerComponent, WizardComponent)

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#3621]
#### Is this a bug, enhancement, or feature request?
Bug.
#### Briefly describe your proposal.

Core. 3 unit tests are failing in the FireFox 81 on Win 10.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular CLI: 10.0.5
Fundamental Library: 0.23.0-rc.7
#### If this is a bug, please provide steps for reproducing it.
To reproduce using sauce labs: checkout https://github.com/AntonOlkhovskyi/fundamental-ngx/tree/feature/setup-saucelabs-integration
In the package.json update test:core:saucelabs with
SAUCE_USERNAME='YOU_SAUCE_USERNAME' SAUCE_ACCESS_KEY='YOUR_SAUCE_ACCESS_KEY'
Make sure it is bind to the EU Central 1 data center.
In karma.conf-ci.js comment all but sl_firefox_win browsers in the customLaunchers obj.
run test:core:saucelabs npm script
#### Please provide relevant source code if applicable.
TOTAL: 3 FAILED, 964 SUCCESS

1) should not update input with invalid time
     DatetimePickerComponent
     Expected false to equal true.

2) should stick to last valid, on invalid string.
     DatetimePickerComponent
     Expected false to be truthy.

3) should handle resize - screen getting smaller
     WizardComponent
     Expected false to be truthy.

**Comment by droshev** [comment]
@AntonOlkhovskyi can we bring this setup in the main repo?

**Comment by Seamoo13** [comment]
not running unit tests on FF anymore
