### ISSUE TITLE
Formatted text: RTL mode UI is not proper

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3628]
Description: RTL mode UI is not proper

Expected: As per the RTL UI should be proper

screenshot: 

![image](https://user-images.githubusercontent.com/32538291/95957971-117acb80-0e1e-11eb-90e1-266f5eb3c0f9.png)

Expected: 
![image](https://user-images.githubusercontent.com/32538291/95957987-1770ac80-0e1e-11eb-8a02-99ba90df4496.png)

**Comment by mykolavorobiov** [comment]
@puru-hk 
Could you please clarify the issue
With RTL mode
![image](https://user-images.githubusercontent.com/38053194/95974199-54886f00-0e1d-11eb-9897-b92a4360a1d0.png)
Without
![image](https://user-images.githubusercontent.com/38053194/95974282-73870100-0e1d-11eb-92fd-7ccbf4ec5a16.png)
