### ISSUE TITLE
Bug: Menu Within Scrolling Container is scrolling outside of container.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3635]
#### Briefly describe your proposal.
On Platform Component when browser window is less than 1100px, the Menu Within Scrolling Container is scrolling outside of container.
#### If this is a bug, please provide steps for reproducing it.
Go to https://sap.github.io/fundamental-ngx/#/platform/menu
Scroll down to Menu Within Scrolling Container
Resize browser to 1100px or less. Scroll up or down within container. See error
![image](https://user-images.githubusercontent.com/71797052/96170762-dd181580-0ed8-11eb-8484-6cb4314dfff4.png)
![image](https://user-images.githubusercontent.com/71797052/96170800-eacd9b00-0ed8-11eb-8c6b-23490d183d5e.png)

**Comment by kavya-b** [comment]
This example makes use of some of [Angular CDK's packages](https://material.angular.io/cdk/overlay/overview), particularly the Overlay and CDKScrollable ones. We could reproduce this issue in their official documented example as well by making the container scrollable and scrolling up/down:
![2020-11-06_19-07-51 (1)](https://user-images.githubusercontent.com/53509521/98372583-005f5c00-2064-11eb-9cd1-8dbcdfe66ed2.gif)

**Comment by xandrio** [comment]
@pierrom  @skocharian Hi, what should we decide here?
we have reference to the https://material.angular.io/cdk/overlay/overview issue.
Should we try to make some workaround here? or close ticket?
We already made some discussion with @dimamarksman but didn't reach some decision.
Need help.

**Comment by dimamarksman** [comment]
I wouldn't consider it an issue.
The example clearly says:

> Menus are designed to reposition themselves upon scroll of the page or within a scrollable container. However, In order to accomplish this the Menu/MenuTrigger system is reliant on the CDK Scrolling package
> 
> For containers that are scrollable (e.g. via the CSS overflow: scroll property), the user needs to add the cdk-scrollable (or cdkScrollable) directive to that container, and import the CDK ScrollingModule.

So if it's needed to reposition opened menu we should use `cdkScrollable` directive.

The issue might appear if the user wants to disable the page scroll at all if any menu is opened or to close the menu once the user starts scrolling a page. I don't see such options in the current implementation (`angular/cdk` which we are using [offers such ones](https://material.angular.io/cdk/overlay/api#ScrollStrategyOptions)).

So if we do need to have such options we should create a separate issue (as an enhancement) to add it.

If we do not need it I would suggest closing this issue.

@droshev @InnaAtanasova please share your thoughts

**Comment by pierrom** [comment]
Point taken and makes sense. From UX perspective, user should not be surprised, or see it as a mistake or a defective behavior. Curious to know everyone's thoughts of point of view. Thanks

**Comment by pierrom** [comment]
Verified and closed.
