### ISSUE TITLE
Style issue: Cascading Menu side-to-side overlap not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3637]
**Describe the bug**
On Core and Platform components: Cascading Menu side-to-side overlap should be 4px.

> Is this issue related to a specific component? Menu (Cascading sub menu)

> What version of the Fundamental Library Styles are you using? v0.22.0

**To Reproduce**
1. Go to https://sap.github.io/fundamental-ngx/#/core/menu
2. Scroll down to Menu (with submenu)
3. Click on button with submenu. See error

**Expected behavior**
There should be more overlap as specified on Visual Core
![image](https://user-images.githubusercontent.com/71797052/96174636-71d14200-0ede-11eb-8ebd-e93ecae1ac74.png)

**Screenshots** of Inspect of NGX
![image](https://user-images.githubusercontent.com/71797052/96174733-94635b00-0ede-11eb-954c-8397dbf892a2.png)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome, Firefox, Safari

**Additional context**
**Just FYI** - the cascading sub menu **overlap on RTL is correct** - however.
![image](https://user-images.githubusercontent.com/71797052/96174793-b230c000-0ede-11eb-9ebe-8bb42ff60a0f.png)

**Comment by InnaAtanasova** [comment]
0.5day estimation

**Comment by mykolavorobiov** [comment]
PR with fix - https://github.com/SAP/fundamental-ngx/pull/4189
