### ISSUE TITLE
Defect Hunting Sprint 48 - Denoland

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3641]
Defect Hunting - NGX Core - Oct 17, 2020

- [x] Avatar with background image - https://github.com/SAP/fundamental-ngx/pull/3666
Before [link](https://5f355f63718e9200075585e1--fundamental-ngx.netlify.app/#/core/avatar#avatar-background-image)
<img width="577" alt="Screen Shot 2020-10-17 at 9 52 55 AM" src="https://user-images.githubusercontent.com/4380815/96338816-918f7400-105e-11eb-9b8a-b61a4511da6c.png">
Now
<img width="585" alt="Screen Shot 2020-10-17 at 9 53 30 AM" src="https://user-images.githubusercontent.com/4380815/96338830-a23fea00-105e-11eb-9816-a889400df11c.png">
also reproducible in the Bar examples with Avatar [here](https://fundamental-ngx.netlify.app/#/core/bar#bar-default)

**Comment by salarenko** [comment]
All of the issues found on Chrome, v.0.23.0 rc-21

- [ ] Small inconsistence in File Uploader documentation. Once "Selected Files", once "Files Selected". We could also update the examples to use OnPush strategy and static string bindings.
- [ ] Timer component scrolls itself on init to have proper value selected. I guess desired behavior is not having the animation on init.
![DATE-TIME-animation](https://user-images.githubusercontent.com/17496353/96589559-420ea980-12e5-11eb-888c-76bc0e936144.gif)
- [ ] Improve "Formatted text" component documentation
- [ ] Improve typing to get rid of casting in Message Toast
![image](https://user-images.githubusercontent.com/17496353/96591025-0c6ac000-12e7-11eb-80a3-e9a8560dec96.png)

- [ ] Compact Multi-Input list elements height
![image](https://user-images.githubusercontent.com/17496353/96591133-37551400-12e7-11eb-9a95-6fa991e5b423.png)

- [ ] Select all in mobile Multi-Input should be a toggle button
![image](https://user-images.githubusercontent.com/17496353/96591245-5a7fc380-12e7-11eb-8387-14e10f399882.png)

- [ ] Cannot select Multi Input list option with "Space" key

- [ ] Multi Input with custom filter throws an error after it has been opened.
![multi-input-errror](https://user-images.githubusercontent.com/17496353/96594593-168ebd80-12eb-11eb-8aeb-0b908a439adf.gif)

- [ ] Popover inside the Dialog
![image](https://user-images.githubusercontent.com/17496353/96601878-b9970580-12f2-11eb-9c84-a954476b8f43.png)

- [ ] Segmented button stays always focused in the "checked" state 
![image](https://user-images.githubusercontent.com/17496353/96602143-fd8a0a80-12f2-11eb-917f-705eb6c69caf.png)

- [ ] Improve Side Navigation example
![image](https://user-images.githubusercontent.com/17496353/96602559-6ffaea80-12f3-11eb-9144-cbd4c1a8fccc.png)

- [ ] Improve Split Button examples
![image](https://user-images.githubusercontent.com/17496353/96602929-d54edb80-12f3-11eb-99ba-894299427a07.png)
![image](https://user-images.githubusercontent.com/17496353/96603000-e4358e00-12f3-11eb-904d-2ab1de7a97ec.png)

- [ ] Table search example is also matching by object keys not only the values
![image](https://user-images.githubusercontent.com/17496353/96603507-5dcd7c00-12f4-11eb-83f6-c492f054451c.png)

- [ ] Table having some animation on link color?
![table-animation](https://user-images.githubusercontent.com/17496353/96605249-41324380-12f6-11eb-8056-97573559ad5c.gif)

- [ ] Checkbox in the table Table in condensed mode has too wide focus
![image](https://user-images.githubusercontent.com/17496353/96603849-b866d800-12f4-11eb-8d03-4daa898d1b85.png)

- [ ] Time having some performance issues (it takes time to switch between `hh:mm:ss`)
![time-performance](https://user-images.githubusercontent.com/17496353/96605190-2f50a080-12f6-11eb-978a-1fcf6ed4aa95.gif)

**Comment by mikerodonnell89** [comment]
Bar images not loading

![Screen Shot 2020-10-20 at 9 07 37 AM](https://user-images.githubusercontent.com/2471874/96605712-c34d4880-12b3-11eb-956d-524253daf331.png)

**Comment by mikerodonnell89** [comment]
add some padding here

![Screen Shot 2020-10-20 at 9 11 08 AM](https://user-images.githubusercontent.com/2471874/96606154-322aa180-12b4-11eb-8cbb-70c52a191994.png)

**Comment by mikerodonnell89** [comment]
Combobox - typing some string and pressing "enter" should select the autocompleted value, remove text selection and move the cursor to the end of the string.  Currently the autocompleted value is selected but the text selection stays

**Comment by mikerodonnell89** [comment]
Why is there padding here

![Screen Shot 2020-10-20 at 9 42 17 AM](https://user-images.githubusercontent.com/2471874/96610170-90598380-12b8-11eb-9b80-76c24b990fdd.png)

**Comment by mikerodonnell89** [comment]
Should list items be clickable with space/enter key?

**Comment by mikerodonnell89** [comment]
Shellbar docs page throws "ExpressionChangedAfterItHasBeenCheckedError"

**Comment by mikerodonnell89** [comment]
Table sort/filter example - trying to click the filter input moves focus to the whole list item

![filterfocus](https://user-images.githubusercontent.com/2471874/96614394-5179fc80-12bd-11eb-8766-726bbd2afbb4.gif)

**Comment by mikerodonnell89** [comment]
Toolbar docs throws console error

**Comment by JKMarkowski** [comment]
- [ ] Wizard - IE11:
![image](https://user-images.githubusercontent.com/26483208/96706648-2368eb00-1397-11eb-8b02-dd67582c51f9.png)

- [ ] Action Bar / Breacrump overflow - IE11 - blink on open
![blinkonactionbar](https://user-images.githubusercontent.com/26483208/96706723-3d0a3280-1397-11eb-8b5c-7a40d4e09074.gif)

- [ ] All browsers - disabled button can be clicked, because of increased offset
![button123](https://user-images.githubusercontent.com/26483208/96706793-557a4d00-1397-11eb-9b2e-b8f096d46e0e.gif)
