### ISSUE TITLE
Avatar: (Core) displays net::ERR_ADDRESS_UNREACHABLE error in console

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#3654]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

On page load avatar component shows below error in console.

GET 'image path' net::ERR_ADDRESS_UNREACHABLE

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
10

#### If this is a bug, please provide steps for reproducing it.
In fundament-ngx/core click on the avatar component and check the console.

<img width="1389" alt="2020-10-20_20-19-47" src="https://user-images.githubusercontent.com/53487468/96603758-f292a280-1311-11eb-8d6a-6732c61c2e07.png">

**Comment by droshev** [comment]
I think the issue has been addressed
