### ISSUE TITLE
Shell-bar: enhanced responsive behavior

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#366]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

Currently the shellbar automatically collapses all collapsible shellbar actions when window.innerWidth < 1024.  It should fold items into the overflow list one by one as the window width shrinks.

Should also demonstrate how to add custom shellbar actions (buttons, etc) to the shellbar

**Comment by droshev** [comment]
@mikerodonnell89 to push his latest changes

**Comment by mikerodonnell89** [comment]
https://github.com/SAP/fundamental-ngx/tree/enhancement/%23366-shellbar-collapse-actions-4

^removes few lines of unused code @MattL75
