### ISSUE TITLE
Filter not accessible in Table example

### ISSUE THREAD

**Issue by Architgoel4** [SAP/fundamental-ngx#3665]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Filter input in Table example cannot be properly interacted with. There is now way to focus and enter the value.

![image](https://user-images.githubusercontent.com/17496353/96840176-6637cb00-144a-11eb-9c92-ec7132a651ed.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.23.0.rc-25

**Comment by salarenko** [comment]
![image](https://user-images.githubusercontent.com/17496353/96840176-6637cb00-144a-11eb-9c92-ec7132a651ed.png)

**Comment by salarenko** [comment]
@Architgoel4 I've fixed the issue description for you, but for the next time please try to properly document the problem. Anyway thanks for reporting 👍

**Comment by droshev** [comment]
@salarenko is this fixed? if so, can we close the issue?
