### ISSUE TITLE
Object List Item: Selected item is not showing properly in Edge browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3672]
Description: Selected item is not showing properly in Edge browser

Windows machine 
Edge browser

Expected: Selected item should show properly

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/96880071-61026c80-149a-11eb-9216-43175b4e3d27.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/96880161-7b3c4a80-149a-11eb-9d4d-f52db8721670.png)

**Comment by sKudum** [comment]
Closing it, as it is not reproducible by Puru in edge again.(after discussion)
