### ISSUE TITLE
avatar: Images are not loading in IE browser 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3673]
Description:   Images are not loading in IE browser
Window Machine 
IE browser 

Expected: Images should display properly 

Screenshot

![image](https://user-images.githubusercontent.com/32538291/96880496-d8380080-149a-11eb-9775-de6d6b9074ef.png)
![image](https://user-images.githubusercontent.com/32538291/96885151-f48a6c00-149f-11eb-9a44-a01120c6b307.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/96880544-e9810d00-149a-11eb-9a80-08586e7105fc.png)

**Comment by kavya-b** [comment]
verified that images load now on IE: 
<img src="https://user-images.githubusercontent.com/53509521/120265480-c97dbb80-c2bd-11eb-8a78-9429f1e9e177.png" width="300">
<img src="https://user-images.githubusercontent.com/53509521/120265591-f9c55a00-c2bd-11eb-8b1d-cd50b6aec84d.png" width="300">

@puru-hk please verify.

**Comment by puru-hk** [comment]
Tested it is working as expected. Hence it is closed.
