### ISSUE TITLE
Panel: RTL mode down arrow is showing wrong

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3674]
Description: RTL mode down arrow is showing wrong

Expected: RTL mode down arrow should show properly 

Screen shot:

![image](https://user-images.githubusercontent.com/32538291/96883201-c1df7400-149d-11eb-9524-7d23f84010cd.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/96883223-c9068200-149d-11eb-8530-4914cd9c2980.png)

**Comment by dimamarksman** [comment]
That should be fixed in scope of fundamental-styles I believe

**Comment by pierrom** [comment]
Please double check the correct arrow to display when arrow button is unclicked on RTL. The arrow should be pointing towards the text label not away from text label.
