### ISSUE TITLE
Table: (Platform) Error in table-column.component.ts during compilation

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#3676]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
On compilation, seeing the following error:
```
    ERROR in node_modules/@fundamental-ngx/platform/lib/components/table/table-column/table-column.component.d.ts:37:9 - error TS2380: 'get' and 'set' accessor must have the same type.
    
    37     set align(align: ColumnAlign);
               ~~~~~
    node_modules/@fundamental-ngx/platform/lib/components/table/table-column/table-column.component.d.ts:38:9 - error TS2380: 'get' and 'set' accessor must have the same type.
    
    38     get align(): string;
               ~~~~~
```

It looks like we just need to change the type of the getter.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@fundamental-ngx/platform 0.23.0-rc.22

#### If this is a bug, please provide steps for reproducing it.

1. Upgrade application to @fundamental-ngx/platform 0.23.0-rc.22
2. `ng serve`
3. see error

#### Please provide relevant source code if applicable.

https://github.com/SAP/fundamental-ngx/blob/2ffd49d3db4079a49709a68fcd37a77ee6dceabc/libs/platform/src/lib/components/table/table-column/table-column.component.ts#L65-L85

**Comment by olshansky** [comment]
@KevinOkamoto I've updated to `0.23.0-rc.25`
![image](https://user-images.githubusercontent.com/14160094/96895651-4b3e7880-1495-11eb-8c90-f15e23121b60.png)

And to prevent this issue I'm already wrapped get/set align by `// @ts-ignore`.
