### ISSUE TITLE
Integrating the latest version of Fundamental-styles in Fundamental-ngx

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3684]
The latest changes in Fundamental-styles (breaking changes, new components, etc.) need to be reflected in the implementation libraries as soon as possible. While it's not always possible this to be done in one sprint, one of the main focuses should be making sure  Fundamental-ngx is up to date with the  Fundamental-styles and that temporary fixes are really temporary and not long-term solutions (esp when it comes to bringing old styling in fund-ngx). 

N.B. This issue is considered an Epic since it's implementation might be spread across different sprints.

**Comment by JKMarkowski** [comment]
TODO:
- Remove card header non-interractive styles, https://github.com/SAP/fundamental-styles/pull/2113 - Can be done after merging https://github.com/SAP/fundamental-ngx/pull/4716
- Introduce status indicator component - https://github.com/SAP/fundamental-styles/pull/2072
- Introduce text component - https://github.com/SAP/fundamental-styles/pull/2084/files
- Introduce avatar group - https://github.com/SAP/fundamental-styles/pull/2066
