### ISSUE TITLE
Defect Hunting Sprint 49 - Denoland

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3685]
List below the issues found during the defect hunting that need to be addressed before the release at the end of the sprint.

**Comment by salarenko** [comment]
- [ ] List with filtering and removable elements. Remove some elements, try filtering and removed elements appear on the list again.
![list-filter-remove](https://user-images.githubusercontent.com/17496353/97977966-3fc04b00-1dcd-11eb-90be-e946910ae3bf.gif)

- [ ] This is rather a proposition than an issue. Shouldn't all module imports be placed right under the page title than under component description?
![image](https://user-images.githubusercontent.com/17496353/97978134-6d0cf900-1dcd-11eb-89ad-6b198e9c8dfe.png)

- [ ] Custom docs styles overriding compact MultiInput
![image](https://user-images.githubusercontent.com/17496353/97978339-bbba9300-1dcd-11eb-8e11-f61b187866f3.png)

- [ ] Input looks like that in toolbar (probably incorrect)
![image](https://user-images.githubusercontent.com/17496353/97981543-be6bb700-1dd2-11eb-9f39-ab4c1cc1b7ba.png)

- [ ] Cannot open Action Sheet

- [ ] Messsage Strip layout is broken
![image](https://user-images.githubusercontent.com/17496353/97983487-aa758480-1dd5-11eb-874e-44d6f6f4a9a2.png)\

- [ ] No range selection indication on hover
![date-range](https://user-images.githubusercontent.com/17496353/97984236-c75e8780-1dd6-11eb-92a1-d45cd30bfcb0.gif)

- [ ] Select max height example not working
![image](https://user-images.githubusercontent.com/17496353/97984703-68e5d900-1dd7-11eb-952b-ed52fdb94f5c.png)

**Comment by katekozlowska** [comment]
Chrome:

[ ] drag&drop does not work when it's enabled (steps to reproduce: disable d&d, then enable again, try to drag&drop)
<img width="1028" alt="Screen Shot 2020-11-03 at 14 06 48" src="https://user-images.githubusercontent.com/7014311/97989019-34295000-1dde-11eb-8c73-ed7830d102ab.png">
[ ] would be nice to include 'only icon' example
<img width="878" alt="Screen Shot 2020-11-03 at 13 55 38" src="https://user-images.githubusercontent.com/7014311/97989053-42776c00-1dde-11eb-945e-e34e5509e783.png">

**Comment by JKMarkowski** [comment]
Stackblitz - missing hammer.js
![image](https://user-images.githubusercontent.com/26483208/97999433-98064580-1deb-11eb-877a-018915cf8733.png)

**Comment by InnaAtanasova** [comment]
- [ ] Carousel error message page. I don't think the navigation buttons should be displayed in case of error. 
Fund-ngx:
<img width="1201" alt="Screen Shot 2020-11-03 at 5 18 11 PM" src="https://user-images.githubusercontent.com/39598672/98046719-b6267280-1df8-11eb-806f-eb8a6ce93d87.png">
Specs:
<img width="747" alt="Screen Shot 2020-11-03 at 5 18 20 PM" src="https://user-images.githubusercontent.com/39598672/98046743-bd4d8080-1df8-11eb-9325-af87b878a8b6.png">

- [ ] Date Picker in Reactive Form with a Range of Dates - second date should not have `...`
<img width="1229" alt="Screen Shot 2020-11-03 at 5 20 53 PM" src="https://user-images.githubusercontent.com/39598672/98046913-0a315700-1df9-11eb-8405-9442564a4eb8.png">

- [ ] Popover body - the list is cutting the rounded corners
<img width="413" alt="Screen Shot 2020-11-03 at 5 29 27 PM" src="https://user-images.githubusercontent.com/39598672/98047622-3d281a80-1dfa-11eb-9b91-aa1438b59e15.png">

- [ ] Toolbar - overflow menu
<img width="803" alt="Screen Shot 2020-11-03 at 5 35 08 PM" src="https://user-images.githubusercontent.com/39598672/98048059-00a8ee80-1dfb-11eb-96f1-20135432a6f3.png">
<img width="1356" alt="Screen Shot 2020-11-03 at 5 34 55 PM" src="https://user-images.githubusercontent.com/39598672/98048068-030b4880-1dfb-11eb-89a0-991969809bd1.png">

**Comment by kavya-b** [comment]
On the latest netlify link, opening the datetime picker and date picker and scrolling down while the popover is open looks off:
datetime picker:
![image](https://user-images.githubusercontent.com/53509521/98197034-b3886200-1f4b-11eb-8687-ac781b24a6a9.png)
date picker:
![image](https://user-images.githubusercontent.com/53509521/98197503-f0a12400-1f4c-11eb-86f0-65406428ff5f.png)

**Comment by Betrozov** [comment]
bug: (platform) display list - all navigation items can be active it the same time https://github.com/SAP/fundamental-ngx/issues/3758
