### ISSUE TITLE
Time component issues

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3695]
- [x] Timer component scrolls itself on init to have proper value selected. I guess desired behavior is not having the animation on init.
![DATE-TIME-animation](https://user-images.githubusercontent.com/17496353/96589559-420ea980-12e5-11eb-888c-76bc0e936144.gif)

- [ ] Time having some performance issues (it takes time to switch between `hh:mm:ss`)
![time-performance](https://user-images.githubusercontent.com/17496353/96605190-2f50a080-12f6-11eb-978a-1fcf6ed4aa95.gif)

**Comment by mikerodonnell89** [comment]
> * [x]  Timer component scrolls itself on init to have proper value selected. I guess desired behavior is not having the animation on init.
>   ![DATE-TIME-animation](https://user-images.githubusercontent.com/17496353/96589559-420ea980-12e5-11eb-888c-76bc0e936144.gif)
> * [ ]  Time having some performance issues (it takes time to switch between `hh:mm:ss`)
>   ![time-performance](https://user-images.githubusercontent.com/17496353/96605190-2f50a080-12f6-11eb-978a-1fcf6ed4aa95.gif)

@InnaAtanasova cannot recreate the performance issue opening a new browser window and clicking around the time options for a while - perhaps a leak started elsewhere?
