### ISSUE TITLE
Bug: Split Menu Button dropdown select missing selected state

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3709]
#### Briefly describe your proposal.
Split Menu Button dropdown only show Hover but not Selected state (light blue BG with dark blue line)
#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/split-menu-button
Scroll down to: Split Menu Buttons Behavior
Click: Default behavior
See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/97648848-0aa1aa80-1a13-11eb-9d28-4cfd9fb01cd1.png)

**Comment by droshev** [comment]
@manjunathanagaraj can you distribute the issue?

**Comment by droshev** [comment]
@pierrom i don't think there is a selection for split menu button though. Where did you get the design for it?

**Comment by pierrom** [comment]
I don't have a design for it, but basing it on a consistent behavior for all dropdown menu to have a selected state, similar to say - Cascading menu dropdown? Thanks for your inquiry.
![image](https://user-images.githubusercontent.com/71797052/97936186-a0994600-1d2f-11eb-8565-07aeccb55684.png)

**Comment by droshev** [comment]
@jessmetivier would you mind double checking with the designers?

**Comment by daisy-yovcheva** [comment]
@droshev Yes. This is correct.
Here is a reference link: https://wiki.ariba.com/pages/viewpage.action?pageId=97363748

**Comment by pierrom** [comment]
Thank you - @Yovcheva-Peykova, Daisy<mailto:DL_555307857BCF849014000004@exchange.sap.corp> and Team for following up.

**Comment by droshev** [comment]
I couldn't find in Fiori 3 such requirement

**Comment by daisy-yovcheva** [comment]
@droshev,

Here is the requirement in Fiori: https://ux.wdf.sap.corp/fiori-design-web/button/#behavior-and-interaction
