### ISSUE TITLE
Add and implement a "copy" button in the playground code snippets

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#371]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
In the playground we have code snippets. It would be great if we add a button on top that copies the code in the clipboard.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7.1, fundamental-ngx beta 25

**Comment by InnaAtanasova** [comment]
> #### Is this a bug, enhancement, or feature request?
> enhancement
> 
> #### Briefly describe your proposal.
> In the playground we have code snippets. It would be great if we add a button on top that copies the code in the clipboard.
> 
> #### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
> angular 7.1, fundamental-ngx beta 25

Agreed! This is a nice feature to have.
