### ISSUE TITLE
Sync tsConfig between projects

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3710]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
`Core` and `Platform` have different ts Config configuration

Accourding to the angular docs it should be:

```
 "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
```
https://angular.io/guide/typescript-configuration
https://angular.io/guide/migration-update-module-and-target-compiler-options

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Master

**Comment by manjunathanagaraj** [comment]
@droshev , @fkolar , i am not the right person to say that the above mentioned configuration settings are good enough. It need not be similar for core and platform, right?
@droshev , please share your inputs here. 
@fkolar , what should be our criteria to consider configurations for platform? Should we consider the deployment environments of our application teams ? I think they all should base their code to alteast Angular 8, right? Is that good enough information to arrive at values for target, module, lib,etc?

**Comment by fkolar** [comment]
@manjunathanagaraj I have pasted configuration what it shoudl be on both, it just needs to be executed and assigned this is why I put you in. .

**Comment by droshev** [comment]
@JKMarkowski @salarenko can you touch base with @fkolar and align what we need to do?
