### ISSUE TITLE
Platform BaseInput is not exported

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3711]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

The `libs/platform/src/lib/components/form/base.input.ts` is not exported. it should be added to the `libs/platform/src/lib/components/form/public_api.ts` 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

master

**Comment by manjunathanagaraj** [comment]
PR #3724 raised for Datetime picker has this issue already addressed. Once this gets merged, this issue will get closed.

**Comment by kavya-b** [comment]
fixed with #3802
