### ISSUE TITLE
Shellbar extra actions is getting placed near search

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#3721]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Any extra actions are getting placed near to the search as shown below.

<img width="317" alt="2020-11-02_12-23-41" src="https://user-images.githubusercontent.com/53487468/97838605-9020a580-1d06-11eb-83a4-6f84e8887c1c.png">

It should be placed as other action icons are placed.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
10

#### If this is a bug, please provide steps for reproducing it.
bug

**Comment by droshev** [comment]
@sKudum can you share the code?

**Comment by sKudum** [comment]
> @sKudum can you share the code?

<img width="1101" alt="2020-11-03_09-51-26" src="https://user-images.githubusercontent.com/53487468/97949604-29f55a80-1dba-11eb-870a-cb1c21affc94.png">
