### ISSUE TITLE
shellbar: notification badge is missing in the overflow menu

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#373]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
- the badges of the additional actions should be there in both scenarios - in the shellbar and when they are part of the overflow menu
- the design of the badges has changed -  [Issue opened in Fundamental-styles](https://github.com/SAP/fundamental-styles/issues/202)
- the text of the items in the overflow menu have to be left aligned
- this issue would require changes in `fundamental-styles`

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7.1, fundamental-ngx 25 beta

#### Is there anything else we should know?
See the attachements
<img width="314" alt="screen shot 2018-12-25 at 7 37 05 pm" src="https://user-images.githubusercontent.com/4380815/50427793-35060800-087e-11e9-976f-ecdfed366bbf.png">
<img width="243" alt="screen shot 2018-12-25 at 7 37 15 pm" src="https://user-images.githubusercontent.com/4380815/50427794-35060800-087e-11e9-8242-8cc4e1e2ab44.png">
<img width="237" alt="screen shot 2018-12-25 at 7 46 39 pm" src="https://user-images.githubusercontent.com/4380815/50427795-359e9e80-087e-11e9-9828-54d6f97acfb9.png">

**Comment by mikerodonnell89** [comment]
Blocked by https://github.com/SAP/fundamental/issues/1137

**Comment by mikerodonnell89** [comment]
@saad-mo @eboyer are there classes available for this?  I used fd-counter and fd-counter--notification and it looks like this: 
![screen shot 2019-02-12 at 4 46 02 pm](https://user-images.githubusercontent.com/2471874/52675983-c3ddeb00-2ee5-11e9-942f-17f171acdaf6.png)

**Comment by droshev** [comment]
@LeoT7508 do we have design for the badges in the shell-bar and when they are part of the overflow menu?

**Comment by LeoT7508** [comment]
@droshev 

We do not, this was never a requirement for us so we never explored it.

**Comment by droshev** [comment]
@LeoT7508 do you think we should address it as we have some implementation which doesn't look final?

**Comment by LeoT7508** [comment]
@droshev 

If this is a hight priority that a lot of teams are asking for then sure, if not then I think we should focus on updating and finishing what exists now. It doesn't make sense to add something that no-one is using vs. working on components that teams need now.

**Comment by InnaAtanasova** [comment]
> Blocked by [SAP/fundamental#1137](https://github.com/SAP/fundamental/issues/1137)

Fixed [here](https://github.com/SAP/fundamental/pull/1146/files)

**Comment by JKMarkowski** [comment]
Will be fixed in: https://github.com/SAP/fundamental-ngx/issues/1581
