### ISSUE TITLE
bug: (platform) menu - focus is missing for avatar menu

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3734]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

One of the avatar menu buttons is skipped on tab navigation and focus state is not shown

#### If this is a bug, please provide steps for reproducing it.

1. go to https://fundamental-ngx.netlify.app/#/platform/menu
2. look at the `Menu with Horizontal Positioning` examples
3. use tab key to navigate through all options

![Peek 2020-11-03 16-17](https://user-images.githubusercontent.com/47522152/97996608-a7d45880-1df0-11eb-8778-4a0862c5e48b.gif)

**Comment by AntonOlkhovskyi** [comment]
Env: FF 83 (Mac, Win)
