### ISSUE TITLE
Missing features: Dynamic Page Layout: The optional header content & Flexible column layout 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3744]
#### Is this a bug, enhancement, or feature request?
Feature request, Enhancement

#### Briefly describe your proposal.

**1 Feature** 
-The optional header content located below the header title is missing. 
Reference link:  https://ux.wdf.sap.corp/fiori-design-web/dynamic-page-layout/#header-content

**2 Feature**
- Combining the dynamic page with the flexible column layout is missing
https://ux.wdf.sap.corp/fiori-design-web/dynamic-page-layout/#combining-the-dynamic-page-with-the-flexible-column-layout

**Comment by kavya-b** [comment]
Hi @daisy-yovcheva ,
1. The header content is present, if you click on the down/up arrow button or click on the title area, the header content will be visible: 
![image](https://user-images.githubusercontent.com/53509521/98197711-58576f00-1f4d-11eb-8a96-2c2933a13d01.png)

2. Flexible column layout is not implemented in styles or library, because of this, this feature is missing.

**Comment by daisy-yovcheva** [comment]
@kavya-b ,

Yes, there is an example with optional header content, but it is only text.
It's very popular to use the following example with 3, 4 or more attributes:
![Screen Shot 2020-11-04 at 8 42 00 PM](https://user-images.githubusercontent.com/72403541/98199165-449f0f00-1f33-11eb-9ce6-60d30e42d031.png)

![Screen Shot 2020-11-04 at 8 41 30 PM](https://user-images.githubusercontent.com/72403541/98199090-21745f80-1f33-11eb-802a-277561ec5260.png)

Regarding the Dynamic page with a flexible column layout, it should be available based on the schedule that Manav sent to us. That's why I thought is missing. 
![Screen Shot 2020-11-04 at 8 54 06 PM](https://user-images.githubusercontent.com/72403541/98199485-e58dca00-1f33-11eb-9df3-6455d3e6019e.png)

Thanks!

**Comment by kavya-b** [comment]
> @kavya-b ,
> 
> Yes, there is an example with optional header content, but it is only text.
> It's very popular to use the following example with 3, 4 or more attributes:
> ![Screen Shot 2020-11-04 at 8 42 00 PM](https://user-images.githubusercontent.com/72403541/98199165-449f0f00-1f33-11eb-9ce6-60d30e42d031.png)
> 
> ![Screen Shot 2020-11-04 at 8 41 30 PM](https://user-images.githubusercontent.com/72403541/98199090-21745f80-1f33-11eb-802a-277561ec5260.png)

I understand. However, this seems more a part of Object Page than Dynamic Page- https://experience.sap.com/fiori-design-web/object-page/#header-content-optional which talks about several types of information that can be part of the header, each of which have styles that need to be implemented: 
![image](https://user-images.githubusercontent.com/53509521/98668012-432b7780-2375-11eb-935b-f21a60f620e1.png)

The visual spec for Object Page only came up few days back and has not been worked on yet. 
This will be worked on when the required styles are implemented as part of Object Page.  
> 
> Regarding the Dynamic page with a flexible column layout, it should be available based on the schedule that Manav sent to us. That's why I thought is missing.
> ![Screen Shot 2020-11-04 at 8 54 06 PM](https://user-images.githubusercontent.com/72403541/98199485-e58dca00-1f33-11eb-9df3-6455d3e6019e.png)
> 
> Thanks!

Not sure of this, maybe @manjunathanagaraj can help with clarifying; flexible column layout is currently not implemented but when it is, Dynamic Page is capable of being used with it.

**Comment by manjunathanagaraj** [comment]
This is dependent on Facets, which we have planned post December. Once facets are developed, this issue can be taken up.
