### ISSUE TITLE
Bug: Responsive design-behavior for Mobile is not aligned with Visual core

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3745]
#### Is this a bug, enhancement, or feature request?
Bug, and enhancement

#### Briefly describe your proposal.

** Issue** 
Looking at the "Page Responsive Behavior" section - It's not aligned with Visual core breaking points and visuals for Mobile. It doesn't work when I shrank the screen.
Issue: 
![Screen Shot 2020-11-04 at 3 28 29 PM](https://user-images.githubusercontent.com/72403541/98178912-49010300-1f06-11eb-9b42-42fdf6e55347.png)

Please refer to Visual core: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2039387288
![DynamicPage_SizeSAnatomy](https://user-images.githubusercontent.com/72403541/98174079-ece5b100-1efc-11eb-9f0a-5b317cb1d5cb.png)

**Comment by kavya-b** [comment]
Hi @daisy-yovcheva , as mentioned in the issue https://github.com/SAP/fundamental-ngx/issues/3474, currently complete responsiveness and mobile mode is not supported in dynamic page. This will be hopefully taken up in the next phase. An issue for tracking this is also already created #3473 . The Page Responsiveness example only tries to show that pagee paddings will be taken care of when `size` is specified by the user.

**Comment by daisy-yovcheva** [comment]
Hi @kavya-b, Thanks for your explanation.

**Comment by puru-hk** [comment]
This issue is an duplicated of #3473. Hence it is closed
