### ISSUE TITLE
Missing features: Table phase 1 component refers to Grid table

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3746]
#### Is this a bug, enhancement, or feature request?
Enhancement, or feature request

#### Briefly describe your proposal.

**NOTE:** The name of the component is wrong. By default "Table" refers to "Responsive table", not to Grid table. Can you please change the name to a "Grid table"?

**It's missing the following features:**
- [ ] A variant of an “Action column” at the end of the table. 
Ex: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2040107154#GridTable(Fiori3.0)-GridTable

- [ ] Horizontal and Vertical scrolling

- [x] The column header provides the label for the corresponding column and access to the column header menu: 
Ex: https://ux.wdf.sap.corp/fiori-design-web/grid-table/#column-header-menu

- [x] Group headers
Ex: https://ux.wdf.sap.corp/fiori-design-web/grid-table/#group1

- [ ] Resizing the columns

- [x] Freeze a column
Ex: https://ux.wdf.sap.corp/fiori-design-web/grid-table/#freeze-columns

- [ ] Drag and drop and the whole item as a drop target
Ex:https://ux.wdf.sap.corp/fiori-design-web/grid-table/#drag-and-drop

- [ ] Highlighted items
Ex: https://ux.wdf.sap.corp/fiori-design-web/grid-table/#highlight-items

- [x] Loading data
 Ex: https://ux.wdf.sap.corp/fiori-design-web/grid-table/#loading-data

**Comment by droshev** [comment]
@manjunathanagaraj is this planned?

**Comment by platon-rov** [comment]
In that component, we're providing features not only of the Grid Table (Fiori 3). 

Is that renaming won't be confusing for the customers who are looking, for example, for the analytical table or the tree table? This component also includes (or will include) all features from all that tables.

@droshev @InnaAtanasova what do you think?

**Comment by manjunathanagaraj** [comment]
We need not rename this to grid table. Because that would lead to further confusions(its not just grid table, either). We may then have to have separate implementations under the table(like we have all the variants of List). 
Currently we have one table with the flexibility to mix and match the features to fulfil the so far identified needs of the developer. Thats how we identified the features and implemented in phases.
I will talk to @daisy-yovcheva about this.
