### ISSUE TITLE
Object marker: wrong statuses of Flag and Favorite 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3749]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
"The self-explanatory statuses Flag and Favorite are always displayed as an icon.", not icon and text - Visual core 

Please remove the following examples: 
![Screen Shot 2020-11-04 at 10 02 58 PM](https://user-images.githubusercontent.com/72403541/98203805-67362580-1f3d-11eb-8f6a-6de224485d7c.png)

**Comment by puru-hk** [comment]
Tested it is working fine.

**Comment by kenykim** [comment]
@puru-hk please let @daisy-yovcheva know this issue has been review by dev team so that she can review it again whether it's been fixed or not, and also she can  change status in the Design QA timeline table
