### ISSUE TITLE
Wizard: Not aligned with Visual core when you move to the next step

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3750]
#### Is this a bug, enhancement, or feature request?
Bug, enhancement

#### Briefly describe your proposal.
 Once you go to a step 2, 3, or 4 - you should see a checkmark instead of the number.
![Screen Shot 2020-11-04 at 10 24 30 PM](https://user-images.githubusercontent.com/72403541/98205381-b7fb4d80-1f40-11eb-9a10-c85970899c0b.png)

Reference to Visual Core:
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2050488712

**Comment by droshev** [comment]
@daisy-yovcheva this is not a bug. If you see there are examples below where the passed steps don't have checkmark
