### ISSUE TITLE
Wizard: Stack group with Action sheets is missing

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3751]
#### Is this a bug, enhancement, or feature request?
Feature

#### Briefly describe your proposal.

Grouped Steps Container:
When you have multiple steps and not enough space on the screen to show all steps, you can click on the grouped container and select a step from the ActionSheet.
Example:
![Screen Shot 2020-11-04 at 10 24 57 PM](https://user-images.githubusercontent.com/72403541/98206596-d7937580-1f42-11eb-9041-271402818ec5.png)

**Comment by puru-hk** [comment]
@droshev This issue raised by Ariba design team. Could you please have a look.
