### ISSUE TITLE
Bug: Core Carousel- Navigating in reverse through arrow keys not working

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3752]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Navigating in reverse through arrow keys not working in Core carousel component.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest netlify 0.23.1-rc.22
Chrome: Version 86.0.4240.111

#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/carousel
2. Use keyboard arrow navigation to navigate through the carousel.
3. Reach the last element.
4. Press left arrow
5. Notice it doesn't navigate.

![2020-11-05_11-50-24 (1)](https://user-images.githubusercontent.com/53509521/98209473-fc004980-1f64-11eb-99b2-fe854cc91530.gif)

Expected: Left and right navigation should work properly.

**Note: works fine on IE, Firefox and Safari**

**Comment by DeepakSap14** [comment]
This is not a functionality issue.
after reaching on last item, navigation button gets disabled and there is no focus on carousel anywhere.
if we click on carousel anywhere for focus and then use arrow keys, then it works.

**Comment by kavya-b** [comment]
this behaviour should then be consistent across browsers right? The issue does not occur on other browsers.

**Comment by DeepakSap14** [comment]
Yes. I meant that while fixing, we have to look, how we can keep carousel on focus.
if carousel is in focus, then it will work.
