### ISSUE TITLE
Bug: Core Carousel- Focus looking off in Firefox and Safari browser

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3753]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
on pressing the navigation arrow buttons, the focus ring does not appear outside the button, but comes inside it momentarily.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Safari- Version 14.0 (15610.1.28.1.9, 15610)
Firefox- 81.0.2 

#### If this is a bug, please provide steps for reproducing it.

1. Go to https://fundamental-ngx.netlify.app/#/core/carousel
2. Click on the arrow button to navigate through the carousel.
3. Notice the focus ring
![2020-11-05_13-10-58 (1)](https://user-images.githubusercontent.com/53509521/98211940-d7a66c00-1f68-11eb-8aa1-52487dbbfadc.gif)

Expected: Focus ring should appear properly.

**Note: works fine in IE and Chrome.**

**Comment by DeepakSap14** [comment]
this has been fixed with PR https://github.com/SAP/fundamental-styles/pull/1866.

**Comment by DeepakSap14** [comment]
This can be closed.
