### ISSUE TITLE
Breadcrumbs: Dropdown menu is missing a line separator between the options

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3762]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The dropdown menu has a line separator between all the options.
Example:
![Screen Shot 2020-11-05 at 10 56 51 AM](https://user-images.githubusercontent.com/72403541/98284219-781c8080-1fa9-11eb-9cd5-958f5e453017.png)

**Comment by puru-hk** [comment]
Dropdown is implemented for responsiveness. Hence it is not an issue.
