### ISSUE TITLE
Message Strips: Missing an cancel button at the end of the strip

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3763]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
-It’s missing the “Cancel” button for Successful and Error message strips in all the sections.
-Looking at the section: "Message strips with Customizable width" - it's missing the warning icon.

**Comment by puru-hk** [comment]
Examples have been provided in playground. Hence it is not an issue.
