### ISSUE TITLE
Popover: Important! Using a wrong component to present popover behaviors

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3765]
#### Is this a bug, enhancement, or feature request?
Bug, Enhancement, 

**NOTE:** 
You are using a "Menu" component to present "Popover".
 Link to menu component: https://deploy-preview-3515--fundamental-ngx.netlify.app/#/core/menu

**Popover Documentation:** 
Visual core: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2033132412
Fiori:https://ux.wdf.sap.corp/fiori-design-web/popover/

#### Briefly describe your proposal.
- "Popover with Header and Footer" examples are totally wrong. Please check the Fiori documentation.

 -Popover outline border looks interrupted around the corners, check for border-color and shadows as well.

**Comment by Lokanathan-k** [comment]
On analysis:
Popover is a container component, which holds list, template, and menu's, as discussed with Daisy we need to add few more examples as the current examples has only menu list as a content, so we need to implement the some more examples as shown in the link, https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.Popover and https://ux.wdf.sap.corp/fiori-design-web/popover/

**Comment by xandrio** [comment]
@daisy-yovcheva can you take a look please on popup component examples.
https://sap.github.io/fundamental-ngx/#/core/popover

@Lokanathan-k popover page contain a lot of examples for this component, maybe you can clarify a bit what exactly should be added as examples, and for menu page or popover page?

**Comment by daisy-yovcheva** [comment]
Hi All,

Technically, all the provided examples are correct, but a little bit confusing because you use the "Menu" component inside of the "Popover" container.

How I said, Popover is a kind of container and the content can vary based on the different use cases. So it would be nice to have something like the examples below:  
![Screen Shot 2021-04-20 at 4 19 10 PM](https://user-images.githubusercontent.com/72403541/115475295-25035680-a1f4-11eb-82b8-4936aea80a39.png)

![Screen Shot 2021-04-20 at 4 02 22 PM](https://user-images.githubusercontent.com/72403541/115474203-cccb5500-a1f1-11eb-9971-83a839addc04.png)

**Comment by xandrio** [comment]
@daisy-yovcheva not clear do we talk about the same samples page - because there link to the menu component.
Link to menu component: https://deploy-preview-3515--fundamental-ngx.netlify.app/#/core/menu

But we have separated page for popover samples:
https://sap.github.io/fundamental-ngx/#/core/popover

Do we talk about same example page?
It would be nice to make short call and clarify.
