### ISSUE TITLE
Combobox: Two columns list data is not aligned properly + missing value states 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3767]
#### Is this a bug, enhancement, or feature request?
Bug, Feature request

#### Briefly describe your proposal.

-Combobox with two columns - misalignments of the options
Reference to Fiori: https://ux.wdf.sap.corp/fiori-design-web/combo-box/#twocolumn-layout

- Combobox with value states are missing - error, success, information, warning
<img width="1118" alt="Screen Shot 2020-11-05 at 10 42 59 PM" src="https://user-images.githubusercontent.com/72403541/98334764-48529480-200c-11eb-9893-d72bbc028933.png">

**Comment by daisy-yovcheva** [comment]
I still don't see the Error, Warning, and Information message below the combo box.

![image](https://user-images.githubusercontent.com/72403541/106571703-5705f600-64ec-11eb-8a01-017b573cae2d.png)

**Comment by puru-hk** [comment]
@daisy-yovcheva Error, Warning, and Information are implemented. Could you please check attached the screen shot 
![image](https://user-images.githubusercontent.com/32538291/108950943-1e8dae00-768d-11eb-86c9-21d36b61b980.png)

**Comment by daisy-yovcheva** [comment]
Hi @puru-hk,

The values States are still missing. Look at the examples below:
![Screen Shot 2021-04-28 at 3 04 30 PM](https://user-images.githubusercontent.com/72403541/116478528-0a079680-a833-11eb-8262-d1705c95074f.png)

Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/combo-box/#styles
Visual core ref: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2056528741
UI5 Demo: https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBoxValueState

Otherwise, the combo box with two columns alignment looks good.

Thanks!
