### ISSUE TITLE
shell-bar: search and notification icons are not on the right positions

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#377]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
by the specification the search should be the first action on the right side of the shell-bar and the notification action should just before the user menu.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7.1, fundamental-ngx 0.0.25 beta

#### If this is a bug, please provide steps for reproducing it.
run the following code:
```
  <fd-shellbar-actions [user]="user" [userMenu]="userMenu" [productSwitcher]="productSwitcher">
    <fd-shellbar-action
      *ngFor="let action of actions"
      [glyph]="action.glyph"
      [callback]="action.callback"
      [label]="action.label"
      [notificationCount]="action.notificationCount"
      [notificationLabel]="action.notificationLabel"
    >
    </fd-shellbar-action>
    <fd-shellbar-action [label]="'Search'">
      <fd-search-input
        [inShellbar]="true"
        [searchTerms]="searchTerms"
        [(ngModel)]="searchTerm"
        [searchFunction]="exampleSearchFunction"
      ></fd-search-input>
    </fd-shellbar-action>
  </fd-shellbar-actions>
```
<img width="307" alt="screen shot 2018-12-26 at 10 44 32 pm" src="https://user-images.githubusercontent.com/4380815/50464627-0d876c00-0960-11e9-825c-e736ae901788.png">

**Comment by mikerodonnell89** [comment]
This is not how it appears in the Fiori fundamentals docs: https://sap.github.io/fundamental/components/shellbar.html

**Comment by droshev** [comment]
@mikerodonnell89 but it is how it specified for the SAP shellbar
