### ISSUE TITLE
Fundamental-ngx 0.25.0 release (+Defect Hunting)

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3786]
All the activities related to the release of 0.25.0 version of Fundamental-ngx.
Please list of critical issues as comments below.

**Comment by InnaAtanasova** [comment]
- [ ] Action Sheet - clicking on the Action Sheet trigger focusses the first element. In the documentation we should provide an example where clicking on any of the list item triggers an event (shows alert, message box, etc to the user) and closes the menu
- [ ] Inline Help - we need to remove Inline Help before the release as part of 0.13.0 adoption. If we keep it, we need to fix this:
<img width="1240" alt="Screen Shot 2020-11-17 at 12 39 16 PM" src="https://user-images.githubusercontent.com/39598672/99426383-01995000-28d2-11eb-98ac-7db1b59f718c.png">
<img width="1275" alt="Screen Shot 2020-11-17 at 12 39 10 PM" src="https://user-images.githubusercontent.com/39598672/99426390-03631380-28d2-11eb-9513-e1b8c322cb61.png">

- [ ] Popover
<img width="1105" alt="Screen Shot 2020-11-17 at 12 41 29 PM" src="https://user-images.githubusercontent.com/39598672/99426564-41603780-28d2-11eb-8ff5-dc07646aaa77.png">
<img width="1063" alt="Screen Shot 2020-11-17 at 12 41 18 PM" src="https://user-images.githubusercontent.com/39598672/99426571-42916480-28d2-11eb-99dc-f1e6653e9ebf.png">

- [ ] Select Semantic States - the size of the messages is not correct. The size fits the content until it reaches its maximum and then the texts goes to second line
<img width="992" alt="Screen Shot 2020-11-17 at 12 43 01 PM" src="https://user-images.githubusercontent.com/39598672/99426782-969c4900-28d2-11eb-8df9-9b78669cf88e.png">
<img width="1083" alt="Screen Shot 2020-11-17 at 12 42 54 PM" src="https://user-images.githubusercontent.com/39598672/99426788-98660c80-28d2-11eb-9222-218e9f104e0b.png">

- [ ] Toolbar - Button in the overflow menu takes the width of the menu
<img width="874" alt="Screen Shot 2020-11-17 at 12 51 59 PM" src="https://user-images.githubusercontent.com/39598672/99427987-14148900-28d4-11eb-8f3e-8ee544daa1b1.png">

- [ ] ShellBar issues
1. The color of the arrow
<img width="457" alt="Screen Shot 2020-11-17 at 12 44 58 PM" src="https://user-images.githubusercontent.com/39598672/99428032-1e368780-28d4-11eb-82ae-635ae32650f2.png">

2. The focus outline
<img width="161" alt="Screen Shot 2020-11-17 at 12 44 35 PM" src="https://user-images.githubusercontent.com/39598672/99428120-38706580-28d4-11eb-9960-a148acd95029.png">
<img width="503" alt="Screen Shot 2020-11-17 at 12 55 37 PM" src="https://user-images.githubusercontent.com/39598672/99428127-3908fc00-28d4-11eb-8f4a-ec248c6a245b.png">

**Comment by JKMarkowski** [comment]
- [ ] IE11 - popover arrow missing
![image](https://user-images.githubusercontent.com/26483208/99520588-8f893f80-2993-11eb-9c67-df226e68547c.png)

**Comment by katekozlowska** [comment]
- [ ] message strip covers date picker
![Screenshot from 2020-11-18 15-01-36](https://user-images.githubusercontent.com/7014311/99540165-768e8780-29af-11eb-85ee-95c0d50dc3b3.png)
