### ISSUE TITLE
Angular Elements

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3788]
- create 2-3 components(composite ones)
- fix styling
- measure bundle sizes, performance

Time estimation: 1day

**Comment by salarenko** [comment]
### Limitations
- When components are composed in following way:
```
<app-parent>
    <app-child></app-child>
</app-parent>
```
And we want to recreate the same structure using web components:
```
<wc-parent>
    <wc-child></wc-child>
</wc-parent>
```
Unlike in first case, `wc-parent` DI tree and `wc-child` DI tree are isolated. This means that parent cannot access reference to the child using "DI based approaches" like `@ContentChild` and child cannot access parent or any dependencies provided in parent DI using injection.

However both `wc-parent` and `wc-child` DI are configured with the same module injectors (both components are declared in the same module). This means that `wc-parent` and `wc-child` have access to the same providers provided in `Module.providers` array or as `@Injectable({ provideIn: 'root' })`.

- Using components as directives

Components with "directive-like" selectors might behave broken and should rather not be used as web components.
A good example is `ButtonComponent`:
https://github.com/SAP/fundamental-ngx/blob/cb0c2d1f619e48dc29c7a29b5eb94822986c8d5d/libs/core/src/lib/button/button.component.ts#L38-L47

which according to the implementation should be used as a directive: `<button fd-button></button>`, but there is no such way after the `ButtonComponent` is transformed into the web component.

### Bundle size
Bundle size for web-component version of the `ButtonComponent`
```
chunk {} runtime.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.js (main) 237 kB [initial] [rendered]
chunk {2} polyfills.js (polyfills) 13.7 kB [initial] [rendered]
chunk {3} polyfills-es5.js (polyfills-es5) 96.6 kB [initial] [rendered]
```
