### ISSUE TITLE
List: Missing features + bug on loading more data on click

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3790]
#### Is this a bug, enhancement, or feature request?
 Bug, Feature request

#### Briefly describe your proposal.

**Bug:**
Load data on button click:
"Show more" button should be replaced with a busy indicator. We don't have to see text + busy indicator.
![Screen Shot 2020-11-09 at 1 16 11 PM](https://user-images.githubusercontent.com/72403541/98597395-a370d980-22e1-11eb-94ab-e4fd5a2f5106.png)

**Missing features:**

-Highlight items
Fiori reference: https://ux.wdf.sap.corp/fiori-design-web/list-overview/#highlight-items
-Sticky title on scroll
Fiori reference: https://ux.wdf.sap.corp/fiori-design-web/list-overview/#scroll
-Drag and drop
Fiori reference: https://ux.wdf.sap.corp/fiori-design-web/list-overview/#drag-and-drop
-List with wrapping behavior: Expanding and Collapsing, More content - Less content
Visual core reference: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2070928854

**Comment by puru-hk** [comment]
This is not a bug. It is for application team to implement way they want to.
