### ISSUE TITLE
Standard list: Missing features + Bug: object status should be aligned on the right

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3791]
#### Is this a bug, enhancement, or feature request?
Bug, Feature request?

#### Briefly describe your proposal.

**Bug:**
Object status should be aligned on the very right, not in the middle.

Missing features:
- Standard list with semantic colored information - only text and object status
Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/standard-list-item/#components

- Standard list with title and subtitle only
Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/standard-list-item/#top

-Standard list with title and status truncation 
Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Standard+List

**Comment by sKudum** [comment]
Hi Team, Its styles issue needs to be fixed in styles.


<img width="1411" alt="2020-11-23_11-54-42" src="https://user-images.githubusercontent.com/53487468/99934060-e3749980-2d82-11eb-844f-f09bc4a2fc70.png">

**Comment by sKudum** [comment]
https://github.com/SAP/fundamental-styles/issues/1906 wll address it.

**Comment by kenykim** [comment]
@pierrom

**Comment by kenykim** [comment]
@pierrom @yukioht Could you test this issue (test)?

**Comment by kenykim** [comment]
![image](https://user-images.githubusercontent.com/58018352/108020559-7a8f6d00-6fd1-11eb-8369-743ed6c98ac8.png)
Bug:
It seems the issue has not been resolved, let's reopen the issue 
@manjunathanagaraj @puru-hk could you please look into the issue again?

Based on the issue,
Object status should be aligned on the very right, not in the middle.
Thanks!

**Comment by sKudum** [comment]
Hi @kenykim ,Its styles issues and the fix is provided in styles. once the latest styles 0.16.0  included in ngx this issue will be resolved here too.

**Comment by sKudum** [comment]
Hi @kenykim ,
 Issue is fixed in latest release of [ngx](https://sap.github.io/fundamental-ngx/#/platform/standard-list-item) please have a look. attaching screens shot for your reference.
<img width="1343" alt="2021-06-01_19-22-46" src="https://user-images.githubusercontent.com/53487468/120335224-f1e1d600-c30e-11eb-9cc1-dcd37380fb4b.png">

**Comment by sKudum** [comment]
Requested design team confirmation on the same. Assigning it do design team.

**Comment by kenykim** [comment]
Hi Sushma, the fixed error looked fine. thanks!

**Comment by sKudum** [comment]
Closing it as designer ?(Kenny kim) has approved it.
