### ISSUE TITLE
Toolbar: Missing features + broken overflow menu

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3792]
#### Is this a bug, enhancement, or feature request?
Bug, Feature request

#### Briefly describe your proposal.

**Bug:**
The overflow menu looks totally broken - It should be used the "Menu" component instead.
Visual core ref: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2061501144

**Missing features:**

-Chart toolbar

-Footer toolbar

-Header toolbar

-Tree toolbar

-Inactive infobar (not clickable)

Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/toolbar-overview/#types

-Table toolbar: 
Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/table-bar/

- Title toolbar + counter + actions on the right: 
Ref:  https://wiki.wdf.sap.corp/wiki/display/visualcore/Toolbar+%28Fiori+3%29+-+Title+Toolbar

**Comment by puru-hk** [comment]
@droshev This issue has been raised by ariba design team . Could you please have a look.
