### ISSUE TITLE
Bug: Object Status Large - Misspelling on Core components

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3797]
#### Is this a bug, enhancement, or feature request? 
Bug

#### Briefly describe your proposal.
Please correct misspelling of "Critical"

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.23.0

#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://sap.github.io/fundamental-ngx/#/core/object-status
2. Scroll down to: Object Status Large Design
3. See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/98618420-09476c00-22b6-11eb-837f-26be7e5b140f.png)

**Comment by puru-hk** [comment]
Tested spelling mistake corrected.
