### ISSUE TITLE
Bug: Default Object Status on Platform components - padding is not right

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3798]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Default Object Status on Platform components -padding is not right, it's too tight - please check Visual Core. However - it's correct on RTL.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.23.0

#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://sap.github.io/fundamental-ngx/#/platform/object-status
2. Scroll down to: Default Object status
3. See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/98619121-6db6fb00-22b7-11eb-8e3a-7a2d10ce325c.png)

**Comment by Lokanathan-k** [comment]
![image](https://user-images.githubusercontent.com/53534379/99934840-318a9c80-2d85-11eb-9bcd-a305556a3faa.png)
fixed as part of defect hunting attached the screen shots.
