### ISSUE TITLE
Bug: Object Status with Text and Icon - padding is not right

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3799]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Object Status with Text and Icon - padding is not right, it's too tight, please check Visual Core, should be 4px.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.23.0

#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://sap.github.io/fundamental-ngx/#/platform/object-status
2. Scroll down to: Object status with Text and Icon
3. See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/98619616-76f49780-22b8-11eb-803d-e183292c2be6.png)

#### Is there anything else we should know?
There are 2 other padding issues on Object Status with padding issues (3 total including this one) #3800 and #3801.

**Comment by puru-hk** [comment]
Duplicate issue 3801
