### ISSUE TITLE
Bug: "Clickable Object Status" with Text and Icon - padding is not right

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3800]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
"Clickable Object Status" with Text and Icon - padding is not right, too tight, please check Visual core, should be 4px.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v.023.0

#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://sap.github.io/fundamental-ngx/#/platform/object-status
2. Scroll down to: Clickable Object Status
3. See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/98620220-b96aa400-22b9-11eb-9e41-b59f0fd4ef07.png)

#### Is there anything else we should know?
There are 2 other similar padding issues for Object Status (3 including this) #3799 and #3801.

**Comment by Lokanathan-k** [comment]
![image](https://user-images.githubusercontent.com/53534379/99934785-fdaf7700-2d84-11eb-84b2-57b952ada070.png)
fixed as part of defect hunting process and screen shot attached
