### ISSUE TITLE
Bug: Object Status "Large" with Text and Icon - padding is not right

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3801]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Object Status "Large" with Text and Icon - padding is not right, it's too tight. Please check Visual Core, should be 4px.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.23.0

#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://sap.github.io/fundamental-ngx/#/platform/object-status
2. Scroll down to: Object Status Large Design
3. See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/98620803-ccca3f00-22ba-11eb-9571-691f7d72aba9.png)

#### Is there anything else we should know?
There are 2 other padding issues similar to this (3 including this one) #3799 and #3800.

**Comment by Lokanathan-k** [comment]
<img width="1220" alt="Screenshot 2020-11-23 at 12 09 30 PM" src="https://user-images.githubusercontent.com/53534379/99934735-d0fb5f80-2d84-11eb-8a18-e9bbb0cf1b6d.png">
Fixed as part of defect hunting process screen shot attached
