### ISSUE TITLE
Fixed Card Layout: The aria-selected attribute is not allowed on this LI66.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3816]
Description: The aria-selected attribute is not allowed on this LI66.

Code Snippet: 
<li tabindex="-1" aria-selected="false" class="fd-list__item" fd-list-item="" role="listitem"><span class="fd-list__title" fd-list-title="">item 1</span></li>

Expected: Developers must use valid markup and follow the rules of the ARIA specification.

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/98772893-c8626b00-240d-11eb-9b38-78b760511260.png)

**Comment by DeepakSap14** [comment]
Hi Puru,
what is this LI66?
also please upload good quality image. on opening the image. Nothing is visible.
and from description issue is not clear.

I tried screen reader on fixed card layout, it is working expected.
