### ISSUE TITLE
Thumbnail: No speech output is conveyed when focus lands on the video as highlighted in red.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3826]
Description: No speech output is conveyed when focus lands on the video as highlighted in red.

Expected: Information about the UI element shall be conveyed when accessed.

Screenshot: 
![image](https://user-images.githubusercontent.com/32538291/98773915-e92bc000-240f-11eb-95f3-84fa8a47af0f.png)

**Comment by manu-kr** [comment]
Changes are done. need to push the changes.

**Comment by puru-hk** [comment]
Tested it is working as expected.
