### ISSUE TITLE
Popover: Popover positioning is incorrect

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#3829]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Where the placement is `left` or `right`, popover positioning looks broken. Observed in Inline Help, but it could happen in any component that uses these placement options.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
1. Go to https://sap.github.io/fundamental-ngx/#/core/inlineHelp
2. Hover over Right and Left examples in Inline Help section.
3. Observe 
![2020-11-11_11-18-50 (1)](https://user-images.githubusercontent.com/53509521/98774156-6fe09d00-2410-11eb-88d3-46e2cf30a3e8.gif)

**Comment by olshansky** [comment]
Looks fixed: 
![popover_position](https://user-images.githubusercontent.com/14160094/100861809-01d14800-349b-11eb-82b0-d0134176523d.gif)
