### ISSUE TITLE
Implement Loading Spinner

### ISSUE THREAD

**Issue by Smux** [SAP/fundamental-ngx#383]
#### Is this a bug, enhancement, or feature request?
Feature Request

#### Briefly describe your proposal.
Loading Spinner (Indicator) currently not available for NGX Fundamental.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current Version

Already implemented in fundamental:
https://sap.github.io/fundamental/components/loading-spinner.html

**Note:** 
We are currently working with fundamental ngx and are very happy with it. However, it would be great if the loading spinner would be available as an angular component. Currenty we are using it like described in the fundamental page.

**Comment by Smux** [comment]
Hey @mikerodonnell89 ,
thanks for picking up this issue so fast :)
I saw that the loading spinner with this version right now only replaces the part of the spinner, but as a developer that is using the component I would still need to bind the aria-busy property to the outside div. I would find this more comfortable to use when I would only need to bind one property on one div/component like in my draft in my previous comment. 
Just my 2 cents how I would like to use it :) Anyway great that ngx fundamental is growing so fast :)

**Comment by mikerodonnell89** [comment]
@Smux I've implemented your recommendation on this branch here: https://github.com/SAP/fundamental-ngx/tree/enhancement/%23383-loading-spinner-automatic-busy

@saadmhybris @xak @eboyer  Will it always safe to assume that the immediate parent element of the loading spinner is the element that needs to be set to busy?  I think we lose some configurability and verbosity with this implementation but, if this is the original intent of the spinner, we can merge this

**Comment by xak** [comment]
> @saadmhybris @xak @eboyer Will it always safe to assume that the immediate parent element of the loading spinner is the element that needs to be set to busy? I think we lose some configurability and verbosity with this implementation but, if this is the original intent of the spinner, we can merge this

The implementation does not require the element be an immediate parent – https://github.com/SAP/fundamental/blob/develop/dist/components/spinner.css#L49 — just that the spinner be a child. The `aria-busy` sets up the parent so that the spinner can be positioned properly.
