### ISSUE TITLE
Action List Item: There is no visible focus provided for the list items, but speech output is conveyed on navigation.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3830]
Description: There is no visible focus provided for the list items, but speech output is conveyed on navigation.

Expected: There is no visible focus provided for the list items, but speech output is conveyed on navigation.

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/98774221-930b4c80-2410-11eb-9e6a-c5112403ac08.png)

**Comment by sKudum** [comment]
In real time application focus will move to list first then on tab it will navigate to each list item. As per Fiori whole list item will not have focusing styles.Only list item will.Added messages which gives opt information during voice over.
