### ISSUE TITLE
Object List Item: There is no text alternative provided for the icons as highlighted in red.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3836]
Description: There is no text alternative provided for the icons as highlighted in red.

Expected: Meaning label/text alternative shall be provided on accessing the non-text UI elements within the application.

Screenshot:
![image](https://user-images.githubusercontent.com/32538291/98775004-34df6900-2412-11eb-8242-7ad64597e454.png)

**Comment by sKudum** [comment]
Not reproducible in the latest release. Hence closing it.
Link for reefernce:https://sap.github.io/fundamental-ngx/#/platform/object-list-item

![2020-12-09_20-11-36 (1)](https://user-images.githubusercontent.com/53487468/101644146-db8f4780-3a5a-11eb-8ed4-477cb5beb8ef.gif)
