### ISSUE TITLE
Dynamic Page: On resizing the screen to 200%, toolbar as highlighted in red overlaps the text present on the screens.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3840]
Description: On resizing the screen to 200%, toolbar as highlighted in red overlaps the text present on the screens.

Expected: All the UI’s within the screen shall be clearly visible without any truncation or overlapping in 200% resize mode.

Screenshot: 
![image](https://user-images.githubusercontent.com/32538291/98775551-5db42e00-2413-11eb-847a-291342d382f3.png)

**Comment by kavya-b** [comment]
@puru-hk fixed with #3925. Please verify.

**Comment by puru-hk** [comment]
Verified it is working fine.
