### ISSUE TITLE
Search Field: No aria-label on search input element

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3843]
Description: Table header as highlighted in red is not associated with its corresponding UI’s, when accessed.

Expected:  Corresponding label must be read out, when each & every UI is accessed.

Screenshot: 

[Header.docx](https://github.com/SAP/fundamental-ngx/files/6220217/Header.docx)

**Comment by IlyaSurmay** [comment]
highlighted text contains rows count information, it's not a table header
need more info on what's the issue here

**Comment by puru-hk** [comment]
@Sanjay-1312 Could you please check this issue. If it is not fixed. Could you please attach the proper screenshot.

**Comment by manjunathanagaraj** [comment]
@Sanjay-1312 , Image is not clear...but it appears to be of playground. The playground is just a tool for the app developers to understand how to play around with properties of the table exposed to them. Its not the actual component. As long as the examples are working fine, it should be good.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

On accessing the search input field, the table header name 'Order Line items(30),
should be conveyed to the user.
i have attached the screenshot for your reference.

Thanks and Regards
Sanjay
