### ISSUE TITLE
Playground: bound label to appropriate select.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3844]
Description: Labels given for the UI’s as highlighted in red is not read out, when corresponding UI’s are accessed.

Expected: Corresponding label must be read out, when each & every UI is accessed.

Screenshot: 

[Combo box.docx](https://github.com/SAP/fundamental-ngx/files/6220215/Combo.box.docx)

**Comment by IlyaSurmay** [comment]
these labels are part of `playground` component that's used in demo, not the table itself
need more research on that and if this issue is present on the other pages where `playground` is used, then a separate ticket should be created

**Comment by puru-hk** [comment]
@Sanjay-1312 Could you please check this issue. If it is not fixed. Could you please attach the proper screenshot.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

The issue is not fixed.
The association label must be read on accessing the Combo box.
I have attached the screenshot with speech output.
So please fix the issue.

Thanks and Regards
Sanjay
