### ISSUE TITLE
Playground: bound label to appropriate group

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3845]
Description: Group label ‘Table’ provided for the group as highlighted in red is not read out, when corresponding UI’s are accessed.

Expected: Corresponding label must be read out, when each & every UI is accessed

Screenshot:
[TAble.docx](https://github.com/SAP/fundamental-ngx/files/6220210/TAble.docx)

**Comment by IlyaSurmay** [comment]
related to #3844, same conclusions

**Comment by puru-hk** [comment]
@Sanjay-1312 Could you please check this issue. If it is not fixed. Could you please attach the proper screenshot.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

The issue is not fixed.
The header name 'Table' is not read.
I have attached the screenshot for your reference.

Thanks and Regards
Sanjay
