### ISSUE TITLE
Add body area to "action bar" or implement own page component

### ISSUE THREAD

**Issue by ignipae** [SAP/fundamental-ngx#385]
#### Is this a bug, enhancement, or feature request?
Enhancement / Feature Request

#### Briefly describe your proposal.
As of now, we have the "Action Bar" component, which can be used as a page title. It would be perfect, if the action bar would have a body, where we could place the page body, so said.
Furthermore, it could have also a footer then.

This way, we would achieve a component, which can be easily used to have a "page layout" with a unified design.

If you don't want to use the action bar, another way could be to have a page component, which uses the action bar as the header area + further parts like body and footer.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
current version

#### Is there anything else we should know?

I am very happy, that we have the ngx fundamental components, and it is a great way of enriching angular application with the fiori design guidelides in a unified way.
Having a "page component" (either with the enhanced action bar or even with an own component) will help us to go much more into this unified direction.

**Comment by mikerodonnell89** [comment]
Hi, glad you are enjoying the library!  For layouts we recommend using core fiori-fundamentals styles with standard HTML elements defined here: https://sap.github.io/fundamental/layouts/

**Comment by ignipae** [comment]
Hi @mikerodonnell89 
Thanks for your response!
I totally agree with you that the fiori-fundamental styles already give a perfect shape for the application structure.
Especially, the [shell layout](https://sap.github.io/fundamental/layouts/shell-layout.html).

However, I was hoping for some kind of possibility like the [openui5 page](https://openui5.hana.ondemand.com/#/api/sap.m.Page) is doing.
Having a "simple to integrate" page component, which has a header (for example the action bar || provided content), content (provided content) and an optional footer, would totally go into that direction.

Thank you already for pointing to the layouts documentation.

**Comment by droshev** [comment]
@ignipae thank you for raising any issues/questions. All the feedback is appreciated and reflected into our library. We have just started so feel free to keep opening issues.

**Comment by MattL75** [comment]
Merging this issue with #453
