### ISSUE TITLE
Table: This input (type=checkbox) should not have an aria-checked attribute, as it has a native semantic checked state

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3850]
Description: This input (type=checkbox) should not have an aria-checked attribute, as it has a native semantic checked state

![image](https://user-images.githubusercontent.com/32538291/98776917-de742980-2415-11eb-8c38-ee84059d0c6b.png)

Expected: Developers must use valid markup and follow the rules of the ARIA specification.

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/98776954-edf37280-2415-11eb-9753-c1b8358d0dc8.png)

**Comment by IlyaSurmay** [comment]
since `fd-checkbox` component it's used there seems like it's related to `Core: Checkbox`, not Table

**Comment by puru-hk** [comment]
@Sanjay-1312 could you please retest this issue.

**Comment by platon-rov** [comment]
Please **do not** take this ticket in work. I've already done it, cannot assign on me & push changes due to access conflicts (sap support resolving it). Thanks.
