### ISSUE TITLE
Shellbar userMenu - item type

### ISSUE THREAD

**Issue by andekande** [SAP/fundamental-ngx#3852]
https://github.com/SAP/fundamental-ngx/blob/fdc06ac94e645ff1be34f6e97fa2b9b32891fd1a/libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts#L55

Is that the correct type?
Your [docu](https://sap.github.io/fundamental-ngx/#/core/shellbar) is using ShellbarUserMenu[] which won't compile:

`Property 'name' is missing in type 'ShellbarUserMenu' but required in type 'ShellbarMenuItem'`

**Comment by gguptha** [comment]
The shellbar [userMenu] expects data of type ShellbarMenuItem instead of ShellbarUserMenu and hence this error. There is no property 'name' in ShellbarMenuItem ...

**Comment by andekande** [comment]
Obviously 
But it's the wrong type, when compared to the native fundamental library - the docu samples do not work therefore and require switching to the other type used in ngx.

**Comment by jojozhuang** [comment]
Obviously, this is a mistake, please fix this ASAP.

In `ShellbarUserMenuComponent`, the type of `userMenu` is `ShellbarUserMenu`.
```java
export class ShellbarUserMenuComponent {
    /** The user data. */
    @Input()
    user: ShellbarUser;

    /** The user menu data. */
    @Input()
    userMenu: ShellbarUserMenu[];
    ...
}
```
However, in `ShellbarActionsComponent`, the type of `userMenu` is `ShellbarMenuItem`. 
```java
export class ShellbarActionsComponent {

    /** The user data. */
    @Input()
    user: ShellbarUser;

    /** The user menu data. */
    @Input()
    userMenu: ShellbarMenuItem[];
    ...
}
