### ISSUE TITLE
Carousel RTL related issues

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3853]
`Carousel with vertical direction` has a bug in RTL mode (at least on my side). Ways to reproduce it:
1. Click on the "right" navigation button 2 times:
<img width="1182" alt="Screen Shot 2020-11-12 at 2 44 37 PM" src="https://user-images.githubusercontent.com/39598672/98988406-9cbab000-24f5-11eb-9f91-21a735ba1edd.png">
2. Switch to RTL using the Switch in the left hand-side corner. The images disappear:
<img width="1187" alt="Screen Shot 2020-11-12 at 2 45 40 PM" src="https://user-images.githubusercontent.com/39598672/98988505-c1af2300-24f5-11eb-9e00-792d5bda3824.png">
3. RTL:  If the carousel is displayed right to left, then pressing the right arrow key should move the carousel to the image to the right.

**Comment by mykolavorobiov** [comment]
@InnaAtanasova 
@mikerodonnell89 
Added fixes in my PR https://github.com/SAP/fundamental-ngx/pull/3774, please recheck

**Comment by manjunathanagaraj** [comment]
this is fixed.
