### ISSUE TITLE
Bug: 'isRequired' property on form labels not displaying asterisk 

### ISSUE THREAD

**Issue by Robyn-Keogh** [SAP/fundamental-ngx#386]
Bug found on **fundamental-ngx: "0.0.22-beta"** with **fiori-fundamentals: "^1.4.1"**
**Angular version: 7.1.1**

Previously if a form label had the **isRequired** property set to true, an asterisk was displayed beside the label. 

After deleting my node_modules and running npm install, this no longer is the case.
Checked it out also on 2 colleagues dev environments and they encounter the same issue.

`<fd-form-label [forValue]="'name'" [isRequired]="true">Name</fd-form-label>`

Also seems to be apparent on the live demo version, see here: https://sap.github.io/fundamental-ngx/docs/form

![image](https://user-images.githubusercontent.com/10871931/50689235-b00ab380-1020-11e9-98ec-55ff2e78642f.png)

The required input field does not have the * beside it, despite having the isRequired property set to true.
This live demo definitely had this before.

**Comment by mikerodonnell89** [comment]
Hi Robyn, thanks for pointing this out.  fiori-fundamentals has deprecated the is-required class and now requires you to add the asterisk to your label manually:  https://sap.github.io/fundamental/components/form.html

Apologies for any convenience.  I've updated the docs accordingly with this pull request: https://github.com/SAP/fundamental-ngx/pull/389
