### ISSUE TITLE
CDK related issue for Popover and Action Sheet

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3860]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.24.0

#### If this is a bug, please provide steps for reproducing it.
Create a new Angular Project
Add Fundamental-ngx to it
Copy the example code from https://sap.github.io/fundamental-ngx/#/core/popover#simple and https://sap.github.io/fundamental-ngx/#/core/action-sheet#action-sheet-cosy and paste it in your app. When you click on the controls, the body of the popover opens at the bottom of the page. See attached screenshots:
1.
![Screen Shot 2020-11-16 at 2 11 42 PM](https://user-images.githubusercontent.com/39598672/99297443-4364c080-2816-11eb-8e8e-d95dfeb069ba.png)

2.
![Screen Shot 2020-11-16 at 2 08 50 PM](https://user-images.githubusercontent.com/39598672/99297444-43fd5700-2816-11eb-8abe-fb8b4a95ef80.png)

3.
![Screen Shot 2020-11-16 at 2 08 43 PM](https://user-images.githubusercontent.com/39598672/99297445-43fd5700-2816-11eb-9d49-61cd457894bb.png)

**Comment by InnaAtanasova** [comment]
A new ng-app with only Action Sheet component:
<img width="1281" alt="Screen Shot 2020-11-16 at 4 14 14 PM" src="https://user-images.githubusercontent.com/39598672/99309183-0d7c0800-2827-11eb-85d1-393b07b75e4d.png">

Action Sheet component + other components:
<img width="2560" alt="Screen Shot 2020-11-16 at 4 14 43 PM" src="https://user-images.githubusercontent.com/39598672/99309205-17057000-2827-11eb-87b6-d750f49e956c.png">

**Comment by InnaAtanasova** [comment]
For Popover:
<img width="980" alt="Screen Shot 2020-11-16 at 4 20 43 PM" src="https://user-images.githubusercontent.com/39598672/99309611-bd517580-2827-11eb-8faf-ae6a5d569a50.png">

results in:
<img width="2555" alt="Screen Shot 2020-11-16 at 4 20 29 PM" src="https://user-images.githubusercontent.com/39598672/99309630-c3475680-2827-11eb-8344-cc8e42a23457.png">

**Comment by kavya-b** [comment]
could be related to #3829?
