### ISSUE TITLE
Card: Missing variant of s list card

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3863]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of List card:
https://ux.wdf.sap.corp/fiori-design-web/overview-page-list-cards/

**Comment by yukioht** [comment]
Hi @daisy-yovcheva,
Is missing variant an image?
It might be good that you also specify the variant type and also assign the issue to Puru to ensure it will be read by him.

<img width="738" alt="Screen Shot 2020-11-18 at 7 38 27 PM" src="https://user-images.githubusercontent.com/71727800/99618337-00e9e200-29d6-11eb-8d72-4c5e9eabd8f4.png">

**Comment by puru-hk** [comment]
@daisy-yovcheva could you please retest this issues.

**Comment by daisy-yovcheva** [comment]
Hi,

1. We do have another variant of the List card: [with select control]
![Screen Shot 2021-03-15 at 7 48 52 PM](https://user-images.githubusercontent.com/72403541/111248600-79992d80-85c7-11eb-9530-2780e558a5e1.png)

Fiori ref link: https://ux.wdf.sap.corp/fiori-design-web/overview-page-list-cards/#list-card

2. There is also one line list card:
![Screen Shot 2021-03-15 at 7 51 45 PM](https://user-images.githubusercontent.com/72403541/111248813-e0b6e200-85c7-11eb-9de1-07076dca0db9.png)

Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Card+%28Fiori+3%29+-+List+Card

Thanks, Daisy

**Comment by puru-hk** [comment]
@daisy-yovcheva we have implemented below priority cards. 
List   Card
--
Bar chart list card
Link list card: List variant
Link list card: Image variant
Object group card
Kindly let us know if this really required for the application team.

**Comment by manjunathanagaraj** [comment]
@daisy-yovcheva , as suggested by design team(https://wiki.ariba.com/pages/viewpage.action?pageId=142122447), our initial scope was to develop the following cards:  
- List Card
- Bar chart list card
- Link list card: List variant
- Link list card: Image variant
- Object group card
- Component card

Other variants will be developed only if they are required by the app teams. So, please confirm if other variants are required. If required, let us know the exact new variants required. We shall take it up for development.

I think this issue can be closed if you dont find any issues in the cards developed so far.

**Comment by DeepakSap14** [comment]
@puru-hk
please verify this, if any issue you can reopen it.

**Comment by daisy-yovcheva** [comment]
Hi @DeepakSap14 and @puru-hk,

The following issues should be fixed:

**1.One line list card - Quick links**
The left padding is not aligned properly: [header + icons]
![Screen Shot 2021-06-10 at 3 02 52 PM](https://user-images.githubusercontent.com/72403541/121602971-ef613980-c9fc-11eb-9aa0-5e12c8fd4e7b.png)

**2. Link List card**
The avatar seems to be not alligned.
![Screen Shot 2021-06-10 at 3 05 47 PM](https://user-images.githubusercontent.com/72403541/121603265-57b01b00-c9fd-11eb-9c3e-a44fa2fc64ea.png)

**3. Variant with Select control**
There is extra padding around the select control. It should be: 16px - top, bottom, left
Also, the same issue with the Avatar.
![Screen Shot 2021-06-10 at 3 11 07 PM](https://user-images.githubusercontent.com/72403541/121603735-1704d180-c9fe-11eb-9bb7-acd3fdd189eb.png)

Thanks!

**Comment by droshev** [comment]
We went through Horizon and this should be according to horizon
