### ISSUE TITLE
Card: Missing variant of a Link list card

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3864]
####
Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of a Link list card:
https://ux.wdf.sap.corp/fiori-design-web/overview-page-list-cards/#link-list-card

**Comment by puru-hk** [comment]
@daisy-yovcheva could you please retest this issues.

**Comment by daisy-yovcheva** [comment]
Hi,

There are 2 types of Link List cards:

1.Variant Type: **List** (You have it), but please remove the borders in order to look like the card below:
![Screen Shot 2021-03-15 at 6 01 18 PM](https://user-images.githubusercontent.com/72403541/111240423-721e5800-85b8-11eb-8c2d-4c932a1e7fd2.png)


2.Variant Type: **Image**  (You don't have it).
![Screen Shot 2021-03-15 at 6 04 05 PM](https://user-images.githubusercontent.com/72403541/111240626-d80adf80-85b8-11eb-8417-f61a3156bc30.png)

Fiori ref link: https://ux.wdf.sap.corp/fiori-design-web/overview-page-list-cards/#link-list-card

Thanks, Daisy

**Comment by puru-hk** [comment]
@DeepakSap14 Can you please add the examples as mentioned above.

**Comment by DeepakSap14** [comment]
For creating Image variant link-list-card, we have dependency on `mini-header component` for giving styles to the title and sub-title. This is in design phase.
Hence Image variant will be blocked for now.

**Comment by droshev** [comment]
is this still needed? if so, then maybe the dev team can implement list card
