### ISSUE TITLE
Card: Missing variant of a Stack card 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3865]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of Stack card:
https://ux.wdf.sap.corp/fiori-design-web/overview-page-stack-card-quick-view-card/#stack-card

**Comment by puru-hk** [comment]
@daisy-yovcheva I have check in the netlify url (https://fundamental-ngx.netlify.app/#/core/card) able to see the Stact card here is the attachment. 
Stack card should have Title, Subtitle and stack content count. I have seen all the content in below attachment. 

![image](https://user-images.githubusercontent.com/32538291/99624628-97f57f00-2a54-11eb-9af1-6fb6eeb95638.png)

**Comment by daisy-yovcheva** [comment]
Hi @puru-hk,

The image that you've shared with me it's not a stack card example.

Here is a stack card example:
<img width="340" alt="Screen Shot 2020-11-18 at 9 45 49 PM" src="https://user-images.githubusercontent.com/72403541/99626769-9b304100-2a3b-11eb-8977-10041da35fd3.png">

Here is Fiori ref: https://ux.wdf.sap.corp/fiori-design-web/overview-page-stack-card-quick-view-card/#overview-page-stack-card-components

All the tickets that I've submitted regarding Card "Missing variants" are not in NGX. The last time you told us that not all of the cards will have a priority, but I don't remember which ones. That's why I submitted all the missing types/variants of cards.

There are 12 different types of cards:

- Standard card
- Table card
- Bar chart list card
- List card
- Link list card
- Stack card
- Quick view card
- Refresh card
- Timeline card
- Calendar card
- Object card
- Analytical card { 9 different types of analytical card}
   -Line
   -Bubble
   -Column
   -Stacked column 
   -Vertical bullet
   -Donut
   -Combined
   -Scatter plot
   -Waterfall

**Comment by DeepakSap14** [comment]
This card type is out of scope.
please see planned component in scope https://wiki.ariba.com/pages/viewpage.action?pageId=142122447.

**Comment by daisy-yovcheva** [comment]
Ok, I will close this ticket for now. Thanks.
