### ISSUE TITLE
Card: Missing variant of a Refresh card

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3867]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of Refresh card:
Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Card+%28Fiori+3%29+-+Refresh

**Comment by DeepakSap14** [comment]
This card type is out of scope.
please see planned component in scope https://wiki.ariba.com/pages/viewpage.action?pageId=142122447.

**Comment by daisy-yovcheva** [comment]
Ok, I will close this ticket for now. Thanks.
