### ISSUE TITLE
Card: Missing variant of a Timeline card

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3868]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of Timeline card:
Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Card+%28Fiori+3%29+-+Timeline+Card

**Comment by DeepakSap14** [comment]
for this we have dependency on "Timeline component".
which is not in scope for now.

**Comment by puru-hk** [comment]
@daisy-yovcheva please see planned component in scope https://wiki.ariba.com/pages/viewpage.action?pageId=142122447.

**Comment by daisy-yovcheva** [comment]
Ok, I will close this ticket for now.
