### ISSUE TITLE
Card: Missing variant of a Calendar card

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3869]
#2811 ## Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of a Calendar card:
Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Card+%28Fiori+3%29+-+Calendar+Card

**Comment by puru-hk** [comment]
@daisy-yovcheva Could you please retest this issue.

**Comment by daisy-yovcheva** [comment]
Hi, Here is used only the Calendar component by itself, but not the Calendar Card.

There are additional functionalities attached to the Calendar card that you can see below:

Here is an example:
![Screen Shot 2021-03-15 at 7 56 29 PM](https://user-images.githubusercontent.com/72403541/111249189-8a966e80-85c8-11eb-98f6-3f917d70c778.png)

Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Card+%28Fiori+3%29+-+Calendar+Card

Fiori ref link: https://ux.wdf.sap.corp/fiori-design-web/cards/#top
![Screen Shot 2021-03-15 at 7 57 21 PM](https://user-images.githubusercontent.com/72403541/111249261-a863d380-85c8-11eb-88ef-0d1dfb3f256f.png)

**Comment by puru-hk** [comment]
@daisy-yovcheva. This is not an issues it an enhancement. As per the fiori3 design we have implemented. 
If any application team needs this feature. Please give us the functionality and visual spec so that we will implement accordingly. Please close this issue and raise another issue for enhancement.

**Comment by daisy-yovcheva** [comment]
Ok, I will close this ticket for now as it is not a part of the list with the highest priority. Thanks, Daisy
