### ISSUE TITLE
Card: Missing variant of an Object card

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3870]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a variant of an Object card:
Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Card+%28Fiori+3%29+-+Object+Card

**Comment by puru-hk** [comment]
@daisy-yovcheva  could you please retest this issues
