### ISSUE TITLE
Card: Missing Loading behavior with busy indicator and Placeholders 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#3871]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

It's missing a Loading behavior with busy indicator and Placeholders 

Placeholder Loading is utilized as a busy indicator in areas where content is being loaded. It will replace traditional busy indicators on the initial loading of a page. If the type of content is known, the specific corresponding type of Placeholder Skeleton will be used to match with the loading content.

![Screen Shot 2020-11-16 at 2 27 48 PM](https://user-images.githubusercontent.com/72403541/99315735-c49a7280-286b-11eb-9619-12ccbda6bb09.png)

Visual core ref: https://wiki.wdf.sap.corp/wiki/display/visualcore/Placeholder+Loading

**Comment by DeepakSap14** [comment]
@puru-hk ,
placeholder loading behaviour is not in scope.

**Comment by puru-hk** [comment]
@daisy-yovcheva  please see planned component in scope https://wiki.ariba.com/pages/viewpage.action?pageId=142122447.

**Comment by puru-hk** [comment]
@daisy-yovcheva This is not a bug. This will be the feature enhancement. It will be planned for later sprint.

**Comment by OleksiyDrozdov** [comment]
@daisy-yovcheva could you please clarify on what exactly component this should be implemented.
