### ISSUE TITLE
Bug: Combo Box is missing dropdown select list when control is clicked

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3872]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
No dropdown list appear when user click on control. But there seems to be some unidentified graphic(?) behind input field. From visual Core: 
![image](https://user-images.githubusercontent.com/71797052/99319974-69429300-281f-11eb-9564-85bb5be32b48.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.22.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/combobox
Scroll down to: Standard Combo Box
Click: UI Control arrow
See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/99320183-e7069e80-281f-11eb-89cc-4d407f728e32.png)

**Comment by Betrozov** [comment]
Hi @pierrom 
Could you please provide more details about the environment where this issue was reproduced?

**Comment by pierrom** [comment]
Thanks for following up @Yurii Betrozov<mailto:notifications@github.com>. That was with v 0.22.0 filed in Nov 16, 2020 - last year. Looks like it was resolved in latest version. I will close this ticket.

In verifying this – I found a new “bug” related to Combobox dropdown width re-sized. I will create a new ticket for that.

Thanks, Pierro
