### ISSUE TITLE
Bug: Combo Box - wide discrepancy in size and color of ghost text or helper text within input field among the 3 browsers.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3873]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When compared side-by-side, there's a wide discrepancy in size and color of ghost text or helper text within input field.

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/combobox
Scroll down to: Standard Combo Box
Repeat: For Chrome, Firefox, Safari
See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/99321167-15857900-2822-11eb-95d2-40fa694786ad.png)

**Comment by olshansky** [comment]
Probably already fixed (cc: @pierrom)
![image](https://user-images.githubusercontent.com/14160094/114733822-568ba600-9d4c-11eb-9fd2-658e3b8a7a47.png)

**Comment by pierrom** [comment]
Fixed. Thanks
