### ISSUE TITLE
Bug: Standard List Item are butting up with one another, padding and heights are not observed and not aligned with Visual Core.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3876]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Standard List Item are butting up with one another, padding and heights are not observed and not aligned with Visual Core.
![image](https://user-images.githubusercontent.com/71797052/99329326-ceec4a80-2832-11eb-9c2d-e0761ca44a23.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/standard-list-item
Scroll to: Standard List Item - (ByLine) Borderless
See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/99329295-be3bd480-2832-11eb-98ea-b8175fbd9225.png)

**Comment by sKudum** [comment]
Not reproducible in the latest release. Hence closing it.
Link for reefernce:https://sap.github.io/fundamental-ngx/#/platform/standard-list-item
<img width="1164" alt="2020-12-09_19-59-43" src="https://user-images.githubusercontent.com/53487468/101642907-928ac380-3a59-11eb-9349-995e42cce36f.png">
