### ISSUE TITLE
Bug: Standard List Item Title and ByLine font size and line heights are not observed and not aligned with Visual Core.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3878]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Standard List Item Title and ByLine font size and line heights are not observed and not aligned with Visual Core.(see below)
Link to Specs: https://wiki.wdf.sap.corp/wiki/display/visualcore/List+%28Fiori+3%29+-+Standard+List+with+Byline#List(Fiori3)StandardListwithByline-Specifications
![image](https://user-images.githubusercontent.com/71797052/99331747-dc0a3900-2834-11eb-840b-f9bd4624744c.png)
![image](https://user-images.githubusercontent.com/71797052/99335056-cf3a1500-2835-11eb-95da-3d306b3e6d28.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/standard-list-item
Scroll: Look through all the items
See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/99335734-ff81b380-2835-11eb-8305-ecb4d514f9f2.png)

**Comment by sKudum** [comment]
Not reproducible in latest release hence closing it.
Link to refer:https://sap.github.io/fundamental-ngx/#/platform/standard-list-item
<img width="1164" alt="2020-12-09_19-59-43" src="https://user-images.githubusercontent.com/53487468/101642765-6111f800-3a59-11eb-8aff-8fdbb792f9d4.png">
