### ISSUE TITLE
Bug: Standard List Item - 1 rem padding around thumbnail image is not observed and not aligned with Visual Core.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3879]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Bug: Standard List Item - 1 rem padding around thumbnail image is not observed and not aligned with Visual Core.
Should be like below:
![image](https://user-images.githubusercontent.com/71797052/99340809-9736d000-283d-11eb-9b59-66464eedf7b4.png)
![image](https://user-images.githubusercontent.com/71797052/99340815-9b62ed80-283d-11eb-8a3a-0178aeb7263a.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/standard-list-item
Scroll : To see all items
See error below, screen shot attached
![image](https://user-images.githubusercontent.com/71797052/99340904-c6e5d800-283d-11eb-9337-5a7ae652ac67.png)

**Comment by sKudum** [comment]
Not reproducible in latest release hence closing it.
<img width="1164" alt="2020-12-09_19-59-43" src="https://user-images.githubusercontent.com/53487468/101642565-27d98800-3a59-11eb-8417-1d3677869297.png">
