### ISSUE TITLE
Message box sub-header example

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#3886]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Update message box complex template documentation example to include sub-header.

#### Is there anything else we should know?
Example is currently missing because of [this fundamental styles bug](https://github.com/SAP/fundamental-styles/issues/1895). Once the issue is resolved example should be introduced.

1h

**Comment by InnaAtanasova** [comment]
As discussed we are not going to introduce this feature.
