### ISSUE TITLE
Bug: Menu Button (Platform): drop-down menu not connected to button

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#3908]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.

When you click on a menu button, the menu appears in the bottom left corner of the screen instead of below the button.

#### If this is a bug, please provide steps for reproducing it.

![Peek 2020-11-20 13-00](https://user-images.githubusercontent.com/47522152/99793094-c9dc1380-2b30-11eb-821c-a5808d1cdc73.gif)

**Comment by olshansky** [comment]
Fixed by https://github.com/SAP/fundamental-ngx/pull/3985
