### ISSUE TITLE
Datetime/Picker: Week and time is not as per the fiori3 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3909]
Description: Week and time is not as per the fiori3 

Expected: Week and time should be as per the fiori3 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/99795436-cefd8a80-2b51-11eb-88ad-5d0928d65121.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/99795451-d3c23e80-2b51-11eb-8595-89adf8eb11f5.png)

![image](https://user-images.githubusercontent.com/32538291/99795458-d6249880-2b51-11eb-975c-687bafd5c3e7.png)

**Comment by salarenko** [comment]
@puru-hk Could you explain what is wrong? Issue is missing proper description. It looks like you are comparing Date-time picker with date-picker and time-picker separately.

**Comment by puru-hk** [comment]
- Week it is implemented as M, T, W but as per the fiori3 visual spec it is Mon, Tue, Wed. And time it is implemented as Hours, Minutes and Second but as per the fiori3 visual spec it is Hrs and Min.

**Comment by salarenko** [comment]
@puru-hk Great, could you update the issue title and decription to match what the issue really is about?

**Comment by droshev** [comment]
we support that https://fundamental-ngx.netlify.app/#/core/calendar#calendar-options
