### ISSUE TITLE
Defect Hunting and Release - Sprint 51

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3922]
List all bugs found during the Defect Hunting as comments below using the following format:
- [ ] short description, browser 
attached image or gif

**Comment by nikvalor** [comment]
Description: Options are not displayed while user typing the text if dropdown was previously closed 
Expected: Options should be displayed while user typing the text if dropdown was previously closed 
Browser: Google Chrome Version 87.0.4280.66
Screenshots: ![image](https://user-images.githubusercontent.com/74654139/100601690-95740e80-330b-11eb-9926-e8e2e2939a8f.png)

**Comment by nikvalor** [comment]
Descriptions: Two objects are selected after choosing any option in the dropdown 
Expected: Only one object should be selected after choosing any option in the dropdown
Browser: Google Chrome Version 87.0.4280.66
Screenshots: ![image](https://user-images.githubusercontent.com/74654139/100601991-fac7ff80-330b-11eb-9be7-a81d7130fcb5.png)

**Comment by nikvalor** [comment]
Description: The full name of object is not displayed in input after selecting any option in the dropdown 
Expected: The full name of object should be displayed in input after selecting any option in the dropdown
Browser: Google Chrome Version 87.0.4280.66
Screenshots: ![image](https://user-images.githubusercontent.com/74654139/100602171-382c8d00-330c-11eb-86dc-7fec64c16b3c.png)

**Comment by katekozlowska** [comment]
- [ ] menu icon misalignment on shellbar, Chrome
![fundamental-ngx netlify app_ (1)](https://user-images.githubusercontent.com/7014311/100729914-a8e5af00-33c9-11eb-95e2-c27f3e2e6dca.png)

**Comment by salarenko** [comment]
- [ ] Menu button missing space between text and expand icon (cross browser)
![image](https://user-images.githubusercontent.com/17496353/100728407-cfa2e600-33c7-11eb-98b5-125b48c03d2a.png)

- [ ] Calendar month and yer buttons text is not centered (cross browser)
![image](https://user-images.githubusercontent.com/17496353/100728786-45a74d00-33c8-11eb-9127-2419e2877d33.png)

- [ ] KPI header is missing icon and scale (IE11)
![image](https://user-images.githubusercontent.com/17496353/100730575-84d69d80-33ca-11eb-9331-3d22a49ea555.png)

- [ ] Carousel buttons changing position after (cross browser)
![jumping-carousel-buttons](https://user-images.githubusercontent.com/17496353/100731347-8c4a7680-33cb-11eb-83c6-db5b2953baf1.gif)

- [ ] Combobox with hidden expand button still changes pointer when the expand button placeholder is hovered (cross browser)
![hidden-combobox-button](https://user-images.githubusercontent.com/17496353/100731820-2f9b8b80-33cc-11eb-8d96-d44839880830.gif)

- [ ] Disabled date picker and message overflowing (cross browser)
![image](https://user-images.githubusercontent.com/17496353/100732556-2959df00-33cd-11eb-993f-821ae617a55f.png)

- [ ] Message box footer buttons text not centered (cross browser)
![image](https://user-images.githubusercontent.com/17496353/100734408-ef3e0c80-33cf-11eb-8461-6cc6e10e0fd5.png)

- [ ] Popover documentation says: `Fundamental-ngx popovers use Popper.js.` which is no more relevant (at least I think so).

- [ ] Split button in Shellbar examples (cross browser)
![image](https://user-images.githubusercontent.com/17496353/100737031-ec451b00-33d3-11eb-9040-0bcde48cb811.png)

- [ ] Collapse side-navigation button icon not centered (cross browser)
![image](https://user-images.githubusercontent.com/17496353/100737240-30d0b680-33d4-11eb-8c34-cdb754502aa5.png)

**Comment by mikerodonnell89** [comment]
All of these issues found on chrome/osx.

- [ ] Scroll spy - scrolling too quickly often does not give the desired result

![scrollspy](https://user-images.githubusercontent.com/2471874/100754768-af176380-33a8-11eb-8da2-8415af520610.gif)

- [ ] Fixed Card Layout - drag and drop not working

- [ ] Wizard branching example - click bank transfer which will automatically proceed you to step 3, then go back to step 2 and click credit card.  It should automatically move you back to step 3 and prompt for CC details.  

- [ ] Can't remember if we've already discussed this but toolbar overflow buttons in the popover need vertical padding

![Screen Shot 2020-12-01 at 7 56 52 AM](https://user-images.githubusercontent.com/2471874/100756752-c8b9aa80-33aa-11eb-9c20-3734a56249fc.png)

- [ ] Time picker form message oddly placed

![Screen Shot 2020-12-01 at 8 00 40 AM](https://user-images.githubusercontent.com/2471874/100757207-509fb480-33ab-11eb-8d77-b22949cb21cc.png)

**Comment by mikerodonnell89** [comment]
- [ ] Selected tabs (both text or icon) not styled

![Screen Shot 2020-12-01 at 9 01 24 AM](https://user-images.githubusercontent.com/2471874/100764643-cc056400-33b3-11eb-9fd3-7a59e3076591.png)

- [ ] Quick fix - column2 should probably come after column1

![Screen Shot 2020-12-01 at 9 03 17 AM](https://user-images.githubusercontent.com/2471874/100764871-0ec73c00-33b4-11eb-9074-b05f61f0f375.png)

- [ ] Column filtering broken
![Screen Shot 2020-12-01 at 9 04 14 AM](https://user-images.githubusercontent.com/2471874/100764959-31595500-33b4-11eb-9da7-a573311bbf61.png)

**Comment by mikerodonnell89** [comment]
- [ ]  Step input warning worth investigating
![Screen Shot 2020-12-01 at 11 01 25 AM](https://user-images.githubusercontent.com/2471874/100778696-8ef59d80-33c4-11eb-884c-a6ae411ba2d7.png)


- [ ] Shellbar counters need to have 1px of blue between the counter and top of the shellbar... here's styles
![Screen Shot 2020-12-01 at 11 05 11 AM](https://user-images.githubusercontent.com/2471874/100779085-16dba780-33c5-11eb-99c1-0d99644fb872.png)
and here's ngx
![Screen Shot 2020-12-01 at 11 05 28 AM](https://user-images.githubusercontent.com/2471874/100779108-1fcc7900-33c5-11eb-9998-f02dc2de21f9.png)
