### ISSUE TITLE
Bug: Extra padding or spacing on Table Card not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3928]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Extra padding/spacing on Table Card not aligned with Visual Core. Width of rows and headers on table should extend edge-to-edge. See spec below from Visual core:
![image](https://user-images.githubusercontent.com/71797052/100155248-c8298d00-2e5b-11eb-9d89-bd6472cfce66.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.24.0

#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://sap.github.io/fundamental-ngx/#/core/card
2. Scroll down to: Table Card
3. See error: pic attached below
![image](https://user-images.githubusercontent.com/71797052/100155193-ac25eb80-2e5b-11eb-8f51-f8145f2b30ef.png)

**Comment by olshansky** [comment]
It's styles issue https://fundamental-styles.netlify.app/?path=/docs/components-card--card-anatomy#table-card

**Comment by DeepakSap14** [comment]
This needs change in style for table component. which is inprogress at https://github.com/SAP/fundamental-styles/issues/2360. once this style is available in Ngx, Ngx can be modified and Pr can be raised for the fix.

**Comment by DeepakSap14** [comment]
class fd-table--no-outer-border has been added in fundamental-styles, we can add a input property in fundamental-ngx/table implementation for creating table without outer border.
As you are working on table components, so i do not want to interfere in it.

**Comment by platon-rov** [comment]
As in the current sprint, my main responsibility is to fix all table bugs so I'm reassigning myself.

**Comment by pierrom** [comment]
Verified and closed.
