### ISSUE TITLE
Bug: Card Footer Bar height should be increased to align with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#3929]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Card Footer Bar height should be increased from 33px to 40px to aligned with Visual Core
![image](https://user-images.githubusercontent.com/71797052/100157441-6834e580-2e5f-11eb-9c4c-d3f1a82a1982.png)
![image](https://user-images.githubusercontent.com/71797052/100157460-6ec35d00-2e5f-11eb-8bd5-f8b369320d4a.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/core/card
Scroll down to: Card Footer
See error below:
![image](https://user-images.githubusercontent.com/71797052/100157616-ab8f5400-2e5f-11eb-812d-b884378cdc3f.png)
![image](https://user-images.githubusercontent.com/71797052/100157629-b1853500-2e5f-11eb-8728-1fa57e7fa0a7.png)

**Comment by olshansky** [comment]
I believe it's styles issue https://fundamental-styles.netlify.app/?path=/docs/components-card--card-anatomy

**Comment by pierrom** [comment]
Corrected. Thank you.
