### ISSUE TITLE
Multi Input: Dropdown lists is not as per the fiori3 style 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3935]
Description: Dropdown list is not as per the fiori3 style 
Checkbox is not displayed. And between the lists there is a lot of gap. 

Expected: Dropdown lists should be as per the firo3 styles

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/100314224-28dfd380-2fdc-11eb-8ff2-b52d8cdd881b.png)

Expected: 
![image](https://user-images.githubusercontent.com/32538291/100314267-4745cf00-2fdc-11eb-8b99-16baf1928770.png)

**Comment by Lokanathan-k** [comment]
@puru-hk  As per the tech spec the difference is only implemented, check box will be available only in the core.

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
