### ISSUE TITLE
Multi Input: Selected one list from the dropdown but in the token it showing two items added

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3936]
Description: Selected one list from the dropdown but in the token it showing two items added

Steps: 
- Type 2 letter it showing the auto suggestion 
- Select one item from the list. 
- In the token it is added 2 and also it showing al

Expected: In th token it should be one item

Screenshot attached. 
![image](https://user-images.githubusercontent.com/32538291/100314643-187c2880-2fdd-11eb-9eea-511006bd4d30.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/100314721-482b3080-2fdd-11eb-9885-5e1a47facdd9.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
