### ISSUE TITLE
Multi input: Placeholder is not as per the fiori3 left side have more space 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3937]
Description: Placeholder is not as per the fiori3 spec. Left side have more space 

Expected: Space is not required. 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/100315070-051d8d00-2fde-11eb-9b22-ce2438f2b31b.png)

Expeted: 

![image](https://user-images.githubusercontent.com/32538291/100315088-0b136e00-2fde-11eb-9665-25835ae5d3e0.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
