### ISSUE TITLE
Multi Input: Even after matching the character autocomplete is not working  

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3938]
Description:  Even after matching the character autocomplete is not working  

Expected: After typing the 2 or 3 letter from the input field if it matches the dropdown list it should autocomplete. 

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/100317021-9cd0aa80-2fe1-11eb-81e4-ed4e8fb1df7b.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/100317074-bb36a600-2fe1-11eb-9459-8254049e0d97.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
