### ISSUE TITLE
Multi Input: Not able remove the selected item in the input field from delete key

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3939]
Description: Not able remove the selected item in the input field from delete key

Expected: From the delete key should able to remove the selected item in the input field

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/100317428-5af43400-2fe2-11eb-83d8-2a85956746c3.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
