### ISSUE TITLE
Create a Fundamental Angular + NativeScript Example

### ISSUE THREAD

**Issue by damien-murphy** [SAP/fundamental-ngx#394]
As a developer it would be great to be able to build NativeScript mobile applications and leverage fundamental-ngx

NativeScript for Angular: https://www.nativescript.org/nativescript-is-how-you-build-native-mobile-apps-with-angular
SAP Mobile Development Kit for NativeScript: https://blogs.sap.com/2018/11/14/new-features-in-mobile-development-kit-2.2-3.0/
More MDK NativeScript Info: https://blogs.sap.com/2018/11/14/new-features-in-mobile-development-kit-2.2-3.0/

A starter example project would help get developers started on such a path.

**Comment by droshev** [comment]
Even though the idea sounds interesting, we can come to this in the future. I will close the issue for now.
Feel free to share more ideas and suggestions
