### ISSUE TITLE
Multi Input: All the selected items is showing truncation

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3940]
Description: All the selected items is showing truncation

Expected: It should not truncation 

Screenshot : 

![image](https://user-images.githubusercontent.com/32538291/100317678-c3dbac00-2fe2-11eb-9ea9-951356742919.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/100317734-d7871280-2fe2-11eb-9695-71d07d0105fd.png)

**Comment by Lokanathan-k** [comment]
breaking changes from the PR https://github.com/SAP/fundamental-styles/pull/1843

**Comment by Lokanathan-k** [comment]
Broken change from the styles introduced, could see affecting the core multi input too.

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
