### ISSUE TITLE
Multi Input: Click on 2 more in the input field it is showing all the items from the dropdown lists.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3941]
Description: Click on 2 more in the input field it is showing all the items from the dropdown lists.

Expected: It should show only selected items from the dropdown list 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/100318172-9c391380-2fe3-11eb-96da-e93194be41b2.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/100318206-ac50f300-2fe3-11eb-90de-395ad36f7f4c.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
