### ISSUE TITLE
Multi Input: Able to select the same item more than twice from the dropdown list

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3943]
Description: Able to select the same item more than twice from the dropdown list

Expected: Selected item should not show in the dropdown list 

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/100318863-c3441500-2fe4-11eb-8019-3c4f44b8c58b.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
