### ISSUE TITLE
Multi Input: No error show if the invalid character entered in the input field

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3944]
Description: No error show if the invalid character entered in the input field

Expected: Error should be shown if the invalid character entered.

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/100320956-fa67f580-2fe7-11eb-8e3c-7a7da89f33cf.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/100321099-300cde80-2fe8-11eb-983b-259f3fa35f7f.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
