### ISSUE TITLE
Multi Input:  IE browser dropdown lists is not as per the fiori3 style

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3959]
Description:  IE browser dropdown lists is not as per the fiori3 style

Dropdown border is shown

Expected: Dropdown lists should be as per the firo3 styles

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/100596027-afb8e700-3321-11eb-8af5-849aa0180b37.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/100596064-bba4a900-3321-11eb-8fcd-4635a7f51157.png)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
