### ISSUE TITLE
Multi Input: Screen is not proper while adding the dropdown items from the list

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3960]
Description: Screen is not proper while adding the dropdown item from the list 

Expected: Screen should be proper 

Attached the video:

[3960.zip](https://github.com/SAP/fundamental-ngx/files/5615272/3960.zip)

**Comment by Lokanathan-k** [comment]
fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4008
