### ISSUE TITLE
Datetime Picker: Placeholder looks different in different browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3968]
Description: Placeholder looks different in different browser

Expected: Placeholder should same for all the browsers. 

Screenshot attached for Safari, FF, Chrome Edge

![image](https://user-images.githubusercontent.com/32538291/100700153-cd8a5880-33c2-11eb-9cff-30d88c92de7e.png)

**Comment by kavya-b** [comment]
Browsers have specific styles for placeholders and this is not something specific to datetimepicker. 
If you look at https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder in different browsers, it would look different in each browser. 
If this is still an issue, it would be on underlying input component, and not on datetimepicker. One thing to be noted is, any modifications to styling the placeholder [may not have support in IE.](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#Browser_compatibility)

**Comment by puru-hk** [comment]
@Lokanathan-k could you please have a look.

**Comment by Lokanathan-k** [comment]
> @Lokanathan-k could you please have a look.

@puru-hk on checking found that the placeholder has different style with different browser. this should be addressed as part of Style changes.

**Comment by Betrozov** [comment]
can not reproduce
please recheck this issue
