### ISSUE TITLE
Datetime/Picker: Prasing is work only one way

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3969]
Description: Datetime/Picker: Prasing is work only one way

Steps: 
1. Try to entered the date and time format from the input. 
2. Click on the date/time icon it is not reflecting the date and time which user entered. 

Other way it is working fine select the date and time from the calendar 

Expected: It should reflect the date and time in the calendar .

This has to be fixed as per the fiori3 guidelines.

**Comment by dimamarksman** [comment]
@puru-hk I can not reproduce it following these steps, it would be great to have a video/gif record to reproduce it

**Comment by puru-hk** [comment]
Sorry I have re-tested it is working fine.
