### ISSUE TITLE
Datetime Picker: Button name is different in spec it is "OK" but in the component it is "Submit"

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#3970]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.

button named wrongly 

Specs:
![image](https://user-images.githubusercontent.com/53534379/100715017-9d4fb380-33dc-11eb-978b-52e474b40d0e.png)

implementation:
![image](https://user-images.githubusercontent.com/53534379/100715133-c07a6300-33dc-11eb-959e-a4b828009d54.png)

**Comment by kavya-b** [comment]
fixed with #3991
