### ISSUE TITLE
Bug: (Platform) Missed styles for menu and split-menu-button components

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#3972]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Missed styles for menu and split-menu-button components

#### If this is a bug, please provide steps for reproducing it.
1. Go to http://localhost:4200/fundamental-ngx#/platform/menu-button or http://localhost:4200/fundamental-ngx#/platform/split-menu-button
2. try to open any menu

#### Please provide relevant source code if applicable.
Need to include to styles of components
```
@import "~@angular/cdk/overlay-prebuilt.css";
```

#### Is there anything else we should know?
![split-menu-button](https://user-images.githubusercontent.com/8318592/100721453-037e0b80-33c8-11eb-818c-4c23db3b8626.png)

**Comment by olshansky** [comment]
Fixed by https://github.com/SAP/fundamental-ngx/pull/3985
