### ISSUE TITLE
Platform Datetime Picker does not take up 100% of its parent container

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3973]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.
Any Inputs fields should not limit its overall width as this is responsibility of the parent layout or container. When we use DatePicker inside forms it looks like this. Width is not 100% like the the other inputs.

![Screen Shot 2020-12-01 at 10 46 45 AM](https://user-images.githubusercontent.com/17149942/100723810-83a17280-33c2-11eb-81d9-50ea357d9866.png)

You can see the problem also on demo page too, when you compare this to other inputs. 

#### If this is a bug, please provide steps for reproducing it.
Please see the demo page

**Comment by kavya-b** [comment]
fixed in #5759
