### ISSUE TITLE
Platform Date Picker does not work with Date Type

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3974]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When we work with forms and let's sat we load an Invoice and we change a date on this object e..g `needBY` date, we cannot send to backend this format or we should not keep in mind to do some special formating 

```
"needBy": {
    "date": {
      "year": 2020,
      "month": 12,
      "day": 17
    },
    "time": {
      "hour": 0,
      "minute": 0,
      "second": 0
    }
  },
```

Microservices comunicates with UTC like formats. So what we want instead when we hit submit, to make sure that we save real date into the form object. Otherwise there is not real added value from what already provides `core` components.

When we define a domain class on the UI level, do we want to define types like this ?

```
export class Requisition {
   title: string;
   needBy: FdDatetime;
}
```

or more nativelly like this ? Which is more natural way. 
```
export class Requisition {
   title: string;
   needBy: Date;
}
```

Checkout some other implementations, as they always support work with native JS Date Object

https://www.primefaces.org/primeng/showcase/#/calendar
https://next.clarity.design/components/date-picker/#date-access
https://material.angular.io/components/datepicker/examples

**Comment by kavya-b** [comment]
would need @dimamarksman 's inputs on this. Is it possible to achieve this with the datetime adapter?

**Comment by dimamarksman** [comment]
Hi @fkolar
On the DateTimeAdapter tech spec meeting it was agreed that default datetime implementation should be based on the FdDateTime instance and not on native js Date.
All date/time components are based on generic DatetimeAdapter implementation. It means that in order to support different date instances (native, momentjs) we have to implement a DatetimeAdapters which knows how to deal with these dates (DatetimeAdapter<Date>, DatetimeAdapter<Moment>)
So in order to work with native date we have to introduce NativeDatetimeAdapter. It should not be much work I believe cause it will mostly  be same adapter as FdDatetimeAdapter

**Comment by fkolar** [comment]
Are you saying that Our EntityStores which will be responsible for comunicating with the backend. will be working with this specific type ? and converting it into UTC here ? 

Our Domain Classes with not work with Data but with FDDate?

**Comment by dimamarksman** [comment]
I think that it's a normal practise to have a mapper layer to map some data in a format which is more sutable for UI and map it back before sending to a server.

**Comment by dimamarksman** [comment]
Also as it was pointed in the datetime adapter PR's description `FdDatetimeAdapter` is based on the native Int.DatetimeFormat as result it's limitted to parse localised date strings properly. 
To work with localised dates reliably we need to introduce adapter based on the third party, e.g. momentjs or date-fns.

**Comment by fkolar** [comment]
I see. Let's leave this like this and we will have to count that our Domain Class, we use this specific type and before sending it to the REST API we will have to do conversion.
