### ISSUE TITLE
Bug: (Core) Tabs – tab have no bottom border but should 

### ISSUE THREAD

**Issue by olshansky** [SAP/fundamental-ngx#3975]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Tabs have no bottom navigation border:
![image](https://user-images.githubusercontent.com/14160094/100726888-33301200-33ce-11eb-95c0-9dbd1564150d.png)

Figma design:
![image](https://user-images.githubusercontent.com/14160094/100726951-493dd280-33ce-11eb-8e21-8e61f1bde567.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx: v 0.25.0
#### Is there anything else we should know?
Chrome

**Comment by InnaAtanasova** [comment]
Closing as it's a duplication of an issue that is part of the Defect Hunting https://github.com/SAP/fundamental-ngx/issues/3922
