### ISSUE TITLE
Scroll spy - scrolling too quickly does not select correct element

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#3982]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

scrolling too quickly often does not give the desired result.  Note in the GIF (right when it starts) I scroll to the top yet element 3 is selected by the spy.  Then i scroll down and up very quickly and element 8 is selected

![scrollspy](https://user-images.githubusercontent.com/2471874/100754768-af176380-33a8-11eb-8da2-8415af520610.gif)

**Comment by maxym-valor** [comment]
Approved!
