### ISSUE TITLE
Bug: Carousel: Keyboard navigation is not proper

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3987]
#### Is this a bug, enhancement, or feature request?
This is a bug.

#### Briefly describe your proposal.
1. In the carousel documentation, go to the section"Carousel with hidden navigation buttons".
(https://fundamental-ngx.netlify.app/#/core/carousel)
2. Try navigating through keyboard.
3. First navigation works fine. For every subsequent navigation, it requires explicit mouse click on the image for the navigation to work.

Tested on Mac/Chrome.

**Comment by DeepakSap14** [comment]
Not able to reproduce it. tested on Mac chrome/firefox/safari.
please verify again.

**Comment by manjunathanagaraj** [comment]
As discussed/shown, it is reproducible if you first click on the image and then try navigating through keyboard.

**Comment by puru-hk** [comment]
@DeepakSap14 I have tested in Microsoft edge I'm able to reproduce. 
Click on the image " Carousel with hidden navigation buttons"
And try to enter the right arrow key from the keyboard. On click on first image it will work, after navigate to second image try to enter the right arrow key it doesn't work. Again need to click on the image then it will work.

**Comment by puru-hk** [comment]
Verified this url https://deploy-preview-3957--fundamental-ngx.netlify.app/#/core/carousel it is working fine
