### ISSUE TITLE
Fixed Card Layout - drag and drop not working

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#3997]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Drag and drop is not working properly in Fixed Card Layout

**Comment by DeepakSap14** [comment]
I am able to drag and drop cards.
There is default dragDelay added, so scrolling will also work together.
So have to hold the card, then it will start dragging.

i have tested it in firefox/chrome/safari/edge.

**Comment by DeepakSap14** [comment]
Not reproducible.
