### ISSUE TITLE
Platform Feed Input user image disappearing at 600px screen size

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#4020]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
User image should disappear below 25rem screen size as per spec, but is disappearing at 37.5rem.
![image](https://user-images.githubusercontent.com/53509521/101314233-1425fa00-387e-11eb-96ae-8b6d99f71fd7.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/platform/feed-input 
2. Adjust the screen size to ~600px.
3. Observe the examples with user image, for example, Standard. Below 600px, the image vanishes.
![2020-12-07_11-27-37 (1)](https://user-images.githubusercontent.com/53509521/101314835-64518c00-387f-11eb-83ab-c34363bb3cfa.gif)
Expected: as per spec, the image should vanish below 25rem(400px) and not 600px.

**Comment by olshansky** [comment]
@kavya-b it's a styles issue _(not ngx)_, [here](https://fundamental-styles.netlify.app/?path=/docs/components-feed-input--standard) has the same behavior
