### ISSUE TITLE
Feed Input: Able to type the disabled input field 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4021]
Description: Able to type the disabled input field 

Expected: User should not allow to type in the disabled input field. 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/101316990-a250af00-3883-11eb-8211-7d0e68e6b94f.png)

**Comment by genereg1** [comment]
Fixed by this PR https://github.com/SAP/fundamental-ngx/issues/4024

**Comment by puru-hk** [comment]
Tested it is working fine.
