### ISSUE TITLE
File Uploader: Drag and drop the valid file the popup is showing invalid file upload.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4025]
Description: Even after drag and drop the valid file the popup is showing invalid file upload. After load successful it should showing in green. 

Expected: If user is trying upload the valid file then it should not show the wrong message 

Screenshot attached:

![image](https://user-images.githubusercontent.com/32538291/101319488-1b520580-3888-11eb-9389-6c66ce1908a8.png)

![image](https://user-images.githubusercontent.com/32538291/101319600-4177a580-3888-11eb-8d2d-6949a0cb97b2.png)

![image](https://user-images.githubusercontent.com/32538291/101319752-77b52500-3888-11eb-9c45-dee6bbbc0aff.png)

**Comment by Lokanathan-k** [comment]
closed as part of the PR https://github.com/SAP/fundamental-ngx/pull/4110
