### ISSUE TITLE
File Uploader: In RTL mode Button.. is showing wrong 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4027]
Description: In RTL mode Button.. is showing wrong 

Expected: RTL mode Button.. should display properly

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/101320687-2dcd3e80-388a-11eb-8df0-0366ffcb4984.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/101320695-33c31f80-388a-11eb-99ef-599e8e53c5c8.png)

**Comment by Lokanathan-k** [comment]
On checking, found that the issue exist with the button component.
Normal View
![image](https://user-images.githubusercontent.com/53534379/102171368-5e316000-3ebc-11eb-889a-3c3f3584e48a.png)

RTL view
![image](https://user-images.githubusercontent.com/53534379/102171291-36da9300-3ebc-11eb-928b-8385bb72c86e.png)

**Comment by sKudum** [comment]
Platform buttons are wrapped on core, so it will show the same behaviour as we have in core. But as per my understanding on RTL special charters and icons should shift there places as shown above.

Hi @salarenko, could you please have a look on it.

**Comment by sKudum** [comment]
Hi @Puru, it is placed as per W3C standards of internationalisation, it seems not a bug. The one which sapui5 has is deviating from W3C standards.

Hi @kenykim , Could you please suggest on it.

**Comment by puru-hk** [comment]
It is working as expected. It is not a bug

**Comment by kenykim** [comment]
Hi all, 
In my opinion, the reading direction should be Right to Left. the screenshots show it still read Left to Right.
