### ISSUE TITLE
Upload Collection: unable to upload folder and files together.

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#4033]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

event after matching the file extension type, files and folders cannot be uploaded together.

#### If this is a bug, please provide steps for reproducing it.
Step 1: open the url(https://fundamental-ngx.netlify.app/#/platform/upload-collection)
step 2: go to section Default
Step3: Create a new folder
Step4: Click on the new folder
Step5: Add the files under the new folder. 
Step6. uploaded files is not able see

PFA video:
[directory and file upload error.zip](https://github.com/SAP/fundamental-ngx/files/5654363/directory.and.file.upload.error.zip)

**Comment by puru-hk** [comment]
@Betrozov I have update the issues title and steps.
