### ISSUE TITLE
Basic Dynamic Page and Disable Header Collapse Page: content runs into header area. 

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4034]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Basic Dynamic Page and Disable Header Collapse Page: content runs into header area during scrolling. 
![image](https://user-images.githubusercontent.com/71797052/101416210-3760a180-389e-11eb-9663-dd8fa643b305.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0
#### If this is a bug, please provide steps for reproducing it.
1. Go to: https://fundamental-ngx.netlify.app/#/platform/dynamic-page
2. Scroll down to: Basic Dynamic Page and Disable Header Collapse
3. Reduce size of browser window either horizontally or vertically
4. Scroll up or down - (see error)

**Comment by kavya-b** [comment]
This is because the `background` property is set to `transparent` value for these examples. This is expected behaviour.

**Comment by kavya-b** [comment]
#4084 fixes this by removing the transparent background examples.

**Comment by pierrom** [comment]
Fixed. Thank you.
