### ISSUE TITLE
Upload collections: Tooltip is not showing for search icon, action, next and previous icons

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4038]
Description: Tooltip is not showing for search icon, action, next and previous icons

Expected: All icons should display tooltip

**Comment by Seamoo13** [comment]
@Betrozov  reproduced, issue remains. Tooltip missing for search bar's search icon and all action items and pagination buttons (left and right arrows)
![2020-12-15_2](https://user-images.githubusercontent.com/47522152/102201905-5dee9000-3ecf-11eb-917e-3ad9d22787ef.png)

**Comment by Seamoo13** [comment]
Update: these issues are from other components search, menu, etc.  (fd-pagination, fdp-menu, fdp-menu-item and fd-input-group). Not from upload collection implementation.

**Comment by Seamoo13** [comment]
duplicates:
https://github.com/SAP/fundamental-ngx/issues/3126
