### ISSUE TITLE
Upload collections: Unable to edit the folder and files

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4039]
Description: Unable to edit the folder and files

Steps: 

- Create a new folder/files
- Select the folder/files
- It is enable to editable field
- change the name of the folder/file 
- It is showing the Successful
- But is not change the name instead it is showing the old name. 

Screenshot attached

![image](https://user-images.githubusercontent.com/32538291/101445092-dc36b980-3946-11eb-88ef-b4707f81a91e.png)

**Comment by Seamoo13** [comment]
@Betrozov  issue remains, new file name not saved
![Peek 2020-12-15 12-17](https://user-images.githubusercontent.com/47522152/102202029-87a7b700-3ecf-11eb-84bc-4feb2c4eea6f.gif)
