### ISSUE TITLE
Upload collections: Without selecting the folder/files able to remove in action column

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4040]
Description: Without selecting the folder/files able to remove in action column

Expected: It should not allow to perform action without selecting the folder/files. 

![image](https://user-images.githubusercontent.com/32538291/101465010-6b52ca00-3965-11eb-8d75-6ddc72d830cf.png)

**Comment by Betrozov** [comment]
waiting for a response from designers

**Comment by puru-hk** [comment]
As per the below mail no need to select the folder/files to remove. Hence closing this issue.

![image](https://user-images.githubusercontent.com/32538291/101712587-dc0bfa80-3abb-11eb-9143-fdd9036675b8.png)
