### ISSUE TITLE
Upload collections: Table should not have column 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4041]
Description: Table should not have column 

Expected: As per the Ariba requirement table doesn't have column 

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/101466227-e5378300-3966-11eb-9d7b-90cde0bd1454.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/101466311-fbddda00-3966-11eb-9975-44a1c9fd08e0.png)

**Comment by Betrozov** [comment]
related to this [PR](https://github.com/SAP/fundamental-ngx/pull/4028)
waiting for the merger
