### ISSUE TITLE
Pagination Component: From keyboard not able to access page 4

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4042]
Description: From keyboard not able to access page 4

Steps:
Login to Fundamental ngx
Select Platform
Click on pagination Component
Try to access the page number from the keyboard. It is not able to access

Expected: Should able to access all the pages from the keyboard

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/101467330-2bd9ad00-3968-11eb-9f1e-5d64b749afa5.png)

**Comment by Betrozov** [comment]
@puru-hk This issue related to the Pagination component

**Comment by puru-hk** [comment]
Tested in the ngx version 31.0 page number is able to access via keyboard. Hence closed.
