### ISSUE TITLE
Upload collections: Setting, Soring , filtering is not implemented  

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4045]
Description: Setting, Soring , filtering is not implemented  

Expected: Setting, Soring , filtering should be implemented 

This issue is created only for the tracking purpose. All these features is implemented in grid list table. Once it is implement to UC I will test and closed this issues.

**Comment by sKudum** [comment]
1).Having details are selected item in single select(item id) and in multi select (number of items selected) will help to have the details of items.
