### ISSUE TITLE
Table phase3 implementation

### ISSUE THREAD

**Issue by skocharian** [SAP/fundamental-ngx#4069]

**Comment by dimamarksman** [comment]
*Yesterday*:
 - was working on table p13 grouping dialog

*Today*:
- going to work on table p13 filtering dialog

**Comment by dimamarksman** [comment]
*Yesterday*:
 - was working on table p13 filtering dialog  

*Today*:
- procced working on table p13 filtering dialog

**Comment by dimamarksman** [comment]
*Yesterday*:
 - was working on table p13 filtering dialog  

*Today*:
- working on table p13 filtering dialog
- start working on table p13 columns dialog

**Comment by dimamarksman** [comment]
Yesterday:
- was working on table p13 filtering dialog

Today:
- working on table p13 columns dialog

**Comment by dimamarksman** [comment]
Yesterday:
 - was working on table p13 columns dialog

Today:
 - going to finish columns dialog
 - start working on adding table's initiate states

**Comment by skocharian** [comment]
PR ETA Dec 31

**Comment by dimamarksman** [comment]
Wednesday:
 - Refactored table row selection, flat rows rendering instead of nested.
Today:
 - Extend platform table examples
 - Create table phase 3 PR

**Comment by dimamarksman** [comment]
Yesterday:
- Extended platform table examples.
- fixed table tests.

Today:
- Fixing platform table unit tests.
- once unit tests are fine create table phase 3 PR

**Comment by dimamarksman** [comment]
Wednesday
 * was addressing table phase 3 PR comments

Today:
 * Going to add unit tests for the table component (in order to address PR's comment)

**Comment by dimamarksman** [comment]
Yesterday
 * review PR's
 * was working on table unit tests

Today:
 * Going to finish table unit tests

**Comment by dimamarksman** [comment]
Yesterday:
 * resolved platform table comments
Today:
 * working on table page scrolling feature

**Comment by dimamarksman** [comment]
close it due to https://github.com/SAP/fundamental-ngx/pull/4255
