### ISSUE TITLE
Emphasized Button not bold

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-ngx#4078]
The emphasized button doesn't show bold text style in NG and it's a deviation from UI5 / Fundamental Styles.
Reason: Actually `font-weight: 700;` is set on the Button component, but it's overwritten by button text style `font-weight: 400;`

This problem occurs in React too where I'll also create an issue.

![image](https://user-images.githubusercontent.com/75482561/101773204-bf3beb00-3aec-11eb-98cd-fadedeedff41.png)

**Comment by droshev** [comment]
The issue comes from the fact that the button wraps a `span` inside
