### ISSUE TITLE
Icon Tab Bar - Changing the order of tabs

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#4093]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Add a possibility to change the order of tabs in the icon tab bar component.
The behavior has been described [here](https://experience.sap.com/fiori-design-web/icontabbar/#changing-the-order-of-tabs).

**Comment by puru-hk** [comment]
Tested It is working fine.
