### ISSUE TITLE
implement auto placement for popovers

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#410]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
At the moment fundamental-ngx doesn't have an implementation for auto-placement of popovers.

Should be a change that also supports inline-help, and other components.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7.1
fundamental-ngx 0.0.26 beta

**Comment by droshev** [comment]
<img width="727" alt="screen shot 2019-01-18 at 2 06 28 pm" src="https://user-images.githubusercontent.com/4380815/51407586-457e6b00-1b2a-11e9-87ab-3eea985c493b.png">

**Comment by mikerodonnell89** [comment]
I'm confused by the screenshot, are you saying the popover should detect if the popover body will bleed off the viewport and position itself accordingly?

**Comment by droshev** [comment]
What I meant is that you may end up having a button(which shows a popover on click/hover) that is position at the bottom of the page and if you click on it, the popover won't be visible and the user might be confused.  Offering an auto placement could be the solution.

**Comment by bcullman** [comment]
there is a library called popperjs that provides this functionality. SAP Concur has had great success with it in our pre-funrdamentals component library. there are wrappers for react (whch we used) ngx and vue 

https://www.npmjs.com/package/ngx-popper

please see https://github.com/SAP/fundamental-react/issues/313

**Comment by desaroxx** [comment]
Same problem here. 

Popover is going out of bounds on the bottom of the window.

If I could control the popover's placement (top, right, bottom or left), then that would already solve my case.

**Comment by bcullman** [comment]
@desaroxx - popper does placement. but it also does flipping when the preferred placement is unavailable (page edge issues)

**Comment by mikerodonnell89** [comment]
blocked by https://github.com/SAP/fundamental/issues/1286
