### ISSUE TITLE
bug: (platform) List - on firefox, the virtual load doesn't load for key navigation

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4107]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
on List, under the virtual scroll example, if you click on a list item and use the down arrow key to navigate down, the list doesn't load more options. 

#### If this is a bug, please provide steps for reproducing it.
1. open firefox
2. go to https://fundamental-ngx.netlify.app/#/platform/list
3. scroll down to the "List - virtual scroll' example
4. click on the first list item
5. use the down arrow key to navigate to the last option

**Actual results:**
list doesn't load next set of list items
![Peek 2020-12-14 16-38](https://user-images.githubusercontent.com/47522152/102101621-87f27480-3e33-11eb-9db4-9d5b7fcab22a.gif)

**Expected results:**
list will load next set of list items
![expectedScroll](https://user-images.githubusercontent.com/47522152/102101635-8b85fb80-3e33-11eb-8b9c-dd923f3cbd2c.gif)

**Comment by sKudum** [comment]
fixed as part of accessibility issue https://github.com/SAP/fundamental-ngx/pull/4160
