### ISSUE TITLE
Bug: Dynamic Page - Footer Bar (border) not correct and not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4111]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Specs for Footer Bar on Dynamic Page according to Visual Core - there should be no Border.
![image](https://user-images.githubusercontent.com/71797052/102175918-2d6a1000-3e55-11eb-96a2-d3b4cba35edb.png)
![image](https://user-images.githubusercontent.com/71797052/102175932-32c75a80-3e55-11eb-802c-53af2663cfc9.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/dynamic-page
Scroll to: Basic Dynamic Page
Click: Click to Open Full Screen button and see bug on Footer Bar.
![image](https://user-images.githubusercontent.com/71797052/102175896-23e0a800-3e55-11eb-9835-d7f011a1993d.png)

**Comment by kavya-b** [comment]
Hi @pierrom , Dynamic Page uses Bar component which in turn uses the Floating Footer Bar.
Please note that `border:none` is applied for floating footer bar in Dynamic Page already:
![image](https://user-images.githubusercontent.com/53509521/103329927-1ea27080-4a85-11eb-931a-d6df9d29ec44.png)
The Ariba image being cross-referenced is not of Fiori's Floating Footer bar. 
The current footer bar in Dynamic Page matches the Fiori3 spec Floating Footer bar:
![image](https://user-images.githubusercontent.com/53509521/103330159-4e05ad00-4a86-11eb-8350-7a082c01652e.png)

Could you please verify again?

**Comment by pierrom** [comment]
OK thank you for checking.  I will close.
