### ISSUE TITLE
List & List Items (Platform): missing examples

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4112]
#### Briefly describe your proposal.
Missing examples: 

List:
- text truncation
- text wrapping
- ~~disabled state for group header~~

Object list item:
- text/key attribute/title/status truncation

Display list item:
- label/text truncation

**Comment by sKudum** [comment]
Hi @Seamoo13 , 

Regarding:   **disabled state for group header**

Group header is meant to display group header as per fioir, it does not have states. 

<img width="678" alt="2020-12-16_11-49-42" src="https://user-images.githubusercontent.com/53487468/102312564-f3078c80-3f94-11eb-8179-8fcebcc98e8b.png">

**Comment by Seamoo13** [comment]
> Hi @Seamoo13 ,
> 
> Regarding: **disabled state for group header**
> 
> Group header is meant to display header info as per fiori, it does not have states.
> 
> <img alt="2020-12-16_11-49-42" width="678" src="https://user-images.githubusercontent.com/53487468/102312564-f3078c80-3f94-11eb-8179-8fcebcc98e8b.png">

Ok, thanks. I crossed it off the list.
