### ISSUE TITLE
fd-multi-input keybord arow navigation not working

### ISSUE THREAD

**Issue by KristapsLeitens** [SAP/fundamental-ngx#4113]
Hi!
fd-multi-input control keyboard arrow navigation is not working.
https://sap.github.io/fundamental-ngx/#/core/multi-input

Issue is reproducible if you follow these steps:
1)Load the fundamental-ngx link provided above and press:
![image](https://user-images.githubusercontent.com/4891309/102216911-8634b980-3ee4-11eb-90d1-fec6e2b3dc8c.png)
Arrow navigation in suggestion list is not working.
2)Close suggestion list and open it again. Then arrow navigation starts working.

To reproduce it you need to reload the page each time.

**Comment by g-cheishvili** [comment]
Works in latest RC and will be included in next release
