### ISSUE TITLE
User is able to enter decimal value in step input component 

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#4121]
Description: User is able to enter decimal value in step input component 
Expected result: according to test cases - Decimal value is not allowed
Screenshot: ![image](https://user-images.githubusercontent.com/74654139/102342683-43391b80-3fa2-11eb-82b5-40f5540b0dce.png)

**Comment by dimamarksman** [comment]
Please see [this requirement](https://experience.sap.com/fiori-design-web/step-input/#display-value)

```
The step input control allows decimal values and can control the number of digits shown after the decimal point (property: displayValuePrecision).
```
