### ISSUE TITLE
Common JS Behavior for Breadcrumbs

### ISSUE THREAD

**Issue by tjbutz** [SAP/fundamental-ngx#4126]
#### Is this a bug, enhancement, or feature request?

feature request

#### Briefly describe your proposal.

As reusing Web Component to share behavior between Fundamental Styles impl. e.g. Angular, React and 3rd Party consumers e.g. [Luigi Micro Frontend Framework](https://luigi-project.io/) (using [svelte](https://svelte.dev/)) is currently not yet an option, we should at least start to discuss to share JS files between frameworks.

As [Luigi Micro Frontend Framework](https://luigi-project.io/) requires to implement the [Breadcrumb](https://sap.github.io/fundamental-ngx/#/core/breadcrumb) feature, it is a good opportunity to share some JS behavior, so that we don't have to reimplement behavior again and again.

**Comment by droshev** [comment]
I think Luigi already solved this in their repo
