### ISSUE TITLE
Bug: Dynamic Page - Navigation/Tab Bar not aligned with Visual Core when selected

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4127]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Dynamic Page - Navigation/Tab Bar not aligned with Visual Core, when selected, tab should be enabled in blue with blue bar below it.
![image](https://user-images.githubusercontent.com/71797052/102409900-aaf06600-3fa4-11eb-93d0-fffd789bc1fd.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/platform/dynamic-page
Click on any button: "Click to open full page" and see error
![image](https://user-images.githubusercontent.com/71797052/102410126-f30f8880-3fa4-11eb-8d79-7636dfb7a1a3.png)

**Comment by kavya-b** [comment]
This issue is due to underlying Tab component and may be fixed with #4120

**Comment by kavya-b** [comment]
@pierrom this is now automatically fixed with #4120, please verify in latest [netlify](https://fundamental-ngx.netlify.app/#/platform/dynamic-page).

**Comment by pierrom** [comment]
Verified fixed - thanks
