### ISSUE TITLE
Bug: (core) Select component does not show initially selected item 

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#4130]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

Core `fd-select` component does not show selected item that is set on initial phase.

It can be reproduced only when `fd-option`s are static, when they are rendered via `ng-for` it works.

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-oe5qzw
#### Is there anything else we should know?
It start working if `fd-option` list is rendered via `ng-for` directive.

**Comment by puru-hk** [comment]
Tested with the version30.1 with this url https://stackblitz.com/run it is working fine.
