### ISSUE TITLE
New Feature: Assistance button on the Shellbar

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#4150]
####  Feature request

It would be good to have an assistance button like this:

![image](https://user-images.githubusercontent.com/74785804/102766712-ddbca480-437e-11eb-95e3-dbca4c38d1ef.png)

[example](https://sapbazar.com/articles/item/2169-sap-fiori-for-sap-s4hana-how-to-setup-the-user-assistant-in-your-s4hana-fiori-launchpad)

Thanks in advance

**Comment by droshev** [comment]
this can be done with the web assistant
