### ISSUE TITLE
BUG: Errors in console when import { PlatformDynamicPageModule } from '@fundamental-ngx/platform';

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#4151]
#### When I add import { PlatformDynamicPageModule } from '@fundamental-ngx/platform', in console I have the follow errors:
`
 Error: node_modules/@fundamental-ngx/platform/lib/components/search-field/search-field.component.d.ts:76:5 - error TS2610: 'disabled' is defined as an accessor in class 'BaseComponent', but is overridden here in 'SearchFieldComponent' as an instance property.
76     disabled: boolean;
       ~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/form/text-area/text-area.component.d.ts:18:9 - error TS2611: 'contentDensity' is defined as a property in class 'BaseInput', but is overridden here in 'TextAreaComponent' as an accessor.
18     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/panel/panel.component.d.ts:45:9 - error TS2611: 'contentDensity' is defined as a property in
class 'BaseComponent', but is overridden here in 'PanelComponent' as an accessor.
45     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/form/switch/switch/switch.component.d.ts:24:9 - error TS2611: 'contentDensity' is defined as
a property in class 'BaseInput', but is overridden here in 'SwitchComponent' as an accessor.
24     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/form/step-input/base.step-input.d.ts:38:9 - error TS2611: 'contentDensity' is defined as a property in class 'BaseInput', but is overridden here in 'StepInputComponent' as an accessor.
38     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/form/input-group/input-group.component.d.ts:29:9 - error TS2611: 'contentDensity' is defined
as a property in class 'BaseInput', but is overridden here in 'InputGroupComponent' as an accessor.
29     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/form/combobox/commons/base-combobox.d.ts:36:9 - error TS2611: 'contentDensity' is defined as
a property in class 'CollectionBaseInput', but is overridden here in 'BaseCombobox' as an accessor.
36     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/list/list.component.d.ts:93:9 - error TS2611: 'contentDensity' is defined as a property in class 'CollectionBaseInput', but is overridden here in 'ListComponent' as an accessor.
93     set contentDensity(contentDensity: ContentDensity);
           ~~~~~~~~~~~~~~[0m
node_modules/@fundamental-ngx/platform/lib/components/form/multi-input/base-multi-input.d.ts:36:9 - error TS2611: 'contentDensity' is defined as a
property in class 'CollectionBaseInput', but is overridden here in 'BaseMultiInput' as an accessor.
36     set contentDensity(contentDensity: ContentDensity);
`

The code compile anyway

Angular version: 10.2.1
Fundamental-NGX version: 0.24.2 (but I tried also with the 0.25.1 and it is the same)

**Comment by JKMarkowski** [comment]
Issue was solved, by changing typescript version from `4.X` to `3.9.7`. Typesciprt@4.X will be supported soon with ng@11.
