### ISSUE TITLE
Bug: Currencies and units of measurements on all the Tables columns are not correct, not consistent, and not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4161]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Currencies and units of measurements on all the Table columns should right-aligned. Table header currencies and amounts s/b right-aligned. All rows under Table header columns should follow suit and also be right-aligned.
![image](https://user-images.githubusercontent.com/71797052/102824406-9e4b8380-4391-11eb-8eef-85cb29c43f4e.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/table
Scroll to any of the Table examples and see error below
![image](https://user-images.githubusercontent.com/71797052/102824521-dd79d480-4391-11eb-8d7e-9815e02782e9.png)

**Comment by xandrio** [comment]
@skocharian please take a look for quick review

> _Currencies and units of measurements on all the Table columns should right-aligned._

Currently I don't see any identifier for currency and units of measurements.
![currency_custom](https://user-images.githubusercontent.com/5276786/114877686-302b4080-9e08-11eb-8246-00835c4907be.png)
![currency_type](https://user-images.githubusercontent.com/5276786/114877878-64066600-9e08-11eb-963b-338b8d3f5726.png)

Cell value is passed as value and I don't see usage of any currency pipes etc.
BTW column have optional property for text alignment:

![currency_custom_3](https://user-images.githubusercontent.com/5276786/114879741-24d91480-9e0a-11eb-8ecf-332136a5a027.png)
![currency_custom_4](https://user-images.githubusercontent.com/5276786/114879771-29053200-9e0a-11eb-97fc-9d25bb08b5b7.png)

**Comment by platon-rov** [comment]
@xandrio answer should help. I don't see a bug here.

**Comment by puru-hk** [comment]
@pierrom could you please retest this issue.

**Comment by pierrom** [comment]
Verified. I will close. Thanks.

**Comment by pierrom** [comment]
Verified and closed. Thanks.

From: Purushothamhk ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Monday, May 24, 2021 at 4:54 AM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Assign ***@***.***>
Subject: Re: [SAP/fundamental-ngx] Bug: Currencies and units of measurements on all the Tables columns are not correct, not consistent, and not aligned with Visual Core (#4161)


Assigned #4161<https://github.com/SAP/fundamental-ngx/issues/4161> to @pierrom<https://github.com/pierrom>.
