### ISSUE TITLE
Bug: Checkbox is missing on left most column on all the rows on Single Row Selection of Table (Platform)

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4162]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Checkbox is missing on left most column on all the rows on Single Row Selection of Table (Platform)
![image](https://user-images.githubusercontent.com/71797052/102841034-fe095500-43b8-11eb-9a76-3a25bb97305a.png)
Visual Core says should be like below.
![image](https://user-images.githubusercontent.com/71797052/102841224-648e7300-43b9-11eb-9294-ae69a5509884.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/table
Scroll to: Single Row Selection Table and see error
![image](https://user-images.githubusercontent.com/71797052/102841164-40cb2d00-43b9-11eb-8777-59b74d93bfb5.png)

**Comment by xandrio** [comment]
@pierrom can you take a look first for documentation?
https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Selection
I guess documentation sample should be fixed first.

![single_selection_sample](https://user-images.githubusercontent.com/5276786/114906205-7a212000-9e22-11eb-96d5-111a1dfaf0b1.png)

**Comment by pierrom** [comment]
Not needed, will close. Thanks
