### ISSUE TITLE
Bug: On Table for Platform - entire row need to exhibit interaction hover state. Currently it is just the single left-most column

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4163]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On Table for Platform - entire row need to exhibit interaction hover state. Currently it is just the single left-most column. This is for Single Row Selection, Multiple Row Selection, Column Grouping, and Column Freezing examples on Table.
![image](https://user-images.githubusercontent.com/71797052/102842963-154a4180-43bd-11eb-8135-debdf4572032.png)

Visual Core states the following:
![image](https://user-images.githubusercontent.com/71797052/102843099-58a4b000-43bd-11eb-9e24-64076f184ed9.png)
![image](https://user-images.githubusercontent.com/71797052/102843112-60fceb00-43bd-11eb-85dc-8ba277a554f9.png)
![image](https://user-images.githubusercontent.com/71797052/102848773-6e6ca200-43ca-11eb-948c-3242d9bdaa1a.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/table
Scroll down to: Single Row Selection and Multiple Row Selection examples
See error
![image](https://user-images.githubusercontent.com/71797052/102843061-4460b300-43bd-11eb-9eb5-04f3029b04e3.png)

**Comment by platon-rov** [comment]
Fix at the level of fundamental-styles implemented with [commit](https://github.com/SAP/fundamental-styles/commit/d05754d08857a6f6b5be8f9fa5f27f0c2c2c2fdb). Fixing in scope of fundamental-ngx should be postponed until new version of fundamental-styles (v0.17.0-rc.42) will be used.

**Comment by platon-rov** [comment]
Fix at the level of Fundamental Styles was enough.
