### ISSUE TITLE
Bug: Table Column alignment not consistent and not aligned with Visual core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4164]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Table Column alignment not consistent and not aligned with Visual core. Currencies and units of measurements should be right-aligned. Everything else is left-aligned.
![image](https://user-images.githubusercontent.com/71797052/102854882-54d25700-43d8-11eb-812b-81e6ee6ba313.png)
![image](https://user-images.githubusercontent.com/71797052/102854937-77647000-43d8-11eb-8cef-25a85757e118.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.25.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/table
Scroll to: Default Table, Single Row Selection, Multi Row Selection, Column Sorting, Column Filtering, Column Grouping, Column Freezing.
![image](https://user-images.githubusercontent.com/71797052/102855163-fe194d00-43d8-11eb-90cc-90145a9a31f8.png)

**Comment by platon-rov** [comment]
We have an additional `align` input property for the table column so we can set text-align for that column. That was done for the examples you've mentioned. We can adjust examples but seems like there no fix needed.

**Comment by platon-rov** [comment]
As I mentioned in the previous reply - for the table (platform) column component we have the `align` property which can be set if align other than `to the left` needed. The ticket should be closed.

**Comment by puru-hk** [comment]
@pierrom Please verify this issue from your side

**Comment by pierrom** [comment]
Verified. I will close. Thanks

**Comment by pierrom** [comment]
Verified. I will close. Thanks

From: Purushothamhk ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Monday, May 24, 2021 at 8:15 AM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP/fundamental-ngx] Bug: Table Column alignment not consistent and not aligned with Visual core (#4164)


@pierrom<https://github.com/pierrom> Please verify this issue from your side

**Comment by pierrom** [comment]
Verified and closed. Thanks.

From: Purushothamhk ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Monday, May 24, 2021 at 8:16 AM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP/fundamental-ngx] Bug: Table Column alignment not consistent and not aligned with Visual core (#4164)


Reopened #4164<https://github.com/SAP/fundamental-ngx/issues/4164>.

**Comment by pierrom** [comment]
Verified and closed. Thanks.

From: manjunathanagaraj ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Monday, May 24, 2021 at 4:52 AM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Assign ***@***.***>
Subject: Re: [SAP/fundamental-ngx] Bug: Table Column alignment not consistent and not aligned with Visual core (#4164)


Assigned #4164<https://github.com/SAP/fundamental-ngx/issues/4164> to @pierrom<https://github.com/pierrom>.
