### ISSUE TITLE
documentation is not responsive

### ISSUE THREAD

**Issue by mscud** [SAP/fundamental-ngx#417]
![screenshot_20190116-124242](https://user-images.githubusercontent.com/545229/51255359-594b9500-19a3-11e9-993b-07f63b726530.png)

**Comment by mikerodonnell89** [comment]
possible duplicate of https://github.com/SAP/fundamental-ngx/issues/347

**Comment by MattL75** [comment]
I think #347 is requesting a full collapsing feature on the sidenav component while this issue is commenting on a broken docs site for mobile
