### ISSUE TITLE
improve component version and status

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#419]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
improve the versioning documentation for each component. We need to document in details the components how close they are to Fiori 3, whether a new design update is about to come, how experimental the component is, how stable the API is

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7.1, fundamental-ngx 0.0.26 beta

see some screenshots how it is done in fundamental-ui
<img width="528" alt="screen shot 2019-01-16 at 11 00 00 am" src="https://user-images.githubusercontent.com/4380815/51261359-13c8a100-197e-11e9-917c-173bd9f28603.png">
<img width="316" alt="screen shot 2019-01-16 at 10 59 53 am" src="https://user-images.githubusercontent.com/4380815/51261360-14613780-197e-11e9-9ade-dcc626737d10.png">
<img width="448" alt="screen shot 2019-01-16 at 10 59 47 am" src="https://user-images.githubusercontent.com/4380815/51261361-14613780-197e-11e9-9aa3-2d142b08423d.png">

**Comment by MattL75** [comment]
Whoever picks this up could also revise which status icon is assigned to each component in the sidebar.

**Comment by droshev** [comment]
not relevant anymore
