### ISSUE TITLE
Test: (Platform) – ApprovalFlowNodeComponent tests failed

### ISSUE THREAD

**Issue by olshansky** [SAP/fundamental-ngx#4209]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
`ApprovalFlowNodeComponent` tests failed _(skipped for unblocking CI)_
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx: 0.26.0
#### Please provide relevant source code if applicable.
`libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.spec.ts`
#### Is there anything else we should know?
- Firefox 84.0 (Mac OS 10.15) ApprovalFlowNodeComponent should add parent-approved class if parent node is approved

**Comment by kavya-b** [comment]
this was fixed in #5302 and is no longer skipped
