### ISSUE TITLE
Form Input component enhanhacement

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#421]
#### Briefly describe your proposal.

Input components in general here does not support template driven (TDF) or reactive driven forms (RDF).  Even 2-way binding for value could work for simple cases but this is not angular way.

When using them in angular form and trying to levarange  `ngModel` or `formControl`  I can not. 

This applies for any inputs based component starting from input fields, dropdown, date pickers, etc..

**Comment by fkolar** [comment]
Toggle is just the simple state YES/NO, True/false soprobably not much. 
I know I would probably add the onChange event but that's about it.

**Comment by MattL75** [comment]
@mikerodonnell89 Can we consider this done?

**Comment by MattL75** [comment]
Closing this. Most (if not all) components that qualify as form components are now compatible with Angular forms.
