### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#422]
#### Briefly describe your proposal.
Let's thing how to bring list component into enterprise level. 
 - Usually list needs to handle large number of items,  
 - They need to support single and multiselection. 
 - Developers needs to be able to customize the way item is rendered `ng-template `
 - Virtual scrolling and lazy loading. 

We dont need to reinvent all this @angular/cdk its good patern library .

**Comment by MattL75** [comment]
- [x] Usually list needs to handle large number of items
- [x] They need to support single and multiselection
- [x] Developers needs to be able to customize the way item is rendered ng-template (already doable)
- [ ] Virtual scrolling and lazy loading.

Considering that virtual scrolling has its own issue thread, I will close this
