### ISSUE TITLE
fix: (Core) Rating indicator Rtl display of dynamicTextIndicator need to be corrected

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#4228]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
dynamicTextIndicator text in Rtl mode is not correct

<img width="1117" alt="Screenshot 2021-01-04 at 5 00 07 PM" src="https://user-images.githubusercontent.com/57661487/103530923-5870de00-4eae-11eb-95b2-4ee1e0dc9957.png">

Expected:
(5 ooofff 4) in Rtl mode instead of (ooofff 5 4)

#### Is there anything else we should know?

fiori:
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2035269535

**Comment by mykolavorobiov** [comment]
@DeepakSap14 For correct view in RTL you should use rtl language (https://www.andiamo.co.uk/resources/right-to-left-languages/).

For example you can combine google translate (Urdu) and switch to RLT direction
![image](https://user-images.githubusercontent.com/38053194/104438734-ff353880-5598-11eb-90e8-1ba49a0cebf5.png)


Only one thing, in this example 
![image](https://user-images.githubusercontent.com/38053194/104438946-3f94b680-5599-11eb-9dcc-3e95ce84adeb.png)
I show custom label between scores, and if you want to check, please change to normal `of` word
