### ISSUE TITLE
Bug: (Platform) File Uploader – asterisk not in a proper place in IE11

### ISSUE THREAD

**Issue by olshansky** [SAP/fundamental-ngx#4234]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
![image](https://user-images.githubusercontent.com/14160094/103533025-0b344280-4e95-11eb-870f-51c2f47236aa.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx: 0.26.0-rc.31
#### If this is a bug, please provide steps for reproducing it.
Open [File Uploader Reactive example ](https://fundamental-ngx.netlify.app/#/platform/file-uploader#file-uploader-disabled) in IE11 and you will see that the red asterisk not in a proper place

**Comment by Lokanathan-k** [comment]
Hi Suren, 
On analysis found that the teaming is applied from required * value is getting from fd-form-field component.
