### ISSUE TITLE
fix(platform): Approval flow phase-1 issues

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#4235]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

1).Stack blitz error=Import error, can't find file:
./approval-flow-example-data-source.class

<img width="850" alt="2021-01-04_18-01-03" src="https://user-images.githubusercontent.com/53487468/103535578-fb2d5a80-4eb6-11eb-88f9-bf98f53effa6.png">

2).Fiori elements has dotted focus not blue border.

<img width="385" alt="2021-01-04_15-41-58" src="https://user-images.githubusercontent.com/53487468/103535591-02ecff00-4eb7-11eb-99c4-cd15b8a42946.png">

3).Object status is displaying a blue border as well. 
<img width="593" alt="2021-01-04_15-43-38" src="https://user-images.githubusercontent.com/53487468/103535599-07191c80-4eb7-11eb-8728-e1fb0f24f0c9.png">

4).As per my understanding status is not actionable item here. Are we intentionally giving it as actionable? If yes, how it is different from card level action.

<img width="593" alt="2021-01-04_15-43-38" src="https://user-images.githubusercontent.com/53487468/103535611-0e402a80-4eb7-11eb-8e1a-4230e4f745ea.png">

5).Are we supporting only desktop mode? Expect desktop other views are breaking.

6).Console shows unwanted logs and errors (inconsistent). 

<img width="1015" alt="2021-01-04_16-44-04" src="https://user-images.githubusercontent.com/53487468/103535622-14360b80-4eb7-11eb-97ab-e34ffc2ad262.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
10
latest 0.26.0-rc.28
#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/platform/approval-flow
Select any example and can observe above issues on click of item.

**Comment by manjunathanagaraj** [comment]
1. Needs to be fixed.
2. Needs to explore further before deciding it as a bug. Requires UX guys consultation.
3 and 4. Needs to be fixed. The styling(blue color border) on object status should not be applied.
5. current only desktop version. For other form factors we need visual specs.
6. to be fixed.

**Comment by DeepakSap14** [comment]
1.Stack blitz error=Import error, can't find file:
-- This issue is coming for all components where a class data file is needed for component. Needs to be investigated further and fixed for all affected examples in components.

2. fixed
3. fixed
4. Non-reproducible
5. NA
6. non-reproducible
