### ISSUE TITLE
fix(platform): Approval flow phase 1 accessibility issues

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#4236]
#### Is this a bug, enhancement, or feature request?
bugs

#### Briefly describe your proposal.
1).Screen reader is reading the undisplayed/hidden node details.

2).Not able to access nodes and avatar on tab.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

10
latest 0.26.0-rc.28
#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/platform/approval-flow
Select any example and can observe above issues on click/tab of item with screen readers.

**Comment by DeepakSap14** [comment]
1. fixed
2. non-reprocible
