### ISSUE TITLE
Data handling for UI component

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#424]
#### Briefly describe your proposal.

When we work with large dataset if thats for autocomplete (search inpu) component, list or datatable, developers usually will not pass a list of values. 
We need to be able to implement some datasource pattern that you implement and provide your reactive feed of data.

**Comment by mikerodonnell89** [comment]
Could you give an example of this "datasource pattern"?  Not really sure what you mean here

**Comment by fkolar** [comment]
When we work with allot of data you dont want to really do:

```
<my-data-list [list]="users"></my-data-list>
```

Cuz loading 1000 users is fine but to load 100 000 it might be different thing. So you need to some mechanism to fetch data incrementally. 

So you can have something like this:
```
<my-data-list [list]="users" (onLoad)="loadMoreUsers($event)"></my-data-list>
```
When you scroll down it can fetch more data. But this probably simple implementation. What I woudl use is  is to have more:

```
<my-data-list [dataSource]="myGraphQLDS"></my-data-list>
```
Datasource is just a concept how to generify of getting data.  You still should keep the both (keep the list) cuz you will have usecases where someone will load small subset of data. 

You describe am interface between a component and application and component will use this path how to fetch and query the data. And if application decides to talk to ODATA you will have specific implementation if you decide you want graphQL it know how to talk to GQL and so on. 

Just think of it you take the data manipulation logic out of the compoent. You will need the same for datatable and other usecases. 

You can play with this more to have different Data providers. I think you can find allot of examples in any enterprise application DataSource is common pattern

**Comment by salarenko** [comment]
@fkolar I think our `InfiniteScrollDirective` provides such functionality.
See: https://sap.github.io/fundamental-ngx/#/core/infiniteScroll

**Comment by droshev** [comment]
let's open this once it is needed by someone
