### ISSUE TITLE
fix: (Core) Object Status are not visible if use High Contrast Black theme

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#4242]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Object Statuses are not visible if use High Contrast Black theme
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
NA
#### If this is a bug, please provide steps for reproducing it.
1. Go to http://localhost:4200/fundamental-ngx#/core/object-status
2. Select High Contrast Black theme
3. Go to any example and turn on `Switch background`

Part of Object Statuses cannot be seen

**Comment by Lokanathan-k** [comment]
HI Deno, 
on checking found the theming is applied as per the HCB and HCW configuration, But when switching the background i could see the information (@sapUiHcInformativeColor) white color merges with the background, is this expected behaviour or does it need changes from the fiori theming team.

**Comment by Lokanathan-k** [comment]
@manjunathanagaraj @droshev on checking the latest the issue has been fixed, and its not reproducible. 

@puru-hk can u pls test this once and close this issue.

**Comment by puru-hk** [comment]
Verified in RC 71 netlify url it is working. Hence closed this issue.
