### ISSUE TITLE
Fixed card layout: Color of the KPI value is wrong

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#4243]
**Describe the bug**

If we want to present a positive state, the KPI values should be green; negative state - red; neutral - grey.
But we don't use grey semantic color for KPI value and referring to a positive state. 
Fiori ref: 
https://ux.wdf.sap.corp/fiori-design-web/analytical-card/

**Comment by puru-hk** [comment]
Verified it is changes are not reflecting in the fixed card layout. @DeepakSap14 can you update the fixed card examples

**Comment by puru-hk** [comment]
This issues is fixed is card. But in fixed card layout it is not fixed. See the attachment.
 ![Screenshot 2021-05-25 at 10.09.37.png](https://images.zenhubusercontent.com/5f4c9866d9d21de4c96444ff/778378aa-13d9-4cd1-808e-d1618fb22bef)

**Comment by DeepakSap14** [comment]
@puru-hk , it has been merged few hours back, and currently netlify is not reflecting it.
have to re-check when netlify is updated.
you can check the PR build deployment here https://deploy-preview-5392--fundamental-ngx.netlify.app.

**Comment by puru-hk** [comment]
@DeepakSap14 I have check the above url still issue is not completely fixed as per the @daisy-yovcheva attachment.

**Comment by DeepakSap14** [comment]
@puru-hk 
please verify this, if any issue you can reopen it.

**Comment by puru-hk** [comment]
@daisy-yovcheva I have tested in this url (https://deploy-preview-5509--fundamental-ngx.netlify.app/#/core/fixed-card-layout) it is working as expected. Please verify from your side and close this issue.
