### ISSUE TITLE
bug: (Core) MultiInput: add empty token and can't remove it

### ISSUE THREAD

**Issue by mykolavorobiov** [SAP/fundamental-ngx#4245]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Allow the creation of new tokens without value and can't remove it.

![multi-input-issue1](https://user-images.githubusercontent.com/38053194/103622357-4ab76900-4f3f-11eb-8f27-75f3b717d378.gif)

#### If this is a bug, please provide steps for reproducing it.
1) Focus MultiInput search field
2) Press enter few times

#### Please provide relevant source code if applicable.
 v 0.26.0-rc.36

**Comment by nikvalor** [comment]
checked this issue at v 0.30.1-rc.63 
not reproduced
