### ISSUE TITLE
Platform: BaseDataProvider not exported

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#4246]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

On the application level we need to enable BaseDataProvider to be used and define main data streams. 

<img width="438" alt="Screen Shot 2021-01-05 at 9 57 28 AM" src="https://user-images.githubusercontent.com/17149942/103626812-03c87400-4f3d-11eb-8541-a1124edbb920.png">

**Comment by droshev** [comment]
Can someone check whether it has been fixed and if so - close the issue?
