### ISSUE TITLE
checkbox on focus is creating extra space.

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#4250]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
focusing on checkbox is creating a extra space as shown in image below in latest main code.
<img width="383" alt="2021-01-05_17-08-10" src="https://user-images.githubusercontent.com/53487468/103642166-c681d780-4f78-11eb-9c29-eaf2479fe469.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
ngx: 0.26.0-rc.34
angular:10

**Comment by DeepakSap14** [comment]
This seems to be fixed.
QA team, please verify and close it.

**Comment by puru-hk** [comment]
Verified in the recent ngx version rc 53 this is fixed. Hence closed.
