### ISSUE TITLE
Platform: Combobox Usability and MetaUI compatibility

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#4253]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

When we try to use combobox in the application we have to do one additional thing which is importing the `PlatformComboboxMobileModule ` to make it work with `DynamicComponentService`. 

```ts
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    PlatformComboboxModule,
    PlatformComboboxMobileModule,
  ],
```

I think this is extra overhead considering we reference directly the component  inside anyway.:

```ts
  private _setUpMobileMode(): void {
        this._dynamicComponentService.createDynamicComponent(
            { listTemplate: this.listTemplate, controlTemplate: this.controlTemplate },
            ComboboxMobileComponent,
            { container: this.elementRef.nativeElement },
            { injector: Injector.create({ providers: [{ provide: COMBOBOX_COMPONENT, useValue: this }] }) }
        );
    }

```

Component should be responsive by default. For MetaUI where we do create dynamic components , we just need a Component for Combobox instantiate it on the fly once and use it. 

In order to load it lazily we could do something like  Dima (@valorkin) used it in the AppShell code. Here is the snipet from my other app where I am testing combobox. 

```ts
  private async renderWithCompilerNoComboModuleImportNeeded(): Promise<void> {
    const module  = await this.compiler.compileModuleAsync(PlatformComboboxMobileModule);
    let ngModuleRef = module.create(this._injector);
    const cFac = ngModuleRef.componentFactoryResolver.resolveComponentFactory(ComboboxMobileComponent)
    const component: ComponentRef<ComboboxComponent>  = this.vc.createComponent(cFac);

    component.instance.dataSource = this.dataSource;
    component.instance.name = 'standard2';
    component.instance.placeholder = 'standard2 placeholder';
  }
```

You can see working example in the: https://github.com/fkolar/fiori-combo-test

**Comment by Betrozov** [comment]
There are about 12 components that use the same approach.
What do you think @fkolar, we need to apply your approach to all components or only for Combobox?

**Comment by valorkin** [comment]
this is something we will have to discuss and apply to all 12 components
importing one module should be enough

**Comment by droshev** [comment]
Can you re-evaluate and if needed fix, otherwise close the issue
