### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#426]
#### Is this a bug, enhancement, or feature request?
Feature

#### Briefly describe your proposal.
One of the key requirements is `i18n`. Even Angular now provides some limitted support along with its CLI but its not yet ready. Currently it relies heavily on static strings which you must have already in HTML templates. For most of the simple usecases it works, but in enterprise you must be able to retrieve your translation string at the runtime.

If you need dynamicity then people use ngx-translate, where the guy behind it is now at Google and working runtime version. 

Not sure if there is any other solution to this?

**Comment by MattL75** [comment]
I'm not sure what you mean, could you please provide a bit more detail? Do you mean a system like ngx-translate? Or just support for different languages on the calendar, time picker... etc?

**Comment by fkolar** [comment]
What I meant and Just you already mention you need to have a way how to provide a translation to the calendar, select, datatable, or any components that needs it. 
Some translation can be static some can be dynamic
