### ISSUE TITLE
Resizable Card Layout - develop layout component

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4262]

**Comment by manjunathanagaraj** [comment]
Implement resizable card layout as per Fiori3 guidelines.


Fiori3 guidelines: https://ux.wdf.sap.corp/fiori-design-web/resizable-card-layout-overview-page/
Fiori3 visual specs: https://wiki.wdf.sap.corp/wiki/display/visualcore/OVP+Resizable+Layout

**Comment by DeepakSap14** [comment]
in-progress: Development for cards data showing increase in data and decrease in data while resize.
