### ISSUE TITLE
User Actions Menu - Tech Spec

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4268]

**Comment by manjunathanagaraj** [comment]
Define technical specs based on Fiori3 guidelines to understand the development approach.

Fiori3 guidelines: https://ux.wdf.sap.corp/fiori-design-web/launchpad/#user-menu

**Comment by mykolavorobiov** [comment]
One more helpful link
https://experience.sap.com/fiori-design-web/services/#user-menu-on-the-home-page

**Comment by manjunathanagaraj** [comment]
Tech spec presented, approved.
