### ISSUE TITLE
Bug: Menu (core) is not working standalone on stackblitz

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#4279]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
`fd-menu` is not working on stackblitz.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@angular/core 10.2.3
@fundamental-ngx/core 0.25.1

#### If this is a bug, please provide steps for reproducing it.
1. Open [example](https://stackblitz.com/edit/angular-8hv5b6?file=src/app/menu-example.component.html)
2. Click Menu button
3. Menu is not opened and error is thrown in the console. 
![image](https://user-images.githubusercontent.com/3263744/103794221-221d9500-504d-11eb-9e35-5a0d0015424a.png)

**Comment by OleksiyDrozdov** [comment]
![image.png](https://images.zenhubusercontent.com/60492e1f104385ee3fc0608a/cdc28717-46b0-4419-bbac-984d4c7634ce)

Issue is not reproducible.

**Comment by maxym-valor** [comment]
@OleksiyDrozdov reproducible for Mobile Example

![image](https://user-images.githubusercontent.com/83698366/126970645-a9f480ce-11f7-4104-b7cb-02b0ef05a150.png)
