### ISSUE TITLE
fix: (Platform) required/mandatory field is not being read for all form elements

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#4280]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Screen reader not able to identify required?mandatory field.
This needs to be fixed for all form field elements like checkbox, radio, text-area, date-picker, multi-input etc.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10

#### If this is a bug, please provide steps for reproducing it.
Currently screen reader does not identify mandatory form field.

**Comment by puru-hk** [comment]
Tested in this url https://deploy-preview-5627--fundamental-ngx.netlify.app/#/platform for  checkbox, radio, text-area, date-picker, multi-input all the mandatory field read by screen reader as "Required"
