### ISSUE TITLE
fix: (Core) add rtlService to combobox

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#4283]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
On using rtl mode, rtl is not getting applied on suggestion popup

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10

#### If this is a bug, please provide steps for reproducing it.
<img width="1537" alt="Screenshot 2021-01-07 at 10 54 50 AM" src="https://user-images.githubusercontent.com/57661487/103854591-d8798c80-50d6-11eb-938f-25136b58d443.png">

**Comment by JKMarkowski** [comment]
@DeepakSap14 Popover is at under body level
![image](https://user-images.githubusercontent.com/26483208/104448046-f2b2df00-559c-11eb-9259-2c93b4ea334e.png)

Can you check if adding `dir=rtl` into body tag will solve it?

**Comment by DeepakSap14** [comment]
No, it is not solving the issue even after adding dir="rtl" on body tag.

<img width="568" alt="Screenshot 2021-01-13 at 6 04 55 PM" src="https://user-images.githubusercontent.com/57661487/104453161-032d7e80-55ca-11eb-9fb7-fff0c2980ad9.png">

**Comment by DeepakSap14** [comment]
This was  application issue. it was fixed and closed.
