### ISSUE TITLE
Thumbnail component enhancement

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4284]
Thumbnail component needs following enhancements as per the feedback received by 1p team:
- A pop up modal dialog to show the thumbnail images
- A carousel within, to show the main image with option to slide through the rest of the images

Here is the visual specs from design team: https://www.figma.com/file/eUbZWsRJ1PNAvd78IiP8qi/Item-detail-page?node-id=206%3A30

**Comment by manu-kr** [comment]
Thumbnail version 2 component has dependency on Dialog and Carousel component, and it require major style changes.
as per the below visual spec specified in the below link.

https://www.figma.com/file/eUbZWsRJ1PNAvd78IiP8qi/Item-detail-page?node-id=206%3A30

**Comment by manu-kr** [comment]
Working on style changes for Thumbnail version 2 component 40% style changes completed.

**Comment by manjunathanagaraj** [comment]
Target sprint for PR merge is sprint56
