### ISSUE TITLE
Key Value and Form facets - component development

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4286]
Following is the scope:
- key value facets
- Form facets
- Image facets
- Rating indicator facets

**Comment by kavya-b** [comment]
Will be developing component in core. 
Denoland team will get back with confirmation on whether to keep a separate documentation page for Facets.
cc: @droshev @InnaAtanasova @JKMarkowski @manjunathanagaraj

**Comment by kavya-b** [comment]
carry forward to sprint 58
