### ISSUE TITLE
Avatar glyph doesn't work inside a card component

### ISSUE THREAD

**Issue by brendandobbs** [SAP/fundamental-ngx#4293]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

"@angular/animations": "^11.0.7",
    "@angular/cdk": "^11.0.3",
    "@angular/common": "11.0.0",
    "@angular/compiler": "11.0.0",
    "@angular/core": "^11.0.7",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "^11.0.7",
    "@angular/platform-browser": "^11.0.7",
    "@angular/platform-browser-dynamic": "^11.0.7",
    "@angular/router": "^11.0.7",
    "@fundamental-ngx/core": "v0.25.1"

#### If this is a bug, please provide steps for reproducing it.

When I add the avatar component to a card component the default glyph is displayed and now the one specified in the avatar component

Example that doesn't work:
```
<fd-card>
    <fd-card-header>
        <fd-avatar size="s" [glyph]="'sales-order'"></fd-avatar>
        <h2 fd-card-title>Sales Orders</h2>
    </fd-card-header>
    <fd-card-content>
        <ul>
            <li>test</li>
        </ul>
    </fd-card-content>
</fd-card>
```
Example that works (outside of fd-card)....

```
<fd-avatar size="s" [glyph]="'sales-order'"></fd-avatar>
```

This screen shot shows the working avatar and the not working avatar
![image](https://user-images.githubusercontent.com/5688693/104016899-0df1a900-51af-11eb-8bd4-dfdad57ace06.png)

#### Please provide relevant source code if applicable.

See above

**Comment by droshev** [comment]
@brendandobbs thanks for the issue. It has been fixed with version `0.27.0`
