### ISSUE TITLE
bug: Card (core) compact font wrong size on IE

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4310]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
card component:
- for the compact text, the value on IE is 13.93px or 0.87rem, should be 14px or 0.875rem

https://fundamental-ngx.netlify.app/#/core/card
**Actual**:
![2021-01-11](https://user-images.githubusercontent.com/47522152/104211240-81f4b100-543c-11eb-9d7f-c99f7b7ace94.png)

**Expected**:
![2021-01-11_1](https://user-images.githubusercontent.com/47522152/104211258-86b96500-543c-11eb-8ae3-262bb6ad9f6c.png)

**Comment by DeepakSap14** [comment]
It is not reproducible, tested in IE 11 browser under windows machine.

**Comment by nikvalor** [comment]
Fixed
