### ISSUE TITLE
Search field. Cursor jumps back to the previously touched search input. 

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4314]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.26.0-rc.55
#### If this is a bug, please provide steps for reproducing it.
1. Open search field component 
2. Start entering a value in the search field.
3. Click into next search field input
AR: Cursor jump back to the first search input
ER: Cursor stays in the second input 
#### Please provide relevant source code if applicable.
Safari, Chrome, FF (IE not tested)
#### Is there anything else we should know?

https://user-images.githubusercontent.com/5969492/104298903-34745480-54cd-11eb-8c01-9bb731a8c37d.mov

**Comment by puru-hk** [comment]
Verify in this url https://deploy-preview-5633--fundamental-ngx.netlify.app/#/platform/search-field working as expected.
