### ISSUE TITLE
Search field. Click on search category is not invoked category list.

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4317]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.26.0-rc.52
#### If this is a bug, please provide steps for reproducing it.
1. Open  Platform => Search field component.
2. Scroll to the example of the search with the category.
3. Click on Category. 
AR: Click on search category is not invoked category list.
ER: Category list is opened. 
#### Is there anything else we should know?
**IE 11**

https://user-images.githubusercontent.com/5969492/104317754-0dc31780-54e7-11eb-82b8-a6941dec6c12.mov

**Comment by AntonOlkhovskyi** [comment]
Unskip _Search field should be able to set category if this option enabled_  e2e test after the fix.

**Comment by DeepakSap14** [comment]
Issue with IE has been fixed with https://github.com/SAP/fundamental-ngx/pull/5484.
please check.

**Comment by maxym-valor** [comment]
Issue is fixed, bug is not reproducable
