### ISSUE TITLE
NGX Docs - Table - Wrong row navigation icon

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-ngx#4319]
**Describe the bug**

In NGX Docs, navigable table rows show the icon `sap-icon://navigation-right-arrow`, but it should be `sap-icon://slim-arrow-right`, as in SAPUI5.
Please update the showcases in NGX Docs.

> Is this issue related to a specific component?

Table

> What version of the Fundamental Library Styles are you using?

Latest (0.14.0)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

DXP

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**Screenshots**

NGX Docs:
![image](https://user-images.githubusercontent.com/75482561/104327383-000f9100-54eb-11eb-93ac-b9f63f532fd6.png)

SAPUI5:
![image](https://user-images.githubusercontent.com/75482561/104165321-7df36f80-53f9-11eb-86fa-0176cac502cd.png)

**Comment by droshev** [comment]
it has been implemented in styles and brought to ngx
