### ISSUE TITLE
Bug: Popover examples doesn't work correctly

### ISSUE THREAD

**Issue by mykolavorobiov** [SAP/fundamental-ngx#4335]
#### Is this a bug, enhancement, or feature request?

Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

fundamental-ngx v 0.26.0-rc.61 

#### If this is a bug, please provide steps for reproducing it.

1) Simple popover example doesn't work.
  ![image](https://user-images.githubusercontent.com/38053194/104509544-7e0a8f80-55f2-11eb-8d84-a4170de55fe1.png)
 App module on `Stackblitz` has component has wrong component name.
 ![image](https://user-images.githubusercontent.com/38053194/104509632-99759a80-55f2-11eb-85a2-193f5710c9fb.png)

2) Simple popover doesn't work
Steps:
- fix previous issue
- try to open popover ![simple-popover-issue](https://user-images.githubusercontent.com/38053194/104510100-523bd980-55f3-11eb-82fe-118ce1bfb179.gif)
- ![image](https://user-images.githubusercontent.com/38053194/104509826-e3f71700-55f2-11eb-8fe0-44c88614d012.png)

3) https://fundamental-ngx.netlify.app/#/core/popover#dropdown doesn't open at all
![dropdown-popover-issue](https://user-images.githubusercontent.com/38053194/104510980-b317e180-55f4-11eb-9900-5616c20ec856.gif)

**Comment by dimamarksman** [comment]
`No component factory found...` issue should fixed via [this PR](https://github.com/SAP/fundamental-ngx/pull/4328)
