### ISSUE TITLE
Tabs used inside DynamicPageContent

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#4337]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
So user add `fd-tabs` component niside `DynamicPageContent` there is added inline styling like
![image](https://user-images.githubusercontent.com/26483208/104594957-33c8f300-5672-11eb-8773-87801381a9b3.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Newest

#### If this is a bug, please provide steps for reproducing it.
Stakcblitz: https://stackblitz.com/edit/angular-jbpbea?file=src/index.html

**Comment by kavya-b** [comment]
19/01 to 20/01- worked on changing fixed positioning design, and making dynamic page work with flexible column layout. Re-requested review after incorporating changes requested. 
21/01- Removed some unused code and fixed a failing test.
