### ISSUE TITLE
DateFormatParser missing

### ISSUE THREAD

**Issue by JensSteckhan** [SAP/fundamental-ngx#4352]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The update to 0.25 breaks, because unlike before, fundamental-ngx-core has no exported member 'DateFormatParser'.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx 0.25.2, angular 10.2.3

#### If this is a bug, please provide steps for reproducing it.
Try to reference DateFormatParser

#### Please provide relevant source code if applicable.
--

#### Is there anything else we should know?
Every single new release fundamental-ngx breaks my code. While I appreciate you sharing your library, it is frustrating.

**Comment by mpienkowski** [comment]
Same story here, there's nothing about that in breaking changes. Please provide some info on how to migrate
