### ISSUE TITLE
Loading spinner module not available

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#436]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

According to documentation (https://sap.github.io/fundamental-ngx/docs/loadingSpinner), loading spinner module should be available under 

`import { LoadingSpinnerModule } from 'fundamental-ngx';` which is not the case

#### If this is a bug, please provide steps for reproducing it.

![image](https://user-images.githubusercontent.com/12159534/51531183-1a06c380-1e3d-11e9-98df-3e9ef07e04e2.png)

**Comment by mikerodonnell89** [comment]
Can you ensure that you have the latest version of the library (0.0.29-beta) by checking your node_modules/fundamental-ngx/package.json file?  I am able to import the loading spinner module in a test project

**Comment by MattL75** [comment]
Closing for housekeeping. Let us know if your issue persists
