### ISSUE TITLE
Value help dialog: Extra icon is appear 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4363]
Description: Extra icon is appear 

Expected: Remove the extra icon

Screenshot: 
![image](https://user-images.githubusercontent.com/32538291/104900075-9f2c0100-59a1-11eb-946a-628513d258ae.png)

**Comment by mykolavorobiov** [comment]
@puru-hk It's not an extra icon. It's one of ways, how you can open value dialog and use result from it. You can call value help dialog from any components.
In this example I used simple button with click handler, 
![image](https://user-images.githubusercontent.com/38053194/105032263-3dca6780-5a5f-11eb-9b21-69fb965126dc.png)
After success with selection, you will have
![image](https://user-images.githubusercontent.com/38053194/105032107-fc39bc80-5a5e-11eb-8866-b5d685863532.png)

If I missed something, please reopen this issue with your description.
