### ISSUE TITLE
Value help dialog: Filter is not implemented for this example

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4364]
Description: Filter is not implemented for this example

Expected: Filter should be implemented. 

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/104905513-7bb88480-59a8-11eb-9c02-1f8101358b2a.png)

**Comment by mykolavorobiov** [comment]
@puru-hk This example shows different between existed data in table `Product id, Name, Product Code, City` and filters above table. As you can see, you have filters for `Name, Product Code, City`.
In this example, I disabled only `product id column`
![image](https://user-images.githubusercontent.com/38053194/105027817-e3c6a380-5a58-11eb-8190-84604c7a5cdf.png)

But you can configure with only one filter, but in table will show all data columns.

If you have any concerns or questions, please reopen this issue.
