### ISSUE TITLE
Manual testing of Table(phase1, 2 and 3) component

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4373]

**Comment by Seamoo13** [comment]
https://github.com/SAP/fundamental-ngx/issues/4408
https://github.com/SAP/fundamental-ngx/issues/4409
https://github.com/SAP/fundamental-ngx/issues/4410
https://github.com/SAP/fundamental-ngx/issues/4411
https://github.com/SAP/fundamental-ngx/issues/4412
https://github.com/SAP/fundamental-ngx/issues/4413
https://github.com/SAP/fundamental-ngx/issues/4414
https://github.com/SAP/fundamental-ngx/issues/4415
