### ISSUE TITLE
Technical specification for Dynamic Page in Core

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#4383]
#### Briefly describe your proposal.
As part of this issue we want to investigate the efforts needed to implement the component, the architecture of the component and the building blocks. 
The goal would be a clear vision of what needs to be done for this component and an estimation of the efforts needed.

**Comment by JKMarkowski** [comment]
API:
- Tabbed content should be changed to `fd-dynamic-page-content > fd-tab-list`
- More `ng-content` to make it more flexible
- Layout actions and global actions can be unified I think
- Naming convention with header and title can be changed - now header is collapsible subheader and title is header
- `fdp-dynamic-page-key-info` Can be just added as an Input `keyInfo` same as title/subtitle

Code:
-  A lot of query selectors - can be changed to viewchild/contentchild reference
- Dynamic page service can be optimised

Enhancements:
- Tabbed tablist support or example
- Check Virtual scroll to make it work like in [Sap Ui5](https://sapui5.hana.ondemand.com/#/entity/sap.f.DynamicPage/sample/sap.f.sample.DynamicPageFreeStyle)


Styles:
- `fd-dynamic-page__tabs--add-shadow` class is useless
- this is created from 2 toolbars - can be easly changed to one
![image](https://user-images.githubusercontent.com/26483208/106762035-b7ed1580-6635-11eb-81cc-b30e69e99c30.png)
