### ISSUE TITLE
Bug: Compact Combobox should also have compact dropdown select

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4384]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
 Currently, Compact Combobox is showing Cozy dropdown select
![image](https://user-images.githubusercontent.com/71797052/104976713-b45d5b80-59b2-11eb-84b3-9a55b4b787bd.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? 
v0.26.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/platform/combobox
Scoll down to: Standard Combobox
Click on Compact Combobox
See error
![image](https://user-images.githubusercontent.com/71797052/104976967-436a7380-59b3-11eb-9c7a-063aacd93b23.png)

**Comment by puru-hk** [comment]
@pierrom Could you please retest this issue.

**Comment by pierrom** [comment]
#4384 is fixed
