### ISSUE TITLE
Flexible Column Layout - the first separator disappears 

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#4395]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Flexible Column Layout left separator disappear

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest main branch

#### If this is a bug, please provide steps for reproducing it.
![flexible column layout](https://user-images.githubusercontent.com/4380815/105110259-3ff6eb00-5a8c-11eb-8dc3-bd14ce11f612.gif)

**Comment by InnaAtanasova** [comment]
This is not a bug!
