### ISSUE TITLE
Flexible Column Layout - expand column has wrong direction animation

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#4397]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Expand Column 3 has a wrong direction animation

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest main branch
#### If this is a bug, please provide steps for reproducing it.

Expand Column 3
![flexible-column-animation](https://user-images.githubusercontent.com/4380815/105111684-72561780-5a8f-11eb-8d11-1ca17f5c12e9.gif)

**Comment by kavya-b** [comment]
@puru-hk @Seamoo13 please verify this; it is no longer reproducible, most probably fixed in PR https://github.com/SAP/fundamental-ngx/pull/4960

**Comment by puru-hk** [comment]
Testes this issues now for expand column direction is right to left. Hence closing this issue.
