### ISSUE TITLE
Feed Input. Disabled Send button is skipped by Tab navigation.

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4398]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
The disabled Send button is skipped by Tab navigation. People who use screen readers will be never aware of its existence in this case.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.26.0-rc.86
#### If this is a bug, please provide steps for reproducing it.
1. Open Feed input component
2. In the first example click in feed-input input. 
3. Click the Tab button.
AR: Disabled Send button is skipped by Tab navigation.
ER: Tab focus should happen on feed input and (>) right arrow with styles as per Fiori3 visual specs.
#### Is there anything else we should know?

https://user-images.githubusercontent.com/5969492/105111717-32f8ec80-5aca-11eb-8010-fd7427c8d780.mov

**Comment by kavya-b** [comment]
closing as this issue was fixed and verified by QA in PR #4488
