### ISSUE TITLE
Feed Input. Tooltip resolves to undefined for placeholder avatar example. 

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4399]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Some meaningful tooltip (or default tooltip text) needs to be assigned to the default avatar image. 
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.26.0-rc.86
#### If this is a bug, please provide steps for reproducing it.
1. Open Feed input component.
2. Scroll down to Placeholder example. 
3. Hover ower default avatar.
AR: Tooltip said Undefined 
ER: Some meaningful tooltip (or default tooltip text) needs to be assigned to the default avatar image.
#### Is there anything else we should know?
Disabled and Max Height examples behave in the same way.  

https://user-images.githubusercontent.com/5969492/105112626-1e1d5880-5acc-11eb-8b46-f25c92bb10ee.mov

**Comment by kavya-b** [comment]
closing as this issue was fixed and verified by QA in PR #4488
