### ISSUE TITLE
Quick View: UI is not as per the fiori3 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4400]
Description: UI is not as per the fiori3 

Expected: UI should be as per the fiori3

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/105114336-b88d9400-5aec-11eb-88a5-4ba6280e15e9.png)

SAP UI5 screenshot: 
![image](https://user-images.githubusercontent.com/32538291/105114344-bd524800-5aec-11eb-95f1-8cb2231cbf8b.png)

Fiori 3 screenshot:

![image](https://user-images.githubusercontent.com/32538291/105114589-2b970a80-5aed-11eb-99d4-57407c74e866.png)

**Comment by olshansky** [comment]
@puru-hk could you please describe what exactly not per f3? Are you about popover heading alignment? 
If yes, I have applied it from the styles repository (https://fundamental-styles.netlify.app/?path=/docs/components-quick-view--popover – check it)

**Comment by puru-hk** [comment]
Tested in the above PR #4418 it is working as expected.
