### ISSUE TITLE
Quick view: One of the example is not working as per the RTL 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4401]
Description: One of the example is not working as per the RTL 

Expected: As per RTL UI should render

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/105114727-757ff080-5aed-11eb-93d0-c7d82e61fb33.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/105114766-95afaf80-5aed-11eb-8c89-dc52b2dbf954.png)

**Comment by olshansky** [comment]
@puru-hk I believe it's a Dialog component issue (http://localhost:4200/fundamental-ngx#/core/dialog – the same behavior)

**Comment by kavya-b** [comment]
duplicate of https://github.com/SAP/fundamental-ngx/issues/4747 and is being fixed in https://github.com/SAP/fundamental-ngx/pull/5170 
@xandrio you can probably add this issue to your PR description or close this as it is a duplicate of 4747. 
cc: @puru-hk

**Comment by puru-hk** [comment]
Verified the recent ngx version rc 105. it is working fine.
