### ISSUE TITLE
Feed Input. Send button is skipped entirely by Tab navigation in Safari.

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4402]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
 Send button is skipped entirely by Tab navigation in Safari.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.26.0-rc.86
#### If this is a bug, please provide steps for reproducing it.
1. Open Feed Input component.
2. In the first example set any value to input.
3. Press Tab.
AR: Send button is skipped by Tab navigation.
ER: Tab focus should happen on feed input and (>) right arrow with styles as per Fiori3 visual specs.
#### Is there anything else we should know?
**ENV: Safari 14.0.2**

https://user-images.githubusercontent.com/5969492/105115405-68550880-5ad1-11eb-947f-636f56e0dd33.mov

**Comment by genereg1** [comment]
@AntonOlkhovskyi 
FYI Safari doesn't support tabbing focus on buttons. You can achieve focus by option + Tab combination

**Comment by manjunathanagaraj** [comment]
@Seamoo13 , could you please check if this can be closed?
