### ISSUE TITLE
Quick View: Firefox browser popover is not showing full

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4403]
Description: Firefox browser popover is not showing full
Browser: Firefox version 84.0.2

Expected: Popover should display properly

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/105115871-a6f9bb80-5aef-11eb-8826-343f8c4752b6.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/105115905-b2e57d80-5aef-11eb-9a07-5de1e7faeda4.png)

**Comment by olshansky** [comment]
Looks the same as https://github.com/SAP/fundamental-ngx/issues/4405

**Comment by puru-hk** [comment]
Duplicate issues of 4405. hence closing this issue
