### ISSUE TITLE
Quick View: Popover is not proper in IE browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4405]
Description: Popover is not proper in IE browser
Browser IE version Build 19041.685

Expected: Popover should display in IE browser

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/105116318-81b97d00-5af0-11eb-9879-3b8df73c6f4c.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/105116348-9d248800-5af0-11eb-9b67-bcdd0e3d644d.png)

**Comment by olshansky** [comment]
@puru-hk I believe it's a Popover component issue (for example the same behavior you can see at the time picker component – https://fundamental-ngx.netlify.app/#/core/timePicker)
![image](https://user-images.githubusercontent.com/14160094/105151322-7a08d100-5b0e-11eb-9fc9-ae4a2e2155a0.png)

**Comment by puru-hk** [comment]
This has to be fixed.

**Comment by puru-hk** [comment]
Tested in the version 30.1. It is working as expected.
