### ISSUE TITLE
Table (platform): can use sorting when it's disabled

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4408]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
In the 'playground' example, if you disable sorting, you can still sort the first column by ascending/descending order once. 
 
#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/table
2. scroll down to the 'playground' example
3. in the table on the right side, scroll down to the last section
4. uncheck sortable, filterable, groupable
5. in the data table, click on the first column name
6. choose a sort option
7. click on the column name again

*Actual results:* you are able to sort the 1st column once while sorting is disabled.

*Expected results:* should not be able to sort when sorting is disabled

![Peek 2021-01-20 11-11](https://user-images.githubusercontent.com/47522152/105153285-ebe21a00-5b10-11eb-922b-ec31195880af.gif)
![2021-01-20_1](https://user-images.githubusercontent.com/47522152/105153290-edabdd80-5b10-11eb-8641-ca2e89b1814b.png)

**Comment by platon-rov** [comment]
Can not reproduce (chrome/safari).

**Comment by nikvalor** [comment]
Fixed
