### ISSUE TITLE
Table (platform): multiple column filter doesn't show user where to input a value

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4409]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for the 'Filtering by multiple columns' example, the filter doesn't show users where to input their value(s). 

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/table
2. scroll down to the 'Filtering by multiple columns' example
3. click on the filter icon
4. choose any options from the drop downs (i.e. Name, Between)
5. look for input field to add your values

*Actual results:* the input field exists, but is not visible to the user (no borders, etc.)

*Expected results:* user should be able to see where to input their values

![Peek 2021-01-20 11-34](https://user-images.githubusercontent.com/47522152/105156541-a889aa80-5b14-11eb-97cd-3cdcab713345.gif)
![2021-01-20_2](https://user-images.githubusercontent.com/47522152/105156683-d53dc200-5b14-11eb-91c9-3271fa2cb202.png)
![2021-01-20_3](https://user-images.githubusercontent.com/47522152/105156686-d66eef00-5b14-11eb-9969-4eab08fae8ef.png)

**Comment by dimamarksman** [comment]
I believe it is because of https://github.com/SAP/fundamental-ngx/issues/4332

**Comment by platon-rov** [comment]
Can not reproduce. Should be closed.

**Comment by nikvalor** [comment]
Fixed
