### ISSUE TITLE
Table (Platform): for IE11, 2 separate tables overlap

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4413]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for the 'playground' example, the two tables overlap each other

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/table
2. scroll down to the playground example
3. look at the 2 tables

*Actual results:* they are overlapping
![2021-01-20_10](https://user-images.githubusercontent.com/47522152/105168765-3ff5fa00-5b23-11eb-8dea-572e08014be8.png)

*expected:*
![2021-01-20_11](https://user-images.githubusercontent.com/47522152/105168805-4dab7f80-5b23-11eb-9216-673b2489605e.png)

**Comment by nikvalor** [comment]
Not fixed. Still actual on IE11 on windows machine.

**Comment by Seamoo13** [comment]
@nikvalor the PR isn't merged yet

**Comment by nikvalor** [comment]
@Seamoo13 Yeah, sorry. My bad
