### ISSUE TITLE
Table (Platform): for Safari, column freezing example is missing scroll bar

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4414]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for Safari 13, missing scroll to show which columns are frozen and which move

#### If this is a bug, please provide steps for reproducing it.
1. open Safari
2. go to https://fundamental-ngx.netlify.app/#/platform/table
3. scroll down to the column freezing example
4. look for the scroll bar at the bottom of the table.

*Actual results:* no scroll bar
![2021-01-20_12](https://user-images.githubusercontent.com/47522152/105169774-b34c3b80-5b24-11eb-9221-d7e7b0ac0c49.png)

**Comment by dimamarksman** [comment]
Isn't that intentional behaviour for safari on mac (scrollbar appears only when something is getting scrolled)?

**Comment by platon-rov** [comment]
Yea, as @dimamarksman said - it's the default behavior on mac, even in chrome. But we do have scrollbars in the SAPUI5 examples, which there is implemented on the app layer.

But I see that we don't have a right (left when RTL) column border after the last fixed columns - it's definitely a bug. I will check it.

About the scrollbars - I will add that point to the next phase of table implementation.
