### ISSUE TITLE
Table (platform): column freezing borders don't match designs

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4415]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
1. borders of frozen columns don't align with non-frozen columns
2. border separating frozen and non-frozen columns should be darker per design

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/table
2. scroll down to the column freezing examples
3. look at the borders between frozen and non-frozen columns

*Actual:*
![2021-01-20_16](https://user-images.githubusercontent.com/47522152/105170928-56518500-5b26-11eb-86ef-6ac56bd19c6d.png)

*Expected:*
![2021-01-20_15](https://user-images.githubusercontent.com/47522152/105170939-5baecf80-5b26-11eb-8b2b-9cfab75f3cd9.png)

**Comment by dimamarksman** [comment]
I believe that's connected to the fundament-styles [issue](https://github.com/SAP/fundamental-styles/issues/1948)

**Comment by platon-rov** [comment]
On hold until https://github.com/SAP/fundamental-styles/pull/2384 not merged.
