### ISSUE TITLE
Datetime Picker (platform): hour value is changed after clicking 'PM' period 

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#4428]
#### Is this a bug, enhancement, or feature request?
Bug

#### If this is a bug, please provide steps for reproducing it.
**Steps**:
1) Open any datetime picker 
2) Select 1 hour and 1 minute 
3) Click on 'PM' period
4) Check hour value

**Actual result:** hour value is changed to 11 
Also actual for ''AM" time 
**Expected result:** hour value shouldn't be changed

#### Is there anything else we should know?
*Video*: 
https://www.loom.com/share/35c77e24f6ed4386b93e13040906cc07

**Comment by kavya-b** [comment]
same behaviour is also observed in Core datetime picker and in time picker component.

**Comment by manjunathanagaraj** [comment]
note: this happens only when i select(change from PM to AM) AM and click again on AM. SImilarly when I change from AM to PM and click again on PM. If I change from AM to PM (or vice versa) and dont click again on the same button, the issue does not occur.
