### ISSUE TITLE
Platform Table phase 4 implementation

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4429]
Phase 4 of the Table component introduces the Tree Table feature.

For details, refer the below technical specs link.
Technical Specs: https://app.gitbook.com/@fundamental-ngx/s/docs/platform-table-phase-4

**Comment by platon-rov** [comment]
In docs I see that we request user to provide `relationKey` for tree table to know which field of object contains children. But we don't request something like `titleKey` to know which field contains title.

So we assuming that we'll have structure like that:
```
[
  {
    name: `Title of row that has children`, // <= User cannot customise in which field title is, it can be 'name', 'title', 'label', etc...
    children: [ ... ] // <= User can customise in which field children are
  }
]
```

I propose to also make it customisable.
