### ISSUE TITLE
Money Field Component - Define technical specs

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4430]
This is non-Fiori3 component and is SAPAriba specific.

**Comment by KevinOkamoto** [comment]
I need feedback from UX and product teams before completing the tech spec. I probably won't be able to finish this this sprint.

**Comment by KevinOkamoto** [comment]
Here's the link to the Money Field component, which is still in progress:

https://app.gitbook.com/@fundamental-ngx/s/docs/work-in-progress/platform-money-input

**Comment by sKudum** [comment]
Can not proceed on this until we get design specs and requirements from David and team

**Comment by sKudum** [comment]
Removed skudum as assignee, as going on leaves.
