### ISSUE TITLE
Carousel (core): when using loop carousel, images change order

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4432]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
For the loop example, the order of images is changed if you use the left arrow btn from pic 1 to go to the last pic, then the right arrow btn to go to the first pic. 1st pic is replaced with 6th pic.

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/core/carousel
2. scroll down to the example "Carousel with looped navigation"
3. look at the 1st image
4. click the left arrow navigation button below the carousel (previous img btn)
5. click the right arrow navigation button (next img btn)
6. look the the 1st image 

**Actual results:** the 1st image in the carousel has been change to the 6th (can see img number by inspecting the img element)
![Peek 2021-01-22 15-41](https://user-images.githubusercontent.com/47522152/105498554-0232d600-5cc9-11eb-8069-cf37201f35ab.gif)

**Expected results:** the 1st image should remain the first

**Comment by DeepakSap14** [comment]
blocked by https://github.com/SAP/fundamental-styles/pull/2343
