### ISSUE TITLE
Carousel (core): navigation buttons appear in the content section without hover

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4434]
#### Briefly describe your proposal.
If the navigation buttons are inside the content area (img), they should only appear on hover. 

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/core/carousel
2. scroll down to the "Carousel with navigation inside content area" example
3. move your mouse so that it is NOT hovering over the carousel
4. look at the carousel navigation buttons

**Actual results:** buttons are displayed when mouse is not hovering over the carousel
![2021-01-22](https://user-images.githubusercontent.com/47522152/105515286-30baac00-5cdd-11eb-98b2-1c2913b77ce4.png)

**Expected results:** buttons will only show on hover
![Peek 2021-01-22 18-07](https://user-images.githubusercontent.com/47522152/105515278-2dbfbb80-5cdd-11eb-90ce-bad9ef17d4a3.gif)

**Comment by DeepakSap14** [comment]
blocked by https://github.com/SAP/fundamental-styles/pull/2343
