### ISSUE TITLE
Bug: Combobox dropdown select does not aligned with input field during window re-sizing.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4437]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Upon clicking dropdown arrow icon, dropdown select does not aligned with input field during window re-sizing. See pics below:
![image](https://user-images.githubusercontent.com/71797052/105555355-11f8ed00-5cbe-11eb-8ce3-8dfd0892c555.png)
![image](https://user-images.githubusercontent.com/71797052/105555370-18876480-5cbe-11eb-9b42-96fef99bc39d.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/combobox
Click dropdown on any input field and make a selection.
Click out of it and resize browser window.
Dropdown select is stuck and frozen on previous size and does not re-size

**Comment by puru-hk** [comment]
@pierrom  could you please retest this issues in this url https://deploy-preview-4741--fundamental-ngx.netlify.app

**Comment by puru-hk** [comment]
@pierrom could you please test this issues in this url https://deploy-preview-4741--fundamental-ngx.netlify.app/#/platform/combobox.

**Comment by puru-hk** [comment]
@pierrom Could you please test this issues.

**Comment by pierrom** [comment]
Hi Puru - retested per your request. Dropdown no longer exceed width of combobox but it should match width. See pics below
<img width="919" alt="Screen Shot 2021-03-10 at 5 44 51 PM" src="https://user-images.githubusercontent.com/71797052/110723307-b4b2ef80-81c8-11eb-8d17-46ddb510330a.png">
<img width="782" alt="Screen Shot 2021-03-10 at 5 45 18 PM" src="https://user-images.githubusercontent.com/71797052/110723320-bbd9fd80-81c8-11eb-9ff5-f774e3e157b9.png">

**Comment by Betrozov** [comment]
> Hi Puru - retested per your request. Dropdown no longer exceed width of combobox but it should match width. See pics below
> <img alt="Screen Shot 2021-03-10 at 5 44 51 PM" width="919" src="https://user-images.githubusercontent.com/71797052/110723307-b4b2ef80-81c8-11eb-8d17-46ddb510330a.png">
> <img alt="Screen Shot 2021-03-10 at 5 45 18 PM" width="782" src="https://user-images.githubusercontent.com/71797052/110723320-bbd9fd80-81c8-11eb-9ff5-f774e3e157b9.png">

This issue related to the Core: Combobox
But the initial issue was for Platform: Combobox
I think we need to create a separate issue for Core: Combobox

FYI: @manjunathanagaraj @puru-hk

**Comment by puru-hk** [comment]
@Betrozov I have created the same issue in core https://github.com/SAP/fundamental-ngx/issues/5174. Please have a look

**Comment by pierrom** [comment]
Verified. I will close.
