### ISSUE TITLE
datetime picker (platform): validation not working correctly

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4441]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for the 'Datetime Picker with Template Forms' example, the field shows error validation when correct data present

#### If this is a bug, please provide steps for reproducing it.
**STR**
1. go to https://fundamental-ngx.netlify.app/#/platform/datetime-picker
2. scroll down to the 'Datetime Picker with Template Forms' example
3. delete the date and time shown
4. click on the icon to choose a new date and time
5. click 'ok' in the popup
6. check input

**Actual results:** valid input exists, but the field shows error validation which states the field is empty
![2021-01-23_5](https://user-images.githubusercontent.com/47522152/105585270-53aa9600-5d99-11eb-9559-71a09e89afd3.png)
![Peek 2021-01-23 16-32](https://user-images.githubusercontent.com/47522152/105585321-573e1d00-5d99-11eb-8e1b-738d37919ee2.gif)

**Comment by OleksiyDrozdov** [comment]
@Seamoo13 , issue is not reproducible. Could you please kindly retest.

**Comment by Seamoo13** [comment]
verified not reproducible.
