### ISSUE TITLE
datetime picker (platform): for IE, many input fields squished (not wide enough)

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4442]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
For IE11, many datetime picker input fields are so small that the text and placeholder text are not visible

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/datetime-picker
2. scroll through the examples and pay attention to the input fields

![2021-01-23_6](https://user-images.githubusercontent.com/47522152/105594208-c61c7580-5d9b-11eb-9d5f-cb2e78e7247c.png)

**Comment by kavya-b** [comment]
This is not reproducible anymore. Probably fixed with the form container column layout changes. Please check @Seamoo13 
![image](https://user-images.githubusercontent.com/53509521/122914803-a7d19a80-d378-11eb-8fbf-a2d067aba5c4.png)
