### ISSUE TITLE
datetime picker (platform): on IE and Edge, popup to select date/time not working for 2 examples

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4463]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for 2 examples, there is no popup to select the date and time (IE, MS Edge)
Datetime Picker with [disableFunction] example
Datetime Picker with Template Forms example

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/datetime-picker
2. scroll down to the "Datetime Picker with Template Forms" example 
3. click on the button to open a popup to choose date/time

**Actual results:** no popup appears
**NOTE:** same for Datetime Picker with [disableFunction] example
![Peek 2021-01-25 10-39](https://user-images.githubusercontent.com/47522152/105681581-f712bc80-5ef9-11eb-9bd9-56ec4bcb8d09.gif)

**Expected results:** popup with date and time selection will appear and user can select date and time
![Peek 2021-01-25 10-42](https://user-images.githubusercontent.com/47522152/105681649-0eea4080-5efa-11eb-8b1e-c605607b746d.gif)

**Comment by kavya-b** [comment]
seems to be opening fine, QA please verify.

**Comment by puru-hk** [comment]
Tested in recent ngx version 30 it is working as expected.
