### ISSUE TITLE
can not install @fundamental-ngx/core package using npm 7 (with default npm setting)

### ISSUE THREAD

**Issue by talsi** [SAP/fundamental-ngx#4467]
#### Is this a bug, enhancement, or feature request?
>bug

#### Briefly describe your proposal.
>npm v7 installs peer dependencies by default.
>`@fundamental-ngx/core` package has peer dependency conflicts.
>https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
> \>=0.19.2
but probably earlier versions too.

#### If this is a bug, please provide steps for reproducing it.
>prerequisites: using npm ^7.0.0 (7.4.2 in my case)
>1. open new empty project
>2. create package.json file
>  2.1 add @fundamental-ngx/core to dependencies (version 0.19.2, for example)
>3. run `npm install`

#### Please provide relevant source code if applicable.
```
{
  "name": "untitled1",
  "version": "1.0.0",
  "dependencies": {
    "@fundamental-ngx/core": "0.19.2"
  }
}
```

#### Is there anything else we should know?
>you can't install the package even if it's the only package you install.
>you must use `--legacy-per-deps` in order for this to work

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: untitled1@1.0.0
npm ERR! Found: @angular/core@9.1.13
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"~9.1.11" from @fundamental-ngx/core@0.19.2
npm ERR!   node_modules/@fundamental-ngx/core
npm ERR!     @fundamental-ngx/core@"0.19.2" from the root project
npm ERR!   peer @angular/core@"9.1.13" from @angular/animations@9.1.13
npm ERR!   node_modules/@angular/animations
npm ERR!     peer @angular/animations@"~9.1.11" from @fundamental-ngx/core@0.19.2
npm ERR!     node_modules/@fundamental-ngx/core
npm ERR!       @fundamental-ngx/core@"0.19.2" from the root project
npm ERR!   1 more (@angular/cdk)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"10.2.4" from @angular/common@10.2.4
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^9.0.0 || ^10.0.0-0" from @angular/cdk@9.2.4
npm ERR!   node_modules/@angular/cdk
npm ERR!     peer @angular/cdk@"~9.2.4" from @fundamental-ngx/core@0.19.2
npm ERR!     node_modules/@fundamental-ngx/core
npm ERR!       @fundamental-ngx/core@"0.19.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by mikerodonnell89** [comment]
@talsi thank you for pointing this out, seems to be an issue with npm 7 as per this thread: https://github.com/angular/angular-cli/issues/19957

Could you try running `npm i @fundamental-ngx/core@0.19.2 --legacy-peer-deps` ?

**Comment by talsi** [comment]
@mikerodonnell89 
hi,
1. it's not related to Angular CLI at all. 
it's happening just by running `npm i @fundamental-ngx/core@0.19.2` in an empty project
```
{
  "name": "untitled1",
  "version": "1.0.0",
  "dependencies": {
    "@fundamental-ngx/core": "0.19.2"
  }
}
```

2. using `--legacy-peer-deps` is a workaround. 
it's probably indeed a bug with npm though i think it's related to this one https://github.com/npm/cli/issues/2553

**Comment by droshev** [comment]
@talsi Do you think you can switch to npm 6. There are issues around npm 7.
