### ISSUE TITLE
File uploader (Platform): Wrong file extension validation on chrome browser 

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#4468]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Wrong file extension validation on chrome browser 

#### If this is a bug, please provide steps for reproducing it.
**Steps to reproduce:**
1. Open file uploader component page
2. Click 'Browse' button and observe available files to upload for chrome browser 
**Actual state:**user is able to select file with incorrect extension 
**Expected state:** user shouldn't be able to select file with incorrect extension. Incorrect files should be disabled in popup 

#### Is there anything else we should know?
Not actual for firefox and safari browser 

Screenshots: 
**Chrome MAC:** (incorrect)
![image](https://user-images.githubusercontent.com/74654139/105706816-b6776b00-5f1a-11eb-8c15-d091544a8c9a.png)
**Firefox MAC:** (works good) 
![image](https://user-images.githubusercontent.com/74654139/105706874-c98a3b00-5f1a-11eb-992a-06d09082acff.png)
**Safari MAC:** (works good)
![image](https://user-images.githubusercontent.com/74654139/105706954-e32b8280-5f1a-11eb-87dc-bbf85494285d.png)

**Comment by manu-kr** [comment]
@nikvalor This is chrome browser behaviour for file input field. you can check other website for the reference ,

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_accept

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

https://sapui5.hana.ondemand.com/#/entity/sap.ui.unified.FileUploader/sample/sap.ui.unified.sample.FileUploaderComplex

Its enabling .jpeg file extension for selection, But inside file uploader component , we have validation to allow only mentioned file extension to select.

I will update the documentation to show valid error message.
