### ISSUE TITLE
Add virtual scrolling

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#447]
#### Is this a bug, enhancement, or feature request?
More enhancement

#### Briefly describe your proposal.

Current implementation of infinite scroll is using on Load callback where it adds new items to the DOM, but it does not remove them from top. This could be definitely fine for simple application but if we try to show thousands of times along with the rest of the application the performance goes does. 

Not only DOM became bigger and angular has to do more work, but you will also keep in memory all the data model for the shown items. 

@angualr/cdk has virtual scrolling component that could help.

**Comment by MattL75** [comment]
What you are asking for is virtual scrolling, which is a different strategy than infinite scroll. We could also implement this, probably would not be very difficult

**Comment by fkolar** [comment]
Yeap Yeap, It really depends what you work with with 20 items or 10k items. Again SAP and its companies work with enterprise data. 
Thanks for renaming it.

**Comment by MattL75** [comment]
Yes you're right lots of data is better handled by virtual scroll, good issue to raise!

**Comment by droshev** [comment]
let's implement it once it is requested by someone
