### ISSUE TITLE
Defect Hunting for Sprint 54 - Los Angeles

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#4482]
- [x] All Browsers Breadcrump overflow menu doesn't open

- [x] IE11 - Toolbar overflow
![image](https://user-images.githubusercontent.com/26483208/105870371-7e465a00-5ff8-11eb-9913-38f4e1483ef5.png)

- [x] All Browsers - One Button and one input is very small - have limited height
![image](https://user-images.githubusercontent.com/26483208/105870900-0b89ae80-5ff9-11eb-80e1-fdad4c969f98.png)

**Comment by droshev** [comment]
- [ ] Dynamic page background span issue visible in dark theme/HCB
<img width="961" alt="Screen Shot 2021-01-26 at 11 55 05 AM" src="https://user-images.githubusercontent.com/4380815/105876996-7cb36c80-5fcd-11eb-932d-91ae218a84a0.png">

**Comment by mikerodonnell89** [comment]
- [ ]  clicking a carousel button moves the focus to the whole carousel (not new to this version)
![carouselfocus](https://user-images.githubusercontent.com/2471874/105882869-6acccc00-5fc3-11eb-999b-782bcae7a7d4.gif)

- [ ] combobox magnifier search button not focusable with tab key - note that the focus does directly for the clear search button to the hide code button
![comboboxsearchfocus](https://user-images.githubusercontent.com/2471874/105883602-47eee780-5fc4-11eb-9fac-574a0e786ef6.gif)

- [ ] Datepicker/Datetimepicker - Should clicking the input change touched to true? (not new to this version)
![Screen Shot 2021-01-26 at 10 51 26 AM](https://user-images.githubusercontent.com/2471874/105883757-7240a500-5fc4-11eb-9800-b60756028d97.png)

- [ ] Form message not working here ![Screen Shot 2021-01-26 at 10 58 48 AM](https://user-images.githubusercontent.com/2471874/105884708-7a4d1480-5fc5-11eb-9fdc-5164c0f58993.png)

- [ ] Grid list drag n drop needs cursor updates (not new to this version)

**Comment by InnaAtanasova** [comment]
- [ ] double focus outline
<img width="626" alt="Screen Shot 2021-01-26 at 1 46 37 PM" src="https://user-images.githubusercontent.com/39598672/105908001-ad0e0180-5ff3-11eb-9a33-f0dc071af408.png">
<img width="675" alt="Screen Shot 2021-01-26 at 1 43 37 PM" src="https://user-images.githubusercontent.com/39598672/105908014-b303e280-5ff3-11eb-9bc3-2dddad8101a5.png">
- [ ] Grid list issues
<img width="841" alt="Screen Shot 2021-01-26 at 1 50 04 PM" src="https://user-images.githubusercontent.com/39598672/105908078-cca52a00-5ff3-11eb-9ce7-eb46a6944ad5.png">
<img width="857" alt="Screen Shot 2021-01-26 at 1 50 36 PM" src="https://user-images.githubusercontent.com/39598672/105908134-ddee3680-5ff3-11eb-9f78-bb59959b6f20.png">
<img width="1680" alt="Screen Shot 2021-01-26 at 1 51 00 PM" src="https://user-images.githubusercontent.com/39598672/105908137-de86cd00-5ff3-11eb-9b42-43c7e440d803.png">

- [ ] Should we remove the fdPopover directive from Simple Popovers example?
<img width="1207" alt="Screen Shot 2021-01-26 at 4 25 25 PM" src="https://user-images.githubusercontent.com/39598672/105908222-f5c5ba80-5ff3-11eb-94d1-b2ef9d412a74.png">

**Comment by mikerodonnell89** [comment]
- [ ] Quick view title missing padding
![Screen Shot 2021-01-26 at 3 23 46 PM](https://user-images.githubusercontent.com/2471874/105913730-7d0e3080-5fea-11eb-8332-9d459b5cb42c.png)

- [ ] Shellbar counters placed weird in overflow menu
![Screen Shot 2021-01-26 at 3 44 50 PM](https://user-images.githubusercontent.com/2471874/105915861-6f0ddf00-5fed-11eb-89c5-23d4dcf9f78d.png)

**Comment by JKMarkowski** [comment]
- [x] Initial Focus Trap doesn't work on popover 
![Peek 2021-01-27 12-28](https://user-images.githubusercontent.com/26483208/105985009-3298bc80-609b-11eb-930a-b61e1ba523f9.gif)

**Comment by kavya-b** [comment]
> * [ ]  Dynamic page background span issue visible in dark theme/HCB
> 
> <img alt="Screen Shot 2021-01-26 at 11 55 05 AM" width="961" src="https://user-images.githubusercontent.com/4380815/105876996-7cb36c80-5fcd-11eb-932d-91ae218a84a0.png">

@droshev could you recheck this with the latest netlify? I merged a PR with dynamic page related changes today and I don't see this issue reproducible.

**Comment by InnaAtanasova** [comment]
All issues have been addressed. Closing this issue
