### ISSUE TITLE
Defect Hunting for Sprint 55 - Monaco

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#4483]
Issues found during the defect hunting.

**Comment by JKMarkowski** [comment]
- [ ] All Browsers - [multi input](https://fundamental-ngx.netlify.app/#/core/multi-input#newTokens) - There is a way to add empty token, which causes errors
![image](https://user-images.githubusercontent.com/26483208/107336709-b7330400-6ab9-11eb-81e6-e1acf2e8776c.png)

**Comment by InnaAtanasova** [comment]
- [ ] Link Tile - all browsers 
<img width="1194" alt="Screen Shot 2021-02-09 at 1 45 15 PM" src="https://user-images.githubusercontent.com/39598672/107411927-1c4c2100-6add-11eb-9e64-581b49d9af2b.png">

**Comment by mikerodonnell89** [comment]
- [ ] Multi-input dropdown items - strange focus on checkbox (not present in styles)
![Screen Shot 2021-02-11 at 1 54 27 PM](https://user-images.githubusercontent.com/2471874/107697585-a973af00-6c70-11eb-924d-8cc29bdcafb5.png)

- [ ] Mobile calendar 'ok' buttons are compact, should be cozy

- [ ] Mobile menu - cannot use arrow keys to navigate menu items

**Comment by mikerodonnell89** [comment]
- [ ] Multi-input dropdown items - strange focus on checkbox (not present in styles)
![Screen Shot 2021-02-11 at 1 54 27 PM](https://user-images.githubusercontent.com/2471874/107697585-a973af00-6c70-11eb-924d-8cc29bdcafb5.png)

- [x] Mobile calendar 'ok' buttons are compact, should be cozy - #4648
