### ISSUE TITLE
Shellbar collapsable action behavior

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#449]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

As I have to read now the spec and looking what is ready, I see different behavior in terms of how action from the shelbar collapse to popover when on smaller device. 

It should not display only text but also icons inverted to different color. 

The way you have implemented it you could simply set some extra flag into the ShellBarAction component to tell if you are rendering current action inside the shell bar or not. 

https://sap.sharepoint.com/sites/107889/Specifications/Fiori3_Phase1_ShellSpecification.pdf?csf=1&e=Xx5Qbf

**Comment by droshev** [comment]
@fkolar is this the same issue as #374?

**Comment by fkolar** [comment]
Yeap. it look like identical issue ! Closing this one. thanks
