### ISSUE TITLE
Dynamic Page tabChange event not firing

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#4514]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
The `tabChange` event which uses underlying core's Tab component does not emit anything.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
1. Go to Tabbed Dynamic Page example in https://sap.github.io/fundamental-ngx/#/platform/dynamic-page 
2. Open the example
3. Switch tabs
4. Open developer console
5. Observe no messages regarding tab changes were logged.

#### Is there anything else we should know?
Core tab had some breaking changes, where `selectedIndexChange` was replaced with `selectedTabChange`. This was not changed in Dynamic Page implementation which uses this output event.

**Comment by puru-hk** [comment]
Tested in PR 4515. When we do the Tab change in developer console message were logged.
