### ISSUE TITLE
Table: On the Filter popup click on the contains drop down menu is showing behind the screen 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4518]
Description: On the Filter popup click on the contains drop down menu is showing behind the screen 

Expected:Menu should display on the filter popup 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/106266824-eb532d00-624e-11eb-8a1e-b657e82ad5b3.png)

**Comment by maxym-valor** [comment]
The bug still be. Steps to reproduce:
1. Open https://fundamental-ngx.netlify.app/#/platform/table
2. Open filter in the table
3. Click on Exclude arrow
4. Click on the second drop-down in Exclude area
![image](https://user-images.githubusercontent.com/83698366/119663860-7201ca80-be3b-11eb-8edf-a5de927589ee.png)

**Comment by platon-rov** [comment]
On hold until [Styles #2390](https://github.com/SAP/fundamental-styles/pull/2390) is merged.
