### ISSUE TITLE
Enhancement: responsive on Shellbar Component

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#4522]
#### 
When the screen is resized, it would be good to 'condense' automatically the side menu.
At the moment we handle the resize event, but it would be better to manage it inside the component itself.

#### 
Angular version: 10.2.1
Library Version: 0.26

Example:

on big screen:

![image](https://user-images.githubusercontent.com/74785804/106280323-0ff2d900-623e-11eb-9dbd-be90c07d18b0.png)

on small screen:

![image](https://user-images.githubusercontent.com/74785804/106280286-010c2680-623e-11eb-9d98-98e5e628c186.png)

Thanks in advance

**Comment by InnaAtanasova** [comment]
As part of this issue we need to do the following:
- [ ] check for which components we can apply this service
- [ ] use as default the breakpoints specified in Fiori3
- [ ] add input properties to allow the user to set custom breakpoints 
- [ ] add input property to allow the user to disable this option and manually set the modifier classes

**Comment by mikerodonnell89** [comment]
Doing this automatically out-of-the-box would be a breaking change, so I have added an optional input to the SideNavigationComponent to set an automatic collapse/expand at a specified pixel breakpoint. [PR here](https://github.com/SAP/fundamental-ngx/pull/7583)
