### ISSUE TITLE
Table phase 4: manual testing

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4551]
do manual testing for all browsers for table phase 4

**Comment by Seamoo13** [comment]
component not implemented

**Comment by manjunathanagaraj** [comment]
Component implementation could not be completed, therefore moving to next sprint

**Comment by Seamoo13** [comment]
component not implemented again.

**Comment by Seamoo13** [comment]
component still not ready for testing

**Comment by Seamoo13** [comment]
left review comments
