### ISSUE TITLE
Scroll bar of fds-app-content component not working

### ISSUE THREAD

**Issue by Shefalika14** [SAP/fundamental-ngx#4554]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The scrollbar that comes in as a part of fds-app-content component is not working. Can only see the disabled scrollbar component but it does not scroll.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@fundamental-ngx/app-shell: 0.2.35

#### If this is a bug, please provide steps for reproducing it.
Include any page within <fds-app-content> </fds-app-content> tags that has contents which require scrolling

**Comment by fkolar** [comment]
![Uploading Screenshot 2021-02-01 at 4.59.13 PM.png…]()

**Comment by fkolar** [comment]
<img width="1655" alt="Screenshot 2021-02-01 at 4 59 13 PM" src="https://user-images.githubusercontent.com/17149942/106464320-ca7e1800-6498-11eb-9463-d27146b15345.png">

**Comment by nowant** [comment]
The components `fds-app-content` , `fds-app-header` and `fds-app-footer` were removed from `app-shell` within PR #4046 . Pls find and copy them there https://github.com/valorkin/ng-mf-submodules/tree/master/packages/one-bx-shell-app/src/app/components

**Comment by nowant** [comment]
Also to fix the issue you should set `height: 100vh`  to `div.content`
