### ISSUE TITLE
Grid list issues - Defect Hunting

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#4560]
Grid list issues
<img width="841" alt="Screen Shot 2021-01-26 at 1 50 04 PM" src="https://user-images.githubusercontent.com/39598672/105908078-cca52a00-5ff3-11eb-9ce7-eb46a6944ad5.png">
<img width="857" alt="Screen Shot 2021-01-26 at 1 50 36 PM" src="https://user-images.githubusercontent.com/39598672/105908134-ddee3680-5ff3-11eb-9f78-bb59959b6f20.png">
<img width="1680" alt="Screen Shot 2021-01-26 at 1 51 00 PM" src="https://user-images.githubusercontent.com/39598672/105908137-de86cd00-5ff3-11eb-9b42-43c7e440d803.png">

**Comment by sKudum** [comment]
Hi @Betrozov ,

 Few more observations:


1). In RTL mode styles are not aligned as expected.
<img width="521" alt="Screenshot 2021-02-08 at 10 58 08 AM" src="https://user-images.githubusercontent.com/53487468/107179463-8a6ce700-69fc-11eb-9fb7-60a851177b0f.png">

2).With Keyboard actions not able to select item either with radio or checkbox.

3).More button click not loading more items on click on enter or space.
