### ISSUE TITLE
bug: value help dialog (platform): for 1 example, missing inclusions/exclusions tab when enabled

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4574]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for 1 example, if you enable inclusions or exclusion and open the dialog, these options aren't present

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/value-help-dialog
2. scroll down to the "filters combinations" example
3. click to enable inclusions/exclustions (the two checkboxes)
4. click to open the dialog 

**Actual results:** no way to add inclusions/exclustions
![2021-02-03_6](https://user-images.githubusercontent.com/47522152/106769233-651b5a00-6645-11eb-9fe0-2f563d745f07.png)
![2021-02-03_5](https://user-images.githubusercontent.com/47522152/106769243-677db400-6645-11eb-8043-e2536b1dbb60.png)
![Peek 2021-02-03 17-17](https://user-images.githubusercontent.com/47522152/106769255-6b113b00-6645-11eb-8f93-618375f7df86.gif)

**Comment by kavya-b** [comment]
@puru-hk @Seamoo13 please re-verify as this example has been removed in PR https://github.com/SAP/fundamental-ngx/pull/4661 so this issue won't be there now.

**Comment by Seamoo13** [comment]
verified
