### ISSUE TITLE
Search-Input option for glyph

### ISSUE THREAD

**Issue by jakeleesap** [SAP/fundamental-ngx#458]
Can you please support the option to use another icon in search-input for glyph ?

thanks

**Comment by droshev** [comment]
@jakeleesap what is your scenario or use case?

**Comment by jakeleesap** [comment]
Hi,
Base on our UX design, this field is default as a  drop down with a default list, until the user type in any value, it will do a round trip to search the value. So, since the original drop down has already contains a list, it should allow us to default the icon as a Arrow-Down so the user would first click on it. Hope my explanation clear :(

**Comment by MattL75** [comment]
I'm not sure I completely understand what it is you're trying to do, but if the baseline requirement is control over the icon in search-input, I'm sure we can accommodate. 

We can still have the search icon as default, so adding the option to change it will only make the component more flexible.

**Comment by jakeleesap** [comment]
Thanks for the response, maybe I explain once more time that is more simple.

Lets say I have many other field that I used "arrow-down" from glyph - and if I want to be consistent for  the same field like "arrow-down" instead of the default "search" icon, it would nice to have the same icon.

thanks

**Comment by MattL75** [comment]
Hi @jakeleesap control over the search input icon will be available in the next release which will hopefully be soon! :)
