### ISSUE TITLE
bug: AppShell cannot use global urls to load assets

### ISSUE THREAD

**Issue by skocharian** [SAP/fundamental-ngx#4581]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

In content item app, we use images from assets folder in the component template.
When these components are rendered through Shellapp routing, images are not loaded.
Reason for this is, Shellapp tries find these images from its own asset folder.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@fundamental-ngx/app-shell: 0.2.35

#### If this is a bug, please provide steps for reproducing it.

1. Add assets with a global url
2. Build the application
3. Observe final asset url — it ir replaced with an app-shell base href, asset doesn't open.

**Comment by manjunathanagaraj** [comment]
Solution for this is found, but implementation to be done in next sprint.

**Comment by manjunathanagaraj** [comment]
The only feasible option seems to be to make it work with absolute URLs.

**Comment by manjunathanagaraj** [comment]
It was exploratory. One solution is implemented, but needs review from Dima. This may require reimplementation or another implementation approach.

**Comment by manjunathanagaraj** [comment]
To publish guidelines for adoption teams

**Comment by omfgnuts** [comment]
^Proofreaded by me! @manjunathanagaraj

**Comment by skocharian** [comment]
Final review is expected to happen today by @valorkin
