### ISSUE TITLE
I18nsupport

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#4593]
- [ ] Even we can use ng CLI to build the project we need to make sure that we support i18n compilation on the remote app

- [ ] Probably app-shell need to pass locale down the remote apps. (Should we re-route to new lang app?

note: most like angular cli fix will be required

- [ ] acceptance: MF users should be able to use default ng cli commands to extract translations and use

- [ ] acceptance: add sample with i18n to demo application

- severity: blocks i18n

- [ ] testing: CI + cypres

**Comment by manjunathanagaraj** [comment]
In progress. Expected to close it by next week.

Also, there are tasks dependent on builder. This will be resolved in next sprint. This will be tracked by creating new issue. @valorkin to create the issue.

**Comment by manjunathanagaraj** [comment]
implementation of ng CLI is in progress. Expected to be completed in next week.
Builder extensions to be included as per the need.

**Comment by manjunathanagaraj** [comment]
expected to be completed by this week.

**Comment by skocharian** [comment]
Implementation done, documentation in progress. ETA — Thursday (March 18)
