### ISSUE TITLE
Select: Example is missing for long text 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4597]
Description: Example is missing for long text 

Expected: Examples should be added for long text

Screenshot attached from the fiori3 

![image](https://user-images.githubusercontent.com/32538291/107187721-75984f80-6a0c-11eb-8495-c4f1e5c98700.png)

**Comment by sKudum** [comment]
In current PR our target was to update usage of selection model and key manager with out breaking existing scenarios. 

Adding a example should be considered as enhancement. Hence updating it as enhancement.

**Comment by sKudum** [comment]
Dependent on https://github.com/SAP/fundamental-styles/issues/2160

**Comment by sKudum** [comment]
once SAP/fundamental-styles#2160 is resolved then we can create examples for it.Till then it is blocked

**Comment by sKudum** [comment]
Removed skudum as assignee, as going on leaves.
