### ISSUE TITLE
table: Table content is not responsive.

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#4601]
#### Briefly describe your proposal.

As per the Specs the table and its content has to adapt to the mobile devices screen.

Expected Behaviour:

<img width="663" alt="Screenshot 2021-02-08 at 1 49 33 PM" src="https://user-images.githubusercontent.com/53534379/107193191-94024900-6a14-11eb-8855-5b3304c67154.png">

current implementation.
<img width="663" alt="Screenshot 2021-02-08 at 1 47 45 PM" src="https://user-images.githubusercontent.com/53534379/107193211-9a90c080-6a14-11eb-9a2f-749530084d4d.png">

there is a difference of view in a mobile view. 

#### If this is a bug, please provide steps for reproducing it.
Step 1: Open URL(https://fundamental-ngx.netlify.app/#/platform/table)
Step 2: Inspect element and switch to mobile view.

**Comment by manjunathanagaraj** [comment]
Mobile version will be addressed in one of the future sprints.
