### ISSUE TITLE
Select: Screen reader is not convery when user select the item from the list

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4613]
Description: Screen reader is not convery when user select the item from the list

Expected: Screen reader should read the selected item from the field

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/107327142-9fb44500-6ad2-11eb-937e-e1a8b126b3ae.png)

**Comment by sKudum** [comment]
Same issues is logged in  https://github.com/SAP/fundamental-ngx/issues/5051 as well. Closing it considering it as duplicate issue.
