### ISSUE TITLE
Select: Not able to scroll down list from the keyboard

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4614]
Description: Not able to scroll down list from the keyboard

Expected: Should able to scroll down list from the keyboard

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/107327752-a8f1e180-6ad3-11eb-9d28-7709475ad7ca.png)

**Comment by sKudum** [comment]
Same issue is logged in #5051 PR by accessibility team in issue 5 hence closing. as it is duplicate of it.
