### ISSUE TITLE
Select: Change value is not selecting in order

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4616]
Description: Change value is not selecting in order

Expected: Change value should select in order

Attached the video 
[2021-02-09_12-46-12.zip](https://github.com/SAP/fundamental-ngx/files/5949545/2021-02-09_12-46-12.zip)

**Comment by sKudum** [comment]
Hi Puru, It is upto customers how they want the values to be changed. as of now we have given random basics. It is not a bug.

As we need it for QA..will can update it accordingly
