### ISSUE TITLE
Bug: multi input is not able to filter new tokens

### ISSUE THREAD

**Issue by akatyabg** [SAP/fundamental-ngx#4645]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Provide a way to validate the new tokens in the multi input when new tokens are allowed.

#### Which versions of Angular and Fundamental Library for Angular are affected? 
v0.26.0

#### If this is a bug, please provide steps for reproducing it.
Press enter in this [example](https://sap.github.io/fundamental-ngx/#/core/multi-input#newTokens).
In the example the  `parseFunc` should filter the empty inputs but it doesn't. New items with `undefined` values are added to the result.

**Comment by droshev** [comment]
it is fixed with https://github.com/SAP/fundamental-ngx/pull/4621
