### ISSUE TITLE
Approval Flow: Accessibility issues 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4662]
There are couple of issues found by accessibility team Approval Flow: Accessibility issues 

Attached screenshot: 
[Approval Form.docx](https://github.com/SAP/fundamental-ngx/files/5980040/Approval.Form.docx)

**Comment by platon-rov** [comment]
[Referenced tech spec.](https://app.gitbook.com/@fundamental-ngx/s/docs/approval-flow-phase-3/aria-approval-flow-phase-3)
