### ISSUE TITLE
bug: object marker (platform): title for example is incorrect

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4698]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
the text only examples have the title "icon and text object marker" should be "text only object marker"

https://fundamental-ngx.netlify.app/#/platform/object-marker
![2021-02-16_1](https://user-images.githubusercontent.com/47522152/108073059-4c149f00-7070-11eb-9b22-c78953fecb4f.png)

**Comment by maxym-valor** [comment]
Fixed
