### ISSUE TITLE
Bug: Combobox dropdown select width does not align with input box width

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4718]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Bug: Combobox dropdown select width does not align with input box width (see below).
![image](https://user-images.githubusercontent.com/71797052/108404687-01606780-71d5-11eb-9a56-86109521aaa5.png)
![image](https://user-images.githubusercontent.com/71797052/108404708-08877580-71d5-11eb-88a9-538e4295d143.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.28.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/combobox
Scroll down to: Standard Combobox
Click on down arrow > re-size window > click on dropdown arrow again > see defect

**Comment by xandrio** [comment]
as I can see solution merged to the main:
@Betrozov merged 3 commits into main from fix-platform-combobox on Feb 26

ref to pull:
https://github.com/SAP/fundamental-ngx/pull/4741

**Comment by pierrom** [comment]
Verified. I will close. Thanks
