### ISSUE TITLE
Bug: (Core) Slider is showing Negative value in tooltip wrong when RTL applied

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#4738]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
On switching to Rtl, Negative value is shown as "10-" , but it should be "-10".

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 10

#### If this is a bug, please provide steps for reproducing it.
https://fundamental-ngx.netlify.app/fundamental-ngx#/core/slider
![Screenshot 2021-02-22 at 2 30 17 PM](https://user-images.githubusercontent.com/57661487/108686659-bcfa0200-751b-11eb-8b5d-85bf18cdea1a.png)

#### Is there anything else we should know?
chrome on Mac

**Comment by puru-hk** [comment]
Tested it is working as expected
