### ISSUE TITLE
PR 4741 Testing

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4762]

**Comment by pierrom** [comment]
Thanks Puru! The original issue #4437 has been fixed and verified. But I'm still seeing two things below. 
![image](https://user-images.githubusercontent.com/71797052/109053311-66aecf80-7691-11eb-80b6-9fae8440ade0.png)
![image](https://user-images.githubusercontent.com/71797052/109053372-77f7dc00-7691-11eb-9a77-7f18234e2ac8.png)

**Comment by pierrom** [comment]
Let me know if you want me to close #4437 and open a new issue for the new ones observed above. Thanks

**Comment by puru-hk** [comment]
Tested PR4741 in this url https://deploy-preview-4741--fundamental-ngx.netlify.app/#/platform/combobox. Issue is working as expected.
