### ISSUE TITLE
Bug: Multi Input (ngx-platform) - remove button appears also in the drop down list with unselected options

### ISSUE THREAD

**Issue by akatyabg** [SAP/fundamental-ngx#4781]
#### Is this a bug, enhancement, or feature request?
bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.28.0

#### If this is a bug, please provide steps for reproducing it.
1. Select multiple options so the "x more" label appears
2. Click  on the "x more" label
3. Directly after click on the multi-input button
=> the list with options will be opened and the remove button will be still displayed, although it shouldn't be
#### Please provide relevant source code if applicable.
<img width="663" alt="Screenshot 2021-02-26 at 18 08 45" src="https://user-images.githubusercontent.com/6072782/109332969-22712a00-785f-11eb-9bb8-641054f74c46.png">

<img width="732" alt="Screenshot 2021-02-26 at 18 09 45" src="https://user-images.githubusercontent.com/6072782/109332950-1be2b280-785f-11eb-8dbe-497c19fd7128.png">

#### Is there anything else we should know?
Link to the control: https://sap.github.io/fundamental-ngx/#/platform/multi-input

**Comment by Lokanathan-k** [comment]
@droshev on checking the issue found that component behaviour is normal, it displays the total selected values form the list in order to remove the from the selected values.

On checking the core Multi Input the functionality is similar.
