### ISSUE TITLE
Popover comp. propagates Click event upwards

### ISSUE THREAD

**Issue by parostatkiem** [SAP/fundamental-ngx#479]
#### Is this a bug, enhancement, or feature request?
Bug and feature request
#### Briefly describe your proposal.
Popover's _click_ event is propagated upwards and there's no way to prevent it (a nice way). 
I'd love to be able to turn on/off the _click_ propagation via component's property like `[propagateClick]="true"`. It should be `false` by default. Basically any way to turn it on/off would be okay.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
- Fundamental-ngx: 0.0.31
- Angular: 6.2.9
#### If this is a bug, please provide steps for reproducing it.
Place `Popover` element inside any other element with _click_ listener attached. Once you click the button to expand the `Popover`, the outer element's _click_ will be fired.
#### Please provide relevant source code if applicable.
This is a temporary workaround that solved the problem in my case (but a hacky one 💻):
```html
// my component's template fragment
<fd-popover [alignment]="'right'" (click)="handlePopoverClick($event);" #popover>
  //doesn't matter; the body of Popover
</fd-popover>
```

```TypeScript
// my component's class' fragment
 @ViewChild('popover') private popover: any;

  handlePopoverClick(event) {
    event.stopPropagation();
    if (this.popover && typeof this.popover.onClickHandler === 'function') {
      this.popover.onClickHandler(event);
    } else {
      console.warn("Could not fire Popover's built-in click event");
    }
  }
```

#### Is there anything else we should know?
I'm afraid many other components with built-in _click_ listener may be affected by this bug, please check it.

Also, please update your documentation with "hidden" component API (such as `PopoverComponent.onClickHandler` that I had to find on my own). The documentation is good and readable so far IMO but lacks a lot of props that can already be used :)

In case of any questions, catch up my team [on Slack](https://sap-cx.slack.com/messages/CBGKQGYQN).

**Comment by mikerodonnell89** [comment]
Hi @parostatkiem, thanks for pointing this out.  I think popover should not stopPropagation by default, however, I do think the popover needs to have public (well-documented) open and close methods, so you can configure your own click behavior (such as stopping propagation).
