### ISSUE TITLE
Error: node_modules/@fundamental-ngx/core/lib/bar/button-bar/button-bar.component.d.ts

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#4795]
It's a bug, getting the error on importing any fundamental module in Angular app.

Using Angular 11.2.3
@fundamental-ngx/core": "^0.28.0"

Steps to reproduce:
1. npm i @fundamental-ngx/core 
2. in app.module.ts  import { FundamentalNgxCoreModule } from '@fundamental-ngx/core';

immediately getting the error
**Error: node_modules/@fundamental-ngx/core/lib/bar/button-bar/button-bar.component.d.ts:15:5 - error TS2610: 'disabled' is defined as an accessor in class 'BaseButton', but is overridden here in 'ButtonBarComponent' as an instance property.

15     disabled: boolean;**

tried with different angular app, getting the same error. Getting warning for peer dependencies which is conflicting with other peer dependencies.

**Comment by mrezadeveloper** [comment]
you can add  "skipLibCheck": true in compilerOptions section to tsconfig.json file in root of your project folder.
