### ISSUE TITLE
 Error: Failed to find exported name of node (class OptionComponent

### ISSUE THREAD

**Issue by mrezadeveloper** [SAP/fundamental-ngx#4796]
It's a bug, getting the error on importing fundamental platform module in Angular app.

Using Angular 11.2.3
@fundamental-ngx/platform": "^0.28.0"

Steps to reproduce:

npm i @fundamental-ngx/platform
in app.module.ts
 import {PlatformDynamicPageModule} from '@fundamental-ngx/platform';
then add it to imports section o
immediately getting the error
**Error: Error on worker #1: Error: Failed to find exported name of node (class OptionComponent {
    constructor() {
        /** Option id attribute */
        this.id = `fdp-option-${nextUniqueId$2++}`;
        /** Whether to disable this option specifically. */
        this.disabled = false;
    }
}) in 'node_modules/@fundamental-ngx/platform/fesm2015/fundamental-ngx-platform.js'.

but if I downgrade @fundamental-ngx/platform to 0.26 version it will work.

**Comment by droshev** [comment]
@mrezadeveloper thank you for raising the issue. we will release a hotfix `0.28.1`.
