### ISSUE TITLE
Add ability to extract i18n to Builder

### ISSUE THREAD

**Issue by skocharian** [SAP/fundamental-ngx#4800]

**Comment by manjunathanagaraj** [comment]
i18n support is almost done. This being the case, the builder as well is expected to be completed by this sprint end.

**Comment by manjunathanagaraj** [comment]
Anton is working on this.

**Comment by skocharian** [comment]
Implementation done, documentation pending. ETA Thursday (March 18)

**Comment by fkolar** [comment]
Closed for inactivity
