### ISSUE TITLE
BUG. Core. Select component. Selected value label missing padding. 

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4818]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.28.1-rc.13
#### If this is a bug, please provide steps for reproducing it.
SR: 
1. Open Select component page (Core)
2. See the first example
AR: Label with indicate selected value has no pudding from select input itself. 
ER: Label with indicate selected value should have pudding from select input itself.

_Applicable to the other select input with Selected value field assigned._ 

#### Is there anything else we should know?
<img width="226" alt="Снимок экрана 2021-02-24 в 10 40 33" src="https://user-images.githubusercontent.com/5969492/109648828-c01c7000-7b63-11eb-8648-34f81814c311.png">

**Comment by sKudum** [comment]
Could you please point us to Fiori guidelines on it.what is expected behaviour in this case.

**Comment by sKudum** [comment]
Hi @kenykim , could you please suggest whether its a bug?If yes please do share the values to be followed in it.

**Comment by kenykim** [comment]
First of all, I am not sure why we need the element 'Selected value' underneath the Select input since the selected value already displays in the Select input, and I can't find any guideline about the element from Fiori. 
so not only the padding of it, the overall composition seems to be a bug.

**Comment by sKudum** [comment]
Hi Kenny, selected value is added just for readability purpose for customer  as part of documentation. It is not added as part of select.

**Comment by kenykim** [comment]
What I meant was we don't need to show the selected value twice. (please check the attachment below)
<img width="398" alt="Screen Shot 2021-05-24 at 10 28 24 PM" src="https://user-images.githubusercontent.com/58018352/119443993-5f727e80-bcdf-11eb-834b-426cd4bfeeeb.png">

**Comment by sKudum** [comment]
> What I meant was we don't need to show the selected value twice. (please check the attachment below)
> <img alt="Screen Shot 2021-05-24 at 10 28 24 PM" width="398" src="https://user-images.githubusercontent.com/58018352/119443993-5f727e80-bcdf-11eb-834b-426cd4bfeeeb.png">

I agree with you..but other components like combobox, checkbox, menu etc are following same format in documentation by which for this also we ended up adding it.

**Comment by Seamoo13** [comment]
agree, not a bug
