### ISSUE TITLE
bug: approval flow (platform): for IE11, edit mode UI not correct

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4832]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
the approver boxes layout is not correct on IE 11

#### If this is a bug, please provide steps for reproducing it.
STR:
1. go to https://fundamental-ngx.netlify.app/#/platform/approval-flow in Internet explorer 11
2. click on the edit button
3. look at the layout of the approvers

**Actual results:**
![2021-03-03_3](https://user-images.githubusercontent.com/47522152/109780732-f1eb1080-7c0f-11eb-94d7-dbc0dfed99cf.png)

**Expected results:**
![2021-03-03_4](https://user-images.githubusercontent.com/47522152/109780755-f7e0f180-7c0f-11eb-8f24-b8cf6edbd9d0.png)

**Comment by maxym-valor** [comment]
Fixed
