### ISSUE TITLE
Input in fd-list-item looses focus immediately

### ISSUE THREAD

**Issue by mpienkowski** [SAP/fundamental-ngx#4835]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Inputs inside of `<li fd-list-item>` are loosing focus immediately

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 10.2.3
Fundamental 0.28.0 (0.22.4 too)

Please visit https://stackblitz.com/edit/ejwsmi--run?file=src/app/input-example.component.html and try to focus on the input. The focus is lost immediately

**Comment by DeepakSap14** [comment]
Not able to re-produce it.
please verify and close.

![2021-06-03_12-40-22 (1)](https://user-images.githubusercontent.com/57661487/120603081-426d4680-c469-11eb-9cd0-a5744929ec97.gif)

**Comment by maxym-valor** [comment]
Can not reproduce.
