### ISSUE TITLE
bug: illustrated message - for IE11, images not present

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4836]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
images not loaded on IE

#### If this is a bug, please provide steps for reproducing it.
STR
1. in IE11, go to https://fundamental-ngx.netlify.app/#/core/illustrated-message
2. look at each example

Actual results: no images
![2021-03-03_13](https://user-images.githubusercontent.com/47522152/109812921-57052d00-7c35-11eb-8465-b3600107f954.png)
![2021-03-03_12](https://user-images.githubusercontent.com/47522152/109812925-58365a00-7c35-11eb-8a6b-c434fe8a76ec.png)
![2021-03-03_11](https://user-images.githubusercontent.com/47522152/109812927-58365a00-7c35-11eb-9f84-9ba4003f1f08.png)

Expected results: images will be present
![2021-03-03_16](https://user-images.githubusercontent.com/47522152/109812958-62f0ef00-7c35-11eb-8fff-e6870fa51776.png)
![2021-03-03_15](https://user-images.githubusercontent.com/47522152/109812962-62f0ef00-7c35-11eb-9544-55087051e21b.png)
![2021-03-03_14](https://user-images.githubusercontent.com/47522152/109812964-63898580-7c35-11eb-8c96-9cf0d3d522c4.png)

**Comment by droshev** [comment]
Angular 12 had deprecated IE11 and in Angular 13 will drop the support so we will close the issue
https://github.com/SAP/fundamental-ngx/wiki/Browser-Support
