### ISSUE TITLE
bug: illustrated message - on Safari, buttons are missing focus state style

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4837]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
For Safari, call -to-action buttons are missing the dotted border on focus

#### If this is a bug, please provide steps for reproducing it.
STR
1. open Safari and go to https://fundamental-ngx.netlify.app/#/core/illustrated-message
2. use mouse or keys to focus on any button

actual results: no focus state
![2021-03-03_9](https://user-images.githubusercontent.com/47522152/109814666-700edd80-7c37-11eb-9609-27318de9f84e.png)

expected results: dotted border appears on focus
![2021-03-03_14](https://user-images.githubusercontent.com/47522152/109814684-743afb00-7c37-11eb-9077-76d753c2aa5a.png)

**Comment by InnaAtanasova** [comment]
Hi @Seamoo13 this bug is not related Illustrated Message component. The buttons in the `<fd-illustrated-message-actions>` component are normal buttons with no specific classes coming from Illustrated Message. This bug belongs to Button component.

**Comment by maxym-valor** [comment]
Works well in Safari 14.1.2
@Seamoo13 Do you remember, maybe you tested in earlier version of Safari?

**Comment by Seamoo13** [comment]
> Works well in Safari 14.1.2 @Seamoo13 Do you remember, maybe you tested in earlier version of Safari?

@maxym-valor if you tested it and it's no longer reproduced then you can close the issue with a comment stating so.

**Comment by maxym-valor** [comment]
Not reproducible anymore :)
