### ISSUE TITLE
Update library peer dependencies

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#484]
#### Is this a bug, enhancement, or feature request?
Bug/Enhancement

#### Briefly describe your proposal.
Update the library's peer dependencies. 

Currently https://bundlephobia.com/result?p=fundamental-ngx@0.0.31 can't properly provide an estimate since our dependencies aren't complete. Should go through and check what is a hard dependency for us.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current

**Comment by droshev** [comment]
fixed by #513
