### ISSUE TITLE
Handle Memory Cache

### ISSUE THREAD

**Issue by skocharian** [SAP/fundamental-ngx#4843]

**Comment by dimamarksman** [comment]
still in progress

**Comment by dimamarksman** [comment]
Added entity-in-memory data service implementation.
However at the last meeting it was said we need only rest implementation, `in-memory` means to use an additional layer to handle cache strategy.

Going to add the cache layer service to cover `in-memory` case. Going to raise PR on 16 March

**Comment by dimamarksman** [comment]
Closed by https://github.com/SAP/fundamental-ngx/pull/4937
