### ISSUE TITLE
Bug: Left and right padding on Action Bar is too wide and not aligned with Visua Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4849]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Left and right padding on Action Bar is 32px. According to Visual Core it should be 1rem.
![image](https://user-images.githubusercontent.com/71797052/109900796-c8040f00-7c4c-11eb-9421-9c59b7a0edb6.png)
![image](https://user-images.githubusercontent.com/71797052/109900805-cc302c80-7c4c-11eb-94ac-f20c39c94cb0.png)
![image](https://user-images.githubusercontent.com/71797052/109902792-c8ea7000-7c4f-11eb-9788-34914b475727.png)
![image](https://user-images.githubusercontent.com/71797052/109902806-cdaf2400-7c4f-11eb-8af9-75f65b78a0b2.png)
![image](https://user-images.githubusercontent.com/71797052/109902833-d273d800-7c4f-11eb-8e03-28e6ffcc8b0f.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.28.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/action-bar
Look at all  the Action Bar items

**Comment by xandrio** [comment]
@pierrom  ticket moved to the https://github.com/SAP/fundamental-styles/issues/2269
Issue related to styles

**Comment by xandrio** [comment]
@pierrom you took documentation from **bar** component but test **action bar** component.
Component and documentation is different.
Please check:
https://sap.github.io/fundamental-ngx/#/core/action-bar
https://sap.github.io/fundamental-ngx/#/core/bar

**Comment by pierrom** [comment]
Agreed. Will close. Thanks.
