### ISSUE TITLE
bug: calendar - aria-label shows wrong date for year range

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4851]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
on the year range view, the aria-label has the wrong dates. Shows start year as both start and end years

#### If this is a bug, please provide steps for reproducing it.
**STR**
1. go to https://fundamental-ngx.netlify.app/#/core/calendar
2. go to the standard calendar example
3. in the top of the calendar, click the year '2021'
4. in the top of the calendar click the year range '2021-2040'
5. use dev tools to inspect any year range on the calendar (for example, 2021-2040)
6. look at the aria-label

**Actual results:** the aria-label lists one year as the start and stop year (i.e. '2021 - 2021')
![2021-03-04_4](https://user-images.githubusercontent.com/47522152/109957430-998a4080-7ced-11eb-8f9b-002a822cc496.png)

**Expected results:** aria-label will reflect the correct year range (i.e. '2021 - 2040')

**Comment by Betrozov** [comment]
Link for testing https://deploy-preview-5512--fundamental-ngx.netlify.app
