### ISSUE TITLE
Status Indicator: Focus is not going for all the icons

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4869]
Description: Focus is not going for all the icons

Expected: Focus should go for all the icons

**Comment by droshev** [comment]
I don't understand the issue here? @puru-hk can you provide mode content?

**Comment by puru-hk** [comment]
When I do tab from the keyboard tab order is not focusing for all the icons. This is one of the a11y requirement.

**Comment by droshev** [comment]
i think the focus should go only if the item is actionable. I don't think the icons are in this case?

**Comment by puru-hk** [comment]
Yes I agree but for screen reader if images or icon are used it should be focused then only screen reader will read the icon/images. This is accessibility requirement.
