### ISSUE TITLE
MultiInput: In RTL mode filter icon is showing wrong. 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4871]
Description: In RTL mode filter icon is showing wrong. 

Expected: Filter icon should display properly in RTL mode

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/110286025-37418080-800a-11eb-8f18-ae90af847326.png)

expected:
![image](https://user-images.githubusercontent.com/32538291/110286044-3d376180-800a-11eb-9386-36eb4c2fee4c.png)

**Comment by droshev** [comment]
why?
