### ISSUE TITLE
Multi Input: Dropdown list dropdown select width does not align with input box width

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4873]
Description: Dropdown list dropdown select width does not align with input box width
Expected: Should be aligned with the dropdown list

Screenshot: 
![image](https://user-images.githubusercontent.com/32538291/110287413-77a1fe00-800c-11eb-9323-8f81af36bc68.png)

expected:
![image](https://user-images.githubusercontent.com/32538291/110287448-90121880-800c-11eb-85a3-1f608846a9b6.png)

**Comment by droshev** [comment]
looks like input `fillControlMode` doesn't work
