### ISSUE TITLE
Multi Input: Focus is not as per the fiori3 spec

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4875]
Description: Focus is not as per the fiori3 spec

Expected: Focus should be as per the fiori3 spec

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/110287705-f6973680-800c-11eb-90d4-89955fefe00c.png)

Expected:
![image](https://user-images.githubusercontent.com/32538291/110287754-09117000-800d-11eb-8d44-d6e0298e0647.png)

**Comment by JKMarkowski** [comment]
@puru-hk Is it IE11?

**Comment by puru-hk** [comment]
No It is chrome browser

**Comment by JKMarkowski** [comment]
I can't reproduce it in any chrome/opera/firefox. @puru-hk Could you check it again [here](https://fundamental-ngx.netlify.app/#/core/multi-input)
![image](https://user-images.githubusercontent.com/26483208/111477931-df082e00-872f-11eb-8fef-1deb756e433d.png)
