### ISSUE TITLE
Platform date picker inconsistent in the use of locale for input validation

### ISSUE THREAD

**Issue by slithzerikai** [SAP/fundamental-ngx#4880]
#### Is this a bug, enhancement, or feature request?
Bug in fundamental-ngx/platform date picker.

#### Briefly describe your proposal.
Date Picker input seems to default to American-style (month/day/year) format to validate dates typed in the date picker, even though it uses the specified locale to display the date picked with the picker.

The locale should be used for both input and display formats. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
As per the stackblitz in the documentation (Angular 10.2.3, Fundamental 0.28).

#### If this is a bug, please provide steps for reproducing it.
Go to 
https://sap.github.io/fundamental-ngx/#/platform/date-picker
and scroll down to 'Internationalization of Date Picker'.

Click on the calendar and pick 'January 13 2020'. Calendar displays:
13/01/2020 (correct).

Then type 14/01/2020.
Input field will be highlighted in red. I understand because the input format is month/day/year and month 14 would be invalid.

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/date-picker
and scroll down to 'Internationalization of Date Picker'.

**Comment by DeepakSap14** [comment]
This has dependency on moment datetime-adapter for date validation. can be picked once that is available.

**Comment by slithzerikai** [comment]
> This has dependency on moment datetime-adapter for date validation. can be picked once that is available.

I think a working example would be very helpful, do you think it would be possible to share one? Thanks.

**Comment by maxym-valor** [comment]
Closed in PR 6351
