### ISSUE TITLE
Approval flow: approver detail 

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-ngx#4882]
In the demo, the approver detail page looks like this:
![image](https://user-images.githubusercontent.com/72157987/110398057-e5a7ee80-8027-11eb-9d4e-75248652ffcc.png)

It should look like:
![image](https://user-images.githubusercontent.com/72157987/110398572-fad14d00-8028-11eb-96c3-bc61377129fa.png)

Figma file:
https://www.figma.com/file/pnt77ElAYF802E7QTPMDkQ/Approval-flow-Copy?node-id=1864%3A17275

**Comment by platon-rov** [comment]
@wenyang33 we're providing ability to user to pass a template for that dialog. I will improve our example but it's always up to user which information to have in the dialog.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/20265336/115075165-55e94000-9f03-11eb-80ef-6758b13fbce1.png">

**Comment by platon-rov** [comment]
@wenyang33 see my previous comment please. Can be re-checked and closed.

**Comment by wenyang33** [comment]
@platon-rov Got it. Then let's close this issue and leave the exact format to the product team.
