### ISSUE TITLE
Approval flow: start indicator

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-ngx#4883]
In the demo, it looks like:
![image](https://user-images.githubusercontent.com/72157987/110399649-07ef3b80-802b-11eb-9fd6-3b2ee11e60a3.png)

It should look like:
![image](https://user-images.githubusercontent.com/72157987/110399745-32d98f80-802b-11eb-9d78-afd403ac9ec4.png)

1. The distance to the left should be the same.
2.  There is a small gap between the start indicator and the first card.

**Comment by platon-rov** [comment]
@wenyang33 fixed in the scope of Approval Flow Phase 3. Can be re-checked and closed.

**Comment by wenyang33** [comment]
@platon-rov Thank you, perfect!
