### ISSUE TITLE
Bring Dynamic Page Core implementation in DXP

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#4894]
- [x] Replace Platform Dynamic Page with Core implementation
- [x] Check issue 386 in DXP
- [x] Check issue 387 in DXP

**Comment by JKMarkowski** [comment]
Links for PRs
- [jukebox](https://github.tools.sap/dxp/jukebox/pull/418)
- [micro frontend](https://github.tools.sap/dxp/dxp-micro-frontend-ngx/pull/43)
- [template ui](https://github.tools.sap/dxp/template-ui/pull/33)
- [core](https://github.tools.sap/dxp/core/pull/150)

**Comment by droshev** [comment]
already done
