### ISSUE TITLE
Bug: Left padding on Standard Combobox "Hide Addon Button" should be 1rem 

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#4904]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Left padding on Standard Combobox "Hide Addon Button" is too tight and should be 1rem. See Visual Core spec below.
![image](https://user-images.githubusercontent.com/71797052/110725732-ec239b00-81cc-11eb-9189-20b9fa267a13.png)
![image](https://user-images.githubusercontent.com/71797052/110725749-f2197c00-81cc-11eb-9e75-cefead4eb651.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/core/combobox
Scroll down to Standard Combobox > specifically "Hide Addon Button"

**Comment by xandrio** [comment]
@pierrom Hello, I think it works as expected, this description pointing to the list.
Please check:
![descrition_list](https://user-images.githubusercontent.com/5276786/117444222-d5d25b00-af41-11eb-9a53-8c6faa678f50.png)
![descrition_list-inspector](https://user-images.githubusercontent.com/5276786/117444230-d834b500-af41-11eb-94f6-14e19ee89569.png)

**Comment by xandrio** [comment]
@pierrom BTW, need to find other documentation related to inputs, I think padding of the box related to input components, right now its equal to 0.6 rem. If needed change base padding what we have right now - we need to change docs and change padding in the lib.

**Comment by pierrom** [comment]
Resolved on v30.1 rc.6
