### ISSUE TITLE
How to compact fdp-form-group component

### ISSUE THREAD

**Issue by seeiuu** [SAP/fundamental-ngx#4906]
#### Feature request
add compact version to fdp-form-group component

#### Briefly describe your proposal.
I would like to have a sort of "compact" attribute for "fdp-form-group". I see that the component, as is it, put a fat padding around the field. 

'fd-col__form-group' seem to be the class name that put 1rem padding.

![padding1rem](https://user-images.githubusercontent.com/40612319/110824420-53a41e00-8293-11eb-88c5-f16c77dc77f5.png)

Is there some way to switch with a minor padding? I would like to have a way to put "compact" o "cozy" with a simple boolean attribute

![padding0 0 25rem](https://user-images.githubusercontent.com/40612319/110824432-59016880-8293-11eb-9f9a-99f2149dfe18.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"angular": "~11.2.4",
"@fundamental-ngx/core": "^0.28.1",
"@fundamental-ngx/platform": "^0.28.1",

**Comment by OleksiyDrozdov** [comment]
In order this functionality to work correctly fundamental-style #2655 changes should be merged and released(0.20.0-rc11)
