### ISSUE TITLE
Defect Hunting Issues for Sprint 58 - Stockholm

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#4908]
Please document the issues found during the defect hunting below
Here are some issues from the previous sprint:
- [x] #4871 fixed with https://github.com/SAP/fundamental-ngx/pull/5008
- [x] #4872 fixed with https://github.com/SAP/fundamental-ngx/pull/5009
- [x] #4873 fixed with https://github.com/SAP/fundamental-ngx/pull/4946
- [x] #4875 fixed with https://github.com/SAP/fundamental-ngx/pull/5012

**Comment by mikerodonnell89** [comment]
- [ ] Feed input max height not working
![Screen Shot 2021-03-25 at 3 48 34 PM](https://user-images.githubusercontent.com/2471874/112548312-a4327580-8d81-11eb-96be-686a41f89d93.png)

- [ ] Grid list single select mode - strange tabbing behavior where it is unclear what is being focused every 3rd press of the tab key

- [ ] Considerable lag when pressing a key to change the selected option in a Select (for example Apple is selected and press "P" to select pineapple)

- [ ] Side nav - space/enter does not expand/collapse multi-level option (maybe this is intended behavior)

- [ ] Split button - clearing field returns "undefined".  Also should plus and minus buttons be accessible via keyboard?
![Screen Shot 2021-03-25 at 3 55 34 PM](https://user-images.githubusercontent.com/2471874/112548883-8ca7bc80-8d82-11eb-923c-ee89cb4d4b13.png)

- [ ] Datepicker, datetimepicker, and timepicker pages throw warning `[DOM] Found 7 elements with non-unique id #: `s.
