### ISSUE TITLE
Approval flow: extra add button

### ISSUE THREAD

**Issue by wenyang33** [SAP/fundamental-ngx#4924]
In the demo, there are "add buttons" in each slot:
![image](https://user-images.githubusercontent.com/72157987/111251247-152c9d00-85cc-11eb-8280-5678e8fcb985.png)

It should be only one "add button" even for multiple slots:
![image](https://user-images.githubusercontent.com/72157987/111251325-3ab9a680-85cc-11eb-9f46-ac84d784ac36.png)

**Comment by platon-rov** [comment]
@wenyang33 fixed in the scope of Approval Flow Phase 3. Can be re-checked and closed.

**Comment by wenyang33** [comment]
Hi @platon-rov, in the demo it still has two "Add" buttons.

**Comment by platon-rov** [comment]
@wenyang33 please try on https://deploy-preview-5302--fundamental-ngx.netlify.app/#/platform/approval-flow as we don't have published new release yet, so on sap.github.io it's not present.

**Comment by wenyang33** [comment]
Thank you! @platon-rov It looks good!
