### ISSUE TITLE
Standard List: Tab order is not highlighting entire list in IE browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4941]
Description: Tab order is not working for all the fields in Standard list

Expected: Tab order should go for all the field in the Standard list

**Comment by DeepakSap14** [comment]
Hi @puru-hk 
[fiori page for list](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2036843636) does not mention about outer focus on entire list. so the current behaviour is browser specific.
so the same behaviour is coming for card also which is using list in its content.

let me know your opinion on it.

**Comment by puru-hk** [comment]
@DeepakSap14. Just checked this even normal tab order is not working properly in IE browser version 20H2.

**Comment by DeepakSap14** [comment]
@puru-hk please check fiori page for list component, it does not say anything for list focus on tab. so it is not part of list component implementation.

**Comment by dimamarksman** [comment]
@puru-hk is it still reproducible?
I can't reproduce it on my end, tried in chrome and it works

**Comment by DeepakSap14** [comment]
This should not be valid now.
Now we are not putting focus on entire list, but the first list item.
@puru-hk , please verify it now.

**Comment by dimamarksman** [comment]
@puru-hk  if it's not valid anymore let's close it

**Comment by puru-hk** [comment]
Verified in V0.31 RC.17 tab order is working fine in IE browse
