### ISSUE TITLE
Unstable tests

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#4957]
The tests were failing and they need to be revisit
- [ ] `e2e/wdio/platform/tests/action-list-item.e2e-spec.ts` - line 48
- [ ] `e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts` - lines 81, 92, 126, 211
- [ ] `e2e/wdio/core/tests/alert.e2e-spec.ts` - line 60
- [ ] `e2e/wdio/core/tests/select.e2e-spec.ts`
- [ ] `e2e/wdio/platform/tests/thumbnail.e2e-spec.ts`
- [ ] `e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts`
- [ ] `e2e/wdio/core/tests/action-bar.e2e-spec.ts`
- [ ] `e2e/wdio/core/tests/link.e2e-spec.ts`
- [ ] `e2e/wdio/platform/tests/link.e2e-spec.ts`
- [ ] `e2e/wdio/platform/tests/object-list-item.e2e-spec.ts`

**Comment by droshev** [comment]
@AntonOlkhovskyi  added few more in the list

**Comment by droshev** [comment]
closing it for now. we will reopen if the issue pops again
