### ISSUE TITLE
Bug with button rendering in IE11

### ISSUE THREAD

**Issue by Robyn-Keogh** [SAP/fundamental-ngx#496]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Buttons render perfectly in Firefox, Edge & Chrome, but when using IE11 some of the Fundamental NGX buttons do not render as they should:
![image](https://user-images.githubusercontent.com/10871931/52473082-daeea700-2b8c-11e9-9c3b-b0cf82a67ee6.png)

Similarly, the panel grid works fine in other browsers, but in IE11 all panel grid panel elements display inline, and do not respect the column sizes given.

#### Which versions of Angular and Fundamental NGX are affected?
Fundamental NGX 0.0.31
Angular: 7.1.1

#### If this is a bug, please provide steps for reproducing it.
Create 2 buttons
```
<button fd-button value="Delete" id="deleteBtn" [options]="'light'">Delete</button>
<button fd-button [glyph]="'add'" id="createBtn" [options]="'emphasized'"></button>
```
View in Chrome - Fine
View in IE11 - like screenshot above

Is this a known issue in IE11 or perhaps I am doing something wrong?

**Comment by MattL75** [comment]
Hi, try with the latest version of Fiori Fundamentals (1.4.2) and see. Supposedly they have better support for IE11 now. Didn't test it myself though.

**Comment by MattL75** [comment]
Since we have no update for a bit, I'm closing this for housekeeping. Feel free to reopen if the issue persists.
