### ISSUE TITLE
Accessibility: Quick View

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#4963]
Accessibility: Illustrated Message Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Quick View_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6168999/Quick.View_Core_ARIBA.Controls.docx)

**Comment by olshansky** [comment]
Changed estimate to 2 since it has 7 issues in one card and needs additional investigation about native behavior of email/phone links.

**Comment by olshansky** [comment]
- [x] **Issue 1 EB:** Ideally, on navigating to the links, the corresponding label should be read. Therefore, the label should be associated to the respective UI element. (https://github.com/SAP/fundamental-ngx/pull/5493)
- [ ] **Issue 2 EB:** Ideally, no additional information should be read and the information read should be clear and precise. – **NOTE:** it's native browser behavior, can't find information on how to customize it _(most likely this is impossible at the moment)_.
- [x] **Issue 3 EB:**  Ideally, all the UI elements should be accessible using keyboard. – **NOTE:** from the issue, email could be activated by Enter keypress
- [ ] **Issue 4 EB:** Ideally, the dialog header along with the focused element information should be read when a dialog appears on the screen and no additional information should be read. – **NOTE:** Dialog component issue _(can't assign `aria-labeladby` for dialog)_
- [x] **Issue 5 EB:** Ideally, on activating the button focus should move to the active pop up. Also, the information ‘activated or selected’ should be read on activating the button. (https://github.com/SAP/fundamental-ngx/pull/5493)
- [x] **Issue 6 EB:** Ideally, the dialog must be closed using ‘ESC’ key. (https://github.com/SAP/fundamental-ngx/pull/5493)
- [x] **Issue 7 EB:** Ideally, the horizontal scroll bar must be avoided for the user. (https://github.com/SAP/fundamental-styles/pull/2385)

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 1: fixed

Issue 2:
The issue is not fixed. An additional information is being read.
![image](https://user-images.githubusercontent.com/78714518/120316010-94438e80-c2fa-11eb-8bf5-daf2235d05b2.png)


Issue: 3 : fixed

Issue 4: 
The Company is read but the whole dialog details is read once.
![image](https://user-images.githubusercontent.com/78714518/120316187-c3f29680-c2fa-11eb-9de5-51ee3b29d7e9.png)
Ideally, the dialog header along with the focused element information should be read when a dialog appears on the screen and no additional information should be read. 
The dialog should have focus and should read the focused element.



Issue 5:
The issue is partially fixed and The  Selected or Activated information  of 'Open Popover', 'Open Pop over with heading' and 'Open Dialog' buttons is not read.

Issue 6: fixed.


Issue: 7
The horizontal scroll bars is available and  the pop up is not visible  properly.
![image](https://user-images.githubusercontent.com/78714518/120316843-7f1b2f80-c2fb-11eb-970f-8c64fe3b4547.png)


Issue 1-6 URL:  https://deploy-preview-5493--fundamental-ngx.netlify.app/#/core/quick-view
Issue 7: URL: https://deploy-preview-2385--fundamental-styles.netlify.app/?path=/docs/components-quick-view--popover
JAWS 2021

Thanks and Regards
Sanjay

**Comment by olshansky** [comment]
@Sanjay-1312 @puru-hk

**Issue 2:** we can't manipulate data in this 'Make a call' popover from our library _(at least I can't find any information about it)_, it's related to native Chrome and OS behavior. I can just remove the link, and make the phone text not clickable to prevent appearing of this popover, but I believe a clickable phone number is more user-friendly. 

**Issue 4:** could be re-tested. I hope it fixed, right now it's focusing on the first focusable item. _(I just following [wai-aria example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html))_

**Issue 5:** could be re-tested. Added `aria-expanded` and `aria-haspopup` to the popover's and dialog buttons.

**Issue 7:** could be re-tested. I've updated **fundamental-styles** version in **fundamental-ngx** library, it should fix the issue with scrollbars inside quick view component. 

> the pop up is not visible properly

As for this issue in **fund-styles** it's related to the implementation of documentation and popover component, not exactly to the quick view component.

**Comment by Sanjay-1312** [comment]
Issue 2: chrome issue.

Issue 4:
The dialog all information is read.
The focus should be available on the first UI element on the dialog
![image](https://user-images.githubusercontent.com/78714518/120596165-07ffab80-c461-11eb-8a0d-5b3b04271ac9.png)

issue 5:
The button selected and the dialog name "Employee' and the details of the person and the 'Contact Administration' is not read.
![image](https://user-images.githubusercontent.com/78714518/120596569-8c522e80-c461-11eb-8268-fad3558038b5.png)

Issue 7:
The Horizontal scroll bar should be avoided to the user in the Responsive design.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue: 4
The group header information 'Contact Details' should be for all the pop over and dialog.
![image](https://user-images.githubusercontent.com/78714518/121153143-7084c900-c863-11eb-8ea8-3f8b5a47667e.png)
Expected : The group header name 'Contact Details' should be read.

Issue: 5
On activating the button, the dialog appears and the focus is available on 'Mobile number' but all information about dialog is read at once.
![image](https://user-images.githubusercontent.com/78714518/121153619-d5d8ba00-c863-11eb-82df-8ff54f9c3161.png)
On activating the button dialog name and details of the employee and header Contact Details and the focused mobile information should be read.

Issue 7:
The horizontal scroll bar should be avoided.

URL: https://deploy-preview-5493--fundamental-ngx.netlify.app/#/core/quick-view
JAWS 2021
