### ISSUE TITLE
Bug. Core. Select. Select component doesn’t expand by click on arrow. 

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4979]
#### Is this a bug, enhancement, or feature request?
Bug.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
 v 0.29.0-rc.45 
#### If this is a bug, please provide steps for reproducing it.
Steps to reproduce: 
1. Open Select component (Core)
2. Click on arrow to expend the options. 
AR: Select component is not expanded. 
ER: Select component is expanded  user is able to pick the option. 

#### Is there anything else we should know?
**ENV: FF v88.0 Mac OS**
Note: First click is applied the focus state. The select is expanded on the second click. 

https://user-images.githubusercontent.com/5969492/111973240-f451d380-8b06-11eb-813c-0a0b493ec0fc.mov

**Comment by maxym-valor** [comment]
Can not reproduce.
