### ISSUE TITLE
Styling Cleanup

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5025]
It looks like the technical debt with hardcoded styling in ngx has augmented. We need to address this asap.
There are few options:
1. the hardcoded styles in ngx has been already address in fundamental-styles repo
2. the hardcoded styles in ngx is not reflected in fundamental-styles repo
In case of the first option then the developer needs to remove the hardcoded styling; use the latest from styles; test and open a PR
In case of the second, then the developer needs to bring it there, open a PR, test it, merge it, then do the steps above.

Denoland team:

- [ ] `libs/core/src/lib/busy-indicator/busy-indicator.component.scss`
- [ ] `libs/core/src/lib/datetime-picker/datetime-picker.component.scss`
- [ ] `libs/core/src/lib/dynamic-page/dynamic-page.component.scss`
- [ ] `libs/core/src/lib/notification/notification/notification.component.scss`
- [ ] `libs/core/src/lib/tabs/tab-list.component.scss`

Ariba and Valor team:
- [x] `libs/core/src/lib/avatar-group/avatar-group.component.scss`
- [x] `libs/core/src/lib/card/card.component.scss`
- [x] `libs/core/src/lib/facets/facet-group.component.scss`
- [x] `libs/core/src/lib/file-uploader/file-uploader.component.scss`
- [x] `libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss`
- [x] `libs/core/src/lib/grid-list/components/grid-list-filter-bar/grid-list-filter-bar.component.scss`
- [ ] `libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.scss`
- [x] `libs/core/src/lib/status-indicator/status-indicator.component.scss`
- [x] `libs/core/src/lib/toolbar/toolbar.component.scss`  https://github.com/SAP/fundamental-ngx/pull/6396
- [ ] `libs/platform/src/lib/components/approval-flow/approval-flow.component.scss`
- [x] `libs/platform/src/lib/components/feed-input/feed-input.component.scss` - https://github.com/SAP/fundamental-ngx/issues/5343
- [x] `libs/platform/src/lib/components/form/multi-input/multi-input.component.scss`
- [x] `libs/platform/src/lib/components/form/step-input/step-input.scss` do not use `px` values
- [x] `libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.scss`
- [x] `libs/platform/src/lib/components/table/table.component.scss` https://github.com/SAP/fundamental-ngx/pull/7062
- [x] `libs/platform/src/lib/components/menu/menu-item.component.scss`

**Comment by manjunathanagaraj** [comment]
Status Indicator, Multi Input, feed input - @Lokanathan-k 
Cards, Fixed card layout, Avatar Group, standard list, grid list,nested list popover - @DeepakSap14 
File Uploader, toolbar, step input,menu item - @manu-kr 
Table - @platon-rov

**Comment by platon-rov** [comment]
`libs/platform/src/lib/components/table/table.component.scss` will be started after merging pr #4777. It's in the final phase of reviewing and a lot of platform table styles were refactored in the scope of that PR. I plan to start it on April 15-16.

**Comment by manjunathanagaraj** [comment]
@DeepakSap14 , i will be moving this issuee to milestone 63, since your PR is not yet merged.
@platon-rov , once your approval flow PR is merged, please you can pick up table related issues.

**Comment by platon-rov** [comment]
As for the table (platform) we have ongoing PR #5879 with a lot of changes it makes sense to refactor the styles after it gets merged. Before that, I will do refactoring for the Approval Flow (platform).

**Comment by platon-rov** [comment]
It makes sense to refactor platform table component after #5692 will be merged.

**Comment by Lokanathan-k** [comment]
issues assigned are fixed as part of the below PR
Status Indicator(PR5168 merged), Multi Input(PR5176 merged), feed input(PR5221 merged)

**Comment by manu-kr** [comment]
Assigned issue merged step input(PR6057 merged),menu item(PR5962 merged) 
File Uploader(PR2267 merged in style ) (PR6194 waiting for core team approval to merge)
Toolbar(PR2589 merged) but will have to remove the style in ngx after the latest release of style(v0.20.0) in ngx.

**Comment by platon-rov** [comment]
Table (platform): #5962 blocked by some related components. Agreed with the A11Y team to merge that PR when all the A11Y will be perfect (all blockers will be fixed). Then it's possible to start CSS styles refactoring.

Approval Flow (platform): #6050 going to be merged today, just after that it's possible to start CSS styles refactoring.

Refactoring is possible if no other more urgent/important things are planned to implement firstly because if there are open PR with changes for the component (just like #5962 now for the Table) its styles refactoring is impossible.

**Comment by platon-rov** [comment]
Table Component, Platform: blocked until Styles Library version in the NGX will be bumped.

**Comment by manjunathanagaraj** [comment]
@aberikashvili , please can you take over platform table and approval flow from Platon?
