### ISSUE TITLE
Add support for in-line alerts (previous functionality)

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#503]
Some users have requested that the previous functionality for alerts be put back, so we should add an [inline] input on the alert that allows users to place alerts where ever they need on a page specifically.  This alert should also not need to use the alert service to open/close

**Comment by droshev** [comment]
@mikerodonnell89 is this fixed?

**Comment by MattL75** [comment]
fixed as of #508
