### ISSUE TITLE
bug: dialog (core): playground example height and width options aren't functional

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#5031]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for the dialog playground example, the height, width, minHeight, maxHeight, minWidth, maxWidth options aren't functioning

#### If this is a bug, please provide steps for reproducing it.
**STR 1:**
1. go to https://fundamental-ngx.netlify.app/#/core/dialog
2. scroll down to the playground example
3. mark 'resizeable' option
4. enter values for minHeight, maxHeight, minWidth, maxWidth options
5. open the dialog
6. inspect the dialog
7. use the resize handle in the dialog and watch the width and height in the dialog's style (in inspect)

**Actual results:** can go below set minimum, can go above set max
**Expected results:** show stay within the given min and max range
![Peek 2021-03-29 07-29](https://user-images.githubusercontent.com/47522152/112787546-6d9a7a80-9061-11eb-8853-bdc855c9755c.gif)

**STR 2:**
1. go to https://fundamental-ngx.netlify.app/#/core/dialog
2. scroll down to the playground example
3. set values for height and width (i.e. 200, 200)
4. open dialog, look at dialog size
5. close dialog
6. set new values for width, height (i.e. 800, 800)
7. open dialog
8 look at dialog size

**Actual results:** dialog is the same size, dialog not affected by inputting size
**Expected results:** dialog should be the size set by user
![Peek 2021-03-29 07-30](https://user-images.githubusercontent.com/47522152/112787673-ba7e5100-9061-11eb-8d15-6cb391aa8f6c.gif)

**Comment by droshev** [comment]
It works fine if we set the values in `px`

**Comment by Seamoo13** [comment]
> It works fine if we set the values in `px`

If user must write 'px' in the field, then there should be a placeholder or something to let them know.

**Comment by droshev** [comment]
@Seamoo13 I understand and what you wrote makes sense. On the other hand it is not a bug in the library. the improvement is for the doc site and feel free to open a PR suggesting a doc improvement
