### ISSUE TITLE
documentation avatar: Images there is not alternative text

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5032]
Description: Images there is not alternative text

Expected: All the images and icon should provide the alternative text 

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/112794820-2cb45d00-9085-11eb-9c95-1c5502e36455.png)

**Comment by droshev** [comment]
This can be achieved as part of the component `fd-avatar` by setting `aria-label`. We can improve our doc site
