### ISSUE TITLE
bug: dialog (core) - case where dialog style not correct

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#5036]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
for the playground examples. it is possible to temporairly break the dialog styles

#### If this is a bug, please provide steps for reproducing it.
**STR:**
1. go to https://fundamental-ngx.netlify.app/#/core/dialog
2. scroll down to the playground example
3. click to open the dialog
4. look at the dialog header
5. close the dialog
6. click to uncheck the option 'focusTrapped'
7. click to open the dialog
8. look at the dialog header

**actual results:** dialog header is wrong style/font
Note: if you click on the dialog after this, the styles will be corrected

**Expected results:** will have correct style

![Peek 2021-03-29 16-23](https://user-images.githubusercontent.com/47522152/112843410-36e95200-90ab-11eb-9fd6-4e5224827860.gif)
![2021-03-29_5](https://user-images.githubusercontent.com/47522152/112843431-3b156f80-90ab-11eb-9002-a83cbcce4cee.png)
![2021-03-29_4](https://user-images.githubusercontent.com/47522152/112843432-3b156f80-90ab-11eb-8302-ebe7db5f9f0b.png)

**Comment by puru-hk** [comment]
@xandrio There is no demo url to test this issue in this PR5525

**Comment by Seamoo13** [comment]
removed ready for QA label because PR hasn't received dev approvals yet and no netlify url is available.

**Comment by xandrio** [comment]
https://github.com/SAP/fundamental-ngx/pull/5525
preview ready
