### ISSUE TITLE
Avatar Group: Business card UI is not as per the fiori3 spec

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5046]
Description: Business card UI is not as per the fiori3 spec

The issue is Phone and mobile number is not as per the fiori3 spec and It is not clickable 

Expected: UI should be as per the Fiori 3 spec

Screenshot:
![image](https://user-images.githubusercontent.com/32538291/113288057-0fdd8b00-930c-11eb-918d-64c94e3f707e.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/112964286-d23efd80-9165-11eb-880d-e1852d825809.png)

**Comment by Seamoo13** [comment]
Don't see the difference between the two pics, please provide details.

**Comment by puru-hk** [comment]
Sorry for the confusion. I have updated the screenshot
