### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by stefanozaccaria-centropaghe** [SAP/fundamental-ngx#5049]
#### Is this a bug, enhancement, or feature request?

request

#### Briefly describe your proposal.

Hi, in this moment I am developing an application with "SAP/fundamental-ngx" library as ui. 
Will I be able to refer to the SAP specification when selling? Just as you wrote on your site?
"The @ fundamental-ngx / core library is a set of Angular components built using SAP Fundamental Styles."
Can I put this and logo in my brochure/leaflet?

**Comment by droshev** [comment]
Thank you for raising this question.
@szcentropaghe would you mind providing more information?

**Comment by szcentropaghe** [comment]
Thank @droshev for your quick reply.
I work in a company that makes ERP. My boss asked me to refresh the ERP's ui. After some reaserch we found in "SAP / fundamental-ngx" a good candidate for this kind of job.
My boss would like to know if he can put the sentence "We use the @ fundamental-ngx / core library as a set of Angular components built using SAP Fundamental Styles." with respective logos (sap and fundamental-ngx) in the leaftlets and / or brochures for commercial reasons.
Is there any legal limit in this scenario?
