### ISSUE TITLE
Avatar Group: Overflow or +4 is not showing in Edge, Chrome and Firefox browser

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5052]
Description:  If the avatar group is more it is not showing the  Overflow or +4 in Edge, Chrome and Firefox browser in windows machine

Expected: Overflow or +4 should display

Screenshot:

Edge:
![image](https://user-images.githubusercontent.com/32538291/113090613-d3286b80-9207-11eb-8f70-6cd476eec505.png)

Chrome:

![image](https://user-images.githubusercontent.com/32538291/113090658-e89d9580-9207-11eb-94bd-60ea6f17343c.png)

Firefox:

![image](https://user-images.githubusercontent.com/32538291/113090689-f8b57500-9207-11eb-959b-a1e8ad250cea.png)

Expected:

![image](https://user-images.githubusercontent.com/32538291/113090746-108cf900-9208-11eb-93aa-8e5458d99b3e.png)

**Comment by Seamoo13** [comment]
It shows if you reduce screen size (i.e. if you use inspect mode and change size of screen, avatar group responds to new size and makes overflow.)
current view is able to show all avatarts, that's why there is no overflow

**Comment by olshansky** [comment]
Works as expected _(as described https://github.com/sap/fundamental-ngx/issues/5052#issuecomment-811651348)_
![image](https://user-images.githubusercontent.com/14160094/119825793-02a1de80-bf00-11eb-9d12-18681b3733fc.png)
