### ISSUE TITLE
Bug: Various Dialogs not showing RTL formatting when enabled

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5075]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Almost all the Template Based Dialog are not properly formatted for RTL. They should ALL show RTL format when enabled.
![image](https://user-images.githubusercontent.com/71797052/113644253-3582d100-9639-11eb-9754-408fa218eae9.png)
![image](https://user-images.githubusercontent.com/71797052/113646003-c909d100-963c-11eb-8c01-20245f5acfc1.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/core/dialog
Scroll to all the various Dialog
Click on Open from Template button > see error

**Comment by xandrio** [comment]
@pierrom  duplicated issue:
https://github.com/SAP/fundamental-ngx/issues/4747

root of the issue is the same

**Comment by pierrom** [comment]
Duplicate of #4747. Will close this.
