### ISSUE TITLE
Bug: The footer Button on Dialogs are not aligned with Visual Core should be Compact not Cozy

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5076]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Desktop specs for footer Button on Dialogs should be Compact, Mobile specs are Cozy.
![image](https://user-images.githubusercontent.com/71797052/113650142-97950380-9644-11eb-8440-b4f0efed908e.png)

According to Visual Core specs:
![image](https://user-images.githubusercontent.com/71797052/113650191-aa0f3d00-9644-11eb-8107-37ad3e245e9f.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/core/dialog
Scroll on any of the Dialogs and see error

**Comment by xandrio** [comment]
Currently we can put any kind of buttons in the footer, user choose what kind of button he need to insert.
![buttons_in_footer_custom](https://user-images.githubusercontent.com/5276786/118275382-06307100-b4cf-11eb-9920-7fc49f64f074.png)
So, what I can do right now for this - I can update documentation of mobile example with compact button.
![mobile_dialog](https://user-images.githubusercontent.com/5276786/118275541-38da6980-b4cf-11eb-820e-3f439f5b38e8.gif)

**Comment by maxym-valor** [comment]
Fixed, tested, everything is ok!

**Comment by pierrom** [comment]
Fixed and verified. I will close. Thanks.
