### ISSUE TITLE
Thumbnail: Create Independent video control.

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5078]
Thumbnail: Create independent video controller for thumbnail component to have tooltip for all video control options
Screenshot
[Thumbnail_ARIBA_Controls.docx](https://github.com/SAP/fundamental-ngx/files/6262311/Thumbnail_ARIBA_Controls.docx):

**Comment by manjunathanagaraj** [comment]
@Sanjay-1312 , regarding Issue 5, case1(acc 260.1, "Ideally, the horizontal scroll bar should be avoided for the user.")....is there an alternative here? Because in such cases we cannot display the image properly. I think this is not a bug, but widely accepted behaviour to avoid displaying only partial data. We need not consider it as a bug. Could you please let me us know if you still have any concerns on this?

**Comment by manjunathanagaraj** [comment]
@Sanjay-1312 , regarding issue 5, case 2 and 3, we got new specs for responsiveness. This was initially not in our scope. Manu shall create a separate issue and track it.

**Comment by manu-kr** [comment]
> @Sanjay-1312 , regarding issue 5, case 2 and 3, we got new specs for responsiveness. This was initially not in our scope. Manu shall create a separate issue and track it.

> @manjunathanagaraj Tracking. here https://github.com/SAP/fundamental-ngx/issues/5427

**Comment by manu-kr** [comment]
@Sanjay-1312 , regarding issue 1 As we are using HTML 5 video tag,  the controls are embedded inside tag, so we not have control over the icons to show the tooltip for the icons.

For your reference you can check.

https://www.w3schools.com/html/html5_video.asp

**Comment by manu-kr** [comment]
@Sanjay-1312 , regarding issue 1 As we are using HTML 5 video tag,  the controls are embedded inside tag, so we not have control over the icons to show the tooltip for the icons.

For your reference you can check.

https://www.w3schools.com/html/html5_video.asp

**Comment by manjunathanagaraj** [comment]
@manu-kr , as discussed with @KevinOkamoto , we need to customise the video player to meet accessibility needs. A reusable video player has to be developed at platform later and this should be used inside thumbnail component. So, its going to be a new component development work. We shall park this for now, work on other bugs and then comeback to this. Please apply the label 'on hold'.
