### ISSUE TITLE
Accessibility: Approval Flow

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5079]
Accessibility: Approval Flow Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Approval flow_ARIBAControls.docx](https://github.com/SAP/fundamental-ngx/files/6262634/Approval.flow_ARIBAControls.docx)

**Comment by platon-rov** [comment]
[Referenced tech spec.](https://app.gitbook.com/@fundamental-ngx/s/docs/approval-flow-phase-3/aria-approval-flow-phase-3)
