### ISSUE TITLE
Bug: Component Based Dalog - right padding is not correct and not aligned with Visual Core.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5087]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Right-side padding should be observed and should be 1rem.
![image](https://user-images.githubusercontent.com/71797052/113805524-87008e00-9715-11eb-8a87-9f116b6c9600.png)
Per visual Core:
![image](https://user-images.githubusercontent.com/71797052/113805564-97186d80-9715-11eb-947d-877bfe81db50.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.) 
v0.29.0

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/core/dialog
Scroll down to Component Based Dialog
Click on button: Open from Component

**Comment by xandrio** [comment]
![content_dialog_padding](https://user-images.githubusercontent.com/5276786/118876861-6754ac00-b8f6-11eb-87ff-1a4be95fa1ae.png)

**Comment by xandrio** [comment]
@pierrom please check, we have responsivePadding property, and it works properly with it.
![content_dialog_padding](https://user-images.githubusercontent.com/5276786/118878231-0037f700-b8f8-11eb-8cb0-75189600b481.png)

Can you doublecheck?
Need to decide - allow padding for any config (removing responsivePadding config property check, PR ready) or just to update documentation.

**Comment by xandrio** [comment]
![responsive_padding](https://user-images.githubusercontent.com/5276786/118878656-78062180-b8f8-11eb-93a3-87ade976c67e.png)

**Comment by puru-hk** [comment]
@pierrom could you please retest this issue.

**Comment by pierrom** [comment]
Not yet fixed. Looks the same as @xandrio reported above.
![image](https://user-images.githubusercontent.com/71797052/119712718-be3a1400-be15-11eb-9ff0-d065f2aa9ca8.png)

**Comment by pierrom** [comment]
Not yet fixed. Looks the same as @xandrio<https://github.com/xandrio> reported a couple of days ago. Is there a later netlify link?
***@***.***D75223.2A34B7F0]


From: Purushothamhk ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Sunday, May 23, 2021 at 10:23 PM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Assign ***@***.***>
Subject: Re: [SAP/fundamental-ngx] Bug: Component Based Dalog - right padding is not correct and not aligned with Visual Core. (#5087)


Assigned #5087<https://github.com/SAP/fundamental-ngx/issues/5087> to @pierrom<https://github.com/pierrom>.

**Comment by xandrio** [comment]
@pierrom you can check this PR:
https://github.com/SAP/fundamental-ngx/pull/5523

We have property for dynamic padding (looks like we need to give customer possibility to choose paddings, so in dialog configuration we can turn-on padding). Documentation updated.

**Comment by xandrio** [comment]
@pierrom check please
https://github.com/SAP/fundamental-ngx/pull/5523

**Comment by pierrom** [comment]
Verified. I will close. Thank you.

**Comment by pierrom** [comment]
Verified. I have closed #5087<https://github.com/SAP/fundamental-ngx/issues/5087>. Let me know if you need me to close #5523 as well. Thank you.

From: Alexandr Ivanov ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Friday, May 28, 2021 at 10:42 PM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP/fundamental-ngx] Bug: Component Based Dalog - right padding is not correct and not aligned with Visual Core. (#5087)


@pierrom<https://github.com/pierrom> check please
#5523<https://github.com/SAP/fundamental-ngx/pull/5523>
