### ISSUE TITLE
Table layout is broken when grouping & freezable columns used in the same time

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#5097]
**Describe the bug**

When grouping enabled layout is broken if freezable columns present.

> Is this issue related to a specific component?

Table, Platform component.

> What version of the Fundamental Library Styles are you using?

v0.28.0.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Maintaining Fundamental-NGX.

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular.

**To Reproduce**
1. Open [StackBlitz](https://stackblitz.com/edit/angular-a1tc81?file=src/app/platform-table-groupable-example.component.html).
2. Group by any column.
3. See broken layout.

**Expected behavior**
a) Layout is not broken
b) Freezing columns not possible with grouping at the same time.

**Screenshots**
![image](https://user-images.githubusercontent.com/20265336/114172169-feb10180-993d-11eb-9401-38564699d811.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 89

**Comment by nikvalor** [comment]
Still actual.
![image](https://user-images.githubusercontent.com/74654139/122077211-38056200-ce04-11eb-8c39-cefb2367ffc4.png)

**Comment by platon-rov** [comment]
@nikvalor have you tried it on the prod (sap.github.io) or on the staging (fundamental-ngx.netlify.app)? Seems like the issue is reproducible on prod, but fixed on staging. By the way you can use playground to test such functionality ;)

**Comment by Seamoo13** [comment]
unable to check until stackblitz [fix](https://github.com/SAP/fundamental-ngx/pull/5738) merged
![2021-06-23_3](https://user-images.githubusercontent.com/47522152/123084287-9f856800-d429-11eb-957e-621fd267e86f.png)

**Comment by Seamoo13** [comment]
@platon-rov  with groupable and column freezing for 1st column, bottom borders are not aligned. (playground example)
![2021-06-23_7](https://user-images.githubusercontent.com/47522152/123086488-276c7180-d42c-11eb-804f-8b8519380735.png)

**Comment by platon-rov** [comment]
It will be fixed with [Styles PR #2549](https://github.com/SAP/fundamental-styles/pull/2549)

**Comment by droshev** [comment]
the styling needs to imported. @platon-rov can you bring them?

**Comment by platon-rov** [comment]
@droshev as I see there is PR opened by @denepdabot about bumping styles version in NGX and someone with merge access should merge it but I don't have such permissions.
