### ISSUE TITLE
Remove i18n "select" and "plural" usage in flavour of something more straight forward

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#5098]
#### Is this a bug, enhancement, or feature request?
SAP team uses internaly i18n plugin which does not support  i18n "select" and "plural" syntax

**Comment by droshev** [comment]
@dimamarksman Can you share more background information?

**Comment by dimamarksman** [comment]
@droshev  SAP team that is involved in `Minerva` project uses some private plugin that helps convert `xlf` files to the `csv` special format (adoption for translators engineers) and then back to the `xlf` format. This plugin [does not support](https://github.wdf.sap.corp/Ariba-commons/acom/wiki/ACOM-Angular-XLF-Approach-In-Detail) `select` and `plural` clauses despite the fact [angular does support it](https://angular.io/guide/i18n#mark-plurals).
It was decided that in order not to block the team we can avoid usage of these clauses for now, but in a long-term perspective this plugin should be extended to support this syntax.
