### ISSUE TITLE
Tabs with custom template and routerLink does not have the `is-selected` styling

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5128]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
Create a new project and import fundamental-ngx. 
Use the example from the documentation for Tabs with custom template and routerLink:
```
<nav fd-tab-nav>
    <div fd-tab-item>
        <a fd-tab-link [active]="rla1.isActive" [routerLink]="'tab1'" routerLinkActive #rla1="routerLinkActive">
            <span fd-tab-tag>Link 1</span>
        </a>
    </div>
    <div fd-tab-item>
        <a fd-tab-link [active]="rla2.isActive" [routerLink]="'tab2'" routerLinkActive #rla2="routerLinkActive">
            <span fd-tab-tag>Link 2</span>
        </a>
    </div>
    <div fd-tab-item>
        <a fd-tab-link [active]="rla3.isActive" [routerLink]="'tab3'" routerLinkActive #rla3="routerLinkActive">
            <span fd-tab-tag>Link 3</span>
        </a>
    </div>
</nav>
```

A selected tab does not change the text color and the selection indicator (the bottom underline) is not shown:
<img width="370" alt="Screen Shot 2021-04-14 at 3 16 14 PM" src="https://user-images.githubusercontent.com/39598672/114766484-73b47a80-9d34-11eb-8d6b-50c5357f366f.png">

Expected behaviour/look:
<img width="354" alt="Screen Shot 2021-04-14 at 3 17 28 PM" src="https://user-images.githubusercontent.com/39598672/114766558-8af36800-9d34-11eb-9047-0e5bd233006e.png">

#### Is there anything else we should know?
Adding the styling to the consuming project fixed the problem. The class `is-selected` is properly applied but for some reason the styling is not coming:

```
.fd-tabs__link.is-selected .fd-tabs__tag {
  color: var(--fdTabs_Selected_Color, var(--sapSelectedColor, #0854a0));
}
.fd-tabs__link.is-selected .fd-tabs__tag:after {
  background-color: var(
    --fdTabs_Selected_Color,
    var(--sapSelectedColor, #0854a0)
  );
}
```

**Comment by olshansky** [comment]
Assigned to Oleksiy Drozdov

**Comment by puru-hk** [comment]
Tested in this url https://deploy-preview-5735--fundamental-ngx.netlify.app/#/core/tabs/tab3 it is working as expected.
