### ISSUE TITLE
Menu with Submenus does not take into account the available spacing

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5129]
#### Is this a bug, enhancement, or feature request?
Bug+Enhancement
#### Briefly describe your proposal.
The submenus of the Menu component always open at the right-hand side not taking into account the available space, whuch causes the following problem:
<img width="304" alt="Screen Shot 2021-04-14 at 3 29 23 PM" src="https://user-images.githubusercontent.com/39598672/114768127-79ab5b00-9d36-11eb-9c0c-cbb40945e092.png">

Expected behaviour: the submenus should move to the other side (similar to what popover is doing).

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by maxym-valor** [comment]
Seems like it's not reproducible anymore, looks correct for now
![image](https://user-images.githubusercontent.com/83698366/141077404-e67f60e3-8b6b-459d-a094-1dc968e415d9.png)
![image](https://user-images.githubusercontent.com/83698366/141077484-e7126a4b-19f0-45e9-9fcf-a11f5b6f766c.png)
