### ISSUE TITLE
FormGroup wrong vertical alignment

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#5130]
#### Is this a bug, enhancement, or feature request?
bug

#### If this is a bug, please provide steps for reproducing it.

When you have more than one column and the number of the fields is not equal for each column fields are aligned to the middle instead of to the top 

<img width="1509" alt="Screen Shot 2021-04-14 at 8 25 45 PM" src="https://user-images.githubusercontent.com/17149942/114774432-78971f80-9d70-11eb-9820-1225d1fe44ee.png">

<img width="1194" alt="Screen Shot 2021-04-14 at 9 36 14 PM" src="https://user-images.githubusercontent.com/17149942/114775036-21de1580-9d71-11eb-83ff-ff7d481a82f4.png">

You can see similar examples in our docs https://sap.github.io/fundamental-ngx/#/platform/form-container (e.g. first one). where you have 3 columns in first and 2 in second. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
Angular CLI: 11.2.8
Node: 12.0.0
OS: darwin x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cdk                    11.2.8
@angular/cli                    11.2.8
@angular/material               11.2.8
@schematics/angular             10.1.7
@schematics/update              0.1102.8
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.5
    

```

**Comment by dimamarksman** [comment]
@fkolar  
We can see the same behavior in the fundamental-styles as well.
I think it should be fixed there, going to create an issue in fundamental-styles

**Comment by dimamarksman** [comment]
Corresponding issue has been created in the [fundamental-styles repo ](https://github.com/SAP/fundamental-styles/issues/2262)

**Comment by sKudum** [comment]
PR-https://github.com/SAP/fundamental-styles/pull/2371 will address this issue.

**Comment by sKudum** [comment]
Can we worked on once SAP/fundamental-styles#2371  changes in styles are published. As per latest discussion no styles in library is allowed till then masking it as blocked.
