### ISSUE TITLE
Missing Peer dependencies

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#5141]
#### Briefly describe your proposal.

I have installed the Fundamental Library. On trying to run the app found got the following exception:

An unhandled exception occurred: The target entry-point "@fundamental-ngx/core" has missing dependencies:
 - @angular/router
 - @angular/animations
 
We noticed that the above mentioned dependencies are peer dependencies but we do not need these dependencies in our app, is there a workaround to get rid of the error without explicitly adding the dependencies in the package.json of our main application? 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

angular: ^11.2.6
"@ngx-translate/core": "^13.0.0",

**Comment by droshev** [comment]
@AleenaSA which version of ngx did you use

**Comment by AleenaSA** [comment]
"@fundamental-ngx/core": "^0.28.0",

**Comment by droshev** [comment]
@AleenaSA Can you try to use npm version 6 and let us know if the issue is still there?
