### ISSUE TITLE
Platform MultiInput component not honoring `displayKey` property when processing selected values

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#5147]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
It looks like the MultiInput component is not using the `displayKey` property when processing selected values. 

If we try to assign selected values to the component we get empty tokens:

<img width="1089" alt="Screen Shot 2021-04-16 at 4 11 28 PM" src="https://user-images.githubusercontent.com/48103491/115093213-7519aa80-9ece-11eb-8e05-b794987bea37.png">

```ts
@Component({
    selector: 'fdp-platform-multi-input-example',
    templateUrl: './platform-multi-input-example.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush,
    providers: [{ provide: DATA_PROVIDERS, useValue: new Map() }]
})
export class PlatformMultiInputExampleComponent {
    selected = [
        { firstName: 'Alabama', lastName: 'Montgomery' },
    ];

    _datasource = [
        { firstName: 'Alabama', lastName: 'Montgomery' },
        { firstName: 'Alaska', lastName: 'Juneau' },
        { firstName: 'Arizona', lastName: 'Phoenix' },
        { firstName: 'Arkansas', lastName: 'Little Rock' },
        { firstName: 'California', lastName: 'Sacramento' },
```
```html
<fdp-form-group #fg>
    <fdp-form-field
        #ffl1
        label="Default Multi Input Field"
        id="input-simple"
        name="reactiveFormInput"
        rank="1"
        placeholder="Field placeholder text"
    >
        <fdp-multi-input
            [formControl]="ffl1.formControl"
            placeholder="Field placeholder text"
            type="text"
            id="fdp-id-default"
            name="input1"
            [dataSource]="_datasource"
            [selected]="selected"
            displayKey="firstName"
        >
        </fdp-multi-input>
    </fdp-form-field>
</fdp-form-group>
```

I believe this is due to the fact that in the MultiInput code we have a hardcoded the `label` field as the value used for comparison:

https://github.com/SAP/fundamental-ngx/blob/9c8c8f424b1ca42855242f17d667db05ed33adf2/libs/platform/src/lib/components/form/multi-input/multi-input.component.ts#L199-L200

https://github.com/SAP/fundamental-ngx/blob/9c8c8f424b1ca42855242f17d667db05ed33adf2/libs/platform/src/lib/components/form/multi-input/multi-input.component.ts#L235-L239

https://github.com/SAP/fundamental-ngx/blob/9c8c8f424b1ca42855242f17d667db05ed33adf2/libs/platform/src/lib/components/form/multi-input/multi-input.component.ts#L279-L291

etc.

The component should not be using the `label` field if it allows the user to pick the `displayKey`.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Fundmantal-NGX v0.29.0-rc.90

#### If this is a bug, please provide steps for reproducing it.

1. Create multi-input field where datasource and selected items do not have `label` as an attribute.
2. Bind both datasource and a sublist of selected items to the multi-input component
3. View multi-input component
4. See empty tokens displayed

**Comment by Lokanathan-k** [comment]
fixed as part of PR https://github.com/SAP/fundamental-ngx/pull/5204
![image](https://user-images.githubusercontent.com/53534379/119313558-5064df80-bc91-11eb-94b4-652dba71a69c.png)
