### ISSUE TITLE
FormGroup Vertical Alignment problem

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#5152]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
When label horizontal alignment is used its not aligned on the left but in the middle. 

https://stackblitz.com/edit/u43rku--run?file=src/app/platform-input-example.component.html

<img width="741" alt="Screen Shot 2021-04-18 at 12 33 41 PM" src="https://user-images.githubusercontent.com/17149942/115142489-563c2500-a042-11eb-855b-74044a15e9eb.png">

**Comment by puru-hk** [comment]
Not able to reproduce in the latest ngx version 0.31.0 rc.125
