### ISSUE TITLE
WCAG 2 readiness 

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#516]
When we are discussing and opening question of FIORI 3. it's required by Fiori 3 bronze level to be able to meet accessibility WCAG Conformance Level A.​

https://webaim.org/standards/wcag/checklist

Are you aware of this and are you monitoring your progress to go side by side with WCAG?
Do you have some maybe table which could monitor the progress and compatiblity ?

Frank

**Comment by mikerodonnell89** [comment]
Hi Frank, a few months ago we made sure every component was keyboard and screenreader navigable, and that proper semantic markup was used for each component.  We may need to revisit this for some newer components such as shellbar and file input, we should open individual issues for those cases

**Comment by droshev** [comment]
@fkolar I think this issue is too generic. How about you open an issue per specific component/gap.

**Comment by fkolar** [comment]
@droshev I agree, its such broad topic I dont even understand it myself but I though that you guys already looked at this and can give straigh answer. 

We are focusing on `Level A` only - whatever it means. I am planing to breakdown this into the table and create such checklist. As I see there is soo much information..

**Comment by MattL75** [comment]
Closing this. We can open individual issues for more specific parts of our WCAG2 readiness.
