### ISSUE TITLE
Platform MultiInput dropdown does not change from "drop down" to "drop up" if there is no space below input field

### ISSUE THREAD

**Issue by KevinOkamoto** [SAP/fundamental-ngx#5166]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

If there is no viewport space below the MultiInput field, the MultiInput menu does not adjust its position. Instead it drops down and the menu is cut off.

<img width="1783" alt="Screen Shot 2021-04-19 at 11 45 54 AM" src="https://user-images.githubusercontent.com/48103491/115287786-85679a80-a105-11eb-8431-245f9a1fbe64.png">

The menu should be aware of its position and drop "up" in such cases, as exemplified in the CDK example:

<img width="1510" alt="Screen Shot 2021-04-19 at 11 46 50 AM" src="https://user-images.githubusercontent.com/48103491/115287955-b647cf80-a105-11eb-9809-12a5f422f224.png">

also, example from UI5:

<img width="1783" alt="Screen Shot 2021-04-19 at 12 02 23 PM" src="https://user-images.githubusercontent.com/48103491/115289296-476b7600-a107-11eb-80a9-9f06382f4066.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Fundamental NGX v0.28.0

#### If this is a bug, please provide steps for reproducing it.

1. Goto page with MultiInput component
2. Adjust size of browser window so that there is little space below MultiInput component
3. Type text into MultiInput field so that the suggestion menu is displayed
4. Observe that the menu will be cut-off by the bottom of browser window.

**Comment by Betrozov** [comment]
Same for Platform: Combobox
