### ISSUE TITLE
Dynamic Page container - formatting adjustments

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#5167]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Rename property name from `subtitle` to `subTitle`

https://sap.github.io/fundamental-ngx/#/platform/dynamic-page

**Comment by kavya-b** [comment]
@fkolar why do we need this change? Isn't subtitle a single word?

**Comment by fkolar** [comment]
Closing this issue, as the rest of the library follow the same pattern.
