### ISSUE TITLE
DynamicPageModule

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#5169]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Dynamic page components are using DynamicPageService which is not part of Module but provided by component. Module should contain everything needed and related to create DynamicPage. When we have this on the component level it limits the usage . 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

<pre><code>
Angular CLI: 11.2.8
Node: 12.0.0
OS: darwin x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cdk                    11.2.8
@angular/cli                    11.2.8
@angular/material               11.2.8
@schematics/angular             10.1.7
@schematics/update              0.1102.8
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.5

</code>
</pre>

**Comment by dimamarksman** [comment]
@fkolar `DynamicPageService` should be dedicated for each particular dynamic page that's why it is in component providers section

**Comment by manjunathanagaraj** [comment]
closing this, as per comments and confirmation from @dimamarksman
