### ISSUE TITLE
Comobox: Bug: Combobox dropdown select does not aligned with input field during window re-sizing

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5174]
bug

#### Briefly describe your proposal.
Upon clicking dropdown arrow icon, dropdown select does not aligned with input field during window re-sizing. See pics below:
![image](https://user-images.githubusercontent.com/71797052/105555355-11f8ed00-5cbe-11eb-8ce3-8dfd0892c555.png)
![image](https://user-images.githubusercontent.com/71797052/105555370-18876480-5cbe-11eb-9b42-96fef99bc39d.png)

#### If this is a bug, please provide steps for reproducing it.
Go to: https://sap.github.io/fundamental-ngx/#/platform/combobox
Click dropdown on any input field and make a selection.
Click out of it and resize browser window.
Dropdown select is stuck and frozen on previous size and does not re-size

**Comment by droshev** [comment]
@puru-hk I am not able to reproduce it. Maybe #4437 fixed it?

**Comment by Seamoo13** [comment]
tested, not reproducible.
