### ISSUE TITLE
Multi Input's search text keeps getting reset

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#5177]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

"Multi Input"'s search text keeps getting reset.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@fundamental-ngx/core: 0.28.1
@angular/core: 10.2.1

#### If this is a bug, please provide steps for reproducing it.

Steps to reproduce:

1. Go to https://sap.github.io/fundamental-ngx/#/core/multi-input
2. Search for "ba"
3. See that option "Banana" appears in drop down
4. Add letter "m" so search is "bam"
5. The search query gets deleted

https://user-images.githubusercontent.com/1498400/115510338-e3b88880-a27f-11eb-862c-d99963ee4cb1.mp4

#### Please provide relevant source code if applicable.
-

#### Is there anything else we should know?
-

**Comment by droshev** [comment]
it has been fixed in the latest rc
