### ISSUE TITLE
Bug ViewDestroyedError in datepicker

### ISSUE THREAD

**Issue by santehniki** [SAP/fundamental-ngx#5182]
#### Is this a bug, enhancement, or feature request?
Bug in datePicker control. When user closes calendarView.
![image](https://user-images.githubusercontent.com/4891309/115685955-65341780-a361-11eb-9353-9330ec5f723d.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.) 
Latest version of Fundamental Library for Angular 0.29.1

#### If this is a bug, please provide steps for reproducing it.
Open stackBlitz example:
![image](https://user-images.githubusercontent.com/4891309/115685669-1be3c800-a361-11eb-9e3e-4d0ce96fba6b.png)
Run code. Open and close calendarView.

#### Please provide relevant source code if applicable.
![image](https://user-images.githubusercontent.com/4891309/115685472-eccd5680-a360-11eb-9164-57bb063c530e.png)

**Comment by droshev** [comment]
We need to downport it to older version too

**Comment by droshev** [comment]
@N1XUS could you follow those [instructions](https://github.com/SAP/fundamental-ngx/wiki/Releasing-Backward-Versions-Above-0.24) and downport it to 0.29

**Comment by santehniki** [comment]
Hi!
I tried v0.29.2. The issue still persists:
Also in the stackblitz sample on v0.31.0-rc.121(this fix should be there, but also showing the same error):
![image](https://user-images.githubusercontent.com/4891309/126615581-c77618c3-3c7f-4fbc-9785-455df39de842.png)

Is it the same for you?
