### ISSUE TITLE
Stackblitz examples for Datetime Picker are not working

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5194]
#### Is this a bug, enhancement, or feature request?
bug in the documentation

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
- open the documentation site
- open Stackblitz for any example in Datetime Picker
- the example is not working

**Comment by Betrozov** [comment]
part of https://github.com/SAP/fundamental-ngx/issues/4391
