### ISSUE TITLE
Modal components are not being destroyed

### ISSUE THREAD

**Issue by schaefermichael** [SAP/fundamental-ngx#524]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7.1.1, fundamental-ngx 0.0.32 (Also occurs in the current docs)

#### If this is a bug, please provide steps for reproducing it.
https://sap.github.io/fundamental-ngx/modal -> Component as content example
When opening a modal, it is appended to the DOM. But after closing, the modal service does not destroy it.
In our specific case, it caused some weird behavior in a reactive form.

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/modal -> Component as content example

**Comment by MattL75** [comment]
Yeah I also saw this as I added sizing inputs yesterday. We're just setting display to none, which doesn't remove a component from the DOM. A better solution would probably be to dynamically generate the modal from the modal service and then remove it from the DOM when it's closed. Something similar. Thoughts @mikerodonnell89 ?
