### ISSUE TITLE
Getting reference to tab-list to set selected tab / Expose selectedTab Parameter on Tab-list

### ISSUE THREAD

**Issue by dkipping** [SAP/fundamental-ngx#525]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
To be able to set the selected tab of a tab list programmatically currently you need the tab list handed in as a parameter into the function from within the template.

In a function that does not have the tab list provided as a parameter since it is not called / referenced in the template however, we need other ways of reference.

We would need to either to get a reference to the fd-tab-list instance via e.g. @ViewChild + ElementRef with selected() working (selected does not seem to be working for me when getting the reference via ElementRef) OR to have an exposed `selectedTab` parameter so that we can link a variable to that parameter in the template.
This would enable manipulation of the variable without the hassle of getting the reference of the tab list.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 6, fundamental ngx 0.0.31

**Comment by MattL75** [comment]
I'm not sure I understand the issue. The `select()` method is not working for you? You need to pass it the tab id for it to work, not a reference to the component itself. You could do the following to fix your issue, I believe - assuming you have a tab with an id of `tab2`. Please correct me if I'm wrong.

```
@Component({
    selector: 'fd-tab-selection-example',
    templateUrl: './tab-selection-example.component.html'
})
export class TabSelectionExampleComponent {
    @ViewChild(TabListComponent) tabList: TabListComponent;
    tab = 'tab2';

    methodCall() {
        this.tabList.select(this.tab);
    }
}
```

However, I do think that we should simplify this. Having an input that would be much more straightforward and allow a more flexible component. The current tab implementation could use a bit of work in general.

**Comment by dkipping** [comment]
Sorry if I was unclear here, I should have provided example code.

What I tried was the following:

```
export class AppComponent {
  @ViewChild("tabList", {read: ElementRef}) tabList: ElementRef;
 id = 'tab2'

  method() {
    this.tabList.select(this.id);
  }
}
```

However getting the tabList like this with ViewChild, leaves me with a reference on which I can not call the select() function.
Trying your approach of using TabListComponent directly in the ViewChild leaves me with a Module not found Error:
```
Module not found: Error: Can't resolve 'fundamental-ngx/lib/tabs/tab-list.component' in '/Users/d071578/Documents/aai-landing-page-fd-ng/src/app'
```

I agree that an input would make it quicker and easier to use, however getting a reference like this would be sufficient for the moment if it would work 😅

**Comment by MattL75** [comment]
The issue with the module not being found is due to us not exposing the component in our public_api. It might be worth considering exporting it for cases like this one, tagging @mikerodonnell89 for an opinion.

For now though you should be able to get away with it the ElementRef solution that you have. You may get a compilation error, which is normal, but also does not mean that you cannot access the select method. A solution which also does not throw a compilation error would be the following.

`
    @ViewChild('tabList') tabList: ElementRef;

    methodCall(): void {
        (this.tabList as any).select('tab2');
    }
`

I can get this to work in a blank app, let me know if you have questions 😄  For now, this should be sufficient as a workaround for your problem I think. At least until we either revamp the tab component, add an input, or expose TabListComponent in public_api.

**Comment by dkipping** [comment]
Hi Matt,

Yes this was sufficient as a workaround, thanks a lot!

**Comment by MattL75** [comment]
I'll close it. We'll create a more broad issue about a tab revamp once we get to it. Glad your issue is fixed :)
