### ISSUE TITLE
Implement Multi Combobox Component

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#526]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
implement multi combo box component
- allow adding custom content items

![screen shot 2019-02-15 at 10 53 23 am](https://user-images.githubusercontent.com/4380815/52868021-421dd580-3110-11e9-9eae-e9c71115ca47.png)

**Comment by MattL75** [comment]
I think this is referred to as multi-input in fundamental?
