### ISSUE TITLE
Add a counter for the remaining characters in TextArea

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5262]
#### Is this a bug, enhancement, or feature request?
enhancement (missing functionality)

#### Briefly describe your proposal.
TextArea should have a counter that keeps track of the remaining characters.
<img width="923" alt="Screen Shot 2021-04-30 at 4 35 29 PM" src="https://user-images.githubusercontent.com/39598672/116751818-97cdb800-a9d2-11eb-9b4b-b2c1f2eec7ea.png">

Acceptance criteria:
- an option to specify the number of characters in the field
- counter 
- validation

**Comment by droshev** [comment]
we have it in platform
