### ISSUE TITLE
on label Extra margin applied which is coming on opposite side of status indicator

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#5270]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Margin on label should not be coming opposite side of status indicator.

**Extra margin coming on top of label**.
<img width="619" alt="Screenshot 2021-05-03 at 3 53 03 PM" src="https://user-images.githubusercontent.com/57661487/116866104-76660980-ac28-11eb-8415-3606b75d2b1b.png">

correct behaviour :
<img width="921" alt="Screenshot 2021-05-03 at 3 56 06 PM" src="https://user-images.githubusercontent.com/57661487/116866041-5a626800-ac28-11eb-95a5-c20fc8773a31.png">

**Comment by Lokanathan-k** [comment]
This requires the style change created a style issue https://github.com/SAP/fundamental-styles/issues/2331 and will be working on it and will be closing the current issue.
