### ISSUE TITLE
Table component - add option to control the width of the column

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5274]
#### Is this a bug, enhancement, or feature request?
The user should be able to set the width of the column with a property, not by applying an inline styling or adding a class.

#### Is there anything else we should know?
Should be implemented in both Core and Platform

**Comment by platon-rov** [comment]
Sorry, my PR isn't related to the core component. Unassigning myself, PR description updated.

**Comment by manjunathanagaraj** [comment]
@InnaAtanasova , this is added for platform table(PR pointed by Platon), therefore removing 'platform' label.
