### ISSUE TITLE
bug: action sheet compact items change to cozy after being clicked

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#5275]
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

v0.29.1

#### If this is a bug, please provide steps for reproducing it.

Open the compact action sheet and click an item.  The popover will close. Open the action sheet again and you will see that the clicked item has changed to cozy size.

![Screen Shot 2021-05-03 at 2 10 28 PM](https://user-images.githubusercontent.com/2471874/116927879-84f8f480-ac19-11eb-989e-1d6659edef9c.png)

**Comment by puru-hk** [comment]
Tested in this URL https://deploy-preview-5552--fundamental-ngx.netlify.app it is working as expected.
