### ISSUE TITLE
Refactor Avatar Group to not rely on styling from the documentation

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5285]
Currently there's a lot of styling added in the scss example tab. We need to get rid of this code and move it in fundamental-styles if necessary.

**Comment by olshansky** [comment]
> Another issue related to Avatar Group:
> When the user clicks on an avatar in the avatar group example a popup opens.
> When they click a link within this popup it does not do anything and just closes.

Fixed in https://github.com/SAP/fundamental-ngx/pull/5074
