### ISSUE TITLE
Dialog with no backdrop is not positioned in the middle of the screen

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5286]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Dialog with no backdrop is not positioned in the middle of the screen

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.29.1
#### If this is a bug, please provide steps for reproducing it.
Create a Dialog and set the `hasBackdrop` property in the config object to `false`. 
```
const dialogRef = this._dialogService.open(dialog, { 
          hasBackdrop: false
});
```

This is how the dialog is positioned:
<img width="1659" alt="Screen Shot 2021-05-04 at 1 38 40 PM" src="https://user-images.githubusercontent.com/39598672/117046506-c43d4900-acde-11eb-807e-fe774859b6e4.png">

This is how it's positioned with backdrop:
<img width="2553" alt="Screen Shot 2021-05-04 at 1 38 21 PM" src="https://user-images.githubusercontent.com/39598672/117046569-d4edbf00-acde-11eb-9966-1f340a65cddc.png">

**Comment by Seamoo13** [comment]
relates to https://github.com/SAP/fundamental-ngx/issues/5034

**Comment by puru-hk** [comment]
Verified in this url https://deploy-preview-5626--fundamental-ngx.netlify.app/#/core/dialog. it is working as expected.

**Comment by puru-hk** [comment]
As this PR5626 is not merged. Hence reopening this issue
