### ISSUE TITLE
BUG. Input. Core. Disabled inputs are skipped bu Tab navigation.

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#5288]
#### Is this a bug, enhancement, or feature request?
BUG
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.29.2-rc.1
#### If this is a bug, please provide steps for reproducing it.
SR: 
1. Focus element previous to disabled input. 
2. Click Tab. 
AR: Disabled input is skipped bu Tab navigation.
ER: Disabled input is in focus state

**Comment by kavya-b** [comment]
Hi @AntonOlkhovskyi  disabled elements generally don't get focus, so this is the expected behaviour - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled 
![image](https://user-images.githubusercontent.com/53509521/117122536-a0980280-adb3-11eb-8834-0321e7533268.png)

**Comment by kavya-b** [comment]
@puru-hk @Seamoo13 please verify this. 

> Hi @AntonOlkhovskyi disabled elements generally don't get focus, so this is the expected behaviour - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled
> ![image](https://user-images.githubusercontent.com/53509521/117122536-a0980280-adb3-11eb-8834-0321e7533268.png)

**Comment by Seamoo13** [comment]
ok, not an issue.
