### ISSUE TITLE
alert doesn't work properly since v 0.0.31

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#529]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
After v 0.0.31 the alert elements after dismiss stay in the dom

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular v 7.3
fundamental-ngx 0.0.31 and later

**Comment by mikerodonnell89** [comment]
Note to self: check out Matt's solution for modal https://github.com/SAP/fundamental-ngx/pull/528
