### ISSUE TITLE
Carousel: Empty State is not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5290]
**Describe the bug**
Carousel: Empty State is not aligned with Visual Core. Information may not be sufficient (see Ariba UX suggestions below), icon is not proportional in size to the content strings.
![image](https://user-images.githubusercontent.com/71797052/101419884-d2a94500-38a5-11eb-9106-e6f8f9eaf018.png)

> Is this issue related to a specific component?
Carousel empty state
> What version of the Fundamental Library Styles are you using?
v0.25.0

**To Reproduce**
1. Go to: https://fundamental-ngx.netlify.app/#/core/carousel
2. Scroll down to: Carousel error message when no item is loaded
3. See error: 
![image](https://user-images.githubusercontent.com/71797052/101420022-37fd3600-38a6-11eb-8751-11220b2f2d58.png)

**Expected behavior**
Visual Core suggest:
![image](https://user-images.githubusercontent.com/71797052/101420085-56633180-38a6-11eb-915d-fe60b1621721.png)
Ariba UX:
![image](https://user-images.githubusercontent.com/71797052/101420137-68dd6b00-38a6-11eb-9bab-ab89c39c0f57.png)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome, Firefox, Safari
 - v0.25.0

**Comment by InnaAtanasova** [comment]
Issue is blocked by Message Page component.

**Comment by droshev** [comment]
Message Page is already in ngx
