### ISSUE TITLE
[rl-license_file-2] License doesn't seem to be compliant (e.g. Apache 2.0, CC-BY 4.0, MIT)!

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5298]
This issue was generated by the SAP Repository Linter. It checks repositories for their compliance with the SAP open source project guidelines. As an SAP employee you can see further details at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-License(rl-license_file-XX)

**Comment by SebastianWolf-SAP** [comment]
This one was fixed by #5838, thanks for merging!
