### ISSUE TITLE
bug: Platform Forms validation message appears inconsistently

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#5326]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
In components where there can be more than 1 type of validation, we can see the validation error message shows up inconsistently. It should show continuously until the error is gone.
#### If this is a bug, please provide steps for reproducing it.
1. Go to Platform Step Input https://fundamental-ngx.netlify.app/#/platform/step-input
2. Go to example Number Step Input with reactive form
3. Focus into the input, the 'required' error comes up.
4. Start enter values from 1-9, notice that validation message appears on every other change
![image](https://user-images.githubusercontent.com/4380815/92054740-24e54200-ed5c-11ea-84d6-4af9e3b2ca09.gif)
Expected: validation message should show continuously until the error is gone.

#### Is there anything else we should know?
This is not specific to Step Input, any component using Platform Forms and having multiple validations can see this issue. 
The triggers currently used are : `'input', 'click', 'mouseenter', 'mouseleave'`. Having `'focusin', 'focusout'` works to fix this particular use case, but doesn't work for components which should show the message without focusing, such as radio group where submitting without selecting a button should show an error(focusing on the radio button might select it and invalidate the error) : 
![image](https://user-images.githubusercontent.com/53509521/117421104-d7008980-af3b-11eb-881a-afc9924964c1.png)

**Comment by OleksiyDrozdov** [comment]
@kavya-b 
could you please provide detailed steps to reproduce, actual and expected behaviour for second scenario (use with reactive form).

**Comment by kavya-b** [comment]
Hi @OleksiyDrozdov do you mean what I talked about with the image 'use with reactive form' ? Here are the steps: 
- Go to https://fundamental-ngx.netlify.app/#/platform/radio-group 
- Go to first example ' Radio Group With Radio Buttons Passed as Content Projection' and look for the fourth radio button group titled 'Radio group with disabled button and validation error' with Submit and Reset button
- Click on Submit button (do not click any radio buttons)
- Notice that the radio buttons get red(error) border and hovering over the radio button group shows the error. 

Expected: Error should appear all the time, not just on hovering. 
Actual: Error appears only on hovering

![2021-07-08_12-34-30 (1)](https://user-images.githubusercontent.com/53509521/124877774-089fda80-dfe9-11eb-898e-e31f2860acdb.gif)

What I was trying to say was, if we kept `'focusin', 'focusout'` as the triggers here for showing the error message, then focusing(through mouse) on the radio button will just select the radio button and the error won't show up ever. Therefore, I was not sure if having only `'focusin', 'focusout'` as the triggers would be enough.
