### ISSUE TITLE
bug: Split-button (core): when you click on any button in first section - you get 2 alerts instead 1

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5347]
#### Is this a bug, enhancement, or feature request?
It is a bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v 0.30.1-rc.1
#### If this is a bug, please provide steps for reproducing it.
1. Visit https://fundamental-ngx.netlify.app/#/core/splitButton
2. Click on Main Action or another else
**Expected result:** an alert 'Main Action clicked' appears
**Actual result:** two alerts appear, first 'Primary button clicked' and second 'Main Action clicked'
![Fundamental_Library_for_Angular_-_Google_Chrome_2021-05-11_15-30-52](https://user-images.githubusercontent.com/83698366/117815799-81dfb300-b26e-11eb-84fc-2e6de161970b.gif)
 

#### Is there anything else we should know?
No

**Comment by DeepakSap14** [comment]
@InnaAtanasova @droshev 
Is it valid issue for Core menu component?

As per implementation, whenever primary button is clicked, we are also clicking selected menu Items in component. which will help user in identifying which item is selected.
is this functionality fine, or should be modified in respect of this issue raised.

**Comment by InnaAtanasova** [comment]
@DeepakSap14 This is a screenshot from the Fiori Design Guidelines. Here's also the link to it: https://ux.wdf.sap.corp/fiori-design-web/button/#split-menu-button

Whenever in doubt you can check the guidelines and/or the visual specs. 
<img width="765" alt="Screen Shot 2021-06-08 at 9 12 54 AM" src="https://user-images.githubusercontent.com/39598672/121198037-d0697880-c83f-11eb-878d-0f9c04b14d3d.png">

**Comment by droshev** [comment]
i don't think there is a bug. The current documentation is confusing. What we need to do is to enhance the documentation explaining those features/API and update the examples:
- [ ] TBD
- [ ] TBD
