### ISSUE TITLE
bug: Split-button(core): drop-down does not close after selecting an element

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5348]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v 0.30.1-rc.1
#### If this is a bug, please provide steps for reproducing it.
1. visit https://fundamental-ngx.netlify.app/#/core/splitButton
2. open on drop-down arrow and choose any point
**Expected result:** after you select an point - drop-down will close
**Actual result:** drop-down does not close after selecting

#### Is there anything else we should know?
No

**Comment by DeepakSap14** [comment]
@InnaAtanasova @droshev 
Is it valid issue for Core menu component?

As per implementation, we are closing Core menu only on escape button and outside focus, not on Menu Item select.
in platform menu we have implemented to close the Menu on menu-item select but not in core menu.

**Comment by puru-hk** [comment]
@Betrozov Tested but I found using the keyboard i'm able to select the list option. 
1. After selection the alert is not shown.
2. After selection of the list continuation of tab order is not working. Again focus is starting from the beginning

**Comment by puru-hk** [comment]
Verified in this PR5690 it is working as expected.
