### ISSUE TITLE
Upgrade Datepicker/Calendar keyboard navigation

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#535]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current

**Comment by mikerodonnell89** [comment]
Specifically, the only differences I see are:

- ui5's datepicker calendar does not open with the keyboard - calendar icon must be clicked
- on ui5, when the day selection grid is open, pressing the right key on the last day of the week will move focus to the first day of the following week (and vice-versa for the first day of the week/left arrow).  If the last day of the month is focused and the right arrow key is pressed, the first day of the next month will be focused.  In fd-ngx, if the last day of a week/month is selected and the user presses the right arrow key, nothing happens.  Same general idea applies for month and year selection

@MattL75 am i missing anything?

**Comment by MattL75** [comment]
focus trap, otherwise this sums it up well

**Comment by mikerodonnell89** [comment]
I think the UI5 calendar should not trap focus entirely, this prevents keyboard-only users from navigating off the calendar when they don't want to make a selection

**Comment by MattL75** [comment]
They're not trapped - if they press enter it selects a date and closes the popover

**Comment by droshev** [comment]
can we hold on this PR for a little while?

**Comment by droshev** [comment]
At the moment the datepicker opens up automatically when the focus ends up on the input field. I think it would be more logical the following scenario:
1. focus goes on the button of the datepicker
2 the user click space and then the pickers shows

**Comment by droshev** [comment]
@mikerodonnell89 the focus trap doesn't work either

**Comment by jeffredodd** [comment]
@droshev I would agree with your suggestion here. The issue with allowing users to navigate while pressing up/down/left/right during the focus of the `<input>` is that you're overriding the users ability to navigate left and right within the text input. 

By putting the calendar into a `role='dialog'` via the click of a date picker button, you create consistency for your inputs and a better calendar experience.  

> At the moment the datepicker opens up automatically when the focus ends up on the input field. I think it would be more logical the following scenario:
> 
> 1. focus goes on the button of the datepicker
> 2. the user click space and then the pickers shows
> 
> Let's see what the others think

**Comment by droshev** [comment]
@jeffredodd and what about focus trap - we enable it once the calendar is open, right?
