### ISSUE TITLE
ng build with production flag causes error

### ISSUE THREAD

**Issue by JensSteckhan** [SAP/fundamental-ngx#5357]
#### Is this a bug, enhancement, or feature request?
error

#### Briefly describe your proposal.
angular offers a production flag when it builds your project:  
ng build --prod="true"  
It used to work fine with fundamental-ngx. Now it causes an error
ERROR in Unexpected value 'undefined' exported by the module 'PlatformSwitchModule in /dev/minutes/node_modules/@fundamental-ngx/platform/fundamental-ngx-platform.d.ts'

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
We are currently on fundamental-ngx 0.26.1 and angular 10.2.3.
Don't know whether it happens in higher versions

#### If this is a bug, please provide steps for reproducing it.
Build any project with ng build --prod="true"

**Comment by droshev** [comment]
In case this was fixed in a newer version we should consider donwporting it

**Comment by droshev** [comment]
the issue should be fixes with the latest rc version
