### ISSUE TITLE
Core: exclude cross-module references

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#5359]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
We currently have inter-references between modules, which removes Tree-shake ability and eliminates the possibility of creating sub-packages for each module.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.30

**Comment by dimamarksman** [comment]
@N1XUS could you please be more specific? What modules are you talking about?

**Comment by N1XUS** [comment]
@dimamarksman majority of the modules are cross-referenced inside other modules. For example, dialog module dependencies:
![image](https://user-images.githubusercontent.com/6586561/118494383-c2d23e80-b72a-11eb-9bbb-5afc2a15fe5a.png)

**Comment by dimamarksman** [comment]
@N1XUS thanks for your response.
Ideally, we have to create a separate issue for each particular case and fix it step by step

**Comment by droshev** [comment]
@dimamarksman we can start with separating dialog and wizard #5402 
How about platform? shall we run the same exercise?
