### ISSUE TITLE
Notification component -  Screen reader is not reading label for close button and also tooltip is not showing for any of the button. 

### ISSUE THREAD

**Issue by manu-kr** [SAP/fundamental-ngx#5393]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
 Make screen reader should read the label for close button and add tooltip value for all the buttons.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 10

**Comment by sKudum** [comment]
Not re producable in latest version.

1.All close button are ready by screen readers.
2.buttons without or truncates text will have tooltips A per w3c Standards.

Hi @puru-hk It is not a bug.Please have a look.

**Comment by puru-hk** [comment]
@sKudum Tool tip is not shown for overflow button. And screen reader is reading as button for the overflow button. Please check.

**Comment by sKudum** [comment]
> @sKudum Tested in the latest version. Tool tip is not shown for overflow button. And screen reader is reading as button for the overflow button. Please check.

Sure..how about point 1 and 2?

**Comment by puru-hk** [comment]
Point 1 and 2 is working fine

**Comment by puru-hk** [comment]
Tested in this url https://deploy-preview-5490--fundamental-ngx.netlify.app . it is working as expected.
