### ISSUE TITLE
Avoid conflicts of CSS between two apps using Fundamental-Styles

### ISSUE THREAD

**Issue by jamaiyar** [SAP/fundamental-ngx#5405]
#### Is there anything else we should know?

We are using components of fd-ngx to build a web component (wc1) which is going to be consumed by another app (app1) that internally uses fundamental-styles to make their screens fiori compliant.

When this happens (app1 consumes wc1), there is a styling conflict observed in some of the ui controls of app1. This happens primarily because of two reasons:

1. Angular’s rendering engine hoists all styles tags of wc1 to the main document. (see first image)
2. fd-ngx components are marked as ViewEncapsulation: None, by design, which also means that css rules in the style tags are not scoped to _ngcontent attributes 

#### Probable solution:
One potential solution could be allowing apps to tell fd-ngx to prefix the CSS rules of fundamental-styles with a given keyword. ex: `.wc1-content .fd-button {...}`

Obviously, there could be other ways to solve the problem also.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/758398/118681094-efff1980-b81c-11eb-88b1-deac7ed92da1.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/758398/118681155-fe4d3580-b81c-11eb-973d-b312dd3c7a8c.png">

**Comment by droshev** [comment]
Hi @jamaiyar, thank you for opening this issue.
Actually it raises a very interesting case. I think we can achieve this diff. version isolation by adopting CSS Modules in fundamental-ngx. This will prevent multiple version conflicting.
We would need to investigate this further but expect an update soon

**Comment by anushanadig** [comment]
Hi @droshev,

I work with @jamaiyar on CCM-UI. We can also use sass-loader to prefix CSS rules dynamically.
https://webpack.js.org/loaders/sass-loader/#additionaldata

**Comment by droshev** [comment]
> Hi @droshev,
> 
> I work with @jamaiyar on CCM-UI. We can also use sass-loader to prefix CSS rules dynamically.
> https://webpack.js.org/loaders/sass-loader/#additionaldata

for now you can go with the scoping approach in the ticket. Once we see how to enable CSS Modules(which does something similar) we will let you know
