### ISSUE TITLE
Components not rendering as expected in different browsers

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#5413]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
the fd components for angular are getting displayed as expected in Chrome browser, however we noticed discrepancies in the Mozilla Firefox and Safari, attaching the document highlighting the same

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: ^11.2.6
"@fundamental-ngx/core": "^0.28.1"

[fd-styles issues.docx](https://github.com/SAP/fundamental-ngx/files/6507960/fd-styles.issues.docx)

The content from the attachment:
- [ ] ellipsis in firefox when using fd-title when used withing flex display
chrome vs. Firefox
![image](https://user-images.githubusercontent.com/4380815/119748603-4692d600-be63-11eb-849e-fbafcbdc88e2.png)

- [x] search icon not getting aligned properly within input group in Safari
Chrome vs. Safari
![image](https://user-images.githubusercontent.com/4380815/119748610-4abef380-be63-11eb-9f66-582d927a78de.png)

**Comment by N1XUS** [comment]
Hello @AleenaSA. Could you please give a code snippet for the first issue?
As for the second one, I've checked input group component in latest safari, and couldn't reproduce the issue you've had.

**Comment by AleenaSA** [comment]
Hi, we were able to fix the first issue by making CSS changes, still not quite sure why the behavior was different just for firefox. And for the second one it seems the issue is not occurring now...  without making any change since the glyph field was provided within the fd component and we didn't add the icon separately. 

`<fd-input-group class="input-field"  type="search" glyph="search" placeholder="Search" [compact]="true"
</fd-input-group>`
