### ISSUE TITLE
Defect hunting for Sprint 62

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5420]
Please record the bugs you found with a short explanation and a screenshot or gif.

**Comment by mikerodonnell89** [comment]
- [ ] Avatar group RTL - missing margin between text and icon in popover 
<img width="519" alt="Screen Shot 2021-05-19 at 8 23 03 AM" src="https://user-images.githubusercontent.com/2471874/118829642-8530fb00-b87b-11eb-88c9-51cb5e462271.png">

**Comment by aberikashvili** [comment]
[ ] Alert icons disappearing when RTL is on

RTL off
![image](https://user-images.githubusercontent.com/3863691/118865529-15aa2280-b8f2-11eb-8c26-244f41633869.png)

RTL on
![image](https://user-images.githubusercontent.com/3863691/118865562-1f338a80-b8f2-11eb-9288-97929aeca5c8.png)

**Comment by N1XUS** [comment]
- [ ] Calendar: On mobile devices, mobile calendar navigation container is not centered when opened in landscape mode
![image](https://user-images.githubusercontent.com/6586561/118944134-f5637d80-b95c-11eb-808d-907169841383.png)
![image](https://user-images.githubusercontent.com/6586561/118944304-1deb7780-b95d-11eb-9e76-7cab77e1331b.png)

- [ ] Card: RTL mode, wrong positioning of counter
![image](https://user-images.githubusercontent.com/6586561/118944384-30fe4780-b95d-11eb-9b82-1b87ec26a801.png)
![image](https://user-images.githubusercontent.com/6586561/118944473-45dadb00-b95d-11eb-805a-921772eaae8c.png)

- [ ] Carousel: RTL mode breaks navigation with gestures
![image](https://user-images.githubusercontent.com/6586561/118944817-93574800-b95d-11eb-8391-618120d5620c.png)
https://user-images.githubusercontent.com/6586561/118945094-cd284e80-b95d-11eb-8c0b-437195beeacd.mov

- [ ] Dialog: RTL not affecting dialog itself 
![image](https://user-images.githubusercontent.com/6586561/118945848-84bd6080-b95e-11eb-98e7-305c43800cdb.png)

- [ ] Facets: RTL for counter looks odd 
![image](https://user-images.githubusercontent.com/6586561/118946085-bcc4a380-b95e-11eb-8a17-96068708473b.png)

- [ ] Feed list: no space before "Reply link" 
![image](https://user-images.githubusercontent.com/6586561/118946330-f2698c80-b95e-11eb-8cd4-cdbdcef4d571.png)

- [ ] Message strip: If we close message strip example in Playground section, and then remove "dismissible" property. message strip should be visible again. Currently it disappears until page is refreshed. Another option is to add "Reset" button in playground section which will reset example to defaults.
- [ ] Pagination: RTL mode didn't change order of the pages. After clicking on "Go to page 1" button, order changed to correct one
![image](https://user-images.githubusercontent.com/6586561/118947668-3c06a700-b960-11eb-938a-6ada609a9753.png)

- [ ] Rating indicator: RTL counter has wrong positions of items
![image](https://user-images.githubusercontent.com/6586561/118947995-8d169b00-b960-11eb-9fb0-a659be0fa7d3.png)

- [ ] Wizard: RTL mode have some issues with navigation items placement: 
![image](https://user-images.githubusercontent.com/6586561/118948348-dc5ccb80-b960-11eb-974d-fdcd52d906da.png)
