### ISSUE TITLE
bug: dialog component (core): if unselect 'focus trapped' checkbox and open-close dialog window - extra dialog window is visible

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5451]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
If unselect 'focus trapped' checkbox - we will have two dialog window. First - main, which appears at the center of the screen, and second - under first, it visible when you closing first dialog window.
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/dialog
2. Go to PlayGround section
3. 'focus trapped' selected by default, unselect it
4. click on Open Dialog button
5. close opened dialog
**Expected result:** dialog is closed, no another windows visible
**Actual result:** when dialog is closing - another dialog window is visible under and immediately disappears.

**Comment by aberikashvili** [comment]
@maxym-valor @Seamoo13 @droshev guys, I just tried to reproduce this issue on latest `main` and on https://fundamental-ngx.netlify.app/#/core/dialog , but I wasn't able to reproduce it, you can see screenshot, there's only 1 dialog in the DOM

![image](https://user-images.githubusercontent.com/3863691/125619265-48438a29-27f7-464d-9ee3-afbf2ee32b21.png)
