### ISSUE TITLE
bug: (click) event goes through on disabled fd-button-bar component

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#5457]
Realized while testing the wizard in dialog example that the `<fd-button-bar>` component will still allow for clicks when `disabled="true"`.  To demonstrate - go to the 2nd step on the wizard in dialog example - "next step" button appears disabled visually while the user has not entered the required fields, however clicking it still progresses to the third step.

**Comment by Smiranin** [comment]
@mikerodonnell89 I tested it and not reproduced.(see video) Can you retest it or provide more specific info?!
https://user-images.githubusercontent.com/14183958/120173275-8c0d2580-c20c-11eb-9de9-2644bf4aca59.mp4

**Comment by KeszleriJudit** [comment]
@Smiranin I have the same issue with the fd-button-bar. In the wizard it's just a simple button tag, but in the Dialog Wizard you can reproduce the same issue, because fd-button-bar is used there.
