### ISSUE TITLE
Bug: Stackblitz does not output element on the page

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5486]
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/menu
2. Click Show Code
3. Click Stackblitz
**Expected result:** element is visible at the right on the page
**Actual result:** no element visible, empty page
#### Is there anything else we should know?
v 0.30.1-rc.11
![image](https://user-images.githubusercontent.com/83698366/119631717-d52e3580-be18-11eb-8fed-1b48c8c368d1.png)

**Comment by DeepakSap14** [comment]
FYI: Stackblitz not working for any of the component in current release for fundamental-ngx.

**Comment by maxym-valor** [comment]
Stackblitz for menu component works correct
