### ISSUE TITLE
Alert stacking logic needs work

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#549]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Depending on when alerts are opened, closed, reopened etc. they can show up stacking over/under each other.

<img width="621" alt="screen shot 2019-02-19 at 9 00 19 pm" src="https://user-images.githubusercontent.com/2471874/53065596-8bac4e80-3489-11e9-9bfb-343f925c0316.png">

**Comment by MattL75** [comment]
I had an idea for a solution for this, haven't tested anything though.

When the first alert is created, we could append an AlertContainerComponent to the body. It would be full height, display flex, flex-direction column, absolute position, high z-index, etc. 

Then, we append the alert to that component. And continuously do so with subsequent alerts being added. Every time an alert closes, we check to see if it was the last one present. If so, we can destroy the alert container. This would only work for alerts opened using the service.

**Comment by droshev** [comment]
@mikerodonnell89 how can you `close` and `reopen` one alert? I thought once an alert has been dismissed it is gone.

**Comment by mikerodonnell89** [comment]
@droshev alerts can be re-opened the same way they were opened the first time.  For alerts handled via the template reference variable route, the alert simply has its display CSS value toggled.  For alerts created via component reference, a new instance of the alert is created and destroyed whenever the open/close functions are called
