### ISSUE TITLE
Add e2e tests (to be ran manually while we wait for CI)

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#55]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal
The components are almost entirely untested now... we should have some e2e tests that we can run manually before merging pull requests.  In the future we'll have CI that can handle the tests but for now, manual tests won't hurt

#### What versions of Angular and Fundamental NGX? (If this is a feature request, use current version)
Angular 6.0.0, fundamental-ngx 0.0.1-beta

**Comment by droshev** [comment]
@mikerodonnell89 is this still valid?
