### ISSUE TITLE
update docs to reflect the semantic version specifics

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#550]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
update the repo documentation how we apply semantic versioning in fundamental-ngx

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
fundamental-0.1.1

**Comment by MattL75** [comment]
Also maybe display the current version somewhere
