### ISSUE TITLE
Bug: Opened combobox hovered page header

### ISSUE THREAD

**Issue by Smiranin** [SAP/fundamental-ngx#5500]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
This issue related to demo [page](https://sap.github.io/fundamental-ngx/#/core/combobox)
When an user opens combobox  and scrolldown, the combobox is hovered a header of page.
![2021-05-26_18-15](https://user-images.githubusercontent.com/14183958/119686603-29eca300-be4f-11eb-93cd-e11f77ad01d2.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx: v0.30.0
"@angular/core": "~11.2.13",
#### If this is a bug, please provide steps for reproducing it.

1. Open demo [page](https://sap.github.io/fundamental-ngx/#/core/combobox) and go to combobox page
2. Open any combobox to see combobox contnet.
3. Scroll down and see how combobox will hover page header.

**Comment by dimamarksman** [comment]
I wouldn't consider it as a bug, `dropdown/overlay` always overlaps other items

**Comment by Smiranin** [comment]
Probably You are right!
