### ISSUE TITLE
Bug: (core) A lot of extra space between elements for Wizzard Component: mobile wizzard

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5504]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
A lot of extra space, which should be cut
#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/wizard#Wizard-Mobile

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/119796484-14748900-bee2-11eb-9e56-a2e0303c592c.png)

**Comment by sKudum** [comment]
Hi Maxym,

This examples gives view in different viewport devices responsiveness . Reducing its height will not full-fill the requirement.

**Comment by maxym-valor** [comment]
Requirement, not a bug. Sorry for you time!
