### ISSUE TITLE
Fixed Card Layout performance/behaviour issue

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5511]
**Describe the bug**
When the the browser changes its size, the cards are destroyed and built again, causing the data inside them to disappear (shows busy indicator, makes a call to the data) and appear again. 

**Expected behavior**
Cards content must be stable when the browser is resized and just adapt to the responsive design

**Comment by N1XUS** [comment]
We need to try to discard current approach, where we re-render child components in "virtual" columns, because this causes this re-initialization of the child components.

What we can try, is to use css grid system with flexboxes to create responsive layout

**Comment by DeepakSap14** [comment]
css grid is not supported in IE11. so we came to this approach.

**Comment by DeepakSap14** [comment]
@InnaAtanasova @N1XUS 
we have to discard current approach and use `css grid`.
but then it will not be supported in IE11. are we fine with that?

**Comment by N1XUS** [comment]
@DeepakSap14 I would say "yes" since ANgular 12 dropped IE11 support too.
