### ISSUE TITLE
bug: (platform) disabled menu button and split menu button opens menu on click

### ISSUE THREAD

**Issue by DeepakSap14** [SAP/fundamental-ngx#5513]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Even when menu button/split menu button is disabled, clicking on it opens the associated menu.

#### If this is a bug, please provide steps for reproducing it.
![image](https://user-images.githubusercontent.com/57661487/119857200-000bad00-bf31-11eb-87e6-23c0dddcbcd0.png)

**Comment by puru-hk** [comment]
Tested in this url https://deploy-preview-5514--fundamental-ngx.netlify.app/#/platform/split-menu-button . it is working as expected.
