### ISSUE TITLE
Notification component: RTL is not working properly

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5515]
Description: RTL is not working 

Expected: RTL should work properly 

Attached the screenshot.

<img width="1680" alt="Screenshot 2021-05-28 at 14 15 34" src="https://user-images.githubusercontent.com/32538291/119956916-355edc00-bfbf-11eb-8899-a5e258eee7f8.png">

**Comment by droshev** [comment]
This is documentation issue and not a bug in the component

**Comment by xandrio** [comment]
@droshev I'm not sure we have only documentation issue. I don't see implementation of RTL at component side,
otherwise I can see some gag at documentation side making RTL "works" only at documentation page.

**Comment by droshev** [comment]
@xandrio actually there are some issues there. We would need to do that in iterations:
- [ ] update the documentation so we can have proper RTL for Notification
- [ ] identify the bugs and document them
- [ ] fix the issue
