### ISSUE TITLE
Bug: (core) No information about API for Wizard component

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5545]
#### Briefly describe your proposal.
Empty page instead API for Wizard component
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/wizard
2. Click on API tab
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/120478015-13959880-c3b5-11eb-942c-ae4c73d05e25.png)

**Comment by sKudum** [comment]
Not reproducible in latest version of ngx hence assigning it for qa review.

<img width="1414" alt="2021-06-10_12-48-14" src="https://user-images.githubusercontent.com/53487468/121481948-43165780-c9ea-11eb-9d42-6d785a943614.png">

**Comment by nikvalor** [comment]
As for me the issue still actual. Could you check the steps to reproduce from the video and try again. Thanks!
https://www.loom.com/share/8ffa7becc0644c3aaf910766867d7ed3
