### ISSUE TITLE
Text color for fd-select cannot be changed if readonly

### ISSUE THREAD

**Issue by DavidEgresits** [SAP/fundamental-ngx#5563]
Dear Colleagues,

Please handle this incident as an internal SAP incident, although I'm working on an internal project, I found that this is the preferred way to open an incident for Fundamentals.

The problem is that we would like to change the text color of the fd-select, but only if it is readonly. Unfortunately, this does not seem to be achievable currently, as the info that the element (fd-select__text-content) is readonly does not reach the UI element which contains the text:
![image](https://user-images.githubusercontent.com/15217061/120664897-9a1ca980-c48b-11eb-804b-f3aea7ced461.png)

I used the following styles:

```
  .fd-select__text-content.is-readonly {
        color: rgb(211, 26, 26);         //Red color does take effect only without is-readonly
    }

    .fd-select__control.is-readonly {
        color: rgb(211, 26, 26);        // Red color does not take effect as the text is embedded into fd-select__text-content
        background-color: aquamarine;       //works
    }
```

Could you please check and fix the issue?

Screenshots
![image](https://user-images.githubusercontent.com/15217061/120664995-af91d380-c48b-11eb-8ab6-fe8f52c5cf9a.png)

Desktop :
OS: macOS
Browser: Chrome
Version: 90.0.4430.212

Thanks and Best regards,
David Egresits
Associate Architect, Business Networks
SAP Labs Hungary

**Comment by sKudum** [comment]
Hi David, ngx will provide the features as per Fiori standards and as this requirement is project specific we have to close it.

As a workaround option. Could you have a class for respective component to add text color to `fd-select__text-content` when its parent div has readonly class.
