### ISSUE TITLE
Defect Hunting for Sprint 64 - Lyon

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5573]
Please report the issues you found during the defect hunting with the following format:

```
- [ ] Short title containing the component name
- Description of the issue
- Ways to reproduce it
- Screenshot or gif
- Browser 
```

Before starting to work on the issue please write your name after the title in bold.
Once the PR is open, please link a link to the PR after your name
Mark this issue as done by checking the checkbox

Example:
<img width="836" alt="Screen Shot 2021-06-03 at 3 29 26 PM" src="https://user-images.githubusercontent.com/39598672/120701160-828bf380-c480-11eb-8aba-d84e08204da8.png">

**Comment by hanjunt** [comment]
- [ ] Card Counter in Card - Table Card, etc
- The card counter reads "of 10 3" in RTL mode.
- All browsers.
![Screen Shot 2021-06-17 at 1 51 46 PM](https://user-images.githubusercontent.com/46663585/122449474-dfed6d80-cf73-11eb-9914-895378715142.png)

**Comment by hanjunt** [comment]
- [ ] Core - Carousel - Carousel with hidden navigation buttons
- In RTL mode, UI stops working and content disappears.
- Enable RTL mode, swipe left or right. 
- All browsers
![Screen Shot 2021-06-17 at 2 22 13 PM](https://user-images.githubusercontent.com/46663585/122453269-2d6bd980-cf78-11eb-9100-3f26f868eb65.png)

**Comment by aberikashvili** [comment]
First Token not fully visible 
![image](https://user-images.githubusercontent.com/3863691/122468647-05f32c00-cfcd-11eb-9be4-89982df57210.png)

**Comment by InnaAtanasova** [comment]
Card component
- when list component is used inside the Card body the List Items do not get focus with Tab key. The focus goes from the Card header to the List body
<img width="887" alt="Screen Shot 2021-06-17 at 4 57 46 PM" src="https://user-images.githubusercontent.com/39598672/122471640-7e39fd00-cf8d-11eb-836b-cde86b5cf41c.png">

**Comment by InnaAtanasova** [comment]
Time Picker has double focus line

<img width="237" alt="Screen Shot 2021-06-17 at 2 37 03 PM" src="https://user-images.githubusercontent.com/39598672/122471749-a0337f80-cf8d-11eb-9ca2-1ab809dcb4c5.png">

**Comment by InnaAtanasova** [comment]
Carousel component:
In the example  `Carousel error message when no item is loaded` it's not used Message Page component as recommended by the specs but a div with icon and text with inline styling 
```
 <div style="width: 100%; display: flex; flex-direction: column;">
            <div style="align-self: center;">
                <i class="sap-icon--document"></i>
            </div>
            <div style="align-self: center;">Items could not be loaded</div>
</div>
```

**Comment by InnaAtanasova** [comment]
Combobox in Mobile mode is missing the button in the input:
Now:
<img width="638" alt="Screen Shot 2021-06-17 at 5 07 56 PM" src="https://user-images.githubusercontent.com/39598672/122472471-a1b17780-cf8e-11eb-950e-372831a28b2b.png">

Before:
<img width="594" alt="Screen Shot 2021-06-17 at 5 07 47 PM" src="https://user-images.githubusercontent.com/39598672/122472480-a5dd9500-cf8e-11eb-993b-9b6177f77603.png">

**Comment by InnaAtanasova** [comment]
Missing a few released versions:
<img width="181" alt="Screen Shot 2021-06-17 at 5 08 50 PM" src="https://user-images.githubusercontent.com/39598672/122472533-bbeb5580-cf8e-11eb-815c-5d5ded634c4d.png">

**Comment by InnaAtanasova** [comment]
File Uploader with truncation loses truncation when a file is selected:
Initially:
<img width="535" alt="Screen Shot 2021-06-17 at 5 11 48 PM" src="https://user-images.githubusercontent.com/39598672/122472994-4633b980-cf8f-11eb-8ef9-f4a8cffc62f9.png">

After you've clicked to upload a file:
<img width="636" alt="Screen Shot 2021-06-17 at 5 11 57 PM" src="https://user-images.githubusercontent.com/39598672/122473013-4d5ac780-cf8f-11eb-815a-918ea6020efb.png">

**Comment by InnaAtanasova** [comment]
List issue with focus:
<img width="1212" alt="Screen Shot 2021-06-17 at 5 16 03 PM" src="https://user-images.githubusercontent.com/39598672/122473350-b93d3000-cf8f-11eb-82d0-3eacf6e48787.png">

The parent gets the focus but not the children elements.

**Comment by InnaAtanasova** [comment]
List with Byline:
Avatar is not centered horizontally
<img width="1200" alt="Screen Shot 2021-06-17 at 5 18 24 PM" src="https://user-images.githubusercontent.com/39598672/122473596-133df580-cf90-11eb-83b0-4cea0f3af4b0.png">

**Comment by InnaAtanasova** [comment]
Interactive List with Byline does not have the pointer cursor. The selected items do not get the correct background color on hover:
<img width="1271" alt="Screen Shot 2021-06-17 at 5 19 34 PM" src="https://user-images.githubusercontent.com/39598672/122473804-54360a00-cf90-11eb-96f9-a2178e85b064.png">

**Comment by droshev** [comment]
Most of the issues are transferred in new issues
