### ISSUE TITLE
Accessibility:  Approval Flow-Platform Component

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5574]
Accessibility: Approval Flow Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Approval flow_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6654147/Approval.flow_Platform_ARIBA.Controls.docx)

**Comment by Sanjay-1312** [comment]
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<h2 style="mso-collapsed-heading:yes"><span lang="EN-US">Issue 1<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | High
-- | --
Checkpoint: | ACC-264



<p class="MsoNormal" style="margin-left:18.0pt"><span lang="EN-US" style="color:white;mso-color-alt:windowtext">Navigate to the names available
within watchers</span><span lang="EN-US"><o:p></o:p></span></p>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">On navigating to the names within
‘watchers’ header, the information ‘watcher’ is not read. <o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Also, the information regarding the element
type is not read. i.e. it does not read the information that the element is
clickable.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">The speech output is:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Sofia Hanson Graphic‑ <br>
Melissa Martin Graphic‑ <br>
Julie Peters Graphic‑ <br>
Fred Gibson Graphic‑ <br>
Expected Behavior:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="font-family:&quot;Times New Roman&quot;,serif">Ideally,
the information ‘watcher’ should be read on navigating to the name. Also, The
element type for all the element should be read.<o:p></o:p></span></p>

<h3><span lang="EN-US">Screenshot:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">Case 1<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Case 2<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<span lang="EN-US" style="font-size:11.0pt;line-height:107%;font-family:&quot;Calibri&quot;,sans-serif;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:Calibri;mso-fareast-theme-font:
minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:&quot;Times New Roman&quot;;
mso-bidi-theme-font:minor-bidi;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA"><br clear="all" style="mso-special-character:line-break;
page-break-before:always">
</span>

<p class="MsoNormal" style="line-height:107%"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>



![image](https://user-images.githubusercontent.com/78714518/121667470-f0ab6880-cac7-11eb-85f6-ccb612ebea97.png)

![image](https://user-images.githubusercontent.com/78714518/121667493-f6a14980-cac7-11eb-9480-2e67c4948292.png)

**Comment by kavya-b** [comment]
Please note there are a total of 20 issues in the attached document. Increasing estimate to 3d at least.
cc: @manjunathanagaraj @skocharian

**Comment by kavya-b** [comment]
Unassigning myself as Platon will be taking up this issue.

**Comment by Karthickc1994** [comment]
Hello Colleague,

The preview URL is not working please provide me the URL for RETEST.

Environment Used: 
[https://deploy-preview-8164--fundamental-ngx.netlify.app/assets/typedoc/platform/classes/approvalflowcomponent]

Regards,
Karthikeyan.c
