### ISSUE TITLE
Avatar Group-Core

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5575]
Accessibility: Avatar Group Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Avatar Group_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6595691/Avatar.Group_Core_ARIBA.Controls.docx)

**Comment by olshansky** [comment]
- [ ] **Issue 1:**

**Observed Behavior:**
- On navigating to the avatars available, additional tab stops are available. i.e. on navigating to the avatar, 2 additiona l tab stops are available after each name.

**Expected Behavior:**
- Ideally, no additional tab stops should be available on navigation and the focus should be clearly visible for the focused UI element.

____
- [ ] **Issue 2:**

**Observed Behavior:**
- On navigating to the avatars available, the name of the person is read but the element type as ‘avatar’ is not read. Therefore, information regarding the element type is not read.
The speech output is:

> Whitney Goldwell 
> David Jason 
> Jason Swan 
> Jason Jason 
> John Bow 
> Simon Parker

**Expected Behavior:**
- Ideally, the element type for all the UI element should be read on navigating using tab key. i.e. on navigating to the avatars, the element type ‘avatar’ should also be read along with the name.

____
- [ ] **Issue 3:**

**Observed Behavior:**
- A lot of additional tab stop with speech is available on navigating using tab key and the information read is not clear.
The speech output is:

> Whitney Copper Graphic- 
> Unlabeled graphic 
> Unlabeled graphic 
> Jonathan Doe Graphic- 
> Unlabeled graphic 
> Sarah Copper Graphic- 
> Unlabeled graphic 
> Unlabeled graphic 
> Whitney Jason Graphic- 
> Unlabeled graphic 
> Unlabeled graphic 
> Whitney Copper Graphic-

**Expected Behavior:**
- Ideally, no additional tab stops should be available on navigation and the information read should be clear and precise.

**Comment by Sanjay-1312** [comment]
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel="Edit-Time-Data" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel="themeData" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<h1><span class="spellingerror"><b><span lang="EN-US" style="font-size:11.0pt;
line-height:106%;mso-fareast-font-family:&quot;Times New Roman&quot;;color:black">Avatar
Group– Core<o:p></o:p></span></b></span></h1>

<h2><span lang="EN-US"><o:p>&nbsp;</o:p></span></h2>

<h2><span lang="EN-US">1.1 Message Details<o:p></o:p></span></h2>


Raise Ticket | &nbsp;
-- | --
Category | &nbsp;
Preprocessed By | &nbsp;
Description | &nbsp;



<h2><span lang="EN-US"><o:p>&nbsp;</o:p></span></h2>

<h2><span lang="EN-US">1.2 Application &amp; Test Environment Details<o:p></o:p></span></h2>


Application   Name: | ARIBA   Controls- Fundamental Library for Angular
-- | --
URL: | https://fundamental-ngx.netlify.app/#/core/home
Web   browser: | Google   Chrome 91.0.4472.77
Operating   System: | Microsoft   Windows 10 x64
Screen   Reader: | JAWS   2021.2012.57.400



<p class="MsoNormal"><span lang="EN-US" style="font-size:12.0pt;line-height:106%;
font-family:&quot;Times New Roman&quot;,serif;mso-no-proof:yes"><o:p>&nbsp;</o:p></span></p>

<b><span lang="EN-US" style="font-size:12.0pt;line-height:107%;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#365F91;mso-ansi-language:EN-US;
mso-fareast-language:EN-US;mso-bidi-language:AR-SA"><br clear="all" style="mso-special-character:line-break;page-break-before:always">
</span></b>

<p class="MsoNormal" style="line-height:107%"><b><span lang="EN-US" style="font-size:12.0pt;line-height:107%;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:&quot;Times New Roman&quot;;color:#365F91"><o:p>&nbsp;</o:p></span></b></p>

<h2><span lang="EN-US">Issue 1<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | High
-- | --
Checkpoint: | ACC-270



<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Press tab to navigate to the avatars
available.<o:p></o:p></span></p>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">On navigating to the avatars available,
additional tab stops are available. i.e. on navigating to the avatar, 2
additional tab stops are available after each name.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Expected Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US" style="font-family:&quot;Times New Roman&quot;,serif">Ideally,
no additional tab stops should be available on navigation and the focus should
be clearly visible for the focused UI element.<o:p></o:p></span></p>

<h3><span lang="EN-US">Screenshot:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="338" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg" v:shapes="Picture_x0020_19"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="font-size:16.0pt;line-height:106%;
color:#00B050">Fixed<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<span lang="EN-US" style="font-size:11.0pt;line-height:107%;font-family:&quot;Calibri&quot;,sans-serif;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:Calibri;mso-fareast-theme-font:
minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:&quot;Times New Roman&quot;;
mso-bidi-theme-font:minor-bidi;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA"><br clear="all" style="mso-special-character:line-break;
page-break-before:always">
</span>

<p class="MsoNormal" style="line-height:107%"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h2><span lang="EN-US">Issue 2<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | High
-- | --
Checkpoint: | ACC-264



<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Press tab to navigate to the avatars
available.<o:p></o:p></span></p>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">On navigating to the avatars available, the
name of the person is read but the element type as ‘avatar’ is not read.
Therefore, information regarding the element type is not read.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">The speech output is:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Whitney Goldwell <br>
David Jason <br>
Jason Swan <br>
Jason Jason <br>
John Bow <br>
Simon Parker<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Expected Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">Ideally, the element type for all the UI
element should be read on navigating using tab key. i.e. on navigating to the
avatars, the element type ‘avatar’ should also be read along with the name.<o:p></o:p></span></p>

<h3><span lang="EN-US">Screenshot:<o:p></o:p></span></h3>

<p class="MsoNormal"><a name="_Hlk73650187"><span lang="EN-US" style="mso-no-proof:
yes"><img border="0" width="601" height="338" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image003.jpg" v:shapes="Picture_x0020_2"></span></a><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="font-size:16.0pt;line-height:106%;
color:#00B050">Fixed<o:p></o:p></span></p>

<span lang="EN-US" style="font-size:11.0pt;line-height:107%;font-family:&quot;Calibri&quot;,sans-serif;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:Calibri;mso-fareast-theme-font:
minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:&quot;Times New Roman&quot;;
mso-bidi-theme-font:minor-bidi;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA"><br clear="all" style="mso-special-character:line-break;
page-break-before:always">
</span>

<p class="MsoNormal" style="line-height:107%"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h2><span lang="EN-US">Issue 3<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | High
-- | --
Checkpoint: | ACC-264



<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Press tab to navigate to the avatars
available.<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-left:18.0pt"><span lang="EN-US">Activate +11
more button and navigate using tab key<o:p></o:p></span></p>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">A lot of additional tab stop with speech is
available on navigating using tab key and the information read is not clear.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">The speech output is:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Whitney Copper Graphic‑ <br>
Unlabeled graphic <br>
Unlabeled graphic <br>
Jonathan Doe Graphic‑ <br>
Unlabeled graphic <br>
Sarah Copper Graphic‑ <br>
Unlabeled graphic <br>
Unlabeled graphic <br>
Whitney Jason Graphic‑ <br>
Unlabeled graphic <br>
Unlabeled graphic <br>
Whitney Copper Graphic‑<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Expected Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">Ideally, no additional tab stops should be
available on navigation and the information read should be clear and precise.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Screenshot:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">Case 1<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="338" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image005.jpg" v:shapes="Picture_x0020_20"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Case 2<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="338" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image007.jpg" v:shapes="Picture_x0020_21"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="font-size:16.0pt;line-height:106%;
color:#00B050">Buttons are removed from scope<o:p></o:p></span></p>

<span lang="EN-US" style="font-size:11.0pt;line-height:107%;font-family:&quot;Calibri&quot;,sans-serif;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:Calibri;mso-fareast-theme-font:
minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:&quot;Times New Roman&quot;;
mso-bidi-theme-font:minor-bidi;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA"><br clear="all" style="mso-special-character:line-break;
page-break-before:always">
</span>

<p class="MsoNormal" style="line-height:107%"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h2><span lang="EN-US">Issue 4<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | Medium
-- | --
Checkpoint: | ACC-266



<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>

<h1 style="margin-top:0cm;vertical-align:top"><span lang="EN-US" style="font-size:12.0pt;line-height:106%;font-family:&quot;inherit&quot;,serif">Ensure
markup documents contain well-formed elements<o:p></o:p></span></h1>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">This DIV has an id attribute of
'fd-avatar-group-0', which is not unique in the same DOM<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Code Snippet:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">&lt;div id="fd-avatar-group-0"
class="fd-avatar-group fd-avatar-group--individual-type fd-avatar-group--s
undefined"&gt;&lt;div class="fd-popover-custom ng-star-inserted"
id="fd-popover-1" placement="bottom"&gt;&lt;div
class="fd-popover__control ng-star-inserted"
cdkoverlayorigin=""&gt;&lt;div&gt;&lt;div style="display:
inline-block;" class="fd-avatar-group__item" tabindex="0"
fd-avatar-group-item=""&gt;&lt;div style="background-image:
url("https://i.pravatar.cc/400?u=43cntwe");"
id="fd-avatar-0" class="fd-avatar fd-avatar--s fd-avatar--circle
fd-avatar--border ng-star-inserted" title="Gordon Goldwell"
role="img"&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
class="fd-popover-custom ng-star-inserted"
id="fd-popover-2" placement="bottom"&gt;&lt;div
class="fd-popover__control ng-star-inserted"
cdkoverlayorigin=""&gt;&lt;div&gt;&lt;div style="display:
inline-block;" class="fd-avatar-group__item"
tabindex="0" fd-avatar-group-item=""&gt;&lt;div
aria-label="Whitney Copper" id="fd-avatar-2"
class="fd-avatar fd-avatar--s fd-avatar--circle fd-avatar--border
ng-star-inserted" title="Whitney Copper"
role="img"&gt;WC&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
class="fd-popover-custom ng-star-inserted"
id="fd-popover-3" placement="bottom"&gt;&lt;div
class="fd-popover__control ng-star-inserted"
cdkoverlayorigin=""&gt;&lt;div&gt;&lt;div style="display:
inline-block;" class="fd-avatar-group__item"
tabindex="0" fd-avatar-group-item=""&gt;&lt;div
id="fd-avatar-4" class="fd-avatar fd-avatar--s fd-avatar--circle
fd-avatar--border ng-star-inserted" title="Jason Bow"
role="img"&gt;&lt;i class="fd-avatar__icon sap-icon--add-contact
ng-star-inserted"
role="presentation"&gt;&lt;/i&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div
class="fd-popover-custom ng-star-inserted"
id="fd-popover-4" placement="bottom"&gt;&lt;div
class="fd-popover__control ng-star-inserted"
cdkoverlayorigin=""&gt;&lt;div&gt;&lt;div style="display:
inline-block;" class="fd-avatar-group__item"
tabindex="0" fd-avatar-group-item=""&gt;&lt;div
id="fd-avatar-6" class="fd-avatar fd-avatar--s fd-avatar--circle
fd-avatar--border ng-star-inserted" title="Christian Parker"
role="img"&gt;&lt;i class="fd-avatar__icon
sap-icon--accidental-leave ng-star-inserted"
role="presentation"&gt;&lt;/i&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Expected Behavior:<o:p></o:p></span></h3>

<p style="margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:
0cm;background:white;vertical-align:baseline"><span style="font-size:9.0pt;
font-family:Roboto;color:black">Ensure that all page elements have complete
start and end tags, elements are nested according to specification, elements do
not contain duplicate attributes, and any IDs are unique (except where allowed
by the document specification). Mismatched opening and closing quotes,
malformed attributes, attributes not space separated, mismatched opening and
closing tags, and in some cases, unquoted attributes are also violations.<o:p></o:p></span></p>

<p style="margin-top:0cm;margin-right:0cm;margin-bottom:12.0pt;margin-left:
0cm;background:white;vertical-align:baseline;font-variant-ligatures: normal;
font-variant-caps: normal;font-variant-numeric: inherit;font-variant-east-asian: inherit;
font-stretch: inherit;box-sizing: border-box;orphans: 2;text-align:start;
widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial;word-spacing:
0px"><span style="font-size:9.0pt;font-family:Roboto;color:black">When
documents do not contain a doctype definition the user agent may not be able to
determine what grammars the document must conform to. A missing doctype is not
a guaranteed failure in cases where it prevents the browser from correctly
rendering the document structure it may be a violation. When a doctype is
necessary to parse the document structure correctly it must be provided.<o:p></o:p></span></p>

<p style="margin:0cm;background:white;vertical-align:baseline;font-variant-ligatures: normal;
font-variant-caps: normal;font-variant-numeric: inherit;font-variant-east-asian: inherit;
font-stretch: inherit;box-sizing: border-box;orphans: 2;text-align:start;
widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial;word-spacing:
0px"><span style="font-size:9.0pt;font-family:Roboto;color:black">The best way
to know that a document meets these requirements is to run the document through
the W3C's&nbsp;<a href="https://validator.w3.org/nu/" style="cursor:pointer;
box-sizing: border-box"><span style="mso-fareast-font-family:&quot;Times New Roman&quot;;
mso-fareast-theme-font:major-fareast;color:#2E65EC;border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0cm;padding:0cm">Nu HTML validator</span></a>.
And then review the errors/warnings.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Screenshot:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="303" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image009.jpg" v:shapes="Picture_x0020_1"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Screenshot 2:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="303" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image011.jpg" v:shapes="Picture_x0020_3"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h2><span lang="EN-US">Issue 5<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | Medium
-- | --
Checkpoint: | ACC-261



<h1 style="margin-top:0cm;vertical-align:top"><span lang="EN-US" style="font-size:12.0pt;line-height:106%;font-family:&quot;inherit&quot;,serif"><o:p>&nbsp;</o:p></span></h1>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">On adapting the theme to high contrast
black theme, the ‘Phone’, ‘Mobile’ and Email are doesn’t meet the color
contrast ratio of 4.5:1.<o:p></o:p></span></p>

<h3><span lang="EN-US">Expected Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">Ideally, the screen should get adapted and
the should have minimum color contrast ratio of 4.5:1.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Screenshot:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="325" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image013.jpg" v:shapes="Picture_x0020_4"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h2><span lang="EN-US">Issue 6<o:p></o:p></span></h2>

<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>


Priority: | Medium
-- | --
Checkpoint | ACC-264



<h3><span lang="EN-US"><o:p>&nbsp;</o:p></span></h3>

<h3><span lang="EN-US">Observed Behavior:<o:p></o:p></span></h3>

<h3><span lang="EN-US">The dialog name and details are not read.<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<h3><span lang="EN-US">Expected Behavior:<o:p></o:p></span></h3>

<p class="MsoNormal"><span lang="EN-US">Ideally, the dialog name followed by the
person name and group header contact details and focused first UI element in
the dialog should be read at one go.<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US">Screenshot:<o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US" style="mso-no-proof:yes"><img border="0" width="601" height="302" src="file:///C:/Users/C5310468/AppData/Local/Temp/msohtmlclip1/01/clip_image015.jpg" v:shapes="Picture_x0020_7"></span><span lang="EN-US"><o:p></o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style="line-height:107%"><span lang="EN-US"><o:p>&nbsp;</o:p></span></p>

**Comment by olshansky** [comment]
Issue 5: 
Cannot reproduce 
![image](https://user-images.githubusercontent.com/14160094/121895340-c60c1a80-cd28-11eb-80f6-40f5b2daacde.png)

Issues 4 & 6 could be re-tested

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 4:
i can able to reproduce,


Issue 5
Fixed

Issue 6:
OB; The dialog details is not read.
EB: The dialog name followed by the details and group information 'Contact' should be read when phone number is accessed at one go.
![image](https://user-images.githubusercontent.com/78714518/122087210-187d3200-ce22-11eb-8913-2fcbda42da59.png)

**Comment by olshansky** [comment]
@Sanjay-1312 hello

**Issue 4:** unfortunately, I still can't reproduce. Probably it's happening because of cache _(local or netlify)_ and I can't control it. 

**Issue 6:** could be re-tested

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

The issue is fixed for issue 4 and 6.
URL: https://deploy-preview-5628--fundamental-ngx.netlify.app/#/core/avatar-group
JAWS 2021

Thanks and Regards
Sanjay
