### ISSUE TITLE
Dynamic Page-Core

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5576]
Accessibility: Dynamic Page-Core  Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Dynamic Page_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6662780/Dynamic.Page_Core_ARIBA.Controls.docx)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken results are below:

Issue1: Fixed
Issue2: Fixed
Issue3:
Observed Behavior: 
On navigating to the tabs, an additional information ‘tab’ is read at first on entering the tabstrip section. Also, the tutor message provided to change the tab is not precise. i.e. it reads to change the selection use ctrl+page down but the tabs cannot be switched using the provided shortcut key. Therefore, the information read is not precise.
The speech output is:
Tab  
Tab 1 Tab selected  
1 of 3
To switch pages, press Control+PageDown.
Tab 2 Tab 
2 of 3
To switch pages, press Control+PageDown.

Issue4: Fixed
Issue5: Fixed
Issue6: Fixed
Issue7: Fixed
Issue8: Fixed
Issue9: Fixed
Issue10: Fixed

Retest environment:
URL:https://deploy-preview-7345--fundamental-ngx.netlify.app/#/core/dynamic-page
Screen reader: Jaws 2021.2111.13 ILM
Browser: Version 99.0.4844.84 (Official Build) (64-bit)

Regards,
Karthikeyan.c

![image](https://user-images.githubusercontent.com/37998745/160749392-4812ced4-5a8c-4a69-85c4-d351606ba2e2.png)

**Comment by genereg1** [comment]
@Veerakarthick 
Fixed pronouncing additional information on entering the tab section
Regarding changing selection and wrong announce key combination is a known JAWS bug in Chrome.
https://github.com/FreedomScientific/VFO-standards-support/issues/337

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken results are below:

Issue1: Fixed
Issue2: Fixed
Issue3:
Observed Behavior:
On navigating to the tabs, an additional information ‘tab’ is read at first on entering the tabstrip section. Also, the tutor message provided to change the tab is not precise. i.e. it reads to change the selection use ctrl+page down but the tabs cannot be switched using the provided shortcut key. Therefore, the information read is not precise.
The speech output is:
�Tab� ��
Tab 1 �Tab� �selected� ��
1 of 3
To switch pages, press Control+PageDown.
Tab 2 �Tab�
2 of 3
To switch pages, press Control+PageDown.

 screen shot:
![image](https://user-images.githubusercontent.com/105037808/173812981-a4f219ff-22e8-4cf1-ad57-a0e7bd01d7d0.png)

Issue4: Fixed
Issue5: Fixed
Issue6: Fixed
Issue7: Fixed
Issue8: Fixed
Issue9: Fixed
Issue10: Fixed

Retest environment:
URL:https://fundamental-ngx-gh--pr7345-fix-dynamic-page-a11-45ql36g8.web.app/fundamental-ngx#/core/dynamic-page
Browser: chrome Version 102.0.5005.115 (Official Build) (64-bit)
screen reader: Jaws2022.2204.20ILM

Regards,
Karthikeyan.c

**Comment by Karthickc1994** [comment]
Hello colleague,

As per the last reply the reported issue is belongs to combination is a known JAWS bug in Chrome.
 Enter into a tablist JAWS narrates: To switch pages, press Control+PageDown  FreedomScientific/VFO-standards-support#337.

so the reported issue  is a technology issue.

Thanks and Regards,
Karthikeyan.c
