### ISSUE TITLE
Multi Input field-Core

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5578]
Accessibility: Multi Input field-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:

[Multi Input field_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6662782/Multi.Input.field_Core_ARIBA.Controls.docx)

Application & Test Environment Details
Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/home
Web browser:	Google Chrome 91.0.4472.77
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2012.57.400

### **Note**
Most of the issues were fixed as part of PR #5950 .
please visit the PR, for taking the changes for fixed issues.

### Issue 1

Priority:	High
Checkpoint:	ACC-264

Within simple multi input header, navigate to the multi input field.
Observed Behavior:
On navigating to the multi input fields throughout, the entire tokens available is read at once. i.e. all the tokens selected is read at once. Therefore, a lot of additional information is read at once.
The speech output is:
Apple Banana cherry 
Multi Input Edit  
Expected Behavior:
Ideally, on navigating to the multi input fields, the information regarding the tokens available should be read but the entire tokens should not be read. For e.g. if there are 3 tokens available in the field, on navigation the information read should be ‘multi input field has tokens’. With this the user will get the information that there are tokens available and as per the requirement the user can navigate to the tokens using arrow keys.
Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122230712-85063880-ced7-11eb-8a59-6bf974f6dce4.png)

Case 2- compact

![image](https://user-images.githubusercontent.com/52071505/122230850-9fd8ad00-ced7-11eb-83f4-afca7a5f097d.png)

### Issue 2

Priority:	High
Checkpoint:	ACC-264

Within simple multi input header, navigate to the multi input field and navigate to the tokens available.
Observed Behavior:
On navigating within the tokens available in the multi input field, the item count for the number of tokens available is not read. i.e. it does not read how many tokens in total are available and also the item count of the focused token.
The speech output is:
Apple Banana cherry 
Multi Input Edit  

Expected Behavior:

Ideally, on navigating within the tokens available in the multi input field, the item count information should be read. For e.g. if there are 2 tokens available on navigating to the token the information read should be, ‘apple 1 of 2 button, Banana 2 of 2 button’. With this the user will know the total number of tokens available and also the item count of the focused token.

Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122230951-b4b54080-ced7-11eb-8f95-6a017534b188.png)

Case 2- compact
![image](https://user-images.githubusercontent.com/52071505/122231082-d282a580-ced7-11eb-9224-cd2a9612c3a5.png)

### Issue 3

Priority:	High
Checkpoint:	ACC-264

Within simple multi input header, navigate to the multi input field and navigate to the tokens available.
Observed Behavior:
On navigating to the tokens available within the multi input field, the information that the token can be deleted is not read. i.e. the information ‘deletable’ for the tokens is not read.
The speech output is:
Apple Banana cherry 
Multi Input Edit  

Expected Behavior:
The information that the tokens can be deleted should be read to the screen reader user. i.e. on navigating to the tokens using arrow keys the information ‘deletable’ should be read.

Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122231289-f8a84580-ced7-11eb-95d4-5645a1db406b.png)

Case 2 - Compact:
![image](https://user-images.githubusercontent.com/52071505/122231378-078ef800-ced8-11eb-9e5c-b6dc7108fe04.png)

### Issue 4

Priority:	High
Checkpoint:	ACC-264

Within simple multi input header, navigate to the multi input field and navigate to the tokens available.
Observed Behavior:
On navigating to the multi input field, the information that the tokens can only be selected from the existing list and a new token cannot be added is not read. i.e. it does not read the information that user cannot input any random token but can select only from the existing tokens.
The speech output is:
Apple Banana cherry 
Multi Input Edit  
cherry
Type in text.

Expected Behavior:
Ideally, the information that only the existing tokens can be selected or searched should be read. i.e. the information that the user cannot randomly input any new token should be conveyed to the user.
Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122231503-1c6b8b80-ced8-11eb-9708-037f6d3fd2c3.png)

Case 2 - Compact:
![image](https://user-images.githubusercontent.com/52071505/122231580-2b523e00-ced8-11eb-947c-3da0a00cd4c5.png)

### Issue 5

Priority:	High
Checkpoint:	ACC-264

Navigate to any multi input field and type any letters for e.g. type ‘ap’.
Observed Behavior:
On typing any character within the multi input field, a list of search result is displayed but the information regarding the list is not read by the screen reader. i.e. it does not read any information when the related list is displayed on the screen.

Expected Behavior:
Ideally, the information regarding the result list displayed after typing any letters should be read by the screen reader. i.e. on typing any letters when a related result list is displayed the information regarding the number of items available within the list should be read for all the multi input fields.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122231749-4e7ced80-ced8-11eb-845a-7263981992c3.png)

### Issue 6

Priority:	High
Checkpoint:	ACC-264

Within Mobile mode multi input navigate to the search field and type any letter, a pop up opens
Observed Behavior:
When the dialog appears on the screen, only the screen title ‘fundamental library for angular’ is read and information regarding the dialog header ‘select fruits’ and information regarding the dialog is not read.
The speech output is:
Fundamental library for angular
Expected Behavior:
Ideally, the dialog header and information regarding the dialog should be read when the dialog appears on the screen along with the information regarding the focused element.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122231852-66ed0800-ced8-11eb-9386-69d6780b284f.png)

### Issue 7

Priority:	High
Checkpoint:	ACC-264

Within Mobile mode multi input navigate to the search field and type any letter, a pop up opens. Press tab once.
Observed Behavior:
When the dialog appears on the screen and on pressing tab a lot of additional information is read before reading information regarding the focused element. i.e. the entire information available within the dialog is read at once.
The speech output is:
Fundamental Library for Angular
Input field with multiple selection enabled. Should be used when a user can select between a limited number of pre-defined options with a filter-enabled context. import { MultiInputModule } from ’@fundamental-ngx/core’; Examples API Simple Multi Input The standard version of the component that most people will use regularly. Width of the input can be controlled simply through the top-level component element sizing. Overflowing tokens can be reviewed by swiping the tokens left and right. Simulate RTL Switch background Multi Input Selected: [Apple,Banana,Pineapple,Tomato,Kiwi,Strawberry,Blueberry] Disabled Multi Input Selected: [Pineapple] Hidden Addon Button Selected: [Kiwi] Show Code Compact Multi Input The compact Multi Input is for large screens. The user can review tokens by pressing the right or left arrows on the keyboard. 
b B anana B lueberry
Select fruits dialog 
b B anana B lueberry
Select fruits dialog Modal  dialog  
b B anana B lueberry
ContentInfoRegion  
Cancel Button  
To activate press spacebar.
Expected Behavior:
Ideally, no additional information should be read when a dialog appears on the screen and the information read should be clear and precise. i.e. when a dialog appears on the screen, information regarding the dialog header, element type and name of the focused element should be read.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122231977-8421d680-ced8-11eb-8392-4e77199fc67b.png)

### Issue 8

Priority:	High
Checkpoint:	ACC-264

Within Mobile mode multi input navigate to the search field and type any letter, a pop up opens.
Activate any checkbox from the list of fruits available.
Observed Behavior:
On selecting any item from the list, the information regarding all the other items available in the list is read at once. Therefore, a lot of additional information is read.
The speech output is:
check box  checked  
To clear checkmark press Spacebar.
Banana Pineapple Kiwi 
Apple  Banana  Pineapple Tomato  Kiwi Strawberry Blueberry Orange
Search here... Edit  

Type in text.

Expected Behavior:
Ideally, on checking any checkbox or selecting any item from the list, information regarding the state of the checkbox and the name of the item should only be read and no additional information should be read.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122232103-9dc31e00-ced8-11eb-9e82-19d045b1594d.png)

### Issue 9

Priority:	High
Checkpoint:	

Within custom filter multi input field, type any character in search field and remove the typed letters
Observed Behavior:
On typing any letters in the search input field, the related list of items is not displayed but the items are displayed only when the user removes the typed data. Therefore, the related search result is displayed only after the user clears the typed data.

Expected Behavior:
Ideally, the list of search results should be displayed when the user types any character and not when the user clears the data within the field.
Screenshot:
Case 1- when typed

![image](https://user-images.githubusercontent.com/52071505/122232292-be8b7380-ced8-11eb-96e4-3ae5697e209b.png)

Case 2 - when removed
![image](https://user-images.githubusercontent.com/52071505/122232342-ca773580-ced8-11eb-94fa-9f4b15b51322.png)

Case 3 - custom item template:
![image](https://user-images.githubusercontent.com/52071505/122232411-d6fb8e00-ced8-11eb-8f0e-4c325b8d42dd.png)

### Issue 10

Priority:	High
Checkpoint:	ACC-264

Within Add new token multi input field, press tab to navigate to the field available.
Observed Behavior:
On navigating to the multi input field, the corresponding label ‘search’ is not read. Therefore, the label is not associated to the respective field.
The speech output is:
Edit Type in text

Expected Behavior:
Ideally, on navigating to the multi input field, the corresponding label should be read.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122232560-f1ce0280-ced8-11eb-8fd9-8f3d990371e4.png)

### Issue 11

Priority:	Medium
Checkpoint:	ACC-282.1

 On resizing the screen to 320 pixels.
Press ‘F12’ button.

Observed Behavior:
When resizing the screen to ‘Responsive Design’ (320) pixels, the texts are outside the card layout.
Expected Behavior:
Ideally, the text should be within the card layout and the there should be no loss of content.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122232654-07432c80-ced9-11eb-9d4f-f020208fd11d.png)

### Issue 12

Priority:	Medium
Checkpoint:	ACC-260.4

 On resizing the screen to 200% zoom.
Press ‘F12’ button.

Observed Behavior:
When resizing the screen to responsive design the horizontal scroll bar is available.
Expected Behavior:
Ideally, the horizontal scroll bar must be avoided to the user.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122232769-1cb85680-ced9-11eb-883b-270091cae446.png)

### Issue 13

Priority:	Medium
Checkpoint:	ACC-264.1

 On selecting the checkbox.

Observed Behavior:
On selecting the list items, of the Compact Multi input section additional information is conveyed. 
Expected Behavior:
Ideally, such additional information should not be conveyed to the user.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122232856-3194ea00-ced9-11eb-9552-9534d69172cf.png)

### Issue 14

Priority:	Medium
Checkpoint:	ACC-255.1

Observed Behavior:
The text alternative or Tooltip for the ‘Close’ and ‘Multi Selectable’ button is not provided.
Expected Behavior:
Ideally, a text alternative for elements should be given which fulfills the purpose of the content.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122232962-4a9d9b00-ced9-11eb-89af-9a678cafce6c.png)

### Issue 15

Priority:	Medium
Checkpoint:	ACC-264.1

Observed Behavior:
On accessing the ‘Multi select’ button, the UI name read as Button.
Expected Behavior:
Ideally, all important information visually conveyed to the user must be read.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122233075-630db580-ced9-11eb-8c9b-8b1093df1b52.png)

### Issue 16

Priority:	Medium
Checkpoint:	ACC-264.1

Observed Behavior:
On accessing the ‘Mobile Mode Multi input’ Multi Value input field, associated label ‘Mobile Mode Multi input’ is not read.
Expected Behavior:
Ideally, the corresponding label must be read out, when each and every UI is accessed.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122233181-7a4ca300-ced9-11eb-928f-ecd2f65f8d57.png)

**Note: This issue persists throughout the control.**

### Issue 17

Priority:	High
Checkpoint:	ACC-270.1

Observed Behavior:
There is no keyboard support provided for the close button.
Expected Behavior:
Ideally, all the associated functionality of an UI must be invokable using keyboard and mouse. Also, application shall be designed so end users can work with the keyboard alone, without requiring to use a mouse or a touch device.

Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122233372-a1a37000-ced9-11eb-80b7-b5f3a8ff85bd.png)

**Comment by manjunathanagaraj** [comment]
Updated contents of the attachment into description

**Comment by DeepakSap14** [comment]
for reading of input search result, a directive is needed to be created and used here for the solution.
will need to revisit and use that directive once available.
for now, changes are pushed to branch https://github.com/SAP/fundamental-ngx/tree/fix/5578-multi-input-a11y.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

Issue 4:
![image](https://user-images.githubusercontent.com/78714518/143003393-2c3b0813-ae52-4632-8a07-eff31acdec47.png)
OB: The selected information within the list is not read.
EB: The selected list item should be read and list should be closed when user checks the checkbox.
Reference  link:
https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp

Issue 6:
![image](https://user-images.githubusercontent.com/78714518/143003498-af82d08d-d9ab-4047-966b-4fd9c5e1772f.png)
OB: The dialog information is read multiple times to the user.
EB: The dialog information and details should be conveyed once to the user.

Issue 8:
![image](https://user-images.githubusercontent.com/78714518/143003563-9d4232e0-aa7c-40dd-88cf-ba868fbdb382.png)
Ob: The selected list item information is not read.
EB: The list item when selected it should be read.
Reference Link:
https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp

Retest Details:
URL:https://deploy-preview-5950--fundamental-ngx.netlify.app/#/core/multi-input
JAWS 2021
