### ISSUE TITLE
Page Footer -Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5580]
Accessibility:  Page Footer -Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Page footer_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6662791/Page.footer_Platform_ARIBA.Controls.docx)

Application & Test Environment Details
Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/platform/home
Web browser:	Google Chrome 91.0.4472.77
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2012.57.400

### Issue 1

Priority:	High
Checkpoint:	ACC-264

Within page footer with icon and image navigate to the links available
Observed Behavior:
On navigating to the links, ‘support, security discloser, privacy statement’, the name of the links is not read. i.e. the information read does not give a clear information regarding the purpose of the links.
The speech output is:
On click you will get to target page Link  
On click you will get to target page Link  
On click you will get to target page Link 

Expected Behavior:
Ideally, the name of the links should be read on navigation and the information read should define the purpose of the UI element.

Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122225384-a6b0f100-ced2-11eb-8288-6f641554b21f.png)

### Issue 2

Priority:	Medium
Checkpoint:	ACC-260.4

Observed Behavior:
On adapting the screen to 200% Zoom, horizontal scroll bar is available.
Expected Behavior:
Horizontal scroll bar must be avoided to the user.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122225477-bcbeb180-ced2-11eb-9233-30548463355a.png)

Case 2:

Observed Behavior:
When resizing the screen to ‘Responsive Design’ (320) pixels, the horizontal scroll bar is available.
Expected Behavior:
Ideally, the horizontal scroll bar must be removed to the user.
Screenshot:

![image](https://user-images.githubusercontent.com/52071505/122225673-e7106f00-ced2-11eb-80fe-5b1714855eea.png)

**Comment by manjunathanagaraj** [comment]
Updated word doc attachment details into description

**Comment by Sanjay-1312** [comment]
Issue: 1
Fixed.

Issue 2:
I can still able to reproduce the issue.
Ob: Horizontal scroll bar  is available
![image](https://user-images.githubusercontent.com/78714518/123455659-9a7a1180-d5ff-11eb-878c-d3d6ad6a9488.png)
![image](https://user-images.githubusercontent.com/78714518/123455796-c39aa200-d5ff-11eb-9ae4-91440cd744a1.png)
EB:   Horizontal scroll bar should be avoided

**Comment by puru-hk** [comment]
@Sanjay-1312 I have verified in the real mobile and iPad device Horizontal scroll bar is not appearing. This issue can be closed.
