### ISSUE TITLE
Search Field- Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5581]
Accessibility: Search Field- Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:

[Search Field_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6595748/Search.Field_Platform_ARIBA.Controls.docx)

**Comment by DeepakSap14** [comment]
- [ ] Issue 1
   Observed Behavior:
       On typing the letters, a list of search result is displayed but the information regarding the search result list is not read by 
       the screen reader.

   Expected Behavior:
      Ideally, when the search result list is displayed on the screen the information regarding the search result list and total 
      number of items available within the list should be read.

![image](https://user-images.githubusercontent.com/57661487/121293302-0aeb1800-c909-11eb-828c-701858a14e7b.png)

**Comment by DeepakSap14** [comment]
one more accessibility issue in search field https://github.com/SAP/fundamental-ngx/issues/5276.

**Comment by Sanjay-1312** [comment]
Issue 1: Fixed

Issue 2: Fixed

Issue 3: 
Same issue persists.
OB: On activating the 'Clear' button, additional information 'A' is read.
EB: ideally, such additional information should be removed.

issue: 4 Fixed

**Comment by DeepakSap14** [comment]
@puru-hk 
Issue 3: this is not an issue from library side. It is default behaviour of Jaws screen reader. I did try to over-ride it, but it can't be done. It is not fixable.
On clearing the input text like `apple`, last cleared character `a` is getting read.
please take decision, we have other issues fixed. You can raise a different issue for issue 3 , so other fixed issue can be merged.
