### ISSUE TITLE
Slider-Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5582]
Accessibility: Slider-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:

[Slider_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6595751/Slider_Platform_ARIBA.Controls.docx)

Application & Test Environment Details
Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/platform/home
Web browser:	Google Chrome 91.0.4472.77
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2012.57.400
Technology:	Angular 11

### Issue 1:
Priority:	High
Checkpoint:	ACC-264

Within all the sliders available navigate to the slider and change the value using arrow keys.
Observed Behavior:
On navigating to the sliders, the information regarding the minimum and maximum values available is not read.
The speech output is:
slider left right slider  Has Popup  
52
To increase or decrease use the Arrow keys.

Expected Behavior:
Ideally, the entire relevant information available should be read on navigating to the sliders. i.e. on navigating to the sliders the information regarding the maximum and minimum value available should be read.

Screenshot:
Case 1- Basic:

![image](https://user-images.githubusercontent.com/52071505/122211561-80845480-cec4-11eb-9744-3beba5490931.png)

Case 2 - Tooltip:

![image](https://user-images.githubusercontent.com/52071505/122211638-942fbb00-cec4-11eb-9379-b7fc40a6ccd9.png)

Case 3 - Tick marks and labels:

![image](https://user-images.githubusercontent.com/52071505/122211703-a4e03100-cec4-11eb-902c-05fec4e84a4f.png)

### Issue 2

Priority:	Medium
Checkpoint:	ACC-264

Within all the sliders available navigate to the slider and change the value using up/down arrow keys.
Observed Behavior:
On changing the value within all the sliders using up/down arrow keys, the information regarding the value is read twice. Therefore, additional information is read.
The speech output is:
slider left right slider  Has Popup  
52
To increase or decrease use the Arrow keys.
53
53
54
54
55
55

Expected Behavior:
Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once and no additional information should be read.

Screenshot:
Case 1- Basic

![image](https://user-images.githubusercontent.com/52071505/122211865-d35e0c00-cec4-11eb-8759-5dd04276a536.png)

Case 2 - Tooltip:

![image](https://user-images.githubusercontent.com/52071505/122211910-e1ac2800-cec4-11eb-975b-27505eb453db.png)

Case 3 - Tickmarks and labels:

![image](https://user-images.githubusercontent.com/52071505/122211968-eec91700-cec4-11eb-9749-7a474d537509.png)

### Issue 3

Priority:	High
Checkpoint:	ACC-264

Within all the sliders available navigate to the slider using tab key.
Observed Behavior:
On navigating to the sliders using tab key, an incorrect information ‘has pop up’ is read even if there is no pop up available.
The speech output is:
slider left right slider  Has Popup  
52
To increase or decrease use the Arrow keys.
53
53
54
54
55
55

Expected Behavior:
Ideally, on navigating to the sliders using tab key, the information read should be clear and precise and no additional information should be read. i.e. the information ‘has pop up’ should not be read if there is no pop up available.

Screenshot:
Case 1- Basic

![image](https://user-images.githubusercontent.com/52071505/122212099-18823e00-cec5-11eb-8567-e536589fc2ac.png)

Case 2 - Tooltip

![image](https://user-images.githubusercontent.com/52071505/122212145-246e0000-cec5-11eb-9595-d885beb6f740.png)

Case 3 - Tickmark and labels
![image](https://user-images.githubusercontent.com/52071505/122212200-3354b280-cec5-11eb-80db-02db89740b0d.png)

### Issue 4

Priority:	High
Checkpoint:	ACC-264

Within custom values navigate to the slider and change the value.
Observed Behavior:
On changing the values within the slider using arrow keys, the value ‘jan1, jan 2, jan 3 etc.’ changes but the same information is not read by the screen reader. i.e. the information regarding the focused value or on changing the value is not read.
The speech output is:
slider left right slider  Has Popup  
0
To increase or decrease use the Arrow keys.
0
0
0
0

Expected Behavior:
Ideally, on changing the alue within the slider, the information regarding the focused value and the changed value should be read.
Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/52071505/122212368-60a16080-cec5-11eb-9e69-a8c40d92d035.png)

Case 2 - Range

![image](https://user-images.githubusercontent.com/52071505/122212420-6e56e600-cec5-11eb-9ec2-ec72c0b0e10d.png)

### Issue 5

Priority:	High
Checkpoint:	ACC-264

Navigate to the slider within form field.
Observed Behavior:
On navigating to the slider using tab key, the corresponding label ‘single mode’, ‘Range Mode’ is not read. Therefore, the label is not associated to the respective UI element.
The speech output is:
slider left right slider  Has Popup  
17
To increase or decrease use the Arrow keys.
slider left right slider  Has Popup  
15
To increase or decrease use the Arrow keys.
slider left right slider  Has Popup  
86
To increase or decrease use the Arrow keys.

Expected Behavior:
Ideally, the corresponding label should be read on navigating to the slider. Therefore, the label should be associated to the respective UI element.
Screenshot:
![image](https://user-images.githubusercontent.com/52071505/122212556-9cd4c100-cec5-11eb-8339-6e112203b915.png)

**Comment by manjunathanagaraj** [comment]
Updated word doc attachment details

**Comment by Sanjay-1312** [comment]
Issue 1:

OB: The minimum and maximum value are not read.
EB: Ideally, the entire relevant information available should be read on navigating to the sliders. i.e. on navigating to the sliders the information regarding the maximum and minimum value available should be read.

issue 2:
OB: On accessing the slider, the values are read as '0' on changing the values.
![image](https://user-images.githubusercontent.com/78714518/123405942-ffb21080-d5c7-11eb-9c11-d85c2f238821.png)
EB: ideally, On changing the values the visible and changed values should be read on increasing and decreasing .

Issue 3:
OB: On accessing the slider, i can still able to reproduce the issue.
![image](https://user-images.githubusercontent.com/78714518/123405486-81ee0500-d5c7-11eb-98ba-73356989ec97.png)
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once and no additional information should be read.

Issue 4:
EB: On Changing the values are not read  but read as 'Zero' value.
![image](https://user-images.githubusercontent.com/78714518/123406362-73ecb400-d5c8-11eb-8c28-cd32f6643e15.png)
EB: Ideally, on changing the value within the slider, the information regarding the focused value and the changed value should be read.

Issue 5:
OB: On changing the value read as '0' on increasing and decreasing the values.
![image](https://user-images.githubusercontent.com/78714518/123406779-e5c4fd80-d5c8-11eb-89ad-6dfc50f2db34.png)
EB: Ideally, the changed value must be read.

[Note: On increasing and Decreasing the value are read as '0'.
So please fix the issue

URL:https://deploy-preview-5683--fundamental-ngx.netlify.app
JAWS 2021

**Comment by Sanjay-1312** [comment]
Issue 1: Fixed

Issue 2: 
![image](https://user-images.githubusercontent.com/78714518/124883401-ea3cdd80-dfee-11eb-91c7-02c3b1bbe3f0.png)
The value being read thrice through out the application.

OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.

Issue 3: 
![image](https://user-images.githubusercontent.com/78714518/124881940-85cd4e80-dfed-11eb-9f4b-742c63d8595a.png)

OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.

Issue 4:

![image](https://user-images.githubusercontent.com/78714518/124883086-9cc07080-dfee-11eb-84ee-6650de62f4e0.png)
OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once. 
The Range value should be read to the user

Issue 5:
![image](https://user-images.githubusercontent.com/78714518/124882922-77cbfd80-dfee-11eb-85e7-0876439dd274.png)
OB: On changing the values using up/down arrow key the values are read thrice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

issue 2,3,4,5:
OB: On changing the values using up/down arrow key the values are read twice to the user.
EB: Ideally, on changing the values within a slider using up/down arrow keys, the information regarding the value should be read only once.
![image](https://user-images.githubusercontent.com/78714518/125590752-e70af5ce-c509-4864-ad94-4c5609ae1468.png)

Note: Throughout the application.

URL: https://deploy-preview-5683--fundamental-ngx.netlify.app
JAWS 2021

**Comment by Sanjay-1312** [comment]
On increasing and decreasing the changed values are read twice using up and down arrow key.
Its known JAWS issue.
