### ISSUE TITLE
Status Indicator- Core

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#5583]
Accessibility:  Status Indicator- Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:

[Status Indicator_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6595754/Status.Indicator_Core_ARIBA.Controls.docx)

Application & Test Environment Details
Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/home
Web browser:	Google Chrome 91.0.4472.77
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2012.57.400

### Issue1:
Priority:	High
Checkpoint:	ACC-264

Within all the status indicators navigate to the progress bar
Observed Behavior:
The information regarding the progress bar for all the status indicators available is not read precise. i.e. for all the status indicators the progress bar information is read as ‘0 %’. Therefore, the information read is not precise.
The speech output is:
Cart Status Indicator default size Progress bar  0 percent
Euro Status Indicator default size Progress bar  0 percent
Factory Status Indicator default size Progress bar  0 percent
Truck Status Indicator default size Progress bar  0 percent
Euro Status Indicator default size Progress bar  0 percent
To activate press spacebar.

Expected Behavior:
Ideally, the information regarding the progress bar for all the status indicators should be read precise by the screen reader. Therefore, the information read should be clear and precise.

Screenshot:
Case 1:

![image](https://user-images.githubusercontent.com/52071505/122210401-3b135780-cec3-11eb-86a9-a299745fc0ed.png)

Case 2:

![image](https://user-images.githubusercontent.com/52071505/122210445-48304680-cec3-11eb-8deb-2670518be604.png)

Case 3:

![image](https://user-images.githubusercontent.com/52071505/122210491-554d3580-cec3-11eb-8efc-7b75a1c99d01.png)

Euro Status Indicator extra small size Progress bar  0 percent
Euro Status Indicator Medium size Progress bar  0 percent
Euro Status Indicator Large size Progress bar  0 percent
Euro Status Indicator Extra Large size Progress bar  0 percent
To activate press spacebar

Case 4:

![image](https://user-images.githubusercontent.com/52071505/122210621-7746b800-cec3-11eb-89ac-3a885f28f1c5.png)

Euro Status Indicator With Negative Filling Progress bar  0 percent
Euro Status Indicator With Critical Filling Progress bar  0 percent
Euro Status Indicator With informative Filling Progress bar  0 percent
To activate press spacebar.

Case 5:

![image](https://user-images.githubusercontent.com/52071505/122210731-934a5980-cec3-11eb-9104-fe669329ca76.png)

Speech output:
Euro Status Indicator Extra Large size with clock wise filling Progress bar  0 percent
Euro Status Indicator Extra Large size with clock wise filling Progress bar  0 percent
To activate press spacebar.

Case 6:
![image](https://user-images.githubusercontent.com/52071505/122210811-a9581a00-cec3-11eb-9ad3-6466892b82f1.png)

Speech output:
Euro Status Indicator with 45 degree filling Progress bar  0 percent
Euro Status Indicator with 90 degree filling Progress bar  0 percent
Euro Status Indicator with 180 degree filling Progress bar  0 percent
Euro Status Indicator with 270 degree filling Progress bar  0 percent

**Comment by manjunathanagaraj** [comment]
word doc attachment details updated.

**Comment by kavya-b** [comment]
@Sanjay-1312 please verify this issue in https://deploy-preview-5705--fundamental-ngx.netlify.app/#/core/status-indicator
