### ISSUE TITLE
Bug: (core) Dialog: if you uncheck 'hasBackDrop' select in Playground - dialog should be opened at the center of the screen

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5587]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
if you uncheck 'hasBackDrop' select in Playground - dialog should  open at the center, but it opens at the left bottom corner
#### If this is a bug, please provide steps for reproducing it.
Open https://deploy-preview-5387--fundamental-ngx.netlify.app/#/core/dialog
Go to Playground section
hasBackdrop selected by default, unselect it
Click on Open Dialog button
Expected result: dialog will open at the center
Actual result: dialog is opened at the lower left corner
#### Is there anything else we should know?
![Запись_экрана_2021-05-24_в_11 18 27](https://user-images.githubusercontent.com/83698366/120792909-e1b03d80-c53e-11eb-9020-f7f79ea2a1be.gif)

**Comment by Seamoo13** [comment]
duplicate
