### ISSUE TITLE
Selection cells wrong position in table

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#5613]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

Seems like on Mac all are looking great. Use Windows for reproducing this one.

![image](https://user-images.githubusercontent.com/20265336/120973230-54a3f900-c777-11eb-8075-8e0e1cac9b1d.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Fundamental-NGX 0.30.0
Chrome 91 (Windows)

#### If this is a bug, please provide steps for reproducing it.

Go to https://sap.github.io/fundamental-ngx/#/platform/table
Scroll down to any example with selection cells

**Comment by puru-hk** [comment]
Tested using this url https://deploy-preview-5614--fundamental-ngx.netlify.app/#/platform/table both Mac and Windows it is working fine 

![image](https://user-images.githubusercontent.com/32538291/121306960-16e0d500-c91d-11eb-9092-470788019ae2.png)
