### ISSUE TITLE
Combobox: roman character input conversion to Chinese characters not replacing roman characters

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#5618]
#### Is this a bug, enhancement, or feature request?
BUG

Chinese users input characters using roman characters and convert them on the fly to native characters.

Current behaviour (the issue):
1. Select a Chinese keyboard
2. Input "a"
3. Press spacebar
4. Input field's value is "a锕"

![roman-characters-not-removed](https://user-images.githubusercontent.com/1498400/121017570-b6775980-c79d-11eb-8f0a-e8047d94f58d.gif)

#### Briefly describe your proposal.

Expected behaviour:
1. Select "Chinese keyboard"
2. Input "a"
3. Press spacebar
4. Expect "a" to be replaced by "锕"

<img width="364" alt="截屏2021-06-07 14 20 40" src="https://user-images.githubusercontent.com/1498400/121017496-a19ac600-c79d-11eb-9130-b4606880d02b.png">

Currently 
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental v0.30 
angular version: same as used on examples webpage for fundamental v0.30

#### If this is a bug, please provide steps for reproducing it.

Go to: https://sap.github.io/fundamental-ngx/#/core/combobox

and do following steps:

1. Select a Chinese keyboard
2. Input "a"
3. Press spacebar
4. Input field's value is "a锕"

**Comment by hanjunt** [comment]
To document the change, this bug is no longer reproducible in version 31 of fundamental-ngx/core/combobox.  i.e. ```v 0.31```

**Comment by aberikashvili** [comment]
@desaroxx @droshev This issue isn't reproduceable 
https://drive.google.com/file/d/1G1n9iIQrR0j6r7sFYSLUkZ83UFas5ojH/view?usp=sharing
