### ISSUE TITLE
bug(platform): disable table toolbar when table in the loading state

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#5623]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

When table in the loading state there is no much sense from the working toolbar as any actions should be processed after data get loaded.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.30.0-rc.60
Chrome 91 (MacOS Big Sur)

#### If this is a bug, please provide steps for reproducing it.

Go to the https://fundamental-ngx.netlify.app/#/platform/table#loading-table
Tab to the search field above the table

**Comment by puru-hk** [comment]
Here is the attachment of the issue 
![Screenshot 2021-06-17 at 14.50.01.png](https://images.zenhubusercontent.com/5f4c9866d9d21de4c96444ff/dba1c7ee-aa91-441e-9db3-d44398842972)

**Comment by platon-rov** [comment]
Currently, we have busy indicator wrapping only the table, not the table toolbar. I guess it may be incorrect as when the table data is loading we should not allow the use of the toolbar. 

I could not find any documents about it so it's an open question right now so I will try to reach the design team to get the answers.
