### ISSUE TITLE
fd-tile's margin is also clickable

### ISSUE THREAD

**Issue by DavidEgresits** [SAP/fundamental-ngx#5630]
Dear Colleagues,

Please handle this incident as an internal SAP incident, although I'm working on an internal project, I found that this is the preferred way to open an incident for Fundamentals.

If margin is added outside of the fd-tile, the margin is also clickable, so if I click outside of the tile, it also fires the click event.
The margin should not be clickable according to the HTML box model.

Screenshot about the issue:
![image](https://user-images.githubusercontent.com/15217061/121148922-7c13c800-c842-11eb-8432-b50145ece194.png)
HTML code:
`<fd-tile class="persona-tile" [double]="true" class="my-3 mx-1" (click)="login()">`

Could you please fix the fd-tile not to fire click event from the margin?

Desktop:
OS: macOS
Browser: Chrome
Version: 90.0.4430.212

Thanks and Best regards,
David Egresits
Associate Architect, SAP Business Networks
SAP Labs Hungary

**Comment by droshev** [comment]
we need to verify whether this is valid

**Comment by platon-rov** [comment]
not reproducible.
