### ISSUE TITLE
Date Time Picker: Scrolling thru the Time Control is Missing

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#5644]
#### Comparing the date time picker with its UI5 version I recognized that scrolling thru the time picker control using the mouse wheel isn't possible. Either it is not working or was forgotten.

See attached .gif of UI5 control as reference.

#### v0.30.0
![datetimepicker-scroll](https://user-images.githubusercontent.com/52921101/121497893-2ffc8b00-c9dc-11eb-85da-1a30dbec983d.gif)

**Comment by droshev** [comment]
@D034394 this can be a good improvement.
