### ISSUE TITLE
Date Time Picker: Cozy Mode Missing

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#5646]
#### According to Fiori Guidelines there is also a cozy mode for the date time picker. Is this planned already / on the roadmap?

![image](https://user-images.githubusercontent.com/52921101/121500169-5ae7de80-c9de-11eb-9a15-a1b01f2c0938.png)

**Comment by droshev** [comment]
Date time picker has compact and cozy:
<img width="582" alt="Screen Shot 2021-11-30 at 19 18 50" src="https://user-images.githubusercontent.com/4380815/144148955-b786d07e-3d74-4860-b949-08ae3c742154.png">
<img width="847" alt="Screen Shot 2021-11-30 at 09 23 10" src="https://user-images.githubusercontent.com/4380815/144148956-3953613d-8aba-460e-99af-a0731d82f908.png">
