### ISSUE TITLE
Bug: (core) a lot of empty extra space in Notification Group example for Notification Component

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5648]
#### Briefly describe your proposal.
A lot of empty extra space in Notification Group example
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.30.1-rc.69
#### If this is a bug, please provide steps for reproducing it.
Open https://fundamental-ngx.netlify.app/#/core/notification
Scroll to Notification Group example
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/121516787-495f0080-c9f7-11eb-8df0-2e98e13e537b.png)
![image](https://user-images.githubusercontent.com/83698366/121516805-4e23b480-c9f7-11eb-96f9-2588069d7165.png)

**Comment by puru-hk** [comment]
Tested in this url it is working fine https://deploy-preview-5736--fundamental-ngx.netlify.app/#/core/notification
