### ISSUE TITLE
Date Time Picker: Too many Elements on the Rotating Time Wheel

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#5652]
#### When opening the date time picker the rotating time wheel shows seven elements for each dimension (hours, minutes, seconds). This causes unnecessary whitespace on the calendar control side. Additionally, this is not in line with the corresponding UI5 control and the Fiori Guidelines which both show only five elements for each time dimension.

Fundamentals NGX:
![image](https://user-images.githubusercontent.com/52921101/121574768-e4bb9a00-ca26-11eb-942c-d69e510b4fa2.png)

UI5 and Fiori Guidelines:
![image](https://user-images.githubusercontent.com/52921101/121554113-27bf4280-ca12-11eb-9b68-ffec130ead96.png)

**Comment by droshev** [comment]
this can be achieved by reducing the visible hours before and after the selected one. It is very easy with css.
