### ISSUE TITLE
Date Time Picker: Rotating Time Wheel is Always Activated

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#5653]
#### When opening the date time picker the rotating time wheel for hours is initially active. Switching between the time wheels for hours, minutes, etc. it isn't possible at any time to "focus out" of the time control at all. One time wheel is always active. This is contradictory to the corresponding of UI5.

Current behavior in NGX:
![datetimepicker-active-ngx](https://user-images.githubusercontent.com/52921101/121562598-e763c280-ca19-11eb-9b3e-e254b27da66a.gif)

Corresponding control in UI5:
![datetimepicker-active-ui5](https://user-images.githubusercontent.com/52921101/121562745-095d4500-ca1a-11eb-8c4f-284f56af24a6.gif)

#### v0.30.0

**Comment by mikerodonnell89** [comment]
I have contacted the designers about this - not mentioned in the fiori specs, will get back to it

**Comment by droshev** [comment]
@D034394 the time picker design changed so I would say let's leave this as is.
