### ISSUE TITLE
Bug: Action bar mobile view, the "Overflow" or "More" icon appears twice

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5679]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="909" alt="Action Bar" src="https://user-images.githubusercontent.com/71797052/121971637-0b7f1680-cd2e-11eb-9e5d-d753f2c9fa0d.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.30.1-rc87

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/action-bar
Scroll down to Action bar mobile view
See error

**Comment by droshev** [comment]
The doc example needs to be updated. This is not a bug
