### ISSUE TITLE
Bug: Action Sheet dropdown layout not consistent and aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5680]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
According to Visual Core:
<img width="1010" alt="Layout and Structure" src="https://user-images.githubusercontent.com/71797052/121972552-39655a80-cd30-11eb-842d-6ef25f661241.png">

Currently this is what is shown for desktop
<img width="554" alt="= Fundamental NGX Core" src="https://user-images.githubusercontent.com/71797052/121974273-e42b4800-cd33-11eb-8acc-6a9d4d52065f.png">
<img width="568" alt="= Fundamental NGX Core" src="https://user-images.githubusercontent.com/71797052/121974293-f0170a00-cd33-11eb-9247-e6cfe8ccda93.png">

Currently this is what is shown for mobile
![image](https://user-images.githubusercontent.com/71797052/121974472-4ab06600-cd34-11eb-8ac8-c5fb5114e288.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.) 
v0.31.0-rc87

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/action-sheet
Scroll down and click on any action  sheet
See discrepancy

**Comment by droshev** [comment]
The feature is already in styles - https://fundamental-styles.netlify.app/?path=/docs/components-action-sheet--action-sheet-desktop#mobile 
We need to update the doc examples
