### ISSUE TITLE
content density setter through URL parameter

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5689]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Introduce an enhancement in content density so the value can be set through URL parameter similar like [Theming Service](https://github.com/SAP/fundamental-ngx/blob/0bfc00a1c7e0a767df9cde9289b8eff073c175e8/libs/core/src/lib/utils/services/themes.service.ts#L93) 

this way it will avoid a lot of boiler plate

**Comment by g-cheishvili** [comment]
Implemented in https://github.com/SAP/fundamental-ngx/pull/8230
