### ISSUE TITLE
Bug: (core)Content Density: if you choose 'compact' or 'Condensed' points in menu list also will be changed

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5708]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.31.0-rc.8
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/content-density
2. In drop-down select 'compact' or 'condensed'
Expected result: only button right from drop-down changed size
Actual result: points in the menu list also changed size
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/122550752-b8160c80-d03c-11eb-859f-357bffab4bc7.png)

![image](https://user-images.githubusercontent.com/83698366/122550782-c401ce80-d03c-11eb-9fb1-5d0609ae2b95.png)

**Comment by droshev** [comment]
@maxym-valor Actually it is the other way around. The service should change the content density to every component which doesn't have explicit content density set.
