### ISSUE TITLE
Bug: Mobile Calendar Portrait / Landscape does not exhibit RTL

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5729]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="706" alt="Fundamental NGX Core •" src="https://user-images.githubusercontent.com/71797052/122852841-25889e00-d2c6-11eb-94c7-14bcf9f25dfe.png">
<img width="702" alt="Fundamental NGX Core" src="https://user-images.githubusercontent.com/71797052/122852853-2b7e7f00-d2c6-11eb-8316-fd33bc9810e2.png">

#### If this is a bug, please provide steps for reproducing it.
Go to: https://fundamental-ngx.netlify.app/#/core/calendar
Scroll down to Mobile Calendar
Click RTL and see error

**Comment by N1XUS** [comment]
Issue was fixed in scope of #5792
