### ISSUE TITLE
Accessibility Testing_Platform_Object Attribute

### ISSUE THREAD

**Issue by fanjum-acc** [SAP/fundamental-ngx#5767]
Hello Colleagues,

Please find attached error document for control: Platform_Object Attribute

[Object Attribute_Platform_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6708832/Object.Attribute_Platform_Ariba.Controls.docx)

**Comment by manu-kr** [comment]
@fanjum-acc @puru-hk 
Related to Issue 2 i.e to focus the 'OK' button in alert box.
As its a browser default alert button we not have control over the styles of the browser and it's not possible to apply focus on OK button. Please refer below link for more details.
https://stackoverflow.com/questions/7853130/how-to-change-the-style-of-alert-box

Related to Issue 4 and Issue 5
Not able to reproduce this Issue.
