### ISSUE TITLE
mobile combobox arrow is present

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5773]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
mobile combobox should not have dropdown arrow control
![image](https://user-images.githubusercontent.com/4380815/123262064-7a463780-d4c5-11eb-9a34-fdebe4be9c74.png)

**Comment by aberikashvili** [comment]
@droshev I can't reproduce this bug on sap.github.io/fundamental-ngx
![image](https://user-images.githubusercontent.com/3863691/125306477-50ec2f00-e340-11eb-822c-b2fc9638c64f.png)

**Comment by aberikashvili** [comment]
not reproduceable
