### ISSUE TITLE
Card Component bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5776]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

- [ ] when list component is used inside the Card body the List Items do not get focus with Tab key. The focus goes from the Card header to the List body
![image](https://user-images.githubusercontent.com/4380815/123263317-d493c800-d4c6-11eb-94cf-2c20d2e591cb.png)

- [ ] The card counter reads "of 10 3" in RTL mode.
All browsers.
![image](https://user-images.githubusercontent.com/4380815/123263376-e4131100-d4c6-11eb-9252-16e8fff898ee.png)

**Comment by Lokanathan-k** [comment]
the list body is focus is part of list component, so new issue is created to follow up 
https://github.com/SAP/fundamental-ngx/issues/5945

**Comment by Lokanathan-k** [comment]
issue 1: fixed as part of the issue,
issue 2: the issue has been already addressed by @dimamarksman  and comments has been approve and closed by @droshev (https://github.com/SAP/fundamental-ngx/issues/3418#issuecomment-700573734)
