### ISSUE TITLE
datepicker bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5786]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] the attribute is actually `placement` not `position`.  Datetime picker docs also mention position when it needs to be placement.
<img width="756" alt="Screen Shot 2021-05-19 at 11 29 21 AM" src="https://user-images.githubusercontent.com/2471874/118857608-78210580-b895-11eb-8544-3107650b3ac9.png">

- [ ] On mobile devices, mobile calendar navigation container is not centered when opened in landscape mode
![image](https://user-images.githubusercontent.com/6586561/118944134-f5637d80-b95c-11eb-808d-907169841383.png)
![image](https://user-images.githubusercontent.com/6586561/118944304-1deb7780-b95d-11eb-9e76-7cab77e1331b.png)

**Comment by kavya-b** [comment]
The calendar landscape issue is a different issue. It should look like [this](https://sap.github.io/fundamental-styles/?path=/docs/components-calendar--days#landscape--mobile-) with a close button at the right, which isn't currently visible and needs to be fixed: 
![image](https://user-images.githubusercontent.com/53509521/125040419-44a07180-e0b5-11eb-8c7b-837e23dcc5f9.png)
