### ISSUE TITLE
Abstract routing

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-ngx#580]
#### enhancement
Abstract routing

#### Briefly describe your proposal.
As a consumer, I should be able to use either ngRoute, UIRouter, or expressJS (or some anything else) for my routing. As such, routing should not be a direct dependency on this UI component library, as seen here:

https://github.com/SAP/fundamental-ngx/blob/master/library/package.json#L18

**Comment by MattL75** [comment]
@mikerodonnell89 This dependency has been here since I joined the team. Any clue why it's here? Pretty sure we don't use the router in any component

**Comment by mikerodonnell89** [comment]
None of our library components are actually dependent on Angular router, we can remove this
