### ISSUE TITLE
Accessibility Testing_Core_Object number

### ISSUE THREAD

**Issue by surbhi175** [SAP/fundamental-ngx#5804]
Hi Team,

Please find the error document attached for Core_Object Number.
[Object Number_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6713714/Object.Number_Core_ARIBA.Controls.docx)

Observed Behavior:

‘0,00 EUR’ orange text displayed within ‘Basic Object Number’, ‘Object Number Status’, ‘Large Object Number’, ‘Bold Object Number’, ‘Object Number Units’ & ‘Object Number Decimal’ sections do not satisfy minimum contrast ratio of at least 3:1 in Default theme.

Expected Behavior:

Ideally, orange text displayed should satisfy minimum contrast ratio of at least 3:1 in Default theme.
![image](https://user-images.githubusercontent.com/53509521/126939481-40f2c1a6-3cdf-47aa-97c0-e1ed73099b3a.png)

**Comment by kavya-b** [comment]
Please see this note at the top of the visual spec page for Object Number: 
![image](https://user-images.githubusercontent.com/53509521/126939383-0bf25445-59f8-4f51-a9d5-9bdcc191ab42.png)
This is a known issue and therefore won't be fixed.
![image](https://user-images.githubusercontent.com/53509521/126939630-a006c68a-1de7-4f97-8a26-3563e93d6610.png)

@puru-hk @Sanjay-1312 @surbhi175

**Comment by dmitry-stepanenko** [comment]
I suppose this ticket can be closed as per comment above

**Comment by puru-hk** [comment]
@Sanjay-1312  As discussed earlier meeting contrast issues can be closed.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

As discussed with the Puru, this color contrast ratio issue can be closed.
Hence Closing the ticket.

Thanks and Regards
Sanjay
