### ISSUE TITLE
bug: table(platform) - errors shown on page loading

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#5807]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

Page loading feature produces errors to the console.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.31.0-rc.23

#### If this is a bug, please provide steps for reproducing it.

Go to the platform table component, page loading example
Scroll several times to the end of the page
On 2-3 scroll - errors appear.

![image](https://user-images.githubusercontent.com/20265336/123391655-e9df2400-d5a4-11eb-879a-74f126f294a9.png)

#### Is there anything else we should know?

Seems like it's because of changes #5526.

**Comment by platon-rov** [comment]
In the scope of PR #5692 tests cases for page scrolling have been disabled. If bug will be fixed before #5692 is merged - ping me/update that PR to enable test cases for the page scrolling.

**Comment by platon-rov** [comment]
In the scope of PR #5692 tests cases for page scrolling have been disabled. If bug will be fixed before #5692 is merged - ping me/update that PR to enable test cases for the page scrolling.

**Comment by puru-hk** [comment]
Looks fine
