### ISSUE TITLE
Bug: (core) Wizard - When you try to select another radio button and click 'Cancel' in confirmation pop-up, focus disappears

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5808]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Wizard component, branching example:
When you selected one payment type and would like change it to another - you will get confirmation pop-up. First time if you click 'Cancel' - focus from radio button disappears(no selected radio-buttons), but it should not. Focus should return to previous selected button. Next time (second, third etc.) it will work as expected, focus will be returned to the previous button
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/wizard#Wizard-Branching
2. Open Wizard
3.  Click 'Go to the payment section page'
4. Select first radio-button
5. Select second radio-button
6. Click 'Cancel' in pop-up
Expected result: focus returned to the first radio-button
Actual result: focus disappeared, no chosen button and when we want to select radio-button we will get pop-up again

![Запись_экрана_2021-06-25_в_11 19 04](https://user-images.githubusercontent.com/83698366/123394117-725ec400-d5a7-11eb-816c-d5faf9aae219.gif)

**Comment by mikerodonnell89** [comment]
Hi @maxym-valor, for the sake of keeping the core fundamental-ngx wizard fairly flexible compared to its platform generated sibling, we have made the branching logic mostly rely on the application developer working with the library.  However I've made some recent changes to the documentation that should be merged soon, here's a link to the PR: https://github.com/SAP/fundamental-ngx/pull/6018
