### ISSUE TITLE
mobile doc - version select not reachable

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5815]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Shellbar - overflow counter cutoff by menu.  I think the overflow counter has some custom css in ngx so the fix might be here, might be in styles, not sure at the moment - **This should be done as badge on button, not menu**
![Screen Shot 2021-02-24 at 5 07 13 PM](https://user-images.githubusercontent.com/2471874/109083237-bfe32700-76c2-11eb-958d-4df65aef85af.png)

**Comment by mikerodonnell89** [comment]
@droshev Description in this issue did not match the title
