### ISSUE TITLE
Bug: (core) Progress-bar should not be visible after edit in Dialog Wizard

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5817]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
When you edited your data in Dialog Wizard and click 'next step' - you see Checkout window with progress-bar, but progress-bar should not be visible.
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/wizard#Wizard-Dialog
2. Click 'Open Wizard in Dialog'
3. Go to second step
4. Fill data in the fields
5. Click 'Next step' until you will be on Checkout page
6. Click 'Cancel'
7. Click 'Open Wizard in Dialog'
6. On checkout page click on Edit in second section 'Customer situation'
7. Update information and click 'Next step'
Expected: you are directed to the Checkout page
Actual: you are on the Checkout page with progress-bar

#### Is there anything else we should know?
![Запись_экрана_2021-06-25_в_13 53 19](https://user-images.githubusercontent.com/83698366/123414849-11da8180-d5bd-11eb-8e58-f97153011f11.gif)

**Comment by N1XUS** [comment]
@maxym-valor the issue has been fixed in wizard generator PR #5823.
