### ISSUE TITLE
Compile errors after switching to Angular Ver.12. Is Angular V.12 supported right now?

### ISSUE THREAD

**Issue by rodema** [SAP/fundamental-ngx#5820]
Hello fundamental-ngx team,
a minimal demo scenario which worked fine with Angular10 throws some compile errors after switching to Angular12.
So my question is, does fundamental-ngx support latest version of Angular (Ver.12)?
If not, are there plans to support it in future and is there already a timeline?

Thank you for your support.
Best regards,
Matthias

#### Is this a bug, enhancement, or feature request?
bug, Angular 12 not supported

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
-> Angular V12, 
    "@fundamental-ngx/platform": "0.30.0",
    "@fundamental-ngx/core": "0.30.0",

#### If this is a bug, please provide steps for reproducing it.

`The following compile errors are thrown when I try to build my demo project with Angular12.

Error: node_modules/@fundamental-ngx/core/node_modules/@angular/platform-browser/platform-browser.d.ts:703:5 - error TS2416: Property 'supportsDOMEvents' in type 'ɵangular_packages_platform_browser_platform_browser_o' is not assignable to the same property in base type 'ɵDomAdapter'.
  Type '() => boolean' is not assignable to type 'boolean'.

703     supportsDOMEvents(): boolean;
        ~~~~~~~~~~~~~~~~~


Error: node_modules/@fundamental-ngx/core/node_modules/@angular/platform-browser/platform-browser.d.ts:703:5 - error TS2425: Class 'ɵDomAdapter' defines instance member property 'supportsDOMEvents', but extended class 'ɵangular_packages_platform_browser_platform_browser_o' defines it as instance member function.

703     supportsDOMEvents(): boolean;
        ~~~~~~~~~~~~~~~~~`


#### Please provide relevant source code if applicable.

#### Is there anything else we should know?

**Comment by droshev** [comment]
Hi @rodema , thanks for raising the issue. Let us investigate and come back to you very soon.

**Comment by N1XUS** [comment]
@rodema as I see, your error log includes @angular library inside @fundamental-ngx. Could you please specify node and npm version? And also steps you've done for installing @fundamental-ngx/core in your project

**Comment by rodema** [comment]
Hello Denis (@N1XUS )
I'm using the following versions of npm and node
λ npm --version
6.14.11
λ node --version
v14.16.0
The project was created via the angular v.12 CLI and contains "only" a fundamental-ngx button element
I have attached the project in a zip file for your reference.

In the package.json file, I have specified the following two entries as dependencies:
    "@fundamental-ngx/core": "0.30.0",
    "@fundamental-ngx/platform": "0.30.0",
Installation of @fundamental-ngx/core like all the other node modules are donw via "npm install".
If you need more information, pls. let me know.
Thank you for your support.

Best regards,
[testappv12.zip](https://github.com/SAP/fundamental-ngx/files/6802569/testappv12.zip)
Matthias

**Comment by N1XUS** [comment]
@rodema hello, thank you for the provided info. Could you please try to install 0.31.0-rc.88 version of fundamental-ngx/core and fundamental-ngx/platform and check if the error still exists?

**Comment by rodema** [comment]
Hello Denis (@N1XUS),
thank you for your fast feedback.
Switching my Angular V12 test project to 
    "@fundamental-ngx/core": "0.31.0-rc.88",
    "@fundamental-ngx/platform": "v0.31.0-rc.88",
solved the compile error.
So I'm going to close this issue.
Looking forward to the official release of version 0.31    
Best regards,
Matthias
