### ISSUE TITLE
bug: Localization issue on Approval flow component

### ISSUE THREAD

**Issue by I835291** [SAP/fundamental-ngx#5835]
#### Steps to reproduce:
1. Create a task of type review
2. Add approvers.
Now you can see a string concatenation issue. The string highlighted ("item selected") should contain the number of items selected as a variable.  So there should be 2 strings like "(0) item selected" where (0)=1 and "(0) items selected" where (0) > 1
![Create_review_type_task_add_approver](https://user-images.githubusercontent.com/86618211/123669407-e6d87380-d7f0-11eb-9dc5-378128d59cef.png)

**Comment by mikerodonnell89** [comment]
Fixed with #7900
