### ISSUE TITLE
There is no option to go to home page once you in component page in Mobile device

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5843]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

Once you are in component page there is no option to go to home page in mobile device

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Samsung Galaxy 10 S Plus
#### If this is a bug, please provide steps for reproducing it.
Login to ngx from the mobile device
Select core or platform
Select any component
Once you are in component page there is no option to go to home page

#### Is there anything else we should know?
![Mobile component page](https://user-images.githubusercontent.com/32538291/123737554-c8da4400-d8c0-11eb-80f2-5fde489e5075.jpg)

**Comment by droshev** [comment]
fixed
