### ISSUE TITLE
Bug: The dependency to @angular/animations is 11.2.13 which restricts use of others libraries before version 12.1.0 (where we have dependencies with critical vulnerabilities)

### ISSUE THREAD

**Issue by anandsgar-sap** [SAP/fundamental-ngx#5850]
Security Vulnerability:
When could be expect an upgrade in dependency version?

**Comment by N1XUS** [comment]
@anandsgar-sap Hello and thank you for the bug report. I've tried with Angular v12 application to add @fundamental-ngx/core via `ng add` command for the latest rc build, and found that of @angular/animations was the same as @angular/core.

Alternatively, you can manually specify required version of @angular/animations in your package.json file

**Comment by droshev** [comment]
@anandsgar-sap is there any chance you experienced this with npm v7?
