### ISSUE TITLE
Platform components don't default to same content density value as core components

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5877]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
There are components in platform that the default content density value is not the same as the value in core.
Examples: button, select,..

All the platform components should default to the same content density as it core

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by sKudum** [comment]
Hi @droshev ,

@fyi
  Out of 40 components in platform found button is loading in compact mode in user applications others are performing as expected. 

<img width="652" alt="2021-07-07_16-21-04" src="https://user-images.githubusercontent.com/53487468/124747545-a8089300-df3f-11eb-9a50-4fa912cce918.png">

please let me know in case am missing something, 

proceeding with fix for button.

**Comment by puru-hk** [comment]
Verified in ngx version rc 31. Select and Button components in platform is implemented. Hence it is closed.
