### ISSUE TITLE
Bug (core): Shellbar component doesn't handle combobox with isSearch="true" properly

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-ngx#5893]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Shellbar component doesn't add requited styles to the clear icon if combobox is used with `isSearch="true"` option.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.32.1
#### If this is a bug, please provide steps for reproducing it.
![image](https://user-images.githubusercontent.com/3263744/124625252-7fdf3e00-de32-11eb-8364-8da8d2e1efc9.png)

#### Please provide relevant source code if applicable.
[Example link](https://stackblitz.com/edit/angular-rlefjp-apnwrd?file=src%2Fapp%2Fshellbar-collapsible-example.component.html)

**Comment by maxym-valor** [comment]
@dimamarksman Add steps to reproduce and expected & actual results in details, please!
