### ISSUE TITLE
Status indicator issue in RTL

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5901]
**Describe the bug**

Status indicator - missing RTL support of the indicator:
<img width="476" alt="Screen Shot 2021-05-20 at 4 16 31 PM" src="https://user-images.githubusercontent.com/39598672/119043231-d2e65a00-b986-11eb-82cc-0480adc75456.png">
<img width="216" alt="Screen Shot 2021-05-20 at 4 16 12 PM" src="https://user-images.githubusercontent.com/39598672/119043234-d37ef080-b986-11eb-8dbb-7f6f1f299e09.png">

**Comment by puru-hk** [comment]
Verified in PR6032 it is working as expected.
