### ISSUE TITLE
modal in modal, fd-modal backdrop should be disabled

### ISSUE THREAD

**Issue by maxmarkus** [SAP/fundamental-ngx#593]
Hello, 

when using modal in modal, the second modal also creates an additional backdrop, which we would like to remove. Would be great to have a fd-modal option to disable the backdrop.

Best, Markus

**Comment by MattL75** [comment]
Hi Markus!

I'm currently in the process of a fairly large revamp of our Alert component as part of #581 . When that's done, we plan on addressing a lot of similar issues with the Modal. Enabling/disabling a backdrop will definitely be a provided feature.
