### ISSUE TITLE
Popover body positioning wrong when scrolling

### ISSUE THREAD

**Issue by maxmarkus** [SAP/fundamental-ngx#594]
Hello, 

We're having an issue with popover positioning inside a modal, if the modal has scrollable content.
The `fd-modal  .fd-modal .fd-popover__body` is set to `position: fixed` which leads to weird behavior when scrolling inside the modal, as you can see at the screenshot.

<img width="80%" alt="screen markus e 2019-03-01 at 14 20 41" src="https://user-images.githubusercontent.com/1720843/53640987-f3069300-3c2d-11e9-846b-8e921b1c2000.png">

We've solved it by setting the position to `absolute` with `::ng-deep fd-modal .fd-modal .fd-popover__body { position: absolute; }`. 
Since `ng-deep` will be deprecated somewhen in the future, we cannot stick to this solution.

Best, Markus

**Comment by MattL75** [comment]
This will be fixed by #410 through Popper.js, but the ticket is waiting on SAP/fundamental#1286

**Comment by droshev** [comment]
@maxmarkus Thanks for raising the issue, we will update you soon.
