### ISSUE TITLE
Window.postMessage() does not work inside unselected tabs (fd-tab)

### ISSUE THREAD

**Issue by kistll** [SAP/fundamental-ngx#5949]
#### Is this a bug, enhancement, or feature request?

Unclear

#### Briefly describe your proposal.

In our applications we make use of [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)  to communicate between modals, frames or the like. In one of our applications we have two modals (modal A and modal B). In both modals there are tabs. In modal A the tabs are realized by using `fd-tab-nav`, `fd-tab-item` and `fd-tab-link`. In modal B the tabs are realized by using `fd-tab-list` and `fd-tab`. For both modals, messages sent by Window.postMessage() are working fine if the sender is the current selected tab. However, messages sent by Window.postMessage() are not working as expected, if the sender is not the current selected tab. In case of modal A this is not an issue as the messages are only triggered if the sender of the messages becomes the current selected tab. In case of modal B this is an issue as the messages are also triggered if the sender of the messages is not the current selected tab. It seems like that in case of modal B the unselected tabs are prerendered inside a shadow DOM or the like. Do you have any idea to solve this? 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@fundamental-ngx/core: 0.28.3

**Comment by droshev** [comment]
@mikerodonnell89 Can you check whether it is still applicable?

**Comment by mikerodonnell89** [comment]
@kistll Can you provide some sample code or a stackblitz that demonstrates the issue you are facing?
