### ISSUE TITLE
bug (core): disabled input changes value according to split menu previous

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5954]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Component: split-menu button
If you change value of pre-last split menu - value of last menu will be changed according to value of pre-last menu.
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/platform/split-menu-button
2. change value for pre-last split menu
Expected: only pre-last menu value changed
Actual: changed value of pre-last menu and disabled menu (next)
![Запись_экрана_2021-07-13_в_13 58 51](https://user-images.githubusercontent.com/83698366/125441568-7db12500-a5b8-49e1-8804-79d84dce3039.gif)

**Comment by puru-hk** [comment]
@maxym-valor bug 5955 is same. Could you please close this issue.
