### ISSUE TITLE
bug (platform): wrong anchor links for split menu button component

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5956]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Wrong links in anchors which dont work.
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/split-menu-button
2. Hover on anchor in any example, first for example
Expected result: correct link 'https://fundamental-ngx.netlify.app/#/platform/split-menu-button#behaviors'
Actual result: wrong link 'https://fundamental-ngx.netlify.app/#/platform/SplitMenuButtonComponent#behaviors'
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/125444435-8a8904a1-df59-4d63-9e1f-861f0100898e.png)

**Comment by puru-hk** [comment]
Verified in PR6059 it is working fine.
