### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#596]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.

- [x] Style like fd-react's next version
- [x] Display version number
- [x] Table-like layout for inputs/outputs etc
- [x] Maybe automatically scrape the files for the properties/methods and display the descriptions using comments in the file? [TSDoc](https://github.com/Microsoft/tsdoc) has a parser. We could use it in a per-file basis. Ideally, we'd do it once when we compile. This needs to be investigated further.
- [x] Tabs for Examples/API at the top. API page should contain tables representing all related child component/service/model etc.
- [x] Tabs to switch between the files of an example, also display file name.
- [x] Use StackBlitz as a playground.
- [x] Have a way to hide/display the code.
- [x] Anchors on all <h> tags, with a link icon to easily share a section of the docs.
- [ ] Table of contents on the right side (as with fd-react). They use [TocBot](https://tscanlin.github.io/tocbot/).

More may be added later

**Comment by droshev** [comment]
i think the dynamically generated inputs/outputs would be great
