### ISSUE TITLE
Approval Flow: Flowline / Overall Design bug

### ISSUE THREAD

**Issue by kenykim** [SAP/fundamental-ngx#5963]
There are gap between implemented and actual design, please check the attachment below
<img width="1192" alt="Screen Shot 2021-07-13 at 10 23 32 AM" src="https://user-images.githubusercontent.com/58018352/125497636-bd769097-9b85-46e7-828d-670f944631cf.png">

Design Spec link:
https://www.figma.com/file/19KQ4L5RL5FIGivfewmB8k/Approval-flow?node-id=757%3A4

You will be able to find Spec for flowline from the link
<img width="958" alt="Screen Shot 2021-07-13 at 10 38 19 AM" src="https://user-images.githubusercontent.com/58018352/125499724-e2a7c998-c0c6-49c5-b3c4-488005fb7996.png">

please check the detail of the specification through 'Inspect'

**Comment by kenykim** [comment]
@manjunathanagaraj Hi Manju could you please check the issue?
thanks!

**Comment by puru-hk** [comment]
This is not an bug because the spec are new. There is not functional impact.
