### ISSUE TITLE
Approval Flow: Edit mode asset

### ISSUE THREAD

**Issue by kenykim** [SAP/fundamental-ngx#5965]
Design assets are not matched with actual design  

![image](https://user-images.githubusercontent.com/58018352/125505394-99e6e0af-814a-4a58-a0ab-ba4c8bcd9a89.png)

Please refer to the following link for its spec 
https://www.figma.com/file/19KQ4L5RL5FIGivfewmB8k/Approval-flow?node-id=757%3A4

**Comment by puru-hk** [comment]
This is not an bug because the spec are new. There is not functional impact.
