### ISSUE TITLE
Carousel behaviour not as expected

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#5969]
#### Is this a bug, enhancement, or feature request?
bug/enhancement

#### Briefly describe your proposal.
For multiple active cards in the carousel, when there is 1/2 carousel item at the end on the screen, we are not able to view it fully when not looped

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 11.2
"@fundamental-ngx/core": "^0.28.1",

```
<fd-carousel [visibleSlidesCount]="visibleSlides" [navigatorInPageIndicator]="false">
            <fd-carousel-item></fd-carousel-item></fd-carousel>
```
`visibleSlides = 5;`

it works when we set [loop]="true" but when the carousel item are less than 5 for e.g. if there are 2 carousel items, then the loop doesn't provide a good user experience.

as shown, not able to fully view the last card.
![image](https://user-images.githubusercontent.com/29952750/125565017-6ebfe6c4-20f9-4996-8f03-c431a4c31bc8.png)

even if there are only 2 cards the right arrow button is active, is this an expected behavior?
![image](https://user-images.githubusercontent.com/29952750/127312974-407ee668-0447-4374-a66a-70f2dd062e38.png)

**Priority**
additionally before clicking on hide, on initial reload, there are no navigation buttons 
![image](https://user-images.githubusercontent.com/29952750/129322275-077806a5-54ac-45f1-b793-8d054d567dfc.png)

but on click of hide and then show, they appear. we are using ngIf to hide/show the carousel section
![image](https://user-images.githubusercontent.com/29952750/129322544-b6c785ec-3b87-465a-9dbd-44d7e476e3b3.png)

**Comment by AleenaSA** [comment]
can we have an update on this, at least the last part asap? @droshev

**Comment by droshev** [comment]
@AleenaSA can you help me understand the issue with this stackblitz - https://stackblitz.com/edit/angular-raxcqd?file=src%2Fapp%2Fcarousel-dynamic-items-example.component.ts

**Comment by AleenaSA** [comment]
Yes, if i hide all cards except the first three..the last card is not fully visibile 
![image](https://user-images.githubusercontent.com/29952750/140259241-53c44b24-bb2c-42c4-b936-6fee250c5bbe.png)

but if we apply loop="true" and the no of cards is less than what's needed to fill the screen then the user experience is not good. [stackblitz](https://stackblitz.com/edit/angular-raxcqd-cf2ycr?file=src%2Fapp%2Fcarousel-dynamic-items-example.component.html)
![image](https://user-images.githubusercontent.com/29952750/140259505-ff77cf95-9166-4253-9ec2-5d1c5490a083.png)

Just wanted to know if these are expected behaviors?

**Comment by AleenaSA** [comment]
FYI, noticed an error in the console 
![image](https://user-images.githubusercontent.com/29952750/146721946-b9568560-df48-4f95-9635-a3800543e143.png)

Steps to reproduce:

1. have a screen size where you can see all the cards at once. resize the screen so that you see fewer cards. navigate to last card. Resize back to full screen. you'll still not see all the cards, have to click on left-arrow button. on click the error pops us

**Comment by AleenaSA** [comment]
We also noticed that if the carousel card contains any Image, then after accidental long press on the image, carousel moves with the cursor until we click outside of the carousel. Is this a known behavior?
