### ISSUE TITLE
menu markup looks odd

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#597]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
The current `menu` markup is:
```
<fd-menu>
    <fd-menu-list>
        <li fd-menu-item>
            <a [attr.href]="'#'">Option 1</a>
        </li>
        <li fd-menu-item>
            <a [routerLink]="'#'">Option 2</a>
        </li>
        <li fd-menu-item>
            Option 3
        </li>
    </fd-menu-list>
</fd-menu>
```
I think there is a room for simplifying/flattening it and instead of component `fd-menu-list` we can have an attribute directive on a `<ul>` element. Especially since we do the same for `<li>` with the directive `fd-menu-list`

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7.3
fundamental-ngx 0.2.0

**Comment by bcullman** [comment]
@droshev @MattL75 depending on how this is interpreted, this, might be the necessary markup.

what you are doing in ngx will be transformed to the following semantic HTML

```
<div>
<Hx>menu title</Hx>
<ul>
<li>item</il>
<li>item</il>
<li>item</il>
</ul>
<div>
```

So, it is possible to represent that as in the following psuedo code:

```
<menu title="menu title">
<item>item</item>
<item>item</item>
<item>item</item>
</menu>
```

But it does make an **assumption** that there is a maximum of one list per title. fundamental was uncertain this assumption could be made, and erred on the side of caution., resulting in the conservative, but allowing for that scenario:

```
<Menu>
    <MenuGroup title="Group Header">
        <MenuList id="ml1">
            <MenuItem url="url" / >
            <MenuItem url="url" / >
            <MenuItem url="url" / >
        </MenuList>
        <MenuList  id="ml2">
            <MenuItem url="url" / >
            <MenuItem url="url" / >
            <MenuItem url="url" / >
        </MenuList>
    </MenuGroup>
</Menu>
```

**Comment by mikerodonnell89** [comment]
@bcullman in Matt's solution here: https://github.com/SAP/fundamental-ngx/pull/603

The markup would look like this, allowing for several menu lists in one menu group
```<fd-menu>
    <fd-menu-group>
        <h1 fd-menu-title>Menu Title</h1>
        <ul fd-menu-list>
            <li fd-menu-item>
                <a [attr.href]="'#'">Option 1</a>
            </li>
            <li fd-menu-item>
                <a [routerLink]="'#'">Option 2</a>
            </li>
            <li fd-menu-item>
                Option 3
            </li>
        </ul>
        <ul fd-menu-list>
            <li fd-menu-item>
                <a [attr.href]="'#'">Option 4</a>
            </li>
            <li fd-menu-item>
                <a [routerLink]="'#'">Option 5</a>
            </li>
            <li fd-menu-item>
                Option 6
            </li>
        </ul>
    </fd-menu-group>
</fd-menu>
```
