### ISSUE TITLE
bug (platform): do not work anchors for few components

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#5970]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Do not work anchor links for example in next components: 

- Checkbox
- Checkbox Group
- Date Picker
- DateTime Picker
- Info label
- Input
- Input Group
- Link
- List
- Standard List Item
- Action List item
- Display List item
- Object List item
- Menu Button
- Object Attribute
- Object Marker
- Radio Button Group
- Search Field (second and third anchors do not work)
- Split Menu Button
- Step input
- Panel
- TimePicker
- Dynamic Page
- Form Container
- Page Footer
- Form Generator
- Wizard Generator

#### If this is a bug, please provide steps for reproducing it.
1. Open a component page
2. Hover on any example name and on the anchor
3. Click on the anchor
Expected result: link is correct, after clicking on achor - you are directed to the right page & right example
Actual result: nothing happened, link does not work

**Comment by kavya-b** [comment]
this has already been fixed and merged in PR https://github.com/SAP/fundamental-ngx/pull/6059.  Issue #6048 was created at the time that also captured many components and the ones mentioned here are also fixed in 6059. Hence, closing this issue. 
cc: @puru-hk
