### ISSUE TITLE
Combobox defect hunting issues

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#5985]
Top 2 corners have a border radius when they should not (applies to multi-input as well):
<img width="248" alt="Screen Shot 2021-07-14 at 2 30 38 PM" src="https://user-images.githubusercontent.com/2471874/125673975-d406a580-dc0e-4918-8019-3a81d75914ff.png">

Clicking the combobox search field 'x' to clear the form erroneously opens the popover

Console error thrown and the user's first input key did not register when using custom filter or display object property

The cursor is focused back to the combobox after the user attempted to leave the input

**Comment by dimamarksman** [comment]
@mikerodonnell89 looking at fiori 3 spec we can see that combobox does have rounded corners 

![image](https://user-images.githubusercontent.com/3263744/131334909-5af4142b-752c-452b-af2b-5f6963dfaab5.png)

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89 looking at fiori 3 spec we can see that combobox does have rounded corners
> 
> ![image](https://user-images.githubusercontent.com/3263744/131334909-5af4142b-752c-452b-af2b-5f6963dfaab5.png)

Looks like you are correct, let's remove these sharp corners

**Comment by aberikashvili** [comment]
@mikerodonnell89 @dimamarksman here's the PR, which removes top sharp corners and make them round https://github.com/SAP/fundamental-styles/pull/2725

**Comment by aberikashvili** [comment]
Closing, because this issue is no more actual. 
As discussed in the above comments, according to Fiori 3 spec, dropdowns should have round corners.
Also sharp corners need to be removed from fund-styles repo and replaced with round corners, styles PR is provided  https://github.com/SAP/fundamental-styles/pull/2725
