### ISSUE TITLE
refactor side navigation api

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#599]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Side Navigation component expected markup can be simplified

**Comment by JKMarkowski** [comment]
Just FYI, I'm on it

**Comment by droshev** [comment]
@jeannewalters @LeoT7508 where can we find the latest design of the left nav?

**Comment by LeoT7508** [comment]
@droshev 

All design sheets are on Zeplin, the navigation sheet is here:
https://zpl.io/2yOJ0e9

**Comment by droshev** [comment]
consider also #347
