### ISSUE TITLE
Cannot render dynamic to render the image, title, and subtitle in the following

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#6012]
#### Is this a bug, enhancement, or feature request?
Bug/Enhancement
#### Briefly describe your proposal.
Please provide possibility to render Dynamic page in the following way

![image](https://user-images.githubusercontent.com/40032066/125961245-a3250ac7-b56d-4565-8191-bfa50ef03d20.png)

**Comment by droshev** [comment]
@MichaelBaySAP Can you share more information about the bug?

**Comment by MichaelBaySAP** [comment]
It was not possible to render the image with dynamic page in this way together with the wizard. However, it is no longer required.
