### ISSUE TITLE
Modal Improvements

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#602]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
- `modalService.open()` should accept
    - a `templateRef`  or a `component` argument. The component should be injected with an object (provider) that has `close` and `dismiss` methods.
    - a config object that overwrites the default options (backdrop, backdropClass, size)

- `modalService.open()` should return a thenable result (observable, promise, whatever)

- `dismiss` and `close` methods should have an optional result argument. When `close(result)` is called then  `modalService.open()` resolves with result. When `dismiss(result)` is called then  `modalService.open()` rejects with result. 

- `modalService` should have a `dismissAll()` method that will dismiss all currently displayed modal windows

- `modalService` should be strongly typed

- There should be an ability to disable the closing of the modal by clicking on the backdrop or by pressing the ESC key

- Modals should have a scrollable body

- There should be a full-screen modal option (size)

- There should be a configuration object token for the service that will provide default option for every modal

**Additional ACC:**

- update the alert documentation to reflect the latest API including all the Types/Classes being introduced.
- document if there are breaking changes and what the developers would need to change
- write unit tests

**Comment by maxmarkus** [comment]
Would be great, if also the constant focus could be fixed. Once you open and close a modal, the close button is focused on the next opening.

<img style="max-width: 630px" alt="screen markus e 2019-03-07 at 13 31 49" src="https://user-images.githubusercontent.com/1720843/53957257-2d64aa00-40de-11e9-9302-7308d3154414.png">

**Comment by MattL75** [comment]
@maxmarkus That's part of the focus trap, which is required for a11y. It will be optional with these new improvements, but not sure that is what you want. 

You would prefer a focus trap, but which does not initially focus the close button? Maybe focuses the modal itself without any visual cues?
