### ISSUE TITLE
Navigate Combobox with arrow keys

### ISSUE THREAD

**Issue by DamianLion** [SAP/fundamental-ngx#604]
#### Is this a bug, enhancement, or feature request?
enhancement (accessibility bug)

#### Briefly describe your proposal.
navigate in combobox with arrow keys and select with enter

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Release v0.2.0 (current version)

#### If this is a bug, please provide steps for reproducing it.
https://sap.github.io/fundamental-ngx/comboboxInput

**Comment by mikerodonnell89** [comment]
Should update the search input component, as the combobox extends the search input and both components need this functionality
