### ISSUE TITLE
extend dialog examples

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6047]
#### Is this a bug, enhancement, or feature request?
documentation enhancement

#### Briefly describe your proposal.

Create a dialog example 
- where the content can swipe between 2(or more `pages`)
- provide back button on top so it can give a cue to the user she is in a second page

**Comment by dkrishnan-01** [comment]
@droshev . here are the screens:
[Screen 1 ](https://www.figma.com/file/izfDuxvyGDWwpCsLUuoi6C/CJ-Experiences-Preview-Builder?node-id=714%3A15246)- when modal pops ups it will have content that looks like this.

[Screen 2](https://www.figma.com/file/izfDuxvyGDWwpCsLUuoi6C/CJ-Experiences-Preview-Builder?node-id=714%3A15246) - when the user clicks on a Link it will take them to the next page with a back arrow on the top left of the modal header

**Comment by droshev** [comment]
@hanjunt do you think you can explore developing those examples as part of the documentation?
