### ISSUE TITLE
Live DEMO missing

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#606]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.

**Readme.md** does not have a link to live demo anymore. It just says:
`View the live demo here.`
That takes to the git source directory instead of actuall running application. Not sure if this a bug.  Before there was a link to github pages

**Comment by MattL75** [comment]
Yeah this was an intentional change, we're now pointing to the actual code since the 'live demo' is only the ghpages site. It seemed more informational to show the code instead.

**Comment by droshev** [comment]
@MattL75 maybe we should remove that sentence from `README.md`
