### ISSUE TITLE
Stable ID's not working

### ISSUE THREAD

**Issue by kuhris** [SAP/fundamental-ngx#607]
#### Is this a bug, enhancement, or feature request?
feature request
#### Briefly describe your proposal.
I am trying to add stable ID’s to my project but they don’t seem to work with Fundamental NGX components, at least not the components that I tried: `<fd-table>` `<fd-table-header>` `<fd-table-body>`
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular: 7.3.3
fundamental-ngx: 0.1.1

**Comment by MattL75** [comment]
You're trying to set an id to a component and it's not working? As in `<fd-table id="my-id"></fd-table>`?

**Comment by kuhris** [comment]
yes, exactly

**Comment by MattL75** [comment]
I can't seem to reproduce. I'm attaching an id to a <fd-table>, <fd-table-body> and <fd-table-header> and it works as expected. Is there some specific steps you could provide to help me reproduce?

**Comment by kuhris** [comment]
Hi Matt, thanks for looking into it. All I did was add the Id and then inspect the element to make sure it was there. I also tried to locate the element on the page using an XPATH selector which kept coming back null.
This morning I tried again, and this time it is working. I’ll close the issue.
