### ISSUE TITLE
Platform table doesn't support % for column width

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6070]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
The platform table offers to set custom column width except in %. We would need to enhance and offer it as the stakeholders are still waiting for it.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx/platform 0.31

**Comment by platon-rov** [comment]
As discussed previously - implementing this feature not in a hackable way requires table component refactoring. 

So, before implementing this one we need to decide if we're going to refactor the table and implement that and other features without any hacks and hardcode and stop support IE11 for some features or we're going to work on the "IE11 first" approach.

**Comment by fkolar** [comment]
We dont have plans to support IE11. What do you mean by hacks?

**Comment by platon-rov** [comment]
We're currently using `position: absolute` for some table HTML elements and it's not correct at all. As the table column's width is calculated automatically - we're breaking it with absolute positioning. It's made like that to have a fixed header & column in the IE11 + there is a lot JS code (for the modern browsers it can be done with `position: sticky` and without any JS code).
