### ISSUE TITLE
Accessibility Testing_Checkbox_Group_Platform

### ISSUE THREAD

**Issue by lalithsagar77** [SAP/fundamental-ngx#6073]
Accessibility: Checkbox_Group-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Checkbox Group_Platform_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6868487/Checkbox.Group_Platform_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

	Navigate to Checkbox Group handling of Form Validation and Error Message Display.
Observed Behavior:
Error/Warning information ‘Value is required’ is not conveyed as highlighted, while accessing the check box.

Expected Behavior:
Ideally, error information for required field should be announced.

Screenshot: 
![image](https://user-images.githubusercontent.com/87702019/126777568-446889cc-fb0c-4674-884c-1e649c635a4f.png)

**Comment by Sanjay-1312** [comment]
Issue: 1

Issue is fixed.

Retest Details:
https://deploy-preview-6312--fundamental-ngx.netlify.app/#/platform/checkbox-group
JAWS 2021
