### ISSUE TITLE
Accessibility Testing_Fixed_Card_Layout_Core

### ISSUE THREAD

**Issue by lalithsagar77** [SAP/fundamental-ngx#6078]
Accessibility: Fixed_Card_Layout-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Fixed Card Layout_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6868627/Fixed.Card.Layout_Core_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

	Navigate to table within card ‘Table Card’.
Observed Behavior:
When user navigates into table within ‘Table Card’, it is seen that the table headers are not announced.

Expected Behavior:
Ideally, when navigating into a table, the table header should be announced.

Screenshot:
![image](https://user-images.githubusercontent.com/87702019/126780052-1db21a5f-c17a-4dca-92a9-b76be3624524.png)

 

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

	Navigate to ‘new’ button at the beginning of card with title ‘Card Title’.
Observed Behavior:
When user navigates into ‘new’ button, it is seen that the UI type for this button is not announced.

Expected Behavior:
Ideally, the UI should be announced.

Screenshot:
![image](https://user-images.githubusercontent.com/87702019/126780058-a331c192-6527-46ad-a052-cb653087dbbf.png)

**Comment by OleksiyDrozdov** [comment]
@lalithsagar77 regarding issue 2: now UI element 'New' is div, it is not a button in the code. Are you sure that UI element New we need to change to button?

**Comment by OleksiyDrozdov** [comment]
issue 1: was resolved in task https://github.com/SAP/fundamental-ngx/pull/6598
