### ISSUE TITLE
Bug: Accessibility Testing_Platform_Object Marker

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6093]
Accessibility: Object Marker-Platform Component (There are couple of accessibility issues found while testing, so I have attached error document for you reference.)
[Object Marker_Platform_Ariba controls.docx](https://github.com/SAP/fundamental-ngx/files/6876827/Object.Marker_Platform_Ariba.controls.docx)
Object Marker- Platform

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/platform/object-marker

Technology:	Angular 11
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

On navigating to ‘Default Object Marker’ section, the highlighted icons such as ‘Favorite’, ‘Flag’, ‘Edit’, ‘Locked’ are not read out in virtual pc mode.

Expected Behavior:
The icon information should be conveyed in virtual pc cursor mode.

Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126960618-72c0c1cf-a9e5-4475-af53-b838cd1e66ac.png)

 

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

On navigating to ‘Text Only Object Marker’ and ‘Icon and Text Object Marker sections, the links ‘Locked’, ‘Edit’, ‘Editable’ and ‘Locked’ are not conveyed. 
Instead of it reading is made as ‘Object Marker with only Text Clickable’.

Expected Behavior:
The name ‘Locked’, ‘Edit’, ‘Editable’, ‘Locked’ and its UI type ‘Link’ also should be conveyed.

Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126960692-e76291c9-2485-4391-8294-b8f1818b652d.png)

 

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

On accessing the 'Edit' ,'Locked' ,'Request' buttons in virtual pc mode of the screen reader, there is an additional navigation is made with no speech.

Expected Behavior:
The additional navigation should be removed when 'Edit' ,'Locked' ,'Request' buttons are accessed in virtual pc mode.

Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126960746-b5060212-4b3b-4ad7-bef3-c20b11841278.png)

 

Issue 4

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

The label ‘Draft Request’ is not getting associated when the ‘Locked’ and ‘Edit’ links are accessed.

Expected Behavior:
The label ‘Draft Request’ should get associated when the ‘Locked’ and ‘Edit’ links are accessed.
Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126960806-bb03d813-1a75-4d80-b870-d39b7927c8df.png)

**Comment by manu-kr** [comment]
Issue1 : Not valid , Those icons are not accessible or clickable so it won't read.
