### ISSUE TITLE
Bug: Accessibility Testing_Core_Object Marker

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6094]
Accessibility: Object Marker -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
[Object Marker_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6876994/Object.Marker_Core_Ariba.Controls.docx)

Object Marker- Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/object-marker

Technology:	Angular 11
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

On navigating to ‘Object Marker Only Icon Example’ section, the highlighted icons such as ‘Favorite’, ‘Flag’, ‘Edit’, ‘Locked’ are not read out in virtual pc mode.

Expected Behavior:
The icon information should be conveyed in virtual pc cursor mode.

Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126964618-bf62f662-9b18-43be-a973-630959019a09.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

The Links ‘Locked’, ‘Editable’, ‘Edit’ is not conveyed and instead of that reading is made as ‘Object Marker with Text Clickable Link’.

Expected Behavior:
The name ‘Locked’, ‘Edit’, ‘Editable’, ‘Locked’ and its UI type ‘Link’ also should be conveyed.

Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126964672-f5748862-72e0-4d5d-a2f4-348d6314bbf3.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

On accessing the 'Edit', 'Locked', 'Request' buttons in virtual pc mode of the screen reader, there is an additional navigation is made with no speech.

Expected Behavior:
The additional navigation should be removed when 'Edit', 'Locked', 'Request' buttons are accessed in virtual pc mode.

Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126964697-0b3c6314-0f0e-4169-915d-fdad58b023d2.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Object Marker’ from the left panel

Observed Behavior:

The label ‘Draft Request’ is not getting associated when the ‘Locked’ and ‘Edit’ links are accessed.

Expected Behavior:
The label ‘Draft Request’ should get associated when the ‘Locked’ and ‘Edit’ links are accessed.
Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126964732-2cabad2f-1ae3-41dc-9894-482ee73d16c9.png)

**Comment by manu-kr** [comment]
Issue1: Not valid. Those icons are not accessible or clickable , so it's not required to be read.

**Comment by manu-kr** [comment]
this issue is fixed and closing this issue.
