### ISSUE TITLE
Bug: Accessibility Testing_Core_Busy Indicator

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6095]
Accessibility: Busy Indicator-Core Component (There are couple of accessibility issues found while testing, so I have attached error document for you reference.)
[Busy Indicator_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6877032/Busy.Indicator_Core_Ariba.Controls.docx)

Busy Indicator- Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/busyIndicator

Technology:	Angular 11
Version: 	V 0.31.0-rc.125
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Busy Indicator’ from the left panel

Observed Behavior:

On accessing the ‘Default Busy indicator’, the percentage of loading is not conveyed.

Expected Behavior:
The percentage of loading information should be conveyed so that user will aware of the progress in loading.

Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126965159-79241812-4c02-493b-bd4c-302533d298a6.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Busy Indicator’ from the left panel

Observed Behavior:

When ‘focus’ is on the complete wrappers, reading is made as ‘loading’ and the labels ‘use Busy indicator as a block wrapper’ and ‘use Busy Indicator as a inline wrapper’ are not conveyed.

Expected Behavior:
All the labels should get associated with the corresponding controls when accessed.
Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126965197-f39b6772-cf52-40ae-bae0-002cf0042d3f.png)

Note: The issue 2 persists with Jaws 2019 as well.

**Comment by InnaAtanasova** [comment]
@Aswathy94 could you point out to a11y guidelines which state this:

```
Observed Behavior:
On accessing the ‘Default Busy indicator’, the percentage of loading is not conveyed.

Expected Behavior:
The percentage of loading information should be conveyed so that user will aware of the progress in loading.
```

This is a busy indicator, not a progress bar.

**Comment by InnaAtanasova** [comment]
As per [this document](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuemax_attribute)aria-valuemin and aria-valuemax are used for components are used for a range widget such as a slider, spinbutton or progressbar.

**Comment by droshev** [comment]
```
Observed Behavior:

On accessing the ‘Default Busy indicator’, the percentage of loading is not conveyed.

Expected Behavior:
The percentage of loading information should be conveyed so that user will aware of the progress in loading.
```

this can be achieved with progress indicator instead where the progress state can be determined.
