### ISSUE TITLE
Bug: Accessibility Testing_Core_Popover

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6097]
Accessibility: Popover-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Popover_Core_Ariba controls.docx](https://github.com/SAP/fundamental-ngx/files/6877089/Popover_Core_Ariba.controls.docx)

Popover- Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/popover

Technology:	Angular 11
Version: 	V 0.31.0-rc.125
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

On accessing the popovers with main heading and subheadings such as ‘Cozy Header’, the headers are not conveyed. 

Expected Behavior:
When the popovers are accessed, all the heading and subheadings should be conveyed.
Screenshot:

Case 1:
 
![image](https://user-images.githubusercontent.com/87646619/126966258-1b270c6e-e663-44fd-b7fa-34c2a017a9ed.png)

Case 2:
 
![image](https://user-images.githubusercontent.com/87646619/126966290-8fb5722a-9833-4850-a598-76299b0c0ac7.png)

Case 3:
![image](https://user-images.githubusercontent.com/87646619/126966340-cae0a07d-ca9d-4dc9-bc93-998d6a630073.png)

 
Case 4:

 
![image](https://user-images.githubusercontent.com/87646619/126966361-b682ec57-d74a-4f3e-af46-364616a60fe9.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

When the ‘back’ button within the ‘Trigger’ popover is accessed, only the UI type ‘button is conveyed.

Expected Behavior:
The name of the button ‘back’ within the popover should be conveyed.
Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126966399-a441e530-dc5f-4f40-8ec1-40541bbd386c.png)

Speech History:
![image](https://user-images.githubusercontent.com/87646619/126966424-9302da9f-486e-4763-a59a-4b8f4b7851ff.png)

 

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

When the segmented buttons within the ‘Popover CDK placement’ sections are accessed, the state ‘selected’ is not conveyed.

Expected Behavior:
The state of the button ‘selected/deselected’ should be conveyed as soon as the segmented buttons are activated.
Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126966465-3cd79c24-6de6-4bf7-b5f8-86ae60ca511a.png)

 

Issue 4

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

The labels ‘Block scroll strategy’, ‘Noop scroll strategy’, ‘Close scroll strategy’… are not conveyed when corresponding popovers are accessed.

Expected Behavior:
All the labels should be conveyed when the corresponding popovers are accessed.

Screenshot:
![image](https://user-images.githubusercontent.com/87646619/126966499-42886a6a-8923-4176-98fd-e3238b0c9b00.png)

 

Issue 5

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

The information about the ‘subNames’ are not conveyed when the ‘Names’ list are expanded.

Expected Behavior:
Information about the subNames should be conveyed when names are expanded.

Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126966540-6e9618b3-617d-404e-88f9-e58350c8da86.png)

Issue 6

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

The popover title ‘Mobile Popover’ is not conveyed as soon as it opened.

Expected Behavior:
The popover title ‘Mobile Popover’ should be conveyed as soon as it opens.
Screenshot:

![image](https://user-images.githubusercontent.com/87646619/126966584-64d060ca-8945-4c0a-a57c-7e145616a506.png)

 

Issue 7

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Popover’ from the left panel

Observed Behavior:

The color indication ‘Success’, ‘Alert’ is not conveyed when the buttons ‘Accept’ and ‘Decline’ within the ‘Mobile popover’ is accessed.

Expected Behavior:

The color indication ‘Success’, ‘Alert’ should be conveyed when the buttons ‘Accept’ and ‘Decline’ within the ‘Mobile popover’ is accessed.
Screenshot:

 
![image](https://user-images.githubusercontent.com/87646619/126966630-90162dfd-8732-456a-9f10-bf0674d6510a.png)

**Comment by puru-hk** [comment]
ssue 1: Fixed

Issue 2: Fixed

Issue 3: Fixed

Issue 4: Not fixed
Observed: On accessing the buttons, the button name is read first followed by the labels.
Expected: The label should be read first followed by the button name

<img width="1277" alt="Screenshot 2021-09-27 at 17 07 20" src="https://user-images.githubusercontent.com/32538291/134900889-5b9b3449-f0f8-4da6-bb2e-3aafb2a731dd.png">

Issue 5: Fixed

Issue 6: Not fixed.
Observed: The header ‘Mobile Popover’ is not read and the dialog is read twice to the user and the focus should be available on the ‘Count Click’ input which is first interactive element in the list

Expected: The Dialog name ‘Mobile Popover’ and dialog should be announced once and the focus should be available on the first interactive element in the dialog.

<img width="1277" alt="Screenshot 2021-09-27 at 17 08 12" src="https://user-images.githubusercontent.com/32538291/134900980-7ac25372-1ff6-4d44-945a-2b4dcb84c730.png">

Issue 7: Fixed

**Comment by george861** [comment]
Hi Colleagues,

Above mentioned issue no 4 and 6 is fixed.

Retest Details:
JAWS 2021.2107.12 ILM

Thanks & Regards
George
