### ISSUE TITLE
Bug: Accessibility Testing_Core_Icon

### ISSUE THREAD

**Issue by Aswathy94** [SAP/fundamental-ngx#6102]
Accessibility: Icon-Core Component (There are couple of accessibility issues found while testing, so I have attached error document for you reference.)
[Icon_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6880739/Icon_Core_Ariba.Controls.docx)

Icon- Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/icon

Technology:	Angular 11
Version: 	V 0.31.0-rc.125
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Icon’ from the left panel

Observed Behavior:

On accessing the icons in virtual pc mode of the screen reader, the name of the icons is continuously read out.

Expected Behavior:
The icon should be read out one by one when accessed in virtual pc cursor mode.

Screenshot 1:

 
![image](https://user-images.githubusercontent.com/87646619/127048466-844aa839-e32c-4927-81f0-8331108ce07c.png)

Screenshot 2:

 

![image](https://user-images.githubusercontent.com/87646619/127048477-606b5ce3-0087-4d05-869f-47a2800c2b66.png)

**Comment by kavya-b** [comment]
closing this issue in favour of #6195 which reports the same issue along with another one.
