### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined at MultiInputComponent_ng_template_6_ul_0_li_1_Template

### ISSUE THREAD

**Issue by aleksabajric** [SAP/fundamental-ngx#6108]
#### **Is this a bug, enhancement, or feature request**?
Bug

#### **Briefly describe your proposal**.
Since I added a multi-input component I occur an error message in the console. Everything works fine just that message appears.
<img width="350" alt="Screenshot 2021-07-27 at 09 38 24" src="https://user-images.githubusercontent.com/36825811/127115258-3a5ba533-b521-4a31-a496-b34471f749c1.png">

#### **Which versions of Angular and Fundamental Library for Angular are affected**? (If this is a feature request, use the current version.)
Angular version is 10 and fundamental is ^0.30.0

**Comment by droshev** [comment]
@aleksabajric version `0.30` is compiled with angular 11( [wiki](https://github.com/SAP/fundamental-ngx/wiki#angular-version-support)). If you are running application with angular 10 then the latest version of fundamental-ngx is `0.28`
