### ISSUE TITLE
bug(platform): Wizard Generator Tooltip “Object object” is shown when hovering over an input field

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#6111]
Wizard Generator: Tooltip “Object object” is shown when hovering over an input field

**Comment by droshev** [comment]
@MichaelBaySAP Can you add more context and maybe the data you are passing to?

**Comment by MichaelBaySAP** [comment]
It happens for any input

**Comment by MichaelBaySAP** [comment]
so just render an input in the wizard

**Comment by MichaelBaySAP** [comment]
v0.31.0

**Comment by MichaelBaySAP** [comment]
Unfortunately, I am unable to record the bug because the tooltip only appear for 0.5sec but Deniz Severin knows how the bug looks like
