### ISSUE TITLE
Enhancement: Allow increasing the wizard data by dynamically cloning/adding controls during wizard flow

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#6125]
An example, for how a design using this would look like can be found below.
![image](https://user-images.githubusercontent.com/40032066/127477754-ecf5b8d1-2e16-4a1e-845a-58b43433915c.png)

**Comment by droshev** [comment]
This can be done with a custom component. This component could be a wrapper for the repetitive components.
