### ISSUE TITLE
Enhancement: Allow customizing the wizard review data

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#6126]
As a developer, I would like more options to choose what will be displayed in the wizard review, not always having to rely on a label to be utilized to present this information. It would be better, if there existed a template to represent the following wizard controls in the following way in the review:
https://github.com/SAP/fundamental-ngx/issues/6125
![image](https://user-images.githubusercontent.com/40032066/127478154-c929f820-3c90-4181-9a7c-e8dd51d05365.png)

**Comment by droshev** [comment]
@N1XUS how does the wizard generator summary page work for custom components?

**Comment by N1XUS** [comment]
This behavior can be achieved with custom summary page and custom value renderer.
