### ISSUE TITLE
introduce collapse/expand in the doc pages + multi-file support

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#613]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Add button Expand/Collapse button for the code snippet examples.

We should also be able to select between files that are part of the example. Whoever takes this could talk with jeanne for ideas on the design.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
angular 7
fundamental-ngx 0.2.0

**Comment by MattL75** [comment]
If you're doing this you could also maybe introduce some tabs to switch between the different files that are relevant to an example

**Comment by droshev** [comment]
@MattL75 this is a good idea but would require a separate discussion.

**Comment by MattL75** [comment]
@droshev Sure, but I don't think this issue's pr should be merged without having the discussion and implementing something for it first. We'll end up with some really clunky documentation otherwise. I prefer having all examples expanded for now
