### ISSUE TITLE
wizard in a dialog summary page should be shown as the last step

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6132]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] At the moment the summary page in the wizard(full screen and in a dialog) is displayed as overlay of the wizard steps. The dialog one requires the summary page to be displayed as a last step instead.
- [ ] Make sure to check the platform wizard generator and that the fix works well with the generator

3d

**Comment by N1XUS** [comment]
* Summary step should be configurable by the end-user to apply title, id, condition on when to show the step in progress bar (for branching wizard scenario)
