### ISSUE TITLE
Accessibility Testing_Checkbox_Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6135]
Accessibility: Checkbox-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Checkbox.docx](https://github.com/SAP/fundamental-ngx/files/6904955/Checkbox.docx)

**Comment by DeepakSap14** [comment]
@puru-hk 
can you check issue 1, issue 2 and issue 3.
These does not seem valid.
for issue 3, i am getting correct color contrast.

It is Non-text, so `AA` value should be applied.

<img width="482" alt="Screenshot 2021-08-18 at 10 14 44 AM" src="https://user-images.githubusercontent.com/57661487/129838812-733a1431-e7f0-4af6-a023-ca7874973a52.png">

**Comment by puru-hk** [comment]
Tested in the real device both (Mobile and iPad) issue 1 and 2 is working fine. @DeepakSap14 ignore these 2 issues

**Comment by Sanjay-1312** [comment]
Issue 3:
The  'Mandatory' symbol suffice the color contrast ratio of 4.5:1.
