### ISSUE TITLE
 Accessibility Testing_ Platform_Info Label

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6136]
Accessibility: Info_Label-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Info.docx](https://github.com/SAP/fundamental-ngx/files/6904961/Info.docx)

**Comment by puru-hk** [comment]
All these issues are not valid. Kindly close this issue

**Comment by manjunathanagaraj** [comment]
closing this, as per above comments.
