### ISSUE TITLE
Accessibilty Testing_Time_Picker_Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6142]
Accessibility: Time Picker-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:
[Time_Picker.docx](https://github.com/SAP/fundamental-ngx/files/6905164/Time_Picker.docx)

**Comment by Karthickc1994** [comment]
Hello Colleague,

Retest has been taken below are the test results.

Issue1: Fixed.
Issue2: Fixed.
Issue3: Fixed.

Retest Environment:
URL: https://fundamental-ngx-gh--pr8087-ds-6142-time-picker-f2eo8ijc.web.app/
Browser: Chrome: Version 102.0.5005.63 (Official Build) (64-bit)
Screen Reader: JAWS 2022.2204.20 ILM

Regards,
Karthikeyan.c
