### ISSUE TITLE
Accessibility Testing_Platform-Button_Split

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6144]
Accessibility: Button_Split-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screenshot:

[Split.docx](https://github.com/SAP/fundamental-ngx/files/7290706/Split.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On accessing the ‘Option1’ button, additional information about Split-button is read.
Expected Behavior:
Ideally, only relevant visible information should be read such additional information should be removed.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/136138035-b119d3dd-86d8-42cc-bdb6-d5667d157e81.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264
(264.1)

Observed Behavior:
Ton accessing the ‘More’ button, its associated label ‘Default Behavior’ should be read.
Expected Behavior:
Ideally, the corresponding label must be read out, when each & every UI is accessed.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/136138119-7eecdfa0-1fad-4eec-95ee-3efd68814308.png)

Issue 3

Priority:	High
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On activating any of the list item from the ‘More’ menu button, additional information is conveyed.
Expected Behavior:
Ideally, only relevant and visible information about the UI should be read out and such extra information should be removed.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/136138158-7b5f6d7c-8fd4-4f33-b2a3-4e12c3fc7751.png)

IIssue 4

Priority:	Medium
Checkpoint:	ACC-283

(283.1)

Observed Behavior:
On accessing the ‘Positive’, ‘Standard’, ‘Negative’ and ‘Ghost’ button’, additional information is conveyed.
Expected Behavior:
Ideally, only relevant and visible information about the UI should be read out and such extra information should be removed.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/136138212-18eeb448-bd2d-4a6a-8f2d-2e04aa1d0202.png)

![image](https://user-images.githubusercontent.com/78714518/136138222-0b40375e-0bd1-4b4e-926b-e1102a1cd50d.png)

![image](https://user-images.githubusercontent.com/78714518/136138235-f8b8e2f4-8074-4c95-b407-e8be4416c321.png)

Issue 5

Priority:	Medium
Checkpoint:	ACC-260

(260.4)

Observed Behavior:
On resizing the screen to 200% zoom, the horizontal scroll bar is available.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
In 200% zoom
![image](https://user-images.githubusercontent.com/78714518/136138333-dc8a198e-eec8-4022-ab73-4fea5be310f7.png)
In 100%zoom
![image](https://user-images.githubusercontent.com/78714518/136138355-4865dd0f-c221-4dfc-8377-5d85107685d2.png)

Issue 6

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On accessing the Cozy Split menu button and Compact split menu button its associated label is not read.
Expected Behavior:
Ideally, when every UI is accessed its associated label should be read.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/136138428-a627c0c5-42db-4f56-8f6b-ddb23397b5f2.png)

Issue 7

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On adapting the screen to text spacing the labels are truncated.
Expected Behavior:
On resizing the screen to different zoom, the data within the screen shouldn’t be truncated 

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/136138535-5f577016-6216-49ca-9dee-953c8048747d.png)

**Comment by kavya-b** [comment]
@Sanjay-1312 no attachment here
