### ISSUE TITLE
Accessibility Testing_Platform_Date_picker

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6146]
Accessibility: Date_picker -Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screenshot:

**Comment by kavya-b** [comment]
@Sanjay-1312 no attachment here

**Comment by dmitry-stepanenko** [comment]
@Sanjay-1312 can you add an attachment? Or should we close the ticket?
