### ISSUE TITLE
Accessibility Testing_ File Uploader

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6147]
Accessibility: File Uploader-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screensht:
[File uploaders (1).docx](https://github.com/SAP/fundamental-ngx/files/7234903/File.uploaders.1.docx)

**Comment by kavya-b** [comment]
@Sanjay-1312 no attachment here

**Comment by manu-kr** [comment]
@Sanjay-1312 Please attach the document.
