### ISSUE TITLE
Accessibility Testing_Link_Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6148]
Accessibility: Link-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screenshot:
[Link_Platform.docx](https://github.com/SAP/fundamental-ngx/files/7370052/Link_Platform.docx)

**Comment by kavya-b** [comment]
@Sanjay-1312 no attachment here
