### ISSUE TITLE
Accessibility Testing _Platform_Switch

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6153]
Accessibility: Switch-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screenshot:
[Switch.docx](https://github.com/SAP/fundamental-ngx/files/6916595/Switch.docx)

 Issue 1

Priority:	Medium
Checkpoint:	ACC-260

(260.4)

Observed Behavior:
On resizing the screen o 200% zoom, the horizontal scroll bar is available and the texts  are truncated.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
Case 1
![image](https://user-images.githubusercontent.com/78714518/127857428-de032c23-9e0e-40eb-b972-21f7677f4a9e.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-260
(260.4)

Observed Behavior
On resizing the screen to 320 pixels CSS, the horizontal scroll bar is available.
Expected Behavior:
The screen layout must be scaled so that there is no loss of either content, affordance, or function.

Screenshot:
![image](https://user-images.githubusercontent.com/78714518/127857504-8cc63410-f4aa-4b01-b9cf-3ae8874c2615.png)

**Comment by kavya-b** [comment]
@puru-hk please check this issue on a mobile device, for horizontal scroll bar issues in documentation pages, I think we had agreed to verify on mobile device if horizontal scroll bar is present.

**Comment by puru-hk** [comment]
Verified in the Samsung S10 Plus device horizontal scroll bar is not coming. Hence this issue can be closed.

**Comment by Sanjay-1312** [comment]
Issue fixed
