### ISSUE TITLE
Accessibility Testing _Radio button_Platform

### ISSUE THREAD

**Issue by Sanjay-1312** [SAP/fundamental-ngx#6165]
Accessibility: Radio button-Platform Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) 
Screenshot:
[Radio Button Group.docx](https://github.com/SAP/fundamental-ngx/files/6953215/Radio.Button.Group.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

Observed Behavior:
On activating the ‘Reset’ button, the information about ‘Reset is done confirmation message is not read.
Expected Behavior:
Ideally, user should be able to know the ‘Reset’ has done and should be conveyed to the user.
Screenshot:
![image](https://user-images.githubusercontent.com/78714518/128683690-6e48d845-dacf-4c73-b9ff-39edeca48f52.png)
![image](https://user-images.githubusercontent.com/78714518/128683720-f5c8acb5-fedc-4c45-a71b-5072a89c94d3.png)
![image](https://user-images.githubusercontent.com/78714518/128683733-b2bb20a0-5315-4d6a-be42-3ff5278c0e7b.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264
(264.1)

Observed Behavior:
On accessing the radio button the navigation information is read first and then the UI name.
Expected Behavior:
Ideally, the UI name should be read and followed by the navigation information.
Screenshot:
![image](https://user-images.githubusercontent.com/78714518/128683794-ace64c77-01a3-4ef1-9bc2-4c02ef91e08c.png)

Note : This issue persists throughout the application

**Comment by DeepakSap14** [comment]
@puru-hk @Sanjay-1312 , missing attachment here.

**Comment by Betrozov** [comment]
I can not reproduce the 2d issue

**Comment by puru-hk** [comment]
Issue 1: Not fixed 

Observed: On activating the ‘Reset’ button, additional information such as available in the dialog is read and the confirmation information is not read.
<img width="1277" alt="Screenshot 2021-09-28 at 09 17 15" src="https://user-images.githubusercontent.com/32538291/135020164-8eccb406-ca0c-4513-a7c6-bfa73e72ef37.png">

Expected: The information about ‘Reset was successful’ should be read and the additional information should be removed.

Issue 2: Not fixed

<img width="1277" alt="Screenshot 2021-09-28 at 09 18 47" src="https://user-images.githubusercontent.com/32538291/135020283-e1e6461d-9c7c-41b4-b7ab-eb4e8f20d7eb.png">

Observed: the same issue persists
