### ISSUE TITLE
Accessibility Testing - Panel - Core

### ISSUE THREAD

**Issue by george861** [SAP/fundamental-ngx#6176]
Accessibility: Panel -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)
Screenshot:
[Panel_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6917790/Panel_Core_Ariba.Controls.docx)

Panel - Core

1.1	Message Details

Raise Ticket	

Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/panel

Technology:	Angular 11
Web browser:	Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	High
Checkpoint:	ACC-270 , ACC-264

(270.5)(264.1)

•	Search ‘Panel’ from the left panel
Observed behavior:
Case 1:
The textual header ‘Panel Header’ is included in navigation order.
Case 2:
On accessing the textual header 'Panel header' , an additional information 'contains text' is announced.
Speech output:
Panel Header
Contains text

Expected Behavior:    
The textual header ‘Panel Header’ should not be included in navigation order as it’s a non-interactive element and only relevant and meaningful information should be announced.
NOTE: the issue persists in all panels  
Screenshot:  
![image](https://user-images.githubusercontent.com/88019003/127781668-bd0f26e0-d7e1-47e5-8552-07140d374c77.png)

Issue 2

Priority:	High
Checkpoint:	ACC-270

(270.5)

•	Search ‘Panel’ from the left panel

Observed Behavior:
The textual content information ‘Lorem ipsum’ within the panel header is also included in the navigation order

Expected Behavior:
The textual contents should not be included in navigation order as it’s a non-interactive element.
NOTE: the issue persists in all panels  
Screenshot:
![image](https://user-images.githubusercontent.com/88019003/127781678-2cf15946-6eab-4898-abf7-95a86f84ad4b.png)

 

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Panel’ from the left panel

Observed Behavior:

On accessing the expand button with the expandable panel, the associated header ‘Panel Header’ is not announced. 

Expected Behavior:
On accessing the expand button with the expandable panel, the associated header ‘Panel Header’ should be announced. 
NOTE: the issue persists in all panels  
Screenshot:

 
![image](https://user-images.githubusercontent.com/88019003/127781684-ceb66a12-260d-4787-bf2b-b780406fc68e.png)

**Comment by Sanjay-1312** [comment]
Issue 1 : Fixed
Issue 2: Fixed
Issue 3: 
![image](https://user-images.githubusercontent.com/78714518/129531935-6f9b5c0c-9aef-470c-a678-9c351bab0c6b.png)

OB: On accessing the "Expand and Collapse' button of Panel header tooltip information is read.
EB: On accessing the button Panel header collapsed and Expanded state should be read and tooltip information should be removed.

**Comment by kavya-b** [comment]
@Sanjay-1312 
Issue 3: `Panel Expand` is the title and also the aria-label. Currently the button's description(or aria-label) is not read, only the associated header's text(`Panel Header`) is read. The button should have read `Panel Header Panel Expand Button collapsed` which is the corresponding header's text(`Panel Header`), the button's aria-label(`Panel Expand`), `button` and the state(`collapsed`), respectively.

I'll make the changes to read as `Panel Header Panel Expand Button collapsed`  as described above. 
Hope that is okay.
