### ISSUE TITLE
Accessibilty Testing - Core - Time Picker

### ISSUE THREAD

**Issue by george861** [SAP/fundamental-ngx#6182]
Accessibility: Time Picker -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Time Picker _Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6915104/Time.Picker._Core_Ariba.Controls.docx)

Time Picker - Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/object-marker

Technology:	Angular 11
Web browser:	Google Chrome 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Time Picker’ from the left panel

Observed Behavior:
Case 1
No information is conveyed about the accessed list box ‘Hrs’, ‘Mins’ and ‘Period’  and upon changing the value within the hours , minutes and period, no information is conveyed about changing values.
Case 2
The values within the ‘Hrs’,’Mins’ and ‘Period’ can be changed via up and down arrow keys, no information is conveyed about this behavior to the user.
Case 3
No information is conveyed as the user can navigate from the list ‘hours’ to ‘Mins’ or from ‘Mins’ to ‘period’ via (Left and Right) arrow keys 
Speech:
Decrease hours Button  
To activate press spacebar.

Expected Behavior:
The information should be conveyed about the accessed list box ‘Hrs’, ‘Mins’ and ‘Period’ and upon changing the time in ‘Hours’, in ‘Minutes’ and in Seconds, the information should be conveyed about changing values.
The information should be conveyed as the user navigates from the list ‘hours’ to ‘Mins’ or from ‘Mins’ to ‘Sec’ via (Left and Right) arrow keys. 

NOTE: the issues persists in all similar UI elements ‘Time Picker’

Screenshot:
 
![image](https://user-images.githubusercontent.com/88019003/127782570-61ee2daa-08c5-4b46-b5b8-0f4d6025da02.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-255

(255.1)

•	Search ‘Time Picker’ from the left panel
Observed behavior:
Case 1
No text alternative or tooltip provided for the button within the time picker input.
Case 2
No tooltip or text alternative provided for the ‘Increase’ and ‘Decrease’ buttons    

Expected Behavior:  
Case 1
 Appropriate text alternative or tooltip provided for the button within the time picker input.
Case 2
Appropriate text alternative should be provided for the buttons ‘Increase’ and ‘Decrease’.

NOTE: the issues persists in all similar UI elements. hence, should be rectified for all the occurrences.

Screenshot:
case 1
![image](https://user-images.githubusercontent.com/88019003/127820893-10bb5245-cefd-439a-bf81-e4fac297edb6.png)

 
![image](https://user-images.githubusercontent.com/88019003/127820936-95fa0c88-5094-4a61-97cd-492060b516f7.png)

Case 2
 
![image](https://user-images.githubusercontent.com/88019003/127820984-79dbfb59-fa3d-46c6-829c-4489be334401.png)

![image](https://user-images.githubusercontent.com/88019003/127820996-52635922-a11d-4805-99c8-366f3cbe40dd.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Time Picker’ from the left panel
Observed behavior:
On accessing the time picker input, an additional ‘\’ backslash information is conveyed and the error information ‘invalid time’ is not announced.
Speech:
Time picker input Edit  Required  
hh\:mm am/pm
Type in text.
Expected Behavior:    
On accessing the time picker input, No additional ‘\’ backslash information should be conveyed and the error information ‘invalid time’ should also be announced.

Screenshot 1 

![image](https://user-images.githubusercontent.com/88019003/127782579-90958be0-5a9e-4f90-a856-977164c8230d.png)

 

Issue 4

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Time Picker’ from the left panel
Observed behavior:
On accessing list box ‘en-US’, the item ‘en- US’ information is not conveyed 
Speech:
Select an option List box  collapsed    Has Popup  
To move to an item press the Arrow keys.
Expected Behavior:    
On accessing list box ‘en-US’, the item ‘en- US’ information should be announced.
Screenshot 1 

![image](https://user-images.githubusercontent.com/88019003/127782583-cb3c6785-218f-4ed0-9e14-b6bd7f7393f4.png)

**Comment by dimamarksman** [comment]
@george861 Hi!
The issue with a backslash is the JAWS issue and nor connected to the ngx component itself.
This issue can be reproduced on any input with aria-label defined. Please check [this example](https://jsfiddle.net/dimamarksman/muezbqya/18/)

**Comment by dimamarksman** [comment]
Can not reproduce issue 4.
`en-US` information is pronounced
![image](https://user-images.githubusercontent.com/3263744/144411430-3f2d0798-5154-4ccf-877c-5dd4d5aceb02.png)
