### ISSUE TITLE
Accessibility testing - Core - Rating Indicator

### ISSUE THREAD

**Issue by george861** [SAP/fundamental-ngx#6183]
Accessibility: Rating Indicator -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Rating Indicator_Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6913240/Rating.Indicator_Core_Ariba.Controls.docx)
Rating Indicator - Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/panel

Technology:	Angular 11
Web browser:	Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Rating Indicator’ from the left panel
Observed behavior:
On accessing the rating indicator, the UI type is announced as a radio button and an additional count information such as ‘5 of 215’ is also announced 

Speech:
4-star radio button  checked  
5 of 215
To change the selection press Up or Down Arrow.
3-star radio button  checked  
4 of 215
To change the selection press Up or Down Arrow.

Expected Behavior:  
On accessing the rating indicator, the UI type should be announced correctly and without any additional information.
  
NOTE: the issue persists for all the similar UI elements.

Screenshot 1 
 
![image](https://user-images.githubusercontent.com/88019003/127782692-255a3bde-bfba-497d-a319-20eeccd10830.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Rating Indicator’ from the left panel

Observed Behavior:
Case 1
On accessing the rating indicator custom icons, the UI element type is announced as a radio button with a count information such as ’59 of 215’.
Case 2
Visually, it is observed that each star indicator can be selected or unselected partially on navigating within the indicators and no information is conveyed about the partial star selection as it conveys for example 5 star , 6 star as its being selected completely even when its visually perceived as ‘3.5’ , ‘4.5’.
Expected Behavior:
On accessing the custom icons rating indicator, the information should be conveyed as each star indicator is selected or unselected partially on navigating within the indicators and the state of each star.  
The same information should be conveyed to the screen reader users which is visually perceived by a non-screen reader user.  
NOTE: the issue persists for all the similar UI elements.

Screenshot:
 
![image](https://user-images.githubusercontent.com/88019003/127782698-08d1ecea-ae04-4424-bf55-0e674fe233e4.png)

Case 2
 
![image](https://user-images.githubusercontent.com/88019003/127782700-230b24f4-7fd9-423c-871d-b85b5c83e387.png)

**Comment by puru-hk** [comment]
Issue 1: Fixed
Issue 2: Fixed

Issue 3: Not Fixed

Observed: There is no keyboard Support provided for the ‘Rating Indicators’.

<img width="1277" alt="Screenshot 2021-09-28 at 09 22 14" src="https://user-images.githubusercontent.com/32538291/135020559-d91737dd-d609-4aa6-86c5-ab8303512ad4.png">
Expected: Ideally, the keyboard support should be provided for the rating indicator.

**Comment by Sanjay-1312** [comment]
Hello Colleagues,

![image](https://user-images.githubusercontent.com/78714518/136012705-138cf7a1-c93a-451a-bf0d-dc227adab405.png)

OB: There is no visible focus provided for the Rating Indicator.
EB: Ideally, visible focus should be provided to the user to identify where the UI elements is available.
