### ISSUE TITLE
Accessibility Testing - Core - Split Button

### ISSUE THREAD

**Issue by george861** [SAP/fundamental-ngx#6185]
Accessibility: Split Button -Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.)

[Split Button Core_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6913253/Split.Button.Core_Ariba.Controls.docx)

Split Button - Core

1.1	Message Details

Raise Ticket	
Category	
Preprocessed By	
Description	

1.2 Application & Test Environment Details

Application Name:	ARIBA Controls- Fundamental Library for Angular
URL:	https://fundamental-ngx.netlify.app/#/core/panel

Technology:	Angular 11
Web browser:	Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Operating System:	Microsoft Windows 10 x64
Screen Reader:	JAWS 2021.2105.53 ILM

 

Issue 1

Priority:	Medium
Checkpoint:	ACC-255

(255.1)

•	Search ‘Split Button’ from the left panel
Observed behavior:
No tooltip or text alternative is provided for the ‘more’ buttons.
Expected Behavior:  
Appropriate tooltip or text alternative should be provided for the ‘More’ buttons.
Screenshot 1 

 
![image](https://user-images.githubusercontent.com/88019003/127782834-50b68516-8357-4516-b0a9-c6de33a695e6.png)

Case 2
 
![image](https://user-images.githubusercontent.com/88019003/127782837-c70f990f-948e-4051-94b4-60da31d4bb35.png)

NOTE: the issue persists in all similar split buttons

Issue 2

Priority:	High
Checkpoint:	ACC-264

(264.1)

•	Search ‘Split Button’ from the left panel

Observed Behavior:
On accessing the items such as ‘option 1’ and ‘option 2’ within the list, the item count information is not announced. 
Speech:
menu  
Option 1 
To move through items press up or down arrow.
Option 2

Expected Behavior:
On accessing the items such as ‘option 1’ and ‘option 2’ within the list, the item count information should be announced. 
Screenshot:
 
![image](https://user-images.githubusercontent.com/88019003/127782840-add7ee5f-8b56-48bf-9f6d-707c4b6e0699.png)

NOTE: the issue persists in all similar split buttons

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

(264.1)

•	Search ‘Split Button’ from the left panel
Observed behavior:
On accessing the different types of split buttons such as ‘emphasized’, ‘ghost’, ‘positive’, ‘negative’, no information is conveyed about the different UI type. All the split buttons are conveyed as same.

Speech:
button-split group  Has Popup  
Option 1 Button  
To activate press spacebar.
More Button  
To activate press spacebar.

Expected Behavior:    
On accessing the different types of split buttons such as ‘Emphasized’, ‘Ghost’, ‘Positive’, ‘Negative’, ‘Attention’ and ‘Transparent’, the UI type information should be announced to the screen reader user.
Screenshot 1 
![image](https://user-images.githubusercontent.com/88019003/127782845-1a775579-59d9-459f-bfdb-a277408ad896.png)

**Comment by dimamarksman** [comment]
@george861 `Ghost` and `Transparent` don't convey any sufficient info to the user.
As for me only `'emphasized', 'positive', 'negative' and 'attention'` convey some usful context for the user
