### ISSUE TITLE
Bug: Footer on message box dialog is not consistent

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#6202]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Footer on message box dialog is not consistent, sometimes footer button is cozy, sometimes compact. Per Visual Core, Cozy button is designated for Tablet and Mobile Devices.
![image](https://user-images.githubusercontent.com/71797052/127943270-01c71324-e543-4265-bfaf-5400aa49a0f5.png)

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/message-box
Scroll down and compare the footers on Object based message box and Template based dialog box

**Comment by droshev** [comment]
Hello,

There is no problem with the footer here as you can put any template and if the template has elements that are not with the same density you can see that.

I saw a different issue though - that the footer in message box doesn't not consider the density service setting (e.g. when we set the value to Cozy the footer is still compact - first example)

**Comment by pierrom** [comment]
Thank you @droshev. I will close this issue. Will you follow up with the issue that you brought up regarding density service setting? Thanks again.
