### ISSUE TITLE
Feed List Item: Avatar shape

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#6204]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Small change:
Recently, Fiori changed the shape of the avatar from rectangle to circle.

NGX:
![Screen Shot 2021-08-02 at 6 43 58 PM](https://user-images.githubusercontent.com/72403541/127944621-952d97b7-c96b-424d-8224-ae225f34a8dc.png)

Fiori:
Ref link: https://ux.wdf.sap.corp/fiori-design-web/feedinput/
![Screen Shot 2021-08-02 at 6 45 08 PM](https://user-images.githubusercontent.com/72403541/127944660-8e8d92ec-7f6c-40fc-a986-a1a376a6c78b.png)

**Comment by puru-hk** [comment]
I check in fiori3 visual spec this is not an issues. As per the fiori3 visual spec we have implemented. Please find the below url fyi..
https://wiki.wdf.sap.corp/wiki/display/visualcore/Feed+%28Fiori+3%29+-+FeedListItem
https://wiki.wdf.sap.corp/wiki/display/visualcore/Feed+%28Fiori+3%29+-+FeedInput

**Comment by puru-hk** [comment]
we will wait for updated fiori3 visual spec. Therefore we mark it as design discrepancy.

**Comment by kavya-b** [comment]
@daisy-yovcheva it is not quite clear from the visual spec when the avatar should have a circle shape and when it should have a rectangular shape. 
avatar spec shows both variations:
![image](https://user-images.githubusercontent.com/53509521/133597066-1a9b16ed-db99-4b66-a4bb-2067b1de7b0d.png)
and so does feed input spec:
![image](https://user-images.githubusercontent.com/53509521/133597202-2f7b24a4-4a6e-4148-a928-055a47ec702d.png)

are there specific rules on when an avatar should be a circle or a rectangle?

Please note we do have a property in ngx-avatar component called `circle` which when set gives the circular shape; you can see it [here](https://fundamental-ngx.netlify.app/#/core/avatar#circle). However, currently there is no property available for the user to specify the shape of the avatar in platform feed input.
