### ISSUE TITLE
Accessibility_Testing_Info Label_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6207]
Accessibility: Info Label-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:
[Info Label_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6920637/Info.Label_Core_ARIBA.Controls.docx)

Issue 1

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
UI type “info label” is not read. Only visible text ‘info label’ is read out. 

The speech output is:

INFO LABEL

INFO LABEL

Expected Behavior:
Ideally, each & every UI should be read out based upon its type when accessed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127948294-cf33d87f-6797-4150-bdd6-cf040117fd0f.png)

Issue 2

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
There are 2-tab stops provided when info labels are accessed. One for icon and one for info label.  

The speech output is:

INFO LABEL

INFO LABEL

Expected Behavior:
Ideally, only one-tab stop should be provided for one info label.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127948324-9925507a-13c0-4b67-a761-1f3bc116c5a2.png)

Issue 3

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
There is only one-tab stop provided for 3 info labels, where 3 info labels are read out altogether.  

The speech output is:
642K14.7

Expected Behavior:
Ideally, 3-tab stops should be provided for 3 info labels. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127948346-8a19dd9e-6a01-4643-93cc-84573709889a.png)

**Comment by InnaAtanasova** [comment]
@Wemitha1234  please specify what do you mean by "UI type “info label” is not read. Only visible text ‘info label’ is read out." My default macos screen reader is reading each Info Label 3 times. It reads:
"Info Label group info label group info label"
