### ISSUE TITLE
Accessibility_Testing_Action Sheet_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6211]
Accessibility: Action Sheet-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Action Sheet_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6920971/Action.Sheet_Core_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for the button. 

The speech output is:
Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each & every non-text UI element.   

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127956394-4efb9058-1e3b-4bb4-bfeb-da82b7cc42b3.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Item count is not read when menu items accessed. 

The speech output is:
menu  
Search 
To move through items press up or down arrow.
Download 
Accept 
Reject 
Decide Later

Expected Behavior:
Ideally, item count should be read out when menu items are accessed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127956417-c4a7555e-4721-4c6d-824a-be338f7fb832.png)

Issue 3

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
When menu items are pressed, notification message appears, which is not read out immediately. 

The speech output is:
Leaving menus
Fundamental Library for Angular

Expected Behavior:
Ideally, notification messages which appears should be read out immediately.  

Screenshot 1:

![image](https://user-images.githubusercontent.com/88035260/127956444-c658dafb-6848-4b91-83f8-fa28643649f7.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/88035260/127956449-15d7aad8-e5e2-411b-b06e-eaa35078afc5.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-273

Observed Behavior:

After pressing escape key, menu items will close but the focus is lost. 
On tabbing, focus is found here on the expand/collapse button on the top left.  

Expected Behavior:
Ideally, after closing menu items, focus should not be lost. Focus should stay on the same UI.  

Screenshot 1:
![image](https://user-images.githubusercontent.com/88035260/127956484-c9175f50-cc3c-4f3c-85c8-f44370fe780f.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/88035260/127956496-9c3ff896-4633-4281-bc32-f95845ea604f.png)

Issue 5

Priority:	Medium
Checkpoint:	ACC-270

Observed Behavior:
Case 1
In forward navigation, ‘Download’ and ‘Reject’ buttons are not reachable via arrow keys. 
In tab key, all buttons are reachable.  

The speech output is:
menu  
Search 
To move through items press up or down arrow.
Accept 
Decide Later 
Cancel

Screenshot 1: Case 1
![image](https://user-images.githubusercontent.com/88035260/127956530-810fd908-fdd8-43db-ade5-5809829335e1.png)

Case 2
In backward navigation, ‘Accept’ and ‘Decide later’ are not reachable via arrow keys. 
In tab key, all buttons are reachable. 

The speech output is:
Cancel 
Reject 
Download 
Search
Screenshot 2: Case 2
![image](https://user-images.githubusercontent.com/88035260/127956557-20758f1b-fd29-4cca-8fb3-d4c97b1e5fb4.png)

Expected Behavior:
Ideally, all buttons should be reachable using arrow keys. 

Issue 6

Priority:	Medium
Checkpoint:	ACC-270

Observed Behavior:
On opening menu, the initial focus is not found on the first menu item. 
On tabbing focus will come to the first menu. 

Expected Behavior:
Ideally, on opening the menu, initial focus should come to the first menu item. 
Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127956597-65cb9314-28e2-414d-8ac4-df0ad4ce89cc.png)

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Issue1: Fixed
Issue2: Fixed
Issue3: Fixed
Issue4: Fixed
Issue5: Fixed
Issue6: Fixed.

Retest Environment:
URL: https://deploy-preview-7390--fundamental-ngx.netlify.app/assets/typedoc/core/classes/actionsheetitemcomponent
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: Jaws2021.2111.13ILM


Regards,
Karthikeyan.c

**Comment by Veerakarthick** [comment]
Hello Colleague,

Retest has been taken below are the details.

Issue1: Fixed
Issue2: Fixed
Issue3: Fixed
Issue4: Fixed
Issue5: Fixed
Issue6:Fixed.

Retest Environment:
URL: https://deploy-preview-7390--fundamental-ngx.netlify.app/assets/typedoc/core/classes/actionsheetitemcomponent
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Screen reader: Jaws2021.2111.13ILM


Regards,
Karthikeyan.c
