### ISSUE TITLE
Accessibility_Testing_Alert_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6212]
Accessibility: Alert-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Alert_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6921411/Alert_Core_ARIBA.Controls.docx)

Issue 1

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
Alert message is not read when Dismiss button is accessed. 

The speech output is:
Dismiss Button  
To activate press spacebar.
Dismiss Button  
To activate press spacebar.
Dismiss Button  
To activate press spacebar.

Expected Behavior:
Ideally, Alert message should be conveyed when Dismiss button is accessed.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127966271-6720b395-fa37-437a-9cbe-3ff16f321e17.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for the Dismiss buttons. 

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each & every non-text UI element.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127966300-2a83fed9-1941-450c-80c9-eee8dbfc78fc.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Separate tab stops are provided for icon and Alert message when accessed in virtual pc mode. 
When icons are accessed in virtual pc mode, there is no speech output. 

Expected Behavior:
Ideally, information about icons should be conveyed to the user. 

Screenshot 1:
![image](https://user-images.githubusercontent.com/88035260/127966318-4cdb03f8-3fdf-4783-8a31-5d70c2866dd9.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-270

Observed Behavior:
The ‘Dismiss’ button and ‘Click to dismiss’ button within Alert message is not reachable using keyboard. 

Expected Behavior:
Ideally, each & every UI should be reachable using keyboard.   

Screenshot 1:
![image](https://user-images.githubusercontent.com/88035260/127966352-8a4716f1-4f88-47ac-9e0e-58a8513eaff5.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/88035260/127966358-4c1ec56f-3b83-4034-8126-dac2941149b6.png)

Issue 5

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Emphasized information about ‘Dismiss All’ button is not read out. 

The speech output is:
Dismiss All Button  
To activate press spacebar.

Expected Behavior:
Ideally, emphasized information about UI should be conveyed. 

Screenshot 1: Case 1
![image](https://user-images.githubusercontent.com/88035260/127966409-b2abfc63-eead-4bb7-9fa0-bf024beb57a1.png)

Issue 6

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
When open dynamic alert button is pressed, Alert message appears, which is not read immediately. 

The speech output is:
Open Dynamic Alert Button  
To activate press spacebar.

Expected Behavior:
Ideally, Alert message should be conveyed immediately.  

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127966435-fae38b2b-13ea-493b-818a-2f392576dc3e.png)

**Comment by Lokanathan-k** [comment]
low Priority will be taken up later

**Comment by Betrozov** [comment]
This issue was discussed with @InnaAtanasova.
We came to the conclusion that since the Alert component is deprecated the issue won't be fixed as it will be removed in the future.

cc: @manjunathanagaraj   @nickiovenko
