### ISSUE TITLE
Accessibility_Testing_Checkbox_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6213]
Accessibility: Checkbox-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Checkbox_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6921455/Checkbox_Core_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Extra information “required” is read out when ‘Option 1’ checkbox is accessed. 
Visually the UI is not marked as required.  

Speech output is:
Option 1 check box  checked  Required  
To clear checkmark press Spacebar.
not checked  Required 
Expected Behavior:
Ideally, only relevant information about UI should be conveyed.   

Screenshot:
 
![image](https://user-images.githubusercontent.com/88035260/127967055-028043d2-4700-4db6-99b3-25d6004baa50.png)

**Comment by Sanjay-1312** [comment]
Issue: Issue fixed

Retest Details:
https://github.com/SAP/fundamental-ngx/issues/6213
JAWS 2021
