### ISSUE TITLE
Modal improvements

### ISSUE THREAD

**Issue by aartek** [SAP/fundamental-ngx#622]
Hello
I'm using fundamental-ngx 0.2.0 and I have few issues:
- when modal is open, it's still possible to focus elements outside modal using tab/shift+tab
- `role="dialog"` is missing

To consider:
- modal could be closed on ESC key press. Of course I can implement it on my side, but maybe at least there could be an option to enable it with some configuration property. After close, focus should be restored to the invoking element. 
  - I can implement ESC support, but I cannot implement restoring focus when `X` button is clicked, because there is no "after close" callback or something similar.

**Comment by MattL75** [comment]
Hi @aartek ! Thanks for raising an issue.

This is solved by #616 which will be a part of the next release (0.3). It should be out relatively soon.

**Comment by MattL75** [comment]
Closing this since for now we discussed this
