### ISSUE TITLE
Accessibility_Testing_Input Group_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6220]
Accessibility: Input Group-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Input Group_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6922804/Input.Group_Core_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for Add to Cart Button. 

Speech output is:
Add to Cart Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127986775-a7fdc9b1-e782-421d-bce9-d4eb2fc603aa.png)

Issue 2

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Information highlighted in red within Input Group is not read out when accessed. 

Speech output is:
Information Edit  
Placeholder
Type in text.

Expected Behavior:
Ideally, information about each & every UI should be conveyed.   

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127986822-809167c3-19f1-4ca1-9946-35892709fea6.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for Calendar Button. 

Speech output is:
Calendar Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for each UI. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127986873-1df3f9d9-1a5c-448d-9a96-ae4a62b2c204.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for Clear Button. 

Speech output is:
Clear Button  
To activate press spacebar.

Screenshot:

![image](https://user-images.githubusercontent.com/88035260/127986918-7f16bd23-e8c5-4134-b08a-3036571e2b1f.png)

**Comment by puru-hk** [comment]
All issues are fixed.
