### ISSUE TITLE
Accessibility_Testing_List with Byline_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6223]
Accessibility: List with Byline-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[List with Byline_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6923223/List.with.Byline_Core_ARIBA.Controls.docx)

Issue 1

Priority:	High
Checkpoint:	ACC-264

Observed Behavior:
Selected state is not read when list items are accessed. 

Speech output is:
list  
with 4 items
Title Byline Text   
1 of 4
To move to an item press the Arrow keys.
Title Byline Text   
2 of 4
To move to an item press the Arrow keys.
Title Byline Text   
3 of 4
To move to an item press the Arrow keys.
Title Byline Text   
4 of 4
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, the selected state should be read out when list items are accessed. 

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127997589-48b623e1-5d20-49b0-866c-09ba03933c3c.png)

Issue 2

Priority:	High
Checkpoint:	ACC-255

Observed Behavior:
Text alternative defining the purpose of UI is not provided for the buttons within list.  

Speech output is:

list  
with 2 items
Title Byline Text   
1 of 2
To move to an item press the Arrow keys.
Button  
To activate press spacebar.
Button  
To activate press spacebar.

Expected Behavior:
Ideally, text alternative describing the purpose of UI should be provided for non-text UI.

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127997622-2e00255b-3f73-43f7-aace-b653172c2d81.png)

Issue 3

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
“Has details” information about list items is not read when accessed. 

Speech output is:
List item with no byline   
2 of 3
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, has details information about list items should be conveyed to the user.   

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127997659-54fcfe1a-c943-4f37-8068-9e28435ce039.png)

Issue 4

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Blue color information about list items is not read when accessed. 

Speech output is:
List item with no byline   
2 of 3
To move to an item press the Arrow keys.

Expected Behavior:
Ideally, color information about list items should be conveyed to the user.   

Screenshot:
![image](https://user-images.githubusercontent.com/88035260/127997687-f83c99c1-d605-4822-99ff-46d8bb27b972.png)

**Comment by Lokanathan-k** [comment]
Issue 1: issue with JAWS application (https://github.com/FreedomScientific/VFO-standards-support/issues/440)
Issue 2: FIxed 
Issue 3: fixed
Issue 4: its a single colour not required to read because and it doesn't represent any status.

**Comment by puru-hk** [comment]
Issue 1: As per the comment in ticket
Issue 2: Fixed
Issue 3: Not fixed.
Issue 4: As per the comment in ticket    
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/32538291/133963492-f4936907-b422-46bd-9038-fafa55b7542d.png)
