### ISSUE TITLE
bug (core): Submenu doesn't close when hovering on a non-submenu item

### ISSUE THREAD

**Issue by aflalves** [SAP/fundamental-ngx#6229]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Submenu doesn't close when hovering on a non-submenu item

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current

#### If this is a bug, please provide steps for reproducing it.
On the menu demo, add a normal menu item to the "menu-with-submenu-example.component".

https://user-images.githubusercontent.com/6796342/128146467-090d0c97-b692-4ca7-86ab-80a924c1eddb.mov

**Comment by platon-rov** [comment]
not reproducible.
