### ISSUE TITLE
bug (platfrom): error message box is getting cut at bottom. <p> tag should not be inside fdp-form-field element

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6232]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
`<p>` tag should not be inside fdp-form-field element.
because of this, error was hidden.

If `<p>` tag is removed error message is getting cut at bottom.

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/128164666-7a1dbc17-b790-4b12-8749-de27c363a25e.png)

**Comment by kavya-b** [comment]
@maxym-valor could you provide more info with reproduction steps? On latest netlify([multicombobox with reactive form example](https://fundamental-ngx.netlify.app/#/platform/multi-combobox)), I don't see the error message getting cut or hidden.
![image](https://user-images.githubusercontent.com/53509521/128866610-de943019-9664-44dc-926f-22f0f834885d.png)

**Comment by maxym-valor** [comment]
@kavya-b Hello, Kavya. @DeepakSap14 connected it with PR 6039 and already merged it

**Comment by kavya-b** [comment]
@maxym-valor oh, then @DeepakSap14 can you close this and assign it to yourself? :)

**Comment by DeepakSap14** [comment]
![multi-combobox](https://user-images.githubusercontent.com/57661487/132028544-27932c3c-8226-40b8-9f09-77f1ef6de26d.gif)

@kavya-b 
issue is not fixed.
connected PR is where, issue was first identified.
defect can still be reproduced.
