### ISSUE TITLE
bug (platform): does not visible error message near input when you hover 

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6233]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Component: input
if input has error and highlited - error message does not visible when you hover on input.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/input#reactive
2. Enter and clear value to get error message
3. Remove focus from input
4. Hover on the input
Expected result: error message displayed
Actual result: error message is not displayed

**Comment by Betrozov** [comment]
Hi @maxym-valor 

Please look at this one, here described how it should work.
https://experience.sap.com/fiori-design-web/input-field/#value-state-and-value-state-message

If we look at it then we will see that we have the same behaviors.
https://sapui5.hana.ondemand.com/#/entity/sap.m.Input/sample/sap.m.sample.InputValueState
