### ISSUE TITLE
Platform wizard generator - after navigating back to the steps from summary, "Next step" button functionality broken

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#6235]
After navigating to the summary page in the platform wizard generator, and going back to a step with the "Edit" link, the "Next Step" button at the bottom of the page simply takes you to the next step after whichever one you clicked to "Edit", and it should be taking you to the summary page.

**Comment by maxym-valor** [comment]
Not reproducible anymore
