### ISSUE TITLE
Enhancement: Allow editing the width of input and editor fields

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#6247]
currently, if I want to change width of an input, I have to create a custom element with an input, put a css class into the custom element and change the width there. It would be great if there existed a custom property to change the width

**Comment by platon-rov** [comment]
It also seems hard to change the width of the input-based components like `combobox` or so where we don't have access to the input element directly and cannot assign class, so it only can be done using `::ng-deep` and by overwriting ngx classes styles.

**Comment by MichaelBaySAP** [comment]
Alright, I will checkout ng deep, the next time I have such a problem.
