### ISSUE TITLE
Bug(core, platform): Accessibility requirements for table

### ISSUE THREAD

**Issue by dksanket** [SAP/fundamental-ngx#6258]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1. Table's contents should be accessible using arrow keys. 
2. Currently if there are multiple rows and columns in a table, if user clicks on tab from any cell, the focus moves to next row same column, instead it should move to same row next column.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.31.0-rc.87 , Angular 10

**Comment by manjunathanagaraj** [comment]
@platon-rov , please check if you have already addressed this for platform table. If yes, please can you link the related PR?

@droshev , please can you assign a team member for having a look at core table?

**Comment by platon-rov** [comment]
@manjunathanagaraj pull request #5692 will fix a11y for the platform table.

But about the core table - should the arrow navigation also be provided there? 

Firstly I got a task about implementing arrow navigation for the platform table component so I have done it but if that feature also should be provided for the core implementation could be different to support core & table at once.
