### ISSUE TITLE
Pagination component renders double link

### ISSUE THREAD

**Issue by marynaKhromova** [SAP/fundamental-ngx#626]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

`fd-pagination` component renders double link. For every page item there is a link that includes another link. Both have the same class `fd-pagination__link`. Also there is no cursor pointer when hover the page link. 

Compared to [Fiori Fundamentals](https://sap.github.io/fundamental/components/pagination.html) , links are not doubled and have a cursor pointer on hover there.

<img width="1381" alt="pagination bug" src="https://user-images.githubusercontent.com/46446373/54359286-a033cf00-4662-11e9-832b-e9d83ce84f33.png">

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

current

**Comment by MattL75** [comment]
@mikerodonnell89 Maybe fix that as part of #623 ?

**Comment by MattL75** [comment]
#623
