### ISSUE TITLE
bug: datetime picker and date picker (platform|core) - can input invalid birthday

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#6278]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
can input invalid calendar birthday

#### If this is a bug, please provide steps for reproducing it.
**STR**
- go to date picker OR datetime picker
- look at birthday field
- type in 'tesrtjghghjk 1990'

**actual results:** calendar date considered valid
**Expected results:** calendar date should have error validation for improper format
for: date picker and datetime picker on core and platform

![2021-08-16](https://user-images.githubusercontent.com/47522152/129540807-746739c2-92e4-4f59-9d47-e4fe070cf329.png)

NOTE: reproduced on form generator 
![2021-08-09_7](https://user-images.githubusercontent.com/47522152/128708114-a421e93b-ad6f-4cfb-8beb-960207042be1.png)

![2021-08-09_9](https://user-images.githubusercontent.com/47522152/128708583-9fbf6154-fb0e-46a6-a419-5a461626b81c.png)

![2021-08-09_8](https://user-images.githubusercontent.com/47522152/128708289-87735511-8c63-4caa-94d3-61da8a02cbdb.png)

relates to: #6277

**Comment by Betrozov** [comment]
@Seamoo13 
this issue I can reproduce here `platform/date-picker`,  `core/date-picker`, `core/datetime-picker` and here `platform/datetime-picker`
could you confirm it, please?

**Comment by Seamoo13** [comment]
> @Seamoo13
> this issue I can reproduce here `platform/date-picker`, `core/date-picker`, `core/datetime-picker` and here `platform/datetime-picker`
> could you confirm it, please?

@Betrozov 
verified issue reproduced in all mentioned components

**Comment by dimamarksman** [comment]
In order to validate date input properly it's needed to use moment adapter instead of fdDatetimeAdapter

**Comment by dimamarksman** [comment]
@Seamoo13 since all these date/time components rely on FdDatetimeAdapter (which relies on native Date.parse() implementation) I wouldn't it consider as a bug cause Date.parse does not guarantee correct parsing except ISO format

**Comment by dimamarksman** [comment]
[Moment date adapter](https://sap.github.io/fundamental-ngx/#/core/moment-datetime-adapter) is based on moment.js and can parse entered string with respect to the given format

**Comment by Seamoo13** [comment]
per @dimamarksman comments, not a bug.
