### ISSUE TITLE
bug wizard generator (platform): scrolling to the steps issue

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6281]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Wizard Generator.
1) When you are on the step 2 or higher and you click on the icon of the 1'st step - you will be directed to there abruptly with a jerk. But when you click on another step icon (2,3,4) - you will be scrolled to there smoothly.
2) Sometimes scrolling works abruptly with a jerk.

If these 2 issue is not connected - please let me know and i'll devide into 2 different issues
#### Is there anything else we should know?
![Запись_экрана_2021-08-09_в_16 14 56](https://user-images.githubusercontent.com/83698366/128712338-0fed14cb-11a7-462a-a53e-06b987e2d10d.gif)
![Запись_экрана_2021-08-09_в_16 53 23](https://user-images.githubusercontent.com/83698366/128717678-cafbc04e-d0c8-4223-b915-b65da2be935e.gif)

**Comment by Betrozov** [comment]
@maxym-valor I cannot reproduce this issue, please check it again
if you can reproduce it, could you provide more details please?

**Comment by maxym-valor** [comment]
Lol, not reproducible anymore
