### ISSUE TITLE
Defect Hunting for Sprint 68 - Popover

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#6287]
#### Issue 1

* [x] While specifying popover position in the RTL mode it keeps its position while the glyph on the button is updated. It confuses in which direction popover should open.

##### LTR

![image](https://user-images.githubusercontent.com/20265336/128739952-1f0e6e04-5ea6-4bc4-9046-f768eb397b2c.png)

##### RTL

![image](https://user-images.githubusercontent.com/20265336/128740016-8c1af41b-c19b-40e1-b968-7189d4c361fe.png)

#### Issue 2

* [x] Dynamic Body Height hasn't rounded corners.

![image](https://user-images.githubusercontent.com/20265336/128741909-023a8331-c78a-4538-a2c5-a3cd5f4f5870.png)

#### Issue 3

* [x] Popover with Reposition Scroll Strategy is buggy (blinks while scrolling).

#### Issue 4 (Internet Explorer)

* [ ] Popover wrong borders

![2021-08-09 21 02 44](https://user-images.githubusercontent.com/20265336/128745342-3f7ec16b-e067-4add-ab70-920f5bf1a241.jpg)
![2021-08-09 21 02 38](https://user-images.githubusercontent.com/20265336/128745345-ba0cbd39-df0c-4ecd-a983-23cbe0d0cb7b.jpg)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.31.0-rc.180

#### If this is a bug, please provide steps for reproducing it.

Go to the https://fundamental-ngx.netlify.app/#/core/popover

**Comment by genereg1** [comment]
`Issue 4` won't fix since we don't support IE11
