### ISSUE TITLE
Wizard generator branching example - cannot progress past step 1

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#6295]
In the wizard generator branching example, I cannot select an item from the dropdown, preventing me from progressing past step 1.

**Comment by Betrozov** [comment]
Hi @mikerodonnell89 
I can not reproduce this issue
Could you please check it and if it is not reproducible please close this issue or add more info about how to reproduce it
Thanks

**Comment by mikerodonnell89** [comment]
Can no longer recreate, closing
