### ISSUE TITLE
bug: Date-time-picker(core): different values for calendar for 'ar' format for FF and other browsers

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6304]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In i18n example if you choose 'ar' format - it will have another look in FF and other browsers
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/datetime-picker#complex-i18n in FF and Chome e.g.
2. In dropdown select 'ar' point
3. Compare view in FF and Chrome
Expected: calendars value are equal
Actual: values are different
#### Is there anything else we should know?
How it looks in FF:
![image](https://user-images.githubusercontent.com/83698366/129045943-463b3258-891c-4cf2-9edd-c33d3559e91a.png)
How it looks in any other browsers: 
![image](https://user-images.githubusercontent.com/83698366/129046325-e16a7637-aa14-46b0-99a8-b6969898bc16.png)

**Comment by nikvalor** [comment]
Fixed
