### ISSUE TITLE
bug(core): avatar group class assigning

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#6316]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

Fix Avatar Group CSS class assigning.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest.

#### If this is a bug, please provide steps for reproducing it.

Unit tests will fail with Ivy disabled for the `AvatarGroupComponent`.

**Comment by manu-kr** [comment]
Closing this bug as fixed after NG12 update.
