### ISSUE TITLE
Modal is not properly rendered for long underlaying content.

### ISSUE THREAD

**Issue by aartek** [SAP/fundamental-ngx#632]
Hi, I have a view with a long list of users and I noticed that on iphone, modal is displayed outside the view area. It's rendered in the middle of the screen, but scrolling is blocked so I cannot reach it. (Tested on 0.3.0-rc7)

![IMG_552F0AF1B0FF-1](https://user-images.githubusercontent.com/5053151/54526830-4855da80-4978-11e9-8301-df6743336f2b.jpeg)

You can also reproduce it in chrome's developer console:
<img width="517" alt="Zrzut ekranu 2019-03-18 o 12 22 36" src="https://user-images.githubusercontent.com/5053151/54527026-ecd81c80-4978-11e9-8243-128d7e9cd30c.png">

**Comment by MattL75** [comment]
The modal is appended to the body so this should not happen. It also doesn't occur in the documentation, even if the content is long. Is there some more details I'm missing for this situation? Could you post more info please?

**Comment by aartek** [comment]
Sidebar and toolbar are not covered with a backdrop, because they're a part of the main frame. View covered with a backdrop is in the child iframe.

**Comment by aartek** [comment]
Sorry, It's a problem on our side. 

One thing to consider as a modal feature is to let users decide about modal position with some configuration property.
