### ISSUE TITLE
bug: textarea (platform): in 'Textarea with message counter' pressing on backspace removing part of the string

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6321]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In 'Textarea with message counter' pressing on backspace once for second field - removing part of the string instead one symbol
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/textarea#counter
2. Focus on second field
3. Press on Backspace
Expected result: one symbol is removed
Actual result: part of the string is removed
#### Is there anything else we should know?
![Запись_экрана_2021-08-12_в_17 37 29](https://user-images.githubusercontent.com/83698366/129216918-0221462c-fa14-4b92-a937-0c62a89a7a06.gif)

**Comment by droshev** [comment]
@maxym-valor - this is desired behavior: 'Start entering. Counter message will not be shown, but if an initial value is set whose length > maxLength, excess text is removed on Backpress'
I think the documentation needs to improved by explaining more about that feature

**Comment by kavya-b** [comment]
The placeholder actually explains the behaviour, but yes, since value is already set, the information isn't evident; so the documentation can definitely be improved here.
![image](https://user-images.githubusercontent.com/53509521/129323605-df90bce7-877a-42f7-a3f0-381a909ad912.png)
