### ISSUE TITLE
Implement Responsive Splitter component 

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#6326]
Link to the visual specs: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2221292146

**Comment by fkolar** [comment]
I would not probably link internal documents as not all can access them ;-) You can link definitely Design from gitbook

**Comment by InnaAtanasova** [comment]
> I would not probably link internal documents as not all can access them ;-) You can link definitely Design from gitbook

That's the idea :) These are internal links and not everyone should access them. The people assigned to these issues have access to them.
