### ISSUE TITLE
Review Installation Guide

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6336]
#### Is this a bug, enhancement, or feature request?
documentation

#### Briefly describe your proposal.
review the content of [wiki](https://github.com/SAP/fundamental-ngx/wiki/Full-Installation-Guide)
add also examples with platform package
include examples with the moment adapter

**Comment by hanjunt** [comment]
Hi Deno @droshev, I updated the installation guide at https://github.com/SAP/fundamental-ngx/wiki/Full-Installation-Guide
-specified npm version
-removed unnecessary command to install fundamental-styles
-added installation guide for platform package
