### ISSUE TITLE
bug(core): inline help disappears when hovering over focused trigger

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#6398]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

Inline help disappears when hovering over-focused trigger.

https://user-images.githubusercontent.com/20265336/131117033-d1fd0d82-613c-41b8-b765-9e0a1b92b46b.mov

#### If this is a bug, please provide steps for reproducing it.

Go to https://fundamental-ngx.netlify.app/#/core/inline-help#styled
Hover over the trigger - inline help appears
Focus (click, tab) trigger, hover over it - inline help disappears

**Comment by migg24** [comment]
Same issue exists with `fd-popover` when you are using `[triggers]="['mouseenter', 'mouseleave']"`.
