### ISSUE TITLE
bug(platform): checkbox without label wrong focus styles on RTL

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#6402]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

Checkbox without label wrong focus styles on RTL.

![image](https://user-images.githubusercontent.com/20265336/131129343-a54d2ff8-83ee-48f3-b806-6cd64cea7a24.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest.

#### If this is a bug, please provide steps for reproducing it.

Go to https://fundamental-ngx.netlify.app/#/platform/checkbox#a11y

**Comment by platon-rov** [comment]
Seems to be fixed, maybe because of Fund Styles version bump.

**Comment by Seamoo13** [comment]
issue resolved
