### ISSUE TITLE
bug(core): Open issues on date-/datetime-/time-picker

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#6428]
#### Is this a bug, enhancement, or feature request?
Mainly bugs

#### Briefly describe your proposal.
There are some new issues on Date-, Time- and DateTime-Picker. To demonstrate the issues I created an stackblitz example with more details and demo-fields: https://stackblitz.com/edit/fundamental-issue-6428

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Fundamental-ngx: 0.31.0. You can see the other deps on stackblitz

#### If this is a bug, please provide steps for reproducing it.
Checkout the above mentioned example in stackblitz

#### Please provide relevant source code if applicable.
Checkout the above mentioned example in stackblitz

**Comment by maxym-valor** [comment]
@zaheral  Please, indicate is that bug on core or platfrom, or both? Also pls add needed labels and update the name of the issue

**Comment by zaheral** [comment]
> @zaheral Please, indicate is that bug on core or platfrom, or both? Also pls add needed labels and update the name of the issue

@maxym-valor It seems that you have already done the points, thanks. The labels are also correct, it is about the core library and it is mainly about bugs.
BTW. I'm not able to modify the labels by myself. Not sure if I'm missing here some permissions or it is intended that none-fundamental members are not allowed to do it.

**Comment by g-cheishvili** [comment]
Tested them out. All of the issues are fixed.
Used fundamental-ngx@0.33.5-rc.50 and angular 12

**Comment by zaheral** [comment]
Hi @g-cheishvili and @droshev,

I tested the open issues on the latest stable fundamental-ngx v0.33.6 and Angular 13. One of the issues are fixed and one looks better. But the rest is still there.
I have created a second stackblitz project with the same code, but with the current stable dependencies:https://stackblitz.com/edit/fundamental-issue-6428-2?file=src/app/date-picker-single-example.component.html

Please have a look on them and open the issue again, because I'm not able to.

BR, Zaher

**Comment by g-cheishvili** [comment]
https://stackblitz.com/edit/fundamental-issue-6428-2-hshneq?devToolsHeight=33&file=src/app/date-picker-single-example.component.ts

This is a version in which 2nd is fixed. Time picker fix will come shortly.

Regarding 3rd: I'll investigate that
