### ISSUE TITLE
bug (platfrom & core) fd-combobox is not ADA compliant

### ISSUE THREAD

**Issue by Peeeeeeter** [SAP/fundamental-ngx#6433]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
For fd-combobox, when user is on focus of the input box, pressing Arrow Down key should open the dropdown.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
N/A
#### If this is a bug, please provide steps for reproducing it.
1. Open combobox on core or platform
2. Focus on input box
3. press Arrow Down
Expected: dropdown is opened
Actual: drop down is not opened
#### Please provide relevant source code if applicable.
fd-combobox

**Comment by Betrozov** [comment]
Hi @Peeeeeeter.
Could you help me to find docs where this behavior is described?
I didn't find any mention of this behavior in [Fiori Design Guidelines](https://experience.sap.com/fiori-design-web/combo-box/)
Also if compare our Combobox with the [SAPUI5 Combobox](https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox) we will see that they have equal behavior.

**Comment by Betrozov** [comment]
Hi @puru-hk
Could you verify it, please?

**Comment by Peeeeeeter** [comment]
Hi @Betrozov,

The Guidelines you linked I don't see info about Accessibility requirement.

I don't know if It is specifically defined somewhere, but it is an issue reported during the Accessibility testing that our app where using fundamental components doesn't return expected result.
This combobox is an example, using arrow down key to expand the dropdown list is expected to be a common behavior, as in google search portal:https://www.google.com

Also I noted that, this component lack the accessbility support to **browse** the dropdown list by using only keyboard interactions.(if the arrow down key works, this isn't a problem).
But per the ACC standard, all interactive UI component that can be triggered by mouse click, like buttons, should have keyboard bindings. In this case, the browsing button(Arrow-down icon) should have keyboard interaction, it needs to be focusable, and on focus should read precisely.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/11143509/135924487-6190a620-6199-4efa-aa0b-87b82d178e55.png">

Some reference:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

https://wiki.wdf.sap.corp/wiki/display/Acc/Expected+AT+Behaviour+for+Fiori+and+UI5+Components

https://wiki.wdf.sap.corp/wiki/display/Acc/SAP+Accessibility+Standard

**Comment by puru-hk** [comment]
@Peeeeeeter I check with the SAP Accessibility standard. Dropdown will work only with Alt+down arrow key. It will not work only down arrow key. Please the below explanation from the SAP Accessibility standard.

Test ACC-270.6: Can every interactive UI element be used from the keyboard, mouse, or touch (such as lists, option fields, or checkboxes)?

Follow the test case.
For each focused UI element
check out how the focused UI element is being operated by keyboard (you may need to read documentation or find out the operating system's behavior)
find out which functions are available if you use the mouse pointer or touch screen gestures or vice versa.
make use of keyboard keystrokes to operate the UI element using the keyboard, such as:
use SPACE or ENTER to trigger an element or select or unselect an item.
use arrow keys to navigate focus or text cursor within a UI element
use context menu key or Shift+F10 to open a menu, which shows according actions to the focused element/item.
use **Alt+Down or the F4 key to open a value help dialog**
check that all functions which the mouse/touch input provides is also available by using keyboard shortcuts/keystrokes.
check the focused element's type (control role) and check the keyboard specification to verify consistency 

This is not a bug

**Comment by Peeeeeeter** [comment]
@puru-hk  I don't think this is not an issue, maybe it is not a bug, but this is an issue that directly reported from customer, it is not something bad to have and it is easy to do so in the library. Customer requested and expected such behavior in our application and it is just not mentioned in the SAP standard, while the same behavior is observed in all other accessibility supported web applications while using JAWS.
