### ISSUE TITLE
bug(platform): split-menu with not fixed width does not work correctly

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6446]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Explanation to split-menu button in example: `fixedWidth=false:`. But if you add long string in this button - it will be cut and showed with 3 dots at the end.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.32.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/split-menu-button#behaviors
2. Click on third split-menu button
3. Inspect third button
4. In DOM tree add long string in this button
Expected result: button changes his width according to string length
Actual result: the string is cut and displayed with 3 dots at the end
#### Is there anything else we should know?
We can see that maximum width is fixed to 12 rem
![image](https://user-images.githubusercontent.com/83698366/131984792-8a91362c-5a26-411d-bce0-cc2428b3a24e.png)
![image](https://user-images.githubusercontent.com/83698366/131985517-25d20795-8970-4c50-b67b-1ccd2b793157.png)

**Comment by Betrozov** [comment]
Discussed this issue with @maxym-valor, came to the conclusion that this is not the issue and can be closed
