### ISSUE TITLE
scrolling in fd-panel-body max-height not working

### ISSUE THREAD

**Issue by kclercR310** [SAP/fundamental-ngx#645]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
If you have a fd-panel with fd-panel-body, it's somehow not possible to only scroll in the fd-panel-body.

if you set max-height: 100% the fd-panel-body still gets bigger than it's parent.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
fdx: 1.4.3
angular: 7.2.0

**Comment by MattL75** [comment]
For a relative max-height property to be applied to the child, an explicit height has to be given to the parent. See [this stackoverflow answer](https://stackoverflow.com/a/14263416). Let me know if you're already doing that, and if so please provide a bit of sample code so I can dig a bit deeper :)
