### ISSUE TITLE
Bug: Split Button dropdown selection missing selected state

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#6451]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="281" alt="Button with Flexible Width" src="https://user-images.githubusercontent.com/71797052/132066981-d3a82303-b162-40f4-a0a4-5a9a5c334bab.png">
<img width="737" alt="Option 1" src="https://user-images.githubusercontent.com/71797052/132066996-e1c8f015-5346-46cd-8701-8d8646bccdf3.png">
<img width="271" alt="Selected State in Dropdown List" src="https://user-images.githubusercontent.com/71797052/132067006-0c7cc7fb-506b-4d90-a9a1-8abe48679b9e.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.32.0

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/split-button
Check the behavior of all button dropdown on all the button types

**Comment by puru-hk** [comment]
This is also persist in core split button
