### ISSUE TITLE
Bug: Dynamic Page Nav/Global Actions on top Toolbar s/b same line at width greater than 1280px

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#6452]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Nav and Global Actions on top Toolbar should be same line at width greater than 1280px. See Quicktime attached.
<img width="892" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/71797052/132075670-16e583ef-52f8-42d1-a470-b4285e1fd282.png">
https://user-images.githubusercontent.com/71797052/132075580-182daeec-dcf6-4759-865b-1977cfd032b6.mov

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/dynamic-page
Click on Basic dynamic Page and Dynamic Page with Tabs

**Comment by puru-hk** [comment]
This is not an issue. Because this an example other examples autoResponsive is 'true"

**Comment by pierrom** [comment]
Closed. Used as an example only.
