### ISSUE TITLE
Requested changes to Combo box

### ISSUE THREAD

**Issue by kuhris** [SAP/fundamental-ngx#646]
#### Is this a bug, enhancement, or feature request?
1 enhancement, 2 bugs in the `<fd-combobox-input>`

#### Briefly describe your proposal.
We are using `<fd-combobox-input>` and want the user to only be able to select the options that we provide. Currently the combobox allows the user to add a new item to the list, which we don't want. Would it be possible to make it an option whether to allow adding new items?

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
version 0.2.0

#### If this is a bug, please provide steps for reproducing it.
1) After selecting a combobox item, the combobox remains open until you click again outside of it.
2) When disabling the combobox, the input portion becomes disabled but the dropdown button remains enabled.

**Comment by MattL75** [comment]
@kuhris At the moment, a combobox without an option to add an item is basically a search input. Is there a reason why you are not using that component instead?

**Comment by kuhris** [comment]
Hi @MattL75 . As a work around we converted to <fd-search-input> but there were still some issues. One tester wrote:
- select the first, it auto-closes properly
- try to select different, only the selected is shown (needs manual removal of input)
- after manual delete, the list is there again. but any of the values you had selected before, is not selectable again
- only solution - manually typing in the value

We are looking for something similar to this: https://sap.github.io/ui5-webcomponents/playground/components/Select/

Where clicking the dropdown presents the users with a list. Not allowing them to add, or type anything in themselves.

Would this be something that we could achieve via settings?

**Comment by MattL75** [comment]
We also have a dropdown component, is there a reason you are sticking to search input and combobox input?

Our dropdown is more of a pattern of our popover component, but support is there. https://sap.github.io/fundamental-ngx/dropdown

@droshev Think it's worth it for us to have an actual dropdown component? Demand is there for it, even if it's just a pattern for something.

**Comment by MattL75** [comment]
Closing for housekeeping. Feel free to re-open it if something comes up.
