### ISSUE TITLE
Project Overview Cards Loading Indicator shown on Browser Resize

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6484]
#### Is this a bug, enhancement, or feature request?
dxp #562 and #707

- [ ] investigate, analyze and estimate
- [ ] tbd break down in tasks

**Comment by platon-rov** [comment]
#562
Assigned on Denis Severin.

#707
Issue in the ngx: https://github.com/SAP/fundamental-ngx/issues/5511, assigned on Oleksiy Drozdov.
