### ISSUE TITLE
Product menu should render also without submenu

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#649]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

Currently when you try to render product menu it requires to have menu items otherwise
it does not look good its still active and when you hover over you see this triangle without the submenu over lay. 

It should be possible to render this

```
<fd-product-menu [control]="productMenuControl">

````
instead of

```
<fd-product-menu [control]="productMenuControl" [items]="productMenuItems">
```

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
```
Angular CLI: 7.3.1
Node: 10.9.0
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.29.0

```

#### If this is a bug, please provide steps for reproducing it.

Use fd-product-menu without the items bindings

#### Is there anything else we should know?
Applicaiton can have only a main Title or Product Title without additional items.

Also its confusing when actual label is called a control in the binding its hard to guess what it is for.

**Comment by mikerodonnell89** [comment]
@fkolar check out how the popover and popover body handle this with an *ngIf
