### ISSUE TITLE
ApprovalFlow: Revisit needed dependencies. 

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#6491]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

<img width="1503" alt="Screen Shot 2021-09-10 at 11 32 54 AM" src="https://user-images.githubusercontent.com/17149942/132834333-8bcb4a58-6242-4cfd-9c7f-1a17f3e07d6c.png">

While trying to compile approval flow as standalone component, so I have this test module and here we use and import approval flow component +  only this test module is compiled. I can see there is allot of unnecessary  dependencies which I believe are caused by really loose imports or something is importing maybe this `FundamentalNgxCoreModule` ?

Anyway the component bundle for AF is really huge and we should revisit what is really imported. 

```ts
@NgModule({
  imports: [
    CommonModule,
    BrowserModule,
    BrowserAnimationsModule,
    PlatformApprovalFlowModule
  ],
  exports: [
    ApprovalFlowComponent
  ],
  declarations: [
    ApprovalFlowComponent
  ],
  providers: [RtlService]
})
export class TestApprovalFlowModule implements DoBootstrap {
  constructor(private injector: Injector) {
  }
```

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest main branch. 
#### If this is a bug, please provide steps for reproducing it.

- Create new component e..g `TestApprovalflowComponent` in your test app which uses Platform Approval flow
- Create Module for it like above, create TsConfig.json, so you can compile this into its own folder
- Create Main.ts for this component - to bootstrap this component 
- Create record in angular.json so you can run ng build xxxx

**Comment by dmitry-stepanenko** [comment]
all dependencies appears to be required
