### ISSUE TITLE
ApprovalFlow: Change Detection Problem

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#6492]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Component does not work inside wrapping component having OnPush strategy. Not event events exposed to trigger CD, as well as internal actions that either switch to edit mode should call also CD. 

When showing dialog we should call CD. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

main branch
#### If this is a bug, please provide steps for reproducing it.

Switch this Documentation example  component for approval flow into OnPush Mode.

**Comment by dmitry-stepanenko** [comment]
cannot reproduce
