### ISSUE TITLE
Update the guide how to create new component in the library

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#6495]
This guide needs to include detailed steps of how to create a new component in the library, assuming it's a new contributor who has never worked with our library before. 
It should include everything from where to register the new module, how to include the new component in the documentation, where to add the module so it's properly exported, what files are needed for the documentation, Stackblitz, etc.
And last but not least all the steps to test the component, add/update existing tests, etc. 

Please use this page: https://github.com/SAP/fundamental-ngx/wiki/Guide-on-how-to-create-new-component-in-Fundamental-ngx

Once it's finalized we will update the existing readme file.

**Comment by IB002** [comment]
Updated with [ #10322](https://github.com/SAP/fundamental-ngx/pull/10322)
