### ISSUE TITLE
new feature: Multi option button

### ISSUE THREAD

**Issue by kevinclerc** [SAP/fundamental-ngx#652]
#### Is this a bug, enhancement, or feature request?
Feature Request
#### Briefly describe your proposal.
Provide a button with the possibility for more options.
It's like a dropdown but if you click on the button, the dropdown does not open.
Only if you click on the "arrow" the options appears

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
0.3.1

#### Is there anything else we should know?
There is such a component in the global design file used by our Designer
![Screen Shot 2019-03-29 at 11 46 52](https://user-images.githubusercontent.com/4631213/55227700-778e0680-5218-11e9-8118-46626bfb9612.png)

**Comment by droshev** [comment]
@LeoT7508 @jeannewalters do we have this in the design?

**Comment by LeoT7508** [comment]
The split button menu should work like any other drop down menu, the menu should be styled the same. Right now I believe its a popover menu.

**Comment by MattL75** [comment]
@LeoT7508 Should first go through the fundamental css library? Or did you have something in mind for some sort of composition?

**Comment by LeoT7508** [comment]
This exists in the newest design sheet that can be found here: 

https://zpl.io/V1wozlE

**Comment by droshev** [comment]
@saad-mo @eboyer do we have this split button with icon and text in fd-ui?

**Comment by mikerodonnell89** [comment]
Blocked by https://github.com/SAP/fundamental/issues/954
