### ISSUE TITLE
bug(platform): Table Documentation Bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6539]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Those issues came from defect hunting session done on Sept 14, 2021 #6498 :

1. (Platform) Table examples are all hardcoding the content density. Please, remove it as we have the content density switcher
2.  Platform Table Playground - section first-column(like align, width) doesn't seem to be working (ariba)
<img width="576" alt="Screen Shot 2021-09-14 at 11 26 50 AM" src="https://user-images.githubusercontent.com/4380815/133286941-0d8804ee-2d5b-4b55-8dd8-4bdefc597dd5.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by george861** [comment]
Hi Colleagues,

Above mentioned issue is fixed.

Retest Details:
JAWS 2021.2107.12 ILM

Thanks & Regards
George
