### ISSUE TITLE
bug(platform): Table - Filtering feature bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6540]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Those issues came from defect hunting session done on Sept 14, 2021 #6498 :

- [x] Search field focus buttons visual defects:

**Steps for reproducing it:**
1. Open https://fundamental-ngx.netlify.app/#/platform/table
2. Click on search field of any examples
**Axtual results:**
<img width="514" alt="Screen Shot 2021-09-14 at 11 11 47 AM" src="https://user-images.githubusercontent.com/4380815/133284389-2424c816-9030-4b16-82d1-ab4c170c3d21.png">
<img width="529" alt="Screen Shot 2021-09-14 at 11 11 42 AM" src="https://user-images.githubusercontent.com/4380815/133284392-e59f2bc6-bbbb-49ab-a28c-e4b0e50da338.png">

- [x] incorrect operation `X` button

**Steps for reproducing it:**

1. Open https://fundamental-ngx.netlify.app/#/platform/table
2. Write some text from table cell in search field of any example
3. Then trigger the filter button - it will filter the content
4. Click on the `X` button
**Actual result:**
Filter is cleared, but the table content is not reflected
<img width="1342" alt="Screen Shot 2021-09-14 at 11 14 08 AM" src="https://user-images.githubusercontent.com/4380815/133284754-5b6b9d80-e028-47a5-a8b9-e20ef1be1aac.png">

**Expected result:**
The data should be updated after the user clicks on `X`

- [ ] After user applied some filter and closed the modal window, and later opened it again, reset button is disabled

**Steps for reproducing it:**

1. Open https://fundamental-ngx.netlify.app/#/platform/table
2. Open any model window 
3. Add some filtres
4. Close and open it again
**Actual result:**
https://www.loom.com/share/7ec8ebb7fec8426284a8535cd862c41f

**Expected result:**
Reset button is available

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by dmitry-stepanenko** [comment]
@droshev @InnaAtanasova @Betrozov 
> Platform table -After user applied some filter and closed the modal window, and later opened it again, reset button is disabled

This seems to be intended: filter values are compared with those with which it was opened. This behavior is observed for all similar modals: filter, group, sort, columns, filter by. 

If there's a need to change this behavior, it should be changed for all these components
