### ISSUE TITLE
bug(platform): Table - column resize bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6541]
#### Is this a bug, enhancement, or feature request?
bug originally reported in #6498

#### Briefly describe your proposal.

- [ ] Platform table -After clicking on column resizer and clicking on the other element, resizer still present
![image](https://user-images.githubusercontent.com/6586561/133286419-f8e439fa-700c-409c-9a16-47835747cba4.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by nikvalor** [comment]
@droshev please provide more details in steps to reproduce, not fully clear what should be done to catch a bug.

**Comment by droshev** [comment]
@N1XUS you reported this issue - can you share more info with @nikvalor

**Comment by N1XUS** [comment]
Cannot reproduce this issue anymore
