### ISSUE TITLE
bug(platform): Table - column freezing bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6547]
#### Is this a bug, enhancement, or feature request?
bug originally reported in #6498

#### Briefly describe your proposal.

- [ ] when you filter in Column Freezing example content there is visible empty gap on the bottom

**Steps for reproducing it:**

1. Open https://fundamental-ngx.netlify.app/#/platform/table#freezable
2. Filter content
**Actual result:**
<img width="685" alt="Screen Shot 2021-09-14 at 11 41 28 AM" src="https://user-images.githubusercontent.com/4380815/133289623-e6f6741c-4326-4598-803e-50fea28829ca.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by george861** [comment]
Hi Colleagues,

Above mentioned issue is fixed.

Thanks & Regards
George
