### ISSUE TITLE
bug(core): action sheet does close when you click on it again

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#6563]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
action sheet does close when you click on button again
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.32.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/action-sheet
2. Click on settings button in any example (except mobile example)
3. Click on setting button again
Expected result: action sheet is closed
Actual result: action sheet is not closed

**Comment by Seamoo13** [comment]
@maxym-valor are you sure that clicking the setting button should close it? I don't see that in the docs and the SAP sample also doesn't close like that.
https://sapui5.hana.ondemand.com/#/entity/sap.m.ActionSheet/sample/sap.m.sample.ActionSheet
https://experience.sap.com/fiori-design-web/action-sheet/

**Comment by maxym-valor** [comment]
@Seamoo13 oops, my mistake, forgot to check how example works, sorry. As a user i expected that it should be closed cz looks like menu.
