### ISSUE TITLE
fd-split-button has wrong border on arrow button

### ISSUE THREAD

**Issue by Mohammadreza-Mohammadi** [SAP/fundamental-ngx#6608]
#### Is this a bug, enhancement, or feature request?
fd-split-button has wrong border on arrow button.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.32.1

**Comment by mikerodonnell89** [comment]
@Mohammadreza-Mohammadi can you elaborate, maybe highlight in a screenshot what exactly is not looking correct?

**Comment by Mohammadreza-Mohammadi** [comment]
I didn't see it again
may be I was wrong.
