### ISSUE TITLE
Do not use H1 as the default header level in components. 

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#666]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
address the components being fixed by https://github.com/SAP/fundamental/issues/1178

**Comment by jbadan** [comment]
This is being addressed in fundamental-react here: https://github.com/SAP/fundamental-react/pull/497

We chose to allow ActionBar to still use `<h1>` as it can be used as a page title. All heading levels are now customizable in the following components: 

* ActionBar
* Menu
* Modal
* Panel
* SideNavigation
