### ISSUE TITLE
multi combo improvement during filtering

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#6718]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
1. go to multi combo box and type a string to filter the items where you have more than one matching items
2. select the first item

The field clears out the typed string

Would be good to keep the string after the selection so the user can select another item

**Comment by xandrio** [comment]
https://user-images.githubusercontent.com/5276786/140388199-85db10a3-0de5-4bd7-9f9c-f7c2f1b2b6de.mp4

current main behavior the same as at ui5 multi combobox
