### ISSUE TITLE
bug(core,platform): stackblitz package.json dependencies are empty

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#6812]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Currently, stackblitz package.json file contains empty dependencies object, which reflects in invalid project configuration.
This happens only when version of fundamental-ngx/core|platform is rc or invalid

**Comment by dmitry-stepanenko** [comment]
There's a PR for this https://github.com/SAP/fundamental-ngx/pull/6771

**Comment by N1XUS** [comment]
Duplicate
