### ISSUE TITLE
Issues in Wizard implemented for DXP Templates

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#6826]
Two scrolling bars appear in wizard
 
![image](https://user-images.githubusercontent.com/40032066/135980082-44eda171-083c-4f3c-91df-5c779e971640.png)

After a create the result is rendered here
 
![image](https://user-images.githubusercontent.com/40032066/135980096-a0688449-2513-4b06-99a6-2ffd5eba3428.png)

Do we not use the switch-tile any more?
 
![image](https://user-images.githubusercontent.com/40032066/135980105-99cd7168-690d-41fe-82a6-7d3049414f36.png)

 
How can I render multiple switches next to each other
 
![image](https://user-images.githubusercontent.com/40032066/135980120-011b350a-d9f3-49a2-b15f-3dd09f7a65c2.png)

Duplicate scrolling bar shown
 
![image](https://user-images.githubusercontent.com/40032066/135980144-6a5edd42-7b7c-4d39-b503-5d923c6e9a07.png)

Buttons move up when scrolling down
 
![image](https://user-images.githubusercontent.com/40032066/135980163-9b44f7ed-8f9f-482c-8fb9-8ebff7db392f.png)

Edit does not work
 
![image](https://user-images.githubusercontent.com/40032066/135980179-38a53465-89aa-4ccb-93ab-bf9b83d44a06.png)

**Comment by puru-hk** [comment]
@MichaelBaySAP Could you add the steps to reproduce the issue.

**Comment by MichaelBaySAP** [comment]
Denis Severin is already working on them

**Comment by N1XUS** [comment]
@MichaelBaySAP If I remember correctly, all issues were addressed already. Can this issue be closed?

**Comment by MichaelBaySAP** [comment]
Yes, this can be closed.
