### ISSUE TITLE
[scrollStrategy] is not working for popovers.

### ISSUE THREAD

**Issue by 22shubham22** [SAP/fundamental-ngx#6863]
### Bug

Whenever we try to implement popovers , so as per the documentation for popovers : https://sap.github.io/fundamental-ngx/#/core/popover#scroll 
[scrollStrategy] is not working. 

Under Normal Circumstance the popover should scroll up and down when page is being scrolled and default scrollstrategy is repositionScrollStrategy. But none of the scroll Strategy is working, tried with close scroll strategy that also didn't work..

So what happens , If we open a popover , and then scroll the page while the popover is open the popover will not scroll up and down with the popover body . The popover sticks at one static place. This issue is also noticed in Menu as Menu is based on popover.

1. When Create button is pressed a popover opens : (create button is the popover body)

![Screenshot (37)](https://user-images.githubusercontent.com/60786471/136502330-4b2aa56c-8c45-4b34-b8d1-7cd251147b67.png)

2. When we scroll , the page moves up , create button moves up but the popover which is supposed to move up along with create button sticks to its same position on the screen.

![Screenshot (38)](https://user-images.githubusercontent.com/60786471/136502346-a7850e09-bbb8-42ad-8979-5050c6437175.png)

##HTML File: 

`<fd-popover  [scrollStrategy]="repositionScrollStrategy"  *ngIf="typesLoaded && applicationTypes.length > 1">
              <fd-popover-control>
                    <button  fd-button label="{{ 'HOME.CREATE' | translate}}" [fdMenu]="true" [fdType]="'emphasized'" 
                     [compact]="true" [ngClass]="{'create-button': showEmptyView}"></button>
                </fd-popover-control>
                <fd-popover-body>
                    <ul fd-list [byline]="true">
                        <div #projectMenu>
                            <li *ngFor="let application of applicationTypes"
                                (click)="!application.isDisabled && openNewprojectDialogBox(application.name, true)" [ngClass]= 
                                {'createdisabled': application.isDisabled}" fd-list-link>
                                <a class="projectMenuPopover" fd-list-content>
                                    <div fd-list-title><b>{{application.name}}</b></div>
                                    <div fd-list-byline>{{application.description | translate}}</div>
                                </a>
                            </li>
                        </div>
                    </ul>
                </fd-popover-body>
          </fd-popover>`

##Ts file:

`ngOnInit(): void {
		this.repositionScrollStrategy = this._overlay.scrollStrategies.reposition({
			autoClose: this.autoClose,
			scrollThrottle: this.scrollThrottle,
		});
}`

Now I tried this way for close scroll strategy also and it did not work too.

Angular version : 12.2.1
fundamental-ngx/core: 0.28.3

**Comment by mikerodonnell89** [comment]
@22shubham22 I am unable to recreate this bug with the Angular and fundamental-ngx versions you have specified, and copying your template HTML as best I could without the complete component code.  Are you able to recreate this issue in a stackblitz?

**Comment by droshev** [comment]
@22shubham22 I tried exporting [this](https://stackblitz.com/edit/angular-atrsbv?file=src%2Findex.html) in stackblitz and it is working as expected.

**Comment by 22shubham22** [comment]
> @22shubham22 I tried exporting [this](https://stackblitz.com/edit/angular-atrsbv?file=src%2Findex.html) in stackblitz and it is working as expected.

Issue cannot be recreated in stackblitz but in our project none of the popovers are working as expected.

https://sap-my.sharepoint.com/:v:/p/shubham_anand/Eecqt2sXJOdDuKP3-f20Mb4BqQS9nm04mn05SID5Ux4Wpw?e=5kd4JX
