### ISSUE TITLE
Add documentation typedoc comments for all components

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#687]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Add documentation typedoc comments to all components. See Alert and Modal for examples.

List of done components: 

- [x] Action Bar (#722)
- [x] Alert (#684)
- [x] Badge (#724)
- [x] Breadcrumb (#726)
- [x] Button (#728) 
- [x] Button Group (#782) 
- [x] Calendar (#867) 
- [x] Combobox Input (#799)
- [x] Date Picker (#867) 
- [x] Datetime Picker (#778) 
- [x] Dropdown
- [x] File Input (#711)
- [x] Form (#777) 
- [x] Icon (#794)
- [x] Identifier (#796)
- [x] Infinite Scroll (#767)
- [x] Image (#797)
- [x] Inline Help (#798) 
- [x] Input Group (#799)
- [x] List (#802 )
- [x] Loading Spinner (#810)
- [x] Menu (#751) 
- [x] Modal (#684)
- [x] Multi Input (#738) 
- [x] Pagination (#811)
- [x] Panel (#765) 
- [x] Popover (#718) 
- [x] Popover Directive (#718) 
- [x] Scroll Spy (#812)
- [x] Search Input (#739) 
- [x] Shellbar (#815)
- [x] Side Navigation (#814)
- [x] Table (#816)
- [x] Tabs (#688) 
- [x] Tile (#809)
- [x] Time (#707)
- [x] Time Picker (#708)
- [x] Toggle (#755) 
- [x] Token (#766)

**Comment by droshev** [comment]
Can we try to wrap up this ticket?
