### ISSUE TITLE
Icon Fonts don't display icons

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#6885]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 12.2.1
"@fundamental-ngx/core": "^0.28.5"

#### If this is a bug, please provide steps for reproducing it.
1. using the sample snippet provided for icons fonts
`<fd-icon font="BusinessSuiteInAppSymbols" [glyph]="'gate'"></fd-icon>` this doesn't display anything. 
In debug console: 

![image](https://user-images.githubusercontent.com/29952750/136917482-ef0c08dd-f892-43d2-a6f5-34658eea1448.png)

It works fine with default sap-icons, just not when we use TNT or BusinesssSuite... font.

Also not able to set Font type using a variable.. 
Using `<fd-icon font="{{item.iconFont}}" [glyph]="item.icon"></fd-icon>` ignores the font type

#### Is there anything else we should know?
Not able to check the sample code snippet in Stackblitz, gives the following error for all the examples 
![image](https://user-images.githubusercontent.com/29952750/136917746-6dcd0d74-1fb3-419e-ae4a-3f1b0aa18f87.png)

**Comment by droshev** [comment]
@AleenaSA did you import the icon fonts(TNT and BusinessSuite)(example)[https://sap.github.io/fundamental-styles/?path=/docs/introduction-overview--page#project-configuration]?

**Comment by AleenaSA** [comment]
Yes, the fonts are added in the styles.css file. also I do see both TNT and BusinessSuite .woff files in my node_modules, but still do not see icons in the application.

**Comment by droshev** [comment]
@AleenaSA i created a simple Angular application where I have imported Fundamental NGX core package and places 1 button and 3 icons(SAP Icon, TNT icon and BusinessSuiteApp icon)
the source is [here](https://github.com/droshev/friendly-octo-palm-tree) and the app is deployed [here](https://droshev.github.io/friendly-octo-palm-tree/)

**Comment by AleenaSA** [comment]
Okay thank you. even I noticed that after creating a sample application that the fonts are loading but for some reason in the application that we are developing the fonts are not loading in the browser(checked in the network tab). the sap-theming version is same as the sample app, the paths to .woff files are correct. the files are loaded properly on build. just that the files are not getting loaded in any browser. Will check more on that and update. Thanks a lot!

**Comment by CemYil03** [comment]
After setting up a minimal project and adding fundamental-ngx, icons still do not appear by default

**Comment by alexalvarezmarambio** [comment]
hi, i haved same problem, but in sample app of @droshev, he have one font-face more. i add this font-face and icons work. why happen, i have not idea, but work.

@font-face {
    font-family: 'SAP-icons';
    src: url('~@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts/SAP-icons.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
