### ISSUE TITLE
The css code in the node_modules folder for fund-styles in outdated

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#6891]
Investigate why the css code in fund-styles node modules is not the latest one. This issue is noticeable for grid component where the latest changes in fund-styles are not in the node_modules folder even if the latest npm version is installed.

**Comment by platon-rov** [comment]
Okay, here is the reason. 

So the chrome has `.fd-col` and we're assuming to have `.fd-row .fd-col` on [fundamental-ngx.netlify.app](fundamental-ngx.netlify.app) as main branch has `fundamental-styles: v0.20.1-rc.39` and change in styles were made in `v0.20.0-rc.31`.

**But [fundamental-ngx.netlify.app](fundamental-ngx.netlify.app) runs `0.32.2-rc.58` of main branch and if we revert to this commit we will see that `fundamental-styles: v0.20.0` is used there. Also, we don't have the next versions deployed there even as the latest one (main branch) is `0.33.0-rc.12`.**

@InnaAtanasova @droshev did we change the dev deployment? If not then the netlify is broken.

**Comment by platon-rov** [comment]
Since we are fixed fundamental-ngx.netlify.app ww should have appropriate styles applied. Issue can be closed.

**Comment by platon-rov** [comment]
Closed as the issue seems to be fixed.
