### ISSUE TITLE
Platform Table custom filtering bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7008]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

2 bugs

- [ ] #7063
![image](https://user-images.githubusercontent.com/6586561/136221894-e3a3db30-0337-4ebf-971d-f5e4ce53381d.png)
- [ ] Custom filtering: Dialog body has strange shadow:  - open an issue
![image](https://user-images.githubusercontent.com/6586561/136222076-41b5c526-2cb5-4ec8-aac7-40f7df880041.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest
reported in #6701

**Comment by dmitry-stepanenko** [comment]
Created a separate issue https://github.com/SAP/fundamental-ngx/issues/7063 for first point here, as it's quite large
