### ISSUE TITLE
bug: wizard-generator(platform): select instead input in edit mode for credit card

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7038]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
When you complete the form - in review mode
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
Browser: Firefox 93
OS: MacOS 10.15
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/wizard-generator#visible-summary
2. Complete first step, go to the 2 step
3. Scroll a little bit higher to do 1 step highlited as current
4. Complete 2 second and go though all next steps 
5. In review choose edit Card Details
Expected result: you are directed to the step 3, you see input there
Actual result: you directed to the step 3, you see select there

Also, another bug here: step one all time highlited as current step but should not!
#### Is there anything else we should know?
https://app.eu-central-1.saucelabs.com/tests/b6b67b6733904bad8536aa7969f45241?auth=4bcfa9595ab7b100d6664bc87c0cacce#2

**Comment by Seamoo13** [comment]
https://user-images.githubusercontent.com/47522152/146178358-3bda1e6e-9fba-4eb9-b298-6cf01baf56d2.mp4

![2021-12-15](https://user-images.githubusercontent.com/47522152/146178372-0d9d5e63-643f-4705-9c9e-2982c851e200.png)
