### ISSUE TITLE
Table Component: long values are not cropped or handle in proper way

### ISSUE THREAD

**Issue by ditiashova** [SAP/fundamental-ngx#705]
### Bug
```
"@angular/core": "^7.0.1",
"fundamental-ngx": "^0.2.0",
```

Hi,

it's related to the issue https://github.com/SAP/fundamental-ngx/issues/704, when I have a long value in the cell, it doesn't get cropped or etc.

Current:
![image](https://user-images.githubusercontent.com/25684357/55811353-aa29e000-5af1-11e9-9dd1-1ba1e5bfeaaa.png)
Expected:
![image](https://user-images.githubusercontent.com/25684357/55811450-d180ad00-5af1-11e9-9c7a-695cdb0c8fc5.png)

**Comment by mikerodonnell89** [comment]
Closing as this is an issue with the fiori-fundamentals library and not fd-ngx
