### ISSUE TITLE
MenuMobileComponent core flaky unit test case

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#7050]
bug

flaky unit test case for core MenuMobileComponent 
![2021-10-29_8](https://user-images.githubusercontent.com/47522152/139459423-d9698695-ffb3-4d1d-99af-fa24491361e2.png)

v.0.33.0-rc.77

**Comment by Betrozov** [comment]
Fixed by this [PR](https://github.com/SAP/fundamental-ngx/pull/7039)
