### ISSUE TITLE
Pagination component: cursor on hover

### ISSUE THREAD

**Issue by ditiashova** [SAP/fundamental-ngx#706]
#### Bug

```
"@angular/core": "^7.0.1",
"fundamental-ngx": "^0.2.0",
```
Hi,
we're using 0.2.0 version and get page number on hover has text cursor instead of pointer:
Actual: ![image](https://user-images.githubusercontent.com/25684357/55812127-0b05e800-5af3-11e9-8721-d4b8b1caee98.png)
Expected:
![image](https://user-images.githubusercontent.com/25684357/55812231-46a0b200-5af3-11e9-900d-4ea69df5b713.png)

Probably, it has cursor value inherited?

**Comment by MattL75** [comment]
Yes this was fixed as part of 0.3 I believe.
