### ISSUE TITLE
platform table semantic rows bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7067]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
the semantic rows in platform table seems to have fixed height:
<img width="844" alt="Screen Shot 2021-11-01 at 09 15 42" src="https://user-images.githubusercontent.com/4380815/139677478-110f4a22-7e46-47df-875a-491e3fd1a2c8.png">

- [ ] extend the documentation to have such examples 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by platon-rov** [comment]
Okay, it's not about semantic column but about absolute positioned cells at all. They are "disconnected" from the table they don't get the row's height and don't react when it changes.

Actually, there is no fast and clear solution as possible with the default table behavior - when any cell's height changes then row height changes. 

It's possible to somehow listen to the cell's height change and then update the height for every cell in the row but I'm totally not sure as this is not the performance way.

**Comment by platon-rov** [comment]
The easiest solution is to have content not wrapped but cropped (overflow). Otherwise, we need to write some js code to track the row's height and update accordingly height of absolute positioned cells. But it's definitely not a clear solution as more calculations lead to less performance.

**Comment by platon-rov** [comment]
Semantic cells can be fixed using the approach from #7091. But the issue remains for the fixed cells.
