### ISSUE TITLE
bug: table(core) - Table with checkboxes in Cozy-mode is not aligned with Visual Core.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7075]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="380" alt="Table with Checkboxes" src="https://user-images.githubusercontent.com/71797052/139769088-0be30e47-c27d-428d-8ad7-eadc93f943c3.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
V0.33.0-rc84

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/table
Scroll down to Table with Checkboxes

**Comment by maxym-valor** [comment]
@pierrom Is it still actual issue? For me it looks okay 
![image](https://user-images.githubusercontent.com/83698366/140943076-cc062adc-5d75-4456-b2b4-a92217792286.png)

**Comment by pierrom** [comment]
I refreshed several times and I still get below.

![Table with Checkboxes](https://user-images.githubusercontent.com/71797052/140970034-57218b58-bb94-4162-893d-b6267338c41f.png)

**Comment by pierrom** [comment]
Thanks @Riabchuk, Maxym (external - ***@***.***> I will check again later - I’m still getting below.


***@***.***


From: Maxym Riabchuk ***@***.***>
Reply-To: SAP/fundamental-ngx ***@***.***>
Date: Tuesday, November 9, 2021 at 6:33 AM
To: SAP/fundamental-ngx ***@***.***>
Cc: "Margallo, Pierro" ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP/fundamental-ngx] bug: table(core) - Table with checkboxes in Cozy-mode is not aligned with Visual Core. (Issue #7075)


@pierrom<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpierrom&data=04%7C01%7Cpierro.margallo01%40sap.com%7Cadc7231297ff49e3871e08d9a38dd639%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637720651860267222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bKY3Z5Rv2GI5ZGdxUo%2FjMEg6P9SD9qsdOoKXQk80fFI%3D&reserved=0> Is it still actual issue? For me it looks okay
[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F83698366%2F140943076-cc062adc-5d75-4456-b2b4-a92217792286.png&data=04%7C01%7Cpierro.margallo01%40sap.com%7Cadc7231297ff49e3871e08d9a38dd639%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637720651860277217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q99Fh1qnMq5qENgjQcYDvc9E35tf0CmHC0xHueRghRY%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSAP%2Ffundamental-ngx%2Fissues%2F7075%23issuecomment-964206750&data=04%7C01%7Cpierro.margallo01%40sap.com%7Cadc7231297ff49e3871e08d9a38dd639%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637720651860287208%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ag1UEv2EO%2B33ysPuj3%2BuU94AGxw047Iyl4m%2BUBFL67k%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARDYSPAQGKXBHXKKXXIWJJLULEWJ3ANCNFSM5HFH3OGQ&data=04%7C01%7Cpierro.margallo01%40sap.com%7Cadc7231297ff49e3871e08d9a38dd639%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637720651860297202%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P5mdvLTTRzAWv0yKV%2F%2FryfCp4fnTSXl%2BOXJUKouSO9E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpierro.margallo01%40sap.com%7Cadc7231297ff49e3871e08d9a38dd639%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637720651860307195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dSokEO89Wwn1%2Fb2%2Bj4%2FgsWzeY6QqDp0xWsv2ISdjqbo%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpierro.margallo01%40sap.com%7Cadc7231297ff49e3871e08d9a38dd639%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637720651860307195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KIp2mVZLLhBmShDrNbxdxHVKZav%2FXEH7QtyYlkzI6ng%3D&reserved=0>.
