### ISSUE TITLE
bug: table(core) - Default Table with long wrapped text - top and bottom padding seem too close to edge of cells.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7076]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="925" alt="Default Table" src="https://user-images.githubusercontent.com/71797052/139771474-067c9e44-e8ea-4c2d-a256-548e8afa8763.png">

Is there documentation on this? I'm only able to find below. **A** + **E** = 12px
<img width="497" alt="Status This is a very negative text Ng" src="https://user-images.githubusercontent.com/71797052/139772375-8e14f6f9-039a-4409-a053-0472fea606df.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.33.0-rc83

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/table
Scroll down to Default Table and see example with long wrapped text

**Comment by puru-hk** [comment]
It a duplicate bug of https://github.com/SAP/fundamental-ngx/issues/7070. Hence this issue can be closed

**Comment by pierrom** [comment]
Duplicate of 7070 - will close
