### ISSUE TITLE
bug: table(core) - Table with pagination format is not aligned with Visual Core.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7078]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="1004" alt="Table With Pagination" src="https://user-images.githubusercontent.com/71797052/139774749-88c8b960-21a7-4f45-b5cd-9a1977774a9c.png">
<img width="898" alt="Pagination with per page select" src="https://user-images.githubusercontent.com/71797052/139774765-0d52420a-a567-4ba7-985e-2385cbd01040.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.33.0-rc83

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/table
Scroll all the way down to Table with pagination.

**Comment by droshev** [comment]
that is fine. We have an improved design.
