### ISSUE TITLE
bug: radio-group(platform): no required icon for required group

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7084]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
no required icon for required group and no label to radio-button group
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
Expected result: 
![image](https://user-images.githubusercontent.com/83698366/139879288-f4701673-cb62-4a3a-a41e-19070bb53df0.png)

Actual result:
![image](https://user-images.githubusercontent.com/83698366/139878618-e3b59582-8582-49e5-8bdc-759351caf98e.png)
![image](https://user-images.githubusercontent.com/83698366/139878663-dfdd9b11-90a6-4fb6-9ab2-360851fc0145.png)

**Comment by platon-rov** [comment]
fixed, not reproducible.
