### ISSUE TITLE
bug: form-container(platform): broken layout for drop-down

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7106]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Broken layout for expanded drop-down
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/form-container#field-inline-change
2. Open drop-down 
Expected result: drop-down layout is correct, no empty space
Actual result: layout broken, 
![image](https://user-images.githubusercontent.com/83698366/140376938-550f809d-b8bb-4664-aa62-02de29601dd0.png)

**Comment by Seamoo13** [comment]
@maxym-valor please also describe the actual and expected results.
