### ISSUE TITLE
enhancement: step-input - remove hardcoded value for compact  and use the service

### ISSUE THREAD

**Issue by Betrozov** [SAP/fundamental-ngx#7108]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Step-input examples remove the hardcoded value for compact and use the service so we can test the content density from the switch in the documentation ShellBar
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by g-cheishvili** [comment]
It is working properly now
