### ISSUE TITLE
The demo (docs) app have performance issue

### ISSUE THREAD

**Issue by alvachien** [SAP/fundamental-ngx#712]
#### Is this a bug, enhancement, or feature request?
BUG 

#### Briefly describe your proposal.
The demo/docs shall work properly with high-performance.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 

#### If this is a bug, please provide steps for reproducing it.
Open https://sap.github.io/fundamental-ngx/
And the Chrome page with high CPU usage.

**Comment by alvachien** [comment]
More detail: 
https://sap.github.io/fundamental-ngx/panel

Page causes Firefox tab page crash;
Page causes Chrome keep loading;

**Comment by MattL75** [comment]
Hi @alvachien! Could you provide a bit more details of what you found? I'm not sure I understand what you mean. That page works fine for me on both Chrome and Firefox with expected CPU usage.

**Comment by alvachien** [comment]
@MattL75 I cannot reproduce it anymore. Thank you.

I just close this issue.
