### ISSUE TITLE
hand pointer over table rows

### ISSUE THREAD

**Issue by khodayar** [SAP/fundamental-ngx#714]
Is this a bug, enhancement, or feature request?
enhancement

Briefly describe your proposal.
By default there is pointer ( cursor : hand) over the rows of the fd-table , which misleads the user if the rows/cells are clickable.  There should classes that removes/add this option if required (e.g., disable-pointer)

**Comment by MattL75** [comment]
This is an issue for the guys at https://github.com/sap/fundamental.

However I'm pretty sure I saw this issue reported there once before so it might be a duplicate.

**Comment by MattL75** [comment]
Found it https://github.com/SAP/fundamental/issues/1284

I'll close this issue since it's being tracked over there

**Comment by khodayar** [comment]
thanks @MattL75
