### ISSUE TITLE
bug: checkbox(core) - wrong check mark color for warning checkbox

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7144]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Check mark for warning checkbox should be orange. For others looks correct, green for success, red for error
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/checkbox#states
2. Click warning checkbox
Expected result: check mark is orange
Actual result: check mark is black
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/140900315-28087c05-8c98-453e-a82f-c16023614b25.png)

**Comment by droshev** [comment]
it is expected
<img width="203" alt="Screen Shot 2021-11-09 at 14 00 55" src="https://user-images.githubusercontent.com/4380815/140987564-c2d76d8f-9ce5-4c88-8142-63829a9ed5ad.png">
