### ISSUE TITLE
bug: wizard-generator(platform): examples do not display correctly in stackblitz

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7153]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In any example in stackblitz -  infinite busy-indicator loading, 4 errors
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/wizard-generator
2. Open any example in stackblitz
Expected result: looks and works correct
Actual result: works incorrect, busy-indicator loading, 4 errors in console. If it's dialog example - first works correct, when you open dialog -  example breaks down
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/83698366/141085361-bea1dc35-e1f5-41dd-ba24-26347ce2c551.png)

**Comment by droshev** [comment]
fixed
