### ISSUE TITLE
enhancement(platform): dynamic page insufficient set of features

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#7168]
#### Is this a bug, enhancement, or feature request?

Enhancement.

#### Briefly describe your proposal.

Actually, platform components are built on top of the core components. In that way, we're reusing core components' code.

For example, the core dynamic page component has `autoResponsive` feature, but since the platform component is built separately we don't have this feature there. 

So here is the indeterminacy - should we implement this feature in the platform by writing repeated code or refactor the platform dynamic page to use the core component in it.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.33.0-rc.124

**Comment by droshev** [comment]
@nickiovenko do you think you can bring this issue in your plannings? I think it would be great if [Platform Dynamic Page](https://fundamental-ngx.netlify.app/#/platform/dynamic-page) is being refactored to re-use more from [Core Dynamic Page](https://fundamental-ngx.netlify.app/#/core/dynamic-page). It will make it easier to bring new features or fix bugs in both
