### ISSUE TITLE
bug: select(core & platofrm) - extra space between arrow icon and right border in select

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7173]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
extra space between arrow icon and right border in select
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0-rc.131
#### If this is a bug, please provide steps for reproducing it.
1. Open Busy Indicator component
2. Open Select component on Core or Platform
3. Hover on any select
Expected result:
![image](https://user-images.githubusercontent.com/83698366/141460227-d11e0b48-0620-429a-93b6-00bbb7bd0153.png)

Actual result: 
![image](https://user-images.githubusercontent.com/83698366/141460133-15919822-5632-4805-b8a2-5a36f17a786a.png)

**Comment by puru-hk** [comment]
Verified in Chrome browser I'm not able to reproduce this issue in both core and platform. Could you please add more information.

**Comment by platon-rov** [comment]
fixed, not reproducible.
