### ISSUE TITLE
bug: avatar group(core) - no information about person from overflow menu

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7176]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
When you are on a low screen resolution and choose a person from the avatar overflow menu, user data is not displayed
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.

**preconditions**:  low screen resolution (1650 * 1050, 1792 * 1120). 

**STR**:
1. open https://fundamental-ngx.netlify.app/#/core/avatar-group#individual-type
2. Click on the last icon (overflow) to open overflow menu
3. Choose any person from the overflow list
4. check user info

**Actual results:** team member info empty
![image](https://user-images.githubusercontent.com/83698366/141491027-96fa5628-8213-4476-a03b-a43b0672a2df.png)

**Expected result:** team member information will be displayed
![image](https://user-images.githubusercontent.com/83698366/141490993-b3b7bcf6-daf9-4570-b132-cf336274d725.png)

extra info: Works correctly on resolutions 1920 * 1080 and 1920 * 1440)

**Comment by puru-hk** [comment]
This is expected behaviour. 
When you click on +3 icon second screenshot is expected . And When it click on the JD icon first screen shot is the expected behaviour. This is not an issues. 
Here the fiori3 visual specs. 
<img width="888" alt="Screenshot 2021-11-14 at 6 37 49 AM" src="https://user-images.githubusercontent.com/32538291/141663712-162390b9-c6bb-4d0a-aa39-59243ea96800.png">

Hence this is not an issue. This can be closed.

**Comment by maxym-valor** [comment]
@puru-hk I guess you did not understand issue correctly. `And When it click on the JD icon **first screen shot** is the expected behaviour` - that's correct, first screenshot is expected, but actualy we have this. Here should be information about the person, but we have no any information, just empty labels.
![image](https://user-images.githubusercontent.com/83698366/141746349-ee55cbec-767b-45bc-9a5c-a83d7d937883.png)

**Comment by puru-hk** [comment]
Got it This has to be fixed

**Comment by platon-rov** [comment]
fixed, not reproducible.
