### ISSUE TITLE
bug: alert(core) - if in playground example we remove first alert - we can not create new one by button

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7189]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In palyground we have 2 alerts. If close second and click 'Open dynamic alert' - new alert will appear. If first close first alert and click button - new alert will not appear
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/alert
2. Scroll to playground example
3. Click on cross-icon in first alert
4. Click 'Open dynamic alert button'
Expected result: new alert appear
Actual result: no new alert

#### Is there anything else we should know?
![Запись_экрана_2021-11-15_в_17 01 13](https://user-images.githubusercontent.com/83698366/141804137-07d75926-d9fb-4de7-b337-bb545320022e.gif)

**Comment by droshev** [comment]
duplicate https://github.com/SAP/fundamental-ngx/issues/6405
