### ISSUE TITLE
Deliver #6572 and #7001 fixes to v0.31.1-rc.24 (Angular 11)

### ISSUE THREAD

**Issue by aberikashvili** [SAP/fundamental-ngx#7197]
Deliver the following fixes into: `v0.31.1-rc.24`, because this is the latest release that supports Angular 10-11.

Create new PR, which contains fixes from the following PRs:
https://github.com/SAP/fundamental-ngx/pull/7194
https://github.com/SAP/fundamental-ngx/pull/6739

And raise against https://github.com/SAP/fundamental-ngx/tree/v0.31.1-rc.24

**Comment by droshev** [comment]
@aberikashvili that is not possible. We can only push to the latest rc

**Comment by aberikashvili** [comment]
Closing this issue, because the version 0.31.1 was released
