### ISSUE TITLE
create an online tool for sharing, running code

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#72]
- [ ] research for existing(open source) one that we can re-use

- [ ] maybe we can think how to embed it in the site so we can use it for the code examples.

**Comment by droshev** [comment]
done by @stefanoScalzo

**Comment by fkolar** [comment]
@droshev How about to create something `Fundamentals Online` and it could be in the format like:

   - https://connect.nrwl.io 

not only to share the code, even I think most of the code like this should be part of the documentaion under `Receipts` sections, but some knowledge adn define cross company best practices how to do things right .
