### ISSUE TITLE
bug: multi-input(core): select - unselect all items issue

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7203]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In mobile example we have button `Select all items`. If we select all items and click on this button again - it will not unselect items, but should do it.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1) Go here https://fundamental-ngx.netlify.app/#/core/multi-input#mobile
2) Open dialog
3) Click on button Select All items
4) click again
Expected result: items not selected
Actual result: items still selected

**Comment by platon-rov** [comment]
fixed, not reproducible.
