### ISSUE TITLE
bug: multi-input(core): when you open mobile example - input disappears

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7207]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
 when you open mobile example - input disappears
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/multi-input#mobile
2. Click on button to open mobile mode
Expected result: input still present
Actual result: input disappears
#### Is there anything else we should know
![Запись_экрана_2021-11-19_в_16 55 50](https://user-images.githubusercontent.com/83698366/142643683-2a077c53-4bbd-4c49-8ba1-8c26963dda17.gif)

**Comment by mikerodonnell89** [comment]
fixed with https://github.com/SAP/fundamental-ngx/pull/8190
