### ISSUE TITLE
Feed Input: Avatar shape

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#7226]
#### Is this a bug, enhancement, or feature request?
Small Enhancement

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0-rc.156

#### If this is a bug, please provide steps for reproducing it.
The avatar should be in a "circular" shape.

Fiori ref: https://experience.sap.com/internal/fiori-design-web/feedinput/#feed-input1

![Screen Shot 2021-11-22 at 4 17 05 PM](https://user-images.githubusercontent.com/72403541/142953879-07fe8e89-7c71-4c43-b127-a45c417a211e.png)

UI5 Demo: https://sapui5.hana.ondemand.com/#/entity/sap.m.FeedInput/sample/sap.m.sample.FeedInput

**Comment by droshev** [comment]
you can achieve that by setting that input to the avatar

**Comment by IB002** [comment]
Address by [ ](https://github.com/SAP/fundamental-ngx/pull/10273)
