### ISSUE TITLE
bug: feed list Item(core): overflow icon should trigger popover & all actions should have icons

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-ngx#7227]
#### Is this a bug, enhancement, or feature request?
Bug / Enhancement

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
V.0.33.0-rc.156

#### If this is a bug, please provide steps for reproducing it.
Overflow icon triggers popover & all actions should have icons in the front of them.

What NGX has currently:
![Screen Shot 2021-11-22 at 4 53 31 PM](https://user-images.githubusercontent.com/72403541/142956417-1d3c608b-bfe9-4112-a9de-157d1e6f08ff.png)

What Fiori3 & Visual Core have:
Fiori ref: https://experience.sap.com/internal/fiori-design-web/feedinput/#actions-on-feed-list-items
![Screen Shot 2021-11-22 at 4 55 46 PM](https://user-images.githubusercontent.com/72403541/142956560-daddfdca-a9db-40ea-9db4-df7a1e72b2f7.png)
VC ref:
 ![Screen Shot 2021-11-22 at 4 55 08 PM](https://user-images.githubusercontent.com/72403541/142956528-ce3837ef-96a9-42ad-92a6-994fd403f6fe.png)

**Comment by dimamarksman** [comment]
So we just need to extend the current example and add icons to the menu.
