### ISSUE TITLE
bug: form container(platform): tooltip icon position and tooltip pop up is not correct

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7231]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="838" alt="Recommended form layouts" src="https://user-images.githubusercontent.com/71797052/142965372-ec2b134c-a401-4523-9a19-3225bb6ef750.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.33.0-rc.156

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/platform/form-container
Scroll down to Recommended Layouts
See Tooltip position
Click on Tooltip and see incorrect position of popup

**Comment by Seamoo13** [comment]
issue not reproduced in v0.33.0-rc.216
