### ISSUE TITLE
bug: combobox(platform): layout is broken

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7232]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
No paddings, layout is broken
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/combobox
2. Have a look to examples
**Actual result:** 
![image](https://user-images.githubusercontent.com/83698366/143010346-f1873106-e8ba-4252-9691-196c31c4a33d.png)
![image](https://user-images.githubusercontent.com/83698366/143010392-188b714b-cc99-437a-ae8f-a5c17c7154e3.png)
**Expected result:** 
![image](https://user-images.githubusercontent.com/83698366/143010611-59c6b33a-0c87-4313-822e-fb36bc467d9c.png)
![image](https://user-images.githubusercontent.com/83698366/143010635-89043c21-79a6-4d6e-8df4-2d0790cbc824.png)

**Comment by Seamoo13** [comment]
additional:
guideline recomends placing label above, but to the left is also allowed.
![2021-12-15_1](https://user-images.githubusercontent.com/47522152/146188513-3dacfd81-6c20-4301-ac2b-bb8db0dae603.png)

**Comment by platon-rov** [comment]
fixed, not reproducable.
