### ISSUE TITLE
bug: toolbar(core): wrong attribute value

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#7234]
#### Is this a bug, enhancement, or feature request?
**bug**

#### Briefly describe your proposal.
Wrong attribute value in split button

#### If this is a bug, please provide steps for reproducing it.

1. Go to https://fundamental-ngx.netlify.app/#/core/toolbar#overflow
2. Click more  button
3. Click more than one time split button
**Actual result:**
When dropdown opened aria-expanded = false and when it closed aria-expanded = true

![image](https://user-images.githubusercontent.com/74654139/143039639-ba6baffe-0f7e-4522-93d9-06f608a8ff86.png)
![image](https://user-images.githubusercontent.com/74654139/143039844-edb30246-f023-4752-b3ca-9220a0944aa8.png)

**Comment by platon-rov** [comment]
fixed, not reproducible.
