### ISSUE TITLE
bug: light dark theme does not work

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7244]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
If you select 'light dark' mode - nothing will be changed, Fiori 3 mode still will be actual
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open any page on fundamental-ngx
2. Click on pallete icon
3. Select Light Dark
Expected result: theme of the site will be change to Light Dark
Actual result: theme still Fiori 3

**Comment by droshev** [comment]
@maxym-valor Light-Dark is supposed to apply the system theme (dark or light). It works for me
