### ISSUE TITLE
[Textarea] Not possible to scroll if textarea is disabled

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#7246]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In the textarea, we could have several lines. If the component is disabled, then it is not more possible to scroll through the lines. 

![Screenshot 2021-11-25 at 16 53 27](https://user-images.githubusercontent.com/26272656/143471673-490bc3d4-9f4d-478d-aa77-92aa2f6bb107.png)

You can check this in this stackblitz demo: https://stackblitz.com/edit/fundamental-issue-7246?file=package.json

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
See Stackblitz demo

#### If this is a bug, please provide steps for reproducing it.
See Stackblitz demo

#### Please provide relevant source code if applicable.
See Stackblitz demo

**Comment by zaheral** [comment]
Hi @puru-hk & @nikvalor, just wanted to check if this issue will be also solved in the core-library, because it is just marked for the platform-library and we have this issue in the core.

**Comment by zaheral** [comment]
Hi @droshev and @InnaAtanasova,

unfortunately, this issue is still not solved on Fundamental-Core v0.33.5. You can check it here on stackblitz: https://stackblitz.com/edit/fundamental-issue-7246-2?file=src%2Fapp%2Ftextarea-state-example.component.html 

On the read-only mode it works, but not on the disabled mode. Please reopen the item if you can confirm that this issue is still available.

**Comment by zaheral** [comment]
Just checked that it is fixed on v0.34.2 released last Friday. Thanks to the team 👍

**Comment by zaheral** [comment]
Hi @droshev and @InnaAtanasova ,

unfortunately, this error occurred again on v0.35.4. I saw that in v0.34.2 it is fixed. Maybe the fix was not taken to the next version? The issue is in the core and platform library. Here are the stackblitz demo examples:

- Platform: https://stackblitz.com/edit/fundamental-issue-7246-3?file=src/app/platform-textarea-basic-example.component.html 
- Core: https://stackblitz.com/edit/fundamental-issue-7246-4?file=src/app/textarea-state-example.component.html 

Please reopen this item.

BR, Zaher

**Comment by zaheral** [comment]
Same issue is still on version 0.36.0

**Comment by platon-rov** [comment]
Available in `0.38.0-rc.3` and will be available in the next stable.

**Comment by zaheral** [comment]
Hi @droshev, @platon-rov and @InnaAtanasova ,

unfortunately, the issue still exists in the newest Fundamental version. See this stackblitz example: https://stackblitz.com/edit/fundamental-issue-6428-5?file=src%2Fapp%2Ftextarea-example.component.html 

Please reopen this Github issue.
