### ISSUE TITLE
bug: toolbar(core): UI breaks by changing window size

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#7253]
#### Is this a bug, enhancement, or feature request?
**bug**

#### Briefly describe your proposal.
UI breaks by changing window size in popover

#### If this is a bug, please provide steps for reproducing it.

1. Go to https://fundamental-ngx.netlify.app/#/core/toolbar#overflow
2. Click more button
3. Decrease window height
**Actual result:**
![image](https://user-images.githubusercontent.com/74654139/143599151-616f8b17-48e7-491e-bcf9-0ce53ea1948b.png)

**Comment by mikerodonnell89** [comment]
Maybe these components (in the example above, input and select) need a min-height? @InnaAtanasova

**Comment by droshev** [comment]
not reproducible
