### ISSUE TITLE
bug: facets & rating indicator(core) - first star in rating indicator does not work

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7268]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
In rating indicator we have 6 stars but actually work 5. If we click on first - no any behavior
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/core/facets#rating-indicator
2. Click on the first star
Expected result: only one star highlighted as selected
Actual result: nothing changed, star does not react for any action
#### Is there anything else we should know
![Запись_экрана_2021-11-29_в_13 41 48](https://user-images.githubusercontent.com/83698366/143862240-516fa1f3-93bd-43a2-83ff-e1aa4c476839.gif)
?

**Comment by Seamoo13** [comment]
Issue is present for all of rating indicator (core)
