### ISSUE TITLE
bug: form generator(platform) - on Chrome needs clean up to be consistent with cozy formatting; OK on Firefox and Safari.

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7277]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
<img width="998" alt="This example shows default scenario of the Form Generator usage with values received from C" src="https://user-images.githubusercontent.com/71797052/143977604-e97c6648-fe10-4695-bea8-942344c22aa8.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.33.0-rc175

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/platform/form-generator
Scroll down and see examples in modules

**Comment by droshev** [comment]
has been fixed in the latest main
