### ISSUE TITLE
bug: message-box(core): no ability to add clickable text in message box

### ISSUE THREAD

**Issue by ninasim** [SAP/fundamental-ngx#7281]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Hi colleagues, 
We have an use case with error message box and the end user is guided to the a page where the template should be onboarded, example - 

"The template you are trying to run is not onboarded with Eureka yet. To onboard it, please follow the steps in https://pages.github.tools.sap/dxp/docs/development/template-sample-automations/#3-register-the-template-in-the-eureka-template-engine."

![image](https://user-images.githubusercontent.com/58508122/144030141-51149dd8-d2c6-4c18-843b-f6d95f61de76.png)

I have checked the available documentation and was not able to find how to put this link as clickable text, may be I have missed something?

**I would like to be be able to add clickable text in message box.**

#### If this is a bug, please provide steps for reproducing it.
1. To paste link in message box
Expected result: link is clickable
Actual result: link is not clickable, it's just text

**Comment by maxym-valor** [comment]
Found that clickable text present in Message Box here https://sapui5.hana.ondemand.com/#/entity/sap.m.MessageBox/sample/sap.m.sample.MessageBoxInfo
