### ISSUE TITLE
bug: table(platform) - header layout of the table is changing after searching

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7283]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
header layout of the table is changing after searching
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/table#single-row-selection
2. Enter any value in search field, i.e. '10'
Expected result: you see result of the searching, styles are correct
Actual result: you see result of the searching, width of the header sections changed
#### Is there anything else we should know?
**Before searching:**
![image](https://user-images.githubusercontent.com/83698366/144039980-b64b22ff-7c09-4e0a-9273-8a5bf92799df.png)
**After searching:** 
![image](https://user-images.githubusercontent.com/83698366/144040033-815c3681-4c7b-4860-9f46-0c1f4a057543.png)

**Comment by Seamoo13** [comment]
duplicates https://github.com/SAP/fundamental-ngx/issues/7010 and issue already fixed.
