### ISSUE TITLE
refactor(core,platform): rename component inputs that duplicate the names of native properties

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#7297]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Across the entire component library there're a lot of cases, where component inputs are named in the same way as native HTML properties (e.g. `name`, `id`, `title`, `class`, `tabindex` etc). This causes a lot of a11y issues as per examples below:
1. When using `id` as an input without square brackets, it ends up with having to html elements with the same id: actual component tag and underlying native element. Because of that for example attached labels are not read
```html
<label fd-form-label for="textarea-1">Some Label</label> <!-- this label won't be read -->
<fdp-textarea id="textarea-1"></fpd-textarea>
```
2. Using `title` as an input without square brackets ends up with 2 titles being read by a11y software.

To overcome this in examples we're using binding with square brackets, but this is more of a workaround, than an actual fix. 

The proposal is to rename all occurrences of such inputs to something not standard. For example,  id => componentId, title => componentTitle and so on.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@fundamental-ngx v0.33

**Comment by dimamarksman** [comment]
I created the issue regarding `for` https://github.com/SAP/fundamental-ngx/pull/7235

**Comment by dimamarksman** [comment]
I agree, we have to rename those inputs to make things clear
