### ISSUE TITLE
[Platform] Search Field with data source not working every time when click on the loop/ on enter 

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#7309]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal
It seems that sometimes when I click on ENTER or on the loop of the component [Search Field](https://sap.github.io/fundamental-ngx/#/platform/search-field) the search is not fired (it is a backend search)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/cli": "11.2.14",
"@fundamental-ngx/core": "0.32.2-rc.53",
"@fundamental-ngx/platform": "0.32.2-rc.53",

#### If this is a bug, please provide steps for reproducing it.
The search field is used into a table (core) that is into a tab that is into a dynamic page.

**Comment by platon-rov** [comment]
Fixed in the latest version. Closing.
