### ISSUE TITLE
Platform: WizardGenerator: Checkbox, label not rendered in WizardGenerator

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7326]
When using the checkbox through 
![image](https://user-images.githubusercontent.com/40032066/145018702-14facb3a-44b7-4409-b92c-c1b1618c8f91.png)
It is only rendered the following 
![image](https://user-images.githubusercontent.com/40032066/145018767-b35a9f02-9d28-4ffb-80ef-7342c36acdd7.png)
The label as in the form generator example is not coming:
![image](https://user-images.githubusercontent.com/40032066/145018839-b939a52d-27a1-4bd0-848d-9c652f6966d0.png)
![image](https://user-images.githubusercontent.com/40032066/146540979-5fe0f6ae-7a1f-4ae4-a7ec-b75250a53816.png)

fundamental-ngx/core: 0.33.0-rc.102
fundamental-ngx/platform: 0.33.0-rc.102

https://github.tools.sap/dxp/template-ui/pull/178

**Comment by N1XUS** [comment]
@MichaelBaySAP As I see from your item configuration, you have the `noLabelLayout` property defined as `true`, which hides the label of the form field. Please set it to false in order for the label to be visible.

![image](https://user-images.githubusercontent.com/6586561/146734507-b1c23227-64bb-459f-8140-e969e2fbc006.png)

**Comment by MichaelBaySAP** [comment]
> @MichaelBaySAP As I see from your item configuration, you have the `noLabelLayout` property defined as `true`, which hides the label of the form field. Please set it to false in order for the label to be visible.
> 
> ![image](https://user-images.githubusercontent.com/6586561/146734507-b1c23227-64bb-459f-8140-e969e2fbc006.png)

Thank you

**Comment by N1XUS** [comment]
@MichaelBaySAP can we close this issue?

**Comment by MichaelBaySAP** [comment]
yes

> @MichaelBaySAP can we close this issue?

Yes
