### ISSUE TITLE
Platform: WizardGenerator: using when function

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7332]
![image](https://user-images.githubusercontent.com/40032066/146442893-60d5309e-ffc7-42f6-a6ef-73e976d22499.png)
Click on Java template
https://github.tools.sap/dxp/template-ui/pull/187

**Comment by N1XUS** [comment]
`when` function of the form item works in the scope of the current form, so checking which items are visible will work only in the scope of the current form user is editing. There’s a solution on how to manually trigger items visibility for the outside forms by using setValue for any field of the outside form. This could be some hidden control where the `when` function always returns `false`. Thus, this item will not be rendered, and will not be present in the final wizard generator forms value, but will work as a trigger that something needs to be checked in a defined form.

**Comment by MichaelBaySAP** [comment]
The `updateValueAndValidity` did not work for me. It would be great if you could provide a working example and we will use it. It would be great if this example used the same format for attaching dependency fields as does the implementation for when steps.


![image](https://user-images.githubusercontent.com/40032066/148038134-32cfa35c-36d6-4a25-9817-025b7bb0cb98.png)

**Comment by MichaelBaySAP** [comment]
Thank you very much for the fix and providing the example. For us to be able to use the fix with the latest Fundamental version, the [breaking changes](https://github.com/SAP/fundamental-ngx/issues/7628) with Wizard Generator need to be fixed.
