### ISSUE TITLE
Platform: WizardGenerator: Second step hidden 

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7333]
![image](https://user-images.githubusercontent.com/40032066/146444264-71581e69-6809-47ee-9586-5d8d6acc6b69.png)
![image](https://user-images.githubusercontent.com/40032066/146444362-34c250fc-ede8-449c-bf2a-945042f1fdee.png)
https://github.tools.sap/dxp/template-ui/pull/188
In Java template, I am setting the second step Component Settings by when to false. Now, I can no longer see the items of Repository Settings step.

**Comment by N1XUS** [comment]
* Wizard generator steps contained duplicated steps with identical ids which caused an error
* step object of wizard generator does not follow `WizardGeneratorItem` interface
