### ISSUE TITLE
platform: error from button import

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7348]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

import platform button and run an angular app - see the attached app
[ngx13.zip](https://github.com/SAP/fundamental-ngx/files/7696332/ngx13.zip)

#### If this is a bug, please provide steps for reproducing it.

`0.33.0-rc.213`

**Comment by platon-rov** [comment]
I see many `@funamental-ngx/core` errors and they're intended. At the wiki page about the library installation we have an item about installing `core` even when want to consume only `platform` https://github.com/SAP/fundamental-ngx/wiki/Full-Installation-Guide#install-fundamental-ngxplatform. Closing this issue.

**Comment by droshev** [comment]
This on the wiki was the old way of importing. This was changed  after we split the package in submodules

**Comment by platon-rov** [comment]
@droshev do you want to say that we should not be installing core to get platform working? From what i see it's still required.
