### ISSUE TITLE
`input-group-search` - `fd-input-group__button--clear` z-index and placeholder length

### ISSUE THREAD

**Issue by jot-hub** [SAP/fundamental-ngx#735]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
(1) currently, the `clear` button is not visible (even though it does appear in the dom).
we currently workaround with custom style `zindex: 1`.

(2) the placeholder text is hidden even when there is clearly whitespace left for the rest of the text. I suspect the occassionally visible `clear` button is the reason for this (i.e. it takes up whitespace even when its not showing up).
![image](https://user-images.githubusercontent.com/18125863/56041578-0ca7f980-5d07-11e9-89a3-ba852a95cff0.png).

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Ng: 7.2.7
fundamental-ngx: 0.3.3

#### If this is a bug, please provide steps for reproducing it.
Just use an `<fd-input-group-search>` in any standalone angular app.

**Comment by MattL75** [comment]
Hey @jot-hub!

Seems like this is mostly a problem with the css classes that we consume from https://github.com/SAP/fundamental. Maybe you could submit the issue there?

**Comment by jot-hub** [comment]
Hi @MattL75 - not completely sure how this should be handled - it will be nice to get a solution from our direct dependency `fundamental-ngx` 😃 - maybe you want to tie this issue with https://github.com/SAP/fundamental/issues/995?

**Comment by MattL75** [comment]
You also have fiori-fundamentals as a direct dependency if you are using fd-ngx since we don't package it with the library. As for this issue, I'll link it in the fundamentals repo, but I'll close it here since there's nothing to do on this repo for this :)
