### ISSUE TITLE
bug: multi-input(platform) - when we open decline list first time - we see cross button

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7360]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
when we open decline list first time - we see, after re-open the disappear
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/multi-input#decline
2. click on button in multi-input
3. Have a look to the list items
Expected result: no cross button
Actual result: cross button displayed and disappears after re-open menu
#### Is there anything else we should know?
![Запись_экрана_2021-12-13_в_17 04 41](https://user-images.githubusercontent.com/83698366/145837139-9f38e103-7833-43e1-95d6-b34e0c80c59d.gif)

**Comment by mikerodonnell89** [comment]
fixed as part of https://github.com/SAP/fundamental-ngx/pull/7457
