### ISSUE TITLE
Defect Hunting Sprint 77 - Sacramento

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#7362]
Defect Hunting issues for Fund-ngx Core and Platform

**Comment by InnaAtanasova** [comment]
- [ ] Keyboard navigation for Avatar group. How would a user navigate between the Avatars with a keyboard only?
<img width="1198" alt="Screen Shot 2021-12-13 at 11 48 20 AM" src="https://user-images.githubusercontent.com/39598672/145854827-9c3c2574-2ca1-4220-802b-abd7a85e9810.png">

- [ ] Avatar gets focus in Bar component:
<img width="525" alt="Screen Shot 2021-12-13 at 11 49 45 AM" src="https://user-images.githubusercontent.com/39598672/145855720-6eb90bbc-196e-45e9-ac7e-e44d61fbd9e2.png">

- [ ] Vertical alignment for Bar component:
<img width="1227" alt="Screen Shot 2021-12-13 at 11 50 04 AM" src="https://user-images.githubusercontent.com/39598672/145855779-dc39ed08-5e4e-41f5-a654-0bcbd4661973.png">

- [ ] Console errors for Avatar:
<img width="839" alt="Screen Shot 2021-12-13 at 11 46 46 AM" src="https://user-images.githubusercontent.com/39598672/145855939-b591446f-3111-4d22-b5bd-70baa052cdb4.png">

- [ ] Carousel issues: 1. Check with the design if the buttons on hover should look like this. 2. Check the focus states. Should the whole element get a focus?
<img width="444" alt="Screen Shot 2021-12-13 at 12 05 21 PM" src="https://user-images.githubusercontent.com/39598672/145857382-6304c019-b35a-465c-b14d-868bbcae5d6b.png">
<img width="898" alt="Screen Shot 2021-12-13 at 12 09 00 PM" src="https://user-images.githubusercontent.com/39598672/145857389-2389cf40-9d77-4d6f-83f1-225ce650d67f.png">

**Comment by InnaAtanasova** [comment]
- [ ] Disabled Date Picker has pointer events and triggers the validation message:
<img width="338" alt="Screen Shot 2021-12-13 at 1 26 20 PM" src="https://user-images.githubusercontent.com/39598672/145868057-33e39bcf-fa0b-4184-b60a-d9befc7ad2b1.png">
- [ ] Date Picker i18n example. Click inside the input field and delete the `m.`, it shows the input field is invalid and colors in red. Add back `m.` and the field is still invalid. Expected behaviour: field should become valid again 
<img width="1234" alt="Screen Shot 2021-12-13 at 1 28 29 PM" src="https://user-images.githubusercontent.com/39598672/145868109-e9ad06d5-e4d0-4600-bbb8-7907b8a8061f.png">

**Comment by InnaAtanasova** [comment]
- [ ] Dialog with inner popovers
<img width="1218" alt="Screen Shot 2021-12-13 at 1 39 17 PM" src="https://user-images.githubusercontent.com/39598672/145869402-62d6f247-5929-43c8-9f2d-4e36ebeea216.png">

**Comment by InnaAtanasova** [comment]
- [ ] Grid List Drag and Drop is not working per specs. It does not indicate the new position on drag.
<img width="1041" alt="Screen Shot 2021-12-13 at 1 58 30 PM" src="https://user-images.githubusercontent.com/39598672/145871881-cdf2ebe1-e230-495b-a31f-5efc85c67313.png">

**Comment by InnaAtanasova** [comment]
- [ ]  Interactive list - third item does not get the proper active state when selected state is applied:
<img width="903" alt="Screen Shot 2021-12-13 at 2 11 05 PM" src="https://user-images.githubusercontent.com/39598672/145873952-bb060beb-026f-4ffc-9fe1-59657db825cb.png">
<img width="1043" alt="Screen Shot 2021-12-13 at 2 10 13 PM" src="https://user-images.githubusercontent.com/39598672/145873955-8f2af26a-b046-4cb0-b4bd-acec3b3ec7b5.png">

**Comment by InnaAtanasova** [comment]
- [ ] No keyboard navigation for pagination. Once you click on a page you can't go to another page using only the keyboard.
<img width="1046" alt="Screen Shot 2021-12-13 at 4 25 53 PM" src="https://user-images.githubusercontent.com/39598672/145891442-428f449f-aa88-4a15-8ae0-fa96c268e127.png">

**Comment by InnaAtanasova** [comment]
- [ ] Select semantic states messages too big and not per design and fund-styles:
<img width="1072" alt="Screen Shot 2021-12-13 at 4 50 58 PM" src="https://user-images.githubusercontent.com/39598672/145894752-86f0a550-09ae-4c1a-beb4-fe8d4e83943a.png">

**Comment by InnaAtanasova** [comment]
- [ ] clicking on More does not show dropdown with the overflow items
<img width="1058" alt="Screen Shot 2021-12-13 at 5 51 11 PM" src="https://user-images.githubusercontent.com/39598672/145902041-1a4847dd-fdd1-417b-af9c-6bb17a45daf8.png">

**Comment by InnaAtanasova** [comment]
- [ ] example needs to be updated. It says 5 of 5 and has 6 stars
<img width="1058" alt="Screen Shot 2021-12-13 at 4 46 57 PM" src="https://user-images.githubusercontent.com/39598672/145902247-d61617d6-ab12-4b88-b2de-125aea3894fb.png">

**Comment by InnaAtanasova** [comment]
- [ ] Vertical navigation - icons and focus issues:
<img width="964" alt="Screen Shot 2021-12-13 at 5 59 38 PM" src="https://user-images.githubusercontent.com/39598672/145902739-540dcf49-f7ff-4ce2-aff4-63bea819d392.png">
<img width="974" alt="Screen Shot 2021-12-13 at 5 59 31 PM" src="https://user-images.githubusercontent.com/39598672/145902743-48d968cc-87c0-45b7-92b1-91833dc687a3.png">

**Comment by mikerodonnell89** [comment]
- [ ] Need some margin here on the platform date picker examples:
<img width="743" alt="Screen Shot 2021-12-14 at 12 49 12 PM" src="https://user-images.githubusercontent.com/2471874/146052530-73d3d9f9-a30a-48be-8442-93eb8fa6c88e.png">

- [ ] Platform, datetime picker forms example - inputs should receive red outline on form submit when the fields are not valid:
<img width="1274" alt="Screen Shot 2021-12-14 at 12 53 01 PM" src="https://user-images.githubusercontent.com/2471874/146053012-db62edce-1f23-4c96-85c5-f30916c973f9.png">

- [ ] Platform datetime w/ template forms - valid date displays as invalid
<img width="651" alt="Screen Shot 2021-12-14 at 1 06 33 PM" src="https://user-images.githubusercontent.com/2471874/146055051-950afe52-749b-4d1d-99c2-1b5c6214b5da.png">

- [ ] Platform datetime pickers with required attribute, starting with a null value - input renders as invalid when the user focuses the input.  Should happen on blur

- [ ] Platform input group - I think using "0.00" as the text addons is confusing here and "USD" or something would be more relevant 
<img width="676" alt="Screen Shot 2021-12-14 at 1 17 47 PM" src="https://user-images.githubusercontent.com/2471874/146056596-7cf3e512-cfbf-4254-b190-9c118e1e123b.png">

- [ ] Platform link - image is 50x50 pixels but due to line height the entire element (and therefore focus outline) extends past the 50px height
<img width="304" alt="Screen Shot 2021-12-14 at 1 19 25 PM" src="https://user-images.githubusercontent.com/2471874/146057102-55739514-6dfc-4740-8931-fce0c11c7b37.png">

- [ ] Platform list, multi-selection example - focusing checkboxes then pressing the "shift" key can have strange results of shifting different items. Shouldn't do anything

**Comment by mikerodonnell89** [comment]
- [ ] Platform list, "action list item" examples - click a list item, then dismiss this alert:
<img width="464" alt="Screen Shot 2021-12-14 at 1 29 42 PM" src="https://user-images.githubusercontent.com/2471874/146058284-eb7cebd2-5081-4a84-99d7-6ea1b45fd3d5.png">
Then press arrow up or arrow down, usually the incorrect list item will receive focus.  But not always, so try doing this at different window scroll positions with different items focused.

- [ ] Platform multi-combobox - "example with" text cut off
<img width="449" alt="Screen Shot 2021-12-14 at 1 54 18 PM" src="https://user-images.githubusercontent.com/2471874/146061650-eb2badf6-e0a5-45a1-a8d8-f9c3cdc905f6.png">

- [ ] Platform multi-combobox mobile mode - open the dialog and select some items.  Click the button next to the input to only display selected items in the list, then click it again to go back to the full list. Observe that the selected items no longer appear selected

**Comment by mikerodonnell89** [comment]
- [ ] Platform multi-input mobile mode - button on right of input resets the search list but does not reset input. Also, "approve" button in dialog footer needs an uppercase "A". Lastly the top right X button does not close the dialog
<img width="392" alt="Screen Shot 2021-12-14 at 2 35 23 PM" src="https://user-images.githubusercontent.com/2471874/146067214-17a3adf7-091b-4fef-a03e-cf222b5a7e7e.png">

- [ ] Platform multi-input decline list type - list options lose their X on subsequent opens of the popover
<img width="1318" alt="Screen Shot 2021-12-14 at 2 53 17 PM" src="https://user-images.githubusercontent.com/2471874/146069805-2b2fe9a8-1574-4e29-a281-ea8c2aa0da63.png">

**Comment by mikerodonnell89** [comment]
- [ ] Platform step input - I can click the plus or minus buttons to change the value of the input, and then pressing the space bar makes it look like the button is being pressed but the number does not change
- [ ] Platform time picker docs could use some margins
![Uploading Screen Shot 2021-12-14 at 5.27.04 PM.png…]()
 

- [ ] Platform upload collection - click checks to edit a filename then drag the column border to make the column wider - extension still wraps incorrectly. Also in my opinion let's just make the default column width settings wider in these examples to get a better look and feel
<img width="434" alt="Screen Shot 2021-12-14 at 5 28 37 PM" src="https://user-images.githubusercontent.com/2471874/146089482-c7d89e2a-1b00-4aab-9d68-01d7253277c0.png">

**Comment by N1XUS** [comment]
- [ ] Value help dialog: controls are not verticaly centered:

![image](https://user-images.githubusercontent.com/6586561/146733377-653fecf7-0cf0-4426-aa78-d9f262709e15.png)

**Comment by Betrozov** [comment]
> * [ ]  Console errors for Avatar:
> 
> <img alt="Screen Shot 2021-12-13 at 11 46 46 AM" width="839" src="https://user-images.githubusercontent.com/39598672/145855939-b591446f-3111-4d22-b5bd-70baa052cdb4.png">


Hi @InnaAtanasova 
It is not the issue but expected behaviors 🙂 
It shows us what will happen if the image does not load for some reason.
