### ISSUE TITLE
Event window:resize called always with Shellbar component

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#7364]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 12.0.5
Fundamental: 0.33.0-rc.207

#### If this is a bug, please provide steps for reproducing it.
We are using the Shellbar component in our application Angular.
Since we migrated to Angular 12 / Fundamental 0.33 we noticed we have a problem on the condensed menu in the Shellbar component.
We have in our code a listener for the OnResize to condense the left menu:

@HostListener('window:resize', ['$event'])
  onResize(event?): void {
    if (window.innerWidth <= 1000) {
      this.condensed = true;
      console.log('CONDENSED');
    } else {
      this.condensed = false;
      console.log('CONDENSED FALSE');
    }
  }

It seems that the onResize event is always called (going always on the false case, so I'm not able to shrink the menu by clicking on the button
![image](https://user-images.githubusercontent.com/74785804/145861943-b976eab9-eb7e-4311-8408-27442e598e24.png)
)
Can you help us?
Thanks in advance

#### Please provide relevant source code if applicable.
@HostListener('window:resize', ['$event'])
  onResize(event?): void {
    if (window.innerWidth <= 1000) {
      this.condensed = true;
      console.log('CONDENSED');
    } else {
      this.condensed = false;
      console.log('CONDENSED FALSE');
    }
  }

used with https://sap.github.io/fundamental-ngx/#/core/shellbar

**Comment by mikerodonnell89** [comment]
Cannot recreate this issue with Angular 13/0.33.0-rc.214, is updating an option?

**Comment by silvia-giordano** [comment]
I already updated from Angular 11 to 12 to use another component (Search Field from Platform),... but ok I can try

**Comment by silvia-giordano** [comment]
@mikerodonnell89 It is fine now for this version on the shellbar resize, thanks
