### ISSUE TITLE
Core: Message strip: Link not rendered inline (UX request)

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7368]
![image](https://user-images.githubusercontent.com/40032066/146020397-b4e89db1-b9ca-4ff2-b4ab-9e841f912fab.png)

To reproduce this issue, 
please pull the branch https://github.tools.sap/dxp/template-ui/tree/includeMessageStrip and look into file https://github.tools.sap/dxp/template-ui/blob/e8899c22e64d3594dbb169da8ddea61f3fcfe744/src/app/pages/templates-detail-page/templates-detail-page.component.html#L7

fundamental-ngx/core: 0.33.0-rc.102
fundamental-ngx/platform: 0.33.0-rc.102

**Comment by droshev** [comment]
I am not able to reproduce it [here](https://stackblitz.com/edit/angular-2ft4xc?file=src%2Fapp%2Fmessage-strip-example.component.html)
