### ISSUE TITLE
Problem on content security policy 

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#7381]
#### Is this a bug, enhancement, or feature request?
BUG

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Problem since 
Angular: 12.0.5  
Fundamental: 0.33.0-rc.207

actual version using
Angular 13
Fundamental 0.33.0-rc.214

#### If this is a bug, please provide steps for reproducing it.
From Angular [documentation](https://angular.io/guide/security#content-security-policy), only 
default-src 'self'; style-src 'self' 'unsafe-inline';
is necessary in meta of the index.html

Now when I start my app I have in the console:
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

and no icons are showed

Previous version functioning for our project:
Angular 11.2.14
Fundamental: 0.32.2-rc.53

Can you help us?
Thanks in advance

**Comment by droshev** [comment]
@N1XUS do you think you can research this issue and how it affects us?

**Comment by mikerodonnell89** [comment]
@silvia-giordano You may need to disable styles inlineCritical in your angular.json file as described in this comment here: https://github.com/angular/angular-cli/issues/20864#issuecomment-844823912

Please refer to the whole thread for some more context as to why this is happening and let us know if the problem persists

**Comment by silvia-giordano** [comment]
@mikerodonnell89 I tried with your suggestion but we still have the problem:
![image](https://user-images.githubusercontent.com/74785804/146528432-9431aeeb-bd44-4ef3-bbd4-91f9d7e7da30.png)
