### ISSUE TITLE
bug(core): submenu menu doesn't close on mouseout

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#7392]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

When mouse pointer is out of submenu it doesn't close.

https://user-images.githubusercontent.com/20265336/146518128-36742d9c-4e57-4efa-aa0a-d791d3524ea9.mov

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.33.0-rc.219

#### If this is a bug, please provide steps for reproducing it.

Go https://fundamental-ngx.netlify.app/#/core/menu#with-submenu

**Comment by wei368** [comment]
when the bug is fixed, is it possible to have a patch for version 0.32.2? thanks

**Comment by dimamarksman** [comment]
I see that [sapui5 component](https://sapui5.hana.ondemand.com/#/entity/sap.m.Menu/sample/sap.m.sample.Menu) also doesn't close a menu when the mouse pointer s moving out of sub-menu. 
It does close the sub-menu when pointer is moving on the sibling parent menu item or the user clicks somewhere.

**Comment by dimamarksman** [comment]
So I'm going to add the ability to close it when the mouse moving out of sub-menu on some menu item or user clicks somewhere

**Comment by wei368** [comment]
thanks @dimamarksman

**Comment by dimamarksman** [comment]
As far as I understand we need this fix for `0.32.2` version as well

**Comment by dimamarksman** [comment]
The fix was released in version [0.32.6](https://www.npmjs.com/package/@fundamental-ngx/core/v/0.32.6)
