### ISSUE TITLE
Defect Hunting for Sprint 78 - New York

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#7396]
Please list all the findings as a thread to this issue

**Comment by platon-rov** [comment]
## Platform Schematics

* Adding platform package fails if `add translations` prompt accepted.
https://github.com/SAP/fundamental-ngx/issues/7420

## Platform Thumbnail
* Dialog looks not correct on small screens, `380px` example
<img width="389" alt="Screenshot 2021-12-22 at 17 26 18" src="https://user-images.githubusercontent.com/20265336/147115919-035586f6-6eca-413f-b416-f234cd9ceacf.png">
