### ISSUE TITLE
fd-button state disabled not properly disabled

### ISSUE THREAD

**Issue by maxmarkus** [SAP/fundamental-ngx#740]
Hello, 

I have experienced that `(click)` events are triggered on `fd-button [state]="'disabled'"`. On standard `[disabled]` it does behave correctly. 
A workaround is currently to define both [state] and [disabled].

Not sure if this is valid, and [state] is only for ui purposes and not for behavior?

Best, Markus

**Comment by MattL75** [comment]
Hey Markus. I'm not sure what the point of the `state` input is. It's really just assigns is-selected and is-disabled classes to the element, but that should be done through native html like `disabled`. It should work fine if you only set disabled, and not worry about state. I'll talk to the team about removing the state input to avoid confusion.
