### ISSUE TITLE
[Feature Request] Add new line into a table - editable row

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#7422]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
We have a [table](https://fundamental-ngx.netlify.app/#/core/table#table-toolbar) in which we want to add a line.
We saw that in the actual component there is a '+' that open a popup.
From Fiori we saw that there are three possible ways to [add a new line into a table](https://experience.sap.com/internal/fiori-design-web/grid-table/#add-items).
We are interested in having the first one:
"Add the item inline. Create an empty, editable row as the first item of the table. Show the Save button on the table toolbar. This option is recommended for simple scenarios with just a few columns and no option to hide columns."

Thanks in advance

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13.0.2
Fundamental 0.33.0-rc.21

**Comment by droshev** [comment]
Let's review [this](https://experience.sap.com/fiori-design-web/grid-table/#add-items) and prepare a proposal how to handle it as part of the platform table.
