### ISSUE TITLE
bug(platform): table with multi-select does not resize properly for compact mode

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#7424]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
When using platform table with a multi-selection option (the first column is filled with the checkbox), the height of the rows does not change when 'compact' content density is selected.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/platform/table#multiple-row-selection
2. Change content density parameter to 'Compact'
ER: The height of the rows should be smaller
AR: The height of the rows didn't change

**Comment by g-cheishvili** [comment]
It is solved judging from the latest deployed version
