### ISSUE TITLE
Support for Multi-Combobox in Form Generator.

### ISSUE THREAD

**Issue by amritanshvns** [SAP/fundamental-ngx#7446]
#### Is this a bug, enhancement, or feature request?
feature-request

#### Briefly describe your proposal.
Support for Multi-Combobox in Form Generator.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Current Version

**Comment by droshev** [comment]
@amritanshvns you can register that as a custom component at the moment - more information you can find [here](https://fundamental-ngx.netlify.app/#/platform/form-generator#custom)
