### ISSUE TITLE
bug: wizard-generator(platform) - behavior not aligned with Visual Core

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7450]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
<img width="937" alt="Default Wizard generator" src="https://user-images.githubusercontent.com/71797052/147529480-63651c9b-7646-4c1a-8ece-fc30ba10a03e.png">
<img width="738" alt="Step Anchor Bar" src="https://user-images.githubusercontent.com/71797052/147529494-d0c88e95-47e5-414c-aafb-50d659f3679d.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.33.0-rc.239

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/platform/wizard-generator
Scroll to Default Wizard Generator

**Comment by droshev** [comment]
@pierrom can you try to reproduce it with the wizard component?
