### ISSUE TITLE
bug: wizard-generator(platform) - Dialog Boxes does not exhibit RTL

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#7451]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
<img width="960" alt="Wizard generator in dialog" src="https://user-images.githubusercontent.com/71797052/147530342-25bf0a61-6358-4d24-b5b0-73cad9f3b95c.png">
<img width="1087" alt="Checkout" src="https://user-images.githubusercontent.com/71797052/147530347-7e795e38-c7a0-474c-bffb-aa03a600d637.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.33.0-rc.239

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/platform/wizard-generator
Scroll to ALL Wizard Generator with Dialogs

**Comment by droshev** [comment]
the documentation lack this part. we need to improve it but it is not a component bug
