### ISSUE TITLE
test(core): flaky calendar e2e tests

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#7484]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
e2e tests for calendar may randomly fail from time to time. This should be investigated. Sample runs:
https://github.com/SAP/fundamental-ngx/runs/4649583243?check_suite_focus=true
https://github.com/SAP/fundamental-ngx/runs/4649539954?check_suite_focus=true

**Comment by Seamoo13** [comment]
already fixed: https://github.com/SAP/fundamental-ngx/pull/7406
