### ISSUE TITLE
Datetimepicker / Datepicker - keyboard input clears the field

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#750]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

Changing the date/time via keyboard clears the input field

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

1) Open datepickers popover (click on input)
2) Set any date using datepicker controls
3) Close datepickers popover
4) Click datepicker input field and adjust date/time using keyboard
5) Click outside or hit tab
6) Data disappears from input

#### Please provide relevant source code if applicable.

n/a

#### Is there anything else we should know?

n/a

**Comment by MattL75** [comment]
The date disappears from the input if the datepicker found the date invalid. Not sure this is the best behaviour, but also unsure if reverting back to the previous date would be better.

Probably the safest solution is to just have a visual cue indicating that the date is invalid.
