### ISSUE TITLE
Critical Defect Hunting issues for Fundmantal-ngx 0.33.0. release

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#7550]
# Sprint 78
## Platform Schematics

* Adding platform package fails if `add translations` prompt accepted.
https://github.com/SAP/fundamental-ngx/issues/7420
https://github.com/SAP/fundamental-ngx/pull/7421

## Platform Thumbnail
* Dialog looks not correct on small screens, `380px` example
<img width="389" alt="Screenshot 2021-12-22 at 17 26 18" src="https://user-images.githubusercontent.com/20265336/147115919-035586f6-6eca-413f-b416-f234cd9ceacf.png">

# Sprint 77
- [x] No keyboard navigation for pagination. Once you click on a page you can't go to another page using only the keyboard.
<img width="1046" alt="Screen Shot 2021-12-13 at 4 25 53 PM" src="https://user-images.githubusercontent.com/39598672/145891442-428f449f-aa88-4a15-8ae0-fa96c268e127.png">

- [x] clicking on More does not show dropdown with the overflow items
<img width="1058" alt="Screen Shot 2021-12-13 at 5 51 11 PM" src="https://user-images.githubusercontent.com/39598672/145902041-1a4847dd-fdd1-417b-af9c-6bb17a45daf8.png">

**Comment by platon-rov** [comment]
@mikerodonnell89 did you have chance to check why we have these two approaches for tokenizer component, with and without horizontal scrolling?

**Comment by platon-rov** [comment]
Only platform issues left, unassigning myself.
