### ISSUE TITLE
Nice-To-Have Defect Hunting issues for Fundmantal-ngx 0.33.0. release

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#7551]
# Sprint 77
- [ ] Avatar gets focus in Bar component:
<img width="525" alt="Screen Shot 2021-12-13 at 11 49 45 AM" src="https://user-images.githubusercontent.com/39598672/145855720-6eb90bbc-196e-45e9-ac7e-e44d61fbd9e2.png">

- [ ] Vertical alignment for Bar component:
<img width="1227" alt="Screen Shot 2021-12-13 at 11 50 04 AM" src="https://user-images.githubusercontent.com/39598672/145855779-dc39ed08-5e4e-41f5-a654-0bcbd4661973.png">

- [ ] Carousel issues: 1. Check with the design if the buttons on hover should look like this. 2. Check the focus states. Should the whole element get a focus?
<img width="444" alt="Screen Shot 2021-12-13 at 12 05 21 PM" src="https://user-images.githubusercontent.com/39598672/145857382-6304c019-b35a-465c-b14d-868bbcae5d6b.png">
<img width="898" alt="Screen Shot 2021-12-13 at 12 09 00 PM" src="https://user-images.githubusercontent.com/39598672/145857389-2389cf40-9d77-4d6f-83f1-225ce650d67f.png">

- [ ]  Interactive list - third item does not get the proper active state when selected state is applied:
<img width="903" alt="Screen Shot 2021-12-13 at 2 11 05 PM" src="https://user-images.githubusercontent.com/39598672/145873952-bb060beb-026f-4ffc-9fe1-59657db825cb.png">
<img width="1043" alt="Screen Shot 2021-12-13 at 2 10 13 PM" src="https://user-images.githubusercontent.com/39598672/145873955-8f2af26a-b046-4cb0-b4bd-acec3b3ec7b5.png">

- [ ] List with Byline active state:
<img width="1211" alt="Screen Shot 2021-12-13 at 3 57 57 PM" src="https://user-images.githubusercontent.com/39598672/145887781-6d31384d-9461-43ae-9aa4-894b23b2adfd.png">

- [ ] Select semantic states messages too big and not per design and fund-styles:
<img width="1072" alt="Screen Shot 2021-12-13 at 4 50 58 PM" src="https://user-images.githubusercontent.com/39598672/145894752-86f0a550-09ae-4c1a-beb4-fe8d4e83943a.png">

- [ ] Platform value help dialog - button content densities do not match that of the application
<img width="1120" alt="Screen Shot 2021-12-14 at 5 33 42 PM" src="https://user-images.githubusercontent.com/2471874/146090068-7d5241f9-8542-4f3e-99cd-f845dafe2efc.png">

- [ ] Platform list, "action list item" examples - click a list item, then dismiss this alert:
<img width="464" alt="Screen Shot 2021-12-14 at 1 29 42 PM" src="https://user-images.githubusercontent.com/2471874/146058284-eb7cebd2-5081-4a84-99d7-6ea1b45fd3d5.png">
Then press arrow up or arrow down, usually the incorrect list item will receive focus.  But not always, so try doing this at different window scroll positions with different items focused.

- [ ] Need some margin here on the platform date picker examples: 
<img width="743" alt="Screen Shot 2021-12-14 at 12 49 12 PM" src="https://user-images.githubusercontent.com/2471874/146052530-73d3d9f9-a30a-48be-8442-93eb8fa6c88e.png">

- [ ] Platform input group - I think using "0.00" as the text addons is confusing here and "USD" or something would be more relevant 
<img width="676" alt="Screen Shot 2021-12-14 at 1 17 47 PM" src="https://user-images.githubusercontent.com/2471874/146056596-7cf3e512-cfbf-4254-b190-9c118e1e123b.png">

- [ ] Platform list, multi-selection example - focusing checkboxes then pressing the "shift" key can have strange results of shifting different items. Shouldn't do anything

**Comment by mikerodonnell89** [comment]
- [ ] Multi-input: [this PR](https://github.com/SAP/fundamental-ngx/pull/7588) allows the user to tab to the expand key to open the dropdown of selectable options. However the user then must shift+tab back to the input part of the multi-input, then press tab, to focus the first item in the list. Instead we should have an additional tab keypress, or down arrow press, focus the first item in the dropdown
