### ISSUE TITLE
When navigating in pagination a weird text is shown in body

### ISSUE THREAD

**Issue by biiit** [SAP/fundamental-ngx#7578]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
If navigating in pagination a weird text is appended in the `<body>`-tag which says `Page undefined is current page`.

#### Which versions of Angular and Fundamental Library for Angular are affected?
@fundamental-ngx/core : 0.32.5

#### If this is a bug, please provide steps for reproducing it.
1. Visit https://sap.github.io/fundamental-ngx/#/core/pagination
2. Open "Source Code" for the Basic Pagination example
3. Click on "StackBlitz"
4. Run the example on "StackBlitz"
5. Click on "Page 2"

#### Is there anything else we should know?
![Screen Shot 2022-01-20 at 09 47 43](https://user-images.githubusercontent.com/12843264/150304646-f24c8849-3499-4af7-b9f3-6843d06fcac2.png)

https://user-images.githubusercontent.com/12843264/150304775-09c5a748-8ed1-4c32-adc8-1ca4df360667.mov

**Comment by droshev** [comment]
@biiit We are about to release an [improved](https://fundamental-ngx.netlify.app/#/core/pagination) pagination. Meanwhile we will check that issue in the previous version.

**Comment by platon-rov** [comment]
@biiit are you okay if the fix will be provided for the refactored & updated pagination component (fiori 3 specs changed) for angular 13+ or do you need a backport for angular 12?

**Comment by biiit** [comment]
@platon-rov @droshev For us it would be fine if the fix is provided with the new pagination component. Any timeline on this?

**Comment by PabloMz85** [comment]
Hi,
I'm having the same issue both in dev and prod. @platon-rov @droshev it would be great to have a solution for Angular 13. Thank you
