### ISSUE TITLE
Defect Hunting for Sprint 80 - Lima

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7587]
Please list all the findings as a thread to this issue.

We will be testing getting inspired [Exploratory Testing Tours](https://github.com/SAP/fundamental-ngx/wiki/Exploratory-Testing-Tours)
- Landmark Tour
- Intellectual Tour
- Back-alley Tour
- Money Tour
- All-Nighter Tour
- Saboteur Tour
- Guidebook Tour
- Obsessive Compulsive Tour
- Supermodel Tour
- Rained-Out Tour
- Antisocial Tour

Browsers:
- MS Edge
- Firefox
- Safari
- Chrome

**Comment by mikerodonnell89** [comment]
- [ ] Multi-input: [this PR](https://github.com/SAP/fundamental-ngx/pull/7588) allows the user to tab to the expand key to open the dropdown of selectable options. However the user then must shift+tab back to the input part of the multi-input, then press tab, to focus the first item in the list. Instead we should have an additional tab keypress, or down arrow press, focus the first item in the dropdown

**Comment by InnaAtanasova** [comment]
- [ ] (Platform) Standard Combobox. Label and Input are not vertically aligned:
<img width="1187" alt="Screen Shot 2022-01-24 at 2 02 47 PM" src="https://user-images.githubusercontent.com/39598672/150847294-3ee9b830-d3f5-452a-a401-1a248f1b21f7.png">
- [ ] (Platform) Combobox with Two Columns example: the selected item is not fully displayed: 
<img width="890" alt="Screen Shot 2022-01-24 at 2 06 04 PM" src="https://user-images.githubusercontent.com/39598672/150847875-382d01aa-63bb-4458-9d89-c5fcab8f65f6.png">
- [ ] (Platform) Date Picker: the validation is not working properly. Invalid year, such as 202 or 20255 is not detected as invalid. 
<img width="395" alt="Screen Shot 2022-01-24 at 2 09 28 PM" src="https://user-images.githubusercontent.com/39598672/150848469-713e6fdb-4e9e-402b-9ce7-47cb9d106ab6.png">
<img width="414" alt="Screen Shot 2022-01-24 at 2 09 16 PM" src="https://user-images.githubusercontent.com/39598672/150848472-feb9d73e-0dc1-43ab-a6b3-b76f49d8aaf2.png">
- [ ] (Platform)  Internationalization of Date Picker - the validation is not working properly. Change the language to German, remove the last digit for the year, the field becomes red (invalid). Add the digit again. The field remains invalid. 
<img width="898" alt="Screen Shot 2022-01-24 at 2 13 52 PM" src="https://user-images.githubusercontent.com/39598672/150849135-bcea3202-c612-40b2-b181-7971f04bea95.png">
- [ ] (Platform)  List - Group header - the header gets a focus. Expected behaviour: the group header is not an interactive element and should not get a focus.
- [ ](Platform)  List - Single Selection - the radio button never indicates the item is selected 
<img width="917" alt="Screen Shot 2022-01-24 at 2 41 04 PM" src="https://user-images.githubusercontent.com/39598672/150852739-3b8604ba-365d-4841-8150-4fa123f9b11f.png">
- [ ] (Platform) Multi Input - user cannot enter a custom value. Expected behaviour: user should be able to type a value that is not available in the list of options, press Enter and this value is registered as a token. Check UI5 demo app for the correct behaviour. 
- [ ] (Platform) Textarea: the alignment of the label and the textarea is not correct:
<img width="1163" alt="Screen Shot 2022-01-24 at 3 07 45 PM" src="https://user-images.githubusercontent.com/39598672/150856716-39168ccc-9392-471d-9b4b-5cf15996c798.png">
- [ ] (Platform) Upload collection - inconsistent styling:
<img width="898" alt="Screen Shot 2022-01-24 at 3 11 25 PM" src="https://user-images.githubusercontent.com/39598672/150857296-f0c8908a-d421-4c34-bd99-4c44eeed6061.png">

**Comment by mikerodonnell89** [comment]
- [ ] Combobox (core): has the double focus outline again ![Screen Shot 2022-01-24 at 1 19 24 PM](https://user-images.githubusercontent.com/2471874/150858289-fc8b3317-3744-4ac7-989d-feb67d721f80.png)

- [ ] Combobox as searchfield (core): right side of dropdown, corners have weird borders (this issue also existed in the past)
![Screen Shot 2022-01-24 at 1 20 21 PM](https://user-images.githubusercontent.com/2471874/150858420-6ea5562b-29a5-4d91-9c8c-24cf7b20db57.png)

- [ ] Datepicker / datetimepicker null validity (core): When clearing the datepicker input, the input is shown as invalid immediately.  For datetimepicker, this happens on blur. Should be consistent across both components

**Comment by InnaAtanasova** [comment]
- [ ] (Core) Avatar Group - inconsistent behaviour for the focus. Navigating the component with keyboard only is almost impossible. At some point the focus disappears or stops working (it gets trapped between JS and CJ avatars)
<img width="973" alt="Screen Shot 2022-01-24 at 3 37 40 PM" src="https://user-images.githubusercontent.com/39598672/150860807-6d15580c-7c07-44aa-a267-46526d06f6a7.png">

- [ ] (Core) Busy Indicator as wrapper - there's a focus around the wrapper and I am not sure why it's there:
<img width="1037" alt="Screen Shot 2022-01-24 at 3 44 01 PM" src="https://user-images.githubusercontent.com/39598672/150861771-fbf9eda8-25a8-4906-8d8a-9f3dc8e957b6.png">
<img width="889" alt="Screen Shot 2022-01-24 at 3 45 20 PM" src="https://user-images.githubusercontent.com/39598672/150861842-9b96b809-6b5e-45e4-ac37-437cee4e0231.png">

- [ ] (Core) Date Picker in Reactive Form - the validation is not working properly:
<img width="1030" alt="Screen Shot 2022-01-24 at 3 49 39 PM" src="https://user-images.githubusercontent.com/39598672/150862532-e49f9e8e-dbe0-43fb-81d2-215fc9a17ab8.png">

- [ ] (Core) Select - wrong position of the button:
<img width="518" alt="Screen Shot 2022-01-24 at 4 07 35 PM" src="https://user-images.githubusercontent.com/39598672/150865002-a3094681-c1c1-4c76-b83a-17d8db7de64d.png">

- [ ] (Core) Step Input: similar issue to the one above:
<img width="810" alt="Screen Shot 2022-01-24 at 4 13 35 PM" src="https://user-images.githubusercontent.com/39598672/150865869-c9060c35-97c3-4580-af4a-dc0079d3866a.png">

**Comment by mikerodonnell89** [comment]
- [ ] Need some margin here
![Screen Shot 2022-01-24 at 3 02 20 PM](https://user-images.githubusercontent.com/2471874/150872424-69e36de3-63ca-40ec-863c-c7e5eac3ac9f.png)

- [ ] Pagination, mobile - when changing the dropdown from 4 to 8 or 4 to 16, the width of the page # input shrinks by 2px
![Screen Shot 2022-01-24 at 3 06 36 PM](https://user-images.githubusercontent.com/2471874/150873159-3330f3b9-edc2-4959-a3b4-7ee5e5787e6e.png)
![Screen Shot 2022-01-24 at 3 06 30 PM](https://user-images.githubusercontent.com/2471874/150873161-18cb733a-7e4a-4d1c-bff3-7c323bfa2ec7.png)

- [ ] Docs - these buttons are not aligned in the shellbar in compact mode
![Screen Shot 2022-01-24 at 3 09 29 PM](https://user-images.githubusercontent.com/2471874/150873291-563ea2ce-7cc7-4e87-b81b-f3508be151d9.png)

- [ ] Vertical nav (core): icons misaligned, wrong size
![Screen Shot 2022-01-24 at 3 14 05 PM](https://user-images.githubusercontent.com/2471874/150873815-d8e8ff1c-e0ba-41d9-b072-d240b10cec8e.png)

**Comment by N1XUS** [comment]
- [ ] Docs: examples with ViewEncapsulation.None interfere with default styles across whole documentation:
Button from step input:
![image](https://user-images.githubusercontent.com/6586561/150972100-0393e744-735a-4892-9eea-422682cb07fc.png)
Has been modified by platform-menu example
![image](https://user-images.githubusercontent.com/6586561/150972017-e529bd52-198c-4d3c-a7e7-3510f2299f5f.png)

**Comment by platon-rov** [comment]
Core

* [ ] (Core) Carousel With Error, should not have tab stop 

![image](https://user-images.githubusercontent.com/20265336/150971984-af86703a-2264-422c-8d17-6e0fd99dec93.png)

* [ ] (Core) Date Time Picker, (Core) Time, (Core) Time Picker, scroll not working for time (hours, minutes, period) but it's meant from the ux

![image](https://user-images.githubusercontent.com/20265336/150972903-d1cb602a-12d1-4e45-ab54-095f697e8d80.png)

* [ ] (Core) Feed List Item Actions, bad RTL support

![image](https://user-images.githubusercontent.com/20265336/150973469-433f0f7b-955a-4dd5-9c02-ec141ed7bc35.png)

* [ ] (Core) Grid List, no keyboard arrows support

![image](https://user-images.githubusercontent.com/20265336/150974014-36841f16-6e7e-49c1-be90-aef93990fb74.png)

* [ ] (Core) Input Group, actually fiori 3 specs doesn't have any input component with icon (addon) inside of the input. https://github.com/SAP/fundamental-ngx/issues/7546

![image](https://user-images.githubusercontent.com/20265336/150974378-eea7d881-dbe0-4594-bfa6-3b6459b75ae2.png)

* [ ] (Core) Status Indicator, has tab stop without a reason (or event on click needed)

![image](https://user-images.githubusercontent.com/20265336/150977137-46763e17-d8a3-401a-8035-d26f7da7fa16.png)

* [ ] (Core) Table, header menu items don't have appropriate cursor (pointer).

![image](https://user-images.githubusercontent.com/20265336/150977725-1d98a82c-4531-418c-9a48-aa39677706a7.png)

* [ ] (Core) Table, pagination example looks ugly

![image](https://user-images.githubusercontent.com/20265336/150978254-347e6d27-6279-4ebe-be97-d4e55d7c0af8.png)

* [ ] (Core) Tabs, focus styles almost not visible for icon mode

![image](https://user-images.githubusercontent.com/20265336/150978522-ceda845f-c9de-46df-9962-9ac8884a4440.png)

* [ ] (Core) Tile, has unneeded tab stop (or event on click needed)

<img width="269" alt="Screenshot 2022-01-25 at 14 41 11" src="https://user-images.githubusercontent.com/20265336/150978953-7c85d68a-97ab-4312-b011-f4d785bb084b.png">

* [ ] (Core) Timeline, when collapsed item expanded line doesn't looks adequate

![image](https://user-images.githubusercontent.com/20265336/150979303-f35ccd34-d2d3-4181-a525-7912b360354a.png)

* [ ] (Core) Fixed Grid Layout, DnD works unstable

https://user-images.githubusercontent.com/20265336/150980228-df4ccc76-21c3-4757-909c-3fbbed3bacd3.mov

**Comment by platon-rov** [comment]
Platform

* [ ] (Platform) List, no radio button dot

![image](https://user-images.githubusercontent.com/20265336/150992219-d5d9eae6-1ed3-4f20-ba85-204af0e3ccad.png)

* [ ] (Platform) Multi Input, deleting not working

![image](https://user-images.githubusercontent.com/20265336/150993261-65c26ed3-4542-4d44-bd6a-745ef6bfe932.png)

* [ ] (Platform) Table, columns width change on toggling groups/tree rows, filtering

![image](https://user-images.githubusercontent.com/20265336/150995933-764f39e3-c600-4668-9be2-acd44fc3f05d.png)

* (Platform) Table, no outer borders, outer border present for header cell mock

![image](https://user-images.githubusercontent.com/20265336/150996576-cd42d803-7311-4d7c-904d-e2c39fd887bc.png)

* (Platform) Upload Collection, pagination looks ugly, can be one lined

![image](https://user-images.githubusercontent.com/20265336/150997010-3d616486-5f86-4009-b728-3e851937989b.png)

* [ ] (Platform) Smart Filter Bar, filtering not working in the table (column header)

![image](https://user-images.githubusercontent.com/20265336/150997252-e01c6b46-29a5-48ad-8342-11c1707be614.png)

**Comment by droshev** [comment]
Platform Multi Input issues transferred into https://github.com/SAP/fundamental-ngx/issues/7606

**Comment by droshev** [comment]
Blockers:

- [ ] Combobox (core): has the double focus outline again ![Screen Shot 2022-01-24 at 1 19 24 PM](https://user-images.githubusercontent.com/2471874/150858289-fc8b3317-3744-4ac7-989d-feb67d721f80.png)

- [ ] (Core) *bug* Busy Indicator as wrapper - there's a focus around the wrapper and I am not sure why it's there:
<img width="1037" alt="Screen Shot 2022-01-24 at 3 44 01 PM" src="https://user-images.githubusercontent.com/39598672/150861771-fbf9eda8-25a8-4906-8d8a-9f3dc8e957b6.png">
<img width="889" alt="Screen Shot 2022-01-24 at 3 45 20 PM" src="https://user-images.githubusercontent.com/39598672/150861842-9b96b809-6b5e-45e4-ac37-437cee4e0231.png">

- [ ] (Core) *bug* Select - wrong position of the button:
<img width="518" alt="Screen Shot 2022-01-24 at 4 07 35 PM" src="https://user-images.githubusercontent.com/39598672/150865002-a3094681-c1c1-4c76-b83a-17d8db7de64d.png">

- [ ] (Core) *bug*  Step Input: similar issue to the one above:
<img width="810" alt="Screen Shot 2022-01-24 at 4 13 35 PM" src="https://user-images.githubusercontent.com/39598672/150865869-c9060c35-97c3-4580-af4a-dc0079d3866a.png">

- [ ] Need some margin here
![Screen Shot 2022-01-24 at 3 02 20 PM](https://user-images.githubusercontent.com/2471874/150872424-69e36de3-63ca-40ec-863c-c7e5eac3ac9f.png)

- [ ] Pagination, mobile - when changing the dropdown from 4 to 8 or 4 to 16, the width of the page # input shrinks by 2px
![Screen Shot 2022-01-24 at 3 06 36 PM](https://user-images.githubusercontent.com/2471874/150873159-3330f3b9-edc2-4959-a3b4-7ee5e5787e6e.png)
![Screen Shot 2022-01-24 at 3 06 30 PM](https://user-images.githubusercontent.com/2471874/150873161-18cb733a-7e4a-4d1c-bff3-7c323bfa2ec7.png)

- [ ] Vertical nav (core): icons misaligned, wrong size
![Screen Shot 2022-01-24 at 3 14 05 PM](https://user-images.githubusercontent.com/2471874/150873815-d8e8ff1c-e0ba-41d9-b072-d240b10cec8e.png)

- [ ] Core Bar in RTL mode: button icon not centered:
![image](https://user-images.githubusercontent.com/6586561/150971642-f4998731-4339-4ffe-9c65-26ffeea9f3c6.png)

* [ ] (Core) Tabs, focus styles almost not visible for icon mode

![image](https://user-images.githubusercontent.com/20265336/150978522-ceda845f-c9de-46df-9962-9ac8884a4440.png)

* [ ] (Core) Tile, has unneeded tab stop (or event on click needed)

<img width="269" alt="Screenshot 2022-01-25 at 14 41 11" src="https://user-images.githubusercontent.com/20265336/150978953-7c85d68a-97ab-4312-b011-f4d785bb084b.png">

* [ ] (Core) Timeline, when collapsed item expanded line doesn't looks adequate

![image](https://user-images.githubusercontent.com/20265336/150979303-f35ccd34-d2d3-4181-a525-7912b360354a.png)


* [ ] (Core) Input Group, actually fiori 3 specs doesn't have any input component with icon (addon) inside of the input. https://github.com/SAP/fundamental-ngx/issues/7546

![image](https://user-images.githubusercontent.com/20265336/150974378-eea7d881-dbe0-4594-bfa6-3b6459b75ae2.png)

* [ ] (Core) Status Indicator, has tab stop without a reason (or event on click needed)

![image](https://user-images.githubusercontent.com/20265336/150977137-46763e17-d8a3-401a-8035-d26f7da7fa16.png)

* [ ] (Core) Table, header menu items don't have appropriate cursor (pointer).

![image](https://user-images.githubusercontent.com/20265336/150977725-1d98a82c-4531-418c-9a48-aa39677706a7.png)

* [ ] (Core) Table, pagination example looks ugly

![image](https://user-images.githubusercontent.com/20265336/150978254-347e6d27-6279-4ebe-be97-d4e55d7c0af8.png)

* [ ] (Core) Date Time Picker, (Core) Time, (Core) Time Picker, scroll not working for time (hours, minutes, period) but it's meant from the ux

![image](https://user-images.githubusercontent.com/20265336/150972903-d1cb602a-12d1-4e45-ab54-095f697e8d80.png)

* [ ] (Platform) Smart Filter Bar, filtering not working in the table (column header)

![image](https://user-images.githubusercontent.com/20265336/150997252-e01c6b46-29a5-48ad-8342-11c1707be614.png)

**Comment by platon-rov** [comment]
* [ ] (Platform) Combobox, States, wrong width of the message

![image](https://user-images.githubusercontent.com/20265336/151581835-8528da4f-25a7-459f-a8c4-e606f90e14a8.png)
