### ISSUE TITLE
string in multi-combobox need to be localized

### ISSUE THREAD

**Issue by JeffChern** [SAP/fundamental-ngx#7610]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
how can we handle the string # more to different locales?
![Screen Shot 2022-01-25 at 1 49 44 PM](https://user-images.githubusercontent.com/5530226/151065705-81fff390-aeb1-4a00-ab9b-8567c8324edd.png)

**Comment by mikerodonnell89** [comment]
Closing as this will be fixed as part of 8731
