### ISSUE TITLE
Core Fixed Grid Layout DnD not responsive

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7617]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

* [ ] (Core) Fixed Grid Layout, DnD works unstable

https://user-images.githubusercontent.com/20265336/150980228-df4ccc76-21c3-4757-909c-3fbbed3bacd3.mov

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

**Comment by platon-rov** [comment]
Related https://github.com/SAP/fundamental-ngx/issues/5511
