### ISSUE TITLE
Fix switch tile breaking changes

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7628]
The switch tile no longer works with the [breaking changes](https://github.com/SAP/fundamental-ngx/wiki/0.33.0-Breaking-Changes) introduced in the new Fundamental version.

For some reason, I am also experiencing this issue on old Fundamental versions when I reinstall my node modules through `npm install`. Therefore, it becomes increasingly difficult to develop.
![image](https://user-images.githubusercontent.com/40032066/151987454-5ed44bda-918d-49bc-b288-8864965d6a6f.png)

It would be great if you could fix the issue in the following [branch](https://github.tools.sap/dxp/template-ui/pull/204). To reproduce it, locally execute the following [branch](https://github.tools.sap/dxp/template-ui/pull/204), open the [Template UI](https://sap.dev.dxp.k8s.ondemand.com/projects/01fgv1yekxw7vfpxtbxdsbmega/components?modal=%2Fprojects%2F01fgv1yekxw7vfpxtbxdsbmega%2Ftemplates%3F~mode%3Dmodal&modalParams=%7B%22title%22:%22Create%20Component%20from%20Template%22%7D), click on Java or Fiori template and then click on Run.

![image](https://user-images.githubusercontent.com/40032066/151404970-85c47c04-4183-44d9-99fc-454bbaa82bb1.png)

**Comment by droshev** [comment]
@MichaelBaySAP did you migrate to the latest?

**Comment by MichaelBaySAP** [comment]
Hi Mladen,
I just migrated to the latest version 0.33.0-rc.304 and I am getting the same error.
Best, Michael

**Comment by MichaelBaySAP** [comment]
This bug meanwhile transferred to our dev environment, despite us not having updated the version. Currently, development on Dev environment is blocked because the bug is not resolved.

**Comment by MichaelBaySAP** [comment]
Fixed after call
