### ISSUE TITLE
Breadcrumb overflow dropdown should has same sorting order as Fiori Guidelines

### ISSUE THREAD

**Issue by mengbingguo** [SAP/fundamental-ngx#7631]
When breadcrumb overflows, some items will go to an overflow dropdown.
The items in the dropdown should be sorted in a way that the breadcrumb root is on the bottom. Like in [Fiori Guidelines](https://experience.sap.com/fiori-design-web/breadcrumb/#responsiveness)

**In Fundamental NGX**
![image](https://user-images.githubusercontent.com/75482561/151569225-ad4cce1f-e198-4fcb-a473-006fedf422c7.png)

**Fiori Guidelines**
![image](https://user-images.githubusercontent.com/75482561/151569613-53d548af-aac9-4392-9d40-c4d78ddd6675.png)

**Comment by droshev** [comment]
Another improvement is to have the menu on mobile to switch to a dialog https://experience.sap.com/fiori-design-web/breadcrumb/
