### ISSUE TITLE
bug(platform): table - column's width issue

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#7648]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Currently, if table column has width set in `%` and table has `0` width - we will see a lot of errors in the console. 

![image](https://user-images.githubusercontent.com/20265336/149344854-8799672a-0444-4fcd-a67c-34ef7906fab2.png)

Table can be initialized and not rendered due to many reasons (it's inside the not active tab, for example) and it shouldn't come up with endless errors in the console.

The fix is to return `auto` as a column width and skip all the calculations if table doesn't have width.

Recent PR https://github.com/SAP/fundamental-ngx/pull/7540 fixed an issue, but the approach was to slow, so we have to come up with another solution

**Comment by platon-rov** [comment]
I tested the case the error came from (table inside not expanded tab) and it seems to be working.

Let's keep this issue open for a while.
