### ISSUE TITLE
chore: running only affected e2e

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#7649]
Current setup of running e2e tests is costly and inefficient, as we are executing all of them on each CI run. Currently e2e step takes about 30 minutes in parallel and more than 70-80 in total.

Instead we should run checks only for affected projects: most of the changes we do, are related only to really small amount of packages

####  - Refactor e2e structure. 
Tests for each package should be moved to a separate lib, that can be tested apart. 
Desired structure:
```
/e2e
    /utils (lib)
    /core
        /core-{{libName}}-e2e (lib)
        /core-{{libName}}-e2e (lib)
        ....
    /platform
        /platform-{{libName}}-e2e (lib)
        /platform-{{libName}}-e2e (lib)
        ....
```
Since we're using WebdriverIO as a test runner, which is not supported by Nx, we need to look into configuring custom `builder` in `angular.json` for running e2e through Nx. Maybe something like this https://github.com/migalons/angular-wdio-builder. Another option is to run it as custom commands https://nx.dev/executors/run-commands-builder for each package.

Additionally we have to ensure that running e2e for each library apart won't take too much time for bootstrapping test dependencies.

#### - Make docs for each package a separate package by itself

Currently `docs` is just a one big application. Because of this it's not possible to track the source of changes there. Since our e2e are being executed against docs, we have to build a proper dependency graph, so whenever there's a change in docs of any component, corresponding e2e are executed. 

Each docs-lib along with `docs` app should be put as an implicit dependency to the configuration of each corresponding e2e library.

Desired structure:
```
/apps
    /docs // <= only entry points here
        /app.module.ts
        /app.component.ts 
/libs
    /docs
        /common
            (current "/apps/docs/documentation" and "/apps/docs/schema" contents)
        /component-docs // <= libs for each package
            /core
            /platform
            /fn
```
Since `docs` is already an app, we may require to move `component-docs` outside of it while making them a libraries, because otherwise it will build incorrect graph. This is quite a big change, but seems as an only proper way to fix the dependencies. 

As an alternative to modifying `docs` app I've also played around with making a script for manual tracking of files in docs, that were changed, so they can be manually associated with e2e. I don't like it because this way doesn't really look solid to me. 

You can play around with my code in this branch `ds/e2e-enhancements`:
1. checkout the branch
2. try to modify something in docs
3. execute `npx ts-node --project tools/tsconfig.tools.json ./tools/scripts/run-e2e-by-affected-docs.ts`
4. observe only affected e2e were executed

**Comment by platon-rov** [comment]
Definitely must have!

But before start working on this we should decide whether we will support existing & write new e2e, as for now we don't have QA engineers at all in the teams that works on the project.

**Comment by platon-rov** [comment]
implemented.
