### ISSUE TITLE
Carousel bug

### ISSUE THREAD

**Issue by aberikashvili** [SAP/fundamental-ngx#7655]
**Issue 1:** 
Step 1. Leave 2 cards
Step 2. Scroll left with mouse, until cards get hidden
Step 3. release mouse
Step 4. click on card

**Issue 2:**
Step 1. Leave 2 cards, so that there not to be enough space for both cards.
Actual behavior: Both arrows disappearing and one dots stays
Expected behavior: When all cards are visible in the area and there's nothing to scroll, **arrows and dots, both should be disappeared**. When all cards aren't visible in the area, it means there's someting to scroll, **so arrows should stay visible and dots too**.

https://stackblitz.com/edit/angular-raxcqd-bhpq1p?file=src%2Fapp%2Fcarousel-dynamic-items-example.component.ts

**Comment by platon-rov** [comment]
Are you talking about this issue? (see video)

Uploading Screen Recording 2022-02-24 at 12.34.10.mov…
