### ISSUE TITLE
Breaking change new version: the switch tile is not rendered properly if I decrease the screen size

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7659]
the switch tile is not rendered properly if I decrease the screen size
![image](https://user-images.githubusercontent.com/40032066/151996632-a20bf337-1b62-46e8-b5a3-96f603f26e0f.png)

The issue can be reproduced through installing the latest Fundamental version or through checking out the following [branch](https://github.tools.sap/dxp/template-ui/pull/192/files). 

Open [Dev](https://sap.dev.dxp.k8s.ondemand.com/projects/01fgv1yekxw7vfpxtbxdsbmega/components?modal=%2Fprojects%2F01fgv1yekxw7vfpxtbxdsbmega%2Ftemplates%3F~mode%3Dmodal&modalParams=%7B%22title%22%3A%22Create%20Component%20from%20Template%22%7D), open DXP Micro Front End template. Click on Run.

**Comment by droshev** [comment]
same as the other issues
