### ISSUE TITLE
Breaking change new version: the values are not loaded properly on change (Repository name should be filled with the value of component name)

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7660]
![image](https://user-images.githubusercontent.com/40032066/151998652-79ace492-4bd3-4403-8444-972bc2fdafa5.png)

The issue can be reproduced through installing the latest Fundamental version or through checking out the following [branch](https://github.tools.sap/dxp/template-ui/pull/192/files). 

Open [Dev](https://sap.dev.dxp.k8s.ondemand.com/projects/01fgv1yekxw7vfpxtbxdsbmega/components?modal=%2Fprojects%2F01fgv1yekxw7vfpxtbxdsbmega%2Ftemplates%3F~mode%3Dmodal&modalParams=%7B%22title%22%3A%22Create%20Component%20from%20Template%22%7D), open DXP Micro Front End template. Click on Run. Enter an arbirtary component name and click on Next.

It would help to fix it in this [branch ](https://github.tools.sap/dxp/template-ui/pull/192/files)if possible as otherwise there will be lots of merge conflicts.

**Comment by droshev** [comment]
@MichaelBaySAP this should not be reported in the external repo. This should stay in DXP(if it is a bug)
