### ISSUE TITLE
Breaking change new version: Select in WizardGenerator no longer works

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#7667]
When I click on Select, it does not open

![image](https://user-images.githubusercontent.com/40032066/152174240-d2d4f919-21ce-4fb0-a601-7945384fb3a3.png)

The issue can be reproduced through installing the latest Fundamental version or through checking out the following [branch](https://github.tools.sap/dxp/template-ui/pull/192/files). 

Open [Dev](https://sap.dev.dxp.k8s.ondemand.com/projects/01fgv1yekxw7vfpxtbxdsbmega/components?modal=%2Fprojects%2F01fgv1yekxw7vfpxtbxdsbmega%2Ftemplates%3F~mode%3Dmodal&modalParams=%7B%22title%22%3A%22Create%20Component%20from%20Template%22%7D), open DXP Micro Front End template. Click on Run.

**Comment by droshev** [comment]
@MichaelBaySAP questions about internal projects should have be logged in the internal repo

**Comment by MichaelBaySAP** [comment]
Thanks I reopened and labeled them
