### ISSUE TITLE
Fiori Next Next

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7670]
**Note:** Please put your name BEFORE you start working on a component and mark as the done (checkbox) when the PR for the component is merged.

Tasks related to the component design updates:

- [ ] bring the latest fn package (update the API, update the Breaking Changes (class names, html structure, etc.)
Update existing components
- [x] Button - @g-cheishvili 
    - [ ] Update according to new styleguide
- [ ] Text Field
- [x] Search - @N1XUS 
- [x] Slider - @N1XUS 
- [ ] Tabs - @g-cheishvili 
- [x] Tag - @g-cheishvili 
- [x] Toggles - Steven
    - [ ] switch - 
    - [ ] checkbox - 
    - [ ] radio - 

Enhance existing components
- [x] Button types and semantics -  @g-cheishvili 
- [ ] Menu Button - 
- [ ] Split Button - 
- [ ] Range slider - talk to Inna before you start working on it
- [ ] Tabs - semantic, types, instance tabs, tab container, multi-instance  - @g-cheishvili 
- [ ] Inputs 
    - [ ]  Select - @StevenZhao318
    - [x] Text Input - @mikerodonnell89 
    - [ ] Combo Box - 
    - [ ] Step Input - 
    - [ ] Multi-Input - @mikerodonnell89 
    - [ ] Search - @StevenZhao318
    - [ ] Token - 
    - [ ] Textarea - @StevenZhao318

Implement new components
- [ ] Dialog - 
- [ ] message box -
- [x] Segmented button -  @g-cheishvili 
- [x] List - [PR](https://github.com/SAP/fundamental-ngx/pull/7767)  @g-cheishvili 
- [ ] Illustrated Messages
- [ ] Shell - 
- [ ] Page - footer, title, group title, toolbar
- [---] Cards - the html and classes will be updated in styles
- [ ] Forms - 
- [x] Avatar - @N1XUS
- [x] Progress Bar - @N1XUS
- [x] Generic Tag - @N1XUS

newly added
- [x] Message Strip (Messaging page) - @N1XUS 
- [x] Object Status (Messaging page) - @N1XUS
- [x] Info Label (Messaging page) - @N1XUS
- [ ] Rating Indicator - 
- [x] Notification (Messaging page) - @N1XUS
- [x] Message Toast (Messaging page) - @N1XUS 
- [ ] Popover (Popups) - @platon-rov 
- [ ] Table

**Comment by N1XUS** [comment]
Tabs, Split button, Menu button, Menu, Select, Combobox, Multi-input are dependent on Dropdown/Popup. So they should be postponed until popover component is implemented

**Comment by droshev** [comment]
we merged all implemented components
