### ISSUE TITLE
fd-file-input onSelect Event not triggered when selecting same file multiple times

### ISSUE THREAD

**Issue by scamastral** [SAP/fundamental-ngx#768]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

The onSelect event is not triggered when the same file is selected again after closing the file-input.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

Angular 7
Fundamental NGX 0.4.5

#### If this is a bug, please provide steps for reproducing it.

Example:
- Select file `example.png` --> onSelect Event triggered correctly
- Select same file `example.png` again --> onSelect Event is never triggered

#### Please provide relevant source code if applicable.

n/a

#### Is there anything else we should know?

To give you some context of the scenario where we experienced this bug:

In a messaging scenario, you send / attach a file with the fd-file-input. If you want to select & send the same file again you are not able to because of this bug.

**Comment by MattL75** [comment]
Pretty sure this is standard behaviour for the html native file input. You could clear the component using the clear() method, which should fix your issue.

I would prefer not straying from the native input behaviour, unless you have some suggestions or ideas for this?

**Comment by scamastral** [comment]
Using the clear() method fixed our issue, thanks! 👍
