### ISSUE TITLE
Remove all instances of is[Component] inputs in the library

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#771]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
This is very unclean. Let's remove it. There's a couple instances I can think of.

- Popover's *isDropdown*. Can be solved by having an actual dropdown component.
- Calendar's *isDateTimePicker*. Can be solved by making the keyboard logic more generic.
- Time's *isDateTimePicker*. Doesn't seem to do anything?

More may be added if I find them.

**Comment by JKMarkowski** [comment]
Just FYI, I will take a look on it.
