### ISSUE TITLE
Alignment of checkbox and its label

### ISSUE THREAD

**Issue by biiit** [SAP/fundamental-ngx#773]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
The checkbox should always stay at the same position, left of the label.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular 7.2
fundamental-ngx 0.4.5
fiori-fundamentals 1.5.7

#### If this is a bug, please provide steps for reproducing it.
The checkbox is first displayed above the label.
1. Check the box, the checkbox is displayed left of the label
2. Click again the box, the checkbox is again above the label.

#### Please provide relevant source code if applicable.
```javascript
<div fd-form-item [isCheck]="contractElement.value === 'true'" *ngIf="contractElement.type === 'CHECKBOX'">
  <input fd-form-control [formControlName]="contractElement.id" [id]="contractElement.id" [name]="contractElement.id" [type]="'checkbox'" (click)="checkBoxChanged(f[contractElement.id])">
  <fd-form-label [forValue]="contractElement.id">{{contractElement.title}}</fd-form-label>
</div>
```

before
![Screen Shot 2019-05-03 at 09 51 21](https://user-images.githubusercontent.com/12843264/57125422-b2d8a380-6d89-11e9-977e-827e1989040e.png)

after
![Screen Shot 2019-05-03 at 09 51 31](https://user-images.githubusercontent.com/12843264/57125431-bbc97500-6d89-11e9-8df7-1e0b6e8ea4de.png)

**Comment by MattL75** [comment]
Hey @biiit! Thanks for reporting an issue.

Could you provide a bit more context? This isn't happening on our end so we'd like to see if maybe there's additional details we're missing. What does the parent element of the form item look like?

**Comment by biiit** [comment]
@MattL75 you are right, there is something weird in my example. I copied the example from the docs and I see this works. I figured then that I misused the `[isCheck]="true"`. This needs to be always set to `true`. I wanted to use it for setting the initial value of the checkbox.
