### ISSUE TITLE
Defect Hunting for Sprint 81 - Santiago

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7744]
Please list all the findings as a thread to this issue.

We will be testing getting inspired [Exploratory Testing Tours](https://github.com/SAP/fundamental-ngx/wiki/Exploratory-Testing-Tours)
- Landmark Tour
- Intellectual Tour
- Back-alley Tour
- Money Tour
- All-Nighter Tour
- Saboteur Tour
- Guidebook Tour
- Obsessive Compulsive Tour
- Supermodel Tour
- Rained-Out Tour
- Antisocial Tour

Browsers:
- MS Edge
- Firefox
- Safari
- Chrome

**Comment by mikerodonnell89** [comment]
- [ ] Action bar (examples) - I am wondering if the save and cancel buttons need to be switched around, throughout the rest of our libraries the affirmative/primary buttons go on the left

- [ ] Core, alert, inline alert - dynamic example is open on page load and does not automatically disappear as the text implies. Closing the alert and clicking the button to open the alert causes strange behavior where the alert will stay up for different lengths of time
![Screen Shot 2022-02-14 at 2 07 20 PM](https://user-images.githubusercontent.com/2471874/153946577-5c0fd588-2a29-445a-8c15-0dea9a36f725.png)

- [ ] Core, Dialog, form example - this "disabled textarea" is not disabled
![Screen Shot 2022-02-14 at 4 40 14 PM](https://user-images.githubusercontent.com/2471874/153965321-720d8ac2-9d9b-4712-b909-a749a13d3039.png)

- [ ] Core multiinput - open the popover using the button on the right - you can no longer use the keyboard down arrow or tab keys to access items in the popover

- [ ] Core select - should the control be changing width when the selection changes? 

- [ ] Core mobile wizard - why are these examples so tall ![Screen Shot 2022-02-14 at 5 07 34 PM](https://user-images.githubusercontent.com/2471874/153967849-d3ef4a00-a757-441f-93b8-56492c1f6123.png)
