### ISSUE TITLE
Defect Hunting for Sprint 82

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#7815]
#### Components to be tested:
- [ ] core Calendar - Mike
- [ ] core Menu - Mike
- [x] core Grid List - Inna
- [x] platform Smart Filter Bar - Inna
- [x] core Upload Collection - Inna
- [x] core Avatar - Inna
- [ ] core Table - Mike
- [x] core List - Inna
- [x] core Message Box - Inna
- [x] core Time Picker - Inna

**Comment by InnaAtanasova** [comment]
- [ ] Avatar - zoom icon is not clickable. The zoom icon should trigger an event specified by the user and the Avatar itself should get a ficus. The zoom icon should have a pointer cursor. UI5 example:
<img width="314" alt="Screen Shot 2022-02-28 at 12 23 29 PM" src="https://user-images.githubusercontent.com/39598672/156029993-92f86d49-6fe3-4f35-b4d6-bb39017541dd.png">

**Comment by mikerodonnell89** [comment]
- [ ] Datepicker, reactive form - focusing the input and even changing the value in the input does not consider the input "touched", only considered touched when the popover is openee

**Comment by InnaAtanasova** [comment]
- [ ] The links in the documentation for Link are not working. List (Standard & Byline) documentation pages are not loaded.
<img width="235" alt="Screen Shot 2022-02-28 at 1 58 44 PM" src="https://user-images.githubusercontent.com/39598672/156042391-6cd453d0-47f1-44bf-aaa4-c1b4b209fe63.png">

**Comment by InnaAtanasova** [comment]
- [ ] Action List - the `Show More` item gets double focus. To reproduce: navigate the list with the Tab key. When you reach `List Item 5`, tab and the `Show More` item will get focus. Tab again and the same element is focussed for second time:
<img width="1227" alt="Screen Shot 2022-02-28 at 2 37 30 PM" src="https://user-images.githubusercontent.com/39598672/156047620-d2fc9037-f4cb-468b-954f-43c60014ae81.png">

**Comment by InnaAtanasova** [comment]
- [ ] Time Picker - not sure if it's a bug or desired behaviour. To reproduce, use the keyboard to open the dropdown menu. Use the tab key to switch from hours to minutes to seconds. You need to press the Tab key **twice** to switch from one to another. Also the buttons (arrows) never get focus.

<img width="562" alt="Screen Shot 2022-02-28 at 3 09 36 PM" src="https://user-images.githubusercontent.com/39598672/156051565-c282a172-c97d-4df5-8781-0a1d19b1a364.png">

**Comment by InnaAtanasova** [comment]
- [ ] Time Picker - disabled state. The user can still select and copy the text from the disabled input:
<img width="537" alt="Screen Shot 2022-02-28 at 3 16 47 PM" src="https://user-images.githubusercontent.com/39598672/156052612-6d96e42e-3788-4f1b-92f9-9c606e6c3107.png">

For reference check Bootstrap example of disabled input: https://getbootstrap.com/docs/4.0/components/forms/#disabled-forms
In this case there are no pointer events.

**Comment by InnaAtanasova** [comment]
- [ ] Time Picker Locale: shouldn't the hours and minutes be translated?
<img width="569" alt="Screen Shot 2022-02-28 at 3 21 28 PM" src="https://user-images.githubusercontent.com/39598672/156056077-f4f2bc4b-8731-44c3-823a-ba28072af0c3.png">
 

- [ ] Time Picker Locale: validation problem. To reproduce:
1. Change the language to **bg**
2. remove the `ч.` part of the input. The field becomes red (invalid)
3. put back the `ч.` part of the input. The field remains invalid.

Step 1:
<img width="465" alt="Screen Shot 2022-02-28 at 3 21 35 PM" src="https://user-images.githubusercontent.com/39598672/156056360-b66937a1-1424-47e4-bcee-bccee2aa51b5.png">


Step 2:
<img width="853" alt="Screen Shot 2022-02-28 at 3 22 25 PM" src="https://user-images.githubusercontent.com/39598672/156056408-cd709e84-3baf-48cd-93bb-fa95719ab879.png">

Step 3:
<img width="880" alt="Screen Shot 2022-02-28 at 3 22 35 PM" src="https://user-images.githubusercontent.com/39598672/156056467-1b91e9f8-d6ae-49d5-bd88-bbf5325d70bf.png">

**Comment by InnaAtanasova** [comment]
- [ ] Upload collection: truncation issues:
1. File name is not truncated
<img width="1376" alt="Screen Shot 2022-02-28 at 4 29 14 PM" src="https://user-images.githubusercontent.com/39598672/156062153-ab28c6a3-df67-4cc8-b4ce-9a640866bb6c.png">

2. Second object status just shows `...` when it's very long
<img width="1380" alt="Screen Shot 2022-02-28 at 4 31 42 PM" src="https://user-images.githubusercontent.com/39598672/156062280-16fdb14d-460b-40c6-901d-3672091afda8.png">

3. First object status is not truncated:
<img width="1382" alt="Screen Shot 2022-02-28 at 4 32 07 PM" src="https://user-images.githubusercontent.com/39598672/156062336-28e7ef4e-53ce-49cd-9884-b512b991eca8.png">

**Comment by InnaAtanasova** [comment]
- [ ] Smart Filter - truncation problems

- Why is the first input truncated when there's enough space to fit it?
<img width="1221" alt="Screen Shot 2022-02-28 at 4 36 41 PM" src="https://user-images.githubusercontent.com/39598672/156063133-9de1d812-44c3-4289-b161-fba4c6b5fc2d.png">

- These 2 are the same type of inputs but look different
<img width="1271" alt="Screen Shot 2022-02-28 at 4 36 56 PM" src="https://user-images.githubusercontent.com/39598672/156063275-841a0966-9c7d-4d15-92bd-c53d12ac39e1.png">
 
- This input is also truncated immediately even if there's enough space. The second row inputs are the same and they behave differently:
<img width="1203" alt="Screen Shot 2022-02-28 at 4 37 34 PM" src="https://user-images.githubusercontent.com/39598672/156063528-781c335a-d026-4a36-9c60-9e0804e3a675.png">

**Comment by InnaAtanasova** [comment]
- [ ] Grid List - focus problems: In my opinion these elements should not be focussed. 

<img width="1183" alt="Screen Shot 2022-02-28 at 5 00 57 PM" src="https://user-images.githubusercontent.com/39598672/156066560-f1eb5f35-b99d-43a6-bd89-708c30ccb072.png">
<img width="1159" alt="Screen Shot 2022-02-28 at 5 01 18 PM" src="https://user-images.githubusercontent.com/39598672/156066555-8b08795c-ee07-4d0d-9f7a-c9803c8fc179.png">
<img width="1202" alt="Screen Shot 2022-02-28 at 5 01 05 PM" src="https://user-images.githubusercontent.com/39598672/156066556-8e44bb9b-dc86-4b0a-8476-159e5a092a5b.png">
<img width="1152" alt="Screen Shot 2022-02-28 at 5 01 26 PM" src="https://user-images.githubusercontent.com/39598672/156066559-ac183dff-1b53-443b-bf02-82845a5902c4.png">
