### ISSUE TITLE
bring more convenience for  i18n in fundamental-ngx components

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#7824]
Currently fundamental-ngx doesn't have unified convenient approach of working with translations:
- core components use inputs 
- platform components use `@angular/localize` package

This brings several issues.

Firstly, since there's no unified approach for working with translations, there's an ambiguity in what approach should be used in a particular case

Secondly, usage of `@angular/localize` brings certain difficulties for those, who does not use it in their apps. Popular packages, like `ngx-translate` or `transloco` packages use json files for translations, which is absolutely incompatible with angular's internal approach. Because of this, in fact, users are forced to use `@angular/localize` in their apps to be able to translate UI components. 

Instead of this we should be technology agnostic in what translation utilities are used.
This can be done by using internal translation vocabulary for our components. It can work similarly to transloco/ngx-translate: we will have a json/js objects, that contain all strings needed for UI components. This data will be supplied to components by using DI mechanism:
- we should have predefined vocabularies for popular languages (en/de/fr/es/ru/ua/it etc)
- if needed, users will be able to override vocabulary for a certain language on any injection level by overriding the injection token

This is a **breaking change** for platform components, that rely on `@angular/localize` tool. However, negative impact should be minimal, if we supply translations for necessary languages.

This tool can be used by core, platform and experimental packages to standardise the requirements.

**Comment by droshev** [comment]
Let's think about that and come up with the next steps
