### ISSUE TITLE
Platform Component(s) around Color Picker

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7827]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.

Implement new components in platform package:
- [ ] color picker
- [ ] color picker popover
- [ ] color palette

The goals of the task:
- to adopt under the hood ui5 web components for those ones
- document how that would work
- list all issues or future problems
- test theming, content density, other cross-component features

**Comment by mikerodonnell89** [comment]
closing this, no longer relevant
