### ISSUE TITLE
Migrate Theming Service

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#7828]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.

The current theming service is implemented as part of @fundamental-nhx/core where we have hardcoded few themes and add 2 css files per theme. The goal of this task is to use the ui5 theming instead. They will handle the `theming-base-content` css files for us. What will be missing is how to pass our delta css file to ui5 theming.

**Comment by mikerodonnell89** [comment]
closing this, no longer relevant
