### ISSUE TITLE
Hardcoding of css color creates issue when switched to High Contract Black and High Contrast White Theme

### ISSUE THREAD

**Issue by 22shubham22** [SAP/fundamental-ngx#7831]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.

When theme is changed from normal to high contrast black , there are certain components on which theme is not applied , like selections in checkboxes and radio buttons , icons due to hardcoding of css colors.
Also we see weirds spacing around button which is not seen in normal theme.

Below are attached screenshots -:

![image](https://user-images.githubusercontent.com/60786471/156501790-7ae14fb3-6fa9-4b7b-baac-857102c61cbb.png)

![image (1)](https://user-images.githubusercontent.com/60786471/156501797-17f1cde8-ac77-4c2a-b6c9-31f45e192791.png)

![image (2)](https://user-images.githubusercontent.com/60786471/156501808-a5e76475-01b6-4384-a249-73d27594d1ed.png)

![image (3)](https://user-images.githubusercontent.com/60786471/156501816-f9a9c582-56e9-4ae5-ba37-3870c317349d.png)

![image (4)](https://user-images.githubusercontent.com/60786471/156501821-beb8d947-cc89-4122-bcec-a14d86988e3e.png)

<img width="578" alt="Screenshot 2022-03-08 at 10 42 21 AM" src="https://user-images.githubusercontent.com/60786471/157176417-0230670b-833d-4b44-9af1-1685caee8ad5.png">

In the screenshot below , if we remove the cursor on this filter tile, it will not visible:

<img width="1536" alt="Screenshot 2022-03-08 at 10 38 40 AM" src="https://user-images.githubusercontent.com/60786471/157176623-a0fc3d8d-e0b1-403a-92df-ba32117dba7b.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Ngx version : 0.32.7
Angular 12.2.1

#### If this is a bug, please provide steps for reproducing it.

use query params to switch to hcb theme : <Link>?sap-theme=sap_fiori_3_hcb

**Comment by droshev** [comment]
@22shubham22 I tried to reproduce those issues on our doc page but I wasn't able to reproduce
<img width="343" alt="Screen Shot 2022-04-03 at 16 31 41" src="https://user-images.githubusercontent.com/4380815/161447326-d5e0bb26-9415-4aad-ae81-29d67f97ee92.png">
<img width="625" alt="Screen Shot 2022-04-03 at 16 29 01" src="https://user-images.githubusercontent.com/4380815/161447328-1e507043-886c-4be1-93f4-eb1cb9b53c27.png">


I guess there is something specific in your application

**Comment by 22shubham22** [comment]
We're using theme parameters which is common across all sap applications -> ?sap-theme=sap_fiori_3_hcb
