### ISSUE TITLE
Truncate the title in fd-breadcrum if it's too long

### ISSUE THREAD

**Issue by JeffChern** [SAP/fundamental-ngx#7840]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Ideally if the title is more than specific length, we should truncate and show title-truncated...
![Screen Shot 2022-01-25 at 11 47 36 AM](https://user-images.githubusercontent.com/5530226/156831615-4e932ac9-cb1c-42dc-974f-13ec7e7a3684.png)
![Screen Shot 2022-01-25 at 11 50 18 AM](https://user-images.githubusercontent.com/5530226/156831616-17aa0e87-e49a-4b58-af0e-dee7c9859947.png)

#### Please provide relevant source code if applicable.
<fd-breadcrum>

**Comment by g-cheishvili** [comment]
I do not think this should be something specifically developed for breadcrumbs. it should be either directive, either pipe, separately, which just will happen to be usable in fd-link
@mikerodonnell89 @shrvr

**Comment by shrvr** [comment]
solved with this: https://github.com/SAP/fundamental-ngx/issues/8239
