### ISSUE TITLE
Menu popover on top of dialog

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#7853]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.
 if the menu item doesn't have anchor link, then on click of item, the popover doesn't close and it comes on top of a dialog as seen in picture. Do we need to programmatically close the popover or is there another way to handle the case where we want to open a dialog on click of menu item? This is particularly an issue in our case when we have a column for popovers in all the table rows.

![image](https://user-images.githubusercontent.com/29952750/156972336-91a44406-4310-40dc-98df-f3a2b89746c6.png)

#### Please provide relevant source code if applicable.
Visible in the image attached

**Comment by g-cheishvili** [comment]
I suppose you could do

```html
<fd-menu #menu>
    <li fd-menu-item (click)="menu.close()">
        <a fd-menu-interactive>
            <span fd-menu-title>Option 1</span>
            <button fd-button glyph="upload" fdType="transparent" (click)="openDialog(confirmationDialog)"></button>
        </a>
    </li>
    <li fd-menu-item>
        <a fd-menu-interactive>
            <span fd-menu-title>Option 2</span>
        </a>
    </li>
    <li fd-menu-item>
        <a fd-menu-interactive>
            <span fd-menu-title>Option 3</span>
        </a>
    </li>
</fd-menu>
```

**Comment by droshev** [comment]
@AleenaSA did you try what @g-cheishvili suggested?

**Comment by AleenaSA** [comment]
Hi, yes the solution works! Thanks @g-cheishvili
