### ISSUE TITLE
<fdp-multi-comboxbox>: [selectedItems] property populated but view is not rendering selected values

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#7862]
## Is this a bug, enhancement, or feature request?
Bug

## Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Our app is currently using v0.31.x, but issue also found on latest release v0.33.x

## If this is a bug, please provide steps for reproducing it.
- As a user, they can only see a small set of values (from the whole data source value set) upon opening the dropdown
 
- User could not scroll the dropdown to see the rest of the data source values, but they could type to search and find their desired values. It appears that the component is not rendering all the data source values upon opening the dropdown. Is this the expected behavior of the component (due to perf concern if the data source set is too large)?
 
- When a user has typed and selected a matching value, the (selectionChange) event is triggered, and as per our business logic requirement, we will need to perform validation API call and then refresh the component view (basically doing some re-initialization)
 
- Now, after refreshing the view, even though we have already chosen to bind the [selectedItems] property to a certain array value, we could not see these multi-select values being rendered inside the input box.
However, if user now types certain keyword and it matches with their previously selected choices, we can see that from opening the dropdown, these previous values are pre-selected and highlighted (since we have bound the ‘selectedItems’ properties already). Like below:
<img width="378" alt="Screen Shot 2022-03-08 at 5 03 56 PM" src="https://user-images.githubusercontent.com/22454655/157543283-37989ed5-800a-46c2-821a-0ef3e0207b7a.png">

- So our main question is: since we have the data already bound to the component’s ‘selectedItems’ property, why isn’t the view rendering these values? Basically, the model is there, but the view is not updated or rendered

## Is there anything else we should know?
Similar issues were also found for the \<fd-multi-input\> component

**Comment by aberikashvili** [comment]
The behavior described in this issue, isn't a bug, multi combobox data source has the limit to show 12 best matches.
As we agreed through mail thread discussion, I introduced limitless option in the PR https://github.com/SAP/fundamental-ngx/pull/7967
