### ISSUE TITLE
Defect hunting sprint 83

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#7877]
Platform multi-combobox: as I select items in the dropdown, the multi-input moves to the right (note popover not aligned with input)

![Screen Shot 2022-03-14 at 2 59 50 PM](https://user-images.githubusercontent.com/2471874/158260517-27bd9442-8df7-4641-8118-36aa2f2cf949.png)

**Comment by platon-rov** [comment]
Fixed with https://github.com/SAP/fundamental-ngx/commit/de0c273e1becf5099f9621049a7f483bbffd80a5
