### ISSUE TITLE
Focus does not shift to the popover menu button.

### ISSUE THREAD

**Issue by rohitbhoite93** [SAP/fundamental-ngx#7882]
#### Is this a bug, enhancement, or feature request?
Accessibility bug

#### Briefly describe your proposal.
This issue is observed in Android mobile app which uses NGX library. Accessibility tool used is talkback on android phone

When popover menu is opened then focus should shift to menu button and items within popover.

Current Behaviour: When popover menu is opened with talkback feature enabled, focus is not shifting to popover menu items. We also tried  adding [focusTrapped]="true" [focusAutoCapture]="true" properties in html. But focus is not shifting to popover menu.

Expected behaviour : Focus should shift to popover menu items and read them sequentially using android talkback.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular :11.2.14
NGX library version : 0.32.1

#### If this is a bug, please provide steps for reproducing it.
1. open popover menu component using tap on android device(talkback enabled).
2. Swipe left/right on screen(Swipe is required to move to next element) and try to read popover menu items using talkback.

**Comment by Lukakatche** [comment]
hi @rohitbhoite93! I was investigating this issue. For me, popover works fine on the Samsung Galaxy device. both in chrome and Samsung internet. https://streamable.com/pnd8yc 
could you please specify which browser/device you're using? 
Thank you!
