### ISSUE TITLE
bug(core,platform): momentjs deprecated now

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#7904]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

MomentJS library used in MomentDateTimeAdapter is deprecated.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest on 22th of March, 2022.

#### Is there anything else we should know?

We can start using dayjs to avoid implementing (i.e. spending time) our own on top of native. Also, native has some limitations, especially, about locales, so i think it's not the option here. From what i see dayjs is the smallest alternative but its api very close to the momentjs and some not included initially features can be achieved using plugins.

Another option - date-fns, that, accordingly to the comparison table, has all the features but is a way bigger by its size, has less locales than dayjs and its api haven't been designed to mimic momentjs.

Here is the whole comparison table: https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md#feature-parity

**Comment by dmitry-stepanenko** [comment]
I think we should go with dayjs in this case. I think date-fns is really convenient, but in our case it's important to provide as much locales as we can. 

@droshev @g-cheishvili @N1XUS any thoughts?

**Comment by platon-rov** [comment]
Possible approaches, pros and cons.

## **dayjs**

Pros:
* more locales
* similar api to the momentjs, less work to migrate to

Cons: 
* is not tree shakable, but only 2kb gzipped

## **date-fns**

Pros:
* is tree shakable

Cons:
* less locales
* different api, more work to migrate to

About the rest both libraries are pretty similar, needed features present in both. 

cc @droshev

**Comment by platon-rov** [comment]
After migrating to **dayjs** or **date-fns** it makes sense to left only one date time adapter in out library. As native one, **fdDateTimeAdapter** has less functionality and takes time to enhance it, fix bugs in it, etc so i vote for keep only custom one, **dayjs** or **date-fns**, depends on which one we choose.

cc @droshev

**Comment by dmitry-stepanenko** [comment]
Yes, totally agree. The fact we have two doesn't bring any value and is only confusing
