### ISSUE TITLE
step-input-control is showing an extra div with latest value of step-input control in the dom

### ISSUE THREAD

**Issue by lalitgoyal2005** [SAP/fundamental-ngx#7907]
#### Is this a bug, enhancement, or feature request?
bug?

#### Briefly describe your proposal.
there shouldn't be any extra div in the dom which shows the current value of step-input control

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fundamental-ngx/core: ^0.33.1
angular: 13.2.2

#### If this is a bug, please provide steps for reproducing it.

- have a step-input control inside angular CDK scroll
- try to change the value of the step-input control
- observe that there will be one more div element that will be shown in the dom all the time.

**However importing @angular/cdk/a11y-prebuilt.css in the .scss file fixes this issue. is it intended to import @angular/cdk/a11y-prebuilt.css explicitly or this is a bug?**

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/6291212/159921466-e2cc957c-6322-4ab1-b56f-e819f18f8bb8.png)

**Comment by droshev** [comment]
@lalitgoyal2005 what is your concern with this `div`?
it is used with accessibility purposes and it should not be visible.
