### ISSUE TITLE
Search bar behavior is different in for firefox and chrome.

### ISSUE THREAD

**Issue by 22shubham22** [SAP/fundamental-ngx#7908]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Search bar behaviour is different in different browsers.

1. Chrome (x appears when we enter some text and on pressing enter searches for the text)
2. Firefox and safari ( x does not appear when we type something and on pressing enter nothing happens )

Chrome 

![Screenshot (386)](https://user-images.githubusercontent.com/60786471/160054244-e84781a1-7b86-4e93-826a-1d2814159679.png)

Firefox & Safari 

![Screenshot (387)](https://user-images.githubusercontent.com/60786471/160054274-3bc05f12-921c-4958-9d6c-2e0ed0d31996.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 12.2.1
Ngx version : 0.32.7

#### If this is a bug, please provide steps for reproducing it.

bug can be noticed while using search bar across different browser .

**Comment by 22shubham22** [comment]
Also I see missing interactive states on the cross mark which reported earlier , inside search bar  as can be seen from the video 

https://user-images.githubusercontent.com/60786471/160537293-3aa8c648-f9bc-4db9-b326-097f46bc252c.mp4

.

It should be something like this : (like how the behavior is for search magnifier icon) 

ON PRESS:

![image-2021-10-12-16-15-35-525](https://user-images.githubusercontent.com/60786471/160537341-9061279d-44ed-49b3-81fd-09c341b6bb4c.png)

**Comment by D034394** [comment]
Hi @droshev, I'd like to support this request since we have the same issue at the moment (relevant for our SAP FSM 2205 release). So, please provide a solution asap if possible. Many thanks!

**Comment by droshev** [comment]
@22shubham22 I tested in Safari, Firefox, and Chrome:
<img width="1197" alt="Screen Shot 2022-04-07 at 14 44 34" src="https://user-images.githubusercontent.com/4380815/162274707-fb66a9ad-b642-42d1-a47f-053839997003.png">

<img width="1209" alt="Screen Shot 2022-04-07 at 14 44 43" src="https://user-images.githubusercontent.com/4380815/162274732-00f5c90b-73af-4faa-b985-62fa83d05231.png">

<img width="2067" alt="Screen Shot 2022-04-07 at 14 44 51" src="https://user-images.githubusercontent.com/4380815/162274761-54fb87d4-da22-481f-a89d-7d80a3989905.png">

and I am able to see the clear button

**Comment by 22shubham22** [comment]
https://user-images.githubusercontent.com/60786471/162278889-394e67ca-6d79-441f-8016-ac87c8d2d116.mp4

Hi @droshev , in recording you can see the behavior of search bar is different across different browser , the cross mark is not appearing in firefox but appering in chrome.

This is the search bar i'm using as per documentation : https://sap.github.io/fundamental-ngx/#/core/input-group

**Comment by droshev** [comment]
@22shubham22 It is good we cleared this out. I would say for you (platform) search field would be the best option in terms of features being offered.
Regarding the (core) Input Group [Search](https://fundamental-ngx.netlify.app/#/core/input-group) you would need to implement the login from the search field. The X button you see in the second example(only under Chrome) comes from the native browser implementation. If you want to use this component then you need to set the input `glyph` to `decline` as it is in the upper example from your video.

Let us know if you need more input

**Comment by 22shubham22** [comment]
> @22shubham22 It is good we cleared this out. I would say for you (platform) search field would be the best option in terms of features being offered. Regarding the (core) Input Group [Search](https://fundamental-ngx.netlify.app/#/core/input-group) you would need to implement the login from the search field. The X button you see in the second example(only under Chrome) comes from the native browser implementation. If you want to use this component then you need to set the input `glyph` to `decline` as it is in the upper example from your video.
> 
> Let us know if you need more input

Thanks a lot for your help. This new component resolves all of our issue around this search bar.
