### ISSUE TITLE
feat(docs): universal version switcher

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-ngx#7926]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
In general, when versions are deployed, we need to update version switcher manually with latest list of the versions. Plus when you switch from that switcher, it opens a new tab with desired version and url will not get transitioned. For instance if you're looking at the Button in v0.20 and want to see how it was in 0.19, and switch, you'll have to navigate to Button docs manually. Plus every version only has previous versions in dropdown. Meaning you can not view next versions.
Netlify has API, which gives you ability to fetch prod endpoints, but only with private API key. Their deployment version IDs are different from commits. So no way to find out deployment version from public information.

Proposal:
Build small application, which will contain only top bar, with version switcher and iframe, with current selected version's deploy url. Save user navigations between component docs and when user switches version try and save state when showing other version of it. This way every old version will have link to new one and new ones to every old versions. Switch between them will be seamless.
One gotcha: API key probably should be hidden from front-end. I think we should use Next.js and their SSR friendliness. As far as I'm aware netlify works with Next.js very well.
So in future fundamental-ngx.netlify.app would not target to fundamental-ngx repo, but to that small navigator app and that navigator app would be manager for the fundamental-ngx deployments

#### Please provide relevant source code if applicable.
related issue #7719

**Comment by platon-rov** [comment]
Plus one level of complexity, I'm not sure about that. I think it can be done easier. 

After deploying we can have a workflow step that will make an api call to the netlify and get the url of the deployment. That url will be added to the url collection that stored here, in repository. Then, in our doc angular application we will just grab it, parse and show appropriate values in the dropdown.

In that way we won't be tied up to the wrapper app that may crash and make documentation app unreachable. We won't have separate title bar for the version dropdown, where dropdown itself should be the ngx component.

**Comment by g-cheishvili** [comment]
@platon-rov that will work, but there will be issue with next versions. All previous versions will not have reference to the next versions

**Comment by platon-rov** [comment]
@g-cheishvili why not? we will create a service that will fetch data from the file in the repository that will be updated with new versions thru the script. 

yea, it won't work for the deployments that were deployed before the service creation but there is a similar thing for the wrapper-based approach, customers who are using direct urls to get to the documentation of the old versions won't see the wrapper.

by the way we can apply fix with the service to every previous major version (luckily, there are not much) then include deployment urls to the collection. as for me that way is still preferable over the adding additional level of complexity.

**Comment by g-cheishvili** [comment]
@platon-rov that really sounds good. We can try that I suppose
