### ISSUE TITLE
Carousel bug in v0.33.5

### ISSUE THREAD

**Issue by AleenaSA** [SAP/fundamental-ngx#7932]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
In carousel with multiple item component ( when there are three cards). when your screen is small and you scroll all the way to last card. and then increase the size width, the cards on the left are not visible and the navigation button also disappears
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 13.2
"@fundamental-ngx/platform": "0.33.5",

#### If this is a bug, please provide steps for reproducing it.
the latest carousel with multiple item component example from the [ngx doc](https://sap.github.io/fundamental-ngx/#/core/carousel)

#### Video Recording of the issue
[https___angular-qbenny.stackblitz.io - Google Chrome 2022-04-01 12-37-09.zip](https://github.com/SAP/fundamental-ngx/files/8395443/https___angular-qbenny.stackblitz.io.-.Google.Chrome.2022-04-01.12-37-09.zip)

**Comment by aberikashvili** [comment]
Hi @AleenaSA, isn't this fix delivered yet or you found it again in new version? 
Please share stackblitz link, I'll check it

**Comment by AleenaSA** [comment]
This is reproducible using the example for multiple item carousel present in the fundamental ngx-core [document ](https://sap.github.io/fundamental-ngx/#/core/carousel). surprisingly, i found it only when there were 3 cards
[https___angular-vtwkzv.stackblitz.io_#_ - Google Chrome 2022-04-20 11-27-21.zip](https://github.com/SAP/fundamental-ngx/files/8518647/https___angular-vtwkzv.stackblitz.io_._.-.Google.Chrome.2022-04-20.11-27-21.zip)

**Comment by AleenaSA** [comment]
any update?
