### ISSUE TITLE
String Localization Issues with Platform Approval-flow Component

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#7952]
#### Is this a bug, enhancement, or feature request?
- Bug

#### Briefly describe your proposal 
Please refer to the JIRA tickets attached below for more details
- These strings should be externalized and be output to the _**message.xlf**_ file while running the 'ng extract i18n' command
- When there is only 1 member, the word 'member' should be in singular case

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
- Issues were found on latest release: **v0.33.5**

#### If this is a bug, please provide steps for reproducing it.
- Import the approval-flow component from F-NGX platform, launch the Angular app in pseudo-locale 'eu', and should be able to see the issues

#### Related SAP Ariba JIRA tickets (with screenshots of the issues)
- https://product-jira.ariba.com/browse/SS-34274
- https://product-jira.ariba.com/browse/SS-34275
- https://product-jira.ariba.com/browse/SS-34276

<img width="1512" alt="Screen Shot 2022-03-31 at 2 24 52 PM" src="https://user-images.githubusercontent.com/22454655/161627769-fc29f69c-82fb-4265-8317-eec11c7598b6.png">
<img width="1507" alt="Screen Shot 2022-03-31 at 2 24 26 PM" src="https://user-images.githubusercontent.com/22454655/161627785-1d14460a-0418-44f1-a88d-5f373c77a70b.png">

**Comment by dmitry-stepanenko** [comment]
Hi Yixuan! Thank you for raising this. We're currently migrating away from `@angular/localize` package. Here's the ticket https://github.com/SAP/fundamental-ngx/issues/7824

Once it's resolved, we will be able to improve translation logic here and in other places too.

**Comment by mikerodonnell89** [comment]
Closing, fixed with #7900
