### ISSUE TITLE
Searching issue in fdp-approval-flow

### ISSUE THREAD

**Issue by Peeeeeeter** [SAP/fundamental-ngx#7953]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.
When search Users in fdp-approval-flow, it is not able to do a real API search, instead, this component is doing a interval filtering on the data it has, so in the case a customer has large user data set, it is not possible to load all users initially, so in this case lazy loading is running, the getUsers api will only return top 3000 user and then passed to **ApprovalDataSource** that fdp-approval-flow interact with.

Then there is no way for customer to query users that out of the initial set.   fdp-approval-flow should provide a way to make this feasible.
proposal: 1.add a new interface that got trigger when searching in ApprovalDataSource, so we can give a concrete implementation to do a API search and update the datasource.
2. Or, fdp-approval-flow should emit the event out to the container component so we can handle.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Issues were found on latest release: v0.33.5

#### If this is a bug, please provide steps for reproducing it.
<img width="736" alt="Screen Shot 2022-04-04 at 2 59 02 PM" src="https://user-images.githubusercontent.com/11143509/161640087-372f1530-7117-424d-ae6a-f1182c0171a1.png">
<img width="767" alt="Screen Shot 2022-04-04 at 2 59 32 PM" src="https://user-images.githubusercontent.com/11143509/161640092-a9a95d2d-4a59-4b1c-9968-05153730d418.png">
#### 
Please provide relevant source code if applicable.

<img width="891" alt="Screen Shot 2022-04-04 at 3 13 23 PM" src="https://user-images.githubusercontent.com/11143509/161640720-20e32e4e-f7b9-4067-9d90-c38490010deb.png">

As you can see, the provided interface doesn't support run additional searching. the component is assuming that all data was contained already inside itself, but his is not always the case.

**Comment by Peeeeeeter** [comment]
Thanks for the answering, I will try this works or not, and will provide an update here soon.

**Comment by fkolar** [comment]
All the data driven components, were designed to work with large data sets so we have `DataSource`, which is always specific to the components (ComboboxDS, TableDS, etc.. ) and `DataProviders`, which can be used across all the different DataSources. 


I believe you are using default implementation of DataProvider which works with Arrays, so you fetch everything and pass this whole payload into the Default DP and this is why you are seeing this behavior.  

At the time of implementing this there was no standardised API so the idea was that each Application team is able to implement their own. 

If your API is unified across all the services, then I would create more generic DP e.. :

```ts
class EntityDataProvider implements DataProvider {
     

}
```
I would assume you have some state management in place or at least some registry so you are able to retrieve connection based on the entity Type (name).
