### ISSUE TITLE
bug in Datetime Picker if drag hour, minutes or second 

### ISSUE THREAD

**Issue by FedchyshynV** [SAP/fundamental-ngx#7959]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
I got incident  from support, it reproducible on old and new versions.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
11-13

#### If this is a bug, please provide steps for reproducing it.
 drag hour, minutes or second and put when it be 0.
 on console you see: "ERROR Error: Cannot read properties of undefined (reading 'value')"
 and data will be previous.

#### Please provide relevant source code if applicable.

` activeChangedHandle(output: PanEndOutput): void {

        const array = this.items.toArray();
        let index: number = array.findIndex((__item) => __item === output.item) + this.offset;

        if (index > array.length) {  !!!!!!!!!!!!!!!!!!!!!!!bug here
            index = index - array.length;
        }

        const _item = array[index];

        this._activeValue = _item.value;

        this.activeValueChange.emit({
            value: this._activeValue,
            after: output.after
        });

        this._activeCarouselItem = _item;
    }`

#### Is there anything else we should know?
 it can be fixed if you will change "> to >=" in **if block** 
 because when you put 0 index will be  24 for hours
 and array.length the same 24
 here you get undefined const _item = array[index];
 error will be here this._activeValue = _item.value ('Cannot read properties of undefined');
 
 ![image](https://user-images.githubusercontent.com/17510642/161755048-52e5832b-2334-41ff-8e20-7f35d3bc091a.png)

**Comment by g-cheishvili** [comment]
@FedchyshynV Thank you, it was very helpful
