### ISSUE TITLE
bug(core,platform): calendar, pickers wrong header when in months, years range selection mode

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#7963]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

* Header should be different when selecting months.

Current:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/20265336/161950390-3e0f2279-da09-4138-aa5f-cc4ca766227b.png">

Specs:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/20265336/161950430-2b52a222-8481-4c74-8a5c-3eda3f2c0746.png">

* Header should be different when selecting range of years.

Current: 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/20265336/161955462-7ed2a0fb-823e-472c-9fb3-7cf1034332b0.png">

Specs:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/20265336/161955502-8e27c927-ae32-4230-b163-6067d05c9dfb.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.34.3-rc.7 

#### If this is a bug, please provide steps for reproducing it.

Go in the month selection mode here https://fundamental-ngx.netlify.app/#/core/calendar#standard

**Comment by mikerodonnell89** [comment]
Where are those screenshots coming from? Our current implementation is all good with the design specs on the wiki
