### ISSUE TITLE
fdp-table with grouping performs very slow

### ISSUE THREAD

**Issue by tomsawdayee** [SAP/fundamental-ngx#7969]
I'm using "@fundamental-ngx/platform": "0.33.5"
I'm trying to use the fdp-table component with grouping feature as described here, in an Angular application -

https://sap.github.io/fundamental-ngx/#/platform/table#groupable
When grouping by a certain column, the performance is very bad and takes too much time.
See in the example page, there's generated violation in chrome's console, and this is with a very small amount of items.
When running this example with a dataset of ~200 entries, each group takes a few seconds. Even the collapse\expand action is very slow.

To Reproduce

1. Go to https://sap.github.io/fundamental-ngx/#/platform/table#groupable
2. Click on 'Group' button to group by an element, then expand\collapse a grouped item
3. See violation issues in chrome debugger

Screenshot
![image](https://user-images.githubusercontent.com/15984790/162324973-27258b77-ac31-49e0-b51c-c70ecf6aa8e6.png)

**Comment by mikerodonnell89** [comment]
Can not recreate on the current version - @tomsawdayee please reopen if this is persisting for you
