### ISSUE TITLE
Button group component issues

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#8]
- [ ] the UI is broken if we mix the size of the buttons within one group so i guess the size could be part of the group. It will avoid repetition as well
- [ ] can't we have only 1 directive for the buttons type and it can be set on the group level instead of the current repetition on each button?

**Comment by droshev** [comment]
@mikerodonnell89 is this still valid?

**Comment by MattL75** [comment]
Closing, if I understand the issue this is not valid anymore.
