### ISSUE TITLE
Can not define testid for OK button in MessageBox

### ISSUE THREAD

**Issue by ninasim** [SAP/fundamental-ngx#8004]
Hi,
we have one message box that is shown as follows:
 openMessage(
    type: MessageBoxType,
    showSemanticIcon: boolean = true,
    title: string,
    message: string,
    closeCallback?: any
  ): void {
    const messageBoxRef = this.messageBoxService.open(
      {
        title,
        content: message,
        approveButton: 'Ok',
        approveButtonCallback: () => {
          if (closeCallback !== undefined) {
            closeCallback();
          }
          messageBoxRef.close('Approved');
        },
        closeButtonCallback: () => {
          if (closeCallback !== undefined) {
            closeCallback();
          }
          messageBoxRef.dismiss('Dismissed');
        },
      },
      {
        type,
        showSemanticIcon: true
      }
    );
  }

We have written integration tests for our scenario. While implemented the test we used the id for the OK button that was '#fd-button-bar-id-0', today the id is different '#fd-button-bar-id-1'. 
Can we set testid for message box ok button, so we do not rely on the id of the component.
We are using Cypress for our integration tests.

Best Regards,
Nina

**Comment by dmitry-stepanenko** [comment]
@ninasim added `id` property to the config. However, I would recommend you to consider using smarter cypress selectors to grab elements by their content. 

For example, you can define custom cypress command like this (not tested)
```
Cypress.Commands.add('getByContent', (identifier: string, content: string) => {
  return cy
    .get(identifier)
    .then((items) => Array.from(items).find((b) => b.innerText === content));
});

```

More details about custom commands https://docs.cypress.io/api/cypress-api/custom-commands
