### ISSUE TITLE
enhancement: remember last applied settings for documentation website

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#8007]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
Currently, if user selects different content density or theme, and goes to different documentation section (jumps from core to platform), those settings are being reset to default.
I would suggest to store those settings somewhere locally so that even with jumping across different libs, it will still apply previously selected config.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current
#### If this is a bug, please provide steps for reproducing it.
1. Go to https://fundamental-ngx.netlify.app/#/core/home
2. Change theme
3. From library selector, select 'Platform'

ER: Selected theme is preserved
AR: Theme has being reset to defaults.

**Comment by g-cheishvili** [comment]
Both theme and Content density has been updated to act this way
