### ISSUE TITLE
fix(platform): list component selection

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#8008]
#### Is this a bug, enhancement, or feature request?
bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Platform list component doesn't work properly with radio buttons and multi selection:
- architecture is poor, list component manages native properties of list items
- if enter or space buttons are used for selection, further arrow navigation is broken
- radio buttons doesn't work at all

**Comment by g-cheishvili** [comment]
If we will manage to properly organize into separate package fn development, then these types of issues will be breeze to fix
