### ISSUE TITLE
bug: FDP Dynamic Page / FD Tab List: `tabChange` event triggered on scroll

### ISSUE THREAD

**Issue by MalteBellmann** [SAP/fundamental-ngx#8050]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
When using the FDP Dynamic Page or the FD Tab List, the `tabChange` event is triggered on the first scroll on the tab even when `[stackContent]="false"` is set.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "13.1.3",
"@fundamental-ngx/core": "0.33.7",
"@fundamental-ngx/platform": "0.33.7",
#### If this is a bug, please provide steps for reproducing it.
1) Go to  https://fundamental-ngx.netlify.app/#/platform/dynamic-page#tabbed
2) open the devtools
3) open the `Default tabs example` example
4) see the message `tab changed to tab_1` in the console (expected)
5) adjust the width of the window to make sure you can scroll
6) Scroll
7) see the message `tab changed to tab_1` in the console again, not expected, the tab did not change

**Comment by mikerodonnell89** [comment]
this appears to be fixed in the current RC

**Comment by MalteBellmann** [comment]
Yes, with 0.36.0-rc.40 this is working now for non-stacked tabs. However, now the opposite problem appears: With stacked tabs, we don't get an event anymore when we scroll down to the second tab: 
0.36.0-rc.40: https://fundamental-ngx.netlify.app/#/platform/dynamic-page#tabbed Stacked Tab example: no tabChanged event when scrolling
vs. 
0.34.2: https://624793d2f1d02d000925c339--fundamental-ngx.netlify.app/#/platform/dynamic-page#tabbed Stacked Tab example: we get the tabChanged event when scrolling down to the second tab

**Comment by mikerodonnell89** [comment]
Thank you @MalteBellmann I think this PR should fix it https://github.com/SAP/fundamental-ngx/pull/8637
