### ISSUE TITLE
The variables need to be part of the strings.

### ISSUE THREAD

**Issue by JeffChern** [SAP/fundamental-ngx#8063]
#### Is this a bug, enhancement, or feature request?
- bug
#### Briefly describe your proposal.
The variables need to be part of the strings.
It's hard for localization team to translate only 'items selected' and 'item selected' Although it looks right for English plural and singular, it's hard to fully translated to other locales. It'll be better if we can use a full sentence.

#### If this is a bug, please provide steps for reproducing it.

Steps for Minerva:
1. Create a guided sourcing project > Full project
2. Create a task
3. Associate the doc
4. Create an approval task
5. Add a step
6. Select A user
7. Select two users
8. Observe the issue

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/5530226/166745633-e1e7c157-afda-4a9e-9bd7-c34466226bbf.png)
![image](https://user-images.githubusercontent.com/5530226/166745647-656392c5-7b01-4a35-b603-dc760a7f6859.png)
Related SAP Ariba JIRA tickets (with screenshots of the issues)
https://product-jira.ariba.com/browse/SS-34275

**Comment by mikerodonnell89** [comment]
Closing as this was addressed in #7900
