### ISSUE TITLE
submenu opened out of visible area

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#8072]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

submenu can not be click on certain screens since submenu is always placed to the of menu. add smart placement so it is not placed out of bounds.

<img width="598" alt="Screenshot 2022-05-10 at 14 11 29" src="https://user-images.githubusercontent.com/1498400/167625709-739dd944-632e-4be0-8cc0-3469c7294eac.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.34.2

#### If this is a bug, please provide steps for reproducing it.

1. https://sap.github.io/fundamental-ngx/#/core/menu
2. make window really narrow
3. open submenu
4. see submenu overflows out of window

#### Is there anything else we should know?
using platform's cascading menu is not an option, because we need features like splitter.

**Comment by mikerodonnell89** [comment]
Hi @desaroxx, in this case you would want to use the `[mobile]` input, see this example: https://sap.github.io/fundamental-ngx/#/core/menu#mobile

Hope that helps, please @ me if not!
