### ISSUE TITLE
Ability to show date in custom date format in date picker.

### ISSUE THREAD

**Issue by shajihamza1988** [SAP/fundamental-ngx#8090]
Is this a bug, enhancement, or feature request?
This is a feature request.

Briefly describe your proposal.
https://sap.github.io/fundamental-ngx/#/core/date-picker
Currently I am not able to show the date in dd/mm/yyyy or any other custom format in datepicker input text box after selecting a date. But the same works fine when I use Internationalization - setLocale. Please extend this option to be able to show the date in any custom format.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version - 13.2.4
Fundamental version - 0.34.2

**Comment by dmitry-stepanenko** [comment]
Hi @shajihamza1988. You can customize the appearance by providing your custom config via `DATE_TIME_FORMATS` injection token. Please take a look at this example https://fundamental-ngx.netlify.app/#/core/date-picker#formatting
