### ISSUE TITLE
FN SelectModule is not exported / available

### ISSUE THREAD

**Issue by jonas-meister-sap** [SAP/fundamental-ngx#8109]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

fundamental-ngx/fn 0.34.3

The linked select component is not rendering:
https://sap.github.io/fundamental-ngx/#/fn/select

For me it looks like, that the "SelectModule" is just not exported:
![image](https://user-images.githubusercontent.com/86601937/169029306-487e0961-d116-46c0-8739-108169ad0b46.png)

Made it work by:

```
import { FundamentalNgxFnModule } from '@fundamental-ngx/fn';
import { SelectModule } from '@fundamental-ngx/fn/select';
```

**Comment by dmitry-stepanenko** [comment]
Hi, @jonas-meister-sap. We recommend to use direct imports from sub-modules instead of the top-level one. Be aware, that top-level imports like `from '@fundamental-ngx/fn';` will be completely removed in the future
