### ISSUE TITLE
Error message borders are wider than the input borders in Platform form generator

### ISSUE THREAD

**Issue by ynnenu** [SAP/fundamental-ngx#8118]
<img width="441" alt="Screen Shot 2022-05-19 at 11 06 59 AM" src="https://user-images.githubusercontent.com/23292047/169557465-d6b8aca8-ded9-4760-929b-7b7d2b5c2f46.png">

**Comment by platon-rov** [comment]
that's how it should be per designs.

<img width="564" alt="CleanShot 2022-12-27 at 14 11 19@2x" src="https://user-images.githubusercontent.com/20265336/209671563-b689218f-de40-4b81-b966-858e3e697a10.png">
