### ISSUE TITLE
Toolbar Overflow elements don't have the proper spacing between them on resize

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#8119]
#### Is this a bug, enhancement, or feature request?
Bug
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
#### If this is a bug, please provide steps for reproducing it.
<img width="589" alt="Screen Shot 2022-05-20 at 2 00 17 PM" src="https://user-images.githubusercontent.com/39598672/169587217-19b5d4e4-0387-4909-afd0-5996d35ea926.png">

1. Go to Toolbar Overflow example: https://deploy-preview-8051--fundamental-ngx.netlify.app/#/core/toolbar#overflow
2. Open the overflow menu. It should look like this:

<img width="1286" alt="Screen Shot 2022-05-20 at 2 14 02 PM" src="https://user-images.githubusercontent.com/39598672/169588449-22a777af-a9c8-4467-9545-c983091c8a08.png">

4. Start shrinking the screen. It starts looking like this:
<img width="715" alt="Screen Shot 2022-05-20 at 2 08 05 PM" src="https://user-images.githubusercontent.com/39598672/169588508-404aefe0-e40c-48a2-9610-2100a57a6d37.png">

The elements that go in the overflow after start the resize don't have the proper spacing between them.

**Comment by mikerodonnell89** [comment]
I think we can safely add `fd-toolbar__overflow-button` to all buttons in the toolbar, doesn't affect anything visually when expanded but adds the margin when collapsed. So maybe it needs a rename and also we might be able to refactor out the FdToolbarOverflowButtonComponent
