### ISSUE TITLE
Request to support usage of data-testid in Tabs

### ISSUE THREAD

**Issue by vzipf** [SAP/fundamental-ngx#8137]
#### Is this a bug, enhancement, or feature request?

Feature request

#### Briefly describe your proposal.

Hi folks,

so here is an - in principle general - feature request.
I depict this in an example using the `TabsModule` as it is documented here: https://sap.github.io/fundamental-ngx/#/core/tabs

We use tabs on our websites quite a lot and we also want to wrire end-to-end tests for those sites.
For this we use [cypress](https://github.com/cypress-io/) (but that's just a side info).
The problem we face is the following.
When we write e2e tests, we need to **identify** the contents of the webpage somehow.
Where possible we set the `data-testid` attribute on the various elements that we want to test.

For this imagine a website having two tabs and the content of each tab is a `<fd-dynamic-page>` on its own.
In our end to end test we would like to:
1) Find the tab to verify its name
2) Click on it
3) Read the content that has loaded
4) Assert the values of the content
5) Click on the other tab and do 1-4 again but with different assertions for the values are different

**Problem Statement**

Now with Fundamental tabs this is not so straight forward as thought originally (see screenshot).
You can see that for each tab the actual element that changes the content is the click to the anchor tag.
Then in a `div` tag with class `<div class=fd-tabs__content>` there is a set of `<fd-tab role="tabpanel">`.
Only the one that has `is-expanded set` has actual content within the the `fd-tab`node.
The other ones are empty.

Now when we want to write an end to end test we do:
1) Get the (currently active) tabs name by CSS selector `div.fd-tabs__item > a[tabindex] > span.fd-tabs__tag`
2) Verify the expected name
3) Select the anchor tag using the CSS selector `div.fd-tabs__item > a[tabindex]`
3) Click on that element to initiate the content loaded
4) Do even more sophisticated CSS selector work to read out the content's.
4) Now we have the content and can do assertions

This is quite complex, error prone and may lead to weak e2e tests for we do not have any control over what Fundamentals is generating.
Today it might be the above, tomorrow the `fd-tabs__item` might be renamed to something else and then our tests are "broken".

**Feature Request**

We want to be able to:
* Get a tabs name (i.e. the text of the anchor tag) using a `data-testid` value we can define in our code
* Select the `<a role="tab">` tag in a `fd-tab-list` by setting e.g. `<fd-tab data-testid="tab-1">`. So the `data-testid` should/could also be set on the anchor tag by Fundamentals.
* Select the content that appears after a tab was clicked by a predefined `data-testid` value. For example if the `data-testid="tab1"` then the content could have `data-testid="tab1_content"` or something similar.

**Conclusion**

We know that end to end testing is not easy at all but we'd like to see that Fundamentals supports it a bit better when it gets to "generated/dynamic" code like in the tab example above.
Here the "generated/dynamic" code is the fact that content is only present AFTER click to the tab and in a specific sub-node.
We can think of even more cases but for this very ticket we wanted to just illustrate what we are struggeling with.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Current version

#### If this is a bug, please provide steps for reproducing it.

N/A

#### Please provide relevant source code if applicable.

N/A

#### Is there anything else we should know?

Here's the screenshot:
![fd-tab-example](https://user-images.githubusercontent.com/78794663/170037823-afed648b-de44-4352-b948-76eea0a8d3a5.PNG)

**Comment by g-cheishvili** [comment]
> **Feature Request**
> 
> We want to be able to:
> 
> * Get a tabs name (i.e. the text of the anchor tag) using a `data-testid` value we can define in our code
> * Select the `<a role="tab">` tag in a `fd-tab-list` by setting e.g. `<fd-tab data-testid="tab-1">`. So the `data-testid` should/could also be set on the anchor tag by Fundamentals.
> * Select the content that appears after a tab was clicked by a predefined `data-testid` value. For example if the `data-testid="tab1"` then the content could have `data-testid="tab1_content"` or something similar.

In the case of the `fd-tab-list`, the `fd-tab` has input `id`, you can either specify it and use whatever string you want or you can skip that and it will be autogenerated(but if you target them with tests, probably you'd want to specify them).
`[fd-tab-link]`, aka the header link element will have that id in DOM and the content for that tab will have id `${whatYouSpecified}-panel`. With this, you can easily locate both `#someId`(aka a[role=tab]) and `#someId-panel`(aka fd-tab) if you pass for example "someId" to `fd-tab` component.

I think this should be enough for your use, if not, just reopen the issue. Huge thanks for reporting!
