### ISSUE TITLE
Multi Input - Async Example - Token name shows value instead of display name

### ISSUE THREAD

**Issue by agugger** [SAP/fundamental-ngx#8143]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
I use the Multi Input Observable async example. https://sap.github.io/fundamental-ngx/#/core/multi-input#observable-async
After searching for Apple, selecting and searching for strawberry the apple token shows the value instead of the display name. As soon as Apple is again available to select it shows the display name correctly again.

I expect the token name should always be the display name.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
See in description

#### Please provide relevant source code if applicable.
Use the one from the example page

#### Is there anything else we should know?
![Screen Shot 2022-05-25 at 15 55 46](https://user-images.githubusercontent.com/12048988/170281915-49d65b0b-f8fe-4563-87f6-e674ee9d69ca.png)

**Comment by mikerodonnell89** [comment]
closing, appears to be fixed as of the latest RC
