### ISSUE TITLE
fdpMenuTriggerFor: Using JAWS VPC mode on fdpMenuTriggerFor gets triggered even for arrow keys it should display menu only on enter or space

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#8144]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The issue is using JAWS VPC mode on , when user traverses through menu trigger button and while going backwards
When focus is on fdp-menu trigger button, and user tries to move to previous element using left arrow key. It opens the menu menu options. But user hasn't pressed Enter key while focus was on fdp-menu. This doesnt happen while moving using right arrow , happens only when using left arrow and going backwards. Please see recording

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13.,   
 "@fundamental-ngx/core": "0.33.4",
  "@fundamental-ngx/platform": "0.33.4",
#### If this is a bug, please provide steps for reproducing it.
Add a fdpmenu and its trigger button in. a table cell and turn on JAWS with vpc mode on , move forward through all table cells where we have fdpmenu trigger button using right arrow key.
Later move backwards using left arrow key.
Notice that when the focus leaves fdp menu trigger button using left arrow key , the menu is opening up.

Expectation: menu should open up only during enter key press and not on left arrow key. 

#### Please provide relevant source code if applicable.
 <div *ngIf="newMenu"
         class="new-menu w-hc-title pop-up-menu-trigger"
         [ngClass]="{'ui-state-disabled':disabled}"
         [ngStyle]="{'pointer-events': disabled ? 'none' : 'initial'}"
         awName [id]="triggerId">
        <button *ngIf="showPopupLabel" [ngClass]="popupLabel ? 'fd-button fd-button--emphasized' : 'fd-button fd-button--transparent' "
                [title]="tooltipText" [fdpMenuTriggerFor]="basicMenu">{{ popupLabel }}
            <span class="pop-up-menu-button-icon"><i *ngIf="iconClass" [ngClass]="iconClass"></i></span>
        </button>
        <button *ngIf="!showPopupLabel" tabindex="0" class="ada-focus" [ngClass]="iconClass || 'sap-icon--overflow fd-button fd-button--transparent mv-rotate--180'"
                [title]="tooltipText"  [attr.aria-label]="tooltipText" [fdpMenuTriggerFor]="basicMenu">
        </button>

        <fdp-menu #basicMenu [xPosition]="'before'">
            <ng-container *ngFor="let group of (menuGroupMap | keyvalue); trackBy: trackByGroup">
                <ng-container *ngFor="let item of group.value; trackBy: trackByLabel; let i = index; let lastLi = last, let firstLi = first">
                    <fdp-menu-item *ngIf="group.value && group.value.length && item.visible !== false && item.items !== undefined"
                                   [ngClass]="{'menu-group-2': lastLi, 'first-li-with-group': firstLi && item.groupName, 'ui-state-disabled':item.disabled}"
                                   [attr.aria-disabled]="item.disabled"
                                   [fdpMenuTriggerFor]="getSubmenu(item.id)">
                        <ng-container *ngTemplateOutlet="menuItemTemplate;context:{i:i,firstLi:firstLi,item:item}">
                        </ng-container>
                    </fdp-menu-item>
                    <fdp-menu-item *ngIf="group.value && group.value.length && item.visible !== false && item.items === undefined" (itemSelect)="item.command()"
                                   [ngClass]="{'menu-group-2': lastLi, 'first-li-with-group': firstLi && item.groupName, 'ui-state-disabled':item.disabled}"
                                   [attr.aria-disabled]="item.disabled">
                        <ng-container *ngTemplateOutlet="menuItemTemplate;context:{i:i,firstLi:firstLi,item:item}">
                        </ng-container>
                    </fdp-menu-item>
                </ng-container>
            </ng-container>
        </fdp-menu>

        
        <ng-container *ngFor="let group of (menuGroupMap | keyvalue)">
            <ng-container *ngFor="let item of group.value">
                <fdp-menu *ngIf="group.value && group.value.length && item.visible !== false && item.items !== undefined" [id]="item.id">
                    <ng-container *ngFor="let subItem of item.items; let i = index; let firstLi = first">
                        <fdp-menu-item *ngIf="group.value && group.value.length && subItem.visible !== false" (itemSelect)="subItem.command()"
                                       [ngClass]="{'menu-group-2': lastLi, 'first-li-with-group': firstLi && subItem.groupName, 'ui-state-disabled':subItem.disabled}"
                                       [attr.aria-disabled]="subItem.disabled">
                            <ng-container *ngTemplateOutlet="menuItemTemplate;context:{i:i,firstLi:firstLi,item:subItem}">
                            </ng-container>
                        </fdp-menu-item>
                    </ng-container>
                </fdp-menu>
            </ng-container>
        </ng-container>
    </div>
#### Is there anything else we should know?
May be some issue with keydown events. Please chec

https://user-images.githubusercontent.com/88182358/170473189-ead21c0c-94bd-4958-a676-3b139e83d7af.mp4

k

**Comment by dmitry-stepanenko** [comment]
@I543348 the behavior by itself was correct as it's expected for the menu to be opened by arrow keys. However, your use case should not have it obviously, so I've added `openByArrowKeys` binding, that can be set to `false` to achieve the behavior you need
