### ISSUE TITLE
Use Alternative to Angular's LOCALE_ID

### ISSUE THREAD

**Issue by desaroxx** [SAP/fundamental-ngx#8145]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
Certain aspects of fd-calendar's internationalization is based on Angular's LOCALE_ID. For example the month names are controlled by LOCALE_ID.

By design Angular's LOCALE_ID needs to be set BEFORE Angular is instantiated (for [more details](https://stackoverflow.com/a/49675774)). We do not use the browser/OS's language setting `navigator.language`. Instead in  Angular we load preferred user languager AFTER Angular is instantiated. This leads to us not being able to set LOCALE_ID to user's preferred. 

Suggested by Angular:
1. Get user's preferred language
2. Configure LOCALE_ID to preferred language
3. Instantiate Angular

Our PROBLEM case:
1. Instantiate Angular
2. Fetch authenticated user's preferred language from backend (whole authentication mechanism, http libs etc all written in Angular)
3. PROBLEM: can not update LOCALE_ID anymore

**Solution Proposal:** Use alternative to Angular's LOCALE_ID to set preferred language. Maybe something similar to the overridable CalendarI18nLabels:

```
@Injectable()
export class MyCustomFdLocaleId extends FdLocaleId {
  localeId = 'de-DE';
}

@Component({
    selector: 'fd-calendar-i18n-example',
    template: ` <fd-calendar [(ngModel)]="date"></fd-calendar>`,
    providers: [
        {
            provide: FdLocaleId,
            useClass: MyCustomFdLocaleId
        }
    ]
})
export class CalendarI18nExampleComponent {
    date: FdDate = new FdDate(2020, 10, 25);
}
```

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.34.2

#### If this is a bug, please provide steps for reproducing it.
-

#### Please provide relevant source code if applicable.
-

#### Is there anything else we should know?
-

**Comment by g-cheishvili** [comment]
You could use [APP_INITIALIZER](https://angular.io/api/core/APP_INITIALIZER) to load things that are needed first, save it in service or somewhere and then use that value just like it is done in the link you provided. Would that be possible?
