### ISSUE TITLE
Type number in Wizard Generator allows letters

### ISSUE THREAD

**Issue by ynnenu** [SAP/fundamental-ngx#8147]
The type= "number" in the wizard generator allows the user to enter letters. Maybe we shouldn't allow the user to enter letters because then the type = "number" looks like type ="input".

<img width="884" alt="Screen Shot 2022-05-27 at 11 16 23 AM" src="https://user-images.githubusercontent.com/23292047/170729266-47caf655-3914-443c-825d-5a79d5e55e17.png">

**Comment by N1XUS** [comment]
@ynnenu Have you provided `controlType: 'number'` to this item in your config object?
