### ISSUE TITLE
fd-token accessibility: Not able to reach tokens using keyboard (tab key)

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#8171]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
fd-tokens are not reachable via keyboard mostly using tab key, there is no element having tabindex=0 for fd-token

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13
    "@fundamental-ngx/core": "0.33.4",
    "@fundamental-ngx/platform": "0.33.4",

#### If this is a bug, please provide steps for reproducing it.
https://sap.github.io/fundamental-ngx/#/core/token - try to reach all tokens using tab key - none of them are accessible

**Comment by mikerodonnell89** [comment]
Hi @I543348, if you tab focus the entire tokenizer (placing the keyboard cursor in the tokenizer's input) you will be able to use the arrow keys to scroll through the tokens and the delete/backspace key will delete them. We can add keyboard support to individual tokens - would the ideal situation in this case be the tab key to iterate over each one?

**Comment by I543348** [comment]
Thanks for the reply @mikerodonnell89 , but what if input box is a readonly then cursor will never reach input box and coz tokens are inside input box , hence focus wont reach tokens as well.
I guess we need a workaround for this case.

**Comment by mikerodonnell89** [comment]
@I543348 Could you take a look at the behavior for tokens on this PR: https://github.com/SAP/fundamental-ngx/pull/8264/files

And let me know if this is what you are looking for? This way I have kept the existing behavior for tokens within tokenizers, but adds a tabindex to tokens that are not.  For standalone tokens you can implement your own behavior utilizing the `onTokenClick` event. However if you also need to handle close click behavior in addition to separate token click behavior, I think we will need to allow additional keyboard focus of the close button
