### ISSUE TITLE
Button keydown event trigger with spacebar

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#8208]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
I am currently using a normal button with **fdpMenuTriggerFor**.
`<button fd-button [fdpMenuTriggerFor]="basicMenu" label="Button example"></button>`
The problem is when the focus is on the button and I am holding the _spacebar_, the event keeps on triggering which is leading to a flickering of menuItems (closing and opening the menu recursively).

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version - 13
ngx - 0.33.4

#### If this is a bug, please provide steps for reproducing it.

Focus on the button (Button example) and hold space - Observe the flickering of menu items
[https://sap.github.io/fundamental-ngx/#/platform/menu](https://sap.github.io/fundamental-ngx/#/platform/menu
)<img width="760" alt="image" src="https://user-images.githubusercontent.com/107252602/173054782-f9686ae4-a480-4d1f-97b8-ded0713c6a74.png">

#### Is there anything else we should know?

ngx core menu seems to be working fine with **fdMenuTrigger** as the event is not getting triggered again and again. I think ismenuOpened check is missing in the platform.
[https://sap.github.io/fundamental-ngx/#/core/menu](https://sap.github.io/fundamental-ngx/#/core/menu)
<img width="604" alt="image" src="https://user-images.githubusercontent.com/107252602/173055557-761005b7-e05c-478a-8d65-2dfc8d7d1d57.png">

**Comment by mikerodonnell89** [comment]
I think this is simply the way the fdp-menu works differently from the fd-menu - it is a bit more opinionated - clicking an item with the core (fd) menu doesn't do anything automatically whereas the platform (fdp) menu fires the itemSelect event, closes the menu, and refocuses the menu trigger button. So holding space will simply open the menu, automatically focus the first item, selects it, close the menu while focusing the trigger button, and the cycle repeats. I think this can be considered the intended behavior and I would recommend using the fd-menu as an alternative if you need to work around this behavior

**Comment by prasad-userdev** [comment]
Thanks for the reply @mikerodonnell89 
Changing it to fd-menu would be our last option as Its been used across the application

According to me, It will run in a loop until the user releases the key which would not be the expectation from the end user/blind users.

Also, If the **span/div** with **role "button"** was used then I agree on your point. But here we are using a default **button**. So the expectation for this would be - single event trigger until any key (space/enter) pressed is released.
