### ISSUE TITLE
[Accessibility][Sourcing] fd-popover body with ul and li with fdp-checkbox combination issue

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#8210]
#### Is this a bug, enhancement, or feature request?
Bug / enhancement 

#### Briefly describe your proposal.
When using fd-popover body containing ul and li with fdp-checkbox each.
User is not able to traverse through checkboxes using up and down arrow keys
User is not able to close the popover using ESC key.
Please take a look.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13 
 "@fundamental-ngx/core": "0.33.4",
    "@fundamental-ngx/platform": "0.33.4",

#### If this is a bug, please provide steps for reproducing it.
This issue is only with keyboard accessibility
Try to open popover body
now traverse through checkbox list items using up and down arrows - doesn't work
try to press ESC key to close popover doesn't work.

#### Please provide relevant source code if applicable.

            <fd-popover-body>
                            <ul fd-list role="list">
                                <li role ="listitem"  *ngFor="let label of boardLabels"
                                    id="{{label.displayName}}">
                                    <fdp-checkbox [name]="label.displayName" [(ngModel)]="label.isSelected"
                                    [value]="label.uniqueName" [label]="label.displayName"
                                   (change)="filterTopicClicked($event)">
                                    </fdp-checkbox>
                                </li>
                            </ul>
                        </fd-popover-body>

#### Is there anything else we should know?
fd-popover with ul and li works fine if li doesnt have fdp-checkbox inside it.
please find screenshot
<img width="485" alt="Screenshot 2022-06-11 at 1 50 21 PM" src="https://user-images.githubusercontent.com/88182358/173179908-b3f19e86-3f2f-468f-b999-e6306efc6572.png">

**Comment by skaquib123** [comment]
@I543348 , If you are using fd-list in "ul" tag then you have to use fd-list-item in "li" tag and fd-checkbox not fdp-checkbox. There is a compatibility issue between fd and fdp components.

Hence, closing this issue.
