### ISSUE TITLE
[Accessibility] [Sourcing] fdp-checkbox ariaLabel or ariaLabelledby is read twice

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#8231]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Add ariaLabel or ariaLabelledby to fdp-checkbox and notice that when focus is on checkbox the aria-label element text is being read twice by screenreader

This is replicable even in link https://sap.github.io/fundamental-ngx/#/platform/checkbox 
under "Accessibility on checkbox" section second checkbox

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13
    "@fundamental-ngx/core": "0.33.4",
    "@fundamental-ngx/platform": "0.33.4",

#### If this is a bug, please provide steps for reproducing it.
Add ariaLabel or ariaLabelledby to fdp-checkbox and notice that when focus is on checkbox the aria-label element text is being read twice by screenreader

#### Please provide relevant source code if applicable.
<p id="checkboxLable">checkbox using aria-labelledby</p>
  <fdp-checkbox name="checkboxA11y2" ariaLabelledBy="checkboxLable" [(ngModel)]="checkboxA11y2"></fdp-checkbox>

#### Is there anything else we should know?
<img width="1792" alt="Screenshot 2022-06-14 at 11 16 08 PM" src="https://user-images.githubusercontent.com/88182358/173654556-dbbca096-12c8-465b-8fc0-4d4d1e0aea02.png">

**Comment by skaquib123** [comment]
Hi @I543348, as discussed it is working as expected.
<img width="1638" alt="Screenshot 2023-01-02 at 5 32 17 PM" src="https://user-images.githubusercontent.com/110972289/210300682-6542bb1c-5ae2-470d-ba0f-ec70e3bf798f.png">
Hence, closing the issue.

**Comment by I543348** [comment]
Thanks @skaquib123 , This issue is no more replicable on latest version of platform checkbox component.
