### ISSUE TITLE
Explore pnpm in NGX

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8268]
Let's try replacing pnpm in NGX repo. Time box **3d**
- [x] We can try this out in a PR and list all pros/cons. 
- [x] Evaluate how this can affect the documentation/team/stakeholders/pipeline/release.
- [x] Play with different node/npm versions
- [x] update `package.json` - prohibit usage of `npm`

**Comment by N1XUS** [comment]
Node 14: run successful
Node 15: run successful
Node 16: run successful
Node 17: run successful
Node 18: run successful

Netlify config has been changed
Github actions has been changed
