### ISSUE TITLE
Dropdown (input, select controls) appears as popover

### ISSUE THREAD

**Issue by ericobranco** [SAP/fundamental-ngx#8287]
Hi Fundamental team, this is a bug discovered by our dev team (I couldn't find it mentioned in the current issues).

It appears that some dropdowns are now styled as popovers. The issue has been described [in this BLI](https://jira.tools.sap/browse/MPPORTAL-1672).
Following are some images:

- Expected:
![image](https://user-images.githubusercontent.com/17690922/175915661-406afa3a-93ce-4384-8a8c-89c7d740a105.png)

- Current:
![image](https://user-images.githubusercontent.com/17690922/175915745-9326fcc2-7763-44c4-8c8f-f49fdc72af93.png)

A colleague has mentioned being able to reproduce this issue by going to the input field (not select) in the [Fundamental NGX input page](https://fundamental-ngx.netlify.app/#/core/input):

![image](https://user-images.githubusercontent.com/17690922/175916207-9c34ba15-9f55-4860-ac70-2970e8e62083.png)

We would be grateful to know what might have caused this. 
Thank you! :)

- [ ] Core select - should the control be changing width when the selection changes? - discuss with designers

**Comment by JenniferStamm** [comment]
@droshev could you please clarify why this was closed? Is that the intended behaviour?
