### ISSUE TITLE
fd-wizard-navigation  UI overlapping with text spacing turned on

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#8295]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
On accessing the wizard steps with text spacing ON, some step text is overlapped on another step.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular - 13
fundamental ngx - 0.34.3-rc.47

#### If this is a bug, please provide steps for reproducing it.
Have a larger number of steps (8 or more) in the wizard and turn text spacing on.

#### Is there anything else we should know?
<img width="1071" alt="Screenshot 2022-06-29 at 15 16 25" src="https://user-images.githubusercontent.com/12679774/176407373-de212298-4f23-4268-b246-236200523919.png">

**Comment by mikerodonnell89** [comment]
What tool is this that adds spacing between characters? Makes sense that the logic that collapses the wizard steps would break when utilizing this. Works as expected when using the browser's zoom tool

**Comment by mikerodonnell89** [comment]
@snigdhaman Using a 3rd party tool to modify the look of our components will naturally break some of their functionality, so I'm sorry to say I don't think we can consider this an issue with the library

**Comment by droshev** [comment]
@snigdhaman What is the purpose of this text spacing ON? Can you share more info?
