### ISSUE TITLE
fd-select focus is lost on press of escape when fd-option is opened

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#8305]
#### Angular version - 13.3.4
Fundamental-ngx - 0.34.3-rc.47

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/core/select

#### Is there anything else we should know?
-

**Comment by fkolar** [comment]
Yes this is an issue. Core Select needs to be fixed as platform also using it internally.
