### ISSUE TITLE
Message Handling for Forms with Message Popover

### ISSUE THREAD

**Issue by D034394** [SAP/fundamental-ngx#8329]
Feature request

We deal with multiple forms across our solution. SAPUI5 provides the message popover for handling messages on such forms.
https://sapui5.netweaver.ondemand.com/sdk/#/entity/sap.m.MessagePopover

We do not see such a component being provided my the fundamental-ngx team and kindly request this as a centrally provided feature.
![image](https://user-images.githubusercontent.com/52921101/177754468-7b3f98e2-78ec-433d-a76b-16199222ef40.png)

**Comment by N1XUS** [comment]
**Research conclusion:**
Angular has 2 ways of forms handing: Template-driven and reactive ones.
Template-driven are actually composing reactive form inside, so what we will need to do is to parse that FormGroup value.

**Reactive form:**
- User will need to provide an input property of the formGroup to the message popover, and add message popover button the correct place on the page.
- Grouping functionality can be supported with platform form container.
- We would need to extend form container to expose such elements for the public API to compose the view.
- What we also would need is to parse custom errors templates from #i18n block
- After that message popover will listen to the form status changes, and render the errors accordingly to the provided templates, or with the error text from the errors object of the control fallback to default 'Field is invalid' if both options are not applicable.

**Template-driven forms:**
Template forms can be parsed with NgForm which exposes FormGroup with it's controls. After we parse NgForm, we fallback to the reactive forms approach.

Implementation time: 15-20 days.
