### ISSUE TITLE
Drag and drop in a table/list

### ISSUE THREAD

**Issue by hisabimbola** [SAP/fundamental-ngx#835]
#### Is this a bug, enhancement, or feature request?
Feature request
#### Briefly describe your proposal.
Support the ability to drag and drop rows or items within a table and from a table to the other
#### Is there anything else we should know?
I noticed that there are several issues created about this (#11, #84, SAP/fundamental#546), but nothing has been done since last year. This feature is now critical for a feature we are implementing in SAP FSM. We would appreciate if this could be implemented

Sample implementation [here](https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.TableDnD)

**Comment by mikerodonnell89** [comment]
This can be accomplished using the Angular CDK.  This PR (https://github.com/SAP/fundamental-ngx/pull/841) contains an example of rearranging rows in a table, the same ideas can be applied to moving an item from one table to another. 

Refer to the Angular CDK docs for more specifics https://material.angular.io/cdk/table/overview

**Comment by MattL75** [comment]
^ What Mike is saying is that there are **no current plans** to include a drag-and-drop functionality in this library. We are instead pointing devs to using the Angular CDK to accomplish this pattern.

**Comment by hisabimbola** [comment]
Okay, we will try that. Thanks for pointing out
