### ISSUE TITLE
Overflow layout standartization

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#8368]
This task lists subtasks for standartizing the Overflow Layout component usage across multiple components in Fundamental-ngx

- [x] Breadcrumbs https://github.com/SAP/fundamental-ngx/issues/8364
- [ ] Avatar Group https://github.com/SAP/fundamental-ngx/issues/8365
- [ ] Icon Tab Bar https://github.com/SAP/fundamental-ngx/issues/8366
- [x] Tabs https://github.com/SAP/fundamental-ngx/issues/8367

**Comment by mikerodonnell89** [comment]
closing as we have separate issues for the 2 remaining items
