### ISSUE TITLE
New Component Object Page

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8369]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.

Sprint 1
- [ ] investigate the component and compare the design with Dynamic Page
- [ ] list the parts that are missing 

Introduce Object Page as a component (maybe just in the platform for now)

**Comment by platon-rov** [comment]
A little investigation done.

Component looks very similar to the Dynamic Page Header that contains Facets. Actually, I didn't notice any difference from the Dynamic Page header, at least from wiki pages of them both. Asked designers about my assumptions.

**Comment by platon-rov** [comment]
Okay, got answer from the designers. They confirmed that object page is the header of the dynamic page with facets inside of it.

We do actually have example in our docs https://fundamental-ngx.netlify.app/#/core/dynamic-page#facets that looks and works 100% the same as described in the object page wiki page.

**Comment by platon-rov** [comment]
From that page https://experience.sap.com/internal/fiori-design-web/object-page/ it gets clear that Object Page is just a certain set of components mixed to represent an Object. 

In that section https://experience.sap.com/internal/fiori-design-web/object-page/#components it's also mentioned that Object Page isn't just a header but header + content + etc, so there is no sense to have object page as the separate component.
