### ISSUE TITLE
Anchors are navigated with tab chain

### ISSUE THREAD

**Issue by Nitin-789** [SAP/fundamental-ngx#8383]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Multiple fd-tab grouped under fd-tab-list are accessible via tab but since all the fd-tab are a part of single group they should only be accessible via arrow keys.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

angular - 13
fundamental ngx - 0.34.3-rc.47

#### If this is a bug, please provide steps for reproducing it.

Access the fd-tab-list consisting of multiple fd-tab via tab keypress and observe the fd-tab to be under tab chain order.

#### Is there anything else we should know?

<img width="1188" alt="Screenshot 2022-07-18 at 12 08 16 PM" src="https://user-images.githubusercontent.com/37510228/179479436-fd094cdf-77ce-44c5-a970-be74f714f358.png">

**Comment by mikerodonnell89** [comment]
this is fixed as of the current version
