### ISSUE TITLE
Class missing in the toolbar of the p13n dialog

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#8386]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

The class `fd-toolbar--cozy` in the child div of fd-toolbar is missing. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
  
* Angular: 13.x
* Fundamental Library: Latest

#### If this is a bug, please provide steps for reproducing it.
  
In the stackblitz at our disposal, we can see it  
[url](https://sap.github.io/fundamental-ngx/#/platform/table#p13-table-columns)
 
![image](https://user-images.githubusercontent.com/34537974/179545012-913f27e7-4135-4986-873b-1e73684d5fc5.png)

**Comment by mikerodonnell89** [comment]
closing as this has been fixed
