### ISSUE TITLE
Carousel losing focus - bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8387]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Carousel keyboard navigation
To reproduce:
1. go to the first example
2. focus the carousel element
3. use the Tab key to focus the arrow button
4. use the right arrow to reach the last image of the carousel
5. now that you are at the last element the focus is lost so going to the other direction using only the keyboard is not possible

**Comment by mikerodonnell89** [comment]
I think we can close this, see my comment here: https://github.com/SAP/fundamental-ngx/issues/8342#issuecomment-1182500830
