### ISSUE TITLE
RangeError when selecting Date in DateTime picker on Safari

### ISSUE THREAD

**Issue by cawmichae** [SAP/fundamental-ngx#839]
Bug

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
        "@angular/animations": "~7.2.0",
        "@angular/cdk": "^7.2.0",
        "@angular/cli": "^7.2.0",
        "@angular/common": "~7.2.0",
        "@angular/compiler": "~7.2.0",
        "@angular/core": "~7.2.0",
        "@angular/forms": "~7.2.0",
        "@angular/http": "^7.2.0",
        "@angular/material": "^7.2.0",
        "@angular/platform-browser": "~7.2.0",
        "@angular/platform-browser-dynamic":

"fundamental-ngx": "^0.5.1",
#### If this is a bug, please provide steps for reproducing it.

In Safari, with the console window open, click on a date. Observe 
RangeError: Invalid Date
runTask - zone.js:199
invokeTask - zone.js:498
timer - zone.js:2281

**Comment by mikerodonnell89** [comment]
Hi, we're unable to reproduce this... should have been fixed here: https://github.com/SAP/fundamental-ngx/pull/820/

Is the error thrown on the calendar or date picker components as well?  Are you able to reproduce it on the documentation site? https://sap.github.io/fundamental-ngx/datetime-picker

What version of Safari are you running?

Thanks!

**Comment by cawmichae** [comment]
I have just tried to reproduce this in an app that comprises ONLY the datetime picker and it is not happening. So it looks like it is not from the DTP, sorry.
