### ISSUE TITLE
Defect Hunting: Input Group RTL issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8399]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] Input group RTL - placeholder final character is cut off

<img width="209" alt="Screen Shot 2021-08-26 at 4 47 50 PM" src="https://user-images.githubusercontent.com/2471874/131045841-2dc3d205-5bde-4f09-8f22-54c9932a402d.png">

**Comment by mikerodonnell89** [comment]
Closing because this should be fixed in fundamental-styles: https://github.com/SAP/fundamental-styles/issues/3742
