### ISSUE TITLE
drag and drop design documentation

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#84]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal
We need design guidelines for drag and drop behaviour (primarily for table rows)
we would need design for the drag and drop of rows in the table.
We foresee: draggable rows, droppable and non-droppable areas, placeholder

#### What versions of Angular and Fundamental NGX? (If this is a feature request, use current version)
angular 6, fundamental 0.3

#### If this is a bug, please provide steps for reproducing it
n/a

#### Please provide relevant source code if applicable
n/a

#### Is there anything else we should know?
n/a
issue opened in fdui - https://github.com/SAP/fundamental/issues/546

**Comment by xak** [comment]
@SAPMontreal This should be an issue in the main FD project.

**Comment by SAPMontreal** [comment]
@xak done https://github.com/SAP/fundamental/issues/546

**Comment by droshev** [comment]
@LeoT7508 were able to finish the design? Let us know if you need something from us.
