### ISSUE TITLE
mutil input will impact the width of dialog

### ISSUE THREAD

**Issue by Crwing** [SAP/fundamental-ngx#8405]
#### Is this a bug, enhancement, or feature request?
should be a bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13.3.8 and Fundamental Library 0.35.1

#### If this is a bug, please provide steps for reproducing it.
If there is one multi input in a dialog, when user selects several entries, the width of dialog will be changed due to user inputs.

#### Please provide relevant source code if applicable.
It can be reproduced, please use below link to test
https://stackblitz.com/edit/angular-rfyhwy?file=src/app/form-dialog-example.component.html

Thanks a lot!

**Comment by mikerodonnell89** [comment]
@Crwing is it possible to work around this by setting the width of the dialog config? i.e.

```
    const dialogRef = this._dialogService.open(dialog, {
      responsivePadding: this.responsivePadding,
      focusTrapped: true,
      verticalPadding: this.verticalPadding,
      width: '300px'
    });
```

**Comment by Crwing** [comment]
Hi @mikerodonnell89 , thanks for your quick response and workaround. 

Yes, I set the a fixed width for the dialog and it works fine. I can use this way currently.

Be honest different screen size using the same width dialog is a little weried specially for big monitor. Just want to check with you whether it is a bug, will it be fixed soon?

Regards
Crwing

**Comment by mikerodonnell89** [comment]
> 

Hi @Crwing sorry for the late response, I am just seeing your comment. You could also instead of passing a px value, pass a vw value, i.e. `90vw` to have the dialog occupy 90% of the viewport regardless of screen size.

**Comment by Crwing** [comment]
Hi @mikerodonnell89 , got it, I close this issue. Thanks for your info and help!
