### ISSUE TITLE
Defect Hunting: Platform List bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8410]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

- [x] - Action List Item

1. go to https://fundamental-ngx.netlify.app/#/platform/action-list-item#basic
2. click on the first item -> an alert pops, press Esc to close it
3. press arrow up with the keyboard - the focus changes (in our case to the last item)
4. click the first item again with the mouse(this will set the focus on the first item again) -> this will pop an alert again. press Esc to close it
5. press arrow up again and notice where the focus is

- [ ] Platform multicselection example 
1. go to https://fundamental-ngx.netlify.app/#/platform/list#multi-selection
2. set the focus on the second check fox
3. press any key -> this will shift the focus on the entire row

**Comment by manavs** [comment]
Validated the first part of the defect, the repeating the steps moves focus next item from the bottom

**Comment by N1XUS** [comment]
@droshev what should be the correct behaviour for the second item?

**Comment by mikerodonnell89** [comment]
Closing as this is no longer relevant due to new keyboard functionality for lists
