### ISSUE TITLE
Defect Hunting: Pagination bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8411]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] No keyboard navigation for pagination. Once you click on a page you can't go to another page using only the keyboard.
<img width="1046" alt="Screen Shot 2021-12-13 at 4 25 53 PM" src="https://user-images.githubusercontent.com/39598672/145891442-428f449f-aa88-4a15-8ae0-fa96c268e127.png">

**Comment by mikerodonnell89** [comment]
You can use the tab key to focus a page and then the arrow keys
