### ISSUE TITLE
Defect Hunting: Avatar bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8414]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] Console errors for Avatar:
<img width="839" alt="Screen Shot 2021-12-13 at 11 46 46 AM" src="https://user-images.githubusercontent.com/39598672/145855939-b591446f-3111-4d22-b5bd-70baa052cdb4.png">

**Comment by N1XUS** [comment]
That's intended to show how fallback for incorrect avatar image works. Closing the issue.
