### ISSUE TITLE
Defect Hunting: Icon Tab Bar

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8418]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

- [ ] ## Platform Icon tab bar
Steps to reproduce:
* [Navigate here](https://fundamental-ngx.netlify.app/#/platform/icon-tab-bar)
* Resize screen so that "More" button appears
* Select any of the items from "More" menu
* Observe that, that item is now moved to visible items
* Resize to bigger screen, to make "More" hidden
* Then resize back to smaller screen
* Observe that selected item is not now in Visible items, but hidden in "More" menu

Expected Behavior:
Selected tab should always be in visible tab headers list

**Comment by N1XUS** [comment]
@droshev I would postpone this bugfix until Icon Tab Bar is migrated to Overflow Layout component usage and then verify the behaviour
