### ISSUE TITLE
After 600px page width become 0px.

### ISSUE THREAD

**Issue by hamiarcher** [SAP/fundamental-ngx#842]
#### Is this a bug, enhancement, or feature request?
This is a bug in Page layout; after 600px page width become 0px.

#### Briefly describe your proposal.
most probably css changes;
@media (min-width:600px) {
  .fd-app {
    display: block;
  }
}

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Release v0.5.1

#### If this is a bug, please provide steps for reproducing it.
attached is code, do nom install and ng serve.
#### Please provide relevant source code if applicable.
[test-ngx.zip](https://github.com/SAP/fundamental-ngx/files/3214494/test-ngx.zip)

#### Is there anything else we should know?

**Comment by MattL75** [comment]
This is an issue for https://github.com/sap/fundamental which is the css library that fundamental-ngx consumes. I think they're aware of the broken layouts though, so it's probably being tracked in an issue somewhere.

**Comment by droshev** [comment]
@hamiarcher could you report the issue in `fundamental-styles` in case you are using `fundamental-ngx`?
