### ISSUE TITLE
Defect Hunting: Pickers bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8420]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] (Core) Date Time Picker, (Core) Time, (Core) Time Picker, scroll not working for time (hours, minutes, period) but it's meant from the ux - https://github.com/SAP/fundamental-ngx/issues/7626

**Comment by mikerodonnell89** [comment]
fixed with https://github.com/SAP/fundamental-ngx/pull/8470
