### ISSUE TITLE
Defect Hunting: status indicator bug

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8421]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

* [ ] (Core) Status Indicator, has tab stop without a reason (or event on click needed)

![image](https://user-images.githubusercontent.com/20265336/150977137-46763e17-d8a3-401a-8035-d26f7da7fa16.png)

**Comment by N1XUS** [comment]
@droshev 
Status indicator has [focusable] input field which is responsible for the tabindex.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/6586561/180713322-d34f0c99-806b-4419-9754-9ab4b9131a4a.png">
Additionally, status indicator presents itself as a progressbar with aria fields, thus focus might be required for the screen reader to correctly read the data.
