### ISSUE TITLE
Defect Hunting: Responsive Spliter bugs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8424]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] Responsive Splitter core - [example](https://fundamental-ngx.netlify.app/#/core/splitter#required-parent-width) - after opening the page in full screen, resize it so the 2 dots on the bottom appear. Clicking on the dots doesn't trigger the activation/visibility of the next page. There is no issue if you refresh the page on the small resolution(no resize)
<img width="847" alt="Screen Shot 2022-02-14 at 11 22 42" src="https://user-images.githubusercontent.com/4380815/153903756-86e0371b-b90c-4aad-a5af-4f1facb92589.png">

**Comment by mikerodonnell89** [comment]
Can't recreate in chrome on the current RC
