### ISSUE TITLE
Links should always have pointer cursor

### ISSUE THREAD

**Issue by akatyabg** [SAP/fundamental-ngx#8425]
#### Feature request

 Currently the fd-link has a "hand" cursor onky if a link/ href (for fdp) is set since it is the default style for <a>. This should be however the default case, even when no routerLink/href is set.

**Comment by droshev** [comment]
the native html links are also like that
https://stackblitz.com/edit/web-platform-atyyt4?file=index.html
`<a>` without `href` is rendered as text and when there is `href` set then it is blue, on hover the pointer changes.
