### ISSUE TITLE
Defect Hunting: Popover

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8434]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [x] I think popover controls should always receive tab focus - https://github.com/SAP/fundamental-ngx/pull/8493
- [ ] If you use tab+space to open popovers, old ones don't close (by default they close when a new one is opened via mouseclick)
<img width="1538" alt="Screen Shot 2022-07-11 at 4 31 20 PM" src="https://user-images.githubusercontent.com/2471874/178369670-135f6cfa-2cc1-4655-9172-908ba16cd85c.png">

**Comment by platon-rov** [comment]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

### Different markup issue

A normal popover has the following markup
```
<fd-popover>
    <fd-popover-control>
        ...
    </fd-popover-control>

    <fd-popover-body>
        ...
    </fd-popover-body>
</fd-popover>
```

While mobile popover has **totally different** markup
```
<button fd-button [fdPopoverTrigger]="popoverMobile">...</button>

<fd-popover #popoverMobile [mobile]="true" [mobileConfig]="...">
    <ng-template #popoverBodyContent>
        ...
    </ng-template>

    <ng-template #popoverFooterContent>
        ...
    </ng-template>
</fd-popover>
```

This actually means that we cannot easily toggle mobile mode with input property. If the user wants to use them both, he has to write two different markups

### No ESC button/backdrop click handling behavior

When clicking on the backdrop or pressing ESC button, nothing happens and no way to configure it what is opposite to the Dialog behavior.

###  Popover dialog doesn't take full screen

Popover shown as popover on large screens, so it's supposed to show popover as dialog on small screens where it should be whole viewport size. 

We either should make popover dialog the full screen or revisit circumstances of sizes of the popover dialog.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use the current version.)

0.36.0-rc.25

**Comment by platon-rov** [comment]
* [ ] Connected popover position wrong

<img width="684" alt="CleanShot 2022-11-16 at 12 13 30@2x" src="https://user-images.githubusercontent.com/20265336/202165907-080c45b8-a792-4402-8979-f0e5dfcce12d.png">
