### ISSUE TITLE
Tabs component cannot be split

### ISSUE THREAD

**Issue by parostatkiem** [SAP/fundamental-ngx#846]
#### Is this a bug, enhancement, or feature request?
Hard to say... 50/50 bug and enhancement ;)
#### Briefly describe your proposal.
For now, `Tabs` component's tab is one element which is fine if a developer wants to use it as you did in your examples. However, one may need (as I did) to separate the _navigation_ part from _content_ (my case: tab _navigation_ in Section header, tab _content_ deep inside Section content, wrapped into `Panel`) and it's impossible to be done. A simple solution is using pure Fundamental library.
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Current

**Comment by JKMarkowski** [comment]
Hi @parostatkiem, I think we can say this issue is solved by [this PR](https://github.com/SAP/fundamental-ngx/pull/976). You can use navigation mode with `*ngSwitch` and track active element on your side, instead of `router-outlet`.

**Comment by parostatkiem** [comment]
We have already solved it somehow in [Console](https://github.com/kyma-project/console), I don't remember how ;) Good to know it's now possible to do it in an official way. The solution looks good to me 👌
