### ISSUE TITLE
Fundamental-ngx doesn’t export the type NumericContentState

### ISSUE THREAD

**Issue by AlpanaSamanta** [SAP/fundamental-ngx#8461]
**#### Is this a bug, enhancement, or feature request?**
bug

#### Briefly describe your proposal.
Fundamental-ngx doesn’t export the type NumericContentState

#### If this is a bug, please provide steps for reproducing it.

I am using "tile" component of fundamental ngx. Instead of hardcoding the value of "state" to negative/positive in the html, I am trying to fetch its value from a function defined in the ts file that returns the string "positive" but I get the below error during build:
**error TS2322: Type 'string' is not assignable to type 'NumericContentState | null | undefined'.**

I was able to reproduce the error in slackblitz example for the tile component:
https://stackblitz.com/edit/angular-c2c6uk?file=src%2Fapp%2Fkpi-example.component.scss,src%2Fapp%2Fkpi-example.component.ts,src%2Fapp%2Fkpi-example.component.html

As we understood that we would need to cast the string to the required type, but it seems like fundamental-ngx doesn’t export the type NumericContentState.
Could you please resolve this bug?

**Comment by N1XUS** [comment]
Fixed with https://github.com/SAP/fundamental-ngx/pull/8463
