### ISSUE TITLE
Table (platform and core): hiding/showing column on table resize

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8467]
#### Is this a bug, enhancement, or feature request?
feature

#### Briefly describe your proposal.
We have popin as a mechanism for Responsive Table. Alternative to that is to have hide/show columns on table width resize. 

`dxp/metadata-registry/issues/402`

**Comment by tjbutz** [comment]
Feature is implemented and available

https://sap.github.io/fundamental-ngx/#/platform/table#responsive-columns
