### ISSUE TITLE
Develop strategy for Fundamental-NGX handling multiple Angular major versions

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#849]
As of 9 hours ago, Angular 8.0.0 has been released. We'll need to hop on that ASAP and make sure none of the breaking changes affect our stuff. I'd prefer to keep the components backwards compatible with at the very least Angular 7 going forward, even if they should currently be compatible with down to 5.

There's no official change blog yet, but [this one](https://blog.angularindepth.com/embrace-yourself-angular-8-is-coming-1bf187c8f0bf) is pretty good.
 
From what I can tell, the only major breaking change that we'll need to deal with is [this one](https://blog.angularindepth.com/embrace-yourself-angular-8-is-coming-1bf187c8f0bf#a053).

We know that compiling our library using Angular 8 would make compatibility with Angular 7 and downwards. 

There's two options, of which only one is feasible. First, we can keep compiling with Angular 7 until 7 goes to LTS. This is not feasible since we'll always be behind, not using the best features of Angular.

The next option is to support multiple versions across branches. We could have an active 0.6.xx version for ng7, which we would keep updating with essential fixes, but move everything new to 0.7.0 which would be compiled with Angular 8.

**Comment by razims** [comment]
when can we expect this?

**Comment by MattL75** [comment]
I hope we can address this soon. However, unless people spam @droshev internally, it probably won't be considered until the start of our next fundamental-ngx sprint.

**Comment by droshev** [comment]
@razims we will address this very soon. Stay tuned :)

**Comment by MattL75** [comment]
In regards to the closed PR - we can't compile the library through Angular 8 and still have it be compatible with Angular 7. If we adjust a couple things and compile with Angular 7, it would be compatible with ng8, however that's not a feasible long-term solution. In my mind, the best solution is to support multiple versions.

**Comment by droshev** [comment]
Let's try only to summarize the findings/investigations for this sprint(14) review. We can focus on finishing the other issues.

**Comment by razims** [comment]
@droshev @MattL75  i understand guys that moving angular forward will end up supporting two branches. But Angular based projects are already moving to ng8, you should go forward too. We started looking towards different libraries, as your plans are unclear for us.

**Comment by droshev** [comment]
@razims We have discussed this topic and I think we came up with a good way of handling multiple Angular major version. We will update you very soon.

**Comment by droshev** [comment]
we need to document what we did to support multiple versions of angular

**Comment by droshev** [comment]
@razims our latest master is already running on Angular 8. In case you want to start playing with it you can get the latest rc package. We are going to document the versioning meanwhile

**Comment by razims** [comment]
@droshev thanks Mladen

**Comment by droshev** [comment]
More info here https://github.com/SAP/fundamental-ngx/wiki#angular-version-support
