### ISSUE TITLE
"more" string in Download Supplier Invitation popup is hardcoded

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#8492]
This is a bug

"more" string in search bar of Download Supplier Invitation pop up is hardcoded.

angular 13

Steps to reproduce:

1. Go to an RFP event page
2. Click three dots top right, next to close.
3. Click Download supplier invitation.
4. Add multiple fields of information for download.

Screenshot of relevant source code is attached

NA
<img width="1133" alt="Screenshot 2022-08-01 at 10 15 56 AM" src="https://user-images.githubusercontent.com/110370099/182074251-ba54cd81-73b3-4142-9530-6d7595ff659f.png">

https://product-jira.ariba.com/browse/SS-36754

**Comment by droshev** [comment]
@sahanaN123 Is there a way to provide a little bit more information?

**Comment by platon-rov** [comment]
fixed.
