### ISSUE TITLE
[Fundamental / Platform] Space between message and field if counter exists 

### ISSUE THREAD

**Issue by emadaldin-baybars** [SAP/fundamental-ngx#8495]
#### Is this a bug, enhancement, or feature request?
Bug on Style

#### Briefly describe your proposal.
In this bug, I'm using the textarea with characters counter in this case the space between the message and the control is so big.

![6087db7d-3819-4523-b90a-5f4f60c2cb72](https://user-images.githubusercontent.com/10583606/182400897-d04e914f-d854-4954-b3c7-2f7cbc44fc47.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
    "@fundamental-ngx/platform": "~0.33.6",
    "@angular/core": "~13.3.0",

**Comment by droshev** [comment]
@yajo-baybars Would you mind sharing a snippet of code how you combined the form messages and the textarea?

**Comment by yajo-baybars** [comment]
Sure, Here it's 

```
<div fd-form-item *ngIf="(viewMode$ | async) !== 'DISPLAY'">
      <sugar-input-label [sugarBindings]="sugarBindings" [bindTo]="bindTo" [viewMode$]="viewMode$"></sugar-input-label>
      <fdp-textarea
          [id]="bindTo"
          [name]="bindTo"
          [formControlName]="bindTo"
          [maxLength]="valueLength"
          [showExceededText]="valueLength? true: false"
          [growing]="true"
          [growingMaxLines]="5"
          [cols]="10"
          wrapType="soft"
          [state]="fundamentalState != 'valid'? fundamentalState : 'default'"
          #textarea>
      </fdp-textarea>
      <fd-form-message
          *ngIf="textarea.value && fundamentalState !== 'valid'"
          [type]="fundamentalState"
          aria-live="assertive"
          aria-atomic="true">
          {{statusMessage$ | async}}
      </fd-form-message> 
  </div>
```

**Comment by emadaldin-baybars** [comment]
any updates ?!

**Comment by emadaldin-baybars** [comment]
Any updates friends ?
