### ISSUE TITLE
Remove dependencies and simplify installation process

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#85]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal
Our installation process is a little clunky, we should remove peer dependencies and have the Fundamental CSS be included automatically 
We need to link the latest version of fundamental-ngx to the latest tested released version of fundamental-ui.

#### What versions of Angular and Fundamental NGX? (If this is a feature request, use current version)
Angular 6.0.0, fundamental-ngx 0.0.3-beta

**Comment by droshev** [comment]
@mikerodonnell89 is something we can do to close this ticket? It's been a while

**Comment by droshev** [comment]
I think we have done this already
