### ISSUE TITLE
Component: Standard Input Control and RichText editor

### ISSUE THREAD

**Issue by alvachien** [SAP/fundamental-ngx#850]
#### Is this a bug, enhancement, or feature request?
Feature request.

#### Briefly describe your proposal.
Standard Input Editor, known as 'input' is quite popular in web application. It shall be supported by Fundamental controls.
RichText Editor, known as 'textarea' is quite popular in web applications. It shall be supported by Fundamental controls.

You can find that it is supported by Angular [Material](https://material.angular.io);

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
All version of NGX;

**Comment by MattL75** [comment]
I'm not sure what you mean. If by `Input Editor` you just mean a normal input element, then we have this in the [form section](https://sap.github.io/fundamental-ngx/form), and the same can be said for textarea. We do not have a rich text editor (yet?), but Material doesn't have one either. It could be considered an enhancement in the long run.

**Comment by alvachien** [comment]
@MattL75 Sorry, I didn't notice the Form section. 
I will close this issue.
