### ISSUE TITLE
SS-37530 | Calendar cannot be closed without selecting data using keyboard

### ISSUE THREAD

**Issue by akd-sap-ariba** [SAP/fundamental-ngx#8526]
#### Is this a bug, enhancement, or feature request?
Bug Fix

#### Briefly describe your proposal.
Observed Behavior:

On accessing any Calendar button a calendar popup is displayed on the screen, this popup cannot be closed using keyboard without selecting any value. To close this popup any date should be selected. But with mouse it’s a different functionality.

Expected Behavior:   

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular-13,
fundamental-ngx/core : ~0.31.2",
fundamental-ngx/platform : 0.31.2",
ngx-translate/core : ^14.0.0",
ngx-translate/http-loader : ^7.0.0",

#### If this is a bug, please provide steps for reproducing it.
On accessing any Calendar button a calendar popup is displayed on the screen, this popup cannot be closed using keyboard without selecting any value. To close this popup any date should be selected. But with mouse it’s a different functionality.
#### Is there anything else we should know?
JIRA Defect - https://product-jira.ariba.com/browse/SS-37530

**Comment by N1XUS** [comment]
@akd-sap-ariba Example code would be nice. On this example: https://fundamental-ngx.netlify.app/#/core/calendar#mobile I can close dialog with escape button. With this example https://fundamental-ngx.netlify.app/#/core/date-picker#simple escape button also works
