### ISSUE TITLE
Project setup problem

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#8531]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

Unable to do `yarn install `with latest git version with message:

```
Error: Failed to find Electron v2.0.18 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip
    at Request.<anonymous> (/Users/i304804/Documents/projects/fundamental-ngx/node_modules/nugget/index.js:169:61)
```
Does anybody has the same issue on latest `M1` chips? 
I see electron is in **dependencies** what are we use this for?

**Comment by droshev** [comment]
@fkolar did you try with npm version 6?

**Comment by platon-rov** [comment]
Seems like it's the issue with m1 (arm) and electron and not the library itself, closing.
