### ISSUE TITLE
Action Sheet is missing SemiBold font for items (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8536]
The Action Sheet component is not currently using the SemiBold font in the items.

This differs from the UI5 implementation (Morning Horizon)
https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.ActionSheet/sample/sap.m.sample.ActionSheet
Make sure to switch to the Morning Horizon theme when looking at the UI5 implementation.

**Comment by InnaAtanasova** [comment]
Closing this issue as it's concerning the css and should be addressed in fund-styles (if needed). The issue in fund-styles: https://github.com/SAP/fundamental-styles/issues/3797
