### ISSUE TITLE
Font weight for button does not correspond to Morning Horizon specs

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8537]
The font weight used in the button is not bold enough compared to the specs:
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698912599

The UI5 implementation has the correct font weight:
https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button

**Comment by InnaAtanasova** [comment]
Closing this issue as it's concerning the css and should be addressed in fund-styles (if needed). The issue in fund-styles: https://github.com/SAP/fundamental-styles/issues/3798
