### ISSUE TITLE
Card header title and subtitle should have the same height (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8538]
According to the [Morning Horizon specs for the Card](https://wiki.one.int.sap/wiki/display/visualcore/Card+(Horizon)+-+Card+Anatomy), the header title and subtitle should have the same height

**Comment by InnaAtanasova** [comment]
Closing this issue as it's concerning the css and should be addressed in fund-styles (if needed). The issue in fund-styles: https://github.com/SAP/fundamental-styles/issues/3800
