### ISSUE TITLE
Carousel: Navigation button size is incorrect (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8539]
According to the [Morning Horizon Carousel Specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913168), the navigation button size should be 2.125 rem with 0.25 rem padding on top and at the bottom.

**Comment by InnaAtanasova** [comment]
Closing this issue as it's concerning the css and should be addressed in fund-styles (if needed). The issue in fund-styles: https://github.com/SAP/fundamental-styles/issues/3801
