### ISSUE TITLE
Row height is greater than the 2.5 rem specified (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8540]
Row height is greater than the 2.5 rem [specified ](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913232)(Morning Horizon)

**Comment by InnaAtanasova** [comment]
Closing this issue as it's concerning the css and should be addressed in fund-styles (if needed). The issue in fund-styles: https://github.com/SAP/fundamental-styles/issues/3802
