### ISSUE TITLE
Feed List Item does not correspond to specs (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8541]
Feed List Item does not correspond to [specs ](https://wiki.one.int.sap/wiki/display/visualcore/Feed+%28Horizon%29+-+FeedListItem)(Morning Horizon)

**Comment by InnaAtanasova** [comment]
Closing this issue as it's concerning the css and should be addressed in fund-styles (if needed). The issue in fund-styles: https://github.com/SAP/fundamental-styles/issues/3803
