### ISSUE TITLE
Icon missing in Form Message for input validation (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8542]
According to the [specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698914037), there should be an icon in the Form Message for input validation (Morning Horizon)

**Comment by InnaAtanasova** [comment]
This is a duplication of an issue in [Fund-styles](https://github.com/SAP/fundamental-styles/issues/3804)
@platon-rov we need to first see if we can handle everything in fund-styles and if changes are needed here as well. Keeping the issue open until we fix it in fund-styles.

**Comment by platon-rov** [comment]
fixed in styles, no changes needed in ngx.
