### ISSUE TITLE
Slider cursor does not have arrows (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8543]
According to the [specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915260), the slider cursor should have arrows (Morning Horizon)

**Comment by InnaAtanasova** [comment]
Hi @obc514 this is coming from fund-styles and we are aware of this. Having the arrows required a breaking change so we decided to not have them (for now). Closing this issue as a similar one is open in fund-styles and we can continue the discussion there.
