### ISSUE TITLE
Timeline does not have expand/collapse (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8544]
According to the [specs,](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915855), the timeline should have the expand/collapse feature (Morning Horizon)

**Comment by InnaAtanasova** [comment]
Hi @obc514 we do not have this feature yet. Could you reach out to us to discuss it further so we can plan this accordingly? Thank you!
