### ISSUE TITLE
Bug: Calendar component next month click

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-ngx#855]
#### Is this a bug, enhancement, or feature request?

Fundamental-react was having some problems with the Calendar component this morning due to it being the 31st, which shows up in the next month on our calendar. I was looking at ngx to see how you handled it and found that the next button skips June. I'm betting this is due to the same problem as in fundamental-react - having previous months days show up in the calendar. 

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

0.5.2

#### If this is a bug, please provide steps for reproducing it.

![2019-05-31 09 07 53](https://user-images.githubusercontent.com/29607818/58719084-b6a91700-8383-11e9-8512-084a9bddfd46.gif)

**Comment by MattL75** [comment]
How did we not notice this before...? Big thanks for the report @jbadan
