### ISSUE TITLE
Control the submenu popup position from right to left

### ISSUE THREAD

**Issue by XYF001** [SAP/fundamental-ngx#8555]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
when using fd-menu and fd-submenu, if menu button is at the right side, the sub menu will be partial displayed and exceeds the screen.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 13, Fundamental library 0.35.4
#### If this is a bug, please provide steps for reproducing it.
use the demo in [menu with-submenu](https://sap.github.io/fundamental-ngx/#/core/menu#with-submenu), change the css to make button at right side. Click the button to show menu and sub menu. The sub menu is partial displayed.

![image](https://user-images.githubusercontent.com/24812746/184585627-6f595211-e5d7-4027-be04-9ddcd10cbf0a.png)

#### Please provide relevant source code if applicable.
[stackblitz](https://stackblitz.com/edit/angular-qmefea?file=src%2Findex.html,src%2Fapp%2Fmenu-with-submenu-example.component.html,src%2Fapp%2Fapp.module.ts)

**Comment by mikerodonnell89** [comment]
I am wondering if we should provide an input that would essentially have this component function as though it's in RTL mode, and of course if the RTL service is returning true then we'd run that specific menu in LTR mode. Thoughts @SAP/fundamental-denoland-team ?

**Comment by XYF001** [comment]
Hi @mikerodonnell89   Finally UX changed the UI not using the submenu. I will close this issue.
