### ISSUE TITLE
Wizard Dialog Title size/weight inconsistency with specs (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8561]
The Wizard Dialog title should be the same as the one specified in the [specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697897301) and in [UI5](https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.Wizard/sample/sap.m.sample.WizardSingleStep)

**Comment by InnaAtanasova** [comment]
Hi @obc514 the title of the Wizard Dialog is customizable by the user:
```
<fd-dialog-header>
       <h2 fd-title [headerSize]="2">Checkout</h2>
</fd-dialog-header>
```

The user can provide whatever content they want between the `<fd-dialog-header>` tags.
