### ISSUE TITLE
Datetime-picker selecting time does not update angular form

### ISSUE THREAD

**Issue by DorinR** [SAP/fundamental-ngx#857]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

If you click the calendar in the datetime picker, it updates the value in the form. But if you update the time, the form is not updated. (see branch datetime-form)

**Comment by JKMarkowski** [comment]
I'll take a look on it.

**Comment by JKMarkowski** [comment]
Hi @DorinR It's not related to fundamental-ngx issue. You can check it, by subscribing on form value changes. The value is updated, but html does not detect any change, so value shown in template is the same.

**Comment by MattL75** [comment]
> The value is updated, but html does not detect any change, so value shown in template is the same.

Yeah that sounds about right, especially since it does work correctly through ngModel. Maybe worth investigating more with your fd-datetime example @DorinR.

**Comment by droshev** [comment]
@mikerodonnell89 can you retest once we merge all open PRs?

**Comment by JKMarkowski** [comment]
Resolved.
