### ISSUE TITLE
Peer Dependency Error with Angular 14

### ISSUE THREAD

**Issue by toaster75** [SAP/fundamental-ngx#8575]
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "^14.1.3"
"@fundamental-ngx/core": "^0.35.4",

trying to update to the latest version of fundamental and getting peer dependency errors 

npm ERR! Found: @angular/animations@14.1.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^14.1.3" from the root project
npm ERR! 
npm ERR! peer @angular/animations@"^13.0.0" from @fundamental-ngx/core@0.35.4
npm ERR! node_modules/@fundamental-ngx/core
npm ERR!   @fundamental-ngx/core@"^0.35.4" from the root project

used the --force command to update fundamental, but this ended badly for the application as you can see in the screenshot.
![image](https://user-images.githubusercontent.com/43145392/185710042-6ccd28df-706c-43b0-87c9-f7da27727efa.png)

Will fundamental be able to run in Angular 14, or will I need to downgrade the application to Angular 13?

**Comment by N1XUS** [comment]
@toaster75 Hello. Version 0.36.0 will support angular 14. You can try installing latest RC version (currently it's [0.36.0-rc.28](https://www.npmjs.com/package/@fundamental-ngx/core/v/0.36.0-rc.28))

**Comment by toaster75** [comment]
Thank you for your quick response.
