### ISSUE TITLE
fdp-multicheckbox issue with same name 

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#8587]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
I am using fdp-multicheckbox component.

Example:
If Apple is from Fruits category and again Apple is from Fruits1 category, it looks like:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/107252602/185840945-45f2280d-3bf0-4a8f-9532-a68ea4f34958.png">

[Multicheckbox stackblitz link - Just type Apple and select](https://stackblitz.com/edit/angular-6mvwz6?file=src/app/multi-combobox-columns-example.component.ts
)

RealWorld example  - If two users have same name but belong to a different group. Then we are observing this issue.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
13.3.4

#### If this is a bug, please provide steps for reproducing it.
[Multicheckbox stackblitz link - Just type Apple and select](https://stackblitz.com/edit/angular-6mvwz6?file=src/app/multi-combobox-columns-example.component.ts
)

#### Is there anything else we should know?
Please fix this ASAP
 [Reference -](https://stackblitz.com/edit/primeng-multiselect-demo-vggwuh?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html)

**Comment by fkolar** [comment]
yes, seems like a problem. You are probably using default Array DataProvider, which does not reflect RealWorld scenario and its meant more to work with local arrays. 
Better approach is to implement custom DataProvider and even here you can implement custom DataProvider, where you implement custom search logic.

**Comment by prasad-userdev** [comment]
The example which I have shared is for easy understanding purpose only
