### ISSUE TITLE
Components that need refactoring related to Skeleton

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#8601]
In order to implement the Skeleton feature, some components need to be refactored and it should be done out of the scope of the Skeleton task.

For these components, the Skeleton switch will be disabled in the documentation and added later when the feature is implemented.

These components are:
- [ ] Timeline
  Timeline nodes are not recovered properly after exiting from skeleton mode.
- [ ] Toolbar, overflow mode.
  The overflow menu is not recovered properly after exiting from skeleton mode. 
  Component still doesn't use Overflow Layout.
- [ ] Value Help Dialog
  Component styles are overriding the default ones of some basic components which are used inside.

**Comment by platon-rov** [comment]
Only 2 blockers in Core - Timeline & Toolbar in Overflow Mode.

**Comment by platon-rov** [comment]
VHD is a blocker in Platform.

**Comment by platon-rov** [comment]
Not needed anymore with new implementation of skeleton.
