### ISSUE TITLE
[sourcing]: fdp-table - support expand all

### ISSUE THREAD

**Issue by I835291** [SAP/fundamental-ngx#8604]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Unable to expand all
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
13
#### If this is a bug, please provide steps for reproducing it.
- Create a tree table with many parents and children
- Unable to expand all
#### Is there anything else we should know?
Showed Frank and Kevin

**Comment by droshev** [comment]
We don't have a tree in ngx at the moment

**Comment by skaquib123** [comment]
Hi @I835291,  as discussed  this is solved in PR #8903 
[https://github.com/SAP/fundamental-ngx/pull/8903](url). 
Hence, I am closing this issue.
