### ISSUE TITLE
[sourcing]: fd-breadcrumb overflow menu is not working

### ISSUE THREAD

**Issue by I835291** [SAP/fundamental-ngx#8610]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Overflow menu for breadcrumb is not working. This is reproducible on the F-NGX example as well.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
13
#### If this is a bug, please provide steps for reproducing it.
1. Create a breadcrumb with 2 level items. Click on the link to go to parent.
2. resize your window so that overflow menu is shown. Click on the menu option, nothing happens
#### Is there anything else we should know?
We are current used this component and customer has the issue with overflow menu. Please help us to fix this. Thanks much!

**Comment by mikerodonnell89** [comment]
This was fixed in #8599, will be in the next release but the fix is present in the latest RC if you need an immediate fix
