### ISSUE TITLE
Core Wizard Circular Dependency

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-ngx#8625]
#### Is this a bug, enhancement, or feature request?
A bit of all

#### Briefly describe your proposal.

The `WizardStepComponent` uses a `WizardStepIndicatorComponent`, at the same time, the `WizardStepIndicatorComponent` needs to know about stacked steps, also `WizardComponent` relies on `WizardStepIndicatorComponent`'s stacked wizard steps' property. We have **circular dependency** because of that.

`wizard/wizard-step-indicator/wizard-step-indicator.component.ts` <-> `wizard/wizard-step/wizard-step.component.ts`

**Comment by mikerodonnell89** [comment]
Duplicate of #8664
