### ISSUE TITLE
fdp-multi-combobox - Items selected and the count shown on the input box doesnt match

### ISSUE THREAD

**Issue by prasad-userdev** [SAP/fundamental-ngx#8633]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Count should match the selected item

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13.x
ngx 0.35.4

#### If this is a bug, please provide steps for reproducing it.
https://stackblitz.com/edit/angular-6mvwz6?file=src%2Fapp%2Fmulti-combobox-columns-example.component.ts
<img width="516" alt="image" src="https://user-images.githubusercontent.com/107252602/187988391-2debc8c2-ef7c-4690-a95a-f6c9f0c7b8be.png">
I also observed, when the input width is increased the count works fine. But this issue comes up when we try to do a horizontal scroll in the input box to check the selected ones.

**Comment by skaquib123** [comment]
@mikerodonnell89 I am confused with expected behaviour. Is it suppose to show "2 more" but also display all the tokens or is it suppose to show all the tokens without "_ more" and accessible only through scroll??

**Comment by skaquib123** [comment]
@prasad-userdev  as discussed, when we keep adding new item in the multi-combobox it is automatically scrolling to right and this achieved in PR #8623. I hope it solves the issue.

**Comment by prasad-userdev** [comment]
Thanks for the update.
