### ISSUE TITLE
Tile title is not aligned properly (Issue in Firefox and Safari) 

### ISSUE THREAD

**Issue by rameshwarsankhala** [SAP/fundamental-ngx#8675]
bug
#### Briefly describe your proposal.
Project names should be aligned in safari and firefox as in Chrome

#### Which versions of Angular and Fundamental Library for Angular are affected? 
NGX version: 0.35.4

In Safari and Firefox:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/26029884/189587926-5997b60d-7c28-439a-ae05-b49470107289.png">

In Chrome(Expected behavior):
![image](https://user-images.githubusercontent.com/26029884/189596257-52f7fa71-a2d6-4888-b93e-04891b342bff.png)

**Comment by mikerodonnell89** [comment]
Could you provide a stackblitz demoing this issue? I think some other parent element may be causing this as the alignment is looking fine in the documentation on safari and firefox:
<img width="329" alt="Screen Shot 2022-09-30 at 1 55 07 PM" src="https://user-images.githubusercontent.com/2471874/193346705-931c7672-a40c-4382-9742-842e19f6578e.png">

**Comment by droshev** [comment]
@rameshwarsankhala we will close the issue as there is not much activities. In case you are able to reproduce, please, drop us a stackblitz example so we can investigate it faster.
