### ISSUE TITLE
Issue in search bar.

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8678]
#### Briefly describe your proposal.

In the earlier version of NGX there used to be clear button inside the **input-group** component for glyphAriaLabel = "Search"
But in the current version there is no clear button appearing inside the search bar. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

V 0.35.4

#### If this is a bug, please provide steps for reproducing it.

Steps for reproducing it :- 
1. Create a Search input with search type using input-group.
2. set the glyphAriaLabel property as "Search".

#### Please provide relevant source code if applicable.

The code snippet can be found at :- https://stackblitz.com/edit/angular-rxdjkb?file=src%2Fapp%2Finput-group-search-example.component.html

**Comment by mikerodonnell89** [comment]
Some webkit browsers would add this small 'x' to any `<input type="search">`. Because it wasn't uniform across all browsers, we have hidden this 'x' in our library via CSS. If you would like to utilize this functionality we encourage you to set up your input group like this code snippet here: 

```
    <fd-input-group
        glyph="decline"
        glyphAriaLabel="Clear"
        placeholder="Search"
        [button]="true"
        [disabled]="false"
        [(ngModel)]="searchTerm"
        (addOnButtonClicked)="searchTerm = ''"
    >
    </fd-input-group>
```
