### ISSUE TITLE
ɵinternalBootstrapApplication was not found

### ISSUE THREAD

**Issue by rolfen** [SAP/fundamental-ngx#8679]
#### Is this a bug, enhancement, or feature request?
Bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@angular/core version 14.2.1
@fundamental-ngx/core  version 0.36.0

#### If this is a bug, please provide steps for reproducing it.

Adding the following to `app.module.ts` and compiling produces the error below. Some code was removed for brevity and replaced by `//...`

```
// ...

import { FundamentalNgxCoreModule } from '@fundamental-ngx/core';

// ...

@NgModule({
  // ...
  imports: [
    // ...
    FundamentalNgxCoreModule
  ],

// ...
```

The error:

```
./node_modules/@fundamental-ngx/core/node_modules/@angular/platform-browser/fesm2020/platform-browser.mjs:1318:9-38 - Error:
 export 'ɵinternalBootstrapApplication' (imported as 'ɵinternalBootstrapApplication') was not found in '@angular/core' (poss
ible exports: ANALYZE_FOR_ENTRY_COMPONENTS, ANIMATION_MODULE_TYPE, APP_BOOTSTRAP_LISTENER, APP_ID, APP_INITIALIZER, Applicat
ionInitStatus, ApplicationModule, ApplicationRef, Attribute, COMPILER_OPTIONS, CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrate
gy, ChangeDetectorRef, Compiler, CompilerFactory, Component, ComponentFactory, ComponentFactoryResolver, ComponentRef, Conte
ntChild, ContentChildren, DEFAULT_CURRENCY_CODE, DebugElement, DebugEventListener, DebugNode, DefaultIterableDiffer, Directi
ve, ENVIRONMENT_INITIALIZER, ElementRef, EmbeddedViewRef, EnvironmentInjector, ErrorHandler

//...

```

#### Is there anything else we should know?

Angular changed the name of the function from `ɵinternalBootstrapApplication` to `ɵinternalCreateApplication` in 14.2.1 which is causing this error.

It is located in `node_modules/@angular/core/index.d.ts` around line 10330 or so in @angular/core version 14.2.1

**Comment by rolfen** [comment]
`@fundamental-ngx/i18n` is requesting an old version of `@angular/platform-browser-dynamic` which is not compatible with the latest version of `@angular/core`, this causes the error when these two modules try to work together.

```
{
  "name": "@fundamental-ngx/i18n",
  "version": "0.36.0",
  "peerDependencies": {
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "rxjs": "7.5.6",
    "zone.js": "0.11.7",
    "@angular/platform-browser-dynamic": "14.0.2"
  },
// ...
```

**Comment by slithzerikai** [comment]
Is there any sort of workaround until this gets addressed properly?

**Comment by g-cheishvili** [comment]
Hopefully, this is fixed with that patch up there

**Comment by m8524769** [comment]
> Is there any sort of workaround until this gets addressed properly?

Downgrading the angular to `~14.0.0` will solve this problem.
