### ISSUE TITLE
problem fd-pagination in rtl mode

### ISSUE THREAD

**Issue by Mohammadreza-Mohammadi** [SAP/fundamental-ngx#8683]
#### Is this a bug, enhancement, or feature request?
this is a bug.
#### Briefly describe your proposal.
in RTL mode the numbers must be start from right to left.
sample :
LTR  1 2 3 4 5 6
RTL 6 5 4 3 2 1

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 13.2
core 0.36
#### If this is a bug, please provide steps for reproducing it.
in the example page of components change LTR to RTL mode.

**Comment by mikerodonnell89** [comment]
thanks @Mohammadreza-Mohammadi this should be fixed in #8697 could you please review?
