### ISSUE TITLE
Time Picker does not correspond to specs (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8684]
The Time Picker got a new design(https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915874) and the [UI5 Implementation](https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.TimePicker/sample/sap.m.sample.TimePicker)

**Comment by mikerodonnell89** [comment]
blocked by https://github.com/SAP/fundamental-styles/issues/3868
