### ISSUE TITLE
Search not working until we click on search icon (Firefox and Safari). 

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8688]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

The search bar doesn't work as expected in Firefox and Safari. When we want to search for an element, we have to click on the search icon explicitly for it to work. Whereas in Chrome it works even if we press enter and searches the element. This same behaviour should happen in Firefox and Safari but currently it doesn't work as expected.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.35.4

Steps for reproducing it :-

      1. Create a Search input with search type using input-group.
      2. set the glyphAriaLabel property as "Search".

Open the Project in either Firefox or Safari browser in order to reproduce it.

#### Is there anything else we should know?
This issue occurs only in Firefox and Safari **Not** in Chrome

**Comment by mikerodonnell89** [comment]
Are you referring to the platform search field? https://sap.github.io/fundamental-ngx/#/platform/search-field

If not, can you provide more details? Maybe a snippet of your html?

**Comment by sameesheikh25** [comment]
Was referring to  Input Group Search in 
https://624793d2f1d02d000925c339--fundamental-ngx.netlify.app/#/core/input-group

**Comment by mikerodonnell89** [comment]
I think what you may be seeing here is browsers handling the `(search)` event differently: https://caniuse.com/mdn-api_htmlinputelement_search_event

Because refactoring this component to emit the search event on keyup rather than on search would be a breaking change, currently I would recommend implementing your own `(keyup.enter)` handling on the input group element like so:

```
    <fd-input-group
        type="search"
        glyph="search"
        glyphAriaLabel="Search"
        placeholder="Search"
        [button]="true"
        [disabled]="false"
        [(ngModel)]="searchTermSecond"
        (keyup.enter)="customSearchFunction()"
    >
```

Thoughts @droshev @InnaAtanasova @g-cheishvili @platon-rov @N1XUS ?

**Comment by N1XUS** [comment]
You can use `(ngModelChange)` event which will be triggered each time model has been changed (e.g. user types something) https://stackblitz.com/edit/document-menu-accessibility-ln76bh?file=src%2Fapp%2Fpopover-trigger-example.component.html,src%2Fapp%2Fpopover-trigger-example.component.ts,src%2Fapp%2Fpopover-trigger-example.component.css
