### ISSUE TITLE
Busy Indicator coming on top on safari

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8711]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
We are using busy indicator component in our project. But its showing weird behaviour in **safari** browser. 
Whenever we load our page the busy indicator appears on the top of page. This behaviour is **not** observed in other browser like
chrome and Firefox. I have attached the screenshot for the same.

<img width="1023" alt="MicrosoftTeams-image (17) new" src="https://user-images.githubusercontent.com/102856000/190993036-034637ca-972c-4150-a57b-c484edb4ad78.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
version affected - 0.35.4

#### If this is a bug, please provide steps for reproducing it.
Put a busy indicator in our project and open the project in **safari** browser only. You will see busy indicator coming on the top of 
screen.

#### Is there anything else we should know?
**This issue is only reproducible in Safari browser.**

**Comment by mikerodonnell89** [comment]
@sameesheikh25 are you still seeing this bug with current versions? If so, could you please provide more context in the form of example code, a stackblitz etc

<img width="1783" alt="Screenshot 2023-01-11 at 9 00 19 AM" src="https://user-images.githubusercontent.com/2471874/211855003-2d8fb67c-a9ec-486e-ba4a-73369888a484.png">

**Comment by sameesheikh25** [comment]
The issue is still reproducible in the newer version of ngx.
The busy indicator stills continues to come on top in safari browser
