### ISSUE TITLE
hand icon not coming when hover over select component

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8716]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The hand icon doesn't come when hovered over the select element in NGX. In the earlier versions it used to show the hand icon as well. But in the latest one it shows the hand icon only when hovered over dropdown icon in right corner of the select component.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.
version -> 0.35.4

#### If this is a bug, please provide steps for reproducing it.

- Implement the given code snippet in the current version [0.35.4] and try to hover over that element it doesn't show the hand icon over entire element.

-  Now try to implement the given code snippet in the previous version [0.34.2] and try to hover over that element it  show the hand icon over entire element.

#### Please provide relevant source code if applicable.
<fd-select placeholder="Select an option" [(value)]="selectedValue1">
    <li fd-option *ngFor="let option of options" [value]="option">{{ option }}</li>
</fd-select>

#### Is there anything else we should know?
In the previous version the behaviour is different then what we observe now.

**Comment by platon-rov** [comment]
It's fixed in 0.37.1, can you update to this version or newer?

**Comment by sameesheikh25** [comment]
As of now we are using v0.35.4 in our project 
So is there any way we can achieve this behaviour in this version

**Comment by platon-rov** [comment]
The easiest way to fix it is to add the next to styles

```css
::ng-deep {
  fd-select {
    cursor: pointer;
  }
}
```

**Comment by platon-rov** [comment]
Not reproducible on the latest version, closing.
