### ISSUE TITLE
[Sourcing] SS-38610 Hardcoded text & buttons in event bidding start time date picker

### ISSUE THREAD

**Issue by i563785** [SAP/fundamental-ngx#8717]
Bug

"Hrs", "Min", "Period", "OK", "Cancel" labels are hardcoded in English and are not being translated for other languages. These labels need to be translated as per the selected language.

Angular version affected: Angular 12

Steps to reproduce the bug on Fundamental NGX playground:

1. Go to https://sap.github.io/fundamental-ngx/#/core/home
2. Click on 'Datetime Picker' option under components on the left of the page 
3. Scroll to i18n example
4. Change the language to any non-English language
5. Click on the calendar icon below
6. Observe the untranslated labels

**Comment by mikerodonnell89** [comment]
These are translated:
<img width="219" alt="Screen Shot 2022-09-30 at 1 28 37 PM" src="https://user-images.githubusercontent.com/2471874/193342962-fcb05b0e-cae5-4f57-9dbe-9d7befa6783d.png">

Some languages are still missing translations and will default to English

**Comment by I568944** [comment]
<img width="1728" alt="Screenshot 2022-10-04 at 10 32 37 AM" src="https://user-images.githubusercontent.com/114974812/193738326-93074db2-9c88-42af-b187-b225c43fe54c.png">
These strings are not getting translated as verified at [https://sap.github.io/fundamental-ngx/#/core/datetime-picker](url)

**Comment by fkolar** [comment]
@i563785, Please do not provide a links to internal issues, this is open source projects with many contributors that does not have access to some internal links.

**Comment by I543348** [comment]
Could you please confirm if "Ok" and "Cancel" button texts are also being translated ?
Thanks.

**Comment by mikerodonnell89** [comment]
There is currently a disconnect with how our calendar handles i18n (using the DatetimeAdapter) compared to the rest of the library (using the @fundamental-ngx/i18n package). Because datetimepicker is a composite of the calendar and time components, we are seeing the discrepancy here. We'll need to sync these up. Thank you for filing this issue. In the meantime you can also see the documentation for i18n (https://sap.github.io/fundamental-ngx/#/core/i18n) to see how to handle translations for the rest of the library, but I think we should make this a priority

**Comment by mikerodonnell89** [comment]
> <img alt="Screenshot 2022-10-04 at 10 32 37 AM" width="1728" src="https://user-images.githubusercontent.com/114974812/193738326-93074db2-9c88-42af-b187-b225c43fe54c.png">
> 
> These strings are not getting translated as verified at [https://sap.github.io/fundamental-ngx/#/core/datetime-picker](url)

To further clarify - the translations you are seeing on the calendar in the quoted screenshot are coming from the DatetimeAdapter. "Sec/Min" and "Ok/Cancel" are not hardcoded in their components, but are actually translated via the [fundamental-ngx/i18n](https://sap.github.io/fundamental-ngx/#/core/i18n) module.  So one current workaround would be that wherever you allow the user to change the locale of the calendar, you could also run some similar logic to the fundamental-ngx/i18n module that would change the "Hrs/Sec/Min" and "Ok/Cancel" of the rest of the datepicker. Or vice-versa. And this logic can be ran globally or per component.

Unfortunately the locales between DatetimeAdapter and fundamental-ngx/i18n will not have a 1:1 correlation - for example when changing the DatetimeAdapter to use `"en-us"` you will need to tell fundamental-ngx/i18n to use `FD_LANGUAGE_ENGLISH`. 

This is admittedly a disjointed approach to localization. One advantage is that the calendar does currently allow more customization than the rest of the library. However I do think these need to be unified, so next week I'll be discussing with my time to find a solution. In the meantime I'll be updating datetimepicker's documentation to demonstrate the temporary solution I described above

**Comment by mikerodonnell89** [comment]
Here is the draft example pull request (I still wish to discuss this with my team and fix e2e tests before merging)

https://github.com/SAP/fundamental-ngx/pull/8810/files

**Comment by I543348** [comment]
Hi @mikerodonnell89 , Could you please confirm if there are any updates on this issue ?

**Comment by droshev** [comment]
the issue seems to be fixed already. If you switch to French you will see this:
![Uploading Screenshot 2023-01-25 at 10.09.27 AM.png…]()
