### ISSUE TITLE
Issue with dialog in Firefox browser.

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8725]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
We are using the list component in our project. But we are getting one issue while running our project in Firefox browser. The list dialog is not consistent in chrome and Firefox. For the same dimension of dialog box we can see different behaviour in different browsers. I have attached the screenshot for the same to briefly explain the issue.

List in Firefox:-
<img width="176" alt="firefox list" src="https://user-images.githubusercontent.com/102856000/191541057-e219494c-97b4-4251-b7bb-d25a268fa14a.png">

List in Chrome:-
<img width="177" alt="chrome list" src="https://user-images.githubusercontent.com/102856000/191541440-16a1903b-ba5a-449f-bb30-07727466d132.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.35.4

#### Is there anything else we should know?
This issue is only Reproducible in **Firefox** browser.

**Comment by mikerodonnell89** [comment]
Unable to recreate this issue, @sameesheikh25 if this persists please provide a stackblitz demonstrating the problem and reopen this issue
