### ISSUE TITLE
Message States are not positioned correctly (wizard generator)

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8727]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Message States are not positioned correctly

`dxp/template-ui/issues/311`

will try to tackle in sprint 98

**Comment by mikerodonnell89** [comment]
Can you post a screenshot and maybe some more details? DXP issues are on the enterprise github

**Comment by littleamigo** [comment]
> Can you post a screenshot and maybe some more details? DXP issues are on the enterprise github

![image](https://user-images.githubusercontent.com/33327256/194623824-bfae9062-6987-4818-a231-ea404fb36258.png)
![image](https://user-images.githubusercontent.com/33327256/194623899-c86c3eff-eca3-4622-9a69-d32165632cff.png)

**Comment by platon-rov** [comment]
cannot reproduce, dxp uses outdated ngx version, probably it's fixed already.
