### ISSUE TITLE
[Wizard when Branching] Review pages listed also not visible inputs

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8728]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
We have created a wizards content, with when conditions, and
the field Namespace is shown when project is selected and not shown when library is selected.

In preview Page we see parameters for the two possible inputs

`dxp/template-ui/issues/245`

we will try to tackle it in sprint 98

**Comment by platon-rov** [comment]
cannot reproduce, dxp uses outdated ngx version.

**Comment by platon-rov** [comment]
reproduced, fixed and raised pr
