### ISSUE TITLE
(enhancement) Change on hover pop-up text when hovering over a List Item description

### ISSUE THREAD

**Issue by kiril-keranov** [SAP/fundamental-ngx#8757]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
When using list items for example Standart List Items https://sap.github.io/fundamental-ngx/#/platform/standard-list-item be able to change the value of the on hover pop-up for the description part. For example:
![image](https://user-images.githubusercontent.com/114745615/193272679-f59dea62-e5aa-4b00-b207-43b98269b8a2.png)
be able to change the on hover pop-up value when hovering over the name in the description text.
Changing the hover pop-up value is needed for both text item spans in the description part, currently resembled on the picture by the name and the date.

**Comment by mikerodonnell89** [comment]
I am unable to get our inline help directive to cooperate here - need to dig in to that

**Comment by N1XUS** [comment]
@kiril-keranov We've extended default [description] and [secondary] input properties. Now you can pass an object containing ariaLabel, title and text

**Comment by ivzhelev** [comment]
@N1XUS we tried to do it like described in the example here:
https://github.com/SAP/fundamental-ngx/blob/main/libs/docs/platform/standard-list-item/examples/platform-standard-list-item-example.component.html#L8-L11

However it just won't work due to:

![image](https://user-images.githubusercontent.com/8601332/203877372-c7ab44ab-5fb9-4777-847e-702ba1e425c2.png)

**Comment by g-cheishvili** [comment]
> Did we do sth wrong?

Which version of platform is that? It says that type for description is `Nullable<string>`, but in latest releases type actually is `Nullable<string | { text: string; ariaLabel?: string; title?: string }>`

**Comment by ivzhelev** [comment]
With the latest fdp rc (0.37.0-rc.29) everything is working correctly and as expected like described in the example here:
https://github.com/SAP/fundamental-ngx/blob/main/libs/docs/platform/standard-list-item/examples/platform-standard-list-item-example.component.html#L8-L11

Thank you for your efforts and for providing/releasing this feature request.

**Comment by droshev** [comment]
as it is fixed we are closing it
