### ISSUE TITLE
bug(core): multi input's input field broken

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#8790]
#### Is this a bug, enhancement, or feature request?

bug.

#### Briefly describe your proposal.

When typing anything to multi-input's input field list with options gets opened instead.

https://user-images.githubusercontent.com/20265336/194273292-6afd21e2-2ffc-4770-9c96-02f68963be11.mov

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.36.1-rc.25

**Comment by mikerodonnell89** [comment]
This is behaving as intended, see the ui5 examples https://sapui5.hana.ondemand.com/#/entity/sap.ui.webc.main.MultiInput/sample/sap.ui.webc.main.sample.MultiInput

**Comment by platon-rov** [comment]
@mikerodonnell89 not only the dropdown got opened (what's ok), but focus is lost from the input field, it's needed to focus again to start typing.

**Comment by mikerodonnell89** [comment]
O
