### ISSUE TITLE
bug(core): segmented button gets touched state too late

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#8791]
#### Is this a bug, enhancement, or feature request?

bug.

#### Briefly describe your proposal.

`onTouched` state is not applied to the segmented button after click, instead it gets applied once we click somewhere else.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.36.1-rc.25

**Comment by mikerodonnell89** [comment]
This is behaving as intended, onTouched should be applied on blur, not when the element is first clicked or focused. I do agree the naming is counterintuitive but see here: https://angular.io/api/forms/ControlValueAccessor#registerontouched

**Comment by platon-rov** [comment]
@mikerodonnell89 yea, it's true for inputs where we can change value dozen of times and only then blur the field and process the validation, but for buttons it probably should behave differently as single click is changing value "completely" and there is no states in between, i hope it makes sense.

Here is the example of how behaves angular material segmented button
https://stackblitz.com/edit/angular-ebyfph?file=src/app/button-toggle-overview-example.html
