### ISSUE TITLE
textarea field: whitespace between label and content too large

### ISSUE THREAD

**Issue by emadaldin-baybars** [SAP/fundamental-ngx#8799]
#### Is this a bug, enhancement, or feature request?
bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "~13.2.2",
"@fundamental-ngx/core": "0.35.4",
"fundamental-styles": "0.24.4",

#### If this is a bug, please provide steps for reproducing it.
Whitespace is too large between label and textarea for sugar field textarea.
<img width="1131" alt="textarea-whitespeace-too-large" src="https://user-images.githubusercontent.com/10583606/194343334-33e3f6bb-90dc-40ff-a410-3f61c93c912f.png">

**Comment by emadaldin-baybars** [comment]
any updates ?

**Comment by emadaldin-baybars** [comment]
Any updates ?!

**Comment by platon-rov** [comment]
Not reproducible on the latest version, closing.
