### ISSUE TITLE
bug(platform): wizard generator selecting step by scrolling is broken

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#8802]
#### Is this a bug, enhancement, or feature request?

bug.

Probably related to https://github.com/SAP/fundamental-ngx/issues/7046

#### Briefly describe your proposal.

When being on step 2 in default example and then scrolling up - step 1 doesn't get selected.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/20265336/194537489-a5f282fc-2949-4bc0-9fcd-0bd4be86846a.png">

But, if we already on step 3 and scroll up then step 1 is selected.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/20265336/194537771-be71be43-8946-4c0c-a569-852596470889.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.36.1-rc.28

**Comment by mikerodonnell89** [comment]
The scrolling logic relies on knowing the viewport height, so the scrolling feature was really only intended for fullscreen wizards where the only elements that occupy vertical space on the screen are the shellbar, wizard nav, wizard content, and wizard footer. This wasn't documented clearly. Please follow #8823 to keep track of this issue
