### ISSUE TITLE
Wizard Generator: Required allows to press Review even if no value is selected

### ISSUE THREAD

**Issue by ninasim** [SAP/fundamental-ngx#8808]
Is this a bug, enhancement, or feature request?
bug

Briefly describe your proposal.
If I set a select control required and do not select an item, I can still navigate to the review.
![image](https://user-images.githubusercontent.com/58508122/194641992-55ebf696-114c-4a84-b9d4-acff22db63de.png)

dxp/template-ui/issues/378

**Comment by mikerodonnell89** [comment]
When creating the form item, are you using `Validators.required`?

```
formItems: [
    {
        name: 'discount',
        message: 'Make a choice',
        type: 'list',
        choices: ['Choice 1', 'Choice 2'],
        validators: [Validators.required]
    }
]
```

It would be helpful to see a snippet of your typescript in this instance

**Comment by ninasim** [comment]
As pers your suggestion, we changed to use select and validators: [Validators.required] it solves the issue

**Comment by littleamigo** [comment]
Thanks, Mike!
