### ISSUE TITLE
(docs) v0.35.x documentation pages are missing

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#8821]
#### Is this a bug, enhancement, or feature request?
bug/feature request

#### Briefly describe your proposal.
The documentation pages have links to older versions except for v0.35.x:
![image](https://user-images.githubusercontent.com/7091280/194818413-e60ae683-212b-4c20-ae70-3c6359f5725b.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current version, v0.35.x

#### If this is a bug, please provide steps for reproducing it.

1. Open https://sap.github.io/fundamental-ngx/#/core/home
2. Click on the version dropdown to open it
3. Find v0.35.x missing

**Comment by platon-rov** [comment]
fixed with https://github.com/SAP/fundamental-ngx/commit/76f39441e4601991405769bc656434eb8878efc8, link will be available in the dropdown menu in the next stable release.
