### ISSUE TITLE
Year Range doesn't change on clicking next year button

### ISSUE THREAD

**Issue by aamirshah01** [SAP/fundamental-ngx#8835]
BUG

Year range doesn't change on clicking next button in datetime-picker control.

Angular version - 13.3.11
Fundamental ngx core and platform - 0.35.4

Steps to reproduce -

Open any datetime-picker control and click on the year range button and then click on next or prev buttons, the year range label values remain same.

GIF: 
![year](https://user-images.githubusercontent.com/59820279/195507070-d67bf528-d794-46f4-935e-54712b2a46de.gif)

**Comment by aamirshah01** [comment]
![year](https://user-images.githubusercontent.com/59820279/195507425-b99b6f97-2673-40ad-b0df-256f400a04d0.gif)

**Comment by aamirshah01** [comment]
![year-range](https://user-images.githubusercontent.com/59820279/195507737-0eb2ffb9-dfdd-412f-9bbf-c8c5ac591d37.gif)
Full Issue

**Comment by aamirshah01** [comment]
@shrvr  : which version will this be available?

**Comment by g-cheishvili** [comment]
> @shrvr : which version will this be available?

Currently, it is on the latest RCs, starting from [v0.36.1-rc.46](https://github.com/SAP/fundamental-ngx/releases/tag/v0.36.1-rc.46), but we plan to release hotfix 0.36.1, just not today
