### ISSUE TITLE
List does not update correctly using an observable as datasource

### ISSUE THREAD

**Issue by burise** [SAP/fundamental-ngx#8847]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When dynamically updating a list using the `dataSource` property (which points to an observable), the CSS of the list items is not updating correctly. For example, the "unRead" property is not taken into account, i.e. the title of the list item is not bolded. Also, some custom CSS that we added is just ignored. Only after clicking on any list item, the CSS will be correct again.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Fundamental 0.36.1-rc.28
Angular 14.2.5

#### If this is a bug, please provide steps for reproducing it.
Add a list that uses the `dataSource` property to load items from an observable. Add some properties like `unRead` or custom CSS to the list items. Add a new item through the observable. Note that the list updated correctly (i.e. the new item is shown), but the CSS is not correct. 

For example, this is what would be expected in our case:
<img width="1709" alt="ui_correct" src="https://user-images.githubusercontent.com/38716799/196023194-bd80e6ad-d1ae-483e-ba7e-73a232c83d0c.PNG">

This is what actually shows:
<img width="1718" alt="ui_wrong" src="https://user-images.githubusercontent.com/38716799/196023131-4e415e8e-16f3-4e91-8c7e-4ae61cac0826.PNG">

The table renders the CSS correctly only after clicking on any list item.

#### Please provide relevant source code if applicable.
Add a list and list items with the following definition (note that `itemSource` is an observable):
```
              <fdp-list
                [dataSource]="itemSource| async"
                [navigationIndicator]="true"
                [hasByLine]="true"
              >
                <fdp-standard-list-item
                  *fdpItemDef="let item"
                  [title]="item.subject"
                  [navigationIndicator]="item.navigationIndicator"
                  [link]="item.link"
                  [unRead]="true"
                  avatarSrc="https://placeimg.com/400/400/nature"
                  [description]="'Sabine Mayer &nbsp;&#183;'"
                  [secondary]="item.timestamp"
                  class="listItem"
                >
```

**Comment by ivzhelev** [comment]
@N1XUS after applying the latest RC, the reported issue actually still persists: 

```
              <fdp-list contentDensity="compact" hasByLine="true">
                <fdp-standard-list-item
                  *ngFor="let item of itemSource | async"
                  [secondary]="item.timestamp.toString()"
                  [title]="item.subject"
                >
                </fdp-standard-list-item>
              </fdp-list>
```
(note that `itemSource` is an `observable`)

The `fdp-list` is **not correctly rendered on initial loading**:

![image](https://user-images.githubusercontent.com/8601332/203884586-d3471dec-d846-4919-85df-b54bc5414c36.png)

After some activity (mouse click, keyboard button press, mouse scroll etc.) the fdp-list is rendered **correctly**:

![image](https://user-images.githubusercontent.com/8601332/203884955-0968adc3-37ee-40f9-8092-c089c01d1d4e.png)

Can you please advice how we could proceed, thanks in advance.
