### ISSUE TITLE
Error on compiling while adding the module in app.module.ts

### ISSUE THREAD

**Issue by gks0089** [SAP/fundamental-ngx#8868]
Once I added the module in the "Imports" portion and run with ng serve without adding any control yet, it already prompt me the error.

![image](https://user-images.githubusercontent.com/64023279/196592376-833998c8-56c2-4f8a-b89c-8d94900e5512.png)

**Comment by mikerodonnell89** [comment]
Hi @gks0089, what version of NGX is this? Can you try deleting your node_modules in your application and running `yarn install` before serving?

**Comment by gks0089** [comment]
Hi @mikerodonnell89 , this is the latest angular version 14

**Comment by gks0089** [comment]
So no one know what is going on?

**Comment by N1XUS** [comment]
@gks0089 Hello. And which version of fundamental-ngx are you using? From what I see, angular lib installed scoped version under fundamental-ngx, and version from node_modules/@angular is not compatible with node_modules/@fundamental-ngx/core/node_modules/@angular.

If you could provide your package.json contents, that would be helpful.

Thank you.
