### ISSUE TITLE
Object Status corners are more rounded than UI5 implementation

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8872]
The Object Status corners are more rounded than the [UI5 Implementation](https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.ObjectStatus/sample/sap.m.sample.ObjectStatus)

**Comment by droshev** [comment]
fixed with https://github.com/SAP/fundamental-styles/pull/3942
