### ISSUE TITLE
Card Footer Documentation

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#8890]
#### Is this a bug, enhancement, or feature request?
Bug or Documentation request

#### Briefly describe your proposal.
Comparing the card footer from v0.34.2 with v0.36.0, the docs changed from recommending `fd-toolbar` to `fd-card-footer` yielding the visual difference:

[v0.34.2](https://624793d2f1d02d000925c339--fundamental-ngx.netlify.app/#/core/card#footer)
![image](https://user-images.githubusercontent.com/7091280/197486128-cc8c124e-0cce-4b9a-849c-dc01d3f25a07.png)

[v0.36.0](https://sap.github.io/fundamental-ngx/#/core/card#footer)
![image](https://user-images.githubusercontent.com/7091280/197486193-b956f9f2-42f2-4f18-9400-25c16607cca8.png)

The Fiori guidelines still recommend the look of v0.34.2, so I'd appreciate if the current docs would also contain an example for that instead of having to go back to find out how to achieve that footer. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current

#### If this is a bug, please provide steps for reproducing it.
Does not apply.

#### Please provide relevant source code if applicable.
Your docs' examples as linked above.

#### Is there anything else we should know?
Does not apply.

**Comment by droshev** [comment]
@JenniferStamm thank you for reporting the request. We have updated the styles for the cards and you can see the example https://fundamental-ngx.netlify.app/#/core/card in Quartz theme
