### ISSUE TITLE
fdp-table - implementation of expand and collapse all feature

### ISSUE THREAD

**Issue by skaquib123** [SAP/fundamental-ngx#8901]
#### Is this a bug, enhancement, or feature request?

feature request for platform treetable.

#### Briefly describe your proposal.

Need to implement expand and collapse all feature in table where we can expand and collapse all the rows of the table. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

current version

#### Is there anything else we should know?
Had discussion with cathy, Georg

**Comment by gks0089** [comment]
hi , may i know what angular version you are using? because I'm using angular version 14 but I can't even run when I add the modules in the app.modules
