### ISSUE TITLE
Adopt feature #3959 from Fundamental-styles

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#8907]
All components that have scrollable area should adopt the Fiori Scrollbar

**Comment by droshev** [comment]
@shrvr do you think you can validate whether the styles scrollbar is properly applied for all the themes?
thanks

**Comment by shrvr** [comment]
> @shrvr do you think you can validate whether the styles scrollbar is properly applied for all the themes? thanks

Yes of course, can do that.:slightly_smiling_face: 
@droshev
