### ISSUE TITLE
Add navigation mode for tabs

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#892]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
Currently, our tabs cannot be used with a router-outlet. In the documentation we are currently using the css classes from fundamental-ui to accomplish this pattern, not the fd-ngx component.

We should have a special mode for the tabs to be used inside a `<nav>` element with `<a>` tags. The solution should look something like the following.

```html
<nav fd-tab-nav>
    <a fd-tab-link
         [routerLink]="link.path"
         routerLinkActive #rla="routerLinkActive"
         [active]="rla.isActive">
             Link
    </a>
</nav>
```

Note that the routerLink, routerLinkActive and associated stuff is not to be handled by fd-ngx components. The only thing we should handle is an `[active]` input which controls the applied class.

**Comment by JKMarkowski** [comment]
just FYI, I'm on it
