### ISSUE TITLE
Dynamic Page Header on focus using Tab does not show dotted box but dotted under line.

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8942]
Dynamic Page Header on focus using Tab does not show dotted box but dotted under line.
Ex: Standard behaviour from NGX https://sap.github.io/fundamental-ngx/#/core/dynamic-page

**Comment by droshev** [comment]
@sameesheikh25  do you mean that:
<img width="237" alt="Screenshot 2022-11-09 at 11 47 16 AM" src="https://user-images.githubusercontent.com/4380815/200890386-aa199c19-0f8b-471d-821f-d44b1ec41af0.png">
