### ISSUE TITLE
Tab/Reading Order not consistent in safari browser

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8943]
Is this a bug, enhancement, or feature request?
-> Bug

Briefly describe your proposal.
-> Tab/Reading Order –For Safari including Carousel – different behaviour for different browser(Tab sequence is not in order)

**Comment by shrvr** [comment]
Can I know in which components other than Carousel you found this issue? @sameesheikh25

**Comment by platon-rov** [comment]
Agree with @shrvr, could you please provide images/videos of broken components.

Also, please notice, that in Safari browser setting about TAB button behavior is different, and you have to enable it to have the same behavior as in other browsers.

![CleanShot 2022-12-16 at 19 53 07@2x](https://user-images.githubusercontent.com/20265336/208168892-1b805da7-9810-4d10-a603-f57503dd0014.png)

**Comment by sameesheikh25** [comment]
Behaviour in safari browser

https://user-images.githubusercontent.com/102856000/208738547-cb20f847-b45d-4b13-a4ef-88385f2fd0b7.mp4

Behaviour in chrome browser

https://user-images.githubusercontent.com/102856000/208739751-8fac1dff-ce72-4a83-852a-dabdb07177b3.mp4

**Comment by mikerodonnell89** [comment]
@sameesheikh25 Did you try @platon-rov 's suggestion above? I am seeing the same behavior across browsers.

**Comment by sameesheikh25** [comment]
This works fine with your given suggestion. So I will be closing this issue.
