### ISSUE TITLE
Duplicate div Ids

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#8948]
Is this a bug, enhancement, or feature request?
-> Bug

Briefly describe your proposal.
-> Duplicate divIds Example: fd-dynamic-page-header-id-6
<div id="fd-dynamic-page-header-id-6" role="region" ngcontent-imf-c258=""><div class="fd-dynamic-pagecollapsible-header-container"><div id="fd-dynamic-page-header-id-6" aria-hidden="false" class="fd-dynamic-pagecollapsible-header" role="region"><div class="fd-breadcrumb" _ngcontent-imf-c258=""><div class="fd-overflow-layout" showmoreposition="left"><div style="display: none;" class="fd-overflow-layoutmore ng-star-inserted"><div class="ng-star-inserted"></div></div><div class="fd-overflow-layoutitems-container"><div class="fd-overflow-layoutitems-wrapper"><div class="fd-overflow-layoutitems"><div class="fd-overflow-layoutitem ng-star-inserted fd-overflow-layoutitem-first" fdoverflowlayoutitemcontainer=""><div class="ng-star-inserted" tabindex="-1" fdoverflowlayoutitem=""><div class="fd-breadcrumbitem" _ngcontent-imf-c258=""><a href="/store" class="fd-link" routerlink="/store" fd-breadcrumb-link="" _ngcontent-imf-c258=""><span class="fd-linkcontent">Store</span></a></div></div></div><div class="fd-overflow-layoutitem ng-star-inserted fd-overflow-layoutitemlast" fdoverflowlayoutitemcontainer=""><div class="ng-star-inserted" tabindex="-1" fdoverflowlayoutitem=""><div class="fd-breadcrumbitem" _ngcontent-imf-c258=""><span _ngcontent-imf-c258="">More Information</span></div></div></div></div></div></div></div></div><div class="toolbar-align" fdtype="transparent" _ngcontent-imf-c258=""><div class="fd-toolbar fd-toolbartransparent fd-toolbarclear" tabindex="-1"><div aria-live="polite" aria-busy="false" tabindex="-1" role="presentation" class="indicator fd-busy-indicatorcontainer fd-busy-indicatorcontainerinline" size="m" _ngcontent-imf-c258=""></div><button type="button" class="fd-button fd-buttonemphasized btn fd-button-compact ng-star-inserted" fd-button="" _ngcontent-imf-c258="">Create from Template</button><div id="fd-popover-466" class="fd-popover-custom" placement="bottom-start" _ngcontent-imf-c258=""><div class="fd-popover_control ng-star-inserted" cdkoverlayorigin=""><div _ngcontent-imf-c258=""><div class="segment-button fd-segm

Expected behavior:
Documents that use markup languages must be well-formed. When documents are not well-formed user agents and/or assistive technology may not correctly parse and render the content to users. Many major user-agents are able to cope well with "bad" markup, however, to be consistent across all platforms and browsers well-formed markup must be used. This is especially important for assistive technology which may or may not be programmed to perform the same level of "coping" that can be found in browsers (which are created by multinational corporations) or assistive technology brands that cost several hundred dollars or more.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
-> v0.35.4

**Comment by shrvr** [comment]
Can I know what you were pointing out from the **Store** link? it is not valid link now @sameesheikh25. Moreover If you can elaborate more, it would help me to understand better. Thank you.
