### ISSUE TITLE
Switch the state of segmented button

### ISSUE THREAD

**Issue by blueskymyw** [SAP/fundamental-ngx#8954]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Can you add some functionality to switch the state of the segmented button except clicking/touching the button?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 14.1.3
Fundamental Library: 0.36.1

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/117795601/200736971-f045da0d-5a78-4bc9-b65d-34b82ab0ad3a.png)

**Comment by N1XUS** [comment]
@blueskymyw thank you for your request. I'm assuming you are using segmented button with ngModel. You can change the state of the button by simply changing the value of the model passed to segmented button. Here's working exampe: https://stackblitz.com/edit/angular-den3jb?file=src%2Fapp%2Fsegmented-button-default-example.component.ts,src%2Fapp%2Fsegmented-button-default-example.component.html

**Comment by blueskymyw** [comment]
@N1XUS Thank you for your answer. Do you mean to use formControlName="basic" ?

**Comment by N1XUS** [comment]
@blueskymyw in the .ts file I've added an example, how to change the state of the segmented button: https://stackblitz.com/edit/angular-den3jb?file=src%2Fapp%2Fsegmented-button-default-example.component.ts,src%2Fapp%2Fsegmented-button-default-example.component.html
so after 2 seconds after the component initialization the value of the segmented button is programatically changed, and then different button is highlighted

**Comment by blueskymyw** [comment]
Thank you for your help. I am using ngModel. Do you mind adding one example to show this usage? 
In addition, I need to closed the right panel and unselected all the buttons. The right panel and the segmented buttons are not in one component.

**Comment by N1XUS** [comment]
@blueskymyw in the example I provided there's 2 options: for ngModel and formGroup. I didn't catch the part with the right panel. What do you mean by that?

**Comment by blueskymyw** [comment]
Can you add some functionality to switch the state of the segmented button controlled by another component? It will be easy to switch the state of the segmented button(selected or unselected).

**Comment by N1XUS** [comment]
@blueskymyw Could you please provide a stackblitz example with the component structure you are using and add some comment there where segmented button state should be changed. It would help a lot to understand your issue.

**Comment by N1XUS** [comment]
@blueskymyw if you want to reset segmented button (so that no buttons are checked), you can just set empty string as a model: https://stackblitz.com/edit/angular-den3jb-8axcnu?file=src%2Fapp%2Fsegmented-button-default-example.component.ts,src%2Fapp%2Fsegmented-button-default-example.component.html check the deselectAll method

**Comment by blueskymyw** [comment]
Thank you for your help

**Comment by N1XUS** [comment]
I'm assuming I can close the issue now. @blueskymyw if you have any other questions, we will gladly help you
