### ISSUE TITLE
inline help focus issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8965]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

go to Form Generator [page](https://fundamental-ngx.netlify.app/#/platform/form-generator#with-promise)
focus on the first field and start tabbing over the fields
The inline help will show the content, but won't close once the focus is out of the icon

<img width="769" alt="Screenshot 2022-11-16 at 10 15 38 AM" src="https://user-images.githubusercontent.com/4380815/202219540-9f0e4078-8491-4aba-9da0-234b966beb13.png">

**Comment by littleamigo** [comment]
just tried out and the fix works great - thanks!
