### ISSUE TITLE
Inverted Object Status - issue with font size, overall size, colors and shadow

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-ngx#8968]
The icon (SAP-Icons Font) and the text (72 Font) size should be 12px. According to the [Visual Core](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698914826), the shadow on the text should be: sapContent_ContrastTextShadow. Please check all the characteristics in the specs to ensure consistency.

**Comment by droshev** [comment]
@obc514 thanks for opening the issue.

The update will come once the [issue](https://github.com/SAP/fundamental-styles/issues/4027) is implemented in styles

**Comment by platon-rov** [comment]
Fixed.
