### ISSUE TITLE
how to customize title for clear button in fdp-search-field compontnt?

### ISSUE THREAD

**Issue by XYF001** [SAP/fundamental-ngx#8980]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When using fdp-search-field component, the title of the clear button is defaulted to 'Clear'.
How can i customize the title for clear button  in different fdp-search-field component?
 e.g.I want to set one fdp-search-field's clear button's title to be 'Clear user', another fdp-search-field's clear button's title to be 'Clear status'. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/platform": "0.33.7",
"@angular/cli": "13.3.8"

#### If this is a bug, please provide steps for reproducing it.
focus on the clear button of the fdp-search-field component, the title will be shown as 'Clear', can not customize the title.

#### Please provide relevant source code if applicable.
```
<fdp-search-field
    placeholder="Search"
    [suggestions]="suggestions"
    fdCompact
    ariaLabel="Search something"
    (searchSubmit)="onCompactSearchSubmit($event)"
    (inputChange)="onCompactInputChange($event)"
></fdp-search-field>
```

**Comment by XYF001** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/24812746/203011862-ec81c4fc-4d91-4039-9a75-d5065dc16e69.png">

**Comment by droshev** [comment]
Hi @XYF001 ,

The localization of that label is done in [here](https://github.com/SAP/fundamental-ngx/blob/e616f647ef5dc29652370fa14f149187b0630758/libs/i18n/src/lib/languages/english.ts#L305). In case you want to override the default ones I would recommend you following [this](https://fundamental-ngx.netlify.app/#/core/i18n#language-customization)
