### ISSUE TITLE
Angular 11 installation of @fundamental-ngx/core

### ISSUE THREAD

**Issue by zulfi316** [SAP/fundamental-ngx#8981]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
It is not possible to use fundamental-ngx/core with Angular 11.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 11
Fundamental-NGX/Core 0.32.15

#### If this is a bug, please provide steps for reproducing it.
I cannot get ng serve to work once I add the fundamental-ngx/core module into my package.json

Here is a stackblitz of the problem -
https://stackblitz.com/edit/angular-1r9kyk?file=package.json

The specific error that I get when I try this locally is ->
An unhandled exception occurred: The target entry-point "@fundamental-ngx/core" has missing dependencies:
 - @angular/localize/init

What can I do to mitigate this?

**Comment by droshev** [comment]
hi @zulfi316 ,

thanks for raising the question. I tried creating a project from scratch locally and it worked. You can see the example [here](https://github.com/droshev/super-doodle)

On the other hand, Angular 11 is not supported. According to Angular official [site](https://angular.io/guide/releases#actively-supported-versions) even Angular 12 is not supported. I would encourage you to upgrade to angular version that has actively support such as Angular 14 or 15.
