### ISSUE TITLE
multi input vs. multi combo

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8985]
#### Is this a bug, enhancement, or feature request?
bug and enhancement (maybe even a breaking change)

#### Briefly describe your proposal.
The current implementations of `core` `multi-input` and `platform` `multi-input` and `multi-combo` do not follow the design guidelines at 100%. The goal of this ticket is to:
- [x] introduce `multi-combo` in `core` package
- [ ] review the existing implementations and apply the proper styling and behaviour, especially, the more items and reviewing the tokens

Design Guidelines
- https://experience.sap.com/fiori-design-web/multi-combobox/
- https://experience.sap.com/fiori-design-web/multiinput/
- https://experience.sap.com/fiori-design-web/multiinput/#reviewing-tokens

additional items to be considered transferred from #7611 

- [x] Multi-input - revisit the keyboard - TBD
- [x] Multi-input: [this PR](https://github.com/SAP/fundamental-ngx/pull/7588) allows the user to tab to the expand key to open the dropdown of selectable options. However the user then must shift+tab back to the input part of the multi-input, then press tab, to focus the first item in the list. Instead we should have an additional tab keypress, or down arrow press, focus the first item in the dropdown
- [x] Multi-input: both the checkbox and the entire list item receive tab focus
- [x] Multi-input (core): adding new tokens example. Type a new token and submit it with the enter key. The token is not added to the tokenizer and when opening the dropdown, is not visible in the list. However you will notice the token has been added to the total count (the "View All" count as increased) and the new item has been added next to the "Selected:" text. - was already fixed 
![image](https://user-images.githubusercontent.com/6586561/219009237-665f3d90-eeb6-456f-ace7-f7b64f007f61.png)

**Comment by droshev** [comment]
Maybe we can combine this task with bringing all the platform features into core and deprecating the platform ones?

**Comment by N1XUS** [comment]
Additionally. in platform multi-input component it's impossible to unset the selected item by clicking on the checkbox, or on the item itself
