### ISSUE TITLE
Fundamentals Wizard Generator: Summary Page, check in tests parameter values

### ISSUE THREAD

**Issue by ninasim** [SAP/fundamental-ngx#8990]
#### Is this a bug, enhancement, or feature request?
Not sure
#### Briefly describe your proposal.
Hi, collegues,
In our tests for the wizard we would like to put a check if all the parameter values are set correct after automatic execution.
So we would like to be able to check that for parameter with label "Name:" we have a value "x".

![image](https://user-images.githubusercontent.com/58508122/203577497-f79647a7-3b4d-47bf-81f4-3157d8827195.png)
What would be your proposal for testing this summary page?
Thanks , 
Nina

**Comment by N1XUS** [comment]
Hello @ninasim. Wizard generator provides ability to change default summary template to a custom one: https://fundamental-ngx.netlify.app/#/platform/wizard-generator#customization

With custom template you can define whatever rendering logic you like

**Comment by InnaAtanasova** [comment]
@ninasim please reopen the issue if the solution provided from @N1XUS doesn't work. Thank you!
