### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8997]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.

Enable Angular 15 in the library. 

https://angular.io/guide/update-to-version-15

https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8

**Comment by N1XUS** [comment]
Closed with https://github.com/SAP/fundamental-ngx/pull/9078
