### ISSUE TITLE
inline help - text goes beyond the visible area

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#9]
On the Fundamental UI website, inline help hovers above their menus but in our app, it goes behind the menus.  Check z-index etc.  On the Fundamental website the text/inline help does not wrap if the help goes off screen/out of the browser window so I'm not sure there's anything we can do there

<img width="352" alt="screen shot 2018-05-31 at 2 43 04 pm" src="https://user-images.githubusercontent.com/2471874/40807226-f463b4b4-64e0-11e8-98a4-31bf2171aa7a.png">

**Comment by MattL75** [comment]
Merging this one with #410
