### ISSUE TITLE
fd-action-sheet does not allow to use custom icons

### ISSUE THREAD

**Issue by tomsawdayee** [SAP/fundamental-ngx#9011]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.

I'm trying to use an external icon library, and while most of the components allow me to use custom icons, I found that the Action-sheet control does not - since theres not control over the button that is rendered within **fd-action-sheet-item**
I would like to be able to gain control over the button that is rendered so I can replace the icon with a custom one.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Current version - 0.36.2

**Comment by platon-rov** [comment]
@tomsawdayee you can update to 0.38.2 or higher and use custom icons like so

```html
<fd-action-sheet-item label="label">
  <my-custom-icon></my-custom-icon>
</fd-action-sheet-item>
```

**Comment by tomsawdayee** [comment]
@platon-rov Great news! That's exactly what I was looking for. Thanks a bunch!
