### ISSUE TITLE
datetime picker has junk number in the pop up

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#9015]
This is a bug

In the popup of date time picker, there is extra column with date from 44 - 48

Angular 13

create any date type term and click the field to select date or time, you will find an extra column with date from 44 - 48

The issue at <fdp-date-picker> component.

Attaching the screenshot for your reference.
<img width="1369" alt="date picker issue" src="https://user-images.githubusercontent.com/110370099/204750604-8aa5dc5d-fe7b-4b85-94e0-e3db484936bb.png">

**Comment by mikerodonnell89** [comment]
Hi @sahanaN123 that is the number of the week of the year. It can be disabled with the <code>[showWeekNumbers]</code> input
