### ISSUE TITLE
The aria-expanded attribute is not allowed on this DIV

### ISSUE THREAD

**Issue by Ashah2013** [SAP/fundamental-ngx#9027]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
This is regarding one of the accessibility bug. The aria-expanded attribute is not allowed on this DIV, according to the accessibility team. This is something framework is adding by its own.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular - 13.3.7
fundamental ngx - 0.36.0

#### If this is a bug, please provide steps for reproducing it.
![image](https://user-images.githubusercontent.com/63425649/205494337-41453e47-98cd-412a-944f-6a11486f1afa.png)
1. https://sap.github.io/fundamental-ngx/#/core/tabs
2. Inspect any Select modes on the page and observe "aria-expanded" property on the div.

#### Please provide relevant source code if applicable.
Source code: 
	`<fd-tab title="{{ 'PACKAGE.description.TEXT' | translate }}" class="tab">
				<ap-cockpit-description
					[description]="package.longDescription"
					[medias]="package.medias"
					[packageSource]="package.packageSource"
				></ap-cockpit-description>
			</fd-tab>`
Generated code:
![image](https://user-images.githubusercontent.com/63425649/205494556-2b2ec76e-1b8a-4363-9bca-72fd6138d912.png)

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/63425649/205160463-d7932724-2231-4fed-b0ee-20e106bd97e6.png)
![image](https://user-images.githubusercontent.com/63425649/205160503-13fc49c0-8dd4-4a1e-b555-3df784740953.png)
![image](https://user-images.githubusercontent.com/63425649/205160536-c20a1149-4636-4321-b4dc-1adc96b6440c.png)

**Comment by g-cheishvili** [comment]
This is not reproducible, please try again with the latest release
