### ISSUE TITLE
Multi Input is not able to handle long names

### ISSUE THREAD

**Issue by sameesheikh25** [SAP/fundamental-ngx#9047]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.

In a multi input control if we provide long name inside dropdownvalues, then the width of the value keeps increasing and it keeps expanding as we keep increasing the name length.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

v 0.35.4

#### If this is a bug, please provide steps for reproducing it.

I have provided the code snippet please copy paste the same and run it in stackblitz.

<fd-multi-input
  inputId="multiInput"
  [dropdownValues]="[
    'Appleefdssdfdfsdfsdfsdfsdfsdfsdfsdfsdfsdxfsdfddfsdfdsfsdfdsfsdfsdfsdfsd',
  ]"
  placeholder="Search here..."
  [(ngModel)]="selected"
></fd-multi-input>

If you increase the length of dropdown values then the width of multi input control will increase accordingly.

#### Is there anything else we should know?

Please provide some option to set some limit in those dropdown values.

**Comment by sameesheikh25** [comment]
<img width="377" alt="long name" src="https://user-images.githubusercontent.com/102856000/208608863-038dd6cc-be3a-4d43-a885-6130b098f358.png">

**Comment by N1XUS** [comment]
There's an input property which allows developers to set max width of the dropdown container. Please check this example: https://stackblitz.com/edit/angular-7fkaak?file=src%2Fapp%2Fmulti-input-example.component.html

**Comment by sameesheikh25** [comment]
can you just provide that property her in comments with max - width?

**Comment by sameesheikh25** [comment]
is there some way we could show the tooltip when hover on multi input values?

**Comment by N1XUS** [comment]
@sameesheikh25 [bodyMaxWidth]="200" will result in dropdown max width 200 pixels

**Comment by N1XUS** [comment]
As to the tooltip, you can try to use custom template where you can add tooltip: https://fundamental-ngx.netlify.app/#/core/multi-input#custom-item
