### ISSUE TITLE
[Accessibility] [Sourcing] Input with autocomplete: Not able to reach suggestion list using keyboard

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9050]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
After typing a letter , once the suggestion list opens up , user is not able to reach the list using keyboard

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13.x.x.
"@fundamental-ngx/core": "0.35.4",
    "@fundamental-ngx/platform": "0.35.4",

#### If this is a bug, please provide steps for reproducing it.
1) Type some letter in the input box
2) suggestion list shows up
3) there is no way to select any option from the suggestion list or reach the list using keyboard

#### Please provide relevant source code if applicable.
This is replicable on https://sap.github.io/fundamental-ngx/#/platform/input
<img width="1286" alt="Screenshot 2022-12-07 at 7 19 48 AM" src="https://user-images.githubusercontent.com/88182358/206068220-7df33806-ccb5-43c4-bd3f-7d205f1a120a.png">

```
<div>
    <fd-popover class="fd-popover" [triggers]="[]" [isOpen]="open" #typeahead>
        <fd-popover-control>
            <fdp-input
                type="text"
                id="form-input-10"
                name="autoCompletTextInput"
                placeholder="Enter the sport name"
                [(ngModel)]="inputText"
                (input)="onSearchChange()"
            >
            </fdp-input>
        </fd-popover-control>
        <fd-popover-body>
            <nav class="fd-menu">
                <ul fd-menu-list class="fd-menu__list">
                    <li
                        fd-menu-list-item
                        class="fd-menu__item"
                        *ngFor="let option of options"
                        (click)="onItemClick(option)"
                    >
                        <span class="fd-menu__link">
                            {{ option }}
                        </span>
                    </li>
                </ul>
            </nav>
        </fd-popover-body>
    </fd-popover>
</div>
```

#### Is there anything else we should know?
User should be able to reach the suggestion list using up and down arrow keys and enter key should select the suggestion from list and put it in input box.

**Comment by mikerodonnell89** [comment]
@I543348 you could add a keydown event handler to the input that intercepts arrow down/arrow up, and use that to focus the first list item.  However seems to me like this design breaks the Platform mold of delivering complex components with fewer lines of code, and follows more the Core line of thinking.

@droshev I think I would like to see an input like `[autocomplete]` on the `fdp-input` that accepts some datasource as the possible options, same as combobox etc. And internally provides popover handling, keyboard support etc. Thoughts?

**Comment by droshev** [comment]
This is just an example how you can link input with other components. This is a custom example and if you want to have such  pattern then you would need to handle the keyboard support as Mike suggested
