### ISSUE TITLE
Inconsistency between popover-list & menu

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#9058]
Bug reported by Dost Arora:

- A11Y:
In Menu, the Accessibility dotted line appears when hovering over the element. In popover-list it appears after pressing tab.
Is there any way to enable/disable this for Menu OR Popover ?
- CSS:
In popover, the corner of first & last element bleeds out from the edges. This does not happen in Menu.
`.fd-menu__list` - has additional box-shadow -box-shadow: var(--sapContent_Shadow1, 0 0 0 .0625rem rgba(0, 0, 0, .42), 0 .125rem .5rem 0 rgba(0, 0, 0, .3)) apart from the popover shadow which makes the menu border looks darker.
`.fd-menu__link` - has unbalanced left & right padding - padding: .75rem 1rem .75rem .75rem. Items are not centered.
`.fd-menu__title` - has font-size var(--sapFontSize, .875rem), whereas .fd-list__title has font-size var(--sapFontLargeSize, 1rem)

Demo: https://stackblitz.com/edit/tpp-issue-2-list-menu-da25?file=src/app/menu-example.component.html

**Comment by mikerodonnell89** [comment]
@dostarora97 Have you been able to find workarounds for the remaining points of this issue?

**Comment by mikerodonnell89** [comment]
Closing, please reopen if there are still any relevant issues
