### ISSUE TITLE
ShellBar examples should be updated / Search functionality

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#9066]
#### Is this a bug, enhancement, or feature request?
Bug, Inconsistency with the design

#### Briefly describe your proposal.
Currently, the way the building blocks of the ShellBar are positioned doesn't match the design guidelines. The examples should be updated.

**Search Field**
the functionality should be updated according to the specs:
![Screenshot 2022-12-12 at 3 35 28 PM](https://user-images.githubusercontent.com/39598672/207149042-29398bc3-5ab2-4886-a148-73e9fcd402bd.png)

**Comment by droshev** [comment]
has been addressed by @N1XUS
