### ISSUE TITLE
DIV has an id attribute of 'fd-dynamic-page-header-id-6', which is not unique in the same DOM

### ISSUE THREAD

**Issue by nagbhushanr** [SAP/fundamental-ngx#9085]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

This is regarding one of the accessibility bug. This DIV has an id attribute of 'fd-dynamic-page-header-id-6', which is not unique in the same DOM.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

angular - 13.3.7
fundamental ngx - 0.36.0

#### If this is a bug, please provide steps for reproducing it.

https://sap.github.io/fundamental-ngx/fundamental-ngx#/core/dynamic-page

#### Please provide relevant source code if applicable.

<div id="**fd-dynamic-page-header-id-6**" role="region" _ngcontent-imf-c258=""><div class="fd-dynamic-page__collapsible-header-container"><div id="**fd-dynamic-page-header-id-6**" aria-hidden="false" class="fd-dynamic-page__collapsible-header" role="region"><div class="fd-breadcrumb" _ngcontent-imf-c258=""><div class="fd-overflow-layout" showmoreposition="left"><div style="display: none;" class="fd-overflow-layout__more ng-star-inserted"><div class="ng-star-inserted"></div></div><div class="fd-overflow-layout__items-container"><div class="fd-overflow-layout__items-wrapper"><div class="fd-overflow-layout__items"><div class="fd-overflow-layout__item ng-star-inserted fd-overflow-layout__item--first" fdoverflowlayoutitemcontainer=""><div class="ng-star-inserted" tabindex="-1" fdoverflowlayoutitem=""><div class="fd-breadcrumb__item" _ngcontent-imf-c258=""><a href="/store" class="fd-link" routerlink="/store" fd-breadcrumb-link="" _ngcontent-imf-c258=""><span class="fd-link__content">Store</span></a></div></div></div><div class="fd-overflow-layout__item ng-star-inserted fd-overflow-layout__item--last" fdoverflowlayoutitemcontainer=""><div class="ng-star-inserted" tabindex="-1" fdoverflowlayoutitem=""><div class="fd-breadcrumb__item" _ngcontent-imf-c258=""><span _ngcontent-imf-c258="">More Information</span></div></div></div></div></div></div></div></div>

#### Is there anything else we should know?

**Expected behavior**
Documents that use markup languages must be well-formed. When documents are not well-formed user agents and/or assistive technology may not correctly parse and render the content to users. Many major user-agents are able to cope well with "bad" markup, however, to be consistent across all platforms and browsers well-formed markup must be used. This is especially important for assistive technology which may or may not be programmed to perform the same level of "coping" that can be found in browsers (which are created by multinational corporations) or assistive technology brands that cost several hundred dollars or more.

![image](https://user-images.githubusercontent.com/119582923/207223813-f182a5e9-21e3-4fa4-8296-b8418adc1486.png)

**Comment by N1XUS** [comment]
Hello @nagbhushanr. Thank you for submitting this ticket.
Unfortunately, I wasn't able to reproduce an issue you've described. Maybe you could provide code example for it?

**Comment by nagbhushanr** [comment]
![image](https://user-images.githubusercontent.com/119582923/208340498-e619f1a0-42de-48ca-b8a0-679fea9b5ae9.png)
Here is the image of the above issue. if you look at the highlighted parts.... the id is similar for both.
Inorder to observe this behavior:
1. Go to fundamental ngx library web page - https://sap.github.io/fundamental-ngx/fundamental-ngx#/core/home
2. Select version 0.36.2
3. In search bar search for Dynamic Page
4. Consider any example given in the page-> click to open in full screen
5. inspect and observer fd-dynamic-page-subheader tag and you can see the above issue

**Comment by N1XUS** [comment]
@nagbhushanr thank you for the explanation.
The issue has been already fixed with v0.37, so you can update to that version or higher
