### ISSUE TITLE
Routing issue on the main documentation site (sap.github.io)

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#9089]
Navigating to https://sap.github.io/fundamental-ngx correctly takes us to the doc page but the current URL is automatically adjusted to https://sap.github.io/fundamental-ngx/fundamental-ngx#/core/home . If you then copy that URL and attempt to navigate to it in a new tab, you'll get a 404. This could be problematic if developers working together want to pass specific documentation to each other, etc. For example when someone asks a question about a component and I have a specific example I'd like to show them, I like to use this little link button:
<img width="34" alt="Screenshot 2022-12-13 at 2 26 11 PM" src="https://user-images.githubusercontent.com/2471874/207415038-e4311e8e-202c-4523-bfb2-79578480eb04.png">
But this doesn't work when passing the URL that is returned here. Only seems to be an issue on the sap.github.io site and not netlify.

**Comment by g-cheishvili** [comment]
I fixed it already
https://github.com/SAP/fundamental-ngx/pull/9097
