### ISSUE TITLE
On doc website, all code examples are incorrect

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9093]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

Go to document website (https://sap.github.io/fundamental-ngx/fundamental-ngx#/platform/home), all the code example are showing the following code.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/7035787/207719726-e3aeb304-e4cb-49a5-9c76-3514a7f750c1.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
N/A

#### If this is a bug, please provide steps for reproducing it.
N/A

#### Please provide relevant source code if applicable.

N/A

#### Is there anything else we should know?

This is an urgent issue.

**Comment by dev-kalleno** [comment]
Absolutely! I can't proceed with my project right now. Thanks for bringing the issue here.

**Comment by droshev** [comment]
@oscargong you can workaround it by going on the main page and changing to platform from the drop down. we will try to fix it

**Comment by N1XUS** [comment]
Potentially fixed with https://github.com/SAP/fundamental-ngx/pull/9097
