### ISSUE TITLE
Bug: Selected element on action bar not focused 

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-ngx#910]
Is this a bug, enhancement, or feature request?
Bug

Briefly describe your proposal.
If the element of the Action bar has been selected, the focus should be at one of those items. In the following screenshot, we cannot distinct which element was selected. 

<img width="503" alt="Screen Shot 2019-06-12 at 5 36 51 PM" src="https://user-images.githubusercontent.com/25252963/59388221-34cccc80-8d39-11e9-8329-229337c9659c.png">

**Comment by MattL75** [comment]
Please flesh this out a bit, not sure what you mean 😅

**Comment by droshev** [comment]
`menu` in this example(which is not part of the `action-bar`) has hover effect so I don't see any issue.
