### ISSUE TITLE
Opening dropdown menu via keyboard 

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-ngx#911]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Opening the dropdown menu via ALT + DownArrow.
- Combobox
- Dropdown
- Popover
- Search input
- Shell bar

**Comment by MattL75** [comment]
We don't have localization editor, nor tree.

Mega menu is deprecated and is being removed from fundamental-styles by Dorin right now

**Comment by JKMarkowski** [comment]
Right now we have Localization editor and Split Button which can be included here. Also search input is deprecated.

**Comment by fkolar** [comment]
While extending `core` select into `platform` I also noticed that keyboard navigation has some issues, we should use cdk for this one

**Comment by JKMarkowski** [comment]
We have `MenuKeyboardService`, which has similar func. as cdk/a11y. It accepts objects, that implements `DefaultMenuItem` with `focus` and `click` methods. We can use it to implement keyboard support for these components.
