### ISSUE TITLE
enhancement: instead of long chain of extended classes, move towards inject and host directives

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#9118]
#### Is this a bug, enhancement, or feature request?
feature request
#### Briefly describe your proposal.
As of angular 15 we have couple of new features we can use for fundamental-ngx.

- [ ] One of them is `inject` function, which allows us to simplify our base classes without using DI in constructors and passing injected dependencies via `super` call.

By doing that we can substantially simplify this construction:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/6586561/208856638-fa2cde97-7f9c-46a8-b7a3-cd1da1e7b8ae.png">

- [ ] Second one is to move base functionality of platform, core and fn into separate package - **CDK**. By doing that we can actually benefit from all three library functionalities, such as selectable list from fn, form controls from platform, dynamic component from core;

- [ ] Third one is the host directives. As an example, for platform multi input component we have chain of extended classes: `PlatformMultiInputComponent` -> `BaseMultiInput` -> `CollectionBaseInput` -> `BaseInput` -> `BaseComponent`. The idea is to split such extensions to separate host directives which can work in combination with each other. This will benefit us in couple of scenarios: If we move such directives into separate CDK package, our core components could potentially also start using those, thus bringing more functionality from platform to core (automatic state messages for form controls, ability to use core controls in platform form group, etc.)

**Comment by g-cheishvili** [comment]
Additional example: there are cases with Data Source elements. Currently, every component which has dataSource support, basically implements again and again, like taking input, understanding type, transforming it into DataSource, and then consuming it in components. Validating, detecting changes, and acting upon them are just a few things that are redundant, additionally, if a child component needs ds and the parent passes it down to it using inputs, the child will invoke the same process again. I believe this logic should be moved away from the components and implemented with the directive, which will handle all the common behaviors.
