### ISSUE TITLE
Bug: Multiple instances of Time picker

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-ngx#913]
#### Is this a bug, enhancement, or feature request?
Bug 

#### Briefly describe your proposal.
It should not be possible to activate multiple instances of Time picker at the same time.

**Comment by mikerodonnell89** [comment]
What do you mean? On our example page, opening a time picker will close any other open time picker

**Comment by SaiShan** [comment]
> What do you mean? On our example page, opening a time picker will close any other open time picker

If you click on one button and then another one without clicking anywhere else, both instances will be shown. See screenshot. 

<img width="1212" alt="Screen Shot 2019-06-20 at 8 09 34 PM" src="https://user-images.githubusercontent.com/25252963/59888824-81e31b00-9397-11e9-8780-c7b8d273eeff.png">
