### ISSUE TITLE
[Question][SmartFilterBar]How to get the field value when focus leave the fitler input

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#9143]
#### Is this a bug, enhancement, or feature request?
feature
#### Briefly describe your proposal.
Hi Experts, we have a requirement to get the values for filters when my input focus leave. I have checked the API, it has output smartFiltersChanged, but this event is only triggered after pressing the GO button. 

Is there any way to get the filter value when my input change.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular:14
Fundamental:0.36.2

**Comment by N1XUS** [comment]
Hello @truezn. Could you please clarify which input you refering to? The one for search, or the one which opens the dialog window to configure the field filter?

**Comment by N1XUS** [comment]
Hello @truezn. In next version Smart Filter Bar (0.39.0) will receive new output events:
- Added new events: `smartFiltersApplied` and `searchInputChanged`.
- `smartFiltersApplied` emitted when 'Go' button clicked.
- `searchInputChanged` emitted when `inputChange` event of search field is emitted.
- `smartFiltersChanged` is now triggered every time when filters model has been updated without 'GO' button click.
