### ISSUE TITLE
No scrollbar if fd-cards too long

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/fundamental-ngx#9173]
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.38.2

#### If this is a bug, please provide steps for reproducing it.
Page inside shellbar with fd-cards:
if the cards are too long there is no scrollbar visible

![image](https://user-images.githubusercontent.com/74785804/210367661-0182e867-965b-4bb8-95b5-86e1e9e20ed2.png)

#### Please provide relevant source code if applicable.
Ask me for the test code

#### Is there anything else we should know?
Suggestion fro; @g-cheishvili: "Looks like issue is that fd-layout-panel-body has class .fd-has-display-block , which is not removable via public api and whether or not it should be removed by us at all I am not sure. I will have to discuss this issue with peers"

**Comment by g-cheishvili** [comment]
Fix to this is just to update fundamental styles right now, so when we release 38.3 and styles will be nest release, it will be fixed automatically

https://github.com/SAP/fundamental-styles/pull/4152 fixed this
