### ISSUE TITLE
[Bug][Smart Filter Bar]: The input values are missing when toggle the show/hide fitler button

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#9175]
#### Is this a bug, enhancement, or feature request?
It is bug
#### Briefly describe your proposal.
After the input the values for filters, and the value is displayed. But when switch the show/hide button, the already input values are missing
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.36.2
#### If this is a bug, please provide steps for reproducing it.
1 Input the filter values 
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/10548281/210513135-42a5c25c-63c0-4b6d-be2b-6da77b5f3a79.png">
2 press the hide filter button
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/10548281/210513383-c9c9b5a8-b050-4534-b54c-413c51193ccb.png">
3 press the show button again
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/10548281/210513777-e0ef0c0e-7ad6-44f3-b94f-073e53da391a.png">

**Comment by platon-rov** [comment]
Closing as no
