### ISSUE TITLE
WizardGeneratorFormItem does not support properties to enable secondaryText

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#9178]
To enable secondaryText on Select control, properties like secondaryKey, showSecondaryText and secondaryTextAlignment are required to be set on the WizardGeneratorFormItem. However, as of now, it is not possible to set them as the interface `WizardGeneratorFormItem` does not support them. Would it be possible to extend the interface by optional properties to enable secondaryTexts?

Here, I have built a Stackblitz for this. (https://stackblitz.com/edit/angular-4qb9ea?file=src%2Fapp%2Fwizard-generator-default-example.component.ts)

**Comment by littleamigo** [comment]
From https://fundamental-ngx.netlify.app/#/platform/select/api:

> Optional secondaryKey
secondaryKey: string

> showSecondaryText
showSecondaryText: boolean = false

> secondaryTextAlignment
secondaryTextAlignment: TextAlignment = 'right'

**Comment by littleamigo** [comment]
It works as expected - thanks, Mike!
