### ISSUE TITLE
Search Field suggestion items overlay search field (if many suggestions are found)

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/fundamental-ngx#9199]
![image](https://user-images.githubusercontent.com/40032066/211578013-574b15dd-24e8-4a34-847a-5c2a3972d30a.png)
Here is a Stackblitz that demonstrates the issue: https://stackblitz.com/edit/angular-9qybvz?file=src%2Fapp%2Fplatform-search-field-basic-example.component.ts

To reproduce:

- open the stackblitz  https://stackblitz.com/edit/angular-9qybvz?file=src%2Fapp%2Fplatform-search-field-basic-example.component.ts
- type 't' into the first search field

I have tried with CSS to manually not overlay the search field.

**Comment by InnaAtanasova** [comment]
Hi @MichaelBaySAP, a PR with the fix is now open and once it's merged you can test it on your side. Please let us know if you still face issue after the update. Thanks

**Comment by littleamigo** [comment]
Hi @InnaAtanasova, thanks for the fix. I've tested it and it works basically okay.

However, the suggestions do not disappear when I scroll the whole page content up and down, neither it scrolls along with the rest of the page. It actually keeps its exact location while the other page content is moving as I scroll. I've observed the same weird visual appearance also with the opened value list of a select control. Is this something you already know and more like a general problem with these open value lists that you already tackle in another issue? Or would you like me to open another issue covering that?
