### ISSUE TITLE
enhancement: CDK focusable list

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#9202]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
With focusable list we have vertical or horizontal navigation available.
In some components (grid, table, etc) navigation can be bi-directional (up-down and left-right at the same time).
I would suggest improving focusable list component and add focusable grid functionality which can be used in table and grid

**Comment by g-cheishvili** [comment]
And calendar, that one is big too
