### ISSUE TITLE
[fdp-table][Sourcing][Dev blocker]: ngIf does not work in fundamental platform table

### ISSUE THREAD

**Issue by rayansailani** [SAP/fundamental-ngx#9212]
#### Is this a bug, enhancement, or feature request? 
Bug
#### Briefly describe your proposal.
*ngIf for fdp table column fails to evaluate when 

- Initial value of variable is false and
- Variable value changes after table is rendered.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Fundamental ngx - 0.38.2

#### If this is a bug, please provide steps for reproducing it.

- Create a platform table with <fdp-column> containing an *ngIf checking for some variable value being true or not. 
- Initialise a variable with value as false
- create a method that causes the change in variable's value to true

Expected: The column that wasn't visible previously should be visible now because the variable's value is true.

Observed: The column is still not visible.

(refer to code and video)
#### Please provide relevant source code if applicable.

```
<!-- component.html file -->
<fdp-table
  [dataSource]="source"
  [trackBy]="trackBy"
  emptyTableMessage="No data found"
>
  <fdp-table-toolbar title="Order Line Items" [hideItemCount]="false">
    <fdp-table-toolbar-actions>
      <fdp-button label="Hide column" (click)="hideCol()"></fdp-button>
    </fdp-table-toolbar-actions>
  </fdp-table-toolbar>

  <fdp-column name="name" key="name" label="Name" align="start"> </fdp-column>

  <fdp-column
    name="description"
    key="description"
    *ngIf="testBool"
    label="Description"
  >
  </fdp-column>

  <fdp-column name="price" key="price.value" label="Price" align="end">
  </fdp-column>

  <fdp-column name="status" key="status" label="Status" align="center">
  </fdp-column>
</fdp-table>

```

```
// component.ts file
import { Component } from '@angular/core';
import { Observable, of } from 'rxjs';

import { FdDate } from '@fundamental-ngx/core/datetime';
import { TableDataSource, TableDataProvider, TableState } from '@fundamental-ngx/platform/table';

@Component({
    selector: 'fdp-platform-table-default-example',
    templateUrl: './platform-table-default-example.component.html'
})
export class PlatformTableDefaultExampleComponent {
    source: TableDataSource<ExampleItem>;
 // test boolean value that is assigned false 
    testBool: boolean = false;

    constructor() {
        this.source = new TableDataSource(new TableDataProviderExample());
    }

    trackBy(index: number, item: ExampleItem): number {
        return item.id;
    }

    alert(message: string): void {
        alert(message);
    }

    hideCol () {
// method that toggles the value of the bool
        this.testBool = !this.testBool;
        console.log(this.testBool);
    }
}

// data provider and other boiler plate code

https://user-images.githubusercontent.com/54993789/212319429-c27b5544-167f-4f8b-a532-a6b750409ba0.mov


```

**Comment by mikerodonnell89** [comment]
This should have been fixed with https://github.com/SAP/fundamental-ngx/pull/8844

**Comment by rayansailani** [comment]
@mikerodonnell89 The issue https://github.com/SAP/fundamental-ngx/pull/8844 is fixed. But there is some issue when the value referenced by *ngIf is initially false.

**Comment by I543348** [comment]
Hi @mikerodonnell89 , this issue should be fixed both when initial value is false and true

**Comment by rayansailani** [comment]
verified as working on preview build and latest version documentation.
