### ISSUE TITLE
Bug: Dropdown expands when label is clicked

### ISSUE THREAD

**Issue by SaiShan** [SAP/fundamental-ngx#924]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
If the user clicks into the label (yellow box), the item should only get focus and the dropdown should not expand. The dropdown should expand when clicking on the down arrow only (green box).

<img width="598" alt="Screen Shot 2019-06-13 at 9 27 04 AM" src="https://user-images.githubusercontent.com/25252963/59436440-9c2c6000-8dbd-11e9-94c2-837178436c41.png">

**Comment by MattL75** [comment]
I've never seen **any** dropdown have the behaviour they're suggesting. So basically they're wrong. Talk about it at the grooming this afternoon.
