### ISSUE TITLE
Initial value for Segmented Button in Reactive Forms doesn't work anymore

### ISSUE THREAD

**Issue by aflalves** [SAP/fundamental-ngx#9240]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Initial value for Segmented Button in Reactive Form doesn't work anymore. We just updated from 0.33 to 0.38.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15
Fundamental 0.38

#### If this is a bug, please provide steps for reproducing it.

We can see the bug in the official docs/demo: [segmented-button](https://sap.github.io/fundamental-ngx/#/core/segmented-button#form)

Looking at the typescript code, the form is created with value "first", so "Left" should be selected (just like the non reactive forms examples)

![image](https://user-images.githubusercontent.com/6796342/213121828-4c354234-d15a-47fd-8a3f-0e2f2f3acc15.png)

**Comment by N1XUS** [comment]
Not reproduced in latest version. Closing
