### ISSUE TITLE
[fdp-table] [Sourcing][Dev blocker]: Expand all / collapse all on page load

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9241]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.

1) There should be a way using which programatically one should be able to decide - whether the table should be expanded or collapsed by default.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13 
core / platform - 0.35.x

#### Is there anything else we should know?
This affects guided sourcing customers, please reach out in case of any further queries.

**Comment by mikerodonnell89** [comment]
I could use a bit more clarification for point 2. Are you saying if a user collapses or expands a specific row, and they navigate away from the page, and then back, the table should remember its state from before the user navigated away?

**Comment by g-cheishvili** [comment]
My 2 cents:
I do not think that saving state of the table is fundamental's responsibility, it should be implemented on user's side, not on lib side

**Comment by I543348** [comment]
> For point 1: An immediate solution would be to access your table component via `ContentChild` / `ViewChild` and call the public methods `expandAll()` or `collapseAll()`. However I can open a PR that provides a boolean input property `expandOnInit` to make this a bit simper
> 
> I could use a bit more clarification for point 2. Are you saying if a user collapses or expands a specific row, or all rows, and they navigate away from the page, and then back, the table should remember its state from before the user navigated away?

Hi @mikerodonnell89 , please ignore point 2 we dont need it , just point 1 fix would work for us.
thanks.

**Comment by mikerodonnell89** [comment]
https://github.com/SAP/fundamental-ngx/pull/9253

**Comment by rayansailani** [comment]
This is still not working in 0.39.0 version as tested on https://stackblitz.com/edit/angular-sagzbh-92ktsl?file=src/app/platform-table-tree-example.component.html

**Comment by mikerodonnell89** [comment]
> This is still not working in 0.39.0 version as tested on https://stackblitz.com/edit/angular-sagzbh-92ktsl?file=src/app/platform-table-tree-example.component.html

It is working in this example, all tree items that have children are expanded when the example first loads. What am I missing here?

**Comment by rayansailani** [comment]
My bad, verified as working now. It didn't seem to work in the stackblitz when I tested it back then. Thanks.
