### ISSUE TITLE
[Sourcing][Enhancement][Dev blocker]: Multi-input with value help dialog Enhancement - Chooser-hierarchy

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9247]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
This is the basic idea (mock-ups are just showing the idea, this is NOT a pixel-perfect design. Do NOT over-style the standard components and use consistent padding / margins for the dialog contents. Strings were not adapted in these mock-ups, etc.):
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
[Multi Input field](https://fundamental-ngx.netlify.app/#/platform/multi-input)
Typing opens a flat list of search-results in the drop-down
Clicking the “value help“ button within the input field opens a Dialog, which contains
A dialog title (ideally fitting to the label of the multi input field, e.g. “Select Locations”, “Select Products”, etc.)
A “search” input field
A tree or tree table ([table](https://fundamental-ngx.netlify.app/#/platform/table) component) filled with all the items
And a dialog footer (Select + Cancel buttons)
 
In the dialog
Selecting items and pressing “Select” adds the corresponding items as tokens to the multi input field
Using the search input field can
Either just filter down the tree (keeping the tree structure but remove all leave items which do not fit to the search term and keep their parent nodes AND remove all empty nodes)
Or provides a flat search results list
In both cases, this would still be a table component.
 
Figma link:
https://www.figma.com/file/eCJFLDGh1AmEhSZr3KlRmR/Untitled?node-id=26%3A26539&t=beENXceeET4s3NhO-1

![image002](https://user-images.githubusercontent.com/88182358/213517213-dcb23d6b-c7a0-4d27-a362-03d0a9213270.png)

#### Is there anything else we should know?
Some of the functionality this component should have are as below -
1) User should be able to search from the input box of multi-input and there should be an autocomplete with a flat list of multi select options matching searched text
2) User should be able to click on the icon square to open a value-help dialog of reasonable width
3) The dialog should contain a search box , tree table with 2 columns (Name and Id) 
4) the tree level should support huge levels and there should be an option to lazy load the leaf nodes in tree 
5) the search box inside dialog should behave exactly as point 1
6) selected nodes should appear as tokens in the search box 
7) The search inside dialog can display complete hierarchy whereas the search outside the dialog should display only flat list
8) There should be a way to display loading animation during lazy loading
9) All of the controls and operations should be supported and performed using keyboard standard keys

This is critical for guided sourcing.

**Comment by droshev** [comment]
This component needs to be created as a web component

**Comment by I543348** [comment]
> This component needs to be created as a web component

We had couple of discussions with UX experts and PMs , the SAP UI5 web component is under design stage and the control is needed for guided sourcing customers as it is a hard commit.  
Thanks

**Comment by droshev** [comment]
The update from the designer was to use Input Group linked with Value help dialog. More info can be found here:
- Input Group (you can use it to make the input look like multi input) - https://fundamental-ngx.netlify.app/#/core/input-group
- Value Help Dialog - https://fundamental-ngx.netlify.app/#/platform/value-help-dialog

**Comment by I543348** [comment]
Thanks @droshev , as a successor of this issue , could you please help us with respective web component's JIRA ticket where we can track the availablility and usage of the component?

**Comment by droshev** [comment]
> Thanks @droshev , as a successor of this issue , could you please help and share - respective web component's JIRA ticket where we can track the availablility and usage of the component?

@I543348 Let's take it directly between us as communication

**Comment by I543348** [comment]
This can be closed.
cc: @droshev
