### ISSUE TITLE
[fdp-table][Sourcing][Accessibility]: input box inside fdp-table-cell issues

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9248]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1) Not able to add spaces inside a input box in a fdp-table-cell : <tr> has keydown event listener, when removed works fine
2)  Not able to traverse through characters using left and right arrow keys inside a input box inside a table cell
3) Accessibility: Not able to move between the input boxes in different rows using up and down arrow keys

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

angular 13
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
Try to type something inside a input box in any table cell and add space - https://sap.github.io/fundamental-ngx/#/platform/table#custom-columns example
Notice that there is "." dot added but not space.

1) Not able to add spaces inside a input box in a fdp-table-cell : <tr> has keydown event listener, when removed works fine
2)  Not able to traverse through characters using left and right arrow keys inside a input box inside a table cell
3) Not able to move between the input boxes in different rows using up and down arrow keys

#### Please provide relevant source code if applicable.
pls refer to https://sap.github.io/fundamental-ngx/#/platform/table#custom-columns 

#### Is there anything else we should know?
works fine when keydown event listener needs to be removed

**Comment by mikerodonnell89** [comment]
I will speak with the accessibility designers about how point #2 should work, since we will still want the left/right arrow keys to move cell focus.

**Comment by mikerodonnell89** [comment]
Interaction guidelines state that table cells with inputs in them should default to focus navigation. When a user moves to a cell with an editable input, they can press f2 (windows) or return (mac) to move into edit mode, where the text cursor will move to the input and the user can then use the arrow keys to move the cursor around text in the input. The user can also start typing immediately after focusing the cell, which would clear all text in the cell and enter edit mode automatically.

**Comment by mikerodonnell89** [comment]
https://github.com/SAP/fundamental-ngx/pull/9368

**Comment by mikerodonnell89** [comment]
Fixed as part of https://github.com/SAP/fundamental-ngx/pull/9324

**Comment by I543348** [comment]
This is fixed. Checked and tested on NGX website https://sap.github.io/fundamental-ngx/#/platform/table#custom-columns
