### ISSUE TITLE
[fdp-table][Sourcing]: Resizing columns is adding an extra column at the end 

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9249]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1) Resizing column is adding an extra blank column at the end of the table

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

angular 13 
core / platform - 0.35.x

#### If this is a bug, please provide steps for reproducing it.
1) Access https://sap.github.io/fundamental-ngx/#/platform/table#default 
2) Try to resize the column
3) Notice that there is a blank column at the end of the table

The no. of columns should not be increased.

#### Please provide relevant source code if applicable.
pls refer to https://sap.github.io/fundamental-ngx/#/platform/table#default 

#### Is there anything else we should know?
This is a blocker for guided sourcing migration

**Comment by droshev** [comment]
@I543348 In ui5 [example](https://ui5.sap.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable) the behaviour is the same - you see an extra column at the end when you shrink the table and it disappear when you expand the columns beyond that width
