### ISSUE TITLE
[fdp-table][Sourcing][Dev blocker]: Not able to search leaf nodes inside tree table

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9250]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Try searching a leaf node text from search inside a table - notice that the leaf node text is not shown even though the text exists in table

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
ANGULAR 13
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
1) Access https://sap.github.io/fundamental-ngx/#/platform/table#tree 
2) Search a leaf node text "Ergo" 
3) notice the table shows " no data found"
4) Instead the table should show the "Ergo" rows as search results

#### Please provide relevant source code if applicable.

pls refer to https://sap.github.io/fundamental-ngx/#/platform/table#tree 
#### Is there anything else we should know?

This is critical to guided sourcing

**Comment by droshev** [comment]
@I543348 is a completely custom function, which means fully controlled by the application. In that case you have full control.
