### ISSUE TITLE
[fdp-combobox][Sourcing][Dev blocker]:Unable to enter numeric values using numeric keypad

### ISSUE THREAD

**Issue by bharathSivaSAP** [SAP/fundamental-ngx#9254]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Try entering a numeric value from using number keypad in the keyboard, the entered numbers are not reflecting in the combobox.
But we are able to enter numbers via the main keypad.
It works with fd-combobox but not in fdp-combobox

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 13
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.

- Access https://sap.github.io/fundamental-ngx/#/platform/combobox
- Try entering a numeric value from using number keypad.
- Number is not entered instead first item from the dropdown is getting highlighted.

#### Please provide relevant source code if applicable.
Please refer to https://sap.github.io/fundamental-ngx/#/platform/combobox

#### Is there anything else we should know?
This is critical to guided sourcing

**Comment by droshev** [comment]
@bharathSivaSAP I was able to do so:
![combo-number](https://user-images.githubusercontent.com/4380815/213955216-0aebd8b5-a341-479c-88a5-ca4e9b7d1365.gif)

**Comment by bharathSivaSAP** [comment]
I think you are using fd-combobox but not fdp-combobox. 
for me it is not working with  fdp-combobox. Attached the recording.

https://user-images.githubusercontent.com/123215488/214112168-0d24100e-ef44-48c1-adaa-2b0fed18739b.mov

**Comment by droshev** [comment]
> * https://sap.github.io/fundamental-ngx/#/platform/combobox

I used the link you provided and it is the very first example

**Comment by bharathSivaSAP** [comment]
Sorry that was fd-combobox link.
This is the correct one: https://stackblitz.com/edit/angular-5zebky?file=src%2Fapp%2Fcombobox-example.component.html
This link has fdp-combobox. Please verify again. 
Thanks.
