### ISSUE TITLE
AM/PM is hard coded on every date-time picker

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#9269]
Its a bug

"AM"/"PM" is hardcoded in all the places where we have fdp-date-picker used

Angular 12

Steps to replicate the issue: I am providing one particular page just to display the issue, but the issue is replicable in all the pages where we have fdp date picker.

1. Log in as language users such as zh_TW210309b, ja210309b, etc.
2. Create a guided sourcing project > full project
3. Create a task
4. Click the three dots to Edit the task 
5. Scroll down to Comments and activity history
6. Leave a comment > Send
7. View the time format of the comment

**Comment by I543348** [comment]
Hi @sahanaN123 , NGX team cannot reproduce the issue on guided sourcing application.
Please share the code snippet or see if the issue is replicable on NGX site itself.

**Comment by droshev** [comment]
@sahanaN123 did you mean time picker instead of date picker, as date picker doesn't have time to store? Or maybe date time picker?

What is the expected result?

**Comment by sahanaN123** [comment]
It should be date picker. I have attached the code snippet from one of the component where we are facing this issue.

Thanks,
Sahana.


From: deno ***@***.***>
Date: Tuesday, 31 January 2023 at 4:09 AM
To: SAP/fundamental-ngx ***@***.***>
Cc: N, Sahana ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP/fundamental-ngx] AM/PM is hard coded on every date-time picker (Issue #9269)

@sahanaN123<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FsahanaN123&data=05%7C01%7Csahana.n%40sap.com%7C0b213d11ac5c4961bfd108db0312c476%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638107151392778382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OvC%2BDa8Ck2ubwnDyVCPO%2BlBezYaP%2F60YRUA%2B1pkootU%3D&reserved=0> did you mean time picker instead of date picker, as date picker doesn't have time to store? Or maybe date time picker?

What is the expected result?

**Comment by sahanaN123** [comment]
@droshev yes time and date-time picker has the issue.

**Comment by I543348** [comment]
This issue is mostly on .localization for AM / PM for fdp-date-time picker

**Comment by droshev** [comment]
@I543348 Can you describe what you would expect as a solution?

**Comment by I543348** [comment]
Hi @sahanaN123  , can you please take a look and confirm on this issue ?
As this is quiet old issue

**Comment by droshev** [comment]
Feel free to open a new issue if there is an improvement needed
