### ISSUE TITLE
Bug: Timeline "Connecting Line" strikes through icons

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#9271]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
As seen on the [docs' first example](https://sap.github.io/fundamental-ngx/#/core/timeline), the connecting line strikes through the icons when initially loading the page.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/7091280/214267201-cebafeec-cb6c-4ab4-913c-792025d0f6bb.png">

It's only broken when initially loading the page. E.g. resizing the browser window fixes the visual defect. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.38.2

#### If this is a bug, please provide steps for reproducing it.
1. Load docs on Timeline and scroll to first example:
https://sap.github.io/fundamental-ngx/#/core/timeline
2. Resize browser window to see the strike-through disappear.

#### Is there anything else we should know?

Fundamentals Team comment:
The height and the width of the connecting lines is calculated dynamically and the css is assigned with inline styling to the element. For example:
`<div class="fd-timeline__connecting-line" style="height: 80px;"></div>`
On window resize these calculations are not applied correctly which results in lines going through the icons of the timeline and even overflowing the component.

**Comment by N1XUS** [comment]
Not reproduced with the latest version. Closing
