### ISSUE TITLE
[Sourcing][Accessibility] Tooltip not being read for linear reading mode in JAWS

### ISSUE THREAD

**Issue by i563785** [SAP/fundamental-ngx#9276]
Bug

Tooltip not being read for linear reading mode in JAWS screen reader

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Steps to replicate the issue:
 1. Go to https://sap.github.io/fundamental-ngx/#/core/inline-help
 2. Under 'Inline Help' example, use JAWS linear reading mode to read the tooltips
 3. Observe the issue

**Comment by droshev** [comment]
@i563785 Could you provide your JAWS settings?

**Comment by i563785** [comment]
Sure @droshev, these are the steps that I'm following:

Turning virtual PC cursor on using Insert+Spacebar+Z
Using down arrow key to navigate to use it in linear reading mode

However if I use Tab key to move to next element, the tooltips are being read as it is running in application mode.

**Comment by I543348** [comment]
> Sure @droshev, these are the steps that I'm following:
> 
> Turning virtual PC cursor on using Insert+Spacebar+Z Using down arrow key to navigate to use it in linear reading mode
> 
> However if I use Tab key to move to next element, the tooltips are being read as it is running in application mode.

The tab key should not be used in linear reading mode of JAWS

**Comment by mikerodonnell89** [comment]
I've reached out to the accessibility team regarding how this should work for us, as I've seen it work differently for different libraries and it's not specifically mentioned in the screenreader specs

**Comment by KaptaanBarbosa** [comment]
This has to be tested via ATL team via JAWS screen reader , please comment which release version we can test this change

**Comment by I543348** [comment]
[v0.41.1-rc.8](https://github.com/SAP/fundamental-ngx/releases/tag/v0.41.1-rc.8)
In this version its available @KaptaanBarbosa

**Comment by i563785** [comment]
Hi @mikerodonnell89, this issue is still replicable for **Inline Help with Template Inside** example. There are totally 2 issues:

1.) when focus goes to the text with tooltip in the linear reading mode, the tooltip isn't visible.
2.)  The tooltip text is not being read in linear reading mode.

JAWS history: 
<img width="955" alt="MicrosoftTeams-image (6)" src="https://github.com/SAP/fundamental-ngx/assets/113977593/2ed26d57-9ec8-405d-b735-53aa1c7f2cce">

**Comment by i563785** [comment]
Hi @mikerodonnell89, the below issues are not resolved for JAWS:

1.) when focus goes to the text with tooltip in the linear reading mode, the tooltip isn't visible.
2.) whenever focus goes to the tooltip in linear reading mode, the screen goes blank.
![Uploading c8485a53-6877-4179-abaa-8fe9c49e57c7.jpg…]()
![3867ec44-beae-4b7e-9561-cb68f8a4b267](https://github.com/SAP/fundamental-ngx/assets/113977593/0666cace-969a-40c5-8741-ec2d2c74285d)

**Comment by mikerodonnell89** [comment]
> Hi @mikerodonnell89, the below issues are not resolved for JAWS:
> 
> 1.) when focus goes to the text with tooltip in the linear reading mode, the tooltip isn't visible. 2.) whenever focus goes to the tooltip in linear reading mode, the screen goes blank.

1.) Linear reading mode isn't supposed to work like a mouse or keyboard and doesn't actually focus or hover elements, so I'm not sure what we can do about this here. I don't think it's possible to emulate a focus or hover event in linear reading mode. The user can use tab keys to actually focus the items with tooltips, which will open the tooltip. Even in linear reading mode, the tooltip content is still read by JAWS when the user arrows to the element with the tooltip, the tooltip just doesn't open.

2.) Appears to be an unrelated side effect of some styling on our documentation website, removing that here: #10006
