### ISSUE TITLE
[Sourcing][Dev-blocker][fdp-table]: Infinite scroll performance issue and expand collapse for tree table

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9278]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1)  User should be able to perform infinte scroll in few seconds , if the dataset is huge say 1000 records in total , there is a lag today resulting in performance issues
2) User should be able to collapse all child rows , which are not yet lazy loaded , when the parent is collapsed or expanded accordingly with infinite scrolling

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
Not sure if this is possible , discussed this with Mike , and logging the issue for an outcome or confirmation.

**Comment by droshev** [comment]
Those requirements should go through web components requests, so they can be provided generically and able to be reused.

**Comment by I543348** [comment]
We cannot use pagination as we need to maintain consistency across guided souring tables and PM teams have provided requirement to use only "infinite scrolling" for all tables
