### ISSUE TITLE
Add colour for an SAP icon in fdp standard list

### ISSUE THREAD

**Issue by DimitarVoynov** [SAP/fundamental-ngx#9279]
Hi colleagues, 

we have the following (rather a consulting) question: 
with ```<fdp-standard-list-item titleIcon="sap-icon sap-icon--account">```
we see the icon being correctly displayed:  
![image](https://user-images.githubusercontent.com/8601332/207625607-19ade72a-d0e0-4fbe-b072-4ea0afd98ae0.png)

but is it possible for us to adjust the color like this: 

![image](https://user-images.githubusercontent.com/8601332/207625468-38fc2f78-0391-4898-a583-1e4921801034.png)

the icon spec is: 
![image](https://user-images.githubusercontent.com/8601332/207625728-add6a2e2-d999-4919-9558-507346a12d42.png)

Thanks in advance!

_Originally posted by @ivzhelev in https://github.com/SAP/fundamental-ngx/issues/8657#issuecomment-1351542184_

**Comment by droshev** [comment]
@DimitarVoynov you can achieve that by using the list from the core package as there you write the avatar tag and it accepts the color as input. I think this should work for you

**Comment by DimitarVoynov** [comment]
Hi @droshev, thanks for this suggestion!

I am not sure this is an option for us though (not to say that I am pretty sure - it is not) as if I understand your suggestion correctly - in order to now use https://sap.github.io/fundamental-ngx/#/core/list we have to switch from `fdp-list` to `fd-list` (also from `fdp-standard-list-item` to `fd-list-item`) and this way we lose some of the properties that `fdp-list` gave us (like `dataSource`). 

This was rather a quick check from my side - only making the above mentioned changes i.e. switching to the 'standard' version of the list and now our UI does not show the notifications correctly.
