### ISSUE TITLE
Platform multi input - searchTermChange event not available

### ISSUE THREAD

**Issue by aaasarthak** [SAP/fundamental-ngx#9280]
#### Is this a bug, enhancement, or feature request?
Feature Request

#### Briefly describe your proposal.
Please add the searchTermChange event as we have already in the core multi-input component.

#### Please provide relevant source code if applicable.
https://github.com/SAP/fundamental-ngx/blob/be8e290bea87a324598e8dd4fc8af84545f75245/libs/core/src/lib/multi-input/multi-input.component.ts#L284

**Comment by droshev** [comment]
@N1XUS what do you think?
