### ISSUE TITLE
Platform multi input - selection mode multi not working as expected

### ISSUE THREAD

**Issue by aaasarthak** [SAP/fundamental-ngx#9281]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In selection mode multi-select, on selecting the values, it should show those values as the tokens in the field as well.

#### If this is a bug, please provide steps for reproducing it.
- Use selection mode as multi on the platform multi-input component, and try selecting the values from the dropdown using the c checkbox
- Observe that, the values in the popover shows as selected in the checkbox, but doesn't reflect in the field as the tokens.

#### Please provide relevant source code if applicable.
```
<fdp-multi-input
                formControlName="item"
                placeholder="Field placeholder text"
                type="text"
                id="fdp-id-reactive"
                name="input1"
                [dataSource]="_datasource"
                displayKey="state"
                selectionMode="multi"
            >
```

#### Is there anything else we should know?

https://user-images.githubusercontent.com/45348322/214542715-8fb94473-5baf-4f73-8a5b-c18b641229a8.mp4

**Comment by droshev** [comment]
@N1XUS do you think with your latest updates this will be fixed?
