### ISSUE TITLE
[sourcing] Platform table is not s not compliant with Fiori when `rowsActivable` is false

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9283]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
Right now, when `rowsActivable` is false, `selectionMode="multiple"`, there is a gray background color when hover over a row. This is not compliant with Fiori. 

Row should have no hover unless it’s single cell-based interactions

See https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Basic

![Oscar ScreenCapture 2023-01-25 at 17 57](https://user-images.githubusercontent.com/7035787/214740446-ee05c248-17df-4866-b6d0-5ae9489a815a.gif)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.38.2

**Comment by droshev** [comment]
@oscargong in that link the table has hover effect too:
![Screenshot 2023-01-30 at 5 43 03 PM](https://user-images.githubusercontent.com/4380815/215613030-cec6ca85-5385-4fad-a004-03126dc66848.png)

**Comment by oscargong** [comment]
> @oscargong in that link the table has hover effect too: ![Screenshot 2023-01-30 at 5 43 03 PM](https://user-images.githubusercontent.com/4380815/215613030-cec6ca85-5385-4fad-a004-03126dc66848.png)

Hi droshev, did you turn on or off any option? On my side, I cannot see the hover state of rows.

https://user-images.githubusercontent.com/7035787/215635455-4b919cb4-b8bd-4eba-b907-dddde4efb226.mp4

**Comment by droshev** [comment]
@oscargong actually I was using an official version (1.109.3) and the link you shared points to in dev version
https://sapui5nightly.int.sap.eu2.hana.ondemand.com/1.109.3/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Basic

**Comment by oscargong** [comment]
Hi @droshev,

Thanks, I will share this with my teams.

**Comment by I543348** [comment]
This is fixed
