### ISSUE TITLE
[Sourcing][Dev blocker]: ngFor not working on fdp-column

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9288]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Not able to iterate fdp-column using ngFor 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 13 
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
1) dynamically add columns to fdp-table using array and ngFor 
2) The number columns appear as many as there are array elements 
3) but the array values are incorrect when used as fdp-column labels

#### Please provide relevant source code if applicable.
html code 
```
  <fdp-column
   *ngFor="let a of arr"
    name="description"
    key="description"
    [label]="a.toString()"
  >
  </fdp-column>
```

component.ts file -> please add arr =[1,2,3,4,5];
notice that only "1" is displayed 5 times but 1 , 2 , 3, 4 and 5 should have been displayed rather.

#### Is there anything else we should know?
This is  a blocker for us , as we are not able to migrate to NGX table
<img width="1789" alt="Screenshot 2023-01-27 at 6 09 52 PM" src="https://user-images.githubusercontent.com/88182358/215089527-331e9d13-26eb-40a1-bc2a-7be4b9a0be45.png">

**Comment by g-cheishvili** [comment]
> #### Is this a bug, enhancement, or feature request?
> Bug
> 
> #### Briefly describe your proposal.
> Not able to iterate fdp-column using ngFor
> 
> #### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
> Angular 13 core / platform : 0.35.x
> 
> #### If this is a bug, please provide steps for reproducing it.
> 1. dynamically add columns to fdp-table using array and ngFor
> 2. The number columns appear as many as there are array elements
> 3. but the array values are incorrect when used as fdp-column labels
> 
> #### Please provide relevant source code if applicable.
> html code
> 
> ```
>   <fdp-column
>    *ngFor="let a of arr"
>     name="description"
>     key="description"
>     [label]="a.toString()"
>   >
>   </fdp-column>
> ```
> 
> component.ts file -> please add arr =[1,2,3,4,5]; notice that only "1" is displayed 5 times but 1 , 2 , 3, 4 and 5 should have been displayed rather.
> 
> #### Is there anything else we should know?
> This is a blocker for us , as we are not able to migrate to NGX table <img alt="Screenshot 2023-01-27 at 6 09 52 PM" width="1789" src="https://user-images.githubusercontent.com/88182358/215089527-331e9d13-26eb-40a1-bc2a-7be4b9a0be45.png">

`name` input value should be different, you pass always `"description"`

**Comment by g-cheishvili** [comment]
Try it, if it does not work, re-open this issue

**Comment by I543348** [comment]
Works fine , Thank you so much for quick update.
