### ISSUE TITLE
[Sourcing][Dev Blocker] Value is not getting updated inside the fdp-table-header and fdp-table-cell tags for the for loop used in the fdp-column

### ISSUE THREAD

**Issue by Ankit0025-cmd** [SAP/fundamental-ngx#9311]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
The columns are not getting rendered dynamically with the array used in the loop. Also the values inside the for loop is not getting changed with the variable.

#### If this is a bug, please provide steps for reproducing it.
1. Add a for loop in the fdp-column tag for an array
2. Use that variable from the for loop using interpolation
3. Change that array in the ts file using some button or any function
5. The values for the variable in the for loop is fixed even the loop run the exact number of times the elements present in the array.
6. The columns are also not getting added dynamically when we change the array using the button(Check the Stackblitz with the console on, it will show that the array is getting updated but the columns are not getting updated with the array).

#### Please provide relevant source code if applicable.
StackBlitz Link: https://stackblitz.com/edit/angular-h3a8bf?file=src/app/platform-table-default-example.component.html 

#### Is there anything else we should know?
Observe the value of the num inside the tags, it is not getting updated when the loop runs. It is fixed at zero which is the initial provided value.

**Comment by I543348** [comment]
This is also a major blocker , Guided sourcig team is stuck to migrate to NGX table.
Request to consider as high priority

**Comment by Ankit0025-cmd** [comment]
The columns are getting added dynamically when the array is updated.
