### ISSUE TITLE
[sourcing]  `fdp-table` support custom toolbar title

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9312]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
Currently, `fdp-table-toolbar` only supports a string type `[title]` binding as the table header. We need a customizable header to implement certain features.

Right now, the closest position we can reached is next to the search input

![Oscar ScreenCapture 2023-01-31 at 23 37@2x](https://user-images.githubusercontent.com/7035787/215992329-7e93d28a-dcaf-4d11-9700-5472dd60690c.png)

If we can support new html tag, such as `<fdp-table-header> </fdp-table-header>`, which can be put inside `<fdp-table-toolbar> </fdp-table-toolbar>`, would be really helpful.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.38.2

#### If this is a bug, please provide steps for reproducing it.

not a bug

#### Please provide relevant source code if applicable.

N/A

**Comment by N1XUS** [comment]
Hello @oscargong. Thank you for your ticket.
You can use `fdp-table-toolbar-left-actions` component for that. Here's small stackblitz example:
https://stackblitz.com/edit/angular-gpd36b?file=src%2Fapp%2Fplatform-table-default-example.component.html

**Comment by oscargong** [comment]
Hi @N1XUS ,

Thanks for your response. `<fdp-table-toolbar-left-actions>` looks enough for this use case. But I cannot use it on my application since we are upgrading both Angular and Fundamental-NGX. I will try later.

Is `<fdp-table-toolbar-left-actions>` mentioned in the doc website? I cannot find it. Should we consider add an example if it is missing?

**Comment by I543348** [comment]
This is fixed
