### ISSUE TITLE
Not able to open URL of V-29.0, just latest version url is accessible.

### ISSUE THREAD

**Issue by bulletproofadks** [SAP/fundamental-ngx#9313]
#### Is this a bug, enhancement, or feature request?
BUG
#### Briefly describe your proposal.
In my project I am using your v29.0, but cant open its url. URL is only working for latest version.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Version 29.0
#### If this is a bug, please provide steps for reproducing it.
try opening https://6040dbed0b78130008f102b5--fundamental-ngx.netlify.app/
#### Please provide relevant source code if applicable.
no
#### Is there anything else we should know?
no

**Comment by N1XUS** [comment]
Hello @bulletproofadks thank you for submitting a ticket.
For older versions you could clone the appropriate branch (for example, this one is for v0.29.1 https://github.com/SAP/fundamental-ngx/tree/v0.29.1) and run it locally

**Comment by bulletproofadks** [comment]
Thanks @Denis, it helped
