### ISSUE TITLE
bug(platform):  fdp standard list not showing more than 50 items (provided with datasource observable)

### ISSUE THREAD

**Issue by ivzhelev** [SAP/fundamental-ngx#9315]
#### Is this a bug, enhancement, or feature request?
bug
As discussed with @N1XUS opening this github issue.

#### Briefly describe your proposal.
When using fdp-list with `dataSource` with `Observable<customType[]>`, no more but only 50 items from the source are shown in the list. Here is the app link: https://stackblitz.com/edit/angular-54hgk7?file=src/app/platform-standard-list-item-with-selection-example.component.ts

So, clicking the **"Add Notification"** blue button "replaces" the datasource with another one that has **51** elements, but only **50** are visible in the browser

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Our current setup:
"Angular": "15.1.0"
"Fundamental": "0.38.2"

#### If this is a bug, please provide steps for reproducing it.
Check the described steps in the section above.

#### Please provide relevant source code if applicable.
Check the described steps in the section above with the source code in the stackblitz example.

#### Is there anything else we should know?

Seems quite related with a previously opened issue: https://github.com/SAP/fundamental-ngx/issues/8996

Thanks for looking into this.

**Comment by N1XUS** [comment]
Hello @ivzhelev
To fix this, you can do following:
In component define `limit = Infinity;`
In component's template, pass this `limit` as input property of `fdp-list` called `[itemSize]`:
```
<fdp-list [itemSize]="limit"></fd-list>
```

**Comment by ivzhelev** [comment]
Thanks for the details @N1XUS 
However, the issue still persists even after setting `limit = Infinity`
Here is the app link: https://stackblitz.com/edit/angular-54hgk7?file=src/app/platform-standard-list-item-with-selection-example.component.html

Thanks in advance.
