### ISSUE TITLE
There is no 4-sided visible focus on dynamic page sub header

### ISSUE THREAD

**Issue by nagbhushanr** [SAP/fundamental-ngx#9316]
#### Is this a bug, enhancement, or feature request?
Accessibility Issue

#### Briefly describe your proposal.
Observed Behavior:
There is no 4-sided visible focus provided to ‘Quick Start’ heading region.

Expected Behavior:
All UIs should be provided with sided visible focus.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular - 15
fundamental ngx - 0.38.2

#### If this is a bug, please provide steps for reproducing it.

https://sap.github.io/fundamental-ngx/fundamental-ngx#/core/dynamic-page
Inspect and check for dynamic page subheader

#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/119582923/216121734-f7ebd9cc-37d7-40b1-a437-dc01efe0b0d9.png)

**Comment by nagbhushanr** [comment]
Hi @N1XUS , this issue was mistakenly raised by me on fundamental styles repo and the solution for this is provided there thank you for that....... but we use fundamental ngx in our product can you please provide the fix here as well. Sorry for the inconvenience.

**Comment by mikerodonnell89** [comment]
This will be fixed in fundamental-ngx when the library bumps its style version

**Comment by nagbhushanr** [comment]
so....no need of any additional efforts, is it? good to know. Thank you.
