### ISSUE TITLE
[Datepicker] dates/formats are constantly changed upon entering calendar

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#932]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

Entering calendar (either via calendar icon or input) triggers date/format changes.

Note that theres also validation (red border) triggered for some dates, probably because of wrong format (30.06 is considered as 6th day of 30th month)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

fundamental-ngx: "0.5.2"
fiori-fundamentals: "1.5.7"

#### If this is a bug, please provide steps for reproducing it.

![dateformatting](https://user-images.githubusercontent.com/12159534/59509627-df67fb00-8eb1-11e9-9b59-18faf32176d9.gif)

#### Please provide relevant source code if applicable.

```
                <fd-date-picker
                    [type]="'single'"
                    formControlName="start">
                </fd-date-picker>
```

```
    this.form = this.fb.group({
      start: [],
      end: [],
    });
```

#### Is there anything else we should know?

**Comment by MattL75** [comment]
@mikerodonnell89 If you remember this is what I had said @JKMarkowski 's closed PR fixed. This is due to us using toLocaleDate, so this all works fine in the US and Canada, but the format is different for some EU countries.
