### ISSUE TITLE
Issue of "about:blank" when opening fd-formatted-text in Safari

### ISSUE THREAD

**Issue by Anysysjgw** [SAP/fundamental-ngx#9322]
#### Is this a bug, enhancement, or feature request?
bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "14.2.5"
"@fundamental-ngx/core": "0.36.0"

#### If this is a bug, please provide steps for reproducing it.
It can be reproduced easily by using the component `fd-formatted-text` and open it in `Safari` (Version 16.3).
- In "Network" tab, we can see a lot of "about:blank" as we use many `fd-formatted-text`.
![image](https://user-images.githubusercontent.com/1304168/216289332-c0c2f3d8-8038-40c0-9c52-6939310efd0a.png)
- In "Console" tab, we can see the error message of `Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set`.
![image](https://user-images.githubusercontent.com/1304168/216481905-37dabef7-b457-41f2-96f3-cd7a6c384ae6.png)
![image](https://user-images.githubusercontent.com/1304168/216289440-31ef3d7f-4d7c-4878-8b26-f57308417308.png)

**Comment by mikerodonnell89** [comment]
Seeing this in safari on our example page: 
<img width="947" alt="Screenshot 2023-03-10 at 11 28 27 AM" src="https://user-images.githubusercontent.com/2471874/224395082-d81482fc-9744-4fd6-99cf-f8ee19d1560c.png">
