### ISSUE TITLE
Read aloud doesn't work fd-popover

### ISSUE THREAD

**Issue by soloshhoter7** [SAP/fundamental-ngx#9342]
#### Is this a bug, enhancement, or feature request?
Its a accessibility bug
#### Briefly describe your proposal.
Whenever i use browser read aloud feature, it doesn't go through the popover content.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular -15
fundamental ngx - 0.38.2
#### If this is a bug, please provide steps for reproducing it.
click on any fd-popover element with text as content, on the mentioned link in edge browser and now use read aloud feature for text to speech.
open any popover and you will observe that popover contents are not read.
https://sap.github.io/fundamental-ngx/#/core/popover

**Comment by mikerodonnell89** [comment]
@soloshhoter7 by default, focus does not move to the popover body content but stays on the popover trigger. You can use the input <code>[focusAutoCapture]="true"</code> to move focus to the popover body when it is opened and the screenreader should start reading the contents automatically
