### ISSUE TITLE
Netlify links to older versions of documentation is not working

### ISSUE THREAD

**Issue by ivijan** [SAP/fundamental-ngx#9343]
#### Is this a bug, enhancement, or feature request?

Documentation bug.

#### Briefly describe your proposal.

On the documentation page https://fundamental-ngx.netlify.app/#/core/home with the older versions dropdown menu list, the older fundamental-ngx versions links are not working for versions bellow 0.37.1. 

#### If this is a bug, please provide steps for reproducing it.

Go to the https://fundamental-ngx.netlify.app/#/core/home page and try to switch to older version number like 0.36.2. 
Result is message "Site Not Found": https://624793d2f1d02d000925c339--fundamental-ngx.netlify.app/

Similar result is on https://sap.github.io/fundamental-ngx/#/core/home with the link to 0.36.2 be: https://635720a7e34ffc00087a288e--fundamental-ngx.netlify.app/

**Comment by droshev** [comment]
it is due to netlify limitations https://www.netlify.com/blog/automated-deploy-cleanup-and-new-deploy-retention-policies/
