### ISSUE TITLE
[Sourcing][Responsiveness]: Platform Multi combobox is not responsive with its input field

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9353]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
If multi combobox option has lengthy text then the width of the dropdown is increasing more than its input field.
This is causing responsive issue

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 14
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
This is replicable on https://sap.github.io/fundamental-ngx/#/platform/multi-combobox#data-source 
Please check attached recording

#### Is there anything else we should know?

[Screen Recording 2023-02-08 at 8.43.50 AM.mov.zip](https://github.com/SAP/fundamental-ngx/files/10681488/Screen.Recording.2023-02-08.at.8.43.50.AM.mov.zip)
This is a major blocker for guided sourcing and is a customer commitment

**Comment by droshev** [comment]
@I543348 The menu takes the visible space so more data is shown. The popover doesn't go beyond the visible space. 

What do you expect to see?

**Comment by droshev** [comment]
Closing the issue as there is no response.

**Comment by I543348** [comment]
Thanks @droshev , I think after your confirmation , i see the width of the popover can go beyond input box so that data can be displayed.
Thanks for confirmation , we are good here.
