### ISSUE TITLE
[Sourcing]: fdp tree table on check of parent checkbox , child checkboxes should also be checked

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9355]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
On check of parent row's checkbox , the child rows should also automatically get checked until and unless user unchecks few of children rows

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 13
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
reproducible on https://sap.github.io/fundamental-ngx/#/platform/table#tree 

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table#tree
#### Is there anything else we should know?

This is a development blocker for guided sourcing 
priority is A
Expecting a property from fdp-table which can be used to decide whether on check of "parent" row child rows should be checked or not - may be a boolean field.

**Comment by droshev** [comment]
This can be handled on the application side

**Comment by I543348** [comment]
Hi @droshev , the guided sourcing tables can support until 2000 rows of data , hence it would be tedious way to make a check on each row's children and recursively check the child rows.
It might make our application slow.

Hence it would be great if it can be handled from F-NGX platform tree table side?

**Comment by fkolar** [comment]
@mikerodonnell89 , @droshev, Let's agree before hand on the solution as this is cheaper than PR. 

When analysing this, there needs to be two changes:

**1) Platform Table level** 
  * this `checked`, it should work similar way as `expanded`
  * `_calculateCheckedAll`, I am not how much this method consider if this tree table
  * Table should have also a selection state - but this would be another issue
  * This is going to be handled similar way as `_toggleExpandableTableRow`
  * In `_toggleMultiSelectRow()`: if we are dealign with a tree mark existing parents + children that are already loaded in Table
  
**2) Application** 
  * Application should use checked state and and make sure any new node, when expanded you we fetch lazily new notes are  also checked.

**Comment by I543348** [comment]
> @mikerodonnell89 , @droshev, Let's agree before hand on the solution as this is cheaper than PR ;-)
> 
> I checked this one and there needs to be two type of changes:
> 
> **1) Platform Table level**
> 
> * this `checked`, it should work similar way as `expanded`
> * `_calculateCheckedAll`, I am not sure how much this method consider if this tree table
> * Table should have also a selection state - but this would be another issue
> * This is going to be handled similar way as `_toggleExpandableTableRow`
>   ***CHANGE:**  In `_toggleMultiSelectRow()`: if we are dealign with a tree mark (checked=true/false) existing parents + children that are already loaded in Table
> * The selection state is kept private, DataSource has no way to tell the Table if something is selected.
> * When something is selected table emits even so app can do something, but app has no way tell tell the app to select something
> * Instead of keeping all these information on the level of TableRow which is internal, probably better to work with e.g.:
>   -> `Item` -> `BaseTableItem` - `TreeItem` types and with this we would be able to keep the state. We already have this something similar on the level of comboxbox (OptionItem - SelectableOptionItem)
> 
> **2) Application**
> 
> * Application should use checked state and and make sure for any new nodes, when expanded  nodes are  also checked.
> * I will extend existing tree-table example
> 
> I assume when we do a search, it needs to reset existing checked state.

@fkolar  regarding point 2 on application - does this mean application has to check if parent checkbox is checked and based on that set the "checked" to true for child checkboxes?

**Comment by fkolar** [comment]
We discussed this and above describe solution is right way to go. 

1) We are going to introduce `TreeItem` interface and extends existing logic 
 * We can do this in more generic way to have `TableItem`, which can be also used in regular table (we will have the same problem)

```ts
public interface Partial<TableItem<T = any>> {
  checked: boolean;
  value: T;
    ...
  // All what we have on the TableRow and does not bellongs to TREE

}

public interface TreeItem extends  TableItem {
  expanded: boolean
  expandable: boolean
   children: Array< TreeItem >;
   ...

```

}



2) It needs to also support current behavior and work directly with the date and only if we are dealing with `TreeItem` or `TableItem` we can apply this logic. 
3) We should also introduce different types of behavior :
 * When state changes also include child or parents (when child is checked, also check parent) - This should be default behavior. 
 * When state changes don't do anything. 

3) Once checked and based on the Type, in the table level iterate over existing data and toggle checked state (child->parent, parent-> child)

4) On the app level it will require to use this interface. This will also allow application to pass initial checked/unchecked state

**Comment by fkolar** [comment]
Update: We are going to simplify this and we will use existing Type TableRow, which needs to be converted to interface, and then we will be able to expose this interface to the DataSource.

**Comment by I543348** [comment]
This issue can be taken up in next sprint , we are fine with this.
@droshev 

Thanks,
Anusha
