### ISSUE TITLE
[Sourcing][Dev blocker]: Not able to programmatically set the page number in tableState.page.currentPage

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9356]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Developers should be able to programatically set page numbers during infinite scroll or pagination , this is needed to refresh the table for actions delete , add rows etc 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 13 
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
tableState.page.currentPage is a readonly and developers dont have control to programatically set page number for some actions on table

#### Is there anything else we should know?
This is a development blocker for guided sourcing
Priority: A

**Comment by N1XUS** [comment]
Hello @I543348. Please refer to `setCurrentPage` method of the `TableComponent`

**Comment by Ankit0025-cmd** [comment]
The page is getting changed as expected.
