### ISSUE TITLE
[Reopen][Sourcing][Responsiveness]: fdp table toolbar is not responsive

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9361]
#### Is this a bug, enhancement, or feature request?
enhancement

#### Briefly describe your proposal.
1) With 200% zoom , If there are many action buttons , then the buttons are overflowing out of container
~~2) With 400% zoom, even if there are only 2 action buttons with search the buttons are overflowing out of container~~
**we only need to account for 200% zoom**

Expected result: The buttons should wrap to next line in the toolbar container

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 13 
core / platform: 0.35.x

#### If this is a bug, please provide steps for reproducing it.
Replicable on https://sap.github.io/fundamental-ngx/#/platform/table 

try adding few more actions buttons say about 4-5 buttons and try zooming to 200%
<img width="1785" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/88182358/217776406-c738249c-3186-4227-af16-c0a00f085d4d.png">

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table 

#### Is there anything else we should know?
This is crticial for DTAG customer for guided sourcing
priority B

**Comment by droshev** [comment]
we need to expose it as part of that toolbar

**Comment by mikerodonnell89** [comment]
We only need to account for 200% zoom and 320px screen width

**Comment by I543348** [comment]
> We only need to account for 200% zoom and 320px screen width

Hi @mikerodonnell89 ,
we checked the NGX site in 320px and found that even in 200% zoom , the table toolbar is not working.
Could you please reopen this issue?

<img width="955" alt="Screenshot 2023-04-13 at 1 28 09 PM" src="https://user-images.githubusercontent.com/88182358/231705732-d01d370e-56d0-4a4d-b65a-7f6e409dc37c.png">

**Comment by I543348** [comment]
Based on experts inputs, this needs to be reopened as we need to support 320px CSS width and currently its not working.
cc: @mikerodonnell89

**Comment by g-cheishvili** [comment]
https://sap.github.io/fundamental-ngx/#/cdk/breakpoint
