### ISSUE TITLE
fd-popover right-end placement is off

### ISSUE THREAD

**Issue by ZsDeak-SAP** [SAP/fundamental-ngx#9363]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Popover placement doesn't seem to be right for 'right-end'

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest (0.39.0rc36)

#### If this is a bug, please provide steps for reproducing it.
I've found it using the documentation examples for [popover placement](https://fundamental-ngx.netlify.app/#/core/popover#placement)

#### Please provide relevant source code if applicable.
```html
 <div class="docs-popover-element">
        <fd-popover placement="right-end" [noArrow]="false" title="right-end">
            <fd-popover-control>
                <button fd-button glyph="navigation-right-arrow"></button>
            </fd-popover-control>
            <fd-popover-body>
                <fd-avatar [circle]="true" style="margin: 1rem" size="xl" glyph="group"></fd-avatar>
            </fd-popover-body>
        </fd-popover>
    </div>
```
#### Is there anything else we should know?
![image](https://user-images.githubusercontent.com/115458873/218033540-94098b91-d1ec-448d-985e-37ed35e1b6c3.png)

**Comment by droshev** [comment]
@IB002 Can you check whether this will be fixed with the latest changes in Horizon?

**Comment by IB002** [comment]
Issue has beeb fixed with latest changes.

<img width="276" alt="Screenshot 2023-08-18 at 3 12 00 PM" src="https://github.com/SAP/fundamental-ngx/assets/132930816/45c52655-0bd1-45c4-8f3f-3ed9651d51f5">
