### ISSUE TITLE
Multi-input selectedChange event does not trigger

### ISSUE THREAD

**Issue by Slevunio** [SAP/fundamental-ngx#9365]
#### Is this a bug, enhancement, or feature request?
BUG

#### Briefly describe your proposal.
-

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 14.2.0
Fundamental-ngx/core: 0.38.2

#### If this is a bug, please provide steps for reproducing it.
1. Open any of multi-input stackblitz code examples
2. In html template pin to (selectedChange) event e.g.:
```
<fd-multi-input
  [mobile]="true"
  [dropdownValues]="values"
  [showAllButton]="false"
  placeholder="Search here..."
  [mobileConfig]="secondConfig"
  [(ngModel)]="selectedValues"
  (selectedChange)="onObjectsSelectionChange($event)"
></fd-multi-input>
```
3. In ts file implement "onObjectsSelectionChange" and log event in console to check if it is triggered e.g.:
`  public onObjectsSelectionChange($event) {
    console.log($event);
  }`
4. Open multi input element
5. Click on any element (not on checkbox, just on element)
6. See that popover closes and chosen element token is visible in input field
7. See that event was not logged in console -> (selectedChange) event was not triggered

#### Please provide relevant source code if applicable.
html:
```
<fd-multi-input
  [mobile]="true"
  [dropdownValues]="values"
  [showAllButton]="false"
  placeholder="Search here..."
  [mobileConfig]="secondConfig"
  [(ngModel)]="selectedValues"
  (selectedChange)="onObjectsSelectionChange($event)"
></fd-multi-input>
```
ts:
```
public onObjectsSelectionChange($event) {
    console.log($event);
}
```
#### Is there anything else we should know?
You can find me on Slack:
Adam Karlowicz

**Comment by mikerodonnell89** [comment]
Unable to recreate this with the current version
