### ISSUE TITLE
icons and css variables

### ISSUE THREAD

**Issue by mmshh89** [SAP/fundamental-ngx#9369]
##I install @fundamental-ngx/core version 0.38.3,

##I used a standard list from @fundamental-ngx/core document in "https://sap.github.io/fundamental-ngx/#/core/list" that contains navigationIndicator and also element are clickable but no icon and no style for active elements available, what's wrong?

##when i console the elements there is no definition for css variables( like : "var(--sapList_SelectionBorderColor)").

**Comment by N1XUS** [comment]
Hello @mmshh89.
Please clarify, have you added @fundamental-ngx/core with `ng add` command?
