### ISSUE TITLE
[Sourcing] fdp-table row index

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9370]
#### Is this a bug, enhancement, or feature request?

enhancement

#### Briefly describe your proposal.

Currently, we use fdp-table-cell to get the get row data but we cannot get row index in fdp-table. It would be helpful if we could get row index like using ng-template. 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: 13
core / platform: 0.35.x

#### If this is a bug, please provide steps for reproducing it.

N/A

#### Please provide relevant source code if applicable.
Previous: 
<img width="516" alt="Screenshot 2023-02-11 at 10 26 16 PM" src="https://user-images.githubusercontent.com/22842279/218296526-af06bb36-27e3-4d52-b84a-21b1851b0422.png">

Current: 
<img width="322" alt="Screenshot 2023-02-11 at 10 26 56 PM" src="https://user-images.githubusercontent.com/22842279/218296550-b83bacd4-6995-4251-adb2-4edc5aa55191.png">

**Comment by I543348** [comment]
Expectation is to expose a variable from fdp-table-cell for keeping track of row index

**Comment by mikerodonnell89** [comment]
@CSENoni 

One way to get this would be to access the table rows from the main table component's viewchild:

`import { TableComponent } from '@fundamental-ngx/platform/table';`

```
@ViewChild(TableComponent)
table: TableComponent;
```

```
this.table.tableRows.forEach((row, index) => {
    console.log(row);
    console.log(index);
});
```

Is that satisfactory? This would give all rows for the table. I think we could also expose functions that would also return only the visible rows if that is desired

**Comment by I543348** [comment]
Hi @mikerodonnell89 , we usually have use cases where we need to use index in html page, dynamically.

**Comment by droshev** [comment]
@I543348 Can't you amend your data source directly and you won't need to render this as a custom html?

**Comment by I543348** [comment]
This is not available in 0.39.0 latest fixes , need to be reopened ; 
<img width="1792" alt="Screenshot 2023-03-06 at 2 51 52 PM" src="https://user-images.githubusercontent.com/88182358/223069188-8143aeea-52cd-42cf-bde6-173eec1be701.png">

**Comment by droshev** [comment]
@I543348 you can follow the PR and see that it is part of 0.39.1-rc.0

**Comment by rayansailani** [comment]
verified as working on stackblitz with v0.39.10-rc.0. Thanks.
