### ISSUE TITLE
Pagination Component - No pages provided in the Pagination object; we cannot provide paging

### ISSUE THREAD

**Issue by alvachien** [SAP/fundamental-ngx#938]
#### Is this a bug, enhancement, or feature request?
It's a bug.

#### Briefly describe your proposal.
There is one error in Console, 'No pages provided in the Pagination object; we cannot provide paging'. It can be observed from the official example https://sap.github.io/fundamental-ngx/pagination by setting totalItems to 0.

It is a wrong behavior. In the real world, data was fetched from the backend, and before the data received, the totalItems is zero or even undefined. the component itself shall not show such error in console.

**Comment by MattL75** [comment]
I agree - this is wrong, this is a very common usecase and shouldn't throw an error.
