### ISSUE TITLE
[Sourcing][Dev Blocker]: Sorting property in fdp-multicombobox, fdp-combobox and fdp-select is required

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#9387]
**Is this a bug, enhancement, or feature request?**
This is an Enhancement which is of high priority.

**Briefly describe your proposal.**
We are making use of above mentioned components for all the dropdown fields in our application where the sorting of DataSource is required. But this functionality is missing for these components. Kindly let us know time line by when we can expect this functionality to be implemented.

**Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)**
Angular 14 and Fundamental NGX 0.38.2

**If this is a bug, please provide steps for reproducing it.**
This is not a BUG

**Please provide relevant source code if applicable.
Is there anything else we should know?**

This is a development blocker for guided sourcing
Priority: A

**Comment by droshev** [comment]
@sahanaN123 Can't you sort the data the way you want before passing it to the component?

**Comment by I543348** [comment]
@sahanaN123  request you to please revert back.

**Comment by fkolar** [comment]
**This issue should be closed. t**he same reply as #9388. Comboboxes are meant to deal with large dataset, You cant rely on in-memory sorting. It needs already sorted before you pass the data to the component. API call. We need to separate between things that belongs to front-end and things that belongs to backend

@sahanaN123 , @droshev
