### ISSUE TITLE
[Sourcing][Dev blocker]: fdp tree table with sort/ grouping is not sorting / grouping rows

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9388]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The tree table along with its child rows should be sorted/ grouped when user selects any column for ASC/ DESC or group by column

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
angular 13
core /platform: 0.35.x

#### If this is a bug, please provide steps for reproducing it.
replicable from NGX examples

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-mammnh?file=src%2Fapp%2Fplatform-table-tree-example.component.html,src%2Fapp%2Fplatform-table-tree-example.component.ts

#### Is there anything else we should know?
This is a blocker for guided sourcing priority A

**Comment by mikerodonnell89** [comment]
I think this is an issue on your end. I notice that nowhere in your typescript is the sort function actually called. See the typescript in this example: https://sap.github.io/fundamental-ngx/#/platform/table

```
        // apply sorting
        if (tableState?.sortBy) {
            this.items = this.sort(tableState);
        }
```

**Comment by yixuan-liu** [comment]
> I think this is an issue on your end. I notice that nowhere in your typescript is the sort function actually called. See the typescript in this example: https://sap.github.io/fundamental-ngx/#/platform/table
> 
> ```
>         // apply sorting
>         if (tableState?.sortBy) {
>             this.items = this.sort(tableState);
>         }
> ```

Sorting does not occur for children nodes of a parent. Also, grouping does not work as of now for tree table

**Comment by I543348** [comment]
thats true , sort happens only for parent nodes when we call sort function inside fetch.
same applies to grouping as well.
Request you to please check.

Thanks.

**Comment by mikerodonnell89** [comment]
Also you are correct that grouping does not work with tree tables, I think we will need to consider that a feature request. This should have been documented in the tree table example, which I think incorrectly implies that tree tables are groupable by saying drag and drop is not possible with `[groupable]` amongst other inputs

**Comment by I543348** [comment]
Hi @droshev , please find inputs from Georg on this issue -

Regarding sorting in trees, I was working on a design concept for this several years ago. Long story short, tree sorting should result in sorting every level within its parent. But there are different kind of trees, in some cases the structure need to stay. So to generalize it beyond a special use cases, sorting would need to offer 3 different options:
Sort leaves only
Sort nodes only
Both (Standard behavior)
 
 
Example:
A
A1
A2
A3
B
B1
B2
B3
C
C1
C2
C3
 
Sorting descending, leaves only would lead to.
A
A3
A2
A1
B
B3
B2
B1
C
C3
C2
C1
 
Sorting descending, node only would lead to:
C
C1
C2
C3
B
B1
B2
B3
A
A1
A2
A3
 
Sorting descending, both would lead to:
C
C3
C2
C1
B
B3
B2
B1
A
A3
A2
A1
 
Is this something you can do on your side? Or is this rather application logic?
 
Does this help?
 
Grouping:
I wonder what is the use-case for grouping in trees? Tree nodes are already a kind of “grouping”…
Can anyone give some more insight on what you would like to achieve with grouping a tree?
 
 ____________________
Please let me know in case of any other information required.
thanks.

**Comment by fkolar** [comment]
I think,  this issue should be **closed**. It does not make sense to do this heavy tree lifting on the the client side. When you  SORT the date became irrelevant as you sort on the subset what was retrieved to the UI. 

The API has more native possibility retrieve the sorted data. its all about UX and performance.  When you will have a table starting A,B, C, and when I click on sort I expect to see Z, Y,. What is the added value to have C, B, A? 

The same goes with grouping. We can discuss to have some in-memory  data adapter that can do this, but your use-case is a enterprise you should not be relaying on the in-memory operations for this use-case. 

@I543348 , @droshev

**Comment by fkolar** [comment]
> @fkolar , we contacted UX experts and the comment / inputs from there can be found in [#9388 (comment)](https://github.com/SAP/fundamental-ngx/issues/9388#issuecomment-1461874524)

Yes, I have read it.

**UX:** 
But to that: When on the UX level we say, it needs to provide 3 different kinds of sorting. This should trigger question back. How do you invoke these 3 sorting type, Pop-up, existing action menu items ?

**Data Handling:**
 * When dealing with large data-set you dont really want Table to do the heavy lifting or to do this all in-memory (in browser)

**Comment by I543348** [comment]
Hi @fkolar , we dont really need all 3 sorting types : just the standard behaviour should work for our use case 
Both (Standard behavior) -> sort nodes first and then leafs inside nodes.

Please let me know if any queries.

**Comment by droshev** [comment]
@I543348  how about Frank's point:
**_When dealing with large data-set you dont really want Table to do the heavy lifting or to do this all in-memory (in browser)_**

**Comment by fkolar** [comment]
@I543348 


**In-memory data manipulation**
* If we really want to do all this in the client side, then the way to do this is implement this functionality in DataSource. For this reason table passes a `TableState` and this is the best place to decide if requests need to go to the backend or just perform some in-memory operation. 

```ts
fetch(tableState: TableState): void {
}
```

For more detail you can checkout `TableComponnet._listenToTableStateChanges`, where here it listen to state changes and triggers `fetch()`

**Comment by droshev** [comment]
> Hi @droshev , as @fkolar requested for our use case - the 3rd option from UX holds good. ie., sorting both parent node and child nodes inside it.
> 
> So we would still expect this from NGX table.

that request should be part of the backend especially when it comes to huge data volume.
