### ISSUE TITLE
Enhancement:Value Help dialog box should support customisation of headers

### ISSUE THREAD

**Issue by ranjithPRao** [SAP/fundamental-ngx#9389]
Is this a bug, enhancement, or feature request?
Enhancement

 Briefly describe your proposal.

The Value Help dialog box does not allow to customise the below headers.
![valueHelpDialog](https://user-images.githubusercontent.com/116718610/221484618-7722a876-a4cf-4b45-8b6e-69538c0fad40.png)

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@fundamental-ngx/core": "0.38
@fundamental-ngx/platform": "0.38

If this is a bug, please provide steps for reproducing it.
NA

Please provide relevant source code if applicable.

_<fdp-value-help-dialog     #vhd     fdCompact     dialogTitle="Simple value help dialog"     uniqueKey="id"     tokenViewField="name"     [formatToken]="formatTokenFn"     [dataSource]="dataSource" (valueChange)="valueChange($event)" headerId="fdp-vhd-header-1" >     <fdp-value-help-dialog-filter         *ngFor="let filter of filters; index as i"         [main]="i < 2"         [key]="filter.key"         [label]="filter.label" [advanced]="i !== 0" ></fdp-value-help-dialog-filter> </fdp-value-help-dialog>_

Is there anything else we should know?

We use this component for various use cases and hence it would be good if we are able to customise this header values.

**Comment by droshev** [comment]
this is a generated dialog and doesn't offer any custom content.

**Comment by mikerodonnell89** [comment]
Reopening as this is a potential future enhancement

**Comment by ranjithPRao** [comment]
Thanks a lot @mikerodonnell89 for taking it up. updated the screenshot with the latest(there is one more header above checkbox which says "item" and needs customisation)

**Comment by mikerodonnell89** [comment]
Regarding the custom headers, here is a potential workaround that utilizes some custom translations.

1. First make sure you are importing the i18n module in the `module.ts` where you are using the value help dialog in (or globally)
```import { I18nModule } from '@fundamental-ngx/i18n';```
```
    imports: [
        I18nModule,
        ...
    ],
```
2. Next, in the typescript for your component where you are using the value help dialog component, you can overwrite default hardcoded values for the dialog like so:
```
export class PlatformVhdBasicExampleComponent {
    languagePatch: FdLanguagePatch = {
        platformVHD: {
            selectTabDisplayCountLabel: 'Custom Count ({{ count }})',
            selectedEmptyLabel: 'No Items Selected',
            selectedAndConditionLabel: 'Selected Items'
        }
    }
   ...
}
```
3. Finally, in your template, you'll add `[fdPatchLanguage]="languagePatch"` to the dialog:
```
<fdp-value-help-dialog
    #vhd
    fdCompact
    dialogTitle="Simple value help dialog"
    uniqueKey="id"
    tokenViewField="name"
    [formatToken]="formatTokenFn"
    [dataSource]="dataSource"
    (valueChange)="valueChange($event)"
    headerId="fdp-vhd-header-1"
    [fdPatchLanguage]="languagePatch" <!-- here -->
>
...
</fdp-value-help-dialog>
```

Here's some more information on how that works: https://fundamental-ngx.netlify.app/#/core/i18n#language-customization

hope this helps!
