### ISSUE TITLE
[sourcing] `Fdp-table` Filter By dialog, elements are not aligned

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9392]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
On `Fdp-table`'s Filter By dialog, elements are not aligned

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.38.2

#### If this is a bug, please provide steps for reproducing it.
Check doc, fdp-table,  Filtering by multiple columns:
https://sap.github.io/fundamental-ngx/#/platform/table#filterable

<img width="839" alt="image" src="https://user-images.githubusercontent.com/7035787/219178831-02a2eebd-64c5-463b-b2cb-ada12100bf8d.png">

**Comment by droshev** [comment]
it seems to be fixed 
<img width="818" alt="Screenshot 2023-03-02 at 9 34 27 AM" src="https://user-images.githubusercontent.com/4380815/222458346-b67712bf-f304-4a9f-b342-f19025845d01.png">

**Comment by I543348** [comment]
This is fixed and tested under https://sap.github.io/fundamental-ngx/#/platform/table#p13-table-filter
