### ISSUE TITLE
Platform tree table drag and drop improvements

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#9421]
Currently you can only drag and drop tree table rows into other rows - they cannot be dropped next to (i.e. before or after). We need both this behavior as well as a way to make this visually distinct. I think the ideas around `@Input() replaceMode` behavior can be expanded upon to make this happen.

**Comment by fkolar** [comment]
While back when I was implementing this behavior, I extracted all this into directive to handle this. 


```html
<ng-template #rowTemplate let-rowData let-even="event" let-odd="odd" let-rowIndex="rowIndex"
             let-nestingLevel="nestingLevel" let-colsToRender="colsToRender">


    <tr #rowElement dtDraggableRow [dndRowIndex]="rowIndex" [dndRowData]="rowData"
        [dropIntoEnabled]="(rowData.metaId && dataMeta[rowData.metaId]) ? dataMeta[rowData.metaId].dropIntoEnabled :
            ((!rowData.metaId && dataMeta[rowData]) ? dataMeta[rowData].dropIntoEnabled : false)"
        class="dt-body-row"
        ....
        [ngClass]="{'dt-even-row': even, 'dt-odd-row': odd,
            ...
            'dt-row-draggable':....,>

        <ng-template ngFor let-col [ngForOf]="colsToRender" let-colIndex="index" [ngForTrackBy]="trackByIndex">
             ....
        </ng-template>
    </tr>
</ng-template>

```


This directive `dtDragableRow`, aggregated all the behaviour related to D2D. 
https://github.wdf.sap.corp/core-ui-platform/AribaCoreUI/blob/v11.0.17/packages/components/src/widgets/datatable2/directives/dt-draggable-row.directive.ts

* was checking the direction so I can apply correct styles
* Drag/Drop position. - inBetween, Before, After, Into
* Apply proper styles to create a effect and visualise better the drop zone
