### ISSUE TITLE
User Menu and dialog in the shellbar

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#9432]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.

Create user menu and settings dialog component which will be added to the shellbar. It should look like [this](https://fundamental-styles.netlify.app/?path=/docs/components-user-menu--default).

- [x] Can we create it in platform and make it driven based on data (like wizard generator)?
- [x] Can we offer/include the theming selector (maybe integrate with the existing Theming functionality). The application should be able to specify the subset of the supported themes.
- [x] Document it with some examples

Out of scope: storing runtime the selected theme and being used in other applications.

**Comment by N1XUS** [comment]
User menu is out of scope of this task and should be implemented as a separate issue.
Items to implement:

- [ ] Text component for form generator (maybe some sort of a switch between readonly/edit modes);
- [ ] Nested groups support with different type of view (list, tabs, form group, etc);
- [ ] List component for form generator with variety of settings for the UI part
