### ISSUE TITLE
Value help dialog column width issue

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#9439]
Note the column width in the screenshot below. Ignore the arrows pointing to "Items (30)" and "Selected Items and Conditions (3)", those are from a separate feature request #9389 

![image](https://user-images.githubusercontent.com/116718610/218992105-fdb8335d-b322-4eb6-ac39-85b658c83d20.png)

**Comment by ranjithPRao** [comment]
The Documentation and StackBlitz can be found for the component at : https://sap.github.io/fundamental-ngx/#/platform/value-help-dialog

To check the component in Ariba landscape, you can follow below steps:
https://svcgcpdev01ss.lab-us.gcpint.ariba.com/Sourcing/Main?realm=petrobras
click on the button "Test Central"
under User textBox enter the username  - customersupportadmin and hit "Set User" button
once logged in, you can open any of the titles shown in "Recently Viewed" section of the UI, it should take to the page where the component is present
