### ISSUE TITLE
Drop Down List box missing a black line on top 

### ISSUE THREAD

**Issue by amaranthHe** [SAP/fundamental-ngx#945]
#### Is this a bug, enhancement, or feature request?
bug 
#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
"fundamental-ngx": "0.3.3", 
#### If this is a bug, please provide steps for reproducing it.
This only happens on an Apple Macbook 
1. go to https://cockpit.stage.faros.kyma.cx  
2. click sidebar link "Extensibility", check the "Actionable Statuses" drop-down button.  The top line is missing

#### Please provide relevant source code if applicable.
<fd-popover #statusSelector id="xf-installations-select-status_filter" placement="bottom-end"
  [isDropdown]="true" [compact]="false">
  {{'XF.INSTALLATIONS.STATUS_FILTER.'+statusFilter | translate}}
  <fd-popover-body>
    <fd-menu>
      <ul fd-menu-list>
        <li fd-menu-item (click)="statusSelector.close();statusFilter = 'ACTIVE'">
          {{'XF.INSTALLATIONS.STATUS_FILTER.ACTIVE' | translate}}</li>
        <li fd-menu-item (click)="statusSelector.close();statusFilter = 'ALL'">
          {{'XF.INSTALLATIONS.STATUS_FILTER.ALL' | translate}}</li>
      </ul>
    </fd-menu>
  </fd-popover-body>
</fd-popover>

**Comment by khodayar** [comment]
possible fix in the css style :
`.fd-dropdown__control::after {
  margin-right: 1px;
  width: 30px;
  height: 30px;
}`

**Comment by InnaAtanasova** [comment]
We are currently at Version 0.9.0. I am not able to reproduce the issue on our side. Could you update the version and let us know if the issue still exists.

**Comment by khodayar** [comment]
thank you !
