### ISSUE TITLE
Multi Input example broken

### ISSUE THREAD

**Issue by littleamigo** [SAP/fundamental-ngx#9452]
#### Is this a bug, enhancement, or feature request?
Bug

![image](https://user-images.githubusercontent.com/33327256/221409809-18d6d647-6311-4d9b-9a65-ee715aa3eed6.png)

#### Briefly describe your proposal.
The example should work

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v0.38.2

#### If this is a bug, please provide steps for reproducing it.
Open the example from the screenshot.
Choose some states from the dropdown list
Remove some states via the 'x'
Open up the dropdown list again
See the differences between what is show in the dropdown list, the select control and the 'Form Selected Item:' list.

**Comment by littleamigo** [comment]
@droshev

**Comment by littleamigo** [comment]
Yes, @N1XUS the example is from https://fundamental-ngx.netlify.app/#/platform/multi-input#reactive

**Comment by N1XUS** [comment]
OK. Then it's been fixed already in this pr https://github.com/SAP/fundamental-ngx/pull/9390. Closing.
