### ISSUE TITLE
[Sourcing][Responsivess]: value help dialog is not responsive in 200%

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9454]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Please check the recording for 200% browser zoom , the value help dialog content is not visible.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
ANgular 15
core / platform: 0.38.2

#### If this is a bug, please provide steps for reproducing it.

https://user-images.githubusercontent.com/88182358/221477142-65aa4caa-2d42-49d2-8cd9-66e91004b547.mov

#### Is there anything else we should know?
This is needed for customer commitment for guided sourcing.

**Comment by mikerodonnell89** [comment]
The accessibility team states we need to support text resizing up to 200% which can be accomplished by resizing the browser to zoom 200%, and we need to accommodate screen widths at 320px. So we do need to make some changes to this dialog but not at 400%
