### ISSUE TITLE
bug(platform): two popovers shown for platform form field control

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-ngx#9461]
#### Is this a bug, enhancement, or feature request?

Bug.

#### Briefly describe your proposal.

Two popovers shown for Platform Form Field control. 

<img width="555" alt="image" src="https://user-images.githubusercontent.com/20265336/221961935-8faac01f-0fca-4b27-bb55-acaedb356768.png">

#### Steps to reproduce

1. Open branching wizard generator
2. Click on "next step" to trigger validation, get error on form field
3. Click on select to open dropdown
4. Click on the first item, somewhere in the middle - get error message popover on top of select's dropdown

**Comment by droshev** [comment]
@IB002 Can you analyze further the issue?
