### ISSUE TITLE
[Sourcing][Dev blocker] `<fdp-table>`: Need support to add customized pop up for table column header 

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#9462]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
As of now for `<fdp-table>` component,  if we enable sorting, grouping or freezing column on certain table column header, by default a pop up will open if user clicks on the header. However, as of now we are unable to provide more customized clickable action to the header. There is no existing out such as a `<ng-template>` provided to achieve so.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest release `v0.38.2`

#### Is there anything else we should know?
Please see attached below our own table column header customization. Our current app behavior has a menu pop-up button next to the column header. If user clicks on it, it will also open the sorting, grouping or freezing column pop-up menu provided from F-NGX. The optimum solution would be to combine those two pop-up in one, if possible.

![Screenshot 2023-02-28 at 11 52 02 AM](https://user-images.githubusercontent.com/22454655/221965257-43e4015c-cd34-42e1-b915-9ad95a20ec06.png)

![Screenshot 2023-02-28 at 11 52 14 AM](https://user-images.githubusercontent.com/22454655/221965291-6cf08250-7fca-446c-b004-02363a8b7906.png)

**Comment by fkolar** [comment]
Instead proving several popups there needs to a way how to register custom actions with this existing popup. You should be able to provide information where they appear, BEFORE/AFTER, FIRST, LAST etc. 

Also there needs to be some constraints here and some guidelines, I think the best way is take it back to UX design to set some initial requirements, maybe you want separate default action from custom ones with some **HR** ?, 
@yixuan-liu

**Comment by I543348** [comment]
Thanks @fkolar , I will trigger an email to our UX designers looping you , and will take it ahead.

**Comment by I543348** [comment]
mail sent to Guided sourcing UX team , will update the thread once we get response.

**Comment by fkolar** [comment]
@I543348 , When reading this more closely, do we really need a popup? When we can add custom actions? Sort, Filter, are custom action of the Table Toolbar.

**Comment by I543348** [comment]
Hi @fkolar , I think it should be a "popover" and not a "popup".
let us wait for UX team's inputs for further steps.

**Comment by fkolar** [comment]
I think this issue should be closed. These popovers is not way of fiori. Just like Just like sort, group and filter are in the toolbar they are not in the popover. I think these action needs to be added as additional actions to the table.

**Comment by I543348** [comment]
Hi @fkolar , Today morning I connected with UX team and we can expect some inputs from them on this query soon, Request you to please keep the issue open till we hear back from UX.

Thanks.

**Comment by I543348** [comment]
Hi @fkolar , we discussed with UX team and below is their proposal-
there should be only one popover , the standard table related actions should be shown first in the menu list and followed by contextual ones for table.


example:
Sort
Group
Freeze
Edit item
Delete item

**Comment by fkolar** [comment]
Looking at the code. This would be helpful to add a flexibility to existing popover. @mikerodonnell89 , @droshev 



```html
<fdp-column name="price"  key="price.value" >
     <fdp-column-action  *fdpColumnActionDef="let column" 
              (click)="customAction(column.key)" 
               icon="some glyph"
              label="my Custom Action Label"
              (keydown.enter)="onKeyDown (column.key)">                                
      </fdp-column-action>   
      
     <fdp-table-header *fdpHeaderCellDef>Price</fdp-table-header>
     <fdp-table-cell *fdpCellDef="let item">
            {{item.price.value}} {{item.price.currency}}
     </fdp-table-cell>
</fdp-column>
```

**Comment by droshev** [comment]
@N1XUS Can you take a look this request? Thanks
