### ISSUE TITLE
[Sourcing]`<fdp-table>`: Need simultaneous support for D&D with [sortable], [groupable], [filterable] columns and [freezeColumnsTo] enabled

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#9463]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
It is written in latest doc that `Drag & Drop (D&D)` is not supported when `[sortable]`, `[groupable]`, `[filterable]` columns and `[freezeColumnsTo]` table properties are enabled. We'd like to have simultaneous support for both functionalities.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Latest release `v0.38.2`

**Comment by fkolar** [comment]
@mikerodonnell89, any idea why we have this restriction? I think coming back to our discussion about in memory sorting and group NOT in TABLE but on the application side in the DataSource. It should be possible no? 

- When  `[sortable], [groupable], [filterable] columns and [freezeColumnsTo]` this is enabled we can allow D&D, which will trigger fetch (TableState)
- DataSource will reorganize these data internally and Table will be reinitialised 

We need to also look at the performance. .

**Comment by mikerodonnell89** [comment]
> @mikerodonnell89, any idea why we have this restriction? I think coming back to our discussion about in memory sorting and group NOT in TABLE but on the application side in the DataSource. It should be possible no?
> 
> * When  `[sortable], [groupable], [filterable] columns and [freezeColumnsTo]` this is enabled we can allow D&D, which will trigger fetch (TableState)

I am not sure why this restriction is in place to begin with, however I think [this PR](https://github.com/SAP/fundamental-ngx/pull/9712) may be all that is needed to open up the possibility of using DnD and sorting etc together.

Sorting, filtering, etc. logic is provided by the application developer, so they should handle any API calls that are required for this if they want the sorting to apply beyond just the front end. Similar to how the drag and drop event must be utilized by the application developer to make any backend adjustments they may need.
