### ISSUE TITLE
[Sourcing][x]fdp-table scroll position to be set during infinite scroll

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9464]
#### Is this a bug, enhancement, or feature request?
Enhancement request

#### Briefly describe your proposal.
When there are more than 100+ rows in a fdp-table , the user adds/deletes the row then the inifinite scroll position should stay at the row where the changes was made.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core /platform: 0.38.2

**Comment by droshev** [comment]
to be evaluated once we merge the [virtual scroll ](https://github.com/SAP/fundamental-ngx/pull/9419)

**Comment by droshev** [comment]
@I543348 the virtual scroll feature has been merged. Can you re-assess the issue?

**Comment by I543348** [comment]
Sure @droshev , we are currently working on to hook virtual scrolling feature in Guided Sourcing , we will update it soon on this.
Thanks.

**Comment by droshev** [comment]
@I543348 Could you provide the exact steps how to reproduce the issue?

**Comment by I543348** [comment]
Hi @droshev , this has been raised as "Enhancement" so there aren't any steps as such.
The request is that -
Suppose a table has 25 rows, the user adds a new row to this table.
The table scroll has to be moved to that newly added row's position.

**Comment by droshev** [comment]
@I543348 can you describe the steps of adding a new row? Do you go to another page, or open a dialog, etc...?

**Comment by I543348** [comment]
Hi @droshev ,
Adding a new item could be from a new page or new popover with form.
However, when the new item gets updated in table data source and if the table has fixed "bodyheight" then the scroll position of the table has to be positioned such that , the item that gets added last has to be in a viewport.

Please let me know if this clarifies the query.
Thanks.

**Comment by droshev** [comment]
@I543348 I think in that case when you navigate somewhere you would need to preserve the state of the table. Then when you come back, you set it to that position.

**Comment by fkolar** [comment]
Closing issue, as we discussed this for a while now:
- To preserve fully a state you need to use TableRow
- To preserve the scroll position you can use solution that I provided [in the other thread](https://github.com/fkolar?tab=repositories)
