### ISSUE TITLE
[Sourcing][Low priority] fdp-table support "pop-in" mode for desktop applications (row-view)

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9469]
#### Is this a bug, enhancement, or feature request?
Enhancement request

#### Briefly describe your proposal.
When there are more than 10-15 columns in a fdp-table , the user should be able to view One default row should be divided to 2 rows, main and secondary. First(main) one is interactive, second has to be used only to display rest of information.
Just like how it is currently implemented in "core" table under pop-in mode example https://sap.github.io/fundamental-ngx/#/core/table#table-pop-in 

This will give user a row-view experience than column view experience.
This is low priority.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core/platform: 0.38.2

#### Is there anything else we should know?
The UX design from Guided sourcing https://www.figma.com/file/59kyXvRSiGSVQs6FzIwvYe/Row-view-%2F-column-view?node-id=0%3A1&t=cjPzfZeHAN2lJz03-0

**Comment by droshev** [comment]
we offer pop-in for platform table - you can see an example here https://fundamental-ngx.netlify.app/#/platform/table#responsive-columns
