### ISSUE TITLE
[Sourcing] Doc Website API page is not loading

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9473]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
N/A

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.39

#### If this is a bug, please provide steps for reproducing it.
Both my local and  https://sap.github.io/ cannot load any component's API page.

local:
![CleanShot 2023-03-03 at 10 39 10@2x](https://user-images.githubusercontent.com/7035787/222801983-e472fbfc-856d-4141-8a06-7c52923d7786.png)

https://sap.github.io/ 
![CleanShot 2023-03-03 at 10 45 25@2x](https://user-images.githubusercontent.com/7035787/222802043-d3149390-e3e5-463d-b3a9-1fa89bb71306.png)

**Comment by I543348** [comment]
This is too critical to move ahead for any NGX components, please help.

**Comment by mikerodonnell89** [comment]
I'll have to investigate why this is happening on this doc site but it appears to be working at the docs for our latest RC here: https://fundamental-ngx.netlify.app/#/platform/table/api

**Comment by droshev** [comment]
@I543348 the issue has been addressed. Use https://fundamental-ngx.netlify.app/#/core/home for now.
Once we trigger a release github pages will be fixed too
