### ISSUE TITLE
[Sourcing] Irrelevant options in filter dropdown for the string datatype.

### ISSUE THREAD

**Issue by Ankit0025-cmd** [SAP/fundamental-ngx#9501]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
Currently the dropdown in the filter dialog has options such as "greater than", "less than", "greater than or equal to" and "less than or equal to". These four options seems irrelevant for a string datatype.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular Version: 15.2.2 Fundamental Version: 0.39.1-rc.4
#### If this is a bug, please provide steps for reproducing it.
Just press the dropdown from the p-13 filter dialog box.

**Comment by mikerodonnell89** [comment]
Greater than, less than etc. is still a useful comparison for some strings. See here: https://javascript.info/comparison#string-comparison
