### ISSUE TITLE
[Sourcing] <fdp-table> Filter datepicker is not aligned

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9503]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
In platform table, the datetimepicker in p13n filter is not aligned with dropdown.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest

The issues are also reproducible in previous version which we are currently using:
"fundamental-styles": "0.27.0",
"@fundamental-ngx/core": "0.39.1-rc.4",
"@fundamental-ngx/platform": "0.39.1-rc.4"

#### If this is a bug, please provide steps for reproducing it.

https://user-images.githubusercontent.com/22842279/224403786-e4a01d9c-4453-4d5d-833e-95eba7146625.mov

**Comment by mikerodonnell89** [comment]
Coming from fundamental-styles:
<img width="1525" alt="Screenshot 2023-03-10 at 12 27 02 PM" src="https://user-images.githubusercontent.com/2471874/224408122-77b0e7c9-bad9-4392-8a06-e8a7dcb18e16.png">

@InnaAtanasova should input group have this margin? Datepicker uses fd-input-group, should datepicker override this margin? Or should the selects to the left of the datepicker have this as well?
