### ISSUE TITLE
The latest version 0.39.0 is not working on Safari, iPad, iphone

### ISSUE THREAD

**Issue by nikola-miletic** [SAP/fundamental-ngx#9515]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
After upgrade from 0.38.6 to 0.39.0 components (such as select, inputs) are not working. The issue exist on official documentation as well
https://sap.github.io/fundamental-ngx/#/core/home

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.39.0 

#### If this is a bug, please provide steps for reproducing it.

1. Open Safari
2. Go to https://sap.github.io/fundamental-ngx/#/core/home
3. Try to choose lib(Core is default) from dropdown 
4. Notice that dropdown is not working
5. Check the developer console
6. See errors
<img width="1674" alt="error" src="https://user-images.githubusercontent.com/43137517/224705723-b245c6df-d25a-4698-ac36-bb59e2189315.png">

<img width="1677" alt="error1" src="https://user-images.githubusercontent.com/43137517/224712517-8f47a6c0-f689-4aba-afff-5f24095bbe6c.png">

**Comment by N1XUS** [comment]
![image](https://user-images.githubusercontent.com/6586561/225588076-795a8154-cc57-47fb-9435-c99146bd8e50.png)
Safari 16.4. Works fine.

**Comment by nikola-miletic** [comment]
@N1XUS I have tested this on:

Safari: 16.3
<img width="285" alt="Screenshot 2023-03-16 at 13 02 26" src="https://user-images.githubusercontent.com/43137517/225611113-6ba042bb-9b9c-4e1a-820a-895e54de7974.png">

and iOS: 16.3.1

**Comment by g-cheishvili** [comment]
Safari 16.3 does not support CSSStyleSheet. I will replace that with ordinary styles for now
