### ISSUE TITLE
[Sourcing][Dev blocker] <fdp-approval-flow> Unable to set custom status

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9518]
#### Is this a bug, enhancement, or feature request?
feature request
#### Briefly describe your proposal.
Back then, for platform approval flow, we can freely set our own status for approval node. However, with current adoption, we notice that these statuses do not show anymore in the approval node:

Previous version:

![Screenshot 2023-03-14 at 11 05 00 AM](https://user-images.githubusercontent.com/22842279/225097723-3dff329f-32d9-4b94-83c2-19128a750399.png)

Now:

![Screenshot 2023-03-14 at 11 06 54 AM](https://user-images.githubusercontent.com/22842279/225097886-74ee3b0a-691e-4d8e-8f11-4e5aff19a902.png)

Looking at https://github.com/SAP/fundamental-ngx/blob/fefac1929380f482a9786b09513779548281256c/libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.html, we see that we can only use 4 types of statuses now if it is not duedate compared to previous version where we can freely use our own status. This is a blocker for our Guided Sourcing project. Could you revert or provide any feature for us to use our own status like we had for previous version?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15.2.0
fundamental-ngx/core: 0.39.1-rc.4
fundamental-ngx/platform": 0.39.1-rc.4

#### Please provide relevant source code if applicable.

![Screenshot 2023-03-14 at 11 18 29 AM](https://user-images.githubusercontent.com/22842279/225100630-85ef1ef2-4403-4593-90e1-e4a3d98e4c57.png)

**Comment by I543348** [comment]
@skaquib123  can you please check and confirm on this issue ?
This is a high priority issue.

**Comment by skaquib123** [comment]
Hey @CSENoni,  You have to use preset strings like "approved", "in progress", "not started" and "rejected".  any other  string value will not be accepted. 

@droshev please let me know if we can change the preset string values of approval flow status.

**Comment by I543348** [comment]
@CSENoni can you please confirm on these changes if working or not?

cc: @skaquib123

**Comment by fkolar** [comment]
@skaquib123, how we are doing on this? Also you also update and describe what are you planning to do on this ticket? The truth is, applications will have custom statuses depending on the business process and these four is a good start but it should be extensible.

**Comment by fkolar** [comment]
Since this can be usecase for other LOBs and teams we need to provide a way to pass in custom statuses

Solution:

1) Inside approval flow Introduce new `ChildContent` template that Application can use to implement their own statuses
  * here App needs to also take care of i18n
2) Change `ApprovalNode.status`  to suport also a `string`
