### ISSUE TITLE
[sourcing]: Expand/Collapse All buttons should be on the left most of the toolbar and need tooltips

### ISSUE THREAD

**Issue by I835291** [SAP/fundamental-ngx#9519]
#### Add Expand/Collapse All buttons. The buttons are shown in the middle like the following:

<img width="900" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/86618211/225108290-0f211f81-dc27-43e9-b749-89f96873d540.png">

I've tried to move to the left most position, it looks much nicer:

![expandCollpaseAll](https://user-images.githubusercontent.com/86618211/225108408-d9aec1ed-de81-4965-b72b-3fc73c7f5bf1.png)

Please also add tooltips for these buttons.

**Comment by I543348** [comment]
This is a little high priority as we plan to deliver these areas to customer.
Can you please prioritize this issue for march 2023?
Thanks,


cc: @droshev , @mikerodonnell89

**Comment by I543348** [comment]
Issue logged for tooltips:https://github.com/SAP/fundamental-ngx/issues/9551

**Comment by I543348** [comment]
Regarding placement of expand all / collapse all buttons , we contacted UX designers and as per fiori standard , the ask is to keep these buttons before sort button 
https://experience.sap.com/internal/fiori-design-web/tree-toolbar/ 

cc: @droshev , @fkolar , @mikerodonnell89

**Comment by omband** [comment]
From the first picture I see that that the "centre" of 2 tables is also not same in the same page. 
So the centre buttons won't be vertically aligned in a single view.

**Comment by fkolar** [comment]
@I543348 , On the picture you provided you say you like the left most position, but on the UX design link you sent it is positioned to the right .

What is the final expectation?

* Move These button from center to the right
* Keep these button before sort buttons?

**Comment by I543348** [comment]
Hi @fkolar , as per our last discussion , we will need these buttons before sort buttons (point 2)
Since I cannot modify the description of the issue on behalf of @I835291 I am commented here.

**Comment by droshev** [comment]
@I543348 The buttons are in the middle as the toolbar has few other features(title information with the number of items on the left and search on the right)
https://fundamental-ngx.netlify.app/#/platform/table#tree
If you pass the proper titling, which will help the accessibility, you won't see an empty gap.

**Comment by I543348** [comment]
Hi @droshev , 
Thanks for the updates, 
Our use case in table has many action buttons on the right as in screenshot, also as per UX experts , we would like to have an option to make it place as in https://experience.sap.com/internal/fiori-design-web/tree-toolbar/ with or without title.
Please help here.

<img width="1710" alt="Screenshot 2023-03-23 at 12 37 46 PM" src="https://user-images.githubusercontent.com/88182358/227129362-ae51961f-c5fa-47d5-8360-6d84610920ed.png">


cc: @fkolar , @I835291

**Comment by fkolar** [comment]
If you need it on the right why:

1. dont you use  - `showExpandCollapseButtons` = false
2. use `fdp-table-toolbar-actions` to pass before sort your actions
 * In this case it woudl be 
 
```html
 <fdp-table-toolbar-actions>
            <fdp-button glyph="expand-all" (click)="refToTable.expandAll()"></fdp-button>
            <fdp-button glyph="collapse-all" (click)="refToTable..collapseAll()"></fdp-button>
            <fd-toolbar-spacer></fd-toolbar-spacer> 
</fdp-table-toolbar-actions>
```

**Comment by I543348** [comment]
Yes this works perfectly fine !
Thanks @fkolar

**Comment by fkolar** [comment]
Great. Also I think @droshev , this issue is ready to be closed. There are no father plan to change the data-table. Unless the whole UX is revised  by central UX and this case applies to all.
