### ISSUE TITLE
[Sourcing] Column with empty label appears on p13 dialog

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9520]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
There is a use case when we have a column with empty label to perform multi-actions (represented as three dots, buttons, or symbol...). However, it is shown in a column panel with empty title like this:

<img width="561" alt="Screenshot 2023-03-14 at 8 31 22 PM" src="https://user-images.githubusercontent.com/22842279/225199093-f6ec8e3e-faba-4fd6-86f4-a72cd0b3d5be.png">

We have [filterable]="false" or [sortable]="false" to make the column not visible on filter or sort panel. Can we have something similar to make that not visible in column panel? Or can we have some property to act as alt label in column panel?

Sample: https://angular-wtufa9.stackblitz.io

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15.2.0
fundamental-ngx/core: 0.39.1-rc.4 or latest
fundamental-ngx/platform": 0.39.1-rc.4 or latest

#### Please provide relevant source code if applicable.
Please refer: https://stackblitz.com/edit/angular-4hdtve?file=src%2Fapp%2Fplatform-table-p13-columns-example.component.html
#### Is there anything else we should know?
UX member does not recommend to have a label for "action" type column, so we don't have workaround for this case.

**Comment by I543348** [comment]
better to expose a property using which developers can set whether column visibility is enabled for this or no.
If no then the column always stays and cannot be hidden

**Comment by droshev** [comment]
For this custom scenario you can use the core table

**Comment by I543348** [comment]
We need something like this which is already working for "row navigation" table example
https://angular-ehic3v.stackblitz.io 

please check.
Thanks.

**Comment by fkolar** [comment]
Temporary before this feature is introduced, you can use in the application following trick. 

1. `@ViewChild` to bind p13n dialog
2. Update getTableColumns method
3. You can use following code:

```ts
ngAfterViewInit(): void {
    const p13d = this.p13Dialog as any;
    const tableColumns = this.p13Dialog?._table.getTableColumns() || [];
    p13d._getTableColumns = () => {
        const cols = tableColumns.filter((c) => c.label.length !== 0 );
        if (cols) {
            return cols;
        }
        return tableColumns
    }
}
```

See pictures:
<img width="556" alt="Screenshot 2023-03-21 at 14 57 27" src="https://user-images.githubusercontent.com/17149942/226700156-71623680-ae51-417c-910a-7796ca1f3943.png">
<img width="1041" alt="Screenshot 2023-03-21 at 14 57 53" src="https://user-images.githubusercontent.com/17149942/226700169-5375d5a7-df6d-4c28-8c24-b9d7514032e6.png">

**Comment by fkolar** [comment]
For the real fix, we have to introduce new  TableColumn' bindings `hideP13` or `skipP13n` 

```html
<fdp-table #table [dataSource]="source">
    <fdp-column name="name" key="name" label="Name" [hideP13n]="true"> </fdp-column>
</fdp-table>
```

@mikerodonnell89 , @droshev  - Any better name? Suggestions are welcomed.

**Comment by fkolar** [comment]
There should be no issue, it still a javascript at the end. . One thing I recommend is to mark this code as deprecated so you wont forget to change it once the real fix is introduced. 


```ts

/**
 * Workaround to remove columns with empty labels out of the p13 dialog
* 
 * @deprecated till https://github.com/SAP/fundamental-ngx/issues/9520 is fixed
 */
ngAfterViewInit(): void {
    const p13d = this.p13Dialog as any;
    const tableColumns = this.p13Dialog?._table.getTableColumns() || [];
    p13d._getTableColumns = () => {
        const cols = tableColumns.filter((c) => c.label.length !== 0 );
        if (cols) {
            return cols;
        }
        return tableColumns
    }
}
```

Regardless of production code, you do want to use this and test it in your test environment first. 
**Trust but always verify** !

**Comment by I543348** [comment]
@fkolar while we are good with this workaround , i think we are still looking for a proper fix for this issue, but this can be of low priority now coz of workaround.

Thank so much for helping us.

**Comment by fkolar** [comment]
We are ok with the workaround but we need to introduce better and more systematic way of configuring this. This situation happens for everyone. Beside already provided fix which is more like a backup solution we can:

1) Look into the p13n-dialog component and its sub-component COLUMN if we can pass and configure something these
2) Introduce a Service (adapter) which is going to be responsible for populating p13 dialog content, Default behavior would be to take all visible column but on the application / component level we should be able to provide our our logic by injecting custom behavior

**Comment by fkolar** [comment]
We should change the priority to low since the workaound is provided.

**Comment by I543348** [comment]
for columns with label="" (empty) , when we set [disableP13n]=true, those columns are now not listed in p13 dialog , however when the user hides other columns from p13, the columns with  [disableP13n]=true are not appearing in the table 
@fkolar  can you please check?

**Comment by fkolar** [comment]
@I543348, I checked and it works. 

I have this setup:

```
<fdp-table #table [dataSource]="source">
    <fdp-table-toolbar title="Order Items"></fdp-table-toolbar>

    <fdp-column name="name" key="name" label="Name" [disableP13n]="true"> </fdp-column>

    <fdp-column name="description" key="description" label="Description"> </fdp-column>

    <fdp-column name="price" key="price.value" label="Price"> </fdp-column>

    <fdp-column name="verified" key="verified" label="Verified" [disableP13n]="true"> </fdp-column>

    <fdp-column name="status" key="status" label="Status" [disableP13n]="true"> </fdp-column>

    <fdp-column name="action" key="" label="" [disableP13n]="true">
        <fdp-table-cell *fdpCellDef="let item">
            <fdp-button label="Action"></fdp-button>
        </fdp-table-cell>
    </fdp-column>
</fdp-table>
<fdp-table-p13-dialog [table]="table"></fdp-table-p13-dialog>
```

All colums are present in the table + they are not present in the P13 dialog
<img width="762" alt="Screenshot 2023-04-26 at 19 47 15" src="https://user-images.githubusercontent.com/17149942/234660548-3e07b479-f7df-4a5f-98e7-97654008afba.png">
<img width="1225" alt="Screenshot 2023-04-26 at 19 47 10" src="https://user-images.githubusercontent.com/17149942/234660558-225cc075-33e0-4d19-958f-c90f7cca489a.png">


Please let me know what else I am missing so I can replicate this..
