### ISSUE TITLE
popover borders are not displayed properly

### ISSUE THREAD

**Issue by arif-mohammad786** [SAP/fundamental-ngx#9521]
BUG

popover borders are not displayed properly.

angular version - 15.1.1
fundamental ngx version - 0.38.2

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/74425047/225244047-643a7f06-b84d-469f-9447-024d00b9bbb3.png)
![Screenshot (94)](https://user-images.githubusercontent.com/74425047/225244130-e8715d82-4a79-4481-981a-c1672c7e8b31.png)

when we have scrollable items inside popover body it has two scroll bars and border at the bottom of popover disappears.

**Comment by bpan4** [comment]
Hi @arif-mohammad786 ! Is it possible to recreate this bug on stackblitz with a similar markup? We are unable to reproduce the same bug on our side.

**Comment by arif-mohammad786** [comment]
https://stackblitz.com/edit/angular-4r7pmm?file=src%2Fapp%2Fpopover-example.component.html,src%2Fapp%2Fpopover-example.component.scss


![image](https://user-images.githubusercontent.com/74425047/231403264-fa753156-7ecc-473a-a685-469587bc5460.png)

**Comment by droshev** [comment]
@arif-mohammad786 if you remove the custom overwriting of `.popover-dropdown` max-height the issue is solved.

**Comment by bpan4** [comment]
Hello @arif-mohammad786 , please find the proposed solution here: https://stackblitz.com/edit/angular-4r7pmm-yzts2b?file=src%2Fapp%2Fpopover-example.component.html,src%2Fapp%2Fpopover-example.component.scss

The key point is to apply `[additionalBodyClass]` to the `fd-popover` component, then apply the custom height of the scrollable item and modify the display of `fd-popover__wrapper` under the defined class in the scss file.
The outer scroll of the `fd-popover` component was applied for accessibility purposes, but may be suppressed using `[additionalBodyClass]`.
