### ISSUE TITLE
[Sourcing][Low][P4] <fdp-table> Custom header does not work with p13 dialog without label

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9526]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
In some tables, we would not like to use label on **fdp-column**. Instead, we customize our header in **fdp-table-header**. However, If we use it instead, p13 dialog will not work. It will be resolved when we put label in **fdp-column**, but is it expected behavior since we have to put two label in two places?
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
fundamental-ngx/core: 0.39.1-rc.4 or latest
fundamental-ngx/platform": 0.39.1-rc.4 or latest

#### If this is a bug, please provide steps for reproducing it.

Using the code below with first column using customized header, p13 dialog will not working properly. It will be resolved when we put some label in **fdp-column**.

#### Please provide relevant source code if applicable.
```
<fdp-table #table [dataSource]="source">
    <fdp-table-toolbar title="Order Items"></fdp-table-toolbar>

    <fdp-column name="name" key="name">
        <fdp-table-header *fdpHeaderCellDef>Name</fdp-table-header>
    </fdp-column>

    <fdp-column name="description" key="description" label="Description"> </fdp-column>

    <fdp-column name="price" key="price.value" label="Price"> </fdp-column>

    <fdp-column name="verified" key="verified" label="Verified"> </fdp-column>

    <fdp-column name="status" key="status" label="Status"> </fdp-column>
</fdp-table>

<!-- Connect P13 Dialog to the table -->
<fdp-table-p13-dialog [table]="table"></fdp-table-p13-dialog>
```

**Comment by I543348** [comment]
can be low priority

**Comment by droshev** [comment]
for that I would advise you to use the core table instead.

**Comment by I543348** [comment]
Hi @droshev  and team, If the NGX library gives an option for developers to use "custom header" template then the existing P13 dialog needs to be compatible with it

**Comment by mikerodonnell89** [comment]
Correct, you should use the name label in this scenario. The string provided here will also be what displays in the p13 dialog:
```
<fdp-column name="name" key="name" label="Name from Label Attribute" [filterable]="true" [dataType]="dataTypeEnum.STRING">
    <fdp-table-header *fdpHeaderCellDef>Name from fdp-table-header</fdp-table-header>
</fdp-column>
```
![Screenshot 2023-11-07 at 5 03 50 PM](https://github.com/SAP/fundamental-ngx/assets/2471874/f487af55-6949-4272-a606-dafb60f111ad)
