### ISSUE TITLE
[Sourcing] When using `[dataType]="dataTypeEnum.DATE"` in `fdp-table` column, items within the filter dialog appear misaligned

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9532]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
When using `[dataType]="dataTypeEnum.DATE"` in `fdp-table` column, items within the filter dialog appear misaligned

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
    "@fundamental-ngx/core": "0.39.1-rc.4",
    "@fundamental-ngx/platform": "0.39.1-rc.4",
   "fundamental-styles": "0.27.0",
```

#### If this is a bug, please provide steps for reproducing it.
Check this stackblitz:
https://stackblitz.com/edit/angular-zh8xgl?file=src/main.ts

I set `Description` column as DATE type. Open Filter Dialog, select Description. And the date picker is not aligned.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/7035787/225784447-e4478b76-7453-4c1a-ae4e-aa75a024c88b.png">

#### Please provide relevant source code if applicable.
Please check stackblitz.

**Comment by I543348** [comment]
this is a duplicate of https://github.com/SAP/fundamental-ngx/issues/9503

**Comment by oscargong** [comment]
hi Anusha, thanks for pointing out. I will close this one.
