### ISSUE TITLE
[Sourcing] fdp-table: Column unfreeze heading label on table to be changed 

### ISSUE THREAD

**Issue by rayansailani** [SAP/fundamental-ngx#9555]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

The header unfreeze clomun label shows label 'HeaderMenuUnfreeze' without spaces. This needs to be changed. 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/54993789/226512977-5bd35cf7-9d93-4998-b1ef-af645f6c8bb9.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
fngx - v0.39-rc19

#### If this is a bug, please provide steps for reproducing it.

https://angular-kg6bss.stackblitz.io

**Comment by fkolar** [comment]
This should be easy fix, as there is missing translation for this new key in libs/i18n/src/lib/languages

**Comment by fkolar** [comment]
Resolved by #9502

<img width="292" alt="Screenshot 2023-03-28 at 8 05 34" src="https://user-images.githubusercontent.com/17149942/228143569-b6eb59f6-5f88-4d23-a860-3730ed361fcd.png">
