### ISSUE TITLE
[Sourcing][Accessibility] fd-list accessibility issues

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9556]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1) Redundant word "group" is being read when traversing through fd-list items
2) Also checkbox checked state is not read by screenreader 
~~instead "?" is read~~ [fixed](https://github.com/SAP/fundamental-styles/pull/4518), needs fundamental-styles version update
3) please make sure the word "list item" is also read for every li in ul

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core / platform: 0.39.1-rc-5

#### If this is a bug, please provide steps for reproducing it.
This is replicable on https://sap.github.io/fundamental-ngx/#/core/list#selection 
<img width="1792" alt="Screenshot 2023-03-21 at 2 48 27 PM" src="https://user-images.githubusercontent.com/88182358/226563677-c4e4e9ca-06d2-4d6a-bfe7-a48325d69468.png">

**Comment by fkolar** [comment]
Can you also review similar case on the SAPUI5 side. this is accessibility proven framework, and if you find similar behavior there, then you can reach out to UX what is correct way of handling this. 

According to this it seems standard behavior even there. 

https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListSelection

Shell we close this issue?

**Comment by I543348** [comment]
Hi @fkolar , please check this recording where "list item" and "not selected or selected" is being read out for sapui5 list but not for NGX list

https://user-images.githubusercontent.com/88182358/228515630-09dd5335-52fa-4b56-aa07-e5d12f619085.mov
hence issue still has to be fixed

**Comment by fkolar** [comment]
@I543348, the video is not showing up. 

1) The GROUP is there in both  - so its not really an issue right? 
2) We still have problem with #2

**Comment by I543348** [comment]
Thanks @fkolar as discsused , the word "list item" should also be read when compared to sapui5 list 
added the 3rd point in issue

3) please make sure the word "list item" is also read for every li in ul

**Comment by fkolar** [comment]
Solution:

-> selection labels in order it can indicate that item is selected or not selected, instead of having the ??? there

**Comment by mikerodonnell89** [comment]
> 1. Redundant word "group" is being read when traversing through fd-list items

This is default behavior when traversing an html list using VoiceOver. See below:

https://user-images.githubusercontent.com/2471874/230180822-94f21d27-259a-4232-8afb-aff0d1211ef6.mov

**Comment by I543348** [comment]
Thanks @mikerodonnell89  we should always follow w3.org standards for accessibility 
please refer to my recording for comparing w3 lists with NGX list for issue 1


https://user-images.githubusercontent.com/88182358/230283611-7780bde0-598c-443e-89ce-ed1c05d1bb3f.mov

**Comment by mikerodonnell89** [comment]
> Thanks @mikerodonnell89 we should always follow w3.org standards for accessibility : https://www.w3.org/WAI/tutorials/page-structure/content/#unordered-list please refer to my recording for comparing w3 lists with NGX list for issue 1


> Author

This is not comparable, since this list on w3 is not tab indexed or keyboard navigable like the fd-list is.

**Comment by I543348** [comment]
Actually if you use JAWS linear reading mode , then each and every text and control would be navigable using keyboard and that is when this issue will be comparable.

**Comment by mikerodonnell89** [comment]
> Actually if you use JAWS linear reading mode , then each and every text and control would be navigable using keyboard and that is when this issue will be comparable.

Which issue are you referring to specifically? I think this comment may be on the wrong issue

**Comment by mikerodonnell89** [comment]
See my comment here regarding the screenreader saying "list item": https://github.com/SAP/fundamental-ngx/issues/9608#issuecomment-1542577517

**Comment by I543348** [comment]
> > Actually if you use JAWS linear reading mode , then each and every text and control would be navigable using keyboard and that is when this issue will be comparable.
> 
> Which issue are you referring to specifically? I think this comment may be on the wrong issue as your original post for the issue pertains to mac's VoiceOver

@mikerodonnell89  i am referring to issue number 1 from the description -
Redundant word "group" is being read when traversing through fd-list items

Thanks.

**Comment by mikerodonnell89** [comment]
> > > Actually if you use JAWS linear reading mode , then each and every text and control would be navigable using keyboard and that is when this issue will be comparable.
> > 
> > 
> > Which issue are you referring to specifically? I think this comment may be on the wrong issue as your original post for the issue pertains to mac's VoiceOver
> 
> @mikerodonnell89 i am referring to issue number 1 from the description - Redundant word "group" is being read when traversing through fd-list items
> 
> Thanks.

Mac's voiceover always announces "group" on list items that have a tabindex. We can hack our way around this but that would be breaking away from the typical behavior of the screenreader.  See UI5 behaving the same way

**Comment by I543348** [comment]
Checked on https://sap.github.io/fundamental-ngx/#/core/list#simple
Issue 1 , 2 and 3  still replicable
All of these are reported by Guided sourcing customers

**Comment by droshev** [comment]
@mikerodonnell89 Can you double check?

**Comment by mikerodonnell89** [comment]
@I543348 please test on https://fundamental-ngx.netlify.com/#/core/home

**Comment by I543348** [comment]
Thanks @mikerodonnell89 , This works fine in netlify link , we will confirm once used from the application as well.
