### ISSUE TITLE
[Sourcing] <fdp-table> UI issue between non-selectable and selectable checkbox in single selection mode

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9562]
#### Is this a bug, enhancement, or feature request?
enhancement
#### Briefly describe your proposal.
For multiple selection mode, if the checkbox is not selectable, the checkbox will not display. However, for single selection, there is no easy way to know which row is non-selectable until we click on the checkbox. It may confuse users.

Here is an example. The checkbox in first row is non-selectable but looks similar to the second row.
<img width="763" alt="Screenshot 2023-03-21 at 3 58 42 PM" src="https://user-images.githubusercontent.com/22842279/226760442-ba18403b-c653-4bd8-9a51-21846f2f7e83.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
"@fundamental-ngx/core": "0.39.1-rc.5" or latest,
"@fundamental-ngx/platform": "0.39.1-rc.5" or latest,
"fundamental-styles": "0.27.0" or latest
#### If this is a bug, please provide steps for reproducing it.
Please refer to the link below.
#### Please provide relevant source code if applicable.
Please refer to: https://stackblitz.com/edit/angular-lwmrle?file=src%2Fapp%2Fplatform-table-multiple-row-selection-example.component.html,src%2Fapp%2Fplatform-table-multiple-row-selection-example.component.ts

**Comment by fkolar** [comment]
There are two things I see, selection only happens on the level of 1st column (we should have behavior for the selection like UI5 so you can click on any column to select a row -Row , RowSelector , Row only)

**Comment by CSENoni** [comment]
@fkolar Thank you for the answer. I brought the issue to UX. I will inform you when I get feedback from him.

**Comment by CSENoni** [comment]
Change it to 'enhancement' because there is actually no doc or design solution for this case.

Hi @fkolar , after discussion with UX team, we can make a small improvement:

- The cursor is changed when moving between selectable and non-selectable row (behavior like multiple row selections in table when there is an disabled row).
- Highlight should not be displayed when user is interacting with entire row for non-selectable row. The current behavior now only does that if interacting with the first column (single mode selection checkbox and even in multiple mode).

https://user-images.githubusercontent.com/22842279/229576255-6fdd7e79-32f9-47e0-b4f6-260621e2c99b.mov

**Comment by CSENoni** [comment]
Close issue since this is not needed because current current Ui is according to Ui5 design.
