### ISSUE TITLE
[Sourcing] fdp-table: expand all / collapse all buttons needs to be moved after separator and match other button styles

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9589]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
As per latest specs , the expand all / collapse all icon buttons have to be moved after "vertical separator" and match the look and feel of that of "sort" button

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core / platform: 0.39.2

#### If this is a bug, please provide steps for reproducing it.
Latest button spec: https://experience.sap.com/internal/fiori-design-web/tree-toolbar/
<img width="1197" alt="Screenshot 2023-03-27 at 2 26 05 PM" src="https://user-images.githubusercontent.com/88182358/227897089-160b90eb-db57-4b2f-9938-a69f5d5b5fc8.png">

**Comment by fkolar** [comment]
It seems the workaround that we provided is not sufficient anymore. This spec was recently updated and this grouping of actions is not new way to go. I think  it is safe to move these two buttons to the sort, filter,.. group. 

@droshev

**Comment by fkolar** [comment]
PR - #9591

**Comment by I543348** [comment]
works fine, thanks.
