### ISSUE TITLE
[Sourcing] content visible above search field in Table columns visibility p-13 dialog box

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#9609]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The scrollable element should not be visible above the search input field

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "0.39.1-rc.20",
"@fundamental-ngx/platform": "0.39.1-rc.20"
"@angular/core": "15.2.0"

#### If this is a bug, please provide steps for reproducing it.
Add multiple columns to the table until the scroll appear in Table columns visibility p-13 dialog. Attached the screenshot for reference

<img width="1792" alt="Screenshot 2023-03-30 at 9 07 32 PM" src="https://user-images.githubusercontent.com/71999626/228889624-1f5d4dea-aebb-4ef1-a1e4-ef0001c39068.png">

**Comment by mikerodonnell89** [comment]
This was fixed with #9770 

https://github.com/SAP/fundamental-ngx/assets/2471874/c1f63f58-8882-4c30-9961-f6d15b41ed8d

**Comment by Sayandeep-123** [comment]
Yes, it is working as expected.
