### ISSUE TITLE
Checkbox component: It is difficult to find out a 'disabled' checkbox is 'Checked' or not

### ISSUE THREAD

**Issue by alvachien** [SAP/fundamental-ngx#962]
#### Is this a bug, enhancement, or feature request?
It's a bug.

#### Briefly describe your proposal.
As you can find in the official example: https://sap.github.io/fundamental-ngx/checkbox
When the checkbox is disabled, it is difficult to find out that the checkbox is Checked or not. The color in CSS shall be adjusted.

A similar case happened in Radio button.

**Comment by droshev** [comment]
@LeoT7508 @jeannewalters what do you think?

**Comment by LeoT7508** [comment]
@alvachien @droshev 

The styling for this is wrong, reference the design sheet for details: https://zpl.io/2Gokp8m

@jeannewalters 

Correct me if Im wrong but if the checkbox or radio button is disabled that doesn't mean the label should change too. The label doesn't need to have any opacity or color change, it should just be the interactive element. Thoughts?

**Comment by droshev** [comment]
This issue will be fixed once we adopt the latest version of `fundamental-styles`. This can be done once the self-contained effort is done. Mode details: https://github.com/SAP/fundamental-styles/issues/136

**Comment by InnaAtanasova** [comment]
<img width="408" alt="Screen Shot 2019-11-13 at 4 15 16 PM" src="https://user-images.githubusercontent.com/39598672/68804931-d631b480-0630-11ea-8a3c-17223642c129.png">
<img width="436" alt="Screen Shot 2019-11-13 at 4 14 51 PM" src="https://user-images.githubusercontent.com/39598672/68804933-d631b480-0630-11ea-80d0-e29d0c904f36.png">

This is the latest state in Fundamental-Styles.

**Comment by JKMarkowski** [comment]
Will be fixed with newest fundamental-styles forms adaptation.
