### ISSUE TITLE
OData support?

### ISSUE THREAD

**Issue by alvachien** [SAP/fundamental-ngx#963]
#### Is this a bug, enhancement, or feature request?
It's a feature request;

#### Briefly describe your proposal.
I understand it is a huge topic, and it cannot be easily achieved.
However, the biggest advantage of the controls in SAPUI5/OpenUI5 library is built-in support for OData. As the fundamental library coming from SAP too, is it possible to support OData?

**Comment by droshev** [comment]
@alvachien can you give some examples?

**Comment by alvachien** [comment]
@droshev 
If you look at repository https://github.com/SAP/openui5
you can find there are lots of codes supporting odata, 
If you are talking about source code example, please refer to https://github.com/SAP/openui5/blob/d8997c98207cc664d4efa18371f06e397be8588b/src/sap.ui.core/src/sap/ui/model/odata/v2/ODataAnnotations.js

Again, it's a feature request and it heavily relies on the position of Fundamental libraries. If the fundamental library just a UI controls like Angular Material https://github.com/angular/components
it is just fine that this repository just provides UI controls implementation based on Angular framework.

**Comment by droshev** [comment]
We don't plan this for the moment
