### ISSUE TITLE
[Sourcing][Dev blocker] <fdp-table> Some issues with freeze columns

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9642]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
There are two issues:
- Issue 1: if we have a inline link (or even button) in a table with scrollbar, first click always does not trigger and set the scrollbar to the left. After a few clicks on the same link, it is fine, but it will be replicated in another link:

https://user-images.githubusercontent.com/22842279/230691629-341759ee-471b-4385-88aa-98a5d20f50d9.mov

In more complex scenario, when we have inline link to open a popover (if successfully), any event triggered to close popover will also give us the same behavior like above (set scrollbar to left).

It is working fine with table without freeze column.

- Issue 2: even though we set width for every column, depending on window size, when we try to for example update table from empty state, it will create a white space in freeze column position until we hover the cursor somewhere on the table. In this case, setting fixed width for parent element will solve the issue, but we believe this has a huge limitation. Can you fix it?

https://user-images.githubusercontent.com/22842279/230692034-eb7e086c-27cb-47ec-9796-cf0abfd0ef27.mov

In our application, we sometimes is switching from empty to having data in table by adding/deleting item, and we could not set fixed width for parent element.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15.2.0
"@fundamental-ngx/core": "0.39.1-rc.26",
"@fundamental-ngx/platform": "0.39.1-rc.26"

#### If this is a bug, please provide steps for reproducing it.

Please refer the link below:

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-udar4q?file=src%2Fapp%2Fplatform-table-freezable-example.component.html,src%2Fapp%2Fplatform-table-freezable-example.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by I543348** [comment]
@CSENoni can you pls validate the fix?
Thanks.

**Comment by CSENoni** [comment]
It is working fine now. Thanks!
