### ISSUE TITLE
[fdp-multi-combobox][Sourcing][Dev blocker]:Unable to enter numeric values using numeric keypad

### ISSUE THREAD

**Issue by bharathSivaSAP** [SAP/fundamental-ngx#9653]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Try entering a numeric value from using number keypad in the keyboard, the entered numbers are not reflecting in the multi combobox.
But we are able to enter numbers via the main keypad.
The issue is with fdp-multi-combobox component.
this is similar to https://github.com/SAP/fundamental-ngx/issues/9254 where fixed the same kind of issue with fdp-combobox.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 15.2.0
core / platform : 0.39.1-rc.26

#### If this is a bug, please provide steps for reproducing it.

- Access https://stackblitz.com/edit/angular-5zebky-9iedzt?file=src%2Fapp%2Fcombobox-example.component.html,src%2Fapp%2Fcombobox-example.component.ts
- Try entering a numeric value from using number keypad.
- Number is not entered instead first item from the dropdown is getting highlighted.

#### Please provide relevant source code if applicable.
Please refer to https://stackblitz.com/edit/angular-5zebky-9iedzt?file=src%2Fapp%2Fcombobox-example.component.html,src%2Fapp%2Fcombobox-example.component.ts

#### Is there anything else we should know?
This is critical to guided sourcing

**Comment by N1XUS** [comment]
The issue is not with the numpad but with clearing the input field if no search text occurrence found in the suggestions

**Comment by bharathSivaSAP** [comment]
Hi @N1XUS It works for fdp-combobox but not for fdp-multi-combobox.

**Comment by bharathSivaSAP** [comment]
Hi @N1XUS,
I have tried again with entries having numbers in it and numpad didn’t work but the normal keypad numbers work. I have attached the screen recording as well.

https://user-images.githubusercontent.com/123215488/233324813-4ef81195-70b5-4b28-9401-bdfe77143a78.mov

**Comment by N1XUS** [comment]
@bharathSivaSAP the version you're using in [stackblitz](https://stackblitz.com/edit/angular-5zebky-9iedzt?file=src%2Fapp%2Fcombobox-example.component.html,src%2Fapp%2Fcombobox-example.component.ts) is not the latest. Can you check same behaviour with the latest RC?

**Comment by bharathSivaSAP** [comment]
@N1XUS Any updates about my previous question ?
