### ISSUE TITLE
[Sourcing] [Responsiveness] p13 dialog box needs mobile mode

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#9658]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.

The p13 dialog box should have a mobile mode so that it works on narrow (down to 320px) screen sizes.

<img width="1791" alt="Screenshot 2023-04-11 at 10 57 44 AM" src="https://user-images.githubusercontent.com/71999626/231064528-584241f1-51e3-4cfe-a9ba-81378bbb18db.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "0.39.1-rc.26",
"@fundamental-ngx/platform": "0.39.1-rc.26",
"@angular/cli": "15.2.0",

**Comment by droshev** [comment]
duplicated #9454

**Comment by mikerodonnell89** [comment]
After speaking with the accessibility team, we are not supporting 400% zoom. We are supporting up to 200%. However we do need to support 320px width screen sizes

**Comment by I543348** [comment]
This is a responsiveness issue
cc : @Sayandeep-123

**Comment by I543348** [comment]
low priority for 400%
