### ISSUE TITLE
Combobox Input: the border should be adjusted for 'Disabled' status

### ISSUE THREAD

**Issue by alvachien** [SAP/fundamental-ngx#966]
#### Is this a bug, enhancement, or feature request?
It's a bug.

#### Briefly describe your proposal.
Check the live demo: https://sap.github.io/fundamental-ngx/comboboxInput
For the disabled combobox component, the border style is quite strange: it seems that the border only applies to the 'Dropdown' button.

**Comment by droshev** [comment]
Once this(https://github.com/SAP/fundamental-styles/issues/136) is done we should address this.
