### ISSUE TITLE
[Sourcing][Responsiveness]] The scroll doesn't work properly in fdp-combobox in certain situation

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#9660]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
--The scroll should work in dropdown in fdp-combobox properly.
 

https://user-images.githubusercontent.com/71999626/231130661-e9d7137b-27a0-4c62-8876-ba25f4daec85.mov

#### If this is a bug, please provide steps for reproducing it.
--Add 5 items in datasource for fdp-combobox and zoom it to get the scroll in the dropdown, the scroll doesn't work.

**Comment by droshev** [comment]
@Sayandeep-123 Can you provide the exact steps how to reproduce the issue and the zoom%?

**Comment by I543348** [comment]
low priority issue as we dont have plan for 400%
