### ISSUE TITLE
[Sourcing][Accessibility] Chooser hierarchy issue 1

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9661]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
The below issues are reported by ATL team - 

1) On accessing the value help for choose hierarchy, a popup opens, Here the label “(3)” and UI type “Dialog” is not read to the users.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/88182358/231159498-eb644650-c793-41b8-b611-530d1cab47e7.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core./ platform: 0.39.0

#### Is there anything else we should know?
These issues are found and reported by ATL team and are required for custom chooser hierarchy component built using "Multi value input" and dialog with tree table

**Comment by droshev** [comment]
@I543348 Is this reproducible on the generic components or is it only specific to the chooser hierarchy?

**Comment by I543348** [comment]
these are generic components related 
cc: @droshev

**Comment by mikerodonnell89** [comment]
For point 3 - "Multi value input field is not provided with visible label" - i think here they are expecting a label, or a placeholder, both of which can be provided by the application developer. The rest I believe we will have to handle on the library

**Comment by mikerodonnell89** [comment]
It would also be nice to have a stackblitz or at least a block of sample code here for your component pattern

**Comment by skaquib123** [comment]
@mikerodonnell89 this is happening in chooser Hierarchy as well. 

Here is a sample code of CH:
[https://stackblitz.com/edit/angular-x6nsxg-vuq8rf?file=src%2Fapp%2Fmulti-input-compact-example.component.ts](url)

**Comment by mikerodonnell89** [comment]
Point 1, from the stackblitz above:
<img width="1151" alt="Screenshot 2023-06-02 at 10 13 41 AM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/5dfe957b-7312-4276-8287-21702bccbc5c">

**Comment by mikerodonnell89** [comment]
On point 4 - Jaws does announce it is a header cell:
<img width="682" alt="Screenshot 2023-06-02 at 10 20 33 AM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/fa49172d-449c-4f9f-8b25-dcd5156851ca">

**Comment by droshev** [comment]
@I543348 is it possible for your team to check and validate the fix?

**Comment by I543348** [comment]
Sure @droshev , I am checking with the respective developer for validation. We will update soon.
Thanks much.
