### ISSUE TITLE
[Sourcing][Dev blocker] <fdp-table> Platform Dnd Rearrangement misinformation

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9665]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

Platform Dnd is working now. We can drag drop item before, inside, and after another item visually. However, there is no way to tell how it dropped programatically. Also, the "rows" object which is part of the event object does not reflect the new arrangement of rows post-drag-and-drop:

https://user-images.githubusercontent.com/22842279/231280007-b40c343f-5092-49e4-9a84-bbe2553c74d0.mov

For this example, drag item inside and after gives the same information from EventEmitter. Is there anyway to know where it drops programatically. Could you provide a way or enhance any functionality?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest

#### Please provide relevant source code if applicable.

Please refer to: https://stackblitz.com/edit/angular-4nvyfd?file=src%2Fapp%2Fplatform-table-tree-example.component.html,src%2Fapp%2Fplatform-table-tree-example.component.ts

**Comment by I543348** [comment]
This is affecting fix from #9421

**Comment by CSENoni** [comment]
I can tell where the row is dropped from the emitted event now in 0.40.1-rc.7. Thanks!

**Comment by I543348** [comment]
Thanks much NGX Team and Hoang for providing the fix so quickly and helping us out.
Appreciated.
