### ISSUE TITLE
Platform list item focus outline incorrect

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#9669]
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Currently, when platform list is placed inside a popover, list item receives wrong focus outline due to the selector `.fd-popover__body .fd-list__item:last-child`. The issue with this is that the markup of the platform list is this:
![image](https://user-images.githubusercontent.com/6586561/231373439-07fa8141-df01-4446-b6d0-f6f9f57e566d.png)
which means that the list item is always last or first child and fits the css selector 
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current
#### If this is a bug, please provide steps for reproducing it.
1. create a popover;
2. place any platform list in it;
3. focus the list item

ER: outline should not have border radius if it's not the first and not the last list item;
AR: outline has border radius applied from first and last child selectors

**Comment by mikerodonnell89** [comment]
I think for this to work properly we should use renderer to remove Angular's wrapping objects. This will mean no breaking changes and the default fundamental-styles css should work fine. I am starting this now
