### ISSUE TITLE
[Bug][v0.36.0][fix card layout]: make the card width as fix, when display only two cards, the margin is incorrect

### ISSUE THREAD

**Issue by truezn** [SAP/fundamental-ngx#9671]
Due to my preview issue is closed, I have to create a new one 
For detail please refer the https://github.com/SAP/fundamental-ngx/issues/9012, 

In preview issue, i have add class as recommend. But it seems not work 

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/10548281/231420732-27abb0eb-e3ad-4b5b-9619-db1cdd3bc471.png">

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/10548281/231422591-c5f29d32-dbfc-46f0-874b-46cb2a239eb3.png">

Please help guide.

**Comment by mikerodonnell89** [comment]
try adding this override in addition to @N1XUS suggestion
```
.fd-fixed-card-layout__card-layout.fd-fixed-card-layout__card-layout--columns-2 .fd-fixed-card-layout__card {
    width: auto;
}
```
