### ISSUE TITLE
Busy Indicator in Component dialog not closing after value change.

### ISSUE THREAD

**Issue by Soumadeep1993** [SAP/fundamental-ngx#9682]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In component based dialog, any data change after initial load is not reflected until a click event or button press event is triggered.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.39.0 and 0.40.0

#### If this is a bug, please provide steps for reproducing it.
Open a component based dialog.
Change any value of a variable or set busyindicator to false after sometime or after completion of any API call.
The changes are not reflected until you click or press any button.

#### Please provide relevant source code if applicable.
Stackblitz code provided as example.
https://stackblitz.com/edit/angular-mylhjb?file=src%2Fapp%2Fdialog-example.component.ts,src%2Fapp%2Fcomponent-based-dialog-example.component.ts

**Comment by mikerodonnell89** [comment]
On first look, a workaround would be to manually trigger change detection like so:

```
export class DialogExampleComponent {
  constructor(public dialogRef: DialogRef, private _cdRef: ChangeDetectorRef) {}
  membersBusyIndicator = false;

  ngOnInit() {
    this.membersBusyIndicator = true;
    setTimeout(() => {
      this.membersBusyIndicator = false;
      this._cdRef.detectChanges();
    }, 4000);
  }
}
```

**Comment by anandsgar-sap** [comment]
Thanks @mikerodonnell89 ,we would try this

Now that we know its a real issue, could you please let me know by when could we can expect a quick fix from library itself.
@Soumadeep1993

**Comment by Soumadeep1993** [comment]
HI @mikerodonnell89, I have tried with the solution you suggested. This does work but there are many scenarios in which we are subscribing and expecting a promise from multiple places in the various dialogs. Triggering a change detector every time would be difficult to cover all scenarios and should not be a valid solution to this issue in my opinion.

**Comment by mikerodonnell89** [comment]
@Soumadeep1993 this is fixed with https://github.com/SAP/fundamental-ngx/pull/9692

**Comment by anandsgar-sap** [comment]
Hello @mikerodonnell89 we have dev close on coming Tuesday, could we consider this to be available by then in the release version of fundamental-ngx, or we should postpone our upgrade by a sprint.

**Comment by mikerodonnell89** [comment]
> 

@anandsgar-sap this will at least be part of a release candidate available on npm by then

**Comment by Soumadeep1993** [comment]
Hi @mikerodonnell89 I tested this in your new release 0.40.3, and still this issue is persisting. Can you please update when will the fix be released.

**Comment by mikerodonnell89** [comment]
You are correct, not sure what happened here. I will investigate
