### ISSUE TITLE
[ProcurementMobileApp][Dev blocker] <fdp-approval-flow> Unable to add additional field in the approval flow node

### ISSUE THREAD

**Issue by Prsnkmr7** [SAP/fundamental-ngx#9709]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Platform approval flow doesn’t allow to add any additional field inside approval node. Currently, it is allowing us add name, description, status and image. We need a functionality where we can add date field also when the status is approved .

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

**Current version:**
<img width="522" alt="image" src="https://user-images.githubusercontent.com/10990285/232761097-cd254e91-1589-4ad9-a027-90f0aaeb6db2.png">

**Expected Version:**
<img width="239" alt="image" src="https://user-images.githubusercontent.com/10990285/232761257-ec6afdc2-7735-4f18-9c7d-622f96225a38.png">

<img width="206" alt="image" src="https://user-images.githubusercontent.com/10990285/232761286-cf5a7e3c-bda6-4810-9af0-9595c2e14cd8.png">

Looking at (https://github.com/SAP/fundamental-ngx/blob/fefac1929380f482a9786b09513779548281256c/libs/platform/src/lib/approval-flow/approval-flow-user-details/approval-flow-user-details.component.html), we see that we can only add name, description and image inside approval node. This is currently a feature blocker in our implementation using this ngx version and hence requesting for resolution.

#### Which versions Fundamental Library  are affected?

fundamental-ngx/core: 0.40.0-rc.5 
fundamental-ngx/platform": 0.40.0-rc.5

#### Please provide relevant source code if applicable.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/10990285/232762237-6fb4755e-ec8b-46a6-9567-0df62c84c765.png">

**Comment by fkolar** [comment]
I think just like providing custom approval status, we should be able to expose Header, Body area to the application with custom ng-tempalte
