### ISSUE TITLE
'FormStates' type is no longer exported from @fundamental-ngx/core

### ISSUE THREAD

**Issue by horatzio-sap** [SAP/fundamental-ngx#9714]
#### When upgrading from @fundamental-ngx/core `0.36.2` to `0.40.0` we ran into the issue that the `FormStates` type is no longer exported from @fundamental-ngx/core.
It is however, still exported from the fundamental-ngx/cdk package.
In none of the 'Breaking Changes' from v 36 to v 40 is it mentioned the removal of this type from the Public api, even though it is clearly a breaking change, at least at type level.

**Comment by mikerodonnell89** [comment]
This should have been documented in breaking changes. However moving forward, developers should import FormStates from fundamental-ngx/cdk.
