### ISSUE TITLE
[Sourcing] Localization issue: `<fd-tokenizer>` 'more' term string still hardcoded

### ISSUE THREAD

**Issue by yixuan-liu** [SAP/fundamental-ngx#9715]
#### Is this a bug, enhancement, or feature request?
A bug
#### Briefly describe your proposal.
Need to localize this string

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
We're using Angular 15 with its built-in localization i18n and F-NGX `0.39.1-rc.4`

#### If this is a bug, please provide steps for reproducing it.
Using the `<fd-tokenizer>` component, add in more tokens so that they exceed the input field width, then focus out from the field until you see the `xxx more` string displayed inside the input field of the tokenizer

![Screenshot 2023-04-19 at 11 42 35 AM](https://user-images.githubusercontent.com/22454655/233170258-5c81939a-3f8c-4b47-9003-6af86ec9f149.png)

![Screenshot 2023-04-19 at 11 42 23 AM](https://user-images.githubusercontent.com/22454655/233170261-64c496c9-fa75-4125-9500-3c8ded5aecd0.png)

![Screenshot 2023-04-19 at 11 15 41 AM](https://user-images.githubusercontent.com/22454655/233170340-0de707f5-624a-416a-ae08-b491775172ee.png)

https://product-jira.ariba.com/browse/SS-44978

#### Is there anything else we should know?
This will cause translation issues with the `<fdp-multi-combobox>` and `<fd-multi-input>` components since they are using the `<fd-tokenizer>`

**Comment by mikerodonnell89** [comment]
It's not hardcoded, it is ready for translation, it just needs translators.
https://github.com/SAP/fundamental-ngx/blob/main/libs/i18n/src/lib/models/lang.ts#L207

**Comment by yixuan-liu** [comment]
Hi @mikerodonnell89 : we use Angular's localization tool to generate translation strings. After running `ng extract-i18n` command we are unable to find any such string or any other F-NGX related strings in the generated `.xlf` file
