### ISSUE TITLE
[Sourcing] <fdp-table> Prevent DND between rows

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9718]
#### Is this a bug, enhancement, or feature request?

enhancement

#### Briefly describe your proposal.

For DnD, UI is always changed before we can validate which row can be dropped. For example, in table having folders and files, file cannot be dropped on another file, but the UI will still reflect the change from dnd. For now, our workaround is to refresh the whole table to revert the change if we detect that the a dropRow should not be droppable by the dragged row from emitted event. It would be helpful if we can have more control on the UI change for dnd through object property or the emitted event to have some validation between dragged and dropped rows before making change on UI.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Latest

**Comment by fkolar** [comment]
This make sense, this needs some additional visuals (UX)

**Comment by CSENoni** [comment]
One found issue https://github.com/SAP/fundamental-ngx/issues/9955

**Comment by CSENoni** [comment]
@I543348 it is still blocked by https://github.com/SAP/fundamental-ngx/issues/9955. I will recheck after https://github.com/SAP/fundamental-ngx/issues/9955 is resolved.

**Comment by CSENoni** [comment]
With version v0.42.0-rc.22, this enhancement is working as expected. We can define which row is droppable and other "table functionalities" are still working normally after dnd. Thanks!
