### ISSUE TITLE
[Sourcing][Low][TBD] Global default ScrollStrategy

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9722]
#### Is this a bug, enhancement, or feature request?
Enhancement / feature request

#### Briefly describe your proposal.

We have `[scrollStrategy]` property binding in `fd-popover` component to control its `ScrollStrategy`. However, other components which use `fd-popover`, such as `fd-menu` and `fd-combobox`, do not have this property binding. 

Could we have a mechanism similar to Content Density to control the default global ScrollStrategy for all components?

Although we have the `cdkScrollable` directive, it may not be sufficient for more complex scenarios. For example, in the doc `<fdp-menu>` component demo, it may extend beyond the boundaries of its container. 

To handle such scenarios, we would like to set default to `Overlay.scrollStrategies.close()`.

https://user-images.githubusercontent.com/7035787/233727715-1bc48cf5-7c2e-4799-b509-b22d72a76ea1.mp4

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

```
    "@fundamental-ngx/core": "0.40.2-rc.7",
    "@fundamental-ngx/platform": "0.40.2-rc.7"
```

#### If this is a bug, please provide steps for reproducing it.
Not a bug

**Comment by fkolar** [comment]
It seems that fd menu does not have the same functionality as fd-popover so you will not be able to set scroll strategy the same way. It can be either extended inside the menu to conditional hide menu on scroll and there situation that make sense, like example you show. 

Other workaround, is to listen for scroll even and manually close menu.

**Comment by oscargong** [comment]
For fdp-combox, fortunately, all the method/property we need are public:
https://stackblitz.com/edit/angular-hxjs8m?file=src/app/combobox-columns-example.component.html

https://github.com/SAP/fundamental-ngx/assets/7035787/b9dbd1d0-82c5-4bf9-ad2e-b2b1f90d29bc

**Comment by oscargong** [comment]
@fkolar @mikerodonnell89  @droshev 
Could we prioritize resolving this issue, as we've received customer complaints about it?

**Comment by fkolar** [comment]
@oscargong , How this combobox video relates to this issue? Maybe I missed something.

**Comment by oscargong** [comment]
Hello @fkolar, apologies for any confusion I may have caused.

As you provided a workaround, I've found that the combobox can utilize it, all the method we need are `public`. However, we still require a global solution, because not every components expose such fields/methods.

**Comment by droshev** [comment]
@oscargong my understanding is that you have a working solution atm, having this global APi is not blocking you, right?

**Comment by oscargong** [comment]
Hi Deno,
Yes this is a nice-to-have now.
