### ISSUE TITLE
[Sourcing] Not able to open API documentation on website

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9724]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Looks like https://github.com/SAP/fundamental-ngx/issues/9473 is again replicable, pls reopen this or consider this as new issue.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Able to replicate on https://sap.github.io/fundamental-ngx/#/platform/table/api

console error 
in.8c8fe5f1c2bae674.js:1 Did not find file TableColumnComponent.
Error: [object Object]
(

#### If this is a bug, please provide steps for reproducing it.
1) click on API
2) try to open any Table component from Platform

**Comment by droshev** [comment]
@I543348 the workaround https://fundamental-ngx.netlify.app/#/platform/table/api

**Comment by droshev** [comment]
it is fixed
