### ISSUE TITLE
[Sourcing] <fd-popover> Unable to scroll in some scenarios

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9728]
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

The core popover in our application scroll is not working consistently across our application. In some places, it can not be scrollable. However, it can be clearly replicable when the popover is used with platform table in mid screen when there is a scrollbar outside.

https://user-images.githubusercontent.com/22842279/233758414-5efd9f9a-8503-4c20-b376-548cd35f2b2d.mov

In this example, it could not be horizontally and vertically scrollable. 

Also, the size change of popover:

https://user-images.githubusercontent.com/22842279/233760988-0dca88ed-d3d4-4436-af1b-44c1cd8714e9.mov

Can also be reproducible without platform table:

https://user-images.githubusercontent.com/22842279/234079248-1a15533d-e862-43b8-9ae1-95c50e877cef.mov

Another notice is that if we shrink the window size at certain level, the popover can be scrollable again, but cannot if we are back to original size.

https://user-images.githubusercontent.com/22842279/234144651-b3f901c2-e89c-4224-9a57-8aea8fcbe9b8.mov

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

latest (40.2-rc.12) and previous

#### If this is a bug, please provide steps for reproducing it.

Inconsistent but it could be replicable when using with platform table and it is placed somewhere in the middle of body with scrollbar. Please refer to the link below. Steps to reproduce:

- Open popover.
- Scroll body scrollbar up/down so that the popover shows scrollbar or change its size.
- Try to scroll up/down or left/right of popover.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-vf7m7w?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,package.json

https://stackblitz.com/edit/angular-imde9d?file=package.json,src%2Fapp%2Fpopover-focus-example.component.html

**Comment by mikerodonnell89** [comment]
Could you try the latest RC versions (around [0.42.0-rc.14](https://www.npmjs.com/package/@fundamental-ngx/core/v/0.42.0-rc.14)) we have made some improvements to the scrolling, having a hard time recreating this now

**Comment by CSENoni** [comment]
I can still reproduce it for this link: https://stackblitz.com/edit/angular-imde9d-xffmeh?file=package.json,src%2Fapp%2Fapp.module.ts

https://github.com/SAP/fundamental-ngx/assets/22842279/f2da14e9-4410-4305-a1f9-f912c8a05f44

**Comment by mikerodonnell89** [comment]
@CSENoni we are still working on a solution to this one, in the meantime for a workaround, if you set a PX height on the fd-popover-body, it looks like that handles this issue

**Comment by CSENoni** [comment]
Setting some height can help but I think it has to be limited in some range. The issue still persists with some height size:

https://github.com/SAP/fundamental-ngx/assets/22842279/54b23ab8-7513-4378-b041-52afb77a628c

But we can temporarily go with that. Thanks!

**Comment by mikerodonnell89** [comment]
Yes I think the height in px needed to be less than whatever 100% of the body was. However on rc-22 looks like it is working better?

https://github.com/SAP/fundamental-ngx/assets/2471874/48cd034f-34ad-4fb5-9c4b-cfb7bab367a3

**Comment by droshev** [comment]
@CSENoni @mikerodonnell89 is the issue reproducible in the latest ngx version?

**Comment by CSENoni** [comment]
@droshev I just checked and it was still reproducible with 0.42.0-rc.23.

**Comment by mikerodonnell89** [comment]
@CSENoni are you updating all the packages?
```
    "@fundamental-ngx/cdk": "0.42.0-rc.24",
    "@fundamental-ngx/core": "0.42.0-rc.24",
    "@fundamental-ngx/i18n": "0.42.0-rc.24",
    "@fundamental-ngx/platform": "0.42.0-rc.24",
```

I am unable to recreate this problem at this point

https://stackblitz.com/edit/angular-imde9d-afqokk?file=package.json


https://github.com/SAP/fundamental-ngx/assets/2471874/7ad4224c-a81b-4ce3-b83a-f40a981caa93

**Comment by CSENoni** [comment]
@mikerodonnell89 @droshev My bad, I probably did not refresh browser properly last time. I just rechecked all scenarios here with 0.42.0-rc.24 and cannot reproduce it now regardless of window size. We are good to close. Thank much and apologize for making you double check @mikerodonnell89
