### ISSUE TITLE
[Sourcing] <fdp-table> Perf with virtualScroll and pageScrolling in certain window size

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9746]
#### Is this a bug, enhancement, or feature request?

Bug and/or enhancement

#### Briefly describe your proposal.

Issue 1: (maybe enhancement)

In certain window size with platform table on dialog, when we have virtualScroll and pageScrolling enabled and when we show some large amount of rows on UI, if we scroll up or down very fast, whitespace will show. 

https://user-images.githubusercontent.com/22842279/234118058-9cecac04-64db-454d-a9d8-58fec0f3abe3.mov

Issue 2: (bug)

In certain window size with platform table on dialog, when we have virtualScroll and pageScrolling enabled and when we show some large amount of rows on UI, if we resize one column and then scroll up/down fast, in additional to whitespace, we see the scrollbar jump up and down for a while.

https://user-images.githubusercontent.com/22842279/234118907-ac69fb41-4dc3-49b2-8e13-7a7e4a9163c3.mov

After jumping is done, when we try to scroll to next page, we see that we still stay on the same page by looking at the first column.

https://user-images.githubusercontent.com/22842279/234118675-90c497bc-218a-468c-a558-173f230bfd06.mov

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

40.2.rc-12 or previous

#### If this is a bug, please provide steps for reproducing it.

Please refer the link below. Step to reproduce:

- Create a platform table with large amount of items (more than 1000) on dialog.
- Resize the width of window size like opening dev tool.
- Scroll down to fetch some amount of data several times.
- Try to scroll up and down fast.
- Then adjust one or more column size.
- Try to scroll up and down fast some times.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-acnvmy?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,package.json,node_modules%2F%40fundamental-ngx%2Fcore%2Fdialog%2Fdialog-service%2Fdialog.service.d.ts

**Comment by CSENoni** [comment]
https://github.com/SAP/fundamental-ngx/assets/22842279/c70338a1-b693-44ff-83c4-dc2f98d023a5

I think it has something to do with the column resizing. I can be replicated without dialog on fundamental playground.

**Comment by mikerodonnell89** [comment]
Issue 1 can possibly be alleviated a bit with the `renderAhead` input property. I'm not sure how we can prevent this entirely. I will take a look into issue 2

**Comment by CSENoni** [comment]
Test on blitz and fundamental playground with all scenarios above, with 0.42.0-rc.22, the "jumping" is not reproduced anymore. The performance seems also to be better. Thanks!
