### ISSUE TITLE
[Sourcing] The background div is still scrollable when `<fd-dialog>` displays

### ISSUE THREAD

**Issue by oscargong** [SAP/fundamental-ngx#9753]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
With design specs: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913313
![Oscar ScreenCapture 2023-04-25 at 19 22@2x](https://user-images.githubusercontent.com/7035787/234449971-1d0d310d-136f-4ee6-b70a-98d06f82e52a.png)

we can still scroll through the background content after the <fd-dialog> is displayed.

https://user-images.githubusercontent.com/7035787/234450340-085bccdc-1f6a-427f-9fd7-ae71e2e68926.mp4

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

```
    "@fundamental-ngx/cdk": "0.40.2-rc.22",
    "@fundamental-ngx/platform": "0.40.2-rc.22",
    "@fundamental-ngx/core": "0.40.2-rc.22",
    "@fundamental-ngx/i18n": "0.40.2-rc.22",
```

#### If this is a bug, please provide steps for reproducing it.

https://stackblitz.com/edit/angular-ilwqqy?file=src/app/dialog-configuration-example.component.html

#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-ilwqqy?file=src/app/dialog-configuration-example.component.html

**Comment by I543348** [comment]
@oscargong  pls evaluate and confirm

**Comment by oscargong** [comment]
verified that it has been fixed
