### ISSUE TITLE
[Bug] Wrong dimensions of the dialog component after opening the wizard component

### ISSUE THREAD

**Issue by markywilson** [SAP/fundamental-ngx#9754]
#### Is this a bug, enhancement, or feature request?
A bug

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular `15.2.7`
NGX Fundamentals `0.40.1`

#### If this is a bug, please provide steps for reproducing it.
- Open dialog component for the first time
<img width="1552" alt="Screenshot 2023-04-26 at 10 47 51" src="https://user-images.githubusercontent.com/7045276/234522562-e2fb4d02-e779-4c34-be23-5c30bf895889.png">

- open the wizard component 
<img width="1552" alt="Screenshot 2023-04-26 at 10 48 14" src="https://user-images.githubusercontent.com/7045276/234522747-1cd4337a-9376-460c-8880-74da95a7dc43.png">
<img width="1552" alt="Screenshot 2023-04-26 at 10 48 11" src="https://user-images.githubusercontent.com/7045276/234522768-9deee47f-f96c-4fd8-b963-56e1e9f7495d.png">

- open a dialog for the 2nd time
<img width="1552" alt="Screenshot 2023-04-26 at 10 48 22" src="https://user-images.githubusercontent.com/7045276/234522880-f80ac76d-f802-4a80-af81-388c14d93a44.png">

🔴 The dialog is full screen now

**Expected Behaviour**

🟢  The dialog should maintain its original size

#### Is there anything else we should know?
The following CSS gets added when loading the wizard component which causes the dialog to take the size of the entire screen
https://github.com/SAP/fundamental-ngx/blob/main/libs/core/src/lib/wizard/wizard.component.scss#L50

**Comment by N1XUS** [comment]
Not reproducible with latest version of fundamental-ngx.
