### ISSUE TITLE
WIP: [Med][Aug]Dynamically adding rows to the ngx-platform table - Create, Save and Cancel button labels should be externalized for translations.

### ISSUE THREAD

**Issue by nehabeke** [SAP/fundamental-ngx#9760]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
I am using ngx platfrom table - https://sap.github.io/fundamental-ngx/#/platform/table/basic
Where I am using property called [editMode]="'inline'" to add rows dynamically to the table.
This property automatically generates 3 buttons: Create, Save and Cancel. These "Create", "Save" and "Cancel" button labels are not localized properly. These strings should be externalized for translations.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/14968987/234940577-296dc929-0ab3-494a-a2ca-74be1e749dfd.png">

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/14968987/234940667-df69dbbb-4f75-45b4-bb8d-6a24b7afd247.png">

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/14968987/234940782-ea184a07-e977-410d-8cde-86a068ca08a2.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular CLI: 15.2.0
"@fundamental-ngx/core": "0.40.2-rc.8",
"@fundamental-ngx/platform": "0.40.2-rc.8",

#### Please provide relevant source code if applicable.
https://stackblitz.com/run?file=src%2Fmain.ts

**Comment by nehabeke** [comment]
Hi, Would you kindly give prompt attention to this particular issue? Please let me know If you have any questions, I will be happy to help.

**Comment by fkolar** [comment]
I checked and the translation is in place

<img width="723" alt="Screenshot 2023-06-26 at 12 44 34" src="https://github.com/SAP/fundamental-ngx/assets/17149942/cd5ae2e3-3155-4489-aeb6-da4d4663f631">
<img width="743" alt="Screenshot 2023-06-26 at 12 44 31" src="https://github.com/SAP/fundamental-ngx/assets/17149942/a21c25b4-4d7a-4f55-92e4-78ffa082dfa5">


It is just some languages might not be fully translated. 

- Which language is the problem here? (we can use temporary Google Translate to do this)

@mikerodonnell89, @N1XUS , there was some way a workaround where application could override some translation right?

**Comment by nehabeke** [comment]
Hi,

I have asked someone from doc team to check this. I will get back to you once I hear back from her.

Thanks,
Neha

**Comment by nehabeke** [comment]
This another bug is similar to this one, could you please take a look at this as well? 
https://github.com/SAP/fundamental-ngx/issues/9884

Thanks,
Neha

**Comment by N1XUS** [comment]
@fkolar @nehabeke You can patch language values by using `patchLanguage` provider: https://github.com/SAP/fundamental-ngx/blob/main/libs/i18n/src/lib/utils/patch-language.ts

**Comment by N1XUS** [comment]
Additionally, you can simply clone one of translation objects, rewrite the language values to your needs, and provide it as a language. Since `FD_LANGUAGE` is a BehaviourSubject, you can emit next value at any time you want.

**Comment by fkolar** [comment]
> Hi,
> 
> I have asked someone from doc team to check this. I will get back to you once I hear back from her.
> 
> Thanks, Neha

Ok. in meanwhile we have a workaround but please get us the information what language does not have the translation. There should be no needs to provide custom translation for those buttons.

**Comment by nehabeke** [comment]
Hi, we have checked, it is not working for any of the languages.

**Comment by fkolar** [comment]
Can you double check? I see something different. in the navigation bar change the language to French for example...

https://fundamental-ngx.netlify.app/#/platform/table/basic#basic-add-rows

**Comment by nehabeke** [comment]
Yes we checked it. I have attached files.

![image (1)](https://github.com/SAP/fundamental-ngx/assets/14968987/8eb47699-7394-41c0-bdc0-3a95eeba9567)
![image (2)](https://github.com/SAP/fundamental-ngx/assets/14968987/ecfe1d3c-902d-4d1a-ab57-09ed63ae96f9)
![image (3)](https://github.com/SAP/fundamental-ngx/assets/14968987/0f002c0b-4e54-49b1-8f82-744fbe982d47)
![image (4)](https://github.com/SAP/fundamental-ngx/assets/14968987/41df9100-9fb6-4b8f-81be-1c28410f9467)
![image (5)](https://github.com/SAP/fundamental-ngx/assets/14968987/8aa4dd7d-4df7-44b7-8c4f-bf2af343395f)
![image](https://github.com/SAP/fundamental-ngx/assets/14968987/98d6f6e2-c0f3-4718-997e-b19ec745e107)

**Comment by fkolar** [comment]
Can you check the link I sent you? There is a table with create button. in the top right corner you can change a lang.

so we can't really say it does not work for any of the languages.

**Comment by nehabeke** [comment]
It is working in the link you have provided. But not working in the application. I am not getting why. Could you please recommend any other solution for this?

**Comment by fkolar** [comment]
I would definitely check:
https://sap.github.io/fundamental-ngx/#/core/i18n
https://github.com/SAP/fundamental-ngx/blob/main/apps/docs/src/app/app.module.ts
https://github.com/SAP/fundamental-ngx/blob/main/libs/docs/core/toolbar/toolbar-docs.component.ts


Closing as this is more about how to use certain thing that can be discussed offline + there is another issue related to i18n https://github.com/SAP/fundamental-ngx/issues/10137
