### ISSUE TITLE
Dialog animations do not work with standalone applications

### ISSUE THREAD

**Issue by moxaj** [SAP/fundamental-ngx#9761]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Recently tried to port an existing application to the new standalone API. If I provide the animations via the new [`provideAnimations()`](https://angular.io/api/platform-browser/animations/provideAnimations), I get the following error when trying to show a dialog:
```
ERROR Error: Unexpected synthetic listener @state.done found. Please make sure that:
  - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
  - There is corresponding configuration for the animation named `@state.done` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
    at checkNoSyntheticProp (dom_renderer.ts:304:11)
    at EmulatedEncapsulationDomRenderer2.listen (dom_renderer.ts:291:20)
    at listenerInternal (listener.ts:179:34)
    at Module.ɵɵsyntheticHostListener (listener.ts:80:3)
    at Object.DialogContainerComponent_HostBindings [as hostBindings] (dialog-container.component.ts:56:31)
    at invokeHostBindingsInCreationMode (shared.ts:1205:9)
    at invokeDirectivesHostBindings (shared.ts:1188:9)
    at createRootComponent (component_ref.ts:393:3)
    at ComponentFactory.create (component_ref.ts:228:19)
    at DomPortalOutlet.attachComponentPortal (dom-portal-outlet.ts:86:39)
```

However, if I use `importProvidersFrom(BrowserAnimationsModule)` (or the old `NgModule` based approach), it works.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Using Angular 15.2.4 and fundamental-ngx 0.40.2.

#### If this is a bug, please provide steps for reproducing it.

1. Create a new angular application, using the [standalone API](https://angular.io/guide/standalone-components).
2. When bootstrapping, use `provideAnimations()`
3. Try to open a dialog using `DialogService`

**Comment by N1XUS** [comment]
Hello @moxaj.
Thank you for submitting this ticket.
Here's a working example of dialog service with standalone component: https://stackblitz.com/edit/angular-lm1ntg?file=src%2Fmain.ts,angular.json,src%2Fglobal_styles.scss

Could you please verify that everything works as expected?

**Comment by moxaj** [comment]
@N1XUS the provided example does work, however with `importProvidersFrom(BrowserModule)` I can replicate the error: https://stackblitz.com/edit/angular-ewmdnp?file=src%2Fmain.ts

**Comment by N1XUS** [comment]
@moxaj It's all about the order of providers :D https://stackblitz.com/edit/angular-btqyn4?file=src%2Fmain.ts
