### ISSUE TITLE
[Sourcing] Date-time picker popup is not scrollable when window size is smaller or window is resized

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#9763]
#### Is this a bug, enhancement, or feature request?

This is a bug.

#### Briefly describe your proposal.
 As the end user might have a window with lesser pixel size and in this case they will not be able to scroll to the end of popup or not even click on cancel or ok button.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version - 15.2.0
Fundamental Library version - 0.40.2-rc.12

#### If this is a bug, please provide steps for reproducing it.
Try opening any of the date time picker after resizing the window to smaller size. 

#### Is there anything else we should know?

https://user-images.githubusercontent.com/110370099/235073854-47d50ac6-6465-4ca8-89bf-941d5d309635.mp4

**Comment by I568944** [comment]
We have observed this issue after verifying the fix given in https://github.com/SAP/fundamental-ngx/issues/9637

**Comment by I568944** [comment]
Verified in v0.41.0. It is working fine. We are able to scroll fd-date-time-picker.
