### ISSUE TITLE
[Bug] Message Strip Icons missing

### ISSUE THREAD

**Issue by JenniferStamm** [SAP/fundamental-ngx#9764]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

The icons are missing from message strips. Please observe that the first example should have the icons at the left:
![image](https://user-images.githubusercontent.com/7091280/235101590-150f00b0-a68f-4cd2-b460-9e0d4403762b.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

v0.40.2

#### If this is a bug, please provide steps for reproducing it.
You can observe it in the documentation:
https://sap.github.io/fundamental-ngx/#/core/message-strip

**Comment by droshev** [comment]
we will fix it.

**Comment by droshev** [comment]
fixed with https://github.com/SAP/fundamental-ngx/pull/9768
