### ISSUE TITLE
fd-side-nav the expanded parent has the same background color as selected item

### ISSUE THREAD

**Issue by khodayar** [SAP/fundamental-ngx#977]
#### Is this a bug, enhancement, or feature request?
Feature request

#### Briefly describe your proposal.
if we select other items when a parent item is expanded, it's formatting looks like a selected item
it's better if  when the parent item is expanded, it just keeps the bold font and not the background color

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
"fundamental-ngx": "0.5.2",

#### If this is a bug, please provide steps for reproducing it.
expand a item which has children
select an item which is not a child of the item mentioned above
it looks like both items (parent and the new one) are selected

#### Please provide relevant source code if applicable.
we need something like :
.fd-side-nav__link[aria-expanded=true]{
  background-color: var(--fd-color-background-2);
}

**Comment by InnaAtanasova** [comment]
This is issue is addressed in [Fundamental-styles](https://github.com/SAP/fundamental-styles/issues/215) and the [PR](https://github.com/SAP/fundamental-styles/pull/255)  is in review. Once it's merged and a new version is released, we are going to refactor the whole Side nav component in NGX

**Comment by droshev** [comment]
We are waiting for the final decision of the design

**Comment by droshev** [comment]
@InnaAtanasova i think we have addressed all the issues regarding the side navigation

**Comment by khodayar** [comment]
thank you @droshev and @InnaAtanasova
