### ISSUE TITLE
[Sourcing] [Accessibility] Focus doesn't goes inside the table row, if the row is navigable 

### ISSUE THREAD

**Issue by Ankit0025-cmd** [SAP/fundamental-ngx#9791]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
The focus should go inside the table row, because there might be some intractable elements inside the table cell.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "15.1.1"

"@fundamental-ngx/cdk": "0.40.3-rc.1",
"@fundamental-ngx/platform": "0.40.3-rc.1",
"@fundamental-ngx/core": "0.40.3-rc.1",
"@fundamental-ngx/i18n": "0.40.3-rc.1",

#### If this is a bug, please provide steps for reproducing it.
Try to get inside any table cell using the keyboard arrow button and the tabs.
#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-kvtygd?file=package.json

**Comment by mikerodonnell89** [comment]
User can press "enter" to focus individual cells within a navigable row, then use arrow keys to navigate to any cell in the table. However, I think we can improve upon the stackblitz here by allowing arrow keys to from whole navigable row to individual cells in the non-navigable row without pressing enter first
