### ISSUE TITLE
[Sourcing] Dialog (with fdp-table inside) is getting closed on Esc key 

### ISSUE THREAD

**Issue by Ankit0025-cmd** [SAP/fundamental-ngx#9794]
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
As when the focus inside the table cell, the escape key should just make the focus out of the element inside the cell to the whole cell, but the currently the event is getting propagated and the dialog is getting closed as well which is not the expected behaviour.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@angular/core": "15.1.1",

"@fundamental-ngx/cdk": "0.40.3-rc.1",
"@fundamental-ngx/platform": "0.40.3-rc.1",
"@fundamental-ngx/core": "0.40.3-rc.1",
"@fundamental-ngx/i18n": "0.40.3-rc.1",
#### If this is a bug, please provide steps for reproducing it.
Just add any intractable element inside the table cell, go to that cell using the arrow keys and now press tab, the focus will be inside the cell to the element. Press Esc, now for a moment we can see that the focus comes to the fdp-table-cell and then the dialog gets closed, which is not the expected behaviour. The dialog should still be open just the focus should move out of the element to the table cell.
#### Please provide relevant source code if applicable.
https://stackblitz.com/edit/angular-jp6fum?file=package.json

**Comment by I543348** [comment]
under evaluation

**Comment by Ankit0025-cmd** [comment]
Working as expected. (Link for reference: https://stackblitz.com/edit/angular-ylsswk?file=src%2Fapp%2Fdialog-complex-example.component.ts )
Thanks
