### ISSUE TITLE
[Sourcing]  fd-combobox fires two selectionChange events when user type value and selects the value from picklist.

### ISSUE THREAD

**Issue by ogudekar** [SAP/fundamental-ngx#9797]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Scenario 1 – [Working]. User selects option from list.
This scenario works fine. As only one event is fired with valid choice selected by user from list.
Scenario 2- [Issue] User types value, auto suggest pops up.  User selects value. Value gets reset.
This scenario is breaking. Since Ngx component fires two events back to back. One with user type text and other with value selected by user. T See below screenshot.
![image](https://user-images.githubusercontent.com/130004670/236571364-699ea165-20c9-493e-b17f-e76e2bb4371b.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "0.39.1-rc.20",
"@fundamental-ngx/platform": "0.39.1-rc.20"
"@angular/core": "15.2.0"

**Comment by I543348** [comment]
Need to be evaluated by @ogudekar
