### ISSUE TITLE
Version 1.0 - Topics to consider and plan

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#9816]
List the high level topics we need to cover to prepare for version 1.0

- [ ] review all open issues and identify critical bugs (plan to fix them)
- [ ] review and plan the accessibility issues
- [ ] prepare infrastructure and publish scripts
- [ ] delete all deprecated components, API, etc. (evaluate the impact)
- [ ] agree on versioning; maintenance; SLA; downporting strategy; LTS
- [ ] align with Angular major version schedule
- [ ] agree on preliminary release date/month
- [ ] Check older components if they can use CDK instead of individual logic implementation (dialogs, notifications, platform form controls, table data source);
- [ ] Check documentation UX (we have large amount of components, examples of those components, and sometimes it's hard to navigate, maybe add subsections same way we have in fundamental-styles);
- [ ] Review `detectChanges` usage, in some cases we can change it to `markForCheck`;

**Comment by g-cheishvili** [comment]
We should check out if there is any critical bug, fix it, **_remove every deprecation_** that we have in our library, and release.

Everything else, including issues with a11y if there any, or infrastructure or something is always doable without a breaking change
