### ISSUE TITLE
Write angular form unit tests

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#982]
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
The components that support Angular forms are currently not tested for their Forms support, only with their two-way binding. We should add tests for angular forms.

**Comment by droshev** [comment]
@mikerodonnell89 will create one example and create a list for future tests

**Comment by mikerodonnell89** [comment]
Pushed a branch here, shows how to set up a component for unit testing a form with a date picker component: https://github.com/SAP/fundamental-ngx/tree/chore/%23982-form-unit-tests
