### ISSUE TITLE
Component Design Update: Carousel

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#9821]
- [x] review markup changes from fd-styles
- [x] Horizon specs(visual and interaction) updates
- [x] Delta theming
- [x] identify and document breaking changes

**Comment by N1XUS** [comment]
BREAKING CHANGE:
Vertical carousel markup change:
Previously navigation buttons had icons sap-icon--slim-arrow-left and sap-icon--slim-arrow-left ignoring the direction. Now if vertical navigation is applied, buttons will have icons sap-icon--slim-arrow-up and sap-icon--slim-arrow-down respectively.
