### ISSUE TITLE
Component Design Update: Toolbar

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#9824]
- [ ] review markup changes from fd-styles
- [ ] Horizon specs(visual and interaction) updates
- [ ] Delta theming
- [ ] identify and document breaking changes

**Comment by N1XUS** [comment]
BREAKING CHANGE:
Removed inner `<div class="fd-toolbar">...</div>`.
Now classes and other attributes applied to the root fd-toolbar element.
