### ISSUE TITLE
Calendar Revamp

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental-ngx#983]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Our current calendar is messy and should be restarted from scratch. It has the following requirements.

* Modular structure. Calendar header and body views should be separate components inside the calendar component. The body should be an ngSwitch (since we do not require the router as a dependency) which controls whether the DayView, MonthView and YearView is selected. See the [calendar2](https://github.com/SAP/fundamental-ngx/blob/feat/calendar2/library/src/lib/calendar/calendar2/calendar2.component.html) branch for an example with the DAY view. The views could all extend a base CalendarView component with the core inputs, perhaps.
* Should support programatically changing view to DayView, MonthView, YearView.
* Should support changing default view to DayView, MonthView, YearView.
* Supports current formatting pattern with the provided services (default parsing/formatting can be modified).
* Follows ISO 8601 standard, where months start with 1. Google the standard for more info like weekday-to-number mappings.
* Do not use the JavaScript Date object as a model. It can be used to fetch stuff like the number of days in a month, however. For the actual model representing the selected date, use something like the FdDate object that is created in the feat/calendar2 branch. I leave the specifics to the programmer, but there should be day, month and year properties.
* Support multiple calendar types, like Gregorian or Julian for example.
* Support angular forms (unit tests included).
* Support two-way binding to a property, preferably of type FdDate.
* Support range mode as in current calendar and changing the range dynamically.
* Support current localization methodology, also investigate supporting Angular's i18n functionality. If both the current methodology AND the Angular i18n can be supported together, we should do so.
* Support keyboard-only navigating with arrow keys.
* Support the current flow of the calendar. Picking a month goes back to the day view, picking a year goes to the day view, etc.
* Calendar should always be the same height. It should not jump around in size. Show 6 weeks, and have the year and month views be the same size as the day view.
* Should support programatically navigating to a date without selecting it.
* Should support programatically selecting a date.
* Should support programatically focusing the element.
* Should work fine in the datepicker and datetime picker. Modifying those two components if necessary IS a part of the scope of this issue.
* Should support changing default first week day shown (should allow any day, not just Sunday or Monday).
* Should support adding every kind of disabling functions that exist in current calendar. Ideally, just one disable function (maybe), and perhaps have some hooks that people can tap into and dynamically change the disable function, mostly for range mode. 
* Should be thoroughly tested.
* Should be well documented, with examples of common use cases and all inputs/outputs/methods properly described.
* Consider maintainability when designing the architecture. It should be easy to maintain and understand, even for people who are new to the fd-ngx project.
* Consider ease of development. It is easy to add functionality to the calendar?
* Consider usability. It is easy for a developer to use this calendar?
* Any breaking changes should be clearly documented in the wiki.
* [Optional] Add a format/parse service (Similar to the DefaultParser) that is compatible with Moment.js and/or Luxon.
* [Optional] Support passing custom templates, maybe a custom day template, custom header etc. 

... More may be added.

Currently needs to be groomed more. Please do not tackle this ticket yet.

**Comment by JKMarkowski** [comment]
Hi, I got some propositions for requirements:

- Should support programatically changing view to DayView, MonthVyew, YearView

- Should support changing default view to DayView, MonthView, YearView,

- Should support changing default first day change (Sunday or Monday)

Maybe I will add something else.

**Comment by MattL75** [comment]
Yep all good requirements - I'll add them to the list.

**Comment by JKMarkowski** [comment]
Hi @DorinR @InnaAtanasova I created some graph, so we can proceed in next week with implementation. 
It's splited to 4 components, that can be implementing in the same time, to I think we can work  pararell.
![calendar (1)](https://user-images.githubusercontent.com/26483208/60727081-576b9300-9f3d-11e9-90fe-da5447cd777d.jpg)

If you have any questions feel free to ask.

**Comment by konradkukier2** [comment]
Any update on this issue or ETA?

Cheers

**Comment by MattL75** [comment]
Hey @konradkukier2.

No clear ETA as of yet but it's in progress and significant work has been done already.
