### ISSUE TITLE
is there any way I can register an explicit icon in the `IconModule` other than the listed ones?

### ISSUE THREAD

**Issue by kushwahashiv** [SAP/fundamental-ngx#987]
#### Is this a bug, enhancement, or feature request?
Yes
#### Briefly describe your proposal.
is there any way I can register an explicit icon in the `IconModule` other than the listed ones in https://sap.github.io/fundamental-ngx/icon
As a user, I should be able to register any SVG icon to the IconModule as I may need an additional icon other than the listed ones in https://sap.github.io/fundamental-ngx/icon. 

#### Is there anything else we should know?
if I can't register an explicit icon to the `IconModule`  I have to implement my own icon control in that case. I also think it is a very important feature as the icon set provided may not be sufficient for a target app.

**Comment by kushwahashiv** [comment]
@MattL75 what's the timeline for above enhancement?

**Comment by MattL75** [comment]
It's been discussed internally a little bit, but nothing is set in stone yet. I'll bring it up at the next planning and see where it fits on the timeline.

**Comment by droshev** [comment]
We offer 2 more icon sets at the moment.
