### ISSUE TITLE
Multi-Input dropdown values are showing randomly as checked even if not selected.

### ISSUE THREAD

**Issue by Soumadeep1993** [SAP/fundamental-ngx#9875]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

Multi-Input dropdown values are showing randomly as checked even if not selected.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.38.2, even the latest 0.40.3 has the issue as can be seen in UI documentation page

#### If this is a bug, please provide steps for reproducing it.

- Open a compact multi-input control.
- Select some values and then unselect all.
- Search for a term, and select it. 
- Then if we see the dropdown values, some other random values are also showing as checked, although its not selected.
- Check multiple times if not visible in the first time. ( It happens randomly ).

- #### Please provide relevant source code if applicable.

https://sap.github.io/fundamental-ngx/#/core/multi-input

Can be seen in the sample documentation of Fundamental NGX compact multi-input or Return results including search term multi-input.

**Comment by Soumadeep1993** [comment]
Hi @mikerodonnell89, can you please look into it on an urgent basis

**Comment by mikerodonnell89** [comment]
closed with #9961
