### ISSUE TITLE
Is there anyway I can freeze a column in a `table` control?

### ISSUE THREAD

**Issue by kushwahashiv** [SAP/fundamental-ngx#988]
#### Is this a bug, enhancement, or feature request?
Yes

#### Briefly describe your proposal.
As a user, I should have an API available in the `TableModule` to freeze one or multiple columns of a table. For example: let's say I want to freeze the last column for action menu and still should be able to scroll horizontally.

**Comment by MattL75** [comment]
Fundamental Styles does have some styling that supports this. See [this page](https://sap.github.io/fundamental-styles/components/table.html) and scroll to the section _Table with Fix Column Header and context menu_.

However, we do recommend using the [Angular CDK](https://material.angular.io/cdk/categories) for table features as we currently do not provide a table API ourselves.

**Comment by kushwahashiv** [comment]
@MattL75 thanks for the info. yes that can be one of the options we may go with.
