### ISSUE TITLE
Clear search button missing in current version of Input Group Search

### ISSUE THREAD

**Issue by f-nie** [SAP/fundamental-ngx#9881]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
In the [documentation of the Input Group Search](https://sap.github.io/fundamental-ngx/#/core/input-group#input-group-search) it is stated that 

> This input group automatically shows a clear search button when the user has entered a value in the input.

This was implemented correctly in earlier versions of Fundamental NGX, e.g. in version 0.29.2:

![image](https://github.com/SAP/fundamental-ngx/assets/45592361/acc16c6c-8fdd-429c-8b9d-9fa0261ecfce)

Now we upgraded to version 0.40.3 and the clear button is missing:

![image](https://github.com/SAP/fundamental-ngx/assets/45592361/87059147-3187-4c3e-a2a6-be4ac81e94b4)

Also in the [Input Group Search example](https://sap.github.io/fundamental-ngx/#/core/input-group#input-group-search) the clear button is missing.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

15.2.9 / 0.40.3

#### If this is a bug, please provide steps for reproducing it.

See [example](https://sap.github.io/fundamental-ngx/#/core/input-group#input-group-search).

#### Please provide relevant source code if applicable.

See [example](https://sap.github.io/fundamental-ngx/#/core/input-group#input-group-search).

#### Is there anything else we should know?

According to the [Fiori Design Guidelines](https://experience.sap.com/internal/fiori-design-web/search/) the clear button should be part of the search field.

**Comment by N1XUS** [comment]
Hello @f-nie. Input group is a common component. For search field specific, we  recommend looking at a dedicated "Search Field" component: https://sap.github.io/fundamental-ngx/#/platform/search-field
