### ISSUE TITLE
[accessibility]"fd-dialog" does not focus on element when opened

### ISSUE THREAD

**Issue by ranjithPRao** [SAP/fundamental-ngx#9882]
bug

#### Briefly describe your proposal.

Briefly describe your proposal.

we have a dialog added in Ariba Sourcing. when the dialog opens, the focus should be on the button/link. but the elements are not getting focused.
attaching the screenrecording:

https://github.com/SAP/fundamental-ngx/assets/116718610/f55d0b9d-2ff6-4749-ba96-ce8bdaf21c7d

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
"@fundamental-ngx/core": "0.40.2-rc.12"
"@fundamental-ngx/platform": "0.40.2-rc.12",
 "fundamental-styles": "0.28.3",

If this is a bug, please provide steps for reproducing it.
please see the attachment

**Comment by mikerodonnell89** [comment]
The first focusable element gets focus when a dialog is opened, which appears to be the dismiss button in the top right in your example video. You can use the `fd-initial-focus` directive on the button you wish to receive focus first
