### ISSUE TITLE
[Med][Aug]"Collapse Panel" and "Expand Panel" titles of fdp-panel are not localized

### ISSUE THREAD

**Issue by nehabeke** [SAP/fundamental-ngx#9884]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Using ngx platfrom panel (fd-panel) - https://sap.github.io/fundamental-ngx/#/platform/panel
fdp-panel has options to collapse/expand panels. 
These words which we are using as a title "Collapse Panel" and "Expand Panel" (shown in the following figure)
are not localized. These strings should be externalized for translations.

![image](https://github.com/SAP/fundamental-ngx/assets/14968987/9ce8f3ab-b5f9-4d14-b0ac-6f7975e7f0a2)

![image](https://github.com/SAP/fundamental-ngx/assets/14968987/f5968110-41c2-4395-ab0f-71ce4a328da6)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular CLI: 15.2.0
"@fundamental-ngx/core": "0.40.2-rc.8",
"@fundamental-ngx/platform": "0.40.2-rc.8",

#### Please provide relevant source code if applicable.
https://stackblitz.com/run?file=src%2Fmain.ts

**Comment by nehabeke** [comment]
Hi, Would you kindly give prompt attention to this particular issue? Please let me know If you have any questions, I will be happy to help.

**Comment by fkolar** [comment]
This is not a bug. 

Please see 

```
 @Input()
    expandLabel: string = this._panelConfig.expandLabel;

    /**
     * ARIA label for button when the Panel is expanded
     */
    @Input()
    collapseLabel: string = this._panelConfig.collapseLabel;
```


And PanelConfig service: https://sap.github.io/fundamental-ngx/#/platform/panel#config
