### ISSUE TITLE
Fd-select popover sticks to its place on scroll when used in a web component

### ISSUE THREAD

**Issue by Soumadeep1993** [SAP/fundamental-ngx#9892]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

Fd-select popover or any popover sticks to its place on scroll when used in a web component

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.38.2
#### If this is a bug, please provide steps for reproducing it.

Use fd-select inside a web component.
expand its popover.
scroll the page.
the popover sticks to its position

#### Please provide relevant source code if applicable.

<img width="495" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/60318003/c03c99c1-797d-468f-b03c-c1a1ff8a9055">

**Comment by droshev** [comment]
@Soumadeep1993 Can you check with a newer version and report a new issue if this is still reproducible? Can you also create a stackblitz example
