### ISSUE TITLE
[Checkbox] Missing Display-Only state

### ISSUE THREAD

**Issue by zaheral** [SAP/fundamental-ngx#9894]
#### Is this a bug, enhancement, or feature request?
Missing feature from Fiori Guidlines

#### Briefly describe your proposal.

In the Fiori Guideline, we can see how the Checkbox should look in the Display-Only state: https://experience.sap.com/internal/fiori-design-web/checkbox/#properties 

We checked the Checkbox Demo Page in Funtmandental and saw that it is currently not possible to have such a state: https://sap.github.io/fundamental-ngx/#/core/checkbox#states 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@fundamental-ngx/core v0.40.x

**Comment by D034394** [comment]
Seems that also Read-Only is not possible as of today.

**Comment by droshev** [comment]
The latest specs were implemented in [styles](https://fundamental-styles.netlify.app/?path=/docs/sap-fiori-components-forms-checkbox--docs#states) and we will bring them. please, follow the [issue](https://github.com/SAP/fundamental-ngx/issues/9823)

**Comment by D034394** [comment]
@droshev , from what I see my understanding is that the display mode is still missing:
Here the specification in the Visual Core (Quartz):
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2060052861#CheckBox(Fiori3)-DisplayOnlyMode
![image](https://github.com/SAP/fundamental-ngx/assets/52921101/1516d2d6-ed54-4789-906e-c27a6dff4b8f)

**Does your previous message mean our request is covered with this ticket: https://github.com/SAP/fundamental-ngx/issues/9832** and we still need to wait for its completion? Any date/timeframe when it is done?

**Comment by N1XUS** [comment]
Fixed with https://github.com/SAP/fundamental-ngx/pull/10315
