### ISSUE TITLE
[Sourcing][x] 'Snap on scroll' feature not working in dynamic page and need some control over 'snap on scroll' feature

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#9908]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
1. 'Snap on scroll' feature is not working in both core and platform dynamic page in fundamental website.
2. Can we have an attribute to enable/disable the 'snap on scroll' feature.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
@fundamental-ngx/core 0.41.0-rc.3
@fundamental-ngx/i18n 0.41.0-rc.3
@fundamental-ngx/platform  0.41.0-rc.3
@angular/cli 15.2.8

#### If this is a bug, please provide steps for reproducing it.

It can be viewed in
Fundamental core link - 
https://sap.github.io/fundamental-ngx/#/core/dynamic-page
Fundamental platform link-
https://sap.github.io/fundamental-ngx/#/platform/dynamic-page

**Comment by I543348** [comment]
This is for implementing responsiveness in Sourcing

**Comment by I543348** [comment]
Hi @skaquib123 , Can you please help with a tentative ETA for this issue?

**Comment by skaquib123** [comment]
@Sayandeep-123 Can you please confirm whether the issue 1 is working or not?

**Comment by fkolar** [comment]
Can you share more details so we can capture it, 

1. Platform Dynamic Page is using core Dynamic Page, so I believe the change needs to be done in CORE
2. Can you describe in more details what do you mean by this snap on scroll behavior - in relation to dynamic page? 

Maybe even fundamentals styles?

**Comment by Sayandeep-123** [comment]
Hi @fkolar, the snap on scroll behaviour is, when we scroll down in the dynamic page, the **subHeader**  get collapsed and on scrolling to the top, it get expanded automatically. 

And we want some control to enable/disable this behaviour.

**Comment by Sayandeep-123** [comment]
> @Sayandeep-123 Can you please confirm whether the issue 1 is working or not?

Hi @skaquib123 , it seems its not working.
Please refer the link to confirm it - https://stackblitz.com/edit/angular-se5klo?file=src%2Fapp%2Fdynamic-page-responsive-example.component.ts

And please let me know if I'm doing something wrong.

**Comment by fkolar** [comment]
We clarified functionality also based on the FIORI specs. snap on scroll and snap on click should be part of the components. Unfortunately snap on scroll does not work anymore. 



Assuming this used to work when there is a disabled test:
@mikerodonnell89 
`xdescribe('DynamicPageComponent default values', () => {`
