### ISSUE TITLE
[Sourcing][Needs Input] fdp-input-group enhancement on mousewheel scroll

### ISSUE THREAD

**Issue by PratikPattanayak12** [SAP/fundamental-ngx#9925]
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
We need a property to control the mousewheel scroll on the input field to be disabled or enabled 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
15

#### If this is a bug, please provide steps for reproducing it.
Enhancement.

**Comment by skaquib123** [comment]
Hi @PratikPattanayak12 , Can you please elaborate your requirement and also which particular component you are referring to?

**Comment by skaquib123** [comment]
@PratikPattanayak12 as discussed,  I am  closing this issue since there is a workaround present.
