### ISSUE TITLE
[Sourcing][High][Jun] Issues after Preserving table state upgrade

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#9928]
#### Is this a bug, enhancement, or feature request?

bug 

#### Briefly describe your proposal.

Issue 1: Collapsed child row icon is collapsed but children of that child are still displayed:

https://github.com/SAP/fundamental-ngx/assets/22842279/9542f185-f5a3-4040-9203-4b1326f3178a

Issue 2 (more like enhancement request): It looks like this is not working with expandAll and collapseAll since the row toggle emitted event is only triggered for individual row. Could you provide us the way to know the expanded state when those two are triggered?

Issue 3: Adding delay for pageScrolling will not work on getting preserved scroll state of the table:

https://github.com/SAP/fundamental-ngx/assets/22842279/8e7984e1-3f96-4e86-8393-caf89a224cf2

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

lastest

#### If this is a bug, please provide steps for reproducing it.

Have table having row with child row and another nested children of that child -> expand then collapse that child -> navigate or toggle button to make table disappear/appear.

#### Please provide relevant source code if applicable.

On fundamental ngx playground.

For issue 3: https://stackblitz.com/edit/angular-9qxxca-5b8ogf?file=package.json,src%2Fapp%2Fplatform-table-preserved-state-example.component.html,src%2Fapp%2Fplatform-table-preserved-state-example.component.ts

**Comment by CSENoni** [comment]
Found one more issue when adding delay to trigger busy indicator of preserved table.

**Comment by N1XUS** [comment]
Hello @CSENoni. Thank you for your ticket.
For item 2, since `collapseAll` and `expandAll` are API methods of the Table component, I don't see a reason why it should have event emitters when the method calls being made, since the logic of calling that methods are fully under apps developers controls, thus, they can internally store flag whether `collapseAll`, or `expandAll` methods were called

**Comment by CSENoni** [comment]
Hi @N1XUS, for issue 2, that means we have to create customized buttons for expandAll and collapseAll to be able to capture the flag. However, there is one issue with that https://github.com/SAP/fundamental-ngx/issues/9589 which indicated this workaround will not work for our design. Hi @fkolar, since you resolved this https://github.com/SAP/fundamental-ngx/issues/9589 and confirmed the workaround was not working back then, can you kindly verify that workaround is still not working now?

However, assuming the customized expand/collapse buttons will work, I am not sure if it is a good idea to create another similar existing buttons just to add a flag, but it is fine for me if the workaround is working.

**Comment by fkolar** [comment]
I am not sure if we are on the same page and on the app level there is no reason to have customised button as you have full access to public method of table. There is also expandAll collapseAll.

Also we are going to discuss this more on the next meeting but there is a agreement that all the requests needs to go thru me first for the review and completeness of information. 

You want to also checkout this repo, where we discuss how to preserve a state: https://github.com/fkolar/table-destroy/tree/main/src. 

You cant use ExampleItem (app object) but you need to use TableRow to be able to preserve expanded states for each node + I also show workaround for the scroll position.

The 9589, there is really nothing to tests, On the app level you do have access to those method.

**Comment by CSENoni** [comment]
@fkolar thanks for the link. I will take a look. The discussion for this issue is to capture the state of expanded/collapsed All when user interacts with those buttons after this https://github.com/SAP/fundamental-ngx/issues/9752 is implemented since I did not see the way to capture it except for creating a customized ones to add the flag.

**Comment by fkolar** [comment]
I just don't see why would you want to keep if all is expanded or collapsed. You care about individual states of each node. But in case you still want to keep this information you have access to table methods such as:


```ts
// once Table is bound in your components you can do workaround similar to this. 

const tableExpandAll = this.table.expandAll;
this.table.expandAll = () => {
  this.expandAll = true;
  tableExpandAll();
}
```

**Comment by CSENoni** [comment]
**Issue 1:** It can still be reproducible but in different scenario now. When we have row that has several levels of nested children and everything is expanded, try to collapse the most-top parent and the children are still displayed but not correctly:

https://github.com/SAP/fundamental-ngx/assets/22842279/cd31827c-bd9b-4cef-af58-dcc9fbcde2d1

**Issue 2:** I think I will discuss more in a meeting, but here is a one of simple use cases:

Right now, we have implementation to remember the individual state of expanded/collapsed of single row since we can store it through event emitter. However, for example, in table with pageScrolling = true and when scrolling exceed pageSize and we call api to fetch another page, user decide to expand all the rows and when we fetch another page, it is expected all rows in next page should be displayed all expanded. It should have similar behavior when user use collapseAll. So, I need a flag to set all new rows all expanded or collapsed depending on user's choice. 

**Issue 3:** It cannot be reproducible with new implementation. Thanks
