### ISSUE TITLE
[Sourcing][High][Jun] Need some control over subtitle in dynamic page

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#9929]
#### Is this a bug, enhancement, or feature request?

Enhancement

#### Briefly describe your proposal.

We want a control to render custom template in subtitle (shown below in the screenshot) of fundamental core dynamic page.

<img width="1792" alt="Screenshot 2023-05-26 at 4 24 23 PM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/8bf3dc4f-0c9b-4731-b92c-fb1954ddf56f">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

@fundamental-ngx/core 0.41.0-rc.3
@fundamental-ngx/i18n 0.41.0-rc.3
@fundamental-ngx/platform 0.41.0-rc.3
@angular/cli 15.2.8

**Comment by I543348** [comment]
This is for implementing responsiveness in Sourcing

**Comment by droshev** [comment]
This can be done for core dynamic page

**Comment by fkolar** [comment]
@Sayandeep-123, can you update the ticket with more details, why this cannot be done using existing code? Do you have some specific design that does not fit?

**Comment by Sayandeep-123** [comment]
Hi @fkolar , I tried using core dynamic page as well. It looks like we can only provide a string as an input in the subtitle as we can see in the below two screenshots.

<img width="1792" alt="Screenshot 2023-06-20 at 5 01 29 PM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/b75bfae9-449a-4285-9baf-9f62d6d9c9b7">

<img width="1792" alt="Screenshot 2023-06-20 at 4 58 19 PM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/287071c4-7483-4e3a-9e42-142ff310a997">

<br></br>
But we want to render our custom template inside the subtitle because in the application, subtitle contains different segments with different styles as shown in the screenshot.
<img width="1772" alt="Screenshot 2023-06-20 at 5 38 19 PM" src="https://github.com/SAP/fundamental-ngx/assets/71999626/02fc7cc0-b93f-4f29-957a-d10ace225ecd">
<br></br>

Please let me know for any further queries.

**Comment by fkolar** [comment]
@Sayandeep-123 

So we need a template to be added so we cna add custom content? We just need to make sure that this content does not break existing layout. Can you also send me some UX example what you want to add into the subheader?

**Comment by Sayandeep-123** [comment]
Yeah, we need a template to add custom content. And the UX example, which have custom content in subtitle is already attached in the above reply.

**Comment by I543348** [comment]
Currently for all of our pages , we are displaying the below information in the subtitle as per UX guidelines
Guided sourcing event status , type , document id, and if multi round bidding we also display round 1 , 2 etc.

These are rendered in subtitle just below the Guided sourcing event main title.
cc: @Sayandeep-123 , @fkolar

**Comment by fkolar** [comment]
Just to confirm, currently, when providing a subtitle, application can only pass a string without some additional formatting 

```
  <fdp-dynamic-page-title [title]="pageTitle" subtitle="Oversized multimaterial sneakers with quilted effect">

```

The new proposal is that we should be able to set custom template, so we can achive something similar to this picture
<img width="1327" alt="Screenshot 2023-06-21 at 11 14 54" src="https://github.com/SAP/fundamental-ngx/assets/17149942/d4256a43-12ab-4167-8b2c-ab12564ce663">

- In this case several spans dividing different information + icon or or other infographics. I believe this is reasonable ask. We just need to confirm if:

1) Custom template as `@Input()`
```
  <fdp-dynamic-page-title [title]="pageTitle" subtitleTemplate="customNgTemplate">

```

2)  Custom template as `@ViewChild()` 
```
  <fdp-dynamic-page-title [title]="pageTitle" >
     <ng-Template #subTittleTemplate>
     </ng...
```

Across the fundamentals we use these two approaches. @mikerodonnell89, what is the latest recommendation. As an `@Input` it made sense before Angular introduced `static:true`, but I have no preference to this. 


The Main change would be in the` F-NGX/Core a`nd platform would be just updated to support this within the` fdp-* `components
