### ISSUE TITLE
Different CSS between Chrome and Firefox

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#994]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
The alignment of the buttons is different between chrome and firefox  
**chrome**:  
![image](https://user-images.githubusercontent.com/34537974/60449829-c9d03080-9c28-11e9-85d7-c1955091e254.png)  
  
**firefox**:  
![image](https://user-images.githubusercontent.com/34537974/60449903-ef5d3a00-9c28-11e9-9167-a537c6722ccd.png)

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
Angular Version: 7.3.8
Fundamental NGX: 0.6.0

#### Please provide relevant source code if applicable.

```<div fd-action-bar>
    <div fd-action-bar-header>
      <h3 fd-action-bar-title></h3>
      <div fd-action-bar-description></div>
    </div>
    <div fd-action-bar-actions>
      <button type="button" class="fd-button sap-icon--nav-back" [routerLink]="''">
        {{ 'page.button.back' | translate }}
      </button>
      <button type="button" class="fd-button sap-icon--edit" [disabled]="" [routerLink]="">
        {{ 'page.button.edit' | translate }}
      </button>
    </div>
  </div>
  <fd-panel-grid [col]="1">
    <fd-panel class="fd-panel fd-has-margin-bottom-large" [columnSpan]="1">
      <fd-panel-header>
        <fd-panel-head>
          <h2 fd-panel-title></h2>
        </fd-panel-head>
      </fd-panel-header>
  </fd-panel-grid>`

**Comment by JohnHavok** [comment]
The cause ? : _.fd-action-bar__header {overflow: hidden;}_

**Comment by JKMarkowski** [comment]
Hi @JohnHavok, I think that it's more [fiori-fundamentals](https://github.com/SAP/fundamental) issue. You should report it there.

**Comment by JohnHavok** [comment]
Huum I suspected it .. I will go to see fiori-fundamental
Sorry !

**Comment by MattL75** [comment]
Closing this here since it's an issue on the css lib
