### ISSUE TITLE
Bug: (Core) SelectModule Focusing bug

### ISSUE THREAD

**Issue by penleychan** [SAP/fundamental-ngx#9943]
#### Is this a bug, enhancement, or feature request?

Bug

`SelectModule` from @fundamental-ngx/core/select auto focusing last element found on the page/form.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular 15.
Fundamental NGX Core 0.41

#### If this is a bug, please provide steps for reproducing it.

Navigate to this documentation page: https://sap.github.io/fundamental-ngx/#/core/select
Last element of `SelectModule` is focused. 

Expected: No focus on controls this should be controlled by user via keyboard navigation or from `fd-intial-focus`

**Comment by droshev** [comment]
@penleychan can you provide a little bit more context, screenshot, and the steps for the issue

**Comment by penleychan** [comment]
@droshev no longer relevant there was another issue reported on later date, similar to this # 10086 which now has been resolved.
