### ISSUE TITLE
 On hover I'm getting dot dot in input text

### ISSUE THREAD

**Issue by jyoti1507** [SAP/fundamental-ngx#9945]
#### Is this a bug, enhancement, or feature request?
https://sap.github.io/fundamental-ngx/#/core/input On hover I'm getting dot dot
#### Briefly describe your proposal.
on hover of any thing like input , checkbox multiple dots are visible. using https://sap.github.io/fundamental-ngx/#/core/
<img width="352" alt="Screenshot 2023-05-29 at 8 49 36 PM" src="https://github.com/SAP/fundamental-ngx/assets/38528135/2304df9a-fc37-4845-81ab-6a1a9c087623">

<img width="422" alt="Screenshot 2023-05-29 at 8 37 37 PM" src="https://github.com/SAP/fundamental-ngx/assets/38528135/3f272807-e954-432d-8133-476fd9e445d7">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
15

**Comment by droshev** [comment]
@jyoti1507 Can you provide all the steps how to reproduce the issue?

**Comment by droshev** [comment]
feel free to open a ticket if this issue is still valid and provide either stackblitz and/or steps how to reproduce
