### ISSUE TITLE
[Multi-Input] Dropdown does not update its position upon typing

### ISSUE THREAD

**Issue by konradkukier2** [SAP/fundamental-ngx#995]
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Dropdown does not update its position  on user typing. Its clearly visible when dropdowns position is top.

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)

latest

#### If this is a bug, please provide steps for reproducing it.

![dropdown](https://user-images.githubusercontent.com/12159534/60513123-b2e81780-9cd6-11e9-8856-27d093ba0905.gif)

**Comment by MattL75** [comment]
Fixed by #996
