### ISSUE TITLE
There is no icon for Storage Bucket

### ISSUE THREAD

**Issue by amirbalaie** [SAP/fundamental-ngx#9952]
#### Is this a bug, enhancement, or feature request?
feature request

#### Briefly describe your proposal.
Please add a bucket icon to https://sap.github.io/fundamental-ngx/#/core/icon
I am talking about Bucket  as a storage container for storing objects.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
V0.41.0

**Comment by droshev** [comment]
Can you check whether this is already fixed?

**Comment by droshev** [comment]
@amirbalaie thanks for the request. We will forward the request to the design team.

**Comment by amirbalaie** [comment]
I see a new icon "paint-bucket". That can be used for what I was looking for.  Thanks.
