### ISSUE TITLE
[Reopen][Sourcing] [Accessibility] Platform Tree table empty cell issue

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9964]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
We performed few tests after previous issues fixes for sanity and found the below issues.
Please help.
**Tree table related issues:** 
**Issue 1:**  The empty cells are conveyed with wrong information “Collapsed”, visually there is nothing to collapse or expand within these cells.
<img width="451" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/00c4e47c-c10d-4113-ae1d-47354fafa7cc">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
All these were tested as on 31st May 2023 on https://sap.github.io/fundamental-ngx/#/platform/table/ platform table component samples

#### If this is a bug, please provide steps for reproducing it.
The screenshots are attached for references from JAWS screenreader version 2023.

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table/

#### Is there anything else we should know?
These are the sanity tests issues found from ATL team

**Comment by mikerodonnell89** [comment]
Many of these are no longer relevant due to recent fixes that are only present currently on https://fundamental-ngx.netlify.com/#/core/home and will soon be deployed to our main documentation site https://sap.github.io/fundamental-ngx

To avoid duplicate issues, please have the accessibility team refer to the latest netlify build

**Comment by I543348** [comment]
Need to check in [v0.42.0-rc.15](https://github.com/SAP/fundamental-ngx/releases/tag/v0.42.0-rc.15)

**Comment by I543348** [comment]
We tested and validated in deploy preview URL , but its not working still.
Please find the attached speech history from JAWS 
<img width="944" alt="Screenshot 2023-07-27 at 2 22 23 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/966160b8-6f63-45b8-a9d4-e7b4a086babc">

Needs to be reopened , please help
cc: @mikerodonnell89 , @fkolar

**Comment by fkolar** [comment]
Its a valid issue: Just to compare what other SAPUI5 tables says for readonly cells
<img width="833" alt="Screenshot 2023-07-27 at 11 20 06" src="https://github.com/SAP/fundamental-ngx/assets/17149942/a6ced860-5136-4d76-942d-2f7419495c2b">
<img width="870" alt="Screenshot 2023-07-27 at 11 19 54" src="https://github.com/SAP/fundamental-ngx/assets/17149942/97d03ffb-f4f5-494f-b318-083ea3b313ef">

**Comment by mikerodonnell89** [comment]
That would be a different issue than what was originally posted

**Comment by I543348** [comment]
Hi @mikerodonnell89 , the expectation is clear to meet UI5 table or as per w3 standards.
The "Empty" cell needs to be communicated to disabled users via screen readers.
Please let me know if you need a new issue to be reported.

Thanks.

**Comment by I543348** [comment]
Sure @droshev ,
the new issue is here: https://github.com/SAP/fundamental-ngx/issues/10320

**Comment by sagar7259** [comment]
Hello,

The reported issue where additional information "Collapsed" is being read is fixed now and there is a new seperate ticket for the "empty" information reading issue. Hence closing this ticket.

Thanks,
Sagar(ATL team)
