### ISSUE TITLE
Accessibility issue for table

### ISSUE THREAD

**Issue by WangmoZhu** [SAP/fundamental-ngx#9966]
#### Is this a bug, enhancement, or feature request?
accessibility issue
#### Briefly describe your proposal.
The aria-colindex attribute is not allowed on this th.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular version: 14.2.10
Fundamental library: 0.36.3
#### Is there anything else we should know?
<img width="1322" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/53166994/ea3ac4a4-0a32-4745-b0dc-da725d71e15a">

**Comment by mikerodonnell89** [comment]
Can you elaborate? This attribute is valid for use on th elements. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-colindex

**Comment by droshev** [comment]
@WangmoZhu Do you think you can answer @mikerodonnell89 's question and provide more information? Can you test with the latest version too?

**Comment by droshev** [comment]
@WangmoZhu Any update?

**Comment by droshev** [comment]
no activities => closing the issue
