### ISSUE TITLE
Accessibility issue for fd-list with popover after upgrade from Ngx 0.354,  angular 13.2.7 to Ngx 0.36. angular 14.0.2

### ISSUE THREAD

**Issue by itsnode** [SAP/fundamental-ngx#9970]
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Tab key navigate between two fd-list under a popover stopped working after angular upgrade 
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
14
#### If this is a bug, please provide steps for reproducing it.
Tab key was working under Ngx 0.35.4 and Angular 13.2.7, see code https://stackblitz.com/edit/angular-7e2qbs-sbexcw?file=src%2Fapp%2Fshellbar-basic-example.component.html
Stopped working under Ngx 0.36 and Angular 14.0.2, see code https://stackblitz.com/edit/angular-zh1zus-r62vjg?file=src%2Fapp%2Fshellbar-basic-example.component.html

https://github.com/SAP/fundamental-ngx/assets/48496287/27c33b27-4a11-4643-bdaa-670a30ceb5b9

**Comment by mikerodonnell89** [comment]
@itsnode are you able to update your fundamental-ngx version to 0.39.0 and Angular to 15? This appears to be resolved by https://github.com/SAP/fundamental-ngx/pull/9242

**Comment by itsnode** [comment]
> @itsnode are you able to update your fundamental-ngx version to 0.39.0 and Angular to 15? This appears to be resolved by #9242

ok. Thanks for response. Yes, we will go ahead upgrade to 0.40 and Angular 15. Confirmed fix once upgrade.
