### ISSUE TITLE
DatePicker/DateTimePicker validity not reflected to form

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#998]
#### Is this a bug, enhancement, or feature request?

Bug.  When an invalid date/datetime is set in the input (or an empty string if allowNull is set to false), the field appears in valid by styling the input, but the surrounding form is still considered 'valid'.

#### Briefly describe your proposal.

I think the DatePicker and DateTimePicker need to implement Validator class for custom form control validation.  Otherwise, the code examples need to demonstrate how a dev can handle validity themselves when using either component in one of their applications.

#### If this is a bug, please provide steps for reproducing it.

Check out the example branch [here](https://github.com/SAP/fundamental-ngx/tree/bug/%23998-datepicker-datetimepicker-null-validty-examples)

Or just add the following to the DatePicker or DateTimePicker form example HTML:

```
        Form Valid: {{customForm.valid}}<br/>
        FormControl Valid: {{customForm.controls.date.valid}}<br/>
```

Then set `[allowNull]=false` and submit the input by pressing return or blurring.  The input appears invalid but the form still says both the form and the control are valid.

Also type nonsense into the input and submit.  Same result

**Comment by JKMarkowski** [comment]
The bug with allownull is fixed in calendar refactor.

**Comment by JKMarkowski** [comment]
About Validator example - I will add some examples, but after merging new calendar.
