### ISSUE TITLE
[Sourcing][Regression] fdp table row selection issues

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9984]
#### Is this a bug, enhancement, or feature request?
Regression issue

#### Briefly describe your proposal.
Until version 0.40.2-rc.19, the issue doesnt exists , after upgrading to 0.41.1-rc.0 the on row click event is not firing.
Also upon selecting all rows checkboxes , the header checkbox is not getting checked.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
ngx core / platform : 0.41.1-rc.0

#### If this is a bug, please provide steps for reproducing it.

1) check any multi select row in fdp-table in version 0.41.1-rc.0 and notice the event is not fired
2) check all rows in multi select rows , observe that header checkbox is not checked automatically

This is causing regressions in all Guided sourcing NGX Platform tables
Please help on priority

**Comment by CSENoni** [comment]
May be because of this: https://github.com/SAP/fundamental-ngx/pull/9762/files

**Comment by mikerodonnell89** [comment]
I think we need more context, example code or something, seems to be working fine here: https://fundamental-ngx.netlify.app/#/platform/table/row-selection

https://github.com/SAP/fundamental-ngx/assets/2471874/faa8c772-1887-461c-9a96-5ed0f0b6bd84

**Comment by CSENoni** [comment]
> I think we need more context, example code or something, seems to be working fine here: https://fundamental-ngx.netlify.app/#/platform/table/row-selection
> 
>  Screen.Recording.2023-06-05.at.12.11.23.PM.mov

I just found out we had to move ngxplatform and ngxcore modules to root level to make it work again. I will try to reproduce it in blitz.

**Comment by CSENoni** [comment]
https://github.com/SAP/fundamental-ngx/assets/22842279/3f0b48e1-f6db-4008-b8d9-6f7b091fcf4e

https://stackblitz.com/edit/angular-sufq3o?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fchild.module.ts,src%2Fapp%2Fapp.component.ts,src%2Findex.html,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts

**Comment by mikerodonnell89** [comment]
fixed in RC version 0.42.0-rc.13
