### ISSUE TITLE
[Sourcing] fdp-table infinite scroll with multi selection rows

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9988]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Upon checking the header checkbox , all of the total rows checkbox should be checked

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular : 15
ngx core / platform: 0.42.0-rc.13

#### If this is a bug, please provide steps for reproducing it.
1) check the header checkbox 
2) scroll to 2nd page items 
3) notice that the lazy loaded rows checkboxes are not getting checked automatically

**Comment by CSENoni** [comment]
Please note that for some tables, we call api to get the next page (new items), so it is expected these are also checked as well if checking the header checkbox (given or something provided to manually do it).

**Comment by N1XUS** [comment]
@CSENoni Hello. Thank you for submitting this ticket.
This PR #9991 brings new property of the `TableRowSelectionChangeEvent` interface called `all`, which indicates whether all items should be checked/unchecked. Additionally to that, platform table allows setting `selectedKey` property to identify selection state of each item. As an example, refer to https://deploy-preview-9991--fundamental-ngx.netlify.app/#/platform/table/scrolling first example here on how to achieve desired behaviour.

**Comment by CSENoni** [comment]
Have a quick review from the link. LGTM. Thanks!
