### ISSUE TITLE
[Sourcing] on Focus event needed  for input box generated from fd-multi-input component

### ISSUE THREAD

**Issue by KaptaanBarbosa** [SAP/fundamental-ngx#9990]
#### Briefly describe your proposal.
whenever user reaches inputbox generated from fd-multi-input component  needed one event that should fired and we can use it to generate offline autocomplete UI

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15 
@fundamental-ngx/core : 0.40.2-rc.12
@fundamental-ngx/platform : 0.40.2-rc.12

**Comment by mikerodonnell89** [comment]
You can use the `focusin` event:

```
<fd-multi-input
    inputId="multiInput"
    [dropdownValues]="['Apple', 'Banana', 'Pineapple', 'Tomato', 'Kiwi', 'Strawberry', 'Blueberry', 'Orange']"
    placeholder="Search here..."
    (searchTermChange)="searchTermChange($event)"
    [(ngModel)]="selected"
    (focusin)="focused($event)"
></fd-multi-input>
```

```
    focused(event: any): void {
        console.log('focused');
        console.log(event);
    }
```

**Comment by I543348** [comment]
@KaptaanBarbosa pls evaluate the fix and confirm
