### ISSUE TITLE
[Sourcing][Accessibility][High][Jun] ATL reported issue for multi input field issue 2

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9995]
#### Briefly describe your proposal.
Accessibility issue reported by ATL team

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core./ platform: 0.39.0

#### If this is a bug, please provide steps for reproducing it.
2) On accessing the multi value input field, its corresponding UI type read to the users as “Edit” which is incorrect. Here “Multi value input edit” should be read.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/88182358/231159578-a67e90d1-9d36-4353-8ebe-f0cb82a86f5c.png">

#### Is there anything else we should know?
These issues are found and reported by ATL team and are required for custom chooser hierarchy component built using "Multi value input" and dialog with tree table

**Comment by mikerodonnell89** [comment]
I've opened a PR here to update the default values: https://github.com/SAP/fundamental-ngx/pull/10071

For future reference, many components, including the multi-input, allow for aria-label overrides via an `ariaLabel` input
<img width="657" alt="Screenshot 2023-06-22 at 1 39 21 PM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/95819536-abdb-42ee-833f-1eab73de5544">
