### ISSUE TITLE
[Sourcing][Accessibility][High][Jun] Chooser hierarchy issue 3

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9996]
#### Briefly describe your proposal.
ATL testing issue 

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core./ platform: 0.39.0

#### If this is a bug, please provide steps for reproducing it.
3) Multi value input field is not provided with visible label
<img width="451" alt="image" src="https://user-images.githubusercontent.com/88182358/231159712-e4f55772-f732-4afd-a0e7-be9d0a32f7e2.png">

**Comment by mikerodonnell89** [comment]
I'm confused what you are looking for here, both the core and platform examples demonstrate how to add placeholders, and you can use these in the form group components.
