### ISSUE TITLE
[Reopen][Sourcing][Accessibility][High][Jul] Chooser hierarchy ATL issue 4 - checkbox states

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9997]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
ATL testing issue 4

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core./ platform: 0.39.0

#### If this is a bug, please provide steps for reproducing it.
4) On accessing the ‘Select all check box’ on the header column, its label provided ‘Check box’ is incorrect as users will not know the difference between cell check box and header check box.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/88182358/231159800-0c399027-9d37-4cab-a10c-5234436331f6.png">

**Comment by fkolar** [comment]
When I checked other implementation. - such as SAPUI5, then they have:
- `title`  attribute on the checkbox wrapping element  - SELECT ALL, DESELECT ALL - but this is just a tooltip
- arialabel which work the same way also in here - It just says x items Select.  

No Additional information about that you are on the header

**Comment by I543348** [comment]
We evaluated the fix , for any multi-select table , the screenreader is still not reading anything related to checkbox and its state for both header and row cells.
Please reopen and help.
<img width="1792" alt="Screenshot 2023-07-24 at 12 04 32 PM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/4e8ea285-5456-47e9-b752-71d7ad43ff63">

**Comment by mikerodonnell89** [comment]
published a hotfix to 0.43.3

**Comment by I543348** [comment]
need to be sent for ATL testing

**Comment by sagar7259** [comment]
Hello,

The issue is still reproducible for chooser hierarchy dialog, hence this needs to fixed. On accessing the ‘Select all check box’ on the header column, its label provided ‘Check box’ is incorrect as users will not know the difference between cell check box and header check box.

Regards,
Sagar (ATL team)

**Comment by droshev** [comment]
@sagar7259 which version did you test that on?
