### ISSUE TITLE
[Sourcing][Accessibility][High][Jul][Reopen] Platform tree table column reading twice with row and column numbers

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9998]
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
ATL testing for platform tree table

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
All these were tested as on 31st May 2023 on https://sap.github.io/fundamental-ngx/#/platform/table/ platform table component samples

#### If this is a bug, please provide steps for reproducing it.
There are 2 issues here,
1)	The information 2 of 5, 2 of 5, before the row and column count is additional information which is not required. This is a table and column and row information is more than enough and too many count information may confuse the screen reader users.
2)	Every time the first column which is accessed is being read with column information twice. And this contains different count of column each time which is incorrect.
<img width="451" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/2c330810-14f3-4a35-aab7-27f4ac5f961c">

#### Please provide relevant source code if applicable.
https://sap.github.io/fundamental-ngx/#/platform/table/

**Comment by I543348** [comment]
Hi @mikerodonnell89 , Even in netlify link , this issue is replicable the column headers are being read twice.
please reopen the issue and help.
<img width="1792" alt="Screenshot 2023-07-11 at 10 47 45 AM" src="https://github.com/SAP/fundamental-ngx/assets/88182358/7c48d2c9-bd54-4d9a-adff-272452a896a0">

Thanks much.
cc: @mikerodonnell89

**Comment by sagar7259** [comment]
The information for all the table cells which is read are still feels like the information is being read multiple times.

In the below screenshot on accessing the 'Screens' cell the reading is made as:
"Screens collapsed
2 of 5
Row 3
Column 2 of 5, row: 3 of 6"

Here 2 of 5 and row 3 is same information of the column/row information which is read again at the end "Column 2 of 5 row 3 of 6"

The expected read is "Screens collapsed column 2 of 5, row: 3 of 6"

![image](https://github.com/SAP/fundamental-ngx/assets/143692208/83abc8f7-4381-4d4b-aac7-7bbdf4a82e64)

Regards,
Sagar(ATL team)

**Comment by droshev** [comment]
> fix(platform): remove aria-labelledby from platform table header cells #10157

@sagar7259 I see from the screenshot you are not using the proper version (e.g. `0.43.10`)
