### ISSUE TITLE
[Sourcing][Accessibility][High][Jul] platform tree table irrelevant text read before focus on child rows

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9999]
#### Is this a bug, enhancement, or feature request?
Bug

#### If this is a bug, please provide steps for reproducing it.
**Issue 3:** 
On expanding any cell within ‘Name’ column, the data within the child levels are read completely at once. Here they are not even focused yet to be read.
<img width="452" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/88182358/63bc949c-f2f0-450d-aa90-2665443b3a3f">

#### Please provide relevant source code if applicable.
All these were tested as on 31st May 2023 on https://sap.github.io/fundamental-ngx/#/platform/table/ platform table component samples

**Comment by mikerodonnell89** [comment]
Please test latest improvements on https://fundamental-ngx.netlify.app/ not https://sap.github.io/fundamental-ngx

This is focusing "Name" header cell, then arrow down to "Laptops" which is already expanded 

![Screenshot 2023-06-22 at 9 38 52 AM](https://github.com/SAP/fundamental-ngx/assets/2471874/cf8a28a2-2c42-4625-a2f2-6905ff29f3b9)

**Comment by sagar7259** [comment]
Hello,

Please dont focus on already expanded cells. First collapse all the children nodes and then navigate to the laptops cell and press enter to expand with JAWS turned on. You can replicate this issue.

Its still reproducible with the latest build.
@rvamudha please reopen this ticket

Regards,
Sagar(ATL Team)

**Comment by droshev** [comment]
@sagar7259 which version did you test on?
